/* ===========================================================
   VOVÔMINIC EMERGÊNCIA — meds/alergia.js
   6 medicações
   Grupos: alergia
   =========================================================== */

MEDICACOES.push(

/* ============== ALERGIA (6) ============== */

{id:"med-cetirizina", contexto:["pa","ubs"], classe:"Anti-histamínico H1 — 2ª geração", grupo:"alergia",
nome:"Cetirizina",
sin:["Zyrtec","Reactine","Cetrizyn","Levocetirizina (Xyzal)"],
formas:["Comprimido 10 mg (cetirizina); 5 mg (levocetirizina)","Solução oral 1 mg/mL","PFPB"],
resumo:"⚠ ANTI-HISTAMÍNICO H1 DE 2ª GERAÇÃO — INÍCIO MAIS RÁPIDO que loratadina (30-60 min). Pode ser MAIS SEDATIVO que loratadina (alguns pacientes — discreta sonolência). Indicações similares: rinite alérgica, urticária. ⚠ LEVOCETIRIZINA é enantiômero S puro (mais potente, dose metade — 5 mg).",
dose_rapida:"10 mg/d (cetirizina); 5 mg/d (levocetirizina)",
doses:[
{ind:"⚠ RINITE ALÉRGICA / URTICÁRIA", dose:"Cetirizina 10 mg VO 1×/d; Levocetirizina 5 mg VO 1×/d", obs:"⚠ Urticária crônica: aumentar até 4× off-label (40/20 mg/d) — ARIA."},
{ind:"Prurido", dose:"10 mg/d (cetirizina) ou 5 mg/d (levocetirizina)", obs:""},
{ind:"Pediatria", dose:"Cetirizina 6-23m: 2,5 mg/d. 2-5a: 5 mg/d. ≥6a: 10 mg/d.", obs:""},
],
ajustes:{
irc:"⚠ TFG 30-49: 5 mg/d. TFG 10-29: 5 mg cada 48h. HD: contraindicada.",
iht:"⚠ Reduzir",
idoso:"⚠ 5 mg/d em ≥77a, especialmente com IRC",
gestante:"⚠ B — segura",
aleita:"Compatível",
ped:"≥6 meses (solução)",
},
mecanismo:"ANTAGONISTA H1 — metabólito ativo da HIDROXIZINA, sem efeito sedativo significativo (atravessa BHE pouco). Levocetirizina é o enantiômero S (R inativo).",
farmacocin:{
absorc:"VO bem absorvida — refeição retarda mas não reduz",
distrib:"Periférica",
metab:"Mínimo (apenas 7% metabolizado)",
elimin:"Renal predominante",
meiavida:"~8h",
ligacao:"~93%",
},
ef_colats:{
comuns:["⚠ Sonolência (em ~10-15% — MAIS que loratadina, MENOS que 1ª geração)","Cefaleia","Boca seca","Fadiga"],
sérios:["Reações alérgicas paradoxais (raras)","Síndrome do prurido grave em SUSPENSÃO ABRUPTA de uso prolongado (descrita) — reduzir gradativo se uso >meses"],
},
interacoes:["⚠ Álcool: sedação somativa","Outros depressores do SNC"],
contraindicacoes:["Hipersensibilidade","TFG <10 (cetirizina HD: ⚠ evitar)"],
monit:["Resposta clínica","Função renal em idoso/IRC"],
gravidez:"B",
sus:"PFPB",
referencias:["ARIA 2024; EAACI."],
},
{id:"med-dexclorfeniramina", contexto:["pa","ubs"], classe:"Anti-histamínico H1 — 1ª geração (sedativo)", grupo:"alergia",
nome:"Dexclorfeniramina",
sin:["Polaramine","Clorfeniramina","Dexchlor"],
formas:["Comprimido 2 mg","Xarope 0,4 mg/mL","Ampola 5 mg/mL IM/IV","REMUME — UBS dispensação direta + PFPB"],
resumo:"⚠ ANTI-HISTAMÍNICO H1 DE 1ª GERAÇÃO — SEDATIVO E ANTICOLINÉRGICO. Disponível IM/IV (emergência alérgica). Indicações: ⚠ REAÇÃO ALÉRGICA AGUDA (urticária, prurido) em emergência. ⚠ EVITAR USO CRÔNICO — sedação, anticolinérgico (idoso: Beers Criteria — quedas, delirium, retenção urinária, glaucoma, demência).",
dose_rapida:"2 mg VO 4-6/6h (adulto); 5 mg IM/IV em emergência",
doses:[
{ind:"⚠ REAÇÃO ALÉRGICA AGUDA (urticária, prurido)", dose:"2-4 mg VO 4-6/6h ou 5 mg IM/IV em emergência", obs:"⚠ NUNCA é o tratamento principal de ANAFILAXIA — adrenalina IM é primeira linha. Anti-H1 é ADJUNTO."},
{ind:"⚠ Prurido alérgico", dose:"2 mg VO 4-6/6h", obs:""},
{ind:"⚠ Anti-emético em vertigem / cinetose", dose:"2 mg VO 4-6/6h ad lib", obs:"Uso off-label."},
{ind:"Pediatria", dose:"≥2a: 0,15 mg/kg/d ÷ 6/6h (máx 6 mg/d em <6a; 12 mg/d em ≥6a)", obs:""},
],
ajustes:{
irc:"Cautela em IRC grave",
iht:"Reduzir em IH",
idoso:"⚠ ⚠ EVITAR — Beers Criteria — anticolinérgico, sedação, quedas, delirium, retenção, ↑ risco demência",
gestante:"⚠ B — historicamente usada. Em rinite alérgica gestacional: PREFERIR loratadina (2ª geração).",
aleita:"⚠ Pode reduzir produção de leite + sedação no lactente — evitar uso crônico",
ped:"≥2a — uso restrito ao mínimo necessário",
},
mecanismo:"ANTAGONISTA H1 + atravessa BHE (SEDAÇÃO) + ANTIMUSCARÍNICO (efeito anticolinérgico) + ANTI-α1 (hipotensão).",
farmacocin:{
absorc:"VO bem absorvida",
distrib:"AMPLA — atravessa BHE",
metab:"Hepático",
elimin:"Renal",
meiavida:"~20-27h",
ligacao:"~70%",
},
ef_colats:{
comuns:["⚠ SEDAÇÃO marcada (até 50% pacientes)","⚠ ANTICOLINÉRGICO: boca seca, retenção urinária, visão turva, constipação","Tonteira","Coordenação prejudicada"],
sérios:["⚠ Delirium em idoso","⚠ Glaucoma ângulo fechado","⚠ Retenção urinária em HPB","Excitação paradoxal em criança","Convulsão em superdose"],
},
interacoes:["⚠ Álcool, BZD, opioides, antidepressivos: SEDAÇÃO SOMATIVA","⚠ Anticolinérgicos: somatório (cuidado: ADT, oxibutinina, antipsicóticos, β2 inalado em alta dose)","IMAO: cuidado"],
contraindicacoes:["⚠ Glaucoma ângulo fechado","⚠ HPB com retenção","⚠ Asma aguda grave","⚠ Idoso (relativa — Beers)","Lactente <2 anos","Hipersensibilidade","Crise epiléptica não controlada"],
monit:["Sedação, função cognitiva","Sintomas anticolinérgicos","Resposta clínica"],
gravidez:"B",
sus:"⚠ REMUME — UBS dispensação direta + PFPB.",
referencias:["⚠ Beers Criteria 2023; ARIA."],
},
{id:"med-fexofenadina", contexto:["pa","ubs"], classe:"Anti-histamínico H1 — 2ª geração", grupo:"alergia",
nome:"Fexofenadina",
sin:["Allegra","Allexofedrin","Fexodane"],
formas:["Comprimido 60 mg, 120 mg, 180 mg","Suspensão oral 6 mg/mL","⚠ NÃO REMUME — PFPB em algumas SES; particular"],
resumo:"⚠ ANTI-HISTAMÍNICO H1 DE 2ª GERAÇÃO — TEORICAMENTE A MENOS SEDATIVA da classe. ⚠ Filha do terfenadino (descontinuado por torsades) — fexofenadina é o metabólito ativo, SEM efeito QT clinicamente relevante. Indicações iguais aos outros. ⚠ Absorção REDUZIDA por suco de frutas (laranja, maçã, uva — efeito transportador OATP).",
dose_rapida:"180 mg/d OU 60 mg 12/12h",
doses:[
{ind:"⚠ RINITE ALÉRGICA", dose:"180 mg VO 1×/d (1 comprimido pela manhã) OU 60 mg 12/12h", obs:""},
{ind:"⚠ URTICÁRIA CRÔNICA", dose:"180 mg VO 1×/d (até 720 mg/d off-label em refratária — ARIA)", obs:""},
{ind:"Pediatria", dose:"6m-2a: 15 mg 12/12h. 2-11a: 30 mg 12/12h. ≥12a: 60 mg 12/12h ou 180 mg/d", obs:""},
],
ajustes:{
irc:"⚠ TFG <80: 60 mg/d (adulto)",
iht:"Sem ajuste rotineiro",
idoso:"Avaliar função renal",
gestante:"⚠ C — uso quando benefício > risco (loratadina é preferida na gestação)",
aleita:"Compatível",
ped:"Aprovada ≥6 meses",
},
mecanismo:"ANTAGONISTA H1 PERIFÉRICO SELETIVO — não atravessa BHE significativamente.",
farmacocin:{
absorc:"VO ~33% — ⚠ REDUZIDO por suco de laranja/maçã/uva (orientar SEPARAR 4h), reduzido por antiácidos com Al/Mg",
distrib:"Periférica",
metab:"Mínimo (não CYP)",
elimin:"Fecal predominante",
meiavida:"~14h",
ligacao:"~70%",
},
ef_colats:{
comuns:["⚠ Sonolência MUITO BAIXA (próxima a placebo)","Cefaleia","Náusea","Dispepsia"],
sérios:["Reações alérgicas (raras)","Sem QT longo (vantagem sobre terfenadino descontinuado)"],
},
interacoes:["⚠ Suco frutas (OATP)","Antiácidos Al/Mg: ↓ absorção","Eritromicina, cetoconazol: ↑ nível (sem QT clinicamente relevante)"],
contraindicacoes:["Hipersensibilidade"],
monit:["Resposta clínica"],
gravidez:"C",
sus:"PFPB em algumas SES",
referencias:["ARIA 2024."],
},
{id:"med-hidroxizina", contexto:["pa","ubs"], classe:"Anti-histamínico H1 — 1ª geração (piperazina)", grupo:"alergia",
nome:"Hidroxizina",
sin:["Hixizine","Pruri-gone","Marax"],
formas:["Comprimido 25 mg","Solução oral 2 mg/mL","FARMASUS"],
resumo:"⚠ ANTI-HISTAMÍNICO H1 DE 1ª GERAÇÃO — sedativo + ANSIOLÍTICO (efeito original — precursor das BZD). Indicações principais: PRURIDO RESISTENTE, urticária aguda, sedação pré-procedimento, ANSIEDADE leve, insônia transitória. ⚠ QT longo (alta dose ou em risco) — FDA Warning 2015.",
dose_rapida:"25 mg VO 6-8/8h",
doses:[
{ind:"⚠ PRURIDO RESISTENTE / urticária", dose:"25 mg VO 6-8/8h × 5-10 dias", obs:"⚠ Útil quando 2ª geração não controla. Sedação ajuda à noite."},
{ind:"⚠ Ansiedade / pré-anestesia", dose:"50-100 mg/d ÷ 6-8h (ansiedade); 50-100 mg IM 30-60 min pré-op", obs:""},
{ind:"⚠ Insônia transitória", dose:"25-50 mg HS", obs:"⚠ Não rotineiro crônico."},
{ind:"Pediatria — prurido/urticária", dose:"0,5-1 mg/kg 6/6h", obs:""},
],
ajustes:{
irc:"Reduzir em TFG <50",
iht:"Reduzir",
idoso:"⚠ EVITAR — Beers (anticolinérgico, sedação, QT)",
gestante:"⚠ C — Evitar 1º trimestre. Em hiperêmese refratária: aceitável 2-3º trimestre.",
aleita:"⚠ Evitar em uso crônico",
ped:"≥6 meses (com cautela)",
},
mecanismo:"ANTAGONISTA H1 + atravessa BHE (sedação + ansiolítico) + ANTIMUSCARÍNICO + 5-HT.",
farmacocin:{
absorc:"VO bem absorvida",
distrib:"AMPLA — BHE",
metab:"Hepático → CETIRIZINA (metabólito ativo, 2ª geração)",
elimin:"Renal",
meiavida:"~14-25h",
ligacao:"Alta",
},
ef_colats:{
comuns:["⚠ Sedação marcada","Anticolinérgico (boca seca, retenção)","Tontura","Cefaleia"],
sérios:["⚠ QT LONGO — FDA Warning 2015 (especialmente >100 mg/d, idoso, eletrólitos baixos)","Convulsão em superdose","Excitação paradoxal em criança","Síndrome anticolinérgica","Hipotensão"],
},
interacoes:["⚠ QT-prolongadores","⚠ Álcool, BZD, opioides: sedação somativa","⚠ Anticolinérgicos","IMAO","Anti-hipertensivos: hipotensão"],
contraindicacoes:["⚠ QT longo congênito ou adquirido","Glaucoma ângulo fechado","HPB com retenção","⚠ Idoso (relativa)","Gestação 1º trim (relativa)","Hipersensibilidade"],
monit:["ECG em risco/dose alta","Sedação","Sintomas anticolinérgicos"],
gravidez:"C",
sus:"FARMASUS",
referencias:["⚠ FDA QT Warning 2015; Beers."],
},
{id:"med-loratadina", contexto:["pa","ubs"], classe:"Anti-histamínico H1 — 2ª geração (não-sedativo)", grupo:"alergia",
nome:"Loratadina",
sin:["Claritin","Loranil","Histadin"],
formas:["Comprimido 10 mg","Xarope 1 mg/mL","REMUME — UBS dispensação direta + PFPB"],
resumo:"⚠ ANTI-HISTAMÍNICO H1 DE 2ª GERAÇÃO — NÃO sedativo (não atravessa BHE significativamente). Indicações: RINITE ALÉRGICA (sazonal + perene), URTICÁRIA CRÔNICA, prurido alérgico. ⚠ NÃO É 1ª LINHA EM EMERGÊNCIA ALÉRGICA / ANAFILAXIA (lá: adrenalina + anti-H1 IV se disponível). Início de ação 1-3h, duração 24h.",
dose_rapida:"10 mg VO 1×/d (adulto)",
doses:[
{ind:"⚠ RINITE ALÉRGICA / URTICÁRIA", dose:"10 mg VO 1×/d ad lib", obs:"⚠ Em urticária crônica refratária: ⚠ AUMENTAR DOSE até 4× (40 mg/d) — ARIA + EAACI permitem off-label antes de subir para imunobiológico."},
{ind:"⚠ Prurido (alérgico, urticariforme)", dose:"10 mg/d", obs:""},
{ind:"Pediatria", dose:"2-5 anos: 5 mg/d. ≥6a: 10 mg/d", obs:""},
],
ajustes:{
irc:"TFG <30: 10 mg cada 48h",
iht:"⚠ Reduzir em IH grave",
idoso:"Geralmente sem ajuste — preferida sobre 1ª geração (sem efeito anticolinérgico)",
gestante:"⚠ B — segura. Considerada SEGURA na gestação (a mais estudada da classe).",
aleita:"Compatível",
ped:"≥2a (xarope) — segura.",
},
mecanismo:"⚠ ANTAGONISTA H1 PERIFÉRICO (seletivo). NÃO atravessa BHE — sem sedação significativa. NÃO bloqueia muscarínicos (sem efeito anticolinérgico).",
farmacocin:{
absorc:"VO bem absorvida",
distrib:"Ampla, periférica — pouco SNC",
metab:"Hepático CYP3A4, CYP2D6 → desloratadina (metabólito ativo)",
elimin:"Renal + fecal",
meiavida:"~8-14h (metabólito ~28h — explica 1×/d)",
ligacao:"~97%",
},
ef_colats:{
comuns:["Sonolência LEVE (em <10% — muito menos que 1ª geração)","Cefaleia","Boca seca leve","Fadiga"],
sérios:["⚠ QT longo em dose alta (raro)","Hepatotoxicidade rara","Reações alérgicas paradoxais (raro)"],
},
interacoes:["⚠ Inibidores CYP3A4 (cetoconazol, eritromicina, claritro): ↑ loratadina (significância clínica modesta)","⚠ Álcool: sedação somativa (mesmo em 2ª geração)","Outros sedativos"],
contraindicacoes:["Hipersensibilidade"],
monit:["Resposta clínica","Sintomas em uso prolongado"],
gravidez:"B",
sus:"⚠ REMUME — UBS dispensação direta + PFPB.",
referencias:["ARIA 2024; EAACI Urticaria 2022."],
},
{id:"med-prometazina", contexto:["pa","ubs"], classe:"Anti-histamínico H1 — 1ª geração (fenotiazina)", grupo:"alergia",
nome:"Prometazina",
sin:["Phenergan","Pamergan","Promezin"],
formas:["Comprimido 25 mg","Solução oral 1 mg/mL","Ampola 50 mg/2 mL IM/IV","Creme tópico 2%","FARMASUS"],
resumo:"⚠ ⚠ ANTI-HISTAMÍNICO H1 DE 1ª GERAÇÃO (FENOTIAZINA) — MUITO SEDATIVO + ANTI-EMÉTICO + ANTICOLINÉRGICO. Indicações: ⚠ ANTI-EMESE forte (gestação, pós-op, cinetose), reação alérgica aguda, sedação pré-procedimento. ⚠ MULTIPLOS RISCOS: distonia / sintomas extrapiramidais (fenotiazina), QT longo, ⚠ NUNCA EM <2 ANOS (depressão respiratória, morte — black box FDA).",
dose_rapida:"25 mg VO/IM/IV 6-8/8h (adulto)",
doses:[
{ind:"⚠ ANTI-EMESE / náusea-vômito pós-op, gestação (HG), cinetose", dose:"25 mg VO/IM 6-8/8h ad lib", obs:"⚠ Hiperêmese gravídica — alternativa a metoclopramida/ondansetrona."},
{ind:"⚠ Reação alérgica aguda (urticária, prurido)", dose:"25 mg VO/IM 6/6h", obs:"⚠ Anafilaxia: ADRENALINA primeiro; prometazina como adjunto somente."},
{ind:"⚠ Sedação pré-procedimento (especialmente em UBS sem anestesista)", dose:"25-50 mg IM 30-60 min antes", obs:"⚠ Cuidado com sedação prolongada, queda."},
{ind:"⚠ Insônia AGUDA TRANSITÓRIA (raro, NÃO ROTINEIRO)", dose:"25 mg HS PRN", obs:"⚠ NÃO USAR cronicamente — anticolinérgico em idoso."},
{ind:"⚠ AGITAÇÃO PSICOMOTORA (com haloperidol)", dose:"50 mg IM + haloperidol 5 mg IM", obs:"⚠ Esquema clássico do PA — sedação + extrapiramidal preventivo do haloperidol."},
{ind:"⚠ Crise de migrânea com vômito (em emergência)", dose:"25 mg IM/IV", obs:""},
],
ajustes:{
irc:"Cautela",
iht:"Reduzir dose",
idoso:"⚠ ⚠ EVITAR — Beers (anticolinérgico forte, sedação prolongada, queda, delirium)",
gestante:"⚠ C — em hiperêmese gravídica: usar quando benefício > risco. Evitar próximo ao parto (depressão respiratória neonatal).",
aleita:"⚠ Pode reduzir produção láctea + sedação lactente — evitar uso crônico",
ped:"⚠ ⚠ ⚠ NUNCA <2 ANOS — BLACK BOX FDA: depressão respiratória fatal. Em 2-12a: cautela extrema, dose mínima.",
},
mecanismo:"ANTAGONISTA H1 + ANTIMUSCARÍNICO + ANTI-D2 (efeito antiemético + extrapiramidal) + ANTI-α1 (hipotensão).",
farmacocin:{
absorc:"VO ~25%",
distrib:"AMPLA — atravessa BHE",
metab:"Hepático",
elimin:"Renal + fecal",
meiavida:"~9-16h",
ligacao:"~90%",
},
ef_colats:{
comuns:["⚠ SEDAÇÃO MARCADA","⚠ ANTICOLINÉRGICO marcado","Hipotensão postural","Tontura"],
sérios:["⚠ ⚠ DEPRESSÃO RESPIRATÓRIA EM <2 ANOS — black box FDA","⚠ DISTONIA AGUDA / EXTRAPIRAMIDAL — tratar com biperideno IM","⚠ SÍNDROME NEUROLÉPTICA MALIGNA (raro)","⚠ NECROSE TISSULAR SE EXTRAVASAR IV — usar veia calibrosa, diluir","⚠ QT LONGO","Convulsão em superdose","Discinesia tardia em uso prolongado"],
},
interacoes:["⚠ Álcool, BZD, opioides: depressão SNC + respiratória","⚠ Anticolinérgicos: somatório","⚠ QT-prolongadores: ⚠ atenção","⚠ Antipsicóticos: somatório extrapiramidal","Tramadol: convulsão"],
contraindicacoes:["⚠ ⚠ <2 ANOS","Coma, depressão SNC importante","Glaucoma ângulo fechado","HPB com retenção","⚠ Idoso (relativa)","Hipersensibilidade","Hipersensibilidade a fenotiazinas"],
monit:["⚠ Vigilância respiratória especialmente em criança","Extrapiramidais (tratar com biperideno)","QT em risco","Sintomas anticolinérgicos"],
gravidez:"C",
sus:"FARMASUS (controle especial)",
referencias:["⚠ FDA Black Box <2a; Beers Criteria; ABEnfar."],
},
);
