/* ===========================================================
   VOVÔMINIC EMERGÊNCIA — meds/pali.js
   15 medicações
   Grupos: pali
   =========================================================== */

MEDICACOES.push(

/* ============== PALI (15) ============== */

{id:"med-bisacodil", classe:"Laxativo estimulante (contato)", grupo:"pali",
nome:"Bisacodil",
sin:["Dulcolax","Lacto-Purga","Bisalax"],
formas:["Comprimido revestido 5 mg","Supositório 10 mg","Solução retal","REMUME — UBS dispensação direta em muitos municípios; PFPB"],
resumo:"⚠ LAXATIVO ESTIMULANTE (contato direto na parede intestinal) — ⚠ INDICAÇÃO PRINCIPAL EM PALIATIVOS: PROFILAXIA E TRATAMENTO DA CONSTIPAÇÃO INDUZIDA POR OPIOIDE. Combinação clássica: BISACODIL + LACTULOSE (estimulante + osmótico) — esquema recomendado profilático em TODA prescrição de opioide. Início VO 6-12h (tomar HS para evacuar manhã); supositório 15-60 min.",
dose_rapida:"5-10 mg VO HS (dia seguinte) OU 10 mg supositório pela manhã (15-60 min)",
doses:[
{ind:"⚠ ⚠ PROFILAXIA da CONSTIPAÇÃO INDUZIDA POR OPIOIDE — recomendado em TODA prescrição de opioide", dose:"5-10 mg VO HS (todo dia)", obs:"⚠ Combinar com LACTULOSE 15-30 mL 12/12h. ⚠ TODO PACIENTE em opioide deve ter laxativo profilático prescrito JUNTO (não 'se precisar')."},
{ind:"⚠ Constipação aguda — desimpactação leve", dose:"10 mg supositório retal pela manhã (efeito 15-60 min) OU enema glicerinado", obs:"⚠ Antes de DESIMPACTAÇÃO MANUAL em fecaloma — tentar enema/supositório primeiro. ⚠ Avaliar fecaloma com diarreia paradoxal (lubrifica em volta da impactação)."},
{ind:"⚠ Preparo de cólon (ambulatorial leve)", dose:"15-30 mg VO na véspera", obs:"Procedimentos diagnósticos leves; em colonoscopia: PEG/manitol mais eficaz."},
{ind:"Constipação crônica — alternativa segura uso prolongado", dose:"5-10 mg VO HS, conforme necessidade", obs:"⚠ Sem evidência forte de dependência ou dano de cólon em uso ambulatorial regular (mito amplamente desfeito)."},
],
ajustes:{
irc:"Sem ajuste",
iht:"Sem ajuste",
idoso:"⚠ Dose habitual; cuidado com cólica e desidratação se uso vigoroso",
gestante:"⚠ B — uso seguro pontual. Constipação gestacional: 1ª linha = fibra + água + lactulose. Bisacodil OK se refratário.",
aleita:"⚠ Compatível",
ped:"≥4 anos (5 mg)",
},
mecanismo:"⚠ Difenilmetano — estimula plexo mioentérico de Auerbach → ↑ peristalse colônica + ↓ reabsorção de água/eletrólitos no cólon → fezes amolecidas e movimento aumentado.",
farmacocin:{
absorc:"VO mínima absorção sistêmica (~5%) — efeito local. Supositório efeito local.",
distrib:"Periférica/intestinal",
metab:"Hidrólise pelas mucosas intestinais",
elimin:"Fecal + renal pequena fração",
meiavida:"~16h (mas efeito independe — local)",
ligacao:"Variável",
},
ef_colats:{
comuns:["⚠ Cólica abdominal","Diarreia","Náusea leve","Sensação de queimação retal (supositório)"],
sérios:["⚠ Hipocalemia em uso EXCESSIVO E PROLONGADO (raro com dose habitual)","Desidratação em uso vigoroso","Colite isquêmica (raro, descrito em uso crônico de altas doses)","Reações alérgicas"],
},
interacoes:["⚠ Diuréticos: ↑ risco hipocalemia em uso excessivo","Antiácidos: NÃO TOMAR JUNTO (separar 1h) — quebra revestimento entérico → libera no estômago → cólica","Leite: idem","Inibidores bomba prótons: idem"],
contraindicacoes:["⚠ Obstrução intestinal","⚠ Abdome agudo cirúrgico","Apendicite suspeita","Doença inflamatória intestinal em atividade grave","Hipersensibilidade"],
monit:["Resposta clínica","Eletrólitos em uso crônico de alta dose","Diarreia paradoxal (fecaloma)"],
gravidez:"B",
sus:"REMUME UBS + PFPB",
referencias:["NICE Palliative Care; AGA Constipation Guidelines; ⚠ Esquema profilático CIO clássico."],
},
{id:"med-bromoprida", classe:"Procinético + antiemético (similar à metoclopramida)", grupo:"pali",
nome:"Bromoprida",
sin:["Digesan","Plamet","Bromoprida"],
formas:["Cápsula 10 mg","Solução oral 4 mg/mL","Ampola 5 mg/mL (2 mL) IM/IV","REMUME — UBS dispensação direta"],
resumo:"⚠ ANÁLOGO BRASILEIRO DA METOCLOPRAMIDA — mecanismo similar (D2 antagonista + procinético). Indicações similares: NÁUSEA + ESTASE GÁSTRICA + dispepsia. ⚠ Perfil de efeitos colaterais similar — extrapiramidais, ⚠ contraindicada em obstrução intestinal. Vantagem: tradição brasileira de uso + acesso fácil.",
dose_rapida:"10 mg VO/IV/SC 6-8/8h",
doses:[
{ind:"⚠ NÁUSEA POR ESTASE GÁSTRICA / dispepsia funcional", dose:"10 mg VO 6-8/8h 30 min antes das refeições", obs:""},
{ind:"⚠ Náusea química / opioide", dose:"10 mg VO/SC 6-8/8h", obs:""},
{ind:"Náusea pós-op", dose:"10 mg IV / IM", obs:""},
],
ajustes:{
irc:"⚠ Reduzir em IRC",
iht:"⚠ Reduzir em IH",
idoso:"⚠ Reduzir dose, vigilância extrapiramidal",
gestante:"⚠ B — uso comum em hiperêmese leve no Brasil",
aleita:"Compatível",
ped:"≥6a (cautela em <12a)",
},
mecanismo:"D2 antagonista + ação procinética via plexo mioentérico (similar metoclopramida).",
farmacocin:{
absorc:"VO bem absorvida",
distrib:"Ampla",
metab:"Hepático",
elimin:"Renal",
meiavida:"~4-6h",
ligacao:"Alta",
},
ef_colats:{
comuns:["Sonolência","Sintomas extrapiramidais","Diarreia","Cefaleia"],
sérios:["⚠ Distonia aguda","⚠ Discinesia tardia em uso prolongado","Hiperprolactinemia","Hipotensão em IV rápido"],
},
interacoes:["Similar à metoclopramida — vide acima"],
contraindicacoes:["⚠ Obstrução intestinal mecânica","Perfuração GI","Convulsão","Feocromocitoma","Parkinson","Hipersensibilidade"],
monit:["Sintomas extrapiramidais","Resposta clínica"],
gravidez:"B",
sus:"⚠ REMUME — UBS dispensação direta",
referencias:["ANVISA; consenso brasileiro."],
},
{id:"med-capsaicina", classe:"Agonista TRPV1 — dessensibilizador de nociceptores cutâneos", grupo:"pali",
nome:"Capsaicina Tópica",
sin:["Qutenza (patch 8%)","Capsicum","Capsaiscina","Aspercrem capsaicina"],
formas:["Creme 0,025% / 0,075% — uso 3-4×/d × 4-8 semanas (manipulado, particular)","Patch 8% (Qutenza) — aplicação única 30-60 min em consultório, repetir cada 3 meses — ⚠ NÃO disponível SUS","REMUME — geralmente NÃO; cremes manipulados em farmácia de manipulação"],
resumo:"⚠ ⚠ DOR NEUROPÁTICA FOCAL — dessensibilização de nociceptores cutâneos via DEPLEÇÃO DE SUBSTÂNCIA P + INTERNALIZAÇÃO DO CANAL TRPV1. Indicação principal: NEURALGIA PÓS-HERPÉTICA + neuropatia diabética dolorosa + dor neuropática focal (cicatriz, pós-cirúrgica). ⚠ Vantagem: ZERO interação sistêmica, sem sedação, sem efeitos cognitivos. ⚠ Desvantagem: queimação intensa inicial (limita adesão), efeito gradual (2-4 semanas creme), patch 8% mais efetivo mas indisponível no SUS.",
dose_rapida:"Creme 0,025-0,075% — aplicar 3-4×/d × 4-8 semanas; Patch 8% — aplicação única 30-60 min em consultório",
doses:[
{ind:"⚠ ⚠ NEURALGIA PÓS-HERPÉTICA — dor localizada (especialmente em idoso, fragilizado, terminal)", dose:"Creme 0,075% — aplicar fina camada 3-4×/d sobre área dolorosa × 4-8 semanas (efeito em 2-4 semanas)", obs:"⚠ ⚠ Orientar: queimação intensa nas primeiras 2 semanas é ESPERADA e indica funcionamento (depleção de substância P). Adesão é o maior desafio. Lavar mãos APÓS aplicar — não tocar olhos/genitais. Não aplicar sobre pele lesada."},
{ind:"⚠ Neuropatia diabética dolorosa focal (especialmente pés)", dose:"Creme 0,075% — 3-4×/d × 4-8 semanas", obs:"⚠ Vantagem em idoso polimedicado — ZERO interação medicamentosa sistêmica."},
{ind:"⚠ Dor neuropática focal pós-cirúrgica / cicatriz", dose:"Creme 0,075% — 3-4×/d × 4-8 semanas", obs:""},
{ind:"⚠ Dor oncológica neuropática focal (paliativo)", dose:"Creme 0,025-0,075% — 3-4×/d", obs:"⚠ Especialmente útil quando opioides em dose alta e ainda há dor neuropática focal residual. Adjuvante."},
{ind:"⚠ Patch Qutenza 8% (clínica especializada)", dose:"Aplicar em consultório 30-60 min após anestesia tópica (lidocaína creme); pode repetir cada 3 meses", obs:"⚠ NÃO DISPONÍVEL SUS — particular, custo alto. Realização em clínica de dor."},
],
ajustes:{
irc:"Sem ajuste — ação local",
iht:"Sem ajuste",
idoso:"⚠ Excelente opção em idoso polimedicado — sem interações sistêmicas. Avaliar habilidade para aplicação correta.",
gestante:"⚠ B — pode usar em área focal pequena",
aleita:"Compatível — não aplicar sobre região mamária se amamentando",
ped:"Não rotineiro <18a (dados limitados)",
},
mecanismo:"⚠ AGONISTA do canal TRPV1 (receptor vanilóide) presente em fibras C nociceptivas. Aplicação repetida causa: (1) DEPLEÇÃO DE SUBSTÂNCIA P nos terminais nervosos; (2) DESSENSIBILIZAÇÃO funcional do TRPV1; (3) DEGENERAÇÃO REVERSÍVEL de fibras nervosas cutâneas. Resultado: ↓ transmissão nociceptiva local. Efeito reversível em 3-6 meses após suspensão.",
farmacocin:{
absorc:"⚠ Mínima absorção sistêmica — efeito local",
distrib:"Local cutânea",
metab:"Local",
elimin:"Local",
meiavida:"N/A — efeito gradual e cumulativo",
ligacao:"N/A",
},
ef_colats:{
comuns:["⚠ ⚠ QUEIMAÇÃO / ARDOR no local — intensa primeiras 2-3 semanas (sinal de funcionamento)","Eritema local","Prurido","Tosse irritativa se inalado","Lacrimejamento se tocar olho"],
sérios:["⚠ ⚠ HIPERTENSÃO transitória durante aplicação do patch 8% (estímulo doloroso → resposta simpática) — monitorar PA","Dermatite intensa em pele sensível","Anafilaxia (raríssimo)","Lesão cutânea por uso excessivo"],
},
interacoes:["⚠ ⚠ ⚠ NÃO TOCAR OLHOS / GENITAIS / MUCOSAS após aplicação — irritação extrema. Lavar mãos com água + sabão (não remove totalmente — usar vinagre se necessário em contaminação acidental).","Não interage sistemicamente — vantagem clínica MAIOR"],
contraindicacoes:["⚠ Pele lesada / aberta no local","⚠ Hipersensibilidade à pimenta","HAS muito mal controlada (relativa, para patch 8%)","Aplicação em face / mucosas / olhos","Hipersensibilidade a capsaicina"],
monit:["Adesão (frequente abandono por queimação)","Resposta clínica em 2-4 semanas","PA durante aplicação de patch 8%","Estado da pele local"],
gravidez:"B",
sus:"⚠ Creme manipulado (particular, ~R$ 30-80/tubo); Patch 8% NÃO disponível SUS",
referencias:["NICE Neuropathic Pain; ⚠ NEURONS Trial (Qutenza); APM Guidelines."],
},
{id:"med-dexametasona", classe:"Glicocorticoide sintético potente, longa duração", grupo:"pali",
nome:"Dexametasona",
sin:["Decadron","Dexason","Dexarinil"],
formas:["Comprimido 0,5 mg, 4 mg","Solução oral 0,1 mg/mL","Ampola 4 mg/mL e 10 mg/2,5 mL IM/IV/SC","Colírio, creme tópico","REMUME — algumas formas em UBS / FARMASUS"],
resumo:"⚠ ⚠ CORTICOIDE POTENTE — pedra angular em PALIATIVOS por múltiplos usos: ⚠ COMPRESSÃO MEDULAR (16 mg IV bolus), HIC por metástase cerebral (4-16 mg/d), antiemético (quimio, opioide, obstrução intestinal), anorexia/bem-estar (4-6 sem), DISPNEIA por linfangite/VCS, dor óssea, anti-inflamatório. Potência 25× hidrocortisona, sem mineralocorticoide. ⚠ Efeitos colaterais cumulativos limitam uso crônico.",
dose_rapida:"2-4 mg/d (apetite/anti-emético) até 16 mg/d (compressão medular, edema cerebral)",
doses:[
{ind:"⚠ ⚠ COMPRESSÃO MEDULAR MALIGNA — EMERGÊNCIA", dose:"16 mg IV BOLUS imediato + 4 mg IV/VO 6/6h × 48h, depois reduzir gradativo", obs:"⚠ ⚠ NÃO ESPERAR IMAGEM — bolus em suspeita clínica forte."},
{ind:"⚠ EDEMA CEREBRAL por metástase / HIC", dose:"4-8 mg VO/IV 6/6h (até 16 mg em sintomas graves)", obs:"⚠ Reduzir gradualmente para dose mínima eficaz após melhora."},
{ind:"⚠ DISPNEIA por LINFANGITE CARCINOMATOSA / SVCS / obstrução brônquica peritumoral", dose:"8-16 mg/d VO/IV/SC (geralmente manhã)", obs:""},
{ind:"⚠ NÁUSEA REFRATÁRIA / quimioterapia / obstrução intestinal", dose:"4-8 mg VO/SC/IV 1-2×/d", obs:"⚠ Adjuvante eficaz — combinação com ondansetrona em quimio."},
{ind:"⚠ ANOREXIA / BEM-ESTAR / FADIGA em paliativos", dose:"2-4 mg VO/manhã × 4-6 sem, depois reavaliar", obs:"⚠ ⚠ EFEITO CURTO PRAZO. Útil em paciente com expectativa de SEMANAS-MESES. Reduzir após melhora."},
{ind:"⚠ DOR ÓSSEA por metástase", dose:"4-8 mg/d", obs:"⚠ Adjuvante — junto a opioide + AINE (se possível) + bifosfonato."},
{ind:"COVID-19 com necessidade O2", dose:"6 mg VO/IV 1×/d × 10d", obs:""},
{ind:"Tireoidite / crise tireotóxica", dose:"2 mg IV 6/6h", obs:"Bloqueia conversão T4→T3."},
{ind:"Maturação pulmonar fetal", dose:"6 mg IM 12/12h × 4 doses", obs:"Obstetrícia."},
],
ajustes:{
irc:"Sem ajuste",
iht:"Cautela",
idoso:"⚠ Risco aumentado: miopatia, hiperglicemia, infecção, fratura. Avaliar risco-benefício.",
gestante:"⚠ C — em maturação pulmonar fetal: indicada. Uso prolongado: cautela.",
aleita:"Compatível em dose paliativa",
ped:"Conforme indicação especialista",
},
mecanismo:"⚠ GLICOCORTICOIDE SINTÉTICO — liga ao receptor citoplasmático, transcrição genética — efeitos anti-inflamatórios + imunossupressores + antiedema + antiemético central + apetite. Sem ação mineralocorticoide (não retém sódio). Potência ~25× hidrocortisona, ~7× prednisolona.",
farmacocin:{
absorc:"VO ~80-90%",
distrib:"Ampla",
metab:"Hepático CYP3A4",
elimin:"Renal",
meiavida:"~36-54h (efeito biológico) — explica DOSE ÚNICA DIÁRIA",
ligacao:"~77%",
},
ef_colats:{
comuns:["⚠ Hiperglicemia (pode descompensar diabetes)","⚠ Insônia (administrar manhã)","Ganho de peso","Edema (leve — sem mineralocorticoide)","Acne, equimoses, pele fina","Dispepsia","Aumento de apetite (benéfico em paliativos)"],
sérios:["⚠ ⚠ MIOPATIA proximal (uso prolongado, principalmente esteróides)","⚠ ⚠ CANDIDÍASE oral / esofágica (frequente em paliativos com dexa)","⚠ INFECÇÕES OPORTUNISTAS (TB reativada, pneumocystose)","⚠ HIPERGLICEMIA / NOVA DM","⚠ SUPRESSÃO ADRENAL (uso >2-3 sem) — não suspender abruptamente","⚠ Psicose / mania por corticoide (raro em paliativos)","⚠ ÚLCERA péptica (cuidado em quem usa AINE)","⚠ OSTEOPOROSE / fratura","⚠ Cataratas / glaucoma (crônico)","HAS","Síndrome de Cushing iatrogênica"],
},
interacoes:["⚠ AINE: ↑ risco GI","⚠ ANTIDIABÉTICOS: ajuste necessário","⚠ Indutores CYP3A4 (rifampicina, fenitoína, carbamazepina): ↓ dexa","⚠ Inibidores CYP3A4 (cetoconazol, claritromicina, ritonavir): ↑ dexa","⚠ Anticoagulantes (warfarina): variável","Vacinas de vírus vivos: ⚠ EVITAR"],
contraindicacoes:["⚠ Infecção fúngica sistêmica não tratada","⚠ Tuberculose ativa sem tratamento","Hipersensibilidade","Cautela em DM, HAS, úlcera, glaucoma"],
monit:["Glicemia","PA","Função adrenal em uso prolongado","Sinais de infecção","Candida oral","Densitometria em uso crônico"],
gravidez:"C",
sus:"⚠ REMUME — algumas formas em UBS / FARMASUS",
referencias:["ANCP; ESMO Bone Mets; NICE; Bristol Guideline."],
},
{id:"med-escopolamina", classe:"Antimuscarínico central (atravessa BHE)", grupo:"pali",
nome:"Escopolamina Hidrobrometo / Bromidrato",
sin:["Hyoscine hydrobromide","Transderm Scop (adesivo TD)","Hioscina (forma central)"],
formas:["Ampola 0,4 mg/mL SC/IM/IV","Adesivo TD 1 mg/72h (Transderm Scop) — ⚠ acesso difícil SUS","⚠ NÃO confundir com hioscina BUTILBROMETO (Buscopan, periférica)"],
resumo:"⚠ ⚠ ANTIMUSCARÍNICO CENTRAL — ⚠ ATRAVESSA A BARREIRA HEMATOENCEFÁLICA (diferente do butilbrometo). Indicações paliativas: ESTERTOR TERMINAL com necessidade de sedação leve (ansioso/agitado), sialorreia patológica (adesivo TD), náusea vestibular/cinetose. ⚠ Causa SEDAÇÃO + AMNÉSIA + DELIRIUM (especialmente em idoso) — PODE SER ÚTIL (paciente terminal agitado) OU PREJUDICIAL (delirium hiperativo).",
dose_rapida:"0,4 mg SC 4-6/6h OU adesivo TD 1 mg/72h (acesso restrito)",
doses:[
{ind:"⚠ ESTERTOR TERMINAL — alternativa com sedação", dose:"0,4 mg SC bolus, depois 0,4 mg SC 4-6/6h", obs:"⚠ Preferir HIOSCINA BUTILBROMETO se NÃO desejar sedação. Usar escopolamina se paciente ansioso/agitado em fase final."},
{ind:"⚠ ⚠ SIALORREIA PATOLÓGICA (ELA, paralisia cerebral, pós-AVC)", dose:"Adesivo TD 1 mg/72h (Transderm Scop) — trocar a cada 3 dias atrás da orelha", obs:"⚠ Acesso difícil SUS — particular. ⚠ Lavar mãos após manuseio (midríase se tocar olho)."},
{ind:"Cinetose / náusea vestibular", dose:"Adesivo TD 4-12h antes da viagem", obs:""},
{ind:"⚠ Estertor terminal + agitação leve", dose:"0,4 mg SC 4-6/6h", obs:"Combinação útil. Se agitação franca: midazolam SC associado."},
],
ajustes:{
irc:"Sem ajuste específico",
iht:"Cautela",
idoso:"⚠ ⚠ EVITAR fora de paliativos — alto risco delirium, queda, retenção. ⚠ Beers Criteria. Em paliativos: usar com cautela e sob indicação clara.",
gestante:"⚠ C — evitar exceto necessidade clara",
aleita:"Cautela — pode reduzir produção láctea",
ped:"⚠ Cautela — efeitos centrais marcados",
},
mecanismo:"ANTAGONISTA muscarínico (similar atropina) + ATRAVESSA BHE → efeito CENTRAL (sedação, amnésia, antiemese vestibular) + efeito periférico (secreção, motilidade).",
farmacocin:{
absorc:"VO erratica; TD ~50% (adesivo); SC/IM boa",
distrib:"⚠ AMPLA — atravessa BHE (diferença fundamental do butilbrometo)",
metab:"Hepático",
elimin:"Renal + fecal",
meiavida:"~8h (forma livre); adesivo libera por 72h",
ligacao:"Baixa",
},
ef_colats:{
comuns:["⚠ Sedação","⚠ Amnésia","Boca seca","Retenção urinária","Visão turva","Constipação","Confusão leve"],
sérios:["⚠ ⚠ DELIRIUM (especialmente em idoso, e a SUSPENSÃO do adesivo pode causar delirium de rebote)","⚠ Glaucoma ângulo fechado","⚠ Retenção urinária aguda","⚠ MIDRÍASE em olho contralateral por contaminação dos dedos (descrito)","Hipertermia (calor)","Bradicardia (paradoxal em baixa dose)"],
},
interacoes:["⚠ ⚠ Outros anticolinérgicos: somatório (incluindo escopolamina + butilbrometo, evitar combinar)","⚠ Álcool, BZD, opioides: sedação somativa","Antidepressivos tricíclicos","Antipsicóticos","Antihistamínicos 1ª geração"],
contraindicacoes:["⚠ Glaucoma ângulo fechado","⚠ HPB com retenção","Miastenia gravis","Hipersensibilidade","⚠ Idoso fora de contexto paliativo (relativa)","Crianças <12a (relativa)"],
monit:["⚠ Vigilância de delirium","Sedação","Retenção urinária","Sialorreia (resposta)"],
gravidez:"C",
sus:"⚠ Ampola FARMASUS em algumas UBS; adesivo TD particular",
referencias:["NICE Palliative Care; APM Guidelines."],
},
{id:"med-haloperidol", classe:"Antipsicótico típico (butirofenona) — D2 antagonista", grupo:"pali",
nome:"Haloperidol",
sin:["Haldol","Haloper","Halo"],
formas:["Comprimido 1 mg, 5 mg","Solução oral 2 mg/mL (gotas)","Ampola 5 mg/mL IM/IV","Ampola decanoato 50 mg/mL IM (depot mensal — psiquiatria)","REMUME — UBS dispensação direta + FARMASUS (controle especial)"],
resumo:"⚠ ⚠ ANTIPSICÓTICO TÍPICO — pedra angular em PALIATIVOS para NÁUSEA POR CTZ (opioide, uremia, hipercalcemia) e DELIRIUM. Doses pequenas (0,5-2 mg) muito eficazes para sintomas paliativos. ⚠ ⚠ EVITAR EM PARKINSON / corpos de Lewy. QT longo em dose alta. Via VO/SC bem tolerada em paliativos.",
dose_rapida:"0,5-2 mg VO/SC 8-12/12h (paliativos); 5 mg IM (agitação aguda)",
doses:[
{ind:"⚠ ⚠ NÁUSEA / VÔMITO em paliativos — mecanismo CTZ (opioide, uremia, hipercalcemia, quimio recente)", dose:"0,5-2 mg VO/SC 8-12/12h ad lib", obs:"⚠ ⚠ 1ª LINHA em náusea por CTZ. Dose BAIXA — efeito antiemético com pouca sedação. Solução oral: 5 gotas = 0,5 mg."},
{ind:"⚠ DELIRIUM em paliativos / hospitalizado", dose:"0,5-2 mg VO/SC 8-12/12h + resgate 0,5-1 mg 1/1h conforme necessário. Idoso: 0,25-0,5 mg", obs:"⚠ 1ª LINHA para delirium hiperativo. ⚠ Não em Parkinson."},
{ind:"⚠ AGITAÇÃO PSICOMOTORA AGUDA (PA / emergência)", dose:"5 mg IM (eventualmente + prometazina 50 mg IM para reduzir extrapiramidal e somar sedação)", obs:"Pode repetir a cada 30-60 min até controle. Máx 20 mg/d."},
{ind:"⚠ Hiperêmese gravídica refratária (off-label)", dose:"0,5-1 mg VO/SC 8/8h", obs:"Após falha de ondansetrona/metoclopramida."},
{ind:"Esquizofrenia / TAB com sintomas psicóticos", dose:"5-15 mg/d (psiquiatria)", obs:""},
],
ajustes:{
irc:"⚠ Cautela em IRC importante",
iht:"⚠ Reduzir em IH",
idoso:"⚠ ⚠ INICIAR 0,25-0,5 mg. Risco AVC + mortalidade em demência (Black Box FDA antipsicóticos). Avaliar risco-benefício, geralmente justificado em paliativos.",
gestante:"⚠ C — em hiperêmese refratária: aceitável após outros. Sintomas extrapiramidais neonatais se uso 3º trim.",
aleita:"Cautela — passa pelo leite",
ped:"⚠ Especialista. Geralmente não em rotina <3a.",
},
mecanismo:"⚠ ANTAGONISTA D2 potente (zona quimioceptora CTZ, gânglios da base, mesolímbico). Pouco efeito anti-α1 e anti-H1 (menos sedativo que clorpro/levome).",
farmacocin:{
absorc:"VO ~60-70%",
distrib:"Ampla, atravessa BHE",
metab:"Hepático CYP3A4 e CYP2D6",
elimin:"Renal + fecal",
meiavida:"~18-25h (decanoato 3 sem)",
ligacao:"~90%",
},
ef_colats:{
comuns:["Sedação leve","Sintomas extrapiramidais (SEP) — bradicinesia, rigidez, distonia, tremor","Sialorreia / disartria","Constipação","Hipotensão (leve)","Acatisia"],
sérios:["⚠ ⚠ SÍNDROME NEUROLÉPTICA MALIGNA (rara — hipertermia, rigidez muscular, alteração mental, CPK alta)","⚠ DISTONIA AGUDA / CRISE OCULOGÍRICA — tratar com biperideno 5 mg IM","⚠ QT LONGO / Torsades — risco em altas doses IV, especialmente >35 mg/d ou com QT-prolongadores","⚠ DISCINESIA TARDIA (uso crônico)","⚠ AVC + mortalidade em IDOSO com demência (Black Box)","Hiperprolactinemia","Convulsão (raro)"],
},
interacoes:["⚠ ⚠ QT-prolongadores (metadona, antiarrítmicos classe Ia/III, ondansetrona dose alta, macrolídeos, azólicos, alguns ISRS): risco TORSADES","⚠ Anticolinérgicos: somatório","⚠ Levodopa/agonistas DA: efeitos OPOSTOS — perda controle Parkinson","Lítio: ↑ neurotoxicidade","Álcool, BZD, opioides: sedação somativa","Indutores CYP (rifampicina, fenitoína, carbamazepina): ↓ haloperidol"],
contraindicacoes:["⚠ ⚠ PARKINSON / demência de corpos de Lewy","⚠ Depressão SNC importante","⚠ QT longo congênito","⚠ Coma","⚠ Lesão de gânglios da base","Hipersensibilidade","Idoso com demência (relativa — Black Box em alguns contextos)"],
monit:["⚠ Sinais extrapiramidais (escalas)","ECG basal em risco / dose alta","Sinais SNM","Resposta clínica"],
gravidez:"C",
sus:"⚠ REMUME — UBS dispensação direta + FARMASUS",
referencias:["ANCP; APA Delirium; NICE Palliative; FDA Black Box demência."],
},
{id:"med-hioscina-butilbrometo", classe:"Antimuscarínico periférico (amônio quaternário)", grupo:"pali",
nome:"Hioscina Butilbrometo (Buscopan)",
sin:["N-butil-brometo de escopolamina","Buscopan","Buscofem (associação)"],
formas:["Comprimido 10 mg","Ampola 20 mg/mL IM/IV/SC","Solução oral / gotas","REMUME — UBS dispensação direta + emergência hospitalar"],
resumo:"⚠ ⚠ ANTIMUSCARÍNICO PERIFÉRICO (amônio quaternário) — ⚠ NÃO ATRAVESSA A BARREIRA HEMATOENCEFÁLICA — vantagem MAIOR: sem sedação nem delirium (diferença chave para escopolamina hidrobrometo). ⚠ ⚠ INDICAÇÕES PALIATIVAS CRÍTICAS: 1ª linha em ESTERTOR TERMINAL (reduz secreção brônquica), obstrução intestinal maligna (reduz secreção + cólica), cólica visceral. Em emergência: cólica biliar, ureteral, intestinal. Compatível SC (kit fim de vida).",
dose_rapida:"20 mg SC/IV/IM 4-6/6h OU infusão contínua SC 60-120 mg/24h",
doses:[
{ind:"⚠ ⚠ ESTERTOR TERMINAL — 1ª linha", dose:"20 mg SC bolus, depois 20 mg SC 4-6/6h OU infusão SC contínua 60-120 mg/24h", obs:"⚠ Iniciar PRECOCEMENTE — não reverte secreção já formada, só PREVINE acúmulo adicional. NÃO ASPIRAR (trauma, sofrimento)."},
{ind:"⚠ ⚠ OBSTRUÇÃO INTESTINAL MALIGNA INOPERÁVEL", dose:"60-120 mg/24h SC infusão contínua (ou 20 mg SC 6/6h)", obs:"⚠ Em combinação com OCTREOTIDA + dexametasona + analgesia + antiemético (haloperidol). Pode evitar SNG. Mantém VO líquidos se tolerar (alimentação por conforto)."},
{ind:"⚠ Cólica visceral (biliar, ureteral, intestinal) em emergência", dose:"20 mg IV/IM em bolus, podendo repetir 4-6/6h. Associar dipirona/AINE.", obs:"⚠ Início rápido IV. Combinar com analgésico — não substitui."},
{ind:"⚠ Sialorreia patológica (paliativa)", dose:"10-20 mg VO 6/6h (efeito modesto VO)", obs:"⚠ Escopolamina adesivo TD pode ser mais efetiva (atravessa BHE)."},
{ind:"Cólica menstrual / espasmo digestivo leve", dose:"10 mg VO 8/8h ad lib", obs:"Uso ambulatorial."},
],
ajustes:{
irc:"Sem ajuste rotineiro",
iht:"Sem ajuste rotineiro",
idoso:"⚠ Cautela em retenção urinária (HPB), glaucoma. ⚠ Vantagem sobre escopolamina/atropina: não atravessa BHE — SEM delirium.",
gestante:"⚠ B/C — uso quando benefício > risco. Cólica gestacional: amplamente usada.",
aleita:"Compatível em uso pontual",
ped:"Pode ser usado conforme indicação (>2a)",
},
mecanismo:"⚠ ANTAGONISTA dos receptores muscarínicos (M1-M5) em terminações nervosas periféricas (gânglios autonômicos parassimpáticos, músculo liso, glândulas exócrinas) → reduz peristalse, espasmo, secreção. ⚠ AMÔNIO QUATERNÁRIO (carga elétrica permanente) → NÃO ATRAVESSA BHE — diferença farmacológica fundamental vs escopolamina/atropina.",
farmacocin:{
absorc:"⚠ VO baixa biodisponibilidade (~8%). SC/IM/IV: boa.",
distrib:"Restrita ao compartimento periférico (não atravessa BHE)",
metab:"Hidrólise + hepático parcial",
elimin:"Fecal + renal",
meiavida:"~5-10h",
ligacao:"Baixa",
},
ef_colats:{
comuns:["⚠ Boca seca","Retenção urinária leve","Constipação","Visão turva (paralisia ciliar — em alguns)","Taquicardia"],
sérios:["⚠ Retenção urinária aguda em HPB","⚠ Crise de glaucoma agudo de ângulo fechado (raro)","Íleo paralítico em uso prolongado/altas doses","Anafilaxia (raro)"],
},
interacoes:["⚠ Outros anticolinérgicos: somatório (ADT, antipsicóticos clássicos, antihistamínicos 1ª geração, oxibutinina) — aumenta efeitos antimuscarínicos","Metoclopramida/bromoprida: antagonismo do efeito procinético","Antiácidos: podem reduzir absorção VO"],
contraindicacoes:["⚠ Glaucoma ângulo fechado","⚠ Retenção urinária (HPB grave)","⚠ Íleo paralítico / obstrução mecânica completa SEM componente espástico","Miastenia gravis","Hipersensibilidade","Megacólon tóxico","Taquiarritmia descompensada"],
monit:["Resposta clínica","Sintomas anticolinérgicos","Função vesical em idoso"],
gravidez:"B/C",
sus:"⚠ REMUME — UBS dispensação direta + emergência hospitalar",
referencias:["NICE Palliative Care; ⚠ Guia PNCP-Br; APM Guidelines."],
},
{id:"med-lactulose", classe:"Laxativo osmótico (dissacarídeo não-absorvido)", grupo:"pali",
nome:"Lactulose",
sin:["Duphalac","Lactulona","Lactulose Stada"],
formas:["Xarope/solução oral 667 mg/mL (66,7 g/100 mL)","REMUME — UBS dispensação direta em muitos municípios; PFPB"],
resumo:"⚠ LAXATIVO OSMÓTICO — dissacarídeo (galactose + frutose) NÃO ABSORVIDO no intestino delgado → fermentação por bactérias colônicas → ácidos orgânicos (acético, láctico) → puxa água por osmose. ⚠ DUAS INDICAÇÕES CHAVE: (1) PROFILAXIA DE CONSTIPAÇÃO OPIOIDE (combinado com bisacodil); (2) ENCEFALOPATIA HEPÁTICA (acidifica lúmen → reduz absorção de amônia). Início 24-48h.",
dose_rapida:"15-30 mL VO 12/12h (constipação); 30-45 mL VO 6/6h (encefalopatia hepática aguda)",
doses:[
{ind:"⚠ ⚠ PROFILAXIA da CONSTIPAÇÃO INDUZIDA POR OPIOIDE", dose:"15-30 mL VO 12/12h (ajustar para 2-3 evacuações/dia normais)", obs:"⚠ Combinar com BISACODIL 5-10 mg VO HS. Esquema clássico opioide → prescrição automática do laxativo."},
{ind:"⚠ Constipação geral", dose:"15-30 mL VO 12/12h ad lib", obs:""},
{ind:"⚠ ⚠ ENCEFALOPATIA HEPÁTICA AGUDA", dose:"30-45 mL VO 6/6h (titular para 2-3 evacuações pastosas/dia)", obs:"⚠ Acidifica lúmen → captura amônia (NH3 → NH4+) → reduz absorção. Alvo: redução amônia + melhora cognitiva. ⚠ Em coma hepático sem VO: pode-se administrar via SNG ou enema (300 mL em 1L água, reter)."},
{ind:"Encefalopatia hepática crônica (profilaxia secundária)", dose:"15-30 mL VO 12/12h", obs:""},
{ind:"Constipação em gestante", dose:"15-30 mL VO 12/12h ad lib", obs:"⚠ 1ª linha em gestação."},
],
ajustes:{
irc:"Sem ajuste",
iht:"Indicada (especialmente em encefalopatia)",
idoso:"Iniciar baixo, ajustar",
gestante:"⚠ B — segura, 1ª linha em gestação",
aleita:"Compatível",
ped:"≥6 meses",
},
mecanismo:"⚠ Dissacarídeo sintético NÃO ABSORVÍVEL no delgado → chega ao cólon → FERMENTADO pela microbiota → ÁCIDOS ORGÂNICOS (acético, propiônico, láctico) → 2 efeitos: (1) OSMÓTICO — puxa água para o lúmen → amolece fezes; (2) ACIDIFICA pH luminal → converte NH3 → NH4+ (não-absorvível) → ↓ amônia sistêmica.",
farmacocin:{
absorc:"⚠ NÃO ABSORVIDO sistêmicamente (vantagem em hepatopata)",
distrib:"Restrito ao lúmen intestinal",
metab:"Bacteriano colônico",
elimin:"Fecal",
meiavida:"N/A — efeito local",
ligacao:"N/A",
},
ef_colats:{
comuns:["⚠ Flatulência (frequente — fermentação)","⚠ Cólica abdominal","Distensão","Náusea (especialmente início)","Sabor muito doce (intolerância — alguns pacientes recusam)","Diarreia se dose excessiva"],
sérios:["⚠ Hipernatremia em uso vigoroso com desidratação","Distúrbio eletrolítico em uso excessivo","Megacólon tóxico em DII (raro)"],
},
interacoes:["⚠ Antiácidos não-absorvíveis (hidróxido de magnésio): podem neutralizar acidificação luminal → reduzir efeito em encefalopatia","Outros laxativos: somatório (intencional ou excessivo)","ATB amplo espectro: podem reduzir flora colônica → ↓ fermentação → ↓ efeito"],
contraindicacoes:["⚠ Galactosemia","⚠ Obstrução intestinal","Apendicite","Hipersensibilidade","⚠ Cautela em DM (contém ~6g açúcar por 10 mL) — não descompensa em uso pontual mas considerar em descompensados"],
monit:["⚠ Resposta clínica (frequência de evacuação)","⚠ Em encefalopatia: nível cognitivo + amônia","Eletrólitos em uso prolongado vigoroso","Glicemia em DM (efeito modesto)"],
gravidez:"B (segura)",
sus:"⚠ REMUME UBS + PFPB",
referencias:["NICE Palliative Care; AGA Constipation; AASLD HE Guidelines."],
},
{id:"med-levomepromazina", classe:"Antipsicótico típico (fenotiazina) — amplo espectro D2/5-HT/H1/M1/α1", grupo:"pali",
nome:"Levomepromazina",
sin:["Neozine","Nozinan","Methotrimeprazine"],
formas:["Comprimido 5 mg, 25 mg, 100 mg","Solução oral 40 mg/mL (gotas)","Ampola 25 mg/mL IM/SC","FARMASUS"],
resumo:"⚠ ⚠ ANTIPSICÓTICO FENOTIAZINA — AMPLO ESPECTRO de receptores (D2 + 5-HT + H1 + M1 + α1). Indicações paliativas: NÁUSEA REFRATÁRIA (multimecanismo — 'limpa-tudo'), DELIRIUM AGITADO refratário, ANSIEDADE-AGITAÇÃO TERMINAL, SEDAÇÃO PROPORCIONAL adjuvante ao midazolam. ⚠ Mais sedativa que haloperidol — útil quando se busca sedação leve. Hipotensão postural significativa.",
dose_rapida:"6,25-25 mg VO/SC 8-24/24h (paliativos)",
doses:[
{ind:"⚠ ⚠ NÁUSEA / VÔMITO REFRATÁRIO em paliativos — espectro amplo", dose:"6,25-12,5 mg VO/SC 12-24/24h ad lib (até 25 mg em refratários)", obs:"⚠ ⚠ 'Limpa-tudo' — útil quando mecanismo de náusea não claro ou multifatorial. Em paciente já em opioide + sem resposta a haloperidol/metoclopramida/ondansetrona."},
{ind:"⚠ DELIRIUM AGITADO refratário em paliativos", dose:"12,5-25 mg VO/SC 8-12/12h + resgate", obs:"⚠ 2ª linha após haloperidol (mais sedativa)."},
{ind:"⚠ AGITAÇÃO TERMINAL", dose:"25-50 mg SC 8-12/12h ou BIC SC 50-100 mg/d", obs:""},
{ind:"⚠ ADJUVANTE em sedação paliativa (com midazolam)", dose:"12,5-25 mg SC 4-6/6h ou BIC SC 50-150 mg/d", obs:"⚠ Combinação útil — soma efeito antiemético + sedativo + analgésico adjuvante."},
{ind:"⚠ Dor refratária (adjuvante)", dose:"6,25-25 mg HS — efeito analgésico adjuvante (modulação cortical)", obs:"Off-label paliativo."},
{ind:"Esquizofrenia (psiquiatria)", dose:"75-300 mg/d ÷ 8/8h", obs:""},
],
ajustes:{
irc:"⚠ Reduzir em IRC",
iht:"⚠ ⚠ Reduzir 50% em IH",
idoso:"⚠ ⚠ Iniciar 6,25 mg. Hipotensão postural acentuada. Black Box demência.",
gestante:"⚠ C — Cautela. Sintomas extrapiramidais neonatais 3º trim.",
aleita:"⚠ Evitar uso crônico",
ped:"Especialista",
},
mecanismo:"⚠ Bloqueio MÚLTIPLO de receptores: D2 (antipsicótico, antiemético), 5-HT2 (antiemético, ansiolítico, analgésico), H1 (sedação, antiemético), M1 muscarínico (antiemético vestibular + anticolinérgico), α1 (hipotensão). Daí efeito amplo em paliativos.",
farmacocin:{
absorc:"VO ~50%",
distrib:"⚠ MUITO AMPLA — lipofílica",
metab:"Hepático",
elimin:"Renal + fecal",
meiavida:"~15-30h",
ligacao:"Alta",
},
ef_colats:{
comuns:["⚠ ⚠ SEDAÇÃO marcada","⚠ HIPOTENSÃO POSTURAL — especialmente no início","Anticolinérgico (boca seca, retenção urinária, visão turva, constipação)","Sintomas extrapiramidais (menos que haloperidol)","Tontura","Sialorreia paradoxal"],
sérios:["⚠ ⚠ HIPOTENSÃO grave em dose IM rápida","⚠ QT longo","⚠ Síndrome neuroléptica maligna (rara)","⚠ AVC + mortalidade em idoso com demência","Discinesia tardia","Reação cutânea grave (raro)","Agranulocitose (raríssima)"],
},
interacoes:["⚠ Outros antipsicóticos, álcool, BZD, opioides: depressão SNC + sedação somativa","⚠ Anti-hipertensivos: hipotensão somativa","⚠ Anticolinérgicos: somatório","⚠ QT-prolongadores","Levodopa: efeitos opostos","IMAO em 14 dias"],
contraindicacoes:["⚠ Coma / depressão SNC importante","⚠ Hipotensão grave","⚠ Parkinson","⚠ QT longo","⚠ Glaucoma ângulo fechado","⚠ HPB com retenção","Hipersensibilidade fenotiazinas","Lactente <2a"],
monit:["PA postural — risco de queda","Sintomas extrapiramidais","ECG em risco","Sintomas anticolinérgicos","Resposta clínica"],
gravidez:"C",
sus:"⚠ FARMASUS",
referencias:["ANCP; EAPC; Twycross R, et al."],
},
{id:"med-lidocaina-patch", classe:"Anestésico local — bloqueador canal Na+ (tópico transdermico)", grupo:"pali",
nome:"Lidocaína Patch 5%",
sin:["Lidoderm","Versatis","Lidopatch","Adesivo de lidocaína"],
formas:["Adesivo 10×14 cm, 5% (700 mg lidocaína)","⚠ NÃO REMUME — particular (custo alto)"],
resumo:"⚠ ⚠ ANALGESIA TÓPICA com lidocaína em formulação adesiva — bloqueia canais de sódio em fibras nervosas SUPERFICIAIS. ⚠ INDICAÇÃO CHAVE: NEURALGIA PÓS-HERPÉTICA (1ª LINHA tópica EAN/NICE) + dor neuropática focal. Vantagem: praticamente SEM absorção sistêmica significativa (<5%) → ZERO sedação, ZERO efeito sistêmico, sem interações. Aplicação até 3 patches simultâneos / 12h por dia / 12h sem adesivo (intervalo).",
dose_rapida:"1-3 adesivos por 12h/dia (12h SEM adesivo)",
doses:[
{ind:"⚠ ⚠ NEURALGIA PÓS-HERPÉTICA — 1ª LINHA tópica (NICE/EAN)", dose:"Aplicar 1-3 adesivos sobre área dolorosa por 12h/dia, seguidos de 12h SEM adesivo. Manter rotina diária.", obs:"⚠ ⚠ Pode CORTAR o adesivo no tamanho da área dolorosa antes de remover proteção. Aplicar em pele íntegra, seca, sem pelos densos. Trocar a cada 12h."},
{ind:"⚠ Dor neuropática focal localizada (cicatriz pós-cirúrgica, neuropatia diabética focal, dor pós-toracotomia)", dose:"1-3 adesivos / 12h /dia", obs:""},
{ind:"⚠ Dor oncológica neuropática SUPERFICIAL focal (paliativo)", dose:"1-3 adesivos / 12h /dia", obs:"⚠ Adjuvante quando opioide + adjuvante sistêmico não controlam dor focal específica."},
{ind:"⚠ Pré-procedimento doloroso (punção, retirada de dreno) — alternativa a creme EMLA", dose:"Aplicar 30-60 min antes do procedimento", obs:"⚠ EMLA (lidocaína+prilocaína) é mais usada para isso. Patch é alternativa em pele extensa."},
],
ajustes:{
irc:"Sem ajuste",
iht:"⚠ Cautela em IH grave (absorção sistêmica pode ↑)",
idoso:"⚠ Excelente perfil em idoso — sem interações sistêmicas",
gestante:"⚠ B — segura",
aleita:"Compatível",
ped:"Não aprovada rotineira <18a",
},
mecanismo:"⚠ Lidocaína em matriz adesiva libera continuamente para a derme onde bloqueia CANAIS DE SÓDIO em fibras nervosas Aδ e C → reduz despolarização ectópica em fibras sensibilizadas (mecanismo central na neuralgia pós-herpética). ⚠ Absorção sistêmica MÍNIMA (<5% da dose total mesmo com 3 patches) — efeito predominantemente local.",
farmacocin:{
absorc:"⚠ <5% absorção sistêmica",
distrib:"Local cutânea",
metab:"Local + hepático CYP3A4/CYP1A2 (fração sistêmica)",
elimin:"Renal",
meiavida:"~2h (fração sistêmica)",
ligacao:"~70%",
},
ef_colats:{
comuns:["Eritema local leve","Prurido","Dermatite por adesivo"],
sérios:["⚠ Toxicidade sistêmica de lidocaína (TEÓRICA — extremamente raro com uso conforme rótulo)","⚠ Reação alérgica ao adesivo"],
},
interacoes:["⚠ Antiarrítmicos classe I (mexiletina, lidocaína IV): cautela em combinação","Cimetidina, propranolol: ↑ lidocaína sistêmica (fração)","Sem interações relevantes em uso normal"],
contraindicacoes:["⚠ Hipersensibilidade a lidocaína / anestésicos amida","Pele lesada / inflamada no local","Hipersensibilidade ao adesivo"],
monit:["Resposta clínica","Estado da pele local"],
gravidez:"B",
sus:"⚠ NÃO disponível SUS — particular (~R$ 50-150/caixa com 5 adesivos)",
referencias:["NICE Neuropathic Pain; EAN Guidelines; ⚠ Cochrane 2014 — moderada evidência."],
},
{id:"med-magnesio-sulfato", classe:"Eletrólito + bloqueador NMDA + estabilizador membrana", grupo:"pali",
nome:"Sulfato de Magnésio",
sin:["MgSO4","Mg sulfato","Magnesium sulfate"],
formas:["Ampola 50% (500 mg/mL) — IV/IM","Ampola 10% — IV (uso pediátrico/diluído)","REMUME UBS uso emergência (eclâmpsia, torsades) — Disponível em hospitais"],
resumo:"⚠ ⚠ SULFATO DE MAGNÉSIO — uso clássico em ECLÂMPSIA + TORSADES DE POINTES + asma grave refratária. ⚠ INDICAÇÃO PALIATIVA MENOS CONHECIDA mas importante: DOR NEUROPÁTICA REFRATÁRIA (efeito NMDA-antagonista similar à cetamina), CÃIBRAS RECORRENTES em fase terminal, hipomagnesemia (causa fadiga, fraqueza, arritmia em paliativos crônicos).",
dose_rapida:"Eclâmpsia: 4-6 g IV em 20 min; Torsades: 2 g IV em 5-15 min; Asma grave: 2 g IV em 20 min; Dor neuropática: 30-50 mg/kg IV em 30 min em ambiente monitorado",
doses:[
{ind:"⚠ ⚠ ECLÂMPSIA / PRÉ-ECLÂMPSIA GRAVE", dose:"Ataque: 4-6 g IV em 100 mL SF em 15-20 min. Manutenção: 1-2 g/h IV contínua × 24h pós-parto. (Esquema Zuspan)", obs:"⚠ Monitorar: reflexos patelares, FR, diurese, Mg sérico (alvo 4-7 mEq/L). Antídoto: gluconato cálcio 1 g IV se toxicidade."},
{ind:"⚠ ⚠ TORSADES DE POINTES (TV polimórfica com QT longo)", dose:"2 g IV em 5-15 min, podendo repetir. Manutenção: 1-2 g/h IV", obs:"⚠ ⚠ 1ª linha INDEPENDENTE DE MAGNESEMIA — sempre tentar."},
{ind:"⚠ ASMA GRAVE refratária a broncodilatador + corticoide", dose:"2 g IV em 100 mL SF em 20 min (dose única)", obs:"⚠ Quando crise não responde a salbutamol + ipratrópio + corticoide. Em criança 25-50 mg/kg IV."},
{ind:"⚠ ⚠ DOR NEUROPÁTICA REFRATÁRIA (off-label paliativo) — adjuvante", dose:"30-50 mg/kg IV em 30-60 min (dose única ou seriada) em ambiente MONITORADO", obs:"⚠ Mecanismo NMDA-antagonista (similar à cetamina). Considerar quando rotação opioide, gabapentinoide, ADT não controlam. Necessita monitor cardíaco."},
{ind:"⚠ CÃIBRAS RECORRENTES em paliativos (fase terminal)", dose:"VO: óxido de magnésio 200-400 mg 1-2×/d ad lib (alternativa); IV se grave: 2 g IV diluído", obs:""},
{ind:"⚠ Hipomagnesemia sintomática (fraqueza, cãibra, arritmia, em paliativos crônicos)", dose:"2-4 g IV em 4-12h (conforme severidade)", obs:""},
{ind:"Constipação (laxativo osmótico, dose única)", dose:"VO 10-30 g de sal de Epsom (sulfato de magnésio) diluído em água", obs:"⚠ Não rotineiro paliativo — preferir lactulose. Para limpeza intestinal."},
],
ajustes:{
irc:"⚠ ⚠ TFG <30: ⚠ ⚠ USAR COM EXTREMA CAUTELA — acúmulo rapidamente tóxico. Reduzir dose 50% E monitorar Mg sérico + reflexos patelares.",
iht:"Sem ajuste específico",
idoso:"⚠ Verificar função renal antes — risco toxicidade ↑",
gestante:"⚠ B — usado AMPLAMENTE em eclâmpsia",
aleita:"Compatível",
ped:"Dose por peso; <2a cautela",
},
mecanismo:"⚠ MÚLTIPLOS: (1) BLOQUEIO DO CANAL DE CÁLCIO L-TIPO em músculo liso → vasodilatação, broncodilatação, ↓ contratilidade uterina; (2) ANTAGONISMO NMDA — competidor do bloqueio voltagem-dependente → ação antinociceptiva neuropática; (3) ESTABILIZAÇÃO DA MEMBRANA — repolariza miocárdio (efeito antiarrítmico em torsades); (4) ↓ liberação de acetilcolina na placa motora → relaxamento muscular esquelético; (5) Vasodilatador cerebral → efeito anticonvulsivante em eclâmpsia.",
farmacocin:{
absorc:"IV imediata; VO ~30% (forma sulfato é laxativa); IM ~100% mas dolorosa",
distrib:"Compartimento extracelular + ossos (30%)",
metab:"Não metabolizado",
elimin:"⚠ Renal — totalmente filtrado e reabsorvido conforme nível",
meiavida:"~4-6h (Mg sérico) — depende de função renal",
ligacao:"~30%",
},
ef_colats:{
comuns:["Calor / rubor durante infusão (vasodilatação)","Náusea","Sonolência","Hipotensão leve","Visão turva (em altas doses)"],
sérios:["⚠ ⚠ ⚠ TOXICIDADE POR HIPERMAGNESEMIA — sequencialmente: perda reflexos patelares (Mg 4-7 mEq/L), depressão respiratória (5-7), bloqueio AV (10), parada cardiorrespiratória (>12). ⚠ ANTÍDOTO: GLUCONATO DE CÁLCIO 1-2 g IV.","⚠ Parada respiratória (em sobredose, especialmente em IRC sem ajuste)","Bradicardia, hipotensão grave","Hipocalcemia secundária"],
},
interacoes:["⚠ ⚠ Bloqueadores neuromusculares (succinilcolina, rocurônio): potencializam — paralisia prolongada","⚠ Aminoglicosídeos: somatório bloqueio neuromuscular","⚠ Antagonistas canal cálcio (nifedipino): hipotensão grave","Digoxina: ↑ toxicidade","Quinolonas, tetraciclinas: ↓ absorção VO (separar 2h)","Diuréticos: ↑ perda magnésio"],
contraindicacoes:["⚠ ⚠ TFG <30 (relativa — cautela extrema, dose reduzida)","⚠ Bloqueio AV de alto grau","Hipermagnesemia preexistente","Hipersensibilidade","⚠ Miastenia gravis (bloqueio neuromuscular potencializa)"],
monit:["⚠ ⚠ Reflexos patelares (PRESENTES = seguro; ABOLIDOS = ↓ ou interromper)","⚠ FR (≥12 ipm)","⚠ Diurese (≥30 mL/h)","Mg sérico se uso prolongado / IRC","ECG em altas doses / IRC"],
gravidez:"B (uso amplamente seguro em eclâmpsia)",
sus:"⚠ REMUME (uso interno emergência) — disponível em UBS/hospital",
referencias:["⚠ Magpie Trial (eclâmpsia); GINA Asthma; AHA Torsades; ⚠ Cochrane — Mg em dor neuropática."],
},
{id:"med-metilnaltrexona", classe:"Antagonista μ-opioide periférico (PAMORA)", grupo:"pali",
nome:"Metilnaltrexona",
sin:["Relistor"],
formas:["Ampola/seringa preenchida 8 mg/0,4 mL e 12 mg/0,6 mL SC","Comprimido 150 mg VO (uso menos comum, mais em CIO não-câncer)","⚠ NÃO REMUME — particular (custo MUITO ALTO)"],
resumo:"⚠ ⚠ ANTAGONISTA μ-OPIOIDE EXCLUSIVAMENTE PERIFÉRICO (PAMORA — peripheral-acting μ opioid receptor antagonist). ⚠ AMÔNIO QUATERNÁRIO — NÃO ATRAVESSA BHE → ⚠ NÃO REVERTE ANALGESIA (vantagem crítica vs naloxona). ⚠ INDICAÇÃO ÚNICA: CONSTIPAÇÃO INDUZIDA POR OPIOIDE (CIO) REFRATÁRIA a laxativos convencionais (bisacodil + lactulose otimizados ≥3 dias). Resposta rápida — frequentemente evacuação em ≤4h da injeção SC. ⚠ Caro, restrito.",
dose_rapida:"Peso 38-61 kg: 8 mg SC; 62-114 kg: 12 mg SC. Frequência: cada 48h conforme necessidade (não diariamente).",
doses:[
{ind:"⚠ ⚠ CONSTIPAÇÃO INDUZIDA POR OPIOIDE REFRATÁRIA — em paciente com câncer avançado, paliativo", dose:"⚠ Por peso: <38 kg: 0,15 mg/kg SC; 38-61 kg: 8 mg SC; 62-114 kg: 12 mg SC; >114 kg: 0,15 mg/kg SC. Frequência: 1 dose, podendo repetir a cada 48h conforme resposta", obs:"⚠ INDICAR APENAS quando esquema convencional (bisacodil 10 mg + lactulose 30 mL 12/12h) por ≥3 dias falhou. ⚠ Avaliar fecaloma antes — desimpactação manual se necessário (metilnaltrexona não desimpacta)."},
{ind:"⚠ CIO em paciente NÃO oncológico (dor crônica não-câncer)", dose:"Comprimido VO 450 mg/d (3× 150 mg) — uso ambulatorial menos comum no Brasil", obs:""},
],
ajustes:{
irc:"⚠ TFG <30: reduzir dose pela METADE",
iht:"Sem ajuste rotineiro (não metabolismo hepático significativo)",
idoso:"⚠ Iniciar pela faixa de peso correspondente; reavaliar resposta",
gestante:"⚠ B — uso quando benefício > risco",
aleita:"Cautela",
ped:"Não aprovada rotineira",
},
mecanismo:"⚠ ANTAGONISTA SELETIVO dos RECEPTORES μ-OPIOIDES PERIFÉRICOS (intestino + outros sítios periféricos). ⚠ ⚠ AMÔNIO QUATERNÁRIO (carga elétrica) → NÃO ATRAVESSA BHE → ⚠ NÃO ANTAGONIZA O EFEITO ANALGÉSICO CENTRAL do opioide. Bloqueia μ no plexo mioentérico → restaura motilidade intestinal sem alterar analgesia.",
farmacocin:{
absorc:"SC ~82%; VO baixa (~7%, mas é a dose VO ajustada)",
distrib:"⚠ Periférica exclusivamente (não BHE)",
metab:"Mínimo hepático",
elimin:"Renal (50% inalterada) + fecal",
meiavida:"~8h",
ligacao:"~11-15%",
},
ef_colats:{
comuns:["⚠ Cólica abdominal","Flatulência","Náusea","Diarreia (após primeira dose — efeito)","Hiperidrose","Tontura"],
sérios:["⚠ ⚠ PERFURAÇÃO INTESTINAL — relatos em pacientes com lesão da parede intestinal (câncer GI infiltrativo, DII em atividade, isquemia intestinal, diverticulite ativa, úlcera péptica grave). ⚠ ⚠ NÃO USAR se houver suspeita de obstrução mecânica ou lesão da parede.","⚠ Síndrome de abstinência opioide periférica (raro em SC; mais em VO)","Hipotensão"],
},
interacoes:["⚠ Outros antagonistas opioides (naloxona, naltrexona): somatório — não usar junto","Cautela com outros laxativos: efeito não somativo (mecanismo diferente)"],
contraindicacoes:["⚠ ⚠ OBSTRUÇÃO INTESTINAL MECÂNICA conhecida ou suspeita","⚠ Lesão GI: úlcera ativa, diverticulite, DII grave em atividade, isquemia intestinal, câncer GI infiltrando parede com risco perfuração","Hipersensibilidade","Cirurgia GI recente (relativa)"],
monit:["⚠ ⚠ Evolução clínica para SINAIS DE PERFURAÇÃO (dor abdominal súbita, defesa, sinais peritoneais) — interromper IMEDIATAMENTE e avaliar","Resposta laxativa","Função renal"],
gravidez:"B",
sus:"⚠ ⚠ NÃO REMUME — particular (custo alto, ~R$ 600-1000/dose)",
referencias:["NICE Palliative Care; APM Guidelines; ⚠ FDA Warning Perforation 2010."],
},
{id:"med-metoclopramida", classe:"Procinético + antiemético (D2 antagonista + 5-HT4 agonista)", grupo:"pali",
nome:"Metoclopramida",
sin:["Plasil","Eucil","Plamet"],
formas:["Comprimido 10 mg","Solução oral 4 mg/mL","Ampola 5 mg/mL (2 mL) IM/IV/SC","REMUME — UBS dispensação direta"],
resumo:"⚠ DUPLO MECANISMO — (1) ANTAGONISTA D2 (CTZ central — antiemético) + (2) AGONISTA 5-HT4 + sensibiliza ACh em plexo mioentérico = PROCINÉTICO. Indicações: NÁUSEA por ESTASE GÁSTRICA + náusea química leve + dispepsia. ⚠ ⚠ CONTRAINDICADA EM OBSTRUÇÃO INTESTINAL MECÂNICA (procinético piora). ⚠ Extrapiramidais — limitar uso prolongado (FDA Warning ≤12 sem).",
dose_rapida:"10 mg VO/IV/SC 6-8/8h (máx 30-40 mg/d)",
doses:[
{ind:"⚠ NÁUSEA POR ESTASE GÁSTRICA / dispepsia funcional / gastroparesia", dose:"10 mg VO 6-8/8h, idealmente 30 min ANTES DAS REFEIÇÕES + HS", obs:"⚠ ⚠ 1ª LINHA em estase. Procinético + antiemético."},
{ind:"⚠ Náusea química leve / opioide-induzida", dose:"10 mg VO/SC 6-8/8h ad lib", obs:"Alternativa ao haloperidol em CTZ."},
{ind:"⚠ Náusea pós-operatória / pós-quimioterapia (em combinação)", dose:"10 mg IV antes do procedimento", obs:"Combinação com ondansetrona + dexa em quimio altamente emetogênica."},
{ind:"⚠ Enxaqueca com vômito (uso adjunto IV)", dose:"10 mg IV", obs:"Pode reduzir frequência."},
{ind:"⚠ Galactagogo (off-label, raro)", dose:"10 mg 8/8h × dias", obs:""},
],
ajustes:{
irc:"⚠ TFG <40: reduzir 50%",
iht:"⚠ Reduzir 50% em IH",
idoso:"⚠ ⚠ Reduzir dose. Sintomas extrapiramidais + sedação mais frequentes.",
gestante:"⚠ B — segura. Útil em hiperêmese gravídica leve.",
aleita:"Compatível",
ped:"⚠ ⚠ EVITAR <1 ano (risco extrapiramidal grave). Após 1a: cautela.",
},
mecanismo:"(1) ANTAGONISTA D2 na CTZ (antiemético central). (2) AGONISTA 5-HT4 + sensibiliza receptores muscarínicos do plexo mioentérico → ↑ liberação de ACh → ↑ tônus esfíncter esofágico inferior + ↑ contratilidade gástrica + relaxa piloro → PROCINÉTICO.",
farmacocin:{
absorc:"VO ~80%",
distrib:"Ampla, atravessa BHE",
metab:"Hepático",
elimin:"Renal predominante",
meiavida:"~5-6h",
ligacao:"~30%",
},
ef_colats:{
comuns:["⚠ Sonolência","⚠ Sintomas EXTRAPIRAMIDAIS — distonia aguda (especialmente em criança/jovem; crise oculogírica)","Fadiga","Diarreia","Cefaleia"],
sérios:["⚠ ⚠ DISCINESIA TARDIA em uso prolongado >12 sem (FDA Warning — limitar)","⚠ ⚠ DISTONIA AGUDA / CRISE OCULOGÍRICA — tratar com BIPERIDENO 5 mg IM","⚠ Síndrome neuroléptica maligna (raro)","⚠ Hiperprolactinemia → galactorreia, ginecomastia, hipogonadismo","Hipotensão (em IV rápido)","Metahemoglobinemia em recém-nascido"],
},
interacoes:["⚠ Outros antipsicóticos: somatório extrapiramidal","⚠ Anticolinérgicos: REDUZEM efeito (antagonismo)","⚠ Opioides: somatório sedação","⚠ ⚠ ISRS/IMAO + metoclopramida: risco síndrome serotoninérgica","Levodopa: efeito antagônico","Digoxina: ↓ digoxina","Ciclosporina: ↑ absorção"],
contraindicacoes:["⚠ ⚠ OBSTRUÇÃO INTESTINAL MECÂNICA","⚠ Perfuração / hemorragia GI","⚠ Convulsão de história","⚠ Feocromocitoma","⚠ Parkinson","Hipersensibilidade","Lactente <1a","IMAO em 14 dias"],
monit:["⚠ Sintomas extrapiramidais — orientar paciente / família","Discinesia tardia em uso prolongado","Resposta clínica"],
gravidez:"B",
sus:"⚠ REMUME — UBS dispensação direta",
referencias:["FDA Warning DT 2009; ANCP; PCDT-MS."],
},
{id:"med-octreotida", classe:"Análogo da somatostatina — antissecretor", grupo:"pali",
nome:"Octreotida",
sin:["Sandostatin","Octreolan","Mioctin"],
formas:["Ampola 50 mcg, 100 mcg, 500 mcg SC/IV","Sandostatin LAR (depot) 10/20/30 mg IM mensal — ⚠ uso oncológico de neuroendócrinos","⚠ CEAF (PCDT-MS Acromegalia / tumores neuroendócrinos / variz esofágica) — fora dessas indicações: particular"],
resumo:"⚠ ⚠ ANÁLOGO SINTÉTICO DA SOMATOSTATINA — potente INIBIDOR DA SECREÇÃO GI/pancreática + inibe hormônios GI/hipofisários. ⚠ ⚠ INDICAÇÃO PALIATIVA CRÍTICA: OBSTRUÇÃO INTESTINAL MALIGNA INOPERÁVEL — REDUZ VOLUME GÁSTRICO/INTESTINAL, REDUZ NÁUSEA E VÔMITO, PODE EVITAR SNG. Também: fístulas digestivas alto débito, diarreia secretora (carcinoide, VIPoma), variz esofágica sangrante (ponte para endoscopia). ⚠ CARO — restrito.",
dose_rapida:"100-300 mcg SC 8/8h OU infusão contínua SC 300-900 mcg/24h",
doses:[
{ind:"⚠ ⚠ OBSTRUÇÃO INTESTINAL MALIGNA INOPERÁVEL", dose:"100-300 mcg SC 8/8h (iniciar 100 mcg). Pode-se infundir contínua SC 300-900 mcg/24h", obs:"⚠ Combinar com DEXAMETASONA + HIOSCINA BUTILBROMETO + ANALGESIA + ANTIEMÉTICO (haloperidol). ⚠ ⚠ NÃO METOCLOPRAMIDA se obstrução completa (procinético contraindicado). 5 dias de teste; se sem resposta — suspender."},
{ind:"⚠ Fístula digestiva alto débito (paliativa)", dose:"50-300 mcg SC 8/8h ou contínua", obs:""},
{ind:"⚠ Diarreia secretora — carcinoide, VIPoma, ileostomia alta débito", dose:"100-600 mcg/d SC ÷ 2-3 doses; titular conforme resposta", obs:""},
{ind:"⚠ Variz esofágica sangrante (emergência, ponte para endoscopia)", dose:"50 mcg IV bolus, depois infusão 25-50 mcg/h IV × 3-5 dias", obs:""},
{ind:"⚠ Acromegalia / tumores neuroendócrinos (uso oncológico)", dose:"Sandostatin LAR 10-30 mg IM 1×/mês", obs:"⚠ Endocrinologia / oncologia. CEAF com PCDT."},
{ind:"⚠ Pancreatite por hipertrigliceridemia / fístula pancreática", dose:"100 mcg SC 8/8h", obs:"Uso restrito; evidência limitada."},
],
ajustes:{
irc:"⚠ TFG <30: reduzir 50%",
iht:"⚠ Reduzir dose",
idoso:"Sem ajuste rotineiro mas iniciar baixo",
gestante:"⚠ B — uso quando benefício > risco",
aleita:"Cautela",
ped:"Uso restrito, dose por peso",
},
mecanismo:"⚠ Análogo sintético da SOMATOSTATINA com meia-vida prolongada. Inibe liberação de GH, TSH, glucagon, insulina, gastrina, VIP, secretina, motilina, polipeptídeo pancreático. Reduz secreção GI, motilidade intestinal, fluxo esplâncnico, pressão portal.",
farmacocin:{
absorc:"SC ~100%; VO degradada",
distrib:"Periférica",
metab:"Hepático parcial",
elimin:"Renal + biliar",
meiavida:"~1.5-2h (SC); LAR 30 dias (depot)",
ligacao:"~65%",
},
ef_colats:{
comuns:["⚠ DOR no local da injeção SC","⚠ COLELITÍASE (uso prolongado — reduz contração da vesícula)","Náusea (paradoxal, no início)","Diarreia ou constipação","Hiperglicemia (inibe insulina)","Hipoglicemia em diabético (inibe glucagon)","Disgeusia","Esteatorreia (uso crônico)"],
sérios:["⚠ Colelitíase / colecistite (15-30% em uso prolongado)","⚠ Pancreatite","Bradicardia / bloqueio AV","Alterações tireoide","Hepatite","Choque cardiogênico (raro)","Reações alérgicas"],
},
interacoes:["⚠ Insulina, hipoglicemiantes orais: ajustar — controle glicêmico variável","Diuréticos: hiponatremia somativa","Ciclosporina: reduz nível","Beta-bloqueadores: bradicardia somativa","Bromocriptina: ↑ nível"],
contraindicacoes:["Hipersensibilidade","Cautela em colelitíase prévia","Cautela em DM (variação glicêmica)"],
monit:["⚠ Glicemia (especialmente diabético)","Função tireoidiana em uso prolongado","USG vias biliares se uso >6m","Resposta clínica (volume drenagem, sintomas)"],
gravidez:"B",
sus:"⚠ CEAF (PCDT Acromegalia / Neuroendócrinos / Hemorragia varizes) — fora destas indicações: particular",
referencias:["NICE Palliative Care; APM Guidelines; ⚠ PCDT-MS Acromegalia."],
},
{id:"med-ondansetrona", classe:"Antiemético — antagonista 5-HT3", grupo:"pali",
nome:"Ondansetrona",
sin:["Zofran","Vonau","Nausedron","Ondansetron"],
formas:["Comprimido 4 mg, 8 mg","Comprimido sublingual / orodispersível 4 mg, 8 mg","Solução oral 4 mg/5 mL","Ampola 2 mg/mL (2 mL, 4 mL) IM/IV/SC","REMUME — UBS dispensação direta (algumas SES); FARMASUS"],
resumo:"⚠ ANTAGONISTA 5-HT3 — antiemético poderoso. Indicações principais: NÁUSEA POR QUIMIO ALTAMENTE EMETOGÊNICA, pós-op, gestação (off-label classe B), náusea oncológica refratária. ⚠ DESVANTAGENS: causa CONSTIPAÇÃO, QT longo (dose alta IV), cefaleia. ⚠ Não atua bem em náusea por ESTASE (não é procinético) — combinar com metoclopramida.",
dose_rapida:"4-8 mg VO/SL/IV/SC 8/8h",
doses:[
{ind:"⚠ NÁUSEA / VÔMITO em QUIMIOTERAPIA altamente emetogênica (com dexa)", dose:"8 mg IV antes da quimio + 8 mg VO 12/12h × 3-5d", obs:"Combinação com dexametasona + aprepitanto em altamente emetogênica."},
{ind:"⚠ NÁUSEA pós-op", dose:"4-8 mg IV/IM (pré ou intra-op)", obs:""},
{ind:"⚠ NÁUSEA EM PALIATIVOS (refratária ou por mecanismo serotoninérgico — quimio recente, radioterapia)", dose:"4-8 mg VO/SC 8/8h", obs:"⚠ Útil em refratários ou em vômito após quimio/radioterapia. NÃO escolha 1ª em CTZ — preferir haloperidol."},
{ind:"⚠ HIPERÊMESE GRAVÍDICA refratária", dose:"4-8 mg VO/SL 8/8h", obs:"⚠ Após falha de outras (metoclopramida, bromoprida). FDA atualizou — segurança 1º trim: dado misto mas baixo risco absoluto. Decisão compartilhada."},
{ind:"Gastroenterite aguda em pediatria (uso restrito)", dose:"4-8 mg dose única", obs:"Reduz vômito, permite hidratação oral."},
],
ajustes:{
irc:"Sem ajuste rotineiro",
iht:"⚠ Reduzir em IH grave (Child C) — máx 8 mg/d",
idoso:"Sem ajuste rotineiro — cuidado QT",
gestante:"⚠ B — uso comum. Recente sinal de fenda palatina 1º trim (modesto, controverso) — preferir outras 1ª linha (metoclopramida, prometazina); usar se refratária.",
aleita:"Compatível",
ped:"⚠ Pode usar em ped. Considerar dose por peso.",
},
mecanismo:"⚠ ANTAGONISTA 5-HT3 — receptor seronérgico em CTZ central + aferentes vagais GI. Bloqueia náusea induzida por liberação de 5-HT (quimio, radio, distensão GI).",
farmacocin:{
absorc:"VO ~60%",
distrib:"Ampla",
metab:"Hepático CYP3A4, CYP2D6",
elimin:"Renal",
meiavida:"~3-6h",
ligacao:"~70-76%",
},
ef_colats:{
comuns:["⚠ CONSTIPAÇÃO (frequente — relevante em paciente com opioide)","Cefaleia","Fadiga","Tontura","Hipotensão leve","Boca seca","Rubor"],
sérios:["⚠ ⚠ QT LONGO — DOSE-DEPENDENTE. Em IV >16 mg dose única: FDA WARNING. Em paciente cardíaco / eletrólitos baixos / outros QT-prolongadores: cuidado","⚠ Síndrome serotoninérgica (com SSRIs, tramadol, IMAO)","Reação alérgica","Hepatotoxicidade rara"],
},
interacoes:["⚠ ⚠ QT-prolongadores: ↑ TORSADES (metadona, antiarrítmicos, claritro, azólicos, haloperidol IV)","⚠ Tramadol / ISRS / IMAO: síndrome serotoninérgica","Inibidores CYP3A4 (cetoconazol): ↑ ondansetrona","Indutores CYP3A4 (rifampicina, fenitoína, carbamazepina): ↓","Apomorfina: hipotensão grave (CI)"],
contraindicacoes:["⚠ QT longo congênito","⚠ Uso simultâneo com apomorfina","Hipersensibilidade","Síndrome serotoninérgica de risco (relativa)"],
monit:["⚠ ECG basal em risco / dose IV alta","Eletrólitos (K, Mg)","Constipação","Resposta clínica"],
gravidez:"B",
sus:"⚠ REMUME — UBS dispensação direta (algumas SES) + FARMASUS",
referencias:["⚠ FDA QT Warning 2012; NCCN Antiemesis; ASCO; ANCP."],
},
);
