/* ===========================================================
   VOVÔMINIC EMERGÊNCIA — meds/psiq.js
   12 medicações
   Grupos: psiq
   =========================================================== */

MEDICACOES.push(

/* ============== PSIQ (12) ============== */

{id:"med-amitriptilina", contexto:["pa","ubs"], classe:"Antidepressivo Tricíclico (ADT)", grupo:"psiq",
nome:"Amitriptilina",
sin:["Tryptanol","Amytril","Limbitrol"],
formas:["Comprimido 25 mg, 75 mg","REMUME — FARMASUS (controle especial C1)"],
resumo:"⚠ ADT clássico — eficácia ANTIDEPRESSIVA equivalente a ISRS porém TOLERABILIDADE PIOR (anticolinérgicos, sedação, ganho de peso) + ⚠ LETAL EM SUPERDOSE (cardiotoxicidade). Hoje USO PRINCIPAL em DOSES BAIXAS para DOR NEUROPÁTICA, fibromialgia, profilaxia de migrânea, insônia. ⚠ EVITAR em idoso (Beers).",
dose_rapida:"DEPRESSÃO: 75-150 mg/d; NEURALGIA/CEFALEIA: 10-50 mg HS",
doses:[
{ind:"⚠ DOR NEUROPÁTICA (diabética, pós-herpética, central)", dose:"10-25 mg HS, titular a 25-75 mg HS", obs:"⚠ Indicação MAIS COMUM hoje. Eficácia comprovada. Dose baixa, efeito independente do antidepressivo."},
{ind:"⚠ Profilaxia de migrânea / cefaleia tensional crônica", dose:"10-25 mg HS, titular a 25-75 mg HS", obs:""},
{ind:"⚠ Fibromialgia", dose:"10-25 mg HS, titular a 25-50 mg HS", obs:"+ exercício aeróbico, TCC."},
{ind:"⚠ Insônia + dor neuropática", dose:"10-25 mg HS", obs:""},
{ind:"Depressão maior (uso histórico)", dose:"75-150 mg/d ÷ 12/12h ou HS. Máx 300 mg/d (psiquiatria)", obs:"⚠ Atualmente ISRS são preferidos. ADT reservado para depressão refratária ou em paciente com indicação adicional."},
{ind:"Enurese noturna em criança", dose:"10-25 mg HS", obs:"Eficaz mas EVITAR — tóxico em superdose, criança vulnerável."},
],
ajustes:{
irc:"Sem ajuste em IRC leve. Cautela em grave.",
iht:"Reduzir 50% em IH",
idoso:"⚠ ⚠ EVITAR — Beers Criteria — anticolinérgico forte, sedação, quedas, retenção, confusão. Se inevitável: 10-25 mg HS.",
gestante:"⚠ C — usar se benefício > risco",
aleita:"Compatível em dose baixa",
ped:"⚠ ≥12a para enurese. ⚠ MUITO TÓXICO EM SUPERDOSE — ocultar de criança/adolescente com ideação suicida.",
},
mecanismo:"INIBE recaptação de SEROTONINA e NORADRENALINA + BLOQUEIA receptores muscarínicos, H1, α1 → explica eficácia + efeitos colaterais. METABÓLITO ATIVO nortriptilina.",
farmacocin:{
absorc:"VO ~50%",
distrib:"Ampla, lipofílico",
metab:"Hepático (CYP2D6, CYP3A4, CYP1A2)",
elimin:"Renal",
meiavida:"~10-26h (variável)",
ligacao:"~95%",
},
ef_colats:{
comuns:["⚠ SEDAÇÃO (forte)","⚠ ANTICOLINÉRGICO: boca seca, constipação, retenção urinária, visão turva, midríase, taquicardia","⚠ GANHO DE PESO","Hipotensão ortostática","Disfunção sexual","Tremor","Sudorese"],
sérios:["⚠ ⚠ CARDIOTOXICIDADE EM SUPERDOSE — bloqueio cardíaco, arritmia ventricular, prolongamento QRS, parada cardíaca — DOSE LETAL BAIXA (10-30 mg/kg) — superdose com 1-2 caixas pode matar","⚠ Prolongamento QT","⚠ Quedas em idoso","⚠ Glaucoma de ângulo fechado","⚠ Retenção urinária em HPB","⚠ Síndrome confusional / delirium","⚠ Aumento ideação suicida em <25a","Síndrome serotoninérgica (com IMAO)","Hiperglicemia","Mania em bipolar"],
},
interacoes:["⚠ IMAO: SD SEROTONINÉRGICA","Anticolinérgicos: somatório (oxibutinina, anti-histamínicos, antipsicóticos)","ISRS (especialmente fluoxetina, paroxetina — inibe CYP2D6): ↑ ADT","QT-prolongadores","Anti-hipertensivos: hipotensão","Tramadol: sd. serotoninérgica + convulsão","Álcool, BZD: sedação somativa"],
contraindicacoes:["⚠ Pós-IAM recente","⚠ Bloqueio AV avançado, QT longo","⚠ Glaucoma ângulo fechado","⚠ HPB com retenção","⚠ Mania ativa","IMAO em 14 dias","⚠ Idoso (relativa)","⚠ Risco SUICIDA — tóxico em superdose, fornecer pequenas quantidades"],
monit:["⚠ ECG basal e em titulação (QT, QRS)","Sintomas anticolinérgicos","Peso","Suicidalidade <25a","Nível sérico se disponível (terapêutico 80-200 ng/mL)"],
gravidez:"C",
sus:"⚠ REMUME — FARMASUS.",
referencias:["NICE Neuropathic Pain; APA; AAFP."],
},
{id:"med-bupropiona", contexto:["pa","ubs"], classe:"Antidepressivo atípico — inibidor de recaptação de noradrenalina e dopamina", grupo:"psiq",
nome:"Bupropiona",
sin:["Zyban","Wellbutrin","Bup","Zetron"],
formas:["Comprimido 150 mg, 300 mg (SR / XL — liberação prolongada)","Comprimido 75 mg IR","REMUME — FARMASUS / Ambulatório de Saúde Mental (PNCT)"],
resumo:"⚠ ANTIDEPRESSIVO ATÍPICO — INIBE RECAPTAÇÃO NA + DOPAMINA. INDICAÇÕES DIFERENCIADAS: cessação tabágica (CENTRAL — PNCT), depressão com fadiga / perda de motivação, depressão com disfunção sexual induzida por ISRS (substituir ou adicionar). ⚠ NÃO É BOA EM ANSIEDADE (pode piorar). ⚠ REDUZ LIMIAR CONVULSIVO — não usar em epilepsia, bulimia, anorexia, abstinência alcoólica.",
dose_rapida:"150-300 mg/d (SR/XL)",
doses:[
{ind:"⚠ ⚠ CESSAÇÃO DO TABAGISMO (PNCT — Brasil)", dose:"150 mg/d × 3 dias, depois 150 mg 12/12h × 7-12 sem. PARAR de fumar na 2ª semana", obs:"⚠ INDICAÇÃO CENTRAL no SUS. Início 1 sem ANTES da data alvo. Combinar com adesivos de nicotina é aceitável."},
{ind:"⚠ Depressão maior", dose:"150 mg/d × 4-7 dias, depois 300 mg/d (SR ÷ 12/12h OU XL 1×/d). Máx 450 mg/d", obs:""},
{ind:"⚠ Depressão com fadiga / hipersomnia / perda de motivação", dose:"150-300 mg/d", obs:"Boa para depressão atípica com fadiga."},
{ind:"⚠ Disfunção sexual induzida por ISRS", dose:"150-300 mg/d adicionado ou substituindo ISRS", obs:""},
{ind:"⚠ TDAH adulto (off-label, alternativa em paciente com contraindicação a estimulante)", dose:"150-300 mg/d", obs:""},
],
ajustes:{
irc:"TFG <50: 150 mg/d (cautela)",
iht:"Reduzir dose em IH",
idoso:"⚠ Iniciar 150 mg/d, monitor sintomas neuropsiquiátricos",
gestante:"⚠ C — Dados limitados. Sertralina/fluoxetina preferidas.",
aleita:"Cautela — pequena concentração no leite",
ped:"⚠ ≥18a (não aprovada em <18a)",
},
mecanismo:"INIBE recaptação de NORADRENALINA + DOPAMINA. SEM efeito serotoninérgico significativo. Sem efeitos colaterais sexuais típicos do ISRS.",
farmacocin:{
absorc:"VO ~85%",
distrib:"Ampla",
metab:"Hepático CYP2B6 → metabólito ativo hidroxibupropiona",
elimin:"Renal",
meiavida:"~21h (forma SR) — 1-2×/d",
ligacao:"~84%",
},
ef_colats:{
comuns:["⚠ INSÔNIA (frequente — tomar pela manhã/tarde, NÃO HS)","Boca seca","Cefaleia","Náusea","Tremor","Sudorese","Constipação","Ansiedade leve, agitação","SEM disfunção sexual significativa"],
sérios:["⚠ ⚠ CONVULSÕES — REDUZ LIMIAR (dose-dependente, ~0,1% a 300 mg/d, ~0,4% a 450 mg/d)","Hipertensão arterial","Síndrome neuropsiquiátrica (mudanças de humor, agitação, comportamento) — FDA warning","Mania em bipolar","Reações de hipersensibilidade graves (raras)","Suicidalidade <25a"],
},
interacoes:["⚠ IMAO","⚠ MEDICAÇÕES QUE REDUZEM LIMIAR CONVULSIVO: tramadol (ABSOLUTAMENTE EVITAR — convulsões reportadas), antipsicóticos, ADT","Levodopa, agonistas dopaminérgicos: somatório","Inibidores/indutores CYP2B6","Álcool (em abstinência — convulsão)"],
contraindicacoes:["⚠ ⚠ EPILEPSIA / convulsões prévias","⚠ BULIMIA / ANOREXIA (alto risco convulsão por distúrbios eletrolíticos)","⚠ ABSTINÊNCIA ALCOÓLICA / BZD recente","⚠ TCE recente / tumor SNC","IMAO 14 dias","⚠ Tramadol concomitante (relativa — alta risco convulsão)","Hipersensibilidade","Mania ativa"],
monit:["⚠ História de convulsão / risco","Pressão arterial","Sintomas neuropsiquiátricos","Sucesso em cessação tabágica"],
gravidez:"C",
sus:"⚠ REMUME — Ambulatório de Saúde Mental (PNCT — Programa Nacional de Controle Tabagismo) + FARMASUS",
referencias:["⚠ PNCT-MS; APA; FDA Neuropsychiatric Warning."],
},
{id:"med-citalopram", contexto:["pa","ubs"], classe:"ISRS — inibidor seletivo de recaptação de serotonina", grupo:"psiq",
nome:"Citalopram",
sin:["Cipramil","Citta","Procimax"],
formas:["Comprimido 20 mg, 40 mg","Solução oral 40 mg/mL","FARMASUS"],
resumo:"⚠ ISRS racêmico (predecessor do escitalopram). Mesmo perfil de QT mas dose máx 40 mg/d (20 mg/d em idoso) — FDA Warning 2012. Atualmente PREFERIDO o escitalopram (enantiômero S puro, dobro da potência por mg).",
dose_rapida:"20-40 mg/d (idoso 10-20 mg/d)",
doses:[
{ind:"Depressão maior", dose:"20 mg/d × 1 sem, depois 20-40 mg/d", obs:"⚠ MÁX 40 mg/d (20 mg em idoso, >60a, IH, CYP2C19 lento). FDA QT Warning."},
{ind:"TAG, pânico, TOC, fobia social", dose:"10-40 mg/d", obs:""},
],
ajustes:{
irc:"TFG <20: cautela",
iht:"⚠ MÁX 20 mg/d",
idoso:"⚠ ⚠ MÁX 20 mg/d — risco QT",
gestante:"C",
aleita:"Compatível",
ped:"Acompanhamento psiquiátrico",
},
mecanismo:"INIBE recaptação 5-HT. Racêmico (R+S) — apenas S é ativo (escitalopram puro = mais eficaz por mg).",
farmacocin:{
absorc:"VO ~80%",
distrib:"Ampla",
metab:"Hepático CYP2C19",
elimin:"Renal",
meiavida:"~35h",
ligacao:"~80%",
},
ef_colats:{
comuns:["Náusea","Cefaleia","Insônia","Disfunção sexual","Sudorese","Boca seca"],
sérios:["⚠ QT LONGO — torsades (FDA Warning)","⚠ Hiponatremia","⚠ Hemorragia","⚠ Suicidalidade em <25a","Síndrome serotoninérgica","Mania"],
},
interacoes:["⚠ IMAO","⚠ QT-prolongadores","Tramadol","Anticoagulantes","AINEs","Omeprazol (↑ citalopram)"],
contraindicacoes:["IMAO","⚠ QT longo, arritmia ventricular","Hipersensibilidade"],
monit:["ECG em risco","Sódio em idoso","Suicidalidade"],
gravidez:"C",
sus:"FARMASUS",
referencias:["FDA QT Warning 2012; NICE."],
},
{id:"med-duloxetina", contexto:["pa","ubs"], classe:"ISRSN — inibidor de recaptação de serotonina e noradrenalina", grupo:"psiq",
nome:"Duloxetina",
sin:["Cymbalta","Velija","Daxetin"],
formas:["Cápsula 30 mg, 60 mg, 90 mg, 120 mg","⚠ Não REMUME nacional — FARMASUS controle especial / componente complementar"],
resumo:"⚠ ISRSN com efeito noradrenérgico desde DOSE BAIXA. ⚠ INDICAÇÃO PRIORITÁRIA em DEPRESSÃO + DOR (dor neuropática diabética, fibromialgia, dor músculo-esquelética crônica, dor crônica em geral). ⚠ Hepatotoxicidade — não usar em IH significativa, álcool pesado.",
dose_rapida:"60-120 mg/d (depressão); 30-60 mg/d (dor)",
doses:[
{ind:"⚠ DEPRESSÃO MAIOR + DOR CRÔNICA / fibromialgia / dor neuropática", dose:"30 mg/d × 1 sem, depois 60 mg/d. Max 120 mg/d", obs:"⚠ INDICAÇÃO ESPECÍFICA — vantagem sobre ISRS quando há dor + humor."},
{ind:"⚠ Dor neuropática diabética (isolada)", dose:"60 mg/d", obs:""},
{ind:"⚠ Fibromialgia (isolada)", dose:"30-60 mg/d", obs:""},
{ind:"⚠ Dor musculoesquelética crônica (lombalgia crônica, OA)", dose:"30-60 mg/d", obs:""},
{ind:"⚠ TAG", dose:"30-120 mg/d", obs:""},
{ind:"⚠ Incontinência urinária de esforço (off-label, registrada em alguns países)", dose:"40-80 mg/d", obs:""},
],
ajustes:{
irc:"TFG <30: EVITAR",
iht:"⚠ ⚠ CONTRAINDICADA em IH (Child B/C)",
idoso:"⚠ Iniciar 30 mg/d. Monitor SIADH.",
gestante:"⚠ C — Cautela",
aleita:"Cautela",
ped:"≥7a (TAG); ≥18a (outras indicações)",
},
mecanismo:"INIBE recaptação 5-HT + NA. Efeito analgésico via via descendente noradrenérgica modulando dor.",
farmacocin:{
absorc:"VO ~50%",
distrib:"Ampla",
metab:"Hepático CYP1A2, CYP2D6",
elimin:"Renal",
meiavida:"~12h",
ligacao:"~90%",
},
ef_colats:{
comuns:["Náusea (mais comum na 1ª sem)","Boca seca","Constipação","Sonolência ou insônia","Fadiga","Sudorese","Tontura","Disfunção sexual","Anorexia / perda peso modesta"],
sérios:["⚠ HEPATOTOXICIDADE — pode causar hepatite. Evitar em álcool pesado, IH","⚠ Aumento de PA (menos que venlafaxina)","Hiponatremia","Hemorragia","Suicidalidade <25a","Síndrome serotoninérgica","Mania","Síndrome de descontinuação (intensa)"],
},
interacoes:["⚠ IMAO","INIBIDOR CYP1A2 (ciprofloxacino, fluvoxamina): ↑ duloxetina","INIBIDOR CYP2D6 (paroxetina, fluoxetina): ↑ duloxetina","Tramadol","Anticoagulantes","AINEs","Álcool"],
contraindicacoes:["⚠ IMAO 14 dias","⚠ IH (Child B/C)","⚠ Álcool pesado","TFG <30","Hipersensibilidade","Glaucoma ângulo fechado"],
monit:["TGO/TGP basal e em uso prolongado","PA","Suicidalidade <25a","Sódio em idoso"],
gravidez:"C",
sus:"FARMASUS / componente complementar",
referencias:["NICE Pain; APA; ADA Diabetic Neuropathy."],
},
{id:"med-escitalopram", contexto:["pa","ubs"], classe:"ISRS — inibidor seletivo de recaptação de serotonina", grupo:"psiq",
nome:"Escitalopram",
sin:["Lexapro","Reconter","Esciton","Exodus"],
formas:["Comprimido 10 mg, 15 mg, 20 mg","Solução oral 20 mg/mL","⚠ Não REMUME nacional. PFPB em algumas SES + FARMASUS controle especial"],
resumo:"⚠ ISRS de PERFIL LIMPO — menos interações medicamentosas (não CYP2D6), bem tolerado, eficácia equivalente a sertralina. PREFERIDO em idoso polifarmacizado, hepatopata. Limitação: ⚠ DOSE MÁXIMA 20 mg (10 mg em idoso) por risco QT. Custo maior que fluoxetina/sertralina.",
dose_rapida:"10-20 mg/d (idoso 5-10 mg/d)",
doses:[
{ind:"⚠ Depressão maior", dose:"5-10 mg/d × 1-2 sem, depois 10-20 mg/d", obs:"Dose efetiva 10 mg/d. ⚠ MÁX 20 mg/d (10 mg em idoso) — QT."},
{ind:"⚠ TAG / pânico / fobia social", dose:"5 mg/d × 1 sem, depois 10-20 mg/d", obs:"⚠ Começar baixo em pânico."},
{ind:"TOC, TEPT", dose:"10-20 mg/d", obs:""},
{ind:"Disforia pré-menstrual", dose:"10-20 mg/d", obs:""},
],
ajustes:{
irc:"TFG <20: cautela",
iht:"⚠ Reduzir para 10 mg/d em IH moderada-grave",
idoso:"⚠ ⚠ MÁX 10 mg/d — risco QT mais acentuado. Iniciar 5 mg.",
gestante:"⚠ C — Dados crescentes. Sertralina e fluoxetina têm mais dados.",
aleita:"Compatível",
ped:"≥12a: 10 mg/d. Acompanhamento psiquiátrico.",
},
mecanismo:"INIBE recaptação 5-HT — enantiômero S do citalopram (10× mais potente que o R). Mínima interação com outros sistemas.",
farmacocin:{
absorc:"VO ~80%, sem interferência alimentar",
distrib:"Ampla",
metab:"Hepático (CYP2C19, CYP3A4 — pouco inibidor)",
elimin:"Renal",
meiavida:"~27-32h",
ligacao:"~56%",
},
ef_colats:{
comuns:["Náusea","Insônia","Sonolência","Disfunção sexual","Sudorese","Boca seca","Cefaleia"],
sérios:["⚠ PROLONGAMENTO QT (especialmente >20 mg/d, idoso, eletrólitos baixos) — TORSADES","⚠ Hiponatremia (SIADH)","⚠ Hemorragia (com AINE/anticoag)","⚠ Aumento de ideação suicida em <25a","Síndrome serotoninérgica","Mania em bipolar"],
},
interacoes:["⚠ IMAO: SD SEROTONINÉRGICA","⚠ QT-PROLONGADORES: somatório (ondansetrona, antiarrítmicos, macrolídeos, antipsicóticos, metadona) — atenção","Tramadol, linezolida, triptanos","Anticoagulantes","AINEs","Omeprazol: ↑ escitalopram (inibe CYP2C19)"],
contraindicacoes:["⚠ IMAO em 14 dias","⚠ QT longo, arritmia ventricular, IAM recente","Hipersensibilidade","Bradicardia, hipocalemia/magnesemia não corrigida"],
monit:["⚠ ECG em risco (dose alta, idoso, polifarmácia QT)","Sódio em idoso","Suicidalidade primeiras 4 sem em <25a"],
gravidez:"C",
sus:"⚠ FARMASUS / componente complementar. PFPB em algumas SES.",
referencias:["FDA QT Warning Citalopram/Escitalopram 2012; NICE."],
},
{id:"med-fluoxetina", contexto:["pa","ubs"], classe:"ISRS — inibidor seletivo de recaptação de serotonina", grupo:"psiq",
nome:"Fluoxetina",
sin:["Prozac","Daforin","Eufor","Verotina"],
formas:["Cápsula 10 mg, 20 mg","Solução oral 4 mg/mL","REMUME — UBS dispensação direta + PFPB + FARMASUS"],
resumo:"⚠ ISRS DE 1ª LINHA AMBULATORIAL — disponibilidade ampla SUS. Vantagem: MEIA-VIDA MUITO LONGA (metabólito ativo 7-15 dias) — washout natural, útil em paciente NÃO-ADERENTE. Desvantagem: maior risco de interações (inibidor CYP2D6 forte). ⚠ Pode ATIVAR — útil em depressão com fadiga, mas pode piorar ansiedade.",
dose_rapida:"20-60 mg/d (1×/d, manhã)",
doses:[
{ind:"⚠ Depressão maior", dose:"10-20 mg/d × 2 sem, depois 20-40 mg/d. Máx 80 mg/d", obs:"Dose efetiva mínima: 20 mg/d. Idoso/adolescente: começar 10 mg."},
{ind:"⚠ TOC", dose:"20 mg/d, titular a 40-80 mg/d", obs:"Dose mais alta em TOC."},
{ind:"⚠ Bulimia nervosa", dose:"60 mg/d", obs:"⚠ Indicação ESPECÍFICA — ÚNICA droga FDA-aprovada para bulimia."},
{ind:"⚠ Disforia pré-menstrual (DDPM)", dose:"20 mg/d contínuo OU apenas fase lútea", obs:""},
{ind:"⚠ Fobia social, pânico, TEPT", dose:"20-60 mg/d", obs:""},
{ind:"⚠ Síndrome climatérica (sintomas vasomotores resistentes)", dose:"20 mg/d", obs:"Off-label, alternativa a TRH em paciente com contraindicação."},
],
ajustes:{
irc:"Sem ajuste",
iht:"⚠ Reduzir 50% em IH moderada-grave",
idoso:"⚠ Iniciar 10 mg/d. Meia-vida ainda mais longa — acumulação. Maior risco hiponatremia, sangramento.",
gestante:"⚠ C — Aceita na gestação, eficácia conhecida. Sertralina é alternativa com mais dados. ⚠ Em 3º trimestre risco aumentado de hipertensão pulmonar persistente do RN.",
aleita:"⚠ Compatível mas concentração no leite materno > sertralina. Observar lactente para sedação, recusa alimentar.",
ped:"⚠ ≥7a (TOC); ≥8a (depressão). Acompanhamento psiquiátrico. Black box FDA.",
},
mecanismo:"INIBE recaptação 5-HT. Metabólito ativo NORFLUOXETINA — meia-vida 7-15 dias (efeito prolongado mesmo após suspensão).",
farmacocin:{
absorc:"VO ~80%",
distrib:"Ampla",
metab:"Hepático (CYP2D6, CYP3A4 — INIBIDOR CYP2D6 forte)",
elimin:"Renal + fecal",
meiavida:"⚠ FLUOXETINA 1-3 dias / NORFLUOXETINA 7-15 dias — características próprias",
ligacao:"~95%",
},
ef_colats:{
comuns:["⚠ ATIVAÇÃO (insônia, agitação, ansiedade) — comum no início — tomar pela MANHÃ","Náusea (transitória)","Cefaleia","Tremor","Disfunção sexual","Anorexia / perda de peso modesta","Sudorese","Boca seca"],
sérios:["⚠ HIPONATREMIA (SIADH) — risco em idoso","⚠ Hemorragia GI/cerebral (com AINE/anticoag)","⚠ Aumento de ideação suicida em <25a (black box)","⚠ Síndrome serotoninérgica (com IMAO, tramadol, triptanos)","⚠ Mania em bipolar","Disfunção sexual","Acatisia"],
},
interacoes:["⚠ IMAO: SD SEROTONINÉRGICA — proibido. ⚠ Washout 5-6 SEMANAS para iniciar IMAO após fluoxetina (vs 14 dias para outros ISRS)","⚠ Tramadol, linezolida, triptanos: sd. serotoninérgica","⚠ INIBIDOR CYP2D6 FORTE — múltiplas interações: tamoxifeno (↓ ativação), tricíclicos (↑ nível), antipsicóticos (↑ haloperidol, risperidona), metoprolol, codeína (↓ analgesia — não ativa em morfina)","⚠ Anticoagulantes: ↑ INR","AINEs: hemorragia GI","Pimozida: contraindicado","Tioridazina: contraindicado (QT)","Lítio: cuidado"],
contraindicacoes:["⚠ IMAO em 14 dias antes / 5-6 sem depois","⚠ Pimozida, tioridazina (QT)","Hipersensibilidade","Mania ativa"],
monit:["Resposta clínica 4-6 sem","Sódio em idoso","Suicidalidade primeiras 4 sem em <25a","Considerar washout LONGO em transição para IMAO","Disfunção sexual"],
gravidez:"C",
sus:"⚠ REMUME — UBS dispensação direta + PFPB + FARMASUS.",
referencias:["DSM-5-TR; APA Practice; NICE; ABP."],
},
{id:"med-mirtazapina", contexto:["pa","ubs"], classe:"Antidepressivo atípico — antagonista α2 e 5-HT2/3", grupo:"psiq",
nome:"Mirtazapina",
sin:["Remeron","Razapina","Menelat"],
formas:["Comprimido 15 mg, 30 mg, 45 mg","Comprimido orodispersível (SolTab) 15 mg, 30 mg, 45 mg","⚠ Não REMUME nacional — FARMASUS / componente complementar"],
resumo:"⚠ ANTIDEPRESSIVO ATÍPICO — INDICAÇÕES DIFERENCIADAS: depressão com INSÔNIA + PERDA DE PESO. Vantagens: SEDAÇÃO POTENTE (em dose baixa — paradoxalmente menos sedação em dose alta), GANHO DE PESO (útil em paciente caquéctico), MENOS DISFUNÇÃO SEXUAL que ISRS, RÁPIDA AÇÃO em ansiedade-insônia. Dose única à NOITE. ⚠ Sem síndrome serotoninérgica significativa (não inibe recaptação 5-HT).",
dose_rapida:"7,5-45 mg HS",
doses:[
{ind:"⚠ DEPRESSÃO + INSÔNIA + PERDA DE PESO (caquéctico, oncológico)", dose:"15 mg HS × 1-2 sem, depois 30 mg HS. Máx 45 mg HS", obs:"⚠ Vantagem em pacientes com perda de peso + insônia. Pode usar em paciente HIV/oncológico."},
{ind:"⚠ DEPRESSÃO REFRATÁRIA — combinada a ISRS", dose:"15-30 mg HS + ISRS", obs:"⚠ 'California Rocket Fuel' — combinação venlafaxina + mirtazapina em depressão refratária (psiquiatria)."},
{ind:"⚠ INSÔNIA + DEPRESSÃO", dose:"7,5-15 mg HS", obs:"⚠ Em dose baixa (7,5-15 mg) — sedação predominante."},
{ind:"⚠ TAG", dose:"15-30 mg HS", obs:""},
{ind:"⚠ Náusea / vômito crônico (off-label, paliativos)", dose:"15-30 mg HS", obs:"Útil em paciente oncológico — combina antiemese + antidepressivo + ganho peso + sono."},
],
ajustes:{
irc:"Sem ajuste leve. Cautela em grave.",
iht:"Reduzir 50%",
idoso:"⚠ Iniciar 7,5-15 mg HS. Monitor sedação, hiponatremia.",
gestante:"C",
aleita:"Cautela — dados limitados",
ped:"⚠ Acompanhamento psiquiátrico",
},
mecanismo:"ANTAGONISTA α-2 PRÉ-SINÁPTICO (↑ liberação NA + 5-HT) + ANTAGONISTA 5-HT2A/2C/3 + ANTAGONISTA H1 POTENTE (sedação + ganho de peso) + leve antimuscarínico.",
farmacocin:{
absorc:"VO ~50%",
distrib:"Ampla",
metab:"Hepático CYP1A2, CYP2D6, CYP3A4",
elimin:"Renal + fecal",
meiavida:"~20-40h",
ligacao:"~85%",
},
ef_colats:{
comuns:["⚠ SEDAÇÃO (paradoxalmente MENOR em doses MAIS ALTAS — efeito ↓NA contrapõe sedação H1)","⚠ GANHO DE PESO (significativo — apetite aumentado)","Boca seca","Constipação","Sonhos vívidos","Tontura"],
sérios:["⚠ Síndrome metabólica em uso prolongado (ganho peso, dislipidemia)","Neutropenia / agranulocitose (raro)","Hiponatremia","Hepatotoxicidade rara","Suicidalidade <25a","Síndrome serotoninérgica (rara — não inibe recaptação)","Mania em bipolar"],
},
interacoes:["⚠ IMAO (relativa — mecanismo diferente, mas cuidar)","Álcool, BZD: sedação somativa","Indutores CYP (carbamazepina): ↓ mirtazapina","Tramadol: convulsão"],
contraindicacoes:["IMAO 14 dias (relativa)","Hipersensibilidade","Mania ativa"],
monit:["Peso","Suicidalidade <25a","Sódio em idoso","Hemograma em caso de sintomas (febre, infecção)"],
gravidez:"C",
sus:"FARMASUS / componente complementar",
referencias:["NICE; APA."],
},
{id:"med-nortriptilina", contexto:["pa","ubs"], classe:"Antidepressivo Tricíclico (ADT)", grupo:"psiq",
nome:"Nortriptilina",
sin:["Pamelor","Pamenor"],
formas:["Cápsula 10 mg, 25 mg, 50 mg, 75 mg","Solução oral 2 mg/mL","REMUME — FARMASUS (controle especial)"],
resumo:"⚠ ADT — METABÓLITO ATIVO da amitriptilina. Vantagem: MENOS sedação, MENOS anticolinérgico, MENOS hipotensão ortostática que amitriptilina. PREFERIDA em idoso quando ADT necessário. Mesmas indicações em DOSE BAIXA: dor neuropática, profilaxia migrânea.",
dose_rapida:"DEPRESSÃO: 50-150 mg/d; DOR: 10-50 mg HS",
doses:[
{ind:"⚠ DOR NEUROPÁTICA", dose:"10-25 mg HS, titular a 25-75 mg HS", obs:"⚠ Preferida sobre amitriptilina em idoso por menor anticolinérgico."},
{ind:"Profilaxia de migrânea", dose:"10-25 mg HS, titular a 25-75 mg HS", obs:""},
{ind:"Depressão maior", dose:"25 mg HS × 1 sem, depois 50-150 mg/d", obs:"Alternativa ADT em paciente que tolera mal amitriptilina."},
],
ajustes:{
irc:"Sem ajuste leve. Cautela em grave.",
iht:"Reduzir 50%",
idoso:"⚠ Mais segura entre ADTs em idoso — começar 10 mg, titular lento",
gestante:"C",
aleita:"Compatível",
ped:"⚠ Acompanhamento psiquiátrico",
},
mecanismo:"INIBE recaptação de NA > 5-HT (mais noradrenérgica que amitriptilina). Menor afinidade por receptores muscarínicos, H1, α1 → menos efeitos colaterais.",
farmacocin:{
absorc:"VO ~50%",
distrib:"Ampla",
metab:"Hepático CYP2D6",
elimin:"Renal",
meiavida:"~16-36h",
ligacao:"~93%",
},
ef_colats:{
comuns:["Boca seca","Constipação","Sonolência leve (menos que amitriptilina)","Taquicardia","Hipotensão ortostática leve","Ganho de peso"],
sérios:["⚠ CARDIOTOXICIDADE EM SUPERDOSE","Prolongamento QT","Retenção urinária","Glaucoma","Mania","Suicidalidade <25a"],
},
interacoes:["⚠ IMAO","ISRS (CYP2D6)","QT-prolongadores","Anticolinérgicos","Tramadol"],
contraindicacoes:["IAM recente, bloqueio AV","Glaucoma","HPB","Mania ativa","IMAO 14 dias"],
monit:["ECG","Sintomas anticolinérgicos","Suicidalidade","Nível terapêutico (50-150 ng/mL)"],
gravidez:"C",
sus:"REMUME — FARMASUS",
referencias:["NICE Neuropathic Pain; APA."],
},
{id:"med-paroxetina", contexto:["pa","ubs"], classe:"ISRS — inibidor seletivo de recaptação de serotonina", grupo:"psiq",
nome:"Paroxetina",
sin:["Aropax","Cebrilin","Pondera","Pamelor (NÃO — é nortriptilina)"],
formas:["Comprimido 10 mg, 20 mg, 25 mg CR (controlled release)","FARMASUS"],
resumo:"⚠ ISRS EFICAZ em ANSIEDADE / pânico / fobia social — historicamente preferido. PORÉM: PIOR PERFIL DE TOLERABILIDADE da classe — anticolinérgico (sedação, boca seca, constipação, retenção urinária), maior ganho de peso, síndrome de descontinuação INTENSA. ⚠ EVITAR em idoso. ⚠ EVITAR em gestação (anomalias cardíacas em meta-análises).",
dose_rapida:"20-40 mg/d (CR 25-50 mg/d)",
doses:[
{ind:"Depressão maior", dose:"20 mg/d, titular a 40 mg/d. Máx 50 mg/d (60 mg em alguns países)", obs:""},
{ind:"⚠ Transtorno de pânico", dose:"10 mg/d × 1 sem (sensibilidade), depois 20-40 mg/d", obs:"Início baixo — pacientes com pânico muito sensíveis."},
{ind:"TAG, fobia social, TEPT, TOC", dose:"20-40 mg/d (TOC até 60 mg/d)", obs:""},
{ind:"Disforia pré-menstrual", dose:"12,5-25 mg/d (CR)", obs:""},
{ind:"Sintomas vasomotores climatério", dose:"7,5 mg/d (formulação específica em alguns países) OU 10-20 mg/d", obs:"Off-label."},
],
ajustes:{
irc:"TFG <30: dose mais baixa",
iht:"Cautela",
idoso:"⚠ EVITAR — Beers Criteria — anticolinérgico, sedação, quedas",
gestante:"⚠ D — EVITAR. Anomalias cardíacas em meta-análises (especialmente 1º trimestre). Trocar para sertralina/fluoxetina ANTES de gestar se possível.",
aleita:"Compatível",
ped:"⚠ ≥18a (não aprovada em <18a)",
},
mecanismo:"INIBE recaptação 5-HT + ATIVIDADE ANTICOLINÉRGICA mais pronunciada que outros ISRS.",
farmacocin:{
absorc:"VO ~50%",
distrib:"Ampla",
metab:"Hepático (CYP2D6 — INIBIDOR FORTE, similar à fluoxetina)",
elimin:"Renal + fecal",
meiavida:"~21h",
ligacao:"~95%",
},
ef_colats:{
comuns:["⚠ SEDAÇÃO (mais que outros ISRS)","⚠ Boca seca, constipação, retenção urinária (anticolinérgico)","Náusea","⚠ GANHO DE PESO (mais que outros ISRS)","⚠ DISFUNÇÃO SEXUAL marcada","Tontura, sudorese"],
sérios:["⚠ SÍNDROME DE DESCONTINUAÇÃO INTENSA — vertigem, parestesia 'choque elétrico', sintomas gripais — PIOR da classe","Hiponatremia","Hemorragia","Suicidalidade em <25a","Síndrome serotoninérgica","Mania","Anomalias cardíacas fetais (1º trimestre)"],
},
interacoes:["⚠ IMAO","⚠ INIBIDOR CYP2D6 FORTE — tamoxifeno (não ativa — proibido em CA mama estrogênio+), tricíclicos, antipsicóticos, codeína","Tramadol","Anticoagulantes","AINEs","Pimozida, tioridazina (QT)"],
contraindicacoes:["⚠ IMAO 14 dias","⚠ Gestação (relativa)","⚠ Idoso (relativa)","Pimozida, tioridazina","Hipersensibilidade"],
monit:["Resposta clínica","Ganho de peso","⚠ Plano de SUSPENSÃO MUITO GRADUAL — reduzir 10% a cada 2-4 sem","Suicidalidade em <25a"],
gravidez:"⚠ D",
sus:"FARMASUS",
referencias:["FDA Pregnancy Warning Paroxetine 2005; APA."],
},
{id:"med-sertralina", contexto:["pa","ubs"], classe:"ISRS — inibidor seletivo de recaptação de serotonina", grupo:"psiq",
nome:"Sertralina",
sin:["Zoloft","Sertran","Serenata","Tolrest"],
formas:["Comprimido 25 mg, 50 mg, 100 mg","Solução oral 20 mg/mL","REMUME — FARMASUS (controle especial — receita C1)"],
resumo:"⚠ ⚠ ISRS DE 1ª LINHA EM MAIORIA DAS INDICAÇÕES. Perfil de SEGURANÇA AMPLO — segura em cardiopata, idoso, gestação (mais estudada e mais segura), poucas interações. Início de ação 2-4 sem, pleno 4-6 sem.",
dose_rapida:"50-200 mg/d (depressão); 25-200 mg/d (ansiedade — começar BAIXO)",
doses:[
{ind:"⚠ Depressão maior", dose:"25-50 mg/d × 1 sem, depois 50 mg/d. Titular a 100-200 mg/d se necessário em 2-4 sem", obs:"Dose efetiva mínima: 50 mg/d. Máx 200 mg/d."},
{ind:"⚠ TAG / Transtorno ansioso", dose:"25 mg/d × 1 sem, depois 50 mg/d. Titular conforme tolerância 50-200 mg/d", obs:"⚠ Pode aumentar ansiedade nas primeiras 2 sem — orientar, persistir."},
{ind:"⚠ Transtorno de pânico", dose:"12,5-25 mg/d × 1 sem, depois 25-50 mg/d. Titular lento 50-200 mg/d", obs:"⚠ Sensibilidade EXTREMA — começar muito baixo."},
{ind:"⚠ TOC", dose:"50 mg/d, titular a 100-200 mg/d (doses mais altas em TOC — até 300 mg em alguns casos)", obs:"Início ação mais lento em TOC — pode levar 8-12 sem."},
{ind:"⚠ TEPT", dose:"50-200 mg/d", obs:""},
{ind:"⚠ Disforia pré-menstrual (DDPM)", dose:"50-100 mg/d contínuo OU 50-150 mg/d apenas na fase lútea", obs:""},
{ind:"⚠ Fobia social", dose:"50-200 mg/d", obs:""},
],
ajustes:{
irc:"Sem ajuste (não eliminada por rim)",
iht:"⚠ Reduzir 50% em IH moderada-grave",
idoso:"⚠ Iniciar 25 mg/d. Maior risco hiponatremia (SIADH), quedas, hemorragia GI.",
gestante:"⚠ ⚠ C — MAIS SEGURA da classe na gestação. Sertralina + fluoxetina são preferidas. Riscos: hipertensão pulmonar persistente do RN (pequeno mas real, especialmente 3º trimestre), sintomas de descontinuação neonatal (irritabilidade, taquipneia, hipoglicemia — autolimitados). ⚠ NÃO SUSPENDER em gestante estabilizada se depressão moderada-grave.",
aleita:"⚠ Compatível — mais segura da classe na lactação (níveis baixos no leite). Continuar.",
ped:"⚠ ≥6a: 25 mg/d (TOC); ≥12a: depressão. Acompanhamento psiquiátrico. ⚠ Black box FDA para ideação suicida em <25a — monitor 1-2 sem.",
},
mecanismo:"INIBE recaptação de serotonina (5-HT) no neurônio pré-sináptico → ↑ disponibilidade sináptica. Mínima ação em outros neurotransmissores. Mecanismo terapêutico não totalmente esclarecido (provável neuroplasticidade após semanas).",
farmacocin:{
absorc:"VO ~88%. Refeição AUMENTA biodisponibilidade — tomar com alimento.",
distrib:"Ampla, atravessa BHE",
metab:"Hepático (CYP3A4, CYP2C19, CYP2B6)",
elimin:"Renal + fecal",
meiavida:"~26h (1×/d)",
ligacao:"~98%",
},
ef_colats:{
comuns:["⚠ DIARREIA (mais que outros ISRS — característica)","Náusea (geralmente transitória)","Cefaleia","Insônia ou sonolência","Sudorese","Tremor leve","DISFUNÇÃO SEXUAL (atraso ejaculatório, anorgasmia, ↓ libido) — frequente","Boca seca","Ganho de peso modesto a longo prazo"],
sérios:["⚠ HIPONATREMIA (SIADH) — risco aumentado em idoso, diurético, baixa ingesta","⚠ HEMORRAGIA — ↑ risco GI alto (especialmente com AINE) e cerebral (em anticoagulado)","⚠ AUMENTO TRANSITÓRIO DE IDEAÇÃO SUICIDA nas 2-4 primeiras semanas em <25a (FDA black box)","⚠ SÍNDROME SEROTONINÉRGICA (em combinação com IMAO, tramadol, linezolida, triptanos, ondansetrona em dose alta)","⚠ SÍNDROME DE DESCONTINUAÇÃO (vertigem, parestesia 'choques elétricos', sintomas gripais, irritabilidade) — sertralina é INTERMEDIÁRIA neste aspecto","Mania/hipomania em paciente bipolar não diagnosticado","Prolongamento QT em dose alta (raro)","Disfunção plaquetária"],
},
interacoes:["⚠ IMAO (incluindo selegilina, linezolida, azul de metileno): SÍNDROME SEROTONINÉRGICA — proibir; washout 14 dias","⚠ Tramadol, linezolida, fentanil, triptanos: risco sd. serotoninérgica","⚠ Anticoagulantes orais (varfarina): ↑ INR e hemorragia","⚠ AINEs / ácido acetilsalicílico: hemorragia GI somativa","Pimozida: ↑ nível, QT","Lítio: cuidado","Inibidores CYP2D6: pequeno impacto"],
contraindicacoes:["⚠ USO de IMAO em 14 dias","⚠ Hipersensibilidade","Uso concomitante com pimozida","Mania/hipomania ativa não tratada"],
monit:["Resposta clínica em 4-6 sem","Sódio sérico em idoso/diurético (1-2 sem)","Suicidalidade primeiras 4 sem em <25a","INR se varfarina","Sintomas sexuais (frequente — discutir)"],
gravidez:"C",
sus:"⚠ REMUME — FARMASUS (receita controle especial C1). Disponibilidade ampla.",
referencias:["DSM-5-TR; APA Practice; NICE; ABP. PCDT-MS Saúde Mental."],
},
{id:"med-trazodona", contexto:["pa","ubs"], classe:"Antidepressivo serotoninérgico atípico", grupo:"psiq",
nome:"Trazodona",
sin:["Donaren","Donaren Retard","Cloridrato de Trazodona"],
formas:["Comprimido 50 mg, 100 mg","Comprimido retard 150 mg","Solução oral 0,6%","FARMASUS controle especial"],
resumo:"⚠ ANTIDEPRESSIVO + SEDATIVO. ⚠ USO PRINCIPAL HOJE: INSÔNIA em DOSE BAIXA (25-100 mg HS) — sem dependência, sem síndrome de descontinuação importante. ⚠ Dose ANTIDEPRESSIVA é alta (150-600 mg/d) e raramente tolerada por sedação. ⚠ Raro mas importante: PRIAPISMO.",
dose_rapida:"INSÔNIA: 25-100 mg HS; DEPRESSÃO: 150-400 mg/d",
doses:[
{ind:"⚠ ⚠ INSÔNIA (uso principal hoje — OFF-LABEL mas amplamente usado)", dose:"25-50 mg HS, titular a 100 mg HS conforme necessidade", obs:"⚠ Sem dependência, sem síndrome de descontinuação significativa. Excelente alternativa a BZD/Z-drug em paciente com história de dependência."},
{ind:"⚠ INSÔNIA + DEPRESSÃO", dose:"50-150 mg HS", obs:""},
{ind:"Depressão maior (uso menos comum)", dose:"150 mg/d × 4-7 dias, titular a 200-400 mg/d ÷ 12/12h", obs:"⚠ Sedação importante — dose alta raramente tolerada."},
{ind:"⚠ Agitação em DEMÊNCIA (off-label)", dose:"25-100 mg/d", obs:""},
],
ajustes:{
irc:"Cautela em IRC grave",
iht:"Reduzir dose",
idoso:"⚠ Iniciar 25 mg HS. Monitor hipotensão postural, sedação, quedas",
gestante:"C — dados limitados",
aleita:"Cautela",
ped:"⚠ Não aprovada — uso off-label em pediatria psiquiátrica especializada",
},
mecanismo:"INIBE recaptação 5-HT (fraco) + ANTAGONISTA 5-HT2A + ANTAGONISTA α1 (hipotensão) + ANTAGONISTA H1 (sedação). Mecanismo do efeito hipnótico: H1 + α1 + 5-HT2A.",
farmacocin:{
absorc:"VO ~65% (refeição reduz pico — tomar 1h antes)",
distrib:"Ampla",
metab:"Hepático CYP3A4 → metabólito ativo mCPP",
elimin:"Renal",
meiavida:"~3-9h",
ligacao:"~90%",
},
ef_colats:{
comuns:["⚠ SEDAÇÃO marcada (intencional em insônia)","Hipotensão ortostática","Tontura","Boca seca","Cefaleia","Náusea","Visão turva","SEM disfunção sexual marcada (vantagem)"],
sérios:["⚠ PRIAPISMO — raro mas EMERGÊNCIA UROLÓGICA — orientar paciente. Risco maior em DOSE ALTA e jovem.","Arritmias (em superdose)","Síncope","Suicidalidade <25a","Síndrome serotoninérgica","Mania","Hepatotoxicidade rara"],
},
interacoes:["⚠ IMAO","Inibidores CYP3A4 (ritonavir, cetoconazol, claritro): ↑ trazodona","QT-prolongadores","Anti-hipertensivos: hipotensão somativa","Álcool, BZD: sedação"],
contraindicacoes:["IMAO 14 dias","⚠ Pós-IAM recente","Histórico de priapismo","Hipersensibilidade","Mania ativa"],
monit:["⚠ Priapismo (orientar — emergência se >2h)","Hipotensão postural especialmente idoso","Sedação, quedas"],
gravidez:"C",
sus:"FARMASUS",
referencias:["AASM Insomnia; APA."],
},
{id:"med-venlafaxina", contexto:["pa","ubs"], classe:"ISRSN — inibidor de recaptação de serotonina e noradrenalina", grupo:"psiq",
nome:"Venlafaxina",
sin:["Efexor","Venlift OD","Velise"],
formas:["Comprimido 37,5 mg, 50 mg, 75 mg (IR)","Cápsula XR 37,5 mg, 75 mg, 150 mg","FARMASUS controle especial"],
resumo:"⚠ ISRSN — em dose BAIXA (<150 mg/d) age principalmente como ISRS; em dose ALTA (≥150 mg/d) atinge efeito noradrenérgico (dor crônica, depressão refratária). PREFERIDA a forma XR (1×/d, menos efeitos). ⚠ Pode AUMENTAR PA — monitor. ⚠ SÍNDROME DE DESCONTINUAÇÃO INTENSA — pior da classe.",
dose_rapida:"75-225 mg/d XR; 37,5-225 mg/d IR ÷ 12/12h",
doses:[
{ind:"⚠ Depressão maior", dose:"75 mg/d XR × 4-7 dias, titular a 150-225 mg/d. Máx 375 mg/d", obs:""},
{ind:"⚠ TAG / fobia social / pânico", dose:"37,5 mg/d × 4-7 dias, depois 75-225 mg/d", obs:"Eficaz em TAG. Pânico: começar baixo (sensibilidade)."},
{ind:"⚠ DOR NEUROPÁTICA / fibromialgia (off-label)", dose:"150-225 mg/d", obs:"Doses noradrenérgicas. Alternativa a duloxetina."},
{ind:"Climatério (sintomas vasomotores)", dose:"37,5-150 mg/d", obs:"Alternativa a TRH em paciente com contraindicação."},
],
ajustes:{
irc:"TFG <30: 50% dose. HD: pós.",
iht:"Reduzir 50% em IH",
idoso:"⚠ Monitor PA, hiponatremia",
gestante:"⚠ C — Cautela. Sintomas neonatais de descontinuação. Sertralina/fluoxetina preferidas.",
aleita:"Cautela",
ped:"⚠ Cuidado — black box suicidalidade",
},
mecanismo:"INIBE recaptação 5-HT (baixa dose) e NA (dose alta). Sem ação anticolinérgica/anti-H1/α1.",
farmacocin:{
absorc:"VO ~45%",
distrib:"Ampla",
metab:"Hepático CYP2D6 → metabólito ativo desvenlafaxina",
elimin:"Renal",
meiavida:"~5h (IR) / ~10h (XR + metabólito)",
ligacao:"~27%",
},
ef_colats:{
comuns:["Náusea (frequente — usar XR, com alimento)","⚠ AUMENTO DE PA (dose-dependente, especialmente >150 mg/d)","Sudorese, calor","Cefaleia, tontura","Disfunção sexual","Insônia ou sonolência","Boca seca","Anorexia"],
sérios:["⚠ ⚠ SÍNDROME DE DESCONTINUAÇÃO INTENSA — pior da classe (vertigem, parestesia 'choque', sintomas gripais, irritabilidade — desconforto intenso por dias-semanas)","⚠ Hipertensão arterial","Hiponatremia","Hemorragia (com AINE/anticoag)","Suicidalidade <25a","Síndrome serotoninérgica","Mania","QT longo em dose alta"],
},
interacoes:["⚠ IMAO: SD SEROTONINÉRGICA","Tramadol, linezolida, triptanos","Anticoagulantes","AINEs","QT-prolongadores em dose alta","Cimetidina (em IH)"],
contraindicacoes:["⚠ IMAO 14 dias","⚠ HAS não controlada","Hipersensibilidade","Mania ativa"],
monit:["⚠ PA — basal e em titulação","Suicidalidade <25a","Sódio em idoso","⚠ Plano de SUSPENSÃO MUITO GRADUAL (semanas a meses)"],
gravidez:"C",
sus:"FARMASUS",
referencias:["NICE Depression; APA."],
},
);
