/* ===========================================================
   VOVÔMINIC EMERGÊNCIA — PULO DO GATO 3 (parte B)
   Cabeça/Pescoço + Genito-urinário + Pediátrico + Comportamental + Procedimentos
   =========================================================== */

PATOLOGIAS.push(

/* ============== EPISTAXE — PASSO A PASSO ============== */
{id:"pulo-epistaxe", nome:"Epistaxe — protocolo de compressão + adrenalina/lidocaína", sis:"pulo", grav:"baixa",
cid:"R04.0", ciap:"R06",
sin:["Epistaxe","Sangramento nasal","Plexo de Kiesselbach","Tampão nasal","Sangue pelo nariz"],
def:"~90% das epistaxes são ANTERIORES (plexo de Kiesselbach, Little's area) e resolvem com COMPRESSÃO MANUAL CORRETA (cartilagem, não osso) × 10 min + adrenalina+lidocaína tópica se persistir. Posteriores (10%) são mais graves, podem precisar de balão.",
quadro:["Sangramento pela narina, geralmente UNILATERAL","Causas comuns: trauma de cutucar, ar seco, IVAS, rinite alérgica, HAS descompensada, anticoagulante, distúrbio coagulação, drogas (cocaína)","⚠ EPISTAXE POSTERIOR: sangramento BILATERAL ou predominância em orofaringe, deglutição de sangue, vômito de sangue — emergência ORL"],
diag:["Inspeção com espéculo nasal + boa iluminação","Pressão arterial (HAS pode ser causa ou consequência)","Hemograma se sangramento volumoso ou anticoagulado: INR, TTPa, plaquetas","Anamnese: anticoagulante, antiagregante, hepatopatia, doença hematológica"],
exames:["PA","Em sangramento volumoso / anticoagulado: hemograma, coagulograma","Tipagem sanguínea se reposição"],
rx:[
{etapa:"inicial", d:"⚠ POSIÇÃO: paciente SENTADO, inclinado para frente (NÃO deitado, NÃO inclinado para trás) — evita deglutição de sangue/aspiração"},
{etapa:"inicial", d:"Pedir para CUSPIR sangue da boca, não engolir (engolir → vômito de sangue mais tarde)"},
{etapa:"inicial", d:"Tranquilizar paciente — ansiedade aumenta PA e sangramento"},
{etapa:"escala", d:"⚠ COMPRESSÃO MANUAL — 1ª manobra (resolve ~70%)"},
{etapa:"escala", d:"Comprimir a CARTILAGEM ANTERIOR (parte mole do nariz, NÃO o osso)"},
{etapa:"escala", d:"Pinçar entre POLEGAR E INDICADOR firmemente"},
{etapa:"escala", d:"Manter por 10-15 MIN ININTERRUPTOS (cronômetro, sem 'verificar' a cada 2 min)"},
{etapa:"escala", d:"Respirar pela boca durante a compressão"},
{etapa:"escala", d:"GELO no dorso do nariz / na nuca / chupar gelo — auxiliar (vasoconstrição)"},
{etapa:"adj", d:"⚠ SE PERSISTIR após compressão: ADRENALINA + LIDOCAÍNA TÓPICAS"},
{etapa:"adj", d:"Embeber gaze com: ADRENALINA 1:1000 (1 mL) + LIDOCAÍNA 2% (2-5 mL) — solução combinada", o:"Lidocaína anestesia + adrenalina vasoconstrição."},
{etapa:"adj", d:"Inserir gaze no vestíbulo nasal anterior (lado sangrando), com pinça baioneta se possível"},
{etapa:"adj", d:"Manter 10-15 min com COMPRESSÃO EXTERNA"},
{etapa:"adj", d:"REMOVER gaze gentilmente após — se reanagrar, repetir compressão"},
{etapa:"adj", d:"⚠ ALTERNATIVA: oximetazolina spray nasal (2 jatos + comprimir) — vasoconstritor disponível"},
{etapa:"adj", d:"⚠ TAMPONAMENTO ANTERIOR — se ainda persistir"},
{etapa:"adj", d:"GAZE 1×30 cm embebida em adrenalina/lidocaína OU vaselina"},
{etapa:"adj", d:"Inserir com pinça baioneta — DOBRADURAS sucessivas, base ao topo (acordeon)"},
{etapa:"adj", d:"Encaminhar ORL para retirada em 24-72h"},
{etapa:"adj", d:"⚠ ALTERNATIVA: Merocel® / tampão expansível — insere seco, hidrata-se com soro fisiológico no local"},
{etapa:"adj", d:"⚠ TAMPONAMENTO POSTERIOR — emergência ORL (sangramento profundo, paciente engole muito sangue, instabilidade)"},
{etapa:"adj", d:"Balão de Foley 12-14 Fr no faringe + tampão anterior em sanduíche — TÉCNICA EMERGENCIAL"},
{etapa:"adj", d:"Internar + ORL"},
{etapa:"adj", d:"⚠ MANEJO ANTI-HIPERTENSIVO: PA elevada por dor/ansiedade é COMUM — não tratar agressivamente. Conforto + analgesia + parar sangramento"},
{etapa:"adj", d:"Se PA persistente >180/110 após sangramento controlado: tratamento padrão de crise hipertensiva"},
{etapa:"alta", d:"PÓS-RESOLUÇÃO: orientar — NÃO assoar nariz por 24-48h, evitar sol forte, picante, álcool, exercício intenso × 48h"},
{etapa:"alta", d:"Hidratação nasal com SF spray + vaselina/pomada cicatrizante na narina × 5-7 dias"},
{etapa:"alta", d:"Investigar etiologia em epistaxe RECORRENTE: HAS, doença hematológica, telangiectasias hereditárias (Osler-Weber-Rendu), uso de medicamentos"},
{etapa:"alta", d:"ENCAMINHAR ORL: epistaxe POSTERIOR (sempre), recorrente, suspeita neoplasia, telangiectasias"},
],
alertas:[
{nivel:"crit", txt:"EPISTAXE POSTERIOR é emergência — sangramento profundo, deglutição de sangue, posteriormente vômito de sangue, possível instabilidade. Tamponamento posterior + ORL urgente."},
{nivel:"crit", txt:"PACIENTE ANTICOAGULADO + epistaxe volumosa: avaliar INR, reverter se grave (vit K, complexo protrombínico). Não suspender anticoagulante sem motivo se sangramento controlado."},
{nivel:"warn", txt:"COMPRIMIR a CARTILAGEM ANTERIOR (parte mole), NÃO o osso. Erro mais comum é comprimir muito alto. 10-15 min contínuos."},
{nivel:"warn", txt:"PA elevada por dor/ansiedade é comum em epistaxe — NÃO tratar agressivamente como crise hipertensiva. Controlar sangramento primeiro, depois reavaliar PA."},
{nivel:"info", txt:"ADRENALINA + LIDOCAÍNA TÓPICAS em gaze é mais eficaz que compressão isolada em sangramentos persistentes. ~80% das epistaxes anteriores resolvem com essa combinação."},
{nivel:"info", txt:"OXIMETAZOLINA spray é alternativa simples disponível (Aturgyl, Afrin) — 2 jatos + compressão."},
],
fluxo:null, diretriz:"AAO-HNS. SBORL."
},

/* ============== OLHO VERMELHO ============== */
{id:"pulo-olho-vermelho", nome:"Olho vermelho — diferenciar com a 'luz do nariz'", sis:"pulo", grav:"moderada",
cid:"H10/H15/H20", ciap:"F02",
sin:["Olho vermelho","Hiperemia conjuntival","Uveíte","Esclerite","Episclerite","Conjuntivite","Glaucoma agudo"],
def:"NA APS — diferenciar olho vermelho banal (conjuntivite/episclerite) de RED FLAGS (uveíte, esclerite, glaucoma agudo, ceratite). TRUQUE: aplicar PHENILEFRINA 2,5% colírio no fundo de saco — em 5 min, episclerite/conjuntivite EMBRANQUECEM (vasos superficiais); esclerite/uveíte NÃO embranquecem (profundo).",
quadro:["BENIGNOS (sem ameaça visual): conjuntivite viral/bacteriana/alérgica, episclerite, blefarite, ressecamento ocular","RED FLAGS (encaminhar oftalmologia URGENTE): uveíte anterior, esclerite, ceratite, úlcera de córnea, glaucoma agudo de ângulo fechado, hifema, abrasão córnea, corpo estranho","SINAIS DE ALARME: dor (vs ardor leve), redução da AV, fotofobia intensa, halos coloridos, hipopio (pus em câmara anterior), miose/midríase, lacrimejamento intenso, vômito (glaucoma)"],
diag:["Anamnese: tempo, dor (vs ardor), fotofobia, redução AV, secreção, halos, prurido","Acuidade visual (importante)","Inspeção: padrão de hiperemia (difusa vs ciliar/peri-limbar), tamanho da pupila, reatividade","FLUORESCEÍNA + luz azul: úlcera/abrasão córnea cora","TESTE DA FENILEFRINA 2,5%: vasos superficiais empalidecem em 5-10 min; profundos não","Tonometria se suspeita glaucoma agudo (>40 mmHg típico)"],
exames:["Exame ocular básico (AV, pupila, fluoresceína)","Tonometria de schiotz / Goldmann (se disponível)","Encaminhar oftalmologia em red flags"],
rx:[
{etapa:"inicial", d:"⚠ AVALIAR RED FLAGS — encaminhar oftalmologia URGENTE se:"},
{etapa:"inicial", d:"(1) Redução da AV"},
{etapa:"inicial", d:"(2) Dor intensa (não apenas ardor)"},
{etapa:"inicial", d:"(3) Fotofobia intensa"},
{etapa:"inicial", d:"(4) Halos ao redor de luzes (glaucoma agudo)"},
{etapa:"inicial", d:"(5) Pupila alterada (miose em uveíte, midríase em glaucoma agudo)"},
{etapa:"inicial", d:"(6) Hipopio (nível de pus em câmara anterior)"},
{etapa:"inicial", d:"(7) Hifema (sangue em câmara anterior)"},
{etapa:"inicial", d:"(8) Lesão corneana visível (úlcera, opacidade)"},
{etapa:"inicial", d:"(9) Trauma recente"},
{etapa:"inicial", d:"(10) Uso de lente de contato + olho vermelho = ceratite presuntiva (Pseudomonas) → ORL/oftalmo URGENTE"},
{etapa:"escala", d:"⚠ TESTE DA FENILEFRINA 2,5% — DIFERENCIA superficial vs profundo"},
{etapa:"escala", d:"Aplicar 1-2 gotas de FENILEFRINA 2,5% no fundo de saco"},
{etapa:"escala", d:"Aguardar 5-10 min"},
{etapa:"escala", d:"SE VASOS EMBRANQUECEM → episclerite ou conjuntivite (superficial — vasoconstrição funciona)"},
{etapa:"escala", d:"SE NÃO EMBRANQUECEM → esclerite ou uveíte (profundo, vasos não acessíveis topicamente) → ENCAMINHAR oftalmo"},
{etapa:"escala", d:"⚠ FLUORESCEÍNA — pesquisa de lesão corneana"},
{etapa:"escala", d:"Tira de fluoresceína embebida em SF + colocar no fundo de saco"},
{etapa:"escala", d:"Lavar com SF — observar com luz azul (lanterna)"},
{etapa:"escala", d:"COR VERDE FLUORESCENTE = úlcera ou abrasão da córnea → tratar (ATB tópico + encaminhar)"},
{etapa:"escala", d:"PADRÃO DENDRÍTICO de coloração = herpes simplex córnea — ENCAMINHAR oftalmo URGENTE (NÃO usar corticoide tópico)"},
{etapa:"adj", d:"⚠ CONJUNTIVITE BACTERIANA: secreção purulenta amarelada espessa, pálpebras grudadas pela manhã"},
{etapa:"adj", d:"Tobramicina colírio 0,3% — 1 gota 4-6×/d × 5-7 dias", o:"OU ciprofloxacino colírio 0,3% (cobertura ampla)."},
{etapa:"adj", d:"Higiene ocular com compressa morna + SF"},
{etapa:"adj", d:"⚠ CONJUNTIVITE VIRAL: lacrimejamento aquoso, hiperemia bilateral, pré-auricular linfonodo, geralmente associada a IVAS"},
{etapa:"adj", d:"AUTOLIMITADA — 7-14 dias"},
{etapa:"adj", d:"Compressa fria, lubrificante ocular (carmelose, polivinilálcool)"},
{etapa:"adj", d:"Lavagem frequente das mãos — ALTAMENTE CONTAGIOSA"},
{etapa:"adj", d:"⚠ CONJUNTIVITE ALÉRGICA: prurido intenso, lacrimejamento, edema, bilateral, sazonal"},
{etapa:"adj", d:"Anti-histamínico tópico (olopatadina, cetotifeno) + lubrificante + compressa fria"},
{etapa:"adj", d:"Anti-histamínico VO se rinite associada"},
{etapa:"adj", d:"⚠ EPISCLERITE: hiperemia setorial, dor leve, sem redução AV. Fenilefrina empalidece"},
{etapa:"adj", d:"Lubrificante + AINE tópico (cetorolaco). Autolimitada"},
{etapa:"adj", d:"Recidiva frequente: investigar AR, LES (em 30%)"},
{etapa:"alta", d:"⚠ NUNCA usar CORTICOIDE TÓPICO ocular sem oftalmologista — risco glaucoma medicamentoso, retardo cicatrização, herpes córnea reativada"},
{etapa:"alta", d:"⚠ NUNCA usar ANESTÉSICO TÓPICO em casa (proparacaína, tetracaína) — toxicidade epitelial, retardo cicatrização. Apenas em consultório para exame"},
{etapa:"alta", d:"⚠ USO DE LENTE DE CONTATO + olho vermelho = SUSPENDER lente + oftalmo. Ceratite por Pseudomonas evolui rápido"},
],
alertas:[
{nivel:"crit", txt:"GLAUCOMA AGUDO DE ÂNGULO FECHADO: olho muito vermelho + dor intensa + midríase fixa + halos + náusea/vômito + AV reduzida = EMERGÊNCIA OFTALMO (cegueira em horas). Iniciar acetazolamida + pilocarpina + analgesia se possível e encaminhar."},
{nivel:"crit", txt:"USO DE LENTE DE CONTATO + olho vermelho = CERATITE BACTERIANA presuntiva (especialmente Pseudomonas). Suspender lente + oftalmo URGENTE. Pode causar perfuração córnea em horas-dias."},
{nivel:"crit", txt:"HERPES SIMPLEX CÓRNEA (padrão dendrítico em fluoresceína) — CORTICOIDE TÓPICO É PROIBIDO (acelera necrose). Aciclovir tópico + oftalmologia."},
{nivel:"warn", txt:"FENILEFRINA TESTE: episclerite/conjuntivite EMBRANQUECEM (superficial). Esclerite/uveíte NÃO empalidecem (profundo). Truque clássico que diferencia."},
{nivel:"warn", txt:"NUNCA prescrever corticoide tópico ocular em APS sem oftalmologista — glaucoma medicamentoso, reativação de herpes córnea, retardo cicatricial."},
{nivel:"warn", txt:"ANESTÉSICO TÓPICO em casa: PROIBIDO. Toxicidade epitelial, dependência, retardo cicatricial."},
{nivel:"info", txt:"VASOCONSTRITOR TÓPICO (Naphazolina, Vasocon) por curto prazo em olho vermelho banal é aceitável — não usar >3-5 dias (rebote)."},
],
fluxo:null, diretriz:"AAO. SBO. Wills Eye Manual."
},

/* ============== LAVAGEM OCULAR ============== */
{id:"pulo-lavagem-ocular", nome:"Lavagem ocular grande volume — cânula nasal invertida (Morgan caseira)", sis:"pulo", grav:"moderada",
cid:"T26", ciap:"F79",
sin:["Lavagem ocular","Queimadura química","Morgan lens","Cânula nasal lavagem"],
def:"EXPOSIÇÃO QUÍMICA OCULAR (cal, cimento, ácido, álcali, detergente concentrado) = URGÊNCIA — IRRIGAR IMEDIATAMENTE com SF/Ringer abundante. Sem lente de Morgan? CÂNULA NASAL INVERTIDA é alternativa (pontas vão para os olhos, conectada a equipo SF).",
quadro:["Acidente com cal, cimento, soda cáustica, ácido de bateria, hipoclorito, detergente industrial, cosméticos, água sanitária","Dor intensa, lacrimejamento, blefaroespasmo, hiperemia, redução AV","⚠ ÁLCALI (cal, soda, cimento) penetra MAIS profundamente que ácido — mais grave","SINAIS DE GRAVIDADE: queratite branca opaca, isquemia perilímbica, hifema, midríase, redução AV importante"],
diag:["Após irrigação inicial: AV, exame ocular completo","pH do fundo de saco (papel pH) — alvo 7,0-7,4","Fluoresceína para avaliar abrasão / úlcera"],
exames:["pH do fundo de saco (essencial)","Após estabilização: tonometria + exame oftalmológico completo"],
rx:[
{etapa:"inicial", d:"⚠ INICIAR IRRIGAÇÃO IMEDIATAMENTE — antes de exame detalhado, antes de aguardar tudo pronto"},
{etapa:"inicial", d:"OBJETIVO: 30 minutos OU 2-3 LITROS de SF/Ringer (ou água potável se SF indisponível)"},
{etapa:"inicial", d:"⚠ ANESTÉSICO TÓPICO PRIMEIRO se disponível (proparacaína colírio 0,5% 1-2 gotas)"},
{etapa:"escala", d:"⚠ TÉCNICA — opções por ordem de preferência:"},
{etapa:"escala", d:"OPÇÃO 1 — LENTE DE MORGAN (se disponível): lente de plástico tipo lente de contato com conexão para equipo. Padrão em PA."},
{etapa:"escala", d:"OPÇÃO 2 — CÂNULA NASAL INVERTIDA (improviso prático):"},
{etapa:"escala", d:"Pegar cânula nasal de O₂ comum (a com 'forquilha' para narinas)"},
{etapa:"escala", d:"VIRAR a cânula — as pontas que iam nas narinas ficam VOLTADAS PARA OS OLHOS do paciente"},
{etapa:"escala", d:"Conectar o conector da cânula em EQUIPO de SF (em vez de O₂)"},
{etapa:"escala", d:"SF 0,9% fluindo livre — irrigar AMBOS os olhos simultaneamente (ou um se for o caso)"},
{etapa:"escala", d:"Permite IRRIGAÇÃO CONTÍNUA hands-free — paciente em decúbito dorsal"},
{etapa:"escala", d:"OPÇÃO 3 — Seringa 60 mL + jato direto (mais artesanal)"},
{etapa:"escala", d:"OPÇÃO 4 — Banho/chuveiro: paciente sob fluxo contínuo, abrir pálpebras"},
{etapa:"adj", d:"⚠ AFASTAR pálpebras manualmente — paciente tem blefaroespasmo intenso. Usar dedos enluvados (sem pressão sobre globo ocular)"},
{etapa:"adj", d:"REMOVER CORPO ESTRANHO SÓLIDO antes/durante irrigação — cal em pedra, cimento, fragmentos. Cotonete molhado, pinça delicada"},
{etapa:"adj", d:"⚠ MEDIR pH cada 5-10 min APÓS irrigação contínua (tira de papel pH no fundo de saco)"},
{etapa:"adj", d:"ALVO: pH 7,0-7,4 estável por 5-10 min"},
{etapa:"adj", d:"Se pH não normalizar: continuar irrigação"},
{etapa:"adj", d:"⚠ ÁLCALI (cal, cimento, soda): irrigar MAIS TEMPO — penetra profundamente, retém"},
{etapa:"adj", d:"ANALGESIA sistêmica: dipirona/paracetamol + AINE"},
{etapa:"alta", d:"⚠ APÓS IRRIGAÇÃO: AVALIAR OFTALMOLOGIA URGENTE em todos os casos"},
{etapa:"alta", d:"Lubrificante ocular abundante (carmelose, lágrima artificial sem conservante)"},
{etapa:"alta", d:"ATB tópico profilático (tobramicina) se erosão corneana"},
{etapa:"alta", d:"ENCAMINHAR oftalmologia para avaliação detalhada — sequelas: cicatriz corneana, sinéquias, ceratoconjuntivite seca crônica, glaucoma secundário"},
],
alertas:[
{nivel:"crit", txt:"NÃO ATRASAR IRRIGAÇÃO — começar IMEDIATAMENTE, mesmo antes de exame ou aguardar SF morno. Minutos importam para evitar lesão permanente."},
{nivel:"crit", txt:"ÁLCALI > ÁCIDO em gravidade — penetra mais profundamente. Irrigar MAIS TEMPO em exposição a cal/cimento/soda."},
{nivel:"crit", txt:"AFASTAR PÁLPEBRAS — paciente em blefaroespasmo intenso. Anestésico tópico facilita. Sem pressão sobre globo."},
{nivel:"warn", txt:"CÂNULA NASAL INVERTIDA: alternativa simples e EFICAZ à lente de Morgan. Disponível em qualquer UBS."},
{nivel:"warn", txt:"REMOVER fragmentos sólidos durante/após irrigação inicial — cimento em pedra, cal seca."},
{nivel:"info", txt:"pH ALVO: 7,0-7,4 estável. Cada UBS deveria ter tiras de papel pH disponíveis."},
],
fluxo:null, diretriz:"AAO. Wills Eye Manual. EYE (oftalmo de emergência)."
},

/* ============== CATETERISMO VESICAL DIFÍCIL ============== */
{id:"pulo-cateter-dificil", nome:"Cateterismo vesical difícil — Coudé e técnica anatômica", sis:"pulo", grav:"moderada",
cid:"-", ciap:"-",
sin:["Sonda vesical difícil","Coudé","Cateter falhou","HPB cateter","Retenção urinária"],
def:"CATETER DE FOLEY que NÃO passa — geralmente em homem com HPB (próstata aumentada faz angulação no colo vesical). Soluções: (1) Posicionar pênis verticalmente; (2) sonda COUDÉ (ponta curva); (3) lubrificação abundante + lidocaína gel; (4) cistostomia se tudo falhar.",
quadro:["Cateterismo vesical indicado (retenção urinária aguda, monitor débito urinário, cirúrgico, pós-op)","Sonda Foley 16-18 Fr não progride após inserção parcial","Mais comum em: homem >50a com HPB, paciente com cirurgia uretral prévia, trauma uretral, estenose","⚠ TENTATIVAS REPETIDAS / FORÇADAS podem causar FALSO TRAJETO, hematúria, sepse"],
diag:["Avaliar próstata ao toque retal (em homem)","Investigar HPB, hiperplasia prostática, cirurgias prévias","Atenção em paciente com hematúria (CAVB?), urgência micccional, infecção"],
exames:["Avaliar próstata clinicamente","USG bexiga (se disponível) — confirma retenção, mede volume residual","Em cateterismo prolongado: cultura urinária"],
rx:[
{etapa:"inicial", d:"⚠ PREPARAR antes de tentar: sonda lubrificada + LIDOCAÍNA GEL 2% intrauretral (5-10 mL, aguardar 5 min)"},
{etapa:"escala", d:"⚠ TÉCNICA ANATÔMICA — passo a passo"},
{etapa:"escala", d:"(1) Paciente em decúbito dorsal, pernas afastadas"},
{etapa:"escala", d:"(2) Antissepsia da glande / uretra com PVPI ou clorexidina"},
{etapa:"escala", d:"(3) Lubrificação GENEROSA da sonda (gel lubrificante)"},
{etapa:"escala", d:"(4) ⚠ INSERIR LIDOCAÍNA GEL na uretra com seringa sem agulha (5-10 mL) — distende uretra + anestesia. Aguardar 3-5 min"},
{etapa:"escala", d:"(5) Posicionar PÊNIS EM ÂNGULO DE 90° (perpendicular ao abdome, apontando para o teto) — retifica a uretra"},
{etapa:"escala", d:"(6) Inserir sonda com pressão SUAVE E CONSTANTE — sem solavanco"},
{etapa:"escala", d:"(7) Ao sentir RESISTÊNCIA (geralmente na próstata ou no esfíncter externo): NÃO FORÇAR. PEDIR paciente a respirar fundo e relaxar (tossir libera esfíncter)"},
{etapa:"escala", d:"(8) Quando passar a próstata: ABAIXAR pênis para 45° + continuar inserção até urina FLUIR"},
{etapa:"escala", d:"(9) ASPIRAR balão SOMENTE após confirmar urina fluindo (não no meio do trajeto — falso trajeto, balão na uretra, ruptura)"},
{etapa:"adj", d:"⚠ SE FALHAR — SONDA COUDÉ (ponta curva)"},
{etapa:"adj", d:"Sonda Foley com ponta em ângulo de 30° — facilita passagem pela próstata aumentada"},
{etapa:"adj", d:"Inserir com a curva apontando para CIMA (na direção da próstata superior)"},
{etapa:"adj", d:"Geralmente disponível em hospitais — UBS pode não ter"},
{etapa:"adj", d:"⚠ AINDA FALHAR — CATETERISMO INTERMITENTE com sonda Nelaton 12-14 Fr (mais fina, sem balão)"},
{etapa:"adj", d:"Alivia retenção imediatamente. Depois encaminhar urologia"},
{etapa:"adj", d:"⚠ ÚLTIMO RECURSO — CISTOSTOMIA SUPRAPÚBICA"},
{etapa:"adj", d:"Indicação: retenção aguda + falha de cateterismo uretral + necessidade de drenagem"},
{etapa:"adj", d:"Técnica: punção suprapúbica com kit específico (cistofix) OU acesso percutâneo guiado por USG"},
{etapa:"adj", d:"Profissional treinado — emergência cirúrgica em UBS"},
{etapa:"adj", d:"⚠ HEMATÚRIA APÓS TENTATIVA: avaliar lesão uretral, falso trajeto. Encaminhar urologia"},
{etapa:"alta", d:"⚠ PÓS-PROCEDIMENTO: monitorizar débito urinário, hematúria, dor lombar"},
{etapa:"alta", d:"Retenção urinária aguda crônica (>1L de resíduo): risco de poliúria pós-obstrutiva — monitor"},
{etapa:"alta", d:"ENCAMINHAR UROLOGIA: paciente com HPB sintomática + retenção aguda — pode precisar RTU/cirurgia"},
{etapa:"alta", d:"⚠ EM CATETERISMO DIFÍCIL/RECORRENTE: alfa-bloqueador (tansulosina 0,4 mg/d) pode facilitar próxima tentativa após 7-14 dias"},
],
alertas:[
{nivel:"crit", txt:"NUNCA FORÇAR a sonda — risco de FALSO TRAJETO, ruptura uretral, sepse. Se resistência: parar, relaxar paciente, tentar Coudé ou cistostomia."},
{nivel:"crit", txt:"NUNCA INSUFLAR BALÃO antes de confirmar urina fluindo — pode estar na uretra, causar ruptura."},
{nivel:"warn", txt:"LIDOCAÍNA GEL intrauretral (5-10 mL, 5 min) reduz desconforto + relaxa esfíncter. Padrão moderno."},
{nivel:"warn", txt:"POSICIONAR PÊNIS A 90° (perpendicular) retifica uretra. Abaixar para 45° após passar próstata."},
{nivel:"warn", txt:"PACIENTE TRAUMA PÉLVICO/URETRAL: NÃO TENTAR cateterismo até excluir lesão uretral (sangue no meato, hematoma perineal). Uretrocistografia retrógrada + urologia."},
{nivel:"info", txt:"CISTOSTOMIA suprapúbica: kit Cystofix ou similar. Profissional treinado. Indicação: falha de cateterismo + retenção urgente."},
],
fluxo:null, diretriz:"EAU Guidelines. SBU. Roberts & Hedges."
},

/* ============== RETENÇÃO URINÁRIA — CREDÉ ============== */
{id:"pulo-crede", nome:"Retenção urinária — manobra de Credé / Valsalva miccional", sis:"pulo", grav:"moderada",
cid:"R33", ciap:"U08",
sin:["Retenção urinária","Manobra de Credé","Bexiga neurogênica","Valsalva miccional"],
def:"MANOBRA DE CREDÉ = compressão manual suprapúbica para esvaziar bexiga = útil em RETENÇÃO POR HIPOATIVIDADE DETRUSORA / BEXIGA NEUROGÊNICA, pós-cirúrgica, parto. ⚠ NÃO USAR se OBSTRUÇÃO (HPB, cálculo, tumor) — refluxo vesico-ureteral / lesão renal.",
quadro:["Retenção urinária aguda em paciente sem obstrução evidente (pós-parto, pós-cirurgia, anestesia, bexiga neurogênica, medicamentos anticolinérgicos)","Distensão suprapúbica + desejo miccional + incapacidade de urinar","⚠ EXCLUIR OBSTRUÇÃO antes — HPB com 'globo vesical' = cateterismo, NÃO Credé"],
diag:["Inspeção + palpação suprapúbica","USG bexiga: volume residual","Toque retal (próstata em homem)","Excluir: HPB, cálculo, infecção, estenose, tumor"],
exames:["USG bexiga (volume)","Urina I + cultura","Em homem: PSA, toque retal"],
rx:[
{etapa:"inicial", d:"⚠ AVALIAR ETIOLOGIA — Credé serve apenas para HIPOATIVIDADE detrusora (sem obstrução)"},
{etapa:"inicial", d:"CONTRAINDICAÇÕES: HPB, cálculo vesical, tumor, estenose uretral, refluxo vesicoureteral já conhecido"},
{etapa:"escala", d:"⚠ MANOBRA DE CREDÉ — apenas em paciente SEM obstrução"},
{etapa:"escala", d:"(1) Paciente sentado no vaso sanitário (postura miccional natural)"},
{etapa:"escala", d:"(2) Inclinar-se levemente para FRENTE"},
{etapa:"escala", d:"(3) Aplicar PRESSÃO MANUAL CONSTANTE SUPRAPÚBICA com as mãos espalmadas (não soco)"},
{etapa:"escala", d:"(4) Em direção INFERO-POSTERIOR (apontando para o sacro)"},
{etapa:"escala", d:"(5) Pressão por 30-60 SEGUNDOS — paciente respira normal e relaxa períneo"},
{etapa:"escala", d:"(6) Pode REPETIR várias vezes"},
{etapa:"adj", d:"⚠ MANOBRA DE VALSALVA MICCIONAL — alternativa/adjunta"},
{etapa:"adj", d:"Paciente sentado, inclinado para frente"},
{etapa:"adj", d:"RESPIRA FUNDO + PRENDE + 'EMPURRA' como se fosse evacuar"},
{etapa:"adj", d:"Combina-se com Credé"},
{etapa:"adj", d:"⚠ ESTIMULOS COMPLEMENTARES:"},
{etapa:"adj", d:"Som de água corrente (torneira, descarga)"},
{etapa:"adj", d:"Compressa morna suprapúbica"},
{etapa:"adj", d:"Imersão da mão em água morna (reflexo gastrocólico-vesical)"},
{etapa:"adj", d:"Relaxamento perineal — respiração profunda"},
{etapa:"adj", d:"⚠ SE PERSISTIR RETENÇÃO + sintomas + volume residual significativo: cateterismo (intermitente ou demora)"},
{etapa:"adj", d:"Após resolução: investigar causa — bexiga neurogênica, neuropatia diabética, medicamentos (anticolinérgicos, opioides, antidepressivos tricíclicos)"},
{etapa:"alta", d:"⚠ EVITAR CREDÉ em paciente com BEXIGA NEUROGÊNICA + DSSE (dissinergia detrusor-esfincteriana) — pode causar refluxo vesico-ureteral e lesão renal. Avaliar urodinâmica"},
{etapa:"alta", d:"ENCAMINHAR UROLOGIA: retenções recorrentes, suspeita de bexiga neurogênica, HPB sintomática"},
{etapa:"alta", d:"REVISAR MEDICAÇÕES com efeito anticolinérgico/retenção: amitriptilina, oxibutinina, anti-histamínicos, opioides, descongestionantes (pseudoefedrina), antiparkinsonianos"},
],
alertas:[
{nivel:"crit", txt:"CREDÉ É CONTRAINDICADO em obstrução baixa (HPB, cálculo, tumor, estenose) — risco refluxo vesico-ureteral e lesão renal. EXCLUIR obstrução antes."},
{nivel:"warn", txt:"BEXIGA NEUROGÊNICA com DISSINERGIA detrusor-esfincteriana: Credé pode causar refluxo + lesão renal alta — urologia + urodinâmica."},
{nivel:"warn", txt:"PRESSÃO SUPRAPÚBICA: mãos ESPALMADAS, direção ínfero-posterior (para sacro). NÃO socar."},
{nivel:"info", txt:"COMBINAR Credé + Valsalva + estímulos auxiliares (água corrente, calor) aumenta taxa de sucesso."},
{nivel:"info", txt:"CAUSAS MEDICAMENTOSAS de retenção: anticolinérgicos, opioides, antidepressivos tricíclicos, anti-histamínicos, pseudoefedrina."},
],
fluxo:null, diretriz:"EAU Guidelines. SBU. Bexiga neurogênica protocols."
},

);
