/* ===========================================================
   VOVÔMINIC EMERGÊNCIA — DADOS CLÍNICOS PARTE 5
   Tier 1: Obstetrícia + Cardio extras + Neuro extras + Trauma + Outras críticas
   =========================================================== */

PATOLOGIAS.push(

/* ============== OBSTETRÍCIA ============== */
{id:"pre-eclampsia", sis:"obst", grav:"alta",
nome:"Pré-eclâmpsia / Eclâmpsia / HELLP",
sin:["pré-eclampsia","eclampsia","HELLP","DHEG"],
def:"PE = HAS (PA ≥140×90) APÓS 20 sem + proteinúria OU disfunção orgânica. PE grave = PAS ≥160 ou PAD ≥110 + sintomas (cefaleia, escotomas, dor HCD, oligúria, edema agudo pulmão). Eclâmpsia = + crise convulsiva. HELLP = Hemólise + ↑enzimas hepáticas + ↓plaquetas (<100k).",
exames:["PA seriada","Proteinúria fita/24h","Hemograma (esquistócitos), plaquetas","TGO/TGP, bilirrubinas, LDH, haptoglobina","Ureia/Cr, ácido úrico","Coagulograma","CTG fetal + USG obstétrico"],
rx:[
{etapa:"escala", d:"Sulfato de Magnésio (Pritchard)",do:"ATAQUE: 4 g IV em 20 min + 10 g IM (5 g cada glúteo). MANUTENÇÃO: 5 g IM 4/4h",via:"IV+IM",o:"PE grave + eclâmpsia. Manter 24h pós-parto ou pós-última crise."},
{etapa:"escala", d:"Sulfato de Magnésio (Zuspan)",do:"ATAQUE: 4-6 g IV em 20 min. MANUTENÇÃO: 1-2 g/h IV BIC",via:"IV",o:"Mais fisiológico. Antídoto: gluconato de cálcio 10% 10 mL IV se intoxicação."},
{etapa:"escala", d:"Hidralazina",do:"5 mg IV bolus, repetir 5-10 mg 20/20 min (máx 30 mg)",via:"IV",o:"1ª linha emergência hipertensiva gestacional. Meta: PAS 140-160, PAD 90-100."},
{etapa:"escala", d:"Nifedipino",do:"10 mg VO, repetir 20/20 min (máx 50 mg)",via:"VO",o:"Alternativa à hidralazina. Não usar sublingual."},
{etapa:"escala", d:"Labetalol",do:"20 mg IV bolus, dobrar dose 10/10 min (máx 300 mg)",via:"IV",o:"Onde disponível — 1ª linha em alguns serviços."},
{etapa:"escala", d:"Betametasona",do:"12 mg IM 24/24h × 2 doses",via:"IM",o:"Maturação pulmonar fetal — gestação 24-34 sem."},
{etapa:"escala", d:"Parto",do:"Interrupção da gestação",via:"Obstétrico",o:"TRATAMENTO DEFINITIVO. PE grave ≥34 sem ou HELLP ou eclâmpsia → resolução."},
],
alertas:[
{t:"crit",x:"Eclâmpsia é DIAGNÓSTICO CLÍNICO — crise tônico-clônica em gestante/puérpera. Sulfato Mg é a 1ª droga, NÃO BZD/fenitoína."},
{t:"crit",x:"HELLP pode ocorrer SEM hipertensão prévia. Dor em HCD/epigástrio + náusea + AST alta em gestante → suspeitar."},
{t:"warn",x:"PE pode evoluir até 6 SEMANAS pós-parto. Eclâmpsia tardia existe."},
{t:"warn",x:"Sinais de intoxicação por Mg: arreflexia patelar (precoce), FR <12, oligúria <100 mL/4h. Suspender Mg, antídoto Ca."},
],
fisio:"Doença trofoblástica — placentação anormal com remodelamento inadequado das artérias espiraladas → isquemia placentária → liberação de fatores antiangiogênicos (sFlt-1, endoglina) que neutralizam VEGF/PlGF → disfunção endotelial sistêmica. Resultado: <strong>vasoespasmo + permeabilidade vascular + ativação plaquetária + microangiopatia trombótica</strong>. Manifesta-se como HAS + proteinúria + lesão de órgão-alvo. HELLP é a expressão hepato-hematológica. Eclâmpsia provavelmente é encefalopatia hipertensiva + vasoespasmo + edema vasogênico (PRES).",
mec:[
{d:"Sulfato de Magnésio", x:"<strong>Não é anticonvulsivante convencional</strong>. Atua como antagonista de NMDA, bloqueia liberação de glutamato, causa vasodilatação cerebral seletiva, reduz edema vasogênico e estabiliza membrana neuronal. Reduz risco de eclâmpsia em 58% (Magpie trial)."},
{d:"Hidralazina", x:"Vasodilatador arteriolar direto — abre canais de K⁺ no músculo liso → hiperpolarização. Reduz RVP sem comprometer fluxo útero-placentário."},
{d:"Betametasona", x:"Corticoide atravessa placenta, ↑surfactante pulmonar fetal e reduz síndrome do desconforto respiratório do RN em ~50%."},
],
diretriz:"FEBRASGO 2020 — Manual de Pré-eclâmpsia. ACOG Practice Bulletin 222 (Gestational Hypertension and Preeclampsia, Obstet Gynecol 2020;135:e237). ISSHP 2021 (DOI:10.1097/HJH.0000000000002889).",
fluxo:null,
calcs:[],
},

{id:"hpp", sis:"obst", grav:"alta",
nome:"Hemorragia Pós-Parto (HPP)",
sin:["HPP","hemorragia puerperal","atonia uterina"],
def:"Perda sanguínea ≥500 mL pós-parto vaginal ou ≥1000 mL pós-cesárea, OU qualquer sangramento com sinais de instabilidade. Precoce: <24h (90%, atonia). Tardia: 24h-12 semanas.",
exames:["SSVV continuamente","Hemograma seriado","Coagulograma + fibrinogênio (alvo >2 g/L)","Lactato, gaso arterial","Tipo sanguíneo + Rh + prova cruzada"],
rx:[
{etapa:"inicial", d:"Massagem uterina bimanual",do:"Contínua",via:"—",o:"1ª medida sempre. Compressão externa + intracavitária."},
{etapa:"escala", d:"Ocitocina",do:"10 UI IM + 20-40 UI em 500 mL SF/RL IV em 1h",via:"IV+IM",o:"1ª linha medicamentosa. CONTÍNUO até cessar."},
{etapa:"escala", d:"Misoprostol",do:"800-1000 mcg retal OU 600 mcg VO/SL",via:"Retal/VO",o:"Se ocitocina indisponível/falha. Pode causar tremor + hipertermia."},
{etapa:"escala", d:"Metilergometrina",do:"0,2 mg IM, pode repetir 2-4h (máx 5 doses)",via:"IM",o:"CONTRAINDICADA em hipertensão, pré-eclâmpsia, cardiopatia."},
{etapa:"escala", d:"Ácido Tranexâmico",do:"1 g IV em 10 min, repetir em 30 min se sangramento ativo (WOMAN trial)",via:"IV",o:"Idealmente nas primeiras 3h. Reduz mortalidade materna em 31%."},
{etapa:"escala", d:"Balão de Bakri / sonda Foley",do:"Insuflar 250-500 mL SF",via:"Intrauterino",o:"Tamponamento — se atonia refratária à medicação."},
{etapa:"escala", d:"Cirurgia",do:"Sutura B-Lynch / ligadura uterinas / histerectomia",via:"Cirúrgico",o:"Falha do tamponamento — chamar obstetra imediato."},
{etapa:"escala", d:"Hemocomponentes",do:"Protocolo de hemorragia maciça 1:1:1 (CH:PFC:plaq)",via:"IV",o:"Manter Hb >7, plaq >50k, fibrinogênio >2 g/L. CH se choque/Hb<7."},
],
alertas:[
{t:"crit",x:"4 T's da HPP — TÔNUS (atonia 70%), TRAUMA (laceração 20%), TECIDO (retenção placentária 10%), TROMBINA (coagulopatia <1%). Identificar e tratar a causa."},
{t:"crit",x:"Choque hipovolêmico em gestante MASCARA — gestantes compensam até 30-40% de perda. Hipotensão é tardia."},
{t:"warn",x:"Ácido tranexâmico — TIME IS LIFE. Cada 15 min de atraso ↓5% benefício. Administrar SEMPRE em HPP com sangramento ativo."},
],
fisio:"Após dequitação, a hemostasia uterina depende primariamente da contração miometrial que comprime os vasos espiralados das artérias uterinas (ligaduras vivas de Pinard). A atonia uterina (70-80% das HPPs) ocorre por: trabalho de parto prolongado, macrossomia, multíparas, corioamnionite, uso de tocolíticos. Outras causas: lacerações vias baixas, retenção placentária, coagulopatia (CIVD, von Willebrand não diagnosticado, descolamento prévio). A perda sanguínea aguda em gestante leva a CIVD por consumo, agravando o quadro.",
mec:[
{d:"Ocitocina",x:"Análogo do hormônio natural — liga-se a receptores de ocitocina no miométrio (densidade ↑↑ no termo) → ativação de Gq → ↑IP3/Ca²⁺ → contração. <strong>Saturável</strong>: doses muito altas não aumentam efeito e podem causar ↓PA, hiponatremia, taquicardia."},
{d:"Misoprostol",x:"Análogo de PGE1 — contração miometrial direta + amadurecimento cervical. Custo baixo, termoestável (uso em campo)."},
{d:"Metilergometrina",x:"Alcaloide do ergot — agonista parcial de receptores α-adrenérgicos e serotoninérgicos → contração uterina <strong>tetânica</strong>. Risco de vasoespasmo sistêmico (HAS, IAM)."},
{d:"Ácido Tranexâmico",x:"Análogo da lisina — bloqueia sítios de ligação da lisina no plasminogênio → inibe ativação para plasmina → reduz fibrinólise. Não é pró-trombótico de forma significativa em doses terapêuticas."},
],
diretriz:"FIGO 2022 (Escobar MF et al., Int J Gynecol Obstet 2022;157:3). WOMAN Trial (Lancet 2017;389:2105, DOI:10.1016/S0140-6736(17)30638-4). MS — Manual Obstetrícia de Alto Risco.",
fluxo:null,
calcs:[],
},

{id:"ectopica", sis:"obst", grav:"alta",
nome:"Gestação Ectópica",
sin:["ectopica","gestação tubária","gravidez tubária"],
def:"Implantação embrionária fora da cavidade uterina (95% tubária). Tríade clássica: atraso menstrual + sangramento vaginal + dor pélvica. Suspeitar em TODA mulher fértil com dor abdominal — β-hCG é OBRIGATÓRIO.",
exames:["β-hCG quantitativo seriado","USG transvaginal","Hemograma + tipagem","Função renal e hepática (pré-MTX)"],
rx:[
{etapa:"escala", d:"Conduta expectante",do:"Seguimento β-hCG h/48h",via:"—",o:"Apenas se: β-hCG <1000-2000 e em queda, paciente estável, sem sangramento livre."},
{etapa:"escala", d:"Metotrexato (MTX)",do:"1 mg/kg IM (dose única) OU 50 mg/m² IM",via:"IM",o:"Critérios: estável, sem ruptura, β-hCG <5000, massa <3,5 cm, sem BCF, função renal/hepática normal. Acompanhamento D4 e D7 — esperado ↓15% em 4-7 dias."},
{etapa:"escala", d:"Salpingostomia/Salpingectomia laparoscópica",do:"—",via:"Cirúrgico",o:"Ruptura, instabilidade, falha de MTX, β-hCG alto, BCF presente, massa grande."},
{etapa:"escala", d:"Hemocomponentes",do:"CH se Hb <7 ou choque",via:"IV",o:"Anti-D 300 mcg IM se Rh-negativa."},
],
alertas:[
{t:"crit",x:"Ectópica ROTA: choque hipovolêmico + Blumberg + sinal de Cullen/Laffont + dor referida ombro (sangue subdiafragmático) → laparotomia/laparoscopia URGENTE."},
{t:"crit",x:"β-hCG ZONA DISCRIMINATÓRIA: USG transvaginal deve mostrar saco gestacional intrauterino quando β-hCG >2000 mUI/mL. Ausência = ectópica até prova contrária."},
{t:"warn",x:"Gestação heterotópica (1:30.000 espontânea, 1:100 em FIV) — não exclui ectópica só porque há gestação tópica."},
],
fisio:"95% tubária (ampolar 70%, ístmica 12%, fimbriada 11%); raras: cornual, ovariana, cervical, cicatriz cesárea, abdominal. Fatores de risco: DIP prévia (PID), tabagismo, FIV/inseminação, DIU in situ, cirurgia tubária, ectópica prévia (recorrência 10-15%). A tuba não tem submucosa nem decidualização — o trofoblasto invade direto a muscular → ruptura em 6-10 sem. A ruptura gera hemoperitônio com choque hipovolêmico clássico.",
mec:[
{d:"Metotrexato",x:"Antagonista do ácido fólico — inibe <strong>dihidrofolato redutase</strong>, bloqueando síntese de purinas/timidina → impede replicação celular. Atua preferencialmente em células com alta proliferação (trofoblasto). Pré-medicar com leucovorina pode mitigar mucosite/mielotoxicidade."},
],
diretriz:"FEBRASGO 2018. ACOG Practice Bulletin 193 — Tubal Ectopic Pregnancy (Obstet Gynecol 2018;131:e91). NICE Ectopic Pregnancy 2019 (NG126).",
fluxo:null,
calcs:[],
},

{id:"aborto", sis:"obst", grav:"media",
nome:"Aborto / Sangramento 1º Trimestre",
sin:["aborto","sangramento gestacional","ameaça aborto","aborto incompleto","aborto infectado"],
def:"Sangramento vaginal <22 sem ou feto <500 g. Tipos: ameaça (colo fechado + BCF+); inevitável (colo aberto); incompleto (restos); completo (vazio); retido (sem BCF); infectado (febre + secreção fétida).",
exames:["β-hCG","USG transvaginal","Hemograma","Coagulograma (se sangramento volumoso)","Tipagem ABO/Rh"],
rx:[
{etapa:"inicial", d:"Ameaça",do:"Repouso relativo + abstinência sexual",via:"—",o:"Sem evidência de progesterona. Reavaliação USG em 7-10 dias."},
{etapa:"escala", d:"Aborto incompleto/inevitável <12 sem",do:"Misoprostol 600-800 mcg vaginal dose única",via:"Vaginal",o:"OU AMIU (até 12 sem) OU expectante (estável, sem infecção)."},
{etapa:"escala", d:"Aborto retido",do:"Misoprostol 800 mcg vaginal 3/3h × 2-3 doses",via:"Vaginal",o:"OU curetagem se >12 sem ou sangramento."},
{etapa:"escala", d:"Aborto infectado",do:"Ampicilina 2g IV 6/6h + Gentamicina 1,5 mg/kg 8/8h + Metronidazol 500 mg IV 8/8h + Curetagem URGENTE após 1ª dose",via:"IV",o:"Após 48h afebril → VO 7-10 dias. Risco de sepse, perfuração, choque tóxico."},
{etapa:"escala", d:"Imunoglobulina anti-D",do:"300 mcg IM em até 72h",via:"IM",o:"TODAS Rh-negativas com sangramento ou aborto."},
],
alertas:[
{t:"crit",x:"Aborto infectado: febre + dor + secreção fétida + sangramento. Pode evoluir para sepse (clostridial, gram-negativos). ATB + esvaziamento URGENTE, NÃO atrasar."},
{t:"warn",x:"Aborto provocado clandestino: alta morbimortalidade. Acolher SEM julgamento — Brasil tem amparo legal nas 3 hipóteses (anencefalia, risco materno, estupro)."},
{t:"info",x:"Aborto legal NÃO precisa de BO. Risco de vida vida = qualquer médico. Estupro = palavra da mulher (Lei 12.845/2013)."},
],
fisio:"Etiologias: cromossomopatias (50%, anomalia mais comum), trombofilia (SAAF), endocrinopatia (insuficiência lútea, hipotireoidismo), uterina (sinéquias, septo, miomas submucosos), infecção (sífilis, TORCH), imunológica. Repetição (≥2-3 abortos) → investigação. <strong>Sangramento de 1º trimestre acontece em 25% das gestações, metade aborta</strong>.",
mec:[
{d:"Misoprostol",x:"Análogo PGE1 — amolece colo + contração uterina. Via vaginal tem biodisponibilidade superior à VO para esvaziamento (Cmax mais sustentado)."},
],
diretriz:"MS — Atenção humanizada ao abortamento (Norma Técnica 2014). FEBRASGO Aborto 2021. WHO Abortion Care Guideline 2022.",
fluxo:null,
calcs:[],
},

{id:"dip", sis:"obst", grav:"media",
nome:"Doença Inflamatória Pélvica (DIP)",
sin:["DIP","DIPA","salpingite","abscesso tubo-ovariano"],
def:"Infecção ascendente do trato genital feminino — endometrite + salpingite ± abscesso tubo-ovariano + peritonite pélvica. Critérios mínimos CDC (1 basta): dor à mobilização do colo OU dor anexial OU dor uterina à palpação bimanual.",
exames:["β-hCG (sempre)","Hemograma, PCR","Cultura endocervical (gonococo + clamídia)","USG/TC pélvica","Sorologia HIV, sífilis, hepatites"],
rx:[
{etapa:"atb", d:"Ambulatorial — Ceftriaxona + Doxiciclina + Metronidazol",do:"500 mg IM dose única + 100 mg 12/12h × 14 dias + 500 mg 12/12h × 14 dias",via:"IM+VO",o:"DIP leve-moderada, estável, sem ATB, gestação excluída."},
{etapa:"atb", d:"Hospitalar — Ceftriaxona + Doxiciclina + Metronidazol",do:"1 g IV/d + 100 mg IV 12/12h + 500 mg IV 8/8h",via:"IV",o:"Indicações: gravidez, abscesso, falha ambulatorial, vômitos, intolerância VO, dúvida diagnóstica, adolescente."},
{etapa:"escala", d:"Drenagem do ATO",do:"Punção USG-guiada ou laparoscópica",via:"—",o:"Abscesso >7 cm, falha ATB 48-72h, ruptura suspeita."},
],
alertas:[
{t:"crit",x:"Abscesso TUBO-OVARIANO ROTO = peritonite + sepse → cirurgia urgente. Mortalidade 5-10%."},
{t:"warn",x:"DIP por DIU recém-inserido (<3 sem) — RETIRAR o DIU. Após 3 semanas, decisão individualizada (DIU pode ser mantido se boa resposta ATB)."},
{t:"info",x:"Síndrome de Fitz-Hugh-Curtis: peri-hepatite por DIP (cordas em violino na laparoscopia). Dor em HCD + DIP."},
],
fisio:"Patógenos: gonococo e clamídia (40-50% combinados), aeróbios (E. coli, S. aureus), anaeróbios (Bacteroides, Peptococcus), micoplasma genitalium. A infecção ascende do colo → endométrio → tubas → peritônio. Sequelas: infertilidade tubária (12% após 1 episódio, 50% após 3), dor pélvica crônica, ectópica (×6-10).",
mec:[
{d:"Ceftriaxona",x:"Cobre gonococo (cepas resistentes a quinolonas). Dose única 500 mg adequada para erradicação cervical."},
{d:"Doxiciclina",x:"Tetraciclina — inibe síntese proteica (30S). Excelente para clamídia (intracelular, longa duração de TTO necessária)."},
{d:"Metronidazol",x:"Anaeróbio + tricomonas. Ativação por redução do grupo nitro em ambiente anaeróbio → radicais que danificam DNA."},
],
diretriz:"CDC STI Treatment Guidelines 2021 (MMWR Recomm Rep 2021;70:1). PCDT-IST MS 2022.",
fluxo:null,
calcs:[],
},

{id:"torcao-anexo", sis:"obst", grav:"alta",
nome:"Torção de Anexo Ovariano",
sin:["torção ovariana","torção anexial"],
def:"Rotação do ovário/tuba no pedículo vascular → isquemia. Dor pélvica unilateral SÚBITA + náusea + vômito + massa anexial. Mulheres em idade reprodutiva; pico aos 20-30 anos e na infância.",
exames:["β-hCG","USG transvaginal com doppler (whirlpool sign, ↓fluxo)","Hemograma","Função renal/eletrólitos","TC se diagnóstico incerto"],
rx:[
{etapa:"escala", d:"Cirurgia URGENTE",do:"Laparoscopia + destorção ovariana",via:"Cirúrgico",o:"PRESERVAR o ovário sempre que possível (mesmo aparentemente necrótico — recupera em 80%). NÃO ooforectomizar de rotina."},
{etapa:"inicial", d:"Analgesia",do:"Dipirona 2g + Tramadol 100mg IV (não mascara)",via:"IV",o:"Acesso venoso + dieta zero enquanto aguarda cirurgia."},
],
alertas:[
{t:"crit",x:"DOPPLER NORMAL NÃO EXCLUI torção (vascularização dual ovariana). Diagnóstico é CLÍNICO + cirúrgico."},
{t:"crit",x:"Janela de viabilidade: ~24-36h. Cada hora conta. NÃO postergar cirurgia para 'tentar conservador'."},
{t:"info",x:"Massa anexial >5 cm é o maior fator de risco. Gestação (corpo lúteo), tumores ovarianos benignos (teratoma) são causas comuns."},
],
fisio:"Em ovários normais, o ligamento útero-ovárico curto e a tuba estabilizam. Cisto/tumor cria 'pêndulo' que pode torcer com movimento brusco/Valsalva. A torção do pedículo bloqueia retorno venoso primeiro (edema, congestão), depois fluxo arterial (isquemia, necrose). Manobra de Adler-Hellin: trompa edemaciada e congesta + ovário azulado/violáceo na laparoscopia.",
mec:[],
diretriz:"ACOG Practice Bulletin 174 — Evaluation and Management of Adnexal Masses (Obstet Gynecol 2016;128:e210). SBMR Imagem 2020.",
fluxo:null,
calcs:[],
},

/* ============== CARDIO EXTRAS ============== */
{id:"sincope", sis:"cardio", grav:"media",
nome:"Síncope",
sin:["síncope","desmaio","perda transitória de consciência","lipotimia"],
def:"Perda transitória de consciência por hipoperfusão cerebral global, súbita, breve (<5 min), com recuperação completa espontânea. 3 grandes grupos: REFLEXA (60%), ORTOSTÁTICA (15%), CARDIOGÊNICA (10-30%). Excluir convulsão, AVC, TCE.",
exames:["ECG 12 derivações","Glicemia capilar","HMG, troponina (se cardiogênica suspeita)","β-HCG mulher fértil","Eletrólitos","Manobra ortostática (HipoTA = ↓PAS ≥20 ou PAD ≥10 em 3 min em pé)"],
rx:[
{etapa:"escala", d:"REFLEXA (vasovagal)",do:"Orientações: hidratação, manobras de contrapressão, sair de gatilhos",via:"—",o:"Boa evolução. β-bloq podem ser tentados se recorrente."},
{etapa:"escala", d:"ORTOSTÁTICA",do:"Suspender hipotensores se possível + hidratação + meias compressivas",via:"—",o:"Fludrocortisona 0,1 mg/d ou midodrina 5-10 mg 8/8h em refratários."},
{etapa:"escala", d:"CARDIOGÊNICA",do:"Internação + monitorização contínua + tratamento da causa",via:"IV",o:"Marcapasso provisório se BAV avançado/sinusal grave. CDI em arritmia ventricular."},
],
alertas:[
{t:"crit",x:"BANDEIRAS VERMELHAS (alto risco — internação): síncope sentado ou em esforço, palpitações antes, história familiar de morte súbita, cardiopatia conhecida, sopro novo, ECG anormal, idade >65a, lesão grave, instabilidade hemodinâmica."},
{t:"warn",x:"Diferenciar SÍNCOPE de CRISE CONVULSIVA — convulsão tem aura, fase tônico-clônica >10s, confusão pós, mordedura lateral de língua, incontinência. Síncope tem mioclonias breves (<10s) sem confusão pós-ictal."},
{t:"info",x:"San Francisco Syncope Rule (CHESS): ICC História, Hto<30, ECG anormal, Shortness of breath, PAS<90. Qualquer = alto risco."},
],
fisio:"Cérebro depende de fluxo constante (~50 mL/100g/min). Interrupção >6-8s já causa LOC. Mecanismos: (1) REFLEXA — eferência vagal súbita (vasovagal, situacional, do seio carotídeo) → bradicardia + vasodilatação; (2) ORTOSTÁTICA — falha autonômica (DM, Parkinson, drogas) ou volume baixo; (3) CARDIOGÊNICA — arritmia (bradi/taqui) ou obstrutiva (EAo, MCH, TEP, dissecção, tamponamento, mixoma).",
mec:[],
diretriz:"ESC 2018 Syncope (Brignole M et al., Eur Heart J 2018;39:1883, DOI:10.1093/eurheartj/ehy037). AHA 2017 (Shen WK et al., Circulation 2017;136:e60).",
fluxo:null,
calcs:[],
},

{id:"pericardite", sis:"cardio", grav:"media",
nome:"Pericardite Aguda / Tamponamento",
sin:["pericardite","tamponamento","derrame pericárdico"],
def:"Pericardite: dor torácica pleurítica (alivia inclinado p/ frente, piora em supino) + atrito pericárdico + ECG (supra ST côncavo difuso + infra PR) + derrame pericárdico (ECO). Tamponamento: dor + Beck (hipotensão + bulhas abafadas + estase jugular) + pulso paradoxal >10 mmHg.",
exames:["ECG (supra ST côncavo + infra PR difusos)","RX tórax (coração em moringa se derrame grande)","Ecocardiograma (CRÍTICO)","HMG, PCR, troponina, função renal","Hemocultura se febril, autoanticorpos se suspeita autoimune","HIV, TB se fator de risco"],
rx:[
{etapa:"escala", d:"AINE — Ibuprofeno",do:"600-800 mg VO 8/8h × 1-2 sem (depois desmame)",via:"VO",o:"1ª linha pericardite aguda. AAS 750-1000 mg 8/8h se pós-IAM."},
{etapa:"escala", d:"Colchicina",do:"0,5 mg VO 12/12h (>70 kg) ou 0,5 mg/d (<70 kg) × 3 meses",via:"VO",o:"COMBINAR com AINE — reduz recidiva (ICAP trial, 50% ↓ recorrência)."},
{etapa:"escala", d:"Pericardiocentese",do:"Punção subxifoide ou para-apical, ECO-guiada",via:"—",o:"TAMPONAMENTO — emergência. NÃO esperar ECO formal se Beck completo + instável."},
{etapa:"adj", d:"Corticoide",do:"Prednisona 0,2-0,5 mg/kg/d × 2-4 sem com desmame",via:"VO",o:"Apenas em refratários, autoimunes, urêmica, TB tratada. Evitar 1ª linha (↑ recidiva)."},
],
alertas:[
{t:"crit",x:"TAMPONAMENTO é diagnóstico CLÍNICO + ECO. Pulso paradoxal + colapso de câmaras direitas no ECO. Pericardiocentese SALVA VIDA — não esperar laboratório/RX."},
{t:"crit",x:"DIFERENCIAR de SCA: supra ST difuso CÔNCAVO (pericardite) vs convexo localizado (IAM); infra PR (pericardite) vs Q (IAM); sem reciprocidade na pericardite."},
{t:"warn",x:"Etiologia: viral/idiopática 80%, urêmica, TB (BR), neoplásica, autoimune (LES), pós-IAM (Dressler), pós-pericardiectomia."},
],
fisio:"Inflamação pericárdica → líquido seroso/serossanguinolento/purulento no saco pericárdico. Pequeno acúmulo gradual → tolerado (até 1-2 L). Acúmulo rápido (mesmo 100-200 mL) → tamponamento (a serosa não distende rápido). O ↑pressão intrapericárdica colaba átrios → ↓retorno venoso → ↓débito → choque obstrutivo. Pulso paradoxal: queda inspiratória de PAS >10 mmHg por exagero da interdependência ventricular.",
mec:[
{d:"AINE",x:"Inibe COX → ↓PG → ↓inflamação pericárdica. Cuidado em pós-IAM (pode prejudicar remodelamento) — preferir AAS."},
{d:"Colchicina",x:"Liga-se à tubulina → impede polimerização de microtúbulos → bloqueia migração de neutrófilos e ativação do inflamassoma NLRP3 (relevante na pericardite recorrente). Custa pouco, alta evidência."},
],
diretriz:"ESC 2015 Pericardial Diseases (Adler Y et al., Eur Heart J 2015;36:2921, DOI:10.1093/eurheartj/ehv318). ICAP Trial (Imazio M et al., NEJM 2013;369:1522).",
fluxo:null,
calcs:[],
},

{id:"endocardite", sis:"cardio", grav:"alta",
nome:"Endocardite Infecciosa",
sin:["endocardite","EI","Duke","Osler"],
def:"Infecção do endotélio valvar/intracardíaco — febre + sopro novo + fenômenos embólicos/imunológicos. Diagnóstico por critérios de Duke modificados (2 maiores; 1 maior + 3 menores; 5 menores).",
exames:["Hemoculturas (3 PARES, em momentos diferentes, ANTES do ATB)","ECO transtorácico (ETT) — se negativo + suspeita alta → transesofágico (ETE)","Hemograma, PCR, VHS, função renal","Sorologia para Bartonella, Coxiella, Brucella se hemocultura negativa","TC tórax/abdome para êmbolos","Avaliação dentária"],
rx:[
{etapa:"atb", d:"Vancomicina + Gentamicina (empírico — válvula nativa)",do:"15-20 mg/kg 12/12h + 1 mg/kg 8/8h",via:"IV",o:"Aguardando hemocultura. Ajustar conforme isolado."},
{etapa:"atb", d:"Vancomicina + Gentamicina + Rifampicina (próteses)",do:"15-20 mg/kg 12/12h + 1 mg/kg 8/8h + 300-450 mg 12/12h",via:"IV",o:"Próteses cardíacas / S. epidermidis."},
{etapa:"atb", d:"S. aureus oxa-sensível",do:"Oxacilina 12 g/d (2 g 4/4h)",via:"IV",o:"× 4-6 semanas. Penicilínicos podem ter associação curta de gentamicina (3-5 dias)."},
{etapa:"escala", d:"S. viridans",do:"Penicilina G 18-24 milhões UI/d ou Ceftriaxona 2 g/d",via:"IV",o:"× 4 semanas. Pode ser feita ambulatorialmente em casos selecionados."},
{etapa:"escala", d:"Cirurgia",do:"Troca valvar",via:"Cirúrgico",o:"Indicações: IC refratária, êmbolos recorrentes apesar de ATB, vegetação >10 mm, abscesso anular, prótese disfuncional, gérmen agressivo (fungo, S. aureus prótese)."},
],
alertas:[
{t:"crit",x:"COLHER hemoculturas ANTES do ATB. 3 pares com pelo menos 1h de intervalo. Sem isso, perde-se a etiologia em 30-50% dos casos."},
{t:"crit",x:"EI em USUÁRIO DE DROGAS IV — geralmente direita (tricúspide), S. aureus. Suspeitar em qualquer febre + comportamento."},
{t:"warn",x:"Profilaxia ATB (amoxi 2g 1h antes) apenas em cardiopatia de alto risco (próteses, EI prévia, congênita cianótica/recém-corrigida) + procedimento dentário com sangramento."},
],
fisio:"Endotélio valvar lesado (turbulência, prótese, dano reumático) → fibrina + plaquetas depositam (vegetação asséptica) → bacteremia (extração dental, IV, GI/GU) → colonização → vegetação infectada → embolização, lesão valvar progressiva, disseminação metastática (cérebro, baço, rim, ossos). Agentes: S. aureus (atualmente o mais comum, agressivo), Streptococcus viridans (dental), enterococos, HACEK, fungos (debilitados, próteses).",
mec:[
{d:"Vancomicina",x:"Glicopeptídeo — liga-se ao terminal D-Ala-D-Ala do peptideoglicano → impede transpeptidação → lise. Cobre MRSA, Enterococcus (não-VRE)."},
{d:"Gentamicina",x:"Aminoglicosídeo — liga-se a 30S → erros de leitura. Sinergia com β-lactâmicos contra enterococos e estreptococos (entra mais fácil)."},
{d:"Rifampicina",x:"Inibe RNA polimerase bacteriana → impede transcrição. Penetra biofilme (essencial em próteses). NUNCA em monoterapia (resistência rápida)."},
],
diretriz:"ESC 2023 Endocarditis Guidelines (Delgado V et al., Eur Heart J 2023;44:3948, DOI:10.1093/eurheartj/ehad193). AHA 2015. Diretriz SBC EI 2019.",
fluxo:null,
calcs:[],
},

);
