/* ===========================================================
   VOVÔMINIC EMERGÊNCIA — DADOS CLÍNICOS PARTE 7
   Tier 3: Infecto extras + Derm + Tox extras + Queimaduras + outras
   =========================================================== */

PATOLOGIAS.push(

/* ============== INFECTO EXTRAS ============== */
{id:"covid", sis:"infecto", grav:"media",
nome:"COVID-19 (SARS-CoV-2)",
sin:["covid","coronavírus","SARS-CoV-2"],
def:"Infecção viral respiratória — sintomas variam de assintomático a SDRA. Quadros: leve (sintomas sem hipoxemia), moderado (pneumonia sem hipoxemia), grave (SpO₂ <94%, FR ≥30, infiltrados >50%), crítico (IRespA, choque, MOF).",
exames:["RT-PCR ou antígeno SARS-CoV-2","RX/TC tórax (vidro fosco bilateral periférico)","HMG (linfopenia), PCR, D-dímero, ferritina, LDH","Gaso arterial","ECG, troponina"],
rx:[
{etapa:"inicial", d:"O₂ suplementar",do:"Cânula → máscara → cateter alto fluxo → VNI → IOT conforme gravidade",via:"—",o:"Alvo SpO₂ 92-96% (gestantes 94-98%). Pronar acordado se SpO₂ <94% em O₂."},
{etapa:"inicial", d:"Dexametasona",do:"6 mg VO/IV/d × 10 dias",via:"VO/IV",o:"INDICADA APENAS se uso de O₂. RECOVERY: reduz mortalidade 36%→29% em VM. NÃO em leves."},
{etapa:"anticoag", d:"Anticoagulação profilática",do:"Enoxaparina 40 mg SC/d (plena se TEV/D-dímero ↑↑)",via:"SC",o:"INTERNADOS — todos. CIVD/TEV comum."},
{etapa:"escala", d:"Tocilizumabe",do:"8 mg/kg IV (máx 800 mg)",via:"IV",o:"Hipoxemia + ↑PCR — disponibilidade SUS limitada."},
{etapa:"inicial", d:"Nirmatrelvir/Ritonavir (Paxlovid)",do:"300/100 mg VO 12/12h × 5 dias",via:"VO",o:"Alto risco + sintomas <5d + sem O₂. Múltiplas interações medicamentosas."},
],
alertas:[
{t:"crit",x:"DETERIORAÇÃO TARDIA (dia 7-10) — jovem aparentemente bem pode descompensar para SDRA. Vigilância SpO₂."},
{t:"crit",x:"Hidroxicloroquina, ivermectina, azitromicina monoterapia, cloroquina, nitazoxanida NÃO TÊM EFICÁCIA comprovada. NÃO prescrever."},
{t:"warn",x:"COVID longo: persistência >12 sem — fadiga, dispneia, déficit cognitivo. Encaminhar especialista."},
],
fisio:"SARS-CoV-2 entra via receptor ACE2 (epitélio respiratório + endotélio + intestino + rim + miocárdio). Tempestade de citocinas → SDRA + microtrombos + miocardite + IRA. Vacinas + Ômicron alteram apresentação (mais leve, menos anosmia).",
mec:[
{d:"Dexametasona",x:"Anti-inflamatório — reduz tempestade de citocinas tardia. Útil APENAS quando há inflamação significativa (uso de O₂)."},
{d:"Nirmatrelvir",x:"Inibidor da protease principal (Mpro) do SARS-CoV-2 — bloqueia clivagem de poliproteínas virais. Ritonavir é booster (inibe CYP3A4)."},
],
diretriz:"NIH COVID-19 Treatment Guidelines (atualização contínua). MS Brasil. WHO Living Guidance.",
fluxo:null, calcs:[],
},

{id:"influenza", sis:"infecto", grav:"media",
nome:"Influenza / SRAG",
sin:["influenza","gripe","H1N1","SRAG"],
def:"Síndrome gripal: febre + tosse + dor garganta + cefaleia/mialgia abruptos. SRAG: dispneia + SpO₂ <95%. Sazonal. Tipos A (H1N1, H3N2 — mais graves), B.",
exames:["PCR influenza A/B (gold standard)","Teste rápido antigênico (S 60-70%)","RX tórax","HMG, gaso"],
rx:[
{etapa:"atb", d:"Oseltamivir",do:"75 mg VO 12/12h × 5 dias",via:"VO",o:"Idealmente <48h. Em GRAVES: usar mesmo após 48h."},
{etapa:"atb", d:"Oseltamivir UTI",do:"150 mg VO 12/12h × 10 dias (dobrada)",via:"VO",o:"Evidência fraca de superioridade — algumas diretrizes endossam."},
{etapa:"adj", d:"Dipirona/Paracetamol",do:"500-1000 mg",via:"VO/IV",o:"NÃO AAS em <16a (Reye)."},
{etapa:"inicial", d:"O₂ + suporte",do:"VM protetora se SDRA",via:"—",o:"IOT precoce em piora rápida."},
{etapa:"escala", d:"ATB superinfecção",do:"Ceftriaxona 2g + azitromicina 500 mg IV",via:"IV",o:"Recidiva febril → S. aureus, pneumococo, Strep A."},
],
alertas:[
{t:"crit",x:"GRUPOS DE RISCO P/ ANTIVIRAL: gestantes, puérperas <6 sem, <2a, ≥60a, comorbidades (DM, cardiopatia, obesidade, imunosupressão), indígenas."},
{t:"crit",x:"H1N1 pode causar SDRA fulminante em jovens — não subestimar dispneia."},
{t:"warn",x:"Diferencial: COVID, RSV, parainfluenza. PCR painel é definitivo."},
],
fisio:"Vírus RNA. Replica em epitélio respiratório → necrose + inflamação. Sintomas sistêmicos por citocinas (IFN-α, IL-6, TNF). Complicações: pneumonia bacteriana secundária (S. aureus, pneumococo — causa #1 morte), miocardite, encefalite, Reye, Guillain-Barré.",
mec:[
{d:"Oseltamivir",x:"Inibidor neuraminidase — enzima viral que libera novas partículas da célula infectada. Inibição → vírus 'preso'."},
],
diretriz:"MS — Protocolo Influenza 2023. IDSA Seasonal Influenza 2018 (Uyeki TM et al., CID 2019;68:e1).",
fluxo:null, calcs:[],
},

{id:"erisipela", sis:"infecto", grav:"media",
nome:"Erisipela",
sin:["erisipela"],
def:"Infecção da derme superficial + linfáticos — placa eritematosa BEM DELIMITADA, calor, dor, edema, ± febre + linfangite. Diferente de celulite (mais profunda, limites menos nítidos). MMII 70%, face 5%.",
exames:["Diagnóstico CLÍNICO","HMG + PCR se sistêmico","Hemoculturas se sepse","USG se suspeita abscesso"],
rx:[
{etapa:"atb", d:"Penicilina G Benzatina",do:"1.200.000 UI IM dose única",via:"IM",o:"1ª LINHA — Strep pyogenes. Não-graves, ambulatorial."},
{etapa:"atb", d:"Cefalexina",do:"500 mg VO 6/6h × 7-10 dias",via:"VO",o:"Ambulatorial. Cobre Strep + S. aureus."},
{etapa:"atb", d:"Penicilina G cristalina",do:"4 milhões UI IV 4/4h",via:"IV",o:"Internação — face, imunossuprimido, sepse, falha VO."},
{etapa:"atb", d:"Clindamicina",do:"600-900 mg IV 8/8h",via:"IV",o:"Alergia à penicilina."},
{etapa:"escala", d:"Suporte",do:"Elevação MMII + repouso + analgesia + marcação bordes",via:"—",o:"Caneta para avaliar progressão."},
{etapa:"adj", d:"Profilaxia secundária",do:"Pen G Benzatina 1.2 mi IM 21/21 dias × 6-12m",via:"IM",o:"Recorrentes (≥2/ano) + linfedema."},
],
alertas:[
{t:"crit",x:"FACE: risco trombose seio cavernoso. ATB IV + monitorização."},
{t:"crit",x:"Diferenciar de FASCEÍTE NECROTIZANTE: dor desproporcional, bolhas, crepitação, necrose, sepse — emergência cirúrgica."},
{t:"warn",x:"Porta de entrada: micose interdigital (tinea pedis) é #1 em MMII. TRATAR para prevenir recidiva."},
],
fisio:"Strep beta-hemolítico A (Strep pyogenes); raramente outras Strep ou S. aureus. Entra por solução de continuidade e dissemina pela derme + linfáticos. Hialuronidase + estreptocinase facilitam disseminação.",
mec:[{d:"Penicilina G",x:"β-lactâmico — inibe transpeptidação na parede bacteriana. Strep pyogenes mantém sensibilidade quase universal."}],
diretriz:"IDSA SSTI 2014 (Stevens DL et al., CID 2014;59:e10, DOI:10.1093/cid/ciu444).",
fluxo:null, calcs:[],
imgs:[
{src:"https://upload.wikimedia.org/wikipedia/commons/1/1c/Erysipel.JPG",
alt:"Erisipela — placa eritematosa bem delimitada",
caption:"Erisipela — placa eritematosa bem delimitada, edema, com bordas elevadas. CHAVE: bordas BEM DEFINIDAS distinguem de celulite.",
source:"Wikimedia Commons / Mahmoudalrawi (CC BY-SA 3.0)"},
],
},

{id:"pep-hiv", sis:"infecto", grav:"alta",
nome:"PEP — Profilaxia Pós-Exposição HIV",
sin:["PEP","profilaxia pós-exposição","exposição HIV"],
def:"Indicada em exposição com risco de transmissão HIV: ocupacional (perfurocortante, mucosa, pele não íntegra) OU sexual (sem proteção com fonte HIV+ ou desconhecida de alto risco) OU droga IV.",
exames:["Teste rápido HIV exposto E fonte (se possível) — ANTES da PEP","Teste rápido sífilis, HBsAg, anti-HCV","Beta-HCG mulher fértil","Função hepática + renal (basal pré-TARV)"],
rx:[
{etapa:"atb", d:"TARV — Tenofovir + Lamivudina + Dolutegravir",do:"TDF 300 + 3TC 300 + DTG 50 mg, 1×/d × 28 dias",via:"VO",o:"INICIAR <72h (idealmente <2h). PCDT MS-Brasil 2017."},
{etapa:"adj", d:"Hepatite B (vacina + IGHAHB)",do:"Vacina 3 doses + IGHAHB 0,06 mL/kg IM (até 7 dias)",via:"IM",o:"Não imunizado ou anti-HBs <10 + fonte HBsAg+."},
{etapa:"escala", d:"Sífilis profilática",do:"Pen G Benzatina 2.4 milhões UI IM",via:"IM",o:"Exposição sexual + fonte com sífilis ativa."},
{etapa:"escala", d:"Contracepção emergência",do:"Levonorgestrel 1,5 mg VO dose única",via:"VO",o:"Até 5 dias — direito da mulher em violência sexual."},
{etapa:"alta", d:"Seguimento",do:"Teste HIV em 30 + 90 + 180 dias",via:"—",o:"+ transaminases. Suporte multidisciplinar se trauma."},
],
alertas:[
{t:"crit",x:"JANELA = 72h. <2h é ideal. Após 72h, NÃO indicar (eficácia ~zero, toxicidade sem benefício)."},
{t:"crit",x:"NUNCA atrasar PEP esperando teste fonte — iniciar empiricamente, SUSPENDER se fonte negativa."},
{t:"warn",x:"Violência sexual: notificação compulsória (SINAN). Coleta material legal. Apoio multidisciplinar."},
{t:"info",x:"PrEP é PRÉ-exposição (risco contínuo). PEP é depois do evento."},
],
fisio:"Risco transmissão HIV: perfurocortante ~0,3%; mucosa ~0,09%; anal receptivo ~1,4%; vaginal receptivo ~0,08%; oral muito baixo. Profilaxia bloqueia ciclo viral antes do estabelecimento sistêmico.",
mec:[
{d:"Tenofovir",x:"INTI análogo de nucleotídeo — bloqueia conversão RNA viral em DNA."},
{d:"Dolutegravir",x:"Inibidor da integrase — bloqueia integração do DNA proviral no genoma."},
],
diretriz:"PCDT MS Brasil — PEP 2021. WHO PEP Guidelines.",
fluxo:null, calcs:[],
},

/* ============== DERMATOLOGIA ============== */
{id:"sjs-net", sis:"derm", grav:"alta",
nome:"Stevens-Johnson / NET / DRESS",
sin:["Stevens-Johnson","SJS","NET","necrólise epidérmica","DRESS"],
def:"Reações cutâneas graves a fármacos. SJS: descamação <10% SCT + ≥2 mucosas. NET (Lyell): >30%. Overlap 10-30%. DRESS: rash + febre + linfadenopatia + eosinofilia + acometimento sistêmico (hepatite, nefrite).",
exames:["HMG com diferencial (eosinofilia em DRESS)","Função renal + hepática","Eletrólitos","Hemoculturas","Biópsia de pele (necrose epidérmica)","RX tórax"],
rx:[
{etapa:"escala", d:"SUSPENDER agente causador",do:"IMEDIATO",via:"—",o:"PILAR. Identificar tudo nos últimos 1-8 sem (alopurinol, sulfa, anticonvulsivante aromático, AINE, β-lactâmico, dapsona, lamotrigina)."},
{etapa:"escala", d:"Unidade de Queimados",do:"Transferência",via:"—",o:"NET >10% deve ser em centro especializado — manejo similar a queimadura grande."},
{etapa:"escala", d:"Reposição volêmica",do:"Cristaloide 2 mL × kg × %SCT em 24h (50% nas 1ªs 8h)",via:"IV",o:"Como queimadura. Acesso central se >30%."},
{etapa:"escala", d:"Cuidados de pele",do:"Não-aderente; prata ou Vaselina/petrolato",via:"—",o:"NÃO debridar agressivamente; evitar adesivos."},
{etapa:"escala", d:"Cuidado ocular",do:"Lubrificação + corticoide tópico + descolamento sinéquias",via:"Tópico",o:"Oftalmologia precoce — sequelas oculares = causa #1 morbidade tardia."},
{etapa:"adj", d:"DRESS — Corticoide",do:"Prednisolona 1 mg/kg/d com desmame lento (6-8 sem)",via:"VO/IV",o:"Maioria dos casos. Rebote frequente."},
{etapa:"escala", d:"Ciclosporina (NET)",do:"3-5 mg/kg/d × 7-10 dias",via:"VO",o:"Evidência observacional. Promissor."},
],
alertas:[
{t:"crit",x:"NÃO RE-EXPOR ao fármaco — risco NET fulminante. Anotar PRONTUÁRIO + cartão alerta + orientar."},
{t:"crit",x:"Sinal de Nikolsky positivo + lesão alvo atípica + mucoso = SJS/NET até prova contrária."},
{t:"warn",x:"DRESS aparece 2-8 sem APÓS início (mais tardio que SJS) — anticonvulsivante aromático + alopurinol clássicos."},
{t:"warn",x:"SCORTEN: idade ≥40, FC ≥120, malignidade, SCT ≥10%, ureia ↑, glicose ↑, HCO₃ ↓. Cada ponto = ↑mortalidade."},
],
fisio:"Reação imune-mediada (T-citotóxica) com apoptose maciça de queratinócitos. HLA específicos predispõem (HLA-B*1502 + carbamazepina em asiáticos, HLA-B*5701 + abacavir). Descolamento epidérmico → 'queimadura interna' (perda barreira, eletrólitos, infecção). Mortalidade NET: 30-50%.",
mec:[
{d:"Ciclosporina",x:"Inibidor calcineurina — bloqueia ativação de células T citotóxicas."},
],
diretriz:"UK SJS/NET Guidelines 2016. Mockenhaupt M, RegisCAR.",
fluxo:null, calcs:[],
imgs:[
{src:"https://upload.wikimedia.org/wikipedia/commons/5/58/Stevens-johnson-syndrome.jpg",
alt:"Lesões em alvo atípicas e descolamento epidérmico em SJS",
caption:"SJS — lesões em alvo atípicas com descolamento epidérmico e acometimento de pelo menos 2 mucosas.",
source:"Wikimedia Commons / DermNet (CC BY-NC-ND 3.0)"},
{src:"https://upload.wikimedia.org/wikipedia/commons/a/ae/Toxic-epidermal-necrolysis.jpg",
alt:"NET — descolamento epidérmico extenso",
caption:"NET (Lyell) — descolamento epidérmico extenso (>30% SCT), sinal de Nikolsky positivo. Manejo igual a queimadura grande.",
source:"Wikimedia Commons / DermNet (CC BY-NC-ND 3.0)"},
],
},

{id:"herpes-zoster", sis:"derm", grav:"media",
nome:"Herpes-Zóster",
sin:["herpes zoster","zoster","cobreiro","neuralgia pós-herpética"],
def:"Reativação do varicela-zóster latente em gânglio sensitivo → erupção vesicular dolorosa em UM DERMÁTOMO unilateral, sem ultrapassar linha média. Dor pode preceder lesões em 1-5 dias.",
exames:["Diagnóstico CLÍNICO","PCR vesícula se atípico","HIV se <50a sem causa identificada"],
rx:[
{etapa:"atb", d:"Aciclovir",do:"800 mg VO 5×/d × 7 dias",via:"VO",o:"INICIAR <72h. Após 72h: só se ainda novas lesões."},
{etapa:"atb", d:"Valaciclovir",do:"1 g VO 8/8h × 7 dias",via:"VO",o:"Mais conveniente (3×/d) — pró-droga, melhor biodisponibilidade."},
{etapa:"atb", d:"Aciclovir IV",do:"10 mg/kg IV 8/8h × 7-10 dias",via:"IV",o:"Imunossuprimido, oftálmico, disseminado, SNC."},
{etapa:"adj", d:"Analgesia",do:"Gabapentina 300-1200 mg/d divididos + dipirona + tramadol",via:"VO",o:"Dor neuropática. Amitriptilina 25-75 mg à noite alternativa."},
{etapa:"escala", d:"Cuidado lesão",do:"Compressas frias + sabão neutro + curativo gaze",via:"Tópico",o:"NÃO usar antivirais tópicos isolados. NÃO romper vesículas."},
],
alertas:[
{t:"crit",x:"ZÓSTER OFTÁLMICO (1º ramo trigêmeo, sinal Hutchinson — vesícula ponta nariz): EMERGÊNCIA oftalmológica. Aciclovir IV + oftalmo URGENTE. Risco ceratite, uveíte, cegueira."},
{t:"crit",x:"Zóster DISSEMINADO (>20 vesículas fora dermátomo) → imunossupressão (HIV, neoplasia). Aciclovir IV + investigar."},
{t:"warn",x:"Ramsay-Hunt: zóster gânglio geniculado — paralisia facial + vesículas conduto + perda auditiva. Aciclovir + corticoide."},
{t:"warn",x:"Vacina (Shingrix): reduz incidência + neuralgia pós-herpética. >50a."},
],
fisio:"VZV permanece latente em gânglios da raiz dorsal pós-varicela. Reativa com idade + imunossupressão + estresse. Replicação no gânglio → migração axonal centrífuga → vesículas dermatomais. Inflamação ganglionar causa neuralgia (aguda e como neuralgia pós-herpética em até 30% >60a).",
mec:[
{d:"Aciclovir",x:"Análogo guanosina — ativado por timidina-quinase viral (seletividade); trifosfato compete com dGTP na DNA polimerase viral → terminação cadeia."},
{d:"Gabapentina",x:"Ligante α2δ de canais cálcio neuronais → ↓liberação glutamato. Eficaz dor neuropática."},
],
diretriz:"IDSA Guidelines. CDC Shingles Guidelines.",
fluxo:null, calcs:[],
imgs:[
{src:"https://upload.wikimedia.org/wikipedia/commons/5/54/Herpes_Zoster_am_Hals.JPG",
alt:"Vesículas agrupadas em base eritematosa em dermátomo torácico",
caption:"Herpes-zóster torácico — vesículas agrupadas em base eritematosa, distribuição dermatomal unilateral.",
source:"Wikimedia Commons / Fisle (CC BY-SA 3.0)"},
],
},

/* ============== TOX EXTRAS ============== */
{id:"tca-tox", sis:"tox", grav:"alta",
nome:"Intoxicação por Antidepressivo Tricíclico",
sin:["TCA","amitriptilina","nortriptilina","intoxicação ATC"],
def:"Sobredose de TCA (amitriptilina, nortriptilina, imipramina, clomipramina) — anticolinérgico + cardiotóxico (Na⁺ canal) + neurotóxico. Tríade: alteração mental + cardiotoxicidade (QRS largo) + anticolinérgico. Pode evoluir rápido em horas.",
exames:["ECG IMEDIATO + monitorização contínua","Gaso arterial (acidose piora cardiotoxicidade)","Nível sérico de TCA (não amplamente disponível BR)","Eletrólitos, glicemia","Função renal, hepática","Nível paracetamol, salicilato (coingestão)"],
rx:[
{etapa:"escala", d:"Bicarbonato de Sódio",do:"1-2 mEq/kg IV bolus + BIC mantendo pH 7,50-7,55",via:"IV",o:"PILAR. INDICAÇÕES: QRS >100 ms, hipotensão, arritmia ventricular. ALCALOSE desloca TCA do Na⁺ canal."},
{etapa:"escala", d:"Carvão ativado",do:"1 g/kg VO/SNG",via:"VO/SNG",o:"<1-2h ingestão E via aérea protegida. NÃO em rebaixamento sem IOT (broncoaspiração)."},
{etapa:"escala", d:"Hidratação",do:"SF 0,9% 20 mL/kg em bolus se hipoTA",via:"IV",o:"Cuidado em IC."},
{etapa:"escala", d:"Noradrenalina",do:"0,05-2 mcg/kg/min BIC",via:"IV",o:"Hipotensão refratária a volume e bicarbonato. EVITAR dopamina (esgotamento por bloqueio de recaptação)."},
{etapa:"escala", d:"Lidocaína (classe IB)",do:"1-1,5 mg/kg IV",via:"IV",o:"Arritmia ventricular refratária ao bicarbonato. ÚNICO antiarrítmico aceito. EVITAR IA, IC, III (prolongam QT)."},
{etapa:"escala", d:"BZD",do:"Diazepam 5-10 mg IV se convulsão",via:"IV",o:"Convulsão é comum (delirium tremens-like)."},
{etapa:"escala", d:"Sulfato de Mg",do:"2 g IV em 5 min",via:"IV",o:"Torsades."},
{etapa:"escala", d:"IOT",do:"Sequência rápida",via:"—",o:"Glasgow ≤8 ou convulsão refratária. Hiperventilar levemente após (pH alvo 7,50)."},
],
alertas:[
{t:"crit",x:"QRS >100 ms = preditor de convulsão; >160 ms = arritmia ventricular. BICARBONATO IMEDIATO."},
{t:"crit",x:"Flumazenil NUNCA — pode precipitar convulsão em coingestão BZD."},
{t:"crit",x:"Fisostigmina (anticolinesterásico) NUNCA em TCA — bradiarritmia fatal descrita."},
{t:"warn",x:"R-wave em aVR >3 mm + S em I/aVL = sinais de toxicidade (Liebelt). Onda R aVR >3 mm = preditor arritmia."},
],
fisio:"TCAs bloqueiam: (1) recaptação noradrenalina/serotonina (efeito terapêutico); (2) receptores muscarínicos (anticolinérgico: midríase, taquicardia, retenção urinária, hipertermia, delirium); (3) α1-adrenérgicos (hipotensão ortostática); (4) Na⁺ canais cardíacos (QRS largo, arritmia ventricular — efeito 'tipo IA quinidina'); (5) GABA-A (limiar convulsivo ↓). Acidose AUMENTA fração não-ionizada do TCA → mais ligação a Na⁺ canal → cardiotoxicidade.",
mec:[
{d:"Bicarbonato",x:"Alcaliniza plasma → desloca TCA do Na⁺ canal por gradiente de prótons + Na⁺ extra compete pelo sítio. Resultado: QRS estreita, hipotensão melhora."},
],
diretriz:"AACT/EAPCCT 2007 Position Paper. Liebelt EL, Toxicol Rev 2005;24:243.",
fluxo:null, calcs:[],
},

{id:"salicilato", sis:"tox", grav:"alta",
nome:"Intoxicação por Salicilato (AAS)",
sin:["salicilato","AAS","aspirina","intoxicação aspirina"],
def:"Sobredose aguda ou crônica de salicilatos (AAS, óleo de Wintergreen, AINE). Clássico: alcalose RESPIRATÓRIA (centro respiratório estimulado) + acidose METABÓLICA (ânion gap) + alterações mentais + zumbido + hipertermia.",
exames:["Nível sérico salicilato (séries 2/2h até pico/queda)","Gaso arterial (típica alcalose mista + acidose metabólica AG)","Glicemia capilar (hipo OU hiper)","Eletrólitos, função renal, hepática","Hemograma, coag","ECG (raro alterações)","Lactato"],
rx:[
{etapa:"escala", d:"Carvão ativado",do:"1 g/kg VO/SNG; doses repetidas 0,5 g/kg 4/4h em ingestão maciça",via:"VO/SNG",o:"INDICADO até várias horas — salicilatos formam bezoar. Via aérea protegida."},
{etapa:"escala", d:"Reidratação",do:"SG/SF + glicose (HipoG cerebral mesmo com BG normal)",via:"IV",o:"Repor déficit. Salicilato causa diurese osmótica."},
{etapa:"escala", d:"Bicarbonato (Alcalinização urinária)",do:"150 mEq em 1L SG 5% IV em 2h, ajustar manter pH urinário 7,5-8,0",via:"IV",o:"PILAR. ↑Excreção urinária 10-20×. K alvo >4 (hipoK impede alcalinização)."},
{etapa:"escala", d:"Reposição de K",do:"KCl 40 mEq por L SG infundido",via:"IV",o:"Salicilato + alcalinização causam HIPOCALEMIA. Sem K, alcalinização falha."},
{etapa:"escala", d:"Hemodiálise",do:"Indicação",via:"—",o:"INDICAÇÕES: nível >100 mg/dL agudo OU >60 mg/dL crônico; SNC alterado, IR, IC, edema pulmonar, acidose refratária. Indicar PRECOCEMENTE."},
{etapa:"escala", d:"IOT — CUIDADO",do:"Manter hiperventilação após IOT",via:"—",o:"Hiperventilação compensa acidose. Se IOT com VM 'normal' → acidose piora drasticamente → óbito rápido. ALERTAR equipe."},
],
alertas:[
{t:"crit",x:"IOT pode MATAR rápido se ventilação 'normal' for instituída. MANTER hiperventilação espontânea sempre que possível. Se IOT necessária: FR alta + Vt amplo."},
{t:"crit",x:"INTOXICAÇÃO CRÔNICA é mais grave que aguda no mesmo nível sérico. Idoso confuso + acidose AG + alcalose resp em uso de AAS regular → suspeitar."},
{t:"warn",x:"Wintergreen (metilsalicilato): 1 mL = ~1g de aspirina. Ingestão pediátrica de pequenas quantidades pode ser letal."},
],
fisio:"AAS é hidrolisado a salicilato (ácido fraco, pKa 3,0). Mecanismos tóxicos: (1) desacopla fosforilação oxidativa → hipertermia + acidose lática; (2) estimula centro respiratório → alcalose respiratória; (3) inibe ciclo de Krebs + síntese ácidos graxos → cetoacidose. Salicilato atravessa BHE em pH baixo — daí piora rápida em acidose. Edema pulmonar não-cardiogênico + cerebral em casos graves.",
mec:[
{d:"Bicarbonato",x:"Alcaliniza urina → ↑fração ionizada de salicilato no túbulo → menos reabsorção. Aumenta clearance dramaticamente. NB: alcalinização sistêmica também impede salicilato de entrar no SNC."},
],
diretriz:"AACT/EAPCCT Position Paper on Salicylate Poisoning 2015.",
fluxo:null, calcs:[],
},

{id:"co-tox", sis:"tox", grav:"alta",
nome:"Intoxicação por Monóxido de Carbono",
sin:["CO","monóxido carbono","intoxicação CO"],
def:"Inalação de CO (incêndio, exaustão de motor, aquecedor mal ventilado, fogão a lenha) → afinidade 240× pela Hb (carboxiHb) → hipóxia tissular. Clínica varia: cefaleia, náusea, confusão, síncope, dor torácica, coma. SpO₂ NORMAL (oxímetro não diferencia HbO₂ de HbCO).",
exames:["CarboxiHb (cooximetria — específico): leve 10-20%, moderado 21-40%, grave >40%","Gaso arterial (acidose metabólica láctica)","ECG, troponina (isquemia miocárdica é comum)","Glicemia, eletrólitos","β-HCG","TC crânio se neuro alterado"],
rx:[
{etapa:"inicial", d:"Remoção da fonte + O₂ 100%",do:"Máscara não-reinalante 15 L/min",via:"—",o:"PILAR. Reduz meia-vida CO de 4-6h (ar ambiente) para ~80 min."},
{etapa:"inicial", d:"O₂ hiperbárico (OHB)",do:"2,5-3 atm × 60-90 min",via:"—",o:"INDICAÇÕES: CarboxiHb >25%, perda consciência, gravidez (mesmo CO baixa), sintomas neuro persistentes, isquemia cardíaca, idade extrema. Meia-vida cai para ~20 min."},
{etapa:"escala", d:"Suporte ABC",do:"IOT se rebaixamento; cristaloide se hipotensão",via:"—",o:"Cuidado com lesão térmica via aérea em vítima de incêndio."},
{etapa:"escala", d:"Cianeto (suspeita coingestão em incêndio)",do:"Hidroxocobalamina 5 g IV em 15 min",via:"IV",o:"Se intoxicação por CIANETO suspeita (fumaça plástico/lã/seda + acidose lática grave + carboxiHb mod-grave + ↓consc). Tiossulfato + nitrito (Cyanide Antidote Kit) alternativa."},
{etapa:"escala", d:"Aconselhamento",do:"Identificar fonte (engenheiro, equipe local) + prevenir recorrência",via:"—",o:"NÃO retornar até fonte sanada. Detector de CO."},
],
alertas:[
{t:"crit",x:"SpO₂ NORMAL com clínica suspeita NÃO EXCLUI. Pedir COOXIMETRIA (gaso com Hb total) — oxímetro de pulso é cego para HbCO."},
{t:"crit",x:"GESTANTE — feto tem afinidade Hb-CO MAIOR que mãe + eliminação mais lenta. Indicação ampla de OHB mesmo CO baixa."},
{t:"warn",x:"Síndrome neurológica tardia (3-40 dias pós): parkinsonismo, déficit cognitivo, demência. OHB pode reduzir incidência."},
{t:"info",x:"BR: câmaras hiperbáricas disponíveis em centros principais (transferir se viável)."},
],
fisio:"CO compete com O₂ pela Hb (afinidade 240×) → carboxiHb não transporta O₂. Curva de dissociação O₂-Hb desviada para esquerda → libera menos O₂ aos tecidos. Adicionalmente: CO se liga a mioglobina cardíaca + citocromo c oxidase → bloqueia respiração mitocondrial. Resultado: hipóxia tecidual + dano isquêmico (cérebro, coração).",
mec:[
{d:"O₂ 100%",x:"Lei de ação das massas — ↑PO₂ desloca CO da Hb. Hiperbárico aumenta drasticamente PO₂ dissolvido no plasma (~6 mL/dL vs 0,3) + acelera dissociação."},
{d:"Hidroxocobalamina",x:"Sequestra cianeto formando cianocobalamina (vit B12) atóxica, excretada pelo rim."},
],
diretriz:"Undersea & Hyperbaric Medical Society 2019. CDC.",
fluxo:null, calcs:[],
},

{id:"litio-tox", sis:"tox", grav:"alta",
nome:"Intoxicação por Lítio",
sin:["lítio","intoxicação lítio","Li"],
def:"Toxicidade aguda (suicídio): sintomas GI predominam inicialmente. Crônica (paciente em uso terapêutico que descompensa por desidratação, IRA, AINE, IECA, tiazídico): mais grave, predominam neurológicos. Nível tóxico >1,5 mEq/L (terapêutico 0,6-1,2).",
exames:["Nível sérico Li (séries — pico tardio em LP)","Função renal (Cr, ureia)","Eletrólitos (Na frequentemente alterado — diabetes insípido nefrogênico)","Cálcio, magnésio, fósforo","TSH (toxicidade tireoidiana crônica)","ECG (alargamento QT, alterações ST inespecíficas)","Gaso, glicemia","β-HCG"],
rx:[
{etapa:"escala", d:"SUSPENDER lítio + drogas que retém Li",do:"AINE, IECA/BRA, tiazídico, espironolactona",via:"—",o:"PILAR. Listar todas as drogas."},
{etapa:"escala", d:"Hidratação SF 0,9%",do:"200-250 mL/h até diurese adequada",via:"IV",o:"Restaurar volemia + diurese. NÃO usar diurético salina forçada."},
{etapa:"escala", d:"Carvão ativado — NÃO eficaz",do:"—",via:"—",o:"Lítio não adsorve em carvão. Útil só para coingestão."},
{etapa:"escala", d:"Lavagem gástrica precoce",do:"<1h ingestão maciça, via aérea protegida",via:"—",o:"Considerar em maciça aguda."},
{etapa:"escala", d:"HEMODIÁLISE",do:"4-6h",via:"—",o:"PILAR em casos graves. INDICAÇÕES: Li >4 mEq/L; >2,5 com sintomas neuro/cardiacos/renais; IR; sintomas que não melhoram. Pode rebote — repetir."},
{etapa:"escala", d:"Manejo arritmia",do:"Conforme tipo",via:"—",o:"Lítio pode causar disfunção sinusal, BAV, QT longo, taquicardia ventricular."},
{etapa:"escala", d:"BZD se convulsão",do:"Diazepam 5-10 mg IV",via:"IV",o:"Status epilepticus pode ocorrer."},
],
alertas:[
{t:"crit",x:"Intoxicação CRÔNICA é mais grave que aguda no mesmo nível — distribuição tecidual completa. Paciente em uso terapêutico com desidratação/IRA pode ter sintomas graves com Li só levemente acima."},
{t:"crit",x:"Sintomas NEURO: tremor → confusão → mioclonias → convulsão → coma. Sequelas neuro permanentes possíveis em casos graves (SILENT — Syndrome of Irreversible Lithium-Effectuated Neurotoxicity)."},
{t:"warn",x:"Diabetes insípido NEFROGÊNICO induzido por Li — polidipsia, poliúria, hiperNa em uso crônico. Pode persistir após suspensão."},
],
fisio:"Lítio é cátion monovalente, similar ao Na. Excreção QUASE EXCLUSIVAMENTE renal — depende da filtração + 80% reabsorção túbulo proximal (como Na). Desidratação/sódio baixo → ↑reabsorção compensatória de Na + Li → níveis ↑. AINE, IECA, tiazídico fazem o mesmo. Mecanismo tóxico: depleção mioinositol cerebral, alteração 2º mensageiros, inibição GSK-3β (também base terapêutica em transtorno bipolar).",
mec:[
{d:"Hemodiálise",x:"Lítio é íon pequeno (massa 7), não-ligado a proteínas, baixo volume de distribuição. IDEAL para diálise — clearance dialisador >>renal. Rebote por redistribuição é regra; repetir."},
],
diretriz:"EXTRIP Workgroup 2015 — Decisões de extração por diálise.",
fluxo:null, calcs:[],
},

/* ============== QUEIMADURAS ============== */
{id:"queimaduras", sis:"trauma", grav:"alta",
nome:"Queimaduras",
sin:["queimaduras","queimadura","grande queimado"],
def:"Lesão térmica/química/elétrica/radioativa. Profundidade: 1º grau (epiderme — hiperemia); 2º superficial (papilas — bolhas, dor); 2º profundo (reticular — bolhas, hipoestesia); 3º (subcutâneo, branca/preta, indolor); 4º (músculo/osso). SCT pela regra dos 9 ou Lund-Browder.",
exames:["SCQ (% superfície corporal queimada) — regra dos 9","Gaso arterial + lactato + carboxiHb (incêndio)","HMG, eletrólitos, função renal, hepática","Cinacídio se incêndio (cianeto)","CPK (rabdomiólise se elétrica/extensa)","ECG (elétrica)","RX tórax (lesão inalatória), broncoscopia se suspeita"],
rx:[
{etapa:"inicial", d:"PARAR PROCESSO — irrigação + remoção roupas",do:"Água corrente 15-20 min. NÃO gelo",via:"—",o:"Reduz progressão. Roupas aderidas: NÃO arrancar. Joias/anéis: remover (edema)."},
{etapa:"inicial", d:"ABCDE — Via aérea PRECOCE",do:"IOT se sinais de lesão inalatória",via:"—",o:"Edema progressivo em 24-48h → IOT enquanto fácil. Sinais: queimadura facial, vibrissa singed, escarro carbonáceo, rouquidão, estridor."},
{etapa:"inicial", d:"O₂ 100% se incêndio (CO)",do:"Máscara não-reinalante",via:"—",o:"Reduz meia-vida CO de 4h para 1h. SpO₂ pode mostrar falsamente normal — pedir carboxiHb."},
{etapa:"inicial", d:"2 acessos calibrosos",do:"Idealmente em pele íntegra; se impossível, mesmo em queimada",via:"—",o:"Calibrosos (14-16G). Acesso central se SCQ extensa + vasopressor."},
{etapa:"inicial", d:"Calcular SCQ — Regra dos 9",do:"% superfície corporal queimada (excluir 1º grau)",via:"—",o:"Wallace adulto: cabeça 9, MS 9 cada, tronco ant 18, tronco post 18, MI 18 cada, períneo 1. Palma do paciente = 1%. Em criança: cabeça 18%."},
{etapa:"escala", d:"① REPOSIÇÃO VOLÊMICA — Fórmula PARKLAND",do:"Ringer Lactato 4 mL × kg × %SCQ em 24h (50% nas 1ªs 8h)",via:"IV",o:"INICIAR da HORA DA QUEIMADURA, não da admissão. RL preferido (evita acidose hipercloremica do SF). Ajustar conforme diurese."},
{etapa:"escala", d:"② Titular pela DIURESE",do:"Adulto 0,5-1 mL/kg/h, ped 1-1,5, elétrica 1-2",via:"—",o:"DIURESE é a melhor medida de adequação. NÃO usar PAM como única meta (pode normalizar com volume excessivo)."},
{etapa:"escala", d:"③ ESCAROTOMIA (queimadura circular)",do:"Indicação: tórax circular (restritiva) ou extremidade (sd compartimental)",via:"Cirúrgico",o:"24-48h após queimadura. Antes que evolua para sd compartimental. Sinais: ↑pressão compartimental, pulsos diminuídos, palidez, parestesia."},
{etapa:"escala", d:"④ Cirurgia precoce (2º profundo, 3º)",do:"Excisão tangencial + enxerto em 5-7 dias",via:"Cirúrgico",o:"Reduz hipermetabolismo, infecção, dor. Centro de queimados."},
{etapa:"atb", d:"ATB profilático sistêmico — NÃO indicado",do:"Apenas se infecção estabelecida + cultura",via:"—",o:"Profilaxia sistêmica AUMENTA resistência. Cobertura empírica em sepse: cobrir Pseudomonas + S. aureus + ESBL."},
{etapa:"adj", d:"Antissepsia tópica — Sulfadiazina prata 1%",do:"Aplicar sobre queimadura + gaze",via:"Tópico",o:"Trocar 24/24h. CI: alergia sulfa, gestante, RN. Alternativa: hidrogel ou hidrofibra."},
{etapa:"adj", d:"ANALGESIA — Morfina IV titulada",do:"0,1 mg/kg IV cada 5-15 min até alívio",via:"IV",o:"Doses generosas. PCA quando possível. NÃO subdosar. Cetamina sub-anestésica útil em curativos."},
{etapa:"adj", d:"VACINA antitetânica",do:"dT ± IGHAT conforme esquema",via:"IM",o:"Sempre questionar esquema. Atualizar se >5 anos (queimadura sujidade). IGHAT 250 UI IM se não-vacinado."},
{etapa:"adj", d:"INTOXICAÇÃO — Hidroxocobalamina (cianeto)",do:"5 g IV em 15 min",via:"IV",o:"Incêndio em ambiente fechado + acidose lática + alteração consciência sem CO suficiente. Disponível em poucos centros."},
{etapa:"adj", d:"Profilaxia úlcera + TEV",do:"IBP + Enoxaparina 40 mg SC/d",via:"IV/SC",o:"Grande queimado: alto risco úlcera de Curling + TEV. Iniciar quando hemorragia controlada."},
{etapa:"alta", d:"CRITÉRIOS DE TRANSFERÊNCIA — ABA",do:"Centro de queimados",via:"—",o:">10% SCQ 2º grau, >5% 3º, face/mãos/pés/períneo/articulações, elétrica/química, inalatória, comorbidades, pediátrico, idoso. CROSS-SP: solicitar vaga."},
{etapa:"alta", d:"Reabilitação precoce",do:"Fisio + nutrição + saúde mental",via:"—",o:"Iniciada na fase aguda. Cicatriz hipertrófica/queloide: pressoterapia, silicone."},
],
alertas:[
{t:"crit",x:"VIA AÉREA — Se evidência inalatória, IOT EM PRECOCE em hospital com recursos. Edema rapidamente progressivo torna IOT mais difícil/impossível."},
{t:"crit",x:"INTOXICAÇÃO CO + CIANETO em incêndio fechado. Suspeitar se acidose lática + ↓consc + carboxiHb >25%. Hidroxocobalamina 5g IV."},
{t:"crit",x:"QUEIMADURA ELÉTRICA: SCQ visível subestima dano profundo. Avaliar rabdomiólise (CPK, urina escura), arritmias (ECG), sd compartimental, lesões internas."},
{t:"warn",x:"NÃO usar gelo. NÃO romper bolhas pequenas. NÃO subdosar analgesia."},
],
fisio:"Lesão tecidual direta + resposta inflamatória sistêmica. >20% SCQ: extravasamento capilar generalizado → choque distributivo + hipovolemia maciça. Hipermetabolismo persistente por meses. Imunossupressão. Catabolismo. Infecção é causa #1 de morte após primeira semana. Lesão inalatória (até 30% mortalidade) por calor (via aérea superior) + toxinas (via aérea inferior) + CO/cianeto sistêmico.",
mec:[
{d:"Ringer Lactato",x:"Cristaloide balanceado — semelhança fisiológica ao plasma. Lactato metabolizado a bicarbonato compensa acidose."},
{d:"Sulfadiazina de Prata",x:"Antiseptico tópico — sulfa + Ag⁺ ativo contra Gram+, Gram-, fungos. Penetração superficial."},
],
diretriz:"American Burn Association (ABA) 2018 Guidelines. ATLS 10ª ed. SBQ — Sociedade Brasileira de Queimaduras.",
fluxo:null, calcs:[],
imgs:[
{src:"https://upload.wikimedia.org/wikipedia/commons/c/ca/Wallace_rule_of_nines.png",
alt:"Regra dos 9 de Wallace — distribuição de superfície corporal",
caption:"Regra dos 9 (Wallace) — cabeça 9%, cada MS 9%, tronco anterior 18%, tronco posterior 18%, cada MI 18%, períneo 1%. Em criança: cabeça 18%, cada MI 13,5%.",
source:"Wikimedia Commons"},
],
},

/* ============== OUTRAS ============== */
{id:"hipotermia", sis:"trauma", grav:"alta",
nome:"Hipotermia",
sin:["hipotermia","frio","T<35"],
def:"Temperatura central <35°C. Leve 32-35: tremor + taquicardia + taquipneia. Moderada 28-32: ↓ tremor + arritmias + ↓consciência. Grave <28: ausência de tremor + bradicardia + apneia + risco FV.",
exames:["Termômetro esofágico/retal/vesical (boca subestima)","ECG (J wave/Osborn em hipotermia <30°C)","Gaso arterial (sem correção de temperatura)","HMG, eletrólitos","Função renal, glicemia, alcoolemia, paracetamol","TC crânio se trauma","Coag (coagulopatia por hipotermia)"],
rx:[
{etapa:"escala", d:"Reaquecimento PASSIVO",do:"Cobertores, ambiente aquecido",via:"—",o:"LEVE (32-35°C). Tremor preservado = sucesso esperado."},
{etapa:"escala", d:"Reaquecimento ATIVO externo",do:"Mantas térmicas, lâmpadas, banho morno",via:"—",o:"Moderada 28-32°C. ATENÇÃO: 'core temperature afterdrop' — sangue periférico frio retorna."},
{etapa:"escala", d:"Reaquecimento ATIVO interno",do:"Cristaloide aquecido a 40°C; O₂ aquecido; lavagem pleural/peritoneal/vesical a 40-45°C",via:"IV/lavado",o:"Grave <28°C. Aquecer 1-2°C/h."},
{etapa:"escala", d:"ECMO/Bypass CP",do:"Reaquecimento extracorpóreo",via:"—",o:"Hipotermia grave instável, PCR. 5-10°C/h. ELEVADA sobrevida em afogamento gelado."},
{etapa:"escala", d:"ACLS modificado",do:"Não declarar morte até T >32-35°C ('No one is dead until warm and dead')",via:"—",o:"RCP/desfibrilação podem ser ineficazes <30°C. Persistir."},
],
alertas:[
{t:"crit",x:"'NO ONE IS DEAD UNTIL WARM AND DEAD'. RCP prolongado em hipotermia → sobrevida descrita após >2h de PCR + reaquecimento ECMO."},
{t:"crit",x:"MANIPULAÇÃO MÍNIMA em hipotermia grave — pode precipitar FV. Posicionar IV, gentilmente."},
{t:"warn",x:"Causas/co-fatores: etilismo, idoso, hipotireoidismo, sepse, drogas (BZD, neurolépticos, opioide), TCE, hipoglicemia."},
],
fisio:"Termorregulação central (hipotálamo) falha → vasoconstrição + tremor inicial → conforme T cai, função celular se reduz progressivamente. Sistema cardiovascular: bradicardia, hipotensão, arritmias (FA → FV <28°C). SNC: ↓consc → coma <30°C. Respiratório: ↓FR → apneia. Renal: 'cold diuresis' (paradoxal). Coagulação: enzimática (inibida pelo frio) — coagulopatia mesmo sem CIVD.",
mec:[],
diretriz:"AHA ACLS 2020 — Hypothermia. Wilderness Medical Society 2019.",
fluxo:null, calcs:[],
},

{id:"golpe-calor", sis:"trauma", grav:"alta",
nome:"Golpe de Calor / Hipertermia",
sin:["golpe de calor","insolação","heat stroke","exaustão por calor"],
def:"Hipertermia >40°C + disfunção do SNC (confusão, convulsão, coma) por falha da termorregulação. Clássico (idoso, onda de calor) ou de esforço (atleta, militar). Diferente de exaustão por calor (T <40, sem disfunção SNC).",
exames:["T central (retal/esofágico — fundamental)","Gaso, lactato, eletrólitos, glicemia","CPK, função renal (rabdomiólise)","Função hepática (lesão térmica)","Coag (CIVD)","ECG","β-HCG"],
rx:[
{etapa:"escala", d:"RESFRIAMENTO IMEDIATO",do:"Imersão em água gelada (atleta) OU spray + ventilador + gelo em axilas/inguinais/pescoço/poplítea",via:"—",o:"PILAR. CADA MINUTO conta. Meta: T <38,5°C em ≤30 min."},
{etapa:"escala", d:"Hidratação cautelosa",do:"SF 0,9% guiado por SSVV (não bolus maciço)",via:"IV",o:"Hipovolemia frequente mas não dominante. Cuidado em idoso cardiopata."},
{etapa:"adj", d:"BZD",do:"Diazepam 5-10 mg IV",via:"IV",o:"Calafrios + agitação (não usar antitérmico — ineficaz, hepatotóxico em paracetamol)."},
{etapa:"adj", d:"NÃO usar antitérmicos",do:"Paracetamol/AINE",via:"—",o:"FALÊNCIA hipotalâmica — não responde. Risco hepato/nefrotoxicidade. Resfriar fisicamente."},
{etapa:"escala", d:"Tratar complicações",do:"Rabdomiólise, IRA, CIVD, arritmia",via:"—",o:"Suporte. UTI."},
{etapa:"escala", d:"Dantrolene",do:"NÃO eficaz",via:"—",o:"Útil em hipertermia MALIGNA anestésica, não em golpe de calor."},
],
alertas:[
{t:"crit",x:"Termômetro RETAL/ESOFÁGICO — boca/axilar subestimam. Sem T central, não há diagnóstico."},
{t:"crit",x:"HEAT STROKE clássico em idoso: mortalidade 10-60% conforme tempo até resfriamento. Onda de calor + paciente isolado em ambiente quente."},
{t:"warn",x:"Drogas: anticolinérgicos, antipsicóticos, simpaticomiméticos (cocaína, anfetamina), diuréticos, álcool — TODOS aumentam risco."},
],
fisio:"Falha de dissipação de calor (radiação, condução, evaporação) supera produção endógena. Hipertermia >40-41°C causa desnaturação proteica + apoptose celular + permeabilidade intestinal (endotoxemia) → resposta inflamatória sistêmica + coagulopatia + falência multissistêmica. Diferente de febre (mediado por citocinas, set point hipotalâmico ajustado — resfriamento físico é ineficaz porque corpo resiste).",
mec:[],
diretriz:"American College of Sports Medicine 2007. Bouchama A, NEJM 2002;346:1978.",
fluxo:null, calcs:[],
},

{id:"hemoptise", sis:"resp", grav:"alta",
nome:"Hemoptise Maciça",
sin:["hemoptise","sangramento pulmonar"],
def:"Eliminação de sangue pela boca proveniente da via aérea (laringe/traqueia/brônquios/parênquima). Maciça: >200-600 mL/24h OU instabilidade hemodinâmica/respiratória. MORTALIDADE 50-80% maciça não tratada — risco PRINCIPAL é asfixia, não hipovolemia.",
exames:["RX/TC tórax + angio-TC (definir sítio + etiologia)","HMG, coag, função renal, gaso","Tipagem + reserva CH","Broncoscopia (diagnóstica + terapêutica)"],
rx:[
{etapa:"inicial", d:"POSICIONAR — decúbito LATERAL do lado SANGRANTE para baixo",do:"Se o sítio é conhecido",via:"—",o:"PILAR. Protege pulmão são. Se desconhecido — decúbito Trendelenburg (pulmonar)."},
{etapa:"inicial", d:"O₂ + via aérea",do:"IOT se necessário (tubo amplo)",via:"—",o:"Tubo grande (8.0+) para broncoscopia. CONSIDERAR IOT seletiva (Carlens) ou bloqueador brônquico do lado sangrante."},
{etapa:"escala", d:"Suporte hemodinâmico",do:"Cristaloide + CH (tipo O- se urgente)",via:"IV",o:"Reverter anticoagulação se aplicável."},
{etapa:"escala", d:"Ácido tranexâmico",do:"500-1000 mg IV em 10 min OU nebulizado 500 mg",via:"IV/Neb",o:"Reduz sangramento — Cochrane 2020. Pode repetir."},
{etapa:"escala", d:"Broncoscopia rígida",do:"Aspiração + cauterização + tamponamento balão",via:"—",o:"Intervenção precoce em centro especializado."},
{etapa:"escala", d:"Embolização ARTÉRIA BRÔNQUICA",do:"Angiografia + embolização",via:"Endovascular",o:"DEFINITIVO. Sucesso 85-95%. Disponível em centros referência."},
{etapa:"escala", d:"Cirurgia",do:"Lobectomia",via:"Cirúrgico",o:"Falha de embolização, sangramento focal localizado."},
],
alertas:[
{t:"crit",x:"ASFIXIA é a causa de morte, não hipovolemia. PROTEGER via aérea + pulmão são."},
{t:"crit",x:"DECÚBITO LATERAL com sítio sangrante PARA BAIXO. Quando se sabe o lado, isso pode salvar a vida."},
{t:"warn",x:"Etiologia em BR: tuberculose ativa/sequela (bronquiectasia, aspergiloma na cavitação), bronquiectasia, neoplasia, micetoma, vasculite, anticoag/anti-plaq, TEP."},
{t:"info",x:"Hemoptise volumosa em paciente jovem feminina = arteriovenosa pulmonar (Osler-Weber-Rendu)?"},
],
fisio:"90% origem em artéria brônquica (alta pressão, sistêmica) — não em circulação pulmonar (baixa pressão). Causas: erosão por inflamação crônica (TB, bronquiectasia), ruptura aneurisma de Rasmussen (TB cavitária), neoplasia, infarto pulmonar (TEP). Anastomoses bronco-pulmonares aumentam em doença crônica.",
mec:[
{d:"Ácido tranexâmico",x:"Antifibrinolítico — análogo lisina, bloqueia sítios de ligação do plasminogênio. ↓dissolução do coágulo, permite hemostasia local."},
],
diretriz:"BTS Guidelines on Hemoptysis. CHEST Guidelines.",
fluxo:null, calcs:[],
},

{id:"sdra", sis:"resp", grav:"alta",
nome:"SDRA / ARDS",
sin:["SDRA","ARDS","Berlin","Síndrome do Desconforto Respiratório Agudo"],
def:"Síndrome inflamatória pulmonar AGUDA — Berlin 2012: início <7 dias + infiltrado bilateral RX/TC + sem evidência de origem cardíaca + hipoxemia. Leve (P/F 200-300, PEEP ≥5), moderada (P/F 100-200), grave (P/F <100).",
exames:["Gaso arterial — calcular P/F","RX/TC tórax","Ecocardiograma (excluir cardiogênico)","HMG + cultura ampla (sepse é causa #1)","BNP, troponina"],
rx:[
{etapa:"escala", d:"Tratar CAUSA",do:"Sepse, pneumonia, aspiração, trauma, transfusão (TRALI), pancreatite",via:"—",o:"PILAR. Sem isso, suporte é apenas paliativo."},
{etapa:"escala", d:"VM PROTETORA (Vt baixo)",do:"Vt 6 mL/kg peso PREDITO + Pplat <30 + driving pressure <15 cmH₂O",via:"VM",o:"ARDSnet — reduz mortalidade. Peso PREDITO (50 + 0,91 × (altura cm - 152,4) H, 45,5 + 0,91 × (altura cm - 152,4) M)."},
{etapa:"escala", d:"PEEP MAIS ALTO",do:"Tabela PEEP/FiO₂ alta (ALVEOLI/EXPRESS)",via:"VM",o:"Mod-grave SDRA. Iniciar 10-12. Titular pela P/F."},
{etapa:"escala", d:"Pronação 16h/d",do:"Posição prona em P/F <150",via:"—",o:"PROSEVA — ↓mortalidade significativamente. Manter 16h/24h, alternando."},
{etapa:"escala", d:"Sedação + curare (BNM)",do:"Sedação profunda + cisatracurio 0,15 mg/kg + 0,3 mg/kg/h",via:"IV",o:"48h em SDRA grave inicial (P/F <120). Reduz mortalidade (ACURASYS). Reavaliar."},
{etapa:"escala", d:"Balanço hídrico negativo",do:"Diurético se euvolêmico + estável",via:"IV",o:"FACTT trial — estratégia conservadora melhora dias livres VM."},
{etapa:"escala", d:"ECMO",do:"VV-ECMO",via:"—",o:"P/F <80 refratário, hipercapnia severa, lesão pulmonar primária reversível. Transferir CENTRO referência."},
{etapa:"adj", d:"NÃO usar — não recomendado",do:"Corticoide rotineiro, surfactante exógeno, β2 alta dose",via:"—",o:"Sem benefício. Corticoide em SDRA por COVID/pneumonia tem evidência (RECOVERY)."},
],
alertas:[
{t:"crit",x:"VM PROTETORA é a única intervenção MORTALIDADE-REDUTORA com evidência sólida. Vt baixo + Pplat baixo SEMPRE — mesmo com 'rebote' de PCO₂ ('permissive hypercapnia')."},
{t:"crit",x:"Pronação NÃO É opcional em P/F <150 — é intervenção de UTI básica em SDRA moderado-grave."},
{t:"warn",x:"Diferencial: SDRA vs edema agudo cardiogênico — ECO + BNP + resposta a diurético. SDRA pode coexistir com IC."},
],
fisio:"Lesão alveolar difusa por estímulo direto (pneumonia, aspiração, contusão, inalação) ou indireto (sepse, pancreatite, transfusão, choque). Fase exsudativa (D1-7): edema rico em proteína + dano endotelial/epitelial + membranas hialinas. Fase proliferativa (D7-21): tentativa de reparo. Fase fibrótica (>21d): fibrose pulmonar.",
mec:[
{d:"Cisatracurio",x:"Bloqueador neuromuscular — antagonista nicotínico competitivo. Eliminação Hofmann (não-renal, não-hepática) — ideal em UTI."},
],
diretriz:"Berlin Definition (ARDS Definition Task Force, JAMA 2012;307:2526). ARDSnet (NEJM 2000;342:1301). PROSEVA (Guérin C et al., NEJM 2013;368:2159). ESICM/ATS/SCCM 2017 (Fan E et al., Am J Respir Crit Care Med 2017;195:1253, DOI:10.1164/rccm.201703-0548ST).",
fluxo:null, calcs:[],
},

{id:"retencao-urinaria", sis:"gu", grav:"media",
nome:"Retenção Urinária Aguda",
sin:["retenção urinária","RUA","sondagem","cateterismo vesical"],
def:"Incapacidade súbita de esvaziar a bexiga, ± dor suprapúbica + globo vesical palpável. H idoso: HPB descompensada (mais comum). M: causas diversas — bexiga neurogênica, ITU, fecaloma, medicações (anticolinérgicos, opioides).",
exames:["Bexigoma palpável / USG point-of-care (>300-500 mL)","EAS + urocultura","Função renal (ureia/Cr — hidronefrose?)","PSA H >50a","Eletrólitos","RX abdome (fecaloma, urolitíase)"],
rx:[
{etapa:"escala", d:"Cateterismo VESICAL de alívio",do:"Foley 14-18 Fr lubrificada",via:"—",o:"DRENAR — alívio imediato. Esvaziar GRADUALMENTE (clampar após 500 mL × 10-15 min) para evitar hematúria 'ex-vacuo' e hipotensão."},
{etapa:"escala", d:"Cateter SUPRAPÚBICO",do:"Punção 2 dedos acima da sínfise",via:"—",o:"Falha de Foley (estenose uretral, próstata muito aumentada, falha técnica) — chamar urologista."},
{etapa:"escala", d:"α-bloqueador",do:"Tansulosina 0,4 mg VO/d ou Doxazosina 2-4 mg/d",via:"VO",o:"H com HPB — começar precoce. Aumenta taxa de sucesso de trial sem cateter."},
{etapa:"escala", d:"ATB se ITU",do:"Conforme antibiograma; Ceftriaxona 1-2 g IV se febre/sepse",via:"IV/VO",o:"Trato urinário superior — sempre ATB."},
{etapa:"escala", d:"Trial sem cateter (TWOC)",do:"Após 24-72h com α-bloq",via:"—",o:"Sucesso 40-60% em retenção 1ª. Falha → urologia para avaliar próstata + uretra."},
{etapa:"inicial", d:"Tratar fecaloma",do:"Toque retal + lavagem retal (glicerina 12% 500 mL)",via:"—",o:"Causa frequente em idoso/acamado. Sondagem alivia sintomas mas não trata."},
],
alertas:[
{t:"crit",x:"BEXIGA NEUROGÊNICA com hidronefrose bilateral + sintomas neuro novos = SÍNDROME DA CAUDA EQUINA — urgência neurocirúrgica. Avaliar reflexos perineais."},
{t:"warn",x:"Drenagem rápida >500 mL pode causar hipotensão por reflexo + hematúria ex-vácuo. CLAMPAR e drenar gradualmente."},
{t:"warn",x:"H idoso com retenção urinária em uso recente de anticolinérgico (anti-H1 OTC, oxibutinina) — suspender medicação."},
],
fisio:"Causas obstrutivas: HPB (mais comum H), estenose uretral, cálculo impactado, neoplasia, fecaloma, prolapso. Causas neurogênicas: lesão medular, esclerose múltipla, AVC, DM, pós-anestesia/cirurgia. Farmacológicas: anticolinérgicos, opioides, β-bloq, BCC, anti-H1, descongestionantes. Bexiga aguda distendida → ↑pressão → refluxo vésico-ureteral → hidronefrose + lesão renal.",
mec:[
{d:"Tansulosina",x:"α1a-bloqueador seletivo (próstata) — relaxa músculo liso prostático/uretral, ↓resistência ao esvaziamento."},
],
diretriz:"EAU Guidelines Urological Trauma. AUA Guidelines.",
fluxo:null, calcs:[],
},

{id:"priapismo", sis:"gu", grav:"alta",
nome:"Priapismo",
sin:["priapismo","ereção prolongada"],
def:"Ereção persistente >4h, NÃO relacionada a estimulação sexual. ISQUÊMICO (baixo fluxo): doloroso, rígido, EMERGÊNCIA — falência fluxo arterial → necrose corpo cavernoso → impotência permanente. NÃO-ISQUÊMICO (alto fluxo): trauma perineal, indolor, parcial, NÃO urgência.",
exames:["GASO sangue cavernoso (punção): isquêmico = PaO₂ <30, PaCO₂ >60, pH <7,25; não-isq = arterial","HMG (descartar falcêmico)","β-HCG não aplicável","Função renal","Investigar causa: falciforme (eletroforese), leucemia, drogas (sildenafil, cocaína, antipsicóticos)","Doppler peniano em casos selecionados"],
rx:[
{etapa:"inicial", d:"ASPIRAÇÃO + IRRIGAÇÃO cavernosa",do:"Agulha 21G na lateral da base do pênis; aspirar 30-50 mL sangue + irrigar SF",via:"—",o:"1ª linha priapismo isquêmico <6h. Anestesia local (bloqueio peniano). Repetir conforme resposta."},
{etapa:"escala", d:"Fenilefrina intracavernosa",do:"100-500 mcg/mL — 1 mL a cada 5-10 min (máx 1 mg) APÓS aspiração",via:"—",o:"Vasoconstrição local. Monitor PA (risco HAS sistêmica). Diluir 1 mL fenilefrina 10 mg em 99 mL SF (100 mcg/mL)."},
{etapa:"escala", d:"Falcêmico — exsanguineotransfusão",do:"Eritroaférese, alvo HbS <30%",via:"IV",o:"Em PARALELO com manejo local. Não atrasar tratamento peniano."},
{etapa:"escala", d:"Cirurgia (Shunt)",do:"Winter / Ebbehoj / Quackels / Grayhack",via:"Cirúrgico",o:"Falha de tratamento conservador >24-48h. Urologista."},
{etapa:"adj", d:"Hidratação + analgesia",do:"IV vigorosa",via:"IV",o:"Especialmente em falcêmico."},
],
alertas:[
{t:"crit",x:"PRIAPISMO ISQUÊMICO >24h = impotência permanente quase certa. EMERGÊNCIA — não 'aguardar resolução espontânea'."},
{t:"crit",x:"Sildenafil/tadalafil + cocaína/anfetamina ou trazodona/risperidona — combinações de risco."},
{t:"warn",x:"Diferenciar isquêmico (rígido + doloroso, alto risco) de não-isquêmico (parcial, indolor, pós-trauma — angiografia + embolização eletiva)."},
],
fisio:"Isquêmico (baixo fluxo): obstrução do retorno venoso pelo plexo venoso peniano → estagnação → hipóxia + acidose + edema endotelial → fibrose corpo cavernoso. Causas: falciforme (vaso-oclusão), leucemia/mieloma (hiperviscosidade), drogas (PDE5i, antipsicóticos, trazodona, anticoag, cocaína), idiopático. Não-isquêmico: laceração arterial peniana pós-trauma perineal → fluxo descontrolado, sem isquemia.",
mec:[
{d:"Fenilefrina",x:"α1-agonista puro → vasoconstrição. Reverte preenchimento corpo cavernoso."},
],
diretriz:"AUA Guidelines on Priapism 2003 (atualização 2021). EAU.",
fluxo:null, calcs:[],
},

{id:"abscesso-peri", sis:"infecto", grav:"media",
nome:"Abscesso Periamigdaliano (Quinsy)",
sin:["abscesso periamigdaliano","Quinsy","peritonsilar"],
def:"Coleção purulenta entre cápsula amigdaliana e músculo constrictor superior. Complicação de amigdalite — odinofagia intensa unilateral + voz 'em batata quente' + trismo + desvio da úvula + abaulamento do pilar amigdaliano + linfadenopatia cervical. Mais comum em adultos jovens.",
exames:["Diagnóstico CLÍNICO — visualização do abaulamento + trismo + desvio úvula","HMG, PCR (leucocitose com desvio)","Hemoculturas se sepse","Cultura material drenado","TC pescoço com contraste se: complicação suspeita (extensão parafaríngea, Lemierre)"],
rx:[
{etapa:"escala", d:"DRENAGEM CIRÚRGICA",do:"Punção aspirativa OU incisão + drenagem com bisturi",via:"—",o:"PILAR. Anestesia local (xilocaína spray 10% + lidocaína injetável). OTORRINO ou emergencista experiente."},
{etapa:"atb", d:"Ceftriaxona + Clindamicina",do:"1-2 g IV + 600 mg IV 8/8h",via:"IV",o:"Cobertura aerobios (Strep) + anaeróbios (Fusobacterium, Prevotella). MS-aprovado."},
{etapa:"atb", d:"Ampicilina-sulbactam",do:"3 g IV 6/6h",via:"IV",o:"Alternativa monoterápica. Ou amoxicilina-clavulanato 1g VO 8/8h após melhora."},
{etapa:"adj", d:"Corticoide",do:"Dexametasona 10 mg IV dose única",via:"IV",o:"Reduz edema + odinofagia + tempo internação. Evidência crescente."},
{etapa:"escala", d:"Hidratação",do:"SF 0,9% — paciente geralmente desidratado (não engole)",via:"IV",o:""},
{etapa:"adj", d:"Analgesia",do:"Dipirona + tramadol; eventualmente morfina",via:"IV",o:"Dor intensa."},
{etapa:"escala", d:"Tonsilectomia (à quente)",do:"Procedimento eletivo após resolução",via:"Cirúrgico",o:"Recorrente (≥2 episódios) ou complicação tonsilar — eletiva. 'À quente' = durante episódio, controversa."},
],
alertas:[
{t:"crit",x:"COMPLICAÇÕES TEMÍVEIS: extensão para espaço parafaríngeo → mediastinite descendente; Sd. de Lemierre (tromboflebite jugular interna por Fusobacterium); aspiração do conteúdo abscesso → pneumonia/SDRA."},
{t:"crit",x:"Trismo grave + estridor + sialorreia = obstrução via aérea iminente — IOT com cuidado (preferencialmente acordada/fibroscopia)."},
{t:"warn",x:"Diferenciar de amigdalite simples (sem abaulamento, úvula central, trismo leve)."},
],
fisio:"Inflamação periamigdaliana progride para abscesso loculado entre a cápsula amigdaliana e músculo constrictor superior. Polimicrobiana — Strep do grupo A (40-50%), anaeróbios (Fusobacterium, Prevotella, Peptostreptococcus). Tratamento pode incluir só drenagem agulha + ATB, sem incisão.",
mec:[],
diretriz:"IDSA Guidelines on Pharyngitis. UpToDate.",
fluxo:null, calcs:[],
},

{id:"reacao-transf", sis:"hemo", grav:"alta",
nome:"Reação Transfusional",
sin:["reação transfusional","TRALI","TACO","RTA hemolítica"],
def:"Reação adversa durante/após transfusão. Tipos críticos: HEMOLÍTICA AGUDA (incompatibilidade ABO, mortalidade alta), TRALI (lesão pulmonar relacionada à transfusão), TACO (sobrecarga circulatória), reação alérgica grave/anafilaxia. Outras: febril não-hemolítica, séptica, urticariforme.",
exames:["PARAR transfusão IMEDIATAMENTE","Reavaliar identificação paciente x bolsa","Coombs direto + tipagem repetida","HMG, LDH, bilirrubina indireta, haptoglobina","EAS (Hb urinária = hemoglobinúria — hemólise)","Função renal","RX tórax (TRALI/TACO)","Hemoculturas do paciente + bolsa (reação séptica)","Eletrólitos, K (hemólise + hipercalemia)"],
rx:[
{etapa:"inicial", d:"PARAR transfusão",do:"Imediato",via:"—",o:"PILAR. Manter acesso com SF separado."},
{etapa:"escala", d:"Notificar banco de sangue",do:"Devolver bolsa + tubos para investigação",via:"—",o:"Sempre. Notificação compulsória."},
{etapa:"escala", d:"Reação HEMOLÍTICA AGUDA",do:"Hidratação vigorosa (SF 200-500 mL/h) + manter PAM ≥65 + manitol/furosemida para débito >100 mL/h",via:"IV",o:"Proteção renal. ALERTAR CIVD. Hemodiálise se IRA."},
{etapa:"escala", d:"TRALI",do:"Suporte ventilatório protetor (Vt 6 mL/kg) — geralmente requer IOT",via:"VM",o:"Distingue de TACO: TRALI sem sobrecarga, BNP normal, biópsia anti-HLA/HNA do doador. Mortalidade 5-25%."},
{etapa:"escala", d:"TACO",do:"Diurético (furosemida 40-80 mg IV) + VNI + restrição volume",via:"IV",o:"Idoso, cardiopata, RN, IRC = risco. Prevenção: transfusão lenta + diurético entre bolsas."},
{etapa:"escala", d:"ANAFILAXIA",do:"Adrenalina 0,3-0,5 mg IM + suporte (ver patologia)",via:"IM",o:"IgA deficiente + IgG anti-IgA é causa clássica."},
{etapa:"escala", d:"Febril não-hemolítica",do:"Paracetamol 1 g + suspender bolsa se T >2°C acima basal ou sintomas",via:"VO/IV",o:"Reação mais comum. Geralmente benigna mas exclui sempre as graves."},
{etapa:"escala", d:"Séptica",do:"ATB amplo espectro empírico (vancomicina + cefepima/ceftazidima)",via:"IV",o:"Bolsa contaminada (mais comum plaquetas armazenadas). Suporte sepse."},
],
alertas:[
{t:"crit",x:"DOR LOMBAR + FEBRE + HIPOTENSÃO + URINA ESCURA durante transfusão = HEMÓLISE AGUDA INTRAVASCULAR. Parar imediato. Frequentemente fatal."},
{t:"crit",x:"TRALI vs TACO: ambos têm dispneia + infiltrado RX nas primeiras 6h pós-transfusão. TACO = sobrecarga (↑BNP, ↑PA, ↑PVC); TRALI = lesão (BNP normal, sem sobrecarga, geralmente PA cai)."},
{t:"warn",x:"REAÇÃO DEMORA: TRALI/TACO podem se apresentar até 6h pós; hemólise tardia até 14 dias."},
{t:"info",x:"Hemovigilância: notificar SISVAN/HEMOVIGILÂNCIA."},
],
fisio:"Hemólise aguda: incompatibilidade ABO (erro de identificação — humano, não laboratorial). Anticorpos pré-formados do receptor atacam hemácias do doador → hemólise intravascular maciça → liberação Hb → IRA + CIVD + choque. TRALI: anticorpos anti-HLA/HNA do doador ativam neutrófilos do receptor → lesão alveolar. TACO: simples sobrecarga de volume. Anafilaxia: IgE-mediada, geralmente IgA-deficiente.",
mec:[],
diretriz:"AABB (American Association of Blood Banks). ANVISA — Hemovigilância. Diretrizes SUS para Hemoterapia.",
fluxo:null, calcs:[],
},

{id:"civd", sis:"hemo", grav:"alta",
nome:"CIVD — Coagulação Intravascular Disseminada",
sin:["CIVD","DIC","coagulação intravascular disseminada","coagulopatia consumo"],
def:"Síndrome adquirida de ativação patológica da coagulação → consumo de fatores e plaquetas → sangramento + microtromboses paradoxal. Sempre secundária — investigar a CAUSA. Critérios ISTH: TAP/INR, plaq, fibrinogênio, D-dímero — escore ≥5 = CIVD.",
exames:["TP/INR, TTPA (alargados)","Fibrinogênio (BAIXO; alto não exclui — proteína de fase aguda)","D-dímero (MUITO ALTO)","Plaquetas (BAIXAS, em queda)","Esfregaço (esquistócitos — microangiopatia)","HMG completo + função renal/hepática","Investigar causa: hemoculturas, β-HCG, função tireoidiana, RX, TC"],
rx:[
{etapa:"escala", d:"TRATAR CAUSA",do:"Sepse → ATB + controle foco; obstétrica → resolução; trauma → cirurgia; neoplasia → quimio",via:"—",o:"PILAR. Sem isso, intervenção é paliativa."},
{etapa:"escala", d:"Reposição fatores SE sangramento ATIVO",do:"PFC 10-15 mL/kg + crioprecipitado (fibrinogênio <100) + plaquetas (se <20-50k)",via:"IV",o:"NÃO repor por valores baixos isolados sem sangramento — alimenta a coagulação intravascular."},
{etapa:"anticoag", d:"Heparina (microtromboses dominantes)",do:"HNF 500 UI/h IV (dose baixa) ou HBPM dose profilática",via:"IV/SC",o:"INDICAÇÕES: predomínio trombótico (pele, gangrena, IRA isquêmica), CIVD crônica de neoplasia, em ausência de sangramento ativo grave. CONTROVERSO em CIVD aguda."},
{etapa:"escala", d:"Antifibrinolítico",do:"Ácido tranexâmico 1g IV — CAUTELOSO",via:"IV",o:"Excepcional — em CIVD com predomínio hiperfibrinolítico (leucemia M3, próstata, hemorragia maciça obstétrica) sob orientação hematologista."},
{etapa:"escala", d:"Vit K",do:"10 mg IV/d × 3 dias",via:"IV",o:"Cofator dos fatores II/VII/IX/X — pode estar deficiente em CIVD prolongada."},
{etapa:"escala", d:"Antitrombina, proteína C ativada",do:"—",via:"—",o:"NÃO recomendadas rotineiramente (Xigris retirado do mercado)."},
],
alertas:[
{t:"crit",x:"CIVD é DIAGNÓSTICO DA DOENÇA DE BASE — não tratar 'a CIVD'. Tratar SEPSE, choque, neoplasia, HELLP, obstétrica, trauma."},
{t:"crit",x:"NÃO repor sangue por números laboratoriais — repor SE sangramento ATIVO. Procoagulantes 'alimentam' processo intravascular."},
{t:"warn",x:"Causas comuns BR: sepse (#1), obstétrica (DPP, embolia LA, HPP), trauma maciço, leucemia M3 (LMA M3 = emergência hematológica)."},
],
fisio:"Doença de base libera fator tecidual (TF) sistemicamente → ativação maciça e descontrolada da coagulação → microtrombos disseminados + consumo de fatores/plaquetas + ativação fibrinolítica secundária (PAI-1 alto inicialmente, depois tPA) → padrão paradoxal: trombose microvascular (lesão isquêmica MOF) + sangramento (consumo). LMA M3 (leucemia promielocítica): grânulos liberam TF + anexina A2 → hiperfibrinólise dominante.",
mec:[],
diretriz:"ISTH 2018 (Wada H et al., J Thromb Haemost 2018;16:1929). British Society for Haematology 2009.",
fluxo:null, calcs:[],
},

);
