/* PARTE 2: GI + Endócrino + GU + Osteomuscular + Psiquiatria + Hidroeletrolítico */
PATOLOGIAS.push(
/* ============== GI ============== */
{
  id:"nausea", sis:"gi", grav:"baixa",
  nome:"Náuseas e Vômitos",
  sin:["náusea","vômito","êmese","antiemético"],
  def:"Sintomas inespecíficos. Sempre investigar causa: gastroenterite, gestação, intox, obstrução, central (HIC, vertigem), drogas (opioides, quimioterapia).",
  exames:["Glicemia","Eletrólitos (Na, K)","Função renal","β-HCG em mulher fértil","Considerar imagem se obstrução"],
  rx:[
    {etapa:"adj", d:"Ondansetrona",do:"4–8 mg IV/VO/SL 8/8h",via:"IV/VO/SL",o:"1ª escolha em gastroenterite/quimio. Cuidado: prolonga QT."},
    {etapa:"adj", d:"Metoclopramida",do:"10 mg IV/IM/VO 8/8h",via:"IV/IM/VO",o:"Procinético. Risco de distonia/SEP em jovem; CI em obstrução."},
    {etapa:"adj", d:"Bromoprida",do:"10 mg IV/VO 8/8h",via:"IV/VO",o:"Alternativa ao metoclopramida."},
    {etapa:"escala", d:"Dimenidrato",do:"50–100 mg IV/IM",via:"IV/IM",o:"Cinetose, vertigem. Sedativo."},
  ],
  alertas:[
    {t:"warn",x:"Vômitos persistentes + cefaleia/papiledema = HIC. Vômitos + sinais de obstrução abdominal = não usar procinético."},
  ],
  fisio:"O vômito é coordenado por núcleos no tronco encefálico (zona quimiorreceptora gatilho — área postrema) ativados por estímulos serotoninérgicos (5-HT3), dopaminérgicos (D2), histaminérgicos (H1), muscarínicos (M1) e NK1. Antieméticos atuam em diferentes receptores.",
  mec:[
    {d:"Ondansetrona",x:"Antagonista <strong>5-HT3</strong> central (área postrema) e periférico (aferências vagais entéricas)."},
    {d:"Metoclopramida",x:"Antagonista <strong>D2</strong> central + agonista <strong>5-HT4</strong> (procinético TGI superior)."},
    {d:"Dimenidrato",x:"Antagonista <strong>H1</strong> central + anticolinérgico — suprime núcleo vestibular e centro do vômito."},
  ],
  diretriz:"Diretrizes brasileiras de antieméticos (SBOC 2018); IDSA gastroenterite 2017.",
  calcs:[],
},
{
  id:"diarreia", sis:"gi", grav:"baixa",
  nome:"Diarreia Aguda",
  sin:["diarreia","gastroenterite","disenteria"],
  def:"≥3 evacuações líquidas/24h <14 dias. Maioria viral autolimitada. Investigar disenteria (sangue/muco/febre alta) e desidratação.",
  exames:["Hemograma + eletrólitos se desidratação","Função renal","Coprocultura se disenteria, imunossupressão, viagem","Toxina C. difficile se ATB recente"],
  rx:[
    {etapa:"escala", d:"SRO/Reidratação oral",do:"50–100 mL após cada evacuação",via:"VO",o:"PILAR. Reidratação suficiente em 90% dos casos."},
    {etapa:"escala", d:"SF 0,9%",do:"30 mL/kg em 30 min se grave",via:"IV",o:"Desidratação grave."},
    {etapa:"escala", d:"Racecadotrila",do:"100 mg VO 8/8h × ≤7 dias",via:"VO",o:"Antissecretor sem efeito na motilidade. Útil em diarreia secretora."},
    {etapa:"escala", d:"Saccharomyces boulardii",do:"500 mg VO 12/12h × 5 dias",via:"VO",o:"Probiótico, especialmente em diarreia pós-ATB."},
    {etapa:"atb", d:"Ciprofloxacino",do:"500 mg VO 12/12h × 3–5 dias",via:"VO",o:"Disenteria moderada/grave (sangue, febre), viajante, imunossuprimido."},
    {etapa:"atb", d:"Metronidazol",do:"500 mg VO 8/8h × 10–14 dias",via:"VO",o:"Suspeita de C. difficile ou amebíase."},
  ],
  alertas:[
    {t:"warn",x:"NÃO usar loperamida (antimotílico) em disenteria — risco de megacólon tóxico e prolongamento da infecção."},
    {t:"info",x:"Reidratação ORAL é superior a IV na maioria. Reservar IV para choque/vômito persistente/coma."},
  ],
  fisio:"Mecanismos: <strong>osmótica</strong> (má absorção — vírus, lactose), <strong>secretora</strong> (toxinas — ETEC, cólera), <strong>inflamatória/invasiva</strong> (Shigella, Salmonella, C. jejuni, EHEC) e <strong>motilidade ↑</strong>. Vírus (norovírus, rotavírus) causam ~70% das diarreias agudas no adulto.",
  mec:[
    {d:"Racecadotrila",x:"Inibe <strong>encefalinase intestinal</strong> → ↑encefalinas → ↓secreção hidroeletrolítica. Não afeta motilidade (vs. loperamida)."},
    {d:"Ciprofloxacino",x:"Fluoroquinolona — inibe DNA-girase e topoisomerase IV bacterianas."},
  ],
  diretriz:"IDSA — Infectious Diarrhea (Shane AL et al., CID 2017;65:e45–e80).",
  calcs:[],
},
{
  id:"hemorroida", sis:"gi", grav:"baixa",
  nome:"Doença Hemorroidária",
  sin:["hemorroidas","hemorroida","fissura anal"],
  def:"Dilatação dos plexos hemorroidários internos (escala I–IV) ou externos. Manifestações: hematoquezia, prolapso, dor (trombose).",
  exames:["Anuscopia/toque","Hemograma se sangramento significativo"],
  rx:[
    {etapa:"escala", d:"Banho de assento morno",do:"15 min, 3×/d",via:"Tópico",o:"Conservador, alívio de dor e edema."},
    {etapa:"escala", d:"Dieta com fibras",do:"25–35 g/d + ≥2L água",via:"VO",o:"Pilar da prevenção. Suplemento: psyllium 5 g 8/8h."},
    {etapa:"escala", d:"Diosmina + Hesperidina",do:"450/50 mg 6/6h por 4 dias, depois 12/12h",via:"VO",o:"Flebotônico — ↑tônus venoso, ↓permeabilidade."},
    {etapa:"escala", d:"Policresuleno + Cinchocaína",do:"Pomada 2–3×/d",via:"Tópico",o:"Sintomático. Lidocaína em gel é alternativa."},
    {etapa:"adj", d:"Trombose hemorroidária",do:"Excisão em <48h se dor intensa",via:"Cirúrgico",o:"Após 48h tende a regredir; pomada + analgesia."},
  ],
  alertas:[
    {t:"info",x:"Hematoquezia indolor em >40a: sempre excluir CCR — encaminhar para colonoscopia."},
  ],
  fisio:"Aumento da pressão venosa nos plexos hemorroidários (esforço evacuatório, obstipação, gestação, sedentarismo) → dilatação → prolapso/sangramento. Trombose externa: coágulo agudo em vênula = dor intensa.",
  mec:[
    {d:"Diosmina + Hesperidina",x:"Flavonoides — ↑tônus venoso (efeito noradrenalina-mediado), ↓permeabilidade capilar, anti-inflamatório."},
  ],
  diretriz:"ASCRS Clinical Practice Guidelines for Hemorrhoids (Davis BR et al., Dis Colon Rectum 2018).",
  calcs:[],
},
{
  id:"hda", sis:"gi", grav:"alta",
  nome:"Hemorragia Digestiva Alta (HDA)",
  sin:["HDA","hematêmese","melena","sangramento digestivo"],
  def:"Sangramento proximal ao ângulo de Treitz. Hematêmese, vômitos em borra de café, melena. Estabilizar + EDA em até 24h. Varicoso vs não-varicoso.",
  exames:["Hemograma seriado","Coagulograma + plaquetas","Função renal + ureia (↑desproporcional)","Tipagem + reserva CH","ECG (ICAD)","Glasgow-Blatchford"],
  rx:[
    {etapa:"inicial", d:"Avaliação inicial + Glasgow-Blatchford",do:"PA, FC, Hb, ureia, creatinina, estado mental",via:"—",o:"GB 0-1 = baixo risco, alta ambulatorial possível. Maior = internar. Buscar sinais de choque (FC>100, PAS<100, frio, oligúria, ↓consciência)."},
    {etapa:"inicial", d:"2 acessos calibrosos + tipagem",do:"16G ou 14G + reserva CH",via:"—",o:"Em hipovolemia: 2 jelcos amplos. Coletar HMG + coag + tipagem na mesma punção."},
    {etapa:"inicial", d:"SNG (apenas se diagnóstico duvidoso)",do:"Lavagem + aspiração",via:"—",o:"NÃO obrigatório. Útil se dúvida HDA vs HDB. Sangue franco = HDA. Café = HDA antiga."},
    {etapa:"escala", d:"① VOLUME — Cristaloide",do:"500-1000 mL bolus, repetir conforme resposta",via:"IV",o:"Alvo PAM ≥65 (não normalizar PA em sangramento ativo — pode piorar)."},
    {etapa:"escala", d:"② TRANSFUSÃO — Concentrado de hemácias",do:"1 UI eleva Hb ~1 g/dL",via:"IV",o:"Alvo Hb >7 (geral) ou >8 (cardiopata). Estratégia RESTRITIVA > liberal (Villanueva NEJM 2013)."},
    {etapa:"escala", d:"③ CHOQUE — Transfusão maciça",do:"Proporção 1:1:1 (CH:PFC:plaquetas)",via:"IV",o:"Em choque grave. Acionar banco de sangue + ácido tranexâmico 1g IV (controverso em HDA — discutir)."},
    {etapa:"escala", d:"④ EDA TERAPÊUTICA em ≤24h",do:"Hemoclipe, escleroterapia, ligadura elástica (varizes)",via:"—",o:"Padrão-ouro diagnóstico-terapêutico. Acionar endoscopia precoce. Estabilizar paciente antes."},
    {etapa:"escala", d:"NÃO-VARICOSO — Omeprazol IV",do:"80 mg IV bolus + 8 mg/h BIC × 72h",via:"IV",o:"Antes da EDA em sangramento ativo. Após EDA: ajustar conforme achado (Forrest)."},
    {etapa:"atb", d:"VARICOSO — Terlipressina",do:"2 mg IV 4/4h × 24h, depois 1 mg 4/4h × 3-5 dias",via:"IV",o:"Suspeita: cirrótico, ascite, encefalopatia, varizes prévias. Reduz pressão portal."},
    {etapa:"escala", d:"VARICOSO — Octreotide (alternativa)",do:"50 mcg IV bolus + 50 mcg/h BIC × 3-5 dias",via:"IV",o:"Alternativa à terlipressina onde indisponível. Sem grandes diferenças de eficácia."},
    {etapa:"atb", d:"PROFILAXIA PBE (cirrótico) — Ceftriaxona",do:"1 g IV/d × 7 dias",via:"IV",o:"OBRIGATÓRIA em cirrótico com HDA. Reduz mortalidade (NNT 22). Norfloxacino VO alternativa."},
    {etapa:"adj", d:"Pré-EDA: Eritromicina (opcional)",do:"250 mg IV 30 min antes",via:"IV",o:"Procinético — limpa estômago, melhora visualização. Sem benefício de mortalidade comprovado mas pode reduzir necessidade de 2ª EDA."},
    {etapa:"adj", d:"Reversão de anticoagulação se em uso",do:"Conforme droga: vit K + PCC (varfarina), idarucizumab (dabigatrana), etc.",via:"IV",o:"Sangramento grave + anticoagulado = reverter. Discutir risco/benefício (válvula mecânica, TEP recente)."},
    {etapa:"alta", d:"IBP de manutenção pós-controle",do:"Omeprazol 40 mg VO/d × 4-8 semanas (úlcera) ou crônico",via:"VO",o:"Cicatrização úlcera. Pesquisa + erradicação H. pylori. Suspender AINE/AAS quando possível."},
  ],
  alertas:[
    {t:"crit",x:"Choque hipovolêmico: ressuscitação balanceada + transfusão maciça (CH:plasma:plaq 1:1:1) + ácido tranexâmico 1 g IV."},
    {t:"info",x:"Glasgow-Blatchford 0–1 = baixíssimo risco, considerar alta ambulatorial."},
  ],
  fisio:"Causas: úlcera péptica (50%), varizes esofagogástricas (10–15%, mortalidade ~20%), Mallory-Weiss (10%), erosões/gastrite, neoplasia, malformação vascular. A perda volêmica aguda gera resposta adrenérgica e ativação renina-angiotensina; coagulopatia dilucional surge após >4–6 UI CH sem fator de coagulação.",
  mec:[
    {d:"Omeprazol",x:"Inibidor de bomba de prótons — bloqueia <strong>H⁺/K⁺-ATPase</strong> nas células parietais → ↑pH gástrico (>6) estabiliza coágulo de fibrina."},
    {d:"Terlipressina",x:"Análogo de vasopressina — agonista <strong>V1</strong> nos vasos esplâncnicos → vasoconstrição → ↓fluxo portal e ↓pressão varicosa."},
    {d:"Octreotide",x:"Análogo de somatostatina — ↓liberação de glucagon (vasodilatador esplâncnico) → vasoconstrição esplâncnica indireta."},
  ],
  diretriz:"ACG Guidelines HDA Não-Varicosa (Laine L et al., Am J Gastroenterol 2021;116:899–917). Baveno VII Consensus 2022 (varizes).",
  calcs:["blatchford"],
},
{
  id:"hdb", sis:"gi", grav:"alta",
  nome:"Hemorragia Digestiva Baixa (HDB)",
  sin:["HDB","hematoquezia","retorragia"],
  def:"Sangramento distal ao Treitz. Hematoquezia/enterorragia. Causas: diverticular (40%), angiodisplasia, neoplasia, doença inflamatória, hemorroida.",
  exames:["Hemograma + coagulograma","Tipagem","Colonoscopia <24h se estável","Angio-TC se ativo/instável"],
  rx:[
    {etapa:"inicial", d:"Reanimação volêmica",do:"SF/Ringer + CH",via:"IV",o:"Mesma estratégia que HDA. Restritiva (Hb>7)."},
    {etapa:"inicial", d:"Suspender anticoagulante/antiagregante",do:"Conforme situação",via:"—",o:"Considerar reversão se grave (vit K, andexanet, idarucizumabe)."},
    {etapa:"escala", d:"Colonoscopia + hemostasia endoscópica",do:"Clip, escleroterapia, eletrocoagulação",via:"—",o:"Diagnóstico + terapêutica."},
    {etapa:"escala", d:"Embolização angiográfica",do:"—",via:"—",o:"Sangramento ativo refratário à endoscopia."},
  ],
  alertas:[
    {t:"warn",x:"15% das HDB \"baixas\" são na verdade HDA com trânsito rápido — considerar EDA se hemodinamicamente instável."},
  ],
  fisio:"Diverticulose causa sangramento por erosão de arteríola adjacente ao colo do divertículo (mais comum em cólon direito). Angiodisplasia (idosos, IRC, doença valvar) é a 2ª causa. HDB raramente é maciça; 80% cessa espontaneamente.",
  mec:[],
  diretriz:"ACG Clinical Guideline: Management of Patients With Acute Lower GI Bleeding (Strate LL, Gralnek IM, Am J Gastroenterol 2016;111:459–474).",
  calcs:[],
},
{
  id:"encefa", sis:"gi", grav:"alta",
  nome:"Encefalopatia Hepática",
  sin:["EH","encefalopatia hepática","coma hepático","amônia"],
  def:"Alteração de consciência em cirrótico/hepatopata. West Haven I–IV. Fator precipitante quase sempre presente.",
  exames:["Hemograma","Função renal + eletrólitos","Glicemia","Amônia sérica (útil se ↓)","HMC e EAS (PBE? ITU?)","Função hepática + INR","TC crânio se déficit/trauma"],
  rx:[
    {etapa:"escala", d:"Lactulose",do:"30 mL VO 1–2h até evacuação, depois 20–30 mL 8/8h",via:"VO/SNG",o:"Meta: 2–3 evacuações pastosas/d. Em coma: enema 300 mL em 700 mL SF."},
    {etapa:"escala", d:"Rifaximina",do:"550 mg VO 12/12h",via:"VO",o:"Adicionar à lactulose em refratário ou recorrente. ATB não absorvível."},
    {etapa:"atb", d:"Metronidazol",do:"250 mg VO 8/8h",via:"VO",o:"Alternativa quando rifaximina indisponível."},
    {etapa:"inicial", d:"Tratar precipitante",do:"—",via:"—",o:"PBE → ceftriaxona; constipação → lactulose; ITU → ATB; sangramento → estabilizar; eletrólitos → corrigir."},
  ],
  alertas:[
    {t:"warn",x:"Identificar e tratar precipitante é tão importante quanto a lactulose: PBE, sangramento GI, drogas (BZD, diurético), constipação, infecção, distúrbios eletrolíticos."},
    {t:"info",x:"Restringir proteínas NÃO é mais recomendado (1,2–1,5 g/kg/d, preferindo vegetal/laticínio)."},
  ],
  fisio:"A insuficiência hepática reduz a depuração de toxinas nitrogenadas (especialmente <strong>amônia</strong>) produzidas pela flora intestinal a partir de proteínas. A amônia atravessa BHE → astrócitos a convertem em glutamina → edema astrocitário → alteração de neurotransmissão (GABA ↑, glutamato modulado). Shunts portossistêmicos agravam.",
  mec:[
    {d:"Lactulose",x:"Dissacarídeo não absorvível — fermentado por bactérias colônicas em ácidos orgânicos → <strong>↓pH do cólon, convertendo NH₃ (absorvível) em NH₄⁺ (não absorvível)</strong>. Também laxativo osmótico, eliminando produtos nitrogenados nas fezes."},
    {d:"Rifaximina",x:"ATB não absorvível — <strong>↓flora colônica produtora de amônia</strong> sem efeito sistêmico relevante."},
  ],
  diretriz:"AASLD/EASL — Hepatic Encephalopathy (Vilstrup H et al., Hepatology 2014;60:715–735).",
  calcs:[],
},
{
  id:"pancreatite", sis:"gi", grav:"alta",
  nome:"Pancreatite Aguda",
  sin:["pancreatite","pancreatite aguda","PA"],
  def:"Dor abdominal alta característica (em faixa) + amilase/lipase ≥3× ULN OU imagem compatível. Critérios de Atlanta. Etiologia 80% biliar/alcoólica.",
  exames:["Amilase + lipase","Função renal + eletrólitos (Ca, Mg)","ALT/AST/FA/GGT/BT","Triglicerídeos, glicemia","LDH, hemograma","RX/USG abdome (biliar)","TC com contraste após 72–96h se complicação"],
  rx:[
    {etapa:"inicial", d:"Ringer Lactato",do:"10 mL/kg bolus + 1,5 mL/kg/h",via:"IV",o:"REGIME MODERADO guiado por meta (PAM>65, diurese>0,5 mL/kg/h, lactato em queda). WATERFALL: agressivo causa mais sobrecarga."},
    {etapa:"adj", d:"Analgesia",do:"Dipirona 1g IV + opioide se intenso (fentanil/morfina)",via:"IV",o:"Não há contraindicação a opioide (mito do espasmo de Oddi)."},
    {etapa:"inicial", d:"Dieta zero inicial",do:"Reintrodução em 24–72h se tolerância",via:"VO",o:"Dieta precoce VO/enteral reduz complicações. NPT só se ↑ ileostomia/jejum prolongado."},
    {etapa:"adj", d:"Antieméticos",do:"Ondansetrona 4–8 mg IV 8/8h",via:"IV",o:"Sintomático."},
    {etapa:"escala", d:"CPRE precoce",do:"<24–48h",via:"—",o:"APENAS se colangite associada OU obstrução biliar persistente. NÃO de rotina."},
    {etapa:"escala", d:"ATB",do:"Imipenem 500 mg 6/6h OU meropenem 1g 8/8h",via:"IV",o:"APENAS em necrose infectada documentada. NÃO profilático."},
  ],
  alertas:[
    {t:"warn",x:"NÃO hidratação agressiva (WATERFALL 2022 — sobrecarga 20,5% vs 6,3%, sem benefício)."},
    {t:"info",x:"Pancreatite biliar leve: colecistectomia na mesma internação. Grave: aguardar resolução."},
  ],
  fisio:"Ativação intra-acinar das enzimas pancreáticas (tripsinogênio → tripsina) → autodigestão glandular + cascata inflamatória sistêmica → SIRS, vazamento capilar, SDRA, IRA. Causas: <strong>cálculos biliares</strong> (40%), <strong>álcool</strong> (35%), hipertrigliceridemia (>1000), CPRE, drogas, escorpião, idiopática.",
  mec:[
    {d:"Ringer Lactato",x:"Cristaloide balanceado — pH ~6,5, sem cloro excessivo. Em PA pode atenuar inflamação intrapancreática vs. SF (estudos sugerem)."},
  ],
  diretriz:"ACG Acute Pancreatitis Guideline (Tenner S et al., Am J Gastroenterol 2024;119:419–437). WATERFALL trial (de-Madaria E et al., NEJM 2022;387:989–1000).",
  calcs:["ranson","bisap"],
},
{
  id:"colelit", sis:"gi", grav:"media",
  nome:"Colelitíase / Cólica Biliar",
  sin:["colelitíase","cálculo biliar","cólica biliar"],
  def:"Dor em hipocôndrio direito/epigástrio pós-prandial, <6h, sem febre nem icterícia (cólica simples). Diferenciar de colecistite (>6h + febre + Murphy +).",
  exames:["USG abdome (cálculo, espessamento de parede)","Hemograma, função hepática, FA, BT","Lipase para descartar pancreatite"],
  rx:[
    {etapa:"adj", d:"Dipirona",do:"1 g IV em 10 min",via:"IV",o:"1ª linha analgésica."},
    {etapa:"escala", d:"Cetoprofeno",do:"100 mg IV em 100 mL SF",via:"IV",o:"AINE — pode reduzir progressão para colecistite."},
    {etapa:"escala", d:"Escopolamina (Buscopan)",do:"20 mg IV/IM",via:"IV/IM",o:"Anticolinérgico — ↓espasmo. CI: glaucoma, taquicardia."},
    {etapa:"escala", d:"Colecistectomia eletiva",do:"Em sintomáticos",via:"Cirúrgico",o:"Mesma internação se episódio agudo grave; ambulatorial em sintomáticos leves."},
  ],
  alertas:[
    {t:"warn",x:"Cólica + febre + Murphy + = colecistite. Cólica + febre + icterícia + dor (Charcot) = colangite. INVESTIGAR."},
  ],
  fisio:"Cálculos formam-se por desequilíbrio de colesterol/sais biliares/lecitina (>70% colesterol; 20% pigmentados). Cólica biliar = obstrução transitória do ducto cístico → distensão da vesícula → dor visceral. Sem obstrução persistente, não há inflamação significativa.",
  mec:[
    {d:"Escopolamina",x:"Antagonista <strong>muscarínico</strong> — ↓motilidade e tônus da musculatura lisa do trato biliar."},
  ],
  diretriz:"AASLD; Tokyo Guidelines 2018.",
  calcs:[],
},
{
  id:"colecistite", sis:"gi", grav:"alta",
  nome:"Colecistite Aguda (Tokyo 2018)",
  sin:["colecistite","colecistite aguda","TG18"],
  def:"Inflamação da vesícula biliar. Critérios TG18: A (Murphy/dor HCD) + B (febre, ↑PCR/leuco) + C (imagem: parede espessada, líquido pericístico). Suspeito = 1A + 1B; definitivo = + C.",
  exames:["USG abdome (parede>4mm, líquido pericístico, Murphy ecográfico)","Hemograma, função hepática, FA, BT, lipase","HMC se febre alta","TC se complicação"],
  rx:[
    {etapa:"inicial", d:"Dieta zero + hidratação",do:"SF 1–2 mL/kg/h",via:"IV",o:"—"},
    {etapa:"adj", d:"Analgesia",do:"Dipirona + opioide",via:"IV",o:"Como em cólica biliar."},
    {etapa:"atb", d:"Ceftriaxona + Metronidazol",do:"1 g IV/d + 500 mg IV 8/8h",via:"IV",o:"Grau I (leve). Cobertura E. coli, Klebsiella, anaeróbios."},
    {etapa:"atb", d:"Piperacilina-tazobactam",do:"4,5 g IV 6/6h",via:"IV",o:"Grau II (moderado) ou paciente com fatores de risco MR."},
    {etapa:"atb", d:"Meropenem",do:"1 g IV 8/8h + vanco/linezolida",via:"IV",o:"Grau III (grave/disfunção orgânica)."},
    {etapa:"inicial", d:"Colecistectomia laparoscópica precoce",do:"<72h",via:"Cirúrgico",o:"Padrão para todos. Grau III: estabilizar primeiro; colecistostomia se inoperável."},
  ],
  alertas:[
    {t:"crit",x:"Sepse de origem biliar: hour-1 bundle + cirurgia/drenagem URGENTE."},
  ],
  fisio:"Obstrução persistente do ducto cístico → distensão → ↑pressão intraluminal → isquemia da parede → invasão bacteriana secundária. Não tratada evolui para empiema, gangrena, perfuração.",
  mec:[
    {d:"Ceftriaxona + Metronidazol",x:"Cobertura Gram-negativos entéricos (cefalosporina 3G) + anaeróbios (5-nitroimidazol — reduzido em ambiente anaeróbio gerando radicais que danificam DNA bacteriano)."},
  ],
  diretriz:"Tokyo Guidelines 2018 (Yokoe M et al., J Hepatobiliary Pancreat Sci 2018;25:41–54, DOI:10.1002/jhbp.515). Antibiótico: Gomi H et al. DOI:10.1002/jhbp.518.",
  calcs:[],
},
{
  id:"colangite", sis:"gi", grav:"alta",
  nome:"Colangite Aguda (Tokyo 2018)",
  sin:["colangite","Charcot","Reynolds","TG18"],
  def:"Infecção biliar com obstrução. Tríade de Charcot: febre + icterícia + dor HCD. Pêntade de Reynolds: + hipotensão + alteração mental. ALTA MORTALIDADE se atraso.",
  exames:["Hemograma + PCR","Função hepática (↑FA, ↑BT direta, ↑GGT, ↑ALT)","HMC (positivas em 50%)","USG abdome → dilatação biliar","ColangioRM ou TC + CPRE diagnóstica/terapêutica"],
  rx:[
    {etapa:"inicial", d:"Estabilização hemodinâmica",do:"Cristaloide + vasopressor se choque",via:"IV",o:"Hour-1 bundle de sepse."},
    {etapa:"atb", d:"Piperacilina-tazobactam",do:"4,5 g IV 6/6h",via:"IV",o:"Inicial empírico amplo (TG18 grau II/III)."},
    {etapa:"atb", d:"Ceftriaxona + Metronidazol",do:"2 g + 500 mg 8/8h",via:"IV",o:"Alternativa em grau I."},
    {etapa:"atb", d:"Meropenem ± Vancomicina",do:"1 g 8/8h + 15 mg/kg 12/12h",via:"IV",o:"Grau III ou fatores MR."},
    {etapa:"escala", d:"Drenagem biliar URGENTE",do:"CPRE em até 24–48h (grau I/II) ou imediata (grau III)",via:"—",o:"Padrão-ouro. PTC se CPRE falha/anatomia."},
  ],
  alertas:[
    {t:"crit",x:"Grau III (disfunção orgânica): drenagem em <12h. Mortalidade sem drenagem 50–100%."},
    {t:"warn",x:"ATB SEM drenagem fracassa — fonte controle é mandatório."},
  ],
  fisio:"Obstrução biliar (coledocolitíase, estenose, tumor) → estase → translocação bacteriana ascendente do duodeno → bacteriobilia → bacteremia. Tóxinas e produtos inflamatórios entram na corrente sanguínea via shunts colangiovenosos → sepse fulminante.",
  mec:[],
  diretriz:"Tokyo Guidelines 2018 (Kiriyama S et al., J Hepatobiliary Pancreat Sci 2018;25:17–30, DOI:10.1002/jhbp.512).",
  calcs:[],
},
{
  id:"drge", sis:"gi", grav:"baixa",
  nome:"DRGE / Esofagite",
  sin:["DRGE","refluxo","esofagite","pirose"],
  def:"Pirose + regurgitação ácida ± disfagia. Diagnóstico clínico + teste terapêutico com IBP. EDA se sinais de alarme.",
  exames:["EDA se: disfagia, idade >50 com sintomas novos, hemorragia, anemia, perda de peso, vômitos persistentes, hist. familiar de CA"],
  rx:[
    {etapa:"escala", d:"Omeprazol",do:"20–40 mg VO/d em jejum × 4–8 sem",via:"VO",o:"1ª linha. 30 min antes do café."},
    {etapa:"escala", d:"Pantoprazol",do:"40 mg VO/d",via:"VO",o:"Alternativa."},
    {etapa:"adj", d:"Bromoprida/Domperidona",do:"10 mg VO 8/8h",via:"VO",o:"Procinético adjuvante. Limitar uso (efeitos cardiovasc/extrapiramidais)."},
    {etapa:"escala", d:"Mudanças de hábito",do:"Perder peso, elevar cabeceira, evitar deitar pós-prandial, ↓café/álcool/gorduras",via:"—",o:"Componente essencial."},
  ],
  alertas:[
    {t:"warn",x:"Sinais de alarme: investigar com EDA. Considerar Barrett (metaplasia)."},
  ],
  fisio:"Disfunção do esfíncter esofágico inferior + relaxamentos transitórios + hérnia de hiato → refluxo ácido → erosão da mucosa esofágica.",
  mec:[
    {d:"Omeprazol/Pantoprazol",x:"<strong>Inibidores irreversíveis da H⁺/K⁺-ATPase</strong> (bomba de prótons) nas células parietais gástricas → ↑pH gástrico."},
  ],
  diretriz:"ACG Guidelines for the Diagnosis and Management of Gastroesophageal Reflux Disease (Katz PO et al., Am J Gastroenterol 2022;117:27–56).",
  calcs:[],
},
{
  id:"ulcera", sis:"gi", grav:"media",
  nome:"Doença Ulcerosa Péptica / H. pylori",
  sin:["úlcera","Hp","H. pylori","gastrite"],
  def:"Dor epigástrica + náuseas. Causas: H. pylori (60–80%), AINE, estresse, Zollinger-Ellison. Diagnóstico: EDA + biópsia / urease / antígeno fecal / teste respiratório.",
  exames:["EDA + biópsia (úlcera + Hp)","Teste de urease ou antígeno fecal Hp","Hemograma se sangramento","Lipase para excluir pancreatite"],
  rx:[
    {etapa:"escala", d:"IBP",do:"Omeprazol 20–40 mg 12/12h × 4–8 sem",via:"VO",o:"Cicatrização da úlcera."},
    {etapa:"escala", d:"Esquema H. pylori (1ª linha)",do:"Claritro 500 mg + Amox 1g + IBP dose dobrada — todos 12/12h × 14 dias",via:"VO",o:"Adesão crítica. Em alta resistência (>15%): quadrupla com bismuto."},
    {etapa:"escala", d:"Esquema quádruplo com bismuto",do:"IBP 12/12h + bismuto + tetraciclina 500 mg 6/6h + metronidazol 500 mg 8/8h × 14 dias",via:"VO",o:"Alta resistência ou falha primeira linha."},
    {etapa:"adj", d:"Suspender AINE",do:"—",via:"—",o:"Se possível. Trocar por paracetamol/dipirona."},
  ],
  alertas:[
    {t:"warn",x:"Complicações: hemorragia (Forrest), perfuração (pneumoperitônio), estenose, malignização."},
  ],
  fisio:"Desequilíbrio entre fatores agressivos (ácido, pepsina, H. pylori, AINE) e defensivos (muco, bicarbonato, prostaglandinas). H. pylori produz urease (neutraliza ácido local) + citotoxinas (CagA, VacA) → gastrite crônica → atrofia → úlcera/CA gástrico.",
  mec:[
    {d:"Claritromicina",x:"Macrolídeo — inibe 50S ribossomal."},
    {d:"Amoxicilina",x:"Aminopenicilina — inibe PBPs."},
    {d:"Bismuto",x:"Antimicrobiano direto contra H. pylori + barreira mucosa."},
  ],
  diretriz:"IV Consenso Brasileiro sobre Infecção pelo Helicobacter pylori (Coelho LGV et al., Arq Gastroenterol 2018;55:97–121).",
  calcs:[],
},
{
  id:"ascite", sis:"gi", grav:"media",
  nome:"Ascite + PBE",
  sin:["ascite","PBE","peritonite","cirrose"],
  def:"Acúmulo de líquido peritoneal. PBE = peritonite bacteriana espontânea em cirrótico (PMN ≥250 no líquido ascítico).",
  exames:["Paracentese diagnóstica em TODOS os admitidos: bioq, celularidade, GASA, Gram, cultura","Hemograma, função renal e hepática","Eletrólitos (hiponatremia comum)"],
  rx:[
    {etapa:"escala", d:"Espironolactona",do:"100–400 mg VO/d",via:"VO",o:"Combinar com furosemida em proporção 100:40 mg. Paracentese terapêutica se ascite tensa."},
    {etapa:"escala", d:"Furosemida",do:"40–160 mg VO/d",via:"VO",o:"Manter relação 100:40 (espiro:furo) para evitar hiponatremia/hipocalemia."},
    {etapa:"escala", d:"Albumina 20%",do:"6–8 g por L removido se paracentese >5 L",via:"IV",o:"Previne disfunção circulatória pós-paracentese."},
    {etapa:"atb", d:"Ceftriaxona",do:"2 g IV/d × 5–7 dias",via:"IV",o:"PBE — empírico. Cobre E. coli, Klebsiella, pneumococo."},
    {etapa:"escala", d:"Albumina (PBE)",do:"1,5 g/kg D1 + 1 g/kg D3",via:"IV",o:"Reduz SHR e mortalidade na PBE."},
    {etapa:"adj", d:"Profilaxia PBE",do:"Norfloxacino 400 mg/d ou SMX-TMP 1 cp/d",via:"VO",o:"Indicações: HDA varicosa, PBE prévia, prot. asc <1,5 g/dL + disfunção renal/Child C."},
  ],
  alertas:[
    {t:"crit",x:"PBE não tratada: mortalidade 60–90%. Iniciar ATB EMPIRICAMENTE assim que paracentese coletada."},
  ],
  fisio:"Cirrose → ↑pressão portal → vasodilatação esplâncnica/sistêmica → ↓volume arterial efetivo → ativação RAA/SNS/ADH → retenção de sódio e água. PBE: translocação bacteriana intestinal → bacteriemia → infecção do líquido ascítico (pobre em opsoninas).",
  mec:[
    {d:"Espironolactona",x:"Antagonista do <strong>receptor da aldosterona</strong> no túbulo coletor → ↑excreção de Na⁺ e retenção de K⁺."},
    {d:"Furosemida",x:"Inibe Na⁺/K⁺/2Cl⁻ na alça de Henle."},
    {d:"Albumina",x:"Mantém pressão oncótica e volume circulante efetivo; ↓incidência de síndrome hepatorrenal pós-paracentese."},
  ],
  diretriz:"AASLD Guideline on Ascites (Biggins SW et al., Hepatology 2021;74:1014–1048). EASL 2018.",
  calcs:["meld","child-pugh"],
},
{
  id:"diverticulite", sis:"gi", grav:"media",
  nome:"Diverticulite Aguda",
  sin:["diverticulite","Hinchey"],
  def:"Dor em FIE + febre + leucocitose em paciente com diverticulose. TC define gravidade (Hinchey I–IV).",
  exames:["TC abdome com contraste (PADRÃO-OURO)","Hemograma, PCR","Função renal"],
  rx:[
    {etapa:"atb", d:"Ciprofloxacino + Metronidazol",do:"500 mg 12/12h + 500 mg 8/8h × 7–10 dias",via:"VO",o:"Não complicada (Hinchey 0–I, sem abscesso). Ambulatorial."},
    {etapa:"atb", d:"Amoxicilina-clavulanato",do:"875/125 mg 12/12h × 7–10 dias",via:"VO",o:"Alternativa em não complicada."},
    {etapa:"atb", d:"Ceftriaxona + Metronidazol",do:"2 g IV/d + 500 mg IV 8/8h",via:"IV",o:"Internação. Hinchey I (abscesso pericólico pequeno) ou intolerância oral."},
    {etapa:"atb", d:"Piperacilina-tazobactam",do:"4,5 g IV 6/6h",via:"IV",o:"Hinchey II–III ou sepse."},
    {etapa:"escala", d:"Drenagem percutânea",do:"—",via:"—",o:"Abscesso >4 cm."},
    {etapa:"escala", d:"Cirurgia (Hartmann)",do:"—",via:"—",o:"Hinchey III (peritonite purulenta) ou IV (fecal)."},
  ],
  alertas:[
    {t:"info",x:"Em casos selecionados de diverticulite não complicada, ATB pode ser dispensado (estudos AVOD, DIABOLO). Decisão individualizada."},
  ],
  fisio:"Obstrução do colo do divertículo por fecálito → ↑pressão → microperfuração → inflamação local. Em cólon sigmoide em 95%. Pode evoluir para abscesso, peritonite, fístula.",
  mec:[],
  diretriz:"ASCRS Clinical Practice Guidelines for Diverticulitis (Hall J et al., Dis Colon Rectum 2020;63:728–747).",
  calcs:[],
},
{
  id:"apendicite", sis:"gi", grav:"alta",
  nome:"Apendicite Aguda",
  sin:["apendicite","apêndice"],
  def:"Dor periumbilical migrando para FID + náuseas + febre baixa + leucocitose. Escores: Alvarado, AIR, AAS.",
  exames:["USG abdome (1ª escolha em jovens, gestantes, crianças)","TC abdome (padrão-ouro adultos)","Hemograma, PCR","β-HCG","EAS"],
  rx:[
    {etapa:"escala", d:"Apendicectomia laparoscópica",do:"—",via:"Cirúrgico",o:"PADRÃO. Preferível em <24h."},
    {etapa:"atb", d:"Ceftriaxona + Metronidazol",do:"2 g + 500 mg IV 8/8h pré-op + 24h pós",via:"IV",o:"Não complicada. Em perfurada/abscesso: estender 5–7 dias."},
    {etapa:"escala", d:"ATB sem cirurgia (NOTA)",do:"Amox-clav 875/125 mg 12/12h × 7–10 dias",via:"VO",o:"Apendicite não complicada selecionada. Recidiva ~25–30% em 1 ano."},
  ],
  alertas:[
    {t:"warn",x:"Sinais de perfuração: dor difusa, peritonismo, febre >39, leuco >18k. TC + cirurgia + ATB amplo."},
  ],
  fisio:"Obstrução luminal (fecálito 60%, hiperplasia linfoide 20% em jovens, tumor 1% em idosos) → distensão → estase → infecção → isquemia → perfuração em 24–72h.",
  mec:[],
  diretriz:"WSES Jerusalem Guidelines 2020 (Di Saverio S et al., World J Emerg Surg 2020;15:27).",
  calcs:["alvarado"],
},
{
  id:"abd-agudo", sis:"gi", grav:"alta",
  nome:"Abdome Agudo (5 tipos)",
  sin:["abdome agudo","abdômen agudo","peritonite"],
  def:"Dor abdominal aguda <7d com necessidade de intervenção. 5 tipos: inflamatório / obstrutivo / perfurativo / vascular / hemorrágico.",
  exames:["RX simples em pé/decúbito + cúpulas","TC com contraste (padrão-ouro)","Hemograma, lactato, função renal, eletrólitos","β-HCG","Tipo sanguíneo + reserva"],
  rx:[
    {etapa:"escala", d:"INFLAMATÓRIO (apendicite, colecistite, diverticulite)",do:"ATB + analgesia + cirurgia conforme caso",via:"—",o:"Ver pages específicas."},
    {etapa:"escala", d:"OBSTRUTIVO",do:"SNG + dieta zero + SF 30 mL/kg + correção eletrolítica",via:"—",o:"Bridada/aderência: tentar conservador 48–72h. Estrangulamento: cirurgia."},
    {etapa:"escala", d:"PERFURATIVO",do:"Cirurgia URGENTE + ATB amplo (piperacilina-tazobactam ou ceftriaxona+metronidazol) + reanimação",via:"—",o:"Pneumoperitônio no RX/TC."},
    {etapa:"escala", d:"VASCULAR (isq. mesentérica)",do:"Heparinização imediata + cirurgia/intervenção endovascular + ATB",via:"—",o:"DOR DESPROPORCIONAL ao exame. Mortalidade 50–80%. Angio-TC."},
    {etapa:"escala", d:"HEMORRÁGICO (ruptura aneurisma, gestação ectópica, baço)",do:"Reanimação balanceada 1:1:1 + ácido tranexâmico 1g + cirurgia/embolização",via:"—",o:"Choque + Hb em queda + massa pulsátil/HCD/anexo doloroso."},
  ],
  alertas:[
    {t:"crit",x:"SEMPRE β-HCG em mulher fértil — gestação ectópica é emergência cirúrgica."},
    {t:"crit",x:"NÃO suspender opioides em obstrução (mito) — alívio da dor não mascara peritonismo, e estudos mostram melhor decisão clínica com analgesia adequada."},
    {t:"warn",x:"Idoso com dor abdominal súbita + FA + dor desproporcional → considerar isquemia mesentérica precoce."},
  ],
  fisio:"Cada tipo tem fisiopatologia distinta — ver páginas específicas (apendicite, colecistite, isquemia mesentérica, perfuração ulcerosa, etc.). Pontos comuns: dor visceral mal localizada (inicial) → dor somática localizada (peritônio parietal envolvido) → peritonite.",
  mec:[],
  diretriz:"WSES Guidelines.",
  fluxo:"abd-agudo",
  calcs:[],
},

/* ============== ENDÓCRINO ============== */
{
  id:"cad-ehh", sis:"endo", grav:"alta",
  nome:"CAD / EHH",
  sin:["CAD","EHH","cetoacidose","cetoacidose diabética","estado hiperosmolar"],
  def:"CAD: glicemia >200 + acidose (pH<7,3 ou HCO3<18) + cetonas+. EHH: glicemia >600 + osmolaridade >320 + leve ou nenhuma cetose + alteração de consciência.",
  exames:["Glicemia, gasometria arterial (pH, HCO3, AG)","Eletrólitos (Na, K, Cl) + função renal","Cetonas séricas/urinárias (β-OH-butirato)","Osmolaridade calculada","Hemograma, PCR (procurar precipitante: infecção, IAM, AVC, suspensão de insulina)","ECG"],
  rx:[
    {etapa:"inicial", d:"Avaliação inicial + monitorização",do:"PA, FC, FR, SpO2, glasgow, glicemia capilar",via:"—",o:"Avaliar gravidade: leve (pH 7,25-7,3), moderada (7-7,25), grave (<7). Buscar PRECIPITANTE: infecção (50%), IAM, AVC, suspensão insulina."},
    {etapa:"inicial", d:"Exames laboratoriais URGENTES",do:"Gasometria, eletrólitos, glicemia, cetonas, função renal",via:"—",o:"Calcular: anion gap, Na corrigido, osmolaridade. Repetir 2/2h até melhora."},
    {etapa:"inicial", d:"2 acessos + sondagem vesical se choque",do:"Acessos calibrosos",via:"—",o:"Monitorar débito urinário (alvo ≥0,5 mL/kg/h)."},
    {etapa:"escala", d:"① VOLUME — SF 0,9%",do:"500-1000 mL na 1ª hora, depois 250-500 mL/h conforme Na corrigido",via:"IV",o:"Hidratação é mais URGENTE que insulina nas primeiras 1-2h. Na corrigido NORMAL/ALTO: passar para SF 0,45%. Em CHOQUE: bolus 15-20 mL/kg."},
    {etapa:"escala", d:"② POTÁSSIO — CHECAR ANTES da insulina",do:"K>5,2: aguardar. K 3,3-5,2: 20-30 mEq/L. K<3,3: 20-30 mEq/h + SUSPENDER insulina",via:"IV",o:"OBRIGATÓRIO. Deficit corporal mesmo com K sérico normal (sai com diurese osmótica). Risco de PCR por hipocalemia se iniciar insulina sem cuidado."},
    {etapa:"escala", d:"③ INSULINA regular BIC",do:"0,1 U/kg/h IV em BIC (SEM bolus rotineiro - ADA 2024)",via:"IV",o:"INICIAR após K conhecido (≥3,3). Diluir 50 UI em 250 mL SF = 0,2 UI/mL. Alvo: ↓glicemia 50-75 mg/dL/h."},
    {etapa:"escala", d:"④ Troca para SG quando glicemia <250-300",do:"SG 5-10% + manter insulina BIC",via:"IV",o:"NÃO suspender insulina (resolve cetose, não glicemia). Manter até resolver acidose."},
    {etapa:"escala", d:"⑤ NaHCO3 8,4% (apenas pH <6,9)",do:"50-100 mEq IV diluído em 400 mL SF + KCl",via:"IV",o:"RESTRITO a acidose extrema. NÃO rotineiro. Risco: hipocalemia, alcalose paradoxal."},
    {etapa:"adj", d:"Tratar PRECIPITANTE",do:"ATB se infecção, ECG/troponina se IAM, TC se AVC",via:"—",o:"50% dos casos têm infecção como gatilho. NÃO esquecer essa investigação."},
    {etapa:"adj", d:"Reposição de Mg e PO4 se baixos",do:"Mg <1,5: 1-2g IV. PO4 <1: cuidadoso",via:"IV",o:"Deficiência comum. Repor Mg facilita correção K."},
    {etapa:"alta", d:"TRANSIÇÃO para insulina SC",do:"Iniciar SC 1-2h ANTES de suspender BIC",via:"SC",o:"Critérios resolução: pH ≥7,3 OU HCO3 >18 + β-OH-butirato <0,6 + glicemia <200 + paciente comendo. Insulina basal + bolus."},
    {etapa:"alta", d:"Educação + prevenção",do:"Sick day rules, automonitorização, identificar precipitantes",via:"—",o:"Endocrino. Plano de manejo em caso de infecções/jejum. Adesão à insulina."},
  ],
  alertas:[
    {t:"crit",x:"Edema cerebral em pediatria: hidratação cautelosa, evitar quedas rápidas de Na/glicemia. Mortalidade 20-25% do edema."},
    {t:"warn",x:"NUNCA iniciar insulina sem checar K — risco de hipocalemia fatal (perda de K com diurese osmótica)."},
    {t:"info",x:"Resolução: pH ≥7,3 ou HCO3 >18 + β-OH-butirato <0,6 + glicemia <200 (ADA/EASD 2024)."},
  ],
  fisio:"CAD: deficiência absoluta de insulina + ↑hormônios contrainsulínicos (glucagon, cortisol, catecolaminas, GH) → lipólise → ácidos graxos livres → ↑oxidação → corpos cetônicos (β-OH-butirato, acetoacetato) → acidose metabólica AG aumentado. Hiperglicemia → diurese osmótica → desidratação intensa + perda de Na/K/Mg/PO4. EHH: insulina suficiente para suprimir lipólise mas insuficiente para evitar hiperglicemia → desidratação + hiperosmolaridade SEM cetoacidose significativa. Pacientes diabéticos tipo 2 idosos.",
  mec:[
    {d:"Insulina regular",x:"Hormônio peptídico — liga-se ao receptor de insulina (tirosina-quinase) → translocação de GLUT-4 → captação de glicose pelo músculo/adipócito; ↓lipólise, ↓cetogênese, ↑síntese proteica."},
  ],
  diretriz:"Consenso ADA/EASD/JBDS/AACE/DTS 2024 — Hyperglycemic Crises in Adults With Diabetes (Umpierrez GE et al., Diabetes Care 2024;47:1257–1275, DOI:10.2337/dci24-0032). Diretriz SBD 2024.",
  fluxo:"cad",
  calcs:["aniongap","osm","corr-na"],
},
{
  id:"glicemia-hosp", sis:"endo", grav:"baixa",
  nome:"Controle Glicêmico Hospitalar",
  sin:["hiperglicemia","controle glicêmico","diabetes hospitalar"],
  def:"Alvo glicêmico 140–180 mg/dL em paciente hospitalizado. Hiperglicemia hospitalar (>140 sem DM prévio) tem pior prognóstico.",
  exames:["HGT 6/6h ou pré-prandial","HbA1c se desconhecida"],
  rx:[
    {etapa:"inicial", d:"Esquema basal-bolus",do:"Basal (NPH/glargina) 0,2–0,3 U/kg/d + bolus prandial (regular/lispro) 0,1 U/kg",via:"SC",o:"1ª escolha em maioria. Ajustar conforme HGT."},
    {etapa:"escala", d:"Sliding scale (correção)",do:"Insulina regular conforme glicemia",via:"SC",o:"NÃO usar sozinho. Apenas como complemento."},
    {etapa:"inicial", d:"BIC de insulina",do:"0,5–1 U/h titulada para glicemia 140–180",via:"IV",o:"UTI, choque, AVE, pós-CIR, dieta zero, hiperglicemia >250 persistente."},
  ],
  alertas:[
    {t:"warn",x:"Em jejum ou dieta zero: SUSPENDER bolus prandial; manter basal reduzida (50–80%)."},
    {t:"info",x:"Sliding scale isolado piora controle e aumenta hipoglicemia. Evitar como única estratégia."},
  ],
  fisio:"Hiperglicemia inibe função neutrofílica, ↑estresse oxidativo, ↑inflamação, ↑coagulação, prejudica cicatrização. Hipoglicemia também é deletéria (arritmias, mortalidade ↑).",
  mec:[],
  diretriz:"ADA Standards of Care 2025 (Diabetes Care 2025).",
  calcs:[],
},
{
  id:"hipoglicemia", sis:"endo", grav:"alta",
  nome:"Hipoglicemia",
  sin:["hipoglicemia","hipo"],
  def:"Glicemia <70 mg/dL. Tríade de Whipple: glicemia baixa + sintomas + melhora com glicose. Em DM: <54 grave; <70 alerta.",
  exames:["HGT","Glicemia plasmática","Insulina/peptídeo C em recorrente (tumor, fictícia)"],
  rx:[
    {etapa:"inicial", d:"Sacarose VO",do:"15 g (3 sachês açúcar em 200 mL água)",via:"VO",o:"Consciente + capaz de deglutir. Reavaliar em 15 min."},
    {etapa:"escala", d:"Glicose 50%",do:"50–100 mL IV bolus",via:"IV",o:"Inconsciente. Manter SG10% se etiologia persistente (sulfonilureia)."},
    {etapa:"inicial", d:"Glucagon",do:"1 mg IM/SC",via:"IM/SC",o:"Sem acesso venoso. Não funciona em hepatopata/desnutrido (sem reserva)."},
    {etapa:"adj", d:"Tiamina",do:"100 mg IV ANTES de glicose",via:"IV",o:"OBRIGATÓRIO em etilistas, desnutridos, gestantes hiperêmese — prevenir Wernicke."},
  ],
  alertas:[
    {t:"crit",x:"Hipoglicemia por sulfonilureia (glibenclamida, glimepirida) ou insulina de longa ação: observar 24–48h após resolução — recorrência."},
    {t:"warn",x:"Sempre tiamina ANTES da glicose em alcoólatra/desnutrido."},
  ],
  fisio:"O cérebro consome ~20% da glicose corporal e não armazena glicogênio. Glicemia <55 → liberação de catecolaminas (sintomas adrenérgicos: tremor, sudorese, palpitação). <50 → neuroglicopenia (confusão, convulsão, coma).",
  mec:[
    {d:"Glucagon",x:"Hormônio pancreático — ativa adenilato ciclase nos hepatócitos → ↑AMPc → glicogenólise + gliconeogênese hepática."},
    {d:"Tiamina (B1)",x:"Cofator de enzimas do ciclo de Krebs e via das pentoses. Sua deficiência + sobrecarga de glicose → encefalopatia de Wernicke."},
  ],
  diretriz:"ADA Standards of Care 2025.",
  calcs:[],
},

/* ============== GU ============== */
{
  id:"cistite", sis:"gu", grav:"baixa",
  nome:"Cistite (ITU baixa)",
  sin:["ITU","cistite","infecção urinária"],
  def:"Disúria + polaciúria + urgência miccional + dor suprapúbica, sem febre. Mulher jovem, não-complicada: tratamento empírico.",
  exames:["EAS (leucocitúria, nitrito, hematúria)","Urocultura SOMENTE se: recorrente, gestante, falha terapêutica, complicada, homem, criança"],
  rx:[
    {etapa:"escala", d:"Nitrofurantoína",do:"100 mg VO 6/6h × 5 dias",via:"VO",o:"1ª linha em cistite não-complicada. CI: ClCr <30, gestante 3º trim."},
    {etapa:"atb", d:"Fosfomicina trometamol",do:"3 g VO dose única",via:"VO",o:"Alternativa. Tomar à noite + vesícula vazia."},
    {etapa:"atb", d:"SMX-TMP",do:"800/160 mg VO 12/12h × 3 dias",via:"VO",o:"Alternativa se resistência local <20%."},
    {etapa:"atb", d:"Cefalexina",do:"500 mg VO 6/6h × 7 dias",via:"VO",o:"Gestante."},
  ],
  alertas:[
    {t:"warn",x:"Bacteriúria assintomática: NÃO tratar EXCETO em gestantes e pré-procedimentos urológicos."},
  ],
  fisio:"Colonização periuretral → ascensão à bexiga → invasão de células uroepiteliais. Agente: E. coli (>80%), Klebsiella, Proteus, Staph. saprophyticus.",
  mec:[
    {d:"Nitrofurantoína",x:"Reduzida intracelularmente, gera intermediários reativos que <strong>danificam DNA/proteínas/ribossomos bacterianos</strong>. Concentra-se na urina."},
    {d:"Fosfomicina",x:"Inibe MurA — <strong>primeira etapa da síntese do peptidoglicano</strong>. Espectro amplo, concentra na urina."},
  ],
  diretriz:"IDSA — Treatment of Uncomplicated Cystitis and Pyelonephritis (Gupta K et al., CID 2011;52:e103–e120).",
  calcs:[],
},
{
  id:"pielonefrite", sis:"gu", grav:"media",
  nome:"Pielonefrite Aguda",
  sin:["pielonefrite","ITU alta"],
  def:"Febre + dor lombar + Giordano + sintomas baixos + leucocitúria. Mais grave que cistite, pode levar à sepse urinária.",
  exames:["EAS + urocultura SEMPRE","Hemograma, PCR, função renal","HMC se internação","USG/TC se complicação"],
  rx:[
    {etapa:"inicial", d:"Avaliação inicial",do:"SSVV + sinais sepse (qSOFA) + Giordano + exame abdominal",via:"—",o:"Diferenciar de cistite baixa. Avaliar obstrução suspeita (cólica, urolitíase prévia)."},
    {etapa:"inicial", d:"Acesso venoso + hidratação",do:"SF/RL 30 mL/kg em 3h se sepse; ou manutenção se estável",via:"IV",o:"Hipovolemia + febre. Ajustar conforme volemia."},
    {etapa:"inicial", d:"Coletar EAS + urocultura + HMC",do:"ANTES da 1ª dose ATB",via:"—",o:"Permite step-down ATB conforme antibiograma."},
    {etapa:"atb", d:"AMBULATORIAL — Ciprofloxacino",do:"500 mg VO 12/12h × 7 dias",via:"VO",o:"Sem comorbidade, sem sepse, sem gestação. Pode falhar se resistência local >10% — checar antibiograma local."},
    {etapa:"atb", d:"AMBULATORIAL alternativo — SMX-TMP",do:"800/160 mg VO 12/12h × 14 dias",via:"VO",o:"Apenas se sensibilidade conhecida (resistência >30% em muitas regiões)."},
    {etapa:"atb", d:"INTERNAÇÃO — Ceftriaxona",do:"1-2 g IV/d × 7-14 dias",via:"IV",o:"1ª LINHA hospitalar. Step-down para VO em 48-72h se melhora + antibiograma."},
    {etapa:"atb", d:"GRAVE/SEPSE — Piperacilina-tazobactam",do:"4,5 g IV 6/6h",via:"IV",o:"Sepse, fatores de risco MR (uso ATB recente, internação, sonda vesical, complicada)."},
    {etapa:"atb", d:"ESBL/MULTIRRESISTENTE — Meropenem",do:"1 g IV 8/8h",via:"IV",o:"ESBL prévia conhecida, sepse refratária, exposição ATB amplo recente."},
    {etapa:"escala", d:"VASOPRESSOR se sepse com choque",do:"Noradrenalina 0,05-2 mcg/kg/min",via:"IV",o:"Meta PAM ≥65. Ver patologia Sepse para escalonamento completo."},
    {etapa:"adj", d:"Antitérmico/Analgésico",do:"Dipirona 2g IV 6/6h ± paracetamol",via:"IV/VO",o:"Conforto + reduz demanda metabólica. Evitar AINEs (risco renal)."},
    {etapa:"adj", d:"Antiemético",do:"Ondansetrona 4-8 mg IV 8/8h",via:"IV",o:"Náusea/vômitos frequentes. Permite hidratação VO."},
    {etapa:"adj", d:"Avaliar OBSTRUÇÃO",do:"USG renal/vias urinárias urgente",via:"—",o:"Hidronefrose + sepse = drenagem URGENTE (cateter duplo J ou nefrostomia). Pielonefrite obstruída evolui mal."},
  ],
  alertas:[
    {t:"crit",x:"Sepse urinária: bundle hour-1. Procurar obstrução (hidronefrose) — drenagem urgente (cateter duplo J, nefrostomia)."},
  ],
  fisio:"Ascensão de bactérias da bexiga via ureter até parênquima renal. E. coli (80%). Em homens/idosos/diabéticos: hospitalar/MR mais frequente.",
  mec:[
    {d:"Ciprofloxacino",x:"Inibe DNA-girase/topoisomerase IV — boa concentração no parênquima renal."},
  ],
  diretriz:"IDSA Gupta 2011; EAU Guidelines on Urological Infections.",
  calcs:[],
},
{
  id:"candidiase", sis:"gu", grav:"baixa",
  nome:"Candidíase Vulvovaginal",
  sin:["candidíase","corrimento","Cândida"],
  def:"Prurido + corrimento branco em \"leite coalhado\" + ardência + dispareunia. Diagnóstico clínico.",
  exames:["Exame especular","pH vaginal <4,5","Microscopia (hifas) se dúvida"],
  rx:[
    {etapa:"escala", d:"Clotrimazol creme 1%",do:"Aplicador vaginal 1×/d × 7 dias",via:"Vaginal",o:"1ª linha. Alternativa: miconazol."},
    {etapa:"atb", d:"Fluconazol",do:"150 mg VO dose única",via:"VO",o:"Não-gestante. Repetir após 3 dias em casos moderados/graves."},
    {etapa:"escala", d:"Nistatina",do:"Creme vaginal 100.000 UI/g × 14 dias",via:"Vaginal",o:"Gestante (Cat B)."},
  ],
  alertas:[
    {t:"warn",x:"NÃO usar fluconazol em gestante (cat. D em altas doses)."},
  ],
  fisio:"Candida albicans (>85%) — comensal vaginal que prolifera com alteração de flora (ATB, gestação, DM, imunossupressão).",
  mec:[
    {d:"Clotrimazol / Miconazol",x:"Azólicos — inibem <strong>14α-desmetilase fúngica (CYP51)</strong> → ↓ergosterol da membrana fúngica."},
  ],
  diretriz:"FEBRASGO — Vulvovaginites 2024.",
  calcs:[],
},
{
  id:"vaginose", sis:"gu", grav:"baixa",
  nome:"Vaginose Bacteriana",
  sin:["vaginose","Gardnerella"],
  def:"Corrimento branco-acinzentado homogêneo + odor de peixe + pH >4,5 + clue cells + KOH+ (Amsel ≥3/4).",
  exames:["Exame especular + pH + KOH whiff test","Microscopia (clue cells)"],
  rx:[
    {etapa:"atb", d:"Metronidazol",do:"500 mg VO 12/12h × 7 dias",via:"VO",o:"1ª linha. Evitar álcool durante e 48h após."},
    {etapa:"atb", d:"Metronidazol gel 0,75%",do:"5 g vaginal 1×/d × 5 dias",via:"Vaginal",o:"Alternativa."},
    {etapa:"atb", d:"Clindamicina creme 2%",do:"5 g vaginal 1×/d × 7 dias",via:"Vaginal",o:"Alternativa."},
  ],
  alertas:[
    {t:"info",x:"Não é IST. Não tratar parceiro de rotina. Tratar SEMPRE em gestação (risco de prematuridade)."},
  ],
  fisio:"Disbiose vaginal — ↓lactobacilos protetores → ↑Gardnerella vaginalis, Atopobium, anaeróbios. pH alcaliniza.",
  mec:[
    {d:"Metronidazol",x:"5-Nitroimidazol — reduzido em condições anaeróbias → gera intermediários reativos que <strong>danificam DNA bacteriano</strong>."},
  ],
  diretriz:"PCDT-IST MS 2022.",
  calcs:[],
},
{
  id:"trico", sis:"gu", grav:"baixa",
  nome:"Tricomoníase",
  sin:["tricomoníase","Trichomonas"],
  def:"Corrimento amarelo-esverdeado, bolhoso, fétido + dispareunia + colo em \"morango\". IST — tratar parceiro.",
  exames:["Exame a fresco (protozoário móvel)","NAAT se disponível"],
  rx:[
    {etapa:"atb", d:"Metronidazol",do:"2 g VO dose única",via:"VO",o:"1ª linha. Ou 500 mg 12/12h × 7 dias. Tratar parceiro."},
    {etapa:"escala", d:"Tinidazol",do:"2 g VO dose única",via:"VO",o:"Alternativa, menor incidência de efeitos adversos."},
  ],
  alertas:[
    {t:"info",x:"IST — investigar outras (HIV, sífilis, gonorreia, clamídia). Tratar parceiro."},
  ],
  fisio:"Trichomonas vaginalis — protozoário flagelado. Transmissão sexual.",
  mec:[],
  diretriz:"PCDT-IST MS 2022.",
  calcs:[],
},
{
  id:"herpes-gen", sis:"gu", grav:"media",
  nome:"Herpes Genital",
  sin:["herpes genital","HSV-2"],
  def:"Vesículas dolorosas em mucosa/pele genital + linfadenopatia + sintomas sistêmicos (primária). Recidivas são geralmente mais leves.",
  exames:["Diagnóstico clínico","PCR/cultura se dúvida"],
  rx:[
    {etapa:"atb", d:"Aciclovir",do:"400 mg VO 8/8h × 7–10 dias (primária) / 5 dias (recidiva)",via:"VO",o:"Iniciar nas primeiras 72h."},
    {etapa:"atb", d:"Valaciclovir",do:"1 g VO 12/12h × 7–10 dias",via:"VO",o:"Alternativa, posologia mais cômoda."},
    {etapa:"escala", d:"Famciclovir",do:"250 mg VO 8/8h × 7–10 dias",via:"VO",o:"Alternativa."},
    {etapa:"adj", d:"Profilaxia diária (se >6 recidivas/ano)",do:"Aciclovir 400 mg 12/12h",via:"VO",o:"Reduz recorrência e transmissão."},
  ],
  alertas:[
    {t:"warn",x:"Gestante com primoinfecção próximo ao parto: cesariana + aciclovir EV (transmissão neonatal grave)."},
  ],
  fisio:"HSV-2 (90%) ou HSV-1 (10%) — infecta neurônios sensitivos sacrais (lat e SS3-4); reativações periódicas → vesículas dérmicas.",
  mec:[
    {d:"Aciclovir",x:"Pró-droga — fosforilada pela <strong>timidina-quinase viral</strong> (apenas células infectadas) → trifosfato inibe <strong>DNA-polimerase viral</strong>."},
  ],
  diretriz:"PCDT-IST MS 2022; CDC STI 2021.",
  calcs:[],
},
{
  id:"uretrite", sis:"gu", grav:"baixa",
  nome:"Uretrite (Gonocócica e Não-Gonocócica)",
  sin:["uretrite","gonorreia","clamídia","DST"],
  def:"Corrimento uretral + disúria. Gono: purulento, abundante. Não-gono (clamídia, micoplasma): mucoide, escasso. Tratamento EMPÍRICO conjunto.",
  exames:["Gram do corrimento (diplococos GN intracelulares = gono)","NAAT (clamídia + gono) se disponível","Investigar outras IST: HIV, sífilis, hepatite"],
  rx:[
    {etapa:"atb", d:"Ceftriaxona",do:"500 mg IM dose única",via:"IM",o:"Cobertura para gonococo. SEMPRE associar tratamento para clamídia."},
    {etapa:"atb", d:"Azitromicina",do:"1 g VO dose única",via:"VO",o:"Cobertura clamídia. + Tratamento conjunto."},
    {etapa:"atb", d:"Doxiciclina",do:"100 mg VO 12/12h × 7 dias",via:"VO",o:"Alternativa à azitromicina. Preferida em DIP."},
    {etapa:"escala", d:"Tratar parceiro(s)",do:"Notificar e tratar",via:"—",o:"Últimos 60 dias."},
  ],
  alertas:[
    {t:"warn",x:"Em gestantes: ceftriaxona + azitromicina (não doxiciclina — Cat D)."},
    {t:"info",x:"Sempre testar HIV + sífilis + hepatites B/C."},
  ],
  fisio:"Neisseria gonorrhoeae e Chlamydia trachomatis — IST de mucosas. Coinfecção em ~30%.",
  mec:[
    {d:"Azitromicina",x:"Macrolídeo — liga 50S ribossomal."},
    {d:"Doxiciclina",x:"Tetraciclina — liga 30S ribossomal."},
  ],
  diretriz:"PCDT-IST MS 2022.",
  calcs:[],
},
{
  id:"urolitiase", sis:"gu", grav:"media",
  nome:"Urolitíase / Cólica Renal",
  sin:["litíase","cálculo renal","cólica","nefrolitíase"],
  def:"Dor súbita lombar irradiando para flanco/virilha + hematúria + náuseas. Cálculo no ureter.",
  exames:["EAS (hematúria 90%)","USG ou TC sem contraste (PADRÃO-OURO)","Função renal, eletrólitos","β-HCG"],
  rx:[
    {etapa:"escala", d:"Cetoprofeno / Diclofenaco",do:"100 mg IV ou 75 mg IM",via:"IV/IM",o:"1ª linha analgésica. CI: IRC, sangramento, gestação 3º trim."},
    {etapa:"adj", d:"Dipirona",do:"1 g IV",via:"IV",o:"Alternativa/associada."},
    {etapa:"escala", d:"Morfina",do:"0,1 mg/kg IV (max 5 mg/dose)",via:"IV",o:"Dor refratária aos AINEs."},
    {etapa:"escala", d:"Tansulosina",do:"0,4 mg VO/d × até 4 sem",via:"VO",o:"Cálculo distal 5–10 mm — facilita expulsão. Alfa-bloqueador."},
    {etapa:"escala", d:"Hidratação",do:"Conforme tolerância oral; não hiperhidratar",via:"VO/IV",o:"NÃO acelera expulsão. Hidratar para diurese 1,5–2 L/d."},
  ],
  alertas:[
    {t:"crit",x:"PIELONEFRITE OBSTRUTIVA (cálculo + febre + hidronefrose) é EMERGÊNCIA — drenagem urgente (duplo J, nefrostomia) + ATB."},
    {t:"info",x:"Cálculos >10 mm raramente são expulsos espontaneamente — referenciar urologia (LECO, URS)."},
  ],
  fisio:"Supersaturação urinária → cristalização → cálculo. Tipos: <strong>oxalato de Ca</strong> (80%), ácido úrico, estruvita (infecção), cisteína. Obstrução do ureter → ↑pressão pielocalicial → dor visceral cólica.",
  mec:[
    {d:"Tansulosina",x:"<strong>α1A-bloqueador seletivo</strong> — relaxa musculatura lisa do ureter distal, ↑probabilidade de expulsão de cálculos de 5–10 mm em até 28 dias."},
    {d:"AINE",x:"Inibe COX → ↓PGE2 (que aumenta a pressão glomerular contralateral e a contração ureteral); ação periférica e central."},
  ],
  diretriz:"EAU Urolithiasis Guidelines 2024.",
  calcs:[],
},
{
  id:"orquiepi", sis:"gu", grav:"media",
  nome:"Orquiepididimite",
  sin:["epididimite","orquite","escroto agudo"],
  def:"Dor escrotal + edema + ↑eptididimo. Diferenciar de torção testicular (emergência cirúrgica em <6h).",
  exames:["USG Doppler ESCROTAL (excluir torção — fluxo testicular preservado)","EAS + urocultura","Gram/NAAT em jovens"],
  rx:[
    {etapa:"atb", d:"Ceftriaxona + Doxiciclina",do:"500 mg IM + 100 mg 12/12h × 10 dias",via:"IM + VO",o:"<35a — cobertura gono + clamídia."},
    {etapa:"atb", d:"Ciprofloxacino",do:"500 mg VO 12/12h × 10–14 dias",via:"VO",o:">35a — cobertura E. coli, enterobactérias."},
    {etapa:"inicial", d:"Repouso + suporte escrotal + AINE",do:"Em todos",via:"—",o:"Reduz edema e dor."},
  ],
  alertas:[
    {t:"crit",x:"TORÇÃO TESTICULAR é emergência absoluta. Início súbito, sem febre, reflexo cremastérico ausente, testículo elevado, dor INTENSA. Cirurgia em <6h."},
  ],
  fisio:"Refluxo retrógrado de patógenos do trato urinário ou DST.",
  mec:[],
  diretriz:"EAU 2024; PCDT-IST MS 2022.",
  calcs:[],
},
{
  id:"sua", sis:"gu", grav:"media",
  nome:"Sangramento Uterino Anormal Agudo",
  sin:["SUA","sangramento uterino","menorragia"],
  def:"Sangramento uterino excessivo (≥80 mL ou duração ≥7 dias). FIGO PALM-COEIN para etiologia.",
  exames:["β-HCG (excluir gestação/aborto)","Hemograma, coagulograma","TSH, prolactina (se anovulação)","USG TV"],
  rx:[
    {etapa:"escala", d:"Estrogênios conjugados",do:"25 mg IV 4/4h até cessar (máx 24h) OU 1,25 mg VO 6/6h",via:"IV/VO",o:"Sangramento agudo — efeito hemostático em 12–24h."},
    {etapa:"escala", d:"Medroxiprogesterona",do:"10 mg VO/d × 5–10 dias",via:"VO",o:"Após cessar agudo, manter ciclo regular."},
    {etapa:"escala", d:"Ácido tranexâmico",do:"1 g VO 8/8h × até 5 dias",via:"VO",o:"Reduz volume em 40–50%."},
    {etapa:"escala", d:"ACO combinado",do:"1 cp 8/8h × 3 dias, depois 12/12h × 7d, depois 1×/d",via:"VO",o:"Hemostático e regularização."},
    {etapa:"escala", d:"Transfusão CH",do:"Se Hb <7 + instabilidade",via:"IV",o:"Hemorrágico grave."},
  ],
  alertas:[
    {t:"warn",x:"Sempre β-HCG primeiro. Aborto incompleto/gravidez ectópica mudam totalmente conduta."},
  ],
  fisio:"Múltiplas causas: pólipo, adenomiose, leiomioma, malignidade/hiperplasia, coagulopatia, ovulação disfuncional, endometrial, iatrogênica, não classificada.",
  mec:[
    {d:"Estrogênio",x:"Estimula proliferação endometrial rápida, recobre áreas sangrantes."},
    {d:"Ácido tranexâmico",x:"Análogo da lisina — inibe ligação plasminogênio à fibrina → ↓fibrinólise."},
  ],
  diretriz:"FEBRASGO 2017.",
  calcs:[],
},

/* ============== OSTEOMUSCULAR ============== */
{
  id:"lombalgia", sis:"ost", grav:"baixa",
  nome:"Lombalgia Mecânica / Torcicolo",
  sin:["lombalgia","dor lombar","torcicolo","cervicalgia"],
  def:"Dor mecânica musculoesquelética sem sinais de alarme. Diagnóstico clínico.",
  exames:["Excluir red flags: trauma, idade <20/>50, neoplasia, perda de peso, déficit motor, retenção urinária, febre, IV, corticoide, anticoagulação"],
  rx:[
    {etapa:"escala", d:"Paracetamol",do:"750–1000 mg 6/6h",via:"VO",o:"1ª linha analgésica."},
    {etapa:"escala", d:"Ibuprofeno/Cetoprofeno",do:"400–600 mg 8/8h ou 100 mg IM",via:"VO/IM",o:"AINE eficaz, atenção a IRC/GIT."},
    {etapa:"escala", d:"Ciclobenzaprina",do:"5–10 mg VO à noite × 5 dias",via:"VO",o:"Miorrelaxante. Causa sonolência."},
    {etapa:"escala", d:"Tramadol",do:"50–100 mg 6/6h",via:"VO/IV",o:"Refratário. Opioide fraco."},
    {etapa:"inicial", d:"Atividade física precoce",do:"Manter movimento",via:"—",o:"Repouso prolongado piora. Retornar atividade gradual."},
  ],
  alertas:[
    {t:"crit",x:"Red flags → imagem URGENTE: déficit motor progressivo, anestesia em sela, retenção urinária (síndrome cauda equina), febre + dor noturna, trauma."},
  ],
  fisio:"Espasmo da musculatura paravertebral — geralmente esforço, postura, estresse, fadiga.",
  mec:[
    {d:"Ciclobenzaprina",x:"Antagonista <strong>5-HT2 central</strong> (tronco encefálico) — relaxante musculoesquelético de ação central, sem efeito direto no músculo."},
  ],
  diretriz:"ACP — Diagnosis and Treatment of Low Back Pain (Qaseem A et al., Ann Intern Med 2017).",
  calcs:[],
},
{
  id:"fratura-exposta", sis:"ost", grav:"alta",
  nome:"Fratura Exposta",
  sin:["fratura exposta","Gustilo","fratura aberta"],
  def:"Fratura óssea com solução de continuidade da pele. Classificação Gustilo-Anderson I–IIIC.",
  exames:["RX 2 incidências","Hemograma, coagulograma","Tipagem"],
  rx:[
    {etapa:"escala", d:"ATB em ≤3h (CRÍTICO)",do:"Tipo I/II: Cefazolina 2 g IV 8/8h × 24h",via:"IV",o:"Atraso aumenta infecção em até 6×."},
    {etapa:"escala", d:"Tipo III",do:"Cefazolina 2 g 8/8h + Gentamicina 5 mg/kg/d",via:"IV",o:"Cobertura GN. Manter 48–72h pós-fechamento."},
    {etapa:"escala", d:"Contaminação por solo/fezes",do:"+ Metronidazol 500 mg 8/8h OU Penicilina G 2 MU 4/4h",via:"IV",o:"Cobertura Clostridium."},
    {etapa:"escala", d:"Antitetânica",do:"Conforme vacinação prévia",via:"IM",o:"Imunoglobulina humana antitetânica (IGHAT) 250–500 UI se status incerto/inadequado."},
    {etapa:"escala", d:"Limpeza + desbridamento + estabilização",do:"Cirúrgico em <6–8h",via:"—",o:"Lavagem cirúrgica copiosa, debridamento, fixação externa."},
    {etapa:"adj", d:"Analgesia",do:"Morfina 0,1 mg/kg IV",via:"IV",o:"Opioide IV titulado."},
  ],
  alertas:[
    {t:"crit",x:"ATB nos primeiros 60–180 min reduz infecção significativamente."},
    {t:"warn",x:"NÃO fechar primariamente em IIIB/C — fechamento tardio após desbridamentos."},
  ],
  fisio:"Lesão tecidual ampla + contaminação ambiental → alto risco de infecção (osteomielite, gangrena) e síndrome compartimental.",
  mec:[],
  diretriz:"Tornetta P, AAOS; SBOT.",
  calcs:[],
},
{
  id:"gota", sis:"ost", grav:"baixa",
  nome:"Crise de Gota",
  sin:["gota","artrite urato","podagra"],
  def:"Artrite aguda, monoarticular, intensa — \"acordou doendo\". Podagra (1ª MTF) clássica. Diagnóstico: cristais de urato monossódico no líquido sinovial (negativamente birrefringentes).",
  exames:["Ácido úrico (pode estar normal na crise)","Punção articular se dúvida","RX articulação"],
  rx:[
    {etapa:"escala", d:"AINE",do:"Naproxeno 500 mg 12/12h OU indometacina 50 mg 8/8h × 5–7 dias",via:"VO",o:"1ª linha em sem CI."},
    {etapa:"escala", d:"Colchicina",do:"1 mg VO + 0,5 mg em 1h, depois 0,5 mg 2–3×/d × 7d",via:"VO",o:"Iniciar nas primeiras 12–24h da crise. Diarreia frequente."},
    {etapa:"escala", d:"Prednisona",do:"30–40 mg/d × 5 dias",via:"VO",o:"AINE/colchicina contraindicados, IRC, idoso. Pode infiltrar articulação."},
    {etapa:"escala", d:"Alopurinol",do:"100 mg/d, titular até 300–600 mg",via:"VO",o:"NÃO iniciar durante a crise. Em uso crônico: NÃO suspender em crise."},
  ],
  alertas:[
    {t:"warn",x:"Iniciar profilaxia (alopurinol/febuxostate) APÓS resolução da crise (2–4 sem). Iniciar com colchicina/AINE 3–6 meses para evitar crise paradoxal."},
  ],
  fisio:"Hiperuricemia → deposição de cristais de urato monossódico em articulações → ativação de inflamassoma NLRP3 → liberação de IL-1β → resposta inflamatória neutrofílica aguda.",
  mec:[
    {d:"Colchicina",x:"Liga-se à <strong>tubulina</strong> e inibe polimerização de microtúbulos → bloqueia quimiotaxia e fagocitose neutrofílica. Inibe inflamassoma NLRP3."},
    {d:"Alopurinol",x:"Inibe <strong>xantina-oxidase</strong> → ↓conversão de hipoxantina/xantina em ácido úrico. Uso CRÔNICO."},
  ],
  diretriz:"ACR 2020 Guideline for the Management of Gout (FitzGerald JD et al., Arthritis Care Res 2020;72:744–760).",
  calcs:[],
},

/* ============== PSIQUIATRIA ============== */
{
  id:"acatisia", sis:"psiq", grav:"baixa",
  nome:"Acatisia",
  sin:["acatisia","SEP","inquietação motora"],
  def:"Inquietação motora subjetiva e objetiva — paciente refere \"não consegue ficar parado\". Efeito adverso de antipsicóticos, metoclopramida, ISRS.",
  exames:["Avaliação clínica","Revisão medicamentosa"],
  rx:[
    {etapa:"escala", d:"Propranolol",do:"20–40 mg VO 8/8h",via:"VO",o:"1ª linha. β-bloqueador lipofílico — atravessa BHE."},
    {etapa:"escala", d:"Biperideno",do:"2–4 mg VO/IM",via:"VO/IM",o:"Anticolinérgico — útil em distonia também."},
    {etapa:"escala", d:"Clonazepam",do:"0,5–2 mg VO",via:"VO",o:"Alternativa."},
    {etapa:"escala", d:"Reduzir/trocar agente causal",do:"—",via:"—",o:"Principalmente — trocar haloperidol por atípico de menor risco."},
  ],
  alertas:[
    {t:"info",x:"Acatisia AGITA o paciente e pode ser confundida com piora psicótica — não aumentar antipsicótico, REDUZIR."},
  ],
  fisio:"Bloqueio de receptores D2 da via mesolímbica/nigroestriatal → desequilíbrio dopaminérgico-colinérgico no estriado.",
  mec:[
    {d:"Propranolol",x:"β-bloqueador não-seletivo lipofílico — penetra BHE e modula sistema noradrenérgico central."},
    {d:"Biperideno",x:"<strong>Anticolinérgico central</strong> — restaura equilíbrio dopa-colinérgico nigroestriatal."},
  ],
  diretriz:"WFSBP; ABP.",
  calcs:[],
},
{
  id:"sind-psicotica", sis:"psiq", grav:"alta",
  nome:"Síndrome Psicótica Aguda",
  sin:["psicose","surto psicótico","esquizofrenia","delírio"],
  def:"Delírios + alucinações + alteração do pensamento. 1º episódio = ↑investigação orgânica (orgânica até prova contrária).",
  exames:["Excluir orgânica: HGT, eletrólitos, função renal/hepática, TSH, B12, sífilis, HIV","TC crânio em primeiro episódio com red flags","Toxicológico"],
  rx:[
    {etapa:"escala", d:"Haloperidol",do:"2,5–5 mg IM, repetir 30 min",via:"IM",o:"Antipsicótico típico clássico. Risco SEP."},
    {etapa:"escala", d:"Olanzapina",do:"10 mg IM",via:"IM",o:"Atípico injetável. NÃO associar a BZD IV (depressão respiratória)."},
    {etapa:"escala", d:"Risperidona",do:"1–2 mg VO/VL",via:"VO",o:"Quando colaborativo."},
    {etapa:"escala", d:"Quetiapina",do:"25–100 mg VO",via:"VO",o:"Útil em idoso (menos SEP)."},
    {etapa:"escala", d:"Prometazina",do:"25–50 mg IM",via:"IM",o:"Adjuvante — sedativo + ↓SEP do haloperidol."},
  ],
  alertas:[
    {t:"warn",x:"Risco de síndrome neuroléptica maligna (rara mas grave): febre + rigidez + ↑CK + disautonomia. Suspender antipsicótico, suporte, dantroleno."},
  ],
  fisio:"Hiperatividade dopaminérgica na via mesolímbica (sintomas positivos) + hipoatividade na mesocortical (negativos).",
  mec:[
    {d:"Haloperidol",x:"<strong>Antagonista D2</strong> (típico) — alta afinidade. Risco SEP, ↑prolactina."},
    {d:"Olanzapina/Risperidona/Quetiapina",x:"<strong>Antagonistas D2 + 5-HT2A</strong> (atípicos) — menor SEP."},
  ],
  diretriz:"ABP; APA.",
  calcs:[],
},
{
  id:"agitacao", sis:"psiq", grav:"alta",
  nome:"Agitação Psicomotora",
  sin:["agitação","violência","contenção"],
  def:"Agitação intensa com risco para paciente/equipe. Etiologia orgânica (delirium, intox), psiquiátrica ou comportamental.",
  exames:["HGT, eletrólitos, função renal","Toxicológico se suspeita","TC crânio se déficit/trauma"],
  rx:[
    {etapa:"escala", d:"Descalonamento verbal",do:"PRIMEIRO sempre",via:"—",o:"Comunicação calma, espaço, evitar confronto. Eficaz em maioria."},
    {etapa:"escala", d:"Haloperidol + Prometazina",do:"5 mg + 25 mg IM (Cochrane TREC)",via:"IM",o:"Esquema mais estudado em agitação aguda — eficaz e seguro."},
    {etapa:"escala", d:"Midazolam",do:"5–15 mg IM",via:"IM",o:"Alternativa em intoxicação alcoólica/desconhecida. Cuidado: depressão respiratória."},
    {etapa:"escala", d:"Olanzapina",do:"10 mg IM",via:"IM",o:"Atípico — NÃO combinar com BZD IV (depressão respiratória)."},
    {etapa:"escala", d:"Cetamina",do:"4–5 mg/kg IM",via:"IM",o:"Refratário extremo (excited delirium). Pré-hospitalar."},
    {etapa:"adj", d:"Contenção mecânica",do:"4–5 pontos, conforme protocolo",via:"—",o:"Último recurso. Tempo limitado, supervisão contínua, reavaliação."},
  ],
  alertas:[
    {t:"crit",x:"Agitação + febre + rigidez = pensar em SNM ou serotoninérgica. NÃO continuar com antipsicótico de alta potência sem avaliar."},
    {t:"warn",x:"Idoso agitado = delirium até prova contrário (infecção, drogas, retenção urinária, fecal, dor). Tratar a CAUSA, não só o sintoma."},
  ],
  fisio:"Múltiplas causas. Sempre buscar desencadeante orgânico, especialmente no idoso.",
  mec:[],
  diretriz:"Diretrizes Brasileiras para o Manejo da Agitação Psicomotora — ABP (Baldaçara L et al., Debates em Psiquiatria 2021–2022).",
  calcs:[],
},
{
  id:"ansiedade", sis:"psiq", grav:"baixa",
  nome:"Crise de Ansiedade / Pânico",
  sin:["ansiedade","pânico","ataque de pânico"],
  def:"Início súbito de medo intenso + sintomas físicos: taquicardia, sudorese, tremor, dispneia, dor torácica, parestesia, despersonalização. Pico em 10 min, autolimitada.",
  exames:["Excluir causa orgânica: ECG, TSH, glicemia, eletrólitos"],
  rx:[
    {etapa:"escala", d:"Clonazepam",do:"0,5–2 mg VO/SL",via:"VO/SL",o:"Início 30–60 min. BZD de meia-vida longa."},
    {etapa:"escala", d:"Alprazolam",do:"0,25–0,5 mg VO",via:"VO",o:"Início rápido, ação curta."},
    {etapa:"escala", d:"Lorazepam",do:"1–2 mg VO",via:"VO",o:"Boa em hepatopata (sem metabólitos ativos)."},
    {etapa:"escala", d:"Tranquilização verbal",do:"—",via:"—",o:"Importante. Respiração lenta. Não é IAM."},
  ],
  alertas:[
    {t:"warn",x:"BZD são para uso AGUDO. Não prescrever crônico — dependência, tolerância. Encaminhar para psiquiatria/psicologia."},
  ],
  fisio:"Hiperativação do eixo límbico-amigdalar com descarga adrenérgica intensa.",
  mec:[
    {d:"BZD (Clonazepam, Alprazolam, Lorazepam)",x:"Agonistas do sítio benzodiazepínico no <strong>receptor GABA-A</strong> → ↑frequência de abertura de canal Cl⁻ → hiperpolarização → inibição neuronal."},
  ],
  diretriz:"APA Practice Guideline for Panic Disorder.",
  calcs:[],
},

/* ============== HIDROELETROLÍTICO ============== */
{
  id:"hipercalemia", sis:"hidro", grav:"alta",
  nome:"Hipercalemia",
  sin:["hipercalemia","K alto","potássio alto"],
  def:"K⁺ >5,5 mEq/L. Grave se >6,5 OU alterações ECG (T apiculada → P achatada → QRS alargado → padrão sinusoidal → FV).",
  exames:["ECG IMEDIATO (em todo K>5,5)","Confirmar com K plasmático (excluir hemólise da amostra)","Função renal, gasometria, glicemia","CK (rabdomiólise)"],
  rx:[
    {etapa:"inicial", d:"ECG IMEDIATO (todo K>5,5)",do:"Buscar: T apiculada → P achatada → ↑PR → QRS alargado → sinusoidal → FV",via:"—",o:"PRIORIDADE absoluta. K alterado SEM ECG = risco PCR não detectado."},
    {etapa:"inicial", d:"Confirmar K plasmático",do:"Coletar 2ª amostra, sem hemólise/garroteamento",via:"—",o:"Hemólise da amostra causa pseudo-hipercalemia. Confirmar antes de tratar agressivamente em assintomático sem ECG."},
    {etapa:"inicial", d:"Suspender drogas culpadas",do:"IECA, BRA, espironolactona, AINE, heparina, trimetoprima, tacrolimus, β-bloqueador",via:"—",o:"Causa medicamentosa é frequente. Suspender o quanto antes."},
    {etapa:"escala", d:"① ESTABILIZAÇÃO MEMBRANA — Gluconato Ca 10%",do:"10 mL IV em 2-3 min, repetir 5 min se ECG persistente",via:"IV",o:"SE ECG ALTERADO. NÃO reduz K. Início 1-3 min, duração ~1h. Não atrasa outras medidas."},
    {etapa:"escala", d:"② TRANSLOCAÇÃO — Insulina + Glicose",do:"Insulina regular 10 UI + Glicose 50% 100 mL (50g) IV em 15-30 min",via:"IV",o:"↓K 0,5-1,2 mEq/L em 30-60 min. Monitorar HGT 1h depois (hipoglicemia tardia comum)."},
    {etapa:"escala", d:"② TRANSLOCAÇÃO — Salbutamol nebulizado",do:"10-20 mg NBZ (4-8× dose habitual)",via:"NBZ",o:"ADITIVO ao insulina (não substitui). Translocação β2. Pode acumular efeito."},
    {etapa:"escala", d:"③ Bicarbonato (apenas se acidose)",do:"50-100 mEq IV se pH<7,2",via:"IV",o:"APENAS em acidose metabólica. NÃO rotineiro. Pode piorar volemia."},
    {etapa:"escala", d:"④ REMOÇÃO — Furosemida (se diurese)",do:"40-80 mg IV",via:"IV",o:"Útil se função renal preservada. Promove excreção renal de K."},
    {etapa:"escala", d:"④ REMOÇÃO — Sorcal / Ciclosilicato",do:"Sorcal 15g VO 6/6h. Lokelma 10g 8/8h × 48h",via:"VO",o:"Remoção intestinal. Efeito em horas (lento). Adjuvante, não substitui medidas urgentes."},
    {etapa:"escala", d:"⑤ HEMODIÁLISE",do:"Acionar nefrologia",via:"—",o:"INDICAÇÕES: K>6,5 refratário, IRC dialítica, ECG persistente, rabdomiólise grave, sobrecarga hídrica concomitante."},
    {etapa:"adj", d:"Investigar CAUSA",do:"Função renal, BHE, drogas, rabdomiólise, hemólise, lise tumoral",via:"—",o:"CK em rabdomiólise, urina, etc. Tratar causa subjacente."},
    {etapa:"alta", d:"Prevenção secundária",do:"Dieta hipocalêmica (frutas, batata, feijão) + reavaliar IECA/BRA",via:"—",o:"Educação alimentar. Monitorização periódica em IRC, IC, DM."},
  ],
  alertas:[
    {t:"crit",x:"K>6,5 ou ECG alterado: cálcio IMEDIATO + insulina + nebulização CONJUNTAMENTE — não em sequência."},
    {t:"warn",x:"Suspender IECA/BRA/espironolactona/AINE/heparina. Trimetoprima e tacrolimus também ↑K."},
  ],
  fisio:"Causas: IRA/IRC + entrada (KCl IV, dieta), saída ↓ (IECA/BRA, espiro, AINE), translocação (acidose, rabdomiólise, hemólise, lise tumoral, hiperglicemia, β-bloqueador). O K extracelular alterado afeta gradiente de membrana → instabilidade elétrica miocárdica → arritmias letais.",
  mec:[
    {d:"Gluconato de Cálcio",x:"↑limiar de despolarização miocárdica → restaura gradiente normal e <strong>estabiliza a membrana</strong> contra hiperexcitabilidade. NÃO altera K sérico."},
    {d:"Insulina + Glicose",x:"Insulina ativa <strong>Na⁺/K⁺-ATPase</strong> → puxa K para o intracelular. Glicose previne hipoglicemia."},
    {d:"Salbutamol",x:"β2-agonista — ativa Na⁺/K⁺-ATPase via AMPc, translocação intracelular."},
    {d:"Sorcal / Lokelma",x:"Trocadores intestinais — retiram K nas fezes em troca de Na/Ca."},
  ],
  diretriz:"KDIGO Acute Hyperkalemia Conference (Clase CM et al., Kidney Int 2020;97:42–61, DOI:10.1016/j.kint.2019.09.018). Lindner G et al., Eur J Emerg Med 2020;27:329–337.",
  fluxo:"hipercalemia",
  calcs:[],
},
{
  id:"hipocalemia", sis:"hidro", grav:"media",
  nome:"Hipocalemia",
  sin:["hipocalemia","K baixo","potássio baixo"],
  def:"K⁺ <3,5 mEq/L. Grave se <2,5 ou ECG alterado (onda U, T aplanada, depressão ST, prolongamento QT, arritmias).",
  exames:["K sérico (confirmar)","ECG","Mg (frequentemente associado — corrigir antes)","Função renal, gasometria, glicemia","Urinários (K, Cl, Na) para etiologia"],
  rx:[
    {etapa:"escala", d:"KCl VO",do:"40–60 mEq/d (xarope 6%: 1 mL = 0,8 mEq)",via:"VO",o:"1ª linha em leve/moderada com tolerância oral."},
    {etapa:"escala", d:"KCl IV periférico",do:"10–20 mEq em 100 mL SF em 1h",via:"IV",o:"Velocidade máx periférica 10–20 mEq/h. NUNCA bolus."},
    {etapa:"escala", d:"KCl IV central",do:"Até 40 mEq/h em CVC com monitor cardíaco",via:"IV central",o:"K<2,5 ou sintomático grave."},
    {etapa:"escala", d:"MgSO4",do:"1–2 g IV em 15 min",via:"IV",o:"Corrigir Mg SEMPRE — hipoMg perpetua hipoK (efeito ROMK)."},
  ],
  alertas:[
    {t:"warn",x:"Suspender diurético tiazídico/alça em hipoK persistente. Investigar perda renal vs gastrointestinal."},
    {t:"info",x:"Cada queda de 1 mEq/L no K sérico corresponde a deficit ~200–400 mEq corporal."},
  ],
  fisio:"Causas: ↓ingesta, perda gastrointestinal (vômito, diarreia, fístula, laxante), perda renal (tiazida, alça, hiperaldo, Bartter/Gitelman), translocação (β2, insulina, alcalose, leucemia).",
  mec:[],
  diretriz:"Brazilian Journal of Nephrology; UpToDate.",
  calcs:[],
},
{
  id:"hipona", sis:"hidro", grav:"alta",
  nome:"Hiponatremia",
  sin:["hiponatremia","Na baixo","sódio baixo","SIADH"],
  def:"Na <135 mEq/L. Aguda <48h (alto risco edema cerebral) vs crônica >48h (risco MIELINÓLISE PONTINA se corrigida rápido demais). Classificar: hipo/iso/hipertônica × hipo/eu/hipervolêmica.",
  exames:["Na sérico + osmolaridade plasmática","Osmolaridade urinária + Na urinário","Volemia (clínica) ★","Função renal, hepática, TSH, cortisol AM","Glicemia (excluir pseudohiponatremia)"],
  rx:[
    {etapa:"escala", d:"NaCl 3% (sintomática grave: convulsão, coma)",do:"100–150 mL IV em 10 min, repetir até 3×",via:"IV",o:"Meta inicial: ↑Na 4–6 mEq/L. Não passar de 8–10 mEq/L em 24h (≤18 mEq/L em 48h) — risco mielinólise."},
    {etapa:"escala", d:"SF 0,9% (hipovolêmica)",do:"1 mL/kg/h",via:"IV",o:"Restaurar volume; após euvolemia, ADH suprimida → diurese livre + correção espontânea — CUIDADO com correção rápida."},
    {etapa:"escala", d:"Restrição hídrica (SIADH/IC)",do:"<800 mL/24h",via:"—",o:"Cronica eu/hipervolêmica."},
    {etapa:"escala", d:"Tolvaptan",do:"15 mg VO/d",via:"VO",o:"Vaptan — em SIADH refratário/IC. Caro."},
    {etapa:"escala", d:"DDAVP \"frenador\"",do:"2 mcg IV se correção rápida demais",via:"IV",o:"Re-induz ADH para EVITAR correção exagerada (≥10 mEq/L em 24h)."},
  ],
  alertas:[
    {t:"crit",x:"MIELINÓLISE PONTINA OSMÓTICA: correção >10 mEq/L em 24h em hiponatremia crônica. Paralisia, alteração consciência, dias depois. PREVENÍVEL — controlar velocidade."},
    {t:"warn",x:"Dosar Na 2/2h durante correção ativa com NaCl 3%."},
  ],
  fisio:"Excesso de água em relação ao Na — geralmente por ADH elevada (SIADH, IC, cirrose, hipovolemia). Aguda: edema cerebral por desequilíbrio osmótico → herniação. Crônica: cérebro se adaptou → correção rápida → mielinólise.",
  mec:[
    {d:"NaCl 3%",x:"Solução hipertônica — ↑osmolaridade plasmática → mobiliza água do compartimento intracelular cerebral → ↓edema."},
    {d:"Tolvaptan",x:"Antagonista V2 — bloqueia ação da ADH no túbulo coletor → aquarese (excreção de água livre)."},
  ],
  diretriz:"European Society of Endocrinology/ESICM/ERA-EDTA Hyponatremia 2014 (Spasovski G et al., Eur J Endocrinol 2014;170:G1–G47, DOI:10.1530/EJE-13-1020).",
  calcs:["corr-na"],
},
{
  id:"hiperna", sis:"hidro", grav:"alta",
  nome:"Hipernatremia",
  sin:["hipernatremia","Na alto","sódio alto"],
  def:"Na >145 mEq/L. Quase sempre deficit de água. Sintomas: sede, letargia, irritabilidade, convulsão (sobretudo se aguda).",
  exames:["Na sérico, osmolaridade","Volemia (clínica)","Osmolaridade urinária (pesquisar DI)","Função renal","Glicemia (DM ↑água)"],
  rx:[
    {etapa:"escala", d:"SG 5% ou SF 0,45%",do:"1 mL/kg/h",via:"IV",o:"Correção lenta — NÃO passar de 10 mEq/L em 24h. Aguda <24h pode corrigir mais rápido."},
    {etapa:"inicial", d:"Água livre VO/SNG",do:"Conforme deficit calculado",via:"VO/SNG",o:"Preferível se TGI tolerar."},
    {etapa:"escala", d:"DDAVP intranasal",do:"10–20 mcg",via:"Intranasal",o:"Diabetes insípido central."},
  ],
  alertas:[
    {t:"warn",x:"Correção rápida em hipernatremia crônica → edema cerebral. Meta: ↓0,5 mEq/L/h ou ≤10 mEq/L em 24h."},
  ],
  fisio:"Sempre déficit de água relativa ao Na. Causas: perda de água sem reposição (idosos, comatosos, perdas renais por DI, perda GI), perda hipotônica (sudorese, diurético), ganho de Na (NaCl hipertônico, NaHCO3).",
  mec:[
    {d:"DDAVP",x:"Análogo da ADH — agonista V2 → ↑permeabilidade ao H2O no túbulo coletor."},
  ],
  diretriz:"Adrogué HJ, Madias NE, NEJM 2000;342:1493–1499.",
  calcs:["corr-na"],
},
{
  id:"hipocalcemia", sis:"hidro", grav:"media",
  nome:"Hipocalcemia",
  sin:["hipocalcemia","Ca baixo"],
  def:"Ca total <8,5 OU Ca iônico <1,1. Sintomas: parestesia, Chvostek, Trousseau, tetania, prolongamento QT.",
  exames:["Ca total + albumina (corrigir) OU Ca iônico","Mg, fósforo","ECG (QT longo)","PTH, vit D"],
  rx:[
    {etapa:"escala", d:"Gluconato de Ca 10%",do:"10–20 mL IV em 10 min, depois 0,5–1 mg/kg/h (Ca elementar) BIC",via:"IV",o:"Sintomática (tetania, convulsão, QT longo). Diluir em SG5% 100 mL."},
    {etapa:"escala", d:"Carbonato de Cálcio",do:"500–1000 mg Ca elementar VO 8/8h",via:"VO",o:"Assintomática ou após estabilização."},
    {etapa:"escala", d:"Vitamina D",do:"Colecalciferol 1000–2000 UI/d",via:"VO",o:"Crônica."},
    {etapa:"escala", d:"MgSO4",do:"1–2 g IV",via:"IV",o:"HipoMg causa hipoCa refratária — sempre corrigir."},
  ],
  alertas:[
    {t:"warn",x:"Corrigir hipoMg ANTES de Ca em hipoCa refratária."},
    {t:"info",x:"Ca corrigido = Ca total + 0,8 × (4 − albumina g/dL)."},
  ],
  fisio:"Causas: hipoparatireoidismo (pós-tireoidectomia), deficiência de vit D, IRC, hipoMg, hiperfosfatemia, pancreatite, transfusão massiva (citrato), sepse, álcool.",
  mec:[],
  diretriz:"Endocrine Society Guidelines.",
  calcs:[],
},
{
  id:"hipercalcemia", sis:"hidro", grav:"alta",
  nome:"Hipercalcemia",
  sin:["hipercalcemia","Ca alto"],
  def:"Ca total >10,5. Severa >14 com sintomas: \"stones, bones, abdominal moans, psychiatric overtones\". Crise hipercalcêmica >14 = emergência.",
  exames:["Ca total + iônico","Albumina","Função renal, eletrólitos, fósforo","PTH (↓ = hipercalcemia maligna; ↑ = primária)","ECG (QT curto)","RX, USG (litíase)"],
  rx:[
    {etapa:"inicial", d:"SF 0,9%",do:"200–300 mL/h × 24–48h",via:"IV",o:"PILAR. Restaura volume + ↑excreção renal de Ca. Cuidado com IC/idoso."},
    {etapa:"escala", d:"Furosemida",do:"20–40 mg IV após volemizar",via:"IV",o:"APENAS APÓS hidratação adequada. Sem furosemida = ↓ excreção renal de Ca."},
    {etapa:"escala", d:"Pamidronato",do:"60–90 mg IV em 2h",via:"IV",o:"Bisfosfonato — efeito em 2–4 dias. Hipercalcemia maligna."},
    {etapa:"escala", d:"Ácido zoledrônico",do:"4 mg IV em 15 min",via:"IV",o:"Alternativa mais potente."},
    {etapa:"escala", d:"Calcitonina",do:"4 UI/kg SC/IM 12/12h",via:"SC/IM",o:"Início rápido (4–6h) mas curto. Ponte até bisfosfonato."},
    {etapa:"escala", d:"Hemodiálise",do:"—",via:"—",o:"Ca>18 com sintomas neurológicos/cardíacos, IRC."},
  ],
  alertas:[
    {t:"crit",x:"Hipercalcemia maligna >14: tratar URGENTE. Sempre investigar neoplasia (mieloma, mama, pulmão, paratireoide)."},
  ],
  fisio:"Causas: <strong>hiperparatireoidismo primário</strong> e <strong>neoplasias</strong> (PTHrP, lise óssea) respondem por 90%. Outros: tiazida, vit D, sarcoidose, hipertireoidismo, imobilização.",
  mec:[
    {d:"Pamidronato / Zoledrônico",x:"<strong>Inibem osteoclastos</strong> (mecanismo via FPPS) → ↓reabsorção óssea → ↓liberação de Ca."},
    {d:"Calcitonina",x:"Hormônio tireoidiano — ↓atividade osteoclástica + ↑excreção renal de Ca. Taquifilaxia em 48h."},
  ],
  diretriz:"Endocrine Society 2016.",
  calcs:[],
},
{
  id:"hipomg", sis:"hidro", grav:"media",
  nome:"Hipo/Hipermagnesemia",
  sin:["hipomagnesemia","Mg","magnésio"],
  def:"HipoMg <1,7. Sintomas: tetania, arritmia, QT longo, hipoK/hipoCa refratários. HiperMg >2,5 (geralmente iatrogênica em IRC, eclâmpsia).",
  exames:["Mg sérico","K, Ca, fósforo","Função renal","ECG (QT longo na hipoMg, prolongamento PR/QT na hiperMg)"],
  rx:[
    {etapa:"escala", d:"HIPO — MgSO4 IV",do:"1–2 g em 100 mL SF/SG em 15–60 min",via:"IV",o:"Repetir conforme nível. Em torsades: 2 g em 10 min."},
    {etapa:"escala", d:"HIPO — Mg VO crônica",do:"Magnésio quelato 100–400 mg/d",via:"VO",o:"Diarréia limitante."},
    {etapa:"escala", d:"HIPER — Gluconato de Ca",do:"10 mL IV em 2 min",via:"IV",o:"Antagoniza efeitos cardíacos."},
    {etapa:"escala", d:"HIPER — Hidratação + Furosemida",do:"SF + furosemida",via:"IV",o:"↑Excreção renal."},
    {etapa:"escala", d:"HIPER — Hemodiálise",do:"—",via:"—",o:"IRC ou Mg muito alto sintomático."},
  ],
  alertas:[
    {t:"warn",x:"Mg é cofator de Na⁺/K⁺-ATPase — hipoMg causa hipoK refratária e ↑risco de arritmia (torsades)."},
  ],
  fisio:"HipoMg: má absorção (etilismo, diarreia), drogas (diurético, IBP, aminoglicosídeo). HiperMg: IRC, dose terapêutica em eclâmpsia.",
  mec:[],
  diretriz:"UpToDate, ESC.",
  calcs:[],
},
);
/* PARTE 2 dados completos */
