/* ===========================================================
   VOVÔMINIC EMERGÊNCIA — BLOCO D RODADA 2
   Asma crônica + DPOC (separadas das crises agudas)
   =========================================================== */

PATOLOGIAS.push(

/* ============== ASMA CRÔNICA ============== */
{id:"asma-cronica", nome:"Asma crônica — manejo ambulatorial GINA 2025", sis:"resp", grav:"baixa",
cid:"J45", ciap:"R96",
sin:["Asma","Asma alérgica","Asma persistente","Bombinha","Asma controle","GINA"],
def:"Doença inflamatória crônica das VA caracterizada por HIPER-RESPONSIVIDADE BRÔNQUICA + obstrução variável e reversível. Tratamento atual GINA 2025 abandona SABA isolado — todos pacientes usam ICS-formoterol (MART/SMART) como estratégia preferida. Foco em CONTROLE de sintomas + redução de RISCO futuro (exacerbação, perda de função pulmonar).",
quadro:["Sintomas episódicos: sibilância, dispneia, opressão torácica, TOSSE — piora à noite/manhã","Gatilhos: exercício, alérgenos (ácaro, pelos, pólen), IVAS, frio, fumaça, AINEs","HISTÓRIA pessoal/familiar de ATOPIA (rinite, eczema, alergia)","Resposta a broncodilatador em prova terapêutica","⚠ DDX: DPOC (>40a, tabagismo, irreversível), bronquiectasia, ICC, RGE com tosse"],
diag:["CLÍNICA — sintomas característicos + variabilidade","ESPIROMETRIA com prova broncodilatadora: VEF1/CVF baixo + reversibilidade (Δ VEF1 ≥12% e 200 mL pós-BD)","Em criança <5a: clínica + prova terapêutica","PEAK FLOW seriado: variabilidade >10% adulto, >13% criança"],
exames:["ESPIROMETRIA pré e pós-BD","PEAK FLOW (importante para automonitorização)","Em casos atípicos/graves: IgE total, IgE específicas, FeNO, eosinófilos, RX tórax (excluir DDX)"],
rx:[
{etapa:"escala", d:"⚠ ESCADA GINA 2025 (adultos e adolescentes) — TRACK 1 PREFERIDA: ICS-formoterol como reliever (MART)"},
{etapa:"escala", d:"⚠ DEGRAU 1-2 (sintomas <2×/sem)"},
{etapa:"escala", d:"Budesonida + formoterol 200/6 mcg DPI 1 inalação CONFORME NECESSÁRIO (PRN)", do:"1 inalação PRN", via:"INH", o:"Substitui o antigo SABA isolado. Anti-inflamatório + broncodilatador conforme necessário."},
{etapa:"escala", d:"OU Beclometasona + formoterol 100/6 mcg PRN"},
{etapa:"escala", d:"⚠ DEGRAU 3 (sintomas >2×/sem)"},
{etapa:"escala", d:"Budesonida + formoterol 200/6 mcg DPI — 1 inalação 1-2×/d FIXO + PRN (MART)", do:"1-2 inal fixo/d + PRN", via:"INH"},
{etapa:"escala", d:"⚠ DEGRAU 4 (sintomas frequentes / função pulmonar reduzida)"},
{etapa:"escala", d:"Budesonida + formoterol 200/6 mcg — 2 inalações 2×/d FIXO + PRN", do:"2 inal 2×/d + PRN", via:"INH"},
{etapa:"escala", d:"⚠ DEGRAU 5 (asma grave / refratária) — referenciar pneumologia"},
{etapa:"escala", d:"Dose alta de ICS-formoterol + LAMA (tiotrópio) + considerar biológicos (anti-IgE: omalizumabe; anti-IL5: mepolizumabe, benralizumabe; anti-IL4/13: dupilumabe)"},
{etapa:"adj", d:"⚠ TRACK 2 (alternativa em <12a ou paciente que não aceita MART)"},
{etapa:"adj", d:"ICS DOSE BAIXA + SABA (salbutamol) PRN — modelo clássico"},
{etapa:"adj", d:"Budesonida 200 mcg DPI 1 inal 2×/d + salbutamol PRN"},
{etapa:"adj", d:"OU fluticasona 250 mcg DPI 1 inal 2×/d + salbutamol PRN"},
{etapa:"adj", d:"⚠ CRIANÇA 6-11a — esquemas adaptados"},
{etapa:"adj", d:"Degrau 1-2: ICS baixa dose + SABA PRN ou ICS-formoterol PRN (preferido)"},
{etapa:"adj", d:"Degrau 3-4: ICS dose média + LABA ou ICS-formoterol MART"},
{etapa:"adj", d:"⚠ CRIANÇA <5a — particularidades"},
{etapa:"adj", d:"Espaçador SEMPRE (sem nebulizador rotineiro em ambulatório)"},
{etapa:"adj", d:"Budesonida 200 mcg ESPAÇADOR 1 puff 2×/d (degrau 2)"},
{etapa:"adj", d:"Ou fluticasona 50-125 mcg 2×/d"},
{etapa:"adj", d:"+ salbutamol PRN espaçador"},
{etapa:"adj", d:"⚠ TÉCNICA INALATÓRIA — ESSENCIAL revisar em cada consulta"},
{etapa:"adj", d:"DPI (pó seco): inspiração rápida e profunda"},
{etapa:"adj", d:"MDI: inspiração LENTA e profunda + retenção 10s"},
{etapa:"adj", d:"ESPAÇADOR sempre em criança <12a + idoso + erro de coordenação"},
{etapa:"adj", d:"⚠ MEDIDAS NÃO-FARMACOLÓGICAS"},
{etapa:"adj", d:"CONTROLE DE GATILHOS: ácaros (capa antiácaro, sol no colchão), pólen, pelos, fumaça, AINEs"},
{etapa:"adj", d:"VACINAÇÃO: influenza anual, pneumocócica, COVID-19, RSV (>60a)"},
{etapa:"adj", d:"CESSAÇÃO TABAGISMO (asma + tabagismo = grave)"},
{etapa:"adj", d:"PESO ADEQUADO (obesidade piora asma)"},
{etapa:"adj", d:"EXERCÍCIO regular (com pré-medicação se asma do esforço)"},
{etapa:"adj", d:"⚠ PLANO DE AÇÃO POR ESCRITO"},
{etapa:"adj", d:"VERDE (controlada): manter medicação"},
{etapa:"adj", d:"AMARELO (piora): aumentar ICS-formoterol PRN + considerar ICS-formoterol 4×/d × 7-14 dias"},
{etapa:"adj", d:"VERMELHO (crise): salbutamol + prednisona + procurar PA"},
{etapa:"alta", d:"AVALIAR CONTROLE em CADA consulta — questionário ACT (>20 controlada)"},
{etapa:"alta", d:"⚠ CONSIDERAR DESCALONAMENTO após 3 meses bem controlada (manter degrau mais baixo eficaz)"},
{etapa:"alta", d:"ENCAMINHAR PNEUMOLOGIA: degrau 4-5, exacerbações recorrentes (>2/ano), falência de controle, dúvida diagnóstica"},
{etapa:"alta", d:"⚠ ATENÇÃO: SABA EM EXCESSO (>3 frascos/ano) = mau controle, risco de morte. Reavaliar tratamento"},
],
alertas:[
{nivel:"crit", txt:"⚠ GINA 2025 ABANDONA SABA ISOLADO — todos pacientes >12a usam ICS-formoterol PRN (não salbutamol isolado). Reduziu mortalidade. Track 1 é preferida."},
{nivel:"crit", txt:"USO DE SABA >3 frascos de salbutamol/ano = MAU CONTROLE. Risco aumentado de exacerbação grave e morte. Reavaliar imediatamente."},
{nivel:"warn", txt:"TÉCNICA INALATÓRIA é o erro mais comum — revisar A CADA consulta. Espaçador sempre em criança, idoso, dúvida."},
{nivel:"warn", txt:"AINE pode desencadear crise grave em asma com pólipos (Samter triad). História cuidadosa."},
{nivel:"warn", txt:"CESSAÇÃO TABAGISMO em asma é prioritária — paciente que continua fumando tem perda acelerada de função e refratariedade ao ICS."},
{nivel:"info", txt:"BIOLÓGICOS (omalizumabe, mepolizumabe, dupilumabe) em asma grave refratária — pneumologia especializada."},
{nivel:"info", txt:"PLANO DE AÇÃO POR ESCRITO reduz internações em 30-50%. Deve estar em mãos do paciente."},
],
fluxo:"fluxo-asma", diretriz:"GINA 2025. SBPT. Diretriz Brasileira de Asma."
},

/* ============== DPOC ============== */
{id:"dpoc", nome:"DPOC — diagnóstico e manejo GOLD 2025", sis:"resp", grav:"moderada",
cid:"J44", ciap:"R95",
sin:["DPOC","Doença pulmonar obstrutiva crônica","Enfisema","Bronquite crônica","Bombeiro","GOLD","Pulmão de fumante"],
def:"DPOC = doença pulmonar progressiva caracterizada por LIMITAÇÃO de fluxo aéreo NÃO totalmente reversível, associada à RESPOSTA INFLAMATÓRIA anormal a partículas/gases nocivos (tabagismo principalmente, biomassa, ocupacional). Tratamento atual GOLD 2025 estratifica por sintomas (mMRC, CAT) + risco de exacerbação (grupos A/B/E).",
quadro:["Tosse crônica + expectoração + DISPNEIA progressiva, em paciente >40a com história de tabagismo (>10 maços-ano)","Outros: biomassa (lenha doméstica em mulheres rurais), exposição ocupacional (poeiras, vapores)","DEFICIÊNCIA DE α-1-ANTITRIPSINA (<5%, considerar em jovens, não-fumantes, distribuição lobar inferior)","Sintomas progressivos: dispneia ao esforço → dispneia em repouso, exacerbações","⚠ DDX: asma (variável, reversível), ICC, bronquiectasia, TB sequelar"],
diag:["ESPIROMETRIA PÓS-BD — DIAGNÓSTICA: VEF1/CVF <0,70","ESTAGIAMENTO GOLD por VEF1 pós-BD: 1 leve (≥80%), 2 moderado (50-79%), 3 grave (30-49%), 4 muito grave (<30%)","GRUPOS A/B/E baseados em sintomas (mMRC, CAT) + exacerbações no último ano","mMRC: 0 (sem dispneia) a 4 (dispneia mínimo esforço)","CAT (COPD Assessment Test): 0-40"],
exames:["ESPIROMETRIA pré e pós-BD — confirma diagnóstico","RX TÓRAX: hiperinsuflação, retificação das cúpulas diafragmáticas (não diagnóstico)","TC TÓRAX: se atípico, suspeita bronquiectasia, avaliar enfisema","α-1-AT: em jovens, não-fumantes","ECG, gasometria, função renal, hemograma (excluir comorbidades)"],
rx:[
{etapa:"escala", d:"⚠ GOLD 2025 — TRATAMENTO POR GRUPO"},
{etapa:"escala", d:"⚠ GRUPO A (sintomas leves, sem/poucas exacerbações)"},
{etapa:"escala", d:"BRONCODILATADOR de longa duração — LABA ou LAMA"},
{etapa:"escala", d:"Tiotrópio 18 mcg DPI 1 inal/d (preferido em A) OU formoterol 12 mcg 12/12h"},
{etapa:"escala", d:"⚠ GRUPO B (mais sintomático, sem/poucas exacerbações)"},
{etapa:"escala", d:"LABA + LAMA — combinação dupla"},
{etapa:"escala", d:"Indacaterol/glicopirrônio 110/50 mcg 1×/d OU vilanterol/umeclidínio 25/62,5 mcg 1×/d OU formoterol/aclidínio 12/400 mcg 2×/d"},
{etapa:"escala", d:"⚠ GRUPO E (exacerbador — ≥2 moderadas/ano OU ≥1 grave que internou) — independente sintomas"},
{etapa:"escala", d:"LABA + LAMA (dupla)"},
{etapa:"escala", d:"Considerar LABA + LAMA + ICS (TRIPLA) se: eosinófilos sangue ≥300/μL OU eosinófilos 100-300 + exacerbações OU asma-DPOC sobreposta"},
{etapa:"escala", d:"Ex tripla: vilanterol/umeclidínio/fluticasona furoato 25/62,5/100 mcg 1×/d (Trelegy)"},
{etapa:"adj", d:"⚠ ICS em DPOC — INDICAÇÕES (não rotineiro)"},
{etapa:"adj", d:"Eosinófilos ≥300/μL (marcador de resposta ao ICS)"},
{etapa:"adj", d:"Exacerbações recorrentes ≥2/ano + eos ≥100"},
{etapa:"adj", d:"Asma-DPOC overlap"},
{etapa:"adj", d:"NÃO INDICAR ICS isolado em DPOC (sempre com LABA-LAMA)"},
{etapa:"adj", d:"⚠ ICS aumenta RISCO PNEUMONIA em DPOC — avaliar risco-benefício"},
{etapa:"adj", d:"⚠ SABA / SAMA — broncodilatador de RESGATE"},
{etapa:"adj", d:"Salbutamol MDI 100 mcg PRN, 1-2 puffs 4-6/d"},
{etapa:"adj", d:"Ipratrópio (Atrovent) MDI 20 mcg PRN — alternativa, especialmente em paciente com taquicardia"},
{etapa:"adj", d:"⚠ MEDIDAS NÃO-FARMACOLÓGICAS — MORE IMPORTANT THAN DRUGS"},
{etapa:"adj", d:"⚠ CESSAÇÃO TABAGISMO — ÚNICA medida que ALTERA HISTÓRIA NATURAL"},
{etapa:"adj", d:"VACINAÇÃO: influenza anual + pneumocócica (PCV13+PPV23) + COVID-19 + RSV + dTPa (uma vez)"},
{etapa:"adj", d:"REABILITAÇÃO PULMONAR — eficaz em mMRC ≥2: melhora função, qualidade de vida, reduz dispneia"},
{etapa:"adj", d:"⚠ OXIGENOTERAPIA DOMICILIAR — INDICAÇÕES"},
{etapa:"adj", d:"PaO₂ ≤55 mmHg em repouso (em ar ambiente, paciente estável)"},
{etapa:"adj", d:"OU PaO₂ 56-59 mmHg + cor pulmonale OU hematócrito >55%"},
{etapa:"adj", d:"Uso ≥15h/dia (idealmente 24h) — melhora sobrevida em hipoxemia crônica"},
{etapa:"adj", d:"⚠ NUTRIÇÃO — caquexia em DPOC avançada"},
{etapa:"adj", d:"Suporte nutricional + suplemento calórico, força muscular respiratória"},
{etapa:"adj", d:"⚠ MUCOLÍTICOS — N-ACETILCISTEÍNA 600 mg 2×/d em paciente com expectoração + exacerbações recorrentes, evidência modesta"},
{etapa:"adj", d:"⚠ MACROLÍDEO PROFILÁTICO — azitromicina 250 mg 3×/sem em paciente com exacerbações recorrentes apesar de tratamento otimizado, pneumologia especializada"},
{etapa:"alta", d:"⚠ ROFLUMILASTE (inibidor PDE4) 500 mcg 1×/d — paciente com bronquite crônica + VEF1 <50% + exacerbações recorrentes apesar de LABA-LAMA-ICS"},
{etapa:"alta", d:"⚠ ACOMPANHAMENTO REGULAR — sintomas, exacerbações, função pulmonar 1×/ano, técnica inalatória, adesão, comorbidades"},
{etapa:"alta", d:"COMORBIDADES FREQUENTES: ICC, CAD, depressão, osteoporose, sarcopenia, DM, câncer pulmão (rastrear se >50a, ≥20 maços-ano)"},
{etapa:"alta", d:"⚠ EXACERBAÇÃO: aumentar SABA/SAMA + corticoide oral (prednisona 40 mg × 5 dias) + ATB se purulência (amoxicilina+clavulanato OU azitromicina × 5-7 dias)"},
{etapa:"alta", d:"ENCAMINHAR PNEUMOLOGIA: exacerbações frequentes, suspeita asma-DPOC overlap, função muito reduzida, hipoxemia, candidato a transplante"},
],
alertas:[
{nivel:"crit", txt:"CESSAÇÃO TABAGISMO é a ÚNICA MEDIDA que altera história natural — não apenas reduz exacerbações, mas DESACELERA a perda de VEF1. Toda consulta de DPOC deve abordar tabagismo."},
{nivel:"crit", txt:"OXIGENOTERAPIA DOMICILIAR (≥15h/d): aumenta SOBREVIDA em hipoxemia crônica. Critérios estritos — PaO₂ ≤55 ou ≤59 + complicação."},
{nivel:"warn", txt:"⚠ ICS em DPOC NÃO É ROTINEIRO — apenas em paciente com eosinófilos altos, exacerbações recorrentes ou ACO. ICS isolado SEM LABA-LAMA é ERRO."},
{nivel:"warn", txt:"⚠ ICS aumenta RISCO PNEUMONIA em DPOC. Avaliar risco-benefício."},
{nivel:"warn", txt:"⚠ BRONCODILATADORES de LONGA são PILAR — SABA isolado NÃO basta em DPOC sintomática. Iniciar LABA ou LAMA precocemente."},
{nivel:"warn", txt:"DEFICIÊNCIA α-1-AT: pensar em DPOC em JOVEM, NÃO-FUMANTE, com distribuição enfisematosa basal. Dosar α-1-AT sérica."},
{nivel:"info", txt:"REABILITAÇÃO PULMONAR (exercício + educação + nutrição) é altamente eficaz mas SUBUTILIZADA. Reduz dispneia, aumenta tolerância, reduz exacerbações."},
{nivel:"info", txt:"RASTREAR CÂNCER DE PULMÃO em fumante 50-80a com ≥20 maços-ano: TC tórax baixa dose anual (USPSTF)."},
],
fluxo:null, diretriz:"GOLD 2025. SBPT. Diretriz Brasileira DPOC."
},

);
