/* PARTE 4: Peçonhentos + Hemocomponentes + Vasoativas + IOT + Gestantes */
PATOLOGIAS.push(
/* ============== PEÇONHENTOS ============== */
{id:"mordedura", sis:"pec", grav:"media",
nome:"Mordedura Humana / Animal",
sin:["mordedura","cão","gato","raiva"],
def:"Ferida por mordida. Risco infeccioso alto (humana 25%, cão 15%, gato 50%). Risco de raiva em mamíferos silvestres/desconhecidos.",
exames:["RX se trauma profundo","Cultura se infectada"],
rx:[
{etapa:"inicial", d:"Lavagem abundante",do:"Água + sabão por 15 min",via:"—",o:"PILAR. NÃO suturar primária (exceto face)."},
{etapa:"atb", d:"Amoxicilina-clavulanato",do:"875/125 mg VO 12/12h × 5–7 dias",via:"VO",o:"Profilaxia: face, mão, articulação, imunossupressão, diabético, todas as humanas e felinas."},
{etapa:"atb", d:"Ampicilina-sulbactam",do:"1,5 g IV 6/6h",via:"IV",o:"Internado/sepse."},
{etapa:"escala", d:"Antitetânica",do:"dT + IGHAT conforme status",via:"IM",o:"Esquema MS."},
{etapa:"escala", d:"Vacina antirrábica",do:"PEP — esquema MS",via:"IM",o:"Sempre que indicado (animal silvestre, suspeito, ataque não provocado)."},
{etapa:"escala", d:"Imunoglobulina antirrábica humana (IGAH)",do:"20 UI/kg IM, infiltrar na ferida",via:"IM",o:"Acidentes graves + 1ª dose de vacina."},
],
alertas:[{t:"crit",x:"Raiva tem letalidade ~100%. Profilaxia pós-exposição (PEP) é a ÚNICA prevenção. Decisão pelo MS — animal silvestre = SEMPRE PEP."}],
fisio:"Flora da boca: Pasteurella (cão/gato), S. aureus, Streptococcus, anaeróbios. Trauma + corpo estranho = alto risco de infecção.",
mec:[],
diretriz:"MS — Norma Técnica Profilaxia da Raiva Humana 2022.",
calcs:[],
},
{id:"botropico", sis:"pec", grav:"alta",
nome:"Acidente Botrópico (Jararaca)",
sin:["jararaca","botrópico","Bothrops"],
def:"Acidente mais comum no Brasil. Veneno proteolítico/coagulante/hemorrágico — dor, edema, equimose, sangramento sistêmico, coagulopatia.",
exames:["Tempo de coagulação (TC) — alterado em coagulopatia","Hemograma, função renal, CK","RX local"],
rx:[
{etapa:"escala", d:"SAB (Soro Antibotrópico)",do:"LEVE: 2–4 ampolas IV / MODERADO: 4–8 / GRAVE: 12 ampolas",via:"IV",o:"Diluir em 250 mL SF, infundir em 30 min. NÃO administrar pré-medicação rotineira."},
{etapa:"escala", d:"Hidratação",do:"SF 1–2 mL/kg/h",via:"IV",o:"Manter diurese >1 mL/kg/h — prevenir IRA."},
{etapa:"adj", d:"Analgesia",do:"Dipirona + opioide",via:"IV",o:"NÃO usar AINE (sangramento) nem corticoide rotineiro."},
{etapa:"escala", d:"Antitetânica",do:"dT/IGHAT",via:"IM",o:"Após correção do TC."},
{etapa:"escala", d:"ATB",do:"Amox-clav OU clinda + cefalosporina",via:"IV/VO",o:"Apenas se infecção secundária — não profilático."},
],
alertas:[
{t:"crit",x:"Reação anafilática ao soro: parar infusão + adrenalina IM + corticoide + anti-H1. Reiniciar mais lento."},
{t:"warn",x:"Se TC ainda alterado em 24h após soro: dose adicional."},
],
fisio:"Veneno do gênero Bothrops com toxinas proteolíticas (necrose local), coagulantes (consumo de fibrinogênio → CIVD), hemorrágicas (hemorraginas — lesão endotelial).",
mec:[{d:"SAB",x:"Imunoglobulinas heterólogas que neutralizam toxinas circulantes. Não reverte dano já estabelecido."}],
diretriz:"MS/Butantan — Manual de Diagnóstico e Tratamento de Acidentes por Animais Peçonhentos 2001 (reimpressão 2017).",
calcs:[],
},
{id:"crotalico", sis:"pec", grav:"alta",
nome:"Acidente Crotálico (Cascavel)",
sin:["cascavel","crotálico","Crotalus"],
def:"Veneno neurotóxico (fácies miastênica) + miotóxico (rabdomiólise → urina escura) + coagulante. MAIOR LETALIDADE entre serpentes brasileiras.",
exames:["CK (rabdomiólise — pode atingir >100.000)","Função renal","Eletrólitos (hipercalemia)","Urina (mioglobinúria)","TC","Hemograma"],
rx:[
{etapa:"escala", d:"SAC (Soro Anticrotálico)",do:"LEVE: 5 ampolas / MODERADO: 10 / GRAVE: 20 ampolas",via:"IV",o:"Diluir + 30 min de infusão."},
{etapa:"escala", d:"Hidratação vigorosa",do:"SF 2–3 mL/kg/h, manter diurese >1–2 mL/kg/h",via:"IV",o:"PROTEÇÃO RENAL. Alvo: urina clara."},
{etapa:"escala", d:"Bicarbonato",do:"Alvo pH urinário >6,5",via:"IV",o:"Alcalinização para prevenir nefrotoxicidade da mioglobina."},
{etapa:"escala", d:"Manitol",do:"0,5 g/kg IV",via:"IV",o:"Em rabdomiólise grave (CK >5000)."},
{etapa:"escala", d:"Diálise",do:"—",via:"—",o:"IRA estabelecida."},
],
alertas:[{t:"crit",x:"Insuficiência respiratória por bloqueio neuromuscular → IOT precoce."}],
fisio:"Veneno do gênero Crotalus contém crotoxina (neurotoxina pré-sináptica — bloqueia liberação de ACh), giroxina (coagulante) e fração nefrotóxica.",
mec:[{d:"SAC",x:"Neutraliza crotoxina e demais frações."}],
diretriz:"MS/Butantan 2001 (2017).",
calcs:[],
},
{id:"elapidico", sis:"pec", grav:"alta",
nome:"Acidente Elapídico (Coral Verdadeira)",
sin:["coral","elapídico","Micrurus"],
def:"Coral verdadeira (Micrurus). Veneno neurotóxico pós-sináptico → paralisia flácida ascendente progressiva → IR respiratória.",
exames:["Clínico — sintomas neurológicos","Gasometria"],
rx:[
{etapa:"escala", d:"SAE (Soro Antielapídico)",do:"10 ampolas IV (dose única para todos)",via:"IV",o:"TODOS sintomáticos = grave."},
{etapa:"escala", d:"IOT preventiva",do:"Considerar mesmo com déficit leve",via:"—",o:"Progressão rápida da paralisia."},
{etapa:"escala", d:"Suporte ventilatório",do:"VM",via:"—",o:"Pode durar dias até regeneração de receptores."},
{etapa:"escala", d:"Neostigmina",do:"0,05 mg/kg IV + atropina 0,01 mg/kg",via:"IV",o:"Útil em coral norte-americana e algumas brasileiras (M. corallinus)."},
],
alertas:[{t:"crit",x:"Risco de PCR por paralisia diafragmática. Internar em UTI imediatamente."}],
fisio:"α-neurotoxinas se ligam aos receptores nicotínicos da placa motora (pós-sinápticos) → bloqueio competitivo → paralisia flácida ascendente.",
mec:[
{d:"SAE",x:"Anticorpos heterólogos que neutralizam as toxinas circulantes."},
{d:"Neostigmina",x:"<strong>Inibidor de acetilcolinesterase</strong> → ↑ACh disponível para competir com a toxina."},
],
diretriz:"MS/Butantan 2001 (2017).",
calcs:[],
},
{id:"laquetico", sis:"pec", grav:"alta",
nome:"Acidente Laquético (Surucucu)",
sin:["surucucu","laquético","Lachesis"],
def:"Lachesis muta — Amazônia/Mata Atlântica. Síndrome botrópica + componente vagal (bradicardia, hipotensão, diarreia, cólica).",
exames:["Como botrópico","ECG (bradicardia)"],
rx:[
{etapa:"escala", d:"SABL (Soro Antibotrópico-Laquético)",do:"MODERADO: 10 ampolas / GRAVE: 20 ampolas",via:"IV",o:"Diluir + 30 min de infusão."},
{etapa:"escala", d:"Atropina",do:"0,5–1 mg IV",via:"IV",o:"Para bradicardia/síndrome vagal."},
{etapa:"adj", d:"Hidratação + analgesia",do:"Como botrópico",via:"IV",o:""},
],
alertas:[{t:"warn",x:"Síndrome vagal pode mascarar gravidade — vigilância contínua."}],
fisio:"Veneno com efeitos botrópicos + neurotoxina vagal (bradicardia, hipotensão, hipersecreção).",
mec:[],
diretriz:"MS/Butantan 2001 (2017).",
calcs:[],
},
{id:"escorpionismo", sis:"pec", grav:"alta",
nome:"Escorpionismo",
sin:["escorpião","Tityus","escorpionismo"],
def:"Picada de escorpião amarelo (T. serrulatus) ou marrom (T. bahiensis). Dor INTENSA local. Crianças/idosos: risco de complicação cardiovascular/pulmonar grave.",
exames:["ECG (taquicardia, arritmia, alterações de repolarização)","Glicemia, eletrólitos (K, Mg, Ca)","CK-MB, troponina","RX/ecocardiograma se grave","Amilase (pancreatite)"],
rx:[
{etapa:"escala", d:"SAEEsc (Soro Antiescorpiônico)",do:"MODERADO: 2–3 ampolas / GRAVE: 4–6 ampolas",via:"IV",o:"Diluir + 30 min infusão. Em adulto picado moderado: pode dispensar soro."},
{etapa:"adj", d:"Analgesia",do:"Dipirona + opioide (morfina/tramadol) + lidocaína 1% infiltração local",via:"IV/Local",o:"Dor pode ser extrema."},
{etapa:"adj", d:"Antieméticos",do:"Ondansetrona 4–8 mg IV",via:"IV",o:"Vômitos são comuns."},
{etapa:"escala", d:"Suporte cardiovascular",do:"Diurético, vasodilatador, IOT, vasopressor conforme caso",via:"IV",o:"Edema pulmonar/miocardite — UTI."},
],
alertas:[{t:"crit",x:"CRIANÇA <7a com picada de T. serrulatus = sempre grave até prova contrária. Vigilância em UTI."}],
fisio:"Toxinas de Tityus abrem canais de Na⁺ voltagem-dependentes → liberação maciça de catecolaminas e ACh → tempestade autonômica. Em crianças predomina simpático → edema pulmonar, miocardite, choque.",
mec:[{d:"SAEEsc",x:"Neutraliza toxinas Ts1, Ts2, etc."}],
diretriz:"MS/Butantan 2001 (2017).",
calcs:[],
},
{id:"araneismo", sis:"pec", grav:"media",
nome:"Araneísmo",
sin:["aranha","Loxosceles","Phoneutria","viúva-negra"],
def:"Picada de aranha. 3 gêneros relevantes no Brasil: <strong>Loxosceles</strong> (marrom — necrose), <strong>Phoneutria</strong> (armadeira — dor intensa), <strong>Latrodectus</strong> (viúva-negra — síndrome muscular).",
exames:["Hemograma, função renal, urina (hemólise em Loxosceles cutâneo-visceral)","CK"],
rx:[
{etapa:"escala", d:"LOXOSCELES — SAAr (Soro Antiaracnídico)",do:"MODERADO/GRAVE: 5–10 ampolas IV",via:"IV",o:"Indicação: forma cutâneo-visceral (hemólise, IRA) OU lesão extensa. Eficácia incerta em forma cutânea pura."},
{etapa:"escala", d:"LOXOSCELES — Prednisona",do:"40–60 mg/d × 5 dias",via:"VO",o:"Forma cutânea."},
{etapa:"adj", d:"PHONEUTRIA — SAAr",do:"MODERADO: 2–4 / GRAVE: 5–10 ampolas",via:"IV",o:"Adultos com manifestação local apenas: analgesia geralmente suficiente."},
{etapa:"adj", d:"PHONEUTRIA — Analgesia",do:"Bloqueio com lidocaína 1% + dipirona + opioide",via:"Local/IV",o:"Dor extrema."},
{etapa:"escala", d:"LATRODECTUS — Soro antilatrodéctico",do:"1–2 ampolas IM",via:"IM",o:"Forma moderada/grave (cãibras generalizadas, abdome em tábua)."},
{etapa:"escala", d:"LATRODECTUS — Gluconato Ca + BZD",do:"10 mL IV + diazepam 10 mg",via:"IV",o:"Espasmos."},
],
alertas:[{t:"warn",x:"Loxosceles cutâneo-visceral (mais em crianças): hemólise + IRA → mortalidade significativa. Vigiar urina e Hb."}],
fisio:"Loxosceles: esfingomielinase D → dermonecrose + hemólise. Phoneutria: toxinas neurotóxicas em canais de Na/Ca → liberação massiva de neurotransmissores → dor intensa. Latrodectus: α-latrotoxina → liberação maciça de ACh.",
mec:[],
diretriz:"MS/Butantan 2001 (2017).",
calcs:[],
},

/* ============== HEMATOLOGIA ============== */
{id:"anemia", sis:"hemo", grav:"media",
nome:"Anemia Ferropriva",
sin:["anemia","ferropriva","ferro"],
def:"Hb <12 (mulher) ou <13 (homem) com VCM <80 + ferritina <30. Causa: perda crônica, ↓ingesta, má absorção, gestação.",
exames:["Hemograma","Ferro sérico, ferritina, sat transferrina","Investigar fonte (TGI em adulto + EDA/colono se ferritina <100 sem causa óbvia)"],
rx:[
{etapa:"inicial", d:"Sulfato ferroso",do:"40–60 mg de Fe elementar 2–3×/d",via:"VO",o:"1 cp = 40 mg Fe elementar. Jejum + suco cítrico (↑absorção). Manter 3–6 meses APÓS Hb normalizar."},
{etapa:"escala", d:"Ferro IV (carboximaltose férrica)",do:"15 mg/kg (máx 1000 mg) em dose única em SF 250 mL em 30 min",via:"IV",o:"Indicações: intolerância VO, perda contínua, IRC, gestação 2º/3º trim, pré-operatório."},
{etapa:"escala", d:"Hidróxido férrico sacarose",do:"200 mg IV 2–3×/sem × 5 doses",via:"IV",o:"Alternativa. Menor dose por aplicação."},
{etapa:"escala", d:"Transfusão de CH",do:"Hb <7 com sintomas; Hb <8 com cardiopatia",via:"IV",o:"Anemia muito grave/sintomática."},
],
alertas:[{t:"warn",x:"Em homem >40 ou pós-menopausa: SEMPRE investigar perda TGI (CCR)."}],
fisio:"Deficit de ferro → ↓síntese de heme → eritropoese ineficaz → eritrócitos hipocrômicos microcíticos.",
mec:[{d:"Sulfato ferroso",x:"Fe²⁺ é absorvido no duodeno via DMT1 (transportador de metal divalente). Carregado pela ferroportina, transportado pela transferrina."}],
diretriz:"WHO; BCSH 2021.",
calcs:[],
},
{id:"hemocomp-ch", sis:"hemo", grav:"media",
nome:"Concentrado de Hemácias (CH)",
sin:["CH","transfusão","hemácias"],
def:"Volume 250–300 mL. 1 UI eleva Hb ~1 g/dL e Ht ~3% em adulto médio. Pediatria: 10–15 mL/kg.",
exames:["Tipo + Coombs","Reserva sanguínea","Hemograma de controle"],
rx:[
{etapa:"escala", d:"Indicação",do:"Hb <7 (geral); <8 cardiopata/idoso/oncologia; <10 isquemia ativa/hipoxemia",via:"—",o:"Estratégia RESTRITIVA é superior à liberal (TRICC, FOCUS)."},
{etapa:"escala", d:"Velocidade",do:"≤2h por unidade (4h se idoso/IC)",via:"IV",o:"Premedicação com hidrocortisona/anti-H1 não rotineira."},
{etapa:"escala", d:"Choque hipovolêmico",do:"Transfusão maciça 1:1:1 (CH:plasma:plaq)",via:"IV",o:"+ ácido tranexâmico 1 g IV."},
],
alertas:[{t:"warn",x:"Reações: febril não-hemolítica, alérgica, TRALI, sobrecarga (TACO), hemolítica aguda — interromper, suporte."}],
fisio:"",
mec:[],
diretriz:"MS — Guia para Uso de Hemocomponentes, 2ª ed. 2015. Hospitalar.",
calcs:[],
},
{id:"hemocomp-plaq", sis:"hemo", grav:"media",
nome:"Concentrado de Plaquetas",
sin:["plaquetas","plaquetopenia","transfusão de plaquetas"],
def:"1 UI/10 kg eleva ~5–10.000/mm³. 1 aférese ≈ 6–8 unidades randômicas.",
exames:["Hemograma"],
rx:[
{etapa:"escala", d:"Profilática",do:"<10.000 (estável); <20.000 (febre/sepse); <50.000 (procedimento); <100.000 (SNC, oftalmo)",via:"IV",o:"Em LMA/quimio."},
{etapa:"escala", d:"Terapêutica",do:"Sangramento ativo: alvo >50.000 (>100.000 SNC)",via:"IV",o:"+ correção de coagulopatia, antifibrinolítico."},
],
alertas:[{t:"warn",x:"PTT/SHU/HIT: NÃO transfundir plaquetas (perpetua trombose)."}],
fisio:"",
mec:[],
diretriz:"MS 2015.",
calcs:[],
},
{id:"hemocomp-crio", sis:"hemo", grav:"media",
nome:"Crioprecipitado",
sin:["crio","crioprecipitado","fibrinogênio"],
def:"Volume 10–15 mL/UI. 1 UI/10 kg eleva fibrinogênio ~50 mg/dL.",
exames:["Coagulograma + fibrinogênio"],
rx:[
{etapa:"escala", d:"Hipofibrinogenemia <150 mg/dL com sangramento",do:"10 UI ou 1 UI/10 kg",via:"IV",o:"CIVD, transfusão maciça, hemorragia obstétrica."},
{etapa:"escala", d:"Hemofilia A, doença von Willebrand",do:"Quando concentrado específico indisponível",via:"IV",o:"Preferir fator específico se disponível."},
],
alertas:[],
fisio:"",
mec:[],
diretriz:"MS 2015.",
calcs:[],
},
{id:"hemocomp-pfc", sis:"hemo", grav:"media",
nome:"Plasma Fresco Congelado (PFC)",
sin:["plasma","PFC"],
def:"Volume 200–250 mL. 10–15 mL/kg eleva fatores ~20–30%.",
exames:["Coagulograma (INR, aPTT)","Hemograma"],
rx:[
{etapa:"escala", d:"Coagulopatia + sangramento ativo",do:"10–15 mL/kg",via:"IV",o:"INR >1,5–2,0 com sangramento."},
{etapa:"escala", d:"Transfusão maciça",do:"1:1:1 com CH e plaquetas",via:"IV",o:""},
{etapa:"anticoag", d:"Reversão de varfarina urgente",do:"PCC (complexo protrombínico) é PREFERIDO; PFC se PCC indisponível",via:"IV",o:"+ vit K 10 mg IV."},
],
alertas:[{t:"warn",x:"NÃO usar para correção de INR sem sangramento (uso de vit K), expansão volêmica ou suporte nutricional."}],
fisio:"",
mec:[],
diretriz:"MS 2015; AABB 2024.",
calcs:[],
},

/* ============== VASOATIVAS ============== */
{id:"vaso-ne", sis:"vaso", grav:"alta",
nome:"Noradrenalina (NE)",
sin:["noradrenalina","norepinefrina","NE","vasopressor"],
def:"Vasopressor de 1ª LINHA em choque distributivo (séptico, anafilático refratário, neurogênico).",
exames:[],
rx:[
{etapa:"escala", d:"Diluição padrão",do:"16 mg em 250 mL SG 5% = 64 mcg/mL OU 4 mg em 250 mL = 16 mcg/mL",via:"IV BIC",o:"Sempre via central preferencial (curto prazo via periférica é aceitável)."},
{etapa:"escala", d:"Dose",do:"0,05–2 mcg/kg/min — iniciar 0,1 mcg/kg/min",via:"IV",o:"Titular para PAM ≥65 mmHg."},
{etapa:"escala", d:"Cálculo (70 kg)",do:"0,1 mcg/kg/min = 7 mcg/min = 6,6 mL/h (16 mcg/mL)",via:"—",o:""},
],
alertas:[{t:"warn",x:"Extravasamento: necrose tecidual. Infiltrar fentolamina 5–10 mg + 10 mL SF na área afetada."}],
fisio:"",
mec:[{d:"Noradrenalina",x:"<strong>α1-agonista potente</strong> (vasoconstrição arterial e venosa) + β1-agonista leve (inotropismo cronotropismo). Aumenta RVS e PAM mantendo débito."}],
diretriz:"SSC 2021.",
calcs:[],
},
{id:"vaso-dobuta", sis:"vaso", grav:"alta",
nome:"Dobutamina",
sin:["dobutamina","inotrópico"],
def:"Inotrópico em choque cardiogênico ou disfunção miocárdica com baixo débito.",
exames:[],
rx:[
{etapa:"escala", d:"Diluição",do:"250 mg em 250 mL SG 5% = 1 mg/mL",via:"IV BIC",o:"Pode periférico."},
{etapa:"escala", d:"Dose",do:"2,5–20 mcg/kg/min — iniciar 5 mcg/kg/min",via:"IV",o:"Titular pelo débito/perfusão."},
{etapa:"escala", d:"Cálculo (70 kg)",do:"5 mcg/kg/min = 21 mL/h",via:"—",o:""},
],
alertas:[{t:"warn",x:"Risco de taquiarritmia. Evitar em choque hipovolêmico não corrigido (pode piorar hipotensão por vasodilatação β2)."}],
fisio:"",
mec:[{d:"Dobutamina",x:"<strong>β1-agonista seletivo</strong> (inotropismo) + β2 leve (vasodilatação). ↑Débito sem ↑↑RVS — bom em IC."}],
diretriz:"ESC HF 2021.",
calcs:[],
},
{id:"vaso-adre", sis:"vaso", grav:"alta",
nome:"Adrenalina (Epinefrina) — Uso Crítico",
sin:["adrenalina","epinefrina"],
def:"Anafilaxia, PCR, choque refratário.",
exames:[],
rx:[
{etapa:"escala", d:"PCR (FV/TV s/p, AESP/assistolia)",do:"1 mg IV/IO em bolus a cada 3–5 min",via:"IV/IO",o:"Diluído 1:10.000 (10 mL)."},
{etapa:"escala", d:"Anafilaxia",do:"0,3–0,5 mg IM 1:1000 (0,3–0,5 mL)",via:"IM",o:"Coxa anterolateral. Repetir 5–15 min."},
{etapa:"escala", d:"Choque refratário em BIC",do:"0,05–2 mcg/kg/min",via:"IV",o:"4 mg em 250 mL SG = 16 mcg/mL."},
],
alertas:[{t:"crit",x:"Em anafilaxia, atraso na adrenalina IM é principal fator associado a morte."}],
fisio:"",
mec:[{d:"Adrenalina",x:"Agonista α1 + α2 + β1 + β2. Cobre todos os mecanismos da anafilaxia (broncodilatação, vasoconstrição, inotropismo)."}],
diretriz:"WAO 2020; ACLS 2020.",
calcs:[],
},
{id:"vaso-vp", sis:"vaso", grav:"alta",
nome:"Vasopressina",
sin:["vasopressina","ADH","V1"],
def:"Vasopressor adjuvante em choque séptico refratário.",
exames:[],
rx:[
{etapa:"escala", d:"Dose fixa",do:"0,03 U/min IV em BIC",via:"IV",o:"NÃO titular. Adicionar quando NE >0,25–0,5 mcg/kg/min para reduzir dose de NE."},
{etapa:"escala", d:"Diluição",do:"20 UI em 100 mL SG 5% = 0,2 UI/mL",via:"—",o:"0,03 UI/min = 9 mL/h."},
],
alertas:[{t:"warn",x:"Risco de isquemia digital/mesentérica em doses altas — manter ≤0,04 U/min."}],
fisio:"",
mec:[{d:"Vasopressina",x:"Agonista <strong>V1 vascular</strong> — vasoconstrição não-catecolaminérgica (útil em deficiência relativa na sepse). Também V2 renal (antidiurético)."}],
diretriz:"SSC 2021.",
calcs:[],
},
{id:"vaso-dopa", sis:"vaso", grav:"alta",
nome:"Dopamina",
sin:["dopamina"],
def:"Vasopressor/inotrópico dose-dependente. CAIU EM DESUSO em sepse (substituído por NE — SOAP-II).",
exames:[],
rx:[
{etapa:"escala", d:"Diluição",do:"200 mg em 250 mL SG = 800 mcg/mL",via:"IV BIC",o:"Central preferível."},
{etapa:"escala", d:"Dose dopaminérgica",do:"1–3 mcg/kg/min",via:"IV",o:"\"Dose renal\" — sem benefício clínico comprovado."},
{etapa:"escala", d:"Dose β1",do:"3–10 mcg/kg/min",via:"IV",o:"Inotropismo."},
{etapa:"escala", d:"Dose α",do:">10 mcg/kg/min",via:"IV",o:"Vasoconstrição."},
],
alertas:[{t:"warn",x:"Maior taxa de arritmia comparada a NE — preferir NE em sepse."}],
fisio:"",
mec:[{d:"Dopamina",x:"Precursor de NE. Em doses baixas predomina ação D1 (vasodilatação renal/mesentérica); doses médias β1; altas α1."}],
diretriz:"SSC 2021; SOAP-II (De Backer D, NEJM 2010).",
calcs:[],
},

/* ============== IOT ============== */
{id:"sri", sis:"iot", grav:"alta",
nome:"Sequência Rápida de Intubação (SRI)",
sin:["SRI","IOT","intubação","laringoscopia"],
def:"Indução farmacológica rápida com sedação + bloqueio neuromuscular para IOT em paciente crítico.",
exames:["Avaliação prévia (LEMON, MOANS, RODS)","Monitor + acesso IV"],
rx:[
{etapa:"inicial", d:"PRÉ-OXIGENAÇÃO",do:"O2 100% 3–5 min ou 8 capacidades vitais",via:"Máscara",o:"Maximiza SpO2 + reserva de O2 alveolar."},
{etapa:"escala", d:"INDUÇÃO — Etomidato",do:"0,3 mg/kg IV",via:"IV",o:"Estabilidade hemodinâmica. Risco de supressão adrenal."},
{etapa:"adj", d:"INDUÇÃO — Cetamina/Escetamina",do:"1–2 mg/kg IV (0,5–1 mg/kg escet)",via:"IV",o:"Broncodilatador, preserva PA. Útil em sepse, asma, trauma."},
{etapa:"escala", d:"INDUÇÃO — Propofol",do:"1,5–2,5 mg/kg IV",via:"IV",o:"Anticonvulsivante; cardiodepressor — evitar em choque."},
{etapa:"escala", d:"INDUÇÃO — Midazolam",do:"0,1–0,3 mg/kg IV",via:"IV",o:"Cardiodepressor; usar em sangramento/sepse com cetamina."},
{etapa:"escala", d:"BNM — Succinilcolina",do:"1–1,5 mg/kg IV",via:"IV",o:"Início 45–60s, dura 5–10min. CI: hipercalemia, queimadura >48h, lesão muscular extensa, hipertermia maligna, ocular aberta."},
{etapa:"escala", d:"BNM — Rocurônio",do:"1,2 mg/kg IV",via:"IV",o:"Início 60s, dura 30–60min. Reversão: sugamadex 16 mg/kg."},
{etapa:"adj", d:"PÓS — Sedação + Analgesia",do:"Fentanil + propofol/midaz",via:"IV BIC",o:"Não esquecer — pacientes paralisados sem sedação sofrem."},
],
alertas:[
{t:"crit",x:"\"NO DESAT\" — Nasal O2 Durante Tentativas (cânula nasal 15 L/min) reduz hipoxemia."},
{t:"warn",x:"7 P's: Preparação, Pré-oxigenação, Pré-medicação, Paralisia + indução, Posicionamento, Passar tubo + confirmar, Pós-cuidados."},
],
fisio:"",
mec:[
{d:"Etomidato",x:"Modula GABA-A — sedação sem alteração hemodinâmica."},
{d:"Cetamina",x:"Antagonista NMDA — anestesia dissociativa. Preserva drive respiratório e PA."},
{d:"Succinilcolina",x:"Agonista nicotínico — despolarização persistente da placa motora → paralisia. Hidrolisada por pseudocolinesterase."},
{d:"Rocurônio",x:"Antagonista nicotínico competitivo (não-despolarizante)."},
],
diretriz:"DAS 2015 (Difficult Airway Society); ABRAMEDE.",
calcs:[],
},
{id:"sedoanalgesia", sis:"iot", grav:"alta",
nome:"Sedoanalgesia em VM",
sin:["sedação","analgesia","sedoanalgesia","BIC"],
def:"Sedoanalgesia pós-IOT para tolerância à VM. Estratégia: analgesia first, sedação leve (RASS 0 a -2), interrupção diária.",
exames:["RASS, CPOT/BPS"],
rx:[
{etapa:"escala", d:"Fentanil",do:"0,5–2 mcg/kg/h BIC",via:"IV",o:"Analgésico opioide preferido em UTI."},
{etapa:"escala", d:"Propofol",do:"5–50 mcg/kg/min",via:"IV",o:"Sedativo de escolha — meia-vida curta, fácil titulação. Cuidado: \"propofol-related infusion syndrome\" em >4 mg/kg/h por >48h."},
{etapa:"escala", d:"Midazolam",do:"0,02–0,1 mg/kg/h",via:"IV",o:"BZD. Acumula em uso prolongado/IRC/hepatopata."},
{etapa:"escala", d:"Cetamina",do:"0,5–2 mg/kg/h",via:"IV",o:"Adjuvante em casos selecionados (asma grave, broncoespasmo, sepse com instabilidade)."},
{etapa:"escala", d:"Dexmedetomidina",do:"0,2–1,4 mcg/kg/h",via:"IV",o:"α2-agonista — sedação leve com preservação de drive respiratório. Útil para desmame."},
],
alertas:[
{t:"warn",x:"Sedação profunda contínua piora desfechos. RASS alvo 0 a -2 sempre que possível."},
{t:"info",x:"\"Sedation vacation\" diário (interrupção até paciente abrir olhos) reduz dias de VM e UTI."},
],
fisio:"",
mec:[{d:"Dexmedetomidina",x:"<strong>α2-agonista</strong> central — inibe liberação de NE no locus coeruleus. Sedação sem depressão respiratória."}],
diretriz:"PADIS Guidelines 2018 (Devlin JW et al., Crit Care Med 2018;46:e825–e873).",
calcs:[],
},

/* ============== GESTANTES ============== */
{id:"gest-antiemetico", sis:"gest", grav:"baixa",
nome:"Antieméticos em Gestantes",
sin:["náusea gestação","hiperêmese","gestante vômito"],
def:"Náuseas/vômitos da gestação (NVG) — 70–80% no 1º trimestre. Hiperêmese: perda peso >5%, cetose, distúrbio hidroeletrolítico.",
exames:["β-HCG quantitativo","Função hepática/renal/eletrólitos","TSH, EAS","USG (excluir doença trofoblástica)"],
rx:[
{etapa:"escala", d:"Piridoxina (B6)",do:"10–25 mg VO 8/8h",via:"VO",o:"1ª linha. Pode associar doxilamina."},
{etapa:"escala", d:"Meclozina",do:"25 mg VO 8/8h",via:"VO",o:"Cat B — antagonista H1 + anticolinérgico."},
{etapa:"escala", d:"Dimenidrato",do:"50 mg VO/IM 6/6h",via:"VO/IM",o:"Cat B."},
{etapa:"adj", d:"Metoclopramida",do:"10 mg VO/IV 8/8h",via:"VO/IV",o:"Cat B. Cuidado distonia."},
{etapa:"adj", d:"Ondansetrona",do:"4–8 mg VO/IV 8/8h",via:"VO/IV",o:"Evitar nas primeiras 10 sem (controvérsia fenda palatina). Após 1º trim: seguro."},
{etapa:"escala", d:"Hidratação IV",do:"SF + glicose + reposição K + tiamina",via:"IV",o:"Hiperêmese — internação."},
{etapa:"adj", d:"Tiamina",do:"100 mg IV/d × 3 dias",via:"IV",o:"Prevenir Wernicke (relatos em hiperêmese)."},
],
alertas:[{t:"info",x:"NVG geralmente regride a partir da 16ª semana. Encaminhar pré-natal."}],
fisio:"",
mec:[],
diretriz:"FEBRASGO; ACOG 2018.",
calcs:[],
},
{id:"gest-dor", sis:"gest", grav:"baixa",
nome:"Dor em Gestante",
sin:["dor gestação","analgesia gestante"],
def:"Manejo da dor respeitando categorias FDA (A/B/C/D/X).",
exames:["Individualizar pela causa"],
rx:[
{etapa:"escala", d:"Paracetamol",do:"500–1000 mg 6/6h (máx 4 g/d)",via:"VO/IV",o:"1ª linha. Cat B. Evitar uso prolongado em altas doses."},
{etapa:"escala", d:"Dipirona",do:"500–1000 mg 6/6h",via:"VO/IV",o:"Cat C — uso restrito; preferir 2º trim. Aceito em PS."},
{etapa:"escala", d:"AINE (ibuprofeno, cetoprofeno)",do:"Curto prazo no 1º/2º trim",via:"VO",o:"CONTRAINDICADO no 3º trim (fechamento ducto arterioso, oligohidrâmnio)."},
{etapa:"escala", d:"Morfina",do:"Conforme dor",via:"IV/SC",o:"Cat C — uso em dor grave. Risco de depressão respiratória neonatal próximo ao parto."},
{etapa:"escala", d:"Tramadol",do:"50–100 mg 6/6h",via:"VO/IV",o:"Cat C. Cautela."},
],
alertas:[{t:"crit",x:"AINE são CONTRAINDICADOS no 3º trimestre. Preferir paracetamol."}],
fisio:"",
mec:[],
diretriz:"FEBRASGO; ACOG.",
calcs:[],
},
{id:"gest-enxaqueca", sis:"gest", grav:"baixa",
nome:"Enxaqueca em Gestante",
sin:["enxaqueca gestação","migrânea gestante"],
def:"Crise migranosa em gestante.",
exames:["Excluir pré-eclâmpsia (sempre PA + EAS)"],
rx:[
{etapa:"escala", d:"Paracetamol ± Cafeína",do:"500–1000 mg + 65 mg cafeína",via:"VO",o:"1ª linha."},
{etapa:"adj", d:"Metoclopramida",do:"10 mg IV",via:"IV",o:"Antiemético + ação antimigranosa."},
{etapa:"escala", d:"Dipirona",do:"1 g IV (preferível 2º trim)",via:"IV",o:"Alternativa."},
{etapa:"escala", d:"Sumatriptano",do:"50 mg VO em casos selecionados",via:"VO",o:"Categoria C — usar com hierarquia (paracetamol primeiro). Evidência crescente de segurança."},
],
alertas:[
{t:"crit",x:"Sempre verificar PA + EAS — pré-eclâmpsia/eclâmpsia pode mimetizar enxaqueca!"},
{t:"warn",x:"NÃO usar ergotamínicos (CI absoluta em gestação)."},
],
fisio:"",
mec:[],
diretriz:"Sociedade Brasileira de Cefaleia.",
calcs:[],
},
{id:"gest-candidiase", sis:"gest", grav:"baixa",
nome:"Candidíase em Gestante",
sin:["candidíase gestação"],
def:"Candidíase vulvovaginal em gestante. Comum (até 40%).",
exames:["Especular + pH + microscopia"],
rx:[
{etapa:"escala", d:"Clotrimazol creme 1%",do:"Aplicador vaginal 1×/d × 7–14 dias",via:"Vaginal",o:"Cat B. 1ª linha em qualquer trimestre."},
{etapa:"escala", d:"Miconazol creme 2%",do:"Aplicador 1×/d × 7 dias",via:"Vaginal",o:"Alternativa."},
{etapa:"escala", d:"Nistatina vaginal",do:"100.000 UI/g × 14 dias",via:"Vaginal",o:"Cat B."},
],
alertas:[
{t:"crit",x:"NÃO usar fluconazol VO em gestante (cat D em altas doses — risco de malformação)."},
{t:"info",x:"Tratar SEMPRE em gestante (mesmo assintomática se cultura+) — risco de transmissão vertical (candidíase neonatal)."},
],
fisio:"",
mec:[],
diretriz:"FEBRASGO 2024.",
calcs:[],
},
);
/* PARTE 4 COMPLETA — TOTAL 80+ patologias */
