/* ===========================================================
   VOVÔMINIC EMERGÊNCIA — DADOS CLÍNICOS PARTE 6
   Tier 1 parte 2: Neuro extras + Trauma + outras críticas
   =========================================================== */

PATOLOGIAS.push(

/* ============== NEURO EXTRAS ============== */
{id:"hsa", sis:"neuro", grav:"alta",
nome:"Hemorragia Subaracnoide (HSA)",
sin:["HSA","hemorragia subaracnoide","aneurisma roto","trovão"],
def:"Sangramento no espaço subaracnoide — cefaleia 'trovão' (worst headache of life), súbita, máxima intensidade <1 min, ± LOC, ± rigidez nucal, ± déficit focal. Escalas: Hunt-Hess (clínica) e Fisher (radiológica).",
exames:["TC crânio sem contraste (95% sensibilidade nas 1ª 6h)","Punção lombar se TC normal + clínica forte (xantocromia)","Angio-TC ou angio-RM cerebral (procurar aneurisma)","ECG (anormal em 50% — taqui, alt repolarização, prolongamento QT)","Hemograma, eletrólitos","Coagulograma"],
rx:[
{etapa:"inicial", d:"Repouso + cabeceira 30°",do:"Ambiente calmo, monitorizado",via:"—",o:"Reduz pico hipertensivo. Profilaxia de TVP MECÂNICA (sem heparina até clipagem)."},
{etapa:"escala", d:"Nimodipino",do:"60 mg VO 4/4h × 21 dias",via:"VO",o:"INICIAR <96h da hemorragia. PREVINE vasoespasmo (não trata). Suspender se hipoTA."},
{etapa:"escala", d:"Controle da PA",do:"PAS <160 (alguns serviços <140) com labetalol/esmolol/nicardipino",via:"IV",o:"ATÉ a clipagem. Após clipagem, mais liberal (PAS 160-200) para HIPERTENSIVA — terapia 'Triple H' antiquada, focar em mantém PAM."},
{etapa:"adj", d:"Anticonvulsivantes",do:"Fenitoína 1 g IV de ataque OU levetiracetam 500 mg IV 12/12h",via:"IV",o:"Profilaxia 3-7 dias. Não usar de rotina (controverso); reservar para crise documentada."},
{etapa:"escala", d:"Clipagem cirúrgica / coiling endovascular",do:"—",via:"Cirúrgico/Endo",o:"DEFINITIVO. ASAP (<24-72h) — preferir coiling se anatomia favorável (ISAT trial, melhor outcome)."},
],
alertas:[
{t:"crit",x:"PIOR cefaleia da vida + súbita + qualquer LOC = HSA até prova contrária. NÃO se contentar com TC normal — fazer punção se >6h ou clínica clara."},
{t:"crit",x:"Vasoespasmo cerebral: dia 4-14 pós-HSA — déficit focal novo. TCD seriado, nimodipino, monitor neuro."},
{t:"warn",x:"Hidrocefalia aguda em até 20% — DVE se Glasgow ↓."},
{t:"warn",x:"Hunt-Hess: I (assintomático/cefaleia leve) → V (coma profundo, descerebração). Mortalidade 70% no V."},
],
fisio:"85% por ruptura de aneurisma sacular (PolIgono de Willis, comunicante anterior/posterior, ACM). Outras: MAV, trauma, dissecção. Após ruptura, sangue arterial sob pressão se dispersa no LCR → ↑↑PIC súbito → LOC e até herniação. Sequelas: ressangramento (24h crítico), vasoespasmo (D4-14), hidrocefalia, hiponatremia (SIADH/cerebral salt wasting), pneumonia, cardiomiopatia de Takotsubo neurogênica.",
mec:[
{d:"Nimodipino",x:"BCC dihidropiridínico — bloqueia canais L de Ca²⁺ no músculo liso vascular, com seletividade cerebral. <strong>Não previne nem reverte vasoespasmo radiologicamente</strong> mas reduz infarto cerebral retardado e melhora prognóstico funcional (mecanismo neuroprotetor não totalmente elucidado)."},
{d:"Ácido tranexâmico (não rotineiro)",x:"Antifibrinolítico — usado em alguns centros pré-clipagem. STASH e ULTRA trials desafiaram benefício rotineiro."},
],
diretriz:"AHA/ASA 2023 (Hoh BL et al., Stroke 2023;54:e314, DOI:10.1161/STR.0000000000000436). Neurocritical Care Society 2023. PCDT MS Brasil.",
fluxo:null,
calcs:[],
},

{id:"ait", sis:"neuro", grav:"alta",
nome:"Ataque Isquêmico Transitório (AIT)",
sin:["AIT","TIA","mini-AVC"],
def:"Déficit neurológico súbito de origem vascular com RESOLUÇÃO COMPLETA em ≤24h (geralmente <1h) e SEM evidência de infarto em imagem. Sinal de alarme — 5% terão AVC em 48h, 10% em 90 dias.",
exames:["TC crânio (sem evidência de infarto)","RM com DWI (gold standard para excluir AVC verdadeiro)","Doppler carótidas + vertebrais","ECG + Holter 24-72h (FA paroxística)","Ecocardiograma transtorácico ± transesofágico","HMG, glicemia, perfil lipídico, função renal","HbA1c"],
rx:[
{etapa:"escala", d:"AAS",do:"300 mg dose única + 75-100 mg/d",via:"VO",o:"Iniciar imediatamente após excluir hemorragia."},
{etapa:"escala", d:"DAPT (AAS + Clopidogrel)",do:"AAS 100 mg/d + Clopi 75 mg/d × 21 dias depois AAS",via:"VO",o:"ABCD² ≥4 ou AIT moderado-alto risco. CHANCE/POINT trials — reduz AVC 32%."},
{etapa:"escala", d:"Atorvastatina",do:"40-80 mg/d",via:"VO",o:"Alta intensidade — SPARCL trial. LDL alvo <70."},
{etapa:"anticoag", d:"Anticoagulação",do:"Apixabana 5 mg 12/12h (dose plena) OU varfarina INR 2-3",via:"VO",o:"SE FA presente. CHA₂DS₂-VA ≥1H ou ≥2M."},
{etapa:"escala", d:"Controle pressórico",do:"Após 24-48h, IECA/BRA + diurético tiazídico",via:"VO",o:"Meta progressiva PAS <130. PROGRESS trial."},
{etapa:"escala", d:"Endarterectomia carotídea",do:"—",via:"Cirúrgico",o:"Estenose sintomática 70-99% — em até 14 dias do evento (NASCET)."},
],
alertas:[
{t:"crit",x:"ABCD² ≥4 ou AIT recente (<48h) ou novo déficit ≥30 min → INTERNAÇÃO + investigação rápida + DAPT 21 dias."},
{t:"crit",x:"Crescendo TIAs (AITs múltiplos em curto intervalo) = pré-AVC iminente — UTI neurológica, anticoag/DAPT, imagem urgente."},
{t:"warn",x:"AIT em <55a com sopro carotídeo → considerar dissecção arterial cervical (jovem, esforço, trauma cervical leve)."},
],
fisio:"Mecanismos idênticos ao AVCi: cardioembólico (FA — origem cardíaca), aterosclerose grande vaso (placa carotídea — embolia arterio-arterial), doença de pequenos vasos (lacunar), criptogênico. A diferença com AVC é apenas que aqui o trombo se desfaz/migra antes do dano permanente. RM-DWI mostra que ~30-50% dos AITs clínicos têm pequena lesão isquêmica — alguns reclassificam.",
mec:[
{d:"Clopidogrel",x:"Tienopiridínico — pró-droga ativada pelo CYP2C19, metabólito liga-se irreversivelmente ao receptor P2Y12 plaquetário → bloqueia ativação plaquetária por ADP."},
{d:"Atorvastatina",x:"Inibidor HMG-CoA redutase — ↓síntese colesterol hepático + efeitos pleiotrópicos (estabiliza placa, ↓inflamação, melhora endotélio)."},
],
diretriz:"AHA/ASA 2021 Secondary Prevention (Kleindorfer DO et al., Stroke 2021;52:e364). ESO 2021. CHANCE/POINT trials.",
fluxo:null,
calcs:["abcd2","chads-va"],
},

{id:"encefalite", sis:"neuro", grav:"alta",
nome:"Encefalite",
sin:["encefalite","encefalite herpética","HSV"],
def:"Inflamação do parênquima cerebral — febre + alteração de consciência/cognição + sintomas focais ou crises convulsivas. Diferente de meningite por DISFUNÇÃO cerebral predominante. Mais comum: HSV-1, arbovírus, autoimune.",
exames:["TC crânio (excluir HIC, lesão expansiva)","Punção lombar com pleocitose linfocítica, proteína ↑, glicose normal","PCR para HSV no LCR (sensibilidade 96-98%)","RM crânio (lesões temporais mediais bilaterais = HSV)","EEG (descargas periódicas lateralizadas — PLEDs em HSV)","Sorologia/PCR para arbovírus, HIV, sífilis"],
rx:[
{etapa:"atb", d:"Aciclovir EMPÍRICO",do:"10 mg/kg IV 8/8h × 14-21 dias",via:"IV",o:"INICIAR EMPIRICAMENTE em qualquer encefalite, NÃO esperar PCR. Aciclovir reduz mortalidade HSV de 70% → 20%."},
{etapa:"inicial", d:"Ajuste de aciclovir",do:"Função renal: ClCr 25-50 → 10 mg/kg 12/12h; <25 → 10 mg/kg 24/24h",via:"IV",o:"Hidratação concomitante (cristaloide 1-2 L) — nefrotoxicidade."},
{etapa:"escala", d:"Anticonvulsivantes",do:"Fenitoína 20 mg/kg IV ou levetiracetam 60 mg/kg IV",via:"IV",o:"Crises são frequentes em HSV (50%). Tratar 1ª crise."},
{etapa:"escala", d:"Cobertura para meningite bacteriana",do:"Ceftriaxona 2g IV 12/12h + Vancomicina + Ampicilina",via:"IV",o:"Se LCR incerto/quadro grave/imunossuprimido — adicionar AMPI se >50a (Listeria)."},
],
alertas:[
{t:"crit",x:"ACICLOVIR ANTES DA PCR. Cada hora de atraso piora outcome. PCR pode ser negativa nas 1ª 72h — não usar resultado precoce para descontinuar."},
{t:"warn",x:"Encefalite autoimune (anti-NMDAR, anti-LGI1) — jovens, alteração comportamental, movimentos anormais, crises. Investigar se PCR negativa + RM atípica. Imunoglobulina + corticoide + plasmaférese."},
{t:"info",x:"HSV poupa lobos frontais (preferência por temporal medial bilateral assimétrica). Aspecto na RM é praticamente diagnóstico."},
],
fisio:"HSV-1 alcança SNC via nervo olfatório/trigêmeo, com tropismo pelos lobos temporais mediais. Infecção citopática → necrose hemorrágica focal → edema cerebral → ↑PIC → herniação. Sem tratamento: 70% mortalidade. Sequelas em sobreviventes mesmo tratados: déficit cognitivo/memorial (lobo temporal é hipocampo).",
mec:[
{d:"Aciclovir",x:"Análogo da guanosina — fosforilado pela <strong>timidina-quinase viral</strong> (só vírus tem essa enzima, daí seletividade); a forma trifosfato compete com dGTP pela DNA polimerase viral → terminação de cadeia."},
],
diretriz:"IDSA Encephalitis 2008 (Tunkel AR et al., Clin Infect Dis 2008;47:303). British Encephalitis Society 2012. PCDT/MS.",
fluxo:null,
calcs:[],
},

{id:"sind-serotonin", sis:"neuro", grav:"alta",
nome:"Síndrome Serotoninérgica / NMS",
sin:["síndrome serotoninérgica","NMS","síndrome neuroléptica maligna","hipertermia maligna"],
def:"Síndrome serotoninérgica: TRIÁDE = alterações mentais + autonômicas (taquicardia, HAS, hipertermia, sudorese) + neuromusculares (CLÔNUS, hiperreflexia, tremor) após inserção/aumento de droga serotoninérgica. NMS: rigidez 'cano de chumbo' + hipertermia + alteração consc + autonômico após neuroléptico (D2-antagonista).",
exames:["CPK (↑↑ ambos), mioglobina urinária","Função renal (rabdomiólise)","Hemograma, função hepática","Gaso arterial, lactato","Eletrólitos","TC crânio + LP se dúvida diagnóstica (excluir meningite)"],
rx:[
{etapa:"atb", d:"SUSPENDER agente causador",do:"Imediato",via:"—",o:"PILAR. Identificar gatilho (ISRS+IMAO+linezolida+tramadol+tryptano+ondansetron, etc.)."},
{etapa:"escala", d:"Suporte agressivo",do:"Resfriamento ativo (manta + cristaloide gelado) + monitorização + hidratação 4-6 L/d",via:"IV",o:"Hipertermia >40°C → intervenção imediata."},
{etapa:"escala", d:"Sedação BZD",do:"Diazepam 5-10 mg IV repetir ou midazolam BIC 0,05-0,2 mg/kg/h",via:"IV",o:"Reduz agitação, rigidez, autonomia. 1ª linha em ambas síndromes."},
{etapa:"escala", d:"Ciproheptadina (S. serotoninérgica)",do:"12 mg VO/SNG ataque + 2 mg 2/2h até melhora (máx 32 mg/d)",via:"VO",o:"Antagonista 5-HT2A. Reservado para casos graves/refratários."},
{etapa:"escala", d:"Bromocriptina + Dantrolene (NMS)",do:"Bromocriptina 2,5-5 mg 8/8h + Dantrolene 2,5 mg/kg IV até 10 mg/kg/d",via:"VO+IV",o:"NMS grave/refratário. Bromocriptina = agonista D2. Dantrolene reduz Ca²⁺ muscular."},
{etapa:"escala", d:"IOT + curare",do:"Bloqueio neuromuscular se rigidez ameaça hipertermia/rabdo",via:"IV",o:"NÃO usar succinilcolina em NMS (risco hipercalemia)."},
],
alertas:[
{t:"crit",x:"NMS rigidez tipo CANO DE CHUMBO (continuous), bradi-reflexia. Serotoninérgica = clônus + HIPERreflexia. Mnemonic: 'neuroléptico = NEUROlepticano' rígido; 'serotonin = SHAKES' (treme/clônus)."},
{t:"crit",x:"HIPERTERMIA >40°C + rabdomiólise + IRA + CIVD → mortalidade 10-20% se não tratada agressivamente."},
{t:"warn",x:"Drogas mais associadas: SS = ISRS+IMAO, linezolida, tramadol, MDMA, LSD. NMS = haloperidol, clorpromazina, depot, retirada abrupta de levodopa."},
],
fisio:"Serotoninérgica: excesso sináptico de 5-HT em receptores 5-HT2A/1A. Início rápido (horas após gatilho). NMS: bloqueio D2 striatal → rigidez e hipertermia central (hipotálamo). Início mais lento (dias-semanas). Ambas causam contratura muscular sustentada → calor + lactato + rabdomiólise + ↑K + acidose + IRA.",
mec:[
{d:"Ciproheptadina",x:"Anti-histamínico de 1ª geração com forte antagonismo 5-HT2A. Bloqueia ação serotoninérgica excessiva."},
{d:"Bromocriptina",x:"Agonista D2 — desbloqueia receptores dopaminérgicos centrais."},
{d:"Dantrolene",x:"Bloqueia receptor de rianodina (RyR1) no retículo sarcoplasmático → ↓liberação de Ca²⁺ → relaxa músculo esquelético sem ação central. Antídoto da hipertermia maligna anestésica também."},
],
diretriz:"Boyer EW, NEJM 2005;352:1112 (Serotonin Syndrome). Strawn JR, Am J Psychiatry 2007;164:870 (NMS).",
fluxo:null,
calcs:[],
},

/* ============== TRAUMA ============== */
{id:"tce", sis:"trauma", grav:"alta",
nome:"Trauma Cranioencefálico (TCE)",
sin:["TCE","trauma craniano","Glasgow"],
def:"Lesão craniana por mecanismo traumático. Classificar por Glasgow: LEVE 13-15 (75%), MODERADO 9-12 (15%), GRAVE 3-8 (10%). Outras escalas: AVPU, Marshall (TC).",
exames:["Glasgow seriado (cada 30-60 min)","TC crânio sem contraste — INDICAÇÕES: Canadian CT Head, New Orleans (HSA, fratura, sinais neuro)","Glicemia capilar","Hemograma, coagulograma","Função renal","Álcool/drogas se suspeita","RX coluna cervical OU mantida proteção cervical"],
rx:[
{etapa:"inicial", d:"ABCDE",do:"Vias aéreas (IOT se Glasgow ≤8) + cervical + ventilação SpO₂ >94% + circulação",via:"—",o:"PILAR. Hipotensão DOBRA mortalidade em TCE grave. Hipoxia idem."},
{etapa:"escala", d:"Cabeceira 30°",do:"Posição neutra",via:"—",o:"Reduz PIC. NÃO se trauma raquimedular instável."},
{etapa:"escala", d:"Manitol",do:"0,25-1 g/kg IV em 15-30 min",via:"IV",o:"Hipertensão intracraniana (HIC) com sinais clínicos (anisocoria, postura). Repetir 4-6h. Monitor osmolaridade <320."},
{etapa:"escala", d:"Salina hipertônica 3%",do:"250 mL IV em 10-15 min",via:"IV",o:"Alternativa ao manitol — preferida em hipotensão/euvolemia. Verificar Na sérico (alvo 145-155)."},
{etapa:"escala", d:"Anti-convulsivante profilático",do:"Levetiracetam 1 g IV ataque + 500 mg 12/12h × 7 dias",via:"IV",o:"TCE grave (Glasgow ≤8) ou contusão/hematoma — apenas 1ª semana (não previne crises tardias)."},
{etapa:"adj", d:"Reversão de anticoagulante",do:"PCC 25-50 UI/kg (varfarina); idarucizumab (dabigatran); andexanet (rivaroxabana/apixabana)",via:"IV",o:"TCE + anticoag = emergência. Reverter ANTES de cirurgia."},
{etapa:"escala", d:"Cirurgia",do:"Craniotomia evacuação OU craniectomia descompressiva",via:"Cirúrgico",o:"HSD/HED >10 mm ou desvio linha média >5 mm ou HIC refratária — chamar neurocirurgia."},
],
alertas:[
{t:"crit",x:"Canadian CT Head: TC se Glasgow <15 em 2h, suspeita fratura aberta/afundada, sinais base de crânio, ≥2 vômitos, idade ≥65a, queda >0,9 m / >5 degraus, amnésia retrógrada >30 min."},
{t:"crit",x:"Lúcido intervalo seguido de deterioração = HEMATOMA EXTRADURAL (artéria meníngea média) — emergência neurocirúrgica."},
{t:"warn",x:"IDOSO em uso de anticoagulante mesmo com TCE leve → TC. Risco de HSD evolutivo."},
{t:"warn",x:"Síndrome do BC (bebê chacoalhado): TCE pediátrico não acidental — investigar."},
],
fisio:"Lesão primária: imediata, mecânica — concussão, contusão, hematoma extradural (artéria meníngea média, fratura temporal), subdural (veias ponte, idoso/etilista, lesão por aceleração), lesão axonal difusa. Lesão secundária: subsequente, evitável — hipoxia, hipotensão, HIC, hipoglicemia, hipertermia, crises. <strong>Foco do manejo: prevenir lesão secundária</strong>. Manter PAM ≥80 (TCE grave alvo PIC <22, PPC 60-70).",
mec:[
{d:"Manitol",x:"Diurético osmótico — atrai água do parênquima cerebral para o intravascular → ↓edema cerebral + ↓PIC. Efeito reológico (↓viscosidade sangue, melhora perfusão)."},
{d:"Salina hipertônica",x:"Gradiente osmótico via BBB → desloca água do intersticial cerebral. Vantagem sobre manitol: também melhora volemia."},
],
diretriz:"Brain Trauma Foundation 4ª ed. 2017 (Carney N et al., Neurosurgery 2017;80:6). ATLS 10ª ed. Canadian CT Head Rule (Stiell IG et al., Lancet 2001;357:1391).",
fluxo:null,
calcs:[],
},

{id:"trauma-torax", sis:"trauma", grav:"alta",
nome:"Trauma de Tórax",
sin:["trauma torácico","pneumotórax hipertensivo","hemotórax","tórax instável","tamponamento traumático"],
def:"Lesão torácica por mecanismo traumático — fechado (acidente, queda) ou penetrante (PAF, FAB). Avaliar lesões que matam rapidamente: 5 RAPIDAMENTE FATAIS = obstrução VA, PNT hipertensivo, PNT aberto, tamponamento, hemotórax maciço, tórax instável.",
exames:["RX tórax inicial","FAST estendido (EFAST) — derrame pleural/pericárdico/PNT","TC tórax com contraste (estável)","ECG","Hemograma, gaso, lactato, tipagem","Troponina (contusão miocárdica)"],
rx:[
{etapa:"escala", d:"PNT HIPERTENSIVO",do:"Punção descompressiva IMEDIATA — 2º EIC linha hemiclavicular OU 5º EIC linha axilar média, cateter 14G longo",via:"—",o:"DIAGNÓSTICO CLÍNICO — NÃO esperar RX. Após, dreno torácico definitivo."},
{etapa:"escala", d:"PNT ABERTO",do:"Curativo de 3 pontos (válvula unidirecional)",via:"—",o:"Selar 3 lados do curativo → escape ar mas não entrada. Dreno torácico definitivo."},
{etapa:"escala", d:"HEMOTÓRAX MACIÇO",do:"Dreno torácico 32-36 Fr",via:"—",o:"Imediato >1500 mL ou >200 mL/h × 4h → TORACOTOMIA. Autotransfusão se disponível."},
{etapa:"escala", d:"TAMPONAMENTO",do:"Pericardiocentese subxifoide ECO-guiada + ressuscitação volêmica",via:"—",o:"Pode reverter choque temporariamente. Cirurgia definitiva (toracotomia)."},
{etapa:"escala", d:"TÓRAX INSTÁVEL",do:"O₂ + analgesia agressiva (bloqueio intercostal/peridural) + VNI/IOT se IRespA",via:"—",o:"Contusão pulmonar é o problema real. Hidratação cautelosa. Estabilização cirúrgica em casos selecionados."},
{etapa:"atb", d:"ATB Profilático",do:"Cefazolina 2g IV se trauma penetrante + dreno",via:"IV",o:"24-48h. Reduz empiema."},
],
alertas:[
{t:"crit",x:"FRATURA DE 1ª/2ª COSTELA = trauma grave — risco de lesão de aorta/grandes vasos. Investigar com angio-TC."},
{t:"crit",x:"TORACOTOMIA DE REANIMAÇÃO: indicada em FAB/PAF torácico com perda de sinais vitais NO PRONTO-SOCORRO (não em pré-hospitalar prolongado, não em trauma fechado com PCR)."},
{t:"warn",x:"Contusão miocárdica: traço suspeito + ECG anormal + ↑troponina. Geralmente conservador, monitorizar 24-48h."},
{t:"warn",x:"Lesão diafragmática esquerda em trauma penetrante baixo — pode passar despercebida e levar a hérnia/encarceramento tardio. Sempre investigar."},
],
fisio:"Trauma fechado mais comum (acidente trânsito 70%, queda 15%, queda objeto 5%). Penetrante: arma branca (mais baixa energia) ou arma de fogo (alta energia, cavitação). Tamponamento em trauma: hemorragia rápida em saco pericárdico → 150-200 mL é suficiente para fisiopatologia (vs ~1L em crônico). Hemotórax: cada hemitorax cabe 2-3L = choque hemorrágico classe III-IV.",
mec:[],
diretriz:"ATLS 10ª ed. (American College of Surgeons 2018). EAST Guidelines.",
fluxo:null,
calcs:[],
},

{id:"trauma-abd", sis:"trauma", grav:"alta",
nome:"Trauma Abdominal",
sin:["trauma abdominal","FAST","laparotomia"],
def:"Lesão abdominal por mecanismo traumático fechado ou penetrante. Trauma fechado: acidente trânsito > queda; órgãos mais lesados: baço, fígado, rim. Penetrante: indicação cirúrgica mais liberal — qualquer FAB com peritonismo, FAF abdominal.",
exames:["FAST (Focused Assessment with Sonography for Trauma) — 4 janelas","TC abdome com contraste (estável, FAST duvidoso)","DPL (lavado peritoneal diagnóstico) — caindo em desuso","Hemograma seriado","Lactato, base excess","Tipagem + prova cruzada"],
rx:[
{etapa:"escala", d:"INSTÁVEL + FAST+",do:"LAPAROTOMIA imediata",via:"Cirúrgico",o:"Sangramento intra-abdominal — não TC. Sala de cirurgia direto."},
{etapa:"escala", d:"ESTÁVEL + Trauma fechado + FAST+",do:"TC com contraste → manejo conservador se grau baixo",via:"—",o:"Trauma esplênico/hepático grau I-III estável → conservador (sucesso 80-90%). Reavaliação frequente."},
{etapa:"escala", d:"PENETRANTE ABD ANTERIOR",do:"FAB + peritonismo → laparotomia; FAB sem peritonismo + estável → exploração local da ferida",via:"—",o:"FAF abdominal: laparotomia em 95% — pode ser exploradora se via duvidosa."},
{etapa:"escala", d:"Ressuscitação balanceada",do:"Hipotensão permissiva (PAS 80-90) até controle cirúrgico — cristaloide ≤1-2 L + transfusão 1:1:1",via:"IV",o:"NÃO super-ressuscitar pré-cirurgia (dilui coagulação, piora sangramento)."},
{etapa:"escala", d:"Ácido tranexâmico",do:"1 g IV em 10 min + 1 g em 8h",via:"IV",o:"CRASH-2: reduz mortalidade se <3h do trauma. SEMPRE em hemorragia grave."},
{etapa:"escala", d:"Embolização angiográfica",do:"—",via:"Endovascular",o:"Trauma esplênico/hepático ativo (blush no TC) em paciente estável."},
],
alertas:[
{t:"crit",x:"Cinto de segurança 'sinal' (equimose abdominal transversal) + dor abdominal = lesão intestinal/mesentério até prova contrária. TC + reavaliação seriada."},
{t:"crit",x:"GRAVIDEZ + trauma — proteger materna primeiro. β-hCG sempre. Anti-D se Rh-negativa. Imobilização lateralizada à esquerda."},
{t:"warn",x:"Trauma pancreático é silencioso — amilase/lipase normais inicialmente; TC com contraste pode subdiagnosticar. Reavaliar."},
],
fisio:"Fechado: lesão por compressão direta, desaceleração (lacerações mesentério, pedículos vasculares), aumento súbito pressão intra-abdominal (ruptura órgão oco). Penetrante: FAB lacera estruturas no trajeto; FAF tem cavitação temporária (alta energia → dano periférico ao trajeto). Hemoperitônio = clínica de choque + irritação peritoneal tardia.",
mec:[],
diretriz:"ATLS 10ª ed. EAST Guidelines. WSES Splenic Trauma 2017 (Coccolini F et al., World J Emerg Surg 2017;12:40).",
fluxo:null,
calcs:[],
},

{id:"fratura-quadril", sis:"trauma", grav:"media",
nome:"Fratura de Quadril em Idoso",
sin:["fratura quadril","fratura colo femoral","fratura transtrocantérica"],
def:"Fratura proximal de fêmur (colo, transtrocantérica, subtrocantérica) — clássica do idoso após queda da própria altura. Sinal: rotação externa + encurtamento + dor + incapacidade carga. Mortalidade 30% em 1 ano se não operado precocemente.",
exames:["RX bacia AP + lateral quadril","TC se RX inconclusivo (mais 5% RX-negativas)","Hemograma, função renal","ECG + RX tórax (pré-op)","Avaliação anestésica","Ecocardiograma se cardiopata"],
rx:[
{etapa:"escala", d:"Cirurgia em <48h",do:"Hemiartroplastia (colo desviada idoso), DHS/parafuso (intertroc), HD (jovem)",via:"Cirúrgico",o:"PILAR. Cada dia de atraso = ↑mortalidade. Múltiplas diretrizes apoiam <48h."},
{etapa:"adj", d:"Profilaxia TVP",do:"Enoxaparina 40 mg SC/d ou HBPM ajustada",via:"SC",o:"INICIAR pré-op (suspender 12h antes) e manter 4-6 semanas pós-op."},
{etapa:"adj", d:"Analgesia",do:"Bloqueio do fáscia ilíaca (3-Em-1) + paracetamol 1g 6/6h + dipirona",via:"IV/regional",o:"EVITAR opioides em idoso — delirium. Bloqueio regional 1ª linha — Cochrane recomendação forte."},
{etapa:"escala", d:"Reposição volêmica",do:"Cristaloide cauteloso",via:"IV",o:"Idoso descompensa fácil. Avaliar volemia clinicamente."},
{etapa:"escala", d:"Otimização cardíaca",do:"Manter β-bloqueador se uso, controlar PA, corrigir anemia (Hb >8)",via:"—",o:"Cirurgia geralmente cardio-tolerada — não atrasar para 'investigação' desnecessária."},
{etapa:"adj", d:"Profilaxia delirium",do:"Hidratação adequada + reorientação + dispositivos auditivos/visuais + evitar BZD/anti-H1",via:"—",o:"Delirium pós-op em até 50% idosos. Haloperidol 0,25-0,5 mg em crise."},
],
alertas:[
{t:"crit",x:"FRATURA + HIPOTENSÃO em idoso = considerar sangramento (trans/subtrocantérica pode perder 1-2 L). Reservar hemocomponentes."},
{t:"warn",x:"FRATURA SEM TRAUMA significativo = fratura patológica (metástase óssea, mieloma, osteoporose grave) — investigar."},
{t:"info",x:"Avaliação de osteoporose pós-fratura: investigação completa + bifosfonatos/denosumabe. ↓50% nova fratura em 3 anos."},
],
fisio:"Osteoporose senil + queda da própria altura. Colo femoral: fratura pode comprometer vascularização (artéria circunflexa femoral medial) → necrose avascular se desviada (Garden III-IV) → indicação de prótese ao invés de osteossíntese. Transtrocantérica: bem vascularizada, osteossíntese (DHS/PFN). Repouso prolongado → TEP, pneumonia, úlcera de pressão, sarcopenia, dependência permanente.",
mec:[],
diretriz:"AAOS 2021 Hip Fractures in Elderly. NICE NG124. Diretrizes SBOT.",
fluxo:null,
calcs:[],
},

/* ============== OUTRAS CRÍTICAS ============== */
{id:"crise-falciforme", sis:"hemo", grav:"alta",
nome:"Crise Falciforme (Vaso-oclusiva)",
sin:["crise falciforme","anemia falciforme","CVO","STA","síndrome torácica aguda"],
def:"Anemia falciforme (HbSS) com episódios agudos: CVO (dor óssea/torácica/abdominal súbita); STA (febre + sintomas resp + infiltrado RX); sequestro esplênico (criança, dor + esplenomegalia + ↓Hb); aplasia (parvovírus B19); priapismo; AVC; sepse (encapsulados).",
exames:["Hemograma com reticulócitos","DHL, bilirrubina, haptoglobina (hemólise)","Função renal, eletrólitos","Hemocultura se febril","RX tórax (sempre se sintomas resp)","β-HCG mulher fértil","Tipagem completa (RhE, Kell — aloimunização)"],
rx:[
{etapa:"adj", d:"Analgesia ESCALONADA",do:"Dipirona 2g + Cetorolaco 30mg IV → Morfina 0,1 mg/kg IV (titular)",via:"IV",o:"NÃO subdosar. Crise falciforme dói tanto quanto IAM. PCA/BIC morfina se necessário. SUBESTIMAÇÃO da dor é a regra."},
{etapa:"escala", d:"Hidratação",do:"SF 1-1,5× manutenção (NÃO bolus)",via:"IV",o:"Evitar super-hidratação (risco edema pulmonar)."},
{etapa:"inicial", d:"O₂",do:"Manter SpO₂ ≥95%",via:"—",o:"NÃO usar liberalmente — só se hipoxêmico. O₂ excessivo pode suprimir eritropoiese."},
{etapa:"escala", d:"ATB (se febril/STA)",do:"Ceftriaxona 2g IV + Azitromicina 500 mg IV",via:"IV",o:"Cobertura pneumococo + Mycoplasma. Atypicals comuns em STA."},
{etapa:"escala", d:"Transfusão simples",do:"CH 10-15 mL/kg",via:"IV",o:"Hb >7-9. NÃO ultrapassar Hb 10 (hiperviscosidade)."},
{etapa:"escala", d:"Exsanguineotransfusão",do:"Eritroaférese ou exsang manual",via:"IV",o:"STA grave, AVC, falência multissistêmica, priapismo refratário. Alvo HbS <30%."},
{etapa:"anticoag", d:"Heparina profilática",do:"Enoxaparina 40 mg SC/d",via:"SC",o:"Internação prolongada — alto risco TVP/TEP."},
{etapa:"adj", d:"Tromboprofilaxia mecânica",do:"Meias compressivas",via:"—",o:"Sempre, mesmo em quem recebe heparina."},
],
alertas:[
{t:"crit",x:"SÍNDROME TORÁCICA AGUDA (STA): febre + dispneia/dor torácica + infiltrado novo RX em paciente com anemia falciforme. Mortalidade 4-10% adultos. Atb + O₂ + transfusão se Hb<9 ou hipoxemia."},
{t:"crit",x:"ANEMIA FALCIFORME + FEBRE = sepse até prova contrária. Asplenia funcional → pneumococo, H. influenzae, salmonella. Hemocultura + ATB IV imediato."},
{t:"warn",x:"AVC isquêmico em criança falciforme: trombólise pode ser tentada (caso-a-caso); exsanguineo é central."},
{t:"warn",x:"Priapismo >4h: aspiração + irrigação salina ± fenilefrina intracavernosa + exsanguineo. Urologia."},
],
fisio:"HbS (β6 Glu→Val): em desoxigenação, HbS polimeriza em fibras longas → hemácia em foice → adesão endotelial + rigidez + obstrução microvascular → isquemia tecidual + dor. Crises desencadeadas por: hipóxia, desidratação, infecção, frio, estresse, álcool, altitude. Pacientes têm asplenia funcional (sequestro autoinfartos no baço) → risco encapsulados.",
mec:[
{d:"Hidroxiureia (manutenção, não-crise)",x:"↑síntese de HbF (fetal) — HbF não polimeriza → reduz episódios e mortalidade. Mecanismo molecular não totalmente elucidado (envolve NO, citocinas)."},
{d:"Voxelotor (manutenção)",x:"Liga-se à HbS estabilizando o estado oxigenado → menos polimerização. Disponibilidade limitada no SUS."},
],
diretriz:"ASH 2020 Sickle Cell (Liem RI et al., Blood Adv 2020;4:1554, DOI:10.1182/bloodadvances.2019001142). NHLBI 2014. PCDT MS Brasil.",
fluxo:null,
calcs:[],
},

{id:"glaucoma-agudo", sis:"oft", grav:"alta",
nome:"Glaucoma Agudo de Ângulo Fechado",
sin:["glaucoma agudo","ângulo fechado","crise glaucomatosa"],
def:"Elevação aguda da pressão intraocular (PIO) por bloqueio pupilar com ângulo iridocorneano fechado. CLÁSSICO: olho vermelho doloroso unilateral + halos coloridos + diminuição visual + náuseas/vômitos + pupila médio-fixa + córnea turva.",
exames:["Tonometria — PIO geralmente 40-80 mmHg (normal 10-21)","Gonioscopia (oftalmologia)","Fundo de olho — escavação papilar","TC se dúvida diagnóstica/AVC"],
rx:[
{etapa:"escala", d:"Acetazolamida",do:"500 mg IV ou VO + 250 mg VO 6/6h",via:"IV/VO",o:"INIBIDOR anidrase carbônica — ↓produção humor aquoso. Cuidado em alérgicos a sulfa."},
{etapa:"escala", d:"Manitol",do:"1-2 g/kg IV em 30-45 min",via:"IV",o:"Diurético osmótico — desidrata vítreo. Cuidado em IC, IRA."},
{etapa:"escala", d:"Pilocarpina 2%",do:"1 gota OD 15/15 min × 1h, depois 6/6h",via:"Tópico",o:"Miótico — abre o ângulo. NÃO usar em ataque agudo da PIO muito alta (ineficaz com PIO >40 — isquemia da íris); SÓ após PIO ↓."},
{etapa:"escala", d:"Timolol 0,5%",do:"1 gota OD 12/12h",via:"Tópico",o:"β-bloq → ↓produção humor aquoso. CI: asma, DPOC grave, BAV."},
{etapa:"escala", d:"Brimonidina",do:"1 gota OD 8/8h",via:"Tópico",o:"α2-agonista — ↓produção + ↑drenagem."},
{etapa:"escala", d:"Latanoprosta",do:"1 gota OD à noite",via:"Tópico",o:"↑drenagem uveoescleral. Adjuvante."},
{etapa:"adj", d:"Antiemético",do:"Ondansetrona 4-8 mg IV",via:"IV",o:"Vômitos aumentam PIO. Tratar."},
{etapa:"inicial", d:"Iridotomia a laser",do:"YAG laser perfuração da íris periférica",via:"Procedimento",o:"DEFINITIVO. Após estabilizar PIO. Também no OUTRO olho profilaticamente."},
],
alertas:[
{t:"crit",x:"PERDA VISUAL EM HORAS-DIAS se não tratado. Urgência oftalmológica REAL. Início imediato de medicação enquanto contata oftalmo."},
{t:"warn",x:"Atropina e simpaticomiméticos PRECIPITAM ataque em pacientes predispostos (anatomia de ângulo estreito) — cuidado em pacientes mais velhos hipermétropes recebendo midriáticos."},
],
fisio:"Ângulo estreito anatômico (idoso, hipermetrope, mulher, asiático) + dilatação pupilar (escuridão, midriáticos, estresse) → bloqueio do trabeculado pela íris periférica → bloqueio do escoamento humor aquoso → ↑PIO súbita → isquemia da retina/nervo óptico. Sem tratamento: cegueira em 24-48h.",
mec:[
{d:"Acetazolamida",x:"Inibe anidrase carbônica → ↓formação HCO₃⁻ no epitélio ciliar → ↓secreção humor aquoso."},
{d:"Timolol",x:"β-bloq não-seletivo → ↓ AMPc no epitélio ciliar → ↓produção humor aquoso."},
{d:"Pilocarpina",x:"Agonista muscarínico → contração esfíncter pupilar (miose) → tração na íris periférica → abre ângulo iridocorneano."},
],
diretriz:"AAO Preferred Practice Pattern — Primary Angle Closure 2020.",
fluxo:null,
calcs:[],
},

{id:"torcao-test", sis:"gu", grav:"alta",
nome:"Torção Testicular",
sin:["torção testicular","testículo torcido","torção cordão espermático"],
def:"Rotação do cordão espermático → isquemia testicular. Dor escrotal súbita unilateral + náusea/vômito + reflexo cremastérico ausente + Prehn negativo (elevação NÃO alivia). PICO: 12-18 anos e neonatal.",
exames:["USG doppler escrotal — ↓fluxo (sensibilidade 88-100%)","β-HCG (afastar gestação se mulher confundida)","Urocultura/EAS"],
rx:[
{etapa:"escala", d:"CIRURGIA URGENTE",do:"Exploração escrotal + destorção + orquiopexia bilateral",via:"Cirúrgico",o:"Janela viabilidade: 4-6h (100% salva), 12h (50%), >24h (≤10%). NÃO ESPERAR USG se quadro clássico."},
{etapa:"escala", d:"Destorção manual",do:"Rotação externa do testículo (como abrir livro)",via:"—",o:"Apenas como ponte até cirurgia. NÃO substitui exploração."},
{etapa:"adj", d:"Analgesia",do:"Dipirona 2g + Tramadol 100mg IV",via:"IV",o:"Cuidado para não mascarar exame seriado."},
],
alertas:[
{t:"crit",x:"CADA HORA CONTA. Diagnóstico é CLÍNICO + USG. Quando há dúvida → operar (custo de orquiectomia desnecessária é menor que perda testicular)."},
{t:"crit",x:"USG NORMAL NÃO EXCLUI (torção intermitente, fluxo preservado parcial)."},
{t:"warn",x:"Diferencial: epididimite (febre, piúria, Prehn positivo, mais gradual), torção apêndice testicular (dor menor, blue dot sign), trauma."},
],
fisio:"Anomalia 'em badalo de sino' (bell-clapper) — testículo móvel dentro da vaginal por inserção alta → torção facilitada por contração cremastérica (frio, esporte, sono). Bilateral em 80% — daí orquiopexia BILATERAL. Após 6h, lesão isquêmica significativa; após 24h, geralmente necrose.",
mec:[],
diretriz:"AUA Guidelines on Testicular Torsion. EAU Pediatric Urology Guidelines 2023.",
fluxo:null,
calcs:[],
},

{id:"insuf-adrenal", sis:"endo", grav:"alta",
nome:"Insuficiência Adrenal Aguda (Crise Addisoniana)",
sin:["insuficiência adrenal","crise addisoniana","Addison","crise suprarrenal"],
def:"Falência aguda do córtex adrenal — hipotensão refratária + náusea/vômito + dor abdominal + hiponatremia + hipercalemia + hipoglicemia + febre. Suspeitar em corticoide crônico que interrompeu/perdeu dose em estresse, sepse, trauma.",
exames:["Glicemia capilar","Eletrólitos (hipoNa + hiperK + hipoglicemia clássicos)","Cortisol sérico (basal — coletar ANTES da reposição)","ACTH (basal — diferenciar 1ª de 2ª)","Hemograma, função renal, gaso","Hemocultura, urinocultura se febril","TC abdome se primária aguda (hemorragia adrenal — Waterhouse-Friderichsen)"],
rx:[
{etapa:"escala", d:"Hidrocortisona",do:"100 mg IV bolus → 50 mg IV 6/6h × 24h → desmame",via:"IV",o:"NÃO esperar cortisol — dar imediatamente. Hidrocortisona tem mineralocorticoide intrínseco (não precisa fludrocortisona aguda)."},
{etapa:"inicial", d:"Cristaloide",do:"SF 0,9% 1 L IV em 1h, depois 1 L IV em 2-4h",via:"IV",o:"Reposição volêmica vigorosa. Pode chegar a 3-5 L primeiras 24h."},
{etapa:"inicial", d:"Correção glicêmica",do:"Glicose 50% 50 mL IV se hipoglicemia",via:"IV",o:"Manter SG 5% após estabilizar."},
{etapa:"escala", d:"Tratar precipitante",do:"ATB se infecção, etc.",via:"—",o:"Sepse é o gatilho mais comum."},
{etapa:"alta", d:"Manutenção crônica (após crise)",do:"Hidrocortisona 15-25 mg/d divididos (2/3 manhã, 1/3 tarde) + Fludrocortisona 0,05-0,2 mg/d (se 1ª)",via:"VO",o:"Educar sobre dose de estresse: dobrar/triplicar em febre, cirurgia, gestação, trauma. Cartão de identificação."},
],
alertas:[
{t:"crit",x:"NÃO ESPERAR cortisol — coletar e tratar empiricamente em hipotensão refratária + hipoNa + hiperK + corticoide crônico recente."},
{t:"crit",x:"Síndrome de Waterhouse-Friderichsen: hemorragia adrenal bilateral em sepse (meningococo, pseudomonas) → choque refratário + petéquias + insuficiência adrenal."},
{t:"warn",x:"Suspensão abrupta de corticoide crônico (uso >3 sem em dose ≥7,5 mg prednisona) → supressão eixo. Desmame gradual ou cobertura de stress."},
],
fisio:"Primária (Addison): destruição córtex adrenal — autoimune (70% adultos), TB (BR), HIV, hemorragia, metástase. Manifesta-se com falta de cortisol E aldosterona → hipoNa + hiperK + hiperpigmentação (↑ACTH/MSH). Secundária: doença hipotálamo-hipófise → só falta cortisol (aldosterona preservada — pouca hipercalemia/hipotensão menos grave). Mais comum: SUSPENSÃO de corticoide crônico (eixo suprimido).",
mec:[
{d:"Hidrocortisona",x:"Cortisol sintético — atua em receptores glicocorticoide (anti-inflamatório, gliconeogênese, sensibilidade vascular a catecolaminas) e em altas doses também em mineralocorticoide (Na/K)."},
{d:"Fludrocortisona",x:"Análogo da aldosterona — ↑reabsorção Na e excreção K nos túbulos coletores."},
],
diretriz:"Endocrine Society 2016 (Bornstein SR et al., J Clin Endocrinol Metab 2016;101:364). UpToDate.",
fluxo:null,
calcs:[],
},

{id:"crise-tireo", sis:"endo", grav:"alta",
nome:"Crise Tireotóxica (Tempestade Tireoidiana)",
sin:["crise tireotóxica","tempestade tireoidiana","Graves","hipertireoidismo descompensado"],
def:"Manifestação extrema do hipertireoidismo — febre alta + taquicardia >130 + arritmias + alteração mental (agitação → coma) + GI (vômitos, diarreia) + cardiopatia descompensada. Mortalidade 10-30% mesmo tratado. Escala de Burch-Wartofsky.",
exames:["TSH (suprimido <0,01) + T4 livre + T3 livre","HMG, função hepática (alt comum)","Função renal, eletrólitos, cálcio","ECG (FA, taqui sinusal)","Hemocultura se febril (infecção é precipitante #1)","Beta-HCG mulher fértil"],
rx:[
{etapa:"escala", d:"Propranolol",do:"40-80 mg VO 4/4h OU 1-2 mg IV bolus repetir 15/15 min",via:"VO/IV",o:"1ª linha — controla taquicardia/HAS/agitação. Bloqueia conversão T4→T3 (efeito extra)."},
{etapa:"escala", d:"Esmolol BIC",do:"50-200 mcg/kg/min",via:"IV",o:"Se intolerância a propranolol (asma) ou necessidade de titulação. Cuidado em IC."},
{etapa:"alta", d:"Propiltiouracila (PTU)",do:"500-1000 mg VO ataque + 250 mg 4/4h",via:"VO/SNG",o:"1ª escolha NA CRISE (bloqueia conversão T4→T3 perifericamente, além de síntese). PREFERIR sobre metimazol em crise (não em manutenção crônica)."},
{etapa:"escala", d:"Iodo (Lugol/SSKI)",do:"Lugol 8-10 gotas 6/6h OU SSKI 5 gotas 6/6h",via:"VO",o:"DAR 1H APÓS PTU (não antes — fornece substrato). Bloqueio Wolff-Chaikoff. Iopanato/ipodato (não disponível BR) é alternativa."},
{etapa:"escala", d:"Hidrocortisona",do:"100 mg IV 8/8h",via:"IV",o:"Bloqueia conversão T4→T3 + reposição (insuficiência adrenal relativa frequente)."},
{etapa:"adj", d:"Resfriamento + Paracetamol",do:"NÃO usar AAS (desloca T4 da TBG → piora)",via:"—",o:"Manta + paracetamol 1g 6/6h. Hipertermia agrava."},
{etapa:"escala", d:"Suporte volêmico",do:"SF 0,9% guiado por volemia",via:"IV",o:"Vômitos + diarreia + sudorese causam desidratação importante."},
],
alertas:[
{t:"crit",x:"DAR PTU ANTES do iodo. Iodo é substrato para síntese; dado antes do PTU pode piorar transitoriamente."},
{t:"crit",x:"NÃO usar AAS para febre — desloca T4 da TBG → ↑hormônio livre."},
{t:"warn",x:"Precipitantes: infecção (mais comum), cirurgia tireoide, parto, IAM, AVC, uso de contraste iodado (cuidado em pacientes Graves), suspensão de tioamida."},
],
fisio:"Crise no hipertireoidismo descompensado (geralmente Graves não tratado). Excesso de hormônio tireoidiano + ↑sensibilidade tecidual a catecolaminas → estado hipermetabólico extremo, taquicardia, hipertermia, lipólise + glicogenólise, vasodilatação, IC alto débito. Insulto agudo (infecção, cirurgia) precipita transformação de hipertireoidismo crônico em crise.",
mec:[
{d:"Propiltiouracila",x:"Inibe peroxidase tireoidiana (organificação iodo + acoplamento iodotirosinas) E inibe deiodinase tipo 1 perifericamente → ↓conversão T4→T3 (vantagem na crise)."},
{d:"Iodo",x:"Bloqueio agudo organificação (Wolff-Chaikoff) — paradoxalmente, doses altas inibem síntese hormonal. Efeito imediato mas transitório (escape em 7-14 dias)."},
{d:"Hidrocortisona",x:"Inibe deiodinase tipo 1, reduzindo conversão periférica T4→T3."},
],
diretriz:"American Thyroid Association 2016 Hyperthyroidism (Ross DS et al., Thyroid 2016;26:1343, DOI:10.1089/thy.2016.0229). Burch HB & Wartofsky L, JCEM 1993 (escala).",
fluxo:null,
calcs:[],
},

{id:"rabdomiolise", sis:"hidro", grav:"alta",
nome:"Rabdomiólise",
sin:["rabdomiólise","CPK alta","mioglobinúria"],
def:"Lise muscular esquelética com liberação de mioglobina, K, fósforo, CK no plasma → risco de IRA por mioglobina + hipercalemia. CRITÉRIO: CK >5× LSN (geralmente >1000). Tríade clássica clássica: dor + fraqueza + urina escura (cor coca-cola).",
exames:["CK, mioglobina sérica e urinária","Eletrólitos (K, Ca, P), ureia, Cr (IRA)","Gaso (acidose), lactato","Função hepática (TGO/TGP elevadas — não significa hepatite)","ECG (hiperK)","EAS (Hb+ sem hemácias = mioglobina), urocultura"],
rx:[
{etapa:"escala", d:"Hidratação AGRESSIVA",do:"SF 0,9% 1-1,5 L/h primeiras horas → ajustar para diurese 200-300 mL/h",via:"IV",o:"PILAR. Manter por 48-72h até CK ↓. Alvo: débito urinário ≥200 mL/h."},
{etapa:"escala", d:"Alcalinização urinária (controverso)",do:"Bicarbonato 8,4% 100-150 mEq em 1L SG/SF — ajustar para pH urinário >6,5",via:"IV",o:"Pode reduzir nefrotoxicidade da mioglobina. NÃO se hipoCa, alcalemia, ICC."},
{etapa:"escala", d:"Tratamento HIPERCALEMIA",do:"Ver patologia específica",via:"—",o:"Pode ser a 1ª manifestação. ECG! Cálcio + insulina/glicose + salbutamol."},
{etapa:"escala", d:"Diálise",do:"—",via:"—",o:"IRA estabelecida com indicação clássica (uremia, sobrecarga, hiperK refratária, acidose grave). Não tem indicação profilática."},
{etapa:"escala", d:"Manitol 20% (controverso)",do:"1 g/kg em 30 min após volemia repleta",via:"IV",o:"Sem evidência clara de benefício; risco de IRA osmótica. Geralmente NÃO recomendado."},
],
alertas:[
{t:"crit",x:"HIPERCALEMIA é a maior ameaça aguda. ECG seriado. Tratar K >6 imediatamente mesmo sem ECG alterado."},
{t:"crit",x:"HIPOCALCEMIA INICIAL (Ca entra no músculo lesado) seguida de HIPERCALCEMIA TARDIA (mobilização). NÃO repor Ca de rotina (piora deposição em mioócitos) — só se sintomática (tetania, QT longo)."},
{t:"warn",x:"Etiologias: trauma/esmagamento, exercício extremo, alcoolismo (queda + decúbito prolongado), estatinas, drogas (cocaína, MDMA), neurolépticos, infecções (gripe, leptospirose), miopatias, hipertermia, isquemia compartimental."},
],
fisio:"Lise da miofibra → liberação maciça intracelular para circulação. Mioglobina passa pelo glomérulo, mas nos túbulos forma cilindros com proteína de Tamm-Horsfall + dissocia em ferro livre + heme → vasoconstrição renal + lesão tubular direta. Resultado: NTA isquêmica/tóxica. Hiperpotassemia + hiperfosfatemia (potencialmente fatais) por liberação intracelular.",
mec:[
{d:"Bicarbonato",x:"Alcaliniza a urina → reduz dissociação da mioglobina + ↓formação de cilindros + ↓oxidação heme → ↓nefrotoxicidade. Evidência clínica modesta."},
],
diretriz:"Bosch X et al., NEJM 2009;361:62. Diretrizes brasileiras IRA.",
fluxo:null,
calcs:[],
},

{id:"tentativa-suicidio", sis:"psiq", grav:"alta",
nome:"Tentativa de Suicídio / Ideação Aguda",
sin:["tentativa de suicídio","ideação suicida","autolesão"],
def:"Comportamento autolesivo intencional com intenção de morrer OU ideação suicida estruturada (plano + método + intenção). Avaliar SEMPRE: ideação, plano, intenção, acesso a método letal, tentativa prévia, fatores de risco.",
exames:["Avaliação clínica completa do método","Toxicologia (paracetamol, salicilatos, etanol)","Eletrólitos, função renal, hepática","ECG (se intoxicação)","Beta-HCG mulher fértil"],
rx:[
{etapa:"inicial", d:"ESTABILIZAR clínica",do:"Tratar lesões/intoxicação conforme método",via:"—",o:"PRIMEIRO clinicamente, depois psiquiatria. ABCDE."},
{etapa:"escala", d:"PROTEGER paciente",do:"Acompanhante 1:1, ambiente seguro (sem objetos cortantes/cordas/medicações)",via:"—",o:"Equipe de enfermagem orientada. Reduzir estímulos."},
{etapa:"escala", d:"AVALIAÇÃO PSIQUIÁTRICA",do:"Avaliação por psiquiatra/psicólogo (Resolução CFM)",via:"—",o:"OBRIGATÓRIA. Determina: alta com plano de segurança vs. internação voluntária vs. involuntária (laudo médico)."},
{etapa:"escala", d:"INTERNAÇÃO INVOLUNTÁRIA",do:"Comunicar MP em até 72h (Lei 10.216/2001)",via:"—",o:"Indicações: ideação ativa + plano + acesso meios; tentativa de alta letalidade; falta de suporte; comorbidade psiquiátrica grave."},
{etapa:"escala", d:"Plano de segurança (se alta)",do:"Identificar sinais alarme + estratégias enfrentamento + acionar suporte + limitar meios + serviços emergência",via:"—",o:"Modelo Stanley-Brown. Família orientada. Retirar armas/medicações de casa."},
{etapa:"escala", d:"Encaminhamento",do:"CAPS / consulta psiquiátrica em ≤7 dias",via:"—",o:"Continuidade do cuidado é fator protetor mais robusto."},
],
alertas:[
{t:"crit",x:"ACOLHA SEM JULGAMENTO. Perguntar diretamente sobre ideação NÃO induz comportamento — falta de pergunta sim."},
{t:"crit",x:"FATORES DE ALTO RISCO: tentativa prévia, plano estruturado, acesso a arma, álcool/drogas, depressão grave, psicose, idoso H solitário, dor crônica, doença terminal, perda recente."},
{t:"warn",x:"Período pós-alta é de ALTO RISCO (especialmente 1ª semana). Garantir consulta em 24-72h, plano de segurança escrito."},
{t:"info",x:"CVV 188 (24h, gratuito). CAPS-AD se comorbidade com substância. SAMU 192 transporte."},
],
fisio:"Multifatorial: transtorno mental (depressão 60%, dependência química, esquizofrenia, transtornos de personalidade), fatores biológicos (serotonina, neuroinflamação), psicossociais (perda, isolamento, dor, doença), genéticos (família). É manifestação de SOFRIMENTO + ↓capacidade de tolerar — não 'fraqueza' nem 'manipulação'.",
mec:[],
diretriz:"MS — Diretrizes para um Modelo Brasileiro de Prevenção do Suicídio (Portaria 1.876/2006). CFM 2.057/2013. WHO LIVE LIFE 2021. Lei 13.819/2019 (notificação compulsória).",
fluxo:null,
calcs:[],
},

);
