/* ===========================================================
   VOVÔMINIC EMERGÊNCIA — PULO DO GATO 3 (parte C)
   Pediatria + Saúde Mental + Procedimentos
   =========================================================== */

PATOLOGIAS.push(

/* ============== IM EM CRIANÇA — ABRAÇO BORBOLETA ============== */
{id:"pulo-im-crianca", nome:"Aplicação IM em criança — abraço de borboleta + distração", sis:"pulo", grav:"baixa",
cid:"-", ciap:"-",
sin:["Vacina criança","IM criança","Abraço borboleta","Bear hug","Distração"],
def:"Aplicação intramuscular em criança ATIVA/AGITADA = CONTENÇÃO COMPASSIVA (não trauma) + DISTRAÇÃO + posição + agulha rápida. Reduz dor, estresse e necessidade de repetir.",
quadro:["Aplicação IM em criança 6m-6a — vacina, dipirona, ceftriaxona, midazolam","Criança ansiosa, cooperação variável","⚠ Em criança >5-6a: pode-se explicar e obter cooperação"],
diag:["Avaliar idade, cooperação, presença de cuidador, local da aplicação"],
exames:["Nenhum"],
rx:[
{etapa:"inicial", d:"⚠ PREPARAR antes — minimizar tempo de espera"},
{etapa:"inicial", d:"Aspirar medicação, seringa pronta com agulha de 25-27G (mais fina, menos dor)"},
{etapa:"inicial", d:"Local: vasto lateral da coxa (<3 anos), deltoide (>3 anos)"},
{etapa:"escala", d:"⚠ POSIÇÃO 'ABRAÇO DE BORBOLETA' (Bear Hug) — para CRIANÇA <5 ANOS"},
{etapa:"escala", d:"(1) Cuidador SENTADO, criança DE FRENTE para cuidador (no colo, virada de frente)"},
{etapa:"escala", d:"(2) Cuidador cruza os braços ao redor da criança — UM BRAÇO sobre o tronco da criança imobilizando o braço dela CONTRALATERAL ao da aplicação"},
{etapa:"escala", d:"(3) OUTRO BRAÇO sob a axila da criança, mão estabilizando o membro a ser puncionado"},
{etapa:"escala", d:"(4) Cuidador cruza as PERNAS sobre as pernas da criança (segura ambas as pernas)"},
{etapa:"escala", d:"(5) Posição estável, sem força excessiva, criança 'abraçada' confortavelmente"},
{etapa:"escala", d:"⚠ TÉCNICA DA APLICAÇÃO RÁPIDA"},
{etapa:"escala", d:"Antissepsia + estabilizar pele com a mão não-dominante (pinçar/pressionar)"},
{etapa:"escala", d:"Inserir agulha em 90° em movimento ÚNICO E RÁPIDO (não devagar)"},
{etapa:"escala", d:"Injetar medicação em velocidade moderada (não muito rápida — dói mais)"},
{etapa:"escala", d:"Retirar agulha + pressão com algodão"},
{etapa:"adj", d:"⚠ DISTRAÇÃO durante o procedimento"},
{etapa:"adj", d:"Música, vídeo no celular, brinquedo, conversa com cuidador"},
{etapa:"adj", d:"Pedir para SOPRAR num cata-vento, em uma vela imaginária (Valsalva — reduz dor)"},
{etapa:"adj", d:"Pirulito / chiquinha para sucção (efeito analgésico em <2 anos)"},
{etapa:"adj", d:"Lactente: AMAMENTAR DURANTE a aplicação — efeito analgésico comprovado"},
{etapa:"adj", d:"⚠ TÉCNICAS DE REDUÇÃO DE DOR ASSOCIADAS"},
{etapa:"adj", d:"GELO no local antes (1-2 min) — pequena anestesia"},
{etapa:"adj", d:"EMLA creme 30-60 min antes (em vacinas programadas, não emergência)"},
{etapa:"adj", d:"Glicose oral 24% sublingual em RN/lactente <1 ano antes do procedimento — efeito analgésico (Doloctan)"},
{etapa:"adj", d:"Aquecer ampola na mão (medicação fria dói mais)"},
{etapa:"adj", d:"⚠ EM CRIANÇA >5-6 ANOS: explicação + cooperação"},
{etapa:"adj", d:"Linguagem honesta: 'vai doer um pouquinho, como uma picada de mosquito, mas vai passar rápido'"},
{etapa:"adj", d:"NÃO mentir ('não vai doer nada') — quebra confiança em vacinas futuras"},
{etapa:"adj", d:"Permitir escolher braço, segurar mão de cuidador, contar até 3 antes"},
{etapa:"alta", d:"PÓS-APLICAÇÃO: elogiar criança ('foi corajoso!'), recompensar (adesivo, pirulito se aceitável)"},
{etapa:"alta", d:"Observação 15-30 min se vacina (raras reações anafiláticas)"},
{etapa:"alta", d:"Orientar pais: dor local 1-2 dias é normal (compressa morna pode ajudar)"},
],
alertas:[
{nivel:"warn", txt:"ABRAÇO DE BORBOLETA é CONTENÇÃO COMPASSIVA — não força excessiva, não trauma. Cuidador como aliado, criança 'abraçada'."},
{nivel:"warn", txt:"NÃO MENTIR para criança ('não vai doer'). Honestidade + linguagem apropriada à idade. Mentira quebra confiança futura."},
{nivel:"info", txt:"AMAMENTAÇÃO durante aplicação em lactente: comprovadamente analgésico (sucção + endorfinas + leite)."},
{nivel:"info", txt:"GLICOSE 24% sublingual em <6 meses: efeito analgésico modesto. Em RN pré-procedimento."},
{nivel:"info", txt:"EMLA tópico 30-60 min antes em vacina programada. Não aplicável em emergência (tempo de absorção)."},
],
fluxo:null, diretriz:"SBP. AAP. Pediatric Pain Society."
},

/* ============== ACESSO VENOSO DIFÍCIL ============== */
{id:"pulo-acesso-venoso", nome:"Acesso venoso difícil — transiluminação + posicionamento", sis:"pulo", grav:"moderada",
cid:"-", ciap:"-",
sin:["Punção venosa difícil","Sem veia","Transiluminação","Lanterna celular","Bíceps manobra"],
def:"Paciente DIFÍCIL DE PUNCIONAR (desidratado, criança, obeso, drogadição, idoso, queimado) = combinar TRANSILUMINAÇÃO (lanterna celular por trás), CALOR LOCAL, manobra do BÍCEPS, garroteamento alternativo. Antes de chamar anestesista ou intraóssea.",
quadro:["Falha repetida de punção venosa","Paciente com veias 'difíceis' por: desidratação, hipotensão/choque, idoso, criança, obeso, queimado, drogadição IV crônica, hipotermia, vasoconstrição","⚠ EM EMERGÊNCIA com necessidade de acesso urgente: intraósseo é alternativa rápida"],
diag:["Inspeção visual + palpação","Avaliar histórico de acessos prévios","Considerar tipo de medicação a infundir (vasoconstritor → veia central / intraósseo)"],
exames:["Conforme contexto clínico"],
rx:[
{etapa:"inicial", d:"⚠ PREPARAR antes de tentar — material completo, ambiente bem iluminado"},
{etapa:"escala", d:"⚠ POSIÇÃO DO PACIENTE"},
{etapa:"escala", d:"DECÚBITO DORSAL com braço PENDENTE da maca (rede de Trendelenburg do braço) — gravidade preenche veias"},
{etapa:"escala", d:"Ou se ortostático: sentar com braço pendente abaixo do nível do coração"},
{etapa:"escala", d:"⚠ MANOBRA DO BÍCEPS (Trick clássico)"},
{etapa:"escala", d:"Garrote no terço médio do braço"},
{etapa:"escala", d:"Pedir paciente FLEXIONAR e ESTENDER o cotovelo várias vezes contra resistência (bombeamento muscular)"},
{etapa:"escala", d:"Pode-se segurar um objeto e apertar repetidamente"},
{etapa:"escala", d:"Veias da fossa cubital se enchem"},
{etapa:"escala", d:"⚠ TRANSILUMINAÇÃO COM CELULAR"},
{etapa:"escala", d:"Lanterna de celular (LED) APOIADA na pele do lado OPOSTO à veia procurada"},
{etapa:"escala", d:"Em ambiente escurecido (apagar luz)"},
{etapa:"escala", d:"Veias aparecem como SOMBRAS LINEARES escuras contra o tecido translúcido"},
{etapa:"escala", d:"Funciona melhor em criança, neonato, paciente magro"},
{etapa:"escala", d:"⚠ CALOR LOCAL"},
{etapa:"escala", d:"Compressa morna na área × 5-10 min — vasodilatação"},
{etapa:"escala", d:"Aquecedor, bolsa de água quente envolta em pano"},
{etapa:"escala", d:"⚠ TAPPING (pequenas batidas) sobre a veia — estimula reflexo de dilatação"},
{etapa:"escala", d:"⚠ GARROTE BAIXO (logo acima do local) — não muito apertado (compressão arterial impede enchimento)"},
{etapa:"adj", d:"⚠ LOCAIS ALTERNATIVOS"},
{etapa:"adj", d:"Veias da mão (dorso) — geralmente visíveis em qualquer paciente"},
{etapa:"adj", d:"Veias do antebraço (basílica, cefálica)"},
{etapa:"adj", d:"Veia jugular externa (em paciente crítico, profissional treinado)"},
{etapa:"adj", d:"Veias do pé (último recurso em adulto, mais comum em pediatria)"},
{etapa:"adj", d:"Em mulher: NÃO usar braço com mastectomia/dissecção axilar"},
{etapa:"adj", d:"⚠ EM CRIANÇA: veias do couro cabeludo (lactente), pé"},
{etapa:"adj", d:"⚠ USG POINT-OF-CARE — padrão crescente"},
{etapa:"adj", d:"Localiza veias profundas em obesos, paciente em choque"},
{etapa:"adj", d:"Permite acesso de veias do antebraço médio (basílica, braquial) sob visualização"},
{etapa:"adj", d:"Curso de treinamento crescente em emergencistas"},
{etapa:"adj", d:"⚠ INTRAÓSSEO — em EMERGÊNCIA com falha repetida"},
{etapa:"adj", d:"Tibial proximal (mais comum) ou úmero proximal"},
{etapa:"adj", d:"Agulha intraóssea (EZ-IO, Cook, etc) — manual ou broca pediátrica"},
{etapa:"adj", d:"Acesso em <60 SEGUNDOS — todas as medicações podem ser infundidas"},
{etapa:"adj", d:"Manter máx 24h, depois transferir para acesso convencional"},
{etapa:"adj", d:"⚠ CATETER VENOSO CENTRAL (jugular interna, subclávia, femoral) — anestesista/intensivista"},
{etapa:"alta", d:"⚠ PERDA DE ACESSO REPETIDA: após 2-3 tentativas frustradas, MUDAR de estratégia (não ficar repetindo)"},
{etapa:"alta", d:"Considerar intraósseo se medicação urgente"},
{etapa:"alta", d:"Solicitar profissional mais experiente / anestesista"},
],
alertas:[
{nivel:"warn", txt:"INTRAÓSSEO em EMERGÊNCIA com falha repetida = ALTERNATIVA RÁPIDA (60 seg). Tibial proximal ou úmero proximal. Não retardar tratamento por acesso difícil."},
{nivel:"warn", txt:"USG POINT-OF-CARE: padrão crescente em ER. Permite acesso de veias profundas. Treinamento curto."},
{nivel:"warn", txt:"GARROTE muito apertado: comprime artérias → menos enchimento venoso. Ajustar tensão."},
{nivel:"info", txt:"TRANSILUMINAÇÃO COM CELULAR LED + ambiente escurecido: funciona melhor em criança/lactente/magro."},
{nivel:"info", txt:"MANOBRA DO BÍCEPS (flexão repetida com garrote) é truque clássico — bombeamento muscular enche veias antecubitais."},
],
fluxo:null, diretriz:"AHA. NAEMT. PALS. ACLS."
},

/* ============== TRAUMA DENTAL FRAGMENTO ============== */
{id:"pulo-fragmento-dente", nome:"Fragmento dental (não avulsionado) — guardar em soro/leite", sis:"pulo", grav:"baixa",
cid:"S02.5", ciap:"D19",
sin:["Fratura coronária","Fragmento dental","Quebra dente","Trauma dental"],
def:"FRATURA CORONÁRIA dental sem avulsão — paciente traz o FRAGMENTO. Pode ser COLADO de volta ao dente pelo dentista em algumas horas — preservação em SORO ou LEITE (NUNCA água) mantém viabilidade. Diferente da AVULSÃO COMPLETA (dente inteiro fora).",
quadro:["Trauma facial / esportivo com QUEBRA de pedaço do dente (ESMALTE, dentina, polpa exposta)","Paciente traz fragmento (frequentemente em papel/embalagem inadequada)","⚠ Diferenciar de AVULSÃO (dente inteiro fora) — outra abordagem","INTRUSÃO/EXTRUSÃO (dente deslocado mas não fora): outras abordagens"],
diag:["Inspeção dental","Classificação Ellis: Classe 1 (apenas esmalte), Classe 2 (dentina), Classe 3 (polpa exposta = vermelho)","Avaliar lesão associada (mucosa, lábio, mandíbula)","Rx panorâmica ou periapical"],
exames:["Rx dental","TC face se trauma maior"],
rx:[
{etapa:"inicial", d:"⚠ AVALIAR fragmento — se traz ou não, condição"},
{etapa:"escala", d:"⚠ CONSERVAÇÃO DO FRAGMENTO (ordem de preferência)"},
{etapa:"escala", d:"1ª escolha: SORO FISIOLÓGICO 0,9% (frasco pequeno, em recipiente plástico/vidro)"},
{etapa:"escala", d:"2ª escolha: LEITE pasteurizado refrigerado (mesma lógica do dente avulsionado — preserva células)"},
{etapa:"escala", d:"3ª escolha: SALIVA — vestíbulo bucal do paciente (se cooperativo, sem risco aspiração)"},
{etapa:"escala", d:"⚠ NUNCA: água da torneira (hipotônica — destrói células), seco no papel, embalagem com algodão"},
{etapa:"escala", d:"Levar ao dentista nas PRÓXIMAS HORAS (idealmente <6h)"},
{etapa:"adj", d:"⚠ MANEJO DA FRATURA DENTAL"},
{etapa:"adj", d:"CLASSE 1 (apenas esmalte): polimento ambulatorial pelo dentista"},
{etapa:"adj", d:"CLASSE 2 (dentina exposta): proteção com ionômero/restauração — encaminhar dentista"},
{etapa:"adj", d:"CLASSE 3 (polpa exposta — ponto vermelho): URGENTE — risco contaminação pulpar, tratamento endodôntico"},
{etapa:"adj", d:"⚠ FRAGMENTO PODE SER COLADO de volta em algumas horas com técnica adesiva pelo dentista"},
{etapa:"adj", d:"⚠ AVALIAR LESÕES ASSOCIADAS"},
{etapa:"adj", d:"Lábios, mucosa oral, língua: pode haver fragmento dental EMBUTIDO na mucosa — Rx tecidos moles"},
{etapa:"adj", d:"Mandíbula, maxila: trauma facial — TC se sinais clínicos"},
{etapa:"adj", d:"TCE associado se mecanismo de alta energia"},
{etapa:"adj", d:"ANTITETÂNICA conforme histórico"},
{etapa:"adj", d:"Antibiótico se exposição pulpar (amoxicilina 500 mg 8/8h × 5 dias)"},
{etapa:"adj", d:"Bochechos com CLOREXIDINA 0,12% 2×/d × 7 dias"},
{etapa:"alta", d:"ENCAMINHAR DENTISTA / ENDODONTISTA URGENTE (poucas horas) — especialmente em exposição pulpar (Classe 3)"},
{etapa:"alta", d:"⚠ ORIENTAR FAMÍLIA: SEMPRE GUARDAR FRAGMENTOS DENTAIS em soro/leite. NÃO descartar"},
{etapa:"alta", d:"PROGNÓSTICO: bom em Classe 1-2 com tratamento adequado. Classe 3 pode precisar tratamento de canal"},
],
alertas:[
{nivel:"crit", txt:"FRATURA CLASSE 3 (exposição pulpar — ponto vermelho/sangramento): URGENTE — risco de contaminação + necrose pulpar. Encaminhar dentista em horas."},
{nivel:"warn", txt:"⚠ MEIO DE PRESERVAÇÃO: SORO FISIOLÓGICO ou LEITE. NUNCA ÁGUA (hipotônica destrói células)."},
{nivel:"warn", txt:"PROCURAR FRAGMENTOS EM MUCOSA / LÁBIO — Rx tecidos moles se quebra com lesão labial associada. Fragmentos enterrados causam abscesso."},
{nivel:"info", txt:"FRAGMENTO PRESERVADO em soro/leite pode ser COLADO de volta em algumas horas pelo dentista — preserva estética."},
{nivel:"info", txt:"DIFERENCIAR de AVULSÃO (dente inteiro fora — janela de 30-60 min) vs FRATURA (fragmento — algumas horas)."},
],
fluxo:null, diretriz:"IADT Guidelines 2020. ABO. Ellis classification."
},

/* ============== ABORDAGEM AO PACIENTE PSICÓTICO ============== */
{id:"pulo-sumo-psicotico", nome:"Abordagem ao paciente psicótico agitado — 'sumô' 5 pessoas", sis:"pulo", grav:"alta",
cid:"F23", ciap:"P98",
sin:["Paciente agitado","Psicose aguda","Contenção","Sumô","Abordagem 5 pessoas","Surto psicótico"],
def:"PACIENTE PSICÓTICO/AGITADO/AGRESSIVO — abordagem física com 5 PESSOAS TREINADAS é MAIS SEGURA e MAIS RÁPIDA que 1 ou 2 (paradoxal). Reduz lesão para paciente E equipe. Combinado com de-escalada verbal + medicação química rápida.",
quadro:["Surto psicótico agudo: alucinações, delírio, desorganização do pensamento","Agitação psicomotora intensa, agressão verbal/física","Causas: esquizofrenia, transtorno bipolar (mania), psicose por substância (cocaína, anfetaminas, álcool, K, LSD), causas orgânicas (delirium, encefalite, hipoxia, hipoglicemia)","⚠ Sempre EXCLUIR causa ORGÂNICA antes de assumir psiquiátrico primário"],
diag:["Anamnese (rápida) + acompanhantes","Sinais vitais (FC, PA, T, SatO₂, glicemia)","Avaliar sinais focais, pupilas, escala de Glasgow","Em quadro novo: investigar causa orgânica antes (delirium é diagnóstico de exclusão)"],
exames:["Glicemia capilar SEMPRE","Em quadro novo / atípico: hemograma, eletrólitos, função renal/hepática, TSH, tóxico (urina), gasometria, ECG, TC crânio"],
rx:[
{etapa:"inicial", d:"⚠ PRIMEIRO — SEGURANÇA DA EQUIPE E DO PACIENTE"},
{etapa:"inicial", d:"Garantir VIA DE SAÍDA — equipe entre paciente e porta"},
{etapa:"inicial", d:"Retirar objetos que possam ser usados como armas"},
{etapa:"inicial", d:"Chamar segurança / polícia se necessário"},
{etapa:"inicial", d:"AVALIAR SINAIS VITAIS + GLICEMIA — descartar causa orgânica imediata"},
{etapa:"escala", d:"⚠ DE-ESCALADA VERBAL — primeira tentativa"},
{etapa:"escala", d:"UM profissional designado para se comunicar — outros recuam"},
{etapa:"escala", d:"Tom calmo, baixo, frases curtas e simples"},
{etapa:"escala", d:"Validar a emoção, não confrontar conteúdo delirante"},
{etapa:"escala", d:"Espaço físico amplo entre profissional e paciente (>2m)"},
{etapa:"escala", d:"Oferecer escolhas (medicação VO vs IM)"},
{etapa:"escala", d:"⚠ NÃO confrontar delírio: 'mas não há ninguém te perseguindo' — VALIDAR a emoção sem reforçar"},
{etapa:"escala", d:"⚠ MEDICAÇÃO RÁPIDA — VO se cooperativo"},
{etapa:"escala", d:"Risperidona 1-2 mg VO + lorazepam 1-2 mg VO (ou diazepam 5-10 mg VO)", o:"Adulto cooperativo. Início 30-60 min."},
{etapa:"escala", d:"Olanzapina 10 mg VO ou dispersível", o:"Sedação rápida, bem aceito."},
{etapa:"escala", d:"⚠ CONTENÇÃO FÍSICA — quando paciente perigoso e medicação VO impossível"},
{etapa:"escala", d:"⚠ TÉCNICA DAS 5 PESSOAS ('SUMÔ' RESPEITOSO)"},
{etapa:"escala", d:"(1) UMA pessoa para CADA MEMBRO (4 pessoas: 2 braços + 2 pernas)"},
{etapa:"escala", d:"(2) UMA pessoa para CABEÇA + comunicação verbal"},
{etapa:"escala", d:"(3) TOTAL: 5 pessoas. Sincronizar abordagem (contar até 3)"},
{etapa:"escala", d:"(4) Cada pessoa segura UM membro firmemente — controla flexão/extensão"},
{etapa:"escala", d:"(5) Decúbito DORSAL com cabeça lateralizada — risco aspiração"},
{etapa:"escala", d:"⚠ NÃO em posição PRONA (risco de morte por compressão respiratória — síndrome de death by restraint, casos legais)"},
{etapa:"escala", d:"(6) Quanto MAIS pessoas, MENOS força CADA UMA precisa fazer — paradoxalmente, menos lesão"},
{etapa:"escala", d:"(7) Aplicar MEDICAÇÃO INTRAMUSCULAR rapidamente — IM coxa lateral"},
{etapa:"escala", d:"⚠ TRANQUILIZAÇÃO RÁPIDA IM"},
{etapa:"escala", d:"Haloperidol 5 mg IM + Midazolam 5 mg IM + Prometazina 25-50 mg IM", o:"Esquema clássico 'B52-mod' / 'haldol-midazolam-fenergan'. Início 15-30 min."},
{etapa:"escala", d:"OU Olanzapina 10 mg IM (alternativa quando disponível)", o:"⚠ Não combinar com benzodiazepínico parenteral (depressão respiratória)."},
{etapa:"escala", d:"OU Ziprasidona 10-20 mg IM (mais sedação rápida)"},
{etapa:"adj", d:"PÓS-CONTENÇÃO + medicação:"},
{etapa:"adj", d:"Monitorar via aérea, SatO₂, FC, PA"},
{etapa:"adj", d:"Reavaliar contenção em 15 min — afrouxar progressivamente conforme sedação"},
{etapa:"adj", d:"Hidratar (paciente sem ingerir há horas/dia)"},
{etapa:"adj", d:"Documentar TUDO — indicação, técnica, medicação, monitorização (questões médico-legais)"},
{etapa:"alta", d:"⚠ INVESTIGAR CAUSA antes/depois da estabilização:"},
{etapa:"alta", d:"INTOXICAÇÃO (cocaína, álcool, anfetamina, K, NPS)"},
{etapa:"alta", d:"ABSTINÊNCIA (álcool, BZD — delirium tremens)"},
{etapa:"alta", d:"CAUSA ORGÂNICA (encefalite, AVC, hipoxia, hipoglicemia, sepse, hipertireoidismo)"},
{etapa:"alta", d:"DESCOMPENSAÇÃO PSIQUIÁTRICA primária"},
{etapa:"alta", d:"ENCAMINHAR psiquiatria de emergência / internação compulsória se necessário"},
{etapa:"alta", d:"⚠ DOCUMENTAR INDICAÇÃO de contenção, técnica usada, medicação, monitor — risco médico-legal alto"},
],
alertas:[
{nivel:"crit", txt:"⚠ NUNCA EM POSIÇÃO PRONA durante contenção — risco morte por restraint (compressão respiratória). Decúbito DORSAL + cabeça lateralizada."},
{nivel:"crit", txt:"5 PESSOAS (1 por membro + 1 para cabeça): paradoxalmente MAIS SEGURO que 2-3. Cada pessoa precisa de MENOS força = menos lesão. Sincronia ESSENCIAL."},
{nivel:"crit", txt:"GLICEMIA SEMPRE antes de medicar agitação — hipoglicemia mimetiza psicose. Erro grave dar haldol em hipoglicêmico."},
{nivel:"warn", txt:"OLANZAPINA IM + BZD parenteral: risco DEPRESSÃO RESPIRATÓRIA. NÃO COMBINAR. Se olanzapina IM: NÃO dar BZD."},
{nivel:"warn", txt:"HALOPERIDOL: cuidado com QT longo (intoxicação por cocaína = arritmia + QT longo). Em jovem com cocaína: PREFERIR BZD isolado."},
{nivel:"warn", txt:"DELIRIUM no idoso: NÃO usar BZD (PIORA). Preferir haloperidol baixa dose OU antipsicótico atípico. Tratar causa subjacente."},
{nivel:"info", txt:"DE-ESCALADA VERBAL evita contenção em ~50% dos casos quando bem feita. Tom calmo, espaço, validar emoção."},
{nivel:"info", txt:"DOCUMENTAR contenção: indicação clínica, técnica, medicação, monitorização. Importante medico-legalmente."},
],
fluxo:null, diretriz:"APA. Joint Commission. Project BETA (Best practices in Evaluation and Treatment of Agitation)."
},

/* ============== PICO HTA vs PÂNICO ============== */
{id:"pulo-pico-vs-panico", nome:"Pico hipertensivo vs ataque de pânico — diferenciar", sis:"pulo", grav:"moderada",
cid:"R45 / I10", ciap:"P74 / K85",
sin:["Crise hipertensiva","Pânico","Ansiedade","Pico hipertensivo","Falsa emergência hipertensiva"],
def:"PA elevada + sintomas agudos NÃO é necessariamente emergência hipertensiva. ATAQUE DE PÂNICO frequentemente cursa com HAS reativa, palpitação, dispneia, sudorese. SEM LOA, NÃO é emergência. Tratar o pânico, não o número.",
quadro:["Paciente com PA elevada + sintomas: cefaleia, palpitação, dispneia, sudorese, formigamento, tonteira","DIFERENCIAR:","EMERGÊNCIA HIPERTENSIVA: PA muito alta + LOA AGUDA (encefalopatia, AVC, EAP, IAM, dissecção, eclâmpsia)","URGÊNCIA HIPERTENSIVA: PA muito alta + sintomas LEVES, sem LOA — controlar gradualmente em 24h","PSEUDO-EMERGÊNCIA (PÂNICO): PA elevada REATIVA aos sintomas de pânico — não é emergência hipertensiva"],
diag:["Sintomas focais neurológicos? (AVC)","Dor torácica isquêmica? (IAM/SCA)","Dispneia + estertores + ortopneia? (EAP)","Edema cerebral (cefaleia + náusea + alteração consciência)?","SE SIM: investigar emergência","SE NÃO: avaliar pânico — palpitação, sensação de morte iminente, dispneia, parestesias, sudorese, tremor — autonômico"],
exames:["PA seriada","ECG","Em emergência: troponina, creatinina, fundoscopia, TC crânio se sintomas neurológicos"],
rx:[
{etapa:"inicial", d:"⚠ AVALIAR LOA AGUDA — pergunta CHAVE"},
{etapa:"inicial", d:"LOA presente: tratar como emergência (NPS, esmolol, etc — UTI)"},
{etapa:"inicial", d:"LOA ausente + PA muito alta: urgência hipertensiva (captopril VO, redução gradual 24h)"},
{etapa:"inicial", d:"LOA ausente + sintomas autonômicos típicos: PSEUDO-EMERGÊNCIA — tratar a CAUSA (pânico)"},
{etapa:"escala", d:"⚠ ATAQUE DE PÂNICO — pistas diagnósticas"},
{etapa:"escala", d:"Sintomas autônômicos: palpitação, sudorese, tremor, dispneia, dor torácica atípica, náusea, tonteira"},
{etapa:"escala", d:"Sintomas neurológicos: parestesias mãos/pés (HIPERVENTILAÇÃO — alcalose respiratória → tetania leve)"},
{etapa:"escala", d:"Sintomas psíquicos: sensação de MORTE iminente, despersonalização, desrealização, medo de enlouquecer"},
{etapa:"escala", d:"DURAÇÃO TÍPICA: 10-30 min (pico em 10 min)"},
{etapa:"escala", d:"História de ATAQUES PRÉVIOS, sintomas idênticos, contexto de estresse"},
{etapa:"escala", d:"⚠ TRATAMENTO DO PÂNICO (não da PA isolada)"},
{etapa:"escala", d:"AMBIENTE TRANQUILO, isolar do agito"},
{etapa:"escala", d:"COMUNICAÇÃO CALMA + reasseguramento — 'isso passa, não vai morrer'"},
{etapa:"escala", d:"⚠ TÉCNICA RESPIRATÓRIA — orientar respiração LENTA e CONTROLADA"},
{etapa:"escala", d:"Inspirar pelo nariz 4 segundos → segurar 4 seg → expirar pela boca 6 seg"},
{etapa:"escala", d:"Repetir várias vezes — corrige alcalose por hiperventilação, reduz sintomas neuromusculares"},
{etapa:"escala", d:"⚠ NÃO USAR SACO DE PAPEL (MITO PERIGOSO)"},
{etapa:"escala", d:"Saco de papel pode causar HIPOXIA grave em paciente com causa orgânica não diagnosticada (TEP, asma, IAM)"},
{etapa:"escala", d:"Casos de morte documentados — abandonado"},
{etapa:"escala", d:"Respiração lenta orientada é alternativa segura e eficaz"},
{etapa:"adj", d:"⚠ MEDICAÇÃO se necessário"},
{etapa:"adj", d:"Lorazepam 1-2 mg SL/VO OU diazepam 5-10 mg VO — em ataque de pânico agudo refratário à abordagem comportamental", o:"Início 10-30 min. Não usar regularmente (dependência)."},
{etapa:"adj", d:"Em emergência ou paciente incapaz de cooperar: lorazepam 1-2 mg IM"},
{etapa:"adj", d:"⚠ REAVALIAR PA APÓS 15-30 min com paciente CALMO"},
{etapa:"adj", d:"Geralmente PA normaliza com a melhora do pânico"},
{etapa:"adj", d:"Se PA persiste alta: avaliar como urgência hipertensiva (captopril 25 mg SL?, repouso, reavaliar)"},
{etapa:"adj", d:"⚠ NÃO USAR captopril sublingual ROTINEIRAMENTE — fora de evidência, pode causar hipotensão excessiva em paciente com pânico"},
{etapa:"alta", d:"⚠ ENCAMINHAR para acompanhamento psiquiátrico/psicológico se ataques recorrentes"},
{etapa:"alta", d:"Em ambulatório: ISRS (sertralina, escitalopram) + TCC são padrão"},
{etapa:"alta", d:"⚠ INVESTIGAR causas orgânicas em pânico atípico: hipertireoidismo, feocromocitoma, abstinência, uso de estimulantes, hipoglicemia"},
],
alertas:[
{nivel:"crit", txt:"⚠ NÃO usar SACO DE PAPEL em hiperventilação — risco HIPOXIA em causa orgânica oculta (TEP, asma, IAM). Casos de morte documentados. Mito perigoso."},
{nivel:"crit", txt:"PA ALTA + SINTOMAS focais (déficit, AVC) = emergência. PA alta + sintomas autonômicos típicos de pânico = pseudo-emergência. Diferenciar antes de tratar."},
{nivel:"warn", txt:"CAPTOPRIL SUBLINGUAL como rotina em PA alta SEM LOA é prática INADEQUADA — risco hipotensão excessiva, sem benefício comprovado. Tratar a causa do quadro."},
{nivel:"warn", txt:"PARESTESIAS em mãos/pés durante crise: alcalose respiratória por hiperventilação. Respiração lenta CORRIGE."},
{nivel:"warn", txt:"BZD em pânico: pontual, não regular. Risco dependência. Tratamento de fundo é ISRS + TCC."},
{nivel:"info", txt:"PÂNICO ATÍPICO (>30 min, sintomas atípicos, primeira crise tardia): investigar causas orgânicas — tireoide, feocromocitoma, hipoglicemia, estimulantes."},
{nivel:"info", txt:"REASSEGURAMENTO + RESPIRAÇÃO LENTA resolve maioria dos ataques de pânico sem medicação."},
],
fluxo:null, diretriz:"DBHA 2025. APA. NICE Panic Disorder."
},

/* ============== HIPERVENTILAÇÃO ============== */
{id:"pulo-hiperventilacao", nome:"Hiperventilação — NÃO saco de papel (mito perigoso)", sis:"pulo", grav:"moderada",
cid:"R06.4", ciap:"R02",
sin:["Hiperventilação","Síndrome hiperventilação","Saco de papel","Alcalose respiratória","Tetania"],
def:"HIPERVENTILAÇÃO causa alcalose respiratória → parestesia, tetania leve, tontura, dor torácica atípica. NÃO usar saco de papel (CAUSAS DE MORTE documentadas — hipoxia em causa orgânica oculta). Tratamento: respiração LENTA controlada + reassurance.",
quadro:["Paciente em hiperventilação aguda, geralmente jovem feminina","Sintomas: respiração rápida + profunda, dispneia subjetiva, parestesia perioral e em mãos/pés (sinal de Trousseau leve), tetania discreta, tontura, sensação de morte iminente","CONTEXTO: pânico, ansiedade, estresse, dor","⚠ EXCLUIR causas ORGÂNICAS: TEP, asma, IAM, acidose metabólica (Kussmaul), intoxicação por salicilato, hipoxia"],
diag:["Anamnese + contexto","FR aumentada (>20-25), profunda","SatO₂ NORMAL ou alta (95-100%) — pista clave","Sinais de Trousseau / Chvostek positivos por tetania leve","⚠ EM DÚVIDA: D-dímero, gasometria (pH alto, pCO₂ baixo, HCO₃ normal), Rx tórax, ECG"],
exames:["SatO₂","Em dúvida: gasometria arterial, D-dímero, ECG, Rx tórax, troponina"],
rx:[
{etapa:"inicial", d:"⚠ EXCLUIR CAUSAS ORGÂNICAS PRIMEIRO — em paciente atípico ou primeira crise"},
{etapa:"inicial", d:"TEP, asma, IAM, sepse, acidose metabólica (DM, IRC), intoxicação salicilato, hipertireoidismo, anemia grave"},
{etapa:"inicial", d:"SE EM DÚVIDA: investigar antes de assumir hiperventilação psicogênica"},
{etapa:"escala", d:"⚠ TRATAMENTO da hiperventilação psicogênica"},
{etapa:"escala", d:"AMBIENTE TRANQUILO, isolar do agito"},
{etapa:"escala", d:"COMUNICAÇÃO CALMA — explicar fisiologia: 'você está respirando rápido demais, isso causa formigamento, mas é benigno e vai passar'"},
{etapa:"escala", d:"⚠ TÉCNICA RESPIRATÓRIA — ORIENTAR respiração LENTA"},
{etapa:"escala", d:"Inspirar pelo nariz 4 seg → segurar 4 seg → expirar lentamente 6-8 seg (técnica 4-4-6)"},
{etapa:"escala", d:"Repetir 5-10 ciclos"},
{etapa:"escala", d:"Pode-se contar JUNTO com o paciente — voz calma do profissional regula respiração"},
{etapa:"escala", d:"⚠ NÃO USAR SACO DE PAPEL — MITO PERIGOSO"},
{etapa:"escala", d:"Saco de papel REINALA CO₂ → em ASMA ou TEP escondidos = hipoxia profunda → óbito documentado"},
{etapa:"escala", d:"Casos de morte por hipoxia + descondicionamento médico-legal"},
{etapa:"escala", d:"Abandonado por sociedades de emergência globalmente"},
{etapa:"adj", d:"⚠ NÃO USAR INALAÇÃO COM ADRENALINA / SALBUTAMOL — não trata, pode piorar"},
{etapa:"adj", d:"⚠ MEDICAÇÃO se refratária à orientação respiratória"},
{etapa:"adj", d:"Diazepam 5-10 mg VO OU lorazepam 1-2 mg SL"},
{etapa:"adj", d:"Início 20-30 min. Não rotineiro em primeiro evento"},
{etapa:"adj", d:"INVESTIGAR transtorno de pânico subjacente"},
{etapa:"adj", d:"⚠ SE PARESTESIAS persistentes / tetania franca / espasmo carpopedal:"},
{etapa:"adj", d:"Pode haver HIPOCALCEMIA SUBJACENTE — dosar cálcio + magnésio (alcalose também 'cobre' cálcio iônico)"},
{etapa:"adj", d:"Em tetania franca: gluconato de cálcio 1 amp 10% IV lento + investigar causa"},
{etapa:"alta", d:"ORIENTAR — em casa: técnica respiração 4-4-6, exercício aeróbico regular, sono adequado"},
{etapa:"alta", d:"ENCAMINHAR psicologia / psiquiatria se crises recorrentes — ISRS + TCC"},
{etapa:"alta", d:"⚠ NUNCA orientar paciente a usar saco de papel em casa"},
],
alertas:[
{nivel:"crit", txt:"⚠ NÃO USAR SACO DE PAPEL — risco HIPOXIA grave em causa orgânica oculta (TEP, asma, IAM, anemia). MORTES DOCUMENTADAS. Mito perigoso."},
{nivel:"crit", txt:"EXCLUIR causas orgânicas (TEP, IAM, asma, acidose metabólica, intoxicação) em PRIMEIRA crise / paciente atípico / sintomas persistentes. Hiperventilação psicogênica é DIAGNÓSTICO DE EXCLUSÃO."},
{nivel:"warn", txt:"TÉCNICA 4-4-6 (inspirar 4s, segurar 4s, expirar 6s) é segura e eficaz. Profissional pode contar junto com paciente."},
{nivel:"warn", txt:"TETANIA FRANCA / espasmo carpopedal persistente: avaliar cálcio + magnésio."},
{nivel:"info", txt:"PARESTESIAS perioral + mãos/pés + tontura = alcalose respiratória. Reversível com respiração lenta."},
],
fluxo:null, diretriz:"AHA. NIH. Anti-mythological emergency literature."
},

/* ============== ABSCESSO PEQUENO — FIELD BLOCK ============== */
{id:"pulo-abscesso-pequeno", nome:"Drenar abscesso pequeno sem dor — field block perilesional", sis:"pulo", grav:"baixa",
cid:"L02", ciap:"S10",
sin:["Abscesso","I&D","Drenagem","Field block","Bloqueio perilesional","Abscesso cutâneo"],
def:"Abscesso pequeno cutâneo = drenagem é IMPRESCINDÍVEL (antibiótico isolado é insuficiente). Anestesia INTRALESIONAL é INEFICAZ (pH ácido inativa lidocaína). Usar BLOQUEIO PERILESIONAL (field block) — infiltrar ao redor da lesão, não dentro.",
quadro:["Abscesso cutâneo simples: flutuação, eritema, calor, dor — pele e tecido subcutâneo","Locais comuns: face (cuidado!), axila, virilha, glúteo, dedos","⚠ FACE: 'zona de risco' acima da boca (triângulo nariz-lábio-glabela) — drenagem precisa cautela por risco trombose seio cavernoso. Pequeno = lateral. Grande/profundo = ORL/cirurgia","⚠ PARANUNGEAL: orientar bem para evitar lesão da matriz ungueal","SIMPLES (< 5 cm, sem celulite extensa, sem febre, paciente sem imunossupressão): UBS","COMPLICADO (>5 cm, celulite extensa, febre, imunossupressão, mão, face, períneo, profundo): cirurgia"],
diag:["Inspeção: flutuação, fluctuação positiva","USG point-of-care: confirma cavidade fluida (diferencia de celulite simples)","Em casos atípicos: tomografia"],
exames:["Geralmente clínico","Cultura do material drenado se atípico, recorrente, imunossuprimido","USG se dúvida diagnóstica"],
rx:[
{etapa:"inicial", d:"⚠ AVALIAR localização e complexidade — encaminhar cirurgia se complicado"},
{etapa:"escala", d:"⚠ PREPARAÇÃO"},
{etapa:"escala", d:"Antissepsia ampla com clorexidina ou PVPI"},
{etapa:"escala", d:"Material: bisturi lâmina 11, gaze, hemostático, soro fisiológico, antibiótico tópico, curativo"},
{etapa:"escala", d:"⚠ ANESTESIA — BLOQUEIO PERILESIONAL (Field Block)"},
{etapa:"escala", d:"Lidocaína 1-2% com adrenalina (em locais NÃO terminais)"},
{etapa:"escala", d:"⚠ NÃO INFILTRAR DENTRO da cavidade do abscesso — pH ácido inativa lidocaína, dor permanece"},
{etapa:"escala", d:"INFILTRAR ao REDOR da lesão, em 4 quadrantes perilesionais, no plano subcutâneo"},
{etapa:"escala", d:"Aguardar 5-10 min para anestesia plena"},
{etapa:"escala", d:"⚠ ALTERNATIVA — cloreto de etila spray (vapocooling) — congelamento momentâneo da pele para incisão rápida"},
{etapa:"escala", d:"⚠ EM ABSCESSO PEQUENO E SUPERFICIAL: bloqueio com agulha 27-30G pode ser quase indolor"},
{etapa:"escala", d:"⚠ INCISÃO + DRENAGEM (I&D)"},
{etapa:"escala", d:"INCISÃO LINEAR com bisturi 11, paralela às linhas de Langer (cicatriz melhor)"},
{etapa:"escala", d:"Tamanho proporcional ao abscesso — abertura completa para drenagem"},
{etapa:"escala", d:"DRENAR pus → coletar para cultura se atípico"},
{etapa:"escala", d:"⚠ BREAKING THE LOCULAÇÕES — com hemostática curva ou dedo, romper septos internos para drenagem completa"},
{etapa:"escala", d:"IRRIGAR cavidade com SF (até líquido sair claro)"},
{etapa:"escala", d:"⚠ CURATIVO COM TAMPÃO (gauze packing) — EVIDÊNCIA RECENTE DESAFIA"},
{etapa:"escala", d:"Tradicionalmente: tampão de gaze (mecha) na cavidade, troca 1-2×/d × 5-7 dias"},
{etapa:"escala", d:"Estudos recentes: em abscessos pequenos não complicados, NÃO tamponar tem resultados equivalentes (menos dor, menos consulta)"},
{etapa:"escala", d:"PRÁTICA ATUAL: abscesso grande/profundo = tampão. Pequeno simples = sem tampão, curativo simples"},
{etapa:"adj", d:"⚠ ANTIBIÓTICO SISTÊMICO — COMPLEMENTAR a I&D em casos selecionados"},
{etapa:"adj", d:"SUFICIENTE I&D isolada em: abscesso pequeno (<2cm), sem celulite extensa, paciente imunocompetente, sem fatores de risco"},
{etapa:"adj", d:"INDICAR ATB se: abscesso >2 cm, celulite extensa, febre, imunossupressão, áreas críticas (face, mão, períneo, articulação), recorrência, falha I&D isolada"},
{etapa:"adj", d:"Cefalexina 500 mg 6/6h × 5-7 dias (cobertura S. aureus + Streptococcus)"},
{etapa:"adj", d:"⚠ Em comunidades com MRSA CA-MRSA frequente: SMX-TMP 800/160 mg 12/12h OU clindamicina 300 mg 8/8h"},
{etapa:"alta", d:"REAVALIAR em 24-72h"},
{etapa:"alta", d:"REMOVER tampão (se usado) em 24-48h → reavaliar"},
{etapa:"alta", d:"Educação: sinais de infecção sistêmica (febre, calafrios, eritema progressivo)"},
{etapa:"alta", d:"⚠ ABSCESSO RECORRENTE: investigar — pilonidal, MRSA, hidradenite supurativa, diabetes, imunossupressão"},
],
alertas:[
{nivel:"crit", txt:"⚠ ABSCESSO NA FACE (acima da boca — triângulo da morte): cautela. Drenagem inadequada pode causar trombose do seio cavernoso. Pequeno e lateral = OK. Grande/profundo/central = ORL/cirurgia."},
{nivel:"warn", txt:"⚠ ANESTESIA INTRA-ABSCESSO É INEFICAZ — pH ácido inativa lidocaína. USAR BLOQUEIO PERILESIONAL (field block)."},
{nivel:"warn", txt:"ABSCESSO PROFUNDO / GRANDE / COMPLICADO / em paciente imunossuprimido = ENCAMINHAR cirurgia."},
{nivel:"warn", txt:"ANTIBIÓTICO ISOLADO em abscesso é INSUFICIENTE — I&D é o tratamento. ATB é complementar em casos selecionados."},
{nivel:"info", txt:"ABSCESSO SIMPLES (<2 cm, sem celulite, paciente saudável): I&D isolada suficiente. ATB não obrigatório."},
{nivel:"info", txt:"CURATIVO COM TAMPÃO: tradicional mas evidência recente questiona em abscessos pequenos. Curativo simples pode ser suficiente."},
],
fluxo:null, diretriz:"IDSA. Tintinalli. Roberts & Hedges."
},

/* ============== INTRAÓSSEO ============== */
{id:"pulo-intraosseo", nome:"Acesso intraósseo de emergência — tibial / umeral", sis:"pulo", grav:"alta",
cid:"-", ciap:"-",
sin:["IO","Intraósseo","EZ-IO","Tibial proximal","Umeral proximal","Acesso de emergência"],
def:"ACESSO INTRAÓSSEO (IO) — quando acesso venoso falha em emergência. Inserção em 30-60 SEGUNDOS. Permite TODAS as medicações IV (incluindo adrenalina, vasopressor, sangue). Indicações: PCR, choque, sepse grave, qualquer paciente que precise de acesso urgente após falha venosa.",
quadro:["Emergência (PCR, choque, anafilaxia, sepse grave, queimadura extensa, politrauma) + falha de acesso venoso periférico após 2-3 tentativas","Manter máximo 24-48h, transferir para acesso convencional após estabilização","SÍTIOS — adulto e criança:","TIBIAL PROXIMAL (mais comum, mais fácil): 1-2 cm abaixo da tuberosidade da tíbia, face medial","ÚMERO PROXIMAL: tubérculo maior, 1 cm acima do colo cirúrgico","FÊMUR DISTAL (criança): 2 cm proximal ao côndilo medial","ESTERNO (adulto, raro)"],
diag:["Cenário emergencial — clínica","Avaliar local: pele íntegra, ausência de fratura no osso alvo"],
exames:["Conforme cenário clínico"],
rx:[
{etapa:"inicial", d:"⚠ INDICAÇÃO: emergência + falha ou impossibilidade de acesso venoso"},
{etapa:"inicial", d:"NÃO precisa pré-medicar (paciente em PCR) ou conforto em emergência hemodinâmica"},
{etapa:"escala", d:"⚠ EQUIPAMENTO"},
{etapa:"escala", d:"AGULHA INTRAÓSSEA (EZ-IO automática com broca, Cook manual, Jamshidi)"},
{etapa:"escala", d:"15G é padrão adulto, 18G pediátrico"},
{etapa:"escala", d:"Soro 0,9% + extensão + seringa 10 mL para flush"},
{etapa:"escala", d:"⚠ SÍTIOS DE PUNÇÃO — TIBIAL PROXIMAL (preferido)"},
{etapa:"escala", d:"(1) Localizar TUBEROSIDADE DA TÍBIA"},
{etapa:"escala", d:"(2) DESCER 1-2 cm e DESVIAR 1 cm MEDIAL (face medial achatada)"},
{etapa:"escala", d:"(3) Pele íntegra, sem fratura no membro"},
{etapa:"escala", d:"⚠ TÉCNICA DE INSERÇÃO"},
{etapa:"escala", d:"Antissepsia rápida com clorexidina/PVPI"},
{etapa:"escala", d:"Inserção PERPENDICULAR ao osso, em movimento ROTATÓRIO firme"},
{etapa:"escala", d:"Se broca elétrica (EZ-IO): pressão firme, gatilho aciona broca, agulha penetra cortical com 'pop' característico"},
{etapa:"escala", d:"PROFUNDIDADE: aproximadamente até a marca preta da agulha visível (~3 cm em adulto)"},
{etapa:"escala", d:"REMOVER trocarte (mandril interno)"},
{etapa:"escala", d:"⚠ CONFIRMAR posicionamento"},
{etapa:"escala", d:"AGULHA FIXA (não move livre)"},
{etapa:"escala", d:"Aspiração de MEDULA ÓSSEA (1-2 mL — pode não vir em todos)"},
{etapa:"escala", d:"FLUSH com 10 mL de SF — corre livremente sem extravasamento"},
{etapa:"escala", d:"⚠ ANALGESIA — antes da primeira infusão em PACIENTE CONSCIENTE"},
{etapa:"escala", d:"Lidocaína 2% sem adrenalina — 40 mg IO (adulto), 0,5 mg/kg (criança)"},
{etapa:"escala", d:"Aguardar 60 seg"},
{etapa:"escala", d:"⚠ DOR DA INFUSÃO INICIAL é importante em consciente — paciente em PCR não percebe"},
{etapa:"adj", d:"⚠ INFUSÃO"},
{etapa:"adj", d:"TODAS as medicações IV podem ser infundidas — adrenalina, atropina, amiodarona, fluidos, sangue, vasopressor"},
{etapa:"adj", d:"VELOCIDADE de infusão: PRESSÃO POSITIVA necessária para fluxo (bag de pressão ou seringa)"},
{etapa:"adj", d:"Doses são as MESMAS da via IV (não há ajuste)"},
{etapa:"adj", d:"⚠ CONTRAINDICAÇÕES"},
{etapa:"adj", d:"FRATURA do osso alvo"},
{etapa:"adj", d:"Infecção / queimadura no local"},
{etapa:"adj", d:"Cirurgia ortopédica recente no osso"},
{etapa:"adj", d:"Osteogênese imperfeita, osteoporose grave"},
{etapa:"adj", d:"⚠ COMPLICAÇÕES"},
{etapa:"adj", d:"EXTRAVASAMENTO (mais comum) — síndrome compartimental se vasoconstritor → remover agulha"},
{etapa:"adj", d:"Osteomielite (rara, ~0,6%)"},
{etapa:"adj", d:"Fratura iatrogênica (rara em técnica adequada)"},
{etapa:"alta", d:"⚠ MANTER MÁX 24-48h — transferir para acesso venoso convencional após estabilização"},
{etapa:"alta", d:"Remover IO antes de transferir paciente para hospital terciário se possível (acesso convencional)"},
{etapa:"alta", d:"DOCUMENTAR: indicação, sítio, hora de inserção, hora de remoção, complicações"},
],
alertas:[
{nivel:"crit", txt:"FRATURA, infecção ou queimadura no osso alvo = CONTRAINDICAÇÃO. Escolher outro sítio."},
{nivel:"crit", txt:"EXTRAVASAMENTO de vasoconstritor IO → síndrome compartimental + necrose. Confirmar posicionamento (sem extravasamento) antes de infundir noradrenalina/adrenalina."},
{nivel:"warn", txt:"ANALGESIA com LIDOCAÍNA IO antes de primeira infusão em PACIENTE CONSCIENTE — dor pode ser intensa. Aguardar 60 seg."},
{nivel:"warn", txt:"PRESSÃO POSITIVA é necessária para fluxo IO (gravidade não basta) — bag de pressão ou seringa de empuxo."},
{nivel:"warn", txt:"MAX 24-48h — transferir para acesso venoso convencional após estabilização. Osteomielite aumenta com tempo."},
{nivel:"info", txt:"EZ-IO (broca elétrica) é mais rápido e fácil que agulha manual. Custo significativo mas crescentemente disponível."},
{nivel:"info", txt:"TIBIAL PROXIMAL é o sítio mais usado em adulto e criança. Úmero proximal é alternativa eficaz."},
],
fluxo:null, diretriz:"AHA ACLS. PALS. ILCOR. EZ-IO training."
},

);
