/* ===========================================================
   VOVÔMINIC EMERGÊNCIA — BLOCO PALIATIVOS (Parte 1)
   Dor oncológica + Escada OMS + Dispneia + Náusea + Constipação
   =========================================================== */

/* ADICIONAR SISTEMA PALIATIVOS */
if (!SISTEMAS.pali) {
  SISTEMAS.pali = { nome: "Cuidados Paliativos", icone: "✿", cor: "#0F766E" };
}

PATOLOGIAS.push(

/* ============== DOR ONCOLÓGICA / ESCADA OMS ============== */
{id:"dor-oncologica", nome:"Dor Oncológica — Escada Analgésica da OMS adaptada", sis:"pali", grav:"variavel",
cid:"R52.1/G89", ciap:"A01",
sin:["Dor oncológica","Escada OMS","Morfina","Opioide","Analgesia paliativa","Dor crônica câncer","Dor mista"],
def:"⚠ Dor crônica em paciente oncológico — manejo baseado na ESCADA ANALGÉSICA DA OMS (1986, atualizada). PRINCÍPIO MODERNO: subir/descer pela escada conforme INTENSIDADE da dor (não 'tentar tudo até falhar'). Adjuvantes em qualquer degrau. Via VO preferida, SC quando VO inviável. ⚠ DOR SEVERA = MORFINA DIRETA — não passar por tramadol/codeína.",
quadro:["Avaliar DOR EM TODAS as consultas — 5º sinal vital","ESCALA: EVA 0-10 (numérica/visual analógica) OU verbal: leve / moderada / severa","Distinguir: NOCICEPTIVA somática (osso, partes moles — bem localizada), NOCICEPTIVA visceral (mal localizada, em cólica), NEUROPÁTICA (queimação, choque, parestesia — adjuvantes essenciais)","⚠ DOR INCIDENTAL: surge ao movimento — analgesia de RESGATE programada antes do esforço","⚠ DOR BREAKTHROUGH (irruptiva): pico súbito sobre dor basal controlada — resgate disponível"],
diag:["⚠ CLÍNICO — caracterizar: localização, intensidade (EVA), tipo (somática/visceral/neuropática), fatores de melhora/piora, duração, função afetada","Mapear dor em corpo (estudo de Brewer)","Avaliar IMPACTO em sono, humor, função, social","⚠ ESCALAS recomendadas: EVA, Brief Pain Inventory (BPI), Faces (em pediatria/cognição limitada), PAINAD (demência)"],
exames:["Rastrear sinais de DOR EMERGENTE: compressão medular (lombar+motor+esfincter), fratura patológica (dor mecânica nova), HIC, plexopatia","Imagem direcionada quando dor nova/mudança de padrão"],
rx:[
{etapa:"escala", d:"⚠ ⚠ ESCADA OMS — INTENSIDADE GUIA O DEGRAU"},
{etapa:"escala", d:"⚠ DEGRAU 1 — Dor LEVE (EVA 1-3)"},
{etapa:"escala", d:"DIPIRONA 500 mg-1 g VO 6/6h ad lib (REMUME, segura)", do:"500 mg-1 g 6/6h", via:"VO", o:""},
{etapa:"escala", d:"PARACETAMOL 500-1000 mg 6/6h (máx 4 g/d)", do:"500-1000 mg 6/6h", via:"VO", o:"⚠ Hepatotoxicidade em dose alta crônica + alcoólatra/hepatopatia."},
{etapa:"escala", d:"⚠ AINE — USO CAUTELOSO em oncológico (sangramento GI + nefrotox + cardiotox + plaquetopenia)", obs:"Ibuprofeno 600 mg 8/8h. Restringir a uso curto + paciente sem fatores de risco. EM PACIENTE COM TROMBOCITOPENIA, INSUFICIÊNCIA RENAL, IECA: ⚠ EVITAR."},
{etapa:"escala", d:"⚠ ADJUVANTES indicados desde DEGRAU 1 se houver componente:"},
{etapa:"escala", d:"DOR ÓSSEA: AINE quando seguro + BIFOSFONATOS (ác. zoledrônico 4 mg IV/mês — oncologia) + RADIOTERAPIA paliativa", obs:""},
{etapa:"escala", d:"DOR NEUROPÁTICA: GABAPENTINA 300 mg HS titular até 900-1800 mg/d OU PREGABALINA 75 mg 12/12h titular até 300-600 mg/d OU AMITRIPTILINA 10-25 mg HS (cuidado idoso) OU DULOXETINA 30-60 mg/d", obs:""},
{etapa:"escala", d:"COMPONENTE INFLAMATÓRIO/ANTITUMORAL/HIC: DEXAMETASONA 4-8 mg/d (reduzir gradativo). Em compressão medular: bolus 16 mg.", obs:""},
{etapa:"escala", d:"⚠ DEGRAU 2 — Dor MODERADA (EVA 4-6)"},
{etapa:"escala", d:"CODEÍNA 30-60 mg VO 4-6/6h (max 240 mg/d) — pro-droga, metabolismo CYP2D6 variável", do:"30-60 mg 4-6/6h", via:"VO", o:"⚠ ULTRAMETABOLIZADORES: morfinização rápida — risco intoxicação. POBRES METABOLIZADORES: ineficácia (~10% caucasianos). Crianças <12a + tonsilectomia: PROIBIDO."},
{etapa:"escala", d:"TRAMADOL 50-100 mg VO 4-6/6h (max 400 mg/d) — opioide fraco com ação serotoninérgica/noradrenérgica", do:"50-100 mg 4-6/6h", via:"VO", o:"⚠ Útil quando há componente NEUROPÁTICO + nociceptivo. Cautela: convulsão, síndrome serotoninérgica com ISRS, hiponatremia em idoso."},
{etapa:"escala", d:"⚠ EVOLUÇÃO MODERNA: o DEGRAU 2 está em desuso — em DOR MODERADA-SEVERA com expectativa de progressão, SUBIR DIRETO PARA MORFINA dose baixa (vide Degrau 3)"},
{etapa:"escala", d:"⚠ ⚠ DEGRAU 3 — Dor SEVERA (EVA 7-10) ou Moderada com expectativa de progressão"},
{etapa:"escala", d:"⚠ MORFINA — 1ª LINHA, padrão-ouro, mais barata + REMUME"},
{etapa:"escala", d:"⚠ INÍCIO em paciente OPIOIDE-NAIVE: MORFINA SIMPLES 5-10 mg VO 4/4h + RESGATE 5 mg VO 1/1h se dor não controlada", do:"5-10 mg 4/4h", via:"VO", o:"⚠ Idoso/caquético/IRC: 2,5-5 mg 4/4h. Após 24-48h: somar TOTAL DAS 24H (basal + resgates) → DIVIDIR EM 2-3 DOSES de MORFINA LP (12/12h ou 8/8h). Manter 10-15% da DOSE DIÁRIA como RESGATE 1/1h."},
{etapa:"escala", d:"⚠ MORFINA LIBERAÇÃO PROLONGADA (LP / MS Contin): 30 mg 12/12h é dose inicial habitual quando paciente já tolera morfina simples", do:"Calcular pelo total/24h", via:"VO", o:"⚠ ⚠ NÃO PARTIR / NÃO MASTIGAR a LP — engolir inteiro."},
{etapa:"escala", d:"⚠ DOR INCIDENTAL/IRRUPTIVA — RESGATE com MORFINA SIMPLES VO (10-15% da dose diária total) repetido em 1/1h conforme necessário", obs:""},
{etapa:"escala", d:"⚠ NÃO USAR DOSE MÁXIMA — TITULAR conforme efeito (não tem 'teto') + efeitos colaterais. Morfina pode chegar a 2-4 g/d em oncológico avançado."},
{etapa:"escala", d:"⚠ ⚠ VIA SUBCUTÂNEA (SC) — quando VO inviável (vômito, disfagia, obstrução, agonia)"},
{etapa:"escala", d:"⚠ CONVERSÃO VO → SC: dividir dose VO POR 2 (morfina VO 30 mg = morfina SC 15 mg)", obs:""},
{etapa:"escala", d:"Administrar 4/4h SC + resgate; OU em bomba SC contínua (4-8 mg/h ajustar conforme dor)", obs:""},
{etapa:"escala", d:"Sítios SC: deltoide, abdome, coxa, região peitoral; rodízio cada 5-7 dias", obs:""},
{etapa:"escala", d:"⚠ OUTROS OPIOIDES FORTES (alternativas)"},
{etapa:"escala", d:"OXICODONA LP 10-20 mg 12/12h — sem componente diferencial sobre morfina, mais cara, melhor em pruriginosos", do:"10-80 mg 12/12h", via:"VO", o:"Conversão: 10 mg oxicodona VO ≈ 15 mg morfina VO."},
{etapa:"escala", d:"⚠ FENTANIL TRANSDÉRMICO 12-100 mcg/h — em paciente ESTÁVEL com dor controlada, intolerância VO/SC, ESTOMA, vômitos refratários", do:"12-100 mcg/h trocar 72h", via:"TD", o:"⚠ ⚠ NÃO USAR EM DOR AGUDA / INSTÁVEL (demora 12-24h para atingir e 12-24h para sair após retirar). Conversão: morfina VO 60 mg/d ≈ fentanil 25 mcg/h. ⚠ Cuidado com febre (↑ absorção), calor, banho quente."},
{etapa:"escala", d:"⚠ ⚠ METADONA 2,5-5 mg 8-12/12h — uso em DOR REFRATÁRIA, dor neuropática complexa, rotação opioide", do:"2,5-30 mg 8-12/12h (titular lento)", via:"VO", o:"⚠ ⚠ ESPECIALISTA — meia-vida longa e variável (8-150h), conversão NÃO linear, QT longo, INTERAÇÕES MEDICAMENTOSAS importantes. Ótima em dor mista (NMDA antagonista)."},
{etapa:"escala", d:"⚠ BUPRENORFINA TRANSDÉRMICA 5-20 mcg/h trocar 7d — alternativa em IRC, idoso, intolerância morfina", do:"5-20 mcg/h 7/7d", via:"TD", o:""},
{etapa:"adj", d:"⚠ ROTAÇÃO DE OPIOIDES"},
{etapa:"adj", d:"⚠ INDICAÇÃO: efeitos colaterais intoleráveis (sedação, mioclonia, alucinação) OU eficácia insuficiente apesar de titulação OU toxicidade renal pela morfina"},
{etapa:"adj", d:"⚠ TABELA DE EQUIVALÊNCIA (MEDD — Morphine Equivalent Daily Dose):"},
{etapa:"adj", d:"Morfina VO ≡ 1 (base)"},
{etapa:"adj", d:"Codeína VO ≡ 0,15 (10 mg codeína = 1,5 mg morfina)"},
{etapa:"adj", d:"Tramadol VO ≡ 0,1-0,2 (50 mg tramadol ≈ 5-10 mg morfina)"},
{etapa:"adj", d:"Oxicodona VO ≡ 1,5 (10 mg oxicodona ≈ 15 mg morfina)"},
{etapa:"adj", d:"Morfina SC/IV ≡ 2-3× VO (15 mg SC = 30-45 mg VO)"},
{etapa:"adj", d:"Fentanil TD: 25 mcg/h ≈ morfina VO 60 mg/d"},
{etapa:"adj", d:"⚠ Metadona: NÃO LINEAR (1-12% conforme dose total — referência especializada)"},
{etapa:"adj", d:"⚠ ⚠ AO ROTACIONAR: REDUZIR 25-50% da dose calculada (cross-tolerance incompleta) — depois titular"},
{etapa:"adj", d:"⚠ EFEITOS COLATERAIS — PROFILAXIA ATIVA"},
{etapa:"adj", d:"⚠ CONSTIPAÇÃO (universal — 100%): PRESCREVER LAXATIVO COM A 1ª DOSE de opioide", obs:""},
{etapa:"adj", d:"BISACODIL 5-10 mg HS + LACTULOSE 15-30 mL 2-3×/d", do:"", via:"VO", o:""},
{etapa:"adj", d:"OU PEG (polietilenoglicol) 17 g/d", obs:""},
{etapa:"adj", d:"REFRATÁRIO: METILNALTREXONA 8-12 mg SC 1×/d", obs:"Antagonista periférico — não atravessa BHE, mantém analgesia."},
{etapa:"adj", d:"⚠ NÁUSEA (30% início — geralmente cede em 5-7d): HALOPERIDOL 0,5-2 mg VO 12/12h ad lib OU METOCLOPRAMIDA 10 mg 8/8h", obs:""},
{etapa:"adj", d:"⚠ SEDAÇÃO INICIAL: comum primeiros 3-5d, geralmente cede. Se persistir: reduzir 25% OU adicionar metilfenidato 5-10 mg manhã (off-label)", obs:""},
{etapa:"adj", d:"⚠ PRURIDO: anti-H1 (loratadina 10 mg/d). Refratário: rotacionar opioide", obs:""},
{etapa:"adj", d:"⚠ MIOCLONIA / DELIRIUM: sinal de TOXICIDADE — reduzir dose, hidratar, rotacionar (especialmente em IRC com morfina — acúmulo do M3G/M6G)", obs:""},
{etapa:"adj", d:"⚠ DEPRESSÃO RESPIRATÓRIA: raro em paciente em uso crônico bem titulado. Se ocorrer: reduzir dose; NALOXONA apenas se FR <8 ou sat <85% com bradipneia → 0,4 mg diluída em 9 mL, administrar 1 mL/min titular ao mínimo necessário (REVERSÃO COMPLETA pode precipitar dor severa + síndrome de abstinência)", obs:""},
{etapa:"alta", d:"⚠ COMUNICAÇÃO + DESMISTIFICAÇÃO"},
{etapa:"alta", d:"⚠ DESMITIFICAR opiofobia — paciente E família. 'Não é viciante quando usado para dor'. Reforçar regularidade vs PRN"},
{etapa:"alta", d:"⚠ ANTECIPAR resgates — prescrever desde início, ensinar registro de dose"},
{etapa:"alta", d:"DIÁRIO DA DOR — quando ocorre, intensidade, fator desencadeante, resgates usados"},
{etapa:"alta", d:"PSICOLOGIA, terapia ocupacional, fisioterapia — abordagem multimodal"},
{etapa:"alta", d:"⚠ DOR REFRATÁRIA / COMPLEXA → REFERENCIAR equipe especializada em paliativos / dor: bloqueios, neurolíticos (plexo celíaco), radioterapia paliativa, intervencionismo"},
],
alertas:[
{nivel:"crit", txt:"⚠ ⚠ DOR SEVERA EM ONCOLÓGICO = MORFINA DIRETA. Não 'subir devagar' por tramadol/codeína — perde tempo, gera frustração + sofrimento. Iniciar 5-10 mg VO 4/4h em opioide-naive."},
{nivel:"crit", txt:"⚠ CONSTIPAÇÃO É UNIVERSAL em opioide. PROFILAXIA com laxativo NA MESMA PRESCRIÇÃO desde a 1ª dose. Não esperar acontecer."},
{nivel:"crit", txt:"⚠ ⚠ COMPRESSÃO MEDULAR é EMERGÊNCIA. Dor lombar nova/progressiva em oncológico + qualquer sinal motor/sensitivo/esfincteriano = DEXAMETASONA 16 mg IV imediata + RM coluna urgente + radioterapia/cirurgia urgente."},
{nivel:"crit", txt:"⚠ OPIOIDE EM IRC: morfina acumula metabólitos NEUROTÓXICOS (M3G — mioclonia, alucinação, delirium). Em TFG <30: ROTACIONAR para fentanil/buprenorfina/metadona OU reduzir dose 25-50%."},
{nivel:"warn", txt:"⚠ Fentanil TRANSDÉRMICO — NUNCA em DOR INSTÁVEL/AGUDA (demora 12-24h para atingir e 12-24h após retirar). Indicado apenas em dor estável bem-controlada por morfina prévia."},
{nivel:"warn", txt:"⚠ METADONA: meia-vida muito variável, conversão NÃO linear, QT longo, múltiplas interações — USO ESPECIALISTA."},
{nivel:"warn", txt:"⚠ Codeína: ULTRAMETABOLIZADORES (CYP2D6) podem ter intoxicação aguda. CRIANÇA <12a + tonsilectomia/adenoidectomia: PROIBIDO (FDA Black Box — mortes documentadas)."},
{nivel:"warn", txt:"⚠ Tramadol + ISRS/IMAO/Tricíclico = SÍNDROME SEROTONINÉRGICA. Tramadol + Bupropiona = CONVULSÃO."},
{nivel:"info", txt:"⚠ AINE em oncológico com risco — sangramento GI, plaquetopenia, IRC, IECA — USE COM CAUTELA. Dor óssea pode beneficiar de DEXAMETASONA + bifosfonato + radioterapia."},
{nivel:"info", txt:"DOR NEUROPÁTICA: gabapentina/pregabalina + amitriptilina + duloxetina. Resposta gradual 2-4 sem. Esperar antes de mudar."},
{nivel:"info", txt:"REFRATARIEDADE: pensar em compressão medular, fratura patológica, plexopatia, dor neuropática mal abordada, sofrimento existencial 'total pain' (Cicely Saunders)."},
],
fluxo:"escada-oms", diretriz:"OMS Cancer Pain Relief; ANCP (Academia Nacional de Cuidados Paliativos); IAHPC; ESMO."
},

/* ============== DISPNEIA EM PALIATIVOS ============== */
{id:"dispneia-paliativa", nome:"Dispneia em Cuidados Paliativos — manejo sintomático", sis:"pali", grav:"moderada",
cid:"R06.0", ciap:"R02",
sin:["Dispneia paliativa","Falta de ar paliativos","Fome de ar","Morfina dispneia","Oxigenoterapia paliativa"],
def:"⚠ DISPNEIA é o sintoma mais incapacitante em paliativos — gera angústia tão intensa quanto dor. ⚠ MORFINA em DOSE BAIXA é 1ª linha (efeito independente da analgesia). Manejar CAUSA + sintoma + ansiedade associada. Não confundir com hipoxemia (que pode coexistir mas não é causa única da sensação).",
quadro:["⚠ Sensação SUBJETIVA de respiração desconfortável — paciente é fonte primária","Pode haver: taquipneia, uso de musculatura acessória, cianose, tiragem","⚠ Hipoxemia (Sat <90%) pode estar presente OU NÃO — dispneia é SENSAÇÃO, não hipoxemia","⚠ ANSIEDADE quase sempre presente — círculo vicioso ansiedade ↔ dispneia","⚠ Causas: progressão tumoral pulmonar, derrame pleural, linfangite carcinomatosa, TEP, ICC, anemia, infecção, fadiga muscular respiratória, ansiedade isolada"],
diag:["⚠ CLÍNICO — escutar o paciente. Escala 0-10 análoga à dor","Saturometria — útil mas NÃO substitui sensação","Exame físico: ausculta (estertor, sibilo, derrame), uso de musculatura, esforço","Imagem direcionada conforme suspeita: Rx tórax (derrame, infiltrado, massa), USG pulmonar (derrame, B-lines)","Considerar D-dímero / angio-TC se TEP possível e plano modificará conduta","⚠ Em paciente em FIM DE VIDA: investigação minimalista — tratar sintoma é prioridade"],
exames:["Saturometria","Rx tórax / USG conforme suspeita","Hemograma (anemia)","Avaliar causa reversível: derrame (toracocentese paliativa), broncoespasmo (broncodilatador), infecção (ATB)"],
rx:[
{etapa:"inicial", d:"⚠ AVALIAR + TRATAR CAUSA REVERSÍVEL primeiro"},
{etapa:"inicial", d:"Derrame pleural sintomático: TORACOCENTESE PALIATIVA (até 1-1,5 L); se recidiva → drenagem com cateter pleural permanente / pleurodese"},
{etapa:"inicial", d:"Broncoespasmo: SALBUTAMOL inalação 5 mg + IPRATRÓPIO 0,5 mg + considerar prednisolona 40 mg/d × 5d"},
{etapa:"inicial", d:"Infecção: ATB EMPÍRICO (mesmo em paliativos quando há benefício sintomático)"},
{etapa:"inicial", d:"Anemia sintomática (Hb <8 + dispneia): transfusão paliativa de CH 1 U"},
{etapa:"inicial", d:"⚠ ⚠ NÃO investigar TEP em paciente em fase ATIVA DE MORTE — tratar com morfina"},
{etapa:"escala", d:"⚠ ⚠ MEDIDAS NÃO-FARMACOLÓGICAS — sempre primeiro/em paralelo"},
{etapa:"escala", d:"⚠ AR FRESCO na FACE — ventilador apontado para face do paciente. Trigeminal estímulo central reduz sensação de dispneia. NÃO é placebo — evidência sólida.", obs:""},
{etapa:"escala", d:"POSIÇÃO ortostática / 'cocheiro' (sentado inclinado para frente)", obs:""},
{etapa:"escala", d:"AMBIENTE: janela aberta, espaço amplo, sem aglomeração", obs:""},
{etapa:"escala", d:"TÉCNICA RESPIRATÓRIA — respiração com lábios semicerrados, diafragmática", obs:""},
{etapa:"escala", d:"⚠ COMUNICAÇÃO TRANQUILA, presença, reasseguramento — reduz ansiedade", obs:""},
{etapa:"escala", d:"FISIOTERAPIA RESPIRATÓRIA — drenagem, técnicas de tosse, vibrocompressão", obs:""},
{etapa:"escala", d:"⚠ ⚠ MORFINA — 1ª LINHA FARMACOLÓGICA"},
{etapa:"escala", d:"⚠ OPIOIDE-NAIVE: MORFINA 2,5-5 mg VO 4/4h + RESGATE 2,5 mg 1/1h conforme necessário", do:"2,5-5 mg 4/4h", via:"VO", o:"⚠ Dose MENOR que para dor. Aumentar 25-50% se inefetiva. Estável: rotacionar para LP."},
{etapa:"escala", d:"⚠ EM USO DE OPIOIDE: adicionar 25-50% à dose habitual OU aumentar a dose basal", obs:""},
{etapa:"escala", d:"⚠ VIA SC: MORFINA 2-2,5 mg SC 4/4h se VO inviável", do:"2-2,5 mg 4/4h", via:"SC", o:""},
{etapa:"escala", d:"⚠ INALAÇÃO de MORFINA: ⚠ NÃO RECOMENDADA — evidência negativa", obs:""},
{etapa:"escala", d:"⚠ BENZODIAZEPÍNICO — quando há COMPONENTE ANSIEDADE proeminente ou dispneia refratária a opioide"},
{etapa:"escala", d:"LORAZEPAM 0,5-1 mg VO/SL 6-8/8h ad lib (preferido por meia-vida intermediária)", do:"0,5-1 mg 6-8/8h", via:"VO/SL", o:""},
{etapa:"escala", d:"MIDAZOLAM 1-2,5 mg SC 4/4h se sintomas mais agudos ou SC necessária", do:"1-2,5 mg 4/4h", via:"SC", o:""},
{etapa:"escala", d:"⚠ Diazepam pode ser usado mas meia-vida longa em idoso/IH"},
{etapa:"escala", d:"⚠ OXIGENOTERAPIA — papel limitado"},
{etapa:"escala", d:"⚠ INDICADA quando Sat <90% E paciente sente alívio (ensaio terapêutico)", obs:""},
{etapa:"escala", d:"Em paciente NORMOXÊMICO: ar fresco/ventilador é EQUIVALENTE ou superior", obs:""},
{etapa:"escala", d:"⚠ NÃO PERSISTIR em paciente que não sente alívio — máscara/cânula podem aumentar desconforto, isolamento, ressecamento mucoso"},
{etapa:"escala", d:"⚠ Em FASE ATIVA DE MORTE: geralmente RETIRAR oxigênio se não estiver dando conforto", obs:""},
{etapa:"adj", d:"⚠ DEXAMETASONA — em dispneia por LINFANGITE CARCINOMATOSA, sd. de VEIA CAVA SUPERIOR, edema peritumoral"},
{etapa:"adj", d:"4-8 mg VO/SC/IV manhã (até 16 mg em VCS aguda), titular para dose mínima efetiva", obs:""},
{etapa:"adj", d:"⚠ FUROSEMIDA — em ICC descompensada / congestão pulmonar"},
{etapa:"adj", d:"⚠ INALAÇÃO DE LIDOCAÍNA — para tosse refratária associada (off-label, especializado)", obs:""},
{etapa:"adj", d:"⚠ DISPNEIA TERMINAL REFRATÁRIA — considerar SEDAÇÃO PALIATIVA (vide patologia 'sedacao-paliativa')"},
{etapa:"alta", d:"⚠ COMUNICAÇÃO É TRATAMENTO — sentar, presença, validar 'isso é assustador, vamos cuidar'"},
{etapa:"alta", d:"INSTRUIR FAMÍLIA: nem todo aumento de respiração = sofrimento. Em fase ativa: respiração agônica/Cheyne-Stokes pode parecer angustiante para família mas paciente raramente sente"},
{etapa:"alta", d:"PLANO DE CRISE: prescrição de resgate domiciliar (morfina simples, lorazepam SL, midazolam SC) com instruções claras"},
],
alertas:[
{nivel:"crit", txt:"⚠ ⚠ MORFINA EM DOSE BAIXA é 1ª LINHA para dispneia paliativa. Evidência sólida. Iniciar 2,5-5 mg VO 4/4h em opioide-naive. ⚠ Dispneia ≠ dor — dose menor."},
{nivel:"crit", txt:"⚠ AR FRESCO NA FACE (ventilador) tem evidência sólida — não é placebo. Estímulo trigeminal reduz sensação. Usar SEMPRE como medida não-farmacológica primária."},
{nivel:"warn", txt:"⚠ OXIGÊNIO tem papel LIMITADO — só quando Sat <90% E paciente sente alívio em ensaio. Em normoxêmico: ar fresco/ventilador é equivalente."},
{nivel:"warn", txt:"⚠ BENZODIAZEPÍNICO em dispneia: 2ª linha — para componente ansioso ou refratariedade. NÃO INICIAR como 1ª linha (morfina vem primeiro)."},
{nivel:"warn", txt:"⚠ NÃO INVESTIGAR TEP em paciente em FASE ATIVA DE MORTE — tratar com morfina + suporte. Em paciente com horizonte de meses: avaliar individualmente."},
{nivel:"info", txt:"⚠ Em fase ativa: RESPIRAÇÃO AGÔNICA / Cheyne-Stokes é normal. Pode parecer angustiante para família mas paciente raramente sente. INSTRUIR a família é parte do tratamento."},
{nivel:"info", txt:"⚠ DISPNEIA REFRATÁRIA a opioide + BZD + medidas: considerar SEDAÇÃO PALIATIVA proporcional."},
],
fluxo:null, diretriz:"ATS/ERS Dispneia Paliativa 2010-2021; ANCP; Hui et al."
},

/* ============== NÁUSEA E VÔMITO EM PALIATIVOS ============== */
{id:"nausea-paliativa", nome:"Náusea e Vômito em Paliativos — manejo por mecanismo", sis:"pali", grav:"moderada",
cid:"R11", ciap:"D09",
sin:["Náusea paliativa","Vômito paliativo","Antiemético","Haloperidol náusea","Metoclopramida","Ondansetrona"],
def:"⚠ Náusea/vômito acometem 40-70% de pacientes paliativos. ⚠ CHAVE: identificar MECANISMO predominante (4-5 mecanismos comuns) — o antiemético DEPENDE do mecanismo. Tratar com 'qualquer um' geralmente falha. ⚠ Sempre via SC quando vômito persistente.",
quadro:["⚠ 5 MECANISMOS PRINCIPAIS (identificar para escolher droga):","(1) ⚠ ESTÍMULO QUÍMICO via CTZ (zona quimioceptora) — opioides, quimio recente, uremia, hipercalcemia, hiponatremia, infecção, drogas. Receptores D2 + 5-HT3","(2) ⚠ ESTASE GÁSTRICA / OBSTRUÇÃO PARCIAL — saciedade precoce, plenitude, refluxo. Tratamento PROCINÉTICO","(3) ⚠ ESTÍMULO VESTIBULAR / movimento — piora com mudança postural. Receptores H1 + muscarínicos","(4) ⚠ ESTÍMULO CORTICAL — ansiedade, ambiente, antecipação. BZD + suporte","(5) ⚠ ESTÍMULO VAGAL / mecanorreceptores — distensão GI, tumor abdominal, constipação, OBSTRUÇÃO MECÂNICA INTESTINAL — corticoide + opioide + antiemético + considerar octreotida","⚠ Constipação + impactação fecal é causa frequente e SUBESTIMADA — sempre avaliar"],
diag:["⚠ ANAMNESE direcionada ao mecanismo:","'Quando começou?' (relação com novo medicamento, quimio, progressão tumoral)","'Sensação de plenitude precoce, refluxo, eructação?' → ESTASE","'Náusea piora com movimento?' → VESTIBULAR","'Ansiedade, antecipação à comida/quimio?' → CORTICAL","'Distensão abdominal, parada de eliminação?' → OBSTRUÇÃO MECÂNICA","Examinar abdome: distensão, RHA (silente / metálicos / aumentados), massas, fecaloma","Toque retal — descartar impactação","Investigar: eletrólitos (Na, Ca), função renal (uremia), causa infecciosa"],
exames:["Eletrólitos (Na, Ca, Mg, K)","Função renal e hepática","Glicemia","⚠ Rx abdome em pé/decúbito — descartar OBSTRUÇÃO INTESTINAL (níveis hidroaéreos, distensão de alças)","Hemograma + PCR se infecção possível"],
rx:[
{etapa:"inicial", d:"⚠ AVALIAR + TRATAR causas REVERSÍVEIS específicas"},
{etapa:"inicial", d:"Hipercalcemia (Ca corrigido >12): hidratação salina + ác. zoledrônico"},
{etapa:"inicial", d:"Hiponatremia: investigar/corrigir SIADH, reposição cuidadosa"},
{etapa:"inicial", d:"Uremia: avaliar diálise paliativa OU controle sintomático"},
{etapa:"inicial", d:"⚠ Constipação grave / impactação: tratar (laxativos, lavagem retal, supositório)"},
{etapa:"inicial", d:"⚠ HIC: dexametasona 8-16 mg/d"},
{etapa:"escala", d:"⚠ ⚠ ESCOLHER ANTIEMÉTICO PELO MECANISMO"},
{etapa:"escala", d:"⚠ (1) CTZ / QUÍMICO (opioide, quimio, uremia, hipercalcemia)"},
{etapa:"escala", d:"⚠ HALOPERIDOL 0,5-2 mg VO/SC 12/12h ad lib — 1ª LINHA. Antagonista D2. Baixa sedação.", do:"0,5-2 mg 12/12h", via:"VO/SC", o:""},
{etapa:"escala", d:"OU METOCLOPRAMIDA 10 mg VO/SC 6-8/8h (max 30 mg/d — limitação por extrapiramidal)", do:"10 mg 6/6h", via:"VO/SC", o:"Ação dupla: anti-D2 + procinética. ⚠ Sintomas extrapiramidais."},
{etapa:"escala", d:"OU ONDANSETRONA 4-8 mg VO/SC 8/8h — útil em náusea por QUIMIO (5-HT3), pós-op, gestação", do:"4-8 mg 8/8h", via:"VO/SC", o:"⚠ Causa CONSTIPAÇÃO + QT longo."},
{etapa:"escala", d:"⚠ (2) ESTASE GÁSTRICA / saciedade precoce / dispepsia / náusea pós-prandial"},
{etapa:"escala", d:"⚠ METOCLOPRAMIDA 10 mg VO/SC 6-8/8h ANTES DAS REFEIÇÕES — 1ª LINHA (procinética via 5-HT4 + anti-D2)", do:"10 mg 6/6h", via:"VO/SC", o:""},
{etapa:"escala", d:"BROMOPRIDA 10 mg VO/SC 6-8/8h — similar à metoclopramida", obs:""},
{etapa:"escala", d:"⚠ ⚠ NÃO USAR em SUSPEITA DE OBSTRUÇÃO MECÂNICA (cólica, distensão, vômito persistente) — pode piorar"},
{etapa:"escala", d:"⚠ (3) VESTIBULAR / cinetose / mudança postural"},
{etapa:"escala", d:"DIMENIDRINATO 50-100 mg VO 6-8/8h — anti-H1 + anticolinérgico", do:"50-100 mg 6-8/8h", via:"VO", o:""},
{etapa:"escala", d:"PROMETAZINA 25 mg VO/IM 8-12/12h — anti-H1 + anti-D2 (multimecanismo, sedativa)", do:"25 mg 8-12/12h", via:"VO/IM", o:""},
{etapa:"escala", d:"ESCOPOLAMINA TRANSDÉRMICA — útil em vestibular + sialorreia (adesivo retroauricular)", obs:""},
{etapa:"escala", d:"⚠ (4) CORTICAL / ansiedade / antecipação"},
{etapa:"escala", d:"⚠ LORAZEPAM 0,5-1 mg VO/SL antes do estímulo (ex: antes da quimio)", do:"0,5-1 mg", via:"SL/VO", o:""},
{etapa:"escala", d:"+ Suporte psicoterapêutico, técnicas de relaxamento, ambiente", obs:""},
{etapa:"escala", d:"⚠ (5) MECANORRECEPTORES / OBSTRUÇÃO INTESTINAL MALIGNA"},
{etapa:"escala", d:"⚠ ⚠ ABORDAGEM TRÍADE — corticoide + opioide + antiemético + ANTI-SECRETOR"},
{etapa:"escala", d:"DEXAMETASONA 8-16 mg/d SC/IV (reduz edema peritumoral, anti-inflamatório, antiemético)", do:"8-16 mg/d", via:"SC/IV", o:""},
{etapa:"escala", d:"MORFINA SC para dor/cólica + ANTIEMÉTICO (haloperidol; NÃO metoclopramida — pode piorar)", obs:""},
{etapa:"escala", d:"⚠ ⚠ HIOSCINA BUTILBROMETO (Buscopan) 20 mg SC 6/6h — antiespasmódico para cólica obstrutiva", do:"20 mg 6/6h", via:"SC", o:""},
{etapa:"escala", d:"⚠ ⚠ OCTREOTIDA 100-300 mcg SC 8/8h OU 300-900 mcg/d SC contínua — REDUZ secreção GI, descomprime alça obstruída (alternativa cirúrgica em paciente fora de cirurgia)", do:"100-900 mcg/d ÷ 8/8h ou contínua", via:"SC", o:"⚠ Especialista. Custo alto."},
{etapa:"escala", d:"⚠ Avaliar SNG de alívio (descompressiva) — em obstrução alta, vômito incoercível, conforto", obs:""},
{etapa:"adj", d:"⚠ NÁUSEA REFRATÁRIA — combinar drogas com MECANISMOS DIFERENTES"},
{etapa:"adj", d:"Ex: haloperidol (D2) + ondansetrona (5-HT3) + dexametasona (anti-inflamatória)", obs:""},
{etapa:"adj", d:"⚠ ⚠ LEVOMEPROMAZINA 6,25-12,5 mg VO/SC 12-24/24h — antiemético de AMPLO ESPECTRO (D2, 5-HT, H1, muscarínico) — 'limpa-tudo' em refratários", do:"6,25-12,5 mg HS ou 12/12h", via:"VO/SC", o:"⚠ Sedativa. Útil em fase mais avançada."},
{etapa:"adj", d:"OLANZAPINA 2,5-10 mg/d — alternativa em refratários (off-label, evidência crescente)", obs:""},
{etapa:"adj", d:"DRONABINOL / canabinoides — em alguns países disponíveis", obs:""},
{etapa:"alta", d:"⚠ MEDIDAS NÃO-FARMACOLÓGICAS"},
{etapa:"alta", d:"REFEIÇÕES PEQUENAS e frequentes; alimentos frios podem ser melhor tolerados; evitar odores fortes"},
{etapa:"alta", d:"GENGIBRE 1-2 g/d (chá, balas) — evidência modesta", obs:""},
{etapa:"alta", d:"AROMATERAPIA (menta, limão) — alguns pacientes respondem", obs:""},
{etapa:"alta", d:"AMBIENTE ventilado, sem odores de cozinha, posição confortável", obs:""},
],
alertas:[
{nivel:"crit", txt:"⚠ ⚠ IDENTIFICAR MECANISMO — antiemético sem mecanismo é tiro no escuro. Haloperidol em CTZ. Metoclopramida em ESTASE. Anti-H1 em VESTIBULAR. BZD em CORTICAL. Tríade (cortico + opioide + anti-D2 + hioscina + octreotida) em OBSTRUÇÃO."},
{nivel:"crit", txt:"⚠ ⚠ METOCLOPRAMIDA / BROMOPRIDA são CONTRAINDICADAS em OBSTRUÇÃO INTESTINAL MECÂNICA — procinéticos pioram. Em suspeita: parar e investigar."},
{nivel:"warn", txt:"⚠ ⚠ Constipação grave / impactação fecal é CAUSA FREQUENTE e SUBESTIMADA de náusea/vômito em paliativos. Toque retal + Rx abdome antes de assumir mecanismo central."},
{nivel:"warn", txt:"⚠ ONDANSETRONA causa CONSTIPAÇÃO + QT longo. Em paciente já em opioide (constipação) ou em risco cardíaco: cuidado."},
{nivel:"warn", txt:"⚠ HALOPERIDOL e PROMETAZINA em IDOSO: risco extrapiramidal + sedação. Doses baixas (haloperidol 0,5-1 mg)."},
{nivel:"info", txt:"⚠ OBSTRUÇÃO INTESTINAL MALIGNA — abordagem tríade: dexametasona + opioide + hioscina butilbrometo (antiespasmódico) + considerar octreotida (anti-secretor). SNG descompressiva quando vômito incoercível."},
{nivel:"info", txt:"⚠ NÁUSEA REFRATÁRIA: combinar drogas com mecanismos DIFERENTES, ou usar LEVOMEPROMAZINA (espectro amplo)."},
],
fluxo:"nausea-paliativa", diretriz:"NICE Palliative Care; ANCP; ESMO."
},

/* ============== CONSTIPAÇÃO INDUZIDA POR OPIOIDE ============== */
{id:"constipacao-opioide", nome:"Constipação Induzida por Opioide (CIO) — profilaxia e manejo", sis:"pali", grav:"moderada",
cid:"K59.0", ciap:"D12",
sin:["Constipação opioide","CIO","Laxativo paliativo","Bisacodil","Lactulose","Metilnaltrexona","Naloxegol"],
def:"⚠ ⚠ TODO paciente em opioide DESENVOLVE constipação (>90%). ⚠ É EFEITO COLATERAL PREVISÍVEL — sem tolerância significativa (não 'passa com tempo'). ⚠ PROFILAXIA ATIVA com laxativo na MESMA PRESCRIÇÃO do opioide. Falhar em prescrever laxativo = falhar como prescritor.",
quadro:["⚠ Sintomas: evacuação <3×/sem, fezes endurecidas, esforço, sensação de evacuação incompleta, distensão, dor abdominal","⚠ Risco de IMPACTAÇÃO FECAL (fecaloma): toque retal — fezes endurecidas em ampola; em alta: paradoxalmente DIARREIA (escape ao redor do fecaloma) — não tratar como diarreia comum","Pode levar a: náusea, anorexia, distensão, dor, pseudo-obstrução"],
diag:["⚠ Anamnese sobre hábito intestinal — frequência, consistência (Bristol 1-7), esforço, sensação","⚠ Toque retal em qualquer paciente com sintomas — DESCARTAR FECALOMA","Examinar abdome — distensão, dor, massas, RHA","Rx abdome se obstrução suspeita ou fecaloma alto"],
exames:["Geralmente clínico","Eletrólitos (K, Ca — hipocalemia e hipercalcemia agravam)","Rx abdome se suspeita obstrução"],
rx:[
{etapa:"inicial", d:"⚠ ⚠ PROFILAXIA OBRIGATÓRIA — prescrever laxativo COM A PRIMEIRA DOSE de opioide"},
{etapa:"inicial", d:"⚠ ⚠ NÃO ESPERAR aparecer — manejar antes"},
{etapa:"escala", d:"⚠ ESCALONAMENTO LAXATIVO"},
{etapa:"escala", d:"⚠ ESQUEMA INICIAL — COMBINAR estimulante + osmótico"},
{etapa:"escala", d:"BISACODIL 5-10 mg VO HS (estimulante de motilidade)", do:"5-10 mg HS", via:"VO", o:""},
{etapa:"escala", d:"+ LACTULOSE 15-30 mL VO 12/12h ad lib (osmótico)", do:"15-30 mL 12/12h", via:"VO", o:"Pode causar flatulência. Sabor adocicado."},
{etapa:"escala", d:"OU PEG (POLIETILENOGLICOL) 17 g em 240 mL água VO 1×/d (osmótico, melhor tolerado)", do:"17 g/d", via:"VO", o:"⚠ Custo maior."},
{etapa:"escala", d:"⚠ AVALIAR EFICÁCIA em 2-3 DIAS — fezes Bristol 3-4, sem esforço"},
{etapa:"adj", d:"⚠ ESCALONAR se inadequado:"},
{etapa:"adj", d:"(1) Aumentar BISACODIL para 10-15 mg HS"},
{etapa:"adj", d:"(2) Adicionar SUPOSITÓRIO de GLICERINA (estimulante retal) — se inicialmente sem evacuação"},
{etapa:"adj", d:"(3) Adicionar ÓLEO MINERAL 15-30 mL VO HS (lubrificante)", obs:"⚠ Cuidado aspiração em idoso/disfagia."},
{etapa:"adj", d:"(4) Aumentar LACTULOSE para 30-45 mL 8/8h"},
{etapa:"adj", d:"(5) SENE 12-50 mg HS (estimulante alternativo)"},
{etapa:"adj", d:"⚠ ⚠ REFRATÁRIO (apesar de combinação otimizada >5-7 dias):"},
{etapa:"adj", d:"⚠ METILNALTREXONA 8 mg SC (peso 38-62 kg) ou 12 mg SC (>62 kg) cada 48h", do:"8-12 mg SC cada 48h", via:"SC", o:"⚠ Antagonista μ-opioide PERIFÉRICO — não atravessa BHE, mantém analgesia. Efeito laxativo em 30-60 min. ⚠ NÃO usar em obstrução suspeita."},
{etapa:"adj", d:"⚠ NALOXEGOL 25 mg VO 1×/d em jejum (antagonista μ oral)", obs:""},
{etapa:"adj", d:"⚠ NALDEMEDINA 0,2 mg VO 1×/d", obs:"Alternativa."},
{etapa:"adj", d:"⚠ FECALOMA — diagnóstico + tratamento"},
{etapa:"adj", d:"⚠ Toque retal — confirma fezes endurecidas em ampola"},
{etapa:"adj", d:"DESIMPACTAÇÃO MANUAL — com luva lubrificada, paciente em decúbito lateral (analgesia/sedação leve pode ser necessária)"},
{etapa:"adj", d:"SUPOSITÓRIO GLICERINA + LAVAGEM RETAL com solução fisiológica (200-500 mL) — para amolecer"},
{etapa:"adj", d:"⚠ DESPRESCREVER 'enema de fosfato' em IDOSO/IRC — risco hiperfosfatemia"},
{etapa:"alta", d:"⚠ MEDIDAS NÃO-FARMACOLÓGICAS"},
{etapa:"alta", d:"Hidratação conforme tolerância (não forçar em fase ativa)"},
{etapa:"alta", d:"Fibras solúveis em paciente FUNCIONAL — em fase avançada/anoréxico/desidratado: ⚠ EVITAR (sem água, pode piorar)"},
{etapa:"alta", d:"Posição ortostática para evacuação se possível; banquinho sob pés"},
{etapa:"alta", d:"Privacidade, tempo, ambiente confortável"},
{etapa:"alta", d:"⚠ ATIVIDADE FÍSICA conforme tolerância — caminhada, mobilização"},
],
alertas:[
{nivel:"crit", txt:"⚠ ⚠ TODO PACIENTE EM OPIOIDE precisa de LAXATIVO PROFILÁTICO desde a 1ª dose. NÃO é opcional. NÃO esperar acontecer. Bisacodil 10 mg HS + Lactulose 15-30 mL 12/12h é esquema-base."},
{nivel:"crit", txt:"⚠ FECALOMA pode se manifestar como DIARREIA paradoxal (escape ao redor) — NÃO TRATAR como diarreia comum. Toque retal antes."},
{nivel:"warn", txt:"⚠ FIBRAS solúveis (psyllium, fibras) NÃO são adequadas em fase avançada/anoréxico/desidratado — sem água, pioram. Usar em paciente com função GI preservada e hidratação adequada."},
{nivel:"warn", txt:"⚠ ENEMA DE FOSFATO em idoso/IRC: risco HIPERFOSFATEMIA / hipocalcemia. Preferir lavagem com solução fisiológica."},
{nivel:"warn", txt:"⚠ METILNALTREXONA / NALOXEGOL: antagonistas PERIFÉRICOS — mantém analgesia central. Indicado em CIO REFRATÁRIA. ⚠ NÃO USAR em obstrução intestinal suspeita."},
{nivel:"info", txt:"⚠ OUTROS opioides têm grau variável de constipação. METADONA, FENTANIL TD, BUPRENORFINA TD: constipação MENOR. Considerar rotação em refratários."},
],
fluxo:"constipacao-opioide", diretriz:"ANCP; MASCC; ESMO Constipation."
},

);
