/* PARTE 3: Infecto + Anafilaxia + Toxicologia */
PATOLOGIAS.push(
/* ============== INFECTOLOGIA ============== */
{
  id:"sepse", sis:"infecto", grav:"alta",
  nome:"Sepse e Choque Séptico",
  sin:["sepse","choque séptico","SSC","hour-1 bundle"],
  def:"Sepse: disfunção orgânica ameaçadora à vida causada por resposta desregulada à infecção (SOFA ≥2). Choque séptico: sepse + hipotensão refratária a volume + lactato >2 + vasopressor para PAM ≥65.",
  exames:["Lactato (repetir 2h depois se >2)","Hemoculturas ANTES do ATB","EAS + urocultura","RX tórax","Hemograma, função renal, gasometria, eletrólitos, coagulograma","PCR/procalcitonina","Culturas dirigidas: LCR, líquido peritoneal, secreção"],
  rx:[
    {etapa:"inicial", d:"Reconhecimento + qSOFA/SOFA",do:"≥2 critérios = sepse",via:"—",o:"qSOFA: FR ≥22, PAS ≤100, alteração mental. SOFA mais sensível na UTI. Tempo é vida."},
    {etapa:"inicial", d:"Lactato",do:"Coletar IMEDIATO; repetir 2h se ≥2 mmol/L",via:"—",o:"Marcador de hipoperfusão. Clearance >10%/h associado a melhor sobrevida."},
    {etapa:"inicial", d:"Hemoculturas",do:"2 pares (2 sítios diferentes) ANTES da 1ª dose ATB",via:"—",o:"NÃO atrasar ATB >45 min para colher culturas."},
    {etapa:"inicial", d:"2 acessos calibrosos + monitorização",do:"PA invasiva se choque, débito urinário, SpO₂, ECG",via:"—",o:"Acesso central precoce se vasopressor previsto."},
    {etapa:"atb", d:"ATB amplo espectro em ≤1h",do:"Conforme foco — empírico inicial",via:"IV",o:"Cada hora de atraso ↑mortalidade ~7,6%. Cobertura: pneumonia (ceftriaxona + macrolídeo), urinária (ceftriaxona/piper-tazo), abdominal (piper-tazo), pele/parte mole (vanco + piper-tazo), neutropenia febril (cefepime), comunitário desconhecido (ceftriaxona + vanco se grave)."},
    {etapa:"escala", d:"① Cristaloide — Ringer Lactato",do:"30 mL/kg em 3h (até melhora hemodinâmica)",via:"IV",o:"RL preferível ao SF (↓hipercloremia/IRA). Reavaliar com VCI/eco/lactato/diurese."},
    {etapa:"escala", d:"② Noradrenalina",do:"0,05–2 mcg/kg/min; iniciar 0,1 mcg/kg/min",via:"IV",o:"VASOPRESSOR DE 1ª LINHA. Pode ser periférico curto prazo (até 6h). META: PAM ≥65."},
    {etapa:"escala", d:"③ Vasopressina (adicionar)",do:"0,03 U/min FIXA",via:"IV",o:"Adicionar se NE >0,25–0,5 mcg/kg/min — reduz dose de NE + complementa via não-catecolaminérgica."},
    {etapa:"escala", d:"④ Hidrocortisona",do:"200 mg/d (50 mg IV 6/6h) ou BIC",via:"IV",o:"CHOQUE REFRATÁRIO: NE >0,25 mcg/kg/min por >4h. Reduz tempo de vasopressor."},
    {etapa:"escala", d:"⑤ Dobutamina (se baixo débito)",do:"2,5–20 mcg/kg/min",via:"IV",o:"Disfunção miocárdica com baixo débito apesar de volume + vasopressor. Pode reduzir PA — manter NE."},
    {etapa:"adj", d:"Foco de controle",do:"Drenagem de abscesso, retirada cateter, desbridamento",via:"—",o:"Tão crítico quanto ATB — primeiras 6-12h. Identificar e remover."},
    {etapa:"adj", d:"Hemocomponentes",do:"CH se Hb <7 (ou <8 em SCA)",via:"IV",o:"Estratégia restritiva. Plaquetas <10k (profilática) ou <50k (procedimento)."},
    {etapa:"adj", d:"Tromboprofilaxia",do:"Enoxaparina 40 mg SC/d",via:"SC",o:"Mecânica (compressão) se contraindicação. Reduz TEV."},
    {etapa:"adj", d:"Controle glicêmico",do:"Insulina BIC alvo 140-180 mg/dL",via:"IV",o:"Evitar hipoglicemia. Sliding scale ou BIC conforme glicemia capilar 4/4h."},
  ],
  alertas:[
    {t:"crit",x:"ATB em ≤1h do reconhecimento. Sepse é emergência tempo-dependente como IAM e AVC."},
    {t:"warn",x:"Em sepse SEM choque, ATB pode aguardar avaliação focada — em choque, ATB IMEDIATO."},
    {t:"info",x:"Brasil — ILAS Protocolo Gerenciado: pacote 1h + checkpoint 6h."},
  ],
  fisio:"Resposta inflamatória sistêmica desregulada à infecção: liberação maciça de citocinas (TNF-α, IL-1, IL-6) → ativação endotelial difusa → vazamento capilar + vasodilatação + microtrombose + disfunção mitocondrial → hipoperfusão tecidual + disfunção orgânica múltipla. \"Choque distributivo\" — débito cardíaco normal/alto, RVS baixa.",
  mec:[
    {d:"Noradrenalina",x:"<strong>α1-agonista predominante</strong> (+ leve β1) — restaura RVS. Vasoconstritor de escolha em choque distributivo."},
    {d:"Vasopressina",x:"Agonista V1 vascular — vasoconstrição <strong>não-catecolaminérgica</strong>; útil em deficiência relativa de vasopressina endógena na sepse."},
    {d:"Hidrocortisona",x:"Glicocorticoide — restaura responsividade adrenérgica (efeito permissivo), reduz inflamação. Em choque refratário, ↓tempo até desmame de vasopressor."},
  ],
  diretriz:"Surviving Sepsis Campaign 2021 (Evans L et al., Intensive Care Med 2021;47:1181–1247, DOI:10.1007/s00134-021-06506-y). ILAS Brasil — Pacote 1h.",
  fluxo:"sepse",
  calcs:["qsofa","sofa"],
},
{
  id:"sifilis", sis:"infecto", grav:"media",
  nome:"Sífilis",
  sin:["sífilis","Treponema","cancro"],
  def:"Infecção sistêmica por T. pallidum. Estágios: primária (cancro), secundária (rash + condiloma plano), latente, terciária (cardiovascular, neuro).",
  exames:["VDRL + TPHA/FTA-ABS","HIV, hepatites B/C","LCR se suspeita de neuro/sintomas oculares/auditivos/HIV+ com VDRL alto"],
  rx:[
    {etapa:"escala", d:"Sífilis recente (<1 ano)",do:"Penicilina G benzatina 2,4 MU IM dose única",via:"IM",o:"1,2 MU em cada glúteo."},
    {etapa:"escala", d:"Sífilis tardia/duração ignorada",do:"Penicilina G benzatina 2,4 MU IM semanalmente × 3 sem",via:"IM",o:"Intervalo 7–9 dias aceitável (Nota Técnica MS 2023)."},
    {etapa:"escala", d:"Neurossífilis",do:"Penicilina G cristalina 18–24 MU/d IV (3–4 MU 4/4h ou BIC) × 14 dias",via:"IV",o:"Internação. Considerar prednisona 30 mg × 3 dias para Jarisch-Herxheimer."},
    {etapa:"atb", d:"Alergia a penicilina",do:"Dessensibilização preferencial; alternativa: doxiciclina 100 mg 12/12h × 14 dias (recente) ou 28 dias (tardia)",via:"VO",o:"Em gestante NÃO há substituto — dessensibilizar."},
  ],
  alertas:[
    {t:"warn",x:"Gestante: SEMPRE penicilina (única que previne transmissão vertical). Dessensibilizar se alergia."},
    {t:"info",x:"Reação de Jarisch-Herxheimer: febre + cefaleia + mialgia 2–8h pós-dose — auto-limitada."},
  ],
  fisio:"T. pallidum penetra mucosas/pele → disseminação linfática e hematogênica precoce. Estágio: incubação 3 sem → cancro 6 sem → secundária 6 sem-6 mês (latente assintomática) → terciária anos depois.",
  mec:[
    {d:"Penicilina",x:"Inibe PBPs bacterianas → bloqueia síntese de peptidoglicano."},
  ],
  diretriz:"PCDT-IST MS 2022 (ISBN 978-65-5993-276-4). Nota Técnica MS 14/2023.",
  calcs:[],
},
{
  id:"dengue", sis:"infecto", grav:"alta",
  nome:"Dengue (MS 2024 — Grupos A/B/C/D)",
  sin:["dengue","arbovírus"],
  def:"Febre + 2 de: cefaleia, dor retro-orbitária, mialgia, artralgia, prostração, exantema. Classificação MS por gravidade clínica.",
  exames:["Hemograma com plaquetas (TODOS — repetir em B/C/D)","NS1 (1º–5º dia), IgM/IgG (após 6º)","Função renal/hepática, eletrólitos","Prova do laço, hematócrito"],
  rx:[
    {etapa:"inicial", d:"GRUPO A (sem alarme, sem comorbidade)",do:"Hidratação oral 60 mL/kg/d (1/3 SRO + 2/3 água)",via:"VO",o:"Ambulatorial. Reavaliação D3 e D5 ou se sinais de alarme."},
    {etapa:"escala", d:"GRUPO B (sangramento de pele OU comorbidade)",do:"Hidratação + obs até resultado HMG",via:"VO/IV",o:"Hemograma obrigatório. Se Ht ↑ ou plaquetopenia: hidratação parenteral 25 mL/kg em 4h."},
    {etapa:"escala", d:"GRUPO C (sinais de alarme)",do:"SF 0,9% 10 mL/kg em 1h",via:"IV",o:"INTERNAR. Repetir até 3× se necessário. Reavaliar Ht 2h depois."},
    {etapa:"escala", d:"GRUPO D (choque/sangramento grave/disfunção)",do:"SF 0,9% 20 mL/kg em 20 min",via:"IV",o:"UTI. Repetir 2–3×. Albumina/coloide se refratário. Hemocomponentes."},
    {etapa:"adj", d:"Analgesia/antitérmico",do:"Paracetamol 500–1000 mg 6/6h ou dipirona",via:"VO/IV",o:"NÃO usar AINE/AAS (risco sangramento)."},
  ],
  alertas:[
    {t:"crit",x:"SINAIS DE ALARME: dor abdominal intensa, vômitos persistentes, acúmulo de líquidos, hipotensão postural, hepatomegalia >2 cm, sangramento de mucosa, letargia, ↑Ht progressivo."},
    {t:"crit",x:"SINAIS DE CHOQUE: extremidades frias, pulso filiforme, enchimento capilar >2s, PA convergente <20 mmHg, taquicardia, oligúria, hipotensão tardia, cianose."},
    {t:"warn",x:"Condições especiais (grupo B independente): <2a, gestante, ≥65a, HAS, DM, DPOC/asma, obesidade, anemia falciforme, DRC, hepatopatia."},
  ],
  fisio:"Após inoculação pelo Aedes aegypti (DENV 1–4), o vírus replica em monócitos/macrófagos → viremia (3–7 dias) → resposta inflamatória sistêmica + <strong>aumento de permeabilidade vascular</strong> (extravasamento plasmático) + <strong>plaquetopenia</strong> (medular + consumo + Ac antiplaqueta) + disfunção hepática. Pico de gravidade entre D4-D6, com a defervescência → fase crítica.",
  mec:[],
  diretriz:"Manejo Clínico da Dengue — Ministério da Saúde, 6ª ed. 2024 (gov.br/saude/dengue). Classificação grupos A/B/C/D.",
  fluxo:"dengue",
  calcs:[],
},
{
  id:"herpes-simples", sis:"infecto", grav:"baixa",
  nome:"Herpes Simples",
  sin:["herpes","HSV-1","herpes labial"],
  def:"Vesículas dolorosas em pele/mucosa. HSV-1: oro-labial. HSV-2: genital. Pode disseminar em imunossuprimidos.",
  exames:["Diagnóstico clínico"],
  rx:[
    {etapa:"atb", d:"Aciclovir VO",do:"400 mg 8/8h × 7–10 dias",via:"VO",o:"Primário ou recorrência grave."},
    {etapa:"atb", d:"Valaciclovir VO",do:"500 mg–1 g 12/12h × 5–10 dias",via:"VO",o:"Alternativa."},
    {etapa:"atb", d:"Aciclovir tópico",do:"5×/d × 4 dias",via:"Tópico",o:"Herpes labial leve — benefício marginal."},
  ],
  alertas:[
    {t:"warn",x:"Herpes oftálmico: emergência. Encaminhar oftalmo."},
  ],
  fisio:"Reativação viral no gânglio sensitivo (HSV-1: trigeminal; HSV-2: sacral) → migração axonal → vesículas mucocutâneas.",
  mec:[
    {d:"Aciclovir",x:"Inibe DNA-polimerase viral após fosforilação por TK viral."},
  ],
  diretriz:"CDC STI 2021; PCDT-IST MS 2022.",
  calcs:[],
},
{
  id:"conjuntivite", sis:"infecto", grav:"baixa",
  nome:"Conjuntivite",
  sin:["conjuntivite","olho vermelho"],
  def:"Hiperemia conjuntival + secreção. Viral: serosa, bilateral, autolimitada. Bacteriana: purulenta. Alérgica: prurido + bilateral.",
  exames:["Acuidade visual","Excluir sinais de gravidade: dor, fotofobia, ↓visão, anisocoria, hipópio"],
  rx:[
    {etapa:"escala", d:"VIRAL — Lágrima artificial",do:"4–6×/d",via:"Tópico",o:"Autolimitada (7–14 dias). Compressas frias. Higiene."},
    {etapa:"atb", d:"BACTERIANA — Tobramicina",do:"1 gota 4/4h × 5–7 dias",via:"Tópico",o:"Ciprofloxacino é alternativa."},
    {etapa:"escala", d:"ALÉRGICA — Olopatadina",do:"1 gota 12/12h",via:"Tópico",o:"Anti-H1 tópico."},
  ],
  alertas:[
    {t:"crit",x:"SINAIS DE GRAVIDADE (\"olho vermelho perigoso\"): ↓acuidade visual, dor intensa, fotofobia, hipópio, anisocoria, halo. Considerar úlcera córnea, uveíte, glaucoma agudo, escleirite — encaminhar oftalmo URGENTE."},
  ],
  fisio:"Viral: adenovírus mais comum. Bacteriana: Staph, Strep, H. influenzae. Alérgica: hipersensibilidade tipo I.",
  mec:[],
  diretriz:"AAO Conjunctivitis PPP 2018.",
  calcs:[],
},
{
  id:"tetano", sis:"infecto", grav:"alta",
  nome:"Tétano",
  sin:["tétano","trismo"],
  def:"Trismo + rigidez muscular generalizada + espasmos por toxina tetânica. Causa: ferimento contaminado + status vacinal inadequado.",
  exames:["Diagnóstico clínico","Hemograma, CK","Eletrólitos"],
  rx:[
    {etapa:"escala", d:"Imunoglobulina humana antitetânica (IGHAT)",do:"500–3000 UI IM (250 UI em criança)",via:"IM",o:"Neutraliza toxina circulante. NÃO atua sobre toxina já ligada."},
    {etapa:"atb", d:"Metronidazol",do:"500 mg IV 8/8h × 7–10 dias",via:"IV",o:"PREFERENCIAL — penicilina pode antagonizar GABA e piorar espasmos."},
    {etapa:"escala", d:"Diazepam",do:"5–10 mg IV 4/4h, titular",via:"IV",o:"Controle de espasmos."},
    {etapa:"adj", d:"Vacina dT",do:"Dose única + completar esquema",via:"IM",o:"Esquema 3 doses se status incerto."},
    {etapa:"escala", d:"Desbridamento da ferida",do:"Limpeza ampla",via:"—",o:"Remoção do tecido necrótico/corpo estranho."},
    {etapa:"escala", d:"Suporte ventilatório",do:"IOT + sedação + bloqueador NM se grave",via:"—",o:"Espasmos laríngeos/diafragmáticos."},
  ],
  alertas:[
    {t:"crit",x:"Disautonomia (taquiarritmias, hipertensão lábil) é causa de morte tardia em tétano. UTI obrigatória."},
  ],
  fisio:"Clostridium tetani (bacilo anaeróbio formador de esporo) → produz <strong>tetanospasmina</strong> que migra retroaxonalmente até SNC → bloqueia liberação de GABA/glicina pelos interneurônios inibitórios → hiperatividade motora descontrolada.",
  mec:[
    {d:"IGHAT",x:"Imunoglobulina hiperimune — neutraliza toxina ainda não ligada aos neurônios."},
    {d:"Metronidazol",x:"Bactericida sobre C. tetani vegetativo — bloqueia produção adicional de toxina."},
    {d:"Diazepam",x:"Agonista GABA-A — restaura tônus inibitório."},
  ],
  diretriz:"MS — Manual de Tétano Acidental 2018.",
  calcs:[],
},
{
  id:"leptospirose", sis:"infecto", grav:"alta",
  nome:"Leptospirose",
  sin:["leptospirose","Weil"],
  def:"Febre + mialgia (panturrilha) + cefaleia + ictericia + IRA + hemorragia (Weil) após exposição a água/lama contaminada (enchentes, ratos).",
  exames:["Hemograma","Função renal e hepática (↑Bili direta, ↑TGO/TGP modestos, ↑FA)","CK (rabdomiólise)","Gasometria, eletrólitos","Coagulograma","Sorologia (MAT, ELISA)","RX tórax (hemorragia pulmonar)"],
  rx:[
    {etapa:"atb", d:"LEVE — Doxiciclina",do:"100 mg VO 12/12h × 7 dias",via:"VO",o:"Forma anictérica. Eficaz se iniciado <5 dias."},
    {etapa:"atb", d:"GRAVE — Ceftriaxona",do:"1 g IV/d × 7 dias",via:"IV",o:"Síndrome de Weil. Alternativa: penicilina cristalina 1,5 MU 6/6h."},
    {etapa:"escala", d:"Suporte intensivo",do:"Hidratação, vasopressor, diálise se necessário",via:"—",o:"IRA é principal causa de morte. Diálise em IRA oligúrica/anúrica."},
    {etapa:"escala", d:"Hemocomponentes",do:"Conforme sangramento",via:"IV",o:"Plaquetopenia + coagulopatia em formas graves."},
  ],
  alertas:[
    {t:"crit",x:"Hemorragia pulmonar (forma fulminante) — mortalidade >50%. ECMO em centros de referência."},
  ],
  fisio:"Leptospira spp (espiroqueta) penetra pele/mucosa → bacteremia → vasculite endotelial generalizada → disfunção orgânica múltipla. Forma grave (Weil): icterícia + IRA + hemorragia.",
  mec:[
    {d:"Doxiciclina",x:"Tetraciclina — inibe 30S ribossomal."},
  ],
  diretriz:"MS — Guia de Vigilância em Saúde 2024.",
  calcs:[],
},
{
  id:"celulite", sis:"infecto", grav:"media",
  nome:"Celulite / Erisipela",
  sin:["celulite","erisipela","linfangite"],
  def:"Eritema + calor + edema + dor cutânea, geralmente em MMII. Erisipela: bordas nítidas, superficial. Celulite: profunda, bordas pouco definidas.",
  exames:["Hemograma, PCR","Função renal","HMC se febre/grave","Excluir TVP (Doppler) e outras causas de \"perna vermelha\""],
  rx:[
    {etapa:"atb", d:"LEVE/AMBULATORIAL — Cefalexina",do:"500 mg VO 6/6h × 7–10 dias",via:"VO",o:"Boa cobertura Staph + Strep."},
    {etapa:"atb", d:"AMBULATORIAL — Amoxicilina-clavulanato",do:"875/125 mg 12/12h × 7 dias",via:"VO",o:"Alternativa."},
    {etapa:"escala", d:"MODERADA/INTERNADO — Oxacilina",do:"2 g IV 4/4h × 7–14 dias",via:"IV",o:"Boa cobertura S. aureus meticilino-sensível."},
    {etapa:"atb", d:"MODERADA — Cefazolina",do:"1–2 g IV 8/8h",via:"IV",o:"Alternativa à oxacilina, mais barata."},
    {etapa:"escala", d:"Suspeita MRSA",do:"Vancomicina 15 mg/kg 12/12h OU Clindamicina 600 mg 8/8h",via:"IV",o:"Hospitalar, drenagem, hist. MRSA."},
    {etapa:"escala", d:"Elevação do membro",do:"30°",via:"—",o:"Reduz edema."},
  ],
  alertas:[
    {t:"crit",x:"FASCEÍTE NECROTIZANTE: dor desproporcional + bolha hemorrágica + necrose + crepitação + toxemia. Cirurgia URGENTE + ATB amplo."},
  ],
  fisio:"Invasão bacteriana através de solução de continuidade da pele (porta de entrada — fissura interdigital frequente). S. aureus e S. pyogenes mais comuns.",
  mec:[
    {d:"Cefalexina/Cefazolina",x:"Cefalosporina 1G — inibe PBPs Gram-positivas."},
  ],
  diretriz:"IDSA SSTI (Stevens DL et al., CID 2014;59:e10–e52).",
  imgs:[
    {src:"https://upload.wikimedia.org/wikipedia/commons/5/5c/Cellulitis_Left_Leg.JPG",
     alt:"Celulite em MI esquerdo",
     caption:"Celulite em MI esquerdo — eritema, edema, calor, com bordas MAIS DIFUSAS que erisipela (que tem bordas elevadas e bem delimitadas).",
     source:"Wikimedia Commons (CC BY-SA 2.5)"},
    {src:"https://upload.wikimedia.org/wikipedia/commons/6/6a/Necrotizing_fasciitis_left_leg.JPEG",
     alt:"Fasceíte necrotizante em MI",
     caption:"FASCEÍTE NECROTIZANTE — eritema com áreas escuras de necrose e bolhas hemorrágicas. EMERGÊNCIA cirúrgica + ATB amplo.",
     source:"Wikimedia Commons / Piotr Smuszkiewicz et al. (CC BY 2.0)"},
  ],
  calcs:[],
},
{
  id:"abscesso", sis:"infecto", grav:"media",
  nome:"Furúnculo / Abscesso Cutâneo",
  sin:["abscesso","furúnculo","drenagem"],
  def:"Coleção purulenta cutânea/subcutânea — dor, flutuação, calor.",
  exames:["Clínico","Cultura do material se grave/recidiva"],
  rx:[
    {etapa:"escala", d:"Drenagem cirúrgica (I&D)",do:"Incisão + drenagem",via:"—",o:"PRINCIPAL conduta. Anestesia local. Curativo com mecha."},
    {etapa:"atb", d:"Clindamicina",do:"300–450 mg VO 6/6h × 7 dias",via:"VO",o:"Cobertura MRSA comunitário. Se febre, celulite ao redor, imunossuprimido."},
    {etapa:"atb", d:"SMX-TMP",do:"800/160 mg 12/12h × 7 dias",via:"VO",o:"Alternativa MRSA."},
  ],
  alertas:[
    {t:"info",x:"Abscesso simples sem celulite: drenagem PODE ser suficiente sem ATB (eficácia 80%)."},
  ],
  fisio:"Folículo piloso ou solução de continuidade → infecção → necrose → coleção purulenta. S. aureus (frequente MRSA comunitário em algumas regiões).",
  mec:[
    {d:"Clindamicina",x:"Liga 50S ribossomal — inibe síntese proteica. Boa contra MRSA comunitário e anaeróbios."},
  ],
  diretriz:"IDSA SSTI 2014.",
  calcs:[],
},
{
  id:"fasceite", sis:"infecto", grav:"alta",
  nome:"Fasceíte Necrotizante",
  sin:["fasceíte","fasceíte necrosante","Fournier"],
  def:"Infecção rapidamente progressiva da fáscia + tecido subcutâneo + necrose. Mortalidade 25–40% mesmo com tratamento.",
  exames:["LRINEC score","Hemograma, PCR, Cr, glicemia, Na, Hb (compõem LRINEC)","Lactato","Imagem (TC) — gás na fáscia"],
  rx:[
    {etapa:"escala", d:"Cirurgia URGENTE",do:"Desbridamento amplo, repetir 24–48h",via:"—",o:"PILAR do tratamento. Cada hora de atraso ↑mortalidade. Múltiplas reabordagens."},
    {etapa:"atb", d:"Piperacilina-tazobactam + Vancomicina + Clindamicina",do:"4,5g 6/6h + 15mg/kg 12/12h + 900 mg 8/8h",via:"IV",o:"Cobertura amplíssima. Clindamicina inibe produção de toxina."},
    {etapa:"atb", d:"Meropenem",do:"1 g IV 8/8h",via:"IV",o:"Alternativa ao piperacilina-tazo em alergia/MR."},
    {etapa:"escala", d:"Suporte intensivo",do:"UTI + vasopressor",via:"—",o:"Sepse grave/choque séptico associado em maioria."},
  ],
  alertas:[
    {t:"crit",x:"Dor DESPROPORCIONAL ao exame físico, bolha hemorrágica, crepitação, anestesia cutânea → SUSPEITAR FASCEÍTE. Cirurgia em <12h."},
  ],
  fisio:"Infecção polimicrobiana (tipo I) ou monomicrobiana por S. pyogenes (tipo II) → liberação de toxinas e enzimas → trombose vascular fascial → isquemia → necrose progressiva.",
  mec:[
    {d:"Clindamicina",x:"<strong>Inibe síntese de toxinas</strong> bacterianas (estreptocócica, estafilocócica) — papel adjuvante essencial."},
  ],
  diretriz:"IDSA SSTI 2014; WSES Necrotizing Soft Tissue Infections 2018.",
  calcs:[],
},
{
  id:"pe-diabetico", sis:"infecto", grav:"media",
  nome:"Pé Diabético Infectado",
  sin:["pé diabético","úlcera diabética","osteomielite"],
  def:"Úlcera/lesão em pé de paciente diabético + sinais de infecção (eritema, edema, calor, secreção purulenta). Classificação IDSA/IWGDF: leve, moderada, grave.",
  exames:["RX (osteomielite, gás)","RM se suspeita de osteomielite","Hemograma, PCR, glicemia, A1c","Cultura de tecido profundo (NÃO swab superficial)","ITB / Doppler arterial (perfusão)"],
  rx:[
    {etapa:"atb", d:"LEVE — Cefalexina + Clindamicina",do:"500 mg 6/6h + 300 mg 6/6h × 1–2 sem",via:"VO",o:"Sem osso/profundidade."},
    {etapa:"atb", d:"MODERADA — Ceftriaxona + Clindamicina",do:"2 g IV/d + 600 mg IV 8/8h",via:"IV",o:"Internação. Step-down VO após melhora."},
    {etapa:"atb", d:"GRAVE — Piperacilina-tazobactam + Vancomicina",do:"4,5 g 6/6h + 15 mg/kg 12/12h",via:"IV",o:"Sepse, gangrena, MR prévia."},
    {etapa:"escala", d:"Controle glicêmico",do:"Alvo 140–180 mg/dL",via:"—",o:"Hiperglicemia perpetua infecção."},
    {etapa:"escala", d:"Desbridamento cirúrgico",do:"Tecido necrótico + drenagem",via:"—",o:"Imprescindível em moderada/grave."},
    {etapa:"escala", d:"Revascularização",do:"Avaliação vascular",via:"—",o:"Se isquemia: angioplastia/bypass."},
  ],
  alertas:[
    {t:"warn",x:"Osteomielite: ATB prolongado 4–6 sem. Excluir com RM + biópsia."},
  ],
  fisio:"Neuropatia + isquemia + imunodepressão + hiperglicemia → úlcera + colonização → infecção polimicrobiana progressiva.",
  mec:[],
  diretriz:"IDSA/IWGDF 2023.",
  calcs:[],
},
{
  id:"neutropenia", sis:"infecto", grav:"alta",
  nome:"Neutropenia Febril",
  sin:["neutropenia febril","NF","quimioterapia"],
  def:"PMN <500 (ou <1000 com queda) + febre ≥38,3°C única OU ≥38°C por 1h. EMERGÊNCIA. ATB <1h.",
  exames:["Hemograma com contagem absoluta","HMC (2 pares, 1 de cateter se presente)","EAS + urocultura","RX tórax","Cultura de qualquer foco","PCR/procalcitonina","Função renal/hepática, eletrólitos","MASCC score"],
  rx:[
    {etapa:"atb", d:"Cefepime",do:"2 g IV 8/8h",via:"IV",o:"1ª linha empírica. Boa cobertura Gram+ e Gram- incluindo Pseudomonas."},
    {etapa:"atb", d:"Piperacilina-tazobactam",do:"4,5 g IV 6/6h",via:"IV",o:"Alternativa."},
    {etapa:"atb", d:"Meropenem",do:"1 g IV 8/8h",via:"IV",o:"Sepse grave, ESBL prévia, falha cefepime."},
    {etapa:"atb", d:"+ Vancomicina",do:"15 mg/kg IV 12/12h",via:"IV",o:"Se: mucosite grave, cateter infectado, hipotensão/sepse, MRSA conhecido, pneumonia."},
    {etapa:"atb", d:"+ Antifúngico (caspofungina/anidulafungina)",do:"70 mg D1 + 50 mg/d",via:"IV",o:"Se febre persiste >4–7 dias com ATB amplo + neutropenia prolongada."},
    {etapa:"escala", d:"G-CSF (filgrastim)",do:"5 mcg/kg/d SC",via:"SC",o:"Considerar em casos selecionados (não rotineiro)."},
  ],
  alertas:[
    {t:"crit",x:"ATB em ≤60 min — tempo é crítico. Mortalidade aumenta com atraso."},
    {t:"info",x:"MASCC ≥21 + clínica estável + sem comorbidade = baixo risco, possível manejo ambulatorial com ciprofloxacino + amox-clav."},
  ],
  fisio:"Quimioterapia → ↓neutrófilos → ↓capacidade de conter translocação bacteriana intestinal/oral → bacteremia rápida + sepse fulminante.",
  mec:[],
  diretriz:"IDSA Neutropenic Fever (Freifeld AG et al., CID 2011;52:e56–e93). NCCN Guidelines.",
  calcs:[],
},

/* ============== ANAFILAXIA ============== */
{
  id:"anafilaxia", sis:"anaf", grav:"alta",
  nome:"Choque Anafilático",
  sin:["anafilaxia","choque anafilático","alergia grave"],
  def:"Reação alérgica sistêmica grave, início rápido (min a horas), envolvendo 2+ sistemas (pele, respiratório, CV, GI). Critérios WAO/EAACI.",
  exames:["Diagnóstico clínico","Triptase sérica em 1–6h (confirmação retrospectiva)","ECG, eletrólitos, função renal"],
  rx:[
    {etapa:"inicial", d:"1. ADRENALINA IM",do:"0,3–0,5 mg IM (1:1000), face anterolateral da coxa",via:"IM",o:"1ª LINHA ÚNICA. Crianças 0,01 mg/kg (máx 0,3). Repetir cada 5–15 min até 3×."},
    {etapa:"inicial", d:"2. Posição supina + elevar MMII",do:"Decúbito dorsal + Trendelenburg",via:"—",o:"Exceto se dispneia grave. NÃO sentar (síndrome ventricular vazio)."},
    {etapa:"inicial", d:"3. O₂ alto fluxo",do:"10–15 L/min máscara não-reinalante",via:"—",o:"SpO₂ ≥94%. IOT precoce se edema laríngeo progressivo."},
    {etapa:"inicial", d:"4. Cristaloide",do:"SF 20 mL/kg em 5–10 min (adulto 1–2 L)",via:"IV",o:"Pode repetir. Choque distributivo."},
    {etapa:"escala", d:"② Adrenalina IM REPETIDA",do:"0,3-0,5 mg IM cada 5-15 min",via:"IM",o:"Se não responder à 1ª dose. Até 3 doses antes de IV."},
    {etapa:"escala", d:"③ Adrenalina IV em BIC (refratário)",do:"0,1 mcg/kg/min, titular 0,05–1 mcg/kg/min",via:"IV",o:"APENAS em ambiente monitorizado, após ≥2 doses IM sem resposta."},
    {etapa:"escala", d:"④ Glucagon (β-bloqueador)",do:"1–5 mg IV bolus + 5–15 mcg/min BIC",via:"IV",o:"Se em β-bloqueador (adrenalina não funciona bem)."},
    {etapa:"adj", d:"ADJUVANTES — Difenidramina",do:"25–50 mg IV",via:"IV",o:"Anti-H1. Trata urticária; NÃO substitui adrenalina."},
    {etapa:"adj", d:"ADJUVANTES — Hidrocortisona",do:"200 mg IV",via:"IV",o:"Pode reduzir reação bifásica (controverso). NÃO previne morte aguda."},
    {etapa:"adj", d:"ADJUVANTES — Ranitidina (anti-H2)",do:"50 mg IV",via:"IV",o:"Sinergia com anti-H1. Opcional."},
    {etapa:"adj", d:"Broncodilatador",do:"Salbutamol nebulização 2,5-5 mg",via:"INH",o:"Se broncoespasmo significativo."},
    {etapa:"alta", d:"Observação ≥6–8h pós-resolução",do:"Internar se: refratária, IV adrenalina, bifásica prévia, β-bloqueador",via:"—",o:"Reação bifásica em 5–20% em 4–8h."},
    {etapa:"alta", d:"Prescrição de alta",do:"Auto-injetor adrenalina (EpiPen) + anti-H1 VO × 5 dias + corticoide VO × 5 dias",via:"VO",o:"Encaminhar alergologia. Identificar e EVITAR gatilho. Cartão de identificação."},
  ],
  alertas:[
    {t:"crit",x:"ADRENALINA IM É A ÚNICA 1ª LINHA. Anti-histamínicos e corticoides são ADJUVANTES e NÃO substituem. Atraso = morte."},
    {t:"warn",x:"Em β-bloqueador: adrenalina pode não responder bem → glucagon."},
  ],
  fisio:"Sensibilização prévia → reexposição → cross-linking de IgE em mastócitos/basófilos → degranulação maciça → liberação de <strong>histamina, triptase, leucotrienos, prostaglandinas, PAF</strong> → vasodilatação sistêmica + ↑permeabilidade capilar (perda de até 50% do volume IV em minutos) + broncoconstrição + edema laríngeo. Causa de morte: choque distributivo refratário + asfixia.",
  mec:[
    {d:"Adrenalina",x:"Agonista α1 (vasoconstrição, ↓edema, ↑PAM), <strong>β1 (inotropismo, cronotropismo)</strong>, <strong>β2 (broncodilatação, ↓liberação de mediadores)</strong>. Cobre TODOS os mecanismos fisiopatológicos."},
    {d:"Glucagon",x:"Ativa adenilato ciclase via receptor próprio (não β) → ↑AMPc cardíaco → contorna β-bloqueio."},
    {d:"Anti-H1",x:"Bloqueia receptores H1 — trata apenas urticária/prurido."},
  ],
  diretriz:"WAO Anaphylaxis 2020 (Cardona V et al., World Allergy Organ J 2020;13:100472, DOI:10.1016/j.waojou.2020.100472). EAACI Anaphylaxis 2021 (Muraro A et al., Allergy 2022;77:357–377, DOI:10.1111/all.15032).",
  imgs:[
    {src:"https://upload.wikimedia.org/wikipedia/commons/c/c9/Urticaria2.JPG",
     alt:"Urticária — pápulas eritematosas elevadas",
     caption:"Urticária — pápulas eritematosas confluentes (wheals), pruriginosas, fugazes. Quando associada a sintomas sistêmicos = anafilaxia.",
     source:"Wikimedia Commons (Domínio público)"},
  ],
  fluxo:"anafilaxia",
  calcs:[],
},
{
  id:"urticaria", sis:"anaf", grav:"baixa",
  nome:"Urticária e Angioedema",
  sin:["urticária","angioedema","alergia"],
  def:"Lesões eritematosas pruriginosas (urticária) ± edema dérmico profundo (angioedema). Aguda (<6 sem) vs crônica.",
  exames:["Clínico","Triptase se suspeita de anafilaxia","C1q/C1-inibidor em angioedema recorrente sem urticária"],
  rx:[
    {etapa:"escala", d:"Loratadina",do:"10 mg VO/d",via:"VO",o:"Anti-H1 de 2ª geração. Pode dobrar dose."},
    {etapa:"escala", d:"Desloratadina",do:"5 mg VO/d",via:"VO",o:"Alternativa. Pode até 4× a dose padrão."},
    {etapa:"escala", d:"Prometazina",do:"25 mg IV/IM",via:"IV/IM",o:"Anti-H1 1ª geração — sedativo. Para alívio agudo."},
    {etapa:"escala", d:"Prednisona",do:"20–40 mg VO/d × 3–5 dias",via:"VO",o:"Extensa ou refratária."},
    {etapa:"escala", d:"Adrenalina IM",do:"0,3 mg",via:"IM",o:"SE angioedema com risco de via aérea (lábios, língua, glote)."},
  ],
  alertas:[
    {t:"crit",x:"Angioedema de via aérea (lábios/língua/glote) → adrenalina IM + IOT preparada."},
    {t:"warn",x:"Angioedema por IECA (não-pruriginoso, sem urticária) NÃO responde a anti-H1/corticoide — icatibant ou C1-inibidor."},
  ],
  fisio:"Urticária: degranulação mastocitária dérmica → liberação histamina → eritema, prurido, edema dérmico superficial. Angioedema: edema da derme profunda/submucosa. Pode ou não ser IgE-mediado.",
  mec:[],
  diretriz:"EAACI/GA²LEN Urticária 2022.",
  calcs:[],
},

/* ============== TOXICOLOGIA ============== */
{
  id:"carvao", sis:"tox", grav:"baixa",
  nome:"Descontaminação Gastrointestinal",
  sin:["carvão ativado","lavagem","descontaminação"],
  def:"Procedimentos para reduzir absorção de tóxico ingerido. Carvão ativado é o mais usado.",
  exames:["Identificar tóxico, dose, tempo, via","Via aérea pérvia + consciência preservada"],
  rx:[
    {etapa:"escala", d:"Carvão ativado",do:"1 g/kg VO/SNG (adulto 50 g)",via:"VO/SNG",o:"Idealmente <1–2h da ingestão. CI: rebaixamento sem proteção de via aérea, íleo, obstrução, corrosivos."},
    {etapa:"escala", d:"Lavagem gástrica",do:"SNG calibroso + SF morno 200 mL × ciclos",via:"SNG",o:"Indicações restritas: <1h + tóxico potencialmente fatal sem antídoto."},
    {etapa:"escala", d:"Irrigação intestinal total",do:"Polietilenoglicol 1–2 L/h",via:"VO/SNG",o:"Ferro, lítio, sustained-release, packers de drogas."},
    {etapa:"escala", d:"Antídoto específico",do:"Conforme tóxico",via:"—",o:"Ver páginas específicas."},
  ],
  alertas:[
    {t:"crit",x:"CARVÃO NÃO ADSORVE: hidrocarbonetos, álcoois, metais (ferro, lítio, plumbo), corrosivos, cianeto."},
    {t:"warn",x:"Indução de vômito (xarope de ipeca) está OBSOLETA — abandonada por inutilidade e riscos."},
  ],
  fisio:"Carvão ativado tem alta superfície (1000–2000 m²/g) — adsorve a maioria dos compostos orgânicos no TGI antes da absorção sistêmica.",
  mec:[
    {d:"Carvão ativado",x:"Superfície porosa altamente adsorvente — liga toxinas no lúmen intestinal por <strong>forças de van der Waals</strong>, prevenindo absorção."},
  ],
  diretriz:"AACT/EAPCCT Position Statements.",
  calcs:[],
},
{
  id:"paracetamol", sis:"tox", grav:"alta",
  nome:"Intoxicação por Paracetamol",
  sin:["paracetamol","acetaminofeno","NAC"],
  def:"Ingestão >150 mg/kg ou >7,5 g em adulto. Toxicidade hepática (CYP2E1 → NAPQI). Pode ser silencioso nas primeiras 24h.",
  exames:["Nível sérico de paracetamol 4–24h pós-ingestão (Rumack-Matthew)","Função hepática (AST/ALT, INR, BT, glicose, NH3)","Função renal","Gasometria, lactato","Tempo de ingestão (CRÍTICO)"],
  rx:[
    {etapa:"escala", d:"N-acetilcisteína (NAC) IV",do:"150 mg/kg em 200 mL SG5% em 1h + 50 mg/kg em 4h + 100 mg/kg em 16h",via:"IV",o:"PROTOCOLO 21h. Eficácia máxima <8h da ingestão."},
    {etapa:"escala", d:"NAC VO",do:"140 mg/kg + 70 mg/kg 4/4h × 17 doses",via:"VO",o:"Alternativa se IV indisponível. Mais difícil tolerância (vômitos)."},
    {etapa:"escala", d:"Carvão ativado",do:"1 g/kg VO/SNG",via:"VO/SNG",o:"<1–2h da ingestão E sem rebaixamento."},
    {etapa:"escala", d:"Indicação de NAC",do:"Acima da linha de tratamento no nomograma Rumack-Matthew (150 mcg/mL às 4h) OU ingestão desconhecida com AST elevado",via:"—",o:"Se nível indisponível e ingestão >150 mg/kg: tratar empiricamente."},
  ],
  alertas:[
    {t:"crit",x:"Hepatite fulminante (King's College Criteria): pH <7,3 OU (INR >6,5 + Cr >3,4 + encefalopatia III/IV). Transplante hepático URGENTE."},
  ],
  fisio:"Doses terapêuticas: 90% metabolizado em conjugados não tóxicos (glicuronil/sulfato). 5% via CYP2E1 gera <strong>NAPQI (N-acetil-p-benzoquinona imina)</strong>, neutralizado pela glutationa. Em sobredose: vias de conjugação saturam → mais NAPQI → glutationa hepática depleta → NAPQI livre causa necrose centrolobular hepática.",
  mec:[
    {d:"N-acetilcisteína (NAC)",x:"<strong>Precursor de glutationa</strong> + conjuga NAPQI diretamente + propriedades antioxidantes. Reduz hepatotoxicidade em >95% se iniciada em <8h."},
  ],
  diretriz:"AASLD; UpToDate; Bateman DN (Lancet 2014).",
  calcs:[],
},
{
  id:"organofosforado", sis:"tox", grav:"alta",
  nome:"Intoxicação por Organofosforado",
  sin:["organofosforado","carbamato","chumbinho","Aldicarb"],
  def:"Inibição da acetilcolinesterase → ↑↑ACh → síndrome muscarínica (SLUDGE) + nicotínica + SNC. Causa frequente: \"chumbinho\" (aldicarb).",
  exames:["Clínico","Atividade da colinesterase plasmática e eritrocitária (se disponível)","ECG (bradicardia, QT longo)","Gasometria, eletrólitos","Glicemia"],
  rx:[
    {etapa:"escala", d:"Descontaminação dérmica",do:"Remover roupas + lavar pele/couro cabeludo com água + sabão",via:"—",o:"EPI para equipe. Cuidado com contaminação secundária."},
    {etapa:"escala", d:"Carvão ativado",do:"1 g/kg VO/SNG",via:"VO/SNG",o:"<1h da ingestão + via aérea protegida."},
    {etapa:"escala", d:"Atropina",do:"2–5 mg IV (criança 0,05 mg/kg). DOBRAR cada 3–5 min até atropinização",via:"IV",o:"ALVOS DE ATROPINIZAÇÃO: pele/mucosas secas, FC>80, broncorreia ausente, midríase. Doses cumulativas podem ser >100 mg."},
    {etapa:"escala", d:"Manutenção atropina",do:"BIC 10–20% da dose de atropinização/h",via:"IV",o:"Por horas/dias. Desmame lento."},
    {etapa:"escala", d:"Pralidoxima (2-PAM)",do:"30 mg/kg IV em 30 min + 8 mg/kg/h BIC",via:"IV",o:"SEMPRE APÓS atropinização. Eficaz nas primeiras 24–48h (antes do \"aging\")."},
    {etapa:"escala", d:"Diazepam",do:"5–10 mg IV PRN",via:"IV",o:"Convulsões + reduz mortalidade (efeito neuroprotetor)."},
    {etapa:"escala", d:"Suporte ventilatório",do:"IOT precoce",via:"—",o:"Insuficiência respiratória é principal causa de morte."},
  ],
  alertas:[
    {t:"crit",x:"NÃO usar succinilcolina na IOT (também metabolizada por colinesterase — paralisia prolongada). Usar rocurônio."},
  ],
  fisio:"Organofosforado liga-se irreversivelmente à <strong>acetilcolinesterase</strong> (após \"aging\" — fosforilação estável) → acúmulo de ACh em receptores muscarínicos (M, SLUDGE: salivação, lacrimejamento, urinação, diarreia, GI, êmese, miose) e nicotínicos (N, fraqueza, fasciculação, paralisia respiratória) e SNC (convulsão, coma).",
  mec:[
    {d:"Atropina",x:"<strong>Antagonista muscarínico</strong> competitivo — bloqueia efeitos M de ACh excessiva (mas NÃO efeitos nicotínicos)."},
    {d:"Pralidoxima",x:"<strong>Reativa a acetilcolinesterase</strong> ao remover o grupo fosforil do sítio ativo — antes do \"aging\" (24–48h)."},
  ],
  diretriz:"Diretrizes Brasileiras para Tratamento das Intoxicações por Agrotóxicos, CONITEC/MS 2018.",
  calcs:[],
},
{
  id:"cocaina", sis:"tox", grav:"alta",
  nome:"Intoxicação por Cocaína",
  sin:["cocaína","crack","simpatomimético"],
  def:"Síndrome simpatomimética: HAS, taquicardia, hipertermia, midríase, agitação, dor torácica, convulsão, IAM, AVC.",
  exames:["ECG (excluir IAM)","Troponina","Eletrólitos, função renal, CK (rabdomiólise)","TC crânio se déficit/convulsão"],
  rx:[
    {etapa:"escala", d:"Benzodiazepínico (1ª linha)",do:"Diazepam 5–10 mg IV ou Midazolam 5 mg IV repetir conforme necessário",via:"IV",o:"PILAR. Controla agitação, taquicardia, HAS, convulsão, dor torácica."},
    {etapa:"escala", d:"AAS + nitratos",do:"AAS 300 mg + nitroglicerina IV/SL",via:"VO/IV/SL",o:"Se dor torácica/IAM associado."},
    {etapa:"escala", d:"Fentolamina",do:"5–10 mg IV em 5 min",via:"IV",o:"α-bloqueador para HAS refratária. Alternativa: nitroprussiato."},
    {etapa:"escala", d:"Resfriamento",do:"Compressas frias + SF gelado se T >40°C",via:"—",o:"Hipertermia ameaça à vida."},
    {etapa:"escala", d:"Hidratação",do:"SF + diurese alvo >1 mL/kg/h",via:"IV",o:"Rabdomiólise."},
  ],
  alertas:[
    {t:"crit",x:"NÃO usar β-bloqueador puro (propranolol, metoprolol) — vasoconstrição α não-oposta → HAS PARADOXAL e ↑mortalidade. Se imprescindível, usar labetalol (α+β)."},
  ],
  fisio:"Cocaína inibe recaptação de noradrenalina, dopamina e serotonina nas sinapses → excesso de catecolaminas → estimulação adrenérgica generalizada (α e β). Também bloqueia canais de Na⁺ voltagem-dependentes → efeito tipo classe I (pró-arrítmico, ↓contratilidade em altas doses).",
  mec:[
    {d:"Diazepam",x:"Agonista GABA-A — modula via dopaminérgica + simpática centralmente. \"Anti-cocaína\" indireto."},
  ],
  diretriz:"AHA Cardiovascular Complications of Cocaine Use (McCord J et al., Circulation 2008).",
  calcs:[],
},
{
  id:"opioide", sis:"tox", grav:"alta",
  nome:"Intoxicação por Opioides",
  sin:["opioide","heroína","fentanil","morfina","naloxona"],
  def:"Tríade: miose puntiforme + depressão respiratória + alteração de consciência. Risco de parada respiratória.",
  exames:["Glicemia, eletrólitos","Gasometria","ECG (QT longo em metadona)"],
  rx:[
    {etapa:"adj", d:"Naloxona",do:"0,04–0,4 mg IV/IM/IN titulada",via:"IV/IM/IN",o:"Dose mínima eficaz — preservar analgesia, evitar abstinência. Repetir 2–3 min se necessário."},
    {etapa:"escala", d:"Naloxona BIC",do:"2/3 da dose efetiva/h",via:"IV",o:"Opioides de longa duração (metadona, opioides extended-release)."},
    {etapa:"escala", d:"Ventilação com BVM",do:"Ambu + máscara",via:"—",o:"Suporte respiratório enquanto naloxona age."},
    {etapa:"escala", d:"IOT se refratário ou aspiração",do:"—",via:"—",o:"Sem resposta a naloxona, vômito, aspiração."},
  ],
  alertas:[
    {t:"warn",x:"Naloxona tem T½ curta (30–60 min) — opioides de longa duração podem ressedar; observar 6–12h e considerar BIC."},
    {t:"info",x:"Abstinência aguda em uso crônico: agitação, midríase, sudorese — desconfortável mas não fatal."},
  ],
  fisio:"Opioides ativam receptores μ no SNC e medula → depressão do centro respiratório bulbar (↓resposta a hipercapnia) + sedação + analgesia + miose.",
  mec:[
    {d:"Naloxona",x:"<strong>Antagonista competitivo do receptor μ</strong> (também κ, δ) — reverte rapidamente os efeitos opioides."},
  ],
  diretriz:"WHO; CDC.",
  calcs:[],
},
{
  id:"bzd-tox", sis:"tox", grav:"media",
  nome:"Intoxicação por Benzodiazepínicos",
  sin:["benzodiazepínico","BZD","diazepam","flumazenil"],
  def:"Sedação + ataxia + disartria + raramente depressão respiratória (exceto polimedicado/idoso/IV).",
  exames:["Clínico","Excluir coingestão (álcool, opioide, antidepressivo)"],
  rx:[
    {etapa:"escala", d:"Suporte",do:"Vias aéreas, monitor",via:"—",o:"Pilar — maioria evolui bem só com observação."},
    {etapa:"escala", d:"Flumazenil",do:"0,2 mg IV em 30s, repetir 0,2 mg cada min até 1 mg",via:"IV",o:"USO RESTRITO — risco de convulsão. CI: uso crônico de BZD, coingestão TCA, hist. de epilepsia."},
  ],
  alertas:[
    {t:"crit",x:"FLUMAZENIL pode precipitar convulsões refratárias — usar apenas em iatrogenia (sedação procedimental) ou intoxicação isolada com depressão respiratória grave."},
  ],
  fisio:"BZDs potencializam GABA-A → ↑frequência de abertura de canais Cl⁻ → hiperpolarização → sedação, ansiólise, anticonvulsivante, miorrelaxamento.",
  mec:[
    {d:"Flumazenil",x:"<strong>Antagonista competitivo do sítio benzodiazepínico</strong> no receptor GABA-A. Reverte sedação e depressão respiratória."},
  ],
  diretriz:"AACT.",
  calcs:[],
},
{
  id:"alcool", sis:"tox", grav:"media",
  nome:"Intoxicação Alcoólica Aguda",
  sin:["álcool","etanol","intoxicação alcoólica","Wernicke"],
  def:"Embriaguez (etilemia variável) com risco de coma + hipoglicemia + hipotermia + aspiração.",
  exames:["HGT (excluir hipoglicemia)","Eletrólitos, função renal/hepática","Gasometria (acidose lática, KAD)","Etilemia (não rotineiro)","TC se trauma craniano"],
  rx:[
    {etapa:"adj", d:"Tiamina",do:"100 mg IV ANTES da glicose",via:"IV",o:"OBRIGATÓRIO em etilistas/desnutridos — prevenção de Wernicke."},
    {etapa:"adj", d:"Glicose 50%",do:"50 mL IV se hipoglicemia",via:"IV",o:"Após tiamina."},
    {etapa:"escala", d:"Hidratação",do:"SF 0,9% conforme déficit",via:"IV",o:"Cuidado com hiponatremia (potomania, polidipsia)."},
    {etapa:"escala", d:"Suporte",do:"Decúbito lateral + vias aéreas + monitor",via:"—",o:"Prevenção de aspiração."},
  ],
  alertas:[
    {t:"crit",x:"Wernicke-Korsakoff: tríade clássica (oftalmoplegia + ataxia + confusão). Tiamina ANTES da glicose previne. Em estabelecido: 500 mg IV 8/8h × 3 dias."},
  ],
  fisio:"Etanol potencializa GABA-A + inibe NMDA → depressão central. Metabolismo zero-order saturado (15–30 mg/dL/h).",
  mec:[
    {d:"Tiamina (vit B1)",x:"Cofator essencial para piruvato desidrogenase, α-cetoglutarato desidrogenase, transcetolase. Deficiência crônica em etilistas. Sem tiamina, infusão de glicose precipita encefalopatia de Wernicke (depleta tiamina remanescente)."},
  ],
  diretriz:"WHO; SBT.",
  calcs:[],
},
{
  id:"abstinencia", sis:"tox", grav:"alta",
  nome:"Abstinência Alcoólica",
  sin:["abstinência","delirium tremens","CIWA"],
  def:"Síndrome 6–24h após última dose de álcool em dependente: tremor, sudorese, taquicardia, ansiedade. Pode evoluir para convulsão (24–48h) e delirium tremens (48–96h).",
  exames:["Eletrólitos (K, Mg, Na, fósforo)","Função hepática","CIWA-Ar"],
  rx:[
    {etapa:"escala", d:"Diazepam",do:"5–20 mg VO/IV cada 1–2h conforme CIWA",via:"VO/IV",o:"1ª linha. Esquema flexível guiado por sintoma (CIWA ≥8)."},
    {etapa:"escala", d:"Lorazepam",do:"1–4 mg IV cada 30 min",via:"IV",o:"Hepatopata (sem metabólitos ativos)."},
    {etapa:"adj", d:"Tiamina",do:"100–300 mg IV/d × 3 dias",via:"IV",o:"Prevenir Wernicke."},
    {etapa:"adj", d:"Reposição eletrolítica",do:"K, Mg, fósforo VO/IV",via:"VO/IV",o:"Frequentemente deficitários."},
    {etapa:"escala", d:"Haloperidol",do:"2,5–5 mg IM",via:"IM",o:"Agitação refratária a BZD. Reduz limiar convulsivo — cautela."},
    {etapa:"adj", d:"Hidratação",do:"SF + glicose se necessário",via:"IV",o:"Após tiamina."},
  ],
  alertas:[
    {t:"crit",x:"DELIRIUM TREMENS (48–96h): confusão + alucinações + ↑↑adrenérgico. Mortalidade 5–15% sem tratamento. UTI + sedação agressiva."},
  ],
  fisio:"Dependência → upregulação de NMDA + downregulation de GABA. Suspensão → hiperatividade NMDA não-contrabalançada → hiperexcitabilidade neuronal → convulsão, alucinação, autonomia desregulada.",
  mec:[
    {d:"BZD",x:"Restauram tônus inibitório GABA-A → controlam todos os sintomas (tremor, ansiedade, convulsão, delirium)."},
  ],
  diretriz:"APA Substance Use Disorders; CIWA-Ar.",
  calcs:[],
},
);
/* PARTE 3 completa */
