/* ===========================================================
   VOVÔMINIC EMERGÊNCIA — BLOCO PALIATIVOS (Parte 2)
   Delirium, Sedação Paliativa, Estertor, Anorexia/Caquexia,
   Últimas Horas, Compressão Medular, Hipercalcemia, SPIKES
   =========================================================== */

PATOLOGIAS.push(

/* ============== DELIRIUM TERMINAL ============== */
{id:"delirium-paliativo", nome:"Delirium em Cuidados Paliativos — manejo agudo + terminal", sis:"pali", grav:"grave",
cid:"F05/R41.0", ciap:"P71",
sin:["Delirium paliativo","Confusão terminal","Agitação terminal","Haloperidol delirium","Levomepromazina"],
def:"⚠ DELIRIUM acomete 80-90% de pacientes paliativos em últimos dias. ⚠ Avaliar SEMPRE: é REVERSÍVEL (infecção, droga, dor, eletrólitos, retenção) ou IRREVERSÍVEL (falência sistêmica em fase ativa)? Conduta varia drasticamente. Subtipos: HIPERATIVO (agitação, agressividade), HIPOATIVO (sonolência, retraimento — mais comum, mais subdiagnosticado), MISTO.",
quadro:["⚠ Início AGUDO + flutuação + desatenção + alteração de consciência/cognição (DSM-5)","HIPERATIVO: agitação, agressividade, delírio, alucinação","HIPOATIVO: sonolência, retraimento, lentificação — frequentemente confundido com 'depressão' ou 'fadiga normal'","MISTO: alternância","⚠ DIFERENCIAR de demência (insidiosa) e depressão (humor)","⚠ Em fase ativa de morte: AGITAÇÃO TERMINAL — irreversível geralmente"],
diag:["⚠ CAM (Confusion Assessment Method): (1) início agudo + flutuação + (2) desatenção + (3) pensamento desorganizado OU (4) nível alterado consciência","Escalas: RASS (agitação-sedação), MDAS (Memorial Delirium Assessment Scale)","⚠ ⚠ INVESTIGAR REVERSIBILIDADE — RAÍZES MNEMÔNICAS:","D — Drogas (opioide, BZD, anticolinérgico, corticoide, abstinência)","E — Eletrólitos (Na, Ca, glicemia, ureia)","L — Low O2 (hipoxemia, hipercapnia, anemia)","I — Infecção (urinária, respiratória, sistêmica)","R — Retenção (urinária, fecal — fecaloma)","I — Insultos intracraniais (mets, AVC, HIC)","U — Uremia, falência hepática","M — Mais — dor, ambiente, privação sensorial"],
exames:["⚠ Triagem básica: hemograma, eletrólitos (Na, K, Ca corrigido, Mg), função renal+hepática, glicemia, gasometria, urocultura","SatO2 + Rx tórax se respiratório","Toque retal — fecaloma","Sondagem vesical se retenção","⚠ TC crânio se sinais focais novos / suspeita meta cerebral"],
rx:[
{etapa:"inicial", d:"⚠ AVALIAR FASE — REVERSÍVEL ou TERMINAL?"},
{etapa:"inicial", d:"⚠ Paciente com horizonte de SEMANAS-MESES + delirium agudo = INVESTIGAR + reverter causa"},
{etapa:"inicial", d:"⚠ Paciente em FASE ATIVA DE MORTE (horas-dias) + agitação = TRATAR SINTOMA (haloperidol, BZD se necessário)"},
{etapa:"escala", d:"⚠ ⚠ MEDIDAS NÃO-FARMACOLÓGICAS — SEMPRE primeiro/em paralelo"},
{etapa:"escala", d:"Ambiente CALMO, iluminação adequada (luz dia, escuro à noite), reorientação verbal frequente"},
{etapa:"escala", d:"Presença de FAMILIAR conhecido + objetos familiares; música preferida"},
{etapa:"escala", d:"REDUZIR estímulos: barulho, equipe rotativa, intervenções desnecessárias"},
{etapa:"escala", d:"⚠ DESPRESCREVER drogas precipitantes: anticolinérgicos, BZD se possível (cuidado com abstinência), opioide em dose excessiva, corticoide"},
{etapa:"escala", d:"⚠ TRATAR causas reversíveis identificadas: ATB se infecção, hidratação cuidadosa se desidratação, sondagem vesical se retenção, desimpactação fecal, correção eletrolítica"},
{etapa:"escala", d:"⚠ ⚠ FARMACOTERAPIA — quando agitação compromete cuidado ou sofrimento"},
{etapa:"escala", d:"⚠ HALOPERIDOL — 1ª LINHA"},
{etapa:"escala", d:"VO: 0,5-2 mg 8-12/12h (idoso: 0,25-0,5 mg). Resgate 0,5-1 mg 1/1h se necessário", do:"0,5-2 mg 8-12/12h + resgate", via:"VO", o:""},
{etapa:"escala", d:"⚠ SC: 1-2 mg cada 4-8h ou contínua 5-15 mg/d", do:"1-5 mg 4-8/8h SC", via:"SC", o:""},
{etapa:"escala", d:"IV apenas em ambiente monitorado (QT)", obs:""},
{etapa:"escala", d:"⚠ CUIDADO em IDOSO + cardiopata: QT longo (sem chegar a 30 mg/d evita risco maior)"},
{etapa:"escala", d:"⚠ ⚠ EVITAR EM PARKINSON / corpos de Lewy — preferir QUETIAPINA"},
{etapa:"escala", d:"⚠ AGITAÇÃO REFRATÁRIA / DELIRIUM HIPERATIVO INTENSO"},
{etapa:"escala", d:"⚠ ⚠ LEVOMEPROMAZINA 12,5-25 mg VO/SC 8-12/12h — sedativa, antiemética, ansiolítica", do:"12,5-50 mg 8-12/12h", via:"VO/SC", o:"⚠ ⚠ Mais sedativa que haloperidol — útil quando se busca sedação leve a moderada. REMUME / FARMASUS."},
{etapa:"escala", d:"⚠ ⚠ MIDAZOLAM SC 2,5-5 mg como resgate; BIC SC 0,5-2 mg/h em refratário", do:"2,5-5 mg SC", via:"SC", o:"⚠ Pode PIORAR delirium (paradoxo BZD) — usar em combinação com antipsicótico, raramente isolado."},
{etapa:"escala", d:"⚠ CLORPROMAZINA, OLANZAPINA — alternativas"},
{etapa:"escala", d:"⚠ QUETIAPINA 12,5-50 mg HS — em Parkinson/Lewy. Menos extrapiramidal.", obs:""},
{etapa:"adj", d:"⚠ DESCONTINUAÇÃO DE BZD em uso crônico — não suspender abruptamente (precipita delirium pior). Reduzir 10-25% a cada 2-3 dias"},
{etapa:"adj", d:"⚠ ABSTINÊNCIA ALCOÓLICA pode mimicar — tiamina 100 mg IV/IM + diazepam 5-10 mg conforme CIWA-Ar"},
{etapa:"alta", d:"⚠ COMUNICAÇÃO COM FAMÍLIA"},
{etapa:"alta", d:"⚠ DELIRIUM TERMINAL — explicar à família que NÃO é sofrimento intencional, NÃO é 'enlouquecer', é manifestação da doença"},
{etapa:"alta", d:"Orientar reorientação suave, presença, voz calma — não argumentar com delírios"},
{etapa:"alta", d:"⚠ AGITAÇÃO TERMINAL pode REQUERER SEDAÇÃO PALIATIVA — discutir com família + equipe"},
{etapa:"alta", d:"⚠ Após resolução em casos reversíveis: pode haver memórias angustiantes — apoio psicológico"},
],
alertas:[
{nivel:"crit", txt:"⚠ ⚠ INVESTIGAR REVERSIBILIDADE em delirium novo. Drogas + Eletrólitos + Infecção + Retenção + Dor + Hipoxia — checklist obrigatório."},
{nivel:"crit", txt:"⚠ HALOPERIDOL é 1ª LINHA — VO ou SC. Dose baixa em idoso (0,25-0,5 mg)."},
{nivel:"warn", txt:"⚠ HALOPERIDOL CONTRAINDICADO em Parkinson / demência de corpos de Lewy — pode precipitar rigidez grave / SNM. Usar QUETIAPINA."},
{nivel:"warn", txt:"⚠ BZD ISOLADO em delirium hiperativo: pode PIORAR (paradoxo). Útil em combinação com antipsicótico, em abstinência alcoólica/BZD, ou em sedação paliativa intencional."},
{nivel:"warn", txt:"⚠ DELIRIUM HIPOATIVO é MAIS COMUM e MAIS SUBDIAGNOSTICADO — paciente quieto/sonolento ≠ paciente em paz. Aplicar CAM."},
{nivel:"info", txt:"⚠ AGITAÇÃO TERMINAL refratária a antipsicótico + BZD = considerar SEDAÇÃO PALIATIVA proporcional (vide patologia 'sedacao-paliativa')."},
],
fluxo:"delirium-paliativo", diretriz:"ANCP; APA Delirium; Inouye et al; ESMO."
},

/* ============== SEDAÇÃO PALIATIVA ============== */
{id:"sedacao-paliativa", nome:"Sedação Paliativa — princípios e protocolo", sis:"pali", grav:"grave",
cid:"Z51.5", ciap:"A20",
sin:["Sedação paliativa","Sedação terminal","Midazolam paliativa","Sintoma refratário","Doutrina duplo efeito"],
def:"⚠ SEDAÇÃO PALIATIVA = uso INTENCIONAL de sedativos para REDUZIR CONSCIÊNCIA de paciente em fim de vida com SINTOMA REFRATÁRIO insuportável. ⚠ ≠ EUTANÁSIA (intenção é aliviar sintoma, não causar morte — princípio do DUPLO EFEITO). ⚠ ≠ Sedação 'leve' em UTI. Pode ser PROPORCIONAL (manter o mínimo necessário para conforto) ou PROFUNDA (refratariedade grave).",
quadro:["⚠ INDICAÇÕES: sintoma REFRATÁRIO + insuportável + em paciente com PROGNÓSTICO MUITO LIMITADO (horas-dias):","Dor refratária a opioide titulado","Dispneia refratária a opioide + BZD","Delirium / agitação terminal refratários","Vômito incoercível","Hemorragia maciça (cuidados de conforto)","Distresse existencial REFRATÁRIO (controverso — discussão multidisciplinar)","⚠ NÃO INDICAÇÃO: paciente com horizonte de semanas-meses + sintoma controlável"],
diag:["⚠ AVALIAÇÃO MULTIDISCIPLINAR — discutir caso com equipe + família + paciente quando lúcido","⚠ Critérios para 'refratariedade':","Sintoma não controlado apesar de abordagem otimizada","Toxicidade inaceitável de tratamentos","Probabilidade muito baixa de resposta a outras terapias","⚠ DOCUMENTAR: intenção (alívio de sintoma, não acelerar morte), discussão com paciente/família, opções exploradas, plano de monitorização","⚠ TIPOS:","PROPORCIONAL: dose mínima para conforto, mantém consciência se possível","PROFUNDA CONTÍNUA: para refratariedade grave em fase ativa","TRANSITÓRIA: respiro temporário (ex: 'crise' aguda, depois reavaliar)"],
exames:["Geralmente clínico","Foco em controle sintomático — exames adicionais apenas se mudam conduta"],
rx:[
{etapa:"inicial", d:"⚠ ⚠ DECISÃO COMPARTILHADA — paciente (se lúcido), família, equipe multidisciplinar"},
{etapa:"inicial", d:"⚠ DOCUMENTAR claramente: intenção (alívio sintoma refratário), sintoma alvo, opções exploradas e falhadas, plano de monitorização, comunicação com família"},
{etapa:"inicial", d:"⚠ NÃO ABANDONAR cuidados — sedação paliativa NÃO É retirar cuidado, é INTENSIFICAR conforto"},
{etapa:"escala", d:"⚠ MIDAZOLAM — 1ª LINHA"},
{etapa:"escala", d:"⚠ INDUÇÃO: 2,5-5 mg SC bolus (idoso/caquético: 1-2,5 mg), repetir cada 10-15 min até conforto", do:"2,5-5 mg SC bolus", via:"SC", o:""},
{etapa:"escala", d:"MANUTENÇÃO: BIC SC 0,5-2 mg/h (titular conforme RASS alvo)", do:"0,5-2 mg/h SC contínua", via:"SC", o:"⚠ Em paciente jovem/estável: doses maiores. Em idoso/caquético: doses bem menores."},
{etapa:"escala", d:"Alternativa BIC IV 1-3 mg/h se via IV mantida", obs:""},
{etapa:"escala", d:"⚠ RASS ALVO geralmente -2 a -3 (sedação leve a moderada — paciente arousable mas confortável); -4 a -5 em refratariedade extrema"},
{etapa:"escala", d:"⚠ MIDAZOLAM REFRATÁRIO (raro):"},
{etapa:"escala", d:"⚠ LEVOMEPROMAZINA SC 12,5-25 mg cada 4-6h OU BIC 50-100 mg/d — adicionar ao midazolam (efeito antiemético + sedativo + analgésico adjuvante)", do:"12,5-100 mg/d ÷ 4-6/6h ou BIC", via:"SC", o:""},
{etapa:"escala", d:"⚠ FENOBARBITAL SC bolus 100-200 mg + BIC 600-1600 mg/d — sedação profunda em refratários", obs:"Especialista."},
{etapa:"escala", d:"⚠ PROPOFOL BIC IV 0,5-2 mg/kg/h — em hospital com acesso IV mantido + monitor", obs:"Ambiente hospitalar."},
{etapa:"escala", d:"⚠ CETAMINA SC — em dor refratária associada (efeito dissociativo + analgésico)", obs:"Especialista."},
{etapa:"adj", d:"⚠ ⚠ MANTER OPIOIDE em paralelo — sedação NÃO substitui analgesia. Manter morfina, ajustar conforme dor/dispneia"},
{etapa:"adj", d:"⚠ MANTER HIOSCINA se estertor; manter haloperidol se náusea"},
{etapa:"adj", d:"⚠ DESPRESCREVER medicações não-essenciais (anti-hipertensivos, hipoglicemiantes, estatinas, etc) — fase ativa não justifica"},
{etapa:"adj", d:"⚠ HIDRATAÇÃO — discussão individualizada"},
{etapa:"adj", d:"Em fase ativa de morte: hidratação parenteral GERALMENTE NÃO BENEFICIA + pode piorar edema, estertor, sobrecarga. Suspender ou minimizar"},
{etapa:"adj", d:"Em paciente com expectativa de dias-semanas + delirium hipoativo por desidratação: pode-se considerar hipodermoclise 500-1000 mL/d SC"},
{etapa:"alta", d:"⚠ COMUNICAÇÃO CONTINUA com família"},
{etapa:"alta", d:"⚠ Reforçar: 'estamos aliviando o sofrimento, não acelerando a morte'"},
{etapa:"alta", d:"Informar processo esperado: respiração pode ficar irregular, estertor pode aparecer (não é sufocamento subjetivo), pele pode ficar mosqueada/marmórea"},
{etapa:"alta", d:"Encorajar família a falar com paciente, tocar, presença — audição persiste mais tempo"},
{etapa:"alta", d:"⚠ APOIO ao LUTO — antecipatório + pós-óbito"},
{etapa:"alta", d:"⚠ EQUIPE — apoio mútuo, supervisão; sedação paliativa é estresse emocional para profissionais"},
],
alertas:[
{nivel:"crit", txt:"⚠ ⚠ SEDAÇÃO PALIATIVA ≠ EUTANÁSIA. Intenção é aliviar sintoma refratário, não causar morte. Princípio do DUPLO EFEITO — ética + legalmente aceito no Brasil (Resolução CFM 1.805/2006 + 2.156/2016)."},
{nivel:"crit", txt:"⚠ REFRATARIEDADE deve ser bem documentada — sintoma intratável apesar de abordagem otimizada, com baixa probabilidade de resposta a outras terapias. Discussão multidisciplinar."},
{nivel:"warn", txt:"⚠ MIDAZOLAM SC é 1ª linha. Indução com bolus (2,5-5 mg) até conforto, depois BIC 0,5-2 mg/h. Idoso/caquético: doses menores."},
{nivel:"warn", txt:"⚠ MANTER ANALGESIA — sedação não substitui opioide. Morfina + midazolam em paralelo."},
{nivel:"info", txt:"⚠ HIDRATAÇÃO em fase ativa: GERALMENTE NÃO ÚTIL e pode piorar (edema, estertor, sobrecarga). Suspender ou minimizar (≤500 mL/d SC)."},
{nivel:"info", txt:"⚠ DOCUMENTAR: intenção, sintoma alvo, opções falhadas, discussão com família, plano de monitorização. Proteção ética e legal."},
],
fluxo:"sedacao-paliativa", diretriz:"ANCP Diretrizes Sedação Paliativa; EAPC; CFM Res 1.805/2006 + 2.156/2016; Cherny+Radbruch."
},

/* ============== ESTERTOR TERMINAL / SIALORREIA ============== */
{id:"estertor-terminal", nome:"Estertor da Morte / Sialorreia Terminal — manejo", sis:"pali", grav:"baixa",
cid:"R09.8", ciap:"R02",
sin:["Estertor terminal","Sororoca","Sialorreia paliativa","Hioscina","Escopolamina","Glicopirrônio"],
def:"⚠ ESTERTOR DA MORTE = ruído de gorgolejo em paciente em FASE ATIVA por acúmulo de secreção em vias aéreas (tipo I — saliva, paciente inconsciente sem deglutir; tipo II — secreção brônquica). ⚠ É MAIS ANGUSTIANTE PARA FAMÍLIA que para paciente — sedado, geralmente não sofre. Manejo: posicionamento + antimuscarínico SC + comunicação familiar.",
quadro:["⚠ RUÍDO de borbulhar / gorgolejar nas vias aéreas superiores em paciente em fase ativa de morte","Não confundir com obstrução de via aérea verdadeira / sufocamento","Paciente geralmente SEM esforço respiratório, sedado","⚠ Tipo I: secreção salivar acumulando (paciente inconsciente sem deglutir) — responde melhor ao antimuscarínico","⚠ Tipo II: secreção brônquica (causa subjacente — pneumonia, edema) — responde pior"],
diag:["⚠ Clínico — característica auscultatória + fase ativa","Observar paciente — sem esforço, sem cianose proeminente significa pouca repercussão respiratória do estertor","⚠ Diferenciar: dispneia ativa (esforço, taquipneia, uso musculatura) vs estertor passivo (ruído sem esforço aparente)"],
exames:["Geralmente nenhum — clínico"],
rx:[
{etapa:"inicial", d:"⚠ ⚠ COMUNICAÇÃO COM FAMÍLIA — INTERVENÇÃO MAIS IMPORTANTE"},
{etapa:"inicial", d:"⚠ Explicar: ruído é por acúmulo de saliva — paciente não está 'sufocando', não há sofrimento subjetivo significativo"},
{etapa:"inicial", d:"⚠ Reasseguramento — 'isso é parte do processo, vamos tornar mais confortável'"},
{etapa:"escala", d:"⚠ MEDIDAS NÃO-FARMACOLÓGICAS"},
{etapa:"escala", d:"⚠ POSICIONAMENTO em DECÚBITO LATERAL — facilita drenagem por gravidade", obs:""},
{etapa:"escala", d:"Cabeceira elevada 30°", obs:""},
{etapa:"escala", d:"⚠ ⚠ NÃO ASPIRAR rotineiramente — invasivo, doloroso, estimula tosse, MAIS secreção reativa. Aspiração apenas se secreção volumosa e bloqueando aeração", obs:""},
{etapa:"escala", d:"Cuidados orais — limpar boca com gaze úmida, hidratar mucosa", obs:""},
{etapa:"escala", d:"⚠ REDUZIR HIDRATAÇÃO PARENTERAL — se em curso, suspender ou minimizar (piora estertor)", obs:""},
{etapa:"escala", d:"⚠ ANTIMUSCARÍNICO SC — redução de secreção"},
{etapa:"escala", d:"⚠ ⚠ HIOSCINA BUTILBROMETO (BUSCOPAN) 20 mg SC 4-6/6h OU BIC 60-120 mg/d", do:"20 mg 4-6/6h SC", via:"SC", o:"⚠ ⚠ NÃO atravessa BHE — sem sedação, sem delirium. SEGURO em paciente acordado. 1ª LINHA NO BRASIL (disponível)."},
{etapa:"escala", d:"⚠ ESCOPOLAMINA (hioscina HIDROBROMETO) 0,4-0,6 mg SC 4-6/6h OU adesivo transdérmico 1 mg cada 72h", do:"0,4-0,6 mg 4-6/6h SC", via:"SC/TD", o:"⚠ Atravessa BHE — pode causar SEDAÇÃO + delirium em algumas pessoas. Adesivo é prático."},
{etapa:"escala", d:"⚠ GLICOPIRRÔNIO 0,2-0,4 mg SC 4-6/6h — mais potente, NÃO atravessa BHE", obs:"Acesso difícil no SUS."},
{etapa:"escala", d:"ATROPINA 0,4-0,6 mg SC 4-6/6h — alternativa em emergência (uso de injeção de atropina já disponível)", do:"0,4-0,6 mg 4-6/6h SC", via:"SC", o:"Atravessa BHE — risco delirium. Uso temporário."},
{etapa:"escala", d:"⚠ INÍCIO PRECOCE é mais eficaz — antes que muita secreção acumule. Em fase ativa: PRESCREVER PROACTIVAMENTE"},
{etapa:"adj", d:"⚠ EFICÁCIA da antimuscarínica é MODESTA — reduz secreção NOVA, não a secreção JÁ ACUMULADA"},
{etapa:"adj", d:"Em refratários: posicionamento + redução de hidratação + paciência + apoio familiar"},
{etapa:"alta", d:"⚠ FOCO EM CONFORTO familiar — explicar processo natural, reforçar que paciente está sereno"},
],
alertas:[
{nivel:"crit", txt:"⚠ ⚠ ESTERTOR É MAIS ANGUSTIANTE PARA A FAMÍLIA — paciente sedado raramente sofre. COMUNICAÇÃO FAMILIAR é tratamento principal."},
{nivel:"crit", txt:"⚠ ⚠ NÃO ASPIRAR rotineiramente — invasivo, doloroso, aumenta secreção reativa. Apenas se secreção volumosa obstruindo aeração."},
{nivel:"warn", txt:"⚠ HIOSCINA BUTILBROMETO (Buscopan) NÃO atravessa BHE — sem sedação/delirium adicional. 1ª linha no Brasil. ESCOPOLAMINA (hidrobrometo) atravessa BHE — risco delirium."},
{nivel:"warn", txt:"⚠ REDUZIR HIDRATAÇÃO PARENTERAL em fase ativa — piora estertor (e edema, sobrecarga, secreção respiratória). Geralmente suspender."},
{nivel:"info", txt:"⚠ ANTIMUSCARÍNICO precoce > tardio — secreção JÁ ACUMULADA não regride. Prescrever proactivamente quando estertor inicia."},
],
fluxo:null, diretriz:"ANCP; Wee-Hudson Sistema Review; EAPC."
},

/* ============== ANOREXIA E CAQUEXIA ============== */
{id:"anorexia-caquexia", nome:"Anorexia / Caquexia Oncológica — manejo paliativo", sis:"pali", grav:"baixa",
cid:"R63.0/C80", ciap:"T08",
sin:["Caquexia","Anorexia oncológica","Megestrol","Mirtazapina paliativo","Dexametasona apetite"],
def:"⚠ CAQUEXIA = perda involuntária de peso (>5% em 6m OU >2% se IMC baixo OU sarcopenia) + alterações metabólicas em paciente com doença sistêmica. ⚠ ≠ desnutrição por jejum — mesmo com nutrição não-reversível em fase avançada. ⚠ NÃO é falha do cuidador. Manejo: tratar reversíveis + apoiar família + foco em qualidade de vida (não em peso).",
quadro:["Perda de peso involuntária","Anorexia (perda de apetite)","Sarcopenia (perda massa muscular)","Inflamação sistêmica (PCR↑, citocinas inflamatórias)","⚠ Estágios: pré-caquexia → caquexia → caquexia refratária (irreversível, fase ativa)","⚠ DISTINGUIR de causas REVERSÍVEIS associadas: náusea, dor, depressão, mucosite, alteração de paladar, candidíase oral, constipação, hipercalcemia, hipotireoidismo, fármaco"],
diag:["⚠ Anamnese + exame: perda de peso real (pesar), apetite, sintomas associados","Avaliar SINTOMAS REVERSÍVEIS contributivos","⚠ ESCALAS: MUST (Malnutrition Universal Screening Tool), avaliação funcional (KPS/ECOG)","Imagem corporal — pode haver sofrimento associado"],
exames:["Hemograma","Albumina, PCR","Cálcio corrigido","Função renal/hepática","TSH","Glicemia"],
rx:[
{etapa:"inicial", d:"⚠ ⚠ COMUNICAÇÃO COM FAMÍLIA — MAIS IMPORTANTE QUE FÁRMACO"},
{etapa:"inicial", d:"⚠ Explicar: caquexia é causada pela DOENÇA, não por 'falta de comida'. Forçar a comer NÃO recupera o paciente"},
{etapa:"inicial", d:"⚠ Cultura brasileira valoriza 'comer bem' como sinal de saúde — pressão familiar pode causar SOFRIMENTO ao paciente"},
{etapa:"inicial", d:"⚠ ⚠ Em FASE AVANÇADA / ATIVA: comer pouco é NORMAL e SAUDÁVEL — diminuição metabólica fisiológica"},
{etapa:"inicial", d:"⚠ NÃO FORÇAR alimentação, SNG, NPT em fase ativa — pode causar dano (aspiração, edema, sofrimento)"},
{etapa:"escala", d:"⚠ TRATAR CAUSAS REVERSÍVEIS ASSOCIADAS"},
{etapa:"escala", d:"Náusea → antiemético adequado ao mecanismo (vide patologia)"},
{etapa:"escala", d:"Dor → analgesia otimizada"},
{etapa:"escala", d:"Depressão → ISRS, suporte"},
{etapa:"escala", d:"Mucosite → bochechos antifúngicos, anti-séptico, anestésico tópico"},
{etapa:"escala", d:"Candidíase oral → fluconazol 100 mg/d × 7-14d OU nistatina solução"},
{etapa:"escala", d:"Constipação → manejo (vide patologia)"},
{etapa:"escala", d:"Hipercalcemia → tratar"},
{etapa:"escala", d:"⚠ MEDIDAS NÃO-FARMACOLÓGICAS"},
{etapa:"escala", d:"⚠ Refeições PEQUENAS, frequentes, conforme PREFERÊNCIA do paciente — não impor 'cardápio saudável'"},
{etapa:"escala", d:"Alimentos com odor + temperatura adaptados ao gosto do paciente"},
{etapa:"escala", d:"AMBIENTE agradável, companhia, sem pressão"},
{etapa:"escala", d:"AVALIAR sabor — câncer/quimio altera percepção (metalizado, ageusia, dosgeusia) — sucos cítricos podem ajudar"},
{etapa:"escala", d:"⚠ COMPLEMENTOS NUTRICIONAIS (ex: Nutren, Nutridrink) — em fase não-terminal podem ajudar pacientes selecionados (preferir leve, sabor escolhido)"},
{etapa:"escala", d:"⚠ NUTRIÇÃO ENTERAL/PARENTERAL — papel LIMITADO em caquexia oncológica avançada. Pode ser ÚTIL em obstrução mecânica reversível, pré-procedimento (cirurgia, RT), paciente com expectativa adequada"},
{etapa:"escala", d:"⚠ ⚠ EM FASE ATIVA DE MORTE: NÃO INICIAR nutrição artificial; AVALIAR SUSPENSÃO se já em curso (decisão compartilhada)"},
{etapa:"adj", d:"⚠ FARMACOTERAPIA — efeito MODESTO em apetite/peso, sem impacto em sobrevida ou função"},
{etapa:"adj", d:"⚠ DEXAMETASONA 2-4 mg/d manhã — efeito CURTO PRAZO (4-6 sem) em apetite/bem-estar, antiemético, antiinflamatório", do:"2-4 mg/d manhã", via:"VO/SC", o:"⚠ Efeito DIMINUI com tempo. Efeitos colaterais cumulativos (miopatia, candida, hiperglicemia). Útil em PACIENTE EM SEMANAS-DIAS."},
{etapa:"adj", d:"⚠ MEGESTROL ACETATO 160-800 mg/d — análogo progestágeno, efeito orexígeno e ganho de peso (gordura), poucas semanas para iniciar", do:"160-800 mg/d", via:"VO", o:"⚠ ⚠ RISCO TROMBOEMBÓLICO + supressão adrenal + edema. Cara. Útil em paciente com expectativa de meses."},
{etapa:"adj", d:"⚠ MIRTAZAPINA 15-30 mg HS — antidepressivo com efeito orexígeno + sedativo + antiemético", do:"15-30 mg HS", via:"VO", o:"⚠ Particularmente útil em paciente com TRIPLA INDICAÇÃO: depressão + insônia + caquexia. (vide bloco psiq)"},
{etapa:"adj", d:"⚠ OLANZAPINA 2,5-5 mg HS — efeito orexígeno + antiemético em refratários", obs:""},
{etapa:"adj", d:"⚠ CANABINOIDES (dronabinol em alguns países) — efeito orexígeno modesto, mais útil em quimio-induzida", obs:""},
{etapa:"adj", d:"⚠ TALIDOMIDA 100-200 mg/d — em caquexia HIV ou oncológica, efeito modesto, especialista (regulamentações específicas)", obs:""},
{etapa:"alta", d:"⚠ COMUNICAÇÃO + APOIO PSICOLÓGICO + ESPIRITUAL"},
{etapa:"alta", d:"Caquexia é sinal de doença avançada — momento para conversas sobre objetivos de cuidado, expectativas"},
{etapa:"alta", d:"⚠ Família frequentemente reage com EMPENHO em alimentar — redirecionar para presença, conversa, contato"},
],
alertas:[
{nivel:"crit", txt:"⚠ ⚠ NÃO FORÇAR alimentação em paciente em fase avançada/ativa. Comer pouco é NORMAL e SAUDÁVEL fisiologicamente. Pressionar gera sofrimento."},
{nivel:"crit", txt:"⚠ NUTRIÇÃO PARENTERAL / SNG raramente beneficia em caquexia oncológica avançada — pode causar dano (aspiração, edema, sobrecarga, infecção)."},
{nivel:"warn", txt:"⚠ DEXAMETASONA tem efeito CURTO PRAZO (4-6 sem) em apetite/bem-estar — útil em paciente em SEMANAS-DIAS. Cuidado com cumulativos."},
{nivel:"warn", txt:"⚠ MEGESTROL tem efeito orexígeno mas RISCO TROMBOEMBÓLICO significativo. Em paciente com sobrevida estimada de meses + sem fatores de risco."},
{nivel:"info", txt:"⚠ TRATAR CAUSAS REVERSÍVEIS (mucosite, candidíase, dor, náusea, depressão) PRIMEIRO. Pode haver melhora significativa sem ir para 'estimulador de apetite'."},
{nivel:"info", txt:"⚠ MIRTAZAPINA: tripla indicação prática (depressão + insônia + ↓ peso) — combo útil em paciente paliativo selecionado."},
],
fluxo:null, diretriz:"ESPEN; ANCP; ASCO Cancer Cachexia 2020."
},

/* ============== ÚLTIMAS HORAS / KIT FIM DE VIDA / VIA SC ============== */
{id:"ultimas-horas", nome:"Últimas Horas de Vida — Cuidados + Kit + Via Subcutânea (SC)", sis:"pali", grav:"grave",
cid:"Z51.5", ciap:"A20",
sin:["Fim de vida","Últimas horas","Kit paliativo","Via subcutânea","Hipodermoclise","Agonia"],
def:"⚠ FASE ATIVA DE MORTE = horizonte de horas-dias. Sinais clínicos clássicos. ⚠ Foco TOTAL em CONFORTO + comunicação familiar. Via SUBCUTÂNEA é via central. KIT BÁSICO previamente prescrito permite resposta rápida em domicílio sem necessidade de UPA. ⚠ Permitir morte em DOMICÍLIO quando esse é o desejo do paciente — direito assegurado.",
quadro:["⚠ SINAIS CLÍNICOS de FASE ATIVA (horas-dias):","↓ ingesta de líquidos e sólidos / dificuldade deglutição","Sonolência crescente, intervalos lúcidos cada vez menores","Respiração irregular — Cheyne-Stokes, pausas, agônica","Estertor terminal (gorgolejo)","Pele MOSQUEADA / marmórea / FRIA em extremidades, cianose periférica","Pulso fino, PA caindo","Diurese reduzida (oligo-anúria)","Alteração cognitiva — delirium, alucinações 'visitantes', referência a viagem","Aparente 'alívio' nas últimas horas em alguns (calm before)","⚠ Pode haver DESPERTAR antes do óbito ('lucidez terminal' / surge final) — frequentemente significativo emocionalmente"],
diag:["⚠ CLÍNICO — reconhecimento de fase","Aceitação da família e do paciente quando possível — não 'forçar reanimação' em fase ativa","⚠ DOCUMENTAR: paciente em fase ativa, plano de cuidados (não-RCP em geral, foco conforto, via SC)","Discussão de OBJETIVOS DE CUIDADO — se ainda não feita, agora"],
exames:["⚠ Geralmente NENHUM — exames adicionais não modificam conduta","Não fazer 'check' de exames laboratoriais de rotina","⚠ DESPRESCREVER medicações não-essenciais"],
rx:[
{etapa:"inicial", d:"⚠ ⚠ ⚠ RECONHECIMENTO DA FASE — comunicar família com clareza"},
{etapa:"inicial", d:"'Estamos entrando nos últimos dias/horas. O foco agora é conforto e presença'"},
{etapa:"inicial", d:"⚠ Reorganizar prioridades: CONFORTO + DIGNIDADE + PRESENÇA FAMILIAR + AMBIENTE"},
{etapa:"escala", d:"⚠ DESPRESCREVER medicações não-essenciais"},
{etapa:"escala", d:"SUSPENDER: anti-hipertensivos, hipoglicemiantes, estatinas, suplementos, vitaminas, antiagregante, AAS preventivo, beta-bloqueador (avaliação caso a caso)"},
{etapa:"escala", d:"MANTER: opioides, antiemético, sedativo, antimuscarínico (estertor), corticoide se útil sintomático"},
{etapa:"escala", d:"⚠ AVALIAR via — VO frequentemente inviável (disfagia, sonolência)"},
{etapa:"escala", d:"⚠ ⚠ VIA SUBCUTÂNEA (SC) — VIA CENTRAL EM PALIATIVOS"},
{etapa:"escala", d:"⚠ ACESSO: cateter (butterfly 21-25 G ou cateter Saf-T-Intima 24G), sítios: deltóide, abdome, coxa anterior, infraclavicular, escapular"},
{etapa:"escala", d:"⚠ RODÍZIO cada 5-7 dias OU se irritação local"},
{etapa:"escala", d:"⚠ VOLUME por sítio: bolus ≤ 2 mL; infusão contínua ≤ 1-2 mL/h (até 4 mL/h se necessário)"},
{etapa:"escala", d:"⚠ DROGAS COMPATÍVEIS SC: morfina, midazolam, haloperidol, levomepromazina, dexametasona, ondansetrona, metoclopramida, hioscina butilbrometo, escopolamina, octreotida, furosemida (volume baixo), enoxaparina, insulina"},
{etapa:"escala", d:"⚠ ⚠ NÃO PODEM ser SC: clorpromazina (necrose), diazepam (precipitação), fenitoína (precipitação), ceftriaxona (necrose), eletrólitos concentrados (K+, NaCl 3%)"},
{etapa:"escala", d:"⚠ HIPODERMOCLISE = hidratação SC com SF 0,9% ou SG 5%, ritmo 25-125 mL/h, até 1500 mL/d. Útil em desidratação leve-moderada. ⚠ Avaliar benefício em fase ativa (frequentemente NÃO indicada)"},
{etapa:"escala", d:"⚠ ⚠ KIT FIM DE VIDA — PRESCRIÇÃO ANTECIPADA EM DOMICÍLIO"},
{etapa:"escala", d:"⚠ Permite à família + cuidador responder a sintomas SEM emergência hospitalar"},
{etapa:"escala", d:"⚠ Drogas + posologia + indicações específicas, dispostas em local acessível"},
{etapa:"escala", d:"COMPOSIÇÃO BÁSICA (variável conforme paciente):"},
{etapa:"escala", d:"(1) MORFINA simples solução oral OU ampola SC — DOR, DISPNEIA"},
{etapa:"escala", d:"(2) MIDAZOLAM ampola 5 mg/mL SC — agitação, dispneia ansiosa, sedação proporcional"},
{etapa:"escala", d:"(3) HALOPERIDOL ampola 5 mg/mL SC — náusea, delirium leve"},
{etapa:"escala", d:"(4) HIOSCINA BUTILBROMETO 20 mg ampola SC — estertor, cólica"},
{etapa:"escala", d:"(5) DEXAMETASONA 4 mg ampola SC — náusea, dispneia (selecionados)"},
{etapa:"escala", d:"(6) LEVOMEPROMAZINA — em refratários"},
{etapa:"escala", d:"+ SERINGAS (1, 5, 10 mL), agulhas 25G, gaze, álcool, papel-toalha"},
{etapa:"escala", d:"+ FOLHA DE INSTRUÇÕES com indicações + doses + telefone do plantonista"},
{etapa:"adj", d:"⚠ EQUIPE de SAD/EMAD ou cuidados paliativos domiciliar idealmente"},
{etapa:"adj", d:"⚠ Em Estiva Gerbi: articular com SAD do município + matriciamento com paliativos regional"},
{etapa:"adj", d:"⚠ NÃO HÁ 'protocolo único' — KIT É INDIVIDUALIZADO ao paciente e sintomas previsíveis"},
{etapa:"alta", d:"⚠ COMUNICAÇÃO COM FAMÍLIA"},
{etapa:"alta", d:"⚠ Permitir / orientar: tocar, falar, despedidas — audição persiste até bem tarde"},
{etapa:"alta", d:"⚠ Sinais de morte iminente: cianose, respiração agônica, ausência de pulso, mosqueamento — explicar antes de acontecer reduz pânico"},
{etapa:"alta", d:"⚠ APÓS O ÓBITO: declaração de óbito em domicílio (em Estiva Gerbi, médico assistente declara — não precisa IML em óbito esperado de doença conhecida em paliativos)"},
{etapa:"alta", d:"⚠ ATESTADO em paciente em paliativos: causa imediata + causa intermediária + causa básica (CID da doença oncológica/avançada de base)"},
{etapa:"alta", d:"⚠ APOIO AO LUTO — antecipatório + pós-óbito. Acompanhamento da família é parte do cuidado paliativo"},
],
alertas:[
{nivel:"crit", txt:"⚠ ⚠ RECONHECER A FASE ATIVA — comunicar com clareza à família. Reorganizar para CONFORTO. Não 'forçar reanimação' em paciente em final de vida natural."},
{nivel:"crit", txt:"⚠ ⚠ VIA SUBCUTÂNEA é VIA CENTRAL em paliativos. Acesso fácil + pouco doloroso + drogas múltiplas compatíveis. NÃO é 'segunda escolha' — em paliativos é PRIMEIRA."},
{nivel:"warn", txt:"⚠ KIT FIM DE VIDA prescrito ANTECIPADAMENTE evita emergência domiciliar. Família/cuidador treinado pode administrar SC. Reduz hospitalização desnecessária."},
{nivel:"warn", txt:"⚠ DESPRESCREVER em fase ativa: anti-hipertensivos, hipoglicemiantes, estatinas, suplementos. Manter: opioide, antiemético, sedativo, antimuscarínico, corticoide útil."},
{nivel:"warn", txt:"⚠ ESTERTOR + RESPIRAÇÃO AGÔNICA podem parecer angustiantes para FAMÍLIA mas raramente são sofrimento para paciente. COMUNICAÇÃO é tratamento."},
{nivel:"info", txt:"⚠ DECLARAÇÃO DE ÓBITO EM DOMICÍLIO em paciente em paliativos: médico assistente declara, NÃO precisa IML em óbito esperado de doença conhecida. Causa imediata + intermediária + básica (CID neoplasia/doença avançada)."},
{nivel:"info", txt:"⚠ APOIO AO LUTO antecipatório + pós-óbito é parte do cuidado paliativo. Equipe inclui família como unidade de cuidado."},
],
fluxo:"ultimas-horas", diretriz:"ANCP; EAPC; PCMS-MS; LCP (Liverpool Care Pathway atualizado)."
},

/* ============== COMPRESSÃO MEDULAR MALIGNA ============== */
{id:"compressao-medular-maligna", nome:"Compressão Medular Maligna — EMERGÊNCIA Oncológica", sis:"pali", grav:"grave",
cid:"G95.2/C79.5", ciap:"L86",
sin:["Compressão medular","CMM","Metástase coluna","Dexametasona compressão","Radioterapia paliativa urgente"],
def:"⚠ ⚠ ⚠ EMERGÊNCIA ONCOLÓGICA — compressão por metástase epidural / vertebral. JANELA TERAPÊUTICA CURTA — déficit motor instalado >48h frequentemente IRREVERSÍVEL. ⚠ Reconhecimento + dexametasona + RM + radioterapia/cirurgia em HORAS. DOR LOMBAR NOVA/PROGRESSIVA em ONCOLÓGICO = investigar SEMPRE.",
quadro:["⚠ DOR LOMBAR / TORÁCICA progressiva, mecânica, piora com decúbito — pode anteceder déficit em SEMANAS","⚠ DÉFICIT MOTOR — paraparesia / tetraparesia conforme nível","Alteração sensitiva com NÍVEL definido","⚠ DISFUNÇÃO ESFINCTERIANA — retenção urinária, constipação, incontinência (lesão tardia, prognóstico pior)","⚠ Sinais de neurônio motor superior abaixo da lesão (hiperreflexia, Babinski) em torácica; flacidez em síndrome cauda equina","Primários frequentes: mama, próstata, pulmão, mieloma múltiplo, rim, linfoma"],
diag:["⚠ ⚠ ALTA SUSPEIÇÃO — dor lombar nova em oncológico = investigar SEMPRE","Exame neurológico CUIDADOSO: força (escala MRC), sensibilidade com NÍVEL, reflexos, tônus","⚠ TOQUE RETAL — avaliar tônus esfincteriano + bulbo-cavernoso"],
exames:["⚠ ⚠ ⚠ RM COLUNA TOTAL (cervical + torácica + lombar) URGENTE — IDEALMENTE EM HORAS","⚠ Se RM indisponível: TC coluna com contraste OU mielo-TC (alternativa)","⚠ Rx coluna pode estar normal mesmo com compressão — não tranquiliza"],
rx:[
{etapa:"inicial", d:"⚠ ⚠ ⚠ DEXAMETASONA EM BOLUS IMEDIATA — não esperar imagem"},
{etapa:"inicial", d:"⚠ DEXAMETASONA 16 mg IV BOLUS ÚNICO, depois 4 mg IV 6/6h × 48h, depois reduzir conforme resposta", do:"16 mg IV bolus + 4 mg 6/6h", via:"IV", o:"⚠ NÃO ESPERAR confirmação — déficit pode evoluir em horas. Em paciente com forte suspeita: BOLUS imediato em qualquer setor (UBS, PA)."},
{etapa:"inicial", d:"⚠ ANALGESIA — opioide adequado, geralmente em escalonamento rápido"},
{etapa:"inicial", d:"⚠ ⚠ REFERENCIAMENTO IMEDIATO — RM URGENTE + oncologia/radioterapia/neurocirurgia"},
{etapa:"escala", d:"⚠ TRATAMENTO DEFINITIVO"},
{etapa:"escala", d:"⚠ ⚠ RADIOTERAPIA PALIATIVA URGENTE — em até 24-48h em paciente com déficit"},
{etapa:"escala", d:"⚠ CIRURGIA DE DESCOMPRESSÃO + estabilização — indicada em paciente com bom performance + sobrevida estimada >3-6m + déficit estabelecido <48h + instabilidade espinhal + tumor radio-resistente (carcinoma renal, sarcoma)"},
{etapa:"escala", d:"⚠ COMBINAÇÃO cirurgia + radioterapia adjuvante — em casos selecionados"},
{etapa:"escala", d:"⚠ Em paciente com expectativa LIMITADA (semanas) ou já parapelégico há >48h: apenas DEXAMETASONA + ANALGESIA + suporte (déficit não recuperável)"},
{etapa:"adj", d:"⚠ TROMBOPROFILAXIA — enoxaparina 40 mg SC 1×/d em paciente acamado por déficit"},
{etapa:"adj", d:"⚠ MANEJO DE BEXIGA — sondagem vesical de demora ou intermitente; cateterismo conforme função"},
{etapa:"adj", d:"⚠ MANEJO INTESTINAL — laxativos, supositórios, lavagem em paciente neurogênico"},
{etapa:"adj", d:"⚠ FISIOTERAPIA / REABILITAÇÃO precoce"},
{etapa:"adj", d:"⚠ BIFOSFONATO em metástase óssea (ácido zoledrônico 4 mg IV/mês) — preventivo de eventos esqueléticos"},
{etapa:"alta", d:"⚠ COMUNICAÇÃO — explicar urgência + janela de oportunidade"},
{etapa:"alta", d:"⚠ Após estabilização: discussão de objetivos de cuidado, prognóstico, retorno a casa, planejamento avançado"},
{etapa:"alta", d:"⚠ APOIO ao paciente em adaptação (cadeirante, sondado) — fisioterapia, psicologia, social"},
],
alertas:[
{nivel:"crit", txt:"⚠ ⚠ ⚠ COMPRESSÃO MEDULAR = EMERGÊNCIA. Déficit motor >48h frequentemente IRREVERSÍVEL. ⚠ DEXAMETASONA 16 mg IV BOLUS IMEDIATA em suspeita — não esperar imagem."},
{nivel:"crit", txt:"⚠ DOR LOMBAR NOVA/PROGRESSIVA em ONCOLÓGICO = SEMPRE INVESTIGAR. Pode anteceder déficit em semanas — JANELA para imagem + tratamento preventivo."},
{nivel:"crit", txt:"⚠ ⚠ RM COLUNA TOTAL URGENTE — preferida. Se indisponível: TC com contraste / mielo-TC."},
{nivel:"warn", txt:"⚠ RADIOTERAPIA PALIATIVA em 24-48h em paciente com déficit + sobrevida adequada. Cirurgia indicada em casos específicos (instabilidade, tumor radio-resistente, paciente com bom performance)."},
{nivel:"warn", txt:"⚠ Em paciente em fase muito avançada ou já paraplégico >48h: foco em conforto + analgesia + suporte (não há recuperação esperada). NÃO submeter a procedimentos invasivos sem benefício."},
],
fluxo:"compressao-medular", diretriz:"NICE Spinal Cord Compression; NCCN; SBOC."
},

/* ============== HIPERCALCEMIA DA MALIGNIDADE ============== */
{id:"hipercalcemia-maligna", nome:"Hipercalcemia da Malignidade — EMERGÊNCIA paliativa", sis:"pali", grav:"grave",
cid:"E83.5", ciap:"T99",
sin:["Hipercalcemia maligna","PTHrP","Bifosfonato","Ácido zoledrônico","Calcitonina","Denosumab"],
def:"⚠ EMERGÊNCIA — cálcio iônico ou Ca total CORRIGIDO PELA ALBUMINA >12 mg/dL com sintomas (poliúria, polidipsia, fraqueza, letargia, confusão, náusea, constipação severa, arritmia). ⚠ Frequente em mama, pulmão, mieloma, rim, cabeça e pescoço. Mortalidade alta em hipercalcemia GRAVE (>14) — tratamento emergencial paliativo.",
quadro:["⚠ NEURO: letargia, confusão, sonolência, coma (com Ca >15)","⚠ GU: poliúria (diabete insipidus nefrogênico), desidratação intensa","⚠ GI: constipação severa, náusea, vômito, anorexia, dor abdominal, pancreatite (raro)","⚠ MUSC: fraqueza, hipotonia, fraqueza proximal","⚠ CV: bradicardia, encurtamento QT, BLOQUEIO em hipercalcemia muito alta","Risco de PCR em Ca >15-16"],
diag:["⚠ Cálcio total — sempre CORRIGIR PELA ALBUMINA: Ca corrigido = Ca medido + 0,8 × (4 − albumina)","Ou medir CÁLCIO IÔNICO (mais preciso)","⚠ Em paciente oncológico com sintomas inexplicados (letargia, constipação, fraqueza): SEMPRE pedir cálcio"],
exames:["⚠ Cálcio total + albumina (calcular corrigido) OU cálcio iônico","Fósforo","Função renal — ureia, creatinina","Eletrólitos","PTH (afastar hiperparatireoidismo primário em casos atípicos)","ECG — QT, arritmia","Glicemia"],
rx:[
{etapa:"inicial", d:"⚠ ⚠ HIDRATAÇÃO VIGOROSA — pedra angular do tratamento"},
{etapa:"inicial", d:"⚠ SOLUÇÃO SALINA 0,9% 200-500 mL/h IV — corrige desidratação + aumenta excreção renal de cálcio", do:"200-500 mL/h IV", via:"IV", o:"⚠ Volume total: 2-4 L em 24h. Monitor: PA, ausculta pulmonar, débito urinário, balanço."},
{etapa:"inicial", d:"⚠ ⚠ EM PALIATIVO COM SOBREVIDA MUITO LIMITADA: avaliar SE TRATAR — vide alerta. Em fase ativa de morte: hipercalcemia pode ser via de morte 'mais suave' — discutir com paciente/família"},
{etapa:"escala", d:"⚠ FUROSEMIDA 20-40 mg IV — usar APENAS após CORRIGIR desidratação. Aumenta cálcio urinário."},
{etapa:"escala", d:"⚠ NÃO usar tiazídico (reduz cálcio urinário)"},
{etapa:"escala", d:"⚠ ⚠ BIFOSFONATO — droga de DESFECHO"},
{etapa:"escala", d:"⚠ ÁCIDO ZOLEDRÔNICO 4 mg IV em 15 min", do:"4 mg IV em 15 min", via:"IV", o:"⚠ INÍCIO de ação em 24-48h. Pico em 4-7 dias. Duração ~30 dias. Reduzir 50% se TFG 30-60. ⚠ EVITAR em TFG <30."},
{etapa:"escala", d:"⚠ PAMIDRONATO 60-90 mg IV em 2-4h — alternativa", do:"60-90 mg IV em 2-4h", via:"IV", o:"Menos potente."},
{etapa:"escala", d:"⚠ HIDRATAR adequadamente antes (>2L) — bifosfonato é nefrotóxico em desidratação"},
{etapa:"escala", d:"⚠ CALCITONINA 4-8 UI/kg SC/IM 12/12h — ação RÁPIDA (12-24h) mas taquifilaxia em 48-72h", do:"4-8 UI/kg SC 12/12h", via:"SC/IM", o:"⚠ Útil em pacientes em ESPERA do efeito do bifosfonato (primeiras 24-48h). Eficácia decai."},
{etapa:"escala", d:"⚠ DENOSUMAB 120 mg SC — anticorpo anti-RANKL. Alternativa em IRC (TFG <30 onde bifosfonato é proibido)", do:"120 mg SC dose única", via:"SC", o:"Custo alto. Especialista."},
{etapa:"escala", d:"⚠ DEXAMETASONA — útil em hipercalcemia por LINFOMA, MIELOMA, GRANULOMATOSE (mediação 1,25-OH-vit D)", obs:"Não é eficaz em hipercalcemia por PTHrP."},
{etapa:"adj", d:"⚠ EM HIPERCALCEMIA REFRATÁRIA / GRAVE COM IRC + RISCO DE VIDA: HEMODIÁLISE com banho baixo cálcio"},
{etapa:"adj", d:"⚠ MOBILIZAÇÃO precoce (imobilidade piora hipercalcemia)"},
{etapa:"alta", d:"⚠ DISCUTIR PROGNÓSTICO + OBJETIVOS — hipercalcemia maligna é frequentemente MARCADOR DE FASE AVANÇADA"},
{etapa:"alta", d:"⚠ Sobrevida média após hipercalcemia maligna = ~30 dias (sem tratamento específico do tumor)"},
{etapa:"alta", d:"⚠ TRATAR vs OBSERVAR — decisão depende de objetivos. Tratar pode reverter sintomas e dar 'tempo' para conversas/encerramentos; não tratar pode ser óbito sem sofrimento"},
],
alertas:[
{nivel:"crit", txt:"⚠ ⚠ HIPERCALCEMIA MALIGNA é EMERGÊNCIA. Hidratação salina 0,9% 200-500 mL/h + bifosfonato (ác. zoledrônico 4 mg IV) + considerar calcitonina como ponte."},
{nivel:"crit", txt:"⚠ ⚠ EM PALIATIVO AVANÇADO / FASE ATIVA: avaliar SE TRATAR. Hipercalcemia maligna é frequentemente VIA DE MORTE 'mais suave' que outras (letargia → coma). Discussão compartilhada com paciente/família."},
{nivel:"warn", txt:"⚠ FUROSEMIDA: usar APENAS APÓS hidratação adequada. Tiazídico é CONTRAINDICADO (↓ excreção de cálcio)."},
{nivel:"warn", txt:"⚠ ÁCIDO ZOLEDRÔNICO em TFG <30: EVITAR. Em TFG 30-60: 50% dose. Em IRC importante: denosumab é alternativa."},
{nivel:"warn", txt:"⚠ DEXAMETASONA: útil em hipercalcemia por LINFOMA / MIELOMA / GRANULOMATOSE. NÃO é eficaz em hipercalcemia por PTHrP (mama, pulmão escamoso)."},
{nivel:"info", txt:"⚠ SOBREVIDA MÉDIA após hipercalcemia maligna não tratada = ~30 dias. Tratar pode REVERTER sintomas e proporcionar TEMPO para conversas + encerramentos."},
],
fluxo:null, diretriz:"NCCN; ESMO; ASCO; Major et al; Stewart NEJM."
},

/* ============== COMUNICAÇÃO DE MÁS NOTÍCIAS — PROTOCOLO SPIKES ============== */
{id:"comunicacao-spikes", nome:"Comunicação de Más Notícias — Protocolo SPIKES + Plano de Cuidado Avançado", sis:"pali", grav:"baixa",
cid:"Z71", ciap:"A45",
sin:["SPIKES","Más notícias","Comunicação difícil","Diretivas antecipadas","Plano de cuidado avançado","Diagnóstico câncer"],
def:"⚠ COMUNICAÇÃO de más notícias é HABILIDADE CLÍNICA CENTRAL — não 'estilo pessoal'. Treinável, validada. ⚠ PROTOCOLO SPIKES (Baile et al, 2000) — 6 passos. Equivocada comunicação é causa frequente de SOFRIMENTO + processos. ⚠ Inclui: diagnóstico ruim, prognóstico limitado, discussão de objetivos de cuidado, decisões de fim de vida.",
quadro:["⚠ MÁS NOTÍCIAS = qualquer informação que altere expectativas do paciente em relação ao futuro de forma adversa","Diagnóstico de doença grave (câncer, demência, IC, esclerose)","Progressão / recidiva","Falha de tratamento","Prognóstico limitado","Necessidade de mudança de objetivos (curativo → paliativo)","Discussão de fim de vida"],
diag:["Não é diagnóstico — é HABILIDADE CLÍNICA","⚠ Auto-avaliação: 'Como estou para esta conversa? Tenho tempo, lugar, energia?'","⚠ Preparo prévio: ler prontuário, alinhar com equipe, ter dados objetivos prontos"],
exames:["Não aplicável"],
rx:[
{etapa:"escala", d:"⚠ ⚠ PROTOCOLO SPIKES — 6 PASSOS"},
{etapa:"escala", d:"⚠ S — SETTING (ambiente)"},
{etapa:"escala", d:"AMBIENTE PRIVATIVO — sala fechada, sem interrupções"},
{etapa:"escala", d:"TEMPO ADEQUADO — pelo menos 30 min, sem pressa de saída"},
{etapa:"escala", d:"PRESENÇA DE FAMILIAR — se paciente desejar"},
{etapa:"escala", d:"POSIÇÃO — sentar em altura do paciente, sem mesa entre vocês, sem celular"},
{etapa:"escala", d:"DESLIGAR celular / pager. Comunicar à equipe 'não interromper'"},
{etapa:"escala", d:"⚠ P — PERCEPTION (percepção do paciente)"},
{etapa:"escala", d:"'O que você sabe sobre sua situação atual?'"},
{etapa:"escala", d:"'O que os outros médicos disseram?'"},
{etapa:"escala", d:"⚠ Calibrar — paciente está em NEGAÇÃO, em CONHECIMENTO PARCIAL, ou em CONHECIMENTO COMPLETO?"},
{etapa:"escala", d:"Não 'corrigir' negação imediatamente — explorar com cuidado"},
{etapa:"escala", d:"⚠ I — INVITATION (convite)"},
{etapa:"escala", d:"'Quanta informação você gostaria de saber sobre os resultados?'"},
{etapa:"escala", d:"'Você prefere que eu fale com você ou com alguém da família primeiro?'"},
{etapa:"escala", d:"⚠ RESPEITAR — alguns pacientes preferem NÃO saber tudo (válido)"},
{etapa:"escala", d:"⚠ K — KNOWLEDGE (compartilhar conhecimento)"},
{etapa:"escala", d:"⚠ 'TIRO DE AVISO' (warning shot) — 'Preciso compartilhar algo difícil...' / 'Os resultados não são os que esperávamos...'"},
{etapa:"escala", d:"DAR a notícia em LINGUAGEM SIMPLES, sem jargão"},
{etapa:"escala", d:"PAUSA — silêncio é necessário, dar tempo para absorver"},
{etapa:"escala", d:"PEDAÇOS pequenos — não despejar tudo de uma vez"},
{etapa:"escala", d:"⚠ NÃO mentir / NÃO suavizar excessivamente — 'pequeno tumor', 'algumas células diferentes' geram confusão"},
{etapa:"escala", d:"⚠ E — EMPATHY / EMOTIONS (responder a emoções)"},
{etapa:"escala", d:"OBSERVAR reação — choro, raiva, silêncio, negação"},
{etapa:"escala", d:"NOMEAR a emoção — 'Vejo que essa notícia foi muito difícil'"},
{etapa:"escala", d:"VALIDAR — 'Faz sentido se sentir assim'"},
{etapa:"escala", d:"⚠ NÃO oferecer soluções imediatas — primeiro sustentar emocionalmente"},
{etapa:"escala", d:"SILÊNCIO é OK — não preencher com fala"},
{etapa:"escala", d:"TOQUE (mão, ombro) se cultural/pessoalmente apropriado"},
{etapa:"escala", d:"⚠ S — STRATEGY / SUMMARY (estratégia e síntese)"},
{etapa:"escala", d:"⚠ Só após sustentar emocionalmente — verificar se paciente 'volta' para a conversa"},
{etapa:"escala", d:"'Você gostaria de saber sobre os próximos passos?'"},
{etapa:"escala", d:"OFERECER PLANO — opções de tratamento, encaminhamentos, próxima consulta"},
{etapa:"escala", d:"VERIFICAR compreensão — 'pode me dizer o que entendeu?'"},
{etapa:"escala", d:"OFERECER companhia continuada — 'vamos passar por isso juntos'"},
{etapa:"escala", d:"AGENDAR próximo contato — 'nos vemos daqui a X dias'"},
{etapa:"adj", d:"⚠ DISCUSSÃO DE OBJETIVOS DE CUIDADO"},
{etapa:"adj", d:"⚠ 'Goals of care discussion' — em qualquer transição, idealmente ANTES de fase ativa"},
{etapa:"adj", d:"PERGUNTAS NORTEADORAS:"},
{etapa:"adj", d:"'O que é mais importante para você agora?'"},
{etapa:"adj", d:"'O que faz a vida valer a pena para você?'"},
{etapa:"adj", d:"'Em uma situação grave, o que você gostaria que fosse feito (ou não)?'"},
{etapa:"adj", d:"'Você prefere mais tempo, mesmo se isso significar tratamentos agressivos? Ou prefere foco em conforto?'"},
{etapa:"adj", d:"⚠ DIRETIVAS ANTECIPADAS DE VONTADE (DAV) — Resolução CFM 1.995/2012"},
{etapa:"adj", d:"Paciente CAPAZ pode registrar em prontuário (preferível) ou em cartório quais tratamentos aceita/recusa em caso de impossibilidade futura de decidir"},
{etapa:"adj", d:"Inclui: RCP, ventilação mecânica, hemodiálise, nutrição artificial, hidratação, transfusão"},
{etapa:"adj", d:"Procurador de saúde — pessoa que toma decisões em nome do paciente quando incapaz"},
{etapa:"adj", d:"⚠ ESPÓLIO ÉTICO — CFM permite limitar tratamentos não-curativos / disproporcionais conforme vontade do paciente (Res 1.805/2006 — ortotanásia)"},
{etapa:"alta", d:"⚠ DOCUMENTAR no prontuário: conteúdo da conversa, presentes, decisões, plano"},
{etapa:"alta", d:"⚠ COMUNICAR equipe — todos devem saber o que foi discutido, evitar contradições"},
{etapa:"alta", d:"⚠ AUTO-CUIDADO do médico — má notícia é desgastante, considerar pausa, supervisão entre pares"},
],
alertas:[
{nivel:"crit", txt:"⚠ COMUNICAÇÃO DE MÁS NOTÍCIAS é habilidade CLÍNICA CENTRAL — treinável. SPIKES (6 passos) é protocolo validado: Setting, Perception, Invitation, Knowledge, Empathy, Strategy."},
{nivel:"warn", txt:"⚠ NÃO MENTIR / NÃO SUAVIZAR excessivamente. 'Pequeno tumor' / 'células diferentes' geram confusão. Honestidade clara em linguagem simples."},
{nivel:"warn", txt:"⚠ RESPEITAR autonomia — alguns pacientes preferem NÃO SABER tudo. Convidar (Invitation step) é essencial."},
{nivel:"info", txt:"⚠ DIRETIVAS ANTECIPADAS DE VONTADE (DAV) — Resolução CFM 1.995/2012. Registrar em prontuário tem validade. Inclui RCP, VM, hemodiálise, nutrição, hidratação. Procurador de saúde nomeado."},
{nivel:"info", txt:"⚠ ORTOTANÁSIA — Res CFM 1.805/2006 permite limitar tratamentos disproporcionais conforme vontade do paciente terminal. Diferente de eutanásia."},
],
fluxo:"spikes", diretriz:"⚠ Baile WF et al. SPIKES. Oncologist 2000; CFM Res 1.805/2006 + 1.995/2012; ANCP; Vital Talk."
},

);
