/* ===========================================================
   VOVÔMINIC EMERGÊNCIA — ABCDE TRAUMA + EXTENDIDO
   Avaliação primária e secundária do trauma (ATLS-based)
   =========================================================== */

PATOLOGIAS.push(

/* ============== ABCDE PRIMÁRIO ============== */
{id:"abcde-trauma-primario", nome:"ABCDE primário do trauma — avaliação inicial ATLS", sis:"trauma", grav:"alta",
cid:"T07", ciap:"A82",
sin:["ABCDE","ATLS","Trauma primário","Avaliação primária","Trauma grave"],
def:"AVALIAÇÃO PRIMÁRIA do paciente traumatizado segue sequência ABCDE — identificar e tratar ameaças à vida na MESMA ORDEM SEMPRE: A) via aérea com controle cervical, B) respiração, C) circulação com controle de hemorragia, D) déficit neurológico, E) exposição e prevenção de hipotermia. Cada etapa tem intervenções específicas. Reavaliar continuamente.",
quadro:["Paciente vítima de TRAUMA — politrauma, acidente, queda, ferimento por arma","Cinemática importante: velocidade, projetil, queda de altura, atropelamento, ejeção","Primeira abordagem em qualquer cenário — pré-hospitalar ou intra-hospitalar","⚠ PREMISSA: cervical é sempre PROTEGIDA até excluir lesão"],
diag:["Avaliação SISTEMÁTICA por A→B→C→D→E","NÃO PULAR etapa por aparente urgência de outra"],
exames:["Em paralelo após estabilização: acessos venosos, sangue para tipagem, gasometria, lactato, troponina (se TCE) ","Imagens conforme indicação: FAST, RX tórax/pelve, TC"],
rx:[
{etapa:"inicial", d:"⚠ SEGURANÇA DA CENA + EPI + Equipe de trauma alertada"},
{etapa:"escala", d:"⚠ A — AIRWAY com CONTROLE CERVICAL"},
{etapa:"escala", d:"PERGUNTAR ao paciente — se RESPONDE COERENTEMENTE: VA pérvia (momentaneamente)"},
{etapa:"escala", d:"AVALIAR: estridor, gargarejo, rouquidão, taquipneia, agitação, cianose"},
{etapa:"escala", d:"⚠ MANTER ALINHAMENTO CERVICAL durante toda a abordagem"},
{etapa:"escala", d:"Imobilização cervical com COLAR + BLOCOS LATERAIS + FIXAÇÃO À MACA"},
{etapa:"escala", d:"⚠ MANOBRAS imediatas se necessário:"},
{etapa:"escala", d:"Elevação do queixo (chin-lift)"},
{etapa:"escala", d:"Tração da mandíbula (jaw-thrust) — preferida em trauma cervical"},
{etapa:"escala", d:"Aspiração de secreções/vômito/sangue"},
{etapa:"escala", d:"Remoção de corpo estranho visível"},
{etapa:"escala", d:"⚠ DISPOSITIVOS:"},
{etapa:"escala", d:"Cânula orofaríngea (Guedel) em inconsciente sem reflexo"},
{etapa:"escala", d:"Cânula nasofaríngea em consciente"},
{etapa:"escala", d:"⚠ VIA AÉREA DEFINITIVA — INDICAÇÕES (intubação):"},
{etapa:"escala", d:"Apneia, GCS ≤8, obstrução não corrigida, queimadura facial/aérea, lesão cervical com edema, choque grave"},
{etapa:"escala", d:"Sequência rápida com etomidato/cetamina + succinilcolina/rocurônio"},
{etapa:"escala", d:"⚠ CRICOTIREOIDOSTOMIA — em via aérea impossível (cant intubate, can't ventilate)"},
{etapa:"escala", d:"⚠ B — BREATHING (respiração e ventilação)"},
{etapa:"escala", d:"INSPEÇÃO: simetria, retrações, ferimentos, deformidade, pulso paradoxal, distensão jugular"},
{etapa:"escala", d:"PALPAÇÃO: enfisema subcutâneo, dor, instabilidade torácica (tórax instável)"},
{etapa:"escala", d:"PERCUSSÃO: timpânico (pneumotórax), maciço (hemotórax)"},
{etapa:"escala", d:"AUSCULTA: assimetria, abolimento (pneumotórax/hemotórax)"},
{etapa:"escala", d:"⚠ AMEAÇAS À VIDA — IDENTIFICAR E TRATAR IMEDIATAMENTE:"},
{etapa:"escala", d:"PNEUMOTÓRAX HIPERTENSIVO: hipotensão + distensão jugular + assimetria + timpanismo + desvio traqueal → TORACOCENTESE DE ALÍVIO (2º EIC linha hemiclavicular OU 4-5º EIC linha axilar anterior, agulha 14G) → DRENO TORÁCICO definitivo"},
{etapa:"escala", d:"HEMOTÓRAX MACIÇO: hipotensão + colapso pulmonar + sons abolidos → DRENO TORÁCICO 28-32 Fr"},
{etapa:"escala", d:"PNEUMOTÓRAX ABERTO: ferida aspirativa → curativo de 3 PONTAS (oclusivo com 1 lado aberto = válvula) + dreno"},
{etapa:"escala", d:"TÓRAX INSTÁVEL: ≥2 fraturas em ≥2 costelas → suporte ventilatório + analgesia"},
{etapa:"escala", d:"⚠ O₂ — 10-15 L/min máscara não-reinalante em todo politrauma inicial"},
{etapa:"escala", d:"MONITOR: SatO₂, capnografia se intubado"},
{etapa:"escala", d:"⚠ C — CIRCULATION com controle de hemorragia"},
{etapa:"escala", d:"AVALIAÇÃO RÁPIDA: nível de consciência, cor da pele, pulso (presença, frequência, qualidade)"},
{etapa:"escala", d:"⚠ HEMORRAGIA EXTERNA — controle imediato:"},
{etapa:"escala", d:"COMPRESSÃO DIRETA com gaze/curativo (1ª escolha)"},
{etapa:"escala", d:"TORNIQUETE em sangramento de membro NÃO controlado por compressão (CAT, SOFTT, ou improvisado com largura adequada)"},
{etapa:"escala", d:"AGENTES HEMOSTÁTICOS (Combat Gauze, Celox) — sangramento juncional"},
{etapa:"escala", d:"⚠ HEMORRAGIA INTERNA — fontes:"},
{etapa:"escala", d:"TÓRAX (hemotórax — RX), ABDOME (FAST), PELVE (RX pelve, ATB band), FÊMUR (deformidade)"},
{etapa:"escala", d:"⚠ ACESSOS VENOSOS — 2 acessos calibrosos (16-18G) em veias periféricas grandes"},
{etapa:"escala", d:"INTRAÓSSEO se falha (tibial proximal, umeral) — 60 segundos"},
{etapa:"escala", d:"⚠ COLETAR SANGUE: tipagem + cruzamento, hemograma, gasometria, lactato, β-hCG, coagulograma"},
{etapa:"escala", d:"⚠ REPOSIÇÃO VOLÊMICA"},
{etapa:"escala", d:"CRISTALOIDE: RINGER LACTATO 1000 mL infusão rápida (limite 2 L em trauma; volumes maiores aumentam mortalidade — hipotensão permissiva)"},
{etapa:"escala", d:"⚠ HEMOTERAPIA precoce: PRBC 1:1:1 (hemácias:plasma:plaquetas) em hemorragia maciça"},
{etapa:"escala", d:"ÁCIDO TRANEXÂMICO 1 g IV em <3h pós-trauma + 1 g em 8h (CRASH-2 trial) — reduz mortalidade em hemorragia"},
{etapa:"escala", d:"⚠ HIPOTENSÃO PERMISSIVA: PA sistólica alvo 80-90 mmHg até controle do sangramento (em trauma penetrante; ajustar em TCE para PAS ≥110)"},
{etapa:"escala", d:"⚠ D — DISABILITY (déficit neurológico)"},
{etapa:"escala", d:"GLASGOW: ocular (1-4) + verbal (1-5) + motor (1-6) = 3-15"},
{etapa:"escala", d:"PUPILAS: tamanho, simetria, fotorreatividade (anisocoria = hipertensão intracraniana / herniação)"},
{etapa:"escala", d:"FUNÇÃO MOTORA: movimento dos 4 membros, força, sensibilidade"},
{etapa:"escala", d:"⚠ AVALIAR sinais de HERNIAÇÃO: anisocoria, postura de descerebração/decorticação, Cushing (HAS + bradicardia + alteração respiratória)"},
{etapa:"escala", d:"GLICEMIA CAPILAR (excluir hipoglicemia)"},
{etapa:"escala", d:"⚠ AINDA em D: avaliar consciência, ABLA (alcohol, drogas, alergias)"},
{etapa:"escala", d:"GCS ≤8: via aérea definitiva indicada"},
{etapa:"escala", d:"GCS 9-12: TC crânio precoce, monitor"},
{etapa:"escala", d:"⚠ E — EXPOSITION e prevenção de HIPOTERMIA"},
{etapa:"escala", d:"DESPIR completamente — cortar roupas se necessário"},
{etapa:"escala", d:"INSPECIONAR todos os segmentos (frente + costas — log-roll preservando cervical)"},
{etapa:"escala", d:"⚠ LOG-ROLL: avaliar coluna toracolombar, dorso, períneo, sangramento retal/vaginal"},
{etapa:"escala", d:"PROCURAR ferimentos ocultos: axila, virilha, períneo, região sacral, lombar"},
{etapa:"escala", d:"⚠ HIPOTERMIA — paciente politraumatizado SE RESFRIA RÁPIDO"},
{etapa:"escala", d:"Cobertor TÉRMICO / aquecimento ativo (Bair Hugger se disponível)"},
{etapa:"escala", d:"Sala AQUECIDA (>24°C)"},
{etapa:"escala", d:"FLUIDOS AQUECIDOS (especialmente em hemoterapia)"},
{etapa:"escala", d:"⚠ TRÍADE LETAL DO TRAUMA: hipotermia + acidose + coagulopatia — prevenir!"},
{etapa:"adj", d:"⚠ REAVALIAR ABCDE continuamente — paciente trauma é DINÂMICO"},
{etapa:"adj", d:"Após estabilização inicial: transferir para AVALIAÇÃO SECUNDÁRIA (ABCDE estendido)"},
{etapa:"alta", d:"⚠ DIRECIONAR para centro de TRAUMA conforme cinemática + gravidade"},
{etapa:"alta", d:"COMUNICAR equipe receptora (SBAR)"},
{etapa:"alta", d:"DOCUMENTAR achados, intervenções, horários"},
],
alertas:[
{nivel:"crit", txt:"⚠ AMEAÇAS À VIDA EM B (Breathing): pneumotórax hipertensivo, hemotórax maciço, pneumotórax aberto, tórax instável. Identificar + tratar IMEDIATAMENTE antes de prosseguir para C."},
{nivel:"crit", txt:"⚠ TRÍADE LETAL DO TRAUMA: hipotermia + acidose + coagulopatia. Prevenir = aquecimento agressivo + hemoterapia balanceada + ácido tranexâmico precoce."},
{nivel:"crit", txt:"⚠ HIPOTENSÃO PERMISSIVA em trauma penetrante (PAS 80-90) — volume excessivo de cristaloide DESLOCA coágulos formados + dilui fatores → AUMENTA mortalidade. Em TCE: PAS ≥110."},
{nivel:"crit", txt:"⚠ ÁCIDO TRANEXÂMICO 1g IV em <3h + 1g em 8h em hemorragia traumática reduz mortalidade (CRASH-2). Disponível, barato, subutilizado."},
{nivel:"warn", txt:"⚠ NÃO PULAR ETAPA — ABCDE é sequencial. Resolver A antes de avaliar B, etc. Mas reavaliar continuamente."},
{nivel:"warn", txt:"⚠ CONTROLE CERVICAL desde o primeiro contato — colar + blocos + maca rígida. Liberar somente após exclusão clínica/radiológica de lesão."},
{nivel:"info", txt:"DEFINITIVA DA VIA AÉREA: GCS ≤8, apneia, obstrução refratária, queimadura aérea, lesão cervical com edema, choque grave."},
{nivel:"info", txt:"REPOSIÇÃO BALANCEADA (1:1:1 hemácias:plasma:plaquetas) > cristaloide isolado em hemorragia maciça."},
],
fluxo:null, diretriz:"ATLS 10ª ed. PHTLS. SBAIT. AHA."
},

/* ============== ABCDE ESTENDIDO / SECUNDÁRIO ============== */
{id:"abcde-trauma-estendido", nome:"ABCDE estendido / secundário — FGHI", sis:"trauma", grav:"alta",
cid:"T07", ciap:"A82",
sin:["ABCDE estendido","ABCDE secundário","FGHI","Avaliação secundária","Trauma secundário","FAST"],
def:"Após ABCDE PRIMÁRIO estabilizado, segue-se AVALIAÇÃO SECUNDÁRIA — exame da cabeça aos pés + investigação SAMPLE + extensões: F (FAST/Foley/Family), G (Glicemia/Gases/Geografia), H (História/Hipotermia/Helicóptero), I (Inventário/Investigação/Imagens). Permite identificar lesões NÃO ameaçadoras de vida imediatas mas relevantes para desfecho.",
quadro:["Paciente politraumatizado APÓS ABCDE primário estabilizado","Continua a avaliação secundária + investigação complementar","⚠ Avaliação secundária só DEPOIS de garantir que ameaças à vida foram tratadas"],
diag:["História + exame da cabeça aos pés + exames complementares","Reavaliar ABCDE a qualquer mudança"],
exames:["Imagens: RX tórax + pelve + cervical (trauma board), FAST, TC crânio/face/tórax/abdome/pelve conforme indicação","Laboratório: hemograma, eletrólitos, função renal/hepática, troponina, lipase, β-hCG, álcool/tóxicos","ECG","Gasometria + lactato (reavaliação)"],
rx:[
{etapa:"inicial", d:"⚠ ABCDE PRIMÁRIO ESTABILIZADO — só agora secundário"},
{etapa:"inicial", d:"⚠ HISTÓRICO — REGRA NEMÔNICA SAMPLE"},
{etapa:"inicial", d:"S — Sinais/sintomas (do trauma)"},
{etapa:"inicial", d:"A — Alergias"},
{etapa:"inicial", d:"M — Medicações em uso (especial: anticoagulantes, antiagregantes)"},
{etapa:"inicial", d:"P — Patologias prévias / cirurgias / Pulmão (DPOC, asma)"},
{etapa:"inicial", d:"L — Last meal (última refeição — para anestesia)"},
{etapa:"inicial", d:"E — Eventos do trauma (cinemática, mecanismo)"},
{etapa:"escala", d:"⚠ F — FAST / Foley / Family / Fractures"},
{etapa:"escala", d:"⚠ FAST (Focused Assessment with Sonography for Trauma):"},
{etapa:"escala", d:"USG abdominal point-of-care — 4 janelas: peri-hepática (Morrison), perisesplênica, pélvica (Douglas), pericárdica"},
{etapa:"escala", d:"FLUIDO LIVRE em qualquer janela = positivo → sugere hemoperitônio / hemopericárdio"},
{etapa:"escala", d:"E-FAST (extended) inclui janelas pleural para pneumotórax"},
{etapa:"escala", d:"Não exclui lesão (sensibilidade ~75%), mas alta especificidade — guia decisão cirúrgica em paciente instável"},
{etapa:"escala", d:"⚠ FOLEY (sonda vesical):"},
{etapa:"escala", d:"Para monitor débito urinário (alvo: 0,5-1 mL/kg/h adulto)"},
{etapa:"escala", d:"⚠ CONTRAINDICAÇÃO ABSOLUTA — suspeita LESÃO URETRAL: sangue no meato, hematoma perineal/escrotal, próstata flutuante ao toque retal, fratura pélvica complexa"},
{etapa:"escala", d:"Em contraindicação: uretrocistografia retrógrada primeiro OU cistostomia suprapúbica"},
{etapa:"escala", d:"⚠ FAMILY (família):"},
{etapa:"escala", d:"Avisar familiares — apoio + obter histórico"},
{etapa:"escala", d:"Decisões compartilhadas (DNAR, doação)"},
{etapa:"escala", d:"⚠ FRATURES (fraturas):"},
{etapa:"escala", d:"Inspeção sistemática — todos os 4 membros + cintura escapular + cintura pélvica"},
{etapa:"escala", d:"⚠ FRATURA PÉLVICA: lesão major — sangramento profuso, alta mortalidade. Pelvic binder + fluido + sangue + transferir centro trauma"},
{etapa:"escala", d:"⚠ FÊMUR: deformidade + dor + perda de 1-1,5 L de sangue. Talas de tração de fêmur"},
{etapa:"adj", d:"⚠ G — GLICEMIA / GASES / GEOGRAFIA"},
{etapa:"adj", d:"⚠ GLICEMIA CAPILAR — todo paciente inconsciente. Hipoglicemia mimetiza/agrava TCE"},
{etapa:"adj", d:"⚠ GASOMETRIA ARTERIAL + lactato:"},
{etapa:"adj", d:"pH, pCO₂, pO₂, HCO₃, BE, lactato, eletrólitos"},
{etapa:"adj", d:"LACTATO ≥2 mmol/L = hipoperfusão. Clarear em 24h reduz mortalidade"},
{etapa:"adj", d:"ACIDOSE METABÓLICA + lactato alto = sinais de hipoperfusão oculta — choque criptococcoso"},
{etapa:"adj", d:"⚠ GEOGRAFIA (mecanismo geográfico):"},
{etapa:"adj", d:"Onde foi o trauma? Acidente rural sem testemunha → demora no socorro → lesões + grave"},
{etapa:"adj", d:"Centro urbano? Especialização disponível?"},
{etapa:"adj", d:"Transferência para centro de trauma se: politrauma, TCE moderado-grave, fratura múltipla, queimadura extensa"},
{etapa:"adj", d:"⚠ H — HISTÓRIA / HIPOTERMIA / HELICÓPTERO"},
{etapa:"adj", d:"⚠ HISTÓRIA DETALHADA — reescuta com paciente consciente ou família"},
{etapa:"adj", d:"Cinemática completa: velocidade, projetil, posição, lugar do veículo, uso de cinto/capacete, ejeção"},
{etapa:"adj", d:"⚠ HIPOTERMIA — MEDIR temperatura central"},
{etapa:"adj", d:"<36°C = hipotermia clinicamente relevante"},
{etapa:"adj", d:"<35°C = hipotermia importante — coagulopatia, arritmia, mortalidade"},
{etapa:"adj", d:"AQUECIMENTO ATIVO: cobertor térmico, fluidos aquecidos (38°C), lavagem cavidades em casos extremos"},
{etapa:"adj", d:"⚠ HELICÓPTERO / TRANSFERÊNCIA:"},
{etapa:"adj", d:"Critérios para acionar SAMU / aeromédico"},
{etapa:"adj", d:"Comunicação SBAR com equipe receptora"},
{etapa:"adj", d:"⚠ I — INVENTÁRIO / INVESTIGAÇÃO / IMAGENS"},
{etapa:"adj", d:"⚠ INVENTÁRIO — exame da CABEÇA aos PÉS:"},
{etapa:"adj", d:"CABEÇA: hematomas, ferimentos, palpar crânio (afundamento), pupila, otorragia, hemorragia retroauricular (Battle), hemorragia periorbitária (olho de guaxinim)"},
{etapa:"adj", d:"FACE: deformidade, instabilidade middle face, oclusão dentária, mobilidade nasal"},
{etapa:"adj", d:"PESCOÇO: enfisema subcutâneo, distensão jugular, desvio traqueal, dor cervical, ferida penetrante"},
{etapa:"adj", d:"TÓRAX: já avaliado em B — reavaliar"},
{etapa:"adj", d:"ABDOME: distensão, dor, defesa, sinais peritoneais, ferida penetrante"},
{etapa:"adj", d:"PELVE: dor à compressão (NÃO 'balançar pelve' rotineiramente — pode aumentar sangramento), instabilidade"},
{etapa:"adj", d:"PERÍNEO: sangue meato, hematoma escrotal/labial, sangramento retal"},
{etapa:"adj", d:"4 MEMBROS: pulsos distais, deformidade, fratura aberta, neurovascular distal"},
{etapa:"adj", d:"⚠ TOQUE RETAL: tônus esfincteriano, próstata, sangue, fragmento ósseo (fratura pélvica)"},
{etapa:"adj", d:"⚠ LOG-ROLL: avaliar coluna toracolombar, dorso completo"},
{etapa:"adj", d:"⚠ INVESTIGAÇÃO:"},
{etapa:"adj", d:"3 RX clássicos do trauma: TÓRAX (frontal), PELVE, CERVICAL (lateral)"},
{etapa:"adj", d:"FAST repetido se piora hemodinâmica"},
{etapa:"adj", d:"TC TÓRAX/ABDOME/PELVE com contraste — paciente estável com cinemática maior"},
{etapa:"adj", d:"TC CRÂNIO se TCE moderado-grave, anticoagulado, GCS <14"},
{etapa:"adj", d:"⚠ IMAGENS — INDICAÇÕES:"},
{etapa:"adj", d:"TC: paciente estável + cinemática significativa"},
{etapa:"adj", d:"FAST/RX: paciente instável + decisão emergencial"},
{etapa:"adj", d:"Angiografia/TC angio: suspeita lesão vascular"},
{etapa:"alta", d:"⚠ APÓS SECUNDÁRIO: decisão de transferência, internação, cirurgia"},
{etapa:"alta", d:"REAVALIAR ABCDE — qualquer mudança no quadro = repetir"},
{etapa:"alta", d:"DOCUMENTAR achados, hipóteses, conduta"},
{etapa:"alta", d:"⚠ PROFILAXIA: antitetânica, antibiótico (em ferida contaminada/aberta), trombose (heparina baixa dose após controle hemorragia)"},
],
alertas:[
{nivel:"crit", txt:"⚠ AVALIAÇÃO SECUNDÁRIA é DEPOIS de estabilização ABCDE primário. NÃO pular A-E para investigar lesões 'interessantes' se ainda há ameaça à vida."},
{nivel:"crit", txt:"⚠ FRATURA PÉLVICA + hipotensão = mortalidade alta. Pelvic binder PRECOCE + hemoterapia + transferir centro trauma. Sangramento retroperitoneal pode ser oculto."},
{nivel:"crit", txt:"⚠ FOLEY contraindicada em suspeita de lesão uretral (sangue meato, hematoma perineal, próstata flutuante, fratura pélvica complexa). Uretrocistografia primeiro OU cistostomia suprapúbica."},
{nivel:"warn", txt:"⚠ FAST não exclui lesão (sens ~75%). Útil em INSTÁVEL para decisão cirúrgica imediata. Em paciente estável: TC com contraste é mais sensível."},
{nivel:"warn", txt:"NÃO 'BALANÇAR PELVE' rotineiramente — pode deslocar coágulos e aumentar sangramento. Apenas compressão suave."},
{nivel:"warn", txt:"⚠ LOG-ROLL: avaliar coluna + dorso. Preservar cervical. Examinador líder coordena."},
{nivel:"warn", txt:"⚠ ANTICOAGULAÇÃO + TCE = TC crânio mesmo com GCS 15. Reverter anticoagulação se hemorragia (vit K, complexo protrombínico, idarucizumabe para dabigatrana)."},
{nivel:"info", txt:"REGRA SAMPLE = Sintomas, Alergias, Medicações, Patologias, Last meal, Eventos. Padrão de história em trauma."},
{nivel:"info", txt:"3 RX CLÁSSICOS: tórax, pelve, cervical lateral. Em centro com TC disponível: maioria substituída por TC."},
],
fluxo:null, diretriz:"ATLS 10ª ed. PHTLS. SBAIT. EAST guidelines."
},

);
