/* ===========================================================
   VOVÔMINIC EMERGÊNCIA — PULO DO GATO 3
   Vias aéreas + Trauma + Articular + Pediátrico + Cabeça/Pescoço
   =========================================================== */

PATOLOGIAS.push(

/* ============== ASMA GRAVE SEM RECURSOS ============== */
{id:"pulo-asma-sem-nada", nome:"Crise asmática sem MDI nem nebulizador — adrenalina IM/SC", sis:"pulo", grav:"alta",
cid:"J46", ciap:"R96",
sin:["Asma sem broncodilatador","Adrenalina IM asma","Terbutalina SC","Asma SUS rural"],
def:"Cenário catástrofe — UBS rural ou ambulância sem broncodilatador inalatório. ADRENALINA IM trata crise asmática grave (efeito β-2 sistêmico) — funciona também se anafilaxia. Salbutamol SC/IM é alternativa quando disponível.",
quadro:["Crise asmática grave/iminente sem recursos respiratórios (MDI, nebulizador, O₂)","Sibilos audíveis, dispneia, taquipneia, retração, fala em palavras","Diferenciar de ANAFILAXIA — adrenalina IM trata AMBOS","Considerar TRANSFERÊNCIA SAMU simultânea"],
diag:["Clínica (sem tempo para exames)","SatO₂ se disponível","Excluir corpo estranho, anafilaxia (urticária, angioedema), ICC, pneumotórax (assimetria)"],
exames:["Geralmente nenhum — agir clinicamente"],
rx:[
{etapa:"inicial", d:"⚠ AVALIAÇÃO em segundos: SatO₂, capacidade de falar, esforço respiratório, NC"},
{etapa:"inicial", d:"POSICIONAR sentado, inclinado para frente — postura de tripé"},
{etapa:"escala", d:"ADRENALINA IM — 1ª linha quando sem outro broncodilatador", do:"0,01 mg/kg IM (máx 0,5 mg adulto, 0,3 mg criança)", via:"IM", o:"Coxa lateral. Repetir 5-15 min se necessário. Adrenalina 1:1000 = 1 mg/mL. Adulto: 0,3-0,5 mL. Criança: 0,01 mL/kg."},
{etapa:"escala", d:"SE DISPONÍVEL: Salbutamol SC ou IM", do:"0,25 mg SC (adulto), 5 mcg/kg (criança)", via:"SC/IM", o:"Menos disponível que adrenalina. Efeito β-2 mais seletivo."},
{etapa:"escala", d:"OU Terbutalina SC", do:"0,25-0,5 mg SC", via:"SC", o:"Alternativa quando disponível."},
{etapa:"adj", d:"CORTICOIDE precoce — VO se tolerar", do:"Prednisona 40-60 mg VO (adulto), 1 mg/kg (criança)"},
{etapa:"adj", d:"OU IM/IV se VO impossível", do:"Hidrocortisona 200-300 mg IV/IM OU dexametasona 8-10 mg"},
{etapa:"adj", d:"SULFATO DE MAGNÉSIO 2 g IV em 20 min — se acesso venoso e crise grave persistente", o:"Broncodilatador via relaxamento muscular liso."},
{etapa:"adj", d:"O₂ se disponível, alvo SatO₂ 93-95%"},
{etapa:"alta", d:"⚠ TRANSFERÊNCIA imediata para hospital — não tratar como ambulatorial"},
{etapa:"alta", d:"Manter adrenalina IM repetida cada 5-15 min enquanto aguarda transporte"},
],
alertas:[
{nivel:"crit", txt:"ADRENALINA IM é SEGURA em asma grave — não retardar por medo de efeito CV. Mortalidade da asma grave > risco da adrenalina em adulto saudável."},
{nivel:"crit", txt:"NÃO ADIAR transferência hospitalar tentando estabilizar em UBS sem recursos. Adrenalina IM é ponte."},
{nivel:"warn", txt:"Em CARDIOPATA / IDOSO frágil: adrenalina pode causar isquemia. Avaliar risco-benefício (em crise grave, ainda assim usar)."},
{nivel:"info", txt:"ADRENALINA tem efeito β-2 (broncodilatação) + α (vasoconstrição) + β-1 (cardíaco). Em asma sem MDI: usar."},
],
fluxo:null, diretriz:"GINA 2024-2025. SBP. ALS algorithms."
},

/* ============== ENGASGO EM BEBÊ <1 ANO ============== */
{id:"pulo-engasgo-bebe", nome:"Engasgo em bebê <1 ano — golpes nas costas + compressões torácicas", sis:"pulo", grav:"alta",
cid:"T17", ciap:"R87",
sin:["Engasgo bebê","Aspiração corpo estranho lactente","Heimlich bebê","BLS pediátrico"],
def:"OBSTRUÇÃO de via aérea por corpo estranho em <1 ano = NÃO USAR HEIMLICH (compressão abdominal lesa órgãos abdominais do lactente). USAR alternância de 5 GOLPES NAS COSTAS + 5 COMPRESSÕES TORÁCICAS até desobstruir ou perda de consciência.",
quadro:["Bebê com SUFOCAÇÃO súbita durante alimentação/exploração oral","Sinais OBSTRUÇÃO COMPLETA: ausência de tosse, ausência de choro, cianose, perda de consciência iminente","OBSTRUÇÃO PARCIAL: tosse, choro, estridor — NÃO INTERVIR com manobra, encorajar tosse"],
diag:["Clínica — testemunho ou suspeita","Avaliar movimento de ar, capacidade de chorar, cor"],
exames:["Nenhum no momento agudo","Pós-resolução: Rx tórax se suspeita aspiração residual"],
rx:[
{etapa:"inicial", d:"⚠ OBSTRUÇÃO PARCIAL (bebê tossindo, chorando, com ar): NÃO INTERVIR com manobra. Encorajar tosse. Transportar para hospital."},
{etapa:"inicial", d:"OBSTRUÇÃO COMPLETA (sem tosse, sem choro, cianótico): INICIAR MANOBRA"},
{etapa:"escala", d:"⚠ MANOBRA — em <1 ANO — NÃO USAR HEIMLICH"},
{etapa:"escala", d:"(1) Posicionar bebê em PRONO no antebraço, cabeça mais baixa que o tórax, mão apoiando mandíbula (NÃO comprimir garganta)"},
{etapa:"escala", d:"(2) Aplicar 5 GOLPES com a base da mão entre as omoplatas, FIRMES, dirigidos para frente-cima"},
{etapa:"escala", d:"(3) VIRAR o bebê em DECÚBITO DORSAL (mantendo cabeça mais baixa) — 1 antebraço sustenta as costas"},
{etapa:"escala", d:"(4) Aplicar 5 COMPRESSÕES TORÁCICAS no esterno (mesmo local da RCP — abaixo da linha mamilar), com 2 dedos, profundidade 1/3 do tórax"},
{etapa:"escala", d:"(5) Verificar boca — se objeto VISÍVEL: retirar com pinça/dedo. NÃO fazer varredura digital ÀS CEGAS (pode empurrar)"},
{etapa:"escala", d:"(6) REPETIR ciclos de 5+5 até desobstruir OU bebê inconsciente"},
{etapa:"adj", d:"⚠ SE BEBÊ FICA INCONSCIENTE:"},
{etapa:"adj", d:"Iniciar RCP padrão pediátrico — 30 compressões + 2 ventilações (1 socorrista) OU 15:2 (2 socorristas)"},
{etapa:"adj", d:"A cada ciclo, VERIFICAR boca antes da ventilação"},
{etapa:"adj", d:"Continuar até resposta ou chegada do SAMU"},
{etapa:"adj", d:"Chamar SAMU 192 — solicitar transporte para hospital pediátrico"},
{etapa:"alta", d:"PÓS-RESOLUÇÃO: levar ao PS mesmo se assintomático — pode haver aspiração de fragmentos, pneumonia química, lesão de mucosa"},
{etapa:"alta", d:"Avaliar Rx tórax — atelectasia, hiperinsuflação localizada (corpo estranho residual?)"},
{etapa:"alta", d:"Orientar pais: ALIMENTOS DE RISCO (uvas inteiras, balas duras, pipoca, amendoim, hot dog, salsicha) — cortar/evitar até 5 anos"},
],
alertas:[
{nivel:"crit", txt:"NÃO USAR HEIMLICH em <1 ano — lesão hepática, esplênica. Apenas golpes nas costas + compressões torácicas."},
{nivel:"crit", txt:"OBSTRUÇÃO PARCIAL (com tosse, choro, ar): NÃO INTERVIR — encorajar tosse + transportar. Intervir só se OBSTRUÇÃO COMPLETA."},
{nivel:"crit", txt:"NUNCA varredura digital às cegas — pode empurrar objeto mais profundo. Só remover se visível."},
{nivel:"warn", txt:"ALIMENTOS DE ALTO RISCO em <5 anos: uva inteira, salsicha em fatias grossas, pipoca, balas duras, amendoim, hot dog. Cortar pequeno ou evitar."},
{nivel:"info", txt:"Após 1 ano: Heimlich pode ser usado (manobra de compressão abdominal acima do umbigo)."},
],
fluxo:null, diretriz:"AHA PALS 2020+update. ILCOR. AAP."
},

/* ============== CRUPE LEVE ============== */
{id:"pulo-crupe-leve", nome:"Crupe leve / tosse de cachorro — ar úmido e calmaria", sis:"pulo", grav:"baixa",
cid:"J05", ciap:"R77",
sin:["Crupe","Laringotraqueíte","Tosse de cachorro","Estridor noturno","Westley score"],
def:"CRUPE VIRAL (laringotraqueíte por parainfluenza, RSV, influenza) — criança 6m-6a com tosse 'rouca/de cachorro' + estridor inspiratório + rouquidão. CASO LEVE (sem estridor em repouso): conduta domiciliar com ar úmido/frio + calmaria + corticoide oral. Não precisa internar.",
quadro:["Criança 6m-6a, pré-quadro de IVAS, evolui com tosse 'rouca/de cachorro' + rouquidão + ESTRIDOR INSPIRATÓRIO","Tipicamente PIORA À NOITE","WESTLEY SCORE: 0-2 leve / 3-7 moderado / 8-11 grave / ≥12 falência iminente","⚠ EXCLUIR: epiglotite (febre alta, sialorreia, posição em tripé, súbito), corpo estranho, anafilaxia, abscesso retrofaríngeo"],
diag:["Clínica — tosse de cachorro + estridor","Westley score","Avaliar SatO₂"],
exames:["Geralmente nenhum em caso leve","Rx pescoço AP (sinal da torre/aguja em coluna de ar) — útil se atípico"],
rx:[
{etapa:"inicial", d:"⚠ CASO LEVE (Westley 0-2, sem estridor em repouso, criança ativa)"},
{etapa:"escala", d:"⚠ AR ÚMIDO FRIO — abrir freezer, sair ao ar frio noturno, banho de chuveiro com vapor", o:"Ar frio causa vasoconstrição da mucosa edemaciada → melhora estridor. Evidência limitada mas seguro e amplamente recomendado."},
{etapa:"escala", d:"CALMARIA — criança chorando piora estridor (Bernoulli — maior fluxo, mais colapso). Colo dos pais, canção"},
{etapa:"escala", d:"⚠ CORTICOIDE ORAL — DEXAMETASONA é padrão", do:"Dexametasona 0,15-0,6 mg/kg VO DOSE ÚNICA (máx 16 mg)", via:"VO", o:"Padrão é 0,6 mg/kg em caso moderado; 0,15-0,3 mg/kg em leve. Dose única. Início ação 2-4h."},
{etapa:"escala", d:"OU Prednisolona 1-2 mg/kg/d × 3 dias", o:"Alternativa se dexa indisponível."},
{etapa:"escala", d:"⚠ HIDRATAÇÃO — oferecer líquidos frios (água, picolé)", o:"Confortou + frescor local."},
{etapa:"adj", d:"⚠ CASO MODERADO-GRAVE (Westley ≥3, estridor em repouso): ADRENALINA NEBULIZADA"},
{etapa:"adj", d:"Adrenalina racêmica 0,5 mL ou L-adrenalina 1:1000 0,5 mL/kg (máx 5 mL) em SF 3-5 mL NBZ", o:"Reduz edema. Efeito 30 min-2h. OBSERVAR 3-4h após (rebote)."},
{etapa:"adj", d:"+ Dexametasona 0,6 mg/kg VO/IM"},
{etapa:"adj", d:"O₂ se SatO₂ <92%"},
{etapa:"alta", d:"ORIENTAR PAIS: piora noturna é típica. Vapor de banheiro / ar frio noturno se piora estridor"},
{etapa:"alta", d:"PROCURAR EMERGÊNCIA: estridor em repouso, dispneia, cianose, recusa de líquidos, sialorreia, posição em tripé, alteração do nível de consciência"},
{etapa:"alta", d:"⚠ EPIGLOTITE (raro pós-vacinação Hib): febre alta + sialorreia + posição em tripé + voz abafada — NÃO mexer na boca, encaminhar via aérea urgente"},
],
alertas:[
{nivel:"crit", txt:"⚠ EPIGLOTITE: febre alta + sialorreia + posição em tripé + voz abafada (não 'rouca'). NÃO mexer na boca / NÃO deitar a criança. Via aérea urgente. Raro pós Hib."},
{nivel:"crit", txt:"⚠ ABSCESSO RETROFARÍNGEO: dor cervical + rigidez + dispneia. Excluir em criança com sintomas atípicos."},
{nivel:"warn", txt:"DEXAMETASONA dose única VO é eficaz mesmo em caso leve — reduz consultas de retorno. Início 2-4h."},
{nivel:"warn", txt:"ADRENALINA NEBULIZADA: observar 3-4h após (efeito rebote possível). Não dar alta antes."},
{nivel:"info", txt:"AR ÚMIDO FRIO: evidência limitada mas amplamente usado. Calmar a criança é tão importante quanto."},
{nivel:"info", txt:"CRUPE recorrente >2 episódios/ano: avaliar refluxo, alergia, anatômica."},
],
fluxo:null, diretriz:"SBP. AAP Croup Guidelines. Westley score."
},

/* ============== ANESTESIA TÓPICA EM SUTURA ============== */
{id:"pulo-sutura-let", nome:"Sutura sem dor — anestésico tópico LET", sis:"pulo", grav:"baixa",
cid:"-", ciap:"-",
sin:["LET","Anestesia tópica","Sutura criança","Lidocaína gel","EMLA","Field block"],
def:"LET (Lidocaína 4% + Epinefrina 1:2000 + Tetracaína 0,5%) — anestésico tópico aplicado em gaze sobre ferida ANTES de infiltração ou às vezes EM SUBSTITUIÇÃO. Reduz dramaticamente dor da injeção, especialmente em CRIANÇA. Disponível em farmácia de manipulação.",
quadro:["Ferida cortante limpa, candidata a sutura — couro cabeludo, face, membros","Criança com pavor de agulha","Adulto ansioso","⚠ NÃO USAR em extremidades terminais (dedo, pênis, nariz, orelha) — adrenalina"],
diag:["Clínica","Avaliar profundidade da ferida (atinge fáscia, músculo?)","Avaliar contaminação (mordedura, contaminação grave — desbridamento + suturas seletivas)"],
exames:["Em mãos: avaliar função tendínea/sensitiva","Rx se suspeita corpo estranho radiopaco"],
rx:[
{etapa:"inicial", d:"⚠ AVALIAR ferida — extensão, profundidade, contaminação, estruturas profundas. Ferida de mordida humana/animal pode não suturar (cicatrização 2ª intenção)"},
{etapa:"inicial", d:"LIMPAR com SF abundante — irrigação 200-500 mL com pressão (seringa 30 mL + cateter 18G)"},
{etapa:"escala", d:"⚠ APLICAR LET (Lidocaína 4% + Epinefrina 1:2000 + Tetracaína 0,5%)"},
{etapa:"escala", d:"Gaze 3×3 cm embebida em LET 1-3 mL, aplicar sobre ferida com pressão suave"},
{etapa:"escala", d:"AGUARDAR 20-30 MIN (anestesia eficaz após esse tempo)"},
{etapa:"escala", d:"Pode COBRIR a gaze com fita oclusiva para manter contato"},
{etapa:"escala", d:"⚠ Após anestesia: lavar a área antes da sutura (remover excesso de tópico)"},
{etapa:"adj", d:"⚠ NÃO USAR LET (contém epinefrina) em extremidades terminais — dedo, pênis, ponta de nariz, lóbulo de orelha"},
{etapa:"adj", d:"ALTERNATIVA TÓPICA — EMLA (lidocaína 2,5% + prilocaína 2,5%): aplicar 30-60 min ANTES da pele íntegra"},
{etapa:"adj", d:"FIELD BLOCK (bloqueio perilesional) — alternativa quando LET indisponível"},
{etapa:"adj", d:"Lidocaína 1-2% com/sem adrenalina, infiltrar AO REDOR da ferida (não dentro) — agulha 27-30G, lenta", o:"Adrenalina prolonga anestesia + reduz sangramento. Não usar em extremidade terminal."},
{etapa:"adj", d:"Para REDUZIR DOR DA INJEÇÃO: usar BICARBONATO 8,4% — diluir 1:10 com lidocaína (1 mL bicarb + 9 mL lido) → pH neutro, dói menos", o:"Truque clássico. Solução fica boa por 24h."},
{etapa:"adj", d:"AQUECER lidocaína à temperatura corporal (mão fechada por 1-2 min) também reduz dor da infiltração"},
{etapa:"alta", d:"PÓS-SUTURA: cobertura simples, retirada de pontos conforme local (face 5-7d, couro cabeludo 7-10d, tronco/membro 10-14d)"},
{etapa:"alta", d:"PROFILAXIA ANTITETÂNICA conforme histórico"},
],
alertas:[
{nivel:"warn", txt:"LET CONTÉM EPINEFRINA — NÃO usar em extremidades terminais (dedo, pênis, nariz, orelha) — risco isquemia."},
{nivel:"warn", txt:"LET é DISPONÍVEL em farmácia de manipulação. Validade ~30 dias refrigerado. Custo razoável."},
{nivel:"warn", txt:"EM CRIANÇA <12 anos: dose máxima de LET geralmente 1-3 mL (lidocaína máx 4 mg/kg)."},
{nivel:"info", txt:"BICARBONATO DILUÍDO 1:10 com lidocaína reduz dor da infiltração — pH neutralizado. AQUECER a solução também."},
{nivel:"info", txt:"EMLA é alternativa para pele ÍNTEGRA (punção venosa, biópsia) — 30-60 min antes."},
],
fluxo:null, diretriz:"AAFP. Roberts & Hedges ER Procedures."
},

/* ============== ADESIVO GRUDADO ============== */
{id:"pulo-adesivo-grudado", nome:"Adesivo / cola super bonder na pele — óleo / vaselina", sis:"pulo", grav:"baixa",
cid:"-", ciap:"S15",
sin:["Cola super bonder","Esparadrapo grudado","Adesivo grudado","Cianoacrilato","Remover adesivo"],
def:"COLA DE CIANOACRILATO (Super Bonder) ou ESPARADRAPO antigo aderido na pele = NÃO TENTAR ARRANCAR — risco de avulsão cutânea. Aplicar ÓLEO / VASELINA / ACETONA (em local apropriado) por 5-10 min — solta gentilmente.",
quadro:["Cola super bonder em pele (acidente doméstico ou industrial)","Esparadrapo / curativo antigo aderido em pele frágil (idoso, criança, dermatite)","Adesivo de ECG / Holter grudado por dias","⚠ EXCLUIR cola no OLHO ou MUCOSA — outra abordagem"],
diag:["Clínica","Em cola no olho/mucosa: encaminhar oftalmologia/cirurgia"],
exames:["Geralmente nenhum"],
rx:[
{etapa:"inicial", d:"⚠ NÃO ARRANCAR — risco avulsão cutânea, dor, sangramento"},
{etapa:"escala", d:"⚠ COLA CIANOACRILATO (Super Bonder)"},
{etapa:"escala", d:"PRIMEIRA OPÇÃO: aplicar ÓLEO DE COZINHA, VASELINA, óleo mineral, manteiga, óleo de bebê — esfregar suavemente por 5-10 min"},
{etapa:"escala", d:"REPETIR aplicação várias vezes — cola amolece progressivamente"},
{etapa:"escala", d:"⚠ ACETONA / esmalte de unha → eficaz mas IRRITANTE — usar com cautela em pele, NÃO usar em criança / mucosa / olho", o:"Esfregar com cotonete embebido. Lavar abundantemente após."},
{etapa:"escala", d:"ALTERNATIVA: água morna + sabão neutro + paciência (15-30 min)"},
{etapa:"escala", d:"⚠ NÃO USAR objeto cortante para separar dedos colados — risco lesão"},
{etapa:"adj", d:"⚠ DEDOS COLADOS UM AO OUTRO (cianoacrilato)"},
{etapa:"adj", d:"NUNCA forçar separação — pode arrancar pele entre os dedos"},
{etapa:"adj", d:"Mergulhar dedos em água morna com sabão + óleo + paciência"},
{etapa:"adj", d:"Movimento de 'rolagem' lenta dos dedos um sobre o outro — quando cola amolecer"},
{etapa:"adj", d:"⚠ ESPARADRAPO antigo / adesivo grudado em pele frágil"},
{etapa:"adj", d:"ÓLEO MINERAL, vaselina ou óleo de bebê — molhar gaze e aplicar sob o adesivo, esperar 2-3 min"},
{etapa:"adj", d:"Remover LENTAMENTE no sentido PARALELO à pele (não perpendicular)"},
{etapa:"adj", d:"Solução comercial: 'remove tape' (com solvente) em hospital"},
{etapa:"adj", d:"⚠ COLA NO OLHO: enxaguar abundantemente com SF — encaminhar oftalmologia. NÃO forçar abertura da pálpebra colada"},
{etapa:"adj", d:"⚠ COLA NA MUCOSA ORAL: água + óleo — encaminhar se persistir"},
{etapa:"alta", d:"PÓS-REMOÇÃO: hidratar pele (creme), curativo se houver abrasão"},
{etapa:"alta", d:"Orientar prevenção: usar luvas com cola, ler instruções"},
],
alertas:[
{nivel:"crit", txt:"COLA NO OLHO: NÃO forçar — encaminhar oftalmologia. SF abundante, evitar coçar. Pálpebras coladas costumam separar espontaneamente em 1-4 dias com cuidado."},
{nivel:"warn", txt:"NÃO ARRANCAR / NÃO USAR CORTANTE — risco avulsão cutânea e laceração."},
{nivel:"warn", txt:"ACETONA: irritante. EVITAR em criança, dermatite, mucosa. Usar pontualmente em adulto sem alergia."},
{nivel:"info", txt:"DEDOS COLADOS: óleo + paciência + 'rolagem' — nunca tração linear forçada."},
{nivel:"info", txt:"PROFISSIONAL DE SAÚDE com adesivos: 'remove tape' (solvente comercial) é mais rápido."},
],
fluxo:null, diretriz:"Tintinalli. Roberts & Hedges. Industrial first aid guides."
},

/* ============== FARPA PROFUNDA ============== */
{id:"pulo-farpa-vegetal", nome:"Farpa profunda / espinho — bicarbonato vs adesivo", sis:"pulo", grav:"baixa",
cid:"T14", ciap:"S14",
sin:["Farpa","Espinho","Vegetal cravado","Bicho-de-pé","Tunga","Removendo farpa"],
def:"Pequenas farpas/espinhos visíveis = pinça reta. Farpas pequenas SUPERFICIAIS (de difícil pinça) = ADESIVO (durex/fita) puxa por adesão. Farpas vegetais SUBMERSAS profundas = PASTA DE BICARBONATO faz a pele 'expulsar' o material em 24-48h.",
quadro:["Farpa de madeira, espinho de planta, ferpa metálica superficial, espinho de cacto","Bicho-de-pé (tungíase) — específico, abordagem diferente","⚠ EXCLUIR farpa profunda em articulação, próximo a nervo/vaso, em olho","⚠ Tetânica é risco — verificar histórico vacinal"],
diag:["Inspeção + transiluminação (lanterna celular por trás)","Profundidade aproximada","Tipo de material (vegetal mais inflamatório que metal)","Rx se metal/vidro radiopaco profundo"],
exames:["Geralmente nenhum","Rx se suspeita corpo estranho radiopaco profundo"],
rx:[
{etapa:"inicial", d:"⚠ AVALIAR profundidade e localização — farpas próximas a olho/nervo/vaso encaminhar"},
{etapa:"inicial", d:"LIMPAR área com SF + clorexidina"},
{etapa:"escala", d:"⚠ FARPA VISÍVEL E ACESSÍVEL — pinça reta"},
{etapa:"escala", d:"Anestesia local (lidocaína 1-2%) se profunda ou paciente sensível"},
{etapa:"escala", d:"Pinça anatômica fina (não com dentes), agarrar PRÓXIMO à pele, puxar no mesmo ângulo de entrada"},
{etapa:"escala", d:"⚠ FARPA PEQUENA SUPERFICIAL (difícil pegar com pinça)"},
{etapa:"escala", d:"TÉCNICA DO ADESIVO: aplicar fita adesiva forte (durex larga, esparadrapo) sobre a área, puxar firme em sentido oposto à entrada — adesão remove farpa"},
{etapa:"escala", d:"Funciona para farpinhas de cacto, espinho de ouriço, palhas finas"},
{etapa:"escala", d:"⚠ FARPA PROFUNDA VEGETAL (não visível, área inflamada com sensação de corpo estranho)"},
{etapa:"escala", d:"TÉCNICA DA PASTA DE BICARBONATO: misturar bicarbonato de sódio + pequena quantidade de água → pasta espessa"},
{etapa:"escala", d:"Aplicar pasta abundante sobre a área, cobrir com curativo oclusivo (durex)"},
{etapa:"escala", d:"Trocar 2-3×/dia × 1-2 dias — a pele 'amolece' e EXPULSA o vegetal espontaneamente", o:"Mecanismo: maceração + inflamação local que ejeta corpo estranho. Funciona melhor em material vegetal (madeira, espinho de planta)."},
{etapa:"adj", d:"⚠ FARPA METÁLICA PROFUNDA: Rx para localizar antes de tentar remover. Em ferida deep com fragmento metálico difícil de localizar: encaminhar cirurgia"},
{etapa:"adj", d:"⚠ ESPINHO DE OURIÇO-CACHEIRO (raro mas existe): geralmente arrancar com pinça é difícil pelas farpas. Cortar a base do espinho pode 'esvaziar' e facilitar — depois pinça"},
{etapa:"adj", d:"⚠ BICHO-DE-PÉ (TUNGÍASE) — Tunga penetrans"},
{etapa:"adj", d:"Lesão típica: pápula branca/amarela com ponto preto central (parasita) — geralmente em planta dos pés"},
{etapa:"adj", d:"REMOÇÃO MECÂNICA com agulha esterilizada — abrir levemente a pele e extrair o parasita inteiro (evitar romper)"},
{etapa:"adj", d:"Antissepsia + tetânica + orientação (sapatos, asseio)"},
{etapa:"adj", d:"Casos extensos: TIABENDAZOL 25 mg/kg/d × 5-10 dias (off-label) ou IVERMECTINA 200 mcg/kg dose única"},
{etapa:"alta", d:"⚠ ANTITETÂNICA conforme histórico — sempre verificar"},
{etapa:"alta", d:"ANTIBIÓTICO só se sinais de infecção (celulite ao redor, supuração)"},
{etapa:"alta", d:"Orientar paciente: sinais de infecção, retorno se piora"},
],
alertas:[
{nivel:"crit", txt:"FARPA EM OLHO: NÃO tentar remover — encaminhar oftalmologia. Cobrir olho contralateral também (movimentos conjugados)."},
{nivel:"warn", txt:"FARPA PROFUNDA próxima a vaso/nervo/articulação: encaminhar cirurgia."},
{nivel:"warn", txt:"ANTITETÂNICA é OBRIGATÓRIA — verificar histórico. Imunoglobulina se ferida suja + esquema incompleto."},
{nivel:"info", txt:"PASTA DE BICARBONATO em farpa vegetal profunda: técnica antiga, funciona. Pele expulsa em 24-48h."},
{nivel:"info", txt:"TÉCNICA DO ADESIVO em farpinha superficial (cacto, ouriço): aplicar fita firme, puxar — extrai dezenas de uma vez."},
],
fluxo:null, diretriz:"Roberts & Hedges. PCDT-MS Tungíase."
},

/* ============== REDUÇÃO DE DEDO ============== */
{id:"pulo-reduzir-dedo", nome:"Redução de luxação de dedo — IFP/IFD/mallet", sis:"pulo", grav:"moderada",
cid:"S63.2", ciap:"L80",
sin:["Luxação dedo","Mallet finger","Boutonnière","IFP luxada","Dedo deslocado"],
def:"Luxações de articulações interfalângicas (IFP, IFD) DORSAIS são as mais comuns — geralmente em esporte/trauma. REDUÇÃO MANUAL após anestesia em bloqueio digital — tração axial suave + flexão. Confirmar com Rx PÓS-redução. Imobilizar e encaminhar.",
quadro:["Trauma na mão/dedo durante esporte (basquete, vôlei, futebol) ou queda","Deformidade visível, dor, impossibilidade de mover","TIPOS: IFP DORSAL (mais comum), IFP VOLAR (rara, lesão central slip = boutonnière), IFD (avulsão tendão extensor = mallet finger)","⚠ EXCLUIR fratura associada antes da redução (Rx)"],
diag:["Inspeção + palpação","TESTAR pulsos digitais (preenchimento capilar) — risco vascular","TESTAR sensibilidade dos nervos digitais (palmar, dorsal)","Rx PRÉ-redução em 2 projeções"],
exames:["Rx dedo AP + perfil + oblíqua (pré e pós-redução)"],
rx:[
{etapa:"inicial", d:"⚠ AVALIAR antes de reduzir: pulso digital, sensibilidade, Rx (excluir fratura)"},
{etapa:"escala", d:"BLOQUEIO DIGITAL com lidocaína 1-2% SEM ADRENALINA (extremidade terminal)"},
{etapa:"escala", d:"Inserção: face lateral da base do dedo, 4 pontos cardeais (2 dorsais + 2 volares) — 1-2 mL em cada lado"},
{etapa:"escala", d:"Aguardar 5-10 min para anestesia plena"},
{etapa:"escala", d:"⚠ REDUÇÃO DE IFP / IFD DORSAL (mais comum)"},
{etapa:"escala", d:"Estabilizar a falange proximal com uma mão"},
{etapa:"escala", d:"Aplicar TRAÇÃO AXIAL no dedo distal + HIPEREXTENSÃO suave"},
{etapa:"escala", d:"Empurrar a base distal de volta sobre a falange proximal + FLEXÃO até reduzir"},
{etapa:"escala", d:"Sente um 'clunk' / movimento súbito + recuperação do alinhamento"},
{etapa:"adj", d:"PÓS-REDUÇÃO: Rx confirmar redução + ausência de fratura visível pós-redução"},
{etapa:"adj", d:"TESTAR movimento ativo do dedo + estabilidade ligamentar"},
{etapa:"adj", d:"IMOBILIZAÇÃO em LEVE FLEXÃO com goteira de alumínio acolchoada × 2-3 semanas"},
{etapa:"adj", d:"⚠ MALLET FINGER (avulsão tendão extensor em IFD)"},
{etapa:"adj", d:"Quadro: dedo em 'martelo' — IFD em flexão, incapaz de estender ativamente"},
{etapa:"adj", d:"TRATAMENTO CONSERVADOR (maioria): goteira em HIPEREXTENSÃO da IFD × 6-8 sem ININTERRUPTAS"},
{etapa:"adj", d:"NÃO PODE flexionar IFD nem 1 vez durante esse período — reinicia o tempo. Importante orientar paciente"},
{etapa:"adj", d:"Encaminhar ortopedia para acompanhamento + decisão de cirurgia em fragmento ósseo grande"},
{etapa:"adj", d:"⚠ BOUTONNIÈRE (lesão da banda central do extensor da IFP)"},
{etapa:"adj", d:"Quadro: IFP em flexão + IFD em hiperextensão (deformidade típica)"},
{etapa:"adj", d:"Inicialmente pode ser sutil — só mais tarde a deformidade aparece"},
{etapa:"adj", d:"Goteira EM EXTENSÃO da IFP × 4-6 sem + acompanhamento ortopédico"},
{etapa:"adj", d:"⚠ LUXAÇÕES IRREDUTÍVEIS / RECIDIVANTES / IFP volar / fratura grande / lesão de tendão flexor: ORTOPEDIA"},
{etapa:"alta", d:"ENCAMINHAR ORTOPEDIA: todas as luxações, especialmente IFP/IFD volares, suspeita de lesão tendínea, fraturas associadas"},
{etapa:"alta", d:"FISIOTERAPIA após imobilização — recuperar amplitude e força"},
{etapa:"alta", d:"⚠ Sequelas comuns se mal tratado: rigidez articular crônica, deformidade boutonnière tardia, dor crônica"},
],
alertas:[
{nivel:"crit", txt:"LUXAÇÃO IRREDUTÍVEL após 1-2 tentativas: ORTOPEDIA. Tentativas múltiplas aumentam edema, lesão tecidual."},
{nivel:"crit", txt:"FRATURA-LUXAÇÃO (especialmente IFP volar): ortopedia — risco instabilidade crônica."},
{nivel:"warn", txt:"BLOQUEIO DIGITAL: lidocaína SEM adrenalina. 4 pontos cardeais na base do dedo."},
{nivel:"warn", txt:"MALLET FINGER: imobilização ININTERRUPTA × 6-8 sem em HIPEREXTENSÃO. Flexionar uma vez = reiniciar contagem. Educar paciente repetidamente."},
{nivel:"warn", txt:"BOUTONNIÈRE precoce é sutil — pode ser confundida com 'entorse'. Goteira EM EXTENSÃO da IFP previne deformidade tardia."},
{nivel:"info", txt:"PÓS-REDUÇÃO: Rx é OBRIGATÓRIO — confirmar redução + excluir fratura associada visível pós-redução."},
],
fluxo:null, diretriz:"AAOS. SBOT. Hand Society."
},

/* ============== COTOVELO DE BABÁ ============== */
{id:"pulo-cotovelo-baba", nome:"Cotovelo de babá — subluxação da cabeça do rádio", sis:"pulo", grav:"baixa",
cid:"S53.0", ciap:"L80",
sin:["Cotovelo de babá","Pronação dolorosa","Subluxação da cabeça do rádio","Nursemaid elbow","Pulled elbow"],
def:"SUBLUXAÇÃO da cabeça do rádio em criança 1-4 anos — TRAÇÃO axial no antebraço estendido (puxar braço quando criança vai cair, levantar pela mão). Quadro: criança não move o braço, segurando-o em pronação. REDUÇÃO POR SUPINAÇÃO + FLEXÃO é tão simples que resolve na UBS em 30 segundos.",
quadro:["Criança 1-4 anos (faixa típica) — mais comum em 2-3 anos","TRAÇÃO axial brusca no antebraço — pais 'levantando pela mão' ao atravessar rua, ou puxando ao cair","Criança RECUSA usar o braço, mantém em ABDUÇÃO leve + PRONAÇÃO, antebraço pendente","SEM edema, SEM deformidade visível, SEM dor à palpação focal","Choro inicial → criança 'pseudoparalítica' do braço","⚠ EXCLUIR: fratura supracondiliana (edema, deformidade, dor focal), trauma intencional"],
diag:["Clínica clássica + história típica","NÃO precisa Rx em quadro CLÁSSICO (sem trauma direto, criança 1-4a, sem edema/deformidade)","Rx em casos atípicos: trauma direto, idade fora da faixa, edema visível, sem história de tração"],
exames:["Em quadro CLÁSSICO: nenhum","Rx cotovelo em caso atípico ou se redução falhar"],
rx:[
{etapa:"inicial", d:"⚠ AVALIAR — quadro clássico vs atípico"},
{etapa:"inicial", d:"CLÁSSICO: idade 1-4a, tração axial, criança não move o braço, sem edema/deformidade → tentar redução SEM Rx"},
{etapa:"inicial", d:"ATÍPICO: idade fora, trauma direto, edema, dor focal → Rx primeiro"},
{etapa:"escala", d:"⚠ MANOBRA DE REDUÇÃO POR SUPINAÇÃO + FLEXÃO (clássica, ~80% sucesso)"},
{etapa:"escala", d:"(1) Examinador SENTADO na frente da criança (no colo do cuidador)"},
{etapa:"escala", d:"(2) Estabilizar o cotovelo com uma mão (polegar sobre cabeça do rádio)"},
{etapa:"escala", d:"(3) Com a outra mão, segurar o punho/mão da criança"},
{etapa:"escala", d:"(4) SUPINAR completamente o antebraço (palma para cima)"},
{etapa:"escala", d:"(5) ENQUANTO supina → FLEXIONAR o cotovelo levando a mão da criança ao OMBRO ipsilateral"},
{etapa:"escala", d:"(6) Sente um 'clunk' / pequeno clique sob o polegar sobre a cabeça do rádio"},
{etapa:"escala", d:"⚠ MANOBRA ALTERNATIVA — HIPERPRONAÇÃO (também eficaz, menos dolorosa)"},
{etapa:"escala", d:"Mesmo posicionamento — estabilizar cotovelo, segurar punho"},
{etapa:"escala", d:"HIPERPRONAR rapidamente o antebraço (palma para baixo)"},
{etapa:"escala", d:"Sente o 'clique' sob o polegar"},
{etapa:"adj", d:"PÓS-REDUÇÃO: aguardar 5-15 min — criança volta a USAR o braço normalmente (chorar pelo doce, alcançar brinquedo)"},
{etapa:"adj", d:"⚠ Se em 30 min criança NÃO volta a usar: tentar a outra manobra OU repetir → se falhar, Rx para descartar fratura oculta"},
{etapa:"alta", d:"ORIENTAR PAIS: NÃO levantar criança pelas mãos / antebraços — pegar pelos braços ou tórax"},
{etapa:"alta", d:"RECIDIVA é frequente (~25%) — pais aprendem a reduzir em casa em recidivas"},
{etapa:"alta", d:"GERALMENTE após 5-6 anos cessa (ligamento anular fortalece)"},
],
alertas:[
{nivel:"warn", txt:"⚠ EM QUADRO ATÍPICO (idade fora, trauma direto, edema, deformidade): Rx ANTES — excluir fratura supracondiliana (emergência) ou outras lesões."},
{nivel:"warn", txt:"FRATURA SUPRACONDILIANA do úmero é EMERGÊNCIA pediátrica — dor intensa, deformidade, edema. NÃO tentar redução. Encaminhar ortopedia urgente."},
{nivel:"warn", txt:"FALHA APÓS 2 MANOBRAS: solicitar Rx + considerar referenciamento."},
{nivel:"info", txt:"MANOBRA DE HIPERPRONAÇÃO é menos dolorosa e tão eficaz quanto supinação+flexão — algumas séries mostram melhor sucesso."},
{nivel:"info", txt:"RECIDIVA ~25%. Orientar pais sobre causa (tração axial) — prevenção é educacional."},
],
fluxo:null, diretriz:"AAP. SBP. Cochrane Review Nursemaid Elbow."
},

/* ============== SD TÚNEL DO CARPO AGUDO ============== */
{id:"pulo-tunel-carpo", nome:"Síndrome do túnel do carpo aguda — splint noturno", sis:"pulo", grav:"baixa",
cid:"G56.0", ciap:"N93",
sin:["Túnel do carpo","STC","Parestesia mediana","Splint punho","Splint noturno"],
def:"Crise aguda de STC = compressão do nervo mediano no punho — parestesia em 3,5 primeiros dedos + dor + 'choque', PIORA À NOITE. SPLINT NOTURNO em posição neutra do punho + AINE × 3-4 sem = primeira linha em maioria dos casos. Evita necessidade de cirurgia em >50%.",
quadro:["Parestesia, queimação, 'choque' em POLEGAR + INDICADOR + MÉDIO + metade radial do anular (território do mediano)","PIORA À NOITE (paciente acorda chacoalhando a mão)","Piora com posições mantidas (telefone, dirigir, leitura)","Pode haver fraqueza na pinça polegar-indicador, atrofia tenar em casos crônicos","⚠ EXCLUIR causas SECUNDÁRIAS: hipotireoidismo, gestação, DM2, gota, AR, mieloma, infiltração tumoral"],
diag:["TINEL: percussão sobre punho ventral → parestesia distal (S ~25-30%, E ~75%)","PHALEN: flexão palmar dos punhos × 60s → parestesia (S ~50%, E ~70%)","DURKAN: compressão direta sobre nervo mediano no punho × 30s — mais sensível","Avaliar perda sensitiva (2-point discrimination), atrofia tenar","Eletroneuromiografia (ENMG) confirma — não imediatamente necessária em quadro típico"],
exames:["Geralmente clínica suficiente","TSH, glicemia (causas secundárias)","ENMG para confirmação / decisão cirúrgica"],
rx:[
{etapa:"escala", d:"⚠ SPLINT NOTURNO — 1ª LINHA"},
{etapa:"escala", d:"Imobilizador de punho em POSIÇÃO NEUTRA (não flexão, não extensão — neutra mesmo)"},
{etapa:"escala", d:"USAR durante o SONO + sempre que possível durante o dia"},
{etapa:"escala", d:"Continuar por 3-4 SEMANAS — avaliar resposta", o:"Melhora em ~60-70% dos casos leves-moderados. Sem benefício prolongado >6 sem (avaliar progresso)."},
{etapa:"escala", d:"⚠ AINE SISTÊMICO em curto prazo"},
{etapa:"escala", d:"Ibuprofeno 400-600 mg VO 8/8h × 7-10 dias", o:"+ protetor gástrico se uso prolongado."},
{etapa:"escala", d:"Naproxeno 500 mg 12/12h × 7-10 dias — alternativa"},
{etapa:"adj", d:"AINE TÓPICO — alternativa em paciente com risco de AINE oral (idoso, IRC, ulcerogênico)"},
{etapa:"adj", d:"Diclofenaco gel 1-2% — aplicar 3-4×/d"},
{etapa:"adj", d:"FISIOTERAPIA: mobilização neural, exercícios de deslizamento do tendão flexor"},
{etapa:"adj", d:"⚠ INFILTRAÇÃO LOCAL com CORTICOIDE — 2ª linha"},
{etapa:"adj", d:"Triamcinolona 40 mg + lidocaína 1% — infiltração no túnel do carpo"},
{etapa:"adj", d:"Eficácia 60-80% em curto prazo, 25-50% sustentada em 1 ano", o:"Especialista (ortopedia/reumatologia)."},
{etapa:"adj", d:"INVESTIGAR CAUSAS SECUNDÁRIAS:"},
{etapa:"adj", d:"TSH (hipotireoidismo)"},
{etapa:"adj", d:"Glicemia + HbA1c (DM2)"},
{etapa:"adj", d:"Gestação atual"},
{etapa:"adj", d:"FR + anti-CCP (AR), ácido úrico (gota)"},
{etapa:"alta", d:"⚠ REFERENCIAR ORTOPEDIA / CIRURGIA DE MÃO se:"},
{etapa:"alta", d:"Falha após 6-8 semanas de tratamento conservador"},
{etapa:"alta", d:"Atrofia tenar / fraqueza significativa"},
{etapa:"alta", d:"ENMG com déficit moderado-grave"},
{etapa:"alta", d:"Sintomas constantes / não apenas noturnos"},
{etapa:"alta", d:"⚠ STC NA GESTAÇÃO: geralmente AUTOLIMITADA pós-parto (resolução em até 1 ano). Splint + analgesia simples. Cirurgia raramente necessária"},
{etapa:"alta", d:"ORIENTAR ergonomia: pausas no teclado/mouse, postura, evitar flexão palmar prolongada"},
],
alertas:[
{nivel:"warn", txt:"INVESTIGAR causas secundárias antes de cirurgia: hipotireoidismo, DM2, gestação, AR. Tratamento da causa pode resolver STC."},
{nivel:"warn", txt:"ATROFIA TENAR / fraqueza significativa = ENMG + ortopedia. Tratamento conservador prolongado pode levar à lesão permanente do mediano."},
{nivel:"warn", txt:"INFILTRAÇÃO COM CORTICOIDE: eficaz em curto prazo (60-80%) mas durabilidade limitada (25-50% em 1 ano). Útil em gestante ou pré-operatório."},
{nivel:"info", txt:"SPLINT NOTURNO: posição NEUTRA do punho. Splints comerciais com 'haste' rígida que mantém neutralidade. Resposta em 3-4 semanas."},
{nivel:"info", txt:"STC GESTACIONAL: geralmente resolve até 1 ano pós-parto. Tratamento conservador (splint + analgesia). Cirurgia raramente."},
],
fluxo:null, diretriz:"AAOS. SBOT. Cochrane Review STC."
},

);
