/* ===========================================================
   VOVÔMINIC EMERGÊNCIA — DADOS CLÍNICOS
   80 patologias do Guia de Prescrições da Emergência 2026
   Estrutura: {id, nome, sin, sis, grav, def, rx, alertas, exames, fisio, mec, diretriz, fluxo, calcs}
   =========================================================== */

const SISTEMAS = {
  cardio:   { nome: "Cardiovascular",        icone: "♥", cor: "#DC2626" },
  neuro:    { nome: "Neurológico",           icone: "⌬", cor: "#7C3AED" },
  resp:     { nome: "Respiratório",          icone: "◐", cor: "#0891B2" },
  gi:       { nome: "Gastrointestinal",      icone: "◗", cor: "#CA8A04" },
  endo:     { nome: "Endócrino",             icone: "◈", cor: "#DB2777" },
  gu:       { nome: "Genito-urinário",       icone: "◎", cor: "#0284C7" },
  ost:      { nome: "Osteomuscular",         icone: "◇", cor: "#65A30D" },
  psiq:     { nome: "Psiquiatria",           icone: "◍", cor: "#9333EA" },
  hidro:    { nome: "Hidroeletrolítico",     icone: "◉", cor: "#0EA5E9" },
  infecto:  { nome: "Infectologia & Sepse",  icone: "✦", cor: "#16A34A" },
  anaf:     { nome: "Anafilaxia & Alergia",  icone: "▲", cor: "#E11D48" },
  tox:      { nome: "Intoxicações",          icone: "☣", cor: "#F59E0B" },
  pec:      { nome: "Animais peçonhentos",   icone: "◬", cor: "#84CC16" },
  hemo:     { nome: "Hematologia & Hemo",    icone: "●", cor: "#BE123C" },
  vaso:     { nome: "Drogas vasoativas",     icone: "◆", cor: "#EA580C" },
  iot:      { nome: "Sedação & IOT",         icone: "≡", cor: "#475569" },
  gest:     { nome: "Gestantes",             icone: "◯", cor: "#DB2777" },
  obst:     { nome: "Obstetrícia",           icone: "♀", cor: "#BE185D" },
  trauma:   { nome: "Trauma",                icone: "✖", cor: "#7C2D12" },
  derm:     { nome: "Dermatologia",          icone: "❋", cor: "#A21CAF" },
  oft:      { nome: "Oftalmologia / ORL",    icone: "◉", cor: "#1D4ED8" },
  ubs:      { nome: "UBS / Prevenção",       icone: "✚", cor: "#059669" },
  anal:     { nome: "Analgesia",             icone: "◴", cor: "#A16207" },
  pulo:     { nome: "Pulo do Gato",          icone: "★", cor: "#F59E0B" },
  conv:     { nome: "Conversores / Calc",    icone: "↔", cor: "#2563EB" },
  proc:     { nome: "Procedimentos",         icone: "✣", cor: "#7C2D12" },
  docs:     { nome: "Médico-Legal / Docs",   icone: "§", cor: "#0F766E" },
  med:      { nome: "Biblioteca Medicações", icone: "℞", cor: "#DB2777" },
};

const PATOLOGIAS = [
/* ============== CARDIO ============== */
{
  id: "tsv", sis: "cardio", grav: "alta",
  nome: "Taquicardia Supraventricular (TSV)",
  sin: ["TSV", "taqui supra", "AVNRT", "AVRT", "taquicardia paroxística"],
  def: "Taquicardia regular de QRS estreito (<120 ms), FC 150–250 bpm, geralmente por reentrada nodal (AVNRT) ou via acessória (AVRT).",
  exames: ["ECG 12 derivações", "Eletrólitos (K, Mg)", "TSH se recorrente", "β-HCG em mulher fértil"],
  rx: [
    { etapa:"inicial", d: "Manobra vagal", do: "Valsalva modificada (REVERT)", via: "—", o: "Tentar primeiro em paciente estável. Decúbito + elevar MMII após esforço expiratório por 15 s." },
    { etapa:"escala", d: "Adenosina", do: "6 mg IV bolus rápido", via: "IV", o: "Veia calibrosa (antecubital), em <1 s + flush SF 20 mL imediato. Avisar paciente: sensação de morte iminente passageira (5–10 s)." },
    { etapa:"escala", d: "Adenosina (2ª dose)", do: "12 mg IV bolus", via: "IV", o: "Se não reverter em 1–2 min. Pode repetir 12 mg." },
    { etapa:"escala", d: "Verapamil", do: "2,5–5 mg IV em 2 min", via: "IV", o: "Alternativa se sem WPW. Evitar com β-bloq, IC ou hipotensão." },
    { etapa:"escala", d: "Metoprolol", do: "2,5–5 mg IV em 2 min", via: "IV", o: "Repetir até 15 mg. Alternativa em pacientes estáveis sem broncoespasmo." },
  ],
  alertas: [
    { t: "crit", x: "Instabilidade (hipotensão, dor torácica, ↓consciência, IC) → cardioversão sincronizada 50–100 J imediata." },
    { t: "warn", x: "Em WPW com FA pré-excitada (QRS largo, irregular, MUITO rápida): NÃO usar adenosina, β-bloq, Ca²⁺-bloq ou digital — risco de FV. Usar procainamida ou cardioversão." },
  ],
  fisio: "A maioria das TSVs decorre de circuitos de reentrada envolvendo o nó AV. Na <strong>AVNRT</strong> (60%), existem duas vias funcionais dentro do próprio nó AV (rápida e lenta) que formam um pequeno circuito. Na <strong>AVRT</strong> (30%), o circuito utiliza uma via acessória (ex.: feixe de Kent no Wolff-Parkinson-White). O gatilho é geralmente uma extrassístole atrial que encontra uma via refratária e percorre a outra, iniciando o ciclo. A FC alta (150–250 bpm) compromete o enchimento ventricular, reduzindo o débito cardíaco e podendo causar sintomas (palpitação, dispneia, dor torácica, pré-síncope). Em corações estruturalmente normais o prognóstico é excelente; a presença de instabilidade exige reversão imediata.",
  mec: [
    { d: "Adenosina", x: "Nucleosídeo endógeno que se liga a receptores <strong>A1 acoplados a Gi</strong> nas células do nó AV. Ativa canais de K⁺ retificadores (hiperpolarização) e inibe corrente Ca²⁺ tipo L → <strong>bloqueio AV transitório de 6–10 s</strong> que interrompe o circuito de reentrada. Meia-vida ultracurta (<10 s) por captação celular e degradação pela adenosina deaminase." },
    { d: "Verapamil", x: "Bloqueador de canais de Ca²⁺ tipo L (classe IV) com seletividade nodal — prolonga período refratário do nó AV." },
    { d: "Metoprolol", x: "Antagonista β1-seletivo — reduz automatismo e condução nodal por antagonismo simpático." },
  ],
  diretriz: "AHA ACLS Adult Tachycardia (Panchal AR et al., Circulation 2020;142:S366–S468, DOI:10.1161/CIR.0000000000000916). Diretriz SBC de Arritmias Supraventriculares 2016.",
  fluxo: "tsv",
  calcs: [],
},
{
  id: "tv", sis: "cardio", grav: "alta",
  nome: "Taquicardia Ventricular (TV)",
  sin: ["TV", "taquicardia ventricular monomórfica", "torsades"],
  def: "Taquicardia de QRS largo (≥120 ms), FC >100, origem ventricular. Monomórfica geralmente por reentrada em cicatriz pós-IAM; polimórfica/torsades em QT longo.",
  exames: ["ECG 12 derivações (comparar com prévio)", "Eletrólitos (K, Mg, Ca)", "Troponina", "Função renal", "Magnésio sérico se QT longo"],
  rx: [
    { etapa:"escala", d: "Cardioversão sincronizada", do: "100 J → 200 J", via: "—", o: "1ª linha SEMPRE que instável (PAS <90, dor torácica, EAP, alteração de consciência). Sedação se possível (etomidato 0,15 mg/kg ou cetamina)." },
    { etapa:"escala", d: "Amiodarona", do: "150 mg IV em 10 min", via: "IV", o: "Estável. Diluir em SG 5% 100 mL. Manutenção: 1 mg/min × 6h, depois 0,5 mg/min × 18h. Total <2,2 g/24h." },
    { etapa:"escala", d: "Sulfato de magnésio", do: "2 g IV em 10 min", via: "IV", o: "TV polimórfica / torsades de pointes. Pode repetir." },
    { etapa:"escala", d: "Lidocaína", do: "1–1,5 mg/kg IV bolus", via: "IV", o: "Alternativa em TV isquêmica. Manutenção 1–4 mg/min." },
  ],
  alertas: [
    { t: "crit", x: "TV sem pulso ou FV → desfibrilação imediata 200 J bifásica + RCP. Algoritmo ACLS PCR." },
    { t: "warn", x: "Torsades: corrigir K e Mg, suspender drogas QT-prolongadoras (haloperidol, ondansetrona, macrolídeos, quinolonas, metadona)." },
  ],
  fisio: "A TV origina-se abaixo do feixe de His. A causa mais comum é <strong>reentrada em torno de cicatriz miocárdica</strong> pós-IAM, mas também ocorre por automatismo anormal (intoxicação digitálica, hipocalemia) ou atividade deflagrada (QT longo → torsades). Na TV polimórfica do tipo torsades de pointes, a repolarização ventricular prolongada (QTc >500 ms) gera EADs (early after-depolarizations) que disparam batimentos ectópicos em padrão de \"giro em torno do eixo\". A FC alta e a perda do sincronismo AV reduzem o débito cardíaco; degeneração para FV é o risco principal.",
  mec: [
    { d: "Amiodarona", x: "Antiarrítmico <strong>multicanal</strong> classe III (Vaughan-Williams) que também tem ação classe I (bloqueio Na⁺), classe II (β-bloqueio não competitivo) e classe IV (bloqueio Ca²⁺). O bloqueio dos canais de K⁺ prolonga a repolarização e o período refratário efetivo, suprimindo reentradas. Efeitos adversos crônicos: tireoide, fígado, pulmão, córnea, pele." },
    { d: "Magnésio", x: "Estabiliza membrana miocárdica, suprime EADs e encurta o QT em torsades, prevenindo recorrência." },
    { d: "Lidocaína", x: "Bloqueador de canais de Na⁺ (classe IB) preferencialmente em estado ativo/inativo — atua em tecido isquêmico com maior despolarização." },
  ],
  diretriz: "AHA ACLS Tachycardia Algorithm 2020 (Panchal AR et al., Circulation 2020;142:S366–S468, DOI:10.1161/CIR.0000000000000916). Diretriz Brasileira de Arritmias Ventriculares (SBC, Arq Bras Cardiol 2020).",
  fluxo: null,
  calcs: [],
},
{
  id: "fa", sis: "cardio", grav: "alta",
  nome: "Fibrilação Atrial e Flutter Atrial",
  sin: ["FA", "fibrilação atrial", "flutter", "arritmia"],
  def: "FA: ausência de ondas P, RR irregularmente irregular. Flutter: ondas F serrilhadas em DII/DIII/aVF, condução geralmente 2:1 (FC ~150).",
  exames: ["ECG 12 derivações", "TSH (descartar tireotoxicose)", "Eletrólitos", "Troponina se dor torácica", "Eco TT (estrutural)", "β-HCG"],
  rx: [
    { etapa:"escala", d: "Metoprolol", do: "5 mg IV em 2 min, repetir até 15 mg", via: "IV", o: "Controle de FC se estável. Manter VO 25–100 mg 12/12h." },
    { etapa:"escala", d: "Diltiazem", do: "0,25 mg/kg IV em 2 min", via: "IV", o: "Alternativa se contraindicação a β-bloq. Repetir 0,35 mg/kg em 15 min se necessário." },
    { etapa:"escala", d: "Deslanosídeo", do: "0,4 mg IV em 5 min", via: "IV", o: "Em IC ou hipotensão. Início em 15–30 min. Cuidado em IRC." },
    { etapa:"escala", d: "Cardioversão sincronizada", do: "150–200 J bifásica", via: "—", o: "Se instável OU eletiva com TEE-guided ou ≥3 sem de anticoagulação. Sedação com etomidato/propofol." },
    { etapa:"anticoag", d: "Anticoagulação (DOAC)", do: "Apixabana 5 mg 12/12h • Rivaroxabana 20 mg/d • Dabigatrana 150 mg 12/12h", via: "VO", o: "Iniciar conforme CHA₂DS₂-VA. DOAC > varfarina em FA não-valvar. Ajustar para IRC." },
    { etapa:"anticoag", d: "Varfarina", do: "Iniciar 2,5–5 mg/d, ajustar INR 2–3", via: "VO", o: "FA valvar (estenose mitral reumática moderada/grave, prótese mecânica)." },
  ],
  alertas: [
    { t: "crit", x: "Instabilidade (hipotensão, dor torácica, ICAD, alteração de consciência) → cardioversão sincronizada imediata 200 J." },
    { t: "warn", x: "Cardioversão eletiva em FA >48h sem anticoagulação prévia: ETE para excluir trombo OU 3 sem de anticoagulação + 4 sem após." },
    { t: "info", x: "CHA₂DS₂-VA (SBC 2025, remove sexo feminino): 0 = não anticoagular; 1 = individualizar; ≥2 = anticoagular." },
  ],
  fisio: "Na FA, múltiplos circuitos de microrreentrada e focos ectópicos das veias pulmonares causam ativação atrial desorganizada (>400 bpm). A perda da contração atrial efetiva reduz o débito cardíaco em 20–30% e gera <strong>estase no apêndice atrial esquerdo</strong>, principal sítio de formação de trombo e fonte de embolia. O risco anual de AVC sem anticoagulação varia de 0,6% (CHA₂DS₂-VA = 0) até 18% (CHA₂DS₂-VA ≥6). O flutter típico é uma macrorreentrada no istmo cavotricuspídeo do AD, com risco embólico semelhante ao da FA.",
  mec: [
    { d: "Apixabana / Rivaroxabana / Edoxabana", x: "Inibidores diretos do <strong>fator Xa</strong>. Bloqueiam a conversão de protrombina em trombina, interrompendo a cascata de coagulação no ponto comum extrínseco/intrínseco. Sem necessidade de monitorização de INR. Reversão: andexanet alfa." },
    { d: "Dabigatrana", x: "Inibidor direto da <strong>trombina (fator IIa)</strong>. Impede conversão de fibrinogênio em fibrina e ativação plaquetária por trombina. Reversão: idarucizumab." },
    { d: "Metoprolol", x: "β1-bloqueador — reduz condução e período refratário do nó AV, controlando resposta ventricular." },
    { d: "Diltiazem", x: "Bloqueador Ca²⁺ tipo L com seletividade nodal (não-diidropiridínico)." },
    { d: "Deslanosídeo / Digoxina", x: "Inibe Na⁺/K⁺-ATPase miocárdica → ↑Ca²⁺ intracelular (inotropismo). No nó AV, ↑tônus vagal e ↓condução." },
  ],
  diretriz: "Diretriz Brasileira de Fibrilação Atrial 2025 (Magalhães LP et al., SBC/SOBRAC, Arq Bras Cardiol 2025). 2023 ACC/AHA/ACCP/HRS Guideline for the Diagnosis and Management of AF (Joglar JA et al., Circulation 2024;149:e1–e156, DOI:10.1161/CIR.0000000000001193).",
  fluxo: null,
  calcs: ["chads-va", "hasbled"],
},
{
  id: "brady", sis: "cardio", grav: "alta",
  nome: "Bradiarritmias e BAVs",
  sin: ["bradicardia", "BAV", "bloqueio AV", "BAVT", "Mobitz"],
  def: "FC <50 bpm sintomática. Disfunção sinusal ou BAVs (1º: PR >200 ms; Mobitz I: PR progressivo até P bloqueada; Mobitz II: PR fixo + P bloqueada súbita; BAVT: dissociação AV).",
  exames: ["ECG 12 derivações + tira longa de DII", "Eletrólitos (K)", "TSH", "Troponina (IAM inferior)", "Função renal", "Revisão medicamentosa"],
  rx: [
    { etapa:"escala", d: "Atropina", do: "1 mg IV bolus, repetir cada 3–5 min", via: "IV", o: "Máximo 3 mg. Pouco efeito em BAV infranodal (Mobitz II, BAVT com QRS largo)." },
    { etapa:"escala", d: "Dopamina", do: "5–20 mcg/kg/min em BIC", via: "IV", o: "2ª linha se atropina falhar. Diluir 250 mg em 250 mL SG5%." },
    { etapa:"escala", d: "Adrenalina", do: "2–10 mcg/min em BIC", via: "IV", o: "2ª linha. 1 mg em 250 mL SG5% = 4 mcg/mL." },
    { etapa:"escala", d: "Marcapasso transcutâneo", do: "60–80 bpm, 50–100 mA", via: "—", o: "Ponte até MPT/definitivo. Sedoanalgesia (fentanil, midazolam)." },
  ],
  alertas: [
    { t: "crit", x: "BAV 2º Mobitz II ou BAVT com QRS largo: NÃO confiar em atropina; preparar marcapasso. Indica MPT em ~todos." },
    { t: "warn", x: "IAM inferior: bradicardia frequentemente vagal, responde bem a atropina. IAM anterior + BAV avançado: lesão extensa, prognóstico ruim." },
    { t: "info", x: "Verificar causas reversíveis: hipercalemia, drogas (β-bloq, dig, Ca²⁺-bloq), hipotireoidismo, hipotermia, hipertensão intracraniana, isquemia." },
  ],
  fisio: "Disfunção sinusal (doença do nó sinusal) é frequente em idosos por fibrose. Os BAVs podem ser <strong>nodais</strong> (Mobitz I, geralmente benignos, responsivos a atropina) ou <strong>infranodais</strong> (Mobitz II, BAVT com QRS largo — comprometimento do feixe de His ou ramos, escape ventricular instável). O escape juncional (40–60 bpm, QRS estreito) é mais estável que o escape ventricular (<40 bpm, QRS largo). Em IAM inferior, a oclusão da artéria coronária direita pode causar bradicardia/BAV por isquemia do nó AV ou tônus vagal (reflexo de Bezold-Jarisch).",
  mec: [
    { d: "Atropina", x: "Antagonista competitivo dos <strong>receptores muscarínicos (M1–M5)</strong>; no nó sinusal e AV bloqueia o tônus vagal mediado por M2, ↑FC e melhora condução. Pouco efeito em bloqueio anatômico abaixo do nó AV." },
    { d: "Dopamina", x: "Em doses 5–10 mcg/kg/min predomina ação β1 (cronotrópico/inotrópico); em doses ≥10 mcg/kg/min adiciona α1 (vasoconstrição)." },
    { d: "Adrenalina", x: "Agonista α e β; em bradicardia o efeito β1 cronotrópico e o β2 acelerador AV são desejáveis." },
  ],
  diretriz: "ACC/AHA/HRS Guideline on the Evaluation and Management of Patients with Bradycardia and Cardiac Conduction Delay (Kusumoto FM et al., Circulation 2019;140:e382–e482, DOI:10.1161/CIR.0000000000000628). AHA ACLS Bradycardia 2020.",
  fluxo: null,
  calcs: [],
},
{
  id: "sca", sis: "cardio", grav: "alta",
  nome: "Síndrome Coronariana Aguda (SCA / IAM)",
  sin: ["IAM", "infarto", "STEMI", "NSTEMI", "angina instável", "supra de ST"],
  def: "Dor torácica anginosa + alteração de ECG (supra ≥1 mm em 2 derivações contíguas ou ≥2 mm V2-V3 = IAMCST; infra/inversão T = IAMSSST/AI) + troponina.",
  exames: ["ECG <10 min da chegada (repetir 15–30 min se inicial não-diagnóstico)", "Troponina ultrassensível 0–1h ou 0–3h", "RX tórax", "Função renal, glicemia, lipidograma", "Hemograma, coagulograma"],
  rx: [
    {etapa:"inicial", d:"ECG <10 min + Monitor + 2 acessos",do:"ECG seriado se inicial não-diagnóstico (15-30 min)",via:"—",o:"Tempo porta-ECG é crítico. Repetir ECG se dor mantida e 1º normal."},
    {etapa:"inicial", d:"AAS",do:"300 mg VO mastigar",via:"VO",o:"Primeira dose IMEDIATA. Manutenção 100 mg/d indefinidamente."},
    {etapa:"inicial", d:"O₂ se SpO₂ <90% ou dispneia",do:"2-4 L/min cateter",via:"—",o:"NÃO oxigênio rotineiro em SpO₂ normal (risco vasoconstrição coronária)."},
    {etapa:"escala", d:"② Inibidor P2Y12 — Clopidogrel",do:"300-600 mg VO ataque",via:"VO",o:"600 mg se ICP. Manutenção 75 mg/d × 12 meses. Idoso >75a + fibrinólise: 75 mg sem ataque."},
    {etapa:"escala", d:"② Inibidor P2Y12 — Ticagrelor (alternativa)",do:"180 mg VO ataque + 90 mg 12/12h",via:"VO",o:"Preferido em IAMCST/IAMSSST de alto risco. CI: sangramento, AVC hemorrágico. NÃO usar com fibrinolítico."},
    {etapa:"escala", d:"② Inibidor P2Y12 — Prasugrel (só ICP)",do:"60 mg VO ataque + 10 mg/d",via:"VO",o:"Apenas para ICP. CI: AVC prévio, >75a, <60 kg."},
    {etapa:"escala", d:"③ Anticoagulante — Enoxaparina",do:"1 mg/kg SC 12/12h",via:"SC",o:"Bolus IV 30 mg se IAMCST com fibrinólise. Idoso >75a: 0,75 mg/kg 12/12h sem bolus."},
    {etapa:"escala", d:"④ REPERFUSÃO — ICP primária (preferida)",do:"Hemodinâmica em ≤90 min porta-balão",via:"—",o:"PADRÃO-OURO no IAMCST. Acionar hemodinâmica IMEDIATAMENTE."},
    {etapa:"escala", d:"④ REPERFUSÃO — Alteplase (se ICP indisponível)",do:"15 mg bolus + 0,75 mg/kg em 30 min + 0,5 mg/kg em 60 min (máx 100 mg)",via:"IV",o:"Se ICP não disponível em ≤120 min e <12h de sintomas, sem CI absoluta. Porta-agulha ≤30 min."},
    {etapa:"adj", d:"Atorvastatina",do:"80 mg VO dose única",via:"VO",o:"Independente do colesterol. Estabiliza placa e reduz eventos."},
    {etapa:"adj", d:"Nitroglicerina",do:"5-200 mcg/min IV titular",via:"IV",o:"Para dor isquêmica + congestão. CI: PAS <90, IAM de VD, sildenafil <24h."},
    {etapa:"adj", d:"Metoprolol (após 24h se estável)",do:"25-50 mg VO 12/12h",via:"VO",o:"NÃO em fase aguda se Killip ≥II, FC<60, PAS<100, BAV. Iniciar quando estável."},
    {etapa:"adj", d:"Morfina (apenas refratária)",do:"2-4 mg IV",via:"IV",o:"Apenas se dor refratária a nitrato. Cuidado: associada com pior desfecho (CRUSADE)."},
    {etapa:"alta", d:"Alta — prescrição MOVED",do:"MEED (Metoprolol+Estatina+Enalapril+DAPT)",via:"VO",o:"DAPT 12 meses (AAS + clopi/tica/prasu). Estatina alta intensidade. IECA/BRA se FE<40. β-bloq. Reabilitação cardíaca."},
  ],
  alertas: [
    { t: "crit", x: "IAMCST: porta-balão ≤90 min ou porta-agulha ≤30 min. Tempo é músculo." },
    { t: "warn", x: "NÃO fazer pré-tratamento rotineiro com inibidor P2Y12 em IAMSSST com estratégia invasiva precoce <24h (ESC 2020, SBC 2021)." },
    { t: "info", x: "IAM de VD (supra em V1, V3R, V4R): NITRATO É CONTRAINDICADO. Tratar com volume." },
  ],
  fisio: "A SCA decorre de ruptura ou erosão de placa aterosclerótica vulnerável → exposição do conteúdo lipídico → ativação plaquetária via colágeno/fator tecidual → agregação plaquetária e cascata de coagulação → trombo. Se a oclusão é <strong>parcial</strong>, há angina instável ou IAMSSST (necrose subendocárdica, infradesnível/inversão T). Se a oclusão é <strong>total</strong>, há IAMCST (necrose transmural, supradesnível). A janela terapêutica é estreita: cada 30 min de atraso na reperfusão = 1% absoluto de aumento de mortalidade em 1 ano. A estratégia primária é a <strong>angioplastia primária</strong> (ICP) — superior à fibrinólise se realizada em ≤120 min da chegada.",
  mec: [
    { d: "AAS", x: "Acetila e <strong>inibe irreversivelmente a COX-1 plaquetária</strong>, impedindo a síntese de tromboxano A2 (potente agregante e vasoconstritor). Efeito por toda a vida da plaqueta (7–10 dias)." },
    { d: "Clopidogrel / Prasugrel / Ticagrelor", x: "Antagonistas do receptor <strong>P2Y12 plaquetário</strong>. Clopidogrel e prasugrel são pró-drogas que se ligam irreversivelmente; ticagrelor é diretamente ativo e reversível. Bloqueiam a amplificação da agregação plaquetária dependente de ADP." },
    { d: "Enoxaparina", x: "Heparina de baixo peso molecular — ativa antitrombina III com preferência por <strong>anti-Xa</strong> (4:1 vs. anti-IIa). Efeito mais previsível que HNF, não requer aPTT." },
    { d: "Alteplase", x: "rt-PA recombinante — converte plasminogênio em plasmina, que <strong>degrada fibrina</strong>. Fibrinoespecífica (atua preferencialmente em coágulos)." },
    { d: "Atorvastatina", x: "Inibe HMG-CoA redutase, ↓síntese de colesterol; efeito pleiotrópico precoce: estabiliza placa, ↓inflamação, melhora função endotelial." },
    { d: "Nitroglicerina", x: "Doador de NO → ativa guanilato ciclase → ↑GMPc → relaxa músculo liso vascular. <strong>Venodilatação predominante</strong> em doses baixas (↓pré-carga), arterial em doses altas." },
    { d: "Metoprolol", x: "β1-bloqueador — ↓FC, ↓contratilidade, ↓consumo miocárdico de O₂ e ↓arritmias." },
  ],
  diretriz: "Diretriz SBC SCA sem Supra de ST 2021 (Nicolau JC et al., Arq Bras Cardiol 2021;117(1):181–264). Diretriz SBC IAM com Supra de ST 2024. 2023 ESC ACS Guidelines (Byrne RA et al., Eur Heart J 2023;44:3720–3826, DOI:10.1093/eurheartj/ehad191).",
  imgs: [
    {src:"https://upload.wikimedia.org/wikipedia/commons/7/76/12_Lead_EKG_ST_Elevation_tracing_color_coded.jpg",
     alt:"ECG 12 derivações com supra de ST",
     caption:"IAMCST — supra de ST em parede inferior (II, III, aVF), com imagem em espelho em DI/aVL.",
     source:"Wikimedia Commons / Glenlarson (Domínio público)"},
  ],
  fluxo: "sca",
  calcs: ["heart", "grace", "timi"],
},
{
  id: "eap", sis: "cardio", grav: "alta",
  nome: "ICAD / Edema Agudo de Pulmão",
  sin: ["EAP", "ICAD", "insuficiência cardíaca", "SCAPE", "FOSPE"],
  def: "Dispneia súbita + congestão pulmonar (crepitantes, dessat) + ↑pressão de enchimento esquerdo. SCAPE: hipertensiva, súbita. FOSPE: hipervolêmica, progressiva.",
  exames: ["RX tórax (cefalização, linhas B, asa de morcego)", "BNP/NT-proBNP", "Troponina", "ECG", "Função renal", "Eletrólitos", "POCUS (linhas B, função VE, VCI)"],
  rx: [
    {etapa:"inicial", d:"Posição sentada + 2 acessos + monitorização",do:"Cabeceira ≥45°, perpendicular à cama",via:"—",o:"Reduz retorno venoso e desconforto. Monitorar PA, FC, SpO2, FR, débito urinário."},
    {etapa:"inicial", d:"O₂ alto fluxo",do:"10-15 L/min máscara não-reinalante",via:"—",o:"SpO2 alvo ≥94%. NÃO atrasa VNI se persiste dessaturação."},
    {etapa:"escala", d:"① VNI (CPAP/BiPAP)",do:"EPAP 8-10, IPAP 12-15 cmH₂O, FiO₂ titulada",via:"Máscara",o:"PRIMEIRA LINHA. Reduz IOT em 50%. CI: rebaixamento, vômitos, instabilidade hemodinâmica grave."},
    {etapa:"escala", d:"② Furosemida",do:"40-80 mg IV bolus (dose IV ≥ dose VO crônica)",via:"IV",o:"Repetir 20-40 min se diurese insuficiente. Manutenção: dobrar dose ou BIC 5-10 mg/h em refratário."},
    {etapa:"escala", d:"③ Nitroglicerina (SCAPE)",do:"5-10 mcg/min, dobrar a cada 3-5 min até 200 mcg/min",via:"IV",o:"PRINCIPAL em SCAPE (hipertensivo). ↓pré-carga em baixa dose, + arterial em alta. Manter PAS >100."},
    {etapa:"escala", d:"③ Nitroprussiato (alternativo)",do:"0,25-10 mcg/kg/min",via:"IV",o:"Vasodilatação balanceada. Cuidado com IRC (tiocianato). Proteger da luz."},
    {etapa:"escala", d:"④ Dobutamina (se baixo débito)",do:"2,5-20 mcg/kg/min",via:"IV",o:"Apenas em baixo débito (PAS <90 sem hipovolemia) + má perfusão. NÃO usar em SCAPE puro."},
    {etapa:"escala", d:"⑤ Noradrenalina (choque cardiogênico)",do:"0,05-1 mcg/kg/min",via:"IV",o:"Se hipotensão grave/choque cardiogênico (Killip IV). Associar dobutamina."},
    {etapa:"adj", d:"Tratar GATILHO",do:"SCA / FA com RVR / crise hipertensiva / infecção / má aderência / anemia / tireotoxicose",via:"—",o:"Buscar e tratar causa subjacente — ECG, troponina, RX, TSH, etc."},
    {etapa:"adj", d:"IOT se falha VNI",do:"Após 1-2h de VNI sem melhora",via:"—",o:"Indicações: rebaixamento, esforço respiratório excessivo, hipoxemia refratária."},
    {etapa:"alta", d:"Otimização medicamentosa pós-estabilização",do:"IECA/BRA + β-bloq + espironolactona + diurético manutenção",via:"VO",o:"GDMT (terapia guiada por diretriz). Considerar sacubitril/valsartana se FE<40%."},
  ],
  alertas: [
    { t: "warn", x: "Morfina em EAP foi associada a pior desfecho (ADHERE n=147.632, OR mortalidade 4,8). EVITAR uso rotineiro." },
    { t: "crit", x: "Choque cardiogênico (Killip IV): noradrenalina + dobutamina + considerar suporte circulatório (BIA, ECMO)." },
    { t: "info", x: "Sempre buscar gatilho: SCA, FA com RVR, crise hipertensiva, infecção, má aderência, anemia, tireotoxicose." },
  ],
  fisio: "A IC descompensada gera ↑pressão diastólica final do VE → transmissão para AE → veias pulmonares → capilar pulmonar. Quando a pressão hidrostática capilar excede ~25 mmHg, há <strong>transudação para o interstício e alvéolos</strong> (edema). Dois fenótipos: <strong>SCAPE</strong> (Sympathetic Crashing Acute Pulmonary Edema) é uma crise hipertensiva com redistribuição de fluido (sem hipervolemia significativa) — o paciente tem PAS muito alta, dispneia súbita, sem ganho de peso. <strong>FOSPE</strong> (Fluid Overload SPE) é hipervolemia progressiva por má aderência/sódio/diuréticos — congestão sistêmica e pulmonar, ganho de peso, edema periférico. O tratamento difere: SCAPE → vasodilatador é a chave; FOSPE → diurético é central.",
  mec: [
    { d: "Furosemida", x: "Inibe o <strong>cotransportador Na⁺/K⁺/2Cl⁻ na alça espessa ascendente de Henle</strong> — natriurese intensa. Adicionalmente, induz venodilatação precoce (15–30 min, antes da diurese) via aumento de prostaglandinas, reduzindo pré-carga." },
    { d: "Nitroglicerina", x: "Liberação de NO → ↑GMPc → relaxamento muscular liso. <strong>Doses baixas (≤1 mcg/kg/min)</strong>: venodilatação seletiva, ↓pré-carga e congestão pulmonar. <strong>Doses altas</strong>: + dilatação arterial, ↓pós-carga." },
    { d: "Nitroprussiato", x: "Doador de NO de ação balanceada (arterial e venosa). Risco de toxicidade por cianeto/tiocianato em uso prolongado ou IRC." },
    { d: "Dobutamina", x: "<strong>β1-agonista</strong> seletivo — ↑contratilidade e FC; leve efeito β2 vasodilatador (↓pós-carga). Útil em baixo débito; pode causar taquicardia, arritmia, e tolerância." },
    { d: "VNI (CPAP)", x: "Pressão positiva contínua na via aérea: (1) recruta alvéolos colapsados → melhora oxigenação; (2) reduz retorno venoso → ↓pré-carga; (3) reduz pós-carga do VE; (4) ↓trabalho respiratório. <strong>Evita IOT em 50% dos casos</strong>." },
  ],
  diretriz: "Diretriz Brasileira de Insuficiência Cardíaca Aguda 2018 (Rohde LE et al., SBC, Arq Bras Cardiol 2018;111:436–539). 2021 ESC HF Guidelines (McDonagh TA et al., Eur Heart J 2021;42:3599–3726).",
  fluxo: null,
  calcs: ["killip"],
},
{
  id: "ehp", sis: "cardio", grav: "alta",
  nome: "Crise Hipertensiva (Emergência / Urgência)",
  sin: ["crise hipertensiva", "emergência hipertensiva", "urgência hipertensiva", "HAS"],
  def: "PA ≥180×120 mmHg. <strong>Emergência</strong>: + lesão de órgão-alvo aguda (encefalopatia, AVC, EAP, SCA, dissecção, eclâmpsia, IRA, retinopatia). <strong>Urgência</strong>: sem LOA aguda.",
  exames: ["Avaliação completa de LOA: ECG, troponina, RX tórax", "Função renal + EAS", "Fundo de olho", "TC crânio se cefaleia/déficit", "β-HCG"],
  rx: [
    { etapa:"escala", d: "Nitroprussiato", do: "0,25–10 mcg/kg/min", via: "IV", o: "Emergência hipertensiva geral. 50 mg em 250 mL SG5% = 200 mcg/mL. Proteger da luz. Reduzir 20–25% nas primeiras 2h, depois para 160×100 em 6h." },
    { etapa:"escala", d: "Nitroglicerina", do: "5–200 mcg/min", via: "IV", o: "EAP, SCA, insuficiência coronariana." },
    { etapa:"escala", d: "Esmolol", do: "Bolus 500 mcg/kg + 50–200 mcg/kg/min", via: "IV", o: "Dissecção aórtica (sempre antes de vasodilatador), SCA, taquiarritmia." },
    { etapa:"escala", d: "Hidralazina", do: "5–10 mg IV", via: "IV", o: "Pré-eclâmpsia/eclâmpsia. Pode causar taquicardia reflexa." },
    { etapa:"escala", d: "Captopril", do: "25 mg VO/SL", via: "VO/SL", o: "Urgência hipertensiva (sem LOA aguda). NÃO é emergência — reduz em horas, não minutos." },
  ],
  alertas: [
    { t: "crit", x: "AVC isquêmico: NÃO reduzir PA agressivamente. Só tratar se >220×120 (sem trombólise) ou >185×110 (com trombólise). Reduzir 15% nas primeiras 24h." },
    { t: "crit", x: "Dissecção aórtica: PAS alvo 100–120 e FC <60 com β-bloqueador ANTES do vasodilatador (evitar taquicardia reflexa = ↑estresse de cisalhamento)." },
    { t: "warn", x: "Urgência hipertensiva NÃO requer redução em minutos. Tratamento VO em algumas horas. Reduzir muito rápido = risco de isquemia." },
  ],
  fisio: "A crise hipertensiva é o resultado de uma elevação aguda da PA que excede a capacidade de autorregulação dos órgãos-alvo. Em pacientes não hipertensos crônicos, valores ≥180×120 podem causar dano; em hipertensos crônicos, a curva de autorregulação está deslocada para a direita e tolera valores mais altos. A <strong>encefalopatia hipertensiva</strong> ocorre quando há falência da autorregulação cerebral → hiperperfusão → edema vasogênico. Na <strong>nefroesclerose maligna</strong>, há necrose fibrinoide das arteríolas → microangiopatia trombótica + IRA. Na dissecção aórtica, o ↑estresse de cisalhamento (dP/dt) propaga o flap intimal.",
  mec: [
    { d: "Nitroprussiato", x: "Sofre redução intracelular (eritrócitos, células endoteliais) <strong>liberando NO e ânion cianeto</strong>. O NO ativa guanilato ciclase → ↑GMPc → relaxamento muscular liso (arterial + venoso balanceado). Início <1 min, duração 1–10 min. Tiocianato (metabólito) acumula em IRC e pode causar toxicidade neurológica em uso >24–48h." },
    { d: "Esmolol", x: "β1-cardiosseletivo ultracurto — degradado por <strong>esterases plasmáticas</strong> (T½ ~9 min). Ideal para situações que requerem titulação rápida (dissecção, perioperatório)." },
    { d: "Hidralazina", x: "Vasodilatador arteriolar direto (mecanismo não totalmente elucidado, possivelmente ↑NO endotelial). Pode causar taquicardia reflexa e síndrome lupus-like." },
    { d: "Captopril", x: "Inibidor da ECA — ↓conversão de angiotensina I em angiotensina II → vasodilatação + ↓aldosterona. Início VO 15–30 min." },
  ],
  diretriz: "Diretrizes Brasileiras de Hipertensão Arterial 2020 (Barroso WKS et al., SBC, Arq Bras Cardiol 2021;116:516–658, DOI:10.36660/abc.20201238). Posicionamento Luso-Brasileiro de Emergências Hipertensivas 2020.",
  fluxo: null,
  calcs: [],
},
{
  id: "dissec", sis: "cardio", grav: "alta",
  nome: "Dissecção Aórtica",
  sin: ["dissecção", "dissecção de aorta", "Stanford A", "Stanford B"],
  def: "Dor torácica/dorsal súbita, em \"rasgo\", máxima desde o início, com diferença de PA entre membros >20 mmHg ou pulsos assimétricos. Stanford A: aorta ascendente (cirúrgica). B: distal à subclávia esquerda.",
  exames: ["Angio-TC de tórax e abdome com contraste (PADRÃO-OURO)", "ECG (excluir IAM, mas pode haver isquemia coronária)", "RX tórax (mediastino alargado em 60%)", "Eco TT/TE", "Hemograma, função renal, lactato", "D-dímero (alto VPN se <500)"],
  rx: [
    { etapa:"escala", d: "Esmolol", do: "Bolus 500 mcg/kg + 50–200 mcg/kg/min", via: "IV", o: "PRIMEIRO. Alvo FC <60. Alternativa: metoprolol 5 mg IV." },
    { etapa:"escala", d: "Nitroprussiato", do: "0,25–10 mcg/kg/min", via: "IV", o: "Após β-bloqueador. Alvo PAS 100–120 mmHg." },
    { etapa:"escala", d: "Morfina", do: "2–4 mg IV", via: "IV", o: "Controle da dor (↓descarga adrenérgica)." },
  ],
  alertas: [
    { t: "crit", x: "Stanford A: cirurgia URGENTE. Mortalidade 1% por hora nas primeiras 48h sem cirurgia." },
    { t: "crit", x: "SEMPRE β-bloqueador ANTES de vasodilatador — vasodilatador isolado causa taquicardia reflexa que ↑dP/dt e propaga dissecção." },
    { t: "warn", x: "Pode mimetizar IAM (extensão para ostios coronários, mais comum em coronária direita). Sempre checar pulsos, dor migratória, RX." },
  ],
  fisio: "A dissecção aórtica inicia-se por um <strong>rasgo na íntima</strong> (causa hipertensão crônica em 70%, Marfan, Ehlers-Danlos, bicúspide, gravidez, trauma, cocaína). O sangue penetra a camada média e propaga-se anterógrada ou retrogradamente, criando um <strong>falso lúmen</strong> separado por flap intimal. A força que propaga a dissecção é o <strong>estresse de cisalhamento (dP/dt)</strong> — dependente da pressão e da força de contração. Por isso, o objetivo terapêutico é <strong>reduzir simultaneamente PA E FC</strong>: β-bloqueador primeiro (evita taquicardia reflexa que ↑dP/dt) e depois vasodilatador. Complicações: ruptura para pericárdio (tamponamento), insuficiência aórtica, isquemia visceral, hemotórax, AVC.",
  mec: [
    { d: "Esmolol", x: "β1-cardiosseletivo ultracurto (T½ 9 min). ↓FC, ↓contratilidade, ↓dP/dt aórtica. Reversibilidade rápida em caso de hipotensão." },
    { d: "Nitroprussiato", x: "Vasodilatação balanceada via NO/GMPc. Reduz pós-carga e PA." },
  ],
  diretriz: "2022 ACC/AHA Guideline for the Diagnosis and Management of Aortic Disease (Isselbacher EM et al., Circulation 2022;146:e334–e482, DOI:10.1161/CIR.0000000000001106). Diretriz SBC de Doença Aórtica 2021.",
  fluxo: null,
  calcs: [],
},
{
  id: "tep", sis: "cardio", grav: "alta",
  nome: "TVP / Tromboembolismo Pulmonar (TEP)",
  sin: ["TVP", "trombose", "TEP", "embolia pulmonar", "tromboembolismo"],
  def: "TVP: dor/edema unilateral de MMII, Wells ≥2. TEP: dispneia, dor torácica pleurítica, taquicardia, ± hipotensão. Alta mortalidade no TEP maciço (>50% se choque + RV dilatado).",
  exames: ["Wells / sPESI / PERC", "D-dímero (alto VPN; usar em baixa probabilidade)", "Angio-TC pulmonar (padrão-ouro)", "USG Doppler venoso de MMII", "ECG (S1Q3T3, taquicardia)", "Eco TT (sobrecarga VD)", "Troponina + BNP (estratificação)"],
  rx: [
    {etapa:"inicial", d:"Estratificação de risco — Wells/PERC/Geneva",do:"Probabilidade pré-teste",via:"—",o:"Baixa+PERC negativo: exclui. Baixa-moderada: D-dímero. Alta: angio-TC direto."},
    {etapa:"inicial", d:"O₂ se SpO₂ <92%",do:"Cateter/máscara conforme",via:"—",o:"Suporte ventilatório se grave (HFNC, VNI, IOT)."},
    {etapa:"inicial", d:"Acesso + monitorização",do:"2 acessos + ECG + SpO₂ + PA",via:"—",o:"Em TEP maciço: monitorização contínua, considerar PA invasiva."},
    {etapa:"escala", d:"① Anticoagulação — Enoxaparina (estável)",do:"1 mg/kg SC 12/12h OU 1,5 mg/kg/d",via:"SC",o:"1ª linha em TVP/TEP estável. ClCr 15-30: 1 mg/kg/d. CI: ClCr <15."},
    {etapa:"escala", d:"① Anticoagulação — HNF (instável, IRC, trombólise iminente)",do:"80 UI/kg bolus + 18 UI/kg/h BIC",via:"IV",o:"Manter aPTT 1,5-2,5× controle. Indicação: TEP maciço, IRC grave (ClCr<30), trombólise iminente, instabilidade."},
    {etapa:"escala", d:"① Anticoagulação — Rivaroxabana VO (alternativa)",do:"15 mg 12/12h × 21 dias, depois 20 mg/d",via:"VO",o:"Dose única (sem ponte com heparina). Tomar com alimento >10 mg."},
    {etapa:"escala", d:"① Anticoagulação — Apixabana VO (alternativa)",do:"10 mg 12/12h × 7 dias, depois 5 mg 12/12h",via:"VO",o:"Sem ponte com heparina. Alternativa principal a rivaroxabana."},
    {etapa:"escala", d:"② TROMBÓLISE — Alteplase (TEP MACIÇO)",do:"100 mg IV em 2h (10 mg bolus + 90 mg em 2h). PCR: 0,6 mg/kg em 15 min",via:"IV",o:"INDICAÇÃO: TEP maciço (choque/PAS <90 sustentado). Mortalidade SEM trombólise 25-50%. CI: AVC isquêmico <3m, AVCh, trauma SNC, sangramento ativo."},
    {etapa:"escala", d:"③ TROMBECTOMIA (se trombólise CI ou falha)",do:"Cirúrgica ou cateter-direcionada",via:"—",o:"TEP maciço com CI a trombólise ou falência apesar da trombólise. Centro especializado."},
    {etapa:"adj", d:"Suporte hemodinâmico se choque",do:"Noradrenalina + cristaloide cauteloso (250-500 mL)",via:"IV",o:"Cuidado com volume excessivo — pode piorar disfunção de VD. Noradrenalina preferível."},
    {etapa:"adj", d:"Filtro de VCI (indicações específicas)",do:"Indicação restrita",via:"—",o:"Apenas se CI absoluta à anticoagulação OU TEP recorrente apesar de anticoagulação plena."},
    {etapa:"alta", d:"Anticoagulação prolongada",do:"≥3 meses (provocado) ou indefinido (não provocado, trombofilia, câncer)",via:"VO",o:"Reavaliação anual. Considerar HEMORR2HAGES/HAS-BLED para risco hemorrágico."},
  ],
  alertas: [
    { t: "crit", x: "TEP maciço (choque/PAS <90 sustentado): trombólise sistêmica é classe I. Mortalidade sem trombólise 25–50%." },
    { t: "warn", x: "Trombólise: CI absolutas — AVC isquêmico <3m, AVC hemorrágico em qualquer momento, trauma SNC, neoplasia SNC, sangramento ativo." },
    { t: "info", x: "Anticoagulação por ≥3 meses; estender se causa não identificada ou trombofilia." },
  ],
  fisio: "A formação de trombo venoso segue a tríade de Virchow: <strong>estase, lesão endotelial e hipercoagulabilidade</strong> (pós-operatório, imobilização, gravidez, neoplasia, contraceptivos, trombofilias). O trombo formado em veias profundas dos MMII embolia para artéria pulmonar via VCI + AD + VD. A obstrução do leito vascular pulmonar gera (1) <strong>distúrbio V/Q</strong> com hipoxemia, (2) <strong>hipertensão pulmonar aguda</strong> e sobrecarga de VD, podendo evoluir para falência ventricular direita aguda e choque obstrutivo. A liberação de mediadores (serotonina, tromboxano) causa broncoespasmo e vasoconstrição adicional. Mortalidade do TEP não tratado: 30%; tratado: 2–8%.",
  mec: [
    { d: "Heparina (HNF)", x: "Liga-se à antitrombina III ativando-a 1000×; o complexo inativa <strong>fatores IIa (trombina) e Xa</strong> proporcionalmente. Monitorada por aPTT. Reversão: protamina." },
    { d: "Enoxaparina (HBPM)", x: "Cadeia menor — maior <strong>seletividade anti-Xa</strong> (3:1 vs. anti-IIa). Farmacocinética previsível, sem necessidade de monitorização rotineira (exceto IRC, obeso). Reversão parcial: protamina (~60%)." },
    { d: "Rivaroxabana / Apixabana", x: "Inibidores diretos do fator Xa (sem necessidade de antitrombina). Bloqueiam conversão de protrombina em trombina. Reversão específica: andexanet alfa." },
    { d: "Alteplase (rt-PA)", x: "Ativador tecidual do plasminogênio recombinante — ativa plasminogênio em plasmina, que <strong>degrada fibrina</strong> do trombo." },
  ],
  diretriz: "2019 ESC Guidelines for the diagnosis and management of acute pulmonary embolism (Konstantinides SV et al., Eur Heart J 2020;41:543–603, DOI:10.1093/eurheartj/ehz405). ASH 2020 VTE guidelines.",
  fluxo: null,
  calcs: ["wells-tep", "wells-tvp", "pesi"],
},

/* ============== NEURO ============== */
{
  id: "cefaleia", sis: "neuro", grav: "baixa",
  nome: "Cefaleia (primária)",
  sin: ["cefaleia", "dor de cabeça", "tensional"],
  def: "Cefaleia sem sinais de alarme (sem início súbito, sem febre, sem déficit, sem trauma, sem alteração de consciência). Tensional é a mais comum.",
  exames: ["Anamnese e exame neurológico completo", "TC crânio se sinais de alarme (SNOOP10)", "PL se suspeita de meningite ou HSA com TC normal"],
  rx: [
    { etapa:"escala", d: "Dipirona", do: "1 g IV ou 500–1000 mg VO 6/6h", via: "IV/VO", o: "1ª linha. Diluir em SF e administrar lento (raro choque)." },
    { etapa:"escala", d: "Paracetamol", do: "750–1000 mg VO 6/6h", via: "VO", o: "Alternativa. Máx 4 g/24h." },
    { etapa:"escala", d: "Ibuprofeno", do: "400–600 mg VO 8/8h", via: "VO", o: "AINE de 1ª escolha por perfil GI." },
    { etapa:"escala", d: "Cetorolaco", do: "30 mg IV/IM 6/6h", via: "IV/IM", o: "Refratário. Máx 5 dias." },
  ],
  alertas: [
    { t: "crit", x: "Sinais de alarme (SNOOP10): início súbito (\"pior cefaleia da vida\"), febre, sintomas neurológicos, idade >50, mudança de padrão, posicional, trauma, papiledema, imunossupressão, gestação. Investigar." },
  ],
  fisio: "A <strong>cefaleia tensional</strong> tem etiologia multifatorial: tensão musculo-esquelética cervical/pericraniana, sensibilização central da via trigeminocervical, estresse. A dor é descrita como aperto bilateral, leve a moderada, sem náuseas/fotofobia significativas, sem piora aos esforços. Geralmente responde bem a analgésicos comuns. Cefaleia <strong>medicamentosa</strong> (rebote) é frequente em uso >15 dias/mês de analgésicos.",
  mec: [
    { d: "Dipirona (metamizol)", x: "Inibe <strong>COX-3 central</strong> e modula o sistema endocanabinoide; ação analgésica/antipirética sem ação anti-inflamatória periférica significativa." },
    { d: "Paracetamol", x: "Inibe predominantemente <strong>COX-2 no SNC</strong>; analgésico/antipirético. Toxicidade hepática em sobredose (NAPQI)." },
    { d: "Ibuprofeno", x: "AINE não-seletivo — inibe COX-1 e COX-2, reduzindo síntese de prostaglandinas pró-inflamatórias e nociceptivas." },
  ],
  diretriz: "Diretrizes para Tratamento da Crise Migranosa SBCe 2018 (Vincent MB et al.). International Classification of Headache Disorders ICHD-3.",
  fluxo: null,
  calcs: [],
},
{
  id: "migranea", sis: "neuro", grav: "media",
  nome: "Crise Migranosa (Enxaqueca)",
  sin: ["enxaqueca", "migrânea", "migraine"],
  def: "Cefaleia unilateral, pulsátil, moderada-grave, com fotofobia/fonofobia e/ou náuseas/vômitos, piora com atividade. ± aura visual/sensitiva.",
  exames: ["Anamnese (ICHD-3)", "Excluir sinais de alarme", "TC se atípica/persistente"],
  rx: [
    { etapa:"adj", d: "Dipirona", do: "1 g IV em SF 100 mL", via: "IV", o: "1ª linha em PS. Pode associar a antiemético." },
    { etapa:"escala", d: "Cetoprofeno", do: "100 mg IV em 100 mL SF", via: "IV", o: "Alternativa AINE." },
    { etapa:"adj", d: "Metoclopramida", do: "10 mg IV em 100 mL SF lento", via: "IV", o: "Antiemético + ação central na enxaqueca. Pode causar distonia." },
    { etapa:"escala", d: "Sumatriptano", do: "6 mg SC ou 50–100 mg VO ou 20 mg intranasal", via: "SC/VO/IN", o: "Repetir após 2h se necessário (máx 200 mg/d VO). CI: coronariopatia, AVC, HAS não controlada, ergotamina <24h." },
    { etapa:"escala", d: "Clorpromazina", do: "12,5–25 mg IV em 100 mL SF lento", via: "IV", o: "Refratário. Risco de hipotensão e distonia. Hidratar antes." },
    { etapa:"adj", d: "Dexametasona", do: "10 mg IV", via: "IV", o: "Reduz recorrência em 24–72h. Considerar em todos com crise grave/prolongada." },
  ],
  alertas: [
    { t: "warn", x: "Triptanos: CI em coronariopatia, AVC, HAS não controlada, hemiplégica/basilar, gestação." },
    { t: "info", x: "Opioides são UM dos PIORES tratamentos para enxaqueca — risco de cronificação, sem evidência de superioridade. Evitar." },
  ],
  fisio: "A enxaqueca decorre da ativação do <strong>sistema trigêmino-vascular</strong>: estímulos no córtex/tronco encefálico ativam neurônios trigeminais → liberação de neuropeptídios pró-inflamatórios (CGRP, substância P, neurocinina A) nos vasos meníngeos → <strong>vasodilatação meníngea + inflamação neurogênica estéril</strong> + sensibilização periférica e central. A aura é causada por <strong>depressão cortical alastrante</strong> (onda de despolarização que se propaga pelo córtex a 3–5 mm/min, com hiperexcitação seguida de inibição). A teoria mais atual coloca a hiperexcitabilidade neuronal e os canais de Ca²⁺ como centrais à fisiopatologia.",
  mec: [
    { d: "Sumatriptano (e outros triptanos)", x: "Agonistas seletivos dos receptores <strong>5-HT1B (vasoconstrição craniana) e 5-HT1D (↓liberação de neuropeptídios pré-sinapticamente)</strong>. Revertem a vasodilatação meníngea e a inflamação neurogênica." },
    { d: "Metoclopramida", x: "<strong>Antagonista D2</strong> central — reduz a dor migranosa por mecanismo dopaminérgico além do efeito antiemético. Também agonista 5-HT4 (procinético)." },
    { d: "Clorpromazina", x: "Antipsicótico típico, antagonista D2/D1 + bloqueio α1 + anti-H1; eficácia comparável a triptanos em PS. Risco de hipotensão." },
    { d: "Dexametasona", x: "Glicocorticoide — reduz inflamação neurogênica e previne recorrência precoce." },
  ],
  diretriz: "Protocolo Brasileiro de Tratamento da Crise de Migrânea (Sociedade Brasileira de Cefaleia 2022). AHS Consensus 2021 (Ailani J et al., Headache 2021).",
  fluxo: null,
  calcs: [],
},
{
  id: "vertigem", sis: "neuro", grav: "baixa",
  nome: "Vertigem",
  sin: ["vertigem", "tontura", "VPPB", "labirintite"],
  def: "Sensação ilusória de movimento. Periférica: rotatória, intensa, com náuseas/sudorese, melhora ao fixar olhar, nistagmo unidirecional/horizontal. Central: pior, com déficit focal, nistagmo vertical/multidirecional.",
  exames: ["Exame neurológico completo", "HINTS (Head Impulse, Nystagmus, Test of Skew)", "Manobra de Dix-Hallpike (VPPB)", "TC ou RM se central"],
  rx: [
    { etapa:"escala", d: "Dimenidrato", do: "50–100 mg IV ou 50 mg VO 6/6h", via: "IV/VO", o: "1ª linha em vertigem aguda periférica. Sonolência." },
    { etapa:"escala", d: "Meclozina", do: "25–50 mg VO 8/8h", via: "VO", o: "Alternativa, menos sedativa." },
    { etapa:"escala", d: "Cinarizina", do: "25 mg VO 8/8h", via: "VO", o: "Pode causar SEP em uso prolongado." },
    { etapa:"adj", d: "Metoclopramida", do: "10 mg IV/IM", via: "IV/IM", o: "Antiemético." },
    { etapa:"escala", d: "Manobra de Epley", do: "Reposicionamento canalicular", via: "—", o: "1ª linha em VPPB do canal posterior." },
  ],
  alertas: [
    { t: "warn", x: "HINTS sugestivo de central (impulso negativo + nistagmo direção-mutável + skew deviation) → AVC cerebelar/tronco. Imagem URGENTE." },
  ],
  fisio: "A vertigem periférica decorre de disfunção do <strong>aparelho vestibular</strong> (labirinto, nervo vestibular): <strong>VPPB</strong> (otólitos deslocados em canais semicirculares — 50% dos casos), <strong>neurite vestibular</strong> (provavelmente viral), <strong>doença de Ménière</strong> (hidropsia endolinfática). A vertigem central decorre de lesão de núcleos vestibulares ou cerebelo (AVC, EM, tumor). A distinção é crucial: AVC cerebelar pode mimetizar neurite e tem indicação de imagem urgente.",
  mec: [
    { d: "Dimenidrato / Meclozina", x: "<strong>Antagonistas H1 + anticolinérgicos centrais</strong> — suprimem a transmissão no núcleo vestibular e zona quimiorreceptora gatilho. Eficazes mas sedativos." },
    { d: "Cinarizina", x: "Bloqueador de canais de Ca²⁺ vestibulares + antagonismo H1; ação \"calmante labiríntico\". Pode causar SEP." },
  ],
  diretriz: "Bárány Society — Classification of Vestibular Disorders (Bisdorff A et al., J Vestib Res 2009;19:1–13).",
  fluxo: null,
  calcs: [],
},
{
  id: "avci", sis: "neuro", grav: "alta",
  nome: "AVC Isquêmico Agudo / Trombólise",
  sin: ["AVC", "AVCI", "derrame", "stroke", "trombólise"],
  def: "Déficit neurológico focal súbito + neuroimagem sem hemorragia. NIHSS quantifica gravidade. Janela para trombólise IV: 4,5h. Trombectomia: até 24h em casos selecionados.",
  exames: ["NIHSS", "TC crânio sem contraste (ASPECTS) — primeira imagem", "Glicemia capilar (descartar hipoglicemia)", "Coagulograma, plaquetas, função renal", "Angio-TC se candidato a trombectomia", "RM se janela estendida/wake-up stroke (mismatch DWI/FLAIR)"],
  rx: [
    {etapa:"inicial", d:"GLICEMIA capilar IMEDIATA",do:"Excluir hipoglicemia (mimic)",via:"—",o:"Hipoglicemia <50: corrigir antes — pode resolver completamente o quadro. Hiperglicemia >180 aumenta risco hemorragia pós-trombólise."},
    {etapa:"inicial", d:"NIHSS + tempo de início",do:"Aplicar NIHSS + LSW (Last Seen Well)",via:"—",o:"NIHSS quantifica gravidade. LSW = última vez bem documentada. CRÍTICO para janela terapêutica."},
    {etapa:"inicial", d:"TC crânio sem contraste IMEDIATA",do:"≤25 min porta-TC, ≤45 min interpretação",via:"—",o:"Excluir hemorragia. Calcular ASPECTS. Achados precoces de isquemia."},
    {etapa:"inicial", d:"Acessos + monitorização + PA",do:"2 acessos, sem retirar sangue para INR (atrasa)",via:"—",o:"Trombólise pode iniciar SEM aguardar INR/coagulograma se sem suspeita de coagulopatia."},
    {etapa:"escala", d:"① Controle PA pré-trombólise",do:"Alvo PAS <185/PAD <110",via:"IV",o:"Labetalol 10-20 mg IV bolus OU Nitroprussiato 0,25-10 mcg/kg/min. NÃO trombolisar se PA não controlada."},
    {etapa:"escala", d:"② TROMBÓLISE — Alteplase",do:"0,9 mg/kg IV (máx 90 mg) — 10% em bolus 1 min + 90% em 60 min",via:"IV",o:"Em até 4,5h do início. Critérios rigorosos inclusão/exclusão. Padrão SUS."},
    {etapa:"escala", d:"② TROMBÓLISE — Tenecteplase (alternativa)",do:"0,25 mg/kg IV bolus único (máx 25 mg)",via:"IV",o:"AHA/ASA 2025 classe I, alternativa à alteplase em janela ≤4,5h. Bolus único, mais prática. Disponibilidade variável SUS."},
    {etapa:"escala", d:"③ TROMBECTOMIA mecânica",do:"Janela ≤6h (todos) ou 6-24h com mismatch (DAWN/DEFUSE-3)",via:"—",o:"Oclusão de grande vaso (LVO: M1, ACI). ASPECTS ≥6. NIHSS ≥6. Acionar centro de AVC IMEDIATAMENTE."},
    {etapa:"adj", d:"Controle PA pós-trombólise",do:"Alvo PA <180/105 por 24h",via:"IV",o:"Monitorizar 15/15 min × 2h, depois 30/30 min × 6h, depois 1/1h × 16h."},
    {etapa:"adj", d:"NÃO antiagregar nas 1ªs 24h pós-trombólise",do:"Risco de hemorragia",via:"—",o:"Reavaliar TC em 24h antes de iniciar AAS. Se sem hemorragia: AAS 300 mg dose única."},
    {etapa:"escala", d:"AAS (sem trombólise ou após 24h)",do:"300 mg VO/SNG dose única + 100 mg/d",via:"VO",o:"Sem trombólise: iniciar imediato. Pós-trombólise: aguardar 24h + TC controle."},
    {etapa:"adj", d:"Atorvastatina",do:"80 mg VO/d",via:"VO",o:"Iniciar em 24-48h. Indicação independente do LDL."},
    {etapa:"alta", d:"Investigação etiológica",do:"Eco TT/TE, Doppler carótidas, Holter, perfil lipídico, HbA1c",via:"—",o:"Definir etiologia (cardioembólica, aterotrombótica, lacunar, criptogênico). Prevenção secundária guiada."},
    {etapa:"alta", d:"Reabilitação precoce",do:"Fisio, fono, TO em 24-48h se estável",via:"—",o:"Reduz incapacidade. Disfagia: avaliação fono antes de VO."},
  ],
  alertas: [
    { t: "crit", x: "CI absolutas à trombólise: AVC/TCE <3m, hemorragia ativa, plaquetas <100k, INR >1,7, glicose <50 ou >400, PA >185×110 não controlada, neoplasia/MAV SNC, endocardite, dissecção aórtica." },
    { t: "warn", x: "Trombectomia mecânica: oclusão de grande vaso (LVO) + janela ≤6h (todos) ou 6–24h com mismatch perfusional. ASPECTS ≥6 preferencial." },
    { t: "info", x: "Não tratar hipoglicemia simulando AVC. Sempre HGT na chegada." },
  ],
  fisio: "A oclusão arterial cerebral interrompe o suprimento de O₂/glicose. Forma-se uma <strong>zona central de infarto irreversível</strong> rodeada de <strong>penumbra isquêmica</strong> — tecido hipoperfundido mas ainda viável que pode ser salvo se reperfundido em tempo hábil. \"Time is brain\": cada minuto perdido = 1,9 milhão de neurônios mortos. A trombólise IV dissolve o trombo restaurando o fluxo; a trombectomia mecânica remove fisicamente o coágulo em oclusões de grande vaso, com benefício extraordinário (NNT 2,6 para incapacidade reduzida). A AHA/ASA 2026 endossou tenecteplase 0,25 mg/kg como classe I (alternativa à alteplase em janela ≤4,5h), por farmacocinética superior (bolus único).",
  mec: [
    { d: "Alteplase (rt-PA)", x: "Ativador tecidual do plasminogênio recombinante — converte plasminogênio circulante em <strong>plasmina, que degrada fibrina</strong> do trombo. Meia-vida 4–5 min." },
    { d: "Tenecteplase", x: "rt-PA modificado geneticamente (3 mutações) — maior fibrinoespecificidade, resistência ao PAI-1 e meia-vida prolongada (~20 min), permitindo bolus único." },
    { d: "AAS", x: "Inibe COX-1 plaquetária irreversivelmente — bloqueia tromboxano A2 e agregação." },
  ],
  diretriz: "AHA/ASA 2025 Guideline for the Management of Patients With Acute Ischemic Stroke (Powers WJ et al., 2025 update; DOI:10.1161/STR.0000000000000513). Linha de Cuidado em AVC, Ministério da Saúde (Portaria GM/MS 4.129/2024). PCDT MS Brasil 2021 (recomenda apenas alteplase em SUS).",
  imgs: [
    {src:"https://upload.wikimedia.org/wikipedia/commons/4/49/MCA_Territory_Infarct.svg",
     alt:"TC de crânio com hipoatenuação em território de ACM",
     caption:"Infarto extenso em território da artéria cerebral média esquerda — hipoatenuação cortical e apagamento dos sulcos.",
     source:"Wikimedia Commons / Lucien Monfils (CC BY-SA 3.0)"},
  ],
  fluxo: "avci",
  calcs: ["nihss"],
},
{
  id: "bell", sis: "neuro", grav: "baixa",
  nome: "Paralisia de Bell",
  sin: ["Bell", "paralisia facial", "paralisia facial periférica"],
  def: "Paralisia facial periférica unilateral aguda, idiopática, com envolvimento DA TESTA (House-Brackmann II–VI). Inicio em 72h, geralmente associada a infecção viral.",
  exames: ["Exame neurológico (excluir AVC: testa preservada na central!)", "Otoscopia (Ramsay Hunt: vesículas + dor)", "Glicemia, A1c", "Sorologia herpes/Lyme se suspeita"],
  rx: [
    { etapa:"escala", d: "Prednisona", do: "60 mg/d × 5 dias + desmame em 5 dias", via: "VO", o: "Iniciar nas primeiras 72h. Aumenta chance de recuperação completa." },
    { etapa:"atb", d: "Aciclovir", do: "400 mg VO 5×/d × 10 dias", via: "VO", o: "Em casos graves ou Ramsay Hunt — benefício controverso isolado, mas usado com corticoide." },
    { etapa:"atb", d: "Valaciclovir", do: "1 g VO 8/8h × 7 dias", via: "VO", o: "Alternativa." },
    { etapa:"escala", d: "Lubrificação ocular", do: "Lágrima artificial + curativo oclusivo noturno", via: "Tópico", o: "FUNDAMENTAL para evitar úlcera de córnea." },
  ],
  alertas: [
    { t: "warn", x: "Se TESTA preservada → central (AVC). Investigar imagem." },
    { t: "info", x: "Recuperação em 70–80% em 3 meses. Pior prognóstico se completa, idade avançada, DM, HAS." },
  ],
  fisio: "A causa mais provável é a <strong>reativação do HSV-1 no gânglio geniculado</strong>, causando inflamação e edema do nervo facial no canal estreito do osso temporal → compressão e bloqueio de condução. Outras causas: HHV-6, Borrelia (Lyme), HIV, sarcoidose. Característica fundamental para diferenciar de AVC: a paralisia periférica acomete TODA a hemiface (incluindo a testa), enquanto o AVC poupa a testa (inervação cortical bilateral da porção superior do núcleo facial).",
  mec: [
    { d: "Prednisona", x: "Glicocorticoide — <strong>reduz edema neural</strong> e inflamação no canal facial. O benefício na recuperação é dose- e tempo-dependente (NNT ~10–12 para recuperação completa)." },
    { d: "Aciclovir / Valaciclovir", x: "Antivirais nucleosídeos — fosforilados pela timidina-quinase viral em monofosfato, depois trifosfato → inibem a <strong>DNA-polimerase viral</strong>." },
  ],
  diretriz: "AAN Practice Guideline Update: Steroids and Antivirals for Bell Palsy (Gronseth GS, Paduga R, Neurology 2012;79:2209–2213).",
  fluxo: null,
  calcs: [],
},
{
  id: "crise", sis: "neuro", grav: "alta",
  nome: "Crise Convulsiva / Estado de Mal Epiléptico",
  sin: ["convulsão", "crise", "EME", "status epilepticus", "epilepsia"],
  def: "Crise convulsiva única autolimitada vs. EME: crise ≥5 min OU crises recorrentes sem recuperação de consciência (ABNeuro/ILAE).",
  exames: ["HGT", "Eletrólitos (Na, Ca, Mg)", "Função renal e hepática", "Hemograma", "Toxicológico", "β-HCG", "Nível sérico de anticonvulsivantes (se em uso)", "TC crânio (1ª crise, focal, déficit, trauma)", "PL se febre/imunossupressão"],
  rx: [
    {etapa:"inicial", d:"PROTEGER + lateralizar + O₂",do:"Cabeceira lateral, retirar objetos, O₂ máscara",via:"—",o:"NÃO conter o paciente. NÃO colocar nada na boca. Cronometrar a crise."},
    {etapa:"inicial", d:"HGT capilar IMEDIATA",do:"Excluir hipoglicemia (mimic frequente)",via:"—",o:"Glicemia <50: Glicose 50% 50 mL IV (após tiamina se etilista)."},
    {etapa:"inicial", d:"Tiamina 100 mg IV antes de glicose",do:"Se etilista, desnutrido, gestante",via:"IV",o:"Previne encefalopatia de Wernicke. EMERGÊNCIA — não atrasa BZD."},
    {etapa:"inicial", d:"Acesso venoso + monitor",do:"2 acessos + ECG + SpO2",via:"—",o:"Acesso difícil em crise — considerar via IO. Coletar exames simultâneo."},
    {etapa:"escala", d:"① BZD — Diazepam IV (acesso disponível)",do:"10 mg IV bolus, repetir até 3×",via:"IV",o:"1ª linha. Em <5 min do início. Cuidado depressão respiratória."},
    {etapa:"escala", d:"① BZD — Midazolam IM (sem acesso IV)",do:"10 mg IM (>40kg) ou 0,2 mg/kg IM/intranasal/bucal",via:"IM/IN",o:"Estudo RAMPART: tão eficaz quanto IV. Início rápido. Sem acesso = via preferida."},
    {etapa:"escala", d:"① BZD — Lorazepam (alternativa preferida)",do:"4 mg IV diluído 1:1",via:"IV",o:"Menor recidiva que diazepam. Onde disponível, preferir."},
    {etapa:"escala", d:"② Anticonvulsivante de 2ª linha — Fenitoína",do:"20 mg/kg IV em SF 0,9% a 50 mg/min",via:"IV",o:"Após BZD se persiste. Monitor cardíaco (bradicardia, hipotensão). Adicional 5-10 mg/kg se ainda persistir."},
    {etapa:"escala", d:"② Anticonvulsivante — Levetiracetam (alternativa)",do:"60 mg/kg IV em 15 min (máx 4,5 g)",via:"IV",o:"ESETT trial: equivalente a fenitoína. Melhor perfil de segurança — preferir em cardiopata."},
    {etapa:"escala", d:"② Anticonvulsivante — Valproato (alternativa)",do:"40 mg/kg IV (máx 3 g)",via:"IV",o:"Útil em generalizadas. CI: hepatopata, gestante (teratogênico)."},
    {etapa:"escala", d:"③ EME refratário (>30 min) — IOT + anestésico",do:"Midazolam 0,2 mg/kg bolus + 0,1-2 mg/kg/h BIC OU Propofol 1-2 mg/kg + 30-200 mcg/kg/min",via:"IV",o:"Preparar IOT. EEG contínuo. UTI."},
    {etapa:"escala", d:"③ EME refratário — Fenobarbital alternativo",do:"15-20 mg/kg IV em 50 mg/min",via:"IV",o:"3ª linha. Depressão respiratória — IOT obrigatória."},
    {etapa:"escala", d:"④ EME super-refratário (>24h)",do:"Coma barbitúrico — Tiopental ou Pentobarbital",via:"IV",o:"UTI com EEG contínuo. Cetamina, lidocaína IV alternativas em estudos."},
    {etapa:"adj", d:"Investigação etiológica",do:"TC, RM, LP se febre, EEG, toxicológico",via:"—",o:"1ª crise sem causa óbvia: TC + considerar PL. Etilista: pensar em abstinência. Gestante: eclâmpsia → MgSO4."},
    {etapa:"alta", d:"Manutenção anticonvulsivante VO",do:"Conforme tipo de crise + neurologista",via:"VO",o:"Crise primária sem causa: discutir início. Causa estrutural ou EME: manutenção indicada."},
  ],
  alertas: [
    { t: "crit", x: "EME super-refratário (>24h): coma barbitúrico com tiopental ou pentobarbital." },
    { t: "warn", x: "SEMPRE tiamina 100 mg IV ANTES de glicose em etilistas/desnutridos (prevenir Wernicke)." },
    { t: "info", x: "Crise primeira sem alterações: investigar ambulatorialmente. Crise com déficit, idade >40, ou alteração estrutural: TC + RM + EEG." },
  ],
  fisio: "Uma crise convulsiva é resultado de uma <strong>descarga neuronal hipersíncrona</strong> excessiva — desequilíbrio entre excitação (glutamato/NMDA/AMPA) e inibição (GABA). Causas: epilepsia primária, suspensão de anticonvulsivante, tumor, AVC, TCE, infecção SNC, drogas/abstinência, distúrbios metabólicos (hipoglicemia, hiponatremia, hipocalcemia, uremia, eclâmpsia), hipertermia. No EME, ocorre <strong>internalização de receptores GABA-A</strong> e <strong>upregulação de NMDA</strong> → resistência progressiva a benzodiazepínicos com o passar do tempo. Por isso o tratamento agressivo nos primeiros 5–30 min é fundamental.",
  mec: [
    { d: "Diazepam / Midazolam / Lorazepam", x: "Agonistas alostéricos positivos do <strong>sítio benzodiazepínico do receptor GABA-A</strong>. ↑frequência de abertura do canal de Cl⁻ → hiperpolarização → inibição neuronal." },
    { d: "Fenitoína", x: "Bloqueia <strong>canais de Na⁺ voltagem-dependentes em estado inativo</strong>, prevenindo despolarização repetitiva de alta frequência." },
    { d: "Levetiracetam", x: "Liga-se à <strong>SV2A (proteína da vesícula sináptica)</strong> — modula liberação de neurotransmissores. Mecanismo único; perfil de segurança superior." },
    { d: "Valproato", x: "Múltiplos: ↑GABA, bloqueio Na⁺/Ca²⁺, modulação canais T." },
    { d: "Fenobarbital", x: "Agonista alostérico positivo do sítio barbitúrico do <strong>GABA-A — ↑duração de abertura do canal de Cl⁻</strong>." },
    { d: "Propofol", x: "Potencializa GABA-A; sedação profunda dose-dependente." },
  ],
  diretriz: "AES Status Epilepticus Guideline (Glauser T et al., Epilepsy Curr 2016;16:48–61). ABNeuro — Diretrizes 2023. ESETT trial (Kapur J et al., NEJM 2019;381:2103–2113, DOI:10.1056/NEJMoa1905795).",
  fluxo: "crise",
  calcs: [],
},
{
  id: "meningite", sis: "neuro", grav: "alta",
  nome: "Meningite Bacteriana / Encefalite",
  sin: ["meningite", "encefalite", "meningite bacteriana"],
  def: "Febre + cefaleia + rigidez de nuca + alteração de consciência (tríade clássica em 44%). Encefalite: + alteração comportamental/cognitiva, déficit focal, crise.",
  exames: ["TC crânio ANTES da PL se: alteração de consciência, déficit focal, crise, imunossupressão, papiledema, >60a", "Punção lombar: bioquímica + celularidade + Gram + cultura + látex + PCR herpes", "Hemoculturas (2 pares)", "Hemograma, PCR/procalcitonina"],
  rx: [
    { etapa:"atb", d: "Ceftriaxona", do: "2 g IV 12/12h", via: "IV", o: "Cobertura pneumococo, meningococo, H. influenzae." },
    { etapa:"atb", d: "Vancomicina", do: "15–20 mg/kg IV 8/8h", via: "IV", o: "Pneumococo resistente à penicilina." },
    { etapa:"atb", d: "Ampicilina", do: "2 g IV 4/4h", via: "IV", o: "Adicionar se >50 anos, imunossupressão, alcoolismo, gestante (cobertura Listeria)." },
    { etapa:"adj", d: "Dexametasona", do: "0,15 mg/kg (10 mg) IV 6/6h × 4 dias", via: "IV", o: "ANTES OU JUNTO à 1ª dose de ATB. Reduz mortalidade em pneumococo." },
    { etapa:"atb", d: "Aciclovir", do: "10 mg/kg IV 8/8h × 14–21 dias", via: "IV", o: "Suspeita de encefalite herpética: febre + alteração comportamental + crise. NÃO atrasar." },
  ],
  alertas: [
    { t: "crit", x: "Não atrasar ATB esperando exames. ATB em ≤30 min do reconhecimento clínico. Coletar hemoculturas (NÃO esperar PL)." },
    { t: "warn", x: "Dexametasona deve ser administrada ANTES ou JUNTO à 1ª dose de ATB — não funciona depois (já houve liberação de citocinas)." },
    { t: "info", x: "PL: PMN ↑↑ + glicose <2/3 da glicemia + proteína ↑ = bacteriana. Linfócitos + glicose normal + proteína ↑ = viral." },
  ],
  fisio: "Bactérias colonizam nasofaringe → invadem corrente sanguínea → atravessam barreira hematoencefálica → multiplicam no LCR (espaço subaracnoide, escasso em defesas) → liberam componentes parietais (LPS, ácido lipoteicoico) → ativação de TLR e cascata inflamatória com liberação maciça de TNF-α, IL-1, IL-6 → edema, ↑pressão intracraniana, vasculite, isquemia. A <strong>resposta inflamatória é mais lesiva que a bactéria em si</strong> — daí o benefício da dexametasona ANTES do ATB (que ↑lise bacteriana e libera mais componentes inflamatórios). Agentes principais: pneumococo (50%), meningococo, H. influenzae, Listeria (>50a/imunossuprimido).",
  mec: [
    { d: "Ceftriaxona", x: "Cefalosporina de 3ª geração — inibe <strong>PBPs (proteínas ligadoras de penicilina)</strong> bloqueando a transpeptidação na síntese do peptidoglicano da parede bacteriana. Boa penetração no LCR inflamado." },
    { d: "Vancomicina", x: "Liga-se ao D-Ala-D-Ala do precursor do peptidoglicano impedindo sua incorporação à parede. Cobertura Gram+ inclusive MRSA." },
    { d: "Ampicilina", x: "Aminopenicilina — inibe PBPs; cobre Listeria (intrinsecamente resistente a cefalosporinas)." },
    { d: "Dexametasona", x: "Glicocorticoide — reduz síntese de citocinas pró-inflamatórias (TNF-α, IL-1), atenuando a resposta inflamatória meníngea. Benefício comprovado em pneumocócica adulta." },
    { d: "Aciclovir", x: "Antiviral — fosforilado pela TK viral → trifosfato inibe DNA-polimerase do herpes." },
  ],
  diretriz: "IDSA Practice Guidelines for the Management of Bacterial Meningitis (Tunkel AR et al., CID 2004;39:1267–1284, atualizado 2023). ESCMID Guideline 2016.",
  fluxo: null,
  calcs: [],
},

/* ============== RESP ============== */
{
  id: "asma", sis: "resp", grav: "alta",
  nome: "Crise Asmática",
  sin: ["asma", "asma aguda", "broncoespasmo", "crise asmática"],
  def: "Dispneia, sibilos, opressão torácica, tosse + ↑uso musc. acessória. Gravidade por: fala, FR, FC, SpO₂, PFE, alteração de consciência.",
  exames: ["Oximetria + monitorização", "PFE pré e pós-tratamento (% predito)", "Gasometria arterial se grave/sem resposta", "RX tórax se febre, dor torácica, suspeita de pneumotórax/PNM", "Hemograma, PCR se infecção"],
  rx: [
    {etapa:"inicial", d:"Avaliação inicial + PFE",do:"Posição sentada + monitorização + PFE pré-tratamento",via:"—",o:"PFE quantifica gravidade. >70%: leve. 40-69%: moderada. <40%: grave. Repetir após 1h."},
    {etapa:"inicial", d:"O₂ titular SpO₂ 93-95%",do:"Cateter/máscara conforme",via:"—",o:"NÃO O₂ rotineiro alto fluxo. Excesso piora V/Q. Em pediatria: alvo 94-98%."},
    {etapa:"escala", d:"① β2-agonista — Salbutamol nebulizado",do:"5 mg (1 mL) em 3 mL SF, repetir 3× a cada 20 min na 1ª hora",via:"NBZ",o:"1ª LINHA. Ou spray 4-8 jatos com espaçador (equivalente). Contínua em grave: 10-15 mg/h."},
    {etapa:"escala", d:"② Anticolinérgico — Ipratrópio",do:"0,5 mg (40 gotas) JUNTO ao salbutamol",via:"NBZ",o:"Aditivo em moderada/grave nas primeiras 3 doses. Sinergia com β2."},
    {etapa:"escala", d:"③ Corticoide sistêmico — Prednisona",do:"40-60 mg VO dose única, manter 5-7 dias",via:"VO",o:"INICIAR PRECOCEMENTE — efeito em 4-6h. SEMPRE em moderada/grave. Sem desmame se ≤14 dias."},
    {etapa:"escala", d:"③ Corticoide — Metilprednisolona IV (se VO impossível)",do:"1-2 mg/kg IV",via:"IV",o:"Equivalência: 1 mg metilpred = 1,25 mg prednisona. Não é melhor que VO se tolerar."},
    {etapa:"escala", d:"④ Sulfato de magnésio (grave refratária)",do:"2 g IV em 100 mL SF em 20 min",via:"IV",o:"Crise grave refratária a β2 + corticoide. Pediatria: 25-50 mg/kg (máx 2 g)."},
    {etapa:"escala", d:"⑤ Adrenalina (parada iminente)",do:"0,3-0,5 mg IM (1:1000)",via:"IM",o:"Refratário, anafilaxia associada, parada respiratória iminente. Repetir 5-15 min."},
    {etapa:"escala", d:"⑥ IOT — Indutor: Cetamina (broncodilatadora)",do:"Cetamina 1-2 mg/kg IV",via:"IV",o:"PREFERIDO em asma — broncodilatador. Evitar histamino-liberadores (morfina). Preparar VM com ↑tempo expiratório."},
    {etapa:"adj", d:"Hidratação adequada",do:"SF/RL conforme volemia",via:"IV",o:"Evitar tanto hipovolemia (aumenta espessamento secreção) quanto sobrecarga."},
    {etapa:"adj", d:"NÃO usar: antibiótico rotineiro, mucolíticos, sedativos",do:"Sem benefício, podem piorar",via:"—",o:"ATB apenas se infecção bacteriana documentada. Sedativos contraindicados (deprimem ventilação)."},
    {etapa:"alta", d:"Manejo de manutenção",do:"Corticoide inalatório ± LABA + plano de ação",via:"INH",o:"Reavaliar técnica inalatória. Gatilhos. Vacinação. Acompanhamento pneumo."},
  ],
  alertas: [
    { t: "crit", x: "Sinais de iminência de parada respiratória: bradipneia, ↓consciência, silêncio à ausculta, cianose. IOT preparada. Ketamina como indutor (broncodilatadora)." },
    { t: "warn", x: "Manter SpO₂ 93–95% (94–98% em crianças, GINA 2024). Excesso de O₂ pode piorar V/Q." },
    { t: "info", x: "PFE >70% = leve; 40–69% = moderada; <40% = grave; <25% = muito grave." },
  ],
  fisio: "A asma é uma doença inflamatória crônica das vias aéreas com hiper-responsividade brônquica. Na crise, há (1) <strong>broncoespasmo do músculo liso brônquico</strong>, (2) <strong>edema da mucosa</strong> e (3) <strong>hipersecreção de muco viscoso</strong>. A inflamação é predominantemente eosinofílica (mediada por Th2/IL-4/IL-5/IL-13). O fluxo aéreo expiratório é limitado, gerando aprisionamento aéreo, hiperinsuflação dinâmica e ↑trabalho respiratório. A hipoxemia decorre do distúrbio V/Q; em fases avançadas, hipercapnia indica fadiga muscular respiratória (sinal de gravidade).",
  mec: [
    { d: "Salbutamol", x: "<strong>Agonista β2-seletivo</strong> — ativa adenilato ciclase → ↑AMPc → relaxamento do músculo liso brônquico. Início em 5 min, pico 30–60 min, duração 4–6h. Efeitos colaterais: tremor, taquicardia, hipocalemia, hiperglicemia." },
    { d: "Ipratrópio", x: "<strong>Antagonista muscarínico M3</strong> nos brônquios — bloqueia o tônus vagal broncoconstritor. Sinergismo com β2-agonista (mecanismos complementares)." },
    { d: "Corticoides (prednisona, metilprednisolona)", x: "Glicocorticoides — <strong>inibem fosfolipase A2 e transcrição de citocinas inflamatórias</strong>, reduzem eosinófilos, ↑expressão de β2-receptores. Início de efeito clínico em 4–6h." },
    { d: "Sulfato de magnésio", x: "<strong>Bloqueia entrada de Ca²⁺</strong> nas células musculares lisas brônquicas → relaxamento. Também inibe degranulação de mastócitos." },
  ],
  diretriz: "GINA 2024 — Global Initiative for Asthma (ginasthma.org/2024-report). SBPT — Recomendações para o Manejo da Asma Grave 2021 (J Bras Pneumol 47:e20210273). PCDT-Asma MS 2024.",
  fluxo: null,
  calcs: [],
},
{
  id: "dpoc", sis: "resp", grav: "alta",
  nome: "DPOC — Exacerbação",
  sin: ["DPOC", "dpoc agudizado", "enfisema", "bronquite", "exacerbação"],
  def: "Piora aguda da dispneia, escarro (volume/purulência) em portador de DPOC. Critérios de Anthonisen: ↑dispneia, ↑volume escarro, ↑purulência (≥2 → considerar ATB).",
  exames: ["Oximetria + gasometria arterial (define VNI)", "RX tórax (PNM, PNT, congestão)", "ECG", "Hemograma, eletrólitos, função renal", "BNP se diagnóstico diferencial com ICC", "Hemoculturas se febre"],
  rx: [
    { etapa:"inicial", d: "Salbutamol nebulizado", do: "5 mg em 3 mL SF, 3× a cada 20 min na 1ª hora", via: "Nebulização", o: "Pode ser contínuo em grave. Em hipercapnia: preferir spray com espaçador (menor risco de retenção de CO₂)." },
    { etapa:"escala", d: "Ipratrópio nebulizado", do: "0,5 mg junto ao salbutamol", via: "Nebulização", o: "Sinérgico." },
    { etapa:"escala", d: "Prednisona", do: "40 mg VO/d × 5 dias (sem desmame)", via: "VO", o: "Reduz falência terapêutica e tempo de internação (REDUCE trial)." },
    { etapa:"atb", d: "Amoxicilina-clavulanato", do: "875/125 mg 12/12h × 5–7 dias", via: "VO", o: "Se Anthonisen ≥2 ou necessidade de VNI/VM." },
    { etapa:"atb", d: "Azitromicina", do: "500 mg/d × 3–5 dias", via: "VO", o: "Alternativa em alergia. Atypicals." },
    { etapa:"escala", d: "VNI (BiPAP)", do: "IPAP 12–15, EPAP 5, FiO₂ p/ SpO₂ 88–92%", via: "Máscara", o: "Indicação: pH <7,35 + pCO₂ >45. Reduz IOT em 60%." },
    { etapa:"inicial", d: "Oxigenoterapia controlada", do: "Cateter nasal 1–3 L/min ou Venturi 24–28%", via: "—", o: "ALVO SpO₂ 88–92%. Excesso de O₂ → ↓drive respiratório e hipercapnia." },
  ],
  alertas: [
    { t: "crit", x: "Sinais de IOT: pH <7,25 sustentado mesmo com VNI, parada/fadiga respiratória, ↓consciência, instabilidade hemodinâmica." },
    { t: "warn", x: "ALVO SpO₂ 88–92% (não 95–100%). Hiperóxia pode causar acidose respiratória e mortalidade em DPOC." },
  ],
  fisio: "A DPOC tem dois fenótipos: <strong>bronquite crônica</strong> (hipersecreção + inflamação) e <strong>enfisema</strong> (destruição alveolar com perda de elastância). Na exacerbação, infecção viral/bacteriana (50–70%) ou poluição/inflamação aumenta o broncoespasmo, edema, secreção → <strong>hiperinsuflação dinâmica + auto-PEEP</strong> → ↑trabalho respiratório → fadiga muscular → hipercapnia → acidose respiratória. Diferente da asma, há limitação fixa ao fluxo aéreo + componente neutrofílico (não eosinofílico).",
  mec: [
    { d: "Salbutamol + Ipratrópio", x: "Broncodilatação por mecanismos complementares (β2-agonista + antagonista M3)." },
    { d: "Prednisona", x: "↓Inflamação brônquica; benefício no DPOC menor que na asma (componente eosinofílico pequeno) mas significativo." },
    { d: "Amoxicilina-clavulanato", x: "Aminopenicilina + inibidor de β-lactamase — cobre Haemophilus, Moraxella, S. pneumoniae produtor de β-lactamase." },
    { d: "VNI (BiPAP)", x: "<strong>IPAP</strong> assiste a inspiração (↓trabalho respiratório, ↑VC, ↓PaCO₂); <strong>EPAP</strong> mantém alvéolos abertos e contrabalança a auto-PEEP." },
  ],
  diretriz: "GOLD 2024 Report — Global Initiative for Chronic Obstructive Lung Disease (goldcopd.org). SBPT — Manual de DPOC 2024 (Pereira LFF et al.).",
  imgs: [
    {src:"https://upload.wikimedia.org/wikipedia/commons/3/36/X-ray_of_COPD_exacerbation_-_anteroposterior_view.jpg",
     alt:"RX tórax com hiperinsuflação em DPOC",
     caption:"DPOC — hiperinsuflação pulmonar, retificação diafragmática, alargamento dos espaços intercostais.",
     source:"Wikimedia Commons / Mikael Häggström (CC0)"},
  ],
  fluxo: null,
  calcs: [],
},
{
  id: "pac", sis: "resp", grav: "media",
  nome: "Pneumonia Adquirida na Comunidade (PAC)",
  sin: ["PAC", "pneumonia", "pneumonia comunitária"],
  def: "Tosse + febre + dispneia/dor pleurítica + crepitação focal + infiltrado novo no RX. CURB-65 estratifica gravidade e sítio de tratamento.",
  exames: ["RX tórax PA + perfil", "Hemograma, PCR/procalcitonina, função renal, eletrólitos, lactato", "Hemoculturas (2 pares) se internação", "Antígeno urinário pneumococo + Legionella se grave", "PCR respiratório viral em pandemia"],
  rx: [
    { etapa:"atb", d: "Amoxicilina", do: "1 g VO 8/8h × 7 dias", via: "VO", o: "Ambulatorial sem comorbidade (CURB-65 0–1)." },
    { etapa:"atb", d: "Amoxicilina-clavulanato + Azitromicina", do: "875/125 mg 12/12h + 500 mg/d × 5 dias", via: "VO", o: "Ambulatorial com comorbidade." },
    { etapa:"atb", d: "Ceftriaxona + Azitromicina", do: "1–2 g IV/d + 500 mg IV/d", via: "IV", o: "Internado, enfermaria (CURB-65 2)." },
    { etapa:"atb", d: "Ceftriaxona + Levofloxacino", do: "2 g IV/d + 750 mg IV/d", via: "IV", o: "UTI (CURB-65 ≥3 ou outros critérios)." },
    { etapa:"atb", d: "Piperacilina-tazobactam ± Vancomicina", do: "4,5 g 6/6h + 15 mg/kg 12/12h", via: "IV", o: "Suspeita Pseudomonas/MRSA: institucionalizado, ATB recente, bronquiectasia, ventilação prévia." },
    { etapa:"atb", d: "Oseltamivir", do: "75 mg VO 12/12h × 5 dias", via: "VO", o: "Influenza em surto/PCR+. Iniciar idealmente em 48h." },
  ],
  alertas: [
    { t: "crit", x: "Sepse: aplicar bundle hour-1 (lactato, hemocultura, ATB <1h, cristaloide, vasopressor)." },
    { t: "info", x: "CURB-65: Confusão / Ureia >50 / FR ≥30 / PA <90×60 / Idade ≥65. 0–1: ambulatorial. 2: enfermaria. ≥3: UTI." },
  ],
  fisio: "PAC = infecção do parênquima pulmonar adquirida em pacientes ambulatoriais. Os patógenos chegam por (1) aspiração de microflora orofaríngea, (2) inalação de aerossol, (3) disseminação hematogênica. Os mais comuns: <strong>S. pneumoniae</strong> (típico, 30%), <strong>Mycoplasma/Chlamydophila/Legionella</strong> (atípicos), <strong>vírus respiratórios</strong> (influenza, SARS-CoV-2). Em CRF grave: + bastonetes Gram-negativos. A inflamação alveolar leva a preenchimento alveolar por exsudato → consolidação visível ao RX. O tratamento ATB deve cobrir típicos + atípicos em pacientes internados.",
  mec: [
    { d: "Amoxicilina / Amox-clav", x: "Aminopenicilinas inibem PBPs (transpeptidação da parede bacteriana). Clavulanato inibe β-lactamases." },
    { d: "Ceftriaxona", x: "Cefalosporina 3ª geração — boa cobertura para pneumococo, H. influenzae, Klebsiella." },
    { d: "Azitromicina", x: "Macrolídeo — liga-se à subunidade <strong>50S do ribossomo bacteriano</strong>, inibindo a translocação na síntese proteica. Cobre atípicos (Mycoplasma, Chlamydophila, Legionella)." },
    { d: "Levofloxacino", x: "Fluoroquinolona — inibe <strong>DNA-girase e topoisomerase IV</strong> bacterianas, impedindo replicação. Cobre típicos + atípicos." },
  ],
  diretriz: "SBPT 2018 — Recomendações para o manejo da PAC (Corrêa RA et al., J Bras Pneumol 2018;44:405–423). ATS/IDSA 2019 (Metlay JP et al., Am J Respir Crit Care Med 2019;200:e45–e67, DOI:10.1164/rccm.201908-1581ST).",
  imgs: [
    {src:"https://upload.wikimedia.org/wikipedia/commons/5/51/X-ray_of_lobar_pneumonia.jpg",
     alt:"RX tórax mostrando pneumonia lobar com consolidação", caption:"Pneumonia lobar — consolidação alveolar densa no lobo inferior direito, com broncograma aéreo.",
     source:"Wikimedia Commons (CC BY-SA)"},
    {src:"https://upload.wikimedia.org/wikipedia/commons/2/20/Chest_X-ray_in_influenza_and_Haemophilus_influenzae.jpg",
     alt:"Consolidação radiológica em pneumonia", caption:"Outro exemplo de consolidação pneumônica.",
     source:"Wikimedia Commons"},
  ],
  fluxo: null,
  calcs: ["curb65"],
},
{
  id: "tb", sis: "resp", grav: "media",
  nome: "Tuberculose Pulmonar",
  sin: ["TB", "tuberculose"],
  def: "Tosse ≥3 sem + febre vespertina, sudorese noturna, emagrecimento, hemoptise. Considerar em todo paciente com PNM atípica ou \"sintomas respiratórios\".",
  exames: ["RX tórax (cavitação em ápice, miliar)", "BAAR no escarro × 2 (manhãs consecutivas)", "TRM-TB (GeneXpert) — diagnóstico + resistência à rifampicina em 2h", "Cultura para micobactérias + TS", "HIV (sempre)", "Função hepática e renal antes do esquema"],
  rx: [
    { etapa:"escala", d: "Esquema RIPE", do: "RHZE coformulado: <50kg 2 cp; 50–70kg 3 cp; >70kg 4 cp — uma vez/dia em jejum", via: "VO", o: "Fase intensiva 2 meses. Composição (por cp): R 150 / H 75 / Z 400 / E 275 mg." },
    { etapa:"escala", d: "Manutenção RH", do: "RH coformulado por mais 4 meses", via: "VO", o: "Total 6 meses em PAS comum. 12 meses em meningite ou óssea." },
    { etapa:"adj", d: "Piridoxina (B6)", do: "50 mg/d", via: "VO", o: "Profilaxia de neuropatia por isoniazida em gestante, lactante, DM, etilista, IRC, HIV." },
    { etapa:"adj", d: "Corticoide", do: "Prednisona 1 mg/kg/d × 4–8 sem", via: "VO", o: "Em meningite tuberculosa e pericardite TB." },
  ],
  alertas: [
    { t: "warn", x: "Hepatotoxicidade do RHZE: monitorar AST/ALT. Suspender se TGO/TGP >3× ULN com sintomas ou >5× ULN sem sintomas." },
    { t: "info", x: "Notificação compulsória. Iniciar tratamento mesmo com BAAR/TRM-TB negativo se clínica e RX compatíveis (sob orientação de pneumologia/SCIH)." },
  ],
  fisio: "<em>Mycobacterium tuberculosis</em>, bacilo aeróbio estrito, é transmitido por aerossol. Após inalação, é fagocitado por macrófagos alveolares; sua parede rica em ácidos micólicos resiste à destruição. Inicia infecção primária com formação de granuloma (resposta Th1/IFN-γ/TNF-α) que contém a infecção em 95% dos casos. <strong>Reativação</strong> ocorre em condições de imunossupressão (HIV, DM, corticoide, desnutrição, idade) → cavitação preferencial em ápices pulmonares (ricos em O₂) e disseminação. Sem tratamento, mortalidade 50%.",
  mec: [
    { d: "Rifampicina", x: "Inibe <strong>RNA-polimerase DNA-dependente bacteriana</strong>, bloqueando síntese de RNA. Bactericida. Indutor potente de CYP450 (interações). Urina/lágrimas avermelhadas." },
    { d: "Isoniazida (H)", x: "Pró-droga — ativada pela <strong>catalase-peroxidase (KatG)</strong> bacteriana; inibe a síntese de <strong>ácidos micólicos</strong> (componente único da parede micobacteriana). Bactericida em divisão." },
    { d: "Pirazinamida (Z)", x: "Pró-droga ativada em meio ácido intracelular (pH <6) pela pirazinamidase; mecanismo final envolve disrupção de membrana e síntese proteica. Ativa em macrófagos." },
    { d: "Etambutol (E)", x: "Inibe <strong>arabinosil-transferase</strong>, bloqueando síntese de arabinogalactano da parede. Bacteriostático. Toxicidade: neurite óptica." },
  ],
  diretriz: "Manual de Recomendações para o Controle da Tuberculose no Brasil (MS, 2ª ed. 2019). WHO Consolidated Guidelines on Tuberculosis 2022.",
  imgs: [
    {src:"https://upload.wikimedia.org/wikipedia/commons/9/9c/Tuberculosis-x-ray-1.jpg",
     alt:"RX de tórax com cavitação apical bilateral",
     caption:"TB pulmonar bilateral — infiltrado heterogêneo nos ápices com cavitações.",
     source:"Wikimedia Commons (Domínio público)"},
  ],
  fluxo: null,
  calcs: [],
},
{
  id: "pneumotorax", sis: "resp", grav: "alta",
  nome: "Pneumotórax / Hemotórax",
  sin: ["pneumotórax", "hemotórax", "PNT"],
  def: "Pneumotórax: ar no espaço pleural — dor torácica súbita + dispneia + hipertimpanismo. Hipertensivo: + hipotensão, desvio traqueal, ↓MV. Hemotórax: sangue no espaço pleural.",
  exames: ["RX tórax PA em pé (hipertransparência sem trama)", "USG point-of-care (ausência de lung sliding, B-lines)", "TC tórax se traumático/loculado", "Hemograma, coagulograma"],
  rx: [
    { etapa:"inicial", d: "Descompressão imediata", do: "Punção 2º EIC linha hemiclavicular OU 4º–5º EIC linha axilar", via: "—", o: "PNT HIPERTENSIVO (instável). Cateter 14G. Drenagem definitiva em seguida." },
    { etapa:"adj", d: "Drenagem torácica em selo d'água", do: "5º EIC linha axilar média, dreno 28–32 Fr", via: "—", o: "PNT >2 cm, sintomático, recidiva, traumatic; hemotórax; derrame complicado. Anestesia local + analgesia." },
    { etapa:"atb", d: "Cefazolina", do: "2 g IV pré-drenagem + 8/8h × 24h", via: "IV", o: "Profilaxia ATB em trauma penetrante." },
    { etapa:"inicial", d: "Conservador", do: "O₂ alto fluxo + observação", via: "—", o: "PNT primário pequeno (<2 cm), assintomático. Reabsorção 1–2%/dia (mais rápido com O₂)." },
  ],
  alertas: [
    { t: "crit", x: "PNT HIPERTENSIVO: diagnóstico CLÍNICO (hipotensão, dispneia grave, ↓MV unilateral, desvio traqueal). NÃO esperar RX — descomprimir imediato." },
  ],
  fisio: "O PNT espontâneo primário ocorre por ruptura de blebs subpleurais (jovens, altos, magros, tabagistas); secundário é complicação de DPOC, asma, TB, fibrose. <strong>Traumático</strong> ocorre por penetração ou contusão. No PNT <strong>hipertensivo</strong>, um mecanismo valvar permite entrada mas não saída de ar — a pressão pleural sobe progressivamente, colaba o pulmão ipsilateral, desvia mediastino e comprime VCS/grandes vasos → ↓retorno venoso → choque obstrutivo. É emergência absoluta.",
  mec: [
    { d: "Drenagem", x: "Remoção mecânica do ar/sangue → restauração da pressão pleural negativa → reexpansão pulmonar." },
    { d: "Oxigenoterapia", x: "↑Pressão parcial de O₂ alveolar → aumenta gradiente para reabsorção pleural (acelera 4×)." },
  ],
  diretriz: "BTS Pleural Disease Guideline 2023 (Roberts ME et al., Thorax 2023;78(Suppl 3):s1–s42). Manual de Trauma ATLS 10ª ed.",
  imgs: [
    {src:"https://upload.wikimedia.org/wikipedia/commons/c/c6/Expired_X-ray_of_pneumothorax.jpg",
     alt:"RX tórax com pneumotórax — expiração",
     caption:"Pneumotórax — RX em expiração: ausência de trama vascular lateralmente, linha pleural visível.",
     source:"Wikimedia Commons / Mikael Häggström (CC0)"},
    {src:"https://upload.wikimedia.org/wikipedia/commons/9/96/Lateral_X-ray_of_pneumothorax_in_inspiration_-_annotated.jpg",
     alt:"RX lateral de pneumotórax com anotação",
     caption:"Visão lateral anotada de pneumotórax.",
     source:"Wikimedia Commons / Mikael Häggström (CC0)"},
  ],
  fluxo: null,
  calcs: [],
},
{
  id: "oma", sis: "resp", grav: "baixa",
  nome: "Otite Média Aguda (OMA)",
  sin: ["OMA", "otite", "otalgia"],
  def: "Otalgia + abaulamento timpânico + sinais de inflamação + início <48h. Diferenciar de otite externa (dor à tração tragal) e otite secretora.",
  exames: ["Otoscopia (abaulamento, hiperemia, opacificação)"],
  rx: [
    { etapa:"atb", d: "Amoxicilina", do: "50 mg/kg/d divididos 8/8h × 7–10 dias", via: "VO", o: "1ª linha. Adultos 500 mg 8/8h ou 875 mg 12/12h." },
    { etapa:"atb", d: "Amoxicilina-clavulanato", do: "50 mg/kg/d (amox) × 10 dias", via: "VO", o: "Falha em 48–72h, <2a, otite recorrente, conjuntivite associada, uso recente de ATB." },
    { etapa:"atb", d: "Ceftriaxona", do: "50 mg/kg IM × 1–3 dias", via: "IM", o: "Vômitos / não-aderência. Dose única adultos: 1–2 g." },
    { etapa:"adj", d: "Analgesia", do: "Paracetamol/dipirona/ibuprofeno", via: "VO", o: "Mesmo se observação sem ATB (≥2a, leve, otoscopia duvidosa)." },
  ],
  alertas: [
    { t: "warn", x: "Mastoidite (dor retroauricular + abaulamento + febre) é emergência — TC + ceftriaxona IV + ORL." },
  ],
  fisio: "A disfunção da tuba auditiva (geralmente após IVAS) cria pressão negativa na orelha média → transudação → meio de cultura para bactérias colonizadoras (S. pneumoniae 30–40%, H. influenzae não-tipável 25%, Moraxella catarrhalis 15%). Em crianças, a tuba mais horizontal e curta predispõe.",
  mec: [
    { d: "Amoxicilina", x: "Aminopenicilina — inibe PBPs (peptidoglicano)." },
  ],
  diretriz: "AAP Clinical Practice Guideline: The Diagnosis and Management of Acute Otitis Media (Lieberthal AS et al., Pediatrics 2013;131:e964–e999, DOI:10.1542/peds.2012-3488).",
  fluxo: null,
  calcs: [],
},
{
  id: "rino", sis: "resp", grav: "baixa",
  nome: "Rinossinusite Aguda",
  sin: ["sinusite", "rinossinusite"],
  def: "Sintomas nasais (obstrução, descarga purulenta, dor facial, hiposmia) por <12 sem. Bacteriana se persistir >10 dias OU piorar após 5 dias OU sintomas \"double-sickening\".",
  exames: ["Clínica (>90% diagnóstico). TC apenas em complicações/refratários."],
  rx: [
    { etapa:"atb", d: "Amoxicilina-clavulanato", do: "875/125 mg 12/12h × 7–10 dias", via: "VO", o: "1ª linha em bacteriana." },
    { etapa:"adj", d: "Corticoide intranasal", do: "Mometasona/fluticasona 1–2 sprays cada narina 1×/d", via: "Intranasal", o: "Reduz sintomas. Pode ser monoterapia em casos leves." },
    { etapa:"escala", d: "Lavagem nasal com salina", do: "Solução salina 0,9% várias vezes ao dia", via: "Intranasal", o: "Eficaz em viral + bacteriana." },
  ],
  alertas: [
    { t: "warn", x: "Complicações: celulite orbitária, abscesso periorbitário, trombose de seio cavernoso, meningite. Sinais: edema/eritema periorbital, proptose, oftalmoplegia, sinais meníngeos. TC + ATB IV + ORL." },
  ],
  fisio: "Obstrução do óstio dos seios paranasais (por edema da mucosa, geralmente após viral) → estase de secreção → infecção bacteriana secundária. Agentes: S. pneumoniae, H. influenzae, M. catarrhalis (similares a OMA).",
  mec: [
    { d: "Amoxicilina-clavulanato", x: "Aminopenicilina + inibidor β-lactamase." },
    { d: "Corticoide intranasal", x: "↓Inflamação da mucosa nasal e dos óstios sinusais → melhora drenagem." },
  ],
  diretriz: "EPOS 2020 — European Position Paper on Rhinosinusitis and Nasal Polyps (Fokkens WJ et al., Rhinology 2020;58:1–464).",
  fluxo: null,
  calcs: [],
},
{
  id: "faringo", sis: "resp", grav: "baixa",
  nome: "Faringoamigdalite",
  sin: ["faringite", "amigdalite", "garganta", "estrepto"],
  def: "Dor de garganta ± febre + exsudato amigdaliano + adenopatia cervical. Diferenciar viral (90%) de estreptocócica (Centor/McIsaac).",
  exames: ["Critérios de Centor/McIsaac", "Strep test rápido se disponível", "Cultura de orofaringe se necessário"],
  rx: [
    { etapa:"atb", d: "Penicilina G benzatina", do: "1.200.000 UI IM dose única (<27kg: 600.000 UI)", via: "IM", o: "1ª linha. Único ATB que comprova prevenção de febre reumática." },
    { etapa:"atb", d: "Amoxicilina", do: "500 mg VO 8/8h × 10 dias (crianças 50 mg/kg/d)", via: "VO", o: "Alternativa quando não há disponibilidade IM." },
    { etapa:"atb", d: "Azitromicina", do: "500 mg/d × 5 dias", via: "VO", o: "Alergia a penicilina." },
    { etapa:"adj", d: "Analgesia", do: "Dipirona/paracetamol/ibuprofeno", via: "VO", o: "Sintomático." },
  ],
  alertas: [
    { t: "warn", x: "Suspeitar mononucleose (EBV) em adolescentes: febre, faringite exsudativa, adenopatia cervical posterior, hepatoesplenomegalia. AAS amox → rash em 90%." },
  ],
  fisio: "Estreptococo β-hemolítico do grupo A (S. pyogenes) — bacteriana mais comum, causa de febre reumática e glomerulonefrite pós-estreptocócica se não tratada. Viral: rinovírus, coronavírus, adenovírus, influenza, EBV, CMV.",
  mec: [
    { d: "Penicilina G", x: "Inibe PBPs (parede)." },
  ],
  diretriz: "IDSA — Clinical Practice Guideline for the Diagnosis and Management of Group A Streptococcal Pharyngitis (Shulman ST et al., CID 2012;55:e86–e102, DOI:10.1093/cid/cis629).",
  fluxo: null,
  calcs: ["centor"],
},
{
  id: "epistaxe", sis: "resp", grav: "media",
  nome: "Epistaxe",
  sin: ["sangramento nasal", "epistaxe"],
  def: "Sangramento nasal. Anterior (90%, área de Kiesselbach) ou posterior (mais grave). Causa: trauma, ressecamento, HAS, anticoagulação, coagulopatia.",
  exames: ["Sinais vitais", "Hemograma, coagulograma se anticoagulado/recorrente", "Rinoscopia anterior"],
  rx: [
    { etapa:"inicial", d: "Compressão digital", do: "Pinçar narinas 10–15 min sem soltar, inclinado para frente", via: "—", o: "1ª medida em TODOS. Eficaz em 80%." },
    { etapa:"escala", d: "Oximetazolina spray", do: "2 jatos cada narina", via: "Intranasal", o: "Vasoconstritor. Pode aplicar em algodão e introduzir." },
    { etapa:"adj", d: "Ácido tranexâmico tópico", do: "500 mg em algodão embebido + tamponamento 10 min", via: "Tópico", o: "Útil em pacientes anticoagulados." },
    { etapa:"escala", d: "Tamponamento anterior", do: "Gaze vaselinada ou tampão expansível por 24–48h", via: "—", o: "Falha de medidas iniciais." },
    { etapa:"atb", d: "Tamponamento posterior", do: "Sonda Foley + tampão anterior", via: "—", o: "Sangramento posterior. Hospitalização. ATB profilático (síndrome do choque tóxico)." },
  ],
  alertas: [
    { t: "warn", x: "HAS é fator agravante, não causa primária — controlar PA, mas tratar a fonte do sangramento." },
  ],
  fisio: "Plexo de Kiesselbach (anterior) é vascularizado por anastomose de várias artérias e é o sítio mais comum (95% das epistaxes). Trauma seco, baixa umidade, hipertensão, anticoagulação e antiagregação contribuem. Epistaxe posterior (artéria esfenopalatina) é mais grave, mais frequente em idosos e mais difícil de controlar.",
  mec: [
    { d: "Ácido tranexâmico", x: "Análogo da lisina — bloqueia o sítio de ligação do plasminogênio à fibrina, <strong>inibindo a fibrinólise</strong>. Estabiliza coágulo." },
    { d: "Oximetazolina", x: "α1-agonista — vasoconstrição local." },
  ],
  diretriz: "AAO-HNS Clinical Practice Guideline: Nosebleed (Tunkel DE et al., Otolaryngol Head Neck Surg 2020;162:S1–S38).",
  fluxo: null,
  calcs: [],
},

];
/* Dados da PARTE 1 (cardio + neuro + resp). Próximas partes adicionadas em seguida. */
