/* ===========================================================
   VOVÔMINIC EMERGÊNCIA — CONTEÚDO MÉDICO-LEGAL
   Notificação compulsória + Templates de evolução + Receituário
   =========================================================== */

PATOLOGIAS.push(

/* ============== NOTIFICAÇÃO COMPULSÓRIA ============== */
{id:"doc-notificacao", sis:"docs", grav:"baixa",
nome:"Notificação Compulsória — Lista e Prazos",
sin:["notificação","compulsória","SINAN","SIVEP","doenças notificáveis"],
def:"Doenças e agravos de notificação compulsória no Brasil (Portaria MS 1.061/2020, atualizada). Médico tem OBRIGAÇÃO LEGAL de notificar. Notificação NÃO depende de confirmação — SUSPEITA já é gatilho.",

exames:[
"NOTIFICAÇÃO COMPULSÓRIA IMEDIATA (≤24h, por telefone/eletrônico):",
"- Acidente por animal peçonhento, Antraz, Botulismo, Cólera, Coqueluche",
"- Dengue (óbito, grave), Difteria, Doença de Chagas aguda, Doença de Creutzfeldt-Jakob",
"- Doença meningocócica e meningites, Eventos adversos pós-vacinação graves",
"- Febre amarela, Febre de Chikungunya (óbito, importado), Febre maculosa",
"- Febre tifoide, Hantavirose, Influenza humana por novo subtipo viral",
"- Malária (fora região amazônica), Óbito materno, Óbito infantil/fetal",
"- Peste, Poliomielite, Raiva humana, Rubéola, Sarampo",
"- Síndrome da Rubéola Congênita, Síndrome do Choque Tóxico, Tétano",
"- Tularemia, Varíola, Violência sexual/auto-provocada",

"NOTIFICAÇÃO COMPULSÓRIA SEMANAL (até 7 dias):",
"- AIDS, Acidente de trabalho com exposição biológica, Acidente de trabalho com mutilação",
"- Câncer relacionado ao trabalho, Coqueluche, Dengue (todos os casos)",
"- Doença de Chagas crônica, Esquistossomose, Febre de Chikungunya",
"- Hanseníase, Hepatites virais, HIV (gestante, criança exposta)",
"- Intoxicação exógena, Leishmaniose tegumentar/visceral, Leptospirose",
"- LER/DORT, PAIR (Perda Auditiva Induzida por Ruído), Sífilis adquirida/congênita/gestante",
"- Toxoplasmose adquirida na gestação, Toxoplasmose congênita",
"- Tuberculose, Violência doméstica, Zika (caso autóctone, gestante)",

"COMO NOTIFICAR:",
"- SINAN (Sistema Informação Agravos Notificação): maioria dos casos",
"- SIVEP-Malária: malária na Amazônia legal",
"- SIVEP-Gripe: SRAG (vigilância sentinela)",
"- e-SUS Notifica: COVID-19 (atualmente integrado SINAN)",
"- Telefone à vigilância epidemiológica municipal: imediata",
"- Ficha SINAN específica: cada agravo tem ficha própria",
],

rx:[
{etapa:"inicial", d:"PASSO 1 — Identificar agravo notificável",do:"Suspeita CLÍNICA é suficiente (não precisa confirmar)",via:"—",o:"Lista completa disponível em http://portalsinan.saude.gov.br. Consultar lista local de agravos sentinela (alguns estados ampliam)."},
{etapa:"inicial", d:"PASSO 2 — Coletar dados",do:"Dados do paciente, da exposição, da doença",via:"—",o:"Use a ficha SINAN específica do agravo. Dados: identificação, residência, data início sintomas, hospitalização, evolução, etiologia."},

{etapa:"escala", d:"PASSO 3 — Notificar dentro do prazo",do:"IMEDIATA (24h por telefone) OU SEMANAL (até 7 dias)",via:"—",o:"Imediata: TELEFONAR vigilância municipal + enviar ficha. Semanal: digitar SINAN. Documentar no prontuário a notificação."},
{etapa:"escala", d:"PASSO 4 — Casos especiais",do:"Casos suspeitos morre antes de confirmação = ainda notificar",via:"—",o:"Cumpre obrigação mesmo com diagnóstico não-confirmado. Vigilância encerra ficha conforme evolução."},

{etapa:"adj", d:"VIOLÊNCIA — Notificação OBRIGATÓRIA",do:"Toda suspeita: sexual, física, psicológica, negligência, financeira",via:"—",o:"Crianças/adolescentes/idosos: também Conselho Tutelar/Delegacia Idoso. NÃO depende de denúncia da vítima — é obrigação do médico (Lei 12.845/2013)."},
{etapa:"adj", d:"VIOLÊNCIA SEXUAL — Profilaxias",do:"Anticoncepção emergência + IST + HIV PEP + Hepatite B (vacina + Ig se não-imune)",via:"VO/IV",o:"≤72h: tudo viável. Coleta de evidências (perícia). Acolhimento ético. Encaminhar serviço de violência sexual de referência."},
{etapa:"adj", d:"ÓBITO MATERNO — Notificação OBRIGATÓRIA",do:"Toda morte de mulher grávida ou até 42 dias após parto/abortamento",via:"—",o:"Investigação obrigatória (Comitê de Mortalidade Materna). Independente da causa (acidente, suicídio, doença não-obstétrica também)."},
],

alertas:[
{t:"crit",x:"NÃO NOTIFICAR é INFRAÇÃO ÉTICA (CFM Res. 2.217/2018) e ADMINISTRATIVA (Lei 6.259/1975). Pode gerar processo CRM + sanção administrativa do MS."},
{t:"crit",x:"VIOLÊNCIA: notificação NÃO é denúncia policial. Não exige consentimento da vítima. Sigilo médico não impede notificação à vigilância em saúde."},
{t:"warn",x:"DUPLICIDADE: se outro profissional já notificou, NÃO é problema. Vigilância identifica e consolida. Melhor duas notificações que zero."},
{t:"info",x:"Notificar IMEDIATAMENTE em surto suspeito (≥2 casos ligados) mesmo de doenças não-listadas. Surto = evento de saúde pública por si só."},
],

fisio:"Notificação compulsória é instrumento da Vigilância Epidemiológica. Permite: detecção precoce de surtos, monitoramento de doenças, planejamento de intervenções, controle de focos. Lei 6.259/1975 e Portarias MS atualizam lista periodicamente.",
mec:[],
diretriz:"Portaria MS Nº 1.061/2020. Lista Nacional de Notificação Compulsória. CFM Resolução 2.217/2018 (Código de Ética Médica). Lei 6.259/1975.",
fluxo:null,
calcs:[],
},

/* ============== TEMPLATE DE EVOLUÇÃO — SEPSE ============== */
{id:"doc-evol-sepse", sis:"docs", grav:"alta",
nome:"Template de Evolução — Sepse",
sin:["evolução","prontuário","sepse template","registro médico"],
def:"Modelo estruturado de evolução para paciente com sepse, com elementos medicolegais essenciais. Copiar, adaptar e preencher.",

exames:[
"ELEMENTOS OBRIGATÓRIOS na evolução:",
"- Sinais vitais (PA, FC, FR, Temp, SpO2, Glasgow, dor EVA)",
"- Avaliação por aparelhos (sistemática)",
"- Dados laboratoriais relevantes",
"- Justificativa para diagnóstico",
"- Justificativa para CADA conduta (especialmente decisões irreversíveis)",
"- Reavaliação após intervenções",
"- Plano para próximas 6-12h",
],

rx:[
{etapa:"inicial", d:"TEMPLATE COMPLETO",do:"Copiar bloco abaixo para o prontuário",via:"—",o:"Adaptar conforme paciente. Manter elementos medicolegais."},
],

alertas:[
{t:"info",x:"TEMPLATE COMPLETO:"},
{t:"info",x:"═══════════════════════════════════════════════"},
{t:"info",x:"DATA: __/__/____  HORA: __:__"},
{t:"info",x:"PLANTONISTA: Dr(a). _________________________"},
{t:"info",x:"CRM/UF: ___________________"},
{t:"info",x:"═══════════════════════════════════════════════"},
{t:"info",x:"PACIENTE: ___________________________________"},
{t:"info",x:"IDADE: ____ anos    SEXO: ______    PESO: ____kg"},
{t:"info",x:"LEITO/Nº PRONTUÁRIO: ________________________"},
{t:"info",x:""},
{t:"info",x:"S — SUBJETIVO (HMA / queixas atuais)"},
{t:"info",x:"Paciente com [tempo] de evolução de [sintomas]. Procurou atendimento por [motivo]. Refere [associados]. Nega [exclusões relevantes: sangramento, dor torácica, etc]. Antecedentes pessoais: [HAS/DM/cardiopatia/etc]. Medicações em uso: ___. Alergias: ___."},
{t:"info",x:""},
{t:"info",x:"O — OBJETIVO"},
{t:"info",x:"Sinais vitais: PA ___/___ mmHg, FC ___ bpm, FR ___ irpm, Tax ___°C, SpO2 ___% em [ar amb/O2 ___L]"},
{t:"info",x:"Glasgow ___/15 (E_V_M_). EVA dor: ___/10. Glicemia capilar: ___mg/dL"},
{t:"info",x:"Exame físico:"},
{t:"info",x:"- ESTADO GERAL: regular/ruim, descorado __+/4+, hidratado, ictérico __+/4+, [outros]"},
{t:"info",x:"- AR: MV [presente/diminuído] bilateralmente, [sem/com] ruídos adventícios, eupneico/dispneico"},
{t:"info",x:"- ACV: BNF, RCR em 2T, [sem/com] sopros, pulsos periféricos [presentes/diminuídos]"},
{t:"info",x:"- ABD: plano, RHA+, doloroso à palpação em [região], [sem/com] sinais de irritação peritoneal, [sem] visceromegalias"},
{t:"info",x:"- NEURO: orientado em tempo e espaço/confuso, [sem/com] déficit focal, pupilas isocóricas e fotorreagentes"},
{t:"info",x:"- MMII: [sem/com] edema, [sem/com] sinais de TVP"},
{t:"info",x:""},
{t:"info",x:"Exames laboratoriais relevantes ([data/hora]):"},
{t:"info",x:"- Hb ___ Ht ___ Leuco ___ (___% bastões) Plaq ___"},
{t:"info",x:"- Cr ___ Ur ___ Na ___ K ___ Cl ___ Ca ___"},
{t:"info",x:"- PCR ___ Lactato ___ (repetido ___) Glicemia ___"},
{t:"info",x:"- Gasometria arterial: pH ___ pCO2 ___ pO2 ___ HCO3 ___ BE ___"},
{t:"info",x:"- TAP/INR ___ TTPA ___"},
{t:"info",x:"- EAS: ___ leucócitos, ___ nitritos, ___"},
{t:"info",x:""},
{t:"info",x:"Imagens: [RX tórax/USG/TC] — [achados]"},
{t:"info",x:""},
{t:"info",x:"A — AVALIAÇÃO"},
{t:"info",x:"Paciente em quadro de SEPSE com critérios:"},
{t:"info",x:"[ ] qSOFA ≥2 (FR≥22, PAS≤100, alteração mental)"},
{t:"info",x:"[ ] SOFA escore ___ (descrever componentes)"},
{t:"info",x:"Foco PROVÁVEL: [pulmonar/urinário/abdominal/pele/meningite/desconhecido]"},
{t:"info",x:"Justificativa do foco: ___ (achados clínicos + exames)"},
{t:"info",x:""},
{t:"info",x:"[ ] Choque séptico (necessita vasopressor + lactato >2 apesar de volume)"},
{t:"info",x:""},
{t:"info",x:"P — PLANO"},
{t:"info",x:"BUNDLE HORA-1:"},
{t:"info",x:"1. Coletado lactato ([hora]) e hemoculturas 2 pares ([hora])"},
{t:"info",x:"2. Iniciado ATB empírico [droga/dose] em [hora] — escolha justificada por: [foco suspeito + epidemiologia local + alergias]"},
{t:"info",x:"3. Cristaloide [Ringer/SF] 30 mL/kg = ___ mL infundido em ___min"},
{t:"info",x:"4. [SE CHOQUE] Noradrenalina iniciada em [hora], dose atual ___ mcg/kg/min, alvo PAM ≥65 mmHg"},
{t:"info",x:""},
{t:"info",x:"REAVALIAÇÕES PROGRAMADAS:"},
{t:"info",x:"- Lactato em 2h"},
{t:"info",x:"- Avaliação de responsividade a volume (USG-VCI, eco, débito urinário)"},
{t:"info",x:"- Ajuste vasopressor"},
{t:"info",x:"- Solicitar [exames complementares]"},
{t:"info",x:""},
{t:"info",x:"COMUNICAÇÃO FAMILIAR:"},
{t:"info",x:"Familiares informados sobre gravidade, prognóstico reservado, intervenções propostas. [Concordaram/manifestaram dúvidas/recusam-se a]."},
{t:"info",x:""},
{t:"info",x:"ASSINATURA + CARIMBO + CRM"},
{t:"info",x:"═══════════════════════════════════════════════"},
],

fisio:"Justificativa medicolegal: registrar a SEQUÊNCIA do raciocínio + intervenções tempo-críticas (lactato, hemoculturas, ATB, volume) é crucial em sepse. Em mortalidade ou complicação, o prontuário é a única defesa do plantonista. SBA — 'o que não está escrito não foi feito'.",
mec:[],
diretriz:"Surviving Sepsis Campaign 2021. ILAS Brasil. CFM Resolução 1.638/2002 (prontuário).",
fluxo:null,
calcs:[],
},

/* ============== TEMPLATE EVOLUÇÃO — IAM ============== */
{id:"doc-evol-iam", sis:"docs", grav:"alta",
nome:"Template de Evolução — IAM/SCA",
sin:["evolução IAM","SCA template","registro médico"],
def:"Modelo de evolução para SCA com supra-ST (STEMI) ou sem supra (NSTEMI/AI). Elementos críticos: tempo porta-ECG, porta-agulha/balão, escolha de estratégia.",

exames:[
"ELEMENTOS CRÍTICOS:",
"- Horário do início da dor",
"- Horário da chegada (porta)",
"- Horário do ECG (alvo ≤10 min)",
"- Horário da decisão de reperfusão",
"- Horário de fibrinolítico (alvo ≤30 min) ou de balão (alvo ≤90 min)",
"- Justificativa para a escolha de estratégia",
"- Score de risco (GRACE/TIMI)",
"- Contraindicações para reperfusão",
],

rx:[
{etapa:"inicial", d:"TEMPLATE COMPLETO",do:"Copiar e adaptar",via:"—",o:"Imprimir e colar no prontuário."},
],

alertas:[
{t:"info",x:"TEMPLATE COMPLETO:"},
{t:"info",x:"═══════════════════════════════════════════════"},
{t:"info",x:"EVOLUÇÃO — SUSPEITA DE SÍNDROME CORONARIANA AGUDA"},
{t:"info",x:"═══════════════════════════════════════════════"},
{t:"info",x:"Paciente com [tempo] de dor torácica iniciada às [hora]."},
{t:"info",x:"Características: [opressiva/peso/queimação], localização [retroesternal/precórdio], irradiação para [braço E/D, mandíbula, dorso], duração [contínua/intermitente], intensidade [EVA __/10]."},
{t:"info",x:"Fatores associados: [sudorese, náusea, dispneia, síncope]."},
{t:"info",x:"Fatores de risco CV: [HAS / DM / DLP / tabagismo (___ maços-ano) / história familiar / IRC / obesidade / sedentarismo]"},
{t:"info",x:"Cardiopatia prévia: [sim/não] — [IAM prévio data / angioplastia / revascularização]"},
{t:"info",x:"Uso de drogas (cocaína recente?): [sim/não]"},
{t:"info",x:""},
{t:"info",x:"SINAIS VITAIS:"},
{t:"info",x:"PA ___/___mmHg (ambos braços: D___/___, E___/___) FC ___bpm FR ___irpm Tax ___ SpO2 ___%"},
{t:"info",x:""},
{t:"info",x:"EXAME FÍSICO:"},
{t:"info",x:"- ACV: BNF, [B3/B4 audível?], sopros, pulsos periféricos simétricos, sinais de IC?"},
{t:"info",x:"- AR: MV bilateral, [estertores em bases (Killip)]?"},
{t:"info",x:"- MMII: edema, perfusão"},
{t:"info",x:""},
{t:"info",x:"CLASSIFICAÇÃO KILLIP: [I/II/III/IV]"},
{t:"info",x:""},
{t:"info",x:"ECG (___:___) — Tempo porta-ECG: ___min"},
{t:"info",x:"Ritmo: ___ FC: ___"},
{t:"info",x:"Achados: [supra ST em ___mm em DII-III-aVF / V1-V4 / V5-V6 / etc] OU [infra ST / T invertida / sem alterações isquêmicas]"},
{t:"info",x:""},
{t:"info",x:"BIOMARCADORES:"},
{t:"info",x:"Troponina ___ (cutoff ___) — coletada [hora]"},
{t:"info",x:"Repetir em 3h: ___ "},
{t:"info",x:""},
{t:"info",x:"DIAGNÓSTICO:"},
{t:"info",x:"[ ] STEMI parede [___] - PERFUSÃO URGENTE"},
{t:"info",x:"[ ] NSTEMI alto risco (GRACE ≥140 ou critérios MAJOR)"},
{t:"info",x:"[ ] NSTEMI intermediário"},
{t:"info",x:"[ ] Angina instável"},
{t:"info",x:""},
{t:"info",x:"CONDUTA INICIAL (registrada com horário):"},
{t:"info",x:"___:___  AAS 300mg VO mastigado"},
{t:"info",x:"___:___  Clopidogrel 300mg VO (or ticagrelor 180mg, ou prasugrel se ICP)"},
{t:"info",x:"___:___  Atorvastatina 80mg VO"},
{t:"info",x:"___:___  Heparina HBPM ___mg SC (or HNF ___UI bolus + ___UI/h BIC)"},
{t:"info",x:"___:___  Nitrato sl/IV se PAS≥110, sem disfunção VD"},
{t:"info",x:"___:___  Morfina IV ___mg titulada (NUNCA antes de avaliar nitrato)"},
{t:"info",x:""},
{t:"info",x:"ESTRATÉGIA DE REPERFUSÃO (STEMI):"},
{t:"info",x:"[ ] ANGIOPLASTIA PRIMÁRIA: tempo porta-balão estimado ___min"},
{t:"info",x:"   Hemodinâmica acionada às ___:___"},
{t:"info",x:"[ ] FIBRINÓLISE: justificativa: [centro sem hemodinâmica + porta-balão >120min]"},
{t:"info",x:"   Tenecteplase ___mg IV (___:___) — tempo porta-agulha: ___min"},
{t:"info",x:"   Contraindicações verificadas:"},
{t:"info",x:"   [ ] AVC hemorrágico prévio — Ausente"},
{t:"info",x:"   [ ] AVCi <3m — Ausente"},
{t:"info",x:"   [ ] Sangramento ativo — Ausente"},
{t:"info",x:"   [ ] Trauma/cirurgia recente — Ausente"},
{t:"info",x:"   [ ] PA >180/110 controlada — Sim"},
{t:"info",x:""},
{t:"info",x:"AVALIAÇÃO DE REPERFUSÃO (90min pós-fibrinólise):"},
{t:"info",x:"- Resolução do supra ≥50%: [sim/não]"},
{t:"info",x:"- Melhora da dor: [sim/não]"},
{t:"info",x:"- Arritmia de reperfusão: [sim/não]"},
{t:"info",x:"Falha de reperfusão → ICP de resgate transferida"},
{t:"info",x:""},
{t:"info",x:"COMUNICAÇÃO:"},
{t:"info",x:"Familiares informados sobre diagnóstico, prognóstico, riscos da intervenção. Concordância obtida."},
{t:"info",x:""},
{t:"info",x:"ASSINATURA + CARIMBO + CRM"},
],

fisio:"Tempo é músculo. STEMI tem mortalidade que aumenta 1% a cada 30 min de atraso. Documentar TEMPOS é medicolegal essencial. Diretrizes brasileiras (SBC) e internacionais (ESC) definem alvos rígidos.",
mec:[],
diretriz:"SBC IAM 2024. ESC STEMI 2023. ESC NSTEMI 2020.",
fluxo:null,
calcs:[],
},

/* ============== TEMPLATE EVOLUÇÃO — AVC ============== */
{id:"doc-evol-avc", sis:"docs", grav:"alta",
nome:"Template de Evolução — AVC",
sin:["evolução AVC","stroke template","registro médico"],
def:"Modelo de evolução para AVC isquêmico ou hemorrágico. Foco em tempos críticos para trombólise e decisão.",

exames:[
"ELEMENTOS CRÍTICOS:",
"- Horário exato do INÍCIO dos sintomas (ou último visto bem)",
"- Horário da chegada (porta)",
"- Horário do TC crânio (alvo ≤25 min)",
"- Horário da decisão de tratamento",
"- Horário do alteplase (alvo ≤60 min porta-agulha)",
"- NIHSS",
"- Critérios para trombólise (inclusão/exclusão)",
],

rx:[
{etapa:"inicial", d:"TEMPLATE COMPLETO",do:"Copiar e adaptar",via:"—",o:"Documentação medicolegal crítica."},
],

alertas:[
{t:"info",x:"TEMPLATE COMPLETO:"},
{t:"info",x:"═══════════════════════════════════════════════"},
{t:"info",x:"EVOLUÇÃO — SUSPEITA DE AVC"},
{t:"info",x:"═══════════════════════════════════════════════"},
{t:"info",x:"Paciente com início de [sintomas] às ___:___ (informante: paciente/familiar)"},
{t:"info",x:"OU 'Último visto bem' às ___:___"},
{t:"info",x:"Sintomas iniciais: [hemiplegia/parestesia/afasia/disartria/desvio rima/diplopia/tontura/cefaleia]"},
{t:"info",x:"Progressão dos sintomas: [evolução súbita/progressiva, sintomas presentes ainda?]"},
{t:"info",x:""},
{t:"info",x:"Antecedentes: HAS, DM, DLP, FA, AVC prévio, IAM, anticoagulado [varfarina/DOAC]"},
{t:"info",x:"Medicações: ___"},
{t:"info",x:""},
{t:"info",x:"SINAIS VITAIS NA CHEGADA (___:___ — porta):"},
{t:"info",x:"PA ___/___mmHg FC ___bpm FR ___irpm Tax ___ SpO2 ___% Glasgow ___ Glicemia capilar ___"},
{t:"info",x:""},
{t:"info",x:"NIHSS na admissão: ___ pontos"},
{t:"info",x:"(detalhar componentes principais)"},
{t:"info",x:""},
{t:"info",x:"EXAME FÍSICO:"},
{t:"info",x:"- NEURO:"},
{t:"info",x:"  Pares cranianos: [paralisia facial central D/E, desvio olhar para D/E, hemianopsia]"},
{t:"info",x:"  Motor: [paresia/plegia MSD/MSE/MID/MIE]"},
{t:"info",x:"  Sensitivo: [perda em hemicorpo]"},
{t:"info",x:"  Linguagem: [afasia expressiva/receptiva/global/disartria]"},
{t:"info",x:"  Coordenação: [ataxia]"},
{t:"info",x:""},
{t:"info",x:"TC CRÂNIO (___:___) — tempo porta-TC: ___min"},
{t:"info",x:"Achados: [normal/hipodensidade em ___/hemorragia em ___/efeito de massa/desvio linha média]"},
{t:"info",x:"ASPECTS: ___/10"},
{t:"info",x:""},
{t:"info",x:"AVALIAÇÃO:"},
{t:"info",x:"[ ] AVC ISQUÊMICO presumido"},
{t:"info",x:"[ ] AVC HEMORRÁGICO confirmado em TC"},
{t:"info",x:"Janela terapêutica: [___ minutos desde último visto bem]"},
{t:"info",x:""},
{t:"info",x:"DECISÃO DE TROMBÓLISE IV (AVC isquêmico):"},
{t:"info",x:"Critérios de inclusão verificados:"},
{t:"info",x:"[X] AVC isquêmico com déficit neurológico mensurável"},
{t:"info",x:"[X] Início <4,5h do tratamento"},
{t:"info",x:"[X] Idade ≥18 anos"},
{t:"info",x:""},
{t:"info",x:"Critérios de exclusão verificados (TODOS AUSENTES):"},
{t:"info",x:"[ ] Hemorragia em TC — Ausente"},
{t:"info",x:"[ ] AVC ou TCE grave em 3 meses — Ausente"},
{t:"info",x:"[ ] Cirurgia maior em 14 dias — Ausente"},
{t:"info",x:"[ ] Sangramento ativo / coagulopatia (INR>1,7, plaq<100k) — Ausente"},
{t:"info",x:"[ ] PAS>185 ou PAD>110 — Controlada"},
{t:"info",x:"[ ] Glicemia <50 ou >400 — Ausente"},
{t:"info",x:"[ ] Anticoagulação plena (HNF<48h, DOAC<48h) — Ausente"},
{t:"info",x:""},
{t:"info",x:"DECISÃO: [TROMBÓLISE INDICADA] / [TROMBÓLISE NÃO INDICADA: motivo ___]"},
{t:"info",x:""},
{t:"info",x:"CONDUTA (com horários):"},
{t:"info",x:"___:___  Alteplase 0,9mg/kg = ___mg IV (10% em bolus 1min, 90% em 60min)"},
{t:"info",x:"   TEMPO PORTA-AGULHA: ___min"},
{t:"info",x:"___:___  PA monitorizada (alvo <180/105)"},
{t:"info",x:"___:___  NIHSS reavaliado: ___"},
{t:"info",x:""},
{t:"info",x:"CRITÉRIOS PARA TROMBECTOMIA MECÂNICA:"},
{t:"info",x:"[ ] Oclusão de grande artéria (ACM M1, ACA, CI) em TC/angio-TC"},
{t:"info",x:"[ ] NIHSS ≥6"},
{t:"info",x:"[ ] ASPECTS ≥6"},
{t:"info",x:"[ ] Janela <6h (ou até 24h em janela estendida com mismatch)"},
{t:"info",x:"Encaminhamento centro especializado: ___:___"},
{t:"info",x:""},
{t:"info",x:"COMUNICAÇÃO:"},
{t:"info",x:"Riscos da trombólise (hemorragia 6%) explicados. Família ciente, concorda com tratamento."},
{t:"info",x:""},
{t:"info",x:"ASSINATURA + CRM"},
],

fisio:"Tempo é cérebro: cada minuto de AVC isquêmico = 1,9 milhão de neurônios mortos. Janela rígida de 4,5h para trombólise IV (até 24h para trombectomia em casos selecionados). Documentação meticulosa de TEMPOS + CRITÉRIOS é defesa medicolegal essencial.",
mec:[],
diretriz:"AHA/ASA Stroke 2019, atualizações 2021/2023. SBDCV — Diretriz brasileira de AVC.",
fluxo:null,
calcs:[],
},

/* ============== RECEITUÁRIO DE ALTA — ITU BAIXA ============== */
{id:"doc-rec-itu", sis:"docs", grav:"baixa",
nome:"Receituário de Alta — ITU Baixa (Cistite)",
sin:["receita ITU","alta cistite","prescrição cistite"],
def:"Receituário pronto para alta de paciente com cistite não-complicada. Adaptar conforme alergia/gestação/MR locais.",

exames:[
"CRITÉRIOS PARA ALTA:",
"- Paciente estável, sem febre",
"- Sem dor lombar/Giordano (excluir pielonefrite)",
"- Sem comorbidade grave / gestação avançada",
"- Capacidade de tomada medicação VO",
"- Acesso a reavaliação se piora",
],

rx:[
{etapa:"inicial", d:"RECEITUÁRIO MODELO",do:"Adaptar conforme paciente",via:"—",o:"Imprimir em receituário institucional."},
],

alertas:[
{t:"info",x:"═══════════════════════════════════════════════"},
{t:"info",x:"RECEITUÁRIO MÉDICO"},
{t:"info",x:"═══════════════════════════════════════════════"},
{t:"info",x:""},
{t:"info",x:"Paciente: _____________________________________"},
{t:"info",x:""},
{t:"info",x:"Dx: Infecção do Trato Urinário Baixa (Cistite) — CID N30.0"},
{t:"info",x:""},
{t:"info",x:"OPÇÃO 1 — Nitrofurantoína (preferencial; mulher não-gestante)"},
{t:"info",x:"1. Nitrofurantoína 100mg ........... 1 cápsula VO 6/6h por 5 dias"},
{t:"info",x:""},
{t:"info",x:"OPÇÃO 2 — Fosfomicina (dose única, alta adesão)"},
{t:"info",x:"1. Fosfomicina trometamol 3g ....... 1 sachê VO dose única (diluir em água)"},
{t:"info",x:""},
{t:"info",x:"OPÇÃO 3 — SMX-TMP (só se sensibilidade local <20% resist)"},
{t:"info",x:"1. SMX-TMP 800/160mg ............... 1 cp VO 12/12h por 3 dias"},
{t:"info",x:""},
{t:"info",x:"OPÇÃO 4 — Ciprofloxacino (RESERVAR — alta resistência)"},
{t:"info",x:"1. Ciprofloxacino 500mg ............ 1 cp VO 12/12h por 3 dias"},
{t:"info",x:""},
{t:"info",x:"GESTANTE — Cefalexina (1ª linha) ou Amoxicilina+clavulanato"},
{t:"info",x:"1. Cefalexina 500mg ................ 1 cp VO 6/6h por 7 dias"},
{t:"info",x:""},
{t:"info",x:"ADJUVANTES (todos):"},
{t:"info",x:"2. Hidratação oral abundante (≥2L/d)"},
{t:"info",x:"3. Fenazopiridina 100mg ............ 1 cp VO 8/8h por 2 dias (analgésico urinário; urina alaranjada)"},
{t:"info",x:""},
{t:"info",x:"ORIENTAÇÕES NÃO-FARMACOLÓGICAS:"},
{t:"info",x:"- Aumentar ingesta hídrica (≥2 litros/dia)"},
{t:"info",x:"- NÃO segurar a urina"},
{t:"info",x:"- Higiene de frente para trás após uso do banheiro"},
{t:"info",x:"- Esvaziar bexiga antes e após relação sexual"},
{t:"info",x:""},
{t:"info",x:"SINAIS DE ALARME (retornar ao PS):"},
{t:"info",x:"- Febre, calafrios"},
{t:"info",x:"- Dor lombar"},
{t:"info",x:"- Vômitos"},
{t:"info",x:"- Sangue na urina persistente"},
{t:"info",x:"- Sem melhora em 48-72h"},
{t:"info",x:""},
{t:"info",x:"Solicitar urocultura de controle apenas se: gestante, ITU recorrente, falha terapêutica."},
{t:"info",x:""},
{t:"info",x:"Data: __/__/____"},
{t:"info",x:"Médico: _______________________ CRM: ______"},
],

fisio:"ITU baixa não-complicada: tratamento empírico orientado por epidemiologia local. Resistência brasileira ao SMX-TMP e ciprofloxacino é alta. Nitrofurantoína e fosfomicina mantêm boa sensibilidade.",
mec:[],
diretriz:"SBI/SBU Brasil — Diretrizes ITU 2024. IDSA Acute Uncomplicated Cystitis 2011.",
fluxo:null,
calcs:[],
},

/* ============== RECEITUÁRIO DE ALTA — DENGUE ============== */
{id:"doc-rec-dengue", sis:"docs", grav:"media",
nome:"Receituário de Alta — Dengue (Grupo A/B sem sinais alarme)",
sin:["receita dengue","alta dengue","prescrição dengue"],
def:"Modelo de alta para dengue grupo A (sem comorbidade) ou B (com comorbidade, sem sinais de alarme). Incluir cartão de acompanhamento + retornos.",

exames:[
"CRITÉRIOS PARA ALTA:",
"- Estado geral preservado",
"- Tolera VO (sem vômitos persistentes)",
"- Diurese adequada",
"- AUSÊNCIA DE SINAIS DE ALARME: dor abdominal intensa/contínua, vômitos persistentes, sangramento mucoso, letargia/irritabilidade, hipotensão postural, hepatomegalia >2cm, ↑Ht súbita com ↓plaquetas",
"- Hematócrito estável",
],

rx:[
{etapa:"inicial", d:"RECEITUÁRIO + ORIENTAÇÕES",do:"Imprimir e entregar",via:"—",o:"Reavaliação diária OBRIGATÓRIA até 48h pós-defervescência."},
],

alertas:[
{t:"info",x:"═══════════════════════════════════════════════"},
{t:"info",x:"DENGUE — ALTA + ORIENTAÇÕES"},
{t:"info",x:"═══════════════════════════════════════════════"},
{t:"info",x:""},
{t:"info",x:"Paciente: _____________________________________"},
{t:"info",x:"Dx: Dengue (CID A90 — clássico / A91 — hemorrágica)"},
{t:"info",x:"Notificada no SINAN — data: ___"},
{t:"info",x:""},
{t:"info",x:"HIDRATAÇÃO ORAL (FUNDAMENTAL):"},
{t:"info",x:"1. ADULTO: 60-80 mL/kg/dia, sendo 1/3 SRO (sal de reidratação oral) + 2/3 água/sucos"},
{t:"info",x:"   Pacientes 60kg → 4-5 L/dia"},
{t:"info",x:"2. CRIANÇA <12 anos: 10 mL/kg em 1h, depois 100 mL/kg em 24h, sendo 1/3 SRO"},
{t:"info",x:""},
{t:"info",x:"SINTOMÁTICOS:"},
{t:"info",x:"3. Paracetamol 500-750mg ........... 1 cp VO 6/6h se febre ou dor (máx 4g/d)"},
{t:"info",x:"   OU Dipirona 500mg ............... 1 cp VO 6/6h se necessário"},
{t:"info",x:""},
{t:"info",x:"⚠ MEDICAMENTOS PROIBIDOS:"},
{t:"info",x:"- AAS (Aspirina) — risco de sangramento + Síndrome de Reye"},
{t:"info",x:"- AINEs (ibuprofeno, diclofenaco, nimesulida) — risco renal + sangramento"},
{t:"info",x:"- Corticoides — não usar em dengue (controverso, exceto choque)"},
{t:"info",x:""},
{t:"info",x:"REPOUSO RELATIVO. ALIMENTAÇÃO LEVE."},
{t:"info",x:""},
{t:"info",x:"⚠⚠⚠ SINAIS DE ALARME (RETORNAR IMEDIATAMENTE):"},
{t:"info",x:"- Dor abdominal intensa ou contínua"},
{t:"info",x:"- Vômitos persistentes (≥3 episódios/h)"},
{t:"info",x:"- Sangramento (gengival, nasal, fezes pretas, urina sangue)"},
{t:"info",x:"- Diminuição da urina"},
{t:"info",x:"- Sonolência, letargia ou irritabilidade"},
{t:"info",x:"- Dificuldade para respirar"},
{t:"info",x:"- Confusão mental"},
{t:"info",x:"- Pele fria, suor, palidez (sinais de choque)"},
{t:"info",x:"- Tontura ao levantar"},
{t:"info",x:""},
{t:"info",x:"⚠ DIA CRÍTICO: 4-7 dia da doença (queda da febre)"},
{t:"info",x:"   90% das complicações ocorrem nesse período."},
{t:"info",x:""},
{t:"info",x:"REAVALIAÇÃO MÉDICA:"},
{t:"info",x:"GRUPO A: retorno em 24h se persistência da febre, ou no 1º dia sem febre."},
{t:"info",x:"GRUPO B: reavaliação DIÁRIA até 48h pós-defervescência."},
{t:"info",x:""},
{t:"info",x:"REPETIR EXAMES:"},
{t:"info",x:"Hemograma a cada 24h até 48h pós-defervescência (Ht/plaquetas)"},
{t:"info",x:""},
{t:"info",x:"PROFILAXIA DOMICILIAR:"},
{t:"info",x:"- Eliminar criadouros do Aedes (água parada)"},
{t:"info",x:"- Uso de repelente"},
{t:"info",x:"- Familiares com sintomas: avaliar"},
{t:"info",x:""},
{t:"info",x:"Data: __/__/____"},
{t:"info",x:"Médico: ______________________ CRM: _______"},
],

fisio:"Dengue tem 3 fases: febril (1-5 dias), crítica (5-7 dias — extravasamento plasmático), recuperação (>7 dias). Defervescência é momento CRÍTICO — paciente pode parecer melhor mas estar entrando em choque. Reavaliação diária é essencial no grupo B.",
mec:[],
diretriz:"MS Brasil — Dengue: Diagnóstico e Manejo Clínico 2024. WHO Dengue 2024.",
fluxo:null,
calcs:[],
},

/* ============== RECEITUÁRIO ALTA — GASTROENTERITE ============== */
{id:"doc-rec-gea", sis:"docs", grav:"baixa",
nome:"Receituário de Alta — Gastroenterite Aguda",
sin:["receita gastroenterite","diarreia alta"],
def:"Modelo de alta para gastroenterite aguda em adulto/criança com desidratação leve a moderada compensada.",

exames:[
"CRITÉRIOS PARA ALTA:",
"- Desidratação leve corrigida ou ausente",
"- Tolera VO",
"- Sem sinais de gravidade (choque, alteração consciência, sangue nas fezes intenso)",
"- Suporte familiar / acesso a retorno",
],

rx:[
{etapa:"inicial", d:"PRESCRIÇÃO DE ALTA",do:"Modelo a copiar",via:"—",o:"Adaptar peso e idade."},
],

alertas:[
{t:"info",x:"═══════════════════════════════════════════════"},
{t:"info",x:"GASTROENTERITE — ALTA + ORIENTAÇÕES"},
{t:"info",x:"═══════════════════════════════════════════════"},
{t:"info",x:""},
{t:"info",x:"Dx: Gastroenterite aguda (CID A09)"},
{t:"info",x:""},
{t:"info",x:"HIDRATAÇÃO ORAL (PRIORIDADE):"},
{t:"info",x:"1. SRO (sal de reidratação oral, sachê na água)"},
{t:"info",x:"   ADULTO: 200 mL após cada episódio de diarreia/vômito"},
{t:"info",x:"   CRIANÇA: 50-100 mL/kg em 4 horas se desidratação leve"},
{t:"info",x:""},
{t:"info",x:"SINTOMÁTICOS:"},
{t:"info",x:"2. Ondansetrona 4-8mg ........... 1 cp VO 8/8h se vômitos (máx 24mg/d)"},
{t:"info",x:"   ou Bromoprida 10mg ............. 1 cp VO 8/8h"},
{t:"info",x:"3. Racecadotrila 100mg ........... 1 cp VO 8/8h por até 7 dias (anti-secretor)"},
{t:"info",x:"4. Probiótico: Saccharomyces boulardii ou Lactobacillus ........... 1 sachê VO 1-2×/d × 5 dias"},
{t:"info",x:""},
{t:"info",x:"⚠ EVITAR:"},
{t:"info",x:"- Loperamida em diarreia COM sangue ou febre (risco megacólon)"},
{t:"info",x:"- Antibiótico NÃO está indicado na maioria (vírus 80%)"},
{t:"info",x:"  Indicar ATB SE: febre alta + leucócitos fecais + disenteria + viagem recente + imunossuprimido"},
{t:"info",x:""},
{t:"info",x:"ALIMENTAÇÃO:"},
{t:"info",x:"- Dieta normal (NÃO suspender). Evitar gorduras, doces, lactose se intolerância."},
{t:"info",x:"- Em crianças: MANTER amamentação."},
{t:"info",x:"- BRAT (banana, arroz, maçã, torrada) — útil mas não obrigatório."},
{t:"info",x:""},
{t:"info",x:"⚠ SINAIS DE ALARME (retornar):"},
{t:"info",x:"- Vômitos persistentes (>24h)"},
{t:"info",x:"- Sangue nas fezes vermelho-vivo"},
{t:"info",x:"- Febre persistente >48h"},
{t:"info",x:"- Sinais de desidratação grave: pouca urina, mucosas secas, sonolência"},
{t:"info",x:"- Em criança: choro sem lágrimas, fontanela deprimida"},
{t:"info",x:""},
{t:"info",x:"PROFILAXIA — HIGIENE:"},
{t:"info",x:"- Lavar as mãos com sabão (especialmente antes refeições e após banheiro)"},
{t:"info",x:"- Água filtrada/fervida"},
{t:"info",x:"- Alimentos bem cozidos"},
{t:"info",x:""},
{t:"info",x:"Data: __/__/____"},
{t:"info",x:"Médico: ______________________ CRM: _______"},
],

fisio:"Gastroenterite: 80% viral (rotavírus, norovírus, adenovírus). 20% bacteriana (E. coli, Salmonella, Shigella, Campylobacter). Manejo é hidratação. ATB raramente indicado e pode piorar (S. enterotoxigênica produz toxina shiga = SHU).",
mec:[],
diretriz:"WHO Diarrhoea 2024. IDSA Infectious Diarrhea 2017. SBP — Diarreia Aguda 2017.",
fluxo:null,
calcs:[],
},

);
