/* ===========================================================
   VOVÔMINIC EMERGÊNCIA — BIBLIOTECA DE MEDICAÇÕES (PARTE 23)
   Anticonvulsivantes Ambulatoriais (uso crônico — manutenção)
   Carbamazepina, Valproato, Lamotrigina, Levetiracetam, Oxcarbazepina, Gabapentina, Pregabalina, Topiramato
   =========================================================== */

MEDICACOES.push(

/* ============== CARBAMAZEPINA ============== */

{id:"med-carbamazepina", classe:"Anticonvulsivante — bloqueador canal sódio + estabilizador de humor", grupo:"neuro",
nome:"Carbamazepina",
sin:["Tegretol","Tegretard","Carbazina"],
formas:["Comprimido 200 mg, 400 mg","Comprimido CR (controlled release) 200 mg, 400 mg","Suspensão 20 mg/mL (raro)","REMUME — FARMASUS (controle especial)"],
resumo:"⚠ ANTICONVULSIVANTE clássico — 1ª linha em epilepsia FOCAL e em ⚠ NEURALGIA DO TRIGÊMEO (fármaco de escolha). Também: estabilizador de humor (bipolar), neuropatia. ⚠ POTENTE INDUTOR ENZIMÁTICO — múltiplas interações. ⚠ Stevens-Johnson em HLA-B*1502 (asiáticos) — testar antes em populações de risco.",
dose_rapida:"200 mg 12/12h titular a 400-1200 mg/d ÷ 12/12h",
doses:[
{ind:"⚠ EPILEPSIA FOCAL (1ª linha)", dose:"200 mg VO 12/12h × 1 sem, depois aumentar 200 mg/sem até dose alvo. Habitual 400-1200 mg/d ÷ 12/12h. Máx 1600 mg/d", obs:"⚠ Iniciar lento — efeitos colaterais dose-dependentes (tontura, ataxia, sedação). Auto-induz metabolismo nas primeiras 2-4 sem (dose precisa subir)."},
{ind:"⚠ ⚠ NEURALGIA DO TRIGÊMEO — 1ª LINHA", dose:"100-200 mg VO 12/12h, titular a 200-1200 mg/d ÷ 12/12h conforme dor", obs:"⚠ Excelente eficácia. Reduzir gradativamente após meses de controle."},
{ind:"⚠ NEURALGIA PÓS-HERPÉTICA (alternativa)", dose:"100-400 mg/d", obs:""},
{ind:"⚠ TRANSTORNO BIPOLAR — alternativa ao lítio", dose:"400-1200 mg/d", obs:"⚠ Psiquiatria. Não usar isolado em depressão bipolar."},
{ind:"Síndrome de retirada de álcool grave", dose:"200 mg 8/8h × 5-7 dias", obs:""},
{ind:"Diabetes insipidus central (off-label)", dose:"100-300 mg/d", obs:""},
],
ajustes:{
irc:"Sem ajuste rotineiro",
iht:"⚠ Reduzir em IH",
idoso:"⚠ Iniciar 100 mg 12/12h. Maior risco SIADH-hiponatremia, sedação, queda.",
gestante:"⚠ ⚠ D — TERATOGÊNICA (espinha bífida 0,5-1%, anomalias craniofaciais, atrasos desenvolvimento). Em mulher idade fértil: usar contracepção + ácido fólico 5 mg/d antes da gestação. ⚠ ⚠ Trocar para LAMOTRIGINA ou LEVETIRACETAM antes da gestação se possível.",
aleita:"Cautela — passa pelo leite (orientar sonolência, anorexia no lactente)",
ped:"≥6a aprovada. Doses por peso.",
},
mecanismo:"⚠ BLOQUEIA CANAL DE SÓDIO DEPENDENTE DE VOLTAGEM no neurônio → estabiliza membrana → reduz disparo neuronal repetitivo. Auto-induz CYP3A4 → meia-vida REDUZ ao longo do tratamento.",
farmacocin:{
absorc:"VO ~80% (lenta, irregular)",
distrib:"Ampla, atravessa BHE",
metab:"⚠ Hepático CYP3A4 — INDUTOR FORTE (CYP3A4, CYP2C9, CYP2C19, GP-P) + AUTO-INDUTOR",
elimin:"Renal + fecal",
meiavida:"⚠ 25-65h inicial, REDUZ para 12-17h após auto-indução (em 2-4 sem)",
ligacao:"~75%",
},
ef_colats:{
comuns:["Tontura","Ataxia","Diplopia","Sonolência","Náusea","Cefaleia","Rash","⚠ HIPONATREMIA (SIADH) — frequente em idoso"],
sérios:["⚠ ⚠ STEVENS-JOHNSON / NET — risco AUMENTADO em portadores de HLA-B*1502 (asiáticos — sul/leste Ásia, indígenas brasileiros podem ter). ⚠ Testar HLA-B*1502 em populações de risco antes de iniciar.","⚠ AGRANULOCITOSE / ANEMIA APLÁSICA (raro mas grave)","⚠ HEPATITE","⚠ SIADH / hiponatremia","⚠ TERATOGENICIDADE","⚠ Síndrome DRESS","Insuficiência cardíaca em alto grau","Bloqueio AV"],
},
interacoes:["⚠ ⚠ INDUTOR POTENTE CYP3A4 — REDUZ MUITAS DROGAS: warfarina, anticoncepcionais (FALHA), corticoides, ciclosporina, antifúngicos, ISRS, antipsicóticos atípicos, antirretrovirais, DOACs, ouros anticonvulsivantes (valproato, lamotrigina)","⚠ INIBIDORES CYP3A4 (macrolídeos, azólicos, fluoxetina, verapamil, diltiazem, suco de toranja): ↑↑ carbamazepina","⚠ Lítio: neurotoxicidade","Isoniazida: ↑ ambas, hepato"],
contraindicacoes:["⚠ Hipersensibilidade","Bloqueio AV","Porfiria aguda","Histórico de aplasia/agranulocitose por droga","HLA-B*1502 positivo (relativa)","Uso concomitante com IMAO (14 dias)"],
monit:["⚠ Hemograma — basal + a cada 1-3 meses inicialmente","⚠ Função hepática","⚠ Sódio sérico em idoso","Nível sérico (terapêutico 4-12 µg/mL)","Sinais cutâneos — IMEDIATA suspensão se rash"],
gravidez:"⚠ D",
sus:"⚠ REMUME — FARMASUS",
referencias:["NICE Epilepsy; ABE."],
},

/* ============== ÁCIDO VALPROICO / VALPROATO ============== */

{id:"med-valproato", classe:"Anticonvulsivante de amplo espectro + estabilizador de humor", grupo:"neuro",
nome:"Ácido Valproico / Divalproato de Sódio",
sin:["Depakote","Depakene","Valpakine","Epilim"],
formas:["Comprimido 250 mg, 500 mg","Comprimido ER 250 mg, 500 mg","Cápsula 250 mg","Solução oral 50 mg/mL","Frasco-ampola IV 100 mg/mL","REMUME — FARMASUS"],
resumo:"⚠ ANTICONVULSIVANTE DE AMPLO ESPECTRO — cobre TODAS as crises (focais, generalizadas tônico-clônicas, ausência, mioclônicas) — 1ª linha em ⚠ EPILEPSIA GENERALIZADA IDIOPÁTICA / ausência / mioclonias. Também: ⚠ ESTABILIZADOR DE HUMOR em bipolar (mania aguda), profilaxia de migrânea. ⚠ ⚠ TERATOGÊNICO POTENTE — categoria X em algumas indicações (espinha bífida 2-3%, defeitos cognitivos importantes).",
dose_rapida:"250 mg 12/12h titular a 750-2000 mg/d ÷ 12/12h (10-60 mg/kg/d)",
doses:[
{ind:"⚠ EPILEPSIA GENERALIZADA (ausência, mioclônica, tônico-clônica primária)", dose:"500-2500 mg/d ÷ 12/12h (10-60 mg/kg/d). Iniciar 250-500 mg/d, titular gradativo", obs:"⚠ 1ª linha em síndrome epiléptica generalizada. ⚠ Pior eficácia em focal (mas cobre)."},
{ind:"⚠ Estado epiléptico — alternativa a fenitoína", dose:"20-40 mg/kg IV bolus, depois 1-2 mg/kg/h", obs:""},
{ind:"⚠ MANIA AGUDA (bipolar)", dose:"15-20 mg/kg/d, titular a 500-1500 mg/d", obs:""},
{ind:"⚠ Profilaxia de MIGRÂNEA", dose:"250-500 mg/d", obs:""},
{ind:"⚠ Demência com agressão (off-label)", dose:"250-500 mg/d", obs:""},
],
ajustes:{
irc:"Pequeno ajuste em TFG <30",
iht:"⚠ ⚠ EVITAR em IH ativa (hepatotoxicidade)",
idoso:"⚠ Reduzir dose. Maior risco hepatotoxicidade, plaquetopenia.",
gestante:"⚠ ⚠ ⚠ X / D — ⚠ TERATOGÊNICO POTENTE: espinha bífida 2-3%, defeitos cardíacos, cognitivos. ⚠ ⚠ EVITAR EM MULHER IDADE FÉRTIL sem contracepção rigorosa. Em epilepsia / bipolar gestante: trocar para lamotrigina / levetiracetam pré-concepcional.",
aleita:"Compatível em baixa dose",
ped:"≥10a. Crianças <2a: risco aumentado hepatotoxicidade FATAL.",
},
mecanismo:"⚠ Múltiplos: ↑ GABA + bloqueia canal Na + bloqueia canal Ca tipo T (relevante em ausência) + outros mecanismos.",
farmacocin:{
absorc:"VO ~100%",
distrib:"Ampla",
metab:"Hepático (UGT, CYP2C9)",
elimin:"Renal",
meiavida:"~9-16h",
ligacao:"~90% — alta",
},
ef_colats:{
comuns:["Náusea / GI (mais frequente com comprimido vs ER)","⚠ GANHO DE PESO","⚠ TREMOR","⚠ ALOPECIA (reversível)","Sonolência","Trombocitopenia leve","Hiperamonemia leve"],
sérios:["⚠ ⚠ HEPATOTOXICIDADE FATAL — especialmente <2 anos em politerapia, doenças metabólicas (POLG mutações)","⚠ PANCREATITE","⚠ HIPERAMONEMIA com encefalopatia (em alguns sem hepatite franca)","⚠ TROMBOCITOPENIA + disfunção plaquetária","⚠ ⚠ TERATOGENICIDADE GRAVE","⚠ SÍNDROME DRESS","Hiperandrogenismo / SOP em mulher","Síndrome Parkinsoniana em idoso"],
},
interacoes:["⚠ INIBIDOR CYP / UGT — ↑ LAMOTRIGINA (risco SJS — usar dose lamotrigina REDUZIDA quando combinar), fenitoína, fenobarbital","⚠ Carbamazepina: ↓ valproato","⚠ AAS, AINE: deslocam valproato livre","Topiramato: hiperamonemia","Carbapenêmicos (meropenem): ↓↓ valproato → risco convulsão"],
contraindicacoes:["⚠ ⚠ IH ativa ou histórico","⚠ Doenças metabólicas (POLG, distúrbio ureia)","⚠ Pancreatite prévia","⚠ Mulher idade fértil sem contracepção (relativa — discussão compartilhada)","⚠ Gestação (categoria X em algumas indicações — bipolar, migrânea)","Discrasia sanguínea","Hipersensibilidade","Porfiria"],
monit:["⚠ TGO/TGP — basal + a cada 1-3 meses","⚠ Hemograma + plaquetas","⚠ Amilase / lipase em dor abdominal","Amônia em encefalopatia","Nível sérico (terapêutico 50-100 µg/mL)","Peso"],
gravidez:"⚠ ⚠ X (bipolar/migrânea); D (epilepsia)",
sus:"⚠ REMUME — FARMASUS",
referencias:["NICE Epilepsy; ABE; ⚠ EMA Pregnancy Prevention Programme Valproato 2018."],
},

/* ============== LAMOTRIGINA ============== */

{id:"med-lamotrigina", classe:"Anticonvulsivante de amplo espectro + estabilizador (depressão bipolar)", grupo:"neuro",
nome:"Lamotrigina",
sin:["Lamictal","Neural","Lamotrix"],
formas:["Comprimido 25 mg, 50 mg, 100 mg, 200 mg","Comprimido dispersível 5 mg, 25 mg","⚠ CEAF (PCDT-MS epilepsia refratária) — algumas SES dispõem em FARMASUS"],
resumo:"⚠ ANTICONVULSIVANTE DE AMPLO ESPECTRO — eficaz em FOCAL + GENERALIZADA. ⚠ INDICAÇÃO ESPECIAL EM PSIQUIATRIA: ⚠ ⚠ DEPRESSÃO BIPOLAR / PROFILAXIA DE FASE DEPRESSIVA — único estabilizador eficaz em depressão. ⚠ ⚠ TITULAÇÃO MUITO LENTA OBRIGATÓRIA — risco de Stevens-Johnson em titulação rápida (especialmente com valproato concomitante).",
dose_rapida:"25 mg/d × 2 sem → 50 mg/d × 2 sem → 100 mg/d (epilepsia ~200-400 mg/d; bipolar 200 mg/d)",
doses:[
{ind:"⚠ EPILEPSIA FOCAL e GENERALIZADA — monoterapia", dose:"⚠ ⚠ TITULAÇÃO LENTA: 25 mg/d × 2 sem → 50 mg/d × 2 sem → 100 mg/d × 1 sem → 200 mg/d. Alvo 200-500 mg/d ÷ 12/12h", obs:"⚠ Não pular etapas. SJS / NET em titulação rápida."},
{ind:"⚠ EPILEPSIA com VALPROATO concomitante", dose:"⚠ DOSE METADE: 25 mg cada 48h × 2 sem → 25 mg/d × 2 sem → 50 mg/d. Alvo 100-200 mg/d", obs:"⚠ ⚠ Valproato INIBE metabolismo da lamotrigina → ↑↑ nível → ↑ risco SJS."},
{ind:"⚠ EPILEPSIA com CARBAMAZEPINA / fenobarbital / fenitoína (indutores) concomitante", dose:"⚠ DOSE DOBRADA: 50 mg/d × 2 sem → 100 mg/d × 2 sem → 200 mg/d. Alvo 300-500 mg/d", obs:""},
{ind:"⚠ ⚠ DEPRESSÃO BIPOLAR / profilaxia fase depressiva — psiquiatria", dose:"25 mg/d × 2 sem → 50 mg/d × 2 sem → 100 mg/d × 1 sem → 200 mg/d. Alvo 100-200 mg/d", obs:"⚠ NÃO eficaz em mania aguda. NÃO eficaz como antidepressivo em depressão unipolar."},
{ind:"Síndrome de Lennox-Gastaut", dose:"Conforme acima", obs:"Pediatria."},
],
ajustes:{
irc:"⚠ TFG <30: redução 25-50%",
iht:"⚠ Reduzir em IH",
idoso:"⚠ Iniciar baixo, titular lento",
gestante:"⚠ C — UM DOS ANTICONVULSIVANTES MAIS SEGUROS NA GESTAÇÃO. PREFERIDO sobre valproato/carbamazepina. ⚠ Nível pode CAIR no 3º trimestre — pode precisar ↑ dose, depois reduzir pós-parto.",
aleita:"⚠ Compatível mas monitor lactente (rash, sedação)",
ped:"≥2a (com supervisão neurológica)",
},
mecanismo:"⚠ Bloqueia canal SÓDIO DEPENDENTE DE VOLTAGEM → estabiliza membrana neuronal. ↓ liberação glutamato.",
farmacocin:{
absorc:"VO ~98%",
distrib:"Ampla",
metab:"⚠ Hepático UGT — ⚠ inibido por valproato; ⚠ induzido por carbamazepina, fenitoína, fenobarbital, ACO",
elimin:"Renal",
meiavida:"~25h (monoterapia); ~60h (com valproato); ~15h (com indutores)",
ligacao:"~55%",
},
ef_colats:{
comuns:["Tontura","Cefaleia","Visão turva","Náusea","Diplopia","⚠ RASH leve em ~10% — INTERROMPER IMEDIATAMENTE"],
sérios:["⚠ ⚠ ⚠ STEVENS-JOHNSON / NET — risco maior em titulação rápida + valproato + criança. Mortalidade significativa. ⚠ INTERROMPER imediatamente ao primeiro sinal de rash sistêmico.","⚠ DRESS (Drug Reaction with Eosinophilia and Systemic Symptoms)","⚠ Síndrome de HEMOFAGOCITOSE","Insônia","Tremor","Ataxia"],
},
interacoes:["⚠ ⚠ VALPROATO: ↑↑ lamotrigina — dose metade, titulação ULTRA-LENTA","⚠ INDUTORES (carbamazepina, fenitoína, fenobarbital, rifampicina): ↓↓ — dose DOBRADA","⚠ ACO combinado: ↓ lamotrigina (etinilestradiol induz UGT) — pode haver flutuação nível durante ciclo. ⚠ Ao interromper ACO: lamotrigina pode subir até toxicidade."],
contraindicacoes:["⚠ Hipersensibilidade","⚠ Histórico de rash por lamotrigina"],
monit:["⚠ ⚠ Rash — orientar paciente: QUALQUER rash = parar e procurar emergência","Nível sérico (terapêutico 3-15 µg/mL — útil em gestação)","Resposta clínica"],
gravidez:"C (uma das mais seguras)",
sus:"⚠ CEAF — PCDT-MS Epilepsia refratária. FARMASUS em algumas SES.",
referencias:["NICE Epilepsy; APA Bipolar; ABE."],
},

/* ============== LEVETIRACETAM ============== */

{id:"med-levetiracetam", classe:"Anticonvulsivante de amplo espectro — moderno", grupo:"neuro",
nome:"Levetiracetam",
sin:["Keppra","Levbio","Levertan"],
formas:["Comprimido 250 mg, 500 mg, 750 mg, 1000 mg","Comprimido XR 500 mg, 750 mg","Solução oral 100 mg/mL","Frasco-ampola IV 500 mg/5 mL","⚠ CEAF — PCDT-MS Epilepsia refratária"],
resumo:"⚠ ⚠ ANTICONVULSIVANTE MODERNO — PERFIL DE TOLERABILIDADE EXCELENTE. AMPLO espectro (focal + generalizada). Vantagens: NÃO metabolizado pelo CYP (sem interações importantes), TITULAÇÃO RÁPIDA possível, sem teratogenicidade significativa (dos mais seguros na gestação), pode ser IV. ⚠ Desvantagem: pode causar IRRITABILIDADE / AGRESSIVIDADE / depressão (frequente — perguntar ativamente).",
dose_rapida:"500 mg 12/12h, titular a 1000-3000 mg/d ÷ 12/12h",
doses:[
{ind:"⚠ EPILEPSIA FOCAL e GENERALIZADA — monoterapia ou adjunto", dose:"500 mg VO 12/12h × 2 sem, depois 1000 mg 12/12h. Alvo 1000-3000 mg/d ÷ 12/12h. Máx 3000 mg/d", obs:"⚠ Titulação RÁPIDA possível (diferença para lamotrigina, carbamazepina). Em emergência epiléptica IV: dose pronta de carga."},
{ind:"⚠ Estado epiléptico — alternativa IV", dose:"60 mg/kg IV bolus em 15 min, depois manutenção", obs:"⚠ Alternativa segura em paciente sem acesso fácil a fenitoína IV / em criança."},
{ind:"⚠ Profilaxia anti-convulsivante em TCE / pós-cirurgia neurológica", dose:"500-1500 mg 12/12h × 7 dias", obs:""},
{ind:"⚠ Gestante com epilepsia que precisa de troca", dose:"Esquema padrão", obs:"⚠ Junto com lamotrigina, é o ANTICONVULSIVANTE PREFERIDO na gestação."},
],
ajustes:{
irc:"⚠ AJUSTE pela TFG: 50-80: 500-1000 mg 12/12h. 30-49: 250-750 mg 12/12h. <30: 250-500 mg 12/12h. HD: pós-sessão.",
iht:"Sem ajuste",
idoso:"⚠ Ajustar pela TFG (frequentemente reduzida)",
gestante:"⚠ ⚠ C — ⚠ UM DOS PREFERIDOS NA GESTAÇÃO (junto com lamotrigina). Sem aumento significativo de defeitos congênitos. ⚠ Nível pode CAIR no 2º-3º trimestre — pode precisar ↑ dose.",
aleita:"⚠ Compatível",
ped:"≥1 mês aprovada",
},
mecanismo:"⚠ MECANISMO ÚNICO — liga-se à PROTEÍNA DA VESÍCULA SINÁPTICA SV2A → modula liberação de neurotransmissores. Bloqueia canais Ca de alta voltagem.",
farmacocin:{
absorc:"VO ~100%",
distrib:"Ampla",
metab:"⚠ MÍNIMO METABOLISMO (24%) — SEM CYP → SEM INTERAÇÕES MEDICAMENTOSAS IMPORTANTES (vantagem MAIOR)",
elimin:"Renal (~66% inalterada)",
meiavida:"~6-8h",
ligacao:"<10%",
},
ef_colats:{
comuns:["⚠ ⚠ IRRITABILIDADE / AGRESSIVIDADE / mudanças de humor — em até 20% (perguntar ativamente)","⚠ DEPRESSÃO / ideação suicida (raro mas descrito)","Sonolência","Cefaleia","Astenia","Tontura"],
sérios:["⚠ Eventos psiquiátricos (psicose, agitação) — raros mas reportados","Suicidalidade","Reações cutâneas (raras)","Pancreatite (raro)"],
},
interacoes:["⚠ ⚠ MÍNIMAS INTERAÇÕES — vantagem clínica MAIOR"],
contraindicacoes:["⚠ Hipersensibilidade","Histórico psiquiátrico severo (relativa — monitorar)"],
monit:["⚠ ⚠ HUMOR / SINTOMAS PSIQUIÁTRICOS — perguntar ativamente em consulta","Função renal","Nível sérico (terapêutico 12-46 µg/mL — pouco usado)","Resposta clínica"],
gravidez:"C (um dos mais seguros)",
sus:"⚠ CEAF — PCDT-MS Epilepsia refratária / Farmasus em algumas SES",
referencias:["NICE; ABE; ⚠ EPILEPSIA na gestação (UK Pregnancy Register)."],
},

/* ============== OXCARBAZEPINA ============== */

{id:"med-oxcarbazepina", classe:"Anticonvulsivante — bloqueador canal sódio (relacionado à carbamazepina)", grupo:"neuro",
nome:"Oxcarbazepina",
sin:["Trileptal","Oxcarb","Oleptal"],
formas:["Comprimido 300 mg, 600 mg","Suspensão oral 60 mg/mL","REMUME — FARMASUS"],
resumo:"⚠ ANÁLOGO DA CARBAMAZEPINA — pro-droga MHD. Vantagens: MENOS interações que carbamazepina (não auto-induz tão fortemente), MENOS efeitos colaterais cognitivos, sem necessidade de monitor hematológico tão rigoroso. ⚠ Desvantagem: MAIOR risco de HIPONATREMIA (até 30% em idoso) que carbamazepina. ⚠ Indicações: epilepsia focal, neuralgia do trigêmeo (alternativa).",
dose_rapida:"300 mg 12/12h titular a 600-1200 mg/d ÷ 12/12h",
doses:[
{ind:"⚠ EPILEPSIA FOCAL", dose:"300 mg VO 12/12h × 1 sem, titular 300 mg/sem. Alvo 600-2400 mg/d ÷ 12/12h", obs:""},
{ind:"⚠ NEURALGIA DO TRIGÊMEO (alternativa)", dose:"150-300 mg 12/12h, titular a 600-1200 mg/d", obs:"Quando carbamazepina não tolerada."},
{ind:"Bipolar (alternativa)", dose:"600-2400 mg/d", obs:""},
],
ajustes:{
irc:"⚠ TFG <30: 50% dose inicial",
iht:"Sem ajuste rotineiro",
idoso:"⚠ Iniciar 150 mg 12/12h. ⚠ ⚠ Monitor sódio rigorosamente — risco SIADH-hiponatremia muito mais alto que carbamazepina (até 30%).",
gestante:"⚠ C — Cautela. Lamotrigina/levetiracetam preferidos.",
aleita:"Cautela",
ped:"≥4a",
},
mecanismo:"PRO-DROGA → MHD (10,11-mono-hidroxi) → bloqueia canal Na dependente de voltagem.",
farmacocin:{
absorc:"VO ~100%",
distrib:"Ampla",
metab:"⚠ Hepático — INDUTOR MODERADO CYP3A4 (menos potente que carbamazepina) + auto-indutor menor",
elimin:"Renal",
meiavida:"~9h (MHD)",
ligacao:"~40%",
},
ef_colats:{
comuns:["⚠ ⚠ HIPONATREMIA — até 30% em idoso (frequente, monitor)","Tontura","Sonolência","Cefaleia","Náusea","Visão turva, diplopia","Ataxia"],
sérios:["⚠ SIADH grave","Stevens-Johnson (menor risco que carbamazepina mas existe)","DRESS","Hepatotoxicidade rara"],
},
interacoes:["⚠ INDUTOR CYP3A4 — reduz: ACO (FALHA), warfarina, ciclosporina, antifúngicos","INIBIDORES (verapamil): ↑ oxcarbazepina","Outros anticonvulsivantes"],
contraindicacoes:["⚠ Hipersensibilidade a oxcarbazepina/carbamazepina (50% cruzada)","Bloqueio AV"],
monit:["⚠ ⚠ SÓDIO — basal + 2-4 sem + a cada 3-6m em idoso","Função hepática","Sinais cutâneos"],
gravidez:"C",
sus:"REMUME — FARMASUS",
referencias:["NICE; ABE."],
},

/* ============== GABAPENTINA ============== */

{id:"med-gabapentina", classe:"Anticonvulsivante / antineurálgico — modulador de canal de cálcio α2δ", grupo:"neuro",
nome:"Gabapentina",
sin:["Neurontin","Gabaneurin","Gamibetal"],
formas:["Cápsula 300 mg, 400 mg","Comprimido 600 mg, 800 mg","⚠ CEAF (PCDT-MS dor neuropática refratária) — particular comum"],
resumo:"⚠ INDICAÇÃO MAIS COMUM HOJE: ⚠ DOR NEUROPÁTICA — diabética, pós-herpética, lombociatalgia neuropática, fibromialgia. ⚠ Em epilepsia: hoje 2ª linha (lamotrigina, levetiracetam, oxcarbazepina preferidas em focal). ⚠ Vantagem: poucas interações. ⚠ Desvantagem: PERFIL DE ABUSO (sedação, euforia em alta dose — uso recreativo crescente), eficácia modesta em dor (NNT ~6).",
dose_rapida:"300 mg HS dia 1 → 300 mg 12/12h dia 2 → 300 mg 8/8h dia 3 → titular conforme efeito até 900-3600 mg/d",
doses:[
{ind:"⚠ DOR NEUROPÁTICA (diabética, pós-herpética)", dose:"Iniciar 300 mg HS, titular gradualmente até 900-3600 mg/d ÷ 8/8h", obs:"⚠ Eficácia gradual — pode levar 2-4 sem para ver efeito. NNT ~6. ⚠ Pregabalina tem eficácia similar, posologia mais simples (2×/d), mas mesmo risco abuso."},
{ind:"⚠ Epilepsia focal (adjunto)", dose:"900-3600 mg/d ÷ 8/8h", obs:"⚠ 2ª linha hoje."},
{ind:"⚠ Síndrome das pernas inquietas", dose:"300-1800 mg HS", obs:""},
{ind:"⚠ Abstinência alcoólica leve (alternativa BZD)", dose:"600-1200 mg/d ÷ 8/8h × 7 dias", obs:""},
{ind:"⚠ Ansiedade generalizada (off-label, adjunto)", dose:"900-3600 mg/d", obs:""},
{ind:"⚠ Climatério — fogachos refratários a TRH", dose:"600-2400 mg/d ÷ 8/8h", obs:""},
],
ajustes:{
irc:"⚠ AJUSTE pela TFG: 50-79: 600-1800 mg/d ÷ 8/8h. 30-49: 300-900. 15-29: 150-600. <15: 150-300. HD: pós.",
iht:"Sem ajuste",
idoso:"⚠ Iniciar 300 mg/d, titular lento. Avaliar TFG.",
gestante:"⚠ C — dados limitados",
aleita:"Cautela",
ped:"≥3a (epilepsia)",
},
mecanismo:"⚠ Liga-se à SUBUNIDADE α2δ do canal de CÁLCIO dependente de voltagem → reduz liberação de glutamato. ⚠ NÃO atua diretamente no GABA (apesar do nome).",
farmacocin:{
absorc:"⚠ ⚠ ABSORÇÃO SATURÁVEL — biodisp DIMINUI com dose (60% a 900 mg/d; 35% a 3600 mg/d). Dividir doses melhora absorção.",
distrib:"Ampla",
metab:"⚠ NÃO metabolizada",
elimin:"⚠ Renal 100% (inalterada)",
meiavida:"~5-7h",
ligacao:"<3%",
},
ef_colats:{
comuns:["⚠ Sonolência","Tontura","Ataxia","Edema periférico","Ganho de peso","Fadiga","Visão turva"],
sérios:["⚠ Suicidalidade (sinal nominal)","⚠ ⚠ POTENCIAL DE ABUSO crescente — euforia, sedação em altas doses, mistura com opioides/álcool → ↑ depressão respiratória","Depressão respiratória + opioide","Rash","Edema generalizado"],
},
interacoes:["⚠ Antiácidos com Al/Mg: ↓ absorção (separar 2h)","Opioides: depressão respiratória somativa","Álcool, BZD: sedação somativa","Morfina: ↑ gabapentina"],
contraindicacoes:["Hipersensibilidade","Cautela em paciente com história de uso de substâncias"],
monit:["Função renal","Sedação","Sintomas humor / suicidalidade","Sinais de abuso"],
gravidez:"C",
sus:"⚠ CEAF — PCDT-MS Dor crônica neuropática refratária",
referencias:["NICE Neuropathic Pain; ⚠ FDA Warning Respiratory Depression 2019."],
},

/* ============== PREGABALINA ============== */

{id:"med-pregabalina", classe:"Antineurálgico / anticonvulsivante — modulador α2δ", grupo:"neuro",
nome:"Pregabalina",
sin:["Lyrica","Prebictal","Pregalex"],
formas:["Cápsula 25 mg, 75 mg, 150 mg, 300 mg","⚠ CEAF (PCDT-MS Dor neuropática refratária) — particular comum"],
resumo:"⚠ SIMILAR à gabapentina (mesmo mecanismo) com ABSORÇÃO LINEAR (não-saturável) — POSOLOGIA SIMPLIFICADA (2×/d). Indicações: dor neuropática (diabética, pós-herpética, central), fibromialgia, epilepsia focal (adjunto), ansiedade generalizada. ⚠ MESMO POTENCIAL DE ABUSO. ⚠ Eficácia ligeiramente superior à gabapentina + posologia melhor — geralmente preferida quando disponível.",
dose_rapida:"75 mg 12/12h, titular a 150-600 mg/d ÷ 12/12h",
doses:[
{ind:"⚠ DOR NEUROPÁTICA (diabética, pós-herpética, central)", dose:"75 mg VO 12/12h × 1 sem, depois 150 mg 12/12h. Máx 600 mg/d ÷ 12/12h", obs:""},
{ind:"⚠ FIBROMIALGIA", dose:"75-225 mg 12/12h", obs:""},
{ind:"⚠ EPILEPSIA FOCAL (adjunto)", dose:"75-300 mg 12/12h", obs:""},
{ind:"⚠ TAG (uso aprovado em alguns países)", dose:"75-300 mg/d ÷ 12/12h", obs:"⚠ Não 1ª linha — preferir ISRS."},
],
ajustes:{
irc:"⚠ AJUSTE pela TFG: 30-59: 50% dose. 15-29: 25%. <15: 25 mg/d.",
iht:"Sem ajuste",
idoso:"⚠ Iniciar baixo, ajustar pela TFG",
gestante:"⚠ C — dados limitados",
aleita:"Cautela",
ped:"≥1m (Lennox-Gastaut)",
},
mecanismo:"⚠ Liga-se à SUBUNIDADE α2δ do canal de cálcio voltagem-dependente → ↓ liberação glutamato.",
farmacocin:{
absorc:"⚠ VO ~90% — ABSORÇÃO LINEAR (não saturável — vantagem sobre gabapentina)",
distrib:"Ampla",
metab:"⚠ NÃO metabolizada",
elimin:"⚠ Renal 90% inalterada",
meiavida:"~6h",
ligacao:"~0%",
},
ef_colats:{
comuns:["Sonolência","Tontura","Edema periférico","Ganho de peso","Visão turva","Boca seca","Ataxia"],
sérios:["⚠ ⚠ POTENCIAL DE ABUSO maior que gabapentina (lista de controlados — droga controlada em UK)","Depressão respiratória + opioide","Insuficiência cardíaca em alto grau (raro)","Encefalopatia em IRC sem ajuste"],
},
interacoes:["⚠ Opioides: depressão respiratória","Álcool, BZD: sedação somativa","Pioglitazona: edema","IECA: edema/angioedema"],
contraindicacoes:["Hipersensibilidade","Cautela em paciente com história de abuso"],
monit:["Função renal","Sedação","Edema, ganho de peso","Sinais de abuso"],
gravidez:"C",
sus:"⚠ CEAF — PCDT-MS Dor crônica neuropática refratária",
referencias:["NICE; FDA Warning."],
},

/* ============== TOPIRAMATO ============== */

{id:"med-topiramato", classe:"Anticonvulsivante de amplo espectro + profilaxia migrânea", grupo:"neuro",
nome:"Topiramato",
sin:["Topamax","Amato","Egide"],
formas:["Comprimido 25 mg, 50 mg, 100 mg","CEAF (PCDT-MS Epilepsia / Migrânea refratária)"],
resumo:"⚠ ANTICONVULSIVANTE DE AMPLO ESPECTRO — eficaz em focal + generalizada. ⚠ INDICAÇÃO MAIS COMUM HOJE: ⚠ ⚠ PROFILAXIA DE MIGRÂNEA (junto com propranolol — 1ª linha). Vantagem: PERDA DE PESO (útil em obesidade comórbida). Desvantagem: efeitos cognitivos significativos (lentificação, palavra na ponta da língua), nefrolitíase, parestesia, acidose metabólica, glaucoma agudo. ⚠ Apelido entre psiquiatras: 'dopamax'.",
dose_rapida:"25 mg HS × 1 sem, titular 25-50 mg/sem até 100-200 mg/d ÷ 12/12h",
doses:[
{ind:"⚠ ⚠ PROFILAXIA DE MIGRÂNEA — 1ª LINHA (com propranolol)", dose:"25 mg HS × 1 sem, titular 25 mg/sem até 50-100 mg/d ÷ 12/12h. Máx 200 mg/d", obs:"⚠ Excelente em migrânea com aura, frequência ≥4/mês. Iniciar lento — efeitos cognitivos."},
{ind:"⚠ EPILEPSIA FOCAL e GENERALIZADA", dose:"100-400 mg/d ÷ 12/12h", obs:""},
{ind:"⚠ TRANSTORNO BIPOLAR (adjunto, off-label)", dose:"50-200 mg/d", obs:""},
{ind:"⚠ Tratamento adjunto da OBESIDADE (off-label)", dose:"50-200 mg/d", obs:""},
{ind:"⚠ COMPULSÃO ALIMENTAR / bulimia (off-label)", dose:"50-300 mg/d", obs:""},
],
ajustes:{
irc:"⚠ TFG <70: reduzir 50%",
iht:"Reduzir",
idoso:"⚠ Iniciar 25 mg HS",
gestante:"⚠ D — TERATOGÊNICO — anomalias craniofaciais (lábio leporino, fenda palatina). EVITAR em mulher fértil sem contracepção rigorosa.",
aleita:"Cautela",
ped:"≥2a (epilepsia)",
},
mecanismo:"⚠ Múltiplos: bloqueia Na + potencia GABA + bloqueia canais Ca + bloqueia receptores AMPA/cainato + INIBE ANIDRASE CARBÔNICA (explica acidose, parestesia, litíase renal, perda peso).",
farmacocin:{
absorc:"VO ~80%",
distrib:"Ampla",
metab:"Parcial hepático",
elimin:"Renal 70% inalterada",
meiavida:"~21h",
ligacao:"~15%",
},
ef_colats:{
comuns:["⚠ ⚠ EFEITOS COGNITIVOS — lentificação, palavra na ponta da língua, dificuldade concentração ('dopamax')","Parestesia (mãos, pés — inibição anidrase carbônica)","Anorexia / perda de peso","Disgeusia (sabor de refrigerante alterado)","Sonolência","Tontura","Cefaleia"],
sérios:["⚠ ⚠ NEFROLITÍASE (cálculos de cálcio + fosfato) — orientar HIDRATAÇÃO","⚠ ⚠ ACIDOSE METABÓLICA HIPERCLORÊMICA","⚠ ⚠ GLAUCOMA DE ÂNGULO FECHADO AGUDO — RARO mas EMERGÊNCIA (dor ocular + visão turva, primeiras semanas — INTERROMPER imediatamente)","⚠ OLIGOIDROSE / HIPERTERMIA em criança (especialmente em calor)","⚠ TERATOGENICIDADE","Suicidalidade (sinal nominal)","Encefalopatia em hiperamonemia (com valproato)"],
},
interacoes:["⚠ ACO combinado: ↓ etinilestradiol em dose >200 mg/d","⚠ Valproato: hiperamonemia","Outros inibidores anidrase carbônica (acetazolamida): acidose somativa","Litio: ↑ lítio"],
contraindicacoes:["⚠ Glaucoma","⚠ Nefrolitíase","⚠ Acidose metabólica","Gestação (relativa em mulher fértil sem contracepção)","Hipersensibilidade"],
monit:["⚠ Função renal + bicarbonato (acidose) — basal + a cada 3-6m","Função cognitiva","Sintomas oculares — alerta urgente","Peso"],
gravidez:"⚠ D",
sus:"CEAF — PCDT-MS Migrânea / Epilepsia",
referencias:["NICE Headache; AAN Migraine; ABE."],
},

);
