/* ===========================================================
   VOVÔMINIC EMERGÊNCIA — BIBLIOTECA DE MEDICAÇÕES (PARTE 13)
   Bloco E Rodada 3 — Antibióticos / Penicilinas
   Amoxicilina, Amox+Clavulanato, Pen V, Pen Benzatina, Ampi+Sulbactam
   =========================================================== */

MEDICACOES.push(

/* ============== AMOXICILINA ============== */

{id:"med-amoxicilina", classe:"β-lactâmico — aminopenicilina", grupo:"atb",
nome:"Amoxicilina",
sin:["Amoxil","Hiconcil","Velamox","Trimox"],
formas:["Cápsula 500 mg","Comprimido 875 mg","Suspensão oral 250 mg/5 mL e 500 mg/5 mL","REMUME — amoxicilina 500 mg + suspensão 250 mg/5 mL em UBS/PFPB"],
resumo:"⚠ ESPECTRO: G+ (Strep — pneumococo, S. pyogenes), G- limitados (H. influenzae sem β-lactamase, E. coli ambulatorial), enterococo. PEGA BEM EM: vias aéreas superiores e inferiores (faringe, otite, sinusite, pneumonia comunitária ambulatorial), erisipela estreptocócica, sífilis (alternativa em alergia leve). NÃO PEGA: S. aureus produtor de β-lactamase (90%+), G- produtores de β-lactamase, anaeróbios da boca em sinusite resistente, MRSA, Pseudomonas.",
dose_rapida:"500 mg VO 8/8h × 7-10d (adulto); 50 mg/kg/d ÷ 8/8h (criança)",
doses:[
{ind:"Faringoamigdalite estreptocócica (S. pyogenes)", dose:"500 mg VO 12/12h × 10 dias (ADULTO); 50 mg/kg/d ÷ 12/12h × 10d (CRIANÇA)", obs:"⚠ Posologia 12/12h tem evidência similar a 8/8h em faringite — facilita adesão. Confirmar Strep antes (Centor ≥3, swab/teste rápido)."},
{ind:"Otite média aguda criança", dose:"80-90 mg/kg/d ÷ 8/8h ou 12/12h × 7-10 dias", obs:"⚠ Dose ALTA pediátrica em otite — supera resistência pneumocócica. ≥6a com sintomas leves: pode observar 48-72h."},
{ind:"Sinusite aguda bacteriana adulto", dose:"500-875 mg VO 8/8h × 5-7 dias", obs:"Maioria das sinusites é VIRAL. Indicar ATB só se sintomas >10d, piora após 5d, ou intensos por >3d (USPSTF, IDSA)."},
{ind:"PAC ambulatorial adulto sem comorbidade", dose:"500 mg-1 g VO 8/8h × 5-7 dias", obs:"1ª linha. Se atípicos suspeitos: + azitromicina 500 mg 1×/d × 3-5d (dual)."},
{ind:"Erisipela / celulite leve sem fatores MRSA", dose:"500 mg VO 8/8h × 7-10 dias", obs:"Cobertura estreptocócica. Se S. aureus suspeito: cefalexina é melhor."},
{ind:"Endocardite — profilaxia em procedimento dentário", dose:"2 g VO dose única 1h antes (adulto); 50 mg/kg (criança)", obs:"Apenas em paciente de ALTO risco (prótese valvar, endocardite prévia, cardiopatia congênita não corrigida). Não rotineiro em ENFERMO comum."},
{ind:"H. pylori — esquema tríplice", dose:"1 g 12/12h × 14 dias", obs:"Combinado com claritromicina 500 mg 12/12h + omeprazol 20 mg 12/12h. Cura ~70-80% (resistência crescente)."},
{ind:"Mordedura animal/humana (cobertura ambulatorial)", dose:"Amox + clavulanato 875/125 mg 12/12h × 5-7d (PREFERIR)", obs:"⚠ Amoxicilina ISOLADA é INSUFICIENTE em mordedura — preferir associação com clavulanato (anaeróbios + Pasteurella)."},
{ind:"Sífilis em alergia leve a penicilina (não anafilática)", dose:"500 mg VO 6/6h + probenecida — uso restrito", obs:"⚠ Padrão é PENICILINA G BENZATINA. Amoxicilina não tem dados robustos em sífilis — dessensibilização à penicilina é preferida."},
{ind:"Lyme disease (raro no Brasil)", dose:"500 mg 8/8h × 14-21 dias", obs:"Alternativa quando doxiciclina contraindicada (gestante, criança <8a)."},
],
ajustes:{
irc:"TFG 10-30: 250-500 mg 12/12h. TFG <10: 250-500 mg 24/24h. Hemodiálise: dose após sessão.",
iht:"Sem ajuste",
idoso:"Sem ajuste se função renal normal. Monitor TFG.",
gestante:"⚠ Categoria B — SEGURA na gestação. Ampla experiência clínica.",
aleita:"Compatível. Pode causar diarreia/candidíase no lactente.",
ped:"50-90 mg/kg/d ÷ 8/8h ou 12/12h. Otite criança: dose alta 80-90 mg/kg/d.",
},
mecanismo:"⚠ Inibe síntese de parede bacteriana — liga-se a PBP (penicillin-binding proteins), impedindo polimerização do peptidoglicano → bacteriólise. BACTERICIDA. Sensível à β-lactamase bacteriana (não cobre cepas produtoras).",
farmacocin:{
absorc:"VO ~75-90% (excelente, melhor que ampicilina). Independe de alimento.",
distrib:"Ampla — incluindo SNC se meninges inflamadas",
metab:"Hepático mínimo",
elimin:"Renal (60-80% inalterada)",
meiavida:"~1-1,5h (3-4h em IRC)",
ligacao:"~17-20% (baixa)",
},
ef_colats:{
comuns:["⚠ Diarreia (5-10%)","Candidíase oral/vaginal","Náusea/vômito","Rash maculopapular benigno (especialmente em mononucleose — quase 100%)"],
sérios:["Anafilaxia (rara mas grave)","Síndrome de Stevens-Johnson","Colite por C. difficile","Encefalopatia (em IRC + dose alta)"],
},
interacoes:["Probenecida: ↑ nível sérico de amoxicilina","Anticoagulantes orais (varfarina): pode ↑ INR","Metotrexato: ↓ excreção → toxicidade","Alopurinol: ↑ incidência de rash"],
contraindicacoes:["⚠ Alergia conhecida a penicilinas (anafilaxia, SJS, eritema multiforme prévio)","⚠ Mononucleose infecciosa — quase 100% desenvolvem rash não alérgico (evitar para não confundir diagnóstico)"],
monit:["Sinais de hipersensibilidade","Função renal em uso prolongado","INR se varfarina"],
gravidez:"B",
sus:"⚠ REMUME — UBS dispensação direta. Também PFPB.",
referencias:["Sanford Guide 2025","IDSA","Diretriz Brasileira PAC","Manuais MS"],
},

/* ============== AMOX + CLAVULANATO ============== */

{id:"med-amox-clav", classe:"β-lactâmico — aminopenicilina + inibidor de β-lactamase", grupo:"atb",
nome:"Amoxicilina + Clavulanato",
sin:["Clavulin","Amoxetil","Sigma Clav","Augmentin"],
formas:["Comprimido 500/125 mg, 875/125 mg, 1000/62,5 mg BD","Suspensão 250/62,5 mg/5 mL, 400/57 mg/5 mL, 600/42,9 mg/5 mL ES (criança)","REMUME — UBS 500/125 mg em algumas SES; PFPB"],
resumo:"⚠ ESPECTRO: AMPLIA cobertura da amoxicilina para BACTÉRIAS PRODUTORAS DE β-LACTAMASE — S. aureus (não MRSA), H. influenzae β-lac+, Moraxella, E. coli β-lac+, Klebsiella, Bacteroides (anaeróbios da BOCA E TRATO GU/GI). PEGA BEM EM: mordedura humana/animal, infecção pé diabético, sinusite/otite refratária, pneumonia aspirativa, infecção odontogênica, ITU complicada. NÃO PEGA: Pseudomonas, MRSA, ESBL.",
dose_rapida:"875/125 mg VO 12/12h × 7-10d (adulto); 45-90 mg/kg/d ÷ 12/12h (criança)",
doses:[
{ind:"Sinusite aguda bacteriana (falha amoxicilina ou pneumococo resistente)", dose:"875/125 mg 12/12h × 5-7 dias", obs:"⚠ Atual diretriz: 1ª linha em ADULTO de área com alta resistência pneumocócica. Em criança ≥3m: 90 mg/kg/d de amoxicilina equivalente."},
{ind:"Otite média aguda refratária / criança >6m", dose:"45-90 mg/kg/d ÷ 12/12h × 7-10 dias", obs:"Dose alta (90 mg/kg/d) em criança com fatores de risco."},
{ind:"PAC adulto com comorbidade", dose:"875/125 mg VO 12/12h × 5-7 dias + azitromicina 500 mg/d", obs:"Comorbidades: DPOC, DM, hepatopatia, alcoolismo, malignidade, asplenia."},
{ind:"⚠ Mordedura humana / animal (cão, gato)", dose:"875/125 mg 12/12h × 5-7 dias (profilaxia) ou 7-14 dias (estabelecida)", obs:"1ª LINHA. Cobertura: Pasteurella (cão/gato), Eikenella (humano), S. aureus, Strep, anaeróbios. Mordedura humana SEMPRE tratar com ATB. Mordedura animal: tratar se mão, face, periarticular, profunda, imunossuprimido."},
{ind:"Infecção odontogênica / abscesso dental", dose:"875/125 mg 12/12h × 5-7 dias", obs:"Cobertura anaeróbios da boca + flora aeróbia. Após drenagem dental quando indicada."},
{ind:"Pé diabético (infecção leve ambulatorial)", dose:"875/125 mg 12/12h × 7-14 dias", obs:"Sem isquemia importante. Profundidade superficial. Encaminhar especialista em casos moderados-graves."},
{ind:"ITU complicada (sem hospitalização)", dose:"875/125 mg 12/12h × 7-14 dias", obs:"Pielonefrite ambulatorial em adulto estável: alternativa quando quinolonas não indicadas."},
{ind:"Pneumonia aspirativa ambulatorial", dose:"875/125 mg 12/12h × 7-10 dias", obs:"Cobertura anaeróbios. Hospitalar: cefotaxima/ceftriaxona + clinda OU piperacilina+tazobactam."},
{ind:"Celulite com fator MRSA NÃO suspeito + S. aureus suspeito", dose:"875/125 mg 12/12h × 5-7 dias", obs:"Se MRSA suspeito: SMX-TMP ou clindamicina."},
{ind:"DPOC — exacerbação bacteriana com purulência", dose:"875/125 mg 12/12h × 5-7 dias", obs:"⚠ Indicar ATB se purulência + dispneia + aumento de secreção (≥2 critérios Anthonisen)."},
],
ajustes:{
irc:"TFG 10-30: 500 mg 12/12h. TFG <10: 500 mg 24/24h. Hemodiálise: pós-sessão.",
iht:"⚠ CAUTELA — pode causar hepatotoxicidade. Em IH grave: evitar.",
idoso:"⚠ Maior risco de COLESTASE / hepatite — uso prolongado. Limitar duração.",
gestante:"B",
aleita:"Compatível",
ped:"45-90 mg/kg/d (amoxicilina) ÷ 12/12h. Suspensões pediátricas com diferentes proporções amox:clav.",
},
mecanismo:"AMOXICILINA inibe síntese de parede (bactericida) + CLAVULANATO inativa β-lactamases bacterianas — restaura atividade contra cepas resistentes.",
farmacocin:{
absorc:"VO ~75-90%. Refeição reduz absorção do clavulanato — tomar com início da refeição (reduz náusea).",
distrib:"Ampla",
metab:"Hepático parcial",
elimin:"Renal predominante",
meiavida:"~1-1,5h",
ligacao:"Baixa",
},
ef_colats:{
comuns:["⚠ DIARREIA (mais alta que amoxicilina isolada — 15-25%)","Náusea/vômito","Candidíase","Cefaleia","Rash"],
sérios:["⚠ Hepatotoxicidade — colestase, hepatite (especialmente >55a, uso prolongado)","Colite por C. difficile","Anafilaxia","Síndrome de Stevens-Johnson"],
},
interacoes:["Anticoagulantes: ↑ INR","Probenecida","Alopurinol: ↑ rash","Metotrexato"],
contraindicacoes:["Alergia a penicilinas","⚠ Hepatotoxicidade prévia por amox+clav","Mononucleose"],
monit:["Sintomas hepáticos em uso >7d","INR se varfarina","Função renal"],
gravidez:"B",
sus:"REMUME em parte das SES. Componente complementar.",
referencias:["IDSA","Sanford Guide","Diretriz Brasileira"],
},

/* ============== PENICILINA V ORAL ============== */

{id:"med-pen-v", classe:"β-lactâmico — penicilina natural oral",
grupo:"atb",
nome:"Penicilina V (fenoximetilpenicilina)",
sin:["Pen-V Oral","V-Cillin"],
formas:["Comprimido 500 mg","Solução oral 250 mg/5 mL","⚠ Disponibilidade limitada no Brasil — frequentemente substituída por amoxicilina"],
resumo:"⚠ ESPECTRO: ESTREITÍSSIMO — apenas G+ (Streptococcus principalmente). PEGA BEM EM: faringite estreptocócica, profilaxia em febre reumática, mordida superficial não contaminada. NÃO PEGA: G-, S. aureus β-lac+, anaeróbios. Hoje muito substituída pela AMOXICILINA (mesma cobertura + melhor absorção + posologia mais fácil).",
dose_rapida:"500 mg VO 8/8h × 10d (adulto); 25-50 mg/kg/d ÷ 6/6h ou 8/8h (criança)",
doses:[
{ind:"Faringite estreptocócica (alternativa à amoxicilina)", dose:"500 mg VO 8/8h × 10 dias", obs:"Ambas são igualmente eficazes. Amoxicilina é preferida por: melhor absorção, posologia mais fácil, sabor mais palatável em criança."},
{ind:"Profilaxia secundária de FEBRE REUMÁTICA", dose:"250 mg VO 12/12h indefinidamente", obs:"⚠ Quando há FR documentada com cardite — profilaxia até 21a ou 5a após último episódio (o que for MAIOR). Sem cardite: até 5a ou 21a. Penicilina benzatina IM mensal é alternativa preferida em paciente não aderente."},
{ind:"Profilaxia em paciente asplênico (pneumococo)", dose:"250-500 mg VO 12/12h ad lib", obs:"Profilaxia em criança asplênica até 5a. Em adulto: avaliar individualmente. Vacinas anti-pneumocócicas + meningocócica + Hib são prioritárias."},
{ind:"Erisipela leve estreptocócica (alternativa)", dose:"500 mg 6/6h × 10 dias", obs:"Geralmente amoxicilina é mais conveniente."},
],
ajustes:{
irc:"TFG <30: reduzir frequência (12/12h)",
iht:"Sem ajuste",
idoso:"Sem ajuste se função renal normal",
gestante:"B",
aleita:"Compatível",
ped:"25-50 mg/kg/d ÷ 6/6h ou 8/8h",
},
mecanismo:"Inibe PBPs → bacteriólise. Resistente ao ácido gástrico (vs penicilina G). BACTERICIDA.",
farmacocin:{
absorc:"VO 60% — menor que amoxicilina",
distrib:"Ampla",
metab:"Hepático mínimo",
elimin:"Renal",
meiavida:"~30-60 min",
ligacao:"~75-80%",
},
ef_colats:{
comuns:["Náusea","Diarreia","Candidíase"],
sérios:["Anafilaxia","Stevens-Johnson"],
},
interacoes:["Probenecida","Tetraciclinas (bacteriostático antagoniza bactericida) — teoricamente"],
contraindicacoes:["Alergia a penicilinas"],
monit:["Hipersensibilidade"],
gravidez:"B",
sus:"⚠ Pouco disponível no SUS — amoxicilina é o substituto operacional.",
referencias:["AHA Febre Reumática","IDSA","Sanford"],
},

/* ============== PENICILINA G BENZATINA ============== */

{id:"med-pen-benzatina", classe:"β-lactâmico — penicilina natural IM depot",
grupo:"atb",
nome:"Penicilina G Benzatina",
sin:["Benzetacil","Bicillin LA","Penadur"],
formas:["Frasco-ampola 600.000 UI (intramuscular)","Frasco-ampola 1.200.000 UI","REMUME — UBS Estiva Gerbi (com equipe capacitada para aplicação)"],
resumo:"⚠ ESPECTRO: APENAS G+ (Strep) + Treponema pallidum (SÍFILIS — uso CENTRAL). DEPOT IM com efeito de SEMANAS — útil em adesão difícil. PEGA BEM EM: sífilis (todos os estágios), faringite estreptocócica (alternativa), profilaxia secundária febre reumática. NÃO PEGA: praticamente todo o resto. NÃO IV (risco êmbolo).",
dose_rapida:"1.200.000-2.400.000 UI IM dose única (sífilis primária/secundária)",
doses:[
{ind:"⚠ SÍFILIS PRIMÁRIA / SECUNDÁRIA / LATENTE RECENTE (<1 ano)", dose:"2.400.000 UI IM DOSE ÚNICA — dividir em 2 sítios (glúteo, vasto lateral): 1.200.000 UI em cada", obs:"⚠ 1ª LINHA — PCDT-MS 2024. Reação de Jarisch-Herxheimer em 12-24h (febre, mialgia, cefaleia) — pré-medicar com paracetamol é razoável."},
{ind:"⚠ SÍFILIS LATENTE TARDIA / DURAÇÃO INDETERMINADA / TERCIÁRIA", dose:"2.400.000 UI IM 1×/SEMANA × 3 SEMANAS (total 7,2 milhões UI)", obs:"⚠ Atenção ao INTERVALO máximo de 14 dias entre doses — se exceder, REINICIAR esquema."},
{ind:"⚠ SÍFILIS NA GESTAÇÃO", dose:"Mesmo esquema acima conforme estágio. ⚠ TRATAR PARCEIRO sem aguardar resultado", obs:"⚠ Iniciar IMEDIATAMENTE ao diagnóstico. ⚠ Em alergia documentada à penicilina: DESSENSIBILIZAÇÃO — não usar substituto em gestação."},
{ind:"⚠ NEUROSSÍFILIS / SÍFILIS OCULAR / OTOSSÍFILIS", dose:"⚠ NÃO usar penicilina benzatina — usar PENICILINA G CRISTALINA (aquosa) 18-24 milhões UI/d IV × 10-14 dias", obs:"⚠ Encaminhar para internação."},
{ind:"Faringite estreptocócica em paciente NÃO aderente VO", dose:"1.200.000 UI IM dose única (adulto); 600.000 UI (criança <27 kg)", obs:"Alternativa quando não há adesão à VO 10 dias."},
{ind:"Profilaxia secundária FEBRE REUMÁTICA", dose:"1.200.000 UI IM CADA 21-28 DIAS (criança/adulto >27 kg); 600.000 UI (criança <27 kg)", obs:"Padrão-ouro pela adesão. Duração: cardite + sequela = até 40a ou vida toda; cardite sem sequela = até 21a ou 10a após último surto; sem cardite = 21a ou 5a após. Aplicação dolorosa — pré-tratar com analgésico se necessário."},
{ind:"Profilaxia em paciente asplênico (pneumococo)", dose:"1.200.000 UI IM cada 28 dias", obs:"Alternativa à penicilina V oral."},
],
ajustes:{
irc:"Geralmente sem ajuste para dose intermitente. Em TFG <10 + uso muito frequente: cautela.",
iht:"Sem ajuste",
idoso:"Sem ajuste",
gestante:"⚠ B — 1ª LINHA em SÍFILIS GESTACIONAL. Dessensibilizar se alérgica.",
aleita:"Compatível",
ped:"<27 kg: 600.000 UI IM. ≥27 kg: 1.200.000 UI.",
},
mecanismo:"Penicilina G em forma de SAL POUCO SOLÚVEL (benzatina) — depósito IM libera lentamente. Concentração sérica baixa mas SUSTENTADA por SEMANAS. Mesmo mecanismo bactericida (inibe PBP).",
farmacocin:{
absorc:"IM — liberação prolongada",
distrib:"Ampla EXCETO SNC (níveis baixos — por isso NÃO usar em neurossífilis)",
metab:"Mínimo",
elimin:"Renal",
meiavida:"Niveis detectáveis por 21-28 dias após dose",
ligacao:"~60-65%",
},
ef_colats:{
comuns:["⚠ Dor intensa no local da aplicação (frequente)","⚠ Reação de Jarisch-Herxheimer em sífilis (12-24h pós-injeção — febre, mialgia, cefaleia)","Reação tardia (rash, urticária)"],
sérios:["Anafilaxia","Embolia se aplicada inadvertidamente IV (síndrome de Hoigné — angústia, alucinações, palpitação — geralmente autolimitada)","Necrose isquêmica se aplicada IA (síndrome de Nicolau)"],
},
interacoes:["Probenecida","Anticoagulantes orais","Metotrexato"],
contraindicacoes:["⚠ Alergia conhecida a penicilinas (em sífilis gestacional: DESSENSIBILIZAR, não substituir)","⚠ NÃO APLICAR IV — risco morte","⚠ NÃO APLICAR IA — risco síndrome de Nicolau"],
monit:["Reações no local","Sintomas Jarisch-Herxheimer","Aspirar antes de injetar (excluir vaso)","Pode haver síncope vasovagal — paciente sentado/deitado durante e após"],
gravidez:"B",
sus:"REMUME — UBS pode dispensar e aplicar com equipe capacitada (treinamento PNI + protocolo de aplicação seguro).",
referencias:["⚠ PCDT-MS IST 2024","CDC STI Guidelines 2021","AHA Febre Reumática"],
},

/* ============== AMPICILINA + SULBACTAM ============== */

{id:"med-ampi-sulb", classe:"β-lactâmico — aminopenicilina + inibidor de β-lactamase (IV)", grupo:"atb",
nome:"Ampicilina + Sulbactam",
sin:["Unasyn","Combactam"],
formas:["Frasco-ampola 1,5 g (1 g ampicilina + 0,5 g sulbactam) IV/IM","Frasco-ampola 3 g (2 g + 1 g) IV","⚠ Uso predominantemente hospitalar — UBS pode ter para uso interno"],
resumo:"⚠ ESPECTRO: similar a amox+clav VO — G+ (Strep, S. aureus β-lac+ não MRSA, enterococo), G- (E. coli, Klebsiella β-lac+, H. influenzae, Moraxella), anaeróbios (Bacteroides). PEGA BEM EM: infecções polimicrobianas hospitalares ambulatoriais — pneumonia aspirativa, abdominais, pé diabético moderado, mordedura grave. NÃO PEGA: Pseudomonas, MRSA, ESBL.",
dose_rapida:"1,5-3 g IV 6/6h",
doses:[
{ind:"PAC moderada-grave hospitalar", dose:"3 g IV 6/6h × 7 dias + macrolídeo (azitro 500 mg/d) ou levofloxacino", obs:""},
{ind:"Pneumonia aspirativa", dose:"3 g IV 6/6h × 7 dias", obs:"Cobertura anaeróbios oral."},
{ind:"Infecção intra-abdominal complicada (leve-moderada)", dose:"3 g IV 6/6h × 5-7 dias após controle de foco", obs:"Em casos graves: piperacilina+tazobactam ou carbapenêmico."},
{ind:"Pé diabético moderado", dose:"3 g IV 6/6h × 7-14 dias", obs:"Cobertura ampla. Em isquemia ou MRSA suspeito: associar vancomicina."},
{ind:"Mordedura humana / animal grave", dose:"3 g IV 6/6h × 7-14 dias", obs:"Em mordeduras infectadas, profundas, com tendinite/artrite."},
{ind:"DPOC exacerbação grave / pneumonia hospitalar leve", dose:"3 g IV 6/6h × 5-7 dias", obs:""},
{ind:"Endocardite (alternativa em alergia a outros)", dose:"3 g IV 6/6h + aminoglicosídeo (gentamicina) × 4-6 sem", obs:"Especialista."},
],
ajustes:{
irc:"TFG 15-30: 1,5-3 g IV 12/12h. TFG <15: 1,5 g 24/24h. Hemodiálise: pós.",
iht:"Cautela em IH grave",
idoso:"Sem ajuste se função renal normal",
gestante:"B",
aleita:"Compatível",
ped:"100-200 mg/kg/d (ampicilina) ÷ 6/6h. Neonatal: dose ajustada.",
},
mecanismo:"AMPICILINA + SULBACTAM (inibe β-lactamase) — bactericida.",
farmacocin:{
absorc:"IV (oral mal absorvida — usa-se VO via sultamicilina, pro-droga)",
distrib:"Ampla incluindo SNC com meninges inflamadas",
metab:"Hepático parcial",
elimin:"Renal",
meiavida:"~1h",
ligacao:"~28% (ampi) / 38% (sulbac)",
},
ef_colats:{
comuns:["Diarreia","Náusea","Rash","Elevação de transaminases","Tromboflebite no local IV"],
sérios:["Anafilaxia","Stevens-Johnson","Colite C. difficile"],
},
interacoes:["Probenecida","Anticoagulantes","Metotrexato","Alopurinol (rash)"],
contraindicacoes:["Alergia a penicilinas","Mononucleose"],
monit:["Função renal/hepática","INR","Sintomas hipersensibilidade"],
gravidez:"B",
sus:"⚠ Uso hospitalar. UBS pode ter para uso interno emergencial conforme realidade local.",
referencias:["Sanford Guide","IDSA","Diretriz Brasileira Pneumonia"],
},

);
