/* ===========================================================
   VOVÔMINIC EMERGÊNCIA — BIBLIOTECA DE MEDICAÇÕES (PARTE 25)
   Adjuvantes Paliativos
   Antieméticos: Haloperidol, Levomepromazina, Metoclopramida, Bromoprida, Ondansetrona
   Antimuscarínicos: Hioscina butilbrometo, Escopolamina hidrobrometo
   Outros: Dexametasona, Octreotida, Bisacodil, Lactulose, Metilnaltrexona
   =========================================================== */

MEDICACOES.push(

/* ============== HALOPERIDOL ============== */

{id:"med-haloperidol", classe:"Antipsicótico típico (butirofenona) — D2 antagonista", grupo:"pali",
nome:"Haloperidol",
sin:["Haldol","Haloper","Halo"],
formas:["Comprimido 1 mg, 5 mg","Solução oral 2 mg/mL (gotas)","Ampola 5 mg/mL IM/IV","Ampola decanoato 50 mg/mL IM (depot mensal — psiquiatria)","REMUME — UBS dispensação direta + FARMASUS (controle especial)"],
resumo:"⚠ ⚠ ANTIPSICÓTICO TÍPICO — pedra angular em PALIATIVOS para NÁUSEA POR CTZ (opioide, uremia, hipercalcemia) e DELIRIUM. Doses pequenas (0,5-2 mg) muito eficazes para sintomas paliativos. ⚠ ⚠ EVITAR EM PARKINSON / corpos de Lewy. QT longo em dose alta. Via VO/SC bem tolerada em paliativos.",
dose_rapida:"0,5-2 mg VO/SC 8-12/12h (paliativos); 5 mg IM (agitação aguda)",
doses:[
{ind:"⚠ ⚠ NÁUSEA / VÔMITO em paliativos — mecanismo CTZ (opioide, uremia, hipercalcemia, quimio recente)", dose:"0,5-2 mg VO/SC 8-12/12h ad lib", obs:"⚠ ⚠ 1ª LINHA em náusea por CTZ. Dose BAIXA — efeito antiemético com pouca sedação. Solução oral: 5 gotas = 0,5 mg."},
{ind:"⚠ DELIRIUM em paliativos / hospitalizado", dose:"0,5-2 mg VO/SC 8-12/12h + resgate 0,5-1 mg 1/1h conforme necessário. Idoso: 0,25-0,5 mg", obs:"⚠ 1ª LINHA para delirium hiperativo. ⚠ Não em Parkinson."},
{ind:"⚠ AGITAÇÃO PSICOMOTORA AGUDA (PA / emergência)", dose:"5 mg IM (eventualmente + prometazina 50 mg IM para reduzir extrapiramidal e somar sedação)", obs:"Pode repetir a cada 30-60 min até controle. Máx 20 mg/d."},
{ind:"⚠ Hiperêmese gravídica refratária (off-label)", dose:"0,5-1 mg VO/SC 8/8h", obs:"Após falha de ondansetrona/metoclopramida."},
{ind:"Esquizofrenia / TAB com sintomas psicóticos", dose:"5-15 mg/d (psiquiatria)", obs:""},
],
ajustes:{
irc:"⚠ Cautela em IRC importante",
iht:"⚠ Reduzir em IH",
idoso:"⚠ ⚠ INICIAR 0,25-0,5 mg. Risco AVC + mortalidade em demência (Black Box FDA antipsicóticos). Avaliar risco-benefício, geralmente justificado em paliativos.",
gestante:"⚠ C — em hiperêmese refratária: aceitável após outros. Sintomas extrapiramidais neonatais se uso 3º trim.",
aleita:"Cautela — passa pelo leite",
ped:"⚠ Especialista. Geralmente não em rotina <3a.",
},
mecanismo:"⚠ ANTAGONISTA D2 potente (zona quimioceptora CTZ, gânglios da base, mesolímbico). Pouco efeito anti-α1 e anti-H1 (menos sedativo que clorpro/levome).",
farmacocin:{
absorc:"VO ~60-70%",
distrib:"Ampla, atravessa BHE",
metab:"Hepático CYP3A4 e CYP2D6",
elimin:"Renal + fecal",
meiavida:"~18-25h (decanoato 3 sem)",
ligacao:"~90%",
},
ef_colats:{
comuns:["Sedação leve","Sintomas extrapiramidais (SEP) — bradicinesia, rigidez, distonia, tremor","Sialorreia / disartria","Constipação","Hipotensão (leve)","Acatisia"],
sérios:["⚠ ⚠ SÍNDROME NEUROLÉPTICA MALIGNA (rara — hipertermia, rigidez muscular, alteração mental, CPK alta)","⚠ DISTONIA AGUDA / CRISE OCULOGÍRICA — tratar com biperideno 5 mg IM","⚠ QT LONGO / Torsades — risco em altas doses IV, especialmente >35 mg/d ou com QT-prolongadores","⚠ DISCINESIA TARDIA (uso crônico)","⚠ AVC + mortalidade em IDOSO com demência (Black Box)","Hiperprolactinemia","Convulsão (raro)"],
},
interacoes:["⚠ ⚠ QT-prolongadores (metadona, antiarrítmicos classe Ia/III, ondansetrona dose alta, macrolídeos, azólicos, alguns ISRS): risco TORSADES","⚠ Anticolinérgicos: somatório","⚠ Levodopa/agonistas DA: efeitos OPOSTOS — perda controle Parkinson","Lítio: ↑ neurotoxicidade","Álcool, BZD, opioides: sedação somativa","Indutores CYP (rifampicina, fenitoína, carbamazepina): ↓ haloperidol"],
contraindicacoes:["⚠ ⚠ PARKINSON / demência de corpos de Lewy","⚠ Depressão SNC importante","⚠ QT longo congênito","⚠ Coma","⚠ Lesão de gânglios da base","Hipersensibilidade","Idoso com demência (relativa — Black Box em alguns contextos)"],
monit:["⚠ Sinais extrapiramidais (escalas)","ECG basal em risco / dose alta","Sinais SNM","Resposta clínica"],
gravidez:"C",
sus:"⚠ REMUME — UBS dispensação direta + FARMASUS",
referencias:["ANCP; APA Delirium; NICE Palliative; FDA Black Box demência."],
},

/* ============== LEVOMEPROMAZINA ============== */

{id:"med-levomepromazina", classe:"Antipsicótico típico (fenotiazina) — amplo espectro D2/5-HT/H1/M1/α1", grupo:"pali",
nome:"Levomepromazina",
sin:["Neozine","Nozinan","Methotrimeprazine"],
formas:["Comprimido 5 mg, 25 mg, 100 mg","Solução oral 40 mg/mL (gotas)","Ampola 25 mg/mL IM/SC","FARMASUS"],
resumo:"⚠ ⚠ ANTIPSICÓTICO FENOTIAZINA — AMPLO ESPECTRO de receptores (D2 + 5-HT + H1 + M1 + α1). Indicações paliativas: NÁUSEA REFRATÁRIA (multimecanismo — 'limpa-tudo'), DELIRIUM AGITADO refratário, ANSIEDADE-AGITAÇÃO TERMINAL, SEDAÇÃO PROPORCIONAL adjuvante ao midazolam. ⚠ Mais sedativa que haloperidol — útil quando se busca sedação leve. Hipotensão postural significativa.",
dose_rapida:"6,25-25 mg VO/SC 8-24/24h (paliativos)",
doses:[
{ind:"⚠ ⚠ NÁUSEA / VÔMITO REFRATÁRIO em paliativos — espectro amplo", dose:"6,25-12,5 mg VO/SC 12-24/24h ad lib (até 25 mg em refratários)", obs:"⚠ ⚠ 'Limpa-tudo' — útil quando mecanismo de náusea não claro ou multifatorial. Em paciente já em opioide + sem resposta a haloperidol/metoclopramida/ondansetrona."},
{ind:"⚠ DELIRIUM AGITADO refratário em paliativos", dose:"12,5-25 mg VO/SC 8-12/12h + resgate", obs:"⚠ 2ª linha após haloperidol (mais sedativa)."},
{ind:"⚠ AGITAÇÃO TERMINAL", dose:"25-50 mg SC 8-12/12h ou BIC SC 50-100 mg/d", obs:""},
{ind:"⚠ ADJUVANTE em sedação paliativa (com midazolam)", dose:"12,5-25 mg SC 4-6/6h ou BIC SC 50-150 mg/d", obs:"⚠ Combinação útil — soma efeito antiemético + sedativo + analgésico adjuvante."},
{ind:"⚠ Dor refratária (adjuvante)", dose:"6,25-25 mg HS — efeito analgésico adjuvante (modulação cortical)", obs:"Off-label paliativo."},
{ind:"Esquizofrenia (psiquiatria)", dose:"75-300 mg/d ÷ 8/8h", obs:""},
],
ajustes:{
irc:"⚠ Reduzir em IRC",
iht:"⚠ ⚠ Reduzir 50% em IH",
idoso:"⚠ ⚠ Iniciar 6,25 mg. Hipotensão postural acentuada. Black Box demência.",
gestante:"⚠ C — Cautela. Sintomas extrapiramidais neonatais 3º trim.",
aleita:"⚠ Evitar uso crônico",
ped:"Especialista",
},
mecanismo:"⚠ Bloqueio MÚLTIPLO de receptores: D2 (antipsicótico, antiemético), 5-HT2 (antiemético, ansiolítico, analgésico), H1 (sedação, antiemético), M1 muscarínico (antiemético vestibular + anticolinérgico), α1 (hipotensão). Daí efeito amplo em paliativos.",
farmacocin:{
absorc:"VO ~50%",
distrib:"⚠ MUITO AMPLA — lipofílica",
metab:"Hepático",
elimin:"Renal + fecal",
meiavida:"~15-30h",
ligacao:"Alta",
},
ef_colats:{
comuns:["⚠ ⚠ SEDAÇÃO marcada","⚠ HIPOTENSÃO POSTURAL — especialmente no início","Anticolinérgico (boca seca, retenção urinária, visão turva, constipação)","Sintomas extrapiramidais (menos que haloperidol)","Tontura","Sialorreia paradoxal"],
sérios:["⚠ ⚠ HIPOTENSÃO grave em dose IM rápida","⚠ QT longo","⚠ Síndrome neuroléptica maligna (rara)","⚠ AVC + mortalidade em idoso com demência","Discinesia tardia","Reação cutânea grave (raro)","Agranulocitose (raríssima)"],
},
interacoes:["⚠ Outros antipsicóticos, álcool, BZD, opioides: depressão SNC + sedação somativa","⚠ Anti-hipertensivos: hipotensão somativa","⚠ Anticolinérgicos: somatório","⚠ QT-prolongadores","Levodopa: efeitos opostos","IMAO em 14 dias"],
contraindicacoes:["⚠ Coma / depressão SNC importante","⚠ Hipotensão grave","⚠ Parkinson","⚠ QT longo","⚠ Glaucoma ângulo fechado","⚠ HPB com retenção","Hipersensibilidade fenotiazinas","Lactente <2a"],
monit:["PA postural — risco de queda","Sintomas extrapiramidais","ECG em risco","Sintomas anticolinérgicos","Resposta clínica"],
gravidez:"C",
sus:"⚠ FARMASUS",
referencias:["ANCP; EAPC; Twycross R, et al."],
},

/* ============== DEXAMETASONA ============== */

{id:"med-dexametasona", classe:"Glicocorticoide sintético potente, longa duração", grupo:"pali",
nome:"Dexametasona",
sin:["Decadron","Dexason","Dexarinil"],
formas:["Comprimido 0,5 mg, 4 mg","Solução oral 0,1 mg/mL","Ampola 4 mg/mL e 10 mg/2,5 mL IM/IV/SC","Colírio, creme tópico","REMUME — algumas formas em UBS / FARMASUS"],
resumo:"⚠ ⚠ CORTICOIDE POTENTE — pedra angular em PALIATIVOS por múltiplos usos: ⚠ COMPRESSÃO MEDULAR (16 mg IV bolus), HIC por metástase cerebral (4-16 mg/d), antiemético (quimio, opioide, obstrução intestinal), anorexia/bem-estar (4-6 sem), DISPNEIA por linfangite/VCS, dor óssea, anti-inflamatório. Potência 25× hidrocortisona, sem mineralocorticoide. ⚠ Efeitos colaterais cumulativos limitam uso crônico.",
dose_rapida:"2-4 mg/d (apetite/anti-emético) até 16 mg/d (compressão medular, edema cerebral)",
doses:[
{ind:"⚠ ⚠ COMPRESSÃO MEDULAR MALIGNA — EMERGÊNCIA", dose:"16 mg IV BOLUS imediato + 4 mg IV/VO 6/6h × 48h, depois reduzir gradativo", obs:"⚠ ⚠ NÃO ESPERAR IMAGEM — bolus em suspeita clínica forte."},
{ind:"⚠ EDEMA CEREBRAL por metástase / HIC", dose:"4-8 mg VO/IV 6/6h (até 16 mg em sintomas graves)", obs:"⚠ Reduzir gradualmente para dose mínima eficaz após melhora."},
{ind:"⚠ DISPNEIA por LINFANGITE CARCINOMATOSA / SVCS / obstrução brônquica peritumoral", dose:"8-16 mg/d VO/IV/SC (geralmente manhã)", obs:""},
{ind:"⚠ NÁUSEA REFRATÁRIA / quimioterapia / obstrução intestinal", dose:"4-8 mg VO/SC/IV 1-2×/d", obs:"⚠ Adjuvante eficaz — combinação com ondansetrona em quimio."},
{ind:"⚠ ANOREXIA / BEM-ESTAR / FADIGA em paliativos", dose:"2-4 mg VO/manhã × 4-6 sem, depois reavaliar", obs:"⚠ ⚠ EFEITO CURTO PRAZO. Útil em paciente com expectativa de SEMANAS-MESES. Reduzir após melhora."},
{ind:"⚠ DOR ÓSSEA por metástase", dose:"4-8 mg/d", obs:"⚠ Adjuvante — junto a opioide + AINE (se possível) + bifosfonato."},
{ind:"COVID-19 com necessidade O2", dose:"6 mg VO/IV 1×/d × 10d", obs:""},
{ind:"Tireoidite / crise tireotóxica", dose:"2 mg IV 6/6h", obs:"Bloqueia conversão T4→T3."},
{ind:"Maturação pulmonar fetal", dose:"6 mg IM 12/12h × 4 doses", obs:"Obstetrícia."},
],
ajustes:{
irc:"Sem ajuste",
iht:"Cautela",
idoso:"⚠ Risco aumentado: miopatia, hiperglicemia, infecção, fratura. Avaliar risco-benefício.",
gestante:"⚠ C — em maturação pulmonar fetal: indicada. Uso prolongado: cautela.",
aleita:"Compatível em dose paliativa",
ped:"Conforme indicação especialista",
},
mecanismo:"⚠ GLICOCORTICOIDE SINTÉTICO — liga ao receptor citoplasmático, transcrição genética — efeitos anti-inflamatórios + imunossupressores + antiedema + antiemético central + apetite. Sem ação mineralocorticoide (não retém sódio). Potência ~25× hidrocortisona, ~7× prednisolona.",
farmacocin:{
absorc:"VO ~80-90%",
distrib:"Ampla",
metab:"Hepático CYP3A4",
elimin:"Renal",
meiavida:"~36-54h (efeito biológico) — explica DOSE ÚNICA DIÁRIA",
ligacao:"~77%",
},
ef_colats:{
comuns:["⚠ Hiperglicemia (pode descompensar diabetes)","⚠ Insônia (administrar manhã)","Ganho de peso","Edema (leve — sem mineralocorticoide)","Acne, equimoses, pele fina","Dispepsia","Aumento de apetite (benéfico em paliativos)"],
sérios:["⚠ ⚠ MIOPATIA proximal (uso prolongado, principalmente esteróides)","⚠ ⚠ CANDIDÍASE oral / esofágica (frequente em paliativos com dexa)","⚠ INFECÇÕES OPORTUNISTAS (TB reativada, pneumocystose)","⚠ HIPERGLICEMIA / NOVA DM","⚠ SUPRESSÃO ADRENAL (uso >2-3 sem) — não suspender abruptamente","⚠ Psicose / mania por corticoide (raro em paliativos)","⚠ ÚLCERA péptica (cuidado em quem usa AINE)","⚠ OSTEOPOROSE / fratura","⚠ Cataratas / glaucoma (crônico)","HAS","Síndrome de Cushing iatrogênica"],
},
interacoes:["⚠ AINE: ↑ risco GI","⚠ ANTIDIABÉTICOS: ajuste necessário","⚠ Indutores CYP3A4 (rifampicina, fenitoína, carbamazepina): ↓ dexa","⚠ Inibidores CYP3A4 (cetoconazol, claritromicina, ritonavir): ↑ dexa","⚠ Anticoagulantes (warfarina): variável","Vacinas de vírus vivos: ⚠ EVITAR"],
contraindicacoes:["⚠ Infecção fúngica sistêmica não tratada","⚠ Tuberculose ativa sem tratamento","Hipersensibilidade","Cautela em DM, HAS, úlcera, glaucoma"],
monit:["Glicemia","PA","Função adrenal em uso prolongado","Sinais de infecção","Candida oral","Densitometria em uso crônico"],
gravidez:"C",
sus:"⚠ REMUME — algumas formas em UBS / FARMASUS",
referencias:["ANCP; ESMO Bone Mets; NICE; Bristol Guideline."],
},

/* ============== METOCLOPRAMIDA ============== */

{id:"med-metoclopramida", classe:"Procinético + antiemético (D2 antagonista + 5-HT4 agonista)", grupo:"pali",
nome:"Metoclopramida",
sin:["Plasil","Eucil","Plamet"],
formas:["Comprimido 10 mg","Solução oral 4 mg/mL","Ampola 5 mg/mL (2 mL) IM/IV/SC","REMUME — UBS dispensação direta"],
resumo:"⚠ DUPLO MECANISMO — (1) ANTAGONISTA D2 (CTZ central — antiemético) + (2) AGONISTA 5-HT4 + sensibiliza ACh em plexo mioentérico = PROCINÉTICO. Indicações: NÁUSEA por ESTASE GÁSTRICA + náusea química leve + dispepsia. ⚠ ⚠ CONTRAINDICADA EM OBSTRUÇÃO INTESTINAL MECÂNICA (procinético piora). ⚠ Extrapiramidais — limitar uso prolongado (FDA Warning ≤12 sem).",
dose_rapida:"10 mg VO/IV/SC 6-8/8h (máx 30-40 mg/d)",
doses:[
{ind:"⚠ NÁUSEA POR ESTASE GÁSTRICA / dispepsia funcional / gastroparesia", dose:"10 mg VO 6-8/8h, idealmente 30 min ANTES DAS REFEIÇÕES + HS", obs:"⚠ ⚠ 1ª LINHA em estase. Procinético + antiemético."},
{ind:"⚠ Náusea química leve / opioide-induzida", dose:"10 mg VO/SC 6-8/8h ad lib", obs:"Alternativa ao haloperidol em CTZ."},
{ind:"⚠ Náusea pós-operatória / pós-quimioterapia (em combinação)", dose:"10 mg IV antes do procedimento", obs:"Combinação com ondansetrona + dexa em quimio altamente emetogênica."},
{ind:"⚠ Enxaqueca com vômito (uso adjunto IV)", dose:"10 mg IV", obs:"Pode reduzir frequência."},
{ind:"⚠ Galactagogo (off-label, raro)", dose:"10 mg 8/8h × dias", obs:""},
],
ajustes:{
irc:"⚠ TFG <40: reduzir 50%",
iht:"⚠ Reduzir 50% em IH",
idoso:"⚠ ⚠ Reduzir dose. Sintomas extrapiramidais + sedação mais frequentes.",
gestante:"⚠ B — segura. Útil em hiperêmese gravídica leve.",
aleita:"Compatível",
ped:"⚠ ⚠ EVITAR <1 ano (risco extrapiramidal grave). Após 1a: cautela.",
},
mecanismo:"(1) ANTAGONISTA D2 na CTZ (antiemético central). (2) AGONISTA 5-HT4 + sensibiliza receptores muscarínicos do plexo mioentérico → ↑ liberação de ACh → ↑ tônus esfíncter esofágico inferior + ↑ contratilidade gástrica + relaxa piloro → PROCINÉTICO.",
farmacocin:{
absorc:"VO ~80%",
distrib:"Ampla, atravessa BHE",
metab:"Hepático",
elimin:"Renal predominante",
meiavida:"~5-6h",
ligacao:"~30%",
},
ef_colats:{
comuns:["⚠ Sonolência","⚠ Sintomas EXTRAPIRAMIDAIS — distonia aguda (especialmente em criança/jovem; crise oculogírica)","Fadiga","Diarreia","Cefaleia"],
sérios:["⚠ ⚠ DISCINESIA TARDIA em uso prolongado >12 sem (FDA Warning — limitar)","⚠ ⚠ DISTONIA AGUDA / CRISE OCULOGÍRICA — tratar com BIPERIDENO 5 mg IM","⚠ Síndrome neuroléptica maligna (raro)","⚠ Hiperprolactinemia → galactorreia, ginecomastia, hipogonadismo","Hipotensão (em IV rápido)","Metahemoglobinemia em recém-nascido"],
},
interacoes:["⚠ Outros antipsicóticos: somatório extrapiramidal","⚠ Anticolinérgicos: REDUZEM efeito (antagonismo)","⚠ Opioides: somatório sedação","⚠ ⚠ ISRS/IMAO + metoclopramida: risco síndrome serotoninérgica","Levodopa: efeito antagônico","Digoxina: ↓ digoxina","Ciclosporina: ↑ absorção"],
contraindicacoes:["⚠ ⚠ OBSTRUÇÃO INTESTINAL MECÂNICA","⚠ Perfuração / hemorragia GI","⚠ Convulsão de história","⚠ Feocromocitoma","⚠ Parkinson","Hipersensibilidade","Lactente <1a","IMAO em 14 dias"],
monit:["⚠ Sintomas extrapiramidais — orientar paciente / família","Discinesia tardia em uso prolongado","Resposta clínica"],
gravidez:"B",
sus:"⚠ REMUME — UBS dispensação direta",
referencias:["FDA Warning DT 2009; ANCP; PCDT-MS."],
},

/* ============== BROMOPRIDA ============== */

{id:"med-bromoprida", classe:"Procinético + antiemético (similar à metoclopramida)", grupo:"pali",
nome:"Bromoprida",
sin:["Digesan","Plamet","Bromoprida"],
formas:["Cápsula 10 mg","Solução oral 4 mg/mL","Ampola 5 mg/mL (2 mL) IM/IV","REMUME — UBS dispensação direta"],
resumo:"⚠ ANÁLOGO BRASILEIRO DA METOCLOPRAMIDA — mecanismo similar (D2 antagonista + procinético). Indicações similares: NÁUSEA + ESTASE GÁSTRICA + dispepsia. ⚠ Perfil de efeitos colaterais similar — extrapiramidais, ⚠ contraindicada em obstrução intestinal. Vantagem: tradição brasileira de uso + acesso fácil.",
dose_rapida:"10 mg VO/IV/SC 6-8/8h",
doses:[
{ind:"⚠ NÁUSEA POR ESTASE GÁSTRICA / dispepsia funcional", dose:"10 mg VO 6-8/8h 30 min antes das refeições", obs:""},
{ind:"⚠ Náusea química / opioide", dose:"10 mg VO/SC 6-8/8h", obs:""},
{ind:"Náusea pós-op", dose:"10 mg IV / IM", obs:""},
],
ajustes:{
irc:"⚠ Reduzir em IRC",
iht:"⚠ Reduzir em IH",
idoso:"⚠ Reduzir dose, vigilância extrapiramidal",
gestante:"⚠ B — uso comum em hiperêmese leve no Brasil",
aleita:"Compatível",
ped:"≥6a (cautela em <12a)",
},
mecanismo:"D2 antagonista + ação procinética via plexo mioentérico (similar metoclopramida).",
farmacocin:{
absorc:"VO bem absorvida",
distrib:"Ampla",
metab:"Hepático",
elimin:"Renal",
meiavida:"~4-6h",
ligacao:"Alta",
},
ef_colats:{
comuns:["Sonolência","Sintomas extrapiramidais","Diarreia","Cefaleia"],
sérios:["⚠ Distonia aguda","⚠ Discinesia tardia em uso prolongado","Hiperprolactinemia","Hipotensão em IV rápido"],
},
interacoes:["Similar à metoclopramida — vide acima"],
contraindicacoes:["⚠ Obstrução intestinal mecânica","Perfuração GI","Convulsão","Feocromocitoma","Parkinson","Hipersensibilidade"],
monit:["Sintomas extrapiramidais","Resposta clínica"],
gravidez:"B",
sus:"⚠ REMUME — UBS dispensação direta",
referencias:["ANVISA; consenso brasileiro."],
},

/* ============== ONDANSETRONA ============== */

{id:"med-ondansetrona", classe:"Antiemético — antagonista 5-HT3", grupo:"pali",
nome:"Ondansetrona",
sin:["Zofran","Vonau","Nausedron","Ondansetron"],
formas:["Comprimido 4 mg, 8 mg","Comprimido sublingual / orodispersível 4 mg, 8 mg","Solução oral 4 mg/5 mL","Ampola 2 mg/mL (2 mL, 4 mL) IM/IV/SC","REMUME — UBS dispensação direta (algumas SES); FARMASUS"],
resumo:"⚠ ANTAGONISTA 5-HT3 — antiemético poderoso. Indicações principais: NÁUSEA POR QUIMIO ALTAMENTE EMETOGÊNICA, pós-op, gestação (off-label classe B), náusea oncológica refratária. ⚠ DESVANTAGENS: causa CONSTIPAÇÃO, QT longo (dose alta IV), cefaleia. ⚠ Não atua bem em náusea por ESTASE (não é procinético) — combinar com metoclopramida.",
dose_rapida:"4-8 mg VO/SL/IV/SC 8/8h",
doses:[
{ind:"⚠ NÁUSEA / VÔMITO em QUIMIOTERAPIA altamente emetogênica (com dexa)", dose:"8 mg IV antes da quimio + 8 mg VO 12/12h × 3-5d", obs:"Combinação com dexametasona + aprepitanto em altamente emetogênica."},
{ind:"⚠ NÁUSEA pós-op", dose:"4-8 mg IV/IM (pré ou intra-op)", obs:""},
{ind:"⚠ NÁUSEA EM PALIATIVOS (refratária ou por mecanismo serotoninérgico — quimio recente, radioterapia)", dose:"4-8 mg VO/SC 8/8h", obs:"⚠ Útil em refratários ou em vômito após quimio/radioterapia. NÃO escolha 1ª em CTZ — preferir haloperidol."},
{ind:"⚠ HIPERÊMESE GRAVÍDICA refratária", dose:"4-8 mg VO/SL 8/8h", obs:"⚠ Após falha de outras (metoclopramida, bromoprida). FDA atualizou — segurança 1º trim: dado misto mas baixo risco absoluto. Decisão compartilhada."},
{ind:"Gastroenterite aguda em pediatria (uso restrito)", dose:"4-8 mg dose única", obs:"Reduz vômito, permite hidratação oral."},
],
ajustes:{
irc:"Sem ajuste rotineiro",
iht:"⚠ Reduzir em IH grave (Child C) — máx 8 mg/d",
idoso:"Sem ajuste rotineiro — cuidado QT",
gestante:"⚠ B — uso comum. Recente sinal de fenda palatina 1º trim (modesto, controverso) — preferir outras 1ª linha (metoclopramida, prometazina); usar se refratária.",
aleita:"Compatível",
ped:"⚠ Pode usar em ped. Considerar dose por peso.",
},
mecanismo:"⚠ ANTAGONISTA 5-HT3 — receptor seronérgico em CTZ central + aferentes vagais GI. Bloqueia náusea induzida por liberação de 5-HT (quimio, radio, distensão GI).",
farmacocin:{
absorc:"VO ~60%",
distrib:"Ampla",
metab:"Hepático CYP3A4, CYP2D6",
elimin:"Renal",
meiavida:"~3-6h",
ligacao:"~70-76%",
},
ef_colats:{
comuns:["⚠ CONSTIPAÇÃO (frequente — relevante em paciente com opioide)","Cefaleia","Fadiga","Tontura","Hipotensão leve","Boca seca","Rubor"],
sérios:["⚠ ⚠ QT LONGO — DOSE-DEPENDENTE. Em IV >16 mg dose única: FDA WARNING. Em paciente cardíaco / eletrólitos baixos / outros QT-prolongadores: cuidado","⚠ Síndrome serotoninérgica (com SSRIs, tramadol, IMAO)","Reação alérgica","Hepatotoxicidade rara"],
},
interacoes:["⚠ ⚠ QT-prolongadores: ↑ TORSADES (metadona, antiarrítmicos, claritro, azólicos, haloperidol IV)","⚠ Tramadol / ISRS / IMAO: síndrome serotoninérgica","Inibidores CYP3A4 (cetoconazol): ↑ ondansetrona","Indutores CYP3A4 (rifampicina, fenitoína, carbamazepina): ↓","Apomorfina: hipotensão grave (CI)"],
contraindicacoes:["⚠ QT longo congênito","⚠ Uso simultâneo com apomorfina","Hipersensibilidade","Síndrome serotoninérgica de risco (relativa)"],
monit:["⚠ ECG basal em risco / dose IV alta","Eletrólitos (K, Mg)","Constipação","Resposta clínica"],
gravidez:"B",
sus:"⚠ REMUME — UBS dispensação direta (algumas SES) + FARMASUS",
referencias:["⚠ FDA QT Warning 2012; NCCN Antiemesis; ASCO; ANCP."],
},

);
