/* ===========================================================
   VOVÔMINIC EMERGÊNCIA — BIBLIOTECA DE MEDICAÇÕES (PARTE 12)
   Bloco D Rodada 2 — Broncodilatadores crônicos
   LABA + LAMA + ICS + Combinações + SAMA
   =========================================================== */

MEDICACOES.push(

/* ============== LABA — β-2 LONGA AÇÃO ============== */

{id:"med-formoterol", classe:"LABA — β-2 agonista de longa duração", grupo:"bd",
nome:"Formoterol",
sin:["Foradil","Oxis","Atimos","Performomist"],
formas:["DPI 12 mcg cápsula (Foradil)","Aerolizer/Turbuhaler 6 e 12 mcg","Solução nebulização 20 mcg/2mL (Performomist)","NÃO disponível como monoterapia no SUS"],
resumo:"LABA com INÍCIO RÁPIDO (1-3 min) — único LABA que pode ser usado como reliever (medicação de RESGATE) em asma. Combinação ICS-formoterol é a base do GINA 2025 (MART).",
dose_rapida:"12 mcg DPI 12/12h (asma/DPOC); ou ICS-formoterol PRN/MART",
doses:[
{ind:"Asma persistente (degrau ≥2) — TRACK 1 GINA preferida", dose:"ICS-formoterol DPI conforme escala — MART", obs:"Budesonida-formoterol 200/6 mcg ou Beclometasona-formoterol 100/6 mcg. PRN em leve, fixo + PRN em moderada/grave."},
{ind:"DPOC — manutenção", dose:"12 mcg DPI 12/12h fixo OU em combinação LABA-LAMA", obs:"Formoterol-aclidínio (Duaklir) é uma das opções de dupla."},
{ind:"Asma do esforço (pré-medicação)", dose:"12 mcg DPI 15-30 min antes do exercício", obs:"Geralmente só após ICS instituído (LABA isolado NÃO indicado em asma)."},
{ind:"Exacerbação leve de DPOC (resgate)", dose:"12 mcg DPI dose extra", obs:"Início ~1-3 min, vantagem sobre salmeterol."},
],
ajustes:{
irc:"Sem ajuste",
iht:"Sem ajuste",
idoso:"Sem ajuste; monitor FC (taquicardia)",
gestante:"Categoria C — uso se benefício > risco. Combinação ICS-formoterol é compatível em asma gestacional.",
aleita:"Compatível",
ped:"≥5a: 6-12 mcg DPI 12/12h. <5a: preferir outras opções.",
},
mecanismo:"AGONISTA β-2 ADRENÉRGICO seletivo de LONGA DURAÇÃO (12h). Relaxamento musculatura lisa brônquica via AMPc. INÍCIO RÁPIDO (1-3 min) — DIFERENCIAL frente salmeterol (15-30 min).",
farmacocin:{
absorc:"INH: ~30-40% biodisponibilidade pulmonar",
distrib:"Pulmonar local",
metab:"Hepático (CYP2D6)",
elimin:"Urinária (8%) + biliar",
meiavida:"~10h",
ligacao:"61-64%",
},
ef_colats:{
comuns:["Tremor de extremidades","Taquicardia","Hipocalemia (em dose alta)","Cefaleia","Cãibras"],
sérios:["Arritmia (raro em dose terapêutica)","Hipocalemia grave (com diurético + corticoide)","Paradoxal broncoespasmo"],
},
interacoes:["Diuréticos potássio-pertuelantes: ↓ K (somatório)","Corticoide: ↓ K (somatório)","Betabloqueadores: antagonismo","IMAO/ADT: aumento efeito CV"],
contraindicacoes:["⚠ LABA ISOLADO em asma — proibido por aumentar mortalidade. SEMPRE com ICS","Taquiarritmia grave","Hipersensibilidade"],
monit:["FC","K em uso crônico + diurético","Sintomas/exacerbações"],
gravidez:"C",
sus:"⚠ NÃO disponível isolado no SUS. Combinações ICS-formoterol estão em REMUME via componente especializado/CEAF.",
referencias:["GINA 2025","GOLD 2025","Bula Foradil"],
},

{id:"med-salmeterol", classe:"LABA — β-2 agonista de longa duração", grupo:"bd",
nome:"Salmeterol",
sin:["Serevent","Salmeral"],
formas:["DPI Diskus 50 mcg/dose (combinação Seretide com fluticasona)","MDI 25 mcg/puff","NÃO disponível como monoterapia no SUS"],
resumo:"LABA de INÍCIO LENTO (15-30 min) — não serve como reliever. Disponível principalmente em combinação com fluticasona (Seretide). Eficaz em asma e DPOC mas não na MART.",
dose_rapida:"50 mcg DPI 12/12h (fixo em combinação ICS)",
doses:[
{ind:"Asma persistente (combinação com ICS)", dose:"50 mcg DPI 12/12h + ICS", obs:"Disponível combinado: salmeterol 50 + fluticasona 100/250/500 mcg (Seretide). Esquemas TRACK 2 GINA."},
{ind:"DPOC — manutenção", dose:"50 mcg DPI 12/12h", obs:"Frequentemente em combinação Seretide ou em combinação LABA-LAMA."},
],
ajustes:{
irc:"Sem ajuste",
iht:"Sem ajuste",
idoso:"Sem ajuste; monitor FC",
gestante:"Categoria C",
aleita:"Compatível",
ped:"≥4a: 50 mcg 12/12h",
},
mecanismo:"β-2 AGONISTA seletivo de LONGA DURAÇÃO (12h). INÍCIO LENTO (15-30 min) — não pode ser usado como reliever. Cauda lipofílica longa que ancora no receptor.",
farmacocin:{
absorc:"INH local",
distrib:"Pulmão",
metab:"Hepático (CYP3A4)",
elimin:"Fecal (60%) + urinária",
meiavida:"~5,5h (efeito 12h por ancoragem ao receptor)",
ligacao:"96%",
},
ef_colats:{
comuns:["Tremor","Taquicardia","Cefaleia","Cãibras","Candidíase oral (com fluticasona)"],
sérios:["Arritmia","Hipocalemia"],
},
interacoes:["Betabloqueadores: antagonismo","IMAO","Inibidores CYP3A4 fortes (cetoconazol, ritonavir): aumentam exposição"],
contraindicacoes:["LABA ISOLADO em asma — proibido","Hipersensibilidade"],
monit:["FC","K","Sintomas/exacerbações"],
gravidez:"C",
sus:"⚠ Em algumas SES regionais via componente especializado (CEAF). Não REMUME nacional.",
referencias:["GINA 2025","GOLD 2025"],
},

{id:"med-indacaterol", classe:"LABA — β-2 agonista ultralonga ação (24h)",
grupo:"bd",
nome:"Indacaterol",
sin:["Onbrize","Hirobriz"],
formas:["DPI Breezhaler 150 e 300 mcg/cápsula","Combinação indacaterol + glicopirrônio (Ultibro) 110/50 mcg"],
resumo:"LABA de 24h — administração 1×/d. Usado em DPOC, geralmente em combinação fixa LABA-LAMA. Início mais rápido que salmeterol (~5 min).",
dose_rapida:"150-300 mcg DPI 1×/d (DPOC)",
doses:[
{ind:"DPOC — manutenção", dose:"150 mcg DPI 1×/d (até 300 mcg em casos selecionados)", obs:"GOLD 2025: opção em GRUPO A (LABA isolado). Em B/E: preferir combinação."},
{ind:"DPOC em combinação", dose:"Indacaterol/glicopirrônio 110/50 mcg DPI 1×/d (Ultibro)", obs:"LABA-LAMA — combinação de 24h."},
],
ajustes:{
irc:"Sem ajuste",
iht:"Leve-moderada: sem ajuste. Grave: cautela.",
idoso:"Sem ajuste",
gestante:"Categoria C",
aleita:"Sem dados",
ped:"Não aprovado <18a",
},
mecanismo:"β-2 AGONISTA seletivo de ULTRALONGA AÇÃO (24h) — primeira opção 1×/d. Início 5 min, pico 15 min.",
farmacocin:{
absorc:"INH local",
distrib:"Pulmão",
metab:"Hepático (UGT1A1, CYP3A4)",
elimin:"Fecal (90%) + urinária",
meiavida:"~40-50h",
ligacao:"94-96%",
},
ef_colats:{
comuns:["Tosse pós-inalação (10%)","Cefaleia","Tremor","Faringite"],
sérios:["Broncoespasmo paradoxal","Arritmia","Hipocalemia"],
},
interacoes:["Betabloqueadores","Diuréticos K-pertuelantes","Inibidores CYP3A4"],
contraindicacoes:["Hipersensibilidade"],
monit:["FC","K"],
gravidez:"C",
sus:"⚠ Não REMUME. Componente especializado em DPOC grave em algumas SES.",
referencias:["GOLD 2025","Bula Onbrize"],
},

{id:"med-olodaterol", classe:"LABA — β-2 agonista ultralonga ação (24h)", grupo:"bd",
nome:"Olodaterol",
sin:["Striverdi","Spiolto (combinação)"],
formas:["Respimat — solução inalatória 2,5 mcg/puff (2 puffs = 5 mcg dose)","Combinação tiotrópio + olodaterol (Spiolto Respimat) 2,5/2,5 mcg"],
resumo:"LABA de 24h — alternativa ao indacaterol. Disponível em Respimat (névoa lenta — boa coordenação) ou em combinação com tiotrópio.",
dose_rapida:"5 mcg (2 puffs Respimat) 1×/d (DPOC)",
doses:[
{ind:"DPOC — manutenção", dose:"5 mcg Respimat 1×/d (2 puffs)", obs:"GOLD 2025: opção 24h em DPOC."},
{ind:"DPOC em combinação LABA-LAMA", dose:"Tiotrópio/olodaterol 2,5/2,5 mcg Respimat 1×/d (Spiolto)", obs:"Combinação LABA-LAMA em formato Respimat."},
],
ajustes:{
irc:"Sem ajuste",
iht:"Leve: sem ajuste. Moderada-grave: cautela.",
idoso:"Sem ajuste",
gestante:"Categoria C",
aleita:"Sem dados",
ped:"Não aprovado <18a",
},
mecanismo:"β-2 AGONISTA seletivo 24h. Respimat = inalador com névoa lenta — facilita inalação coordenada.",
farmacocin:{
absorc:"INH local",
distrib:"Pulmão",
metab:"Hepático",
elimin:"Urinária + biliar",
meiavida:"~45h",
ligacao:"60%",
},
ef_colats:{
comuns:["Nasofaringite","Tosse","Tontura"],
sérios:["Broncoespasmo paradoxal","Arritmia"],
},
interacoes:["Betabloqueadores","Diuréticos"],
contraindicacoes:["Hipersensibilidade"],
monit:["FC","K"],
gravidez:"C",
sus:"Não REMUME nacional",
referencias:["GOLD 2025"],
},

/* ============== LAMA — ANTICOLINÉRGICO LONGA AÇÃO ============== */

{id:"med-tiotropio", classe:"LAMA — anticolinérgico de longa duração",
grupo:"bd",
nome:"Tiotrópio",
sin:["Spiriva","Spiriva HandiHaler","Spiriva Respimat"],
formas:["HandiHaler — cápsulas 18 mcg DPI (dose 1×/d)","Respimat — solução 2,5 mcg/puff (2 puffs = 5 mcg 1×/d)","SUS REMUME — componente especializado em DPOC moderada-grave"],
resumo:"LAMA de referência. Bloqueia receptor muscarínico M3 — broncodilatação por inibição vagal. 24h de ação. Padrão GOLD em DPOC grupo A e como base de combinações.",
dose_rapida:"18 mcg DPI ou 5 mcg Respimat 1×/d",
doses:[
{ind:"DPOC — manutenção (Grupo A)", dose:"18 mcg DPI 1×/d OU 5 mcg Respimat 1×/d", obs:"1ª linha em DPOC com sintomas leves-moderados sem exacerbações."},
{ind:"DPOC em combinação", dose:"Em combinação LABA-LAMA: tiotrópio + olodaterol 2,5/2,5 mcg Respimat 1×/d (Spiolto)", obs:"Grupo B/E."},
{ind:"Asma grave (degrau 4-5)", dose:"2,5 mcg Respimat 1×/d (off-label aprovado em adultos com asma grave)", obs:"GINA 2025: add-on em asma grave não controlada por ICS-LABA."},
],
ajustes:{
irc:"TFG <50: cautela (acumulação). Idoso + IRC: monitor",
iht:"Sem ajuste",
idoso:"Cautela em IRC. Monitor sintomas anticolinérgicos.",
gestante:"Categoria C",
aleita:"Compatível",
ped:"≥6a: 2,5 mcg Respimat 1×/d (em asma grave; off-label)",
},
mecanismo:"ANTIMUSCARÍNICO seletivo M3 (e M1) com lenta dissociação — efeito 24h. Bloqueio do tônus vagal brônquico = broncodilatação.",
farmacocin:{
absorc:"INH local; <2% sistêmico",
distrib:"Pulmão",
metab:"Hepático mínimo (renal predominante)",
elimin:"Renal (74% via ativa)",
meiavida:"~25h",
ligacao:"72%",
},
ef_colats:{
comuns:["Xerostomia (boca seca) — 5-15%","Constipação","Tosse","Faringite"],
sérios:["Retenção urinária (em HPB)","Glaucoma de ângulo fechado (em predisposto)","Arritmia (raro)"],
},
interacoes:["Outros anticolinérgicos: somatório de efeitos","Cuidado com ipratrópio simultâneo (sobreposição farmacológica)"],
contraindicacoes:["Hipersensibilidade","Glaucoma de ângulo fechado","HPB descompensada","Retenção urinária"],
monit:["Função vesical/intestinal","Sintomas anticolinérgicos"],
gravidez:"C",
sus:"REMUME — componente especializado (CEAF). DPOC moderada-grave com critérios.",
referencias:["GOLD 2025","GINA 2025 (add-on asma grave)"],
},

{id:"med-glicopirronio", classe:"LAMA — anticolinérgico de longa duração", grupo:"bd",
nome:"Glicopirrônio (brometo)",
sin:["Seebri Breezhaler","Tovanor Breezhaler"],
formas:["DPI 50 mcg/cápsula — Breezhaler 1×/d","Combinação indacaterol + glicopirrônio (Ultibro) 110/50 mcg"],
resumo:"LAMA alternativo de 24h. Disponível em combinação fixa LABA-LAMA (Ultibro). Eficácia similar ao tiotrópio em DPOC.",
dose_rapida:"50 mcg DPI 1×/d",
doses:[
{ind:"DPOC — monoterapia (Grupo A)", dose:"50 mcg DPI 1×/d (Seebri)", obs:""},
{ind:"DPOC em combinação LABA-LAMA", dose:"Indacaterol/glicopirrônio 110/50 mcg DPI 1×/d (Ultibro)", obs:"Grupo B/E."},
],
ajustes:{
irc:"TFG <30: dose mantida; monitor",
iht:"Sem ajuste",
idoso:"Sem ajuste",
gestante:"C",
aleita:"Sem dados",
ped:"Não aprovado <18a",
},
mecanismo:"Antimuscarínico seletivo M3.",
farmacocin:{
absorc:"INH",
distrib:"Pulmão",
metab:"Mínimo (CYP2D6)",
elimin:"Renal (~60%)",
meiavida:"~33-57h",
ligacao:"38-41%",
},
ef_colats:{
comuns:["Xerostomia","Constipação","Cefaleia"],
sérios:["Retenção urinária","Glaucoma"],
},
interacoes:["Outros anticolinérgicos"],
contraindicacoes:["Hipersensibilidade","HPB descompensada","Glaucoma de ângulo fechado"],
monit:["Sintomas anticolinérgicos"],
gravidez:"C",
sus:"Não REMUME nacional",
referencias:["GOLD 2025"],
},

{id:"med-umeclidinio", classe:"LAMA — anticolinérgico de longa duração", grupo:"bd",
nome:"Umeclidínio",
sin:["Incruse Ellipta","Anoro Ellipta (combinação)"],
formas:["DPI Ellipta 62,5 mcg/dose 1×/d","Combinação umeclidínio + vilanterol (Anoro) 62,5/25 mcg","Tripla — fluticasona+umeclidínio+vilanterol (Trelegy) 100/62,5/25 mcg"],
resumo:"LAMA de 24h em formato Ellipta — fácil uso (1 puff/d). Disponível em combinação dupla (Anoro) e TRIPLA (Trelegy).",
dose_rapida:"62,5 mcg DPI Ellipta 1×/d",
doses:[
{ind:"DPOC — monoterapia (Grupo A)", dose:"62,5 mcg DPI 1×/d (Incruse)", obs:""},
{ind:"DPOC dupla LABA-LAMA", dose:"Umeclidínio/vilanterol 62,5/25 mcg DPI 1×/d (Anoro)", obs:"Grupo B/E sem indicação de ICS."},
{ind:"DPOC tripla LABA-LAMA-ICS", dose:"Fluticasona/umeclidínio/vilanterol 100/62,5/25 mcg DPI 1×/d (Trelegy)", obs:"Grupo E com eos ≥300 ou exacerbador grave."},
],
ajustes:{
irc:"Sem ajuste",
iht:"Sem ajuste",
idoso:"Sem ajuste",
gestante:"C",
aleita:"Sem dados",
ped:"Não aprovado <18a",
},
mecanismo:"Antimuscarínico seletivo M3.",
farmacocin:{
absorc:"INH",
distrib:"Pulmão",
metab:"Hepático (CYP2D6)",
elimin:"Fecal (58%) + urinária",
meiavida:"~11h",
ligacao:"89%",
},
ef_colats:{
comuns:["Xerostomia","Faringite","Tosse"],
sérios:["Retenção urinária","Glaucoma"],
},
interacoes:["Outros anticolinérgicos"],
contraindicacoes:["Hipersensibilidade","HPB descompensada","Glaucoma de ângulo fechado"],
monit:["Sintomas anticolinérgicos"],
gravidez:"C",
sus:"Não REMUME nacional",
referencias:["GOLD 2025"],
},

/* ============== ICS — CORTICOIDES INALATÓRIOS ============== */

{id:"med-budesonida", classe:"ICS — corticosteroide inalatório (média potência)", grupo:"bd",
nome:"Budesonida",
sin:["Pulmicort","Budecort","Miflonide","Symbicort (combinação)"],
formas:["DPI Turbuhaler 100, 200, 400 mcg/dose","Aerolizer 200, 400 mcg/cápsula","Solução nebulizar 0,25 e 0,5 mg/mL ampolas","SUS REMUME — Pulmicort solução 0,5 mg/mL em algumas SES"],
resumo:"ICS de média potência. Combinação budesonida-formoterol (Symbicort) é o padrão MART do GINA. Solução nebulizar útil em crise asmática aguda (criança e adulto).",
dose_rapida:"200-800 mcg/d DPI dividido 1-2×/d (asma); 1-2 mg NBZ 2-3×/d (crise/criança)",
doses:[
{ind:"Asma persistente (TRACK 2 / monoterapia ICS)", dose:"200-400 mcg DPI 12/12h (dose baixa); 400-800 mcg 12/12h (média); >800 mcg/d (alta)", obs:"ICS isolado é Track 2 GINA. Preferir Track 1 (ICS-formoterol)."},
{ind:"Asma — combinação budesonida-formoterol (Symbicort)", dose:"200/6 ou 400/12 mcg DPI — esquema MART", obs:"Padrão atual GINA 2025."},
{ind:"DPOC — combinação com LABA (em grupo E com eos altos)", dose:"Símbicort 200/6 mcg 2 inal 2×/d em DPOC", obs:"ICS isolado NÃO em DPOC. Combinação dupla LABA-ICS ou tripla LABA-LAMA-ICS."},
{ind:"Crise asmática — solução nebulizada", dose:"1-2 mg NBZ a cada 12h (adulto); 0,5-1 mg NBZ a cada 12h (criança)", obs:"Adjunto ao tratamento padrão."},
{ind:"Crupe moderado-grave em criança", dose:"2 mg NBZ dose única", obs:"Alternativa à dexametasona oral."},
],
ajustes:{
irc:"Sem ajuste",
iht:"Cautela em IH grave",
idoso:"Sem ajuste",
gestante:"⚠ Categoria B — ICS preferido em asma gestacional. NÃO suspender. Manter controle.",
aleita:"Compatível",
ped:"≥6m em nebulização. ≥6a em DPI 200-400 mcg/d.",
},
mecanismo:"CORTICOSTEROIDE GLICOCORTICOIDE — efeito anti-inflamatório local. Reduz citocinas, eosinófilos, hiperreatividade. Baixa absorção sistêmica em dose terapêutica.",
farmacocin:{
absorc:"INH local; ~25% sistêmico",
distrib:"Pulmão local",
metab:"Hepático (CYP3A4) — primeiro passo importante",
elimin:"Urinária (60%)",
meiavida:"~2-3h",
ligacao:"85-90%",
},
ef_colats:{
comuns:["Candidíase oral (uso sem espaçador, sem bochecho)","Disfonia","Tosse pós-inalação"],
sérios:["Pneumonia em DPOC (ICS aumenta risco)","Supressão adrenal (em dose alta crônica)","Glaucoma/catarata (uso muito prolongado e alto)","Redução modesta do crescimento em criança (~1 cm na altura final)"],
},
interacoes:["Inibidores CYP3A4 (cetoconazol, ritonavir): aumentam exposição","Outros corticoides: somatório"],
contraindicacoes:["Hipersensibilidade","TB pulmonar ativa não tratada (relativa)"],
monit:["Adesão + técnica inalatória","Candidíase oral","Crescimento em criança","Densidade óssea em uso muito prolongado"],
gravidez:"⚠ B — preferido em asma gestacional (NÃO SUSPENDER)",
sus:"Pulmicort solução: REMUME em algumas SES. DPI/combinação: componente especializado.",
referencias:["GINA 2025","GOLD 2025","SBPT"],
},

{id:"med-fluticasona", classe:"ICS — corticosteroide inalatório (alta potência)", grupo:"bd",
nome:"Fluticasona (propionato e furoato)",
sin:["Flixotide","Flovent","Seretide (combinação)","Trelegy (tripla)","Arnuity Ellipta (furoato)"],
formas:["MDI 50, 125, 250 mcg/puff (propionato)","Diskus DPI 100, 250, 500 mcg/dose","Ellipta DPI 100, 200 mcg (furoato — 1×/d)","Combinação seretide (fluticasona + salmeterol) Diskus 100/50, 250/50, 500/50","Combinação Trelegy (furoato + umeclidínio + vilanterol) Ellipta 100/62,5/25 mcg","NÃO REMUME nacional"],
resumo:"ICS de ALTA POTÊNCIA. Propionato (12/12h) é o clássico (Seretide). Furoato (1×/d) é a versão moderna (Trelegy tripla). Asma persistente moderada-grave + DPOC com ICS.",
dose_rapida:"PROPIONATO 100-500 mcg 12/12h; FUROATO 100-200 mcg 1×/d",
doses:[
{ind:"Asma persistente — fluticasona propionato monoterapia", dose:"100-250 mcg 12/12h (dose baixa-média)", obs:""},
{ind:"Asma persistente — combinação fluticasona-salmeterol (Seretide)", dose:"100/50, 250/50 ou 500/50 mcg Diskus 12/12h", obs:"Track 2 GINA — ICS-LABA em paciente que não aceita MART."},
{ind:"Asma persistente — fluticasona furoato monoterapia (Arnuity)", dose:"100-200 mcg Ellipta 1×/d", obs:"Posologia 1×/d."},
{ind:"DPOC — tripla (Trelegy)", dose:"Fluticasona furoato 100 + umeclidínio 62,5 + vilanterol 25 mcg Ellipta 1×/d", obs:"Grupo E com eos altos ou exacerbador."},
],
ajustes:{
irc:"Sem ajuste",
iht:"Cautela em IH grave (acumulação)",
idoso:"Sem ajuste",
gestante:"⚠ C — alternativa quando budesonida insuficiente",
aleita:"Compatível",
ped:"≥4a (propionato); ≥5a (furoato em Ellipta)",
},
mecanismo:"GLICOCORTICOIDE de alta potência tópica. Propionato — biodisponibilidade sistêmica baixa por extensa primeira passagem hepática (CYP3A4). Furoato — similar mas 1×/d.",
farmacocin:{
absorc:"INH ~30%",
distrib:"Pulmão",
metab:"Hepático (CYP3A4) — extenso primeiro passo",
elimin:"Fecal (>90%)",
meiavida:"~8-10h (propionato); ~24h (furoato)",
ligacao:"91%",
},
ef_colats:{
comuns:["Candidíase oral","Disfonia","Tosse"],
sérios:["⚠ Pneumonia em DPOC (>tiotrópio)","Supressão adrenal em dose alta","Catarata/glaucoma","Redução estatura"],
},
interacoes:["⚠ INIBIDORES CYP3A4 (ritonavir, cobicistate, cetoconazol, claritromicina): aumentam exposição sistêmica — síndrome de Cushing iatrogênica documentada"],
contraindicacoes:["Hipersensibilidade","TB pulmonar ativa não tratada (relativa)"],
monit:["Adesão + técnica","Candidíase oral","Cortisol matinal em uso alto crônico","Densidade óssea"],
gravidez:"C",
sus:"⚠ Não REMUME. Componente especializado (CEAF) em asma grave / DPOC moderada-grave.",
referencias:["GINA 2025","GOLD 2025"],
},

{id:"med-beclometasona", classe:"ICS — corticosteroide inalatório (baixa-média potência)", grupo:"bd",
nome:"Beclometasona",
sin:["Clenil","Qvar","Beclosol","Foster (combinação)"],
formas:["MDI Clenil 50, 200, 250 mcg/puff (HFA reformulado — partículas pequenas)","Qvar 80 e 100 mcg/puff","Combinação beclometasona + formoterol (Foster, Fostair) 100/6 mcg MDI","SUS REMUME — Beclometasona 50 mcg MDI em algumas SES (limitado)"],
resumo:"ICS clássico de baixa-média potência. Reformulado HFA (Clenil) com partículas extrafinas alcança vias aéreas pequenas. Combinação beclometasona-formoterol (Foster) é opção MART acessível.",
dose_rapida:"100-400 mcg 12/12h (HFA tem dose menor que CFC antigo)",
doses:[
{ind:"Asma persistente leve-moderada", dose:"100-400 mcg 12/12h (HFA partículas extrafinas)", obs:"Dose equivalente a 200-800 mcg de beclometasona antiga CFC."},
{ind:"Asma — combinação beclometasona-formoterol (Foster)", dose:"100/6 mcg 1-2 puff 1-2×/d ± PRN (MART)", obs:"Esquema MART em paciente que prefere MDI a DPI."},
],
ajustes:{
irc:"Sem ajuste",
iht:"Cautela",
idoso:"Sem ajuste",
gestante:"C",
aleita:"Compatível",
ped:"≥5a",
},
mecanismo:"Glicocorticoide tópico — efeito anti-inflamatório local. HFA com partículas pequenas alcança vias aéreas distais.",
farmacocin:{
absorc:"INH",
distrib:"Pulmão",
metab:"Hepático (metabólito ativo BMP)",
elimin:"Fecal predominante",
meiavida:"~3h (beclometasona); ~7h (metabólito ativo BMP)",
ligacao:"87%",
},
ef_colats:{
comuns:["Candidíase oral","Disfonia","Tosse"],
sérios:["Supressão adrenal","Catarata/glaucoma","Pneumonia em DPOC (menor que fluticasona)"],
},
interacoes:["Inibidores CYP3A4"],
contraindicacoes:["Hipersensibilidade","TB pulmonar ativa não tratada (relativa)"],
monit:["Adesão + técnica","Candidíase oral"],
gravidez:"C",
sus:"⚠ Em algumas SES como REMUME. Componente especializado para combinação Foster.",
referencias:["GINA 2025"],
},

/* ============== SAMA — ANTICOLINÉRGICO CURTA AÇÃO ============== */

{id:"med-ipratropio", classe:"SAMA — anticolinérgico de curta duração", grupo:"bd",
nome:"Ipratrópio (brometo)",
sin:["Atrovent","Atrovent N","Combivent (com salbutamol)"],
formas:["MDI 20 mcg/puff (Atrovent N HFA)","Solução nebulizar 0,025% (250 mcg/mL — 0,5 mg/2mL ampola)","Combinação ipratrópio + salbutamol (Combivent) 0,5 mg + 2,5 mg ampola NBZ; 20+100 mcg MDI","SUS REMUME — Atrovent solução 0,25 mg/mL ampolas; Atrovent N spray"],
resumo:"SAMA — antimuscarínico de curta duração (4-6h). Usado em CRISES (asma, DPOC) e como broncodilatador em paciente com intolerância a SABA (taquicardia). Combinado com salbutamol em emergência (Combivent) potencializa efeito.",
dose_rapida:"40-80 mcg MDI; 0,25-0,5 mg NBZ a cada 4-6h",
doses:[
{ind:"Crise asmática — em nebulização combinada com salbutamol", dose:"Ipratrópio 0,5 mg + salbutamol 5 mg NBZ a cada 20 min × 3 doses, depois 1-4h", obs:"Adjunto em crise moderada-grave. Combivent é a apresentação combinada."},
{ind:"Exacerbação de DPOC", dose:"Ipratrópio 0,5 mg NBZ a cada 4-6h ± salbutamol", obs:"Broncodilatador de resgate."},
{ind:"DPOC — manutenção (alternativa em paciente que não tolera SABA)", dose:"Ipratrópio MDI 20 mcg 2 puffs 4-6×/d", obs:"Menos eficaz que LABA-LAMA. Reserva para casos selecionados."},
{ind:"Rinorreia anticolinérgica (uso off-label)", dose:"Spray nasal 0,03-0,06% 2 jatos cada narina 2-3×/d", obs:"Em rinorreia por exposição ao frio, rinite vasomotora."},
],
ajustes:{
irc:"Sem ajuste",
iht:"Sem ajuste",
idoso:"Cautela em HPB, glaucoma",
gestante:"⚠ B — compatível em crise",
aleita:"Compatível",
ped:"≥1a NBZ 0,125-0,25 mg; ≥6a MDI 1-2 puff",
},
mecanismo:"ANTAGONISTA MUSCARÍNICO NÃO seletivo (curta duração). Broncodilatação por bloqueio do tônus vagal. Início 15 min, pico 1-2h, duração 4-6h.",
farmacocin:{
absorc:"INH; <1% sistêmico (sal quaternário não atravessa membranas)",
distrib:"Pulmão local",
metab:"Mínimo",
elimin:"Renal/fecal",
meiavida:"~1,6h",
ligacao:"Baixa",
},
ef_colats:{
comuns:["Xerostomia","Gosto amargo","Tosse"],
sérios:["Retenção urinária","Glaucoma de ângulo fechado","Broncoespasmo paradoxal"],
},
interacoes:["Outros anticolinérgicos (incluindo tiotrópio): NÃO USAR JUNTO (sobreposição)"],
contraindicacoes:["Hipersensibilidade","Glaucoma de ângulo fechado","HPB descompensada"],
monit:["Sintomas anticolinérgicos","Eficácia em crise"],
gravidez:"B",
sus:"REMUME — Atrovent solução nebulizar.",
referencias:["GINA 2025","GOLD 2025","SBPT"],
},

);
