/* ===========================================================
   VOVÔMINIC EMERGÊNCIA — BIBLIOTECA DE MEDICAÇÕES (PARTE 16)
   Bloco E Rodada 3 — Tetras + Sulfa + Clinda + Metro + Genta + Nitro + Fosfo
   =========================================================== */

MEDICACOES.push(

/* ============== DOXICICLINA ============== */

{id:"med-doxiciclina", classe:"Tetraciclina (longa duração)", grupo:"atb",
nome:"Doxiciclina",
sin:["Vibramycin","Doxycin","Vibravenosa (IV)"],
formas:["Cápsula / comprimido 100 mg","Suspensão 50 mg/5 mL (raro)","REMUME — UBS dispensação direta + PFPB"],
resumo:"⚠ ESPECTRO: ATÍPICOS (Chlamydia, Mycoplasma, Rickettsia, Coxiella — febre Q, Borrelia — Lyme), G+ limitados (S. aureus incluindo CA-MRSA, Strep limitado), G- (H. influenzae, alguns enterobactérias, Vibrio), ZOONOSES (leptospirose, brucelose, ehrlichiose), espiroquetas (sífilis em alergia, Lyme), MALÁRIA (profilaxia). PEGA BEM EM: DST por Chlamydia (1ª linha — 7d superior à azitromicina), acne moderada-grave, rosácea, leptospirose, riquettsiose, Lyme, malária (profilaxia). NÃO PEGA: anaeróbios bem, Pseudomonas, Proteus, enterococo.",
dose_rapida:"100 mg VO 12/12h × 7-21d",
doses:[
{ind:"⚠ CHLAMYDIA / NGU — 1ª LINHA atual (PCDT-MS atualização)", dose:"100 mg VO 12/12h × 7 dias", obs:"⚠ Cura SUPERIOR à azitromicina dose única (Geisler et al). PCDT-MS atualiza priorizando doxi quando possível adesão. Em gestante: NÃO USAR — preferir azitromicina."},
{ind:"⚠ LEPTOSPIROSE (forma leve / profilaxia)", dose:"100 mg VO 12/12h × 7 dias (tratamento); 200 mg/sem (profilaxia em exposição prolongada)", obs:"⚠ 1ª LINHA em forma leve ambulatorial. Forma grave (Síndrome de Weil): ceftriaxona IV + hospitalização. PCDT-MS Leptospirose."},
{ind:"⚠ RIQUETTSIOSE / FEBRE MACULOSA BRASILEIRA", dose:"100 mg VO/IV 12/12h × 7 dias (mínimo 3 dias após cessar febre)", obs:"⚠ 1ª LINHA — INICIAR EMPÍRICA na suspeita (NÃO esperar sorologia — mortalidade alta em retardo). Carrapato. Mata em <14 dias se não tratado."},
{ind:"Acne vulgar moderada-grave (inflamatória)", dose:"100 mg VO 1×/d × 3-6 meses", obs:"Dermatologia. Reduz inflamação + Cutibacterium acnes."},
{ind:"Rosácea pápulo-pustular", dose:"40-100 mg VO 1×/d × 1-3 meses", obs:"Dermatologia."},
{ind:"PAC atípica (alternativa em alérgico a macrolídeo)", dose:"100 mg 12/12h × 7-10 dias", obs:""},
{ind:"DPOC exacerbação (alternativa)", dose:"100 mg 12/12h × 5-7 dias", obs:""},
{ind:"Profilaxia de MALÁRIA em viajante a região endêmica (Plasmodium falciparum)", dose:"100 mg 1×/d — começar 1-2 dias antes, durante exposição, até 4 semanas após", obs:""},
{ind:"⚠ DOENÇA DE LYME (raro Brasil — viajantes)", dose:"100 mg 12/12h × 14-21 dias", obs:""},
{ind:"Brucelose", dose:"100 mg 12/12h × 6 semanas + rifampicina", obs:"Infectologia."},
{ind:"DIP (Doença Inflamatória Pélvica)", dose:"100 mg 12/12h × 14 dias + metronidazol + ceftriaxona dose única", obs:"PCDT-MS IST."},
{ind:"⚠ MORDIDA DE CARRAPATO em área endêmica — profilaxia", dose:"200 mg VO dose única", obs:"⚠ Borrelia em até 72h após picada de Ixodes em área Lyme endêmica. Não rotineiro em Brasil."},
{ind:"Sífilis em alergia à penicilina (não gestante)", dose:"100 mg VO 12/12h × 14 dias (sífilis primária/secundária); 28 dias (latente)", obs:"⚠ Alternativa não preferida — sempre tentar dessensibilização à penicilina primeiro."},
],
ajustes:{
irc:"Sem ajuste (não eliminada por rim)",
iht:"Cautela em IH grave",
idoso:"Sem ajuste — boa opção em idoso com IRC",
gestante:"⚠ ⚠ ⚠ CATEGORIA D — CONTRAINDICADA. Causa coloração permanente de dentes do feto + hipoplasia do esmalte + inibição crescimento ósseo (>16 sem).",
aleita:"⚠ Evitar em uso prolongado — coloração de dentes do lactente. Em curto prazo: aceitável.",
ped:"⚠ ⚠ EVITAR <8 ANOS — coloração permanente de dentes + hipoplasia esmalte. Exceção: doença com risco de vida (riquettsiose, antrax) — benefício > risco.",
},
mecanismo:"BACTERIOSTÁTICO. Liga-se à subunidade 30S ribossomal — inibe síntese proteica. Concentra intracelularmente (atinge patógenos intracelulares).",
farmacocin:{
absorc:"VO ~95% — ⚠ QUELAÇÃO por cátions di/trivalentes (Ca, Mg, Al, Fe, Zn — laticínios, antiácidos, ferro). Tomar 2h antes ou 4h após.",
distrib:"Ampla incluindo intracelular",
metab:"Mínimo",
elimin:"Fecal predominante (não renal!) — boa opção em IRC",
meiavida:"~18-22h (1-2×/d)",
ligacao:"~80-90%",
},
ef_colats:{
comuns:["⚠ Fotossensibilidade (frequente — orientar protetor solar)","Náusea","Diarreia","Candidíase","Esofagite (engolir com água + ortostase 30 min após)"],
sérios:["Hepatotoxicidade","Hipertensão intracraniana benigna (pseudotumor cerebri)","Stevens-Johnson","Anafilaxia","Colite C. difficile (incomum — preferida em risco de Cdiff)"],
},
interacoes:["Cátions di/trivalentes — quelação","Warfarina: ↑ INR","Anticoncepcionais orais: ↓ eficácia (questionável)","Anticonvulsivantes (fenitoína, carbamazepina): ↓ doxi","Rifampicina: ↓ doxi","Methoxyflurano: nefrotoxicidade"],
contraindicacoes:["⚠ Gestação","⚠ Criança <8a","Alergia a tetraciclinas","Hipersensibilidade"],
monit:["Sintomas hepáticos","Sintomas neurológicos (cefaleia + papiledema)","Adesão a posologia (com água, ortostase)"],
gravidez:"⚠ D",
sus:"⚠ REMUME — UBS dispensação direta + PFPB.",
referencias:["⚠ PCDT-MS IST","PCDT-MS Leptospirose","PCDT-MS Febre Maculosa","Sanford"],
},

/* ============== SULFAMETOXAZOL + TRIMETOPRIM ============== */

{id:"med-smx-tmp", classe:"Sulfonamida + diaminopirimidina (sinérgica)", grupo:"atb",
nome:"Sulfametoxazol + Trimetoprim (SMX-TMP, Bactrim)",
sin:["Bactrim","Bactrim F (forte)","Cotrimoxazol","Septrin","TMP-SMX"],
formas:["Comprimido 400+80 mg (simples)","Comprimido 800+160 mg (FORTE / DS)","Suspensão 200+40 mg/5 mL","Frasco-ampola 400+80 mg IV","REMUME — UBS dispensação direta + PFPB"],
resumo:"⚠ ESPECTRO: AMPLO — G+ (S. aureus incluindo CA-MRSA, Strep limitado, Listeria, Nocardia), G- (E. coli, Klebsiella, Proteus, Shigella, Salmonella), Pneumocystis jirovecii, Stenotrophomonas. PEGA BEM EM: ITU não complicada, CA-MRSA pele (1ª linha), pneumocistose (PCP em HIV), profilaxia em HIV/transplantado, toxoplasmose (alternativa), nocardia. NÃO PEGA: anaeróbios, Pseudomonas, Treponema, atípicos respiratórios.",
dose_rapida:"800/160 mg (1 comp F) VO 12/12h × 3-14d (variável por infecção)",
doses:[
{ind:"⚠ ITU NÃO COMPLICADA cistite", dose:"800/160 mg (1 comp F) 12/12h × 3 dias", obs:"⚠ 1ª linha em região com resistência E. coli a SMX-TMP <20% (Brasil tem regiões com >20% — preferir nitrofurantoína ou fosfomicina nessas áreas)."},
{ind:"⚠ CELULITE / ABSCESSO com SUSPEITA DE CA-MRSA", dose:"800/160 mg 12/12h × 5-10 dias (+ drenagem de abscesso)", obs:"⚠ Cobertura CA-MRSA — preferida em pessoa com surto familiar de furunculose, usuário de drogas IV, áreas com alta prevalência."},
{ind:"⚠ Pneumocistose (PCP / Pneumocystis jirovecii) em HIV/imunossuprimido", dose:"15-20 mg/kg/d de trimetoprim ÷ 6/6h × 21 dias (tratamento); 800/160 mg 1×/d 3×/sem ad lib (profilaxia)", obs:"⚠ Profilaxia em HIV com CD4 <200; transplantado renal."},
{ind:"Toxoplasmose (alternativa a sulfadiazina+pirimetamina)", dose:"800/160 mg 12/12h × 4-6 semanas", obs:"Em HIV. Profilaxia: 800/160 mg/d."},
{ind:"Diarreia bacteriana (Shigella, Salmonella, ETEC)", dose:"800/160 mg 12/12h × 3-5 dias", obs:"Resistência crescente em algumas regiões."},
{ind:"Prostatite crônica bacteriana (alternativa)", dose:"800/160 mg 12/12h × 1-3 meses", obs:"Quinolona é preferida."},
{ind:"Acne vulgar (alternativa)", dose:"800/160 mg/d × 3 meses", obs:""},
{ind:"Nocardia", dose:"15-20 mg/kg/d ÷ 6/6h × 6-12 meses", obs:"Infectologia."},
{ind:"Profilaxia em paciente imunossuprimido (transplantado, HIV)", dose:"800/160 mg 1×/d 3×/sem OU 400/80 mg 1×/d", obs:""},
],
ajustes:{
irc:"TFG 15-30: 50% dose. TFG <15: EVITAR (acúmulo + risco hiperK + cristalúria). Hemodiálise: pós.",
iht:"⚠ Cautela em IH grave",
idoso:"⚠ Maior risco HIPERPOTASSEMIA + IRA + delirium + interação warfarina. Evitar em paciente frágil sem alternativa.",
gestante:"⚠ C (1º trimestre — antagonismo folato → defeitos do tubo neural). ⚠ EVITAR no 3º trimestre — KERNICTERUS por deslocamento da bilirrubina.",
aleita:"⚠ Compatível >1 mês. Evitar em RN/lactente <1 mês.",
ped:"6-12 mg/kg/d ÷ 12/12h (trimetoprim). ⚠ NÃO USAR <2 MESES — kernicterus.",
},
mecanismo:"⚠ SINERGISMO — SULFAMETOXAZOL bloqueia di-hidropteroato sintetase + TRIMETOPRIM bloqueia di-hidrofolato redutase = inibição sequencial da síntese de FOLATO bacteriano → bactericida. Bactérias dependem de síntese de folato (humanos absorvem da dieta).",
farmacocin:{
absorc:"VO ~90-100% (excelente)",
distrib:"Ampla — bom em próstata, pulmão, urina concentrada",
metab:"Hepático parcial",
elimin:"Renal (50-80% inalterada)",
meiavida:"SMX ~10h / TMP ~10h",
ligacao:"SMX 70% / TMP 44%",
},
ef_colats:{
comuns:["Rash maculopapular","Náusea/vômito","Diarreia","Candidíase","Cefaleia"],
sérios:["⚠ HIPERPOTASSEMIA (especialmente IRC, idoso, com IECA/BRA/espironolactona)","⚠ IRA (cristalúria + nefrite intersticial)","⚠ Stevens-Johnson / NET — RISCO RELATIVAMENTE ALTO entre os ATBs","⚠ Anemia hemolítica em deficiência de G6PD","Anemia megaloblástica (antagonismo folato)","Trombocitopenia, neutropenia","Hepatotoxicidade","Pseudotumor cerebri","Colite C. difficile","⚠ HIPOGLICEMIA em DM com sulfonilureia (potencializa)","⚠ Kernicterus em neonato"],
},
interacoes:["⚠ Warfarina: ↑ INR significativo","⚠ Sulfonilureias: hipoglicemia","⚠ IECA/BRA/espironolactona: HIPER-K","⚠ Metotrexato: toxicidade aditiva","⚠ Anticonvulsivantes (fenitoína): toxicidade","Diuréticos tiazídicos: hipoNA","ACO: ↓ eficácia (rara)"],
contraindicacoes:["⚠ Alergia a sulfas","⚠ Gestação 3º trimestre + neonato <2m","⚠ Deficiência G6PD (relativa — risco hemólise)","⚠ Discrasia sanguínea","⚠ IH grave","TFG <15"],
monit:["⚠ K, função renal","Hemograma em uso prolongado","INR se varfarina","Rash — INTERROMPER ao menor sinal de SJS"],
gravidez:"⚠ C (D no 3º trimestre)",
sus:"REMUME — UBS + PFPB.",
referencias:["IDSA","PCDT-MS HIV","Sanford"],
},

/* ============== CLINDAMICINA ============== */

{id:"med-clindamicina", classe:"Lincosamida", grupo:"atb",
nome:"Clindamicina",
sin:["Cleocin","Dalacin","Sigma Clinda"],
formas:["Cápsula 150 mg, 300 mg","Solução oral 75 mg/5 mL","Frasco-ampola 150 mg/mL (300, 600, 900 mg IV/IM)","Creme vaginal 2%","REMUME — em FARMASUS / componente complementar"],
resumo:"⚠ ESPECTRO: G+ AMPLO (S. aureus incluindo CA-MRSA — variável por região, Strep, S. pneumoniae), ANAERÓBIOS DA BOCA E DA PELE (Bacteroides, Prevotella, Fusobacterium, Peptostreptococcus). NÃO PEGA BEM: anaeróbios INTRA-ABDOMINAIS (Bacteroides fragilis tem resistência crescente — preferir metronidazol), G-, MRSA HOSPITALAR. PEGA BEM EM: pele e partes moles em alérgico β-lactâmico, infecção odontogênica, sinusite resistente, vaginose, malária + clindamicina (uso veterinário).",
dose_rapida:"300 mg VO 6/6h × 7-14d; 600-900 mg IV 8/8h",
doses:[
{ind:"⚠ Celulite / abscesso em alergia a β-lactâmico", dose:"300-450 mg VO 6/6h × 5-7 dias", obs:"Cobertura S. aureus + Strep + alguns CA-MRSA."},
{ind:"⚠ Infecção odontogênica / abscesso dental em alergia à penicilina", dose:"300-450 mg VO 6/6h × 5-7 dias", obs:"⚠ Excelente em anaeróbios orais."},
{ind:"Sinusite refratária em alergia", dose:"300-450 mg 6/6h × 7-10 dias", obs:""},
{ind:"⚠ Síndrome do choque tóxico estreptocócico/estafilocócico (associado à penicilina)", dose:"900 mg IV 8/8h + penicilina G OU vancomicina", obs:"⚠ ADJUNTO — inibe síntese de TOXINAS (efeito 'antitoxina' único)."},
{ind:"⚠ Fasceíte necrotizante (com β-lactâmico amplo)", dose:"600-900 mg IV 8/8h + piperacilina+tazobactam OU carbapenêmico", obs:"⚠ Inibe síntese de toxinas estreptocócicas — adjuvante essencial."},
{ind:"Vaginose bacteriana", dose:"Creme 2% 5 g intravaginal 1×/d × 7 dias OU 300 mg VO 12/12h × 7 dias", obs:""},
{ind:"Acne (oral ou tópica)", dose:"150-300 mg/d (oral); gel 1% 2×/d (tópico)", obs:""},
{ind:"Profilaxia cirúrgica em paciente alérgico a β-lactâmico", dose:"600-900 mg IV 30-60 min pré-cirurgia", obs:""},
{ind:"Profilaxia endocardite em paciente alérgico a amoxicilina — procedimento dental", dose:"600 mg VO 1h antes (adulto)", obs:""},
{ind:"Toxoplasmose cerebral em HIV (alternativa)", dose:"600 mg 6/6h + pirimetamina + ácido folínico", obs:""},
{ind:"Malária P. falciparum complicada (associada à quinino/artesunato)", dose:"10 mg/kg 12/12h × 7 dias", obs:""},
],
ajustes:{
irc:"Sem ajuste (fecal predominante)",
iht:"⚠ Reduzir dose em IH grave",
idoso:"⚠ Maior risco de COLITE POR C. DIFFICILE — usar com cautela",
gestante:"B",
aleita:"⚠ Cautela — pode causar diarreia, candidíase, fezes com sangue no lactente",
ped:"10-30 mg/kg/d ÷ 6/6h",
},
mecanismo:"BACTERIOSTÁTICO. Liga-se ao 50S ribossomal — inibe síntese proteica. ⚠ Inibe síntese de TOXINAS (Strep, Staph) — explica uso em fasceíte/choque tóxico.",
farmacocin:{
absorc:"VO ~90%",
distrib:"Ampla incluindo osso (boa para osteomielite), pus, abscessos — NÃO atravessa BHE",
metab:"Hepático",
elimin:"Hepático/biliar predominante (fecal)",
meiavida:"~2,5h",
ligacao:"~90%",
},
ef_colats:{
comuns:["Diarreia (frequente — até 20%)","Náusea","Rash","Gosto metálico (IV)"],
sérios:["⚠ COLITE POR C. DIFFICILE — RISCO MUITO ALTO (clássica associação histórica)","Stevens-Johnson","Hepatotoxicidade","Síndrome DRESS","Esofagite (se VO sem água)","Anafilaxia"],
},
interacoes:["⚠ Bloqueadores neuromusculares — potencializa (cuidado em anestesia)","Eritromicina: antagonismo (mesmo sítio ribossomal)"],
contraindicacoes:["Alergia a clindamicina/lincomicina","⚠ Histórico de colite associada a ATB"],
monit:["⚠ Diarreia / sintomas Cdiff (interromper imediatamente se >3 evacuações líquidas/dia + febre/cólica)","Função hepática em uso prolongado"],
gravidez:"B",
sus:"⚠ REMUME — em FARMASUS para uso ambulatorial (controlado) + componente complementar.",
referencias:["IDSA Skin and Soft Tissue","Sanford"],
},

/* ============== METRONIDAZOL ============== */

{id:"med-metronidazol", classe:"Nitroimidazólico", grupo:"atb",
nome:"Metronidazol",
sin:["Flagyl","Metrocream","Metrogel"],
formas:["Comprimido 250 mg, 400 mg","Suspensão 200 mg/5 mL","Frasco-ampola 500 mg IV","Gel vaginal 0,75%","Creme vaginal 100 mg/g","Geleia oral / pomada","REMUME — UBS dispensação direta + PFPB"],
resumo:"⚠ ESPECTRO: ANAERÓBIOS (Bacteroides, Clostridium incluindo C. difficile, Prevotella, Peptostreptococcus, Fusobacterium), PROTOZOÁRIOS (Trichomonas, Giardia, Entamoeba histolytica), H. PYLORI (esquema), Gardnerella (vaginose). ⚠ NÃO PEGA: aeróbios. Sempre ASSOCIADO em infecção mista (intra-abdominal, pé diabético) com cobertura aeróbia.",
dose_rapida:"400 mg VO 8/8h × 7d (anaeróbios); 2 g dose única (tricomoníase)",
doses:[
{ind:"⚠ INFECÇÃO INTRA-ABDOMINAL (com cobertura aeróbios)", dose:"500 mg IV 8/8h OU 400 mg VO 8/8h × 7-10 dias + cefalexina/cipro/ceftriaxona", obs:"⚠ Diverticulite, apendicite após drenagem, peritonite secundária."},
{ind:"⚠ TRICOMONÍASE (vaginite)", dose:"2 g VO DOSE ÚNICA (mulher e parceiro)", obs:"⚠ PCDT-MS IST. Tratar SEMPRE parceiro. Alternativa: 500 mg 12/12h × 7d."},
{ind:"⚠ VAGINOSE BACTERIANA", dose:"500 mg VO 12/12h × 7 dias OU gel 0,75% intravaginal 5 g 1×/d × 5 dias", obs:""},
{ind:"⚠ GIARDÍASE", dose:"250-500 mg VO 8/8h × 5-7 dias (adulto); 15 mg/kg/d ÷ 8/8h × 5d (criança)", obs:"OU tinidazol 2 g dose única."},
{ind:"⚠ AMEBÍASE (Entamoeba histolytica)", dose:"500-750 mg VO 8/8h × 7-10 dias (intestinal); + 30-40 dias para amebíase hepática (associar ao paromomicina ou furoato para limpeza luminal)", obs:""},
{ind:"⚠ C. DIFFICILE LEVE-MODERADA (alternativa em recursos limitados)", dose:"500 mg VO 8/8h × 10-14 dias", obs:"⚠ IDSA 2021: vancomicina VO ou fidaxomicina são preferidas. Metro só em casos leves quando vanco indisponível."},
{ind:"⚠ H. PYLORI — esquema quádruplo (em alta resistência claritro)", dose:"500 mg VO 8/8h × 14 dias + bismuto + tetraciclina + IBP", obs:""},
{ind:"⚠ ABSCESSO ODONTOGÊNICO PROFUNDO (com cobertura aeróbia)", dose:"400 mg 8/8h × 7 dias + amoxicilina OU clindamicina", obs:""},
{ind:"DIP (Doença Inflamatória Pélvica)", dose:"500 mg 12/12h × 14 dias + doxiciclina + ceftriaxona", obs:""},
{ind:"⚠ ROSÁCEA gel tópico", dose:"Gel 0,75% 2×/d em pele afetada", obs:""},
{ind:"⚠ PÉ DIABÉTICO INFECTADO (com cobertura aeróbia)", dose:"500 mg 8/8h + cipro/cefalexina/amox-clav × 7-14 dias", obs:""},
],
ajustes:{
irc:"TFG <10: 50% dose. Hemodiálise: pós.",
iht:"⚠ IH grave (Child C): 50% dose",
idoso:"Sem ajuste em função renal/hepática normal",
gestante:"⚠ B — segura no 2º e 3º trimestre. ⚠ 1º trimestre: evitar se possível (controverso — meta-análises não confirmam teratogenicidade, mas reservar)",
aleita:"⚠ Em dose única (tricomoníase): pausar amamentação 12-24h pós-dose. Em uso prolongado: cuidado, sabor amargo no leite, evitar se possível.",
ped:"15-50 mg/kg/d ÷ 8/8h",
},
mecanismo:"PRO-DROGA — ativada em ANAERÓBIOS por redução do grupo nitro → metabólitos tóxicos rompem DNA bacteriano/parasitário. BACTERICIDA.",
farmacocin:{
absorc:"VO ~100% (excelente)",
distrib:"AMPLA incluindo SNC, abscessos, ossos, próstata",
metab:"Hepático (CYP450 — inibidor moderado)",
elimin:"Renal predominante",
meiavida:"~8h",
ligacao:"<20%",
},
ef_colats:{
comuns:["⚠ Gosto metálico (típico — frequente)","Náusea/vômito","Diarreia","Cefaleia","Urina escura (reversível, sem significado clínico)","Glossite, estomatite"],
sérios:["⚠ EFEITO DISULFIRAM-LIKE com álcool (náusea, rubor, taquicardia, hipotensão) — ABSTÊNCIA durante e 48h após uso","⚠ NEUROPATIA periférica (uso prolongado >2-4 semanas — geralmente reversível)","⚠ Encefalopatia / convulsão (raro, uso prolongado)","Pancreatite","Stevens-Johnson","Neutropenia"],
},
interacoes:["⚠ ÁLCOOL — reação disulfiram-like","⚠ Warfarina: ↑ INR significativo","Lítio: ↑ toxicidade","Fenitoína: ↑ nível","Disulfiram: psicose","Tacrolimo, ciclosporina: ↑ nível"],
contraindicacoes:["Alergia a nitroimidazólicos","⚠ Gestação 1º trimestre (relativa)","⚠ Uso concomitante com álcool"],
monit:["⚠ Sintomas neurológicos em uso >2 semanas","INR se varfarina","Hemograma em uso prolongado"],
gravidez:"B",
sus:"⚠ REMUME — UBS dispensação direta + PFPB.",
referencias:["⚠ PCDT-MS IST 2024","IDSA Intra-abdominal","Sanford"],
},

/* ============== GENTAMICINA ============== */

{id:"med-gentamicina", classe:"Aminoglicosídeo", grupo:"atb",
nome:"Gentamicina",
sin:["Garamicin","Septopal","Cidomycin"],
formas:["Frasco-ampola 40 mg/mL — 1 mL (40 mg), 2 mL (80 mg) IV/IM","Colírio 3 mg/mL (0,3%)","Pomada/creme 0,1%","REMUME — UBS uso INTERNO (não dispensa para casa)"],
resumo:"⚠ ESPECTRO: G- (E. coli, Klebsiella, Proteus, Enterobacter, Pseudomonas — alguns), SINÉRGICO com β-lactâmicos contra Strep / Enterococo / S. aureus (em endocardite). ⚠ NÃO ATIVO em anaeróbios (precisa O2 para entrar na bactéria). PEGA BEM EM: ITU complicada (uso interno), sepse de foco urinário (com β-lactâmico), endocardite (sinergismo), profilaxia pré-cirúrgica em alérgico β-lac. NÃO PEGA: anaeróbios, Strep monoterapia, ambulatório (sempre tópico/IV).",
dose_rapida:"⚠ DOSE ÚNICA DIÁRIA: 5-7 mg/kg IV 1×/d (preferido — menos toxicidade); ESQUEMA MÚLTIPLO: 1-1,7 mg/kg 8/8h",
doses:[
{ind:"⚠ Sepse de foco urinário (com β-lactâmico)", dose:"5-7 mg/kg IV 1×/d × 5-7 dias", obs:""},
{ind:"Pielonefrite hospitalar grave / urosepse", dose:"5-7 mg/kg/d + ceftriaxona OU piperacilina+tazobactam", obs:""},
{ind:"⚠ ENDOCARDITE — sinergismo", dose:"1 mg/kg 8/8h em endocardite por Enterococo (com ampicilina); pode usar dose 3 mg/kg/d se MSSA (com oxa/cefazolina)", obs:"⚠ Dose REDUZIDA em endocardite por sinergismo — não monoterapia."},
{ind:"Profilaxia em alergia β-lactâmico (cirurgia colorretal)", dose:"1,5 mg/kg + metronidazol pré-cirurgia", obs:""},
{ind:"Otite externa / conjuntivite bacteriana — tópico", dose:"Colírio: 1-2 gotas 4-6×/d × 5-7 dias", obs:""},
{ind:"Tularemia, peste, brucelose (em combinação)", dose:"5 mg/kg/d × 7-14 dias", obs:""},
],
ajustes:{
irc:"⚠ AJUSTE OBRIGATÓRIO — dose única diária estendida (intervalo 24-72h conforme TFG)",
iht:"Sem ajuste",
idoso:"⚠ MAIOR RISCO NEFRO + OTOTÓXICO — preferir dose única + monitor",
gestante:"⚠ D — TERATOGÊNICA (ototoxicidade fetal). Usar apenas em risco de vida + sem alternativa.",
aleita:"Compatível (mal absorvida VO)",
ped:"5-7 mg/kg/d (DUD) OU 2,5 mg/kg 8/8h",
},
mecanismo:"BACTERICIDA. Liga-se 30S ribossomal — inibe síntese proteica + leitura errada do mRNA. Sinergismo com β-lactâmico (β-lac abre parede → gentamicina entra).",
farmacocin:{
absorc:"⚠ NÃO absorvida VO (apenas IV/IM/tópica)",
distrib:"Ampla — POBRE em SNC, próstata, secreções respiratórias",
metab:"Mínimo",
elimin:"Renal (>90% inalterada)",
meiavida:"~2-3h (normal); 24-60h em IRC",
ligacao:"<10%",
},
ef_colats:{
comuns:["Náusea, vômito","Dor IM","Tromboflebite IV"],
sérios:["⚠ NEFROTOXICIDADE — NTA, geralmente reversível com retirada","⚠ OTOTOXICIDADE — cocleovestibular IRREVERSÍVEL (especialmente vestibular — desequilíbrio crônico). Cumulativa com furosemida.","Bloqueio neuromuscular (em miastenia, doses altas)","Hipomagnesemia, hipocalcemia"],
},
interacoes:["⚠ Diuréticos de alça (furosemida): nefro + ototoxicidade somativa","⚠ Vancomicina: nefrotoxicidade","⚠ Contrastes iodados, AINEs, IECA: nefrotoxicidade","Bloqueadores neuromusculares: potencializa","Cisplatina: nefro + ototóxico"],
contraindicacoes:["⚠ Gestação","Alergia","Miastenia gravis","⚠ Histórico ototoxicidade por aminoglicosídeo"],
monit:["⚠ Função renal a cada 2-3 dias","⚠ Pico/vale séricos (se uso >3-5 dias)","Sintomas auditivos/vestibulares","Magnésio, cálcio"],
gravidez:"D",
sus:"REMUME — UBS USO INTERNO (não para casa). Hospitais.",
referencias:["IDSA","Sanford"],
},

/* ============== NITROFURANTOÍNA ============== */

{id:"med-nitrofurantoina", classe:"Nitrofurano — antimicrobiano urinário", grupo:"atb",
nome:"Nitrofurantoína",
sin:["Macrodantina","Macrobid","Furadantina"],
formas:["Cápsula 100 mg (Macrodantina — microcristais)","Cápsula 100 mg liberação prolongada (Macrobid)","REMUME — UBS dispensação direta + PFPB"],
resumo:"⚠ ESPECTRO ESTREITO — concentra-se apenas em URINA (sem ação sistêmica). G+ (E. faecalis, S. saprophyticus) + G- (E. coli, Klebsiella, Enterobacter). ⚠ NÃO PEGA: Proteus, Pseudomonas, Serratia (resistência intrínseca). PEGA BEM EM: CISTITE NÃO COMPLICADA (1ª LINHA atual em região com resistência à SMX-TMP). NÃO USAR EM: pielonefrite (concentração tecidual insuficiente), prostatite, sepse, gestação >36 sem, criança <1m.",
dose_rapida:"100 mg VO 6/6h × 5d (Macrodantina); 100 mg 12/12h × 5d (Macrobid liberação prolongada)",
doses:[
{ind:"⚠ CISTITE NÃO COMPLICADA mulher", dose:"100 mg VO 6/6h × 5 dias (Macrodantina) OU 100 mg 12/12h × 5d (Macrobid)", obs:"⚠ 1ª LINHA (IDSA, USPSTF). Curso de 5 dias > 3 dias (taxa de cura). Não usar em pielonefrite."},
{ind:"⚠ Profilaxia de ITU recorrente em mulher", dose:"50-100 mg VO 1×/d ad lib OU pós-coital", obs:"Em ITU recorrente apesar de medidas comportamentais. Reavaliar a cada 3-6 meses."},
{ind:"Bacteriúria assintomática NA GESTAÇÃO", dose:"100 mg 6/6h × 5-7 dias", obs:"⚠ Tratar bacteriúria na gestação (única indicação rotineira de tratar bacteriúria assintomática). ⚠ NÃO USAR no 3º trimestre (>36 sem) — hemólise neonatal."},
],
ajustes:{
irc:"⚠ TFG <60: EVITAR (acúmulo + ineficaz — não atinge urina). Em TFG 30-60 controverso (alguns aceitam em cistite simples se função estável).",
iht:"Cautela em IH",
idoso:"⚠ EVITAR em TFG reduzida (frequente). ⚠ Pneumopatia crônica: risco fibrose pulmonar com uso prolongado",
gestante:"⚠ B 1º-2º trimestre. ⚠ EVITAR >36 SEMANAS — hemólise neonatal (G6PD imatura).",
aleita:"⚠ Evitar <1 mês de vida do lactente (G6PD imatura)",
ped:"⚠ EVITAR <1 MÊS. ≥1m: 5-7 mg/kg/d ÷ 6/6h",
},
mecanismo:"PRO-DROGA — reduzida em bactérias por nitrorredutases → metabólitos reativos que danificam ribossomos e DNA bacteriano. BACTERIOSTÁTICO (bactericida em dose alta).",
farmacocin:{
absorc:"⚠ VO bem absorvida MAS ⚠ rapidamente eliminada — atinge concentração apenas em URINA (não atinge tecidos)",
distrib:"⚠ APENAS URINA",
metab:"Hepático parcial",
elimin:"Renal (40% inalterada)",
meiavida:"~30-60 min",
ligacao:"~40%",
},
ef_colats:{
comuns:["Náusea/vômito (frequente — tomar COM ALIMENTO)","Diarreia","Cefaleia","Urina escura/amarelada (sem significado clínico)"],
sérios:["⚠ FIBROSE PULMONAR (uso prolongado — meses; idoso). REVERSÍVEL se precoce.","⚠ Pneumonite aguda — hipersensibilidade (em uso curto, geralmente reversível)","⚠ Anemia hemolítica em deficiência G6PD","Neuropatia periférica (uso prolongado, IRC)","Hepatotoxicidade","Stevens-Johnson"],
},
interacoes:["Antiácidos com magnésio: ↓ absorção","Ácido nalidíxico: antagonismo","Probenecida: ↑ nível"],
contraindicacoes:["⚠ TFG <60","⚠ Gestação >36 sem","⚠ Lactente <1m","Deficiência G6PD (relativa)","Anúria, oligúria"],
monit:["⚠ Função pulmonar em uso prolongado","Função hepática","Hemograma"],
gravidez:"B (D após 36 sem)",
sus:"REMUME — UBS dispensação direta + PFPB.",
referencias:["IDSA Uncomplicated UTI 2010","USPSTF","Sanford"],
},

/* ============== FOSFOMICINA ============== */

{id:"med-fosfomicina", classe:"Fosfonato — antimicrobiano urinário", grupo:"atb",
nome:"Fosfomicina (trometamol)",
sin:["Monuril","Fosfocin"],
formas:["Sachê 3 g (granulado para diluição em água)","⚠ Não REMUME nacional — PFPB em algumas SES; particular acessível"],
resumo:"⚠ ESPECTRO: G+ (Enterococcus incluindo VRE — única opção VO!, S. saprophyticus) + G- (E. coli incluindo ESBL — vantagem!, Klebsiella, Citrobacter, alguns Pseudomonas, Proteus). PEGA BEM EM: CISTITE NÃO COMPLICADA (dose única — atrativa adesão), ITU por ESBL ambulatorial, profilaxia em algumas situações urológicas. ⚠ NÃO PEGA: tecidos fora do trato urinário, anaeróbios.",
dose_rapida:"3 g VO DOSE ÚNICA (cistite)",
doses:[
{ind:"⚠ CISTITE NÃO COMPLICADA mulher — DOSE ÚNICA", dose:"3 g VO DOSE ÚNICA, diluída em água, à NOITE com bexiga vazia", obs:"⚠ Vantagem: ADESÃO 100% (dose única). 1ª linha IDSA junto com nitrofurantoína. Eficácia ligeiramente inferior em mulheres com fatores de risco (≥65a, recorrência) — preferir nitrofurantoína 5d nesses casos."},
{ind:"⚠ ITU por E. coli ESBL ambulatorial", dose:"3 g VO cada 48-72h × 2-3 doses", obs:"⚠ Vantagem ÚNICA — única opção VO eficaz em ESBL em cistite. Infectologia."},
{ind:"Bacteriúria assintomática na gestação", dose:"3 g VO dose única", obs:"Alternativa em gestante."},
{ind:"Profilaxia pré-cistoscopia / biopsia prostática", dose:"3 g VO dose única na noite anterior + 3 g 24h após", obs:""},
],
ajustes:{
irc:"TFG <10: cautela (acumulação — geralmente bem tolerada em dose única)",
iht:"Sem ajuste",
idoso:"Sem ajuste em função renal estável",
gestante:"B",
aleita:"Cautela (poucos dados)",
ped:"≥12a: dose adulto. <12a: dados limitados.",
},
mecanismo:"BACTERICIDA — inibe enzima MurA (UDP-N-acetilglicosamina enolpiruvil transferase) — primeira etapa da síntese de peptidoglicano. Mecanismo único — sem resistência cruzada com outras classes.",
farmacocin:{
absorc:"VO ~30-40% (em jejum maior)",
distrib:"⚠ APENAS URINA em concentrações terapêuticas",
metab:"Não metabolizada",
elimin:"Renal (90% inalterada)",
meiavida:"~5-7h (urina concentrada por 24-48h)",
ligacao:"<10%",
},
ef_colats:{
comuns:["Diarreia","Náusea","Cefaleia","Vaginite"],
sérios:["Anafilaxia (rara)","Colite C. difficile (rara)"],
},
interacoes:["Metoclopramida: ↓ absorção","Antiácidos: pode ↓ absorção"],
contraindicacoes:["Alergia","TFG <10 (cautela)"],
monit:["Sintomas urinários (resolução em 3-5 dias)"],
gravidez:"B",
sus:"⚠ Não REMUME nacional. PFPB em algumas SES.",
referencias:["IDSA UTI","Sanford"],
},

);
