/* ===========================================================
   VOVÔMINIC EMERGÊNCIA — BIBLIOTECA DE MEDICAÇÕES (PARTE 15)
   Bloco E Rodada 3 — Macrolídeos + Fluoroquinolonas
   =========================================================== */

MEDICACOES.push(

/* ============== AZITROMICINA ============== */

{id:"med-azitromicina", classe:"Macrolídeo (15 membros — azalida)", grupo:"atb",
nome:"Azitromicina",
sin:["Zitromax","Azi","Astro","Zithromax"],
formas:["Comprimido 500 mg","Suspensão oral 200 mg/5 mL e 600 mg/15 mL (frasco unitário)","Frasco-ampola 500 mg IV","REMUME — UBS dispensação direta + PFPB"],
resumo:"⚠ ESPECTRO: G+ (Strep — pneumococo limitado por resistência crescente), ATÍPICOS (Mycoplasma, Chlamydia, Legionella, Ureaplasma), G- limitados (H. influenzae, Moraxella, Bordetella, Campylobacter, Helicobacter), micobactérias atípicas (MAC). PEGA BEM EM: PAC atípica (1ª escolha de cobertura atípica), DST por Chlamydia (DOSE ÚNICA), coqueluche, otite/sinusite em alérgico a β-lactâmico, diarreia bacteriana (Campylobacter, Salmonella). NÃO PEGA: anaeróbios, Pseudomonas, MRSA (variável), Enterococcus, Mycoplasma macrolídeo-resistente.",
dose_rapida:"500 mg VO 1×/d × 3-5 dias (esquema simples); 1 g VO dose única (DST)",
doses:[
{ind:"⚠ PAC ambulatorial — cobertura ATÍPICOS", dose:"500 mg VO 1×/d × 3-5 dias", obs:"⚠ Em ASSOCIAÇÃO com amoxicilina ou amox+clav em PAC com cobertura completa. Monoterapia só em paciente jovem, atípica clara, sem comorbidade."},
{ind:"PAC hospitalar moderada-grave (cobertura atípicos)", dose:"500 mg IV/VO 1×/d × 5-7 dias + β-lactâmico (ceftriaxona)", obs:""},
{ind:"⚠ CHLAMYDIA / NGU — DOSE ÚNICA", dose:"1 g VO DOSE ÚNICA", obs:"⚠ PCDT-MS IST 2024 — atualizado preferência para doxiciclina 100 mg 12/12h × 7d se possível adesão (eficácia superior). Azitromicina mantida em adesão duvidosa, gestante, alergia."},
{ind:"⚠ GONORREIA — em ASSOCIAÇÃO com ceftriaxona", dose:"1 g VO dose única + ceftriaxona 500 mg IM dose única", obs:"⚠ PCDT-MS — atualmente CDC já discute monoterapia ceftriaxona, mas Brasil mantém esquema dual."},
{ind:"Sinusite aguda bacteriana / otite em alergia a β-lactâmico", dose:"500 mg dia 1, depois 250 mg/d × 4 dias (total 5d) OU 500 mg/d × 3d", obs:"⚠ Não é 1ª linha em alérgico — preferir cefalosporina se alergia leve, ou clinda/doxi se alergia grave a β-lactâmico."},
{ind:"Faringite estreptocócica em alergia à penicilina", dose:"500 mg dia 1, depois 250 mg/d × 4 dias", obs:"⚠ Resistência crescente — cefalexina é melhor escolha em alergia leve."},
{ind:"⚠ COQUELUCHE", dose:"500 mg dia 1, depois 250 mg/d × 4 dias (adulto)", obs:"⚠ Criança: 10 mg/kg dia 1, depois 5 mg/kg/d × 4d. <1 mês: associada a estenose pilórica."},
{ind:"Diarreia bacteriana grave (Shigella, Salmonella não-typhi, Campylobacter)", dose:"500 mg/d × 3 dias", obs:"Em diarreia com SANGUE, febre alta, imunossuprimido. Não rotineira em diarreia simples."},
{ind:"⚠ EXACERBAÇÃO DE DPOC", dose:"500 mg dia 1, depois 250 mg/d × 4 dias", obs:"Quando há purulência."},
{ind:"⚠ Profilaxia em DPOC exacerbador recorrente", dose:"250 mg 3×/sem (segunda/quarta/sexta) em paciente com exacerbações frequentes apesar de tratamento otimizado", obs:"⚠ GOLD 2025. Pneumologia. ⚠ Avaliar QT, ototoxicidade, resistência."},
{ind:"Bartonella (gato), micobacterias atípicas (MAC) em HIV", dose:"500 mg/d (Bartonella); 600 mg/sem (MAC profilaxia)", obs:"Infectologia."},
],
ajustes:{
irc:"Sem ajuste (mínima excreção renal)",
iht:"⚠ Cautela em IH grave",
idoso:"⚠ Monitorar QT longo. Cuidado em cardiopata + diurético.",
gestante:"⚠ B — preferida na gestação para cobertura atípica e DST.",
aleita:"Compatível",
ped:"10 mg/kg dia 1, depois 5 mg/kg/d × 4 dias (PAC, otite). ⚠ <1 mês: associada a ESTENOSE PILÓRICA HIPERTRÓFICA — evitar.",
},
mecanismo:"⚠ BACTERIOSTÁTICO (bactericida em altas concentrações). Liga-se à subunidade RIBOSSÔMICA 50S — inibe síntese proteica. Concentra-se INTRACELULARMENTE (>fagocitário) — explica eficácia em atípicos e meia-vida tecidual longa (3-5 dias após dose).",
farmacocin:{
absorc:"VO ~37% — refeição reduz absorção dos comprimidos (tomar 1h antes ou 2h após). Suspensão pode ser com alimento.",
distrib:"AMPLA — concentração tecidual >> plasma (até 100×). Não atravessa BHE.",
metab:"Hepático mínimo",
elimin:"Biliar predominante",
meiavida:"⚠ 68h (vida média tecidual 3-5 dias após última dose — explica esquemas curtos)",
ligacao:"~50% (variável com concentração)",
},
ef_colats:{
comuns:["Diarreia (5-15%)","Náusea/vômito","Dor abdominal","Gosto metálico"],
sérios:["⚠ PROLONGAMENTO DE QT — torsades de pointes (RARO mas possível, especialmente associado a outros QT-prolongadores)","Hepatotoxicidade","Colite C. difficile","⚠ ESTENOSE PILÓRICA HIPERTRÓFICA em <1 mês (BB) — evitar","Ototoxicidade reversível em dose alta prolongada"],
},
interacoes:["⚠ QT-PROLONGADORES (haloperidol, ondansetrona, citalopram, antiarrítmicos): risco torsades","⚠ Anticoagulantes orais (varfarina): ↑ INR","Digoxina: ↑ nível","Estatinas: cuidado (rabdomiólise rara)","Ergot derivados: vasoespasmo grave"],
contraindicacoes:["Alergia a macrolídeos","⚠ Histórico de QT longo / arritmia ventricular","⚠ Hepatopatia colestática prévia por macrolídeo","Miastenia gravis (relativa)"],
monit:["ECG / QT em risco","Função hepática em uso prolongado","Sinais auditivos em uso crônico"],
gravidez:"B",
sus:"⚠ REMUME — UBS dispensação direta + PFPB.",
referencias:["⚠ PCDT-MS IST 2024","IDSA PAC","Sanford"],
},

/* ============== CLARITROMICINA ============== */

{id:"med-claritromicina", classe:"Macrolídeo (14 membros)", grupo:"atb",
nome:"Claritromicina",
sin:["Klaricid","Klacid","Bicrolid"],
formas:["Comprimido 250 mg, 500 mg","Suspensão 125 mg/5 mL, 250 mg/5 mL","XR comprimido 500 mg","⚠ Não REMUME nacional — em PFPB algumas SES"],
resumo:"⚠ ESPECTRO: similar à azitromicina (G+, atípicos, alguns G-) — DIFERENCIAL: melhor cobertura H. pylori (USO CENTRAL EM ERRADICAÇÃO). PEGA BEM EM: H. pylori (esquema tríplice), PAC atípica, MAC. NÃO PEGA: anaeróbios, Pseudomonas, MRSA.",
dose_rapida:"500 mg VO 12/12h × 7-14d",
doses:[
{ind:"⚠ H. PYLORI — esquema tríplice", dose:"500 mg VO 12/12h × 14 dias + amoxicilina 1 g 12/12h + omeprazol 20 mg 12/12h", obs:"⚠ Cura ~70-80% (resistência crescente). Em região de alta resistência: esquema quádruplo (omep + bismuto + tetraciclina + metro)."},
{ind:"PAC atípica (alternativa à azitromicina)", dose:"500 mg 12/12h × 7-14 dias", obs:""},
{ind:"Sinusite / otite / faringite em alérgico a β-lactâmico", dose:"250-500 mg 12/12h × 5-10 dias", obs:""},
{ind:"MAC (Mycobacterium avium complex) — HIV", dose:"500 mg 12/12h + etambutol + rifabutina × ≥12 meses", obs:"Infectologia."},
],
ajustes:{
irc:"TFG <30: 50% dose, intervalo dobrado",
iht:"Cautela",
idoso:"⚠ Monitor QT longo",
gestante:"⚠ C — preferir azitromicina (B)",
aleita:"Compatível",
ped:"15 mg/kg/d ÷ 12/12h",
},
mecanismo:"BACTERIOSTÁTICO. Liga-se ao 50S — inibe síntese proteica.",
farmacocin:{
absorc:"VO ~50%",
distrib:"Ampla (tecido > plasma)",
metab:"⚠ Hepático CYP3A4 (FORTE INIBIDOR — múltiplas interações)",
elimin:"Renal (40%) + biliar (60%)",
meiavida:"~3-7h",
ligacao:"~70%",
},
ef_colats:{
comuns:["Diarreia","Gosto metálico/amargo (típico)","Náusea","Dor abdominal"],
sérios:["⚠ QT LONGO — torsades","Hepatotoxicidade","Colite C. difficile","Síndrome de Stevens-Johnson","⚠ Aumenta risco CV (estudos observacionais)"],
},
interacoes:["⚠ INIBIDOR FORTE CYP3A4 — múltiplas: estatinas (rabdomiólise — proibir simvastatina, lovastatina; cautela com atorvastatina), benzodiazepínicos (midazolam, triazolam — proibir), warfarina, digoxina, colchicina (mortalidade — em IRC), ergot, antiarrítmicos, antifúngicos, IECA","QT-prolongadores"],
contraindicacoes:["Alergia a macrolídeos","QT longo","Uso concomitante com simvastatina/lovastatina","Uso com ergot, pimozida, cisapride, colchicina (em IRC)","⚠ Gestação 1º trimestre (preferir azitro)"],
monit:["ECG","Função hepática","Interações"],
gravidez:"C",
sus:"PFPB em algumas SES (Saúde Mental — controlados)",
referencias:["⚠ IV Consenso H. pylori","Sanford","IDSA"],
},

/* ============== CIPROFLOXACINO ============== */

{id:"med-ciprofloxacino", classe:"Fluoroquinolona — 2ª geração", grupo:"atb",
nome:"Ciprofloxacino",
sin:["Cipro","Ciproflox","Ciprobay"],
formas:["Comprimido 250 mg, 500 mg","Suspensão 250 mg/5 mL (raramente)","Frasco-ampola 200 mg, 400 mg IV","Colírio 0,3%","Otológico 0,3%","REMUME — UBS dispensação direta + PFPB; colírio em algumas SES"],
resumo:"⚠ ESPECTRO: G- AMPLO (E. coli, Klebsiella, Proteus, Enterobacter, Salmonella, Shigella, Campylobacter, ⚠ PSEUDOMONAS), G+ LIMITADOS (cobertura medíocre de S. aureus, pneumococo — NÃO usar em pele/PAC), atípicos parciais (Legionella OK, Mycoplasma/Chlamydia subótimo), N. gonorrhoeae (mas resistência alta — abandonado), micobacterias atípicas. PEGA BEM EM: ITU complicada, prostatite, gastroenterite bacteriana, infecção intra-abdominal (com metro), otite externa maligna. NÃO PEGA: anaeróbios, Strep/pneumococo (insuficiente), MRSA, sífilis. ⚠ ABANDONADA na gonorreia.",
dose_rapida:"500 mg VO 12/12h × 7-14d; 400 mg IV 12/12h",
doses:[
{ind:"⚠ ITU COMPLICADA / PIELONEFRITE ambulatorial", dose:"500 mg VO 12/12h × 7-10 dias (cistite complicada); 7-14d (pielonefrite ambulatorial)", obs:"⚠ 1ª linha em pielonefrite ambulatorial em adulto SEM gestação e SEM alergia. Cistite NÃO complicada: PREFERIR nitrofurantoína, fosfomicina, SMX-TMP (P4 — reduzir uso de quinolona)."},
{ind:"Prostatite aguda bacteriana", dose:"500 mg VO 12/12h × 4-6 semanas", obs:"Excelente penetração prostática. Crônica: 4-12 sem."},
{ind:"Diarreia do viajante moderada-grave / disenteria", dose:"500 mg 12/12h × 1-3 dias", obs:"Empírica em diarreia com sangue, febre alta, imunossuprimido. Maioria das diarreias virais não precisa ATB."},
{ind:"Febre tifoide", dose:"500 mg 12/12h × 7-10 dias", obs:"⚠ Resistência crescente em algumas regiões — preferir ceftriaxona ou azitromicina conforme padrão local."},
{ind:"Infecção intra-abdominal ambulatorial", dose:"500 mg 12/12h + METRONIDAZOL 500 mg 8/8h × 7-10 dias", obs:"⚠ Sempre associar metronidazol para cobertura anaeróbios."},
{ind:"Otite externa maligna (Pseudomonas)", dose:"750 mg 12/12h × 4-6 semanas", obs:"⚠ Diabético, imunossuprimido."},
{ind:"Profilaxia em meningococcemia (contactantes)", dose:"500 mg VO dose única", obs:"Alternativa à rifampicina/ceftriaxona."},
{ind:"⚠ Antrax pós-exposição (bioterrorismo)", dose:"500 mg 12/12h × 60 dias", obs:"Profilaxia."},
{ind:"Otite externa simples — gotas", dose:"3-4 gotas 12/12h × 7-10 dias", obs:"Cobertura Pseudomonas. ⚠ Em otite média + perfuração: usar PRECAUÇÕES (raramente ototóxica se ouvido médio acessível)."},
],
ajustes:{
irc:"TFG 30-50: 250-500 mg 12/12h. TFG <30: 250-500 mg 24/24h. HD: pós.",
iht:"Sem ajuste",
idoso:"⚠ Maior risco TENDINITE / RUPTURA TENDÍNEA + QT longo + delirium",
gestante:"⚠ C — EVITAR (efeitos em cartilagem em modelos animais; usar se único disponível)",
aleita:"⚠ Compatível mas preferir alternativa quando possível",
ped:"⚠ EVITAR — risco artropatia em modelos animais. Usar apenas em infecção grave SEM alternativa (Pseudomonas em fibrose cística, antrax).",
},
mecanismo:"BACTERICIDA — inibe DNA girase (topoisomerase II) e topoisomerase IV → bloqueia replicação do DNA bacteriano.",
farmacocin:{
absorc:"⚠ VO ~70% — ⚠ QUELAÇÃO por cálcio, magnésio, alumínio, ferro, zinco (antiácidos, multivitamínicos, laticínios): ↓ absorção 50%+. Tomar 2h antes ou 6h depois de cátions di/trivalentes.",
distrib:"Ampla — boa penetração próstata, ossos, pulmão. SNC limitado.",
metab:"Hepático parcial (CYP1A2 — inibidor moderado)",
elimin:"Renal (50-70%)",
meiavida:"~4-6h",
ligacao:"~20-40%",
},
ef_colats:{
comuns:["Náusea/diarreia","Cefaleia","Tontura","Insônia","Fotossensibilidade"],
sérios:["⚠ TENDINITE / RUPTURA TENDÃO DE AQUILES (↑ risco idoso + corticoide + transplantado renal) — EVITAR exercício extremo","⚠ QT LONGO — torsades","⚠ DISGLICEMIA (hipo ou hiperglicemia, especialmente em DM com hipoglicemiantes)","⚠ NEUROTOXICIDADE — convulsão, confusão, alucinação, delirium (especialmente idoso, IRC)","⚠ ANEURISMA / DISSECÇÃO AÓRTICA — risco aumentado (FDA warning 2018)","Colite C. difficile","Stevens-Johnson","Anafilaxia","Cristalúria (em alta dose / baixa hidratação)","Toxicidade hepática"],
},
interacoes:["⚠ CÁTIONS di/trivalentes — quelação","⚠ Teofilina, cafeína: ↑ nível (inibe CYP1A2)","Warfarina: ↑ INR","AINEs: ↑ risco convulsão","QT-prolongadores","Hipoglicemiantes orais: disglicemia"],
contraindicacoes:["⚠ Gestação / lactação (relativa)","⚠ Criança <18a (relativa)","Miastenia gravis","QT longo","Histórico tendinite por quinolona"],
monit:["⚠ Sintomas tendíneos","Glicemia em DM","ECG em risco","Sintomas neurológicos","Função renal/hepática"],
gravidez:"C",
sus:"REMUME — UBS dispensação direta + PFPB.",
referencias:["⚠ FDA Warning Tendinopatia e Aneurisma","Sanford","IDSA"],
},

/* ============== LEVOFLOXACINO ============== */

{id:"med-levofloxacino", classe:"Fluoroquinolona — 3ª geração ('respiratória')", grupo:"atb",
nome:"Levofloxacino",
sin:["Tavanic","Levaquin","Levoxin"],
formas:["Comprimido 250 mg, 500 mg, 750 mg","Solução oral 25 mg/mL","Frasco-ampola 500 mg IV","REMUME — em FARMASUS / algumas SES + PFPB"],
resumo:"⚠ ESPECTRO: AMPLIA cipro para G+ — boa cobertura DE PNEUMOCOCO + atípicos (Mycoplasma, Chlamydia, Legionella — excelente). MANTÉM cobertura G- + Pseudomonas (mais fraca que cipro). PEGA BEM EM: PAC moderada-grave (1ª escolha em alergia a β-lactâmico ou em paciente com risco resistente), DPOC exacerbação, sinusite resistente, pielonefrite. NÃO PEGA: anaeróbios, MRSA, sífilis. ⚠ É a 'quinolona respiratória' clássica.",
dose_rapida:"500-750 mg VO/IV 1×/dia × 5-7d (PAC); 750 mg/d em casos graves",
doses:[
{ind:"PAC moderada-grave hospitalar (monoterapia)", dose:"750 mg VO/IV 1×/d × 5 dias (curso curto eficaz) OU 500 mg × 7-10 dias", obs:"⚠ Alternativa à dual ceftriaxona+azitromicina. Excelente em alérgicos a β-lactâmico."},
{ind:"PAC ambulatorial em paciente com comorbidade / risco resistência", dose:"750 mg/d × 5 dias OU 500 mg/d × 7 dias", obs:""},
{ind:"DPOC exacerbação", dose:"500-750 mg/d × 5-7 dias", obs:"Quando há purulência e fatores de risco para Pseudomonas (uso prévio de ATB, exacerbações frequentes)."},
{ind:"Sinusite resistente / refratária", dose:"500 mg/d × 5-7 dias", obs:""},
{ind:"⚠ PIELONEFRITE / ITU complicada", dose:"500-750 mg/d × 7-10 dias", obs:""},
{ind:"⚠ TB MDR / XDR — 2ª linha", dose:"500-1000 mg/d em esquemas combinados", obs:"⚠ Infectologia / referência terciária."},
{ind:"Profilaxia / tratamento de antrax pós-exposição", dose:"500 mg/d × 60 dias", obs:""},
{ind:"Prostatite", dose:"500 mg/d × 4-6 sem (aguda) ou 6-12 sem (crônica)", obs:""},
],
ajustes:{
irc:"TFG 20-49: 750 mg dose 1, depois 750 mg/48h OU 500 mg/d. TFG <20: 750 mg, depois 500 mg/48h. HD: idem.",
iht:"Sem ajuste",
idoso:"⚠ Maior risco tendinite + QT + delirium. Considerar redução dose se TFG diminuída.",
gestante:"⚠ C — EVITAR",
aleita:"Cautela",
ped:"⚠ EVITAR — exceto antrax / Pseudomonas em fibrose cística",
},
mecanismo:"BACTERICIDA — inibe DNA girase + topoisomerase IV. Maior atividade contra G+ por melhor inibição de topoisomerase IV (alvo principal em G+).",
farmacocin:{
absorc:"⚠ VO 99% (excelente — bioequivalência VO=IV). Quelação por cátions.",
distrib:"Ampla — boa penetração tecido pulmonar (>plasma), próstata, ossos",
metab:"Mínimo",
elimin:"Renal (87% inalterada)",
meiavida:"~6-8h (1×/d)",
ligacao:"~24-38%",
},
ef_colats:{
comuns:["Náusea","Cefaleia","Tontura","Insônia","Fotossensibilidade"],
sérios:["⚠ TENDINITE / RUPTURA AQUILES — risco similar ao cipro","⚠ QT LONGO","⚠ DISGLICEMIA — mais comum que cipro","⚠ NEUROTOXICIDADE — convulsão, confusão, alucinação","⚠ ANEURISMA / DISSECÇÃO AÓRTICA","Stevens-Johnson","Anafilaxia","Hepatotoxicidade"],
},
interacoes:["Cátions di/trivalentes — quelação","Warfarina","AINEs: ↑ convulsão","QT-prolongadores","Hipoglicemiantes: disglicemia"],
contraindicacoes:["⚠ Gestação / lactação","⚠ Criança","Miastenia gravis","QT longo","Tendinite prévia por quinolona"],
monit:["Sintomas tendíneos","Glicemia em DM","ECG em risco","Sintomas neurológicos"],
gravidez:"C",
sus:"REMUME em algumas SES (Saúde Mental — controlados) + PFPB",
referencias:["FDA Warning","IDSA PAC","Sanford"],
},

/* ============== NORFLOXACINO ============== */

{id:"med-norfloxacino", classe:"Fluoroquinolona — 2ª geração (uso restrito)", grupo:"atb",
nome:"Norfloxacino",
sin:["Floxacin","Noroxin","Uritrim"],
formas:["Comprimido 400 mg","REMUME (em algumas SES) + PFPB","⚠ Uso restrito — não tem boa concentração sistêmica fora do trato urinário"],
resumo:"⚠ ESPECTRO: G- ambulatoriais (E. coli, Klebsiella, Proteus, alguns Pseudomonas). NÃO ATINGE concentração tecidual significativa fora de URINA + INTESTINO — uso restrito. PEGA BEM EM: cistite não complicada (alternativa), profilaxia de PBE em cirrose, diarreia infecciosa. NÃO PEGA: tudo o resto sistêmico, MRSA, anaeróbios.",
dose_rapida:"400 mg VO 12/12h × 3-7d (cistite); 400 mg/d (profilaxia PBE)",
doses:[
{ind:"Cistite não complicada (alternativa)", dose:"400 mg 12/12h × 3 dias", obs:"⚠ NÃO 1ª linha — preferir nitrofurantoína, fosfomicina, SMX-TMP. Norflo é alternativa quando outros indisponíveis."},
{ind:"⚠ Profilaxia secundária de Peritonite Bacteriana Espontânea (PBE)", dose:"400 mg VO 1×/d ad lib", obs:"⚠ Cirrótico com episódio prévio de PBE. Hepatologia."},
{ind:"Profilaxia primária PBE em cirrose com ascite + sangramento digestivo", dose:"400 mg 12/12h × 7 dias", obs:""},
{ind:"Diarreia bacteriana ambulatorial (alternativa cipro)", dose:"400 mg 12/12h × 3-5 dias", obs:""},
],
ajustes:{
irc:"TFG <30: 400 mg 24/24h",
iht:"Sem ajuste",
idoso:"⚠ Cuidado com tendinite + delirium",
gestante:"⚠ C — EVITAR",
aleita:"Cautela",
ped:"⚠ EVITAR <18a",
},
mecanismo:"BACTERICIDA — inibe DNA girase. ⚠ Concentração tecidual baixa fora urina/intestino — limitação clínica.",
farmacocin:{
absorc:"VO ~40% — quelação por cátions",
distrib:"⚠ LIMITADA — urina/intestino bem, tecidos sistêmicos mal",
metab:"Hepático parcial",
elimin:"Renal 30% + fecal 30%",
meiavida:"~3-4h",
ligacao:"~14%",
},
ef_colats:{
comuns:["Náusea","Diarreia","Cefaleia","Tontura"],
sérios:["⚠ Tendinite/ruptura","⚠ Neurotoxicidade","⚠ Aneurisma","Disglicemia","Anafilaxia"],
},
interacoes:["Cátions di/trivalentes","Warfarina","Teofilina","AINEs"],
contraindicacoes:["⚠ Gestação","⚠ Criança","Tendinite prévia","Miastenia"],
monit:["Sintomas tendíneos","Glicemia"],
gravidez:"C",
sus:"REMUME em algumas SES",
referencias:["Sanford","AASLD (PBE)"],
},

);
