/* ===========================================================
   VOVÔMINIC EMERGÊNCIA — MEDICAÇÕES (PARTE 6)
   ANTI-HIPERTENSIVOS COMPLEMENTARES — disponíveis no
   mercado brasileiro, conforme DBHA 2025
   =========================================================== */

MEDICACOES.push(

/* ============== BRA — MAIS OPÇÕES ============== */

{id:"med-olmesartana", classe:"BRA — Bloqueador AT1", grupo:"anti_hipertensivo",
nome:"Olmesartana",
sin:["Benicar","Benicar HCT","Olmetec"],
formas:["Comprimidos 20, 40 mg — privada","Combinações fixas: olmesartana+HCTZ; olmesartana+anlodipino (Sevikar)"],
resumo:"BRA com maior potência por mg. Eficácia 24h excelente. Cuidado raro com ENTEROPATIA SPRUE-LIKE em uso prolongado.",
dose_rapida:"20-40 mg VO 1×/d",
doses:[
{ind:"HAS — monoterapia ou combinada", dose:"20 mg VO 1×/d inicial; titular até 40 mg/d", obs:"Combinações fixas com HCTZ ou anlodipino (Sevikar) disponíveis."},
{ind:"DM2 com microalbuminúria", dose:"20-40 mg/d", obs:"ROADMAP — estudos sugerem nefroproteção."},
],
ajustes:{
irc:"Sem ajuste rotineiro. ClCr <20: cautela.",
iht:"IH grave: cautela.",
idoso:"Sem ajuste.",
gestante:"CATEGORIA D — contraindicado 2º-3º trim.",
aleita:"Evitar.",
ped:"≥6 anos: especializado.",
},
mecanismo:"Antagonista AT1 — maior potência por mg entre BRA. Forte ligação ao receptor. Pró-droga ativada por hidrólise.",
farmacocin:{absorc:"VO: 26%", distrib:"Ampla", metab:"Hidrólise rápida", elimin:"Fezes + Renal", meiavida:"10-15h", ligacao:">99%"},
espectro:["HAS","HAS resistente","DM2 com microalbuminúria","Combinação BCC (Sevikar)"],
interacoes:[
{droga:"AINE, K+, IECA, espironolactona", efeito:"Hipercalemia, IRA."},
{droga:"Antiácidos", efeito:"↓ absorção — separar 2h."},
{droga:"Lítio", efeito:"↑ lítio."},
],
efeitos:[
{tipo:"comum", item:"Tontura, hipercalemia leve, ↑Cr leve"},
{tipo:"sério", item:"Angioedema raro, ENTEROPATIA SPRUE-LIKE (diarreia crônica + perda peso + atrofia vilositária — reversível ao suspender)"},
{tipo:"raro", item:"Hepatotoxicidade"},
],
alertas:[
{nivel:"crit", txt:"GESTAÇÃO: contraindicado."},
{nivel:"warn", txt:"ENTEROPATIA SPRUE-LIKE: efeito raro mas DESCRITO ESPECIFICAMENTE para olmesartana. Suspeitar em uso prolongado (meses-anos) com diarreia crônica + perda peso + má-absorção. SUSPENDER → resolução em semanas. Pode confundir com doença celíaca (biópsia parecida)."},
{nivel:"warn", txt:"MAIOR POTÊNCIA por mg entre BRA — útil em HAS resistente. Cuidado com hipotensão em idoso magro."},
{nivel:"info", txt:"SEVIKAR (olmesartana + anlodipino): combinação fixa moderna com bom perfil em HAS estágio 2-3."},
],
preparo:"VO comprimido, com ou sem alimento.",
monitor:"PA, K+, creatinina basal + 1-2 sem + 1 mês + 6 meses. Vigilar diarreia crônica em uso prolongado.",
diretriz:"DBHA 2025. ROADMAP trial. FDA warning (sprue-like).",
fluxo:null, calcs:[],
},

{id:"med-candesartana", classe:"BRA — Bloqueador AT1", grupo:"anti_hipertensivo",
nome:"Candesartana",
sin:["Atacand","Blopress"],
formas:["Comprimidos 8, 16, 32 mg — privada"],
resumo:"BRA com forte evidência em IC (CHARM trial). Boa cobertura 24h. Alternativa moderna à losartana.",
dose_rapida:"8-32 mg VO 1×/d",
doses:[
{ind:"HAS", dose:"8 mg VO 1×/d inicial; titular até 32 mg/d", obs:""},
{ind:"IC com FE reduzida (CHARM-Alternative)", dose:"4-32 mg/d (alvo dose máxima tolerada)", obs:"CHARM — reduz mortalidade em IC FE reduzida em pacientes intolerantes a IECA."},
{ind:"IC com FE preservada (CHARM-Preserved)", dose:"32 mg/d", obs:"Benefício mais modesto."},
],
ajustes:{
irc:"Sem ajuste rotineiro até TFG 30.",
iht:"IH grave: iniciar 4 mg.",
idoso:"Iniciar 4 mg.",
gestante:"CATEGORIA D — contraindicado.",
aleita:"Evitar.",
ped:"1-17 anos: dose por peso.",
},
mecanismo:"BRA com MAIOR AFINIDADE pelo receptor AT1 entre BRA e dissociação mais lenta — eficácia anti-hipertensiva prolongada.",
farmacocin:{absorc:"VO: 15% (pró-droga)", distrib:"Ampla", metab:"Mínimo", elimin:"Renal 33% + Bile 67%", meiavida:"9-12h", ligacao:">99%"},
espectro:["HAS","IC com FE reduzida (CHARM)","IC FE preservada"],
interacoes:[{droga:"Mesmas dos BRA", efeito:"AINE, K+, IECA."}],
efeitos:[
{tipo:"comum", item:"Tontura, hipercalemia leve"},
{tipo:"sério", item:"Angioedema, IRA, hipercalemia grave"},
{tipo:"raro", item:"Hepatite"},
],
alertas:[
{nivel:"crit", txt:"GESTAÇÃO: contraindicado."},
{nivel:"warn", txt:"CHARM trials: evidência sólida em IC — boa escolha quando IECA não tolerado."},
{nivel:"info", txt:"DOSE EQUIVALENTE: 16 mg candesartana ≈ 50 mg losartana ≈ 80 mg valsartana."},
],
preparo:"VO comprimido, com ou sem alimento.",
monitor:"PA, K+, Cr basal + 1-2 sem + 1 mês + 6 meses.",
diretriz:"DBHA 2025. CHARM-Alternative, CHARM-Preserved.",
fluxo:null, calcs:[],
},

{id:"med-irbesartana", classe:"BRA — Bloqueador AT1", grupo:"anti_hipertensivo",
nome:"Irbesartana",
sin:["Aprovel","Avapro","Coaprovel (combinada)"],
formas:["Comprimidos 75, 150, 300 mg — privada"],
resumo:"BRA com evidência sólida em nefroproteção em DM2 (IDNT, IRMA-2). Posologia 1×/d simples.",
dose_rapida:"150-300 mg VO 1×/d",
doses:[
{ind:"HAS", dose:"150 mg VO 1×/d inicial; titular até 300 mg/d", obs:"Combinação fixa com HCTZ (Coaprovel)."},
{ind:"Nefropatia diabética em DM2 (IDNT, IRMA-2)", dose:"300 mg/d", obs:"IDNT — reduz progressão IRC em DM2 com nefropatia estabelecida. IRMA-2 — previne progressão de micro para macroalbuminúria."},
],
ajustes:{
irc:"Sem ajuste rotineiro até TFG 30.",
iht:"Sem ajuste rotineiro.",
idoso:"Iniciar 75 mg.",
gestante:"CATEGORIA D — contraindicado.",
aleita:"Evitar.",
ped:"≥6 anos: 75-150 mg/d.",
},
mecanismo:"BRA com farmacocinética prolongada permitindo cobertura 24h em dose única.",
farmacocin:{absorc:"VO: 60-80%", distrib:"Ampla", metab:"CYP2C9 mínimo", elimin:"Fezes 80%", meiavida:"11-15h", ligacao:"~96%"},
espectro:["HAS","Nefropatia diabética DM2 (IDNT, IRMA-2)","DM2 com microalbuminúria"],
interacoes:[{droga:"Mesmas dos BRA", efeito:"AINE, K+, IECA."}],
efeitos:[
{tipo:"comum", item:"Tontura, hipercalemia leve, fadiga"},
{tipo:"sério", item:"Angioedema, IRA"},
{tipo:"raro", item:"Hepatite, anemia"},
],
alertas:[
{nivel:"crit", txt:"GESTAÇÃO: contraindicado."},
{nivel:"warn", txt:"NEFROPROTEÇÃO DM2: IDNT/IRMA-2 são estudos clássicos — irbesartana tem evidência específica em nefroproteção diabética."},
{nivel:"info", txt:"Coaprovel (irbesartana 150/300 mg + HCTZ 12,5 mg) — combinação fixa útil."},
],
preparo:"VO comprimido, com ou sem alimento.",
monitor:"PA, K+, Cr basal + 1-2 sem + 1 mês + 6 meses + RAC anual em DM.",
diretriz:"DBHA 2025. IDNT (NEJM 2001). IRMA-2.",
fluxo:null, calcs:[],
},

{id:"med-azilsartana", classe:"BRA — Bloqueador AT1 (mais recente)", grupo:"anti_hipertensivo",
nome:"Azilsartana (medoxomila)",
sin:["Edarbi","Edarbyclor (combinada)"],
formas:["Comprimidos 20, 40, 80 mg — privada"],
resumo:"BRA mais recente. MAIOR POTÊNCIA anti-hipertensiva entre BRA em estudos head-to-head. Evidência CV de longo prazo ainda em desenvolvimento.",
dose_rapida:"40-80 mg VO 1×/d",
doses:[
{ind:"HAS — refratária a outros BRA", dose:"40 mg VO 1×/d inicial; titular até 80 mg/d", obs:"Em meta-análises diretas, superou valsartana, olmesartana e candesartana em redução de PA."},
{ind:"HAS estágio 2-3", dose:"80 mg/d", obs:"Pode evitar terapia tripla em alguns pacientes."},
],
ajustes:{
irc:"Sem ajuste rotineiro até TFG 30.",
iht:"Sem ajuste rotineiro.",
idoso:"Sem ajuste.",
gestante:"CATEGORIA D — contraindicado.",
aleita:"Evitar.",
ped:"Não recomendada.",
},
mecanismo:"BRA com dissociação MAIS LENTA do receptor AT1 entre as BRA → maior eficácia 24h. Pró-droga (medoxomila → azilsartana ácida).",
farmacocin:{absorc:"VO: 60%", distrib:"Ampla", metab:"CYP2C9", elimin:"Fezes 55% + Renal 42%", meiavida:"11h", ligacao:">99%"},
espectro:["HAS — maior potência anti-hipertensiva","HAS refratária a outros BRA"],
interacoes:[{droga:"Mesmas dos BRA", efeito:"AINE, K+, IECA."}],
efeitos:[
{tipo:"comum", item:"Diarreia (mais incidente que outras BRA), tontura, hipotensão postural"},
{tipo:"sério", item:"Angioedema, IRA"},
{tipo:"raro", item:"Hepatite"},
],
alertas:[
{nivel:"crit", txt:"GESTAÇÃO: contraindicado."},
{nivel:"warn", txt:"POUCA EVIDÊNCIA CV de longo prazo — droga ainda relativamente recente. Eficácia anti-hipertensiva é o ponto forte."},
{nivel:"info", txt:"Opção quando outros BRA insuficientes. Custo é maior."},
],
preparo:"VO comprimido, com ou sem alimento.",
monitor:"PA, K+, Cr basal + 1-2 sem + 1 mês + 6 meses.",
diretriz:"DBHA 2025. Estudos Sica et al.",
fluxo:null, calcs:[],
},

/* ============== IECA — MAIS OPÇÕES ============== */

{id:"med-lisinopril", classe:"IECA de longa ação — NÃO-pró-droga", grupo:"anti_hipertensivo",
nome:"Lisinopril",
sin:["Prinivil","Zestril"],
formas:["Comprimidos 5, 10, 20 mg — privada"],
resumo:"IECA de longa ação. NÃO-PRÓ-DROGA (ativo direto, sem necessidade de fígado). Vantagem em hepatopata. Posologia 1×/d. Eliminação predominantemente renal.",
dose_rapida:"10-40 mg VO 1×/d",
doses:[
{ind:"HAS", dose:"10 mg VO 1×/d inicial; titular até 40 mg/d (máx 80 mg/d)", obs:"Posologia 1×/d. Dose mais alta que enalapril por equivalência."},
{ind:"IC com FE reduzida (ATLAS trial)", dose:"2,5-5 mg/d inicial; titular até 35-40 mg/d", obs:"ATLAS — alta dose reduz hospitalização mais que baixa dose. SOLVD também."},
{ind:"Pós-IAM com disfunção VE (GISSI-3)", dose:"5-10 mg/d", obs:"Iniciar 24h pós-IAM se PAS >100."},
{ind:"Nefropatia diabética/proteinúrica", dose:"10-40 mg/d", obs:"Reduz proteinúria + progressão IRC."},
],
ajustes:{
irc:"ClCr 30-60: 50% da dose. ClCr <30: 25%. HD: 2,5-5 mg pós-HD.",
iht:"NÃO É PRÓ-DROGA → SEM AJUSTE em IH (vantagem vs enalapril/ramipril).",
idoso:"Iniciar 2,5-5 mg.",
gestante:"CATEGORIA D — contraindicado 2º-3º trim.",
aleita:"Compatível em dose baixa.",
ped:"≥6 anos: 0,07-0,6 mg/kg/d.",
},
mecanismo:"IECA — inibe ECA. DIFERENÇA dos outros: NÃO É PRÓ-DROGA (forma ativa direta). Não depende de conversão hepática. Vantagem em IH grave (vs enalapril/ramipril/perindopril que são pró-drogas).",
farmacocin:{absorc:"VO: 25-50% (sem efeito de comida)", distrib:"Ampla", metab:"NÃO metabolizada", elimin:"Renal (100% inalterada)", meiavida:"~12h (permite 1×/d)", ligacao:"<10%"},
espectro:["HAS","IC com FE reduzida (ATLAS, SOLVD)","Pós-IAM (GISSI-3)","Nefropatia diabética","VANTAGEM em HEPATOPATA (não-pró-droga)"],
interacoes:[
{droga:"AINE", efeito:"REDUZ efeito + IRA + hipercalemia."},
{droga:"K+, espironolactona", efeito:"Hipercalemia."},
{droga:"BRA", efeito:"Não combinar."},
{droga:"Sacubitril/valsartana", efeito:"CONTRAINDICAÇÃO — wash-out 36h."},
],
efeitos:[
{tipo:"comum", item:"Tosse seca (10-15%), tontura, hipotensão, hipercalemia, ↑Cr"},
{tipo:"sério", item:"Angioedema raro, IRA aguda, hipercalemia grave"},
{tipo:"raro", item:"Neutropenia, hepatite"},
],
alertas:[
{nivel:"crit", txt:"GESTAÇÃO: contraindicado 2º-3º trimestre."},
{nivel:"warn", txt:"VANTAGEM em HEPATOPATA: lisinopril NÃO é pró-droga (vs enalapril/ramipril/perindopril que precisam de ativação hepática). Em IH grave: mantém eficácia plena."},
{nivel:"warn", txt:"ELIMINAÇÃO 100% RENAL: ajustar cuidadosamente em IRC. Diferente do enalapril (parcial hepático)."},
{nivel:"info", txt:"ATLAS trial: dose alta (32,5-35 mg/d) reduz hospitalização por IC mais que dose baixa (2,5-5 mg/d). Titular sempre que tolerar."},
],
preparo:"VO comprimido, com ou sem alimento.",
monitor:"PA, K+, Cr basal + 1-2 sem + 1 mês + 6 meses + anual.",
diretriz:"DBHA 2025. ATLAS trial. GISSI-3. SOLVD.",
fluxo:null, calcs:[],
},

{id:"med-perindopril", classe:"IECA de longa ação — pró-droga", grupo:"anti_hipertensivo",
nome:"Perindopril (arginina ou erbumina)",
sin:["Coversyl","Coversum"],
formas:["Comprimidos 4, 8 mg (erbumina) ou 5, 10 mg (arginina) — privada","Combinações fixas: perindopril + indapamida (Preterax/Noliprel); perindopril + anlodipino"],
resumo:"IECA de longa ação. Evidência CV sólida (EUROPA — DAC estável). Combinação com indapamida é PADRÃO em pós-AVC (PROGRESS). Excelente tolerabilidade.",
dose_rapida:"4-8 mg VO 1×/d (erbumina) ou 5-10 mg/d (arginina)",
doses:[
{ind:"HAS", dose:"4-5 mg VO 1×/d inicial; titular até 8-10 mg/d", obs:"Posologia 1×/d. Boa tolerância."},
{ind:"DAC estável (EUROPA trial)", dose:"8 mg/d", obs:"EUROPA — reduz desfechos CV em DAC estável, independente de HAS."},
{ind:"Pós-AVC isquêmico (PROGRESS — com indapamida)", dose:"4 mg + indapamida 2,5 mg/d", obs:"PROGRESS — reduz recorrência AVC em 28%. PADRÃO pós-AVC."},
{ind:"IC com FE preservada (PEP-CHF)", dose:"4-8 mg/d", obs:"Benefício modesto em FE preservada."},
{ind:"DM2 + macroalbuminúria (ADVANCE)", dose:"4-8 mg/d", obs:"ADVANCE — combinada com indapamida reduz desfechos macrovasculares e mortalidade total em DM2."},
],
ajustes:{
irc:"ClCr 30-60: 2-4 mg/d. ClCr <30: 2 mg dias alternados. HD: pós-HD.",
iht:"Sem ajuste rotineiro.",
idoso:"Iniciar 2 mg.",
gestante:"CATEGORIA D — contraindicado.",
aleita:"Compatível em dose baixa.",
ped:"Não recomendada.",
},
mecanismo:"IECA pró-droga — perindopril → perindoprilato ativo. Alta lipossolubilidade → penetração tecidular profunda (cardiovascular, renal) → efeito tecidular potente além do hemodinâmico.",
farmacocin:{absorc:"VO: 65-70%", distrib:"Alta penetração tecidular", metab:"Hepático → perindoprilato (ativo)", elimin:"Renal", meiavida:"Perindopril 1h | Perindoprilato 30-120h efeito clínico", ligacao:"~20%"},
espectro:["HAS","DAC estável (EUROPA)","Pós-AVC (PROGRESS — com indapamida)","IC com FE reduzida/preservada","DM2 + nefropatia (ADVANCE)"],
interacoes:[
{droga:"AINE, K+, BRA", efeito:"Como demais IECA."},
{droga:"Sacubitril/valsartana", efeito:"CONTRAINDICAÇÃO — wash-out 36h."},
],
efeitos:[
{tipo:"comum", item:"Tosse seca, tontura, hipotensão"},
{tipo:"sério", item:"Angioedema, IRA, hipercalemia"},
{tipo:"raro", item:"Neutropenia"},
],
alertas:[
{nivel:"crit", txt:"GESTAÇÃO: contraindicado."},
{nivel:"warn", txt:"PROGRESS trial: perindopril + indapamida (Preterax/Noliprel) é PADRÃO pós-AVC isquêmico — reduz recorrência 28%."},
{nivel:"warn", txt:"EUROPA trial: perindopril em DAC estável reduz desfechos CV 20% — mesmo SEM HAS, IC ou disfunção VE."},
{nivel:"info", txt:"ARGININA vs ERBUMINA: mesma molécula ativa. Doses ligeiramente diferentes (4 mg erbumina ≈ 5 mg arginina)."},
],
preparo:"VO comprimido, em jejum (manhã, 30 min antes do café — absorção 2× melhor que com comida).",
monitor:"PA, K+, Cr basal + 1-2 sem + 1 mês + 6 meses.",
diretriz:"DBHA 2025. EUROPA trial. PROGRESS trial. ADVANCE.",
fluxo:null, calcs:[],
},

/* ============== BCC DIIDROPIRIDÍNICOS DE 3ª GERAÇÃO ============== */

{id:"med-lercanidipino", classe:"BCC diidropiridínico de 3ª geração", grupo:"anti_hipertensivo",
nome:"Lercanidipino",
sin:["Zanidip","Zanedip"],
formas:["Comprimidos 10, 20 mg — privada"],
resumo:"BCC-DHP de 3ª geração — MENOS EDEMA MALEOLAR que anlodipino (5-10% vs 10-20%). Boa alternativa em paciente intolerante ao anlodipino.",
dose_rapida:"10-20 mg VO 1×/d (EM JEJUM)",
doses:[
{ind:"HAS — alternativa ao anlodipino (especialmente se edema)", dose:"10 mg VO 1×/d inicial; titular até 20 mg/d", obs:"TOMAR EM JEJUM (15 min antes da refeição) — comida triplica a absorção (risco hipotensão)."},
{ind:"HAS em idoso (boa tolerância)", dose:"10 mg/d", obs:"Menos taquicardia reflexa e edema vs outros BCC."},
],
ajustes:{
irc:"Sem ajuste até TFG 30. <30: cautela.",
iht:"IH leve-moderada: sem ajuste. IH grave: cautela.",
idoso:"Iniciar 10 mg.",
gestante:"Categoria C — evitar (preferir nifedipino retard).",
aleita:"Sem dados.",
ped:"Não recomendada.",
},
mecanismo:"BCC-DHP de 3ª geração — alta seletividade vascular + ativação gradual por depósito lipossolúvel em membrana → vasodilatação progressiva → MENOS taquicardia reflexa e MENOS edema maleolar.",
farmacocin:{absorc:"VO: 10% em jejum. Comida ↑ 3× absorção → tomar EM JEJUM.", distrib:"Alta lipossolubilidade — depósito em membrana vascular", metab:"Hepático CYP3A4", elimin:"Fezes 50% + Renal", meiavida:"8-10h (efeito clínico 24h)", ligacao:">98%"},
espectro:["HAS — alternativa ao anlodipino","HAS com edema refratário ao anlodipino","HAS em idoso"],
interacoes:[
{droga:"Inibidores CYP3A4 (cetoconazol, claritromicina)", efeito:"↑ lercanidipino — hipotensão. EVITAR."},
{droga:"Suco de grapefruit/pomelo", efeito:"↑ lercanidipino significativamente — EVITAR."},
{droga:"Indutores CYP3A4 (rifampicina, fenitoína)", efeito:"↓ lercanidipino."},
],
efeitos:[
{tipo:"comum", item:"Edema maleolar (MENOR que anlodipino), cefaleia, rubor, palpitação"},
{tipo:"sério", item:"Hipotensão grave (em uso pós-prandial), bradicardia"},
{tipo:"raro", item:"Hiperplasia gengival"},
],
alertas:[
{nivel:"crit", txt:"TOMAR EM JEJUM (15 min antes da refeição) — comida triplica absorção → risco hipotensão grave."},
{nivel:"crit", txt:"SUCO DE GRAPEFRUIT/POMELO — aumenta drasticamente a concentração. EVITAR completamente."},
{nivel:"warn", txt:"VANTAGEM PRINCIPAL: MENOS EDEMA MALEOLAR que anlodipino (5-10% vs 10-20%). Indicado se paciente teve que suspender anlodipino por edema."},
{nivel:"info", txt:"MANIDIPINO é alternativa similar — também BCC-DHP de 3ª geração com perfil de edema melhor."},
],
preparo:"VO comprimido, EM JEJUM (15 min antes da refeição) — CRÍTICO.",
monitor:"PA, FC, edema MMII basal + 4 sem.",
diretriz:"DBHA 2025.",
fluxo:null, calcs:[],
},

{id:"med-manidipino", classe:"BCC diidropiridínico de 3ª geração", grupo:"anti_hipertensivo",
nome:"Manidipino",
sin:["Manyper","Caldine"],
formas:["Comprimidos 10, 20 mg — privada"],
resumo:"BCC-DHP de 3ª geração — perfil similar ao lercanidipino. MENOS EDEMA. Tomar com café (vs lercanidipino em jejum).",
dose_rapida:"10-20 mg VO 1×/d (com café)",
doses:[
{ind:"HAS — alternativa ao anlodipino", dose:"10 mg VO 1×/d (manhã com café); titular até 20 mg/d", obs:"Tomar com refeição (vs lercanidipino que é em jejum)."},
],
ajustes:{
irc:"Sem ajuste até TFG 30.",
iht:"IH grave: contraindicado.",
idoso:"Iniciar 10 mg.",
gestante:"Categoria C — evitar.",
aleita:"Sem dados.",
ped:"Não recomendada.",
},
mecanismo:"BCC-DHP de 3ª geração — mesma classe do lercanidipino. Liberação gradual em membrana vascular.",
farmacocin:{absorc:"VO: ~15% (comida ↑ absorção)", distrib:"Alta lipossolubilidade", metab:"CYP3A4", elimin:"Fezes", meiavida:"4-8h (efeito 24h)", ligacao:">99%"},
espectro:["HAS — alternativa ao anlodipino","HAS com edema refratário"],
interacoes:[{droga:"Mesmas do lercanidipino", efeito:"CYP3A4, grapefruit."}],
efeitos:[
{tipo:"comum", item:"Edema maleolar (menor que anlodipino), cefaleia, rubor"},
{tipo:"sério", item:"Hipotensão"},
{tipo:"raro", item:"Hepatotoxicidade"},
],
alertas:[
{nivel:"warn", txt:"MENOR edema maleolar que anlodipino — alternativa em paciente intolerante."},
{nivel:"info", txt:"DIFERENÇA do lercanidipino: tomar com café (vs lercanidipino em jejum). Conferir orientação."},
],
preparo:"VO comprimido, com café da manhã.",
monitor:"PA, FC, edema MMII.",
diretriz:"DBHA 2025.",
fluxo:null, calcs:[],
},

/* ============== BCC NÃO-DIIDROPIRIDÍNICOS ============== */

{id:"med-verapamil", classe:"BCC NÃO-diidropiridínico — cronotrópico negativo", grupo:"anti_hipertensivo",
nome:"Verapamil",
sin:["Dilacoron"],
formas:["Comprimidos 80, 120 mg (curta ação) — SUS","Comprimidos retard 120, 180, 240 mg — privada","Ampolas 5 mg/2 mL (IV — arritmia)"],
resumo:"BCC NÃO-DHP — bloqueia condução AV. Útil em FA com RVR, TSV, angina. CONTRAINDICADO em IC com FE reduzida e BAV. NÃO combinar com β-bloq.",
dose_rapida:"VO retard 120-240 mg/d | IV 5-10 mg lento (FA aguda)",
doses:[
{ind:"FA com RVR (controle FC ambulatorial)", dose:"120-360 mg/d VO retard divididos em 1-2 tomadas", obs:"Alternativa a β-bloq. Útil em asma/DPOC ativo (não broncoconstritor)."},
{ind:"TSV — cardioversão aguda (alternativa adenosina)", dose:"IV 5-10 mg em 2 min; pode repetir 10 mg em 30 min", obs:"Cuidado: hipotensão grave. Preferir adenosina. NÃO em WPW + FA."},
{ind:"Angina (incluindo Prinzmetal)", dose:"120-240 mg/d", obs:"Vasodilatação coronariana + cronotrópico negativo."},
{ind:"HAS — uso seletivo (NÃO 1ª linha)", dose:"120-240 mg/d retard", obs:"Útil em HAS + arritmia supraventricular."},
{ind:"Profilaxia enxaqueca (off-label)", dose:"120-240 mg/d", obs:"Uso em neurologia."},
],
ajustes:{
irc:"Sem ajuste rotineiro.",
iht:"IH grave: reduzir 50%.",
idoso:"Iniciar 40 mg 8/8h ou 120 mg retard 1×/d. Risco constipação grave.",
gestante:"Categoria C — pode usar em arritmia.",
aleita:"Compatível em dose baixa.",
ped:"Uso especializado.",
},
mecanismo:"BCC NÃO-DHP — bloqueia canais Ca²⁺ tipo-L em musculatura lisa vascular E miocárdio (vs DHP que é seletivo vascular). Efeitos: vasodilatação + ↓ cronotropismo nodal AV + ↓ inotropismo.",
farmacocin:{absorc:"VO: 20-35% (1ª passagem extensa)", distrib:"Ampla", metab:"CYP3A4 → norverapamil (ativo)", elimin:"Renal 70%", meiavida:"3-7h | Retard 12-16h", ligacao:"~90%"},
espectro:["FA com RVR","TSV (cardioversão aguda IV)","Angina (incluindo vasoespástica)","HAS com arritmia","Profilaxia enxaqueca"],
interacoes:[
{droga:"β-bloqueadores", efeito:"BRADICARDIA / BAV GRAVE — NÃO combinar VO."},
{droga:"Digoxina", efeito:"↑ digoxina 50-75% — reduzir digoxina."},
{droga:"Sinvastatina", efeito:"↑ estatina — rabdomiólise. Limitar sinvastatina 20 mg/d."},
{droga:"Grapefruit", efeito:"↑ verapamil — evitar."},
],
efeitos:[
{tipo:"comum", item:"CONSTIPAÇÃO (30-40% — efeito clássico), bradicardia, hipotensão postural, cefaleia, edema MMII"},
{tipo:"sério", item:"BAV avançado, IC aguda em FE reduzida (CONTRAINDICAÇÃO), hipotensão grave (IV rápido)"},
{tipo:"raro", item:"Hiperplasia gengival, ginecomastia, hepatite"},
],
alertas:[
{nivel:"crit", txt:"CONTRAINDICADO em IC com FE REDUZIDA (depressão miocárdica → piora). CONTRAINDICADO em BAV 2°/3° grau sem MP. CONTRAINDICADO em FA com WPW (acelera via acessória — FV)."},
{nivel:"crit", txt:"NÃO COMBINAR com β-BLOQ VO — risco BAV avançado, bradicardia sintomática, IC aguda."},
{nivel:"crit", txt:"IV em FA com WPW: pode degenerar para FV. Identificar QRS largo + irregular ANTES — cardioversão elétrica."},
{nivel:"warn", txt:"CONSTIPAÇÃO importante (30-40%) — fibras + hidratação. Em idoso: pode causar fecaloma."},
{nivel:"info", txt:"VERAPAMIL vs DILTIAZEM: verapamil mais cronotrópico negativo e constipação; diltiazem mais vasodilatador e menos constipação."},
],
preparo:"VO comprimido. IV bolus: 5-10 mg em 2 min sob monitor ECG.",
monitor:"PA, FC, ECG (PR, BAV), intestinal.",
diretriz:"DBHA 2025. ESC AF 2024.",
fluxo:null, calcs:[],
},

{id:"med-diltiazem", classe:"BCC NÃO-diidropiridínico — controle FC + vasodilatador", grupo:"anti_hipertensivo",
nome:"Diltiazem",
sin:["Cardizem","Cardizem CD","Balcor"],
formas:["Comprimidos 30, 60 mg (curta ação) — privada","Cápsulas retard 90, 120, 180, 240, 300 mg — privada","Ampolas 25 mg (IV — FA aguda)"],
resumo:"BCC NÃO-DHP — alternativa ao verapamil com MENOR efeito inotrópico negativo e MENOS constipação. Controle FC em FA + vasodilatador.",
dose_rapida:"180-360 mg/d VO retard | IV bolus 0,25 mg/kg",
doses:[
{ind:"FA com RVR (controle FC ambulatorial)", dose:"180-360 mg/d VO retard 1×/d", obs:"Alternativa ao verapamil — MENOS constipação."},
{ind:"FA com RVR aguda (IV)", dose:"0,25 mg/kg IV bolus em 2 min (~15-20 mg em 70 kg); pode repetir 0,35 mg/kg em 15 min; BIC 5-15 mg/h", obs:"Útil em paciente SEM IC. Monitor PA contínuo."},
{ind:"Angina (especialmente vasoespástica)", dose:"180-360 mg/d", obs:"Vasodilatador coronariano + ↓ FC."},
{ind:"HAS com arritmia (uso seletivo)", dose:"180-360 mg/d retard", obs:"Não 1ª linha em HAS isolada."},
],
ajustes:{
irc:"Sem ajuste rotineiro.",
iht:"IH grave: reduzir 50%.",
idoso:"Iniciar 60-120 mg/d.",
gestante:"Categoria C.",
aleita:"Compatível em dose baixa.",
ped:"Uso especializado.",
},
mecanismo:"BCC NÃO-DHP — bloqueia canais Ca²⁺ tipo-L. Vs verapamil: MAIOR vasodilatador, MENOR cronotrópico/inotrópico negativo. Vs DHP: tem efeito nodal AV (útil em FA).",
farmacocin:{absorc:"VO: 40-60% (1ª passagem)", distrib:"Ampla", metab:"CYP3A4 → desacetildiltiazem (ativo)", elimin:"Renal 35% + Fezes 65%", meiavida:"3-5h | Retard 5-7h", ligacao:"~80%"},
espectro:["FA com RVR","Angina vasoespástica","HAS + arritmia"],
interacoes:[
{droga:"β-bloqueadores", efeito:"BAV/bradicardia — NÃO combinar VO."},
{droga:"Digoxina", efeito:"↑ digoxina ~20%."},
{droga:"Sinvastatina", efeito:"↑ estatina — limitar 20 mg/d."},
{droga:"Inibidores CYP3A4", efeito:"↑ diltiazem."},
],
efeitos:[
{tipo:"comum", item:"Bradicardia, hipotensão postural, edema maleolar, constipação (MENOR que verapamil)"},
{tipo:"sério", item:"BAV avançado, IC aguda em FE reduzida (cuidado), bradicardia sintomática"},
{tipo:"raro", item:"Hiperplasia gengival, hepatite"},
],
alertas:[
{nivel:"crit", txt:"CONTRAINDICADO em IC com FE REDUZIDA descompensada, BAV 2°/3° grau sem MP, FA com WPW."},
{nivel:"crit", txt:"NÃO COMBINAR com β-bloq VO — risco BAV/bradicardia."},
{nivel:"warn", txt:"DILTIAZEM vs VERAPAMIL: diltiazem é MAIS vasodilatador + MENOS constipação + MENOR depressão miocárdica. Preferível em maioria dos cenários."},
{nivel:"info", txt:"FORMULAÇÕES MÚLTIPLAS: curta (30/60 mg 8/8h), retard 1×/d ou 12/12h. Confirmar nome comercial."},
],
preparo:"VO comprimido, com ou sem alimento. IV: bolus 2 min sob monitor ECG.",
monitor:"PA, FC, ECG, edema.",
diretriz:"DBHA 2025. ESC AF 2024.",
fluxo:null, calcs:[],
},

/* ============== β-BLOQUEADORES — MAIS OPÇÕES ============== */

{id:"med-propranolol", classe:"β-bloqueador NÃO-seletivo (β1 + β2)", grupo:"anti_hipertensivo",
nome:"Propranolol",
sin:["Inderal","Pranolol"],
formas:["Comprimidos 10, 40, 80 mg — SUS/REMUME","Cápsulas LP 80, 120, 160 mg — privada","Ampolas 1 mg/mL (IV — emergência)"],
resumo:"β-bloq não-seletivo clássico, SUS amplamente disponível. Indicações específicas: TIREOTOXICOSE, profilaxia ENXAQUECA, TREMOR ESSENCIAL, ansiedade situacional, SANGRAMENTO VARICOSO. NÃO 1ª linha em HAS.",
dose_rapida:"VO: 40-160 mg/d em 2-3 tomadas | Crise tireoidiana IV: 1-5 mg lento",
doses:[
{ind:"Tireotoxicose / Crise tireoidiana (controle adrenérgico)", dose:"40-120 mg VO 6/6h ou 8/8h | Crise: 1-5 mg IV lento ou 60-80 mg VO 4/4h", obs:"Bloqueia efeitos adrenérgicos + inibe conversão T4→T3 periférica. Combinar com PTU/metimazol + lugol."},
{ind:"Profilaxia de enxaqueca", dose:"40-160 mg/d divididos", obs:"1ª linha em profilaxia farmacológica."},
{ind:"Tremor essencial", dose:"40-320 mg/d divididos", obs:"Eficácia em 50-70%."},
{ind:"Ansiedade situacional / desempenho", dose:"10-40 mg VO 30-60 min antes do evento", obs:"Bloqueia sintomas autonômicos."},
{ind:"Sangramento varicoso esofágico (profilaxia)", dose:"20-40 mg 12/12h, titular até FC <55-60 ou ↓25% basal", obs:"Reduz pressão portal. Carvedilol é alternativa."},
{ind:"HAS / Pós-IAM (uso seletivo)", dose:"40-80 mg 12/12h", obs:"NÃO 1ª linha (DBHA 2025). Bisoprolol/metoprolol succ/carvedilol têm mais evidência em IC pós-IAM."},
],
ajustes:{
irc:"Sem ajuste (eliminação hepática).",
iht:"IH grave: reduzir 50%.",
idoso:"Iniciar 10-20 mg.",
gestante:"Categoria C — pode causar RCIU/bradicardia neonatal. Preferir alternativa em HAS gestante.",
aleita:"Compatível em dose baixa.",
ped:"0,5-4 mg/kg/d divididos.",
},
mecanismo:"β-bloqueador NÃO-SELETIVO — bloqueia β1 (FC, DC) E β2 (broncoconstrição, vasoconstrição periférica, glicogenólise). LIPOSSOLÚVEL — atravessa BBB (efeitos centrais).",
farmacocin:{absorc:"VO: 30% (1ª passagem extensa)", distrib:"Lipossolúvel — alta BBB", metab:"CYP1A2, CYP2D6 — extenso", elimin:"Renal (metabólitos)", meiavida:"3-6h | LP 8-11h", ligacao:"~90%"},
espectro:["Tireotoxicose / crise tireoidiana","Profilaxia enxaqueca","Tremor essencial","Ansiedade situacional","Sangramento varicoso esofágico","HAS (uso seletivo)","Hipertensão portal"],
interacoes:[
{droga:"BCC não-DHP (verapamil, diltiazem)", efeito:"Bradicardia/BAV — NÃO combinar VO."},
{droga:"Adrenalina (em anafilaxia)", efeito:"Bloqueio β-2 paradoxal → crise hipertensiva + broncoespasmo refratário. Usar GLUCAGON."},
{droga:"Insulina/sulfonilureia", efeito:"Mascarar hipoglicemia (sintomas adrenérgicos)."},
],
efeitos:[
{tipo:"comum", item:"Bradicardia, fadiga, extremidades frias, BRONCOESPASMO (β2 não-seletivo), hipotensão postural, pesadelos (atravessa BBB), disfunção sexual"},
{tipo:"sério", item:"Bradicardia grave/BAV, BRONCOESPASMO em asma/DPOC (CONTRAINDICAÇÃO), IC aguda em FE reduzida, mascaramento de hipoglicemia, depressão"},
{tipo:"raro", item:"Síndrome de retirada (rebote HAS + IAM)"},
],
alertas:[
{nivel:"crit", txt:"ASMA ATIVA + DPOC com broncoespasmo: CONTRAINDICADO (β2 não-seletivo). Preferir bisoprolol/nebivolol/metoprolol (β1-seletivos)."},
{nivel:"crit", txt:"DM + HIPOGLICEMIAS frequentes: propranolol mascara TODOS os sintomas adrenérgicos. Em β1-seletivo: só palpitação é mascarada."},
{nivel:"crit", txt:"NÃO SUSPENDER ABRUPTAMENTE — síndrome de retirada (rebote HAS + risco IAM em DAC). Reduzir 50% por 1-2 sem."},
{nivel:"warn", txt:"ANAFILAXIA em paciente em propranolol: adrenalina pode ter resposta paradoxal — GLUCAGON 1-5 mg IV bolus é a alternativa."},
{nivel:"info", txt:"PROFILAXIA ENXAQUECA é indicação CLÁSSICA. Topiramato e amitriptilina são alternativas."},
],
preparo:"VO comprimido, com ou sem alimento.",
monitor:"PA, FC (manter ≥55), glicemia em DM, sintomas broncoespasmo, humor.",
diretriz:"DBHA 2025. Cochrane (enxaqueca). Diretrizes Tireoide.",
fluxo:null, calcs:[],
},

{id:"med-nebivolol", classe:"β1-bloqueador altamente cardiosseletivo + vasodilatador (NO)", grupo:"anti_hipertensivo",
nome:"Nebivolol",
sin:["Nebilet","Nebilenin"],
formas:["Comprimidos 5 mg — privada"],
resumo:"β1-bloqueador de 3ª geração com efeito vasodilatador adicional via óxido nítrico (NO). MENOS efeitos colaterais (broncoespasmo, disfunção sexual). Boa opção em idoso (SENIORS).",
dose_rapida:"5-10 mg VO 1×/d",
doses:[
{ind:"HAS — uso seletivo (paciente intolerante a outros β-bloq)", dose:"5 mg VO 1×/d inicial; titular até 10 mg/d", obs:"Não 1ª linha em HAS isolada (DBHA 2025)."},
{ind:"IC com FE reduzida em IDOSO (SENIORS trial)", dose:"1,25 mg/d inicial; DOBRAR cada 2 sem até 10 mg/d", obs:"SENIORS — eficácia em ≥70 anos. Alternativa em idoso intolerante."},
{ind:"HAS com disfunção erétil (perfil favorável)", dose:"5 mg/d", obs:"MENOR disfunção sexual via vasodilatação por NO."},
],
ajustes:{
irc:"ClCr <30: iniciar 2,5 mg.",
iht:"IH grave: cautela.",
idoso:"Iniciar 2,5 mg.",
gestante:"Categoria C — evitar.",
aleita:"Cautela.",
ped:"Não recomendada.",
},
mecanismo:"β1-bloqueador HIGHLY seletivo (maior seletividade β1/β2 entre β-bloq) + vasodilatador via ↑ óxido nítrico (NO) endotelial. Perfil sexual + metabólico melhor que outros β-bloq.",
farmacocin:{absorc:"VO: 12-96% (variabilidade CYP2D6)", distrib:"Ampla", metab:"CYP2D6 — metabólitos ativos", elimin:"Renal e fezes", meiavida:"10-50h (depende CYP2D6)", ligacao:"~98%"},
espectro:["HAS — opção em intolerância","IC com FE reduzida em idoso (SENIORS)","HAS com disfunção erétil"],
interacoes:[
{droga:"BCC não-DHP", efeito:"Bradicardia/BAV — não combinar."},
{droga:"Inibidores CYP2D6 (fluoxetina, paroxetina, bupropiona)", efeito:"↑ nebivolol — hipotensão."},
],
efeitos:[
{tipo:"comum", item:"Cefaleia, fadiga, bradicardia (menor que atenolol), edema (menor)"},
{tipo:"sério", item:"Bradicardia grave/BAV"},
{tipo:"raro", item:"Broncoespasmo (raríssimo — alta seletividade β1)"},
],
alertas:[
{nivel:"warn", txt:"MAIOR SELETIVIDADE β1 entre β-bloq — MELHOR perfil em DPOC, asma controlada, DM."},
{nivel:"warn", txt:"VASODILATADOR via NO — perfil sexual MELHOR que outros β-bloq."},
{nivel:"info", txt:"CYP2D6: 5-10% da população são metabolizadores lentos → ↑ efeito. Iniciar dose menor em risco."},
{nivel:"info", txt:"SENIORS trial: eficácia em ≥70 anos com IC. Alternativa quando bisoprolol/carvedilol mal tolerados."},
],
preparo:"VO comprimido, com ou sem alimento.",
monitor:"PA, FC, sintomas IC.",
diretriz:"DBHA 2025. SENIORS trial.",
fluxo:null, calcs:[],
},

/* ============== POUPADOR K+ ADICIONAL ============== */

{id:"med-amilorida", classe:"Diurético poupador de K+ (bloq canal ENaC)", grupo:"anti_hipertensivo",
nome:"Amilorida (Moduretic)",
sin:["Moduretic (combinada com HCTZ — única apresentação BR)"],
formas:["Amilorida 5 mg + HCTZ 50 mg (Moduretic) — combinação fixa única disponível no Brasil"],
resumo:"Poupador de K+ via bloqueio ENaC. NO BRASIL: APENAS em combinação fixa Moduretic. Útil em HAS resistente leve + hipocalemia.",
dose_rapida:"1 comprimido Moduretic VO 1×/d (manhã)",
doses:[
{ind:"HAS — combinada quando hipocalemia com tiazídico", dose:"1 comp Moduretic (5 mg/50 mg) VO 1×/d (manhã)", obs:"Útil quando paciente desenvolve hipocalemia com HCTZ — amilorida compensa."},
{ind:"HAS resistente leve com hipocalemia", dose:"1 comp/d", obs:"Quando espironolactona é mal tolerada (ginecomastia em homem). 3ª-4ª linha."},
],
ajustes:{
irc:"ClCr <60: cuidado (hipercalemia). ClCr <30: CONTRAINDICADA.",
iht:"Sem ajuste rotineiro.",
idoso:"Iniciar dose menor. Risco hipercalemia.",
gestante:"Categoria B — uso restrito.",
aleita:"Compatível.",
ped:"Não recomendada.",
},
mecanismo:"Bloqueia canal ENaC (Epithelial Sodium Channel) no ducto coletor → ↑ excreção Na+ MAS retém K+/H+. NÃO depende de aldosterona (vs espironolactona).",
farmacocin:{absorc:"VO: 15-25%", distrib:"Não atravessa BBB", metab:"NÃO metabolizada", elimin:"Renal 50% inalterada", meiavida:"6-9h", ligacao:"Mínima"},
espectro:["HAS + hipocalemia por tiazídico","HAS resistente leve","Alternativa à espironolactona quando ginecomastia"],
interacoes:[
{droga:"iSRA, K+, espironolactona", efeito:"HIPERCALEMIA — não combinar ou monitor rigoroso."},
{droga:"AINE", efeito:"Hipercalemia + IRA."},
{droga:"Lítio", efeito:"↑ lítio."},
],
efeitos:[
{tipo:"comum", item:"Hipercalemia (mecanismo principal), náusea, tontura"},
{tipo:"sério", item:"Hipercalemia grave em IRC/idoso/iSRA, IRA"},
{tipo:"raro", item:"Ginecomastia (muito menor que espironolactona)"},
],
alertas:[
{nivel:"crit", txt:"HIPERCALEMIA: contraindicada se K+ basal >5,5 ou ClCr <30. Monitor K+ basal + 1 sem + 4 sem."},
{nivel:"warn", txt:"MODURETIC: única apresentação BR é em COMBINAÇÃO FIXA com HCTZ 50 mg. Limitação: HCTZ 50 mg é dose alta — em paciente que precisa só de poupador, dose excessiva de tiazídico."},
{nivel:"warn", txt:"ALTERNATIVA: espironolactona é mais usada (evidência em IC, cirrose, HAS resistente). Amilorida útil em intolerância à espironolactona (ginecomastia)."},
],
preparo:"VO comprimido, manhã.",
monitor:"PA, K+, Cr basal + 1 sem + 1 mês + 6 meses.",
diretriz:"DBHA 2025.",
fluxo:null, calcs:[],
},

/* ============== SIMPATOLÍTICO CENTRAL ADICIONAL ============== */

{id:"med-clonidina", classe:"Simpatolítico central — agonista α2", grupo:"anti_hipertensivo",
nome:"Clonidina",
sin:["Atensina","Catapresan"],
formas:["Comprimidos 0,1 mg, 0,15 mg, 0,2 mg — SUS","Adesivo transdérmico 0,1-0,3 mg/24h — privada"],
resumo:"Simpatolítico central α2-agonista. Uso em URGÊNCIA HIPERTENSIVA, HAS resistente, abstinência alcoólica/opioide, tireotoxicose. RISCO REBOTE se suspenso abruptamente.",
dose_rapida:"Urgência: 0,1-0,2 mg VO | Crônico: 0,1 mg 8/8h ou 12/12h",
doses:[
{ind:"URGÊNCIA hipertensiva (sem LOA aguda)", dose:"0,1-0,2 mg VO, repetir 0,1 mg cada 1-2h se necessário (máx 0,7 mg em 24h)", obs:"Início 30-60 min. Alternativa ao captopril 25 mg SL. Sedação esperada."},
{ind:"HAS resistente (4ª-5ª droga)", dose:"0,1 mg 8/8h ou 12/12h inicial; titular até 0,3 mg 8/8h", obs:"Posologia inconveniente — alternativa: adesivo 1×/sem."},
{ind:"Síndrome de abstinência alcoólica/opioide", dose:"0,1-0,2 mg 8/8h", obs:"Reduz hiperatividade simpática (taquicardia, HAS, agitação)."},
{ind:"TDAH em criança (off-label)", dose:"0,05-0,2 mg/d", obs:"Especializado — neuro/psiquiatria infantil."},
{ind:"Tireotoxicose (alternativa a β-bloq em asma)", dose:"0,1-0,2 mg 8/8h", obs:"Reduz sintomas adrenérgicos."},
{ind:"Fogachos da menopausa (off-label)", dose:"0,05-0,1 mg 12/12h", obs:"Alternativa não-hormonal."},
],
ajustes:{
irc:"ClCr <30: reduzir 50%.",
iht:"Sem ajuste rotineiro.",
idoso:"Iniciar 0,05 mg 12/12h. Risco sedação + hipotensão postural alto.",
gestante:"Categoria C — pode usar se essencial.",
aleita:"Compatível em dose baixa.",
ped:"TDAH off-label.",
},
mecanismo:"Agonista α2 central no SNC → reduz tônus simpático periférico → ↓ FC + ↓ PA. Em uso crônico há down-regulation dos receptores → SUSPENSÃO ABRUPTA = rebote adrenérgico (taquicardia, HAS grave).",
farmacocin:{absorc:"VO: 75-95% | Adesivo: 24h", distrib:"Atravessa BBB", metab:"Hepático parcial", elimin:"Renal 50% inalterada", meiavida:"6-20h", ligacao:"~30%"},
espectro:["Urgência hipertensiva (alternativa ao captopril)","HAS resistente (linha tardia)","Abstinência alcoólica/opioide","TDAH em criança","Tireotoxicose (em asma)","Fogachos da menopausa"],
interacoes:[
{droga:"β-bloqueadores", efeito:"Suspensão da clonidina + β-bloq simultâneo = CRISE HIPERTENSIVA. Suspender β-bloq ANTES da clonidina."},
{droga:"Antidepressivos tricíclicos", efeito:"Reduzem efeito da clonidina (bloqueiam α2)."},
{droga:"Álcool, sedativos", efeito:"Sedação aditiva."},
],
efeitos:[
{tipo:"comum", item:"SEDAÇÃO importante, boca seca (>50%), hipotensão postural, bradicardia, constipação, disfunção sexual"},
{tipo:"sério", item:"REBOTE HIPERTENSIVO se suspenso abruptamente (HAS grave + taquicardia em 24-48h), depressão, BAV, bradicardia grave"},
{tipo:"raro", item:"Síndrome de Raynaud, alucinações, parkinsonismo"},
],
alertas:[
{nivel:"crit", txt:"REBOTE HIPERTENSIVO: NUNCA suspender abruptamente em uso >2 semanas — rebote 24-48h após (HAS grave, taquicardia, sudorese, agitação, risco AVC/IAM). DESMAMAR gradualmente em 1-2 semanas."},
{nivel:"crit", txt:"INTERAÇÃO com β-BLOQUEADOR: se paciente usa AMBOS, RETIRAR β-BLOQ PRIMEIRO (vários dias antes) e depois clonidina. Suspensão simultânea = crise."},
{nivel:"warn", txt:"SEDAÇÃO LIMITA USO em paciente que dirige/trabalho com atenção. Em idoso: risco queda."},
{nivel:"warn", txt:"BOCA SECA: efeito muito frequente — hidratação, gomas sem açúcar. Pode causar má aderência."},
{nivel:"info", txt:"ADESIVO TRANSDÉRMICO: troca semanal — adesão melhor, mas reação local em 30-50%."},
],
preparo:"VO comprimido. Adesivo: aplicar em pele íntegra do tronco superior/braço.",
monitor:"PA, FC, sintomas posturais, sedação.",
diretriz:"DBHA 2025.",
fluxo:null, calcs:[],
},

/* ============== VASODILATADOR — MINOXIDIL ============== */

{id:"med-minoxidil", classe:"Vasodilatador arterial direto — abridor canal K-ATP", grupo:"anti_hipertensivo",
nome:"Minoxidil (oral)",
sin:["Loniten (oral)","Rogaine (tópico — alopecia, NÃO HAS)"],
formas:["Comprimidos 5, 10 mg (oral — HAS resistente extrema) — privada","Solução tópica 2-5% — APENAS para alopecia, não para HAS"],
resumo:"VASODILATADOR ARTERIAL EXTREMAMENTE POTENTE — ÚLTIMA LINHA em HAS resistente refratária. SEMPRE combinado com β-bloq + diurético de alça. Efeito colateral notório: HIPERTRICOSE.",
dose_rapida:"5-40 mg VO 1-2×/d (uso especializado)",
doses:[
{ind:"HAS RESISTENTE REFRATÁRIA — ÚLTIMA LINHA", dose:"5 mg VO 1×/d inicial; titular cada 3 dias até 10-40 mg/d em 1-2 tomadas (máx 100 mg/d)", obs:"SEMPRE combinado com β-bloq (controle taquicardia reflexa) + DIURÉTICO DE ALÇA (controle retenção)."},
],
ajustes:{
irc:"Reduzir dose. ClCr <30: cautela extrema.",
iht:"Cautela.",
idoso:"Iniciar 2,5 mg. Risco IC + hipertricose alto.",
gestante:"Categoria C — evitar.",
aleita:"Sem dados.",
ped:"Especializado.",
},
mecanismo:"Pró-droga — minoxidil sulfato (ativo) abre canais K-ATP em musculatura lisa arterial → hiperpolarização → vasodilatação ARTERIAL POTENTE (não venosa). Ativa simpático reflexamente → taquicardia + retenção de Na+/H2O → necessidade obrigatória de β-bloq + diurético.",
farmacocin:{absorc:"VO: 90%", distrib:"Ampla", metab:"Hepático (sulfação)", elimin:"Renal", meiavida:"3-4h (efeito 24h)", ligacao:"Mínima"},
espectro:["HAS resistente REFRATÁRIA — última linha (após espironolactona, bisoprolol, doxazosina)","Alopecia androgenética — formulação TÓPICA APENAS"],
interacoes:[
{droga:"β-bloqueadores", efeito:"COMBINAÇÃO OBRIGATÓRIA — minoxidil isolado causa taquicardia extrema."},
{droga:"Diuréticos de alça (furosemida)", efeito:"COMBINAÇÃO OBRIGATÓRIA — minoxidil isolado causa retenção massiva."},
],
efeitos:[
{tipo:"comum", item:"HIPERTRICOSE (80%! — pelos no rosto, tronco, MMII; reversível 1-6 meses pós-suspensão), retenção líquida/edema, taquicardia reflexa, cefaleia"},
{tipo:"sério", item:"DERRAME PERICÁRDICO (3% — tamponamento possível), IC por sobrecarga volume, hipotensão grave, isquemia miocárdica (taquicardia)"},
{tipo:"raro", item:"Necrose papilar renal, alterações ECG"},
],
alertas:[
{nivel:"crit", txt:"NUNCA USAR ISOLADO — sempre combinado com β-BLOQ + DIURÉTICO DE ALÇA. Sem essa combinação: descompensação CV grave."},
{nivel:"crit", txt:"DERRAME PERICÁRDICO em 3% — pode causar tamponamento. ECO basal e 4-6 sem. Suspender se sintomas."},
{nivel:"crit", txt:"ÚLTIMA LINHA — usar APENAS quando HAS resistente comprovada após exclusão de HAS secundária, otimização de adesão, falência de espironolactona + bisoprolol/doxazosina."},
{nivel:"warn", txt:"HIPERTRICOSE em 80% — orientar paciente ANTES (motivo principal de descontinuação, especialmente mulheres). Reversível em 1-6 meses pós-suspensão."},
{nivel:"info", txt:"VERSÃO TÓPICA (Rogaine): apenas alopecia androgenética — NÃO usar via oral para alopecia."},
],
preparo:"VO comprimido. Sempre prescrever com β-bloq + diurético de alça concomitantes.",
monitor:"PA, FC, peso (retenção), ECG, ECO 4-6 sem (pericárdio), eletrólitos, função renal.",
diretriz:"DBHA 2025.",
fluxo:null, calcs:[],
},

);
