/* ===========================================================
   VOVÔMINIC DOUTÔ — meds/gineco.js
   Saúde da Mulher / Ginecologia / Obstetrícia
   Contracepção · Climatério · Gestação · Sangramento · Vulvovaginites
   =========================================================== */

MEDICACOES.push(

/* ============== CONTRACEPÇÃO HORMONAL ============== */

{id:"med-aco-combinado", contexto:["ubs"], classe:"Contraceptivo hormonal combinado oral", grupo:"contraceptivo",
nome:"ACO combinado (Etinilestradiol + Levonorgestrel)",
sin:["Microvlar","Ciclo 21","Level","Nordette"],
formas:["Cartela 21 comprimidos: etinilestradiol 30 mcg + levonorgestrel 150 mcg — UBS / PFPB"],
resumo:"ACO combinado de baixa dose (30 mcg EE) — 1ª linha contracepção hormonal oral em mulher saudável <35a. Eficácia ~99% uso perfeito, ~91% uso típico. Disponível UBS + PFPB.",
dose_rapida:"1 cp/dia VO por 21 dias, pausa 7 dias, recomeçar nova cartela",
doses:[
{ind:"Contracepção (esquema clássico)", dose:"1 cp/dia, mesmo horário, 21 dias + 7 dias pausa", obs:"Iniciar 1º dia menstruação (proteção imediata) OU dia 5 (usar barreira 7 dias). Atraso ≤12h: continuar; >12h: usar barreira 7d."},
{ind:"Esquema estendido (suprimir menstruação)", dose:"3 cartelas seguidas + 7 dias pausa", obs:"Útil em dismenorreia, endometriose. Sem evidência de risco aumentado."},
{ind:"Acne moderada (off-label, mas reconhecido)", dose:"Padrão de uso contraceptivo", obs:"Melhora após 3-6 meses. Drospirenona+EE tem melhor efeito sobre acne."},
],
ajustes:{
irc:"Sem ajuste em DRC leve/moderada. Cautela na grave.",
iht:"CONTRAINDICAÇÃO em hepatopatia grave/colestase.",
idoso:"Em geral não indicado >50a / pós-menopausa.",
gestante:"CONTRAINDICAÇÃO ABSOLUTA. Categoria X.",
aleita:"CONTRAINDICAÇÃO RELATIVA — estrogênio reduz produção láctea. Aguardar 6 meses pós-parto OU usar progestágeno isolado.",
ped:"Adolescente: liberado após menarca, geralmente >14a com avaliação. Sem restrição absoluta de idade.",
},
mecanismo:"Etinilestradiol + progestágeno suprimem o eixo hipotálamo-hipófise-gonadal, inibindo a ovulação por bloqueio do pico de LH. Espessamento do muco cervical (efeito progestagênico) reduz penetração espermática. Modificação endometrial reduz nidação.",
farmacocin:{absorc:"VO completa", distrib:"Ampla; ligação albumina (EE) e SHBG (LNG)", metab:"Hepático CYP3A4", elimin:"Renal e biliar", meiavida:"EE 12-24h; LNG 24-32h", ligacao:"EE 97%; LNG 97%"},
espectro:["Contracepção","Regulação ciclo menstrual","Dismenorreia / endometriose","Acne moderada","SOP (regulação)","Tratamento sintomático mioma pequeno","Supressão menstrual (esquemas estendidos)"],
interacoes:[
{droga:"Rifampicina, rifabutina", efeito:"REDUZ MUITO eficácia. Trocar método. Vigência + 4 semanas após."},
{droga:"Anticonvulsivantes indutores (fenitoína, carbamazepina, fenobarbital, topiramato >200mg, oxcarbazepina)", efeito:"REDUZ eficácia. Considerar DIU ou injetável."},
{droga:"Lamotrigina", efeito:"ACO REDUZ níveis de lamotrigina (não o contrário). Pode descompensar epilepsia."},
{droga:"ATB betalactâmicos comuns (amoxicilina, etc)", efeito:"NÃO há evidência forte de redução de eficácia. Mito desfeito — pode usar."},
{droga:"Modafinil, bosentana", efeito:"REDUZ eficácia."},
{droga:"Inibidores de protease HIV", efeito:"Variável — consultar PCDT."},
],
efeitos:[
{tipo:"comum", item:"Náusea (1º mês), spotting intermenstrual, ganho peso modesto, mastalgia, alteração libido, cefaleia leve"},
{tipo:"sério", item:"TROMBOEMBOLISMO VENOSO (TVP/EP) — risco 3-5×, especialmente 1º ano + fumante + obesidade. AVE isquêmico em alto risco. Hipertensão"},
{tipo:"raro", item:"Adenoma hepático, hepatocarcinoma (uso muito prolongado), CA mama (risco discreto, regride após suspensão)"},
],
alertas:[
{nivel:"crit", txt:"TROMBOEMBOLISMO: risco AUMENTA com tabagismo + idade >35a (CONTRAINDICAÇÃO ABSOLUTA). Mulher >35a fumante NÃO usar ACO combinado — usar progestágeno isolado, DIU."},
{nivel:"crit", txt:"CONTRAINDICAÇÕES ABSOLUTAS (categoria 4 OMS): trombose prévia/atual, mutação trombofilica, IAM/AVE prévio, doença valvar complicada, CA mama atual, hepatopatia grave, enxaqueca COM AURA, gestação, lactação <6 sem, HAS grave (≥160/100), DM com complicações, lúpus com SAAF."},
{nivel:"warn", txt:"ENXAQUECA COM AURA + ACO combinado = AVE — categoria 4 OMS. Trocar para progestágeno isolado / DIU."},
{nivel:"warn", txt:"Hepatopatia ativa, colestase prévia gravídica: contraindicação."},
{nivel:"info", txt:"Pausa de 7 dias permite sangramento de privação. Esquema ESTENDIDO (3 cartelas sem pausa) é seguro e útil em dismenorreia/endometriose."},
{nivel:"info", txt:"Atraso até 12h: tomar e continuar. >12h: tomar + usar barreira 7d. >2 cps esquecidos: contracepção emergência se relação."},
],
preparo:"VO, mesmo horário diário.",
monitor:"PA anual, peso, sintomas de TVP. Reavaliar contraindicações periodicamente.",
diretriz:"OMS — Medical Eligibility Criteria for Contraceptive Use 2015. FEBRASGO — Manual de Anticoncepção. CDC US-MEC.",
fluxo:null, calcs:[],
},

{id:"med-desogestrel", contexto:["ubs"], classe:"Contraceptivo progestágeno isolado oral", grupo:"contraceptivo",
nome:"Desogestrel 75 mcg",
sin:["Cerazette","Nactali","Juliet"],
formas:["Comprimidos 75 mcg, cartela 28 — privada (alguns municípios via PFPB)"],
resumo:"Progestágeno isolado de USO CONTÍNUO, inibe ovulação em ~97% dos ciclos. Indicado em CONTRAINDICAÇÃO a estrogênio: lactante, fumante >35a, enxaqueca com aura, hipertensa, pós-bariátrica. Não tem pausa entre cartelas.",
dose_rapida:"1 cp/dia VO continuamente (sem pausa)",
doses:[
{ind:"Contracepção em mulher com contraindicação a estrogênio", dose:"1 cp/dia, 28 dias seguidos, sem pausa", obs:"Janela de atraso 12h (vs 3h da minipílula clássica). Início no 1º dia menstruação ou imediato pós-parto. Eficácia ~99% se uso correto."},
{ind:"Lactação (qualquer momento pós-parto)", dose:"1 cp/dia contínuo", obs:"Não interfere com lactação. Pode iniciar imediatamente pós-parto."},
{ind:"Endometriose (efeito sobre dor)", dose:"1 cp/dia contínuo", obs:"Efeito hipoestrogênico + amenorreia frequente — alivia dor."},
],
ajustes:{
irc:"Sem ajuste habitual.",
iht:"CONTRAINDICAÇÃO em hepatopatia ativa grave.",
idoso:"Pode usar até menopausa.",
gestante:"CONTRAINDICAÇÃO. Categoria X.",
aleita:"PERMITIDO — preferido em lactação.",
ped:"Pós-menarca.",
},
mecanismo:"Progestágeno potente — inibe pico de LH e ovulação em ~97% dos ciclos (mais que outros progestágenos isolados). Espessa muco cervical, atrofia endométrio. Não tem componente estrogênico — sem efeitos sobre coagulação, mama, pressão.",
farmacocin:{absorc:"VO 76%", distrib:"Ampla", metab:"Hepático (etonogestrel é metabólito ativo)", elimin:"Renal e biliar", meiavida:"~30h", ligacao:"96%"},
espectro:["Contracepção (lactante, >35a fumante, contraindicação ao estrogênio)","Endometriose (controle de dor)","Adenomiose","Sangramento uterino disfuncional"],
interacoes:[
{droga:"Rifampicina, anticonvulsivantes indutores", efeito:"REDUZ eficácia. Considerar DIU."},
{droga:"Antirretrovirais (alguns)", efeito:"Pode reduzir/aumentar — consultar PCDT."},
],
efeitos:[
{tipo:"comum", item:"Sangramento irregular (50% nos primeiros 3m), amenorreia (~20-50% após 6m), acne, mastalgia, alteração libido"},
{tipo:"sério", item:"Cisto funcional ovariano (raramente sintomático), depressão (raro)"},
{tipo:"raro", item:"Trombose (muito raro, sem associação clara com progestágeno isolado)"},
],
alertas:[
{nivel:"info", txt:"DIFERENTE DA MINIPÍLULA CLÁSSICA (noretisterona 0,35mg): desogestrel inibe OVULAÇÃO; minipílula clássica não. Por isso desogestrel tem janela de 12h vs 3h."},
{nivel:"info", txt:"Sangramento irregular é EFEITO ESPERADO e comum — orientar antes para evitar abandono. Padrão se estabiliza em 3-6m (frequentemente amenorreia)."},
{nivel:"warn", txt:"Contraindicações: gestação, CA mama atual, trombose ATIVA (relativa), hepatopatia grave, sangramento vaginal sem diagnóstico."},
{nivel:"info", txt:"Pós-parto: pode iniciar imediatamente, inclusive lactante. Pós-aborto: imediato. Após parar ACO combinado: iniciar no dia seguinte (sem pausa)."},
],
preparo:"VO, mesmo horário.",
monitor:"PA anual. Avaliar padrão menstrual em 3-6m.",
diretriz:"OMS MEC 2015. FEBRASGO — Manual de Anticoncepção. CDC US-MEC.",
fluxo:null, calcs:[],
},

{id:"med-noretisterona", contexto:["ubs"], classe:"Contraceptivo progestágeno isolado (minipílula)", grupo:"contraceptivo",
nome:"Noretisterona 0,35 mg",
sin:["Micronor","Norestin"],
formas:["Comprimidos 0,35 mg, cartela 35 — UBS (para lactantes)"],
resumo:"Minipílula clássica para LACTANTES. Não inibe ovulação consistentemente — eficácia depende de muco cervical e endométrio. Janela RÍGIDA de 3h (≠ desogestrel que tem 12h).",
dose_rapida:"1 cp/dia VO continuamente, MESMO horário (janela 3h)",
doses:[
{ind:"Contracepção em LACTANTE (gold standard de uso)", dose:"1 cp/dia contínuo, mesmo horário ±3h", obs:"Iniciar a partir da 6ª semana pós-parto. Eficácia muito boa em amenorreia lactacional. ATENÇÃO ao horário: tolerância só 3h."},
{ind:"Contracepção em não-lactante (alternativa quando desogestrel indisponível)", dose:"1 cp/dia", obs:"Eficácia inferior em mulher não-lactante — preferir desogestrel."},
],
ajustes:{
irc:"Sem ajuste habitual.",
iht:"Cautela em hepatopatia.",
idoso:"Indicação limitada (climatério).",
gestante:"Contraindicação.",
aleita:"PRINCIPAL indicação. Categoria preferida.",
ped:"Não rotineiro.",
},
mecanismo:"Progestágeno fraco — espessa muco cervical e altera endométrio. Inibe ovulação em apenas ~50% dos ciclos (vs 97% do desogestrel). Por isso eficácia depende muito da regularidade do uso.",
farmacocin:{absorc:"VO 60-80%", distrib:"Ampla", metab:"Hepático", elimin:"Renal e biliar", meiavida:"8h", ligacao:"80%"},
espectro:["Contracepção em lactante (1ª linha)","Contracepção em contraindicação ao estrogênio"],
interacoes:[{droga:"Indutores enzimáticos (rifampicina, anticonvulsivantes)", efeito:"REDUZ eficácia."}],
efeitos:[
{tipo:"comum", item:"Sangramento irregular, spotting, amenorreia, acne leve"},
{tipo:"sério", item:"Cisto funcional ovariano (raro)"},
],
alertas:[
{nivel:"warn", txt:"JANELA DE 3 HORAS — esquecimento >3h compromete eficácia. SE atraso: tomar + barreira por 48h. Janela RÍGIDA, diferente do desogestrel."},
{nivel:"info", txt:"Eficácia ÓTIMA em lactante (combinação com amenorreia lactacional). Em não-lactante: preferir desogestrel ou outro método."},
{nivel:"info", txt:"Início ideal: 6ª semana pós-parto. Sem pausa entre cartelas."},
],
preparo:"VO, MESMO horário.",
monitor:"Avaliar adesão ao horário em consultas.",
diretriz:"OMS MEC 2015. FEBRASGO — Anticoncepção em situações especiais.",
fluxo:null, calcs:[],
},

{id:"med-injetavel-mensal", contexto:["ubs"], classe:"Contraceptivo injetável combinado mensal", grupo:"contraceptivo",
nome:"Cipionato Estradiol + Algestona Acetofenida (injetável mensal)",
sin:["Mesigyna","Cyclofemina","Perlutan","Preg-Less"],
formas:["Ampola 1 mL IM: estradiol cipionato 5 mg + algestona acetofenida 75 mg — UBS"],
resumo:"Injetável MENSAL combinado (estrogênio + progestágeno). Eficácia >99% uso correto. Aplicação primeiros 5 dias do ciclo, depois mensal ±3 dias. Útil para baixa adesão a VO. Mesmas contraindicações do ACO combinado.",
dose_rapida:"1 ampola IM profunda a cada 30 dias ± 3 dias",
doses:[
{ind:"Contracepção mensal", dose:"1 amp IM (glúteo) a cada 30d ± 3d", obs:"1ª aplicação: dia 1-5 do ciclo. Próximas: contar 30 dias da 1ª, intervalo ±3d. Atraso >3d → barreira 7d. Eficácia >99%."},
],
ajustes:{
irc:"Cautela em DRC moderada/grave.",
iht:"CONTRAINDICAÇÃO em hepatopatia grave.",
idoso:"Não indicado pós-menopausa.",
gestante:"CONTRAINDICAÇÃO.",
aleita:"CONTRAINDICAÇÃO RELATIVA — estrogênio. Preferir progestágeno isolado.",
ped:"Pós-menarca.",
},
mecanismo:"Mesmo do ACO combinado: estradiol cipionato + algestona acetofenida liberados gradualmente IM, suprimem eixo HHO. Conveniência de aplicação mensal.",
farmacocin:{absorc:"IM — pico em 12-24h, manutenção 30 dias", distrib:"Ampla", metab:"Hepático", elimin:"Variável", meiavida:"Estradiol cipionato ~12d; algestona ~7d", ligacao:"Alta"},
espectro:["Contracepção em adesão irregular","Mulher que esquece pílula","Alternativa ao DIU em mulher que não quer DIU"],
interacoes:[{droga:"Mesmas do ACO combinado.", efeito:"—"}],
efeitos:[
{tipo:"comum", item:"Sangramento irregular inicial, ganho de peso, alteração de humor, mastalgia, cefaleia"},
{tipo:"sério", item:"TROMBOEMBOLISMO (similar ao ACO oral), hipertensão"},
],
alertas:[
{nivel:"warn", txt:"Mesmas contraindicações do ACO combinado (TEV, fumante >35a, enxaqueca com aura, etc.)."},
{nivel:"info", txt:"Aplicação IM PROFUNDA no glúteo. Não massagear pós-aplicação (libera mais rápido)."},
{nivel:"info", txt:"Atraso >3 dias: tomar normalmente + barreira 7d. Atraso >7 dias: contracepção emergência se relação prévia."},
],
preparo:"IM profunda, glúteo.",
monitor:"PA anual, peso.",
diretriz:"OMS MEC 2015. FEBRASGO — Manual de Anticoncepção.",
fluxo:null, calcs:[],
},

{id:"med-medroxiprog-depot", contexto:["ubs"], classe:"Contraceptivo injetável progestágeno trimestral", grupo:"contraceptivo",
nome:"Medroxiprogesterona Depot (injetável trimestral)",
sin:["Depo-Provera","Contracep","Tricilon"],
formas:["Ampola 150 mg/mL IM — UBS"],
resumo:"Injetável TRIMESTRAL de progestágeno isolado. Eficácia >99%. Útil em contraindicação a estrogênio + necessidade de longa duração + alta adesão. CUIDADO: efeitos sobre densidade óssea após uso prolongado (>2 anos).",
dose_rapida:"150 mg IM profunda a cada 12 semanas (3 meses)",
doses:[
{ind:"Contracepção (progestágeno isolado, longa duração)", dose:"150 mg IM glúteo ou deltoide a cada 90 dias ± 2 sem", obs:"1ª aplicação: até 5º dia do ciclo. Próximas: 90 dias. Eficácia rápida (24h). Atraso até 4 sem: pode aplicar; >4 sem: descartar gestação."},
{ind:"Endometriose (uso off-label)", dose:"Mesma dose", obs:"Supressão menstrual com alivio da dor. Amenorreia após 6-12m em maioria."},
],
ajustes:{
irc:"Sem ajuste.",
iht:"CONTRAINDICAÇÃO em hepatopatia ativa grave.",
idoso:"Não indicado pós-menopausa.",
gestante:"CONTRAINDICAÇÃO.",
aleita:"PERMITIDO — pode iniciar 6 semanas pós-parto.",
ped:"Pós-menarca. CUIDADO com densidade óssea em adolescente — discutir alternativas.",
},
mecanismo:"Progestágeno potente em depósito IM. Inibe ovulação efetivamente, espessa muco, atrofia endométrio. Hipoestrogenismo associado por supressão de FSH — efeito sobre osso.",
farmacocin:{absorc:"IM lenta", distrib:"Ampla", metab:"Hepático", elimin:"Renal e biliar", meiavida:"~50 dias", ligacao:"~90%"},
espectro:["Contracepção de longa duração","Endometriose","Anemia falciforme (reduz crises)","Epilepsia (alguns dados favoráveis)","Deficiência intelectual (cuidado de necessidades especiais)"],
interacoes:[{droga:"Indutores enzimáticos", efeito:"Não há redução significativa — vantagem em quem usa anticonvulsivantes."}],
efeitos:[
{tipo:"comum", item:"Sangramento irregular inicial + amenorreia (~50% em 1 ano), ganho de peso (~2-5 kg em 1 ano), atraso para retorno à fertilidade (até 6-12m após última dose), depressão (controverso), redução da densidade óssea"},
{tipo:"sério", item:"Osteoporose com uso prolongado (>2 anos) — REVERSÍVEL após suspensão"},
{tipo:"raro", item:"Trombose (raríssimo com progestágeno isolado)"},
],
alertas:[
{nivel:"warn", txt:"USO PROLONGADO (&gt;2 ANOS): reavaliar — densidade óssea reduz. Considerar alternativa em adolescente, em risco de osteoporose, em uso de corticoide crônico. Efeito é REVERSÍVEL após suspensão."},
{nivel:"info", txt:"Atraso para fertilidade pós-suspensão pode ser de 6-12 MESES (média ~10 meses). Orientar pacientes que querem gestar logo a usar OUTRO método."},
{nivel:"info", txt:"Sangramento irregular nos primeiros 3-6 meses é COMUM. Amenorreia final é o desfecho mais frequente — orientar antes."},
{nivel:"info", txt:"Excelente opção em mulher com contraindicação ao estrogênio + dificuldade de adesão diária. Pode iniciar imediato pós-parto se não lactando, ou após 6 semanas se lactando."},
],
preparo:"IM profunda, glúteo ou deltoide. Não massagear.",
monitor:"PA anual. Densidade óssea se uso >2-3 anos.",
diretriz:"OMS MEC 2015. FEBRASGO. CDC US-MEC.",
fluxo:null, calcs:[],
},

{id:"med-levonorgestrel-emergencia", contexto:["pa","ubs"], classe:"Contracepção de emergência", grupo:"contraceptivo",
nome:"Levonorgestrel 1,5 mg (Contracepção de Emergência)",
sin:["Postinor","Pilem","Pílula do dia seguinte"],
formas:["Comprimido 1,5 mg dose única OU 2 cp de 0,75 mg — UBS / drogaria"],
resumo:"Pílula do dia seguinte. Eficácia decai rapidamente com tempo: ~95% se em 24h, ~85% em 48h, ~58% em 72h. Pode usar até 5 dias mas eficácia mínima após 72h. NÃO é abortiva — atua impedindo/atrasando ovulação.",
dose_rapida:"1,5 mg VO dose única, o mais cedo possível, até 72h (idealmente)",
doses:[
{ind:"Contracepção de emergência após relação desprotegida", dose:"1,5 mg dose única (ou 2× 0,75 mg juntos)", obs:"Eficácia decai com tempo. Repetir se vômito em até 2h. Pode usar em ciclo já com método (falha de método). Próxima menstruação pode atrasar ~7 dias."},
],
ajustes:{
irc:"Sem ajuste.",
iht:"Cautela em hepatopatia grave.",
idoso:"Não aplicável.",
gestante:"Sem efeito sobre gestação já estabelecida (não é abortiva). Sem teratogenicidade comprovada.",
aleita:"PERMITIDO. Pode amamentar normalmente.",
ped:"Pós-menarca. Sem restrição de idade.",
},
mecanismo:"Progestágeno alta dose — inibe ou atrasa o PICO DE LH e a ovulação. Se a ovulação já ocorreu, eficácia é zero. Não impede implantação de óvulo já fecundado (NÃO é abortivo).",
farmacocin:{absorc:"VO rápida", distrib:"Ampla", metab:"Hepático", elimin:"Renal e biliar", meiavida:"~26h", ligacao:"~50%"},
espectro:["Contracepção pós-coital","Falha de método (rompimento camisinha, esquecimento ACO, agressão sexual)"],
interacoes:[{droga:"Indutores enzimáticos", efeito:"REDUZ eficácia. Considerar DIU de cobre como contracepção emergência alternativa (eficácia >99%)."}],
efeitos:[
{tipo:"comum", item:"Náusea, cefaleia, dor abdominal, fadiga, alteração do próximo ciclo (atraso 5-7d ou antecipação), sangramento irregular"},
{tipo:"sério", item:"Vômito (10%) — se em ≤2h da tomada, REPETIR dose"},
],
alertas:[
{nivel:"crit", txt:"<strong>NÃO É MÉTODO REGULAR.</strong> Eficácia de apenas ~85% mesmo nas melhores condições. Após uso, paciente deve iniciar/retomar método regular IMEDIATAMENTE."},
{nivel:"info", txt:"DIU DE COBRE em até 5 dias pós-relação = contracepção emergência MAIS EFICAZ (eficácia >99%) + contracepção contínua. Discutir como opção."},
{nivel:"info", txt:"Disponível GRATUITAMENTE em qualquer UBS, sem receita. Acesso garantido em casos de violência sexual."},
{nivel:"info", txt:"Pode usar várias vezes no mesmo ciclo se necessário, mas eficácia reduz e há mais efeitos. Não é abortiva nem teratogênica."},
],
preparo:"VO, com ou sem alimento.",
monitor:"Teste de gravidez se atraso menstrual >7 dias.",
diretriz:"OMS — Emergency Contraception. FEBRASGO. MS — Norma técnica de prevenção e tratamento dos agravos resultantes da violência sexual.",
fluxo:null, calcs:[],
},

/* ============== CLIMATÉRIO / TRH ============== */

{id:"med-estradiol-trh", contexto:["ubs"], classe:"Terapia hormonal — estrogênio sistêmico", grupo:"ginecologico",
nome:"Estradiol (TRH oral/transdérmica)",
sin:["Climaderm","Oestrogel","Estreva","Sistema TS"],
formas:["Oral 1 mg ou 2 mg (cps)","Gel transdérmico 0,06% (0,75 mg/dose)","Adesivo 25/50/75/100 mcg/d 7 dias","Spray transdérmico — privada (parcial PFPB algumas regiões)"],
resumo:"Estrogênio para TRH do climatério SINTOMÁTICO (ondas de calor, secura, sintomas vasomotores). USAR menor dose eficaz, menor tempo possível (<5 anos preferencial). Em mulher COM ÚTERO: associar progestágeno (proteção endometrial). Transdérmica preferível em risco TEV.",
dose_rapida:"Oral: 1 mg/d. Adesivo: 25-50 mcg/d. Gel: 0,75-1,5 mg/d. SEMPRE associar progestágeno se útero.",
doses:[
{ind:"Sintomas vasomotores moderados/graves no climatério (com útero)", dose:"Estradiol 1 mg VO/d (ou 25-50 mcg adesivo) + progestágeno 10-12 dias/mês (ou contínuo)", obs:"Sequencial: 14d só estrogênio + 14d combinada com progestágeno (gera sangramento). Contínuo: ambos diários (amenorreia)."},
{ind:"Sintomas vasomotores com HISTERECTOMIA prévia (sem útero)", dose:"Estradiol 1 mg/d sozinho", obs:"NÃO precisa progestágeno se útero ausente."},
{ind:"Atrofia urogenital isolada", dose:"Estriol vaginal (ver medicação específica)", obs:"Preferir tópico vaginal — efeito local sem risco sistêmico."},
{ind:"Insuficiência ovariana prematura (POI) <40a", dose:"2 mg VO/d (ou equivalente) até idade média da menopausa (~51a)", obs:"Reposição obrigatória — protege osso, coração, função sexual. Diferente da TRH de menopausa normal."},
],
ajustes:{
irc:"Sem ajuste habitual.",
iht:"CONTRAINDICAÇÃO em hepatopatia ativa.",
idoso:"NÃO INICIAR após 60a ou >10 anos pós-menopausa — risco CV supera benefício.",
gestante:"CONTRAINDICAÇÃO ABSOLUTA.",
aleita:"Suprime lactação — não usar.",
ped:"Não.",
},
mecanismo:"Repõe estrogênio circulante. Reduz secreção hipotalâmica de GnRH (negativa). Receptores estrogênicos em todo corpo: pele, mucosa, osso, vasos, SNC. Efeito vasomotor relacionado a termorregulação hipotalâmica.",
farmacocin:{absorc:"Oral 30-40% biodisponibilidade; transdérmica evita 1ª passagem hepática", distrib:"Ampla", metab:"Hepático (estriol, estrona)", elimin:"Renal", meiavida:"~24h", ligacao:"SHBG e albumina"},
espectro:["Sintomas vasomotores climatério","Atrofia urogenital","Prevenção osteoporose em alto risco (não 1ª linha)","Insuficiência ovariana prematura","Disfunção sexual relacionada à menopausa"],
interacoes:[
{droga:"Indutores enzimáticos (rifampicina, anticonvulsivantes)", efeito:"REDUZ níveis."},
{droga:"Anticoagulantes", efeito:"Pode reduzir eficácia da varfarina (interação complexa)."},
],
efeitos:[
{tipo:"comum", item:"Mastalgia, ganho peso modesto, retenção hídrica, náusea, cefaleia, sangramento vaginal (se sequencial)"},
{tipo:"sério", item:"TROMBOEMBOLISMO VENOSO (especialmente VO; transdérmico é mais seguro), AVE, CA mama (com uso prolongado >5 anos), CA endométrio se sem oposição progestagênica em útero, doença coronariana em início tardio"},
{tipo:"raro", item:"Adenoma hepático, colelitíase"},
],
alertas:[
{nivel:"crit", txt:"TRH NUNCA em mulher COM ÚTERO sem progestágeno associado — risco de CA endométrio aumenta 5-10x sem proteção."},
{nivel:"crit", txt:"CONTRAINDICAÇÕES ABSOLUTAS: CA mama, CA endométrio, sangramento vaginal não diagnosticado, hepatopatia ativa, TEV agudo, AVE/IAM recente, gestação."},
{nivel:"warn", txt:"INICIAR cedo (próximo da menopausa, &lt;60a, &lt;10 anos pós-menopausa) — janela de oportunidade. Iniciar TARDIO aumenta risco CV sem benefício."},
{nivel:"warn", txt:"Mama: discussão de risco no exame anual. Estudos sugerem ~1 caso adicional/1000 mulheres-ano após 5+ anos uso."},
{nivel:"info", txt:"Via TRANSDÉRMICA é PREFERÍVEL: não tem 1ª passagem hepática, menor risco TEV, menor efeito sobre triglicerides/SHBG. Usar em risco TEV moderado, dislipidemia, hipertrigliceridemia."},
{nivel:"info", txt:"MENOR DOSE EFICAZ pelo MENOR TEMPO necessário. Reavaliar a cada 1-2 anos."},
],
preparo:"VO com líquido; gel/spray em pele limpa, alternar locais.",
monitor:"PA, peso, mama anual (mamografia), exame ginecológico, sangramento.",
diretriz:"NAMS 2022 — Hormone Therapy Position Statement. FEBRASGO Manual de Climatério. SBEM — Diretrizes de TRH.",
fluxo:null, calcs:[],
},

{id:"med-estriol-vaginal", contexto:["ubs"], classe:"Estrogênio tópico vaginal — atrofia urogenital", grupo:"ginecologico",
nome:"Estriol vaginal",
sin:["Ovestrion","Premarin vaginal (estrogênios conjugados)"],
formas:["Creme vaginal 1 mg/g — privada (alguns PFPB)","Comprimidos vaginais"],
resumo:"Estrogênio fraco APENAS local — trata atrofia urogenital (secura vaginal, dispareunia, ITU recorrente) sem efeitos sistêmicos significativos. PRIMEIRA ESCOLHA para atrofia isolada. Pode ser usado em paciente com CA mama PRÉVIO (discussão individual).",
dose_rapida:"1 g creme intravaginal/noite × 2 sem; manutenção 1-2×/sem",
doses:[
{ind:"Atrofia vaginal sintomática (secura, dispareunia, irritação)", dose:"1 g creme intravaginal à noite × 2 semanas; depois 1 g 2×/semana", obs:"Resultado em 2-4 semanas. Manutenção indefinida se sintomas. Aplicar com aplicador ou dedo, idealmente à noite."},
{ind:"ITU recorrente pós-menopausa", dose:"Mesmo esquema", obs:"Atrofia urogenital favorece ITU — TRH local reduz recorrência em ~50%. Pode ser combinada com profilaxia ATB se necessário."},
{ind:"Sangramento por atrofia / dispareunia em parceria sexual", dose:"Mesmo esquema", obs:"Restaura epitélio."},
],
ajustes:{
irc:"Sem ajuste.",
iht:"Cautela em hepatopatia grave (absorção mínima mas existe).",
idoso:"Indicação principal. Sem limite de idade.",
gestante:"Não aplicável.",
aleita:"Não aplicável geralmente.",
ped:"Não.",
},
mecanismo:"Estriol é estrogênio fraco (~1/10 da potência do estradiol). Aplicado localmente: efeito restritivo na mucosa vaginal — restaura epitélio, pH, flora lactobacilar, lubrificação. Absorção sistêmica MÍNIMA (~5% do uso oral). Sem efeito significativo sobre endométrio em doses recomendadas.",
farmacocin:{absorc:"Local; sistêmica mínima", distrib:"Restrita", metab:"Hepático", elimin:"Renal", meiavida:"Curta", ligacao:"Alta"},
espectro:["Atrofia urogenital pós-menopausa","ITU recorrente em pós-menopausa","Dispareunia por atrofia","Vaginite atrófica"],
interacoes:[{droga:"Sistêmicas: mínimas pela baixa absorção", efeito:"—"}],
efeitos:[
{tipo:"comum", item:"Irritação local leve no início, secreção vaginal aumentada (efeito terapêutico)"},
{tipo:"raro", item:"Sangramento vaginal (geralmente reativação do epitélio), efeitos sistêmicos mínimos com doses padrão"},
],
alertas:[
{nivel:"info", txt:"<strong>PRIMEIRA ESCOLHA para atrofia ISOLADA</strong> — sem necessidade de progestágeno oposto, sem risco sistêmico significativo. Diferente da TRH sistêmica."},
{nivel:"info", txt:"Em paciente com CA mama prévio: USO É CONTROVERSO mas geralmente PERMITIDO em sintomas refratários. Discutir com mastologia. Absorção sistêmica é mínima."},
{nivel:"info", txt:"Não tem efeito sobre sintomas vasomotores (ondas de calor) — para isso é TRH sistêmica."},
{nivel:"warn", txt:"Sangramento vaginal pós-menopausa em paciente em uso: investigar (atrofia + ou outra causa)."},
],
preparo:"Aplicador intravaginal, deitada, à noite. Lavar mãos.",
monitor:"Avaliar sintomas em 4-6 semanas. Sangramento vaginal: investigar.",
diretriz:"NAMS 2022. FEBRASGO — Climatério. ISGE.",
fluxo:null, calcs:[],
},

{id:"med-tibolona", contexto:["ubs"], classe:"Esteroide sintético — atividade estrogênica + progestagênica + androgênica", grupo:"ginecologico",
nome:"Tibolona",
sin:["Livial","Riselle","Reduclim"],
formas:["Comprimidos 2,5 mg — privada"],
resumo:"Esteroide sintético com efeitos teciduais MISTOS (estrógeno na mama menos, no endométrio menos, no osso e cérebro mais) — alternativa à TRH convencional em mulher com útero (não precisa progestágeno separado). Não há sangramento sequencial.",
dose_rapida:"2,5 mg VO/d (única dose)",
doses:[
{ind:"Sintomas vasomotores climatério + atrofia (mulher pós-menopáusica >12m amenorreia)", dose:"2,5 mg VO 1×/d", obs:"Iniciar SÓ após 12m de amenorreia (senão sangramento irregular). Efeito sobre ondas em 4-8 semanas."},
{ind:"Prevenção osteoporose pós-menopausa (sintomática)", dose:"2,5 mg/d", obs:"Aumenta DMO. Em risco fratura: alendronato + cálcio + vit D são primeira linha."},
],
ajustes:{
irc:"Sem ajuste habitual.",
iht:"CONTRAINDICAÇÃO em hepatopatia grave.",
idoso:"Cautela após 60a — discussão risco/benefício.",
gestante:"CONTRAINDICAÇÃO.",
aleita:"CONTRAINDICAÇÃO.",
ped:"Não.",
},
mecanismo:"Metabolizada em 3 isômeros com perfis distintos: efeito estrogênico no osso e cérebro, progestagênico no endométrio (sem proliferação, sem sangramento), levemente androgênico (efeito sobre libido e humor).",
farmacocin:{absorc:"VO completa", distrib:"Ampla", metab:"Hepático extenso", elimin:"Fecal e renal", meiavida:"~45h", ligacao:"Alta"},
espectro:["Sintomas climatéricos vasomotores","Atrofia urogenital","Osteoporose pós-menopausa","Libido reduzida pós-menopausa (efeito androgênico)"],
interacoes:[{droga:"Anticoagulantes (varfarina)", efeito:"Pode reduzir efeito anticoagulante."}],
efeitos:[
{tipo:"comum", item:"Cefaleia, mastalgia, sangramento vaginal (especialmente se uso precoce — primeiros 12m pós-menopausa), ganho de peso modesto"},
{tipo:"sério", item:"AVE em mulheres >60a (estudo LIFT — uso para osteoporose), CA mama (controverso — alguns estudos sugerem aumento, outros redução), tromboembolismo"},
{tipo:"raro", item:"Hepatotoxicidade"},
],
alertas:[
{nivel:"crit", txt:"NÃO INICIAR em mulher com menos de 12 meses de amenorreia — risco de sangramento irregular e hiperplasia endometrial."},
{nivel:"crit", txt:"CONTRAINDICAÇÕES: CA mama (atual ou histórico), CA endométrio, AVE prévio, TEV ativo, sangramento vaginal não diagnosticado, hepatopatia grave."},
{nivel:"warn", txt:"Em >60a com osteoporose isolada: PREFERIR bisfosfonatos (alendronato/risedronato) — risco AVE da tibolona em idosas (LIFT trial)."},
{nivel:"info", txt:"Vantagem sobre TRH combinada: AMENORREIA (sem sangramento sequencial), efeito sobre libido por componente androgênico, dose única diária."},
],
preparo:"VO, mesmo horário.",
monitor:"PA, mama, sangramento vaginal.",
diretriz:"NAMS 2022. FEBRASGO — Climatério.",
fluxo:null, calcs:[],
},

/* ============== ONCOLÓGICOS GINECOLÓGICOS / SERM ============== */

{id:"med-tamoxifeno", contexto:["ubs"], classe:"SERM — modulador seletivo do receptor de estrogênio", grupo:"oncologico_endocrino",
nome:"Tamoxifeno",
sin:["Nolvadex","Tamoxin","Estrocur"],
formas:["Comprimidos 10 mg, 20 mg — UBS/SUS/CEAF (PCDT MS para CA mama receptor+)"],
resumo:"SERM clássico — antagonista estrogênico na MAMA + agonista em endométrio/osso. Tratamento adjuvante de CA mama receptor hormonal positivo + quimioprevenção em alto risco. Efeito por 5-10 anos. Risco de CA endométrio + TEV.",
dose_rapida:"20 mg VO 1×/d por 5 anos (estendido 10a em alto risco)",
doses:[
{ind:"Tratamento adjuvante CA mama RH+ (pré-menopausa)", dose:"20 mg VO 1×/d × 5 anos (estender a 10 anos em alto risco)", obs:"Padrão em mulher PRÉ-MENOPAUSA. Em pós-menopausa: inibidores de aromatase (anastrozol, letrozol) são preferíveis."},
{ind:"Quimioprevenção em mulher alto risco (BRCA, ATM/PALB2, hist familiar forte, CDIS, hiperplasia atípica)", dose:"20 mg VO/d × 5 anos", obs:"Decisão compartilhada — reduz CA mama em ~50% em mulheres de alto risco. Considerar trade-off com riscos."},
{ind:"Ginecomastia masculina por excesso de estrogênio", dose:"10-20 mg/d", obs:"Off-label mas usado. Reduz tamanho da glândula em 70% dos casos quando dor associada."},
],
ajustes:{
irc:"Sem ajuste habitual.",
iht:"Cautela em hepatopatia (metabolismo hepático).",
idoso:"Sem ajuste, monitorar TEV.",
gestante:"CONTRAINDICAÇÃO ABSOLUTA — teratogênico. Categoria D.",
aleita:"CONTRAINDICAÇÃO.",
ped:"Não rotineiro.",
},
mecanismo:"Liga ao receptor de estrogênio (RE) com efeito MISTO conforme tecido: ANTAGONISTA na mama (bloqueio efeito proliferativo do estrogênio), AGONISTA em endométrio (risco CA endométrio) e osso (efeito protetor). Metabolizado em endoxifeno (metabólito ativo principal) via CYP2D6.",
farmacocin:{absorc:"VO completa", distrib:"Ampla, atravessa BHE", metab:"Hepático CYP2D6 → endoxifeno", elimin:"Biliar e renal", meiavida:"~7 dias (endoxifeno ~14d)", ligacao:"99%"},
espectro:["CA mama receptor hormonal positivo (adjuvante)","Quimioprevenção CA mama em alto risco","CA mama metastático RH+","CDIS receptor hormonal positivo","Ginecomastia"],
interacoes:[
{droga:"Inibidores CYP2D6 fortes (paroxetina, fluoxetina, bupropiona)", efeito:"REDUZ formação de endoxifeno → REDUZ eficácia. EVITAR. Preferir sertralina, venlafaxina, escitalopram, citalopram."},
{droga:"Varfarina", efeito:"AUMENTA INR — monitorar."},
{droga:"Indutores CYP3A4", efeito:"Pode reduzir."},
],
efeitos:[
{tipo:"comum", item:"Sintomas climatéricos (ondas de calor, secura vaginal), náusea leve, fadiga, retenção hídrica, alteração menstrual em pré-menopausa"},
{tipo:"sério", item:"TROMBOEMBOLISMO VENOSO (TVP/EP — risco ~2-3x), CA endométrio (risco ~2-3x em pós-menopausa), AVE, catarata, esteatose hepática"},
{tipo:"raro", item:"Hepatite, leucopenia, alteração visual (retinopatia em altas doses)"},
],
alertas:[
{nivel:"crit", txt:"<strong>TEV (trombose):</strong> risco 2-3× — orientar paciente sobre sintomas (dor em panturrilha, dispneia súbita). Imobilização prolongada / cirurgia: considerar suspensão temporária (discutir com oncologia)."},
{nivel:"crit", txt:"<strong>CA ENDOMÉTRIO:</strong> risco aumentado em pós-menopáusicas. SANGRAMENTO VAGINAL PÓS-MENOPAUSA EM USO DE TAMOXIFENO = USG TV + biópsia/histeroscopia."},
{nivel:"warn", txt:"<strong>EVITAR ISRS POTENTES INIBIDORES CYP2D6</strong> (paroxetina, fluoxetina, bupropiona) — reduzem eficácia. Se necessário antidepressivo: sertralina, venlafaxina, escitalopram, citalopram OK."},
{nivel:"warn", txt:"GESTAÇÃO TERATOGÊNICA — orientar contracepção NÃO HORMONAL (DIU cobre preferível) durante uso e até 2 meses pós-suspensão. Mulher pré-menopausa em uso de tamoxifeno pode ter ovulação preservada."},
{nivel:"info", txt:"DURAÇÃO: 5 anos é padrão; 10 anos considerar em alto risco (ATLAS, aTTom trials). Decisão individualizada com oncologia."},
],
preparo:"VO, mesmo horário, com ou sem alimento.",
monitor:"Sangramento vaginal pós-menopausa, sintomas TEV, exame ginecológico anual, hemograma e função hepática periódica.",
diretriz:"PCDT MS — Carcinoma de Mama. NCCN Breast Cancer. ASCO Guidelines. PCDT específico no SUS define inclusão.",
fluxo:null, calcs:[],
},

/* ============== OBSTETRÍCIA ============== */

{id:"med-misoprostol", contexto:["pa","ubs"], classe:"Análogo PGE1 — uterotônico", grupo:"obstetrico",
nome:"Misoprostol",
sin:["Prostokos","Cytotec (uso hospitalar restrito Brasil)"],
formas:["Comprimidos 25, 100, 200 mcg — uso HOSPITALAR RESTRITO no Brasil (Portaria 344/98). Não dispensação ambulatorial."],
resumo:"Análogo PGE1 — contração uterina + maturação cervical. INDICAÇÕES TIGHTLY REGULADAS: indução de parto, abortamento incompleto/retido em ambiente hospitalar, hemorragia pós-parto, AVE/aborto medicamentoso (em situações legais). USO ESTRITAMENTE HOSPITALAR no Brasil.",
dose_rapida:"VARIA conforme indicação. SEMPRE em ambiente hospitalar.",
doses:[
{ind:"Indução de parto a termo (colo desfavorável)", dose:"25 mcg vaginal a cada 4-6h (máximo 6 doses)", obs:"PROTOCOLO HOSPITALAR. Monitoramento contínuo materno-fetal. NÃO ambulatorial."},
{ind:"Abortamento retido / incompleto (manejo medicamentoso hospitalar)", dose:"600 mcg sublingual ou 800 mcg vaginal × 1 dose", obs:"Hospitalar. ≤12 semanas. Em algumas situações em ambulatório de referência."},
{ind:"Hemorragia pós-parto (atonia uterina) — 2ª linha", dose:"800 mcg retal ou 600 mcg sublingual × 1 dose", obs:"Quando ocitocina + metilergometrina insuficientes. Pode ser usado quando ocitocina indisponível."},
{ind:"AVE medicamentoso em situações LEGAIS (estupro, risco vida materna, anencefalia)", dose:"Conforme protocolo MS / FEBRASGO", obs:"Centros de referência habilitados."},
],
ajustes:{
irc:"Sem ajuste habitual.",
iht:"Sem ajuste habitual.",
idoso:"Indicação rara.",
gestante:"USO ESPECÍFICO obstétrico, fora dele = CONTRAINDICAÇÃO (teratogênico — síndrome de Möbius).",
aleita:"Doses para hemorragia pós-parto: aceitável.",
ped:"Não.",
},
mecanismo:"Análogo da prostaglandina E1 — efeitos uterotônico (contração miometrial) + cervical (maturação por colagenólise). Doses pequenas induzem contração; doses maiores são abortivas.",
farmacocin:{absorc:"VO 88%, sublingual rápida, vaginal sustentada", distrib:"Ampla", metab:"Hepático", elimin:"Renal", meiavida:"30-60min (forma ácida)", ligacao:"~90%"},
espectro:["Indução parto","Abortamento medicamentoso (em situações legais)","Hemorragia pós-parto","Maturação cervical pré-procedimento","Úlcera induzida por AINE (indicação histórica, pouco usada)"],
interacoes:[{droga:"Ocitocina", efeito:"Efeito uterotônico aditivo. Espaçar 4h após misoprostol vaginal antes de ocitocina."}],
efeitos:[
{tipo:"comum", item:"Cólica, sangramento (intencional em indicações obstétricas), náusea, vômito, diarreia, calafrios, febre transitória"},
{tipo:"sério", item:"HIPERTONIA UTERINA com sofrimento fetal (em indução), RUPTURA UTERINA (especialmente em cesariana prévia), hemorragia"},
],
alertas:[
{nivel:"crit", txt:"<strong>USO ESTRITAMENTE HOSPITALAR NO BRASIL.</strong> Portaria 344/98 — Lista C1. Dispensação restrita a hospitais habilitados. NÃO prescrever para uso ambulatorial."},
{nivel:"crit", txt:"<strong>TERATOGÊNICO se usado em gestação que vai prosseguir</strong> — síndrome de Möbius (paralisia facial congênita, malformações de membros). NÃO usar em gestação que não será interrompida."},
{nivel:"crit", txt:"CESARIANA PRÉVIA + INDUÇÃO = RISCO DE RUPTURA UTERINA. Avaliar caso a caso, doses menores, monitoramento intensivo."},
{nivel:"info", txt:"Em situações legais de aborto (estupro, risco vida materna, anencefalia comprovada): Lei Federal protege. Encaminhar para centros de referência habilitados."},
{nivel:"info", txt:"Hemorragia pós-parto em ambiente sem ocitocina (rural, transporte): misoprostol pode salvar vida — orientação OMS para uso em emergência."},
],
preparo:"Conforme via: vaginal, sublingual, retal, oral. Hospitalar.",
monitor:"Contrações uterinas, BCF, sangramento, sinais vitais.",
diretriz:"OMS — Recomendações para indução do trabalho de parto. FEBRASGO. Manual MS — Gestação de Alto Risco. Portaria 344/98 (ANVISA).",
fluxo:null, calcs:[],
},

{id:"med-acido-tranexamico", contexto:["pa","ubs"], classe:"Antifibrinolítico — análogo da lisina", grupo:"hemostatico",
nome:"Ácido Tranexâmico",
sin:["Transamin","Hemoblock","Cyklokapron"],
formas:["Comprimidos 250 mg, 500 mg — UBS / PFPB","Solução oral","Ampola 50 mg/mL — hospitalar"],
resumo:"Antifibrinolítico — reduz sangramento por bloquear conversão plasminogênio→plasmina. USO AMPLO: sangramento uterino abundante, hemorragia pós-parto, trauma com sangramento, cirurgia, epistaxe. Eficaz, barato, perfil de segurança bom.",
dose_rapida:"VO 1 g 3-4×/d (sangramento menstrual abundante). IV 1 g lento + 1 g 8h (trauma/HPP).",
doses:[
{ind:"Sangramento Uterino Abundante (menorragia)", dose:"1 g VO 3-4×/d durante os dias do sangramento (max 5 dias/ciclo)", obs:"Reduz sangramento ~40-50%. Iniciar no 1º dia do ciclo. Não usa fora do sangramento. NÃO contraceptivo."},
{ind:"Hemorragia pós-parto (HPP) — CRASH-2 paradigm", dose:"1 g IV lento (10 min) + 1 g IV 30 min depois", obs:"Iniciar dentro das 3 PRIMEIRAS HORAS do parto. Reduz mortalidade por sangramento em HPP (estudo WOMAN, 2017). ENTRA NO BUNDLE DE HPP."},
{ind:"Trauma com sangramento ativo / risco hemorrágico", dose:"1 g IV em 10 min + 1 g IV em 8h", obs:"CRASH-2: iniciar nas 3 PRIMEIRAS HORAS pós-trauma. Reduz mortalidade por sangramento."},
{ind:"Sangramento dental, epistaxe recorrente, sangramento ENT", dose:"500 mg-1 g VO 3-4×/d × 3-7d ou tópico (compressa embebida)", obs:"Eficaz em hemofilia, anticoagulação."},
{ind:"Cirurgia eletiva com risco hemorrágico (ortopédica grande, cardíaca)", dose:"10-20 mg/kg IV pré-incisão", obs:"Reduz sangramento intra-op."},
],
ajustes:{
irc:"REDUZIR dose. TFG 50-80: 50% dose; 10-50: 25% dose; <10: 10% dose ou suspender.",
iht:"Sem ajuste habitual.",
idoso:"Cuidado com risco TEV em sedentária.",
gestante:"CATEGORIA B — usado em HPP. Não usar profilaticamente em gestante por TEV.",
aleita:"Compatível.",
ped:"Pode usar — doses específicas.",
},
mecanismo:"Bloqueia sítios de ligação de lisina no plasminogênio → não converte em plasmina → não degrada fibrina → coágulo estável. Antifibrinolítico clássico.",
farmacocin:{absorc:"VO 40-60%", distrib:"Pequeno volume", metab:"Mínimo", elimin:"Renal (predominante)", meiavida:"~2h", ligacao:"<10%"},
espectro:["Sangramento uterino anormal","Hemorragia pós-parto","Trauma hemorrágico","Sangramento dental, epistaxe","Cirurgia eletiva com risco","Hemofilia (adjuvante)","Anticoagulação revertida"],
interacoes:[
{droga:"ACO combinados, terapia hormonal estrogênica", efeito:"Risco TEV aditivo — usar com cautela em mulher com história prévia."},
{droga:"Complexo protrombínico, fator VIIa", efeito:"Risco trombótico aditivo."},
],
efeitos:[
{tipo:"comum", item:"Náusea, diarreia, cefaleia, alterações visuais transitórias"},
{tipo:"sério", item:"TROMBOEMBOLISMO (TVP, EP, AVE, IAM) — risco mais teórico que demonstrado em estudos randomizados; eventos raros mas possíveis"},
{tipo:"raro", item:"Convulsão (altas doses, especialmente neurocirurgia/cardiocirurgia), distúrbio visual"},
],
alertas:[
{nivel:"warn", txt:"<strong>CONTRAINDICAÇÕES:</strong> TEV ativo, AVE recente, sangramento subaracnóideo (controverso — em hemorragia subaracnóide pode usar), CIVD, hemorragia genitourinária superior alta (pode formar coágulo obstrutivo)."},
{nivel:"info", txt:"<strong>HEMORRAGIA PÓS-PARTO:</strong> incluir no bundle de manejo (compressão + ocitocina + misoprostol + ácido tranexâmico + RH se necessário). Iniciar nas 3h pós-parto (WOMAN trial)."},
{nivel:"info", txt:"<strong>SANGRAMENTO MENSTRUAL ABUNDANTE:</strong> 1g VO 3-4x/d nos dias do sangramento reduz fluxo ~40-50%. Não usar fora do sangramento. Não é contraceptivo."},
{nivel:"info", txt:"<strong>TRAUMA:</strong> CRASH-2 demonstrou redução de mortalidade. Iniciar nas 3 primeiras horas. Bundle de trauma."},
],
preparo:"VO com ou sem alimento. IV: 1g em 100 mL SF, infusão 10 min (não bolus rápido — pode dar hipotensão).",
monitor:"Sangramento, sinais de TEV, função renal.",
diretriz:"WOMAN trial — Lancet 2017. CRASH-2 — Lancet 2010. WHO recomendação 2017. PCDT MS — Trauma. FEBRASGO — Sangramento Uterino Anormal.",
fluxo:null, calcs:[],
},

/* ============== VULVOVAGINITES ============== */

{id:"med-clotrimazol-vaginal", contexto:["ubs"], classe:"Antifúngico imidazólico tópico vaginal", grupo:"antifungico_topico",
nome:"Clotrimazol vaginal",
sin:["Gino-Canesten","Gino-Gauz","Clotrimaderm"],
formas:["Creme vaginal 1% (~20 g) com aplicadores — PFPB / privada","Comprimido vaginal 100 mg / 500 mg"],
resumo:"Antifúngico imidazólico tópico — 1ª linha em candidíase vulvovaginal não-complicada. Eficácia ~80-90%. Vários esquemas posológicos. Acessível.",
dose_rapida:"Creme 1% intravaginal × 7 noites OU compr. 500 mg vaginal dose única",
doses:[
{ind:"Candidíase vulvovaginal não-complicada", dose:"Creme 1% 5g intravaginal à noite × 7 dias OU compr. 100 mg × 6 dias OU compr. 500 mg dose única", obs:"Eficácia equivalente. Aplicar à noite, deitada. Pode adicionar creme vulvar para alívio sintomático."},
{ind:"Candidíase recorrente (≥4 episódios/ano)", dose:"Indução: como acima por 14d; manutenção: compr. 500 mg vaginal semanal × 6 meses", obs:"Alternativa: fluconazol oral 150 mg semanal × 6m. Investigar causa subjacente (DM, imunossupressão, antibioticoterapia frequente)."},
],
ajustes:{
irc:"Sem ajuste (absorção mínima).",
iht:"Sem ajuste.",
idoso:"Sem ajuste.",
gestante:"PERMITIDO. Pode usar tópico vaginal 7 dias (preferir tópico ao oral na gestação).",
aleita:"Compatível.",
ped:"Não rotina.",
},
mecanismo:"Inibe síntese de ergosterol fungico (CYP450 fúngico) → membrana fúngica disfuncional → morte celular. Tópico = baixa absorção sistêmica.",
farmacocin:{absorc:"Mínima sistêmica", distrib:"Local", metab:"Local", elimin:"Local", meiavida:"Local", ligacao:"—"},
espectro:["Candida albicans","Outros Candida sp. (eficácia variável em C. glabrata, C. krusei)"],
interacoes:[{droga:"Mínimas pela via tópica", efeito:"—"}],
efeitos:[
{tipo:"comum", item:"Ardor/irritação local leve, prurido transitório, secreção vaginal aumentada"},
{tipo:"raro", item:"Reação alérgica local"},
],
alertas:[
{nivel:"info", txt:"Preferir TÓPICO em GESTANTE (oral fluconazol associado a defeitos com uso prolongado em altas doses)."},
{nivel:"info", txt:"Candidíase recorrente em paciente não-DM: investigar diabetes oculto, HIV, uso de corticoide, imunossupressão."},
{nivel:"info", txt:"NÃO tratar parceiro assintomático rotineiramente — candidíase não é IST. Tratar parceiro só se balanopostite sintomática."},
{nivel:"warn", txt:"Outras vulvovaginites: corrimento amarelo-esverdeado fétido + 'pH alterado' = TRICOMONÍASE (metronidazol oral). 'Cheiro de peixe' + secreção fina cinzenta = VAGINOSE BACTERIANA (metronidazol oral ou vaginal). Differential dx essencial."},
],
preparo:"Creme: aplicador intravaginal à noite. Comprimido: introdução vaginal profunda à noite. Deitada por 30 min após.",
monitor:"Resolução de sintomas em 7-14 dias.",
diretriz:"CDC STI Treatment Guidelines 2021. FEBRASGO — Vulvovaginites. PCDT MS — IST.",
fluxo:null, calcs:[],
},

{id:"med-metronidazol-vaginal", contexto:["ubs"], classe:"Antimicrobiano vaginal — nitroimidazol tópico", grupo:"vaginal_antibacteriano",
nome:"Metronidazol gel vaginal 0,75%",
sin:["Flagystatin (combinação)","Vagimid"],
formas:["Gel vaginal 0,75% (~40 g) com aplicador — privada/PFPB algumas regiões","Comprimidos vaginais 500 mg — combinações"],
resumo:"Metronidazol tópico para VAGINOSE BACTERIANA. Eficácia ~70-80%. Alternativa ao oral. Não trata tricomoníase (esta exige tratamento sistêmico).",
dose_rapida:"Gel 0,75% intravaginal 1×/d × 5 dias",
doses:[
{ind:"Vaginose bacteriana (Gardnerella vaginalis e anaeróbios)", dose:"5 g de gel intravaginal à noite × 5 dias", obs:"Alternativa: clindamicina creme vaginal 2% 5g × 7 noites. Ou metronidazol oral 500mg 2×/d × 7 dias."},
{ind:"Vaginose bacteriana recorrente", dose:"Indução padrão; manutenção 2x/sem × 4-6m", obs:"Recorrência comum. Considerar outras estratégias."},
],
ajustes:{
irc:"Sem ajuste (absorção mínima).",
iht:"Sem ajuste.",
idoso:"Sem ajuste.",
gestante:"PERMITIDO no 2º e 3º trimestres. 1º trimestre: cautela (uso oral em 1T é controverso — gel é mais aceito).",
aleita:"Tópico aceitável.",
ped:"Não rotina.",
},
mecanismo:"Pró-fármaco reduzido em anaeróbios → metabólitos nitro reagem com DNA bacteriano → quebra de DNA. Atividade contra anaeróbios estritos e protozoários (mas tópico tem menos absorção para tricomoníase sistêmica).",
farmacocin:{absorc:"Mínima sistêmica (~25% pela mucosa)", distrib:"Local", metab:"Hepático mínimo", elimin:"Renal", meiavida:"—", ligacao:"—"},
espectro:["Vaginose bacteriana (anaeróbios + Gardnerella)","NÃO trata Candida","NÃO trata adequadamente Trichomonas (precisa sistêmico)"],
interacoes:[{droga:"Mínimas pela via", efeito:"—"}],
efeitos:[
{tipo:"comum", item:"Ardor local, sabor metálico leve, secreção"},
{tipo:"raro", item:"Candidíase secundária ao tratamento"},
],
alertas:[
{nivel:"warn", txt:"<strong>NÃO TRATA TRICOMONÍASE</strong> adequadamente. Tricomoníase = metronidazol ORAL 2g dose única OU 500mg 2x/d × 7d + tratamento do parceiro."},
{nivel:"info", txt:"Vaginose bacteriana NÃO É IST mas há associação com sexo recente. NÃO tratar parceiro masculino rotineiramente — sem evidência de benefício."},
{nivel:"warn", txt:"Em GESTANTE com VB sintomática: TRATAR (associação com parto prematuro, RPMO). Tópico ou oral conforme PCDT."},
{nivel:"info", txt:"Evitar relação sexual durante tratamento (irritação). Não usar duchas vaginais."},
],
preparo:"Gel intravaginal à noite com aplicador.",
monitor:"Resolução em 1-2 semanas.",
diretriz:"CDC STI 2021. FEBRASGO — Vulvovaginites. PCDT MS.",
fluxo:null, calcs:[],
},

/* ============== SUPLEMENTAÇÃO GESTACIONAL ============== */

{id:"med-acido-folico-5mg", contexto:["ubs"], classe:"Vitamina hidrossolúvel — ácido fólico (B9)", grupo:"vitamina",
nome:"Ácido Fólico 5 mg",
sin:["Folacin","Endofolin"],
formas:["Comprimidos 5 mg — UBS / PFPB"],
resumo:"Suplementação para prevenção de defeitos do tubo neural (DTN) — espinha bífida, anencefalia. RECOMENDADO 1-3 MESES ANTES da concepção + até 12ª semana gestação. Dose padrão 0,4-0,8 mg; 5 mg em alto risco.",
dose_rapida:"Pré-concepção e gestação: 0,4-0,8 mg/d (mulher sem fator de risco) ou 5 mg/d (alto risco)",
doses:[
{ind:"Pré-concepção + gestação (rotina) — mulher sem fator de risco", dose:"0,4-0,8 mg VO/d", obs:"Iniciar IDEALMENTE 1-3 MESES antes de engravidar. Continuar até 12ª semana. CBAF tem 5 mg — adequado para pré-conceção, ajustar."},
{ind:"GESTANTE com FATORES DE RISCO para DTN", dose:"5 mg VO/d até 12ª semana", obs:"Alto risco: DTN prévio em filho/familiar, DM mal controlado, epilepsia em uso de ácido valproico/carbamazepina, anemia falciforme, IMC ≥35, obesidade mórbida, talassemia, alguns medicamentos antifolatos."},
{ind:"Anemia megaloblástica por deficiência de folato (não B12)", dose:"5 mg VO/d × 4 meses (reposição) + investigar causa", obs:"DESCARTAR DEFICIÊNCIA B12 ANTES — repor folato em deficiência de B12 melhora hemograma mas piora neuropatia. Dosar B12 sempre."},
{ind:"Hemoglobinopatias (anemia falciforme, talassemia) — alta demanda", dose:"5 mg VO/d contínuo", obs:"Hemólise crônica → aumento de demanda de folato. Suplementação contínua."},
],
ajustes:{
irc:"Sem ajuste.",
iht:"Sem ajuste.",
idoso:"Pode usar; lembrar de investigar B12 simultaneamente.",
gestante:"Indicação principal — SEGURO em qualquer dose.",
aleita:"Compatível.",
ped:"Pode usar em deficiências específicas.",
},
mecanismo:"Cofator essencial para síntese de purinas e timidina (DNA), conversão de homocisteína em metionina. Crítico para fechamento do tubo neural (entre 21-28 dias pós-concepção, ANTES da maioria saber que está grávida).",
farmacocin:{absorc:"VO ~50-90%", distrib:"Ampla, incluindo barreira placentária", metab:"Hepático", elimin:"Renal e biliar", meiavida:"~14h", ligacao:"~70%"},
espectro:["Prevenção DTN","Anemia megaloblástica por folato","Hemoglobinopatias","Suplementação em uso de antifolatos (metotrexato, anticonvulsivantes)"],
interacoes:[
{droga:"Metotrexato", efeito:"Folato REVERTE toxicidade (intencional). Suplementação 5 mg/sem em uso crônico de MTX."},
{droga:"Anticonvulsivantes (fenitoína, carbamazepina, valproato, fenobarbital)", efeito:"REDUZEM folato. Suplementar."},
{droga:"Trimetoprim (SMX-TMP)", efeito:"Inibe folato bacteriano. Em uso prolongado: considerar suplemento."},
{droga:"Levodopa", efeito:"Aumento absorção interfere com efeito. Discutir tempo de uso."},
],
efeitos:[
{tipo:"comum", item:"Náusea leve, alteração do sono (raro)"},
{tipo:"raro", item:"Reação alérgica"},
],
alertas:[
{nivel:"crit", txt:"<strong>DESCARTAR DEFICIÊNCIA DE B12 antes de prescrever ÁCIDO FÓLICO ISOLADO</strong> em paciente com anemia macrocítica/sintomas neurológicos. Folato corrige a anemia mas PIORA a neuropatia da deficiência de B12 (mascarando a doença até dano neurológico irreversível)."},
{nivel:"info", txt:"<strong>JANELA PRÉ-CONCEPCIONAL é CRÍTICA:</strong> tubo neural fecha em 21-28 dias pós-concepção. Mulher que descobre gestação na 6ª-8ª semana = janela PASSADA. Por isso a recomendação é EM TODA mulher em idade fértil planejando engravidar."},
{nivel:"info", txt:"Em CBAF temos apenas 5 mg — usar 1 cp/dia em alto risco; em rotina, fracionar (impraticável) ou usar dose 5 mg (não causa dano nessa dose)."},
{nivel:"info", txt:"FORTIFICAÇÃO da farinha de trigo e milho no Brasil (desde 2002, com folato) — contribui para redução de DTN populacional. Mas suplementação periconcepcional ainda recomendada."},
],
preparo:"VO, com ou sem alimento.",
monitor:"Hemograma se anemia. Em alto risco DTN: confirmar uso correto.",
diretriz:"WHO — Periconceptional Folate Supplementation. MS — Caderno Atenção Básica Pré-natal. FEBRASGO. SBP.",
fluxo:null, calcs:[],
}

);
