/* ===========================================================
   VOVÔMINIC DOUTÔ — meds/derm.js
   Dermatológicos tópicos / Tratamentos cutâneos
   Acne · Psoríase · Eczema · Escabiose · Antibacterianos tópicos · Queratose actínica
   =========================================================== */

MEDICACOES.push(

/* ============== IMUNOMODULADORES TÓPICOS (eczema, dermatite atópica) ============== */

{id:"med-tacrolimo-topico", contexto:["ubs"], classe:"Imunomodulador tópico — inibidor calcineurina", grupo:"imunomodulador_topico",
nome:"Tacrolimo tópico (pomada)",
sin:["Protopic","Tacroz"],
formas:["Pomada 0,03% e 0,1% (tubos 10g/30g) — privada (CEAF em alguns estados para indicações específicas)"],
resumo:"Imunomodulador tópico NÃO-ESTEROIDAL para dermatite atópica moderada/grave. POUPA córtex/áreas sensíveis (face, pálpebras, pregas) onde corticoide tópico tem mais efeitos adversos. Sem atrofia cutânea, sem estrias.",
dose_rapida:"Aplicar fina camada nas lesões 2×/d até clareamento; depois 2-3×/sem (manutenção)",
doses:[
{ind:"Dermatite atópica MODERADA/GRAVE em ADULTO (>16a)", dose:"Tacrolimo 0,1% pomada 2×/d nas lesões, fina camada", obs:"Não em pele lesada/erodida grave. Pode causar ardência inicial — passa em ~1 semana. Após controle: passar a manutenção 2-3×/sem nas áreas problema."},
{ind:"Dermatite atópica em CRIANÇA (2-16a)", dose:"Tacrolimo 0,03% pomada 2×/d", obs:"Concentração reduzida em criança. Mesmo esquema."},
{ind:"Tratamento PROATIVO (manutenção)", dose:"Tacrolimo 0,03% ou 0,1% 2-3×/sem nas áreas frequentes de surto", obs:"Reduz frequência de surtos. Esquema reconhecido em diretrizes europeias e brasileiras."},
{ind:"Vitiligo (off-label, áreas de face)", dose:"0,1% 2×/d", obs:"Off-label mas usado em vitiligo segmentar de face com algum benefício."},
],
ajustes:{
irc:"Sistêmico mínimo — sem ajuste.",
iht:"Mínimo.",
idoso:"Sem ajuste.",
gestante:"Categoria C — dados limitados, evitar uso extenso. Pequenas áreas: aceitável.",
aleita:"Evitar áreas mamárias.",
ped:">2 anos: 0,03%.",
},
mecanismo:"Inibe calcineurina no linfócito T → bloqueia produção de IL-2 e outras citocinas inflamatórias na pele. Não causa atrofia (vs corticoide).",
farmacocin:{absorc:"Mínima pela pele íntegra", distrib:"Local", metab:"Local", elimin:"Local", meiavida:"—", ligacao:"—"},
espectro:["Dermatite atópica","Eczema crônico de mão","Dermatite seborreica facial refratária","Vitiligo facial/segmentar (off-label)"],
interacoes:[{droga:"Sistêmicas: mínimas pela via", efeito:"—"}],
efeitos:[
{tipo:"comum", item:"Ardência/queimor na aplicação (primeira semana, depois melhora), prurido transitório, eritema, flushing com álcool (raro)"},
{tipo:"raro", item:"Infecção cutânea local (impetigo, herpes simples) — interrompido se ativa, foliculite"},
],
alertas:[
{nivel:"info", txt:"<strong>NÃO É CORTICOIDE</strong> — sem atrofia, estrias, telangiectasias. Útil em áreas sensíveis (face, pálpebras, pregas, genitais) onde corticoide tópico é problemático."},
{nivel:"info", txt:"<strong>ARDÊNCIA INICIAL:</strong> efeito comum (até 50%) — passa em ~1 semana. Não suspender. Aplicar em pele seca, pequenas quantidades."},
{nivel:"warn", txt:"<strong>EVITAR FOTOEXPOSIÇÃO INTENSA</strong> durante uso — pode aumentar risco teórico de fotoenvelhecimento/CA pele com uso prolongado em áreas expostas. Fotoproteção rigorosa."},
{nivel:"info", txt:"FDA tem 'black box warning' sobre risco teórico de linfoma — em uso TÓPICO em humanos NÃO há evidência forte. Estudos epidemiológicos não confirmam. Usar com critério em criança."},
{nivel:"warn", txt:"NÃO usar em pele com infecção ativa (bacteriana, viral, fúngica) — pode agravar. Tratar infecção primeiro."},
],
preparo:"Aplicar fina camada com mãos limpas. Não cobrir com curativo oclusivo.",
monitor:"Resposta clínica em 1-2 semanas.",
diretriz:"SBD — Consenso Brasileiro de Dermatite Atópica. ETFAD/AAD Eczema Guidelines.",
fluxo:null, calcs:[],
},

{id:"med-pimecrolimo-topico", contexto:["ubs"], classe:"Imunomodulador tópico — inibidor calcineurina", grupo:"imunomodulador_topico",
nome:"Pimecrolimo tópico (creme)",
sin:["Elidel"],
formas:["Creme 1% (tubos 15g/30g/60g) — privada"],
resumo:"Similar ao tacrolimo, mais leve (creme não pomada — melhor aceitação). Indicado em dermatite atópica LEVE-MODERADA. Útil em face e dobras.",
dose_rapida:"Aplicar 2×/d nas lesões",
doses:[
{ind:"Dermatite atópica leve a moderada (>2 anos)", dose:"Creme 1% — fina camada 2×/d nas lesões", obs:"Mais cosmeticamente aceitável (creme), bom para face. Eficácia ligeiramente inferior ao tacrolimo 0,1% em grave."},
],
ajustes:{
irc:"Sistêmico mínimo.",
iht:"Mínimo.",
idoso:"OK.",
gestante:"Categoria C — pequenas áreas aceitável.",
aleita:"Evitar mama.",
ped:">2 anos.",
},
mecanismo:"Mesmo do tacrolimo — inibidor de calcineurina. Pimecrolimo tem distribuição mais cutânea, menor absorção sistêmica.",
farmacocin:{absorc:"Mínima", distrib:"Local", metab:"Local", elimin:"—", meiavida:"—", ligacao:"—"},
espectro:["Dermatite atópica leve-moderada","Eczema facial","Dermatite seborreica"],
interacoes:[{droga:"Mínimas", efeito:"—"}],
efeitos:[{tipo:"comum", item:"Ardência leve, eritema transitório"}, {tipo:"raro", item:"Foliculite, infecção secundária"}],
alertas:[
{nivel:"info", txt:"Pimecrolimo é versão CREME (mais cosmeticamente aceitável que pomada de tacrolimo). Útil em face, pescoço, áreas visíveis."},
{nivel:"info", txt:"Mesma 'black box warning' da FDA — sem evidência clínica de aumento de risco."},
],
preparo:"Fina camada, mãos limpas.",
monitor:"Resposta clínica.",
diretriz:"SBD. AAD Eczema Guidelines.",
fluxo:null, calcs:[],
},

/* ============== ACNE ============== */

{id:"med-adapaleno", contexto:["ubs"], classe:"Retinoide tópico — 3ª geração", grupo:"antiacne_topico",
nome:"Adapaleno",
sin:["Differin","Adaclene","Epiduo (combinado com peróxido benzoíla)"],
formas:["Gel/creme 0,1% (tubos 15-30g) — PFPB / privada","Gel 0,3% (mais potente, prescrição)","Combinado: adapaleno 0,1% + peróxido benzoíla 2,5% — Epiduo"],
resumo:"Retinoide tópico de 3ª geração para acne LEVE-MODERADA. Comedolítico + anti-inflamatório. Tolerância melhor que tretinoína. Disponível em PFPB algumas regiões.",
dose_rapida:"Aplicar fina camada à noite após limpeza, em pele seca, 1×/d",
doses:[
{ind:"Acne vulgar leve a moderada (comedoniana, papulopustulosa)", dose:"Gel 0,1% — fina camada NOITE × indefinida (até estabilização)", obs:"Iniciar com aplicação a cada 2 dias por 1-2 semanas, depois diária. Esperar 4-8 semanas para resposta significativa. Manutenção indefinida."},
{ind:"Manutenção após tratamento ativo", dose:"Mesmo esquema noturno", obs:"Para PREVENIR recidiva. Acne é doença crônica — tratamento prolongado."},
],
ajustes:{
irc:"Sistêmico mínimo.",
iht:"Mínimo.",
idoso:"Raramente indicado.",
gestante:"CATEGORIA C — evitar (retinoides têm associação teórica com teratogenicidade — adapaleno tem absorção mínima mas evita-se por precaução).",
aleita:"Evitar área mamária.",
ped:">12 anos: liberado. Pré-puberal: dermatologia avalia.",
},
mecanismo:"Modula diferenciação queratinócitos via receptores do ácido retinoico (RAR-β, γ) → previne formação de microcomedões + reduz inflamação.",
farmacocin:{absorc:"Mínima sistêmica (<0,25%)", distrib:"Local", metab:"Local", elimin:"—", meiavida:"—", ligacao:"—"},
espectro:["Acne vulgar","Hiperpigmentação pós-inflamatória","Rosácea (off-label, com cautela)"],
interacoes:[{droga:"Outros tópicos irritantes simultâneos", efeito:"Aditiva. Espaçar uso (ex: peróxido manhã + adapaleno noite)."}],
efeitos:[
{tipo:"comum", item:"Ardência inicial, descamação, eritema, ressecamento (especialmente primeiras 2-4 semanas)"},
{tipo:"raro", item:"Hiperpigmentação ou hipopigmentação transitória"},
],
alertas:[
{nivel:"info", txt:"<strong>EFEITO DEMORA</strong> — resposta significativa apenas em 4-8 semanas. Persistência é essencial. Paciente pode achar que 'piorou' inicialmente — explicar."},
{nivel:"warn", txt:"<strong>FOTOSSENSIBILIDADE.</strong> Aplicar à NOITE. Fotoproteção rigorosa durante uso (FPS ≥30, idealmente 50)."},
{nivel:"info", txt:"INICIAR com aplicação a cada 2 dias por 1-2 semanas para reduzir irritação."},
{nivel:"info", txt:"Acne é doença crônica. Educar paciente: tratamento PROLONGADO + cuidados de pele permanentes. Tratamento NÃO é estética — é doença inflamatória."},
{nivel:"warn", txt:"Evitar em gestante por precaução."},
],
preparo:"Pele LAVADA e SECA. Fina camada. Não esfregar.",
monitor:"Resposta clínica em 4-8 semanas. Pele em geral.",
diretriz:"SBD — Consenso Acne. AAD Acne Guidelines.",
fluxo:null, calcs:[],
},

{id:"med-tretinoina-topica", contexto:["ubs"], classe:"Retinoide tópico — 1ª geração", grupo:"antiacne_topico",
nome:"Tretinoína tópica",
sin:["Vitanol-A","Vitanol-A Plus","Retin-A","Renova"],
formas:["Creme/gel 0,025%, 0,05%, 0,1% — privada / PFPB algumas regiões"],
resumo:"Retinoide tópico 1ª geração — comedolítico potente. Mais irritante que adapaleno. Usado em acne e fotoenvelhecimento. Aplicação NOTURNA.",
dose_rapida:"Aplicar fina camada à noite em pele seca, iniciar 0,025% 3×/sem",
doses:[
{ind:"Acne vulgar (comedoniana, papulopustulosa)", dose:"0,025% noite 3×/sem inicialmente, progredir para diário; subir concentração se tolerado", obs:"Iniciar baixa concentração + frequência reduzida → escalar conforme tolerância."},
{ind:"Fotoenvelhecimento / rugas finas / discromias", dose:"0,025-0,05% noturno × meses-anos", obs:"Estudos comprovam melhora de rugas finas, hiperpigmentação solar. Uso prolongado. Sempre com fotoproteção rigorosa."},
{ind:"Queratose actínica (off-label, isolado tem pouco poder — combinação)", dose:"0,1% + outros agentes", obs:"5-fluoruracila tópica é mais usado em QA."},
],
ajustes:{
irc:"Mínimo.",
iht:"Mínimo.",
idoso:"Mais sensível à irritação.",
gestante:"CATEGORIA C — EVITAR retinoides tópicos em gestante por precaução (apesar de absorção baixa).",
aleita:"Evitar mama.",
ped:">12 anos.",
},
mecanismo:"Liga RAR (receptor de ácido retinoico) — modula transcrição gênica → diferenciação queratinócitos, redução inflamação, neocolagênese (anti-aging).",
farmacocin:{absorc:"Sistêmica mínima", distrib:"Local", metab:"Local", elimin:"—", meiavida:"—", ligacao:"—"},
espectro:["Acne","Fotoenvelhecimento","Hiperpigmentação pós-inflamatória"],
interacoes:[{droga:"Outros tópicos irritantes", efeito:"Aditiva."}],
efeitos:[
{tipo:"comum", item:"Irritação MAIS PRONUNCIADA que adapaleno: eritema, descamação, ressecamento, ardência. 'Retinização' nas 2-6 primeiras semanas."},
{tipo:"raro", item:"Hiperpigmentação"},
],
alertas:[
{nivel:"warn", txt:"<strong>MAIS IRRITANTE</strong> que adapaleno. Iniciar baixa concentração (0,025%) + frequência reduzida (3×/sem). Subir gradualmente."},
{nivel:"warn", txt:"<strong>FOTOSSENSIBILIDADE</strong> — uso NOTURNO + fotoprotetor diário rigoroso."},
{nivel:"crit", txt:"<strong>EVITAR EM GESTAÇÃO</strong> — embora absorção sistêmica seja mínima, recomendação geral é evitar retinoides tópicos."},
{nivel:"info", txt:"Pode causar 'PURGING' (piora inicial da acne) nas 2-4 primeiras semanas — efeito esperado, persistir."},
],
preparo:"Pele SECA (esperar 15-20 min após lavar). Fina camada. Noturna.",
monitor:"Resposta em 8-12 semanas.",
diretriz:"SBD — Consenso Acne. AAD.",
fluxo:null, calcs:[],
},

{id:"med-peroxido-benzoila", contexto:["ubs"], classe:"Antimicrobiano tópico — peróxido", grupo:"antiacne_topico",
nome:"Peróxido de Benzoíla",
sin:["Benzac","Brevoxyl","Oxipoll","Epiduo (combinado adapaleno)"],
formas:["Gel/creme 2,5%, 5%, 10% — PFPB / privada","Combinado com clindamicina 1%","Combinado com adapaleno 0,1% (Epiduo)"],
resumo:"Antimicrobiano tópico contra C. acnes (antigo P. acnes). Sem resistência bacteriana. 1ª LINHA em acne inflamatória. Pode causar irritação + clareamento de tecidos/cabelo.",
dose_rapida:"Gel 2,5% ou 5% aplicar 1-2×/d nas lesões",
doses:[
{ind:"Acne vulgar inflamatória", dose:"Gel 2,5-5% — aplicar 1-2×/d nas lesões após limpeza", obs:"Iniciar 2,5% (eficaz e menos irritante que 5-10%). Aplicação em todo o rosto se acne difusa, em lesões se localizada."},
{ind:"Combinação com retinoide (Epiduo) ou ATB tópico", dose:"1×/d à noite (Epiduo) ou matinal", obs:"Peróxido + adapaleno = sinérgico. Peróxido + clindamicina = previne resistência da clindamicina."},
],
ajustes:{
irc:"Sistêmico mínimo.",
iht:"Mínimo.",
idoso:"Sem ajuste.",
gestante:"CATEGORIA C — uso em pequenas áreas é aceitável.",
aleita:"Evitar mama.",
ped:">12 anos.",
},
mecanismo:"Libera radicais livres de oxigênio → bactericida contra C. acnes + comedolítico + anti-inflamatório. Sem resistência bacteriana (mecanismo inespecífico).",
farmacocin:{absorc:"~5%", distrib:"Local", metab:"Local", elimin:"—", meiavida:"—", ligacao:"—"},
espectro:["C. acnes","Acne inflamatória"],
interacoes:[{droga:"Tetraciclinas tópicas, tretinoína (mesmo horário)", efeito:"Pode oxidar/inativar — espaçar."}],
efeitos:[
{tipo:"comum", item:"Eritema, descamação, ardência, ressecamento. CLAREAMENTO DE TECIDOS (toalhas, roupas, cabelo, sobrancelhas)"},
{tipo:"raro", item:"Reação alérgica de contato"},
],
alertas:[
{nivel:"warn", txt:"<strong>CLAREIA TECIDOS</strong> — toalhas, fronhas, roupas, cabelo (se contato). Orientar paciente: usar toalha branca durante tratamento."},
{nivel:"info", txt:"<strong>COMBINAR COM RETINOIDE</strong> (adapaleno ou tretinoína à noite + peróxido manhã) — esquema sinérgico padrão de tratamento de acne moderada."},
{nivel:"info", txt:"PEROXIDO + ATB tópico (clindamicina, eritromicina) PREVINE RESISTÊNCIA ao ATB. Combinações são preferenciais."},
{nivel:"info", txt:"Iniciar 2,5% — mesma eficácia + menos irritação que 5-10%."},
],
preparo:"Pele lavada e seca.",
monitor:"Resposta em 4-8 semanas.",
diretriz:"SBD. AAD.",
fluxo:null, calcs:[],
},

{id:"med-clindamicina-topica", contexto:["ubs"], classe:"Antibiótico tópico — lincosamida", grupo:"antiacne_topico",
nome:"Clindamicina tópica",
sin:["Dalacin T","Clindoxyl ADG (combinada com peróxido)"],
formas:["Solução/gel 1% — privada/PFPB","Combinada com peróxido benzoíla 5% — clindoxyl"],
resumo:"Antibiótico tópico para acne inflamatória. SEMPRE em combinação com peróxido de benzoíla ou retinoide para PREVENIR RESISTÊNCIA bacteriana. Não usar como monoterapia.",
dose_rapida:"Aplicar 1-2×/d nas lesões — sempre combinado",
doses:[
{ind:"Acne inflamatória moderada", dose:"1% gel/solução 2×/d nas lesões, EM COMBINAÇÃO com peróxido de benzoíla ou retinoide", obs:"Monoterapia gera resistência rapidamente. Não usar mais de 3 meses sem reavaliar."},
],
ajustes:{
irc:"Mínimo.",
iht:"Mínimo.",
idoso:"Sem ajuste.",
gestante:"Categoria B — aceitável em áreas pequenas.",
aleita:"Evitar mama.",
ped:">12 anos.",
},
mecanismo:"Inibe síntese proteica bacteriana (subunidade 50S do ribossomo). Reduz C. acnes + ação anti-inflamatória.",
farmacocin:{absorc:"<10%", distrib:"Local", metab:"Local", elimin:"—", meiavida:"—", ligacao:"—"},
espectro:["C. acnes","Estafilococos cutâneos","Estreptococos"],
interacoes:[{droga:"Outros tópicos irritantes", efeito:"Aditiva."}],
efeitos:[
{tipo:"comum", item:"Ardência leve, ressecamento, descamação"},
{tipo:"raro", item:"Colite pseudomembranosa (raríssima por via tópica — absorção baixa), reação alérgica"},
],
alertas:[
{nivel:"crit", txt:"<strong>NUNCA EM MONOTERAPIA</strong> — resistência bacteriana se desenvolve rapidamente. SEMPRE combinar com peróxido de benzoíla (que previne resistência) ou retinoide."},
{nivel:"info", txt:"Limitar uso a 3 meses; reavaliar."},
],
preparo:"Pele limpa.",
monitor:"Resposta. Não prolongar além de 3 meses.",
diretriz:"SBD — Consenso Acne. AAD.",
fluxo:null, calcs:[],
},

/* ============== PSORÍASE ============== */

{id:"med-calcipotriol", contexto:["ubs"], classe:"Análogo vitamina D tópico", grupo:"antipsoriase_topico",
nome:"Calcipotriol",
sin:["Daivonex","Daivobet (combinado com betametasona)"],
formas:["Pomada/creme 50 mcg/g — privada","Combinação calcipotriol + betametasona dipropionato — Daivobet"],
resumo:"Análogo vitamina D3 — efeito antiproliferativo + diferenciador queratinócitos em psoríase em placa. 1ª linha para psoríase leve a moderada localizada. Combinado com corticoide tópico aumenta eficácia.",
dose_rapida:"Aplicar fina camada 2×/d nas placas (máx 100g/sem)",
doses:[
{ind:"Psoríase em placa leve-moderada", dose:"50 mcg/g — aplicar fina camada 2×/d nas placas", obs:"Resposta em 4-8 semanas. Máximo 100 g/semana. Não usar em face (irritação) nem dobras."},
{ind:"Psoríase moderada (combinado com betametasona) — Daivobet", dose:"1×/d × 4 sem (intensivo); depois 1×/d 2-3×/sem (manutenção)", obs:"Combinação mais eficaz que monoterapias. Esquema padrão de manutenção."},
],
ajustes:{
irc:"Sistêmico mínimo se uso restrito; cautela em DRC grave (hipercalcemia teórica em uso extenso).",
iht:"Mínimo.",
idoso:"OK.",
gestante:"Categoria C — uso em pequenas áreas aceitável.",
aleita:"Evitar mama.",
ped:">6 anos: pode usar conforme orientação dermatológica.",
},
mecanismo:"Análogo da 1,25-OH-vit D3 — liga receptores VDR nos queratinócitos → reduz proliferação + induz diferenciação + modula inflamação local.",
farmacocin:{absorc:"~6% (pele lesionada)", distrib:"Local", metab:"Hepático", elimin:"Biliar", meiavida:"—", ligacao:"—"},
espectro:["Psoríase em placa"],
interacoes:[{droga:"Calcêmicos sistêmicos", efeito:"Cuidado teórico em uso extenso."}],
efeitos:[
{tipo:"comum", item:"Irritação cutânea local, ardência (especialmente face/dobras — EVITAR), ressecamento"},
{tipo:"raro", item:"Hipercalcemia (uso extenso >100 g/sem ou em pele com grande perda de barreira), foliculite"},
],
alertas:[
{nivel:"warn", txt:"<strong>NÃO usar em FACE ou DOBRAS</strong> — risco de irritação significativa. Estes locais: corticoide tópico leve ou inibidores de calcineurina."},
{nivel:"warn", txt:"Limite: 100 g/semana — uso excessivo pode causar hipercalcemia."},
{nivel:"info", txt:"Combinação com corticoide tópico (Daivobet) é mais eficaz e tem perfil de tolerância melhor. Esquema preferido em psoríase localizada moderada."},
],
preparo:"Aplicar fina camada nas placas.",
monitor:"Resposta clínica. Sintomas hipercalcemia se uso extenso.",
diretriz:"SBD — Consenso Psoríase. AAD/NPF Psoriasis Guidelines.",
fluxo:null, calcs:[],
},

/* ============== ESCABIOSE ============== */

{id:"med-permetrina-creme", contexto:["pa","ubs"], classe:"Escabicida / pediculicida — piretroide", grupo:"antiparasita_topico",
nome:"Permetrina 5% creme",
sin:["Permetrina","Kwell-K","Scabin","Stiefel"],
formas:["Creme 5% (tubo 30 g) — UBS / PFPB"],
resumo:"1ª LINHA para escabiose (sarna humana). Eficácia ~90%. Aplicação noturna de corpo inteiro (do pescoço para baixo). Tratar contactantes simultaneamente.",
dose_rapida:"Aplicar corpo inteiro à noite, deixar 8-14h, lavar; repetir após 7-14 dias",
doses:[
{ind:"Escabiose (Sarcoptes scabiei)", dose:"Aplicar creme 5% em TODO O CORPO da nuca para baixo (incluindo unhas, pregas, genitais) ANTES de dormir; lavar pela manhã (8-14h depois). REPETIR em 7-14 dias.", obs:"Aplicação minuciosa: dobras, entre dedos, sob unhas, área genital. EM CRIANÇA <2a: cabeça também. TRATAR contactantes íntimos simultaneamente. Lavar roupas/lençóis em água quente OU isolar 72h."},
{ind:"Pediculose (piolho de cabeça)", dose:"Permetrina 1% (loção/shampoo) é versão para piolho — aplicar 10 min, repetir 7-10d", obs:"Versão 5% é para escabiose; 1% para piolho — diferentes formulações."},
],
ajustes:{
irc:"Mínimo.",
iht:"Mínimo.",
idoso:"OK.",
gestante:"Categoria B — escolha em gestação.",
aleita:"Permitido.",
ped:">2 meses: indicado.",
},
mecanismo:"Piretroide — bloqueia canais de sódio dos neurônios do parasita → paralisia + morte.",
farmacocin:{absorc:"<2%", distrib:"Pele", metab:"Local + hepático mínimo", elimin:"Renal/fecal", meiavida:"—", ligacao:"—"},
espectro:["Sarcoptes scabiei","Pediculus humanus","Phthirus pubis"],
interacoes:[{droga:"Mínimas", efeito:"—"}],
efeitos:[
{tipo:"comum", item:"Prurido transitório (escabiose pode persistir 2-4 semanas APÓS cura — efeito imune residual, NÃO indica falha de tratamento), ardência leve, eritema"},
{tipo:"raro", item:"Hipersensibilidade"},
],
alertas:[
{nivel:"crit", txt:"<strong>PRURIDO APÓS TRATAMENTO ≠ FALHA</strong>. Prurido persiste 2-4 SEMANAS após cura (resposta imune residual). Tratar SINTOMÁTICO com anti-histamínico. NÃO repetir permetrina precocemente."},
{nivel:"warn", txt:"<strong>TRATAR CONTACTANTES</strong> íntimos simultaneamente (mesmo assintomáticos — período de incubação 4-6 sem). Lavar TODA roupa de cama e roupas usadas em 72h em água quente OU isolar 72h sem contato."},
{nivel:"info", txt:"Aplicação MINUCIOSA: dobras (cotovelo, joelho, axila), entre dedos, sob unhas, área genital, mamária, umbigo. Em <2a: incluir couro cabeludo."},
{nivel:"info", txt:"REPETIR em 7-14 dias para pegar ciclo de ovos não-eclodidos."},
{nivel:"warn", txt:"Em escabiose CROSTOSA (Norueguesa) — imunossuprimidos, internados: ivermectina oral 200 mcg/kg + permetrina tópica. Doença altamente transmissível em surto institucional."},
],
preparo:"Banho prévio. Pele seca. Aplicar generosamente em todo corpo (40g em adulto). Vestir roupas leves para dormir.",
monitor:"Resposta em 1-2 semanas (lesões); prurido pode persistir 2-4 sem.",
diretriz:"PCDT MS — Escabiose. CDC Treatment Guidelines.",
fluxo:null, calcs:[],
},

/* ============== ANTIBACTERIANOS TÓPICOS ============== */

{id:"med-mupirocina", contexto:["pa","ubs"], classe:"Antibacteriano tópico — derivado ácido pseudomônico", grupo:"antibiotico_topico",
nome:"Mupirocina",
sin:["Bactroban","Bactermac","Plasimine"],
formas:["Pomada 2% (tubo 15 g) — PFPB / privada"],
resumo:"Antibacteriano tópico — 1ª linha em impetigo, foliculite. Cobertura S. aureus (incluindo MRSA) e Streptococcus. Descolonização nasal de MRSA.",
dose_rapida:"Aplicar fina camada 3×/d × 5-10 dias",
doses:[
{ind:"Impetigo (não-bolhoso/bolhoso) — lesões localizadas", dose:"Aplicar 3×/d × 5-10 dias", obs:"Indicação para impetigo localizado (poucas lesões). Em impetigo extenso, múltiplo, ou bolhoso com sintomas sistêmicos: ATB oral (cefalexina, amoxicilina + clavulanato)."},
{ind:"Foliculite superficial", dose:"3×/d × 5-7d", obs:"Em foliculite extensa ou refratária: ATB oral."},
{ind:"Descolonização nasal de MRSA / S. aureus (pré-cirurgia, recorrente)", dose:"Aplicação intranasal 2×/d × 5 dias", obs:"Indicação em cirurgia cardíaca/ortopédica de grande porte + colonização nasal documentada."},
{ind:"Profilaxia secundária em furunculose recorrente", dose:"5 dias/mês intranasal", obs:"Junto com banhos com antisséptico."},
],
ajustes:{
irc:"Mínimo.",
iht:"Mínimo.",
idoso:"OK.",
gestante:"Categoria B.",
aleita:"OK.",
ped:">2 meses.",
},
mecanismo:"Inibe isoleucil-tRNA sintetase bacteriana → bloqueia síntese proteica. Mecanismo único — pouca resistência cruzada com outras classes.",
farmacocin:{absorc:"Mínima", distrib:"Local", metab:"Local", elimin:"—", meiavida:"—", ligacao:"—"},
espectro:["S. aureus (incluindo MRSA)","Streptococcus pyogenes","Outros gram-positivos cutâneos"],
interacoes:[{droga:"Mínimas", efeito:"—"}],
efeitos:[{tipo:"comum", item:"Ardência leve, prurido"}, {tipo:"raro", item:"Eczema de contato"}],
alertas:[
{nivel:"info", txt:"Excelente atividade contra MRSA cutâneo — eficácia mantida onde clindamicina/eritromicina já falha."},
{nivel:"warn", txt:"Não usar mais que 10-14 dias — risco de resistência."},
{nivel:"info", txt:"Lesões EXTENSAS, FEBRE, comprometimento sistêmico: ATB oral, não tópico."},
],
preparo:"Lavar lesão (água + sabão) antes. Fina camada.",
monitor:"Resposta em 3-7 dias.",
diretriz:"SBD. CDC SSTI Guidelines. IDSA SSTI Guidelines.",
fluxo:null, calcs:[],
},

{id:"med-acido-fusidico", contexto:["ubs"], classe:"Antibacteriano tópico — esteroide antibacteriano", grupo:"antibiotico_topico",
nome:"Ácido Fusídico (tópico)",
sin:["Verutex","Fucidin"],
formas:["Creme 2% (tubo 15 g) — privada","Combinado com hidrocortisona (Fucidin-H)","Combinado com betametasona"],
resumo:"Antibacteriano tópico contra estafilococos cutâneos. Alternativa à mupirocina em impetigo. Combinações com corticoide úteis em dermatite atópica infectada.",
dose_rapida:"Aplicar 2-3×/d × 5-10 dias",
doses:[
{ind:"Infecções cutâneas estafilocócicas leves localizadas", dose:"Aplicar 2-3×/d × 5-10 dias", obs:"Impetigo, foliculite, erisipela leve."},
{ind:"Dermatite atópica infectada (Fucidin-H)", dose:"2-3×/d × 7-10d", obs:"Combinação ATB + corticoide para dermatite com infecção bacteriana secundária. Não usar prolongadamente."},
],
ajustes:{
irc:"Mínimo.",
iht:"Mínimo.",
idoso:"OK.",
gestante:"Categoria B.",
aleita:"OK.",
ped:"OK.",
},
mecanismo:"Inibe síntese proteica bacteriana (fator G ribossômico) — bactericida especialmente contra S. aureus.",
farmacocin:{absorc:"Mínima", distrib:"Local", metab:"—", elimin:"—", meiavida:"—", ligacao:"—"},
espectro:["S. aureus (sensível e resistente)","Estreptococos"],
interacoes:[{droga:"Mínimas", efeito:"—"}],
efeitos:[{tipo:"comum", item:"Ardência leve, eritema"}, {tipo:"raro", item:"Reação alérgica"}],
alertas:[
{nivel:"info", txt:"Alternativa à mupirocina em impetigo. Não usar prolongadamente (resistência)."},
{nivel:"warn", txt:"Combinação com corticoide: limitar a 1-2 semanas para evitar atrofia."},
],
preparo:"Lavar antes. Fina camada.",
monitor:"Resposta em 3-7 dias.",
diretriz:"SBD.",
fluxo:null, calcs:[],
},

/* ============== ANTITUMORAIS TÓPICOS (queratose actínica, CBC superficial, verrugas) ============== */

{id:"med-imiquimode", contexto:["ubs"], classe:"Imunomodulador tópico — agonista TLR7", grupo:"antitumoral_topico",
nome:"Imiquimode",
sin:["Aldara","Imuxen"],
formas:["Creme 5% — saches uso único — privada"],
resumo:"Imunomodulador tópico — ativa imunidade local. Indicado em CONDILOMA ACUMINADO, CBC SUPERFICIAL, queratose actínica. Reação inflamatória local INTENSA é esperada e parte do efeito.",
dose_rapida:"3-5×/semana à noite, conforme indicação. Aplicação prolongada (semanas a meses).",
doses:[
{ind:"Condiloma acuminado (verrugas genitais externas)", dose:"3×/sem (segunda/quarta/sexta) à noite × até 16 semanas ou clareamento", obs:"Lavar pela manhã. Pode causar erosão/úlcera local — pausar se intolerável."},
{ind:"Carcinoma basocelular SUPERFICIAL (apenas — não nodular/esclerodermiforme)", dose:"5×/sem × 6 semanas (atualmente: dermatologia define)", obs:"Apenas em CBC SUPERFICIAL diagnóstico histológico. Lesões pequenas, baixo risco. Resposta cosmética melhor que cirurgia. Dermatologia avalia."},
{ind:"Queratose actínica em campo (face, couro cabeludo)", dose:"3×/sem × 4 semanas, pausa 4 sem, repetir", obs:"Excelente para campo de cancerização — múltiplas lesões e área."},
],
ajustes:{
irc:"Mínimo.",
iht:"Mínimo.",
idoso:"Indicação frequente (queratose actínica, CBC superficial).",
gestante:"Categoria C — evitar.",
aleita:"Evitar.",
ped:">12 anos.",
},
mecanismo:"Agonista do Toll-like Receptor 7 (TLR7) — ativa imunidade inata local + adaptativa. Recrutamento de células T citotóxicas. Pode induzir clareamento de lesões virais e tumorais superficiais.",
farmacocin:{absorc:"~9%", distrib:"Local + sistêmica mínima", metab:"Hepático", elimin:"Renal", meiavida:"—", ligacao:"—"},
espectro:["HPV (condiloma)","CBC superficial","Queratose actínica","Doença de Bowen (CEC in situ)"],
interacoes:[{droga:"Mínimas", efeito:"—"}],
efeitos:[
{tipo:"comum", item:"REAÇÃO INFLAMATÓRIA LOCAL INTENSA (eritema, edema, erosão, descamação, prurido, dor, escabosidade) — é EFEITO DESEJADO, não complicação. Sintomas sistêmicos gripais leves (~30%)"},
{tipo:"sério", item:"Reação inflamatória grave com ulceração extensa, infecção secundária, despigmentação"},
],
alertas:[
{nivel:"warn", txt:"<strong>REAÇÃO LOCAL INTENSA É ESPERADA E DESEJADA</strong> — eritema, erosão, crosta. Sinaliza ativação imune. NÃO suspender por isso. Se intolerável: pausa de alguns dias, reduzir frequência."},
{nivel:"info", txt:"<strong>FOLLOW-UP RIGOROSO</strong> em CBC tratado com imiquimode — biópsia para confirmar resposta completa em 3-6 meses. Recidivas possíveis."},
{nivel:"warn", txt:"NÃO usar em CBC nodular/morfeiforme — apenas SUPERFICIAL. Em CEC invasivo ou melanoma: NÃO usar."},
{nivel:"info", txt:"Em condiloma extenso: combinação com criocautério/eletrocautério acelera resposta."},
],
preparo:"Aplicação à noite, deixar 6-10h, lavar pela manhã.",
monitor:"Resposta clínica e histológica (em CBC).",
diretriz:"SBD — Consenso CBC. NCCN Skin Cancer Guidelines. EADV.",
fluxo:null, calcs:[],
},

{id:"med-fluoruracila-topica", contexto:["ubs"], classe:"Antimetabólito tópico — análogo pirimidina", grupo:"antitumoral_topico",
nome:"Fluoruracila 5% tópica (5-FU)",
sin:["Efurix","Fluoroplex"],
formas:["Creme 5% — privada"],
resumo:"Antimetabólito tópico — 1ª linha em queratose actínica (campo de cancerização) e doença de Bowen. Reação inflamatória local intensa é esperada.",
dose_rapida:"2×/d × 2-4 semanas",
doses:[
{ind:"Queratose actínica (face, couro cabeludo) — campo", dose:"5% creme 1-2×/d × 2-4 semanas", obs:"Iniciar com aplicação 1×/d, escalar para 2×/d. Resposta CLÍNICA: eritema → erosão → crosta → descamação → resolução. Pode reaparecer — repetir após 6-12m."},
{ind:"Doença de Bowen (CEC in situ)", dose:"2×/d × 4-8 semanas", obs:"Indicação restrita; dermatologia avalia."},
{ind:"CBC superficial pequeno", dose:"2×/d × 6-12 semanas", obs:"Diagnóstico histológico prévio. Alternativa à cirurgia em lesões pequenas, baixo risco, áreas cosmeticamente sensíveis."},
],
ajustes:{
irc:"Mínimo (absorção <10%).",
iht:"Mínimo.",
idoso:"Indicação frequente.",
gestante:"CATEGORIA X — CONTRAINDICAÇÃO em gestante (teratogenicidade do 5-FU sistêmico, absorção mínima mas precaução).",
aleita:"Evitar.",
ped:"Não usado em criança.",
},
mecanismo:"Antimetabólito — análogo da pirimidina. Inibe timidilato sintetase → bloqueia síntese DNA. Atua em células com alta proliferação (atípicas).",
farmacocin:{absorc:"~6% tópica", distrib:"Local", metab:"Hepático sistêmico", elimin:"—", meiavida:"—", ligacao:"—"},
espectro:["Queratose actínica","Doença de Bowen","CBC superficial","Verruga vulgar refratária (off-label)"],
interacoes:[{droga:"Sistêmicas: mínimas pela via", efeito:"—"}],
efeitos:[
{tipo:"comum", item:"INFLAMAÇÃO LOCAL INTENSA (eritema, erosão, ulceração, crosta, ardência, prurido) — efeito DESEJADO. Sintomas sistêmicos raros."},
{tipo:"sério", item:"Reação inflamatória grave em pacientes com deficiência de DPD (dihidropirimidina desidrogenase) — absorção sistêmica mínima geralmente não causa toxicidade sistêmica significativa, mas teste de DPD pode ser relevante em uso extenso"},
],
alertas:[
{nivel:"warn", txt:"<strong>REAÇÃO INTENSA ESPERADA E DESEJADA</strong> — paciente vai 'piorar' antes de 'melhorar'. Eritema → erosão → crosta → cura. Avisar antes."},
{nivel:"warn", txt:"DOR LOCAL pode ser significativa — analgesia + emolientes leves AS NOITES quando não aplicar."},
{nivel:"crit", txt:"GESTANTE: CONTRAINDICAÇÃO."},
{nivel:"info", txt:"Excelente para CAMPO DE CANCERIZAÇÃO em face/couro cabeludo de pacientes idosos com múltiplas QAs. Trata lesões clínicas E sub-clínicas. Imiquimode é alternativa."},
],
preparo:"Aplicar com luva ou cotonete (não pegar com mão nua). Pele seca. Não cobrir.",
monitor:"Reação inflamatória esperada. Suspender se intolerável + retomar após pausa. Avaliar clareamento em 2-4 semanas após fim de tratamento.",
diretriz:"SBD. NCCN. EADV. AAD AK Guidelines.",
fluxo:null, calcs:[],
}

);
