/* ===========================================================
   VOVÔMINIC EMERGÊNCIA — BIBLIOTECA DE MEDICAÇÕES (PARTE 14)
   Bloco E Rodada 3 — Antibióticos / Cefalosporinas
   Cefalexina, Cefazolina, Cefuroxima, Ceftriaxona, Cefepima (menção)
   =========================================================== */

MEDICACOES.push(

/* ============== CEFALEXINA (1ª GERAÇÃO ORAL) ============== */

{id:"med-cefalexina", classe:"β-lactâmico — cefalosporina 1ª geração ORAL", grupo:"atb",
nome:"Cefalexina",
sin:["Keflex","Keforal","Cefalexin"],
formas:["Cápsula 500 mg","Suspensão oral 250 mg/5 mL","REMUME — UBS dispensação direta + PFPB"],
resumo:"⚠ ESPECTRO: G+ (S. aureus β-lac+ não MRSA, Strep, S. pyogenes) + G- LIMITADOS (E. coli ambulatorial, P. mirabilis, Klebsiella). PEGA BEM EM: PELE E PARTES MOLES (erisipela, celulite, foliculite, impetigo, abscesso pequeno após drenagem), ITU não complicada, mastite, profilaxia cirúrgica (substituível por cefazolina IV). NÃO PEGA: anaeróbios, MRSA, Pseudomonas, Listeria, enterococo. ⚠ CEFALOSPORINA DE 1ª GERAÇÃO TEM A MELHOR COBERTURA G+ DE TODA A CLASSE.",
dose_rapida:"500 mg VO 6/6h × 7-10d (adulto); 25-100 mg/kg/d ÷ 6/6h (criança)",
doses:[
{ind:"⚠ Erisipela / celulite não complicada (sem MRSA)", dose:"500 mg VO 6/6h × 7-10 dias", obs:"1ª LINHA. Cobertura Strep + S. aureus. Em MRSA suspeito (abscesso purulento, IV drug user, surto): SMX-TMP ou clindamicina."},
{ind:"Foliculite / furunculose pequena", dose:"500 mg VO 6/6h × 5-7 dias", obs:"+ drenagem se abscesso."},
{ind:"Impetigo (extenso ou bolhoso)", dose:"250-500 mg VO 6/6h × 7 dias (adulto); 25-50 mg/kg/d (criança)", obs:"Lesões localizadas: mupirocina tópica é suficiente."},
{ind:"ITU não complicada cistite", dose:"500 mg VO 6/6h × 5-7 dias", obs:"⚠ Alternativa quando nitrofurantoína / SMX-TMP / fosfomicina não indicados (alergia, falência). Pielonefrite ambulatorial: 1 g 6/6h × 10-14d."},
{ind:"Mastite puerperal", dose:"500 mg VO 6/6h × 10-14 dias", obs:"S. aureus é o agente principal. Manter aleitamento. Em MRSA: SMX-TMP ou clindamicina."},
{ind:"Profilaxia em paciente com prótese valvar / endocardite — procedimento dentário (alergia a amoxicilina)", dose:"2 g VO dose única 1h antes (adulto); 50 mg/kg criança", obs:"Apenas em pacientes de ALTO risco. Não fazer profilaxia rotineira."},
{ind:"Infecção de ferida cirúrgica leve / pós-operatória", dose:"500 mg VO 6/6h × 5-7 dias", obs:""},
{ind:"Dermohipodermite leve sem complicação", dose:"500 mg VO 6/6h × 7 dias", obs:""},
],
ajustes:{
irc:"TFG 10-50: 500 mg 8-12/12h. TFG <10: 500 mg 24/24h. Hemodiálise: pós.",
iht:"Sem ajuste",
idoso:"Sem ajuste se função renal normal",
gestante:"B",
aleita:"Compatível",
ped:"25-100 mg/kg/d ÷ 6/6h. Pele: 50 mg/kg/d.",
},
mecanismo:"β-LACTÂMICO — inibe síntese de parede (PBPs) → bacteriólise. Mais estável a β-lactamases gram-positivas (S. aureus produtores) que penicilinas. Cobertura G+ AMPLA, G- limitada.",
farmacocin:{
absorc:"VO 90% (excelente)",
distrib:"Ampla — POUCO penetra SNC (não usar em meningite)",
metab:"Mínimo",
elimin:"Renal (>80% inalterada)",
meiavida:"~1h",
ligacao:"~14%",
},
ef_colats:{
comuns:["Diarreia","Náusea","Candidíase","Rash maculopapular"],
sérios:["Anafilaxia","Stevens-Johnson","Colite por C. difficile","Eosinofilia, neutropenia (raro)"],
},
interacoes:["Probenecida: ↑ nível","Anticoagulantes: ↑ INR possível","Metformina: pode ↑ nível"],
contraindicacoes:["⚠ Alergia conhecida a cefalosporinas","⚠ Alergia a penicilinas com reação ANAFILÁTICA prévia (risco cruzado ~1-5%; em alergia mediada por IgE, EVITAR)"],
monit:["Hipersensibilidade","Função renal em uso prolongado"],
gravidez:"B",
sus:"⚠ REMUME — UBS dispensação direta + PFPB.",
referencias:["IDSA Skin and Soft Tissue 2014","Sanford","Diretriz Brasileira"],
},

/* ============== CEFAZOLINA (1ª GERAÇÃO IV) ============== */

{id:"med-cefazolina", classe:"β-lactâmico — cefalosporina 1ª geração IV/IM", grupo:"atb",
nome:"Cefazolina",
sin:["Kefazol","Ancef"],
formas:["Frasco-ampola 1 g IV/IM","⚠ Uso predominantemente hospitalar e perioperatório. UBS pode ter para uso interno emergencial / ferida grave"],
resumo:"⚠ ESPECTRO: similar à cefalexina (G+ amplo, G- limitado), mas IV/IM. PEGA BEM EM: PROFILAXIA CIRÚRGICA (1ª linha em maioria das cirurgias limpas), pielonefrite, celulite grave, endocardite por S. aureus sensível (alternativa). USO CENTRAL: profilaxia cirúrgica — 1 g IV 30-60 min antes da incisão.",
dose_rapida:"1-2 g IV/IM 8/8h (tratamento); 1-2 g 30-60 min pré-cirurgia (profilaxia)",
doses:[
{ind:"⚠ Profilaxia cirúrgica (cirurgia limpa)", dose:"1-2 g IV 30-60 min antes da incisão; redose intraoperatória se >4h ou >1.500 mL sangramento", obs:"⚠ 1ª LINHA em maioria das cirurgias limpas (ortopédica, cardiotorácica, vascular, herniária, ginecológica). Dose 2 g se >120 kg. Pediátrica: 30 mg/kg."},
{ind:"Celulite / erisipela grave hospitalar", dose:"1-2 g IV 8/8h × 7-10 dias (transição para VO quando estável)", obs:""},
{ind:"Pielonefrite hospitalar adulto", dose:"1-2 g IV 8/8h × 10-14 dias", obs:"Alternativa a ceftriaxona em ITU complicada."},
{ind:"Bacteremia / endocardite por MSSA (S. aureus sensível meticilina)", dose:"2 g IV 8/8h (endocardite); 4-6 semanas", obs:"⚠ É a 1ª LINHA EM ENDOCARDITE POR MSSA — superior a vancomicina."},
{ind:"Infecção de ferida cirúrgica moderada-grave", dose:"1-2 g IV 8/8h × 5-10 dias", obs:""},
],
ajustes:{
irc:"TFG 10-50: 1-2 g 12/12h. TFG <10: 0,5-1 g 24/24h. Hemodiálise: pós-sessão.",
iht:"Sem ajuste",
idoso:"Sem ajuste se TFG normal",
gestante:"B",
aleita:"Compatível",
ped:"50-100 mg/kg/d ÷ 6-8/8h",
},
mecanismo:"Inibe PBPs → bactericida. Vantagem em profilaxia: vida média 1,5h, atinge boa concentração tecidual em 30 min.",
farmacocin:{
absorc:"IV/IM (não VO)",
distrib:"Ampla — não SNC",
metab:"Mínimo",
elimin:"Renal (>80%)",
meiavida:"~1,5-2h",
ligacao:"~80%",
},
ef_colats:{
comuns:["Tromboflebite local","Rash","Diarreia"],
sérios:["Anafilaxia","Stevens-Johnson","Colite C. difficile","Eosinofilia"],
},
interacoes:["Probenecida","Anticoagulantes (varfarina)"],
contraindicacoes:["Alergia a cefalosporinas","Alergia IgE-mediada a penicilinas"],
monit:["Hipersensibilidade","Função renal"],
gravidez:"B",
sus:"⚠ Uso hospitalar / interno UBS para procedimento emergencial.",
referencias:["IDSA Surgical Site Infection","Sanford"],
},

/* ============== CEFUROXIMA (2ª GERAÇÃO) ============== */

{id:"med-cefuroxima", classe:"β-lactâmico — cefalosporina 2ª geração", grupo:"atb",
nome:"Cefuroxima (axetil VO / sódica IV)",
sin:["Zinnat","Ceftin","Cefoxin","Zinacef (IV)"],
formas:["Comprimido 250 mg, 500 mg (axetil VO)","Suspensão 250 mg/5 mL (axetil)","Frasco-ampola 750 mg, 1,5 g (sódica IV/IM)","⚠ Não REMUME nacional — em PFPB algumas SES"],
resumo:"⚠ ESPECTRO: AMPLIA a cobertura de 1ª geração — G+ (Strep, S. aureus β-lac+, S. pneumoniae), G- (H. influenzae β-lac+, Moraxella, E. coli, Klebsiella, Proteus), Neisseria gonorrhoeae. PEGA BEM EM: pneumonia comunitária, sinusite/otite refratária, ITU complicada, gonorreia (alternativa). NÃO PEGA: anaeróbios (exceção parcial — alguns Bacteroides), Pseudomonas, MRSA, ESBL.",
dose_rapida:"500 mg VO 12/12h × 7-10d; 750-1500 mg IV 8/8h",
doses:[
{ind:"PAC ambulatorial moderada / com comorbidade", dose:"500 mg VO 12/12h × 5-7 dias + macrolídeo (azitromicina)", obs:"Alternativa a amox+clav."},
{ind:"Sinusite aguda bacteriana / otite refratária", dose:"500 mg 12/12h × 5-7 dias", obs:""},
{ind:"DPOC — exacerbação", dose:"500 mg 12/12h × 5-7 dias", obs:""},
{ind:"ITU complicada não hospitalar", dose:"250-500 mg 12/12h × 7-14 dias", obs:"Pielonefrite ambulatorial estável."},
{ind:"Lyme disease (raro Brasil)", dose:"500 mg 12/12h × 14-21 dias", obs:"Alternativa quando doxiciclina contraindicada."},
{ind:"Gonorreia (alternativa)", dose:"1 g VO dose única", obs:"⚠ 1ª linha atual = ceftriaxona 500 mg IM dose única."},
{ind:"Profilaxia cirúrgica em alguns procedimentos", dose:"1,5 g IV 30 min pré-cirurgia", obs:"Cirurgias colorretais, cabeça e pescoço — geralmente com metronidazol."},
],
ajustes:{
irc:"TFG 10-50: 250-500 mg 24/24h. TFG <10: ajustar mais. Hemodiálise: pós.",
iht:"Sem ajuste",
idoso:"Sem ajuste se função renal normal",
gestante:"B",
aleita:"Compatível",
ped:"30 mg/kg/d ÷ 12/12h. Otite/PAC: 30-40 mg/kg/d.",
},
mecanismo:"Inibe PBPs. Maior estabilidade a β-lactamases que cefalosporinas 1ª geração — melhor cobertura G-.",
farmacocin:{
absorc:"VO axetil: ~50% (melhora COM alimento)",
distrib:"Ampla — não SNC",
metab:"Hepático (hidrólise para forma ativa)",
elimin:"Renal",
meiavida:"~1,2h",
ligacao:"~33-50%",
},
ef_colats:{
comuns:["Diarreia","Náusea","Rash","Candidíase"],
sérios:["Anafilaxia","Stevens-Johnson","Colite C. difficile"],
},
interacoes:["Probenecida","Anticoagulantes","Inibidores H2 / IBP: ↓ absorção"],
contraindicacoes:["Alergia a cefalosporinas","Alergia IgE-mediada a penicilinas"],
monit:["Hipersensibilidade","Função renal"],
gravidez:"B",
sus:"PFPB em algumas SES",
referencias:["Sanford","IDSA"],
},

/* ============== CEFTRIAXONA (3ª GERAÇÃO IV/IM) ============== */

{id:"med-ceftriaxona", classe:"β-lactâmico — cefalosporina 3ª geração IV/IM", grupo:"atb",
nome:"Ceftriaxona",
sin:["Rocefin","Triaxin","Ceftrix"],
formas:["Frasco-ampola 500 mg, 1 g IM/IV","REMUME — UBS dispõe 500 mg / 1 g para uso interno emergencial"],
resumo:"⚠ ESPECTRO: AMPLIADO para G- (mantém boa cobertura G+ exceto enterococo) — E. coli, Klebsiella, Proteus, H. influenzae, N. gonorrhoeae, N. meningitidis, S. pneumoniae (incluindo resistente intermediário). PEGA BEM EM: meningite bacteriana (1ª linha após coleta cultura), gonorreia (DOSE ÚNICA), pielonefrite, PAC moderada-grave hospitalar, sepse de foco oculto, febre tifoide, doença pélvica inflamatória. ⚠ NÃO PEGA: anaeróbios (precisa associar metronidazol), Pseudomonas, MRSA, ESBL, Enterococcus, Listeria.",
dose_rapida:"1-2 g IV/IM 1×/dia (a maioria); meningite 2 g 12/12h",
doses:[
{ind:"⚠ GONORREIA (1ª LINHA)", dose:"500 mg IM DOSE ÚNICA (≥150 kg: 1 g IM)", obs:"⚠ + AZITROMICINA 1 g VO dose única (cobertura clamídia, embora atual CDC discuta isolada). PCDT-MS IST 2024."},
{ind:"⚠ MENINGITE BACTERIANA EMPÍRICA adulto", dose:"2 g IV 12/12h × 10-14 dias (ajustar pela cultura)", obs:"⚠ ASSOCIAR VANCOMICINA (S. pneumoniae resistente) + AMPICILINA se >50a/imunossuprimido (Listeria). DEXAMETASONA 0,15 mg/kg 6/6h × 4d ANTES ou COM 1ª dose ATB."},
{ind:"PAC moderada-grave hospitalar", dose:"1-2 g IV 1×/d × 5-7 dias + AZITROMICINA 500 mg/d (atípicos)", obs:"1ª linha em PAC hospitalar. Pode passar para VO após melhora (amox+clav, levofloxacino)."},
{ind:"Pielonefrite hospitalar / complicada", dose:"1-2 g IV 1×/d × 7-14 dias", obs:"1ª linha em PIELONEFRITE GESTACIONAL hospitalar."},
{ind:"Febre tifoide / paratifoide", dose:"2 g IV 1×/d × 10-14 dias", obs:"Em casos graves ou complicados (perfuração, choque)."},
{ind:"Doença pélvica inflamatória (DIP)", dose:"500 mg IM dose única + doxiciclina 100 mg 12/12h VO × 14d + metronidazol 500 mg 12/12h VO × 14d", obs:"PCDT-MS IST."},
{ind:"Sepse de foco indeterminado adulto", dose:"1-2 g IV 1×/d (ajustar por foco)", obs:"Cobertura empírica de G+ comunitário + G-. Se grave: ampliar."},
{ind:"Endocardite por estreptococos viridans (sensível)", dose:"2 g IV 1×/d × 4 semanas", obs:""},
{ind:"Sífilis na alergia à penicilina (DESSENSIBILIZAÇÃO PREFERIDA na gestação)", dose:"1 g IM/IV 1×/d × 10-14 dias (sífilis primária/secundária)", obs:"⚠ Alternativa quando dessensibilização não viável. PCDT-MS 2024."},
{ind:"Cancroide (Haemophilus ducreyi)", dose:"250 mg IM dose única", obs:""},
{ind:"Prostatite aguda bacteriana", dose:"1-2 g IV 1×/d × 4 semanas (transição para fluoroquinolona VO após melhora)", obs:""},
{ind:"Profilaxia em meningococcemia (contactantes)", dose:"250 mg IM dose única (adulto); 125 mg (criança <15a)", obs:"Alternativa à rifampicina/ciprofloxacino."},
],
ajustes:{
irc:"Sem ajuste em TFG até 10. Hemodiálise: dose padrão pós-sessão.",
iht:"⚠ TFG normal + IH grave: reduzir 50%",
idoso:"Sem ajuste",
gestante:"B",
aleita:"Compatível",
ped:"50-100 mg/kg/d 1×/d. Meningite: 100 mg/kg/d ÷ 12/12h. ⚠ NÃO USAR EM NEONATO COM HIPERBILIRRUBINEMIA (deslocamento de bilirrubina ligada à albumina — kernicterus) — usar cefotaxima.",
},
mecanismo:"Inibe PBPs — bactericida. Vida média longa (~8h) permite 1×/d. Excelente penetração SNC.",
farmacocin:{
absorc:"IV/IM (não VO)",
distrib:"Ampla incluindo SNC, vesícula, próstata",
metab:"Mínimo",
elimin:"Renal (33-67%) + biliar (33-67%)",
meiavida:"~8h",
ligacao:"~85-95%",
},
ef_colats:{
comuns:["Diarreia","Eosinofilia","Trombocitose","Rash","Dor IM local","Elevação transaminases leve"],
sérios:["Anafilaxia","Stevens-Johnson","Colite C. difficile","⚠ Cálculos de cálcio (em criança com Ringer lactato concomitante — REAÇÃO LETAL em neonato)","Anemia hemolítica imunomediada (rara)","Pseudolitíase biliar (reversível)"],
},
interacoes:["⚠ NÃO INFUNDIR junto com RINGER LACTATO ou outras soluções contendo CÁLCIO em NEONATO — precipitação cálcio-ceftriaxona pulmonar/renal","Anticoagulantes orais","Probenecida"],
contraindicacoes:["Alergia a cefalosporinas","Alergia IgE-mediada a penicilinas","Neonato ictérico","⚠ Neonato + soluções de cálcio EV"],
monit:["Hipersensibilidade","Função hepática + renal em uso prolongado","INR"],
gravidez:"B",
sus:"⚠ REMUME — UBS para uso INTERNO emergencial. Hospitais/PA com estoque amplo.",
referencias:["⚠ PCDT-MS IST 2024","IDSA Meningitis","Sanford"],
},

/* ============== CEFEPIMA (4ª GERAÇÃO — referência) ============== */

{id:"med-cefepima", classe:"β-lactâmico — cefalosporina 4ª geração IV (anti-Pseudomonas)", grupo:"atb",
nome:"Cefepima",
sin:["Maxcef","Maxipime"],
formas:["Frasco-ampola 1 g, 2 g IV","⚠ Uso exclusivamente hospitalar — referência para conhecimento (não dispensa em UBS)"],
resumo:"⚠ ESPECTRO: AMPLO — G+ (incluindo MSSA, S. pneumoniae, Strep) + G- (incluindo PSEUDOMONAS aeruginosa, Enterobacter, Serratia) + alguns ESBL parciais. PEGA BEM EM: infecções nosocomiais graves, neutropenia febril, pneumonia hospitalar (HAP/VAP), pielonefrite hospitalar grave. NÃO PEGA: anaeróbios, MRSA, ESBL puro, Stenotrophomonas, Acinetobacter resistente.",
dose_rapida:"1-2 g IV 8-12/12h (hospitalar)",
doses:[
{ind:"Neutropenia febril (empírico)", dose:"2 g IV 8/8h", obs:"Monoterapia padrão em neutropenia febril estável. Em choque: associar amino + vancomicina."},
{ind:"Pneumonia nosocomial / VAP", dose:"2 g IV 8/8h × 7-10 dias", obs:"Cobertura Pseudomonas. Em VAP com risco MRSA: + vancomicina ou linezolida."},
{ind:"Pielonefrite hospitalar grave", dose:"1-2 g IV 12/12h × 10-14 dias", obs:""},
{ind:"Infecção nosocomial grave de foco indeterminado", dose:"2 g IV 8/8h × 7-14 dias", obs:""},
{ind:"Meningite hospitalar / pós-cirurgia neurológica", dose:"2 g IV 8/8h", obs:""},
],
ajustes:{
irc:"⚠ Ajuste IMPORTANTE em IRC — risco NEUROTOXICIDADE (encefalopatia, mioclonia, convulsão). TFG 30-60: 2g 12/12h. TFG 11-29: 2g 24/24h. TFG <10: 1g 24/24h. Diálise: pós.",
iht:"Sem ajuste",
idoso:"⚠ Maior risco de neurotoxicidade em IRC concomitante — ajustar agressivamente",
gestante:"B",
aleita:"Compatível",
ped:"50 mg/kg 12/12h (até 8/8h em casos graves)",
},
mecanismo:"Inibe PBPs. Maior estabilidade a β-lactamases AmpC (que inutilizam ceftriaxona) — melhor cobertura de Enterobacter, Serratia, Pseudomonas.",
farmacocin:{
absorc:"IV (não VO)",
distrib:"Ampla incluindo SNC",
metab:"Mínimo",
elimin:"Renal (>85%)",
meiavida:"~2h",
ligacao:"~20%",
},
ef_colats:{
comuns:["Diarreia","Cefaleia","Náusea","Rash","Tromboflebite IV"],
sérios:["⚠ NEUROTOXICIDADE em IRC com dose inadequada — encefalopatia, mioclonia, convulsão, status não convulsivo. Pode mimetizar AVC.","Anafilaxia","Stevens-Johnson","Colite C. difficile"],
},
interacoes:["Aminoglicosídeos: nefrotoxicidade somativa","Diuréticos de alça"],
contraindicacoes:["Alergia a cefalosporinas","⚠ IRC sem ajuste (neurotoxicidade)"],
monit:["⚠ Sintomas neurológicos em IRC","Função renal","Coombs (anemia hemolítica)"],
gravidez:"B",
sus:"Uso hospitalar (CEAF em algumas indicações)",
referencias:["Sanford","IDSA Neutropenia Febril"],
},

);
