/* ===========================================================
   VOVÔMINIC EMERGÊNCIA — BIBLIOTECA DE MEDICAÇÕES (PARTE 19)
   Bloco E — Antifúngicos
   Fluconazol, Itraconazol, Terbinafina, Nistatina, Cetoconazol tópico, Miconazol tópico
   =========================================================== */

MEDICACOES.push(

/* ============== FLUCONAZOL ============== */

{id:"med-fluconazol", classe:"Antifúngico azólico — triazol", grupo:"atb",
nome:"Fluconazol",
sin:["Zoltec","Flucazol","Triflucan","Candix"],
formas:["Cápsula 100 mg, 150 mg","Comprimido 50 mg, 150 mg","Suspensão oral 50 mg/5 mL, 200 mg/5 mL","Frasco-ampola 200 mg / 100 mL IV","REMUME — UBS dispensação direta + PFPB"],
resumo:"⚠ ESPECTRO: Candida (incluindo C. albicans, ⚠ C. glabrata resistência crescente, C. krusei RESISTENTE intrínseco), Cryptococcus neoformans, alguns dermatófitos (mas terbinafina é melhor), Coccidioides, Histoplasma. PEGA BEM EM: candidíase oral/esofágica/vulvovaginal, criptococose (HIV), micose sistêmica leve. ⚠ NÃO PEGA: Aspergillus, mucormicose, alguns dermatófitos (pior que terbinafina).",
dose_rapida:"150 mg VO DOSE ÚNICA (candidíase vulvovaginal); 100-400 mg/d (sistêmica)",
doses:[
{ind:"⚠ CANDIDÍASE VULVOVAGINAL (não complicada)", dose:"150 mg VO DOSE ÚNICA", obs:"⚠ Eficácia ~80%. Recidiva: 150 mg cada 72h × 3 doses, depois 150 mg 1×/sem × 6 meses."},
{ind:"⚠ CANDIDÍASE ORAL (sapinho / muguet)", dose:"100-200 mg/d × 7-14 dias (adulto)", obs:"Imunocompetente: nistatina oral pode ser suficiente. Imunossuprimido / HIV: fluconazol sistêmico."},
{ind:"⚠ CANDIDÍASE ESOFÁGICA", dose:"200-400 mg/d × 14-21 dias", obs:""},
{ind:"⚠ CRIPTOCOCOSE em HIV (manutenção)", dose:"200 mg/d ad lib até reconstituição imune", obs:"Fase aguda: anfotericina B + flucitosina × 2 sem, depois fluconazol manutenção."},
{ind:"⚠ TINEA versicolor / dermatófitos extensos (alternativa a terbinafina)", dose:"300 mg/sem × 2-4 sem (tinea versicolor); 150 mg/sem × 4-6 sem (tinea corporis/cruris)", obs:""},
{ind:"⚠ ONICOMICOSE (alternativa a terbinafina — preferível terbinafina)", dose:"150-300 mg/sem × 3-6 meses (mão) ou 6-12 meses (pé)", obs:"⚠ Terbinafina é 1ª linha para onicomicose dermatofítica."},
{ind:"Profilaxia em paciente imunossuprimido grave (oncológico, transplante)", dose:"400 mg/d", obs:"Infectologia / hematologia."},
],
ajustes:{
irc:"⚠ TFG <50: 50% dose. TFG <10: 25%. HD: pós.",
iht:"Sem ajuste rotineiro mas monitor transaminases",
idoso:"Sem ajuste em função renal/hepática normal",
gestante:"⚠ ⚠ DOSE ÚNICA 150 mg (candidíase vulvovaginal): aceitável. ⚠ DOSE ALTA (>400 mg/d) NO 1º TRIMESTRE: CATEGORIA D — anomalias craniofaciais. Em criptococose gestacional grave: anfotericina B é preferida.",
aleita:"Compatível (dose única)",
ped:"3-12 mg/kg/d 1×/d. Profilaxia neonatal em UTI: 3-6 mg/kg/d",
},
mecanismo:"⚠ INIBE 14-α-DEMETILASE FÚNGICA (CYP fúngico) → bloqueia síntese de ERGOSTEROL (componente da membrana fúngica). FUNGISTÁTICO em maioria das Candida (fungicida em alguns).",
farmacocin:{
absorc:"VO ~90% (excelente) — não afetada por alimento, pH gástrico",
distrib:"⚠ AMPLA — incluindo SNC, urina, líquido peritoneal, articular (boa em criptococose, urinária)",
metab:"Mínimo",
elimin:"Renal (>80% inalterada)",
meiavida:"~30h (1×/d)",
ligacao:"~11%",
},
ef_colats:{
comuns:["Náusea","Diarreia","Cefaleia","Rash","Dor abdominal"],
sérios:["⚠ HEPATOTOXICIDADE — geralmente leve (elevação transaminases), raramente hepatite franca","⚠ PROLONGAMENTO QT — torsades","⚠ Anomalias congênitas em DOSE ALTA crônica no 1º trimestre","Síndrome de Stevens-Johnson","Anafilaxia","Insuficiência adrenal (raro)","Alopecia em uso prolongado"],
},
interacoes:["⚠ INIBE CYP3A4, CYP2C9 — múltiplas: ⚠ WARFARINA (↑↑ INR — perigoso), sulfonilureias (hipoglicemia), fenitoína, ciclosporina, tacrolimo, estatinas (rabdomiólise — proibir sinvastatina), rifabutina, claritromicina, antiarrítmicos","⚠ QT-PROLONGADORES: somatório","Hidroclorotiazida: ↑ fluconazol"],
contraindicacoes:["Hipersensibilidade","⚠ Uso com QT-prolongadores em paciente de risco","⚠ DOSE ALTA na gestação 1º trimestre"],
monit:["⚠ TGO/TGP em uso prolongado","INR se varfarina","Glicemia se sulfonilureia","ECG em risco","Função renal"],
gravidez:"⚠ Dose única: B/C. ⚠ Dose alta crônica 1º trim: D",
sus:"⚠ REMUME — UBS dispensação direta + PFPB.",
referencias:["IDSA Candidiasis 2016; PCDT-MS HIV; Sanford."],
},

/* ============== ITRACONAZOL ============== */

{id:"med-itraconazol", classe:"Antifúngico azólico — triazol", grupo:"atb",
nome:"Itraconazol",
sin:["Sporanox","Itrazol","Itranax"],
formas:["Cápsula 100 mg","Solução oral 10 mg/mL","FARMASUS / componente complementar — variável"],
resumo:"⚠ ESPECTRO MAIS AMPLO QUE FLUCONAZOL: dermatófitos, Candida, ⚠ Aspergillus (resgate), Sporothrix schenckii (esporotricose — relevante no Brasil), Histoplasma, Paracoccidioides, Blastomyces. ⚠ PEGA BEM EM: ESPOROTRICOSE (1ª linha), paracoccidioidomicose, onicomicose, tinhas refratárias, micose sistêmica leve-moderada. ⚠ NÃO PEGA: mucormicose, alguns Candida não-albicans.",
dose_rapida:"100-200 mg/d × 1-6 meses (variável por indicação)",
doses:[
{ind:"⚠ ⚠ ESPOROTRICOSE (Sporothrix schenckii) — 1ª LINHA", dose:"100-200 mg/d × 3-6 meses (estender 2-4 sem após cura clínica)", obs:"⚠ Endêmica no Brasil — especialmente RJ + Sudeste em transmissão felina. PCDT-MS Esporotricose."},
{ind:"⚠ PARACOCCIDIOIDOMICOSE (Paracoccidioides brasiliensis)", dose:"100-200 mg/d × 6-12 meses (forma juvenil) ou 6-18 meses (crônica)", obs:"⚠ Endêmica no Brasil rural. Alternativa a SMX-TMP de longa duração."},
{ind:"⚠ ONICOMICOSE", dose:"200 mg/d × 12 sem (mão) ou pulso 200 mg 12/12h × 1 sem / mês × 2-3 ciclos (mão) ou 3-4 ciclos (pé)", obs:"⚠ Terbinafina é 1ª linha. Itraconazol é alternativa em dermatófito + leveduras."},
{ind:"⚠ TINHA refratária / extensa", dose:"100 mg/d × 2-4 sem (tinea corporis/cruris); 100 mg/d × 6-8 sem (tinea capitis); 200 mg/d × 7d (pulse) para tinea pedis", obs:""},
{ind:"⚠ Aspergilose invasiva (resgate em paciente que não tolera voriconazol)", dose:"200 mg 12/12h", obs:"Infectologia."},
{ind:"⚠ Pitiriasis versicolor extensa", dose:"200 mg/d × 7 dias", obs:""},
{ind:"⚠ Histoplasmose / blastomicose", dose:"200 mg 12-24/12h × 6-12 meses", obs:""},
],
ajustes:{
irc:"⚠ Solução oral: evitar em TFG <30 (excipiente ciclodextrina nefrotóxico). Cápsula: sem ajuste",
iht:"⚠ Cautela em IH — pode causar hepatotoxicidade grave",
idoso:"⚠ Monitor função hepática + cardíaca",
gestante:"⚠ C — EVITAR (teratogênico em modelos animais). Em esporotricose gestacional: anfotericina B.",
aleita:"⚠ Compatível (limitada concentração)",
ped:"5 mg/kg/d (não bem padronizado <12a)",
},
mecanismo:"INIBE 14-α-DEMETILASE FÚNGICA → bloqueia ergosterol. FUNGISTÁTICO. Mais ativo em Candida não-albicans + dermatófitos + fungos dimórficos que fluconazol.",
farmacocin:{
absorc:"⚠ CÁPSULA: ABSORÇÃO PH-DEPENDENTE — tomar COM ALIMENTO + bebida ácida (refrigerante cola). REDUZIDA por IBP, H2-bloqueador, antiácido. SOLUÇÃO ORAL: melhor absorção em JEJUM, NÃO afetada por pH.",
distrib:"Ampla — ALTA concentração em UNHA, pele, mucosas (ideal onicomicose, tinea). NÃO atinge SNC bem.",
metab:"Hepático CYP3A4",
elimin:"Fecal predominante",
meiavida:"~21h (1×/d)",
ligacao:"~99,8%",
},
ef_colats:{
comuns:["Náusea","Vômito","Diarreia","Dor abdominal","Cefaleia","Rash","Edema"],
sérios:["⚠ ⚠ INSUFICIÊNCIA CARDÍACA — BLACK BOX FDA — efeito INOTRÓPICO NEGATIVO. NÃO USAR em paciente com ICC ou disfunção VE.","⚠ HEPATOTOXICIDADE — hepatite, raramente fatal","Prolongamento QT","Hipocalemia","Síndrome de Stevens-Johnson","Insuficiência adrenal","Neuropatia periférica (raro, uso prolongado)"],
},
interacoes:["⚠ INIBE CYP3A4 — múltiplas interações: ⚠ ESTATINAS (rabdomiólise — proibir sinvastatina, lovastatina), warfarina, ciclosporina, tacrolimo, antiarrítmicos, BZD (midazolam, triazolam — proibir), ergot, alguns antineoplásicos","⚠ Indutores CYP3A4 (rifampicina, carbamazepina, fenitoína): ↓↓ itraconazol","⚠ Antiácidos / IBP / H2 (cápsula): ↓ absorção","QT-prolongadores"],
contraindicacoes:["⚠ ⚠ INSUFICIÊNCIA CARDÍACA / disfunção VE","⚠ Uso com sinvastatina, lovastatina, midazolam, triazolam","⚠ Hipersensibilidade","⚠ Gestação (teratogênico)"],
monit:["⚠ TGO/TGP — basal e a cada 1-2 meses","⚠ Sinais de ICC em paciente de risco","Função renal","ECG em risco"],
gravidez:"⚠ C (evitar)",
sus:"FARMASUS / componente complementar / PCDT específicos (esporotricose, paracoccidioidomicose)",
referencias:["⚠ PCDT-MS Esporotricose; PCDT-MS Paracoccidioidomicose; IDSA; FDA Black Box."],
},

/* ============== TERBINAFINA ============== */

{id:"med-terbinafina", classe:"Antifúngico alilamina", grupo:"atb",
nome:"Terbinafina",
sin:["Lamisil","Funtyl","Terbisil"],
formas:["Comprimido 250 mg","Creme 1%","Solução tópica 1%","REMUME — alguns componentes em PFPB"],
resumo:"⚠ ESPECTRO PRIMORDIAL: DERMATÓFITOS (Trichophyton, Microsporum, Epidermophyton) — fungicida. ATIVIDADE LIMITADA em Candida e leveduras (vs fluconazol/itraconazol que cobrem). ⚠ PEGA BEM EM: ⚠ ONICOMICOSE DERMATOFÍTICA (1ª LINHA — mais eficaz que azólicos), tinea pedis extensa, tinea capitis em criança. NÃO PEGA: Candida bem, Malassezia/pitiríase versicolor.",
dose_rapida:"250 mg/d VO × 6-12 sem (onicomicose); creme 1×/d (tópico)",
doses:[
{ind:"⚠ ⚠ ONICOMICOSE DERMATOFÍTICA — 1ª LINHA", dose:"250 mg VO 1×/d × 6 sem (UNHA DA MÃO) ou 12 sem (UNHA DO PÉ)", obs:"⚠ Cura clínica 60-80%, micológica ~70%. SUPERIOR aos azólicos em onicomicose dermatofítica. Confirmar etiologia antes (KOH / cultura) — em onicomicose por Candida (mãos, paroníquia), preferir fluconazol/itraconazol."},
{ind:"⚠ TINEA PEDIS extensa / refratária a tópico", dose:"250 mg VO 1×/d × 2-6 sem", obs:""},
{ind:"⚠ TINEA CAPITIS (especialmente Trichophyton tonsurans)", dose:"125-250 mg/d × 4-6 sem (criança 3-6 mg/kg/d)", obs:"⚠ Terbinafina é preferida para T. tonsurans (mais comum em surto escolar); GRISEOFULVINA é melhor para Microsporum canis."},
{ind:"⚠ TINEA CORPORIS / CRURIS extensa", dose:"250 mg/d × 2-4 sem", obs:"Geralmente tópico é suficiente. Sistêmico em extensa, refratária, ou foliculite (Trichophyton)."},
{ind:"Tópico — tinea corporis/cruris/pedis", dose:"Creme/solução 1% 1-2×/d × 1-2 semanas (corporis/cruris); 4 sem (pedis interdigital)", obs:""},
],
ajustes:{
irc:"⚠ TFG <50: EVITAR sistêmica (acúmulo, não estudado adequadamente)",
iht:"⚠ EVITAR em IH crônica — risco hepatotoxicidade",
idoso:"⚠ Avaliar função renal + hepática antes",
gestante:"⚠ B — uso oral evitar (dados limitados); tópico aceitável",
aleita:"⚠ Oral evitar; tópico aceitável",
ped:"⚠ ≥4a — sistêmica: 62,5-250 mg/d conforme peso. Tópico: pode em qualquer idade.",
},
mecanismo:"⚠ INIBE ESQUALENO EPOXIDASE FÚNGICA → bloqueia síntese de ergosterol em PASSO ANTERIOR aos azólicos + acúmulo tóxico de esqualeno. FUNGICIDA contra dermatófitos.",
farmacocin:{
absorc:"VO ~80%",
distrib:"⚠ AMPLA — alta concentração em PELE, UNHA, PELO (ideal para estas indicações). Lipofílica.",
metab:"Hepático CYP múltiplos",
elimin:"Renal + fecal",
meiavida:"~36h (acumula na pele/unha — efeito persistente após suspensão)",
ligacao:">99%",
},
ef_colats:{
comuns:["⚠ DISGEUSIA (alteração do paladar — frequente, geralmente reversível em 4-8 sem)","Náusea","Diarreia","Dor abdominal","Rash","Cefaleia"],
sérios:["⚠ ⚠ HEPATOTOXICIDADE — hepatite, raramente fatal — monitorar transaminases. Não usar em hepatopatia prévia.","⚠ NEUTROPENIA / agranulocitose (raro)","Síndrome de Stevens-Johnson / NET","Lúpus induzido por droga","⚠ DEPRESSÃO / IDEAÇÃO SUICIDA (raras mas reportadas — atenção em paciente com história psiquiátrica)","Reação cutânea grave"],
},
interacoes:["⚠ Rifampicina: ↓↓ terbinafina","⚠ Cimetidina: ↑ terbinafina","⚠ INIBE CYP2D6 — pode aumentar antidepressivos tricíclicos, β-bloqueadores, codeína, dextrometorfano","Cafeína: ↑ exposição"],
contraindicacoes:["⚠ Hepatopatia crônica","⚠ TFG <50 (sistêmica)","Hipersensibilidade"],
monit:["⚠ TGO/TGP basal + a cada 4-6 sem em uso prolongado","Hemograma","Sinais de hepatite (icterícia, escure urina, prurido)","Sintomas psiquiátricos"],
gravidez:"B (uso oral evitar; tópico OK)",
sus:"REMUME — UBS em algumas SES",
referencias:["IDSA; British Association of Dermatologists."],
},

/* ============== NISTATINA ============== */

{id:"med-nistatina", classe:"Antifúngico poliênico", grupo:"atb",
nome:"Nistatina",
sin:["Mycostatin","Micostatin"],
formas:["Suspensão oral 100.000 UI/mL","Creme vaginal 25.000 UI/g","Óvulo vaginal","Pomada/creme tópico 100.000 UI/g","REMUME — UBS dispensação direta + PFPB"],
resumo:"⚠ ESPECTRO: APENAS Candida (C. albicans excelente; outras Candida variável) — sem absorção sistêmica (apenas tópica/luminal). PEGA BEM EM: candidíase oral em criança/lactente, candidíase vaginal leve, candidíase intertriginosa, dermatite das fraldas com candida. ⚠ NÃO PEGA: dermatófitos, sistêmica (sem absorção), Aspergillus.",
dose_rapida:"100.000-500.000 UI VO 4×/d (oral); creme vaginal 1×/d × 14d",
doses:[
{ind:"⚠ CANDIDÍASE ORAL — lactente / criança", dose:"100.000-200.000 UI VO 4×/d × 7-14 dias", obs:"⚠ Bochechar e ENGOLIR (efeito local em orofaringe + esôfago superior). Em lactente: aplicar com swab na mucosa. ⚠ Imunossuprimido / esofágica: usar fluconazol sistêmico."},
{ind:"⚠ CANDIDÍASE ORAL ADULTO (alternativa a fluconazol em quadro leve)", dose:"500.000 UI VO 4×/d × 14 dias", obs:""},
{ind:"⚠ CANDIDÍASE VULVOVAGINAL", dose:"Creme vaginal 100.000 UI/g aplicador cheio (~5 g) 1×/d à noite × 14 dias", obs:"⚠ Fluconazol VO dose única é geralmente preferido. Nistatina em gestação ou intolerância oral."},
{ind:"⚠ DERMATITE DAS FRALDAS por Candida", dose:"Pomada / creme 100.000 UI/g 3-4×/d até resolução (geralmente 7-14 dias)", obs:""},
{ind:"⚠ INTERTRIGO candidiásico (dobras, mama, axila, virilha)", dose:"Pomada 2-3×/d × 7-14 dias", obs:""},
{ind:"Profilaxia de candidíase oral em RN prematuro / lactente em ATB", dose:"100.000 UI 4×/d ad lib", obs:""},
],
ajustes:{
irc:"Sem ajuste (não sistêmica)",
iht:"Sem ajuste",
idoso:"Sem ajuste",
gestante:"⚠ ⚠ A — SEGURA na gestação (tópica/luminal, sem absorção)",
aleita:"⚠ A — segura",
ped:"⚠ Segura desde RN — escolha em candidíase oral lactente.",
},
mecanismo:"⚠ LIGA-SE AO ERGOSTEROL na membrana fúngica → forma poros → vazamento iônico → morte celular. FUNGICIDA. Não absorvida sistemicamente VO (ação intestinal/oral somente).",
farmacocin:{
absorc:"⚠ VO ~0% (não absorvida sistemicamente — ação luminal)",
distrib:"Tópica / luminal apenas",
metab:"Não metabolizada (não absorvida)",
elimin:"Fecal (inalterada)",
meiavida:"Local",
ligacao:"Não aplicável",
},
ef_colats:{
comuns:["⚠ Sabor amargo (criança recusa às vezes)","Náusea (rara)","Diarreia leve","Reação local (rash, ardor) — rara"],
sérios:["⚠ Raramente reação alérgica","Geralmente sem efeitos sistêmicos"],
},
interacoes:["Nenhuma significativa (não absorvida)"],
contraindicacoes:["Hipersensibilidade"],
monit:["Resposta clínica","Adesão"],
gravidez:"A",
sus:"⚠ REMUME — UBS dispensação direta + PFPB.",
referencias:["IDSA Candidiasis; PCDT-MS HIV."],
},

/* ============== CETOCONAZOL TÓPICO ============== */

{id:"med-cetoconazol", classe:"Antifúngico azólico — imidazol (tópico)", grupo:"atb",
nome:"Cetoconazol (tópico)",
sin:["Nizoral","Nizoral Shampoo","Aftil"],
formas:["Creme 2%","Shampoo 2%","⚠ Comprimido 200 mg — RETIRADO do mercado pela ANVISA/FDA por hepatotoxicidade grave","REMUME — UBS dispensação direta (shampoo) + PFPB"],
resumo:"⚠ ⚠ APENAS USO TÓPICO HOJE — comprimido VO descontinuado por hepatotoxicidade fatal. ESPECTRO TÓPICO: Malassezia furfur (pitiríase versicolor, dermatite seborreica), Candida, dermatófitos. PEGA BEM EM: ⚠ ⚠ DERMATITE SEBORREICA (couro cabeludo / face) — 1ª LINHA, pitiríase versicolor, tinhas localizadas. NÃO PEGA: micose sistêmica (não absorve), unha (sem penetração).",
dose_rapida:"Shampoo 2× /sem; creme 1-2×/d × 2-4 sem",
doses:[
{ind:"⚠ ⚠ DERMATITE SEBORREICA (couro cabeludo) — 1ª LINHA", dose:"Shampoo 2% 2-3×/sem × 4 sem, depois 1×/sem manutenção", obs:"⚠ Aplicar, MASSAGEAR, DEIXAR AGIR 3-5 MIN, enxaguar. Padrão-ouro tópico. Alternar com piritionato de zinco / sulfeto selênio / cetoconazol shampoo. Casos extensos: + corticoide tópico de baixa potência (hidrocortisona 1%) curto prazo."},
{ind:"⚠ DERMATITE SEBORREICA (face)", dose:"Creme 2% 1-2×/d × 2-4 sem", obs:""},
{ind:"⚠ PITIRÍASE VERSICOLOR", dose:"Shampoo 2% aplicar do pescoço para baixo, deixar 5-10 min, enxaguar — 1×/d × 5-7 dias", obs:"⚠ Eficácia excelente. Em casos extensos refratários: fluconazol VO."},
{ind:"⚠ TINHA cruris / corporis / pedis localizada", dose:"Creme 2% 1-2×/d × 2-4 sem", obs:""},
{ind:"Candidíase cutânea (intertriginosa)", dose:"Creme 2% 1-2×/d × 1-2 sem", obs:""},
],
ajustes:{
irc:"Não aplicável (tópico)",
iht:"Não aplicável (tópico)",
idoso:"Sem ajuste",
gestante:"⚠ B (tópico) — segura na gestação. Evitar comprimido (descontinuado).",
aleita:"Compatível tópico",
ped:"Tópico em criança — não bem padronizado <12a mas geralmente seguro",
},
mecanismo:"INIBE 14-α-DEMETILASE fúngica → bloqueia ergosterol. FUNGISTÁTICO tópico. SEM absorção sistêmica significativa em uso tópico adequado.",
farmacocin:{
absorc:"⚠ Tópico — absorção sistêmica desprezível",
distrib:"Pele/couro cabeludo",
metab:"Hepático (se absorvido)",
elimin:"Fecal",
meiavida:"Local",
ligacao:"Não aplicável",
},
ef_colats:{
comuns:["Irritação local","Ressecamento","Prurido","Eritema","Folículite leve"],
sérios:["⚠ HEPATOTOXICIDADE — descrita com uso ORAL (descontinuado). Tópico: muito raro","Reação alérgica local","Aplicação extensa em superfície grande pode ter absorção"],
},
interacoes:["⚠ Forma oral (descontinuada): muitas interações CYP3A4. Tópico: nenhuma significativa."],
contraindicacoes:["⚠ Hepatopatia (oral — descontinuada)","Hipersensibilidade"],
monit:["Resposta clínica"],
gravidez:"B (tópico)",
sus:"⚠ REMUME — UBS dispensação direta (shampoo) + PFPB.",
referencias:["⚠ FDA / ANVISA — descontinuação cetoconazol oral por hepatotoxicidade; AAD Seborrheic Dermatitis."],
},

/* ============== MICONAZOL ============== */

{id:"med-miconazol", classe:"Antifúngico azólico — imidazol (tópico)", grupo:"atb",
nome:"Miconazol (tópico)",
sin:["Daktarin","Vodol","Miconal"],
formas:["Creme 2% (cutâneo)","Creme vaginal 2%","Pó cutâneo 2%","Sol oral / gel oral 2% (Daktarin gel oral)","REMUME — UBS dispensação direta + PFPB"],
resumo:"⚠ Imidazol tópico AMPLO — Candida, dermatófitos, Malassezia. PEGA BEM EM: candidíase vulvovaginal, candidíase cutânea, tinhas localizadas, candidíase oral (gel — alternativa à nistatina). ⚠ Cápsula/comprimido oral: descontinuada por hepatotoxicidade.",
dose_rapida:"Creme 2% 1-2×/d × 2-4 sem; vaginal 1 aplic/d × 7d; gel oral 4×/d",
doses:[
{ind:"⚠ CANDIDÍASE VULVOVAGINAL", dose:"Creme vaginal 2% aplicador cheio à NOITE × 7 dias", obs:"Alternativa em paciente que prefere tópico ou gestante (evita fluconazol VO em gestação se possível)."},
{ind:"⚠ CANDIDÍASE CUTÂNEA / intertrigo", dose:"Creme 2% 1-2×/d × 2-4 sem", obs:""},
{ind:"⚠ DERMATITE DAS FRALDAS por candida (alternativa a nistatina)", dose:"Creme 2% 2-3×/d até resolução", obs:""},
{ind:"⚠ TINHAS LOCALIZADAS (cruris, corporis, pedis)", dose:"Creme 2% 1-2×/d × 2-4 sem", obs:""},
{ind:"⚠ CANDIDÍASE ORAL — gel (alternativa a nistatina)", dose:"Gel 2% — 1,25 mL (¼ colher chá) 4×/d × 7-14 dias (manter no boca o quanto possível)", obs:"⚠ NUNCA engolir — ação local. Em lactente: cuidado com aspiração."},
{ind:"⚠ PITIRÍASE VERSICOLOR (alternativa)", dose:"Creme/loção 2% 1-2×/d × 2-4 sem", obs:""},
],
ajustes:{
irc:"Não aplicável (tópico)",
iht:"Não aplicável (tópico)",
idoso:"Sem ajuste",
gestante:"⚠ B (tópico) — segura. ⚠ Creme vaginal: PREFERIR aplicador SEM aplicador em gestação avançada.",
aleita:"Compatível tópico",
ped:"Tópico: segura. ⚠ Gel oral: cuidado com aspiração em <2a — em lactente preferir nistatina suspensão.",
},
mecanismo:"INIBE 14-α-demetilase fúngica → bloqueia ergosterol. FUNGISTÁTICO.",
farmacocin:{
absorc:"Tópico — mínima absorção sistêmica",
distrib:"Local",
metab:"Hepático se absorvido",
elimin:"Fecal",
meiavida:"Local",
ligacao:"Não aplicável",
},
ef_colats:{
comuns:["Irritação local","Ardor / queimação","Eritema","Prurido"],
sérios:["Reação alérgica local","⚠ Cremes vaginais em LÁTEX (preservativos, diafragma): podem comprometer (uso de barreira contraceptiva alternativa)","⚠ Gel oral + warfarina (mesmo doses pequenas): pode aumentar INR (descrito)"],
},
interacoes:["⚠ Gel oral + warfarina: ↑ INR (mesmo absorção mínima — relatos importantes)","⚠ Látex (preservativos, diafragma): cremes vaginais podem danificar"],
contraindicacoes:["Hipersensibilidade","⚠ Aspiração em <2a (gel oral) — usar nistatina"],
monit:["Resposta clínica","INR se warfarina + gel oral"],
gravidez:"B (tópico)",
sus:"⚠ REMUME — UBS dispensação direta + PFPB.",
referencias:["IDSA Candidiasis; PCDT-MS IST."],
},

);
