/* ===========================================================
   VOVÔMINIC EMERGÊNCIA — BIBLIOTECA DE MEDICAÇÕES (PARTE 26)
   Adjuvantes Paliativos — antimuscarínicos + octreotida + laxativos
   Hioscina butil, Escopolamina, Octreotida, Bisacodil, Lactulose, Metilnaltrexona
   =========================================================== */

MEDICACOES.push(

/* ============== HIOSCINA BUTILBROMETO (BUSCOPAN) ============== */

{id:"med-hioscina-butil", classe:"Antimuscarínico — periférico (não atravessa BHE)", grupo:"pali",
nome:"Hioscina Butilbrometo",
sin:["Buscopan","Butilescopolamina","Butilbrometo de escopolamina"],
formas:["Comprimido 10 mg","Drágea + dipirona (Buscopan Composto)","Solução oral 4 mg/mL (criança)","Ampola 20 mg/mL IM/IV/SC","REMUME — UBS dispensação direta"],
resumo:"⚠ ⚠ ANTIMUSCARÍNICO PERIFÉRICO — NÃO ATRAVESSA BHE (amônio quaternário). VANTAGEM: SEM sedação, SEM delirium, SEM efeito central. Indicações em paliativos: ⚠ ESTERTOR TERMINAL (1ª linha no Brasil), CÓLICA GI ou GU, OBSTRUÇÃO INTESTINAL MALIGNA (antiespasmódico). Em emergência: cólica renal, cólica biliar, dismenorreia.",
dose_rapida:"10-20 mg VO/IM/IV/SC 4-6/6h",
doses:[
{ind:"⚠ ⚠ ESTERTOR TERMINAL — 1ª LINHA no Brasil", dose:"20 mg SC 4-6/6h OU BIC SC 60-120 mg/d", obs:"⚠ ⚠ Sem sedação, sem delirium — diferença da escopolamina hidrobrometo. Início precoce (antes de muita secreção) é mais eficaz."},
{ind:"⚠ CÓLICA em obstrução intestinal maligna (paliativos)", dose:"20 mg SC 4-6/6h OU BIC SC 60-120 mg/d", obs:"⚠ Combinado com opioide + antiemético + considerar octreotida."},
{ind:"⚠ Cólica renal / biliar / dismenorreia (emergência)", dose:"20 mg IV/IM bolus, pode repetir em 30 min", obs:"⚠ Útil junto a dipirona/AINE."},
{ind:"Pré-medicação para EDA / colonoscopia", dose:"20 mg IV imediatamente antes", obs:"Reduz peristaltismo."},
{ind:"⚠ Cólica intestinal funcional / SII", dose:"10 mg VO 6-8/8h ad lib", obs:""},
{ind:"Sialorreia em ELA / Parkinson (off-label)", dose:"10-20 mg VO 8-12/12h ou patch off-label", obs:""},
],
ajustes:{
irc:"Sem ajuste rotineiro",
iht:"Cautela",
idoso:"⚠ Cuidado com efeitos anticolinérgicos periféricos (retenção urinária, constipação, glaucoma) — mas SEM delirium (vantagem)",
gestante:"⚠ C — uso comum em cólica gestacional. Cautela 1º trim.",
aleita:"Compatível",
ped:"≥6a aprovada para cólica",
},
mecanismo:"⚠ ⚠ ANTIMUSCARÍNICO (amônio QUATERNÁRIO) — NÃO atravessa BHE. Bloqueia receptores M2/M3 em musculatura lisa GI/GU/biliar → antiespasmódico + antisecretor (reduz secreção GI quando dose alta).",
farmacocin:{
absorc:"VO ~8% (muito baixa — explica preferência por SC/IM/IV em paliativos)",
distrib:"⚠ Periférica — NÃO BHE",
metab:"Hepático mínimo",
elimin:"Renal + fecal",
meiavida:"~3-5h (SC)",
ligacao:"Baixa",
},
ef_colats:{
comuns:["Boca seca","Retenção urinária leve","Constipação","Visão turva","Taquicardia leve","Tonteira"],
sérios:["⚠ ⚠ ⚠ GLAUCOMA agudo de ângulo fechado (raríssimo — agudo: dor ocular + visão turva)","⚠ Retenção urinária aguda em HPB","Reação alérgica","Anafilaxia (rara)"],
},
interacoes:["⚠ Outros anticolinérgicos: somatório periférico (não central)","⚠ Inibidores da AChE (donepezila, rivastigmina): efeito antagônico","Levodopa: ↓ absorção"],
contraindicacoes:["⚠ Glaucoma ângulo fechado","⚠ HPB com retenção","⚠ Estenose mecânica GI / íleo (oposto da obstrução funcional/cólica)","⚠ Miastenia gravis","⚠ Megacolon","Hipersensibilidade","Taquiarritmia"],
monit:["Retenção urinária em risco","Resposta clínica"],
gravidez:"C",
sus:"⚠ REMUME — UBS dispensação direta",
referencias:["ANCP; EAPC Estertor; Buscopan Bula."],
},

/* ============== ESCOPOLAMINA HIDROBROMETO ============== */

{id:"med-escopolamina-hb", classe:"Antimuscarínico central (atravessa BHE)", grupo:"pali",
nome:"Escopolamina (hidrobrometo)",
sin:["Hioscina hidrobrometo","Scopolamine","Transderm Scop"],
formas:["Ampola 0,4 mg/mL e 0,6 mg/mL SC/IM","Adesivo transdérmico 1 mg/72h (importado / particular)","FARMASUS / particular"],
resumo:"⚠ ANTIMUSCARÍNICO TERCIÁRIO — ATRAVESSA BHE (diferente da hioscina butilbrometo). Efeito CENTRAL + periférico. Indicações: ⚠ SIALORREIA / ESTERTOR TERMINAL (alternativa à hioscina butil quando útil sedação leve), CINETOSE, antiemético vestibular. ⚠ Pode causar SEDAÇÃO + DELIRIUM (especialmente idoso) — perfil colateral CENTRAL.",
dose_rapida:"0,4-0,6 mg SC 4-6/6h OU adesivo 1 mg/72h",
doses:[
{ind:"⚠ ESTERTOR TERMINAL — alternativa à hioscina butil quando sedação leve útil", dose:"0,4-0,6 mg SC 4-6/6h OU BIC SC 1,2-2,4 mg/d", obs:"⚠ Diferença para hioscina butil: ATRAVESSA BHE → SEDAÇÃO + risco de delirium. Útil em paciente já sedado/em fase ativa."},
{ind:"⚠ SIALORREIA persistente (ELA, Parkinson, demência)", dose:"Adesivo TD 1 mg/72h (retroauricular)", obs:""},
{ind:"⚠ Cinetose / vertigem", dose:"Adesivo TD 1 mg/72h", obs:""},
{ind:"Antiemético vestibular paliativo", dose:"0,3-0,6 mg SC 6/6h", obs:""},
],
ajustes:{
irc:"Cautela",
iht:"Cautela",
idoso:"⚠ ⚠ EVITAR uso prolongado — risco delirium, sedação, queda. Em fase ativa: pode ser aceitável.",
gestante:"⚠ C — Cautela",
aleita:"Cautela",
ped:"Especialista",
},
mecanismo:"⚠ ANTIMUSCARÍNICO terciário — atravessa BHE. Bloqueia receptores M1-M5 periféricos + centrais. Antagonismo vestibular (cinetose), antissecretor (sialorreia, secreção brônquica), antiespasmódico GI/GU.",
farmacocin:{
absorc:"VO baixa (~10%); SC/TD melhores",
distrib:"⚠ Ampla — atravessa BHE (terciária)",
metab:"Hepático",
elimin:"Renal",
meiavida:"~2-9h (SC); adesivo libera por 72h",
ligacao:"Variável",
},
ef_colats:{
comuns:["⚠ Sedação (diferença da hioscina butil)","Boca seca","Visão turva","Retenção urinária","Constipação","Taquicardia"],
sérios:["⚠ ⚠ DELIRIUM / CONFUSÃO em idoso","⚠ Glaucoma agudo","⚠ Retenção urinária aguda","Excitação paradoxal (criança)","Hipertermia em criança"],
},
interacoes:["⚠ Outros anticolinérgicos: somatório central E periférico","Outros sedativos: depressão SNC somativa","Inibidores AChE: antagonismo"],
contraindicacoes:["⚠ Glaucoma ângulo fechado","⚠ HPB com retenção","⚠ Megacolon / íleo","⚠ Miastenia gravis","Demência (relativa — risco delirium)","Hipersensibilidade"],
monit:["Estado mental (delirium)","Retenção urinária","Sedação","Resposta clínica"],
gravidez:"C",
sus:"⚠ FARMASUS / particular",
referencias:["ANCP; EAPC Estertor; SBN."],
},

/* ============== OCTREOTIDA ============== */

{id:"med-octreotida", classe:"Análogo sintético da somatostatina", grupo:"pali",
nome:"Octreotida",
sin:["Sandostatin","Sandostatina LAR (depot)","Octrolong"],
formas:["Ampola 50, 100, 500 mcg/mL SC/IV","Frasco LAR (depot) 10, 20, 30 mg IM mensal","⚠ CEAF — PCDT específico (acromegalia, TNE); em paliativos: prescrição especialista"],
resumo:"⚠ ANÁLOGO DA SOMATOSTATINA — inibe múltiplos hormônios + REDUZ SECREÇÕES GI (gástrica, pancreática, biliar, intestinal). Indicação paliativa principal: ⚠ ⚠ OBSTRUÇÃO INTESTINAL MALIGNA — reduz secreção, descomprime alça, controla vômito (alternativa à cirurgia em paciente não-cirúrgico). Também: tumores neuroendócrinos, acromegalia, hemorragia varicosa.",
dose_rapida:"100-300 mcg SC 8/8h OU BIC SC 300-900 mcg/d",
doses:[
{ind:"⚠ ⚠ OBSTRUÇÃO INTESTINAL MALIGNA — controle de vômito + secreção", dose:"⚠ INÍCIO: 100 mcg SC 8/8h × 24-48h. Se inadequado: titular até 300-900 mcg/d (BIC SC ou ÷ 8/8h)", obs:"⚠ ⚠ ESPECIALISTA. Alternativa quando cirurgia inviável. Combinar com dexametasona + opioide + hioscina butil. Pode reduzir necessidade de SNG descompressiva."},
{ind:"⚠ Diarreia secretora paraneoplásica (síndrome carcinoide, VIPoma)", dose:"100-300 mcg SC 8-12/12h", obs:""},
{ind:"⚠ Sd. Carcinoide — alívio sintomático", dose:"100-500 mcg SC 8/8h ou LAR 20-30 mg IM mensal", obs:""},
{ind:"⚠ Fístula GI alto débito / pós-cirúrgica", dose:"50-200 mcg SC 8/8h", obs:""},
{ind:"⚠ Hemorragia varicosa (UTI / endoscopia)", dose:"Bolus 50 mcg IV + BIC 25-50 mcg/h × 3-5d", obs:"⚠ Alternativa à terlipressina."},
],
ajustes:{
irc:"Reduzir em IRC grave",
iht:"Cautela",
idoso:"⚠ Iniciar baixo",
gestante:"⚠ B — Cautela",
aleita:"Cautela",
ped:"Especialista",
},
mecanismo:"⚠ ANÁLOGO DA SOMATOSTATINA — liga receptores SSTR2 e SSTR5 → INIBE: GH, insulina, glucagon, gastrina, secretina, VIP, CCK + REDUZ MOTILIDADE INTESTINAL + REDUZ FLUXO SANGUÍNEO ESPLÂNICO + REDUZ SECREÇÃO GI (paliativos = chave do efeito em obstrução).",
farmacocin:{
absorc:"SC ~100%",
distrib:"Limitada",
metab:"Hepático",
elimin:"Renal + bile",
meiavida:"~1,5h (forma simples); LAR 1 mês",
ligacao:"~65%",
},
ef_colats:{
comuns:["Dor no local (transitória)","Cólica abdominal, flatulência (efeito procinético inicial)","Diarreia OU constipação","Hipoglicemia ou hiperglicemia leve (variável)","Náusea"],
sérios:["⚠ COLELITÍASE em uso prolongado >6m (reduz contração biliar) — USG anual","⚠ Hipotireoidismo","Bradicardia","Pancreatite (raro)","Hipoglicemia grave em diabético insulino-dependente (variável)"],
},
interacoes:["⚠ Insulina, hipoglicemiantes: ajuste necessário","Ciclosporina: ↓ absorção","Bromocriptina: ↑ nível","Beta-bloqueadores: bradicardia somativa"],
contraindicacoes:["Hipersensibilidade","Cautela em diabetes mal controlada"],
monit:["Glicemia","Função tireoidiana em uso prolongado","USG vias biliares anual em uso >6m","Resposta clínica"],
gravidez:"B",
sus:"⚠ CEAF — PCDT específico; particular comum em paliativos",
referencias:["⚠ MASCC Obstrução Intestinal; ANCP; ESMO."],
},

/* ============== BISACODIL ============== */

{id:"med-bisacodil", classe:"Laxativo estimulante de contato", grupo:"pali",
nome:"Bisacodil",
sin:["Dulcolax","Bisacolax","Lactopurga (combinado)"],
formas:["Comprimido entérico 5 mg","Supositório 10 mg","Drágea 5 mg","REMUME — UBS dispensação direta + PFPB"],
resumo:"⚠ LAXATIVO ESTIMULANTE de contato — atua DIRETAMENTE na mucosa do cólon → ↑ motilidade + ↑ secreção. Indicação principal em paliativos: ⚠ ⚠ PROFILAXIA DE CONSTIPAÇÃO INDUZIDA POR OPIOIDE — combinado com lactulose ou PEG. Efeito em 6-12h (VO) ou 15-60 min (supositório). Bem tolerado. Comprimido REVESTIDO ENTÉRICO — não esmagar.",
dose_rapida:"5-10 mg VO HS (VO leva 6-12h); 10 mg supositório (15-60 min)",
doses:[
{ind:"⚠ ⚠ PROFILAXIA / TRATAMENTO DE CONSTIPAÇÃO INDUZIDA POR OPIOIDE", dose:"⚠ 5-10 mg VO HS — combinar com lactulose 15-30 mL 12/12h. Prescrever JUNTO com a primeira dose de opioide", obs:"⚠ ⚠ EM TODA PRESCRIÇÃO DE OPIOIDE. Comprimido revestido: ENGOLIR INTEIRO (não mastigar — protege estômago do efeito direto)."},
{ind:"⚠ Constipação refratária — escalonamento", dose:"10-15 mg VO HS + supositório 10 mg de manhã se evacuação inadequada", obs:""},
{ind:"⚠ Constipação em paciente sem evacuação ≥3 dias / impactação alta", dose:"Supositório 10 mg + lavagem retal (SF 250-500 mL)", obs:""},
{ind:"Preparo intestinal pré-procedimento", dose:"15-30 mg VO 12h antes", obs:""},
],
ajustes:{
irc:"Sem ajuste",
iht:"Sem ajuste",
idoso:"Sem ajuste — cuidado com depleção volêmica/eletrolítica em uso crônico",
gestante:"⚠ Categoria B — segura. Útil em constipação gestacional.",
aleita:"Compatível",
ped:"≥4-6a; supositório aprovado >3a",
},
mecanismo:"⚠ Pro-droga — hidrolisada por esterase bacteriana do cólon → BHPM (forma ativa) → estimula plexo de Auerbach → ↑ peristaltismo + ↑ secreção de água/eletrólitos.",
farmacocin:{
absorc:"VO ~5% (atua localmente — vantagem)",
distrib:"Local",
metab:"Cólon (esterases)",
elimin:"Fecal",
meiavida:"Não aplicável",
ligacao:"",
},
ef_colats:{
comuns:["⚠ Cólica abdominal (leve a moderada)","Diarreia em dose excessiva","Náusea leve"],
sérios:["⚠ Distúrbios hidroeletrolíticos em uso CRÔNICO ABUSIVO (hipocalemia, alcalose, desidratação)","Reação alérgica","Cólica intensa","Melanose coli em uso muito prolongado (benigna)"],
},
interacoes:["⚠ Diuréticos: hipocalemia somativa","⚠ Digoxina: ↑ toxicidade por hipocalemia","Antiácidos / IBP / leite: ⚠ NÃO TOMAR JUNTO com comprimido (quebra revestimento entérico)","Outros laxativos"],
contraindicacoes:["⚠ Obstrução intestinal","⚠ Apendicite / abdome agudo","⚠ Sangramento GI ativo","⚠ Megacolon","⚠ Desidratação grave","Hipersensibilidade"],
monit:["Resposta clínica","Eletrólitos em uso crônico","Sinais de cólica intensa"],
gravidez:"B",
sus:"⚠ REMUME — UBS dispensação direta + PFPB",
referencias:["ANCP; ESMO Constipação."],
},

/* ============== LACTULOSE ============== */

{id:"med-lactulose", classe:"Laxativo osmótico + redutor de amônia", grupo:"pali",
nome:"Lactulose",
sin:["Duphalac","Pentalac","Laevolac","Constulose"],
formas:["Solução oral 667 mg/mL (mais comum) ou 10 g/15 mL","Frasco 120, 200, 500 mL","REMUME — UBS dispensação direta + PFPB"],
resumo:"⚠ LAXATIVO OSMÓTICO — dissacarídeo SINTÉTICO não absorvível. ↑ água no cólon → fezes mais moles. Indicações: ⚠ ⚠ CONSTIPAÇÃO (especialmente em OPIOIDE, gestação, idoso, IRC) + ⚠ ENCEFALOPATIA HEPÁTICA (reduz absorção de amônia). Sabor adocicado. Efeito gradual em 24-48h.",
dose_rapida:"15-30 mL VO 12/12h (constipação); 30-45 mL 8/8h (encefalopatia hepática)",
doses:[
{ind:"⚠ ⚠ CONSTIPAÇÃO em paliativos / induzida por opioide", dose:"15-30 mL VO 12/12h ad lib (até 30-45 mL 12/12h se necessário)", obs:"⚠ Combinar com bisacodil. Efeito em 24-48h. Sabor adocicado — alguns pacientes não toleram (usar PEG)."},
{ind:"⚠ ENCEFALOPATIA HEPÁTICA — aguda e crônica", dose:"30-45 mL VO 8/8h até 2-3 evacuações pastosas/d", obs:"⚠ Mecanismo: acidifica cólon → captura NH₃ → NH₄+ → reduz absorção. Em paciente IH com encefalopatia: meta = 2-3 evacuações pastosas/d."},
{ind:"⚠ Encefalopatia hepática — enema (paciente não cooperativo)", dose:"300 mL em 700 mL SF — clister, manter 30-60 min", obs:""},
{ind:"⚠ Constipação gestacional", dose:"15-30 mL VO 12/12h", obs:""},
{ind:"Pediatria — constipação crônica", dose:"1-2 mL/kg/d ÷ 1-2×/d", obs:""},
],
ajustes:{
irc:"Sem ajuste",
iht:"Útil (indicação em IH com encefalopatia)",
idoso:"Sem ajuste — útil em constipação geriátrica",
gestante:"⚠ B — segura",
aleita:"Compatível",
ped:"Aprovada em qualquer idade",
},
mecanismo:"⚠ DISSACARÍDEO SINTÉTICO (galactose + frutose) — NÃO HIDROLISADO no intestino delgado humano. No CÓLON: bactérias fermentam → ácido láctico + acético → ↓ pH intestinal → CONVERTE NH₃ em NH₄+ (não absorvível — encefalopatia hepática). EFEITO OSMÓTICO atrai água → amolece fezes.",
farmacocin:{
absorc:"⚠ <3% absorvida (atua localmente)",
distrib:"Limitada ao cólon",
metab:"Fermentação bacteriana no cólon",
elimin:"Fecal",
meiavida:"Não aplicável",
ligacao:"",
},
ef_colats:{
comuns:["⚠ FLATULÊNCIA (frequente — fermentação)","Cólica abdominal","Diarreia em dose excessiva","Náusea (sabor adocicado intolerável a alguns)"],
sérios:["⚠ Distúrbios hidroeletrolíticos em uso EXCESSIVO (hipernatremia paradoxal por perda fecal de água)","Hipocalemia (uso crônico em dose alta)"],
},
interacoes:["⚠ NEOMICINA, RIFAXIMINA: combinação útil em encefalopatia hepática refratária","Outros laxativos: somatório","Antiácidos: podem reduzir acidificação colônica (relevante em encefalopatia)"],
contraindicacoes:["⚠ Obstrução intestinal","⚠ Galactosemia","⚠ Apendicite / abdome agudo","Hipersensibilidade","Cautela em diabetes (contém galactose+frutose, geralmente impacto pequeno)"],
monit:["Resposta clínica (frequência + consistência de evacuação)","Eletrólitos em uso crônico em dose alta","Em encefalopatia: nível de consciência + frequência fecal (meta 2-3 pastosas/d)"],
gravidez:"B",
sus:"⚠ REMUME — UBS dispensação direta + PFPB",
referencias:["ANCP; ESMO Constipação; AASLD Encefalopatia Hepática."],
},

/* ============== METILNALTREXONA ============== */

{id:"med-metilnaltrexona", classe:"Antagonista μ-opioide PERIFÉRICO", grupo:"pali",
nome:"Metilnaltrexona",
sin:["Relistor"],
formas:["Ampola 12 mg/0,6 mL SC (também 8 mg/0,4 mL)","Comprimido 150 mg (CIO em não-câncer)","⚠ CEAF / particular — custo alto, NÃO REMUME na maioria das SES"],
resumo:"⚠ ⚠ ANTAGONISTA μ-OPIOIDE PERIFÉRICO — não atravessa BHE (carga +). VANTAGEM ÚNICA: BLOQUEIA EFEITOS GI DO OPIOIDE (constipação) SEM REVERTER ANALGESIA central. Indicação: ⚠ ⚠ CONSTIPAÇÃO INDUZIDA POR OPIOIDE (CIO) REFRATÁRIA a laxativos otimizados. Efeito em 30-60 min. ⚠ Custo alto. Não usar em obstrução suspeita.",
dose_rapida:"8 mg SC (38-62 kg) ou 12 mg SC (>62 kg) cada 48h",
doses:[
{ind:"⚠ ⚠ CONSTIPAÇÃO INDUZIDA POR OPIOIDE refratária — paciente com câncer", dose:"⚠ Peso 38-62 kg: 8 mg SC. Peso 62-114 kg: 12 mg SC. Peso >114 kg: 0,15 mg/kg SC. ⚠ Cada 48h (não diário)", obs:"⚠ ⚠ APENAS quando laxativos otimizados (bisacodil + lactulose/PEG + supositórios) FALHARAM em >5-7 dias. Efeito laxativo em 30-60 min."},
{ind:"⚠ CIO em condição não-oncológica (dor crônica)", dose:"450 mg VO 1×/d em jejum (forma oral) OU 12 mg SC cada 48h", obs:""},
],
ajustes:{
irc:"⚠ TFG <30: reduzir 50%",
iht:"⚠ IH grave: usar com cautela",
idoso:"Sem ajuste rotineiro além de peso/TFG",
gestante:"⚠ B — uso quando benefício > risco. Sintomas de abstinência opioide em feto teórico.",
aleita:"Cautela",
ped:"Não aprovada rotineira",
},
mecanismo:"⚠ ANTAGONISTA μ-opioide com carga POSITIVA (quaternária — derivada da naltrexona) — NÃO atravessa BHE. Bloqueia receptores μ no trato GI → reverte constipação. NÃO afeta analgesia central (paciente mantém analgesia adequada).",
farmacocin:{
absorc:"SC ~100% (oral ~1% — explica dose 150 mg VO vs 12 mg SC)",
distrib:"⚠ Periférica — NÃO atravessa BHE",
metab:"Mínimo",
elimin:"Renal + fecal",
meiavida:"~8h",
ligacao:"Baixa",
},
ef_colats:{
comuns:["Cólica abdominal (transitória)","Flatulência","Náusea","Diarreia","Hiperidrose","Tontura"],
sérios:["⚠ ⚠ PERFURAÇÃO GI — relatos em paciente com lesão GI prévia (úlcera, neoplasia GI, diverticulite, CCR — risco maior). ⚠ NÃO USAR em paciente com obstrução suspeita ou lesão GI ativa","⚠ Síndrome de abstinência opioide se metilnaltrexona consegue atravessar BHE (raro — em pacientes com BHE comprometida — meta cerebral, AVC, encefalopatia)"],
},
interacoes:["Outros opioides: bloqueio periférico (manter analgesia)","Indutores / inibidores CYP: efeito mínimo"],
contraindicacoes:["⚠ ⚠ OBSTRUÇÃO INTESTINAL MECÂNICA conhecida ou suspeita","⚠ Risco aumentado de perfuração GI (úlcera ativa, neoplasia GI obstrutiva, diverticulite ativa, doença GI grave)","Hipersensibilidade"],
monit:["Sinais de perfuração GI — dor abdominal súbita intensa pós-administração → suspender + investigar","Resposta laxativa","Sintomas de abstinência (raro)"],
gravidez:"B",
sus:"⚠ ⚠ CEAF / particular — NÃO REMUME na maioria das SES",
referencias:["MASCC Constipação Opioide; ANCP; AGA Guideline."],
},

);
