/* ===========================================================
   VOVÔMINIC DOUTÔ — pat/oft-mfc.js
   Oftalmologia básica MFC — catarata, DMRI/RD, olho seco,
   blefarite/hordéolo/calázio, pterígio, acuidade visual MFC
   Sistema: oft
   Fonte: CBO 2024, AAO Preferred Practice Pattern 2024
   =========================================================== */

PATOLOGIAS.push(

/* ============================================================
   1. CATARATA — reconhecimento e encaminhamento
   ============================================================ */
{
id:"catarata", contexto:["ubs"], nome:"Catarata — Reconhecimento, Avaliação e Encaminhamento",
sis:"oft", grav:"baixa",
cid:"H25", ciap:"F92",
sin:["catarata","catarata senil","catarata congênita","opacificação do cristalino","baixa visual"],
def:"Opacificação progressiva do cristalino, causando redução da acuidade visual e da qualidade da visão. Tipos: SENIL (mais comum, >60a — relacionada à idade), CONGÊNITA (RN/lactente — urgência diagnóstica), TRAUMÁTICA, METABÓLICA (DM — catarata diabética mais precoce), MEDICAMENTOSA (corticoide sistêmico ou tópico ocular crônico), por radiação. Cirurgia é o ÚNICO tratamento efetivo — facectomia + implante de LIO (lente intraocular).",
intro:"Catarata é a PRINCIPAL CAUSA DE CEGUEIRA REVERSÍVEL no mundo. No Brasil, é responsável por mais de 50% das cegueiras tratáveis. MFC: identificar BAIXA VISUAL em consulta de rotina (especialmente em idoso, diabético, pós-cirurgia ocular), aplicar TESTE DE ACUIDADE VISUAL (Snellen), encaminhar oftalmologia. CATARATA CONGÊNITA é URGÊNCIA ABSOLUTA (RN — reflexo vermelho ausente/anormal → encaminhar em 24-48h; janela ambliópica curta). Em adulto: encaminhamento eletivo conforme impacto na qualidade de vida + função.",
fisio:"Cristalino normalmente transparente — composto majoritariamente de proteínas (cristalinas) bem-organizadas. Com idade: oxidação + glicação + reticulação destas proteínas → desorganização estrutural → opacificação progressiva (núcleo, córtex, ou subcapsular posterior). Acelerada em DM (glicação intensa), corticoide (subcapsular posterior), exposição UV crônica, tabagismo, álcool, trauma.",
apresentacao:"Adulto idoso (>60a) ou diabético/usuário de corticoide com: BAIXA VISUAL GRADUAL e progressiva (meses-anos), VISÃO EMBAÇADA (como 'através de vidro fosco' ou 'vista turva'), HALOS coloridos noturnos em torno de luzes, OFUSCAMENTO em ambientes muito iluminados (paradoxal — pior com sol), redução da visão de contraste, mudanças freqüentes na prescrição óptica ('o óculos não está mais bom'), MIOPIZAÇÃO progressiva (paciente que precisava de óculos para perto e parou de precisar — porque o cristalino ficou mais convergente). Ao exame: REFLEXO VERMELHO diminuído ou ausente; ao oftalmoscópio direto, vê-se opacidade no eixo visual.",
sintomas:[
"BAIXA VISUAL GRADUAL e progressiva (meses-anos)",
"Visão embaçada (\"como vidro fosco\"), redução da nitidez",
"Halos coloridos noturnos em torno de luzes (faróis)",
"OFUSCAMENTO paradoxal em luz intensa (precisa fechar os olhos no sol)",
"Redução da visão de cores (especialmente azul)",
"Mudança frequente da prescrição óptica",
"Miopização (\"voltou a ler sem óculos\") — segunda visão paradoxal",
"REFLEXO VERMELHO diminuído ou ausente",
"Em catarata avançada: leucocoria (pupila branca visível)",
"Em catarata CONGÊNITA: leucocoria + nistagmo + estrabismo + reflexo vermelho ausente em RN/lactente — EMERGÊNCIA",
],
profilaxia:"FOTOPROTEÇÃO ocular com óculos UV (chapéu de aba larga + óculos com proteção UV400) desde infância. Cessar tabagismo. Controle de DM rigoroso. Uso de corticoide tópico/sistêmico apenas com indicação. Dieta rica em antioxidantes (vegetais verde-escuros, frutas vermelhas) — evidência fraca mas plausível. Rastreio oftalmológico anual em idoso, diabético, usuário de corticoide crônico.",
freire:"Idoso com baixa visual frequentemente atribui a 'idade — não tem jeito'. Educar: 'catarata tem TRATAMENTO, é a cirurgia mais comum do mundo, segura e eficaz; você pode voltar a enxergar muito bem'. Validar impacto: quedas, depressão, isolamento social, perda de autonomia decorrem de baixa visual não-tratada. Em DM: prevenção é controle glicêmico + fotoproteção. Em catarata congênita: orientar URGÊNCIA aos pais — janela curta de desenvolvimento visual.",
sus_tx:"NÃO HÁ TRATAMENTO CLÍNICO eficaz — colírios 'anti-catarata' são INEFICAZES (vendidos privadamente sem evidência). TRATAMENTO É CIRÚRGICO: FACECTOMIA com EMULSIFICAÇÃO + IMPLANTE DE LIO (lente intraocular monofocal padrão pelo SUS; LIOs multifocais/tóricas particulares). Indicação cirúrgica: quando a CATARATA INTERFERE NAS ATIVIDADES DIÁRIAS do paciente (dirigir, ler, trabalhar, atividades de vida diária) — decisão individualizada, não baseada apenas em medida de AV. CATARATA CONGÊNITA é EMERGÊNCIA — encaminhar oftalmo pediátrico em 24-48h; cirurgia idealmente nas primeiras 4-8 semanas em catarata bilateral, 4-6 semanas em unilateral (janela ambliópica). Em RN com qualquer alteração do reflexo vermelho (teste do reflexo vermelho = 'Teste do Olhinho' — Lei 19.435 SP e congêneres + obrigatório em maternidades): encaminhar oftalmo pediátrico URGENTE. MFC PRÉ-OPERATÓRIO: controle de DM/HAS, suspender AAS apenas se cirurgião pedir (geralmente não suspende), avaliação clínica de risco cirúrgico (em geral baixo, anestesia tópica/peribulbar). Pós-operatório: colírio antibiótico + corticoide por 4-6 sem (especialista).",
padrao_ouro:"Acrescenta: técnica FACO-EMULSIFICAÇÃO com lentes premium (multifocais, tóricas, EDOF) — fora SUS padrão; cirurgia robótica (FemtoLaser); biometria óptica (IOL Master); coadjuvância em DM (panfotocoagulação prévia se RD ativa). Acompanhamento: 1d, 7d, 30d, 90d pós-op.",
prog:"Cirurgia é uma das mais EFETIVAS e SEGURAS da medicina — >95% recuperação visual significativa. Complicações são raras (<2%): endoftalmite (~0,1%, prevenida com iodopovidona pré-op + ATB intracameral), descompensação corneana (em endotélio comprometido), opacificação capsular tardia (resolvido com YAG laser).",
acomp:"Após cirurgia: pós-operatório precoce em oftalmo (1d, 7d, 30d, 90d). Manutenção: oftalmo anual para vigilância de outras patologias (DMRI, RD, glaucoma). MFC: controle de DM/HAS continua + vigilância de baixa visual em outro olho.",
p4:"NÃO indicar 'colírios anti-catarata' — sem eficácia, custo desnecessário. NÃO esperar 'amadurecer a catarata' antes da cirurgia (conceito antigo); indicação é quando interfere na função. NÃO indicar cirurgia em paciente assintomático ou com baixa interferência funcional 'para prevenir'. NÃO confundir baixa visual de OUTRAS causas (DMRI, RD, glaucoma, ambliopia, mácula) com catarata isolada — oftalmo distingue. NÃO atrasar encaminhamento em catarata congênita — janela ambliópica é estreita.",
alertas:[
{nivel:"crit", txt:"⚠ CATARATA CONGÊNITA = EMERGÊNCIA. RN com REFLEXO VERMELHO ausente/anormal/assimétrico (Teste do Olhinho na maternidade ou em UBS) → encaminhar oftalmo pediátrico em 24-48h. Janela cirúrgica: 4-8 sem (bilateral) ou 4-6 sem (unilateral). Atraso = ambliopia irrecuperável + nistagmo permanente."},
{nivel:"crit", txt:"⚠ LEUCOCORIA (pupila branca) em criança: catarata congênita / retinoblastoma / persistência hiperplásica do vítreo / Coats / toxocara / etc. Encaminhar oftalmo pediátrico URGÊNCIA. Retinoblastoma é tumor letal se atrasado."},
{nivel:"warn", txt:"DM + CATARATA: catarata diabética acelerada, especialmente em DM mal-controlado. Hiperglicemia transitória pode causar miopização funcional (cristalino edemaciado) — antes de cirurgia, estabilizar glicemia. Avaliar RETINOPATIA DIABÉTICA antes da cirurgia (pode precisar tratamento prévio)."},
{nivel:"warn", txt:"CORTICOIDE TÓPICO OCULAR ou SISTÊMICO CRÔNICO: catarata subcapsular posterior é efeito adverso conhecido. Em pacientes em corticoide crônico (prednisona ≥7,5 mg/d por meses; colírio corticoide >6 m): avaliação oftalmo anual."},
{nivel:"warn", txt:"FATOR DE RISCO PARA QUEDAS em idoso com catarata. Avaliação multidimensional: visão + equilíbrio + audição + ambiente. Articulação com fisio/NASF, modificação domiciliar (iluminação, tapetes)."},
{nivel:"info", txt:"TESTE DO OLHINHO (reflexo vermelho) em RN: obrigatório em maternidades (Lei 19.435/2010 SP e congêneres por estado). Em UBS: realizar em puericultura primeira consulta + 6m + 12m + 24m. Aprendizado simples — qualquer profissional treinado realiza."},
{nivel:"info", txt:"INDICAÇÃO CIRÚRGICA é INDIVIDUALIZADA: AV não-corrigida + impacto em atividades (dirigir, ler, trabalhar). Paciente com AV 20/40 que dirige por trabalho pode ter indicação; AV 20/100 em paciente acamado pode não ter prioridade alta. Decisão compartilhada paciente-oftalmologista."},
],
diretriz:"[AAO Preferred Practice Pattern — Cataract 2021/2024] [CBO — Diretrizes Brasileiras de Catarata 2023] [Sociedade Brasileira de Oftalmologia Pediátrica — Catarata Congênita 2022]"
},

/* ============================================================
   2. DMRI + RETINOPATIA DIABÉTICA — rastreio MFC
   ============================================================ */
{
id:"dmri-retinopatia-diabetica", contexto:["ubs"], nome:"DMRI + Retinopatia Diabética — Rastreio Fundoscópico MFC",
sis:"oft", grav:"media",
cid:"H35.3, H36.0", ciap:"F83",
sin:["DMRI","degeneração macular relacionada à idade","drusas","retinopatia diabética","RD","retinopatia diabética não-proliferativa","retinopatia proliferativa","edema macular diabético","cegueira em DM"],
def:"DUAS DOENÇAS RETINIANAS PRINCIPAIS de prevalência crescente. DMRI: degeneração macular pela idade — DMRI SECA/NÃO-EXSUDATIVA (atrofia geográfica, drusas, ~85% — progressão lenta) vs DMRI ÚMIDA/EXSUDATIVA (neovascularização coroideana, ~15% — perda visual rápida, tratável com anti-VEGF). Principal causa de cegueira em >60a no mundo desenvolvido. RETINOPATIA DIABÉTICA: complicação microvascular do DM — RD NÃO-PROLIFERATIVA (NPDR — leve/moderada/grave) e RD PROLIFERATIVA (PDR — neovascularização, hemorragias, descolamento). EDEMA MACULAR DIABÉTICO (EMD) — perda visual aguda em qualquer estágio.",
intro:"DMRI e RD são CAUSAS COMUNS de CEGUEIRA EVITÁVEL. MFC: encaminhar rastreio fundoscópico em GRUPOS DE RISCO. EM DIABÉTICO: rastreio fundoscópico ANUAL é OBRIGATÓRIO (PCDT-MS DM2, ADA, SBD). EM IDOSO: avaliação oftalmológica anual após 60a com atenção à mácula. Reconhecer SINTOMAS DE ALARME (perda visual súbita, metamorfopsia, escotoma central novo) e encaminhar urgência. Anti-VEGF (intravítreo) revolucionou tratamento de DMRI úmida e EMD — disponível pelo SUS com PCDT específico.",
fisio:"DMRI: acúmulo de drusas (depósitos extracelulares sob EPR) → estresse oxidativo + inflamação + dano ao epitélio pigmentar retiniano (EPR) → atrofia (DMRI seca) ou crescimento de neovasos da coroide através da membrana de Bruch (DMRI úmida) → exsudação + hemorragia + cicatrização. Fatores: idade, tabagismo (forte), genética (CFH, ARMS2), fototipo claro, baixa ingestão de antioxidantes. RD: hiperglicemia crônica → glicação + estresse oxidativo + inflamação → dano microvascular retiniano → isquemia → liberação de VEGF → neovascularização frágil → hemorragias + edema + descolamento. Pior em HAS + dislipidemia + nefropatia + DM longa duração.",
apresentacao:"DMRI: idoso (>60a) com baixa visual CENTRAL gradual (DMRI seca) ou súbita (DMRI úmida), METAMORFOPSIA (linhas retas parecem onduladas — teste de Amsler), ESCOTOMA CENTRAL, redução da visão de leitura/cores. Visão periférica preservada (orienta-se no espaço, mas não reconhece face/lê). Ao fundo de olho: drusas, alterações pigmentares na mácula, atrofia geográfica (seca) ou hemorragia/edema subretiniano (úmida). RD: diabético de longa duração, frequentemente ASSINTOMÁTICO até estágio avançado (estímulo a RASTREIO). Pode apresentar baixa visual gradual (EMD) ou súbita (hemorragia vítrea da PDR). Ao fundo: microaneurismas, hemorragias 'em chama de vela'/dot-blot, exsudatos duros (depósitos lipídicos amarelos), exsudatos algodonosos (isquemia), tortuosidade venosa, neovasos em estágio proliferativo. EDEMA MACULAR: espessamento da mácula com perda visual central.",
sintomas:[
"DMRI: baixa visual CENTRAL gradual (seca) ou súbita (úmida); metamorfopsia (linhas onduladas); escotoma central; visão periférica preservada",
"DMRI úmida: ALARME — perda visual SÚBITA central; metamorfopsia nova ou piora rápida; encaminhamento URGÊNCIA (anti-VEGF altera prognóstico)",
"Teste de AMSLER auto-aplicado: paciente fixa o ponto central da grade; distorções/escotomas = alarme; recomendar em paciente com DMRI ou alto risco",
"RD precoce: ASSINTOMÁTICA — daí necessidade de rastreio ATIVO fundoscópico",
"RD avançada: baixa visual gradual (EMD), súbita (hemorragia vítrea / descolamento), perda de campo, miodesopsias 'flashes'",
"DM2 ao diagnóstico já pode ter RD (DM2 não-diagnosticado por anos); DM1 em geral 5-10a antes de RD evidente",
"Risco: duração do DM, A1c elevada, HAS, dislipidemia, nefropatia, gestação",
],
profilaxia:"DMRI: CESSAÇÃO DE TABAGISMO (fortemente eficaz), dieta rica em antioxidantes/ômega-3, fotoproteção UV, controle de HAS/dislipidemia, peso saudável. Suplementação AREDS-2 (luteína, zeaxantina, vit C, vit E, zinco, cobre) em DMRI INTERMEDIÁRIA-AVANÇADA — RECOMENDADA pelas diretrizes; uso preventivo populacional NÃO recomendado. RD: controle GLICÊMICO RIGOROSO (A1c <7% se possível, individualizado), controle de HAS (PA <130/80), dislipidemia (LDL conforme RCV), abandono do tabagismo, rastreio FUNDOSCÓPICO ANUAL.",
freire:"Paciente diabético frequentemente subestima riscos da retinopatia: 'meu DM tá controlado'. Educar: 'controle do açúcar é SEU TRABALHO, mas mesmo bem-controlado precisa REVISÃO de RETINA todo ano — porque a retinopatia pode aparecer sem nenhum sintoma e quando aparece sintoma já é avançada; tratamento precoce com laser ou injeção é muito eficaz, esperar = cegueira'. Em DMRI: educar sobre TESTE DE AMSLER caseiro (papel quadriculado, fixar centro); 'qualquer onda, falha, distorção nova = avisar oftalmo no mesmo dia'. Em idoso com baixa visual estabelecida: orientar adaptação (lupa, luz, contraste), articular AGA, suporte familiar.",
sus_tx:"FUNDOSCOPIA é o eixo do rastreio — IDEALMENTE feita por oftalmo com pupila DILATADA (midríase). Em UBS: oftalmoscopia direta SEM dilatação tem alcance limitado, mas pode identificar achados grosseiros (hemorragia, exsudato, edema macular). RASTREIO RD: TODO DIABÉTICO com pelo menos 1 fundoscopia/ano com oftalmo (telemedicina retinográfica em alguns serviços é alternativa). Em DM2: ao diagnóstico + anual. Em DM1: a partir de 5a de doença (10-15a se diag na infância) + anual. Em GESTANTE com DM prévio: rastreio no 1º trim + repetir no 3º trim/pós-parto (risco de progressão). RASTREIO DMRI: avaliação oftalmológica anual em idoso >60a, especialmente fototipo claro / tabagista / história familiar. SUPLEMENTAÇÃO em DMRI: AREDS-2 (luteína+zeaxantina+vit C+vit E+zinco+cobre) em DMRI intermediária-grave em pelo menos um olho — disponível em particular ou via SUS em alguns estados. TRATAMENTOS ESPECÍFICOS — ENCAMINHAR OFTALMO: anti-VEGF intravítreo (ranibizumabe, bevacizumabe off-label, aflibercepte) em DMRI úmida e EMD; fotocoagulação a laser em RD não-proliferativa grave ou RD proliferativa; vitrectomia em hemorragia vítrea persistente / descolamento de retina tracional. MFC: otimizar DM + HAS + dislipidemia + cessação tabagismo + dieta + atividade física = parte central do tratamento.",
padrao_ouro:"Acrescenta: TELEMEDICINA RETINOGRÁFICA (rastreio em UBS com câmera + interpretação remota — alguns programas estaduais); tomografia de coerência óptica (OCT — padrão-ouro para EMD/DMRI); angiografia fluoresceínica; anti-VEGF intravítreo seriado; faricimabe (novo, anti-VEGF + anti-angiopoietina); pelogetide; AREDS-2 formulação atual; suplementos com luteína.",
prog:"DMRI seca: progressão lenta, sem tratamento específico mas modificável com cessação tabagismo + AREDS-2 + manejo de RCV. DMRI úmida: anti-VEGF transformou prognóstico — estabilização ou melhora em maioria. RD: controle metabólico previne; tratamentos (anti-VEGF, fotocoagulação) estabilizam mas raramente revertem perda visual estabelecida. PRECOCE é a chave em ambas.",
acomp:"DM: oftalmo anual (mais frequente se RD evidente). DMRI: oftalmo semestral-anual conforme estágio; em DMRI úmida em tratamento com anti-VEGF: mensal/bimestral. Teste de Amsler caseiro mensal em DMRI / alto risco. MFC: A1c trimestral em DM, PA mensal-trimestral, lipidograma anual.",
p4:"NÃO indicar suplementos AREDS-2 em pessoa sem DMRI ou com DMRI INICIAL (sem benefício); apenas em DMRI intermediária-grave. NÃO substituir RASTREIO FUNDOSCÓPICO por 'paciente sem queixa não precisa de retina' — RD precoce é ASSINTOMÁTICA. NÃO indicar laser preventivo em RD sem indicação. NÃO usar anti-inflamatório/corticoide ocular sem oftalmo. NÃO ignorar METAMORFOPSIA NOVA em paciente com DMRI conhecida — é EMERGÊNCIA para anti-VEGF.",
alertas:[
{nivel:"crit", txt:"⚠ PERDA VISUAL SÚBITA UNILATERAL em paciente DM ou idoso: DMRI úmida com hemorragia / hemorragia vítrea diabética / oclusão venosa retiniana / descolamento de retina = ENCAMINHAR OFTALMO URGÊNCIA (24-48h)."},
{nivel:"crit", txt:"⚠ METAMORFOPSIA NOVA em paciente com DMRI conhecida = exsudação ativa = JANELA PARA ANTI-VEGF. Encaminhar oftalmo em 1-7 dias. Tratamento precoce preserva acuidade."},
{nivel:"crit", txt:"⚠ FLASHES + MIODESOPSIAS FLUTUANTES + 'CORTINA' NO CAMPO VISUAL = DESCOLAMENTO DE RETINA. EMERGÊNCIA — oftalmo no mesmo dia. Cirurgia em poucas horas-dias preserva visão."},
{nivel:"warn", txt:"DM RECÉM-DIAGNOSTICADO: já pode ter RD avançada (DM2 frequentemente subdiagnosticado por anos). FUNDOSCOPIA ao diagnóstico — não esperar 1 ano."},
{nivel:"warn", txt:"TABAGISMO em DMRI: principal fator de risco MODIFICÁVEL. Cessação reduz progressão. Intervenção breve + apoio + farmacoterapia (NRT, bupropiona, vareniclina) — essencial."},
{nivel:"warn", txt:"GESTANTE COM DM PRÉVIO: risco de PROGRESSÃO RÁPIDA de retinopatia. Fundoscopia no 1º trim + repetir no 3º trim/pós-parto. Em RD avançada: discutir com oftalmo manejo gestacional."},
{nivel:"info", txt:"TELEMEDICINA RETINOGRÁFICA está em expansão em alguns estados/municípios — câmera retiniana em UBS, interpretação remota por oftalmo. Permite rastreio em larga escala. Verificar disponibilidade local."},
{nivel:"info", txt:"TESTE DE AMSLER caseiro: papel quadriculado tamanho página, fixar o ponto central com um olho (cobrir o outro), notar se LINHAS estão retas, ou se há ONDULAÇÕES/FALHAS/MANCHAS. Mudança = alarme. Mensal em DMRI / alto risco."},
],
diretriz:"[AAO Preferred Practice Pattern — Age-Related Macular Degeneration 2022/2024] [AAO PPP — Diabetic Retinopathy 2022/2024] [PCDT-MS Tratamento da DMRI Úmida e EMD 2021] [SBD — Diretrizes 2024 — Retinopatia Diabética] [ADA Standards of Care 2024]"
},

/* ============================================================
   3. OLHO SECO — Síndrome do Olho Seco
   ============================================================ */
{
id:"olho-seco", contexto:["ubs"], nome:"Síndrome do Olho Seco — Diagnóstico e Manejo MFC",
sis:"oft", grav:"baixa",
cid:"H04.1", ciap:"F99",
sin:["olho seco","síndrome do olho seco","ceratoconjuntivite seca","Sjögren","disfunção lacrimal","DED","dry eye disease"],
def:"Doença multifatorial da superfície ocular caracterizada por PERDA DE HOMEOSTASE DO FILME LACRIMAL, com sintomas oculares (desconforto, ardência, sensação de areia, ressecamento, visão flutuante) e mediada por instabilidade do filme lacrimal, hiperosmolaridade, inflamação e dano à superfície. Dois mecanismos principais: EVAPORATIVO (mais comum, 80% — disfunção das glândulas de Meibomius/MGD, blefarite) e DEFICIÊNCIA AQUOSA (síndrome de Sjögren primária/secundária, idosos, pós-radioterapia, medicações).",
intro:"Olho seco é EXTREMAMENTE comum — prevalência ~10-30% em adultos, maior em idosos, mulheres, usuários de tela. MFC: diagnóstico clínico (sintomas + alguns testes simples), descartar causas secundárias (Sjögren, drogas, cirurgia refrativa, lentes de contato, BLEFARITE associada), manejo conservador com LUBRIFICAÇÃO + higiene palpebral + compressas mornas, encaminhar oftalmo em casos refratários ou suspeita de Sjögren.",
fisio:"Filme lacrimal = camada lipídica (Meibomius) + aquosa (lacrimal principal/acessórias) + mucínica (células caliciformes). Disfunção em qualquer camada → instabilidade. EVAPORATIVO: disfunção meibomiana → menos lipídio → evaporação acelerada da lágrima. AQUOSO: redução de produção lacrimal — Sjögren (autoimune contra glândulas exócrinas), envelhecimento, pós-cirurgia/radioterapia. Hiperosmolaridade resultante → estresse osmótico → inflamação na superfície → ciclo de auto-perpetuação.",
apresentacao:"Adulto (mais idosos + mulheres) com sintomas crônicos/intermitentes de desconforto ocular: SENSAÇÃO DE AREIA / corpo estranho, ARDÊNCIA, RESSECAMENTO, FOTOFOBIA leve, VISÃO FLUTUANTE (melhora ao piscar — diferencial com refrativo), LACRIMEJAMENTO PARADOXAL (olho seco IRRITADO produz hipersecreção reflexa — paciente diz 'meu olho lacrimeja muito mas é seco'), piora ao final do dia, em ambientes secos/ar condicionado/avião, ao usar telas (redução de piscar). HIPEREMIA conjuntival difusa. Em casos graves: ceratite ponteada (pontos epiteliais corados na fluoresceína), erosões corneanas. PALPEBRAS: pode haver blefarite associada (margens palpebrais inflamadas, secreção espumosa em pestanas — MGD).",
sintomas:[
"Sensação de AREIA ou corpo estranho",
"Ardência, queimação, irritação",
"Ressecamento",
"FOTOFOBIA leve a moderada",
"Visão flutuante que melhora ao piscar (diferencial com refrativo)",
"Lacrimejamento paradoxal (olho seco irritado = produção reflexa de lágrima)",
"Piora vespertina, em ar seco, ar condicionado, vento, telas (redução do piscar)",
"Sensação de pálpebras pesadas/cansadas",
"Em casos graves: dor, baixa visual, fotofobia importante",
"PIORA em uso de lentes de contato",
],
profilaxia:"PISCAR ATIVAMENTE em uso de telas (regra 20-20-20: a cada 20 min, olhar 20 segundos para algo a 20 pés / 6 m de distância). Umidificar ambiente. Evitar ventiladores/ar condicionado direto. Higiene palpebral em MGD/blefarite (compressas mornas + massagem suave). Cessação de tabagismo. Dieta rica em ômega-3 (peixe, linhaça — evidência moderada). Pausa de telas. Em uso de lentes de contato: higiene + tempo de uso adequado.",
freire:"Paciente com olho seco frequentemente sofre por anos sem diagnóstico — 'olho cansado', 'fico no computador demais', 'é da idade'. Validar como doença real, crônica, tratável. Educar sobre PISCAR (em uso prolongado de tela paciente pisca 30-50% menos), umidificação, compressas mornas. Tranquilizar sobre BENIGNIDADE (não cega), mas CRONICIDADE (manejo contínuo, não cura definitiva). Em mulher de meia-idade com olho seco + boca seca + artralgia: pensar em SJÖGREN — solicitar autoanticorpos (FAN, anti-Ro/SSA, anti-La/SSB) e encaminhar reumato.",
sus_tx:"LUBRIFICAÇÃO ARTIFICIAL é o eixo: COLÍRIO LUBRIFICANTE (lágrimas artificiais) — preferir sem conservante em uso frequente (>4×/dia). Disponibilidade no SUS: limitada — algumas UBS têm hipromelose/carmelose; usuário frequentemente compra particular (Lacribell, Refresh, Systane, Hyabak). Aplicar 4-6×/dia. EM CASOS MAIS GRAVES: gel/pomada à noite. HIGIENE PALPEBRAL em MGD/blefarite: compressas mornas 5-10 min 2×/dia + massagem palpebral suave + limpeza com shampoo neutro infantil ou produtos específicos (Blephagel, Blephaclean) na linha das pestanas. CICLOSPORINA 0,05% COLÍRIO 1 gota em cada olho 12/12h (Restasis® — particular ou via CEAF em alguns estados com PCDT específico) em olho seco moderado-grave — efeito após 4-12 semanas; uso contínuo. ENCAMINHAR OFTALMO se: refratariedade ao manejo conservador, suspeita de Sjögren, achados de ceratite/úlcera corneana, baixa visual associada. EM SJÖGREN SUSPEITA: solicitar AUTOANTICORPOS (FAN, anti-Ro/SSA, anti-La/SSB) + investigar sintomas sistêmicos (boca seca/xerostomia, artralgia, fadiga, manifestações outras) + encaminhar REUMATO.",
padrao_ouro:"Acrescenta: lubrificantes premium (gel, sem conservantes, com hialuronato/trealose); CICLOSPORINA 0,05% (Restasis®) 1 gota 12/12h ou CICLOSPORINA 0,1% (Ikervis®) 1 gota à noite; lifitegrast (anti-LFA-1 — Xiidra); soro autólogo 20% colírio (em centro especializado); plugs lacrimais (oclusão temporária da via lacrimal — derma/oftalmo); LipiFlow (terapia térmica meibomiana); IPL (luz pulsada) periocular; punctoplastia.",
prog:"Crônico, flutuante. Bem-manejado: vida normal. Não-tratado: desconforto persistente, possível progressão a ceratite/úlcera/comprometimento visual.",
acomp:"Reavaliar 4-8 sem após início. Estável: trimestral-semestral. Avaliar adesão à lubrificação, higiene palpebral, identificação de gatilhos, sintomas de Sjögren sistêmicos.",
p4:"NÃO usar colírio DESCONGESTIONANTE (nafazolina, oximetazolina — 'Visine') CRONICAMENTE — efeito rebote, piora olho seco. NÃO usar colírio com CORTICOIDE sem oftalmo — risco de glaucoma + catarata + infecção. NÃO indicar ATB tópico rotina sem infecção. NÃO usar antihistamínico tópico crônico sem indicação (pode ressecar mais). NÃO atribuir TODA queixa ocular crônica a 'olho seco' sem descartar outras (glaucoma de ângulo aberto, alergias, etc.).",
alertas:[
{nivel:"warn", txt:"SJÖGREN SUSPEITA: mulher meia-idade com olho seco + BOCA SECA (xerostomia) + ARTRALGIA ± fadiga ± parotidite recorrente ± vasculite. Solicitar FAN, anti-Ro/SSA, anti-La/SSB + encaminhar reumato. Associação com linfoma MALT (10× risco) — vigilância."},
{nivel:"warn", txt:"DROGAS QUE CAUSAM OLHO SECO: anti-histamínicos (loratadina, dexclorfeniramina), antidepressivos (especialmente TCA), anti-hipertensivos (BB, diuréticos), retinoides VO (isotretinoína), oxibutinina, anticolinérgicos em geral, isotretinoína. Revisar medicação em olho seco refratário."},
{nivel:"warn", txt:"CERATITE / ÚLCERA CORNEANA: dor + fotofobia importante + baixa visual + hiperemia ciliar (vasos profundos perilimbares) = ENCAMINHAR OFTALMO URGÊNCIA. Em usuário de lentes de contato: especialmente preocupante (Pseudomonas, Acanthamoeba)."},
{nivel:"warn", txt:"COLÍRIOS COM CONSERVANTES (cloreto de benzalcônio) em uso frequente (>4-6×/dia): toxicidade epitelial, piora paradoxal de olho seco. Preferir UNIDOSE ou frascos sem conservantes em uso frequente."},
{nivel:"info", txt:"REGRA 20-20-20 para usuários de tela: a cada 20 min, olhar para algo a 20 pés (6 m) por 20 segundos. Restaura piscar, reduz fadiga visual."},
{nivel:"info", txt:"COMPRESSAS MORNAS (não quentes) 5-10 min em pálpebras fechadas + massagem palpebral suave de 'cima para baixo' (drena meibomius) = manejo gratuito e altamente eficaz em MGD/blefarite (causa #1 de olho seco evaporativo)."},
],
diretriz:"[TFOS DEWS II 2017 — Definition and Classification] [AAO PPP — Dry Eye Syndrome 2023] [SBO — Consenso Brasileiro de Olho Seco 2022]"
},

/* ============================================================
   4. BLEFARITE + HORDÉOLO + CALÁZIO
   ============================================================ */
{
id:"blefarite-hordeolo-calazio", contexto:["pa","ubs"], nome:"Blefarite + Hordéolo + Calázio — Patologias Palpebrais Comuns",
sis:"oft", grav:"baixa",
cid:"H01, H00", ciap:"F72",
sin:["blefarite","hordéolo","terçol","calázio","cálazio","inflamação palpebral","MGD","disfunção meibomiana"],
def:"Três entidades inflamatórias palpebrais frequentes. BLEFARITE: inflamação crônica da margem palpebral — anterior (escamas/crostas em pestanas — Staphylococcus, seborreia) ou posterior (disfunção meibomiana / MGD — placas amarelo-cerosas tampando orifícios). HORDÉOLO ('terçol'): infecção aguda de glândula palpebral — externo (Zeis/Moll, com pestana envolvida) ou interno (Meibomius, mais profundo). Geralmente Staphylococcus aureus. CALÁZIO: lipogranuloma estéril por obstrução crônica de glândula de Meibomius — nódulo indolor após resolução de hordéolo ou MGD crônico.",
intro:"Patologias palpebrais são EXTREMAMENTE comuns em UBS. MFC: distinguir entre as três (apresentação, dor, evolução), manejo conservador (compressas mornas + higiene + ATB tópico em hordéolo agudo), encaminhar oftalmo em calázio persistente, hordéolo refratário, ou suspeita de neoplasia (calázio recidivante mesmo local em idoso = pensar CARCINOMA SEBÁCEO — raro mas letal).",
fisio:"BLEFARITE ANTERIOR: colonização exagerada de S. aureus + dermatite seborreica (Malassezia) na margem palpebral → inflamação. BLEFARITE POSTERIOR (MGD): obstrução das glândulas de Meibomius (que produzem lipídio do filme lacrimal) → estase → inflamação + colonização → secreção alterada. HORDÉOLO: infecção aguda bacteriana (geralmente S. aureus) de glândulas palpebrais — Zeis/Moll (externo) ou Meibomius (interno). CALÁZIO: granuloma lipogranulomatoso ESTÉRIL por extravasamento de conteúdo glandular após obstrução crônica — frequentemente sequela de hordéolo interno ou MGD crônico.",
apresentacao:"BLEFARITE: paciente com sintomas crônicos — ardência, prurido palpebral, sensação de corpo estranho, lacrimejamento, vermelhidão das margens palpebrais, escamas/crostas em pestanas (anterior) ou MGD (posterior — secreção espumosa visível ao expressar pálpebra). Frequentemente em paciente com dermatite seborreica facial ou rosácea ocular. HORDÉOLO: NÓDULO DOLOROSO + ERITEMA + EDEMA em margem palpebral (externo) ou em corpo palpebral (interno) — agudo, surge em 1-3 dias. Pode haver ponta amarelada (drenagem espontânea próxima). CALÁZIO: NÓDULO INDOLOR + FIRME na espessura palpebral, sem eritema agudo (ou eritema leve residual), sem sinais inflamatórios francos — evolução de semanas. Pode comprimir córnea (astigmatismo induzido).",
sintomas:[
"BLEFARITE: ardência, prurido, sensação de areia, vermelhidão das margens, escamas/crostas em pestanas, secreção espumosa (MGD), piora pela manhã",
"BLEFARITE associada: dermatite seborreica facial, rosácea, olho seco",
"HORDÉOLO: NÓDULO DOLOROSO + eritema + edema agudo em margem (externo) ou corpo palpebral (interno); pode evoluir para drenagem espontânea",
"CALÁZIO: nódulo INDOLOR firme em espessura palpebral, evolução crônica (semanas), sem sinais inflamatórios francos",
"Em criança: blefarites recidivantes/extensas — investigar molusco contagioso palpebral, atopia",
"Em idoso: calázio RECIDIVANTE no mesmo local → suspeitar CARCINOMA SEBÁCEO (raro, mas grave)",
],
profilaxia:"HIGIENE PALPEBRAL diária em paciente com tendência: compressas mornas 5-10 min + massagem suave + limpeza com shampoo neutro infantil ou produto específico (Blephagel, Blephaclean, lenços oculares) na linha das pestanas. Em rosácea/MGD: doxiciclina VO pode ajudar prevenção (efeito anti-inflamatório). Cuidado em uso prolongado de lentes de contato (limpeza adequada).",
freire:"Paciente com 'terçol' frequentemente busca UBS angustiado, querendo ATB tópico/sistêmico — educar que MAIORIA RESOLVE COM COMPRESSAS MORNAS + HIGIENE em 5-7 dias, sem ATB. Em blefarite crônica: educar sobre TRATAMENTO DIÁRIO (higiene palpebral é o trabalho diário do paciente, não medicação que cura) — não cura, controla. Combater estigma social ('é contagioso? meu filho pode pegar?' — pouca transmissibilidade real). Em calázio que não some: orientar incisão e curetagem em oftalmo (procedimento simples ambulatorial).",
sus_tx:"BLEFARITE: HIGIENE PALPEBRAL DIÁRIA é o eixo (compressas mornas 5-10 min 2×/dia + massagem suave + limpeza com shampoo neutro infantil — gratuito e eficaz). Em flare/exacerbação: ATB tópico ocular (TOBRAMICINA colírio ou pomada — UBS conforme disponibilidade) 4×/dia por 7-10 dias na linha das pestanas (com cotonete). Em MGD severo/refratário/rosácea ocular: DOXICICLINA 100 mg VO 1-2×/dia por 6-12 sem (anti-inflamatório, modulador meibomiano — UBS) ou azitromicina pulsada. HORDÉOLO: COMPRESSAS MORNAS 10-15 min 4-6×/dia (eixo do tratamento) + ATB tópico ocular (tobramicina ou cipro colírio, 4×/dia por 5-7 dias). Sistêmico (CEFALEXINA 500 mg VO 6/6h por 7 dias — UBS; ou AMOXICILINA+CLAVULANATO 500+125 mg VO 8/8h por 7-10 dias — UBS) em hordéolo refratário, com celulite preseptal associada, ou imunodeprimido. AUTOLIMITADO geralmente em 5-7 dias. NÃO ESPREMER (risco difusão). CALÁZIO: COMPRESSAS MORNAS + MASSAGEM SUAVE 2-3×/dia por 4-6 sem (eixo — 50% resolvem). Se persistir após 4-6 sem: encaminhar OFTALMO para INCISÃO + CURETAGEM (procedimento ambulatorial simples) ou injeção intralesional de TRIANCINOLONA. ENCAMINHAR oftalmo: hordéolo refratário, calázio persistente >6 sem, calázio RECIDIVANTE NO MESMO LOCAL (especialmente idoso — biópsia para CARCINOMA SEBÁCEO).",
padrao_ouro:"Acrescenta: terapia térmica meibomiana (LipiFlow); luz pulsada intensa (IPL) periocular; biópsia de calázio recidivante; produtos específicos de higiene palpebral; lentes umectantes em MGD.",
prog:"BLEFARITE: crônica, manejável com higiene; flares periódicos. HORDÉOLO: autolimitado em 5-7 dias na maioria. CALÁZIO: 50% resolvem com compressa morna; restantes precisam incisão/triancinolona (procedimento simples). Recidivância NO MESMO LOCAL em idoso = ALARME para carcinoma sebáceo.",
acomp:"Blefarite: reavaliar 4-6 sem após início; manutenção crônica com higiene. Hordéolo: reavaliar 7-10 dias (resolução esperada). Calázio: reavaliar 4-6 sem.",
p4:"NÃO ESPREMER hordéolo (risco celulite/disseminação). NÃO usar CORTICOIDE TÓPICO OCULAR isolado sem oftalmo (risco de glaucoma, catarata, mascarar herpes). NÃO confundir HORDÉOLO (doloroso, agudo) com CALÁZIO (indolor, crônico). NÃO usar ATB sistêmico em hordéolo NÃO-COMPLICADO. NÃO ignorar calázio RECIDIVANTE no mesmo local em idoso — biópsia.",
alertas:[
{nivel:"crit", txt:"⚠ CELULITE PRESEPTAL evoluindo para CELULITE ORBITÁRIA: hordéolo/calázio complicado com edema palpebral extenso, proptose, dor à movimentação ocular, restrição de motilidade, baixa visual, febre = EMERGÊNCIA. Encaminhar PS / hospitalar — ATB IV (ceftriaxona + clinda), TC órbita."},
{nivel:"warn", txt:"CALÁZIO RECIDIVANTE NO MESMO LOCAL em IDOSO: pensar em CARCINOMA SEBÁCEO (raro, mas grave, alta morbimortalidade se atrasado). Diferencial também com basocelular palpebral. BIOPSIAR — encaminhar oftalmo / derma."},
{nivel:"warn", txt:"BLEFARITE em CRIANÇA com RECIDIVA frequente: investigar MOLUSCO CONTAGIOSO palpebral (pápulas umbilicadas perto do cílio), atopia, parasitoses pestaneiras (Phthirus pubis em cílios em criança — investigar abuso); em adolescente — acne rosácea ocular."},
{nivel:"warn", txt:"ROSÁCEA OCULAR: blefarite + meibomite + telangiectasias palpebrais + olho seco + sensibilidade ocular + frequentemente associada à rosácea facial. Doxiciclina VO 100 mg 1×/dia por 8-12 sem é eficaz."},
{nivel:"info", txt:"COMPRESSAS MORNAS em todas: NÃO QUENTES (risco queimadura) — toalha morna (~40°C), aplicar 5-15 min, várias vezes ao dia. Maioria dos pacientes melhora drasticamente com isso isolado."},
{nivel:"info", txt:"NÃO ESPREMER hordéolo — ele drena espontaneamente quando 'pronto'. Espremer disseminada infecção e pode evoluir para celulite. Compressa morna acelera maturação e drenagem espontânea."},
],
diretriz:"[AAO PPP — Blepharitis 2018/2024] [TFOS DEWS II 2017] [SBO — Doenças Palpebrais 2022]"
},

/* ============================================================
   5. PTERÍGIO — neoformação conjuntival
   ============================================================ */
{
id:"pterigio", contexto:["ubs"], nome:"Pterígio — Avaliação MFC e Critério Cirúrgico",
sis:"oft", grav:"baixa",
cid:"H11.0", ciap:"F99",
sin:["pterígio","carne crescida no olho","crescimento conjuntival","neoformação conjuntival","pinguécula"],
def:"Crescimento fibrovascular benigno da conjuntiva bulbar invadindo a córnea, geralmente em lado NASAL (90%). Resultado da exposição crônica à RADIAÇÃO UV + vento + poeira + clima seco. Comum em populações tropicais, ao ar livre, agricultores, pescadores. Distinto de PINGUÉCULA (lesão amarelada na conjuntiva sem invadir córnea — variante mais leve, mais comum, sem mesmo risco).",
intro:"Pterígio é EXTREMAMENTE comum no Brasil — incidência alta especialmente em populações rurais, agricultores, pescadores, motoristas, profissionais ao ar livre. MFC: diagnóstico clínico fácil, educar sobre FOTOPROTEÇÃO (eixo da prevenção secundária), manejo conservador em lesões pequenas/estáveis (lubrificante, vasoconstritor leve em flares), encaminhar oftalmo para cirurgia em lesões progressivas, dor crônica, astigmatismo significativo, ou invasão do eixo visual.",
fisio:"Exposição CRÔNICA à RADIAÇÃO UV → dano nas células-tronco do limbo (margem corneoescleral) → proliferação fibrovascular conjuntival → invasão da córnea com 'cabeça' avançando + 'corpo' na conjuntiva bulbar. Componentes inflamatórios (em flares — vermelhidão, edema). Reaparece após cirurgia em 30-50% se não usar antimitótico/transplante adjuvante.",
apresentacao:"Adulto trabalhador ao ar livre (agricultor, pescador, construtor, motorista, vendedor ambulante) com 'crescimento de carne no olho', em LADO NASAL bilateral em geral. Pode ser ASSINTOMÁTICO em fase estável ou SINTOMÁTICO em flare (hiperemia + ardência + sensação de corpo estranho). Em avanço sobre córnea: pode induzir ASTIGMATISMO (queixa visual) e em casos extremos invadir EIXO VISUAL (baixa visual). PINGUÉCULA: lesão amarelada na conjuntiva interpalpebral (lateral à córnea, mais nasal), SEM invasão corneana, geralmente assintomática.",
sintomas:[
"Crescimento fibrovascular na conjuntiva, geralmente NASAL, invadindo córnea",
"Em flares: ardência, sensação de areia, vermelhidão, lacrimejamento, fotofobia",
"Em pterígio AVANÇADO: astigmatismo (visão borrada), em casos extremos invasão do eixo visual com baixa visual",
"História de EXPOSIÇÃO SOLAR/UV CRÔNICA + vento + poeira",
"Bilateralidade frequente (assimétrica)",
"PINGUÉCULA: lesão amarelada NA CONJUNTIVA SEM invadir córnea — assintomática em geral, sem urgência",
],
profilaxia:"FOTOPROTEÇÃO OCULAR: óculos com proteção UV400 + chapéu de aba larga em exposição ao ar livre. Lubrificação ocular em ambientes secos. Vasoconstritor tópico em flares (curto prazo). Cessação de tabagismo. EM PROFISSIONAIS AO AR LIVRE: orientar EPI ocular (óculos protetores) — articulação com medicina do trabalho.",
freire:"Paciente com pterígio frequentemente quer 'arrancar essa carne' — explicar que CIRURGIA TEM INDICAÇÃO ESPECÍFICA (avanço progressivo + comprometimento visual + dor crônica não-controlada) e que RECIDIVA é frequente (30-50%) se não houver fotoproteção adequada após. Educar TRABALHADOR RURAL/AO AR LIVRE: 'óculos com UV não é luxo, é equipamento de proteção tão essencial quanto bota e chapéu — previne pterígio, catarata, DMRI e câncer de pele palpebral'. Validar incômodo estético sem subestimar (é parte do impacto na qualidade de vida).",
sus_tx:"MANEJO CONSERVADOR em pterígio ESTÁVEL/PEQUENO: LUBRIFICANTES OCULARES (lágrimas artificiais sem conservante — carmelose 0,5%, hidroxipropilmetilcelulose) 1-2 gotas em cada olho 4-6×/dia ou conforme sintomas — UBS conforme disponibilidade ou particular; VASOCONSTRITOR TÓPICO (tetra-hidrozolina, nafazolina) 1 gota 2-3×/dia em FLARE — uso curto (<5 dias) para não causar rebote — particular; AINE TÓPICO em flare inflamatório curto: CETOROLACO COLÍRIO 0,5% 1 gota 4×/dia por 5-7 dias (particular) ou DICLOFENACO COLÍRIO 0,1% 1 gota 4×/dia por 5-7 dias (particular). EM INFLAMAÇÃO MAIS INTENSA: corticoide tópico baixa-média potência por curto período sob supervisão oftalmo — FLUOROMETOLONA 0,1% 1 gota 4×/dia por 5-7 dias (não usar prolongado pelo risco de glaucoma e catarata). CIRURGIA: indicada em — (1) avanço progressivo (documentado em fotos seriadas), (2) invasão do eixo visual ou com astigmatismo significativo afetando AV, (3) sintomas inflamatórios CRÔNICOS NÃO-CONTROLADOS, (4) impacto estético importante (não é razão exclusiva mas pode entrar em decisão compartilhada). Técnica preferida: EXCISÃO + AUTOENXERTO CONJUNTIVAL (cobertura com conjuntiva sadia do mesmo paciente — reduz recidiva para ~5-10%). Alternativa: excisão + mitomicina-C tópica + autoenxerto/membrana amniótica — derma/oftalmo. SUS oferece cirurgia em centros referenciados. FOTOPROTEÇÃO RIGOROSA APÓS — sem isso, recidiva certa.",
padrao_ouro:"Acrescenta: técnica de autoenxerto conjuntival com cola de fibrina; transplante de membrana amniótica; mitomicina-C 0,02% intraoperatória adjuvante; bevacizumabe subconjuntival adjuvante (estudo); cirurgia em centros com microscopia de alta resolução.",
prog:"Bom em maioria. Pterígio pequeno/estável: pode acompanhar conservadoramente por anos sem indicação cirúrgica. Pós-cirúrgico: recidiva ~5-10% com autoenxerto (mais com excisão simples ~30-50%).",
acomp:"Conforme estabilidade. Pterígio pequeno: anual com fotografia para detectar progressão. Pós-cirurgia: oftalmo 1d, 7d, 30d, 3m, 6m.",
p4:"NÃO indicar cirurgia em pterígio PEQUENO/ESTÁVEL sem queixas funcionais — risco cirúrgico + recidiva. NÃO usar vasoconstritor ocular CRONICAMENTE — efeito rebote. NÃO confundir pterígio com PINGUÉCULA (não invade córnea, sem indicação cirúrgica habitual). NÃO ignorar lesão pigmentada na conjuntiva (mancha negra) — diferencial NEVO/MELANOMA conjuntival → oftalmo.",
alertas:[
{nivel:"warn", txt:"PTERÍGIO ATÍPICO: bilateralidade muito assimétrica, crescimento rápido, lado temporal (não-nasal), pigmentado, em paciente jovem sem fator de exposição = ENCAMINHAR OFTALMO para descartar OSSN (Ocular Surface Squamous Neoplasia) ou neoplasia conjuntival."},
{nivel:"warn", txt:"PIGMENTAÇÃO CONJUNTIVAL focal (mancha negra/marrom): pode ser NEVO conjuntival, MELANOSE racial (mais comum em pele negra), ou MELANOMA conjuntival (raro mas grave). Encaminhar oftalmo se: crescimento, espessamento, vascularização, sintomas."},
{nivel:"warn", txt:"FOTOPROTEÇÃO OCULAR em TRABALHADOR AO AR LIVRE (agricultor, pescador, construtor, motorista, vendedor ambulante, gari): direito a EPI ocular adequado — óculos com proteção UV. Articulação com medicina do trabalho. Pterígio relacionado ao trabalho pode ser causa de NTEP (Nexo Técnico Epidemiológico Previdenciário)."},
{nivel:"info", txt:"INDICAÇÃO CIRÚRGICA é por SINTOMAS + PROGRESSÃO documentada, não por tamanho isolado. Pterígio pequeno estável em pé-de-jardineiro de 80 anos pode ser conduzido conservadoramente; pterígio progressivo em pessoa de 40a com risco de invasão visual precisa cirurgia."},
{nivel:"info", txt:"PRÉ-OPERATÓRIO: educar paciente sobre RECIDIVA (~10% com autoenxerto, mais sem) — fotoproteção rigorosa pós-op é parte do tratamento."},
],
diretriz:"[AAO PPP — Conjunctivitis 2024] [SBO — Cirurgia de Pterígio 2023]"
},

/* ============================================================
   6. AVALIAÇÃO DE ACUIDADE VISUAL MFC
   ============================================================ */
{
id:"avaliacao-acuidade-visual-mfc", contexto:["ubs"], nome:"Avaliação de Acuidade Visual na MFC — Snellen + Conduta",
sis:"oft", grav:"baixa",
cid:"Z01.0, H54", ciap:"F71",
sin:["acuidade visual","tabela de Snellen","baixa visual","ametropia","miopia","hipermetropia","astigmatismo","presbiopia","cegueira"],
def:"Avaliação da AV em consulta de rotina MFC é INSTRUMENTO BÁSICO para identificar pacientes com baixa visual e direcionar para correção óptica (refrativa — óculos) ou investigação clínica (catarata, DMRI, RD, glaucoma, etc.). Tabela de SNELLEN é o padrão (medida em 5 ou 6 metros — adaptada). Resultado expresso em fração: numerador = distância de aferição (5/5 ou 6/6), denominador = distância em que pessoa NORMAL veria aquele optótipo. AV 20/20 = visão normal; 20/40 = vê a 20 pés o que normal vê a 40 (limite inferior para dirigir, geralmente). CEGUEIRA LEGAL: AV ≤ 20/200 no melhor olho com melhor correção, OU campo visual ≤ 20°.",
intro:"AV é instrumento POUCO usado em MFC mas DEVERIA SER ROTINEIRO — especialmente em criança, idoso, diabético, queixa visual. RASTREIO DE ACUIDADE VISUAL: criança em puericultura (4-5a, 6a, 8a, 10a — saúde escolar), idoso anual a partir de 60a, diabético anual, motorista profissional, queixa visual em qualquer idade. Em UBS: ter TABELA DE SNELLEN impressa + iluminação adequada + distância padronizada (5-6 m em corredor / sala marcada). PROCEDIMENTO SIMPLES, RÁPIDO (5 min), de ALTO RENDIMENTO.",
fisio:"AV mede capacidade do sistema visual de discriminar detalhes finos (ângulo visual mínimo). Depende de: meios oculares transparentes (córnea, cristalino, vítreo), retina íntegra (especialmente mácula), nervo óptico e via visual centrais funcionais. Erros REFRATIVOS (miopia, hipermetropia, astigmatismo, presbiopia) reduzem AV mas são CORRIGÍVEIS com óculos. Patologias estruturais reduzem AV NÃO-CORRIGÍVEL com refração — exigem manejo específico.",
apresentacao:"Paciente em consulta MFC — aferição como SINAL VITAL ocular. Procedimento: (1) Posicionar paciente a 5-6 m da tabela (marcar no chão); (2) Iluminação adequada da tabela; (3) Ocluir um olho com palma da mão / oclusor opaco (NÃO empurrar globo) — testar UM OLHO POR VEZ; (4) Ler de cima para baixo até a menor linha lida COM ACERTOS; (5) Anotar fração — '20/20' = última linha lida foi 20/20; (6) Repetir outro olho; (7) Se usa óculos: aferir COM correção (AV corrigida — AVCC); registrar se diferente da sem correção. ATALHOS em paciente que não lê: 'tabela E' (Snellen E direcionada — paciente indica direção do E), figuras (criança pré-escolar), conta dedos a 30 cm, movimentos de mão a 30 cm, percepção luminosa, sem percepção luminosa.",
sintomas:[
"PROCEDIMENTO DE AFERIÇÃO: tabela de Snellen a 5-6 m + iluminação + um olho por vez + COM E SEM correção",
"AV NORMAL (20/20 ou melhor) — sem necessidade de investigação refrativa adicional",
"AV REDUZIDA que MELHORA com correção (óculos do paciente) ou com PINHOLE (orifício estenopeico — improvisado com cartão furado) = ERRO REFRATIVO → encaminhar oftalmo/optometrista",
"AV REDUZIDA que NÃO melhora com pinhole = causa NÃO-REFRATIVA → investigar (catarata, DMRI, RD, glaucoma, ambliopia, neurológica) → encaminhar oftalmo",
"BAIXA VISUAL UNILATERAL recente = ALARME (AVC retiniano, oclusão venosa/arterial, neurite óptica, descolamento, hemorragia vítrea) → oftalmo URGÊNCIA",
"CEGUEIRA LEGAL: AV ≤ 20/200 melhor olho com correção OU campo ≤ 20° → encaminhar + benefícios sociais (BPC/LOAS)",
],
profilaxia:"RASTREIO ATIVO em consultas MFC: criança (puericultura 4a, 6a, 8a, 10a; saúde escolar), idoso anual ≥60a, diabético anual ao diagnóstico, queixa visual em qualquer idade. EM CRIANÇA com BV unilateral: AMBLIOPIA é grande questão (janela 6-10a) — encaminhamento PRECOCE crítico.",
freire:"Educar sobre AV como SINAL VITAL ocular. Em paciente com BV não-detectada: 'você se acostumou com a visão como está, mas ela pode ser melhor — vamos ver se é uma questão de óculos ou se precisamos investigar mais'. Em CRIANÇA com possível ambliopia (\"olho preguiçoso\"): URGÊNCIA dos pais — janela ambliópica é 6-10 anos, depois tratamento perde eficácia. Em IDOSO com BV progressiva atribuída à 'idade': frequentemente CATARATA tratável.",
sus_tx:"AFERIR AV em consulta de rotina, especialmente em: criança em puericultura (todas), saúde escolar (programa do MS), idoso anual ≥60a, diabético anual, hipertenso, queixa visual em qualquer idade. Em CRIANÇA pré-escolar: tabela E + figuras; em pré-alfabetizada: encaminhar oftalmo pediátrico para AV objetiva. ENCAMINHAR OFTALMO: AV<20/40 em adulto sem causa óbvia / AV<20/30 em criança / qualquer baixa visual aguda / baixa visual em paciente com fator de risco (DM, HAS, idoso). EM ERRO REFRATIVO SUSPEITO: pinhole melhora AV → encaminhar para refração. Em emergências (perda visual súbita, dor, trauma, glaucoma agudo): EMERGÊNCIA. Em programas de saúde escolar do MS: AV é parte do exame obrigatório (Programa Saúde na Escola — PSE). Articular doação de óculos via município/parceiros em casos de vulnerabilidade.",
padrao_ouro:"Acrescenta: tabelas ETDRS (padrão científico, mais preciso); refração objetiva (autorrefrator, retinoscopia); refração subjetiva; ortóptica (criança com ambliopia/estrabismo); programa de doação de óculos institucional.",
prog:"Erros refrativos: correção com óculos = AV normal restaurada (se sem patologia adicional). Patologias estruturais: prognóstico depende da causa (catarata reversível; DMRI/RD parcialmente; glaucoma estável se controlado).",
acomp:"Anual em idoso, diabético, em PSE escolar. Imediato em queixa visual aguda. Educar criança/idoso para retorno se piora.",
p4:"NÃO presumir AV normal em paciente assintomático sem aferir — muitas BV não-detectadas. NÃO indicar óculos sem REFRAÇÃO de oftalmo/optometrista (auto-prescrição é problemática). NÃO atribuir BV a 'idade/diabetes/cansaço' sem investigar. NÃO confundir AMBLIOPIA infantil com 'preguiça' do olho — é entidade tratável com janela curta.",
alertas:[
{nivel:"crit", txt:"⚠ PERDA VISUAL SÚBITA (em horas-dias) — UNILATERAL ou bilateral: oclusão vascular (artéria ou veia central da retina), neurite óptica (mulher jovem — esclerose múltipla), descolamento de retina, hemorragia vítrea, AVC occipital, arterite de células gigantes (idoso >50a com cefaleia + claudicação mandibular — VHS↑). ENCAMINHAR OFTALMO/PS URGÊNCIA. Janela terapêutica curta para algumas (AVC retiniano, ACG)."},
{nivel:"crit", txt:"⚠ TRAUMA OCULAR com baixa visual: hifema, ruptura do globo, descolamento, hemorragia. NÃO TAMPONAR olho de paciente com suspeita de ruptura (pode prolapsar conteúdo). Encaminhar PS oftalmo URGENTE."},
{nivel:"warn", txt:"AMBLIOPIA (\"olho preguiçoso\") em CRIANÇA: AV reduzida em UM ou ambos olhos por desuso na infância (estrabismo, anisometropia, deprivação por catarata congênita). JANELA DE TRATAMENTO até ~6-10 anos. Encaminhamento precoce a oftalmo pediátrico para oclusão/correção. Após janela: tratamento perde eficácia."},
{nivel:"warn", txt:"AV ASSIMÉTRICA EM CRIANÇA: AV diferente entre olhos (anisocoria visual >2 linhas) = ALARME para ambliopia, estrabismo, anisometropia, catarata unilateral, retinoblastoma. Encaminhar oftalmo pediátrico."},
{nivel:"info", txt:"PINHOLE (ORIFÍCIO ESTENOPEICO): cartão com orifício de ~1 mm — se paciente vê melhor através dele, causa da BV é REFRATIVA (corrige com óculos); se não melhora, causa é PATOLÓGICA. Improvisado com cartão furado em UBS."},
{nivel:"info", txt:"CEGUEIRA LEGAL no Brasil (Decreto 5.296/2004): AV ≤ 20/200 no melhor olho COM CORREÇÃO ÓTIMA, ou campo visual ≤ 20°. Direito a BPC/LOAS (benefício assistencial — INSS), passe livre, isenção de IPI auto, etc. Encaminhar assistência social."},
{nivel:"info", txt:"TABELA DE SNELLEN com OPTÓTIPOS RELEVANTES (letras claras, E direcionada, figuras infantis) deve estar disponível em TODA UBS — adesivada em parede, em corredor de 5-6 m com iluminação adequada. Equipamento de BAIXÍSSIMO CUSTO e ALTO RENDIMENTO."},
],
diretriz:"[OMS — World Report on Vision 2019] [PSE — Programa Saúde na Escola MS] [CBO — Diretrizes de Saúde Ocular 2023] [Decreto 5.296/2004 — Deficiência Visual]"
},
);
