/* ===========================================================
   VOVÔMINIC EMERGÊNCIA — pat/pali.js
   12 patologias
   Sistemas: pali
   =========================================================== */

PATOLOGIAS.push(

/* ============== PALI (12) ============== */

{id:"anorexia-caquexia", contexto:["pa","ubs"], nome:"Anorexia / Caquexia Oncológica — manejo paliativo", sis:"pali", grav:"baixa",
cid:"R63.0/C80", ciap:"T08",
sin:["Caquexia","Anorexia oncológica","Megestrol","Mirtazapina paliativo","Dexametasona apetite"],
def:"⚠ CAQUEXIA = perda involuntária de peso (>5% em 6m OU >2% se IMC baixo OU sarcopenia) + alterações metabólicas em paciente com doença sistêmica. ⚠ ≠ desnutrição por jejum — mesmo com nutrição não-reversível em fase avançada. ⚠ NÃO é falha do cuidador. Manejo: tratar reversíveis + apoiar família + foco em qualidade de vida (não em peso).",
quadro:["Perda de peso involuntária","Anorexia (perda de apetite)","Sarcopenia (perda massa muscular)","Inflamação sistêmica (PCR↑, citocinas inflamatórias)","⚠ Estágios: pré-caquexia → caquexia → caquexia refratária (irreversível, fase ativa)","⚠ DISTINGUIR de causas REVERSÍVEIS associadas: náusea, dor, depressão, mucosite, alteração de paladar, candidíase oral, constipação, hipercalcemia, hipotireoidismo, fármaco"],
diag:["⚠ Anamnese + exame: perda de peso real (pesar), apetite, sintomas associados","Avaliar SINTOMAS REVERSÍVEIS contributivos","⚠ ESCALAS: MUST (Malnutrition Universal Screening Tool), avaliação funcional (KPS/ECOG)","Imagem corporal — pode haver sofrimento associado"],
exames:["Hemograma","Albumina, PCR","Cálcio corrigido","Função renal/hepática","TSH","Glicemia"],
rx:[
{etapa:"inicial", d:"⚠ ⚠ COMUNICAÇÃO COM FAMÍLIA — MAIS IMPORTANTE QUE FÁRMACO"},
{etapa:"inicial", d:"⚠ Explicar: caquexia é causada pela DOENÇA, não por 'falta de comida'. Forçar a comer NÃO recupera o paciente"},
{etapa:"inicial", d:"⚠ Cultura brasileira valoriza 'comer bem' como sinal de saúde — pressão familiar pode causar SOFRIMENTO ao paciente"},
{etapa:"inicial", d:"⚠ ⚠ Em FASE AVANÇADA / ATIVA: comer pouco é NORMAL e SAUDÁVEL — diminuição metabólica fisiológica"},
{etapa:"inicial", d:"⚠ NÃO FORÇAR alimentação, SNG, NPT em fase ativa — pode causar dano (aspiração, edema, sofrimento)"},
{etapa:"escala", d:"⚠ TRATAR CAUSAS REVERSÍVEIS ASSOCIADAS"},
{etapa:"escala", d:"Náusea → antiemético adequado ao mecanismo (vide patologia)"},
{etapa:"escala", d:"Dor → analgesia otimizada"},
{etapa:"escala", d:"Depressão → ISRS, suporte"},
{etapa:"escala", d:"Mucosite → bochechos antifúngicos, anti-séptico, anestésico tópico"},
{etapa:"escala", d:"Candidíase oral → fluconazol 100 mg/d × 7-14d OU nistatina solução"},
{etapa:"escala", d:"Constipação → manejo (vide patologia)"},
{etapa:"escala", d:"Hipercalcemia → tratar"},
{etapa:"escala", d:"⚠ MEDIDAS NÃO-FARMACOLÓGICAS"},
{etapa:"escala", d:"⚠ Refeições PEQUENAS, frequentes, conforme PREFERÊNCIA do paciente — não impor 'cardápio saudável'"},
{etapa:"escala", d:"Alimentos com odor + temperatura adaptados ao gosto do paciente"},
{etapa:"escala", d:"AMBIENTE agradável, companhia, sem pressão"},
{etapa:"escala", d:"AVALIAR sabor — câncer/quimio altera percepção (metalizado, ageusia, dosgeusia) — sucos cítricos podem ajudar"},
{etapa:"escala", d:"⚠ COMPLEMENTOS NUTRICIONAIS (ex: Nutren, Nutridrink) — em fase não-terminal podem ajudar pacientes selecionados (preferir leve, sabor escolhido)"},
{etapa:"escala", d:"⚠ NUTRIÇÃO ENTERAL/PARENTERAL — papel LIMITADO em caquexia oncológica avançada. Pode ser ÚTIL em obstrução mecânica reversível, pré-procedimento (cirurgia, RT), paciente com expectativa adequada"},
{etapa:"escala", d:"⚠ ⚠ EM FASE ATIVA DE MORTE: NÃO INICIAR nutrição artificial; AVALIAR SUSPENSÃO se já em curso (decisão compartilhada)"},
{etapa:"adj", d:"⚠ FARMACOTERAPIA — efeito MODESTO em apetite/peso, sem impacto em sobrevida ou função"},
{etapa:"adj", d:"⚠ DEXAMETASONA 2-4 mg/d manhã — efeito CURTO PRAZO (4-6 sem) em apetite/bem-estar, antiemético, antiinflamatório", do:"2-4 mg/d manhã", via:"VO/SC", o:"⚠ Efeito DIMINUI com tempo. Efeitos colaterais cumulativos (miopatia, candida, hiperglicemia). Útil em PACIENTE EM SEMANAS-DIAS."},
{etapa:"adj", d:"⚠ MEGESTROL ACETATO 160-800 mg/d — análogo progestágeno, efeito orexígeno e ganho de peso (gordura), poucas semanas para iniciar", do:"160-800 mg/d", via:"VO", o:"⚠ ⚠ RISCO TROMBOEMBÓLICO + supressão adrenal + edema. Cara. Útil em paciente com expectativa de meses."},
{etapa:"adj", d:"⚠ MIRTAZAPINA 15-30 mg HS — antidepressivo com efeito orexígeno + sedativo + antiemético", do:"15-30 mg HS", via:"VO", o:"⚠ Particularmente útil em paciente com TRIPLA INDICAÇÃO: depressão + insônia + caquexia. (vide bloco psiq)"},
{etapa:"adj", d:"⚠ OLANZAPINA 2,5-5 mg HS — efeito orexígeno + antiemético em refratários", obs:""},
{etapa:"adj", d:"⚠ CANABINOIDES (dronabinol em alguns países) — efeito orexígeno modesto, mais útil em quimio-induzida", obs:""},
{etapa:"adj", d:"⚠ TALIDOMIDA 100-200 mg/d — em caquexia HIV ou oncológica, efeito modesto, especialista (regulamentações específicas)", obs:""},
{etapa:"alta", d:"⚠ COMUNICAÇÃO + APOIO PSICOLÓGICO + ESPIRITUAL"},
{etapa:"alta", d:"Caquexia é sinal de doença avançada — momento para conversas sobre objetivos de cuidado, expectativas"},
{etapa:"alta", d:"⚠ Família frequentemente reage com EMPENHO em alimentar — redirecionar para presença, conversa, contato"},
],
alertas:[
{nivel:"crit", txt:"⚠ ⚠ NÃO FORÇAR alimentação em paciente em fase avançada/ativa. Comer pouco é NORMAL e SAUDÁVEL fisiologicamente. Pressionar gera sofrimento."},
{nivel:"crit", txt:"⚠ NUTRIÇÃO PARENTERAL / SNG raramente beneficia em caquexia oncológica avançada — pode causar dano (aspiração, edema, sobrecarga, infecção)."},
{nivel:"warn", txt:"⚠ DEXAMETASONA tem efeito CURTO PRAZO (4-6 sem) em apetite/bem-estar — útil em paciente em SEMANAS-DIAS. Cuidado com cumulativos."},
{nivel:"warn", txt:"⚠ MEGESTROL tem efeito orexígeno mas RISCO TROMBOEMBÓLICO significativo. Em paciente com sobrevida estimada de meses + sem fatores de risco."},
{nivel:"info", txt:"⚠ TRATAR CAUSAS REVERSÍVEIS (mucosite, candidíase, dor, náusea, depressão) PRIMEIRO. Pode haver melhora significativa sem ir para 'estimulador de apetite'."},
{nivel:"info", txt:"⚠ MIRTAZAPINA: tripla indicação prática (depressão + insônia + ↓ peso) — combo útil em paciente paliativo selecionado."},
],
fluxo:null, diretriz:"ESPEN; ANCP; ASCO Cancer Cachexia 2020."
},
{id:"compressao-medular-maligna", contexto:["pa","ubs"], nome:"Compressão Medular Maligna — EMERGÊNCIA Oncológica", sis:"pali", grav:"grave",
cid:"G95.2/C79.5", ciap:"L86",
sin:["Compressão medular","CMM","Metástase coluna","Dexametasona compressão","Radioterapia paliativa urgente"],
def:"⚠ ⚠ ⚠ EMERGÊNCIA ONCOLÓGICA — compressão por metástase epidural / vertebral. JANELA TERAPÊUTICA CURTA — déficit motor instalado >48h frequentemente IRREVERSÍVEL. ⚠ Reconhecimento + dexametasona + RM + radioterapia/cirurgia em HORAS. DOR LOMBAR NOVA/PROGRESSIVA em ONCOLÓGICO = investigar SEMPRE.",
quadro:["⚠ DOR LOMBAR / TORÁCICA progressiva, mecânica, piora com decúbito — pode anteceder déficit em SEMANAS","⚠ DÉFICIT MOTOR — paraparesia / tetraparesia conforme nível","Alteração sensitiva com NÍVEL definido","⚠ DISFUNÇÃO ESFINCTERIANA — retenção urinária, constipação, incontinência (lesão tardia, prognóstico pior)","⚠ Sinais de neurônio motor superior abaixo da lesão (hiperreflexia, Babinski) em torácica; flacidez em síndrome cauda equina","Primários frequentes: mama, próstata, pulmão, mieloma múltiplo, rim, linfoma"],
diag:["⚠ ⚠ ALTA SUSPEIÇÃO — dor lombar nova em oncológico = investigar SEMPRE","Exame neurológico CUIDADOSO: força (escala MRC), sensibilidade com NÍVEL, reflexos, tônus","⚠ TOQUE RETAL — avaliar tônus esfincteriano + bulbo-cavernoso"],
exames:["⚠ ⚠ ⚠ RM COLUNA TOTAL (cervical + torácica + lombar) URGENTE — IDEALMENTE EM HORAS","⚠ Se RM indisponível: TC coluna com contraste OU mielo-TC (alternativa)","⚠ Rx coluna pode estar normal mesmo com compressão — não tranquiliza"],
rx:[
{etapa:"inicial", d:"⚠ ⚠ ⚠ DEXAMETASONA EM BOLUS IMEDIATA — não esperar imagem"},
{etapa:"inicial", d:"⚠ DEXAMETASONA 16 mg IV BOLUS ÚNICO, depois 4 mg IV 6/6h × 48h, depois reduzir conforme resposta", do:"16 mg IV bolus + 4 mg 6/6h", via:"IV", o:"⚠ NÃO ESPERAR confirmação — déficit pode evoluir em horas. Em paciente com forte suspeita: BOLUS imediato em qualquer setor (UBS, PA)."},
{etapa:"inicial", d:"⚠ ANALGESIA — opioide adequado, geralmente em escalonamento rápido"},
{etapa:"inicial", d:"⚠ ⚠ REFERENCIAMENTO IMEDIATO — RM URGENTE + oncologia/radioterapia/neurocirurgia"},
{etapa:"escala", d:"⚠ TRATAMENTO DEFINITIVO"},
{etapa:"escala", d:"⚠ ⚠ RADIOTERAPIA PALIATIVA URGENTE — em até 24-48h em paciente com déficit"},
{etapa:"escala", d:"⚠ CIRURGIA DE DESCOMPRESSÃO + estabilização — indicada em paciente com bom performance + sobrevida estimada >3-6m + déficit estabelecido <48h + instabilidade espinhal + tumor radio-resistente (carcinoma renal, sarcoma)"},
{etapa:"escala", d:"⚠ COMBINAÇÃO cirurgia + radioterapia adjuvante — em casos selecionados"},
{etapa:"escala", d:"⚠ Em paciente com expectativa LIMITADA (semanas) ou já parapelégico há >48h: apenas DEXAMETASONA + ANALGESIA + suporte (déficit não recuperável)"},
{etapa:"adj", d:"⚠ TROMBOPROFILAXIA — enoxaparina 40 mg SC 1×/d em paciente acamado por déficit"},
{etapa:"adj", d:"⚠ MANEJO DE BEXIGA — sondagem vesical de demora ou intermitente; cateterismo conforme função"},
{etapa:"adj", d:"⚠ MANEJO INTESTINAL — laxativos, supositórios, lavagem em paciente neurogênico"},
{etapa:"adj", d:"⚠ FISIOTERAPIA / REABILITAÇÃO precoce"},
{etapa:"adj", d:"⚠ BIFOSFONATO em metástase óssea (ácido zoledrônico 4 mg IV/mês) — preventivo de eventos esqueléticos"},
{etapa:"alta", d:"⚠ COMUNICAÇÃO — explicar urgência + janela de oportunidade"},
{etapa:"alta", d:"⚠ Após estabilização: discussão de objetivos de cuidado, prognóstico, retorno a casa, planejamento avançado"},
{etapa:"alta", d:"⚠ APOIO ao paciente em adaptação (cadeirante, sondado) — fisioterapia, psicologia, social"},
],
alertas:[
{nivel:"crit", txt:"⚠ ⚠ ⚠ COMPRESSÃO MEDULAR = EMERGÊNCIA. Déficit motor >48h frequentemente IRREVERSÍVEL. ⚠ DEXAMETASONA 16 mg IV BOLUS IMEDIATA em suspeita — não esperar imagem."},
{nivel:"crit", txt:"⚠ DOR LOMBAR NOVA/PROGRESSIVA em ONCOLÓGICO = SEMPRE INVESTIGAR. Pode anteceder déficit em semanas — JANELA para imagem + tratamento preventivo."},
{nivel:"crit", txt:"⚠ ⚠ RM COLUNA TOTAL URGENTE — preferida. Se indisponível: TC com contraste / mielo-TC."},
{nivel:"warn", txt:"⚠ RADIOTERAPIA PALIATIVA em 24-48h em paciente com déficit + sobrevida adequada. Cirurgia indicada em casos específicos (instabilidade, tumor radio-resistente, paciente com bom performance)."},
{nivel:"warn", txt:"⚠ Em paciente em fase muito avançada ou já paraplégico >48h: foco em conforto + analgesia + suporte (não há recuperação esperada). NÃO submeter a procedimentos invasivos sem benefício."},
],
fluxo:"compressao-medular", diretriz:"NICE Spinal Cord Compression; NCCN; SBOC."
},
{id:"comunicacao-spikes", contexto:["pa","ubs"], nome:"Comunicação de Más Notícias — Protocolo SPIKES + Plano de Cuidado Avançado", sis:"pali", grav:"baixa",
cid:"Z71", ciap:"A45",
sin:["SPIKES","Más notícias","Comunicação difícil","Diretivas antecipadas","Plano de cuidado avançado","Diagnóstico câncer"],
def:"⚠ COMUNICAÇÃO de más notícias é HABILIDADE CLÍNICA CENTRAL — não 'estilo pessoal'. Treinável, validada. ⚠ PROTOCOLO SPIKES (Baile et al, 2000) — 6 passos. Equivocada comunicação é causa frequente de SOFRIMENTO + processos. ⚠ Inclui: diagnóstico ruim, prognóstico limitado, discussão de objetivos de cuidado, decisões de fim de vida.",
quadro:["⚠ MÁS NOTÍCIAS = qualquer informação que altere expectativas do paciente em relação ao futuro de forma adversa","Diagnóstico de doença grave (câncer, demência, IC, esclerose)","Progressão / recidiva","Falha de tratamento","Prognóstico limitado","Necessidade de mudança de objetivos (curativo → paliativo)","Discussão de fim de vida"],
diag:["Não é diagnóstico — é HABILIDADE CLÍNICA","⚠ Auto-avaliação: 'Como estou para esta conversa? Tenho tempo, lugar, energia?'","⚠ Preparo prévio: ler prontuário, alinhar com equipe, ter dados objetivos prontos"],
exames:["Não aplicável"],
rx:[
{etapa:"escala", d:"⚠ ⚠ PROTOCOLO SPIKES — 6 PASSOS"},
{etapa:"escala", d:"⚠ S — SETTING (ambiente)"},
{etapa:"escala", d:"AMBIENTE PRIVATIVO — sala fechada, sem interrupções"},
{etapa:"escala", d:"TEMPO ADEQUADO — pelo menos 30 min, sem pressa de saída"},
{etapa:"escala", d:"PRESENÇA DE FAMILIAR — se paciente desejar"},
{etapa:"escala", d:"POSIÇÃO — sentar em altura do paciente, sem mesa entre vocês, sem celular"},
{etapa:"escala", d:"DESLIGAR celular / pager. Comunicar à equipe 'não interromper'"},
{etapa:"escala", d:"⚠ P — PERCEPTION (percepção do paciente)"},
{etapa:"escala", d:"'O que você sabe sobre sua situação atual?'"},
{etapa:"escala", d:"'O que os outros médicos disseram?'"},
{etapa:"escala", d:"⚠ Calibrar — paciente está em NEGAÇÃO, em CONHECIMENTO PARCIAL, ou em CONHECIMENTO COMPLETO?"},
{etapa:"escala", d:"Não 'corrigir' negação imediatamente — explorar com cuidado"},
{etapa:"escala", d:"⚠ I — INVITATION (convite)"},
{etapa:"escala", d:"'Quanta informação você gostaria de saber sobre os resultados?'"},
{etapa:"escala", d:"'Você prefere que eu fale com você ou com alguém da família primeiro?'"},
{etapa:"escala", d:"⚠ RESPEITAR — alguns pacientes preferem NÃO saber tudo (válido)"},
{etapa:"escala", d:"⚠ K — KNOWLEDGE (compartilhar conhecimento)"},
{etapa:"escala", d:"⚠ 'TIRO DE AVISO' (warning shot) — 'Preciso compartilhar algo difícil...' / 'Os resultados não são os que esperávamos...'"},
{etapa:"escala", d:"DAR a notícia em LINGUAGEM SIMPLES, sem jargão"},
{etapa:"escala", d:"PAUSA — silêncio é necessário, dar tempo para absorver"},
{etapa:"escala", d:"PEDAÇOS pequenos — não despejar tudo de uma vez"},
{etapa:"escala", d:"⚠ NÃO mentir / NÃO suavizar excessivamente — 'pequeno tumor', 'algumas células diferentes' geram confusão"},
{etapa:"escala", d:"⚠ E — EMPATHY / EMOTIONS (responder a emoções)"},
{etapa:"escala", d:"OBSERVAR reação — choro, raiva, silêncio, negação"},
{etapa:"escala", d:"NOMEAR a emoção — 'Vejo que essa notícia foi muito difícil'"},
{etapa:"escala", d:"VALIDAR — 'Faz sentido se sentir assim'"},
{etapa:"escala", d:"⚠ NÃO oferecer soluções imediatas — primeiro sustentar emocionalmente"},
{etapa:"escala", d:"SILÊNCIO é OK — não preencher com fala"},
{etapa:"escala", d:"TOQUE (mão, ombro) se cultural/pessoalmente apropriado"},
{etapa:"escala", d:"⚠ S — STRATEGY / SUMMARY (estratégia e síntese)"},
{etapa:"escala", d:"⚠ Só após sustentar emocionalmente — verificar se paciente 'volta' para a conversa"},
{etapa:"escala", d:"'Você gostaria de saber sobre os próximos passos?'"},
{etapa:"escala", d:"OFERECER PLANO — opções de tratamento, encaminhamentos, próxima consulta"},
{etapa:"escala", d:"VERIFICAR compreensão — 'pode me dizer o que entendeu?'"},
{etapa:"escala", d:"OFERECER companhia continuada — 'vamos passar por isso juntos'"},
{etapa:"escala", d:"AGENDAR próximo contato — 'nos vemos daqui a X dias'"},
{etapa:"adj", d:"⚠ DISCUSSÃO DE OBJETIVOS DE CUIDADO"},
{etapa:"adj", d:"⚠ 'Goals of care discussion' — em qualquer transição, idealmente ANTES de fase ativa"},
{etapa:"adj", d:"PERGUNTAS NORTEADORAS:"},
{etapa:"adj", d:"'O que é mais importante para você agora?'"},
{etapa:"adj", d:"'O que faz a vida valer a pena para você?'"},
{etapa:"adj", d:"'Em uma situação grave, o que você gostaria que fosse feito (ou não)?'"},
{etapa:"adj", d:"'Você prefere mais tempo, mesmo se isso significar tratamentos agressivos? Ou prefere foco em conforto?'"},
{etapa:"adj", d:"⚠ DIRETIVAS ANTECIPADAS DE VONTADE (DAV) — Resolução CFM 1.995/2012"},
{etapa:"adj", d:"Paciente CAPAZ pode registrar em prontuário (preferível) ou em cartório quais tratamentos aceita/recusa em caso de impossibilidade futura de decidir"},
{etapa:"adj", d:"Inclui: RCP, ventilação mecânica, hemodiálise, nutrição artificial, hidratação, transfusão"},
{etapa:"adj", d:"Procurador de saúde — pessoa que toma decisões em nome do paciente quando incapaz"},
{etapa:"adj", d:"⚠ ESPÓLIO ÉTICO — CFM permite limitar tratamentos não-curativos / disproporcionais conforme vontade do paciente (Res 1.805/2006 — ortotanásia)"},
{etapa:"alta", d:"⚠ DOCUMENTAR no prontuário: conteúdo da conversa, presentes, decisões, plano"},
{etapa:"alta", d:"⚠ COMUNICAR equipe — todos devem saber o que foi discutido, evitar contradições"},
{etapa:"alta", d:"⚠ AUTO-CUIDADO do médico — má notícia é desgastante, considerar pausa, supervisão entre pares"},
],
alertas:[
{nivel:"crit", txt:"⚠ COMUNICAÇÃO DE MÁS NOTÍCIAS é habilidade CLÍNICA CENTRAL — treinável. SPIKES (6 passos) é protocolo validado: Setting, Perception, Invitation, Knowledge, Empathy, Strategy."},
{nivel:"warn", txt:"⚠ NÃO MENTIR / NÃO SUAVIZAR excessivamente. 'Pequeno tumor' / 'células diferentes' geram confusão. Honestidade clara em linguagem simples."},
{nivel:"warn", txt:"⚠ RESPEITAR autonomia — alguns pacientes preferem NÃO SABER tudo. Convidar (Invitation step) é essencial."},
{nivel:"info", txt:"⚠ DIRETIVAS ANTECIPADAS DE VONTADE (DAV) — Resolução CFM 1.995/2012. Registrar em prontuário tem validade. Inclui RCP, VM, hemodiálise, nutrição, hidratação. Procurador de saúde nomeado."},
{nivel:"info", txt:"⚠ ORTOTANÁSIA — Res CFM 1.805/2006 permite limitar tratamentos disproporcionais conforme vontade do paciente terminal. Diferente de eutanásia."},
],
fluxo:"spikes", diretriz:"⚠ Baile WF et al. SPIKES. Oncologist 2000; CFM Res 1.805/2006 + 1.995/2012; ANCP; Vital Talk."
},
{id:"constipacao-opioide", contexto:["pa","ubs"], nome:"Constipação Induzida por Opioide (CIO) — profilaxia e manejo", sis:"pali", grav:"moderada",
cid:"K59.0", ciap:"D12",
sin:["Constipação opioide","CIO","Laxativo paliativo","Bisacodil","Lactulose","Metilnaltrexona","Naloxegol"],
def:"⚠ ⚠ TODO paciente em opioide DESENVOLVE constipação (>90%). ⚠ É EFEITO COLATERAL PREVISÍVEL — sem tolerância significativa (não 'passa com tempo'). ⚠ PROFILAXIA ATIVA com laxativo na MESMA PRESCRIÇÃO do opioide. Falhar em prescrever laxativo = falhar como prescritor.",
quadro:["⚠ Sintomas: evacuação <3×/sem, fezes endurecidas, esforço, sensação de evacuação incompleta, distensão, dor abdominal","⚠ Risco de IMPACTAÇÃO FECAL (fecaloma): toque retal — fezes endurecidas em ampola; em alta: paradoxalmente DIARREIA (escape ao redor do fecaloma) — não tratar como diarreia comum","Pode levar a: náusea, anorexia, distensão, dor, pseudo-obstrução"],
diag:["⚠ Anamnese sobre hábito intestinal — frequência, consistência (Bristol 1-7), esforço, sensação","⚠ Toque retal em qualquer paciente com sintomas — DESCARTAR FECALOMA","Examinar abdome — distensão, dor, massas, RHA","Rx abdome se obstrução suspeita ou fecaloma alto"],
exames:["Geralmente clínico","Eletrólitos (K, Ca — hipocalemia e hipercalcemia agravam)","Rx abdome se suspeita obstrução"],
rx:[
{etapa:"inicial", d:"⚠ ⚠ PROFILAXIA OBRIGATÓRIA — prescrever laxativo COM A PRIMEIRA DOSE de opioide"},
{etapa:"inicial", d:"⚠ ⚠ NÃO ESPERAR aparecer — manejar antes"},
{etapa:"escala", d:"⚠ ESCALONAMENTO LAXATIVO"},
{etapa:"escala", d:"⚠ ESQUEMA INICIAL — COMBINAR estimulante + osmótico"},
{etapa:"escala", d:"BISACODIL 5-10 mg VO HS (estimulante de motilidade)", do:"5-10 mg HS", via:"VO", o:""},
{etapa:"escala", d:"+ LACTULOSE 15-30 mL VO 12/12h ad lib (osmótico)", do:"15-30 mL 12/12h", via:"VO", o:"Pode causar flatulência. Sabor adocicado."},
{etapa:"escala", d:"OU PEG (POLIETILENOGLICOL) 17 g em 240 mL água VO 1×/d (osmótico, melhor tolerado)", do:"17 g/d", via:"VO", o:"⚠ Custo maior."},
{etapa:"escala", d:"⚠ AVALIAR EFICÁCIA em 2-3 DIAS — fezes Bristol 3-4, sem esforço"},
{etapa:"adj", d:"⚠ ESCALONAR se inadequado:"},
{etapa:"adj", d:"(1) Aumentar BISACODIL para 10-15 mg HS"},
{etapa:"adj", d:"(2) Adicionar SUPOSITÓRIO de GLICERINA (estimulante retal) — se inicialmente sem evacuação"},
{etapa:"adj", d:"(3) Adicionar ÓLEO MINERAL 15-30 mL VO HS (lubrificante)", obs:"⚠ Cuidado aspiração em idoso/disfagia."},
{etapa:"adj", d:"(4) Aumentar LACTULOSE para 30-45 mL 8/8h"},
{etapa:"adj", d:"(5) SENE 12-50 mg HS (estimulante alternativo)"},
{etapa:"adj", d:"⚠ ⚠ REFRATÁRIO (apesar de combinação otimizada >5-7 dias):"},
{etapa:"adj", d:"⚠ METILNALTREXONA 8 mg SC (peso 38-62 kg) ou 12 mg SC (>62 kg) cada 48h", do:"8-12 mg SC cada 48h", via:"SC", o:"⚠ Antagonista μ-opioide PERIFÉRICO — não atravessa BHE, mantém analgesia. Efeito laxativo em 30-60 min. ⚠ NÃO usar em obstrução suspeita."},
{etapa:"adj", d:"⚠ NALOXEGOL 25 mg VO 1×/d em jejum (antagonista μ oral)", obs:""},
{etapa:"adj", d:"⚠ NALDEMEDINA 0,2 mg VO 1×/d", obs:"Alternativa."},
{etapa:"adj", d:"⚠ FECALOMA — diagnóstico + tratamento"},
{etapa:"adj", d:"⚠ Toque retal — confirma fezes endurecidas em ampola"},
{etapa:"adj", d:"DESIMPACTAÇÃO MANUAL — com luva lubrificada, paciente em decúbito lateral (analgesia/sedação leve pode ser necessária)"},
{etapa:"adj", d:"SUPOSITÓRIO GLICERINA + LAVAGEM RETAL com solução fisiológica (200-500 mL) — para amolecer"},
{etapa:"adj", d:"⚠ DESPRESCREVER 'enema de fosfato' em IDOSO/IRC — risco hiperfosfatemia"},
{etapa:"alta", d:"⚠ MEDIDAS NÃO-FARMACOLÓGICAS"},
{etapa:"alta", d:"Hidratação conforme tolerância (não forçar em fase ativa)"},
{etapa:"alta", d:"Fibras solúveis em paciente FUNCIONAL — em fase avançada/anoréxico/desidratado: ⚠ EVITAR (sem água, pode piorar)"},
{etapa:"alta", d:"Posição ortostática para evacuação se possível; banquinho sob pés"},
{etapa:"alta", d:"Privacidade, tempo, ambiente confortável"},
{etapa:"alta", d:"⚠ ATIVIDADE FÍSICA conforme tolerância — caminhada, mobilização"},
],
alertas:[
{nivel:"crit", txt:"⚠ ⚠ TODO PACIENTE EM OPIOIDE precisa de LAXATIVO PROFILÁTICO desde a 1ª dose. NÃO é opcional. NÃO esperar acontecer. Bisacodil 10 mg HS + Lactulose 15-30 mL 12/12h é esquema-base."},
{nivel:"crit", txt:"⚠ FECALOMA pode se manifestar como DIARREIA paradoxal (escape ao redor) — NÃO TRATAR como diarreia comum. Toque retal antes."},
{nivel:"warn", txt:"⚠ FIBRAS solúveis (psyllium, fibras) NÃO são adequadas em fase avançada/anoréxico/desidratado — sem água, pioram. Usar em paciente com função GI preservada e hidratação adequada."},
{nivel:"warn", txt:"⚠ ENEMA DE FOSFATO em idoso/IRC: risco HIPERFOSFATEMIA / hipocalcemia. Preferir lavagem com solução fisiológica."},
{nivel:"warn", txt:"⚠ METILNALTREXONA / NALOXEGOL: antagonistas PERIFÉRICOS — mantém analgesia central. Indicado em CIO REFRATÁRIA. ⚠ NÃO USAR em obstrução intestinal suspeita."},
{nivel:"info", txt:"⚠ OUTROS opioides têm grau variável de constipação. METADONA, FENTANIL TD, BUPRENORFINA TD: constipação MENOR. Considerar rotação em refratários."},
],
fluxo:"constipacao-opioide", diretriz:"ANCP; MASCC; ESMO Constipation."
},
{id:"delirium-paliativo", contexto:["pa","ubs"], nome:"Delirium em Cuidados Paliativos — manejo agudo + terminal", sis:"pali", grav:"grave",
cid:"F05/R41.0", ciap:"P71",
sin:["Delirium paliativo","Confusão terminal","Agitação terminal","Haloperidol delirium","Levomepromazina"],
def:"⚠ DELIRIUM acomete 80-90% de pacientes paliativos em últimos dias. ⚠ Avaliar SEMPRE: é REVERSÍVEL (infecção, droga, dor, eletrólitos, retenção) ou IRREVERSÍVEL (falência sistêmica em fase ativa)? Conduta varia drasticamente. Subtipos: HIPERATIVO (agitação, agressividade), HIPOATIVO (sonolência, retraimento — mais comum, mais subdiagnosticado), MISTO.",
quadro:["⚠ Início AGUDO + flutuação + desatenção + alteração de consciência/cognição (DSM-5)","HIPERATIVO: agitação, agressividade, delírio, alucinação","HIPOATIVO: sonolência, retraimento, lentificação — frequentemente confundido com 'depressão' ou 'fadiga normal'","MISTO: alternância","⚠ DIFERENCIAR de demência (insidiosa) e depressão (humor)","⚠ Em fase ativa de morte: AGITAÇÃO TERMINAL — irreversível geralmente"],
diag:["⚠ CAM (Confusion Assessment Method): (1) início agudo + flutuação + (2) desatenção + (3) pensamento desorganizado OU (4) nível alterado consciência","Escalas: RASS (agitação-sedação), MDAS (Memorial Delirium Assessment Scale)","⚠ ⚠ INVESTIGAR REVERSIBILIDADE — RAÍZES MNEMÔNICAS:","D — Drogas (opioide, BZD, anticolinérgico, corticoide, abstinência)","E — Eletrólitos (Na, Ca, glicemia, ureia)","L — Low O2 (hipoxemia, hipercapnia, anemia)","I — Infecção (urinária, respiratória, sistêmica)","R — Retenção (urinária, fecal — fecaloma)","I — Insultos intracraniais (mets, AVC, HIC)","U — Uremia, falência hepática","M — Mais — dor, ambiente, privação sensorial"],
exames:["⚠ Triagem básica: hemograma, eletrólitos (Na, K, Ca corrigido, Mg), função renal+hepática, glicemia, gasometria, urocultura","SatO2 + Rx tórax se respiratório","Toque retal — fecaloma","Sondagem vesical se retenção","⚠ TC crânio se sinais focais novos / suspeita meta cerebral"],
rx:[
{etapa:"inicial", d:"⚠ AVALIAR FASE — REVERSÍVEL ou TERMINAL?"},
{etapa:"inicial", d:"⚠ Paciente com horizonte de SEMANAS-MESES + delirium agudo = INVESTIGAR + reverter causa"},
{etapa:"inicial", d:"⚠ Paciente em FASE ATIVA DE MORTE (horas-dias) + agitação = TRATAR SINTOMA (haloperidol, BZD se necessário)"},
{etapa:"escala", d:"⚠ ⚠ MEDIDAS NÃO-FARMACOLÓGICAS — SEMPRE primeiro/em paralelo"},
{etapa:"escala", d:"Ambiente CALMO, iluminação adequada (luz dia, escuro à noite), reorientação verbal frequente"},
{etapa:"escala", d:"Presença de FAMILIAR conhecido + objetos familiares; música preferida"},
{etapa:"escala", d:"REDUZIR estímulos: barulho, equipe rotativa, intervenções desnecessárias"},
{etapa:"escala", d:"⚠ DESPRESCREVER drogas precipitantes: anticolinérgicos, BZD se possível (cuidado com abstinência), opioide em dose excessiva, corticoide"},
{etapa:"escala", d:"⚠ TRATAR causas reversíveis identificadas: ATB se infecção, hidratação cuidadosa se desidratação, sondagem vesical se retenção, desimpactação fecal, correção eletrolítica"},
{etapa:"escala", d:"⚠ ⚠ FARMACOTERAPIA — quando agitação compromete cuidado ou sofrimento"},
{etapa:"escala", d:"⚠ HALOPERIDOL — 1ª LINHA"},
{etapa:"escala", d:"VO: 0,5-2 mg 8-12/12h (idoso: 0,25-0,5 mg). Resgate 0,5-1 mg 1/1h se necessário", do:"0,5-2 mg 8-12/12h + resgate", via:"VO", o:""},
{etapa:"escala", d:"⚠ SC: 1-2 mg cada 4-8h ou contínua 5-15 mg/d", do:"1-5 mg 4-8/8h SC", via:"SC", o:""},
{etapa:"escala", d:"IV apenas em ambiente monitorado (QT)", obs:""},
{etapa:"escala", d:"⚠ CUIDADO em IDOSO + cardiopata: QT longo (sem chegar a 30 mg/d evita risco maior)"},
{etapa:"escala", d:"⚠ ⚠ EVITAR EM PARKINSON / corpos de Lewy — preferir QUETIAPINA"},
{etapa:"escala", d:"⚠ AGITAÇÃO REFRATÁRIA / DELIRIUM HIPERATIVO INTENSO"},
{etapa:"escala", d:"⚠ ⚠ LEVOMEPROMAZINA 12,5-25 mg VO/SC 8-12/12h — sedativa, antiemética, ansiolítica", do:"12,5-50 mg 8-12/12h", via:"VO/SC", o:"⚠ ⚠ Mais sedativa que haloperidol — útil quando se busca sedação leve a moderada. REMUME / FARMASUS."},
{etapa:"escala", d:"⚠ ⚠ MIDAZOLAM SC 2,5-5 mg como resgate; BIC SC 0,5-2 mg/h em refratário", do:"2,5-5 mg SC", via:"SC", o:"⚠ Pode PIORAR delirium (paradoxo BZD) — usar em combinação com antipsicótico, raramente isolado."},
{etapa:"escala", d:"⚠ CLORPROMAZINA, OLANZAPINA — alternativas"},
{etapa:"escala", d:"⚠ QUETIAPINA 12,5-50 mg HS — em Parkinson/Lewy. Menos extrapiramidal.", obs:""},
{etapa:"adj", d:"⚠ DESCONTINUAÇÃO DE BZD em uso crônico — não suspender abruptamente (precipita delirium pior). Reduzir 10-25% a cada 2-3 dias"},
{etapa:"adj", d:"⚠ ABSTINÊNCIA ALCOÓLICA pode mimicar — tiamina 100 mg IV/IM + diazepam 5-10 mg conforme CIWA-Ar"},
{etapa:"alta", d:"⚠ COMUNICAÇÃO COM FAMÍLIA"},
{etapa:"alta", d:"⚠ DELIRIUM TERMINAL — explicar à família que NÃO é sofrimento intencional, NÃO é 'enlouquecer', é manifestação da doença"},
{etapa:"alta", d:"Orientar reorientação suave, presença, voz calma — não argumentar com delírios"},
{etapa:"alta", d:"⚠ AGITAÇÃO TERMINAL pode REQUERER SEDAÇÃO PALIATIVA — discutir com família + equipe"},
{etapa:"alta", d:"⚠ Após resolução em casos reversíveis: pode haver memórias angustiantes — apoio psicológico"},
],
alertas:[
{nivel:"crit", txt:"⚠ ⚠ INVESTIGAR REVERSIBILIDADE em delirium novo. Drogas + Eletrólitos + Infecção + Retenção + Dor + Hipoxia — checklist obrigatório."},
{nivel:"crit", txt:"⚠ HALOPERIDOL é 1ª LINHA — VO ou SC. Dose baixa em idoso (0,25-0,5 mg)."},
{nivel:"warn", txt:"⚠ HALOPERIDOL CONTRAINDICADO em Parkinson / demência de corpos de Lewy — pode precipitar rigidez grave / SNM. Usar QUETIAPINA."},
{nivel:"warn", txt:"⚠ BZD ISOLADO em delirium hiperativo: pode PIORAR (paradoxo). Útil em combinação com antipsicótico, em abstinência alcoólica/BZD, ou em sedação paliativa intencional."},
{nivel:"warn", txt:"⚠ DELIRIUM HIPOATIVO é MAIS COMUM e MAIS SUBDIAGNOSTICADO — paciente quieto/sonolento ≠ paciente em paz. Aplicar CAM."},
{nivel:"info", txt:"⚠ AGITAÇÃO TERMINAL refratária a antipsicótico + BZD = considerar SEDAÇÃO PALIATIVA proporcional (vide patologia 'sedacao-paliativa')."},
],
fluxo:"delirium-paliativo", diretriz:"ANCP; APA Delirium; Inouye et al; ESMO."
},
{id:"dispneia-paliativa", contexto:["pa","ubs"], nome:"Dispneia em Cuidados Paliativos — manejo sintomático", sis:"pali", grav:"moderada",
cid:"R06.0", ciap:"R02",
sin:["Dispneia paliativa","Falta de ar paliativos","Fome de ar","Morfina dispneia","Oxigenoterapia paliativa"],
def:"⚠ DISPNEIA é o sintoma mais incapacitante em paliativos — gera angústia tão intensa quanto dor. ⚠ MORFINA em DOSE BAIXA é 1ª linha (efeito independente da analgesia). Manejar CAUSA + sintoma + ansiedade associada. Não confundir com hipoxemia (que pode coexistir mas não é causa única da sensação).",
quadro:["⚠ Sensação SUBJETIVA de respiração desconfortável — paciente é fonte primária","Pode haver: taquipneia, uso de musculatura acessória, cianose, tiragem","⚠ Hipoxemia (Sat <90%) pode estar presente OU NÃO — dispneia é SENSAÇÃO, não hipoxemia","⚠ ANSIEDADE quase sempre presente — círculo vicioso ansiedade ↔ dispneia","⚠ Causas: progressão tumoral pulmonar, derrame pleural, linfangite carcinomatosa, TEP, ICC, anemia, infecção, fadiga muscular respiratória, ansiedade isolada"],
diag:["⚠ CLÍNICO — escutar o paciente. Escala 0-10 análoga à dor","Saturometria — útil mas NÃO substitui sensação","Exame físico: ausculta (estertor, sibilo, derrame), uso de musculatura, esforço","Imagem direcionada conforme suspeita: Rx tórax (derrame, infiltrado, massa), USG pulmonar (derrame, B-lines)","Considerar D-dímero / angio-TC se TEP possível e plano modificará conduta","⚠ Em paciente em FIM DE VIDA: investigação minimalista — tratar sintoma é prioridade"],
exames:["Saturometria","Rx tórax / USG conforme suspeita","Hemograma (anemia)","Avaliar causa reversível: derrame (toracocentese paliativa), broncoespasmo (broncodilatador), infecção (ATB)"],
rx:[
{etapa:"inicial", d:"⚠ AVALIAR + TRATAR CAUSA REVERSÍVEL primeiro"},
{etapa:"inicial", d:"Derrame pleural sintomático: TORACOCENTESE PALIATIVA (até 1-1,5 L); se recidiva → drenagem com cateter pleural permanente / pleurodese"},
{etapa:"inicial", d:"Broncoespasmo: SALBUTAMOL inalação 5 mg + IPRATRÓPIO 0,5 mg + considerar prednisolona 40 mg/d × 5d"},
{etapa:"inicial", d:"Infecção: ATB EMPÍRICO (mesmo em paliativos quando há benefício sintomático)"},
{etapa:"inicial", d:"Anemia sintomática (Hb <8 + dispneia): transfusão paliativa de CH 1 U"},
{etapa:"inicial", d:"⚠ ⚠ NÃO investigar TEP em paciente em fase ATIVA DE MORTE — tratar com morfina"},
{etapa:"escala", d:"⚠ ⚠ MEDIDAS NÃO-FARMACOLÓGICAS — sempre primeiro/em paralelo"},
{etapa:"escala", d:"⚠ AR FRESCO na FACE — ventilador apontado para face do paciente. Trigeminal estímulo central reduz sensação de dispneia. NÃO é placebo — evidência sólida.", obs:""},
{etapa:"escala", d:"POSIÇÃO ortostática / 'cocheiro' (sentado inclinado para frente)", obs:""},
{etapa:"escala", d:"AMBIENTE: janela aberta, espaço amplo, sem aglomeração", obs:""},
{etapa:"escala", d:"TÉCNICA RESPIRATÓRIA — respiração com lábios semicerrados, diafragmática", obs:""},
{etapa:"escala", d:"⚠ COMUNICAÇÃO TRANQUILA, presença, reasseguramento — reduz ansiedade", obs:""},
{etapa:"escala", d:"FISIOTERAPIA RESPIRATÓRIA — drenagem, técnicas de tosse, vibrocompressão", obs:""},
{etapa:"escala", d:"⚠ ⚠ MORFINA — 1ª LINHA FARMACOLÓGICA"},
{etapa:"escala", d:"⚠ OPIOIDE-NAIVE: MORFINA 2,5-5 mg VO 4/4h + RESGATE 2,5 mg 1/1h conforme necessário", do:"2,5-5 mg 4/4h", via:"VO", o:"⚠ Dose MENOR que para dor. Aumentar 25-50% se inefetiva. Estável: rotacionar para LP."},
{etapa:"escala", d:"⚠ EM USO DE OPIOIDE: adicionar 25-50% à dose habitual OU aumentar a dose basal", obs:""},
{etapa:"escala", d:"⚠ VIA SC: MORFINA 2-2,5 mg SC 4/4h se VO inviável", do:"2-2,5 mg 4/4h", via:"SC", o:""},
{etapa:"escala", d:"⚠ INALAÇÃO de MORFINA: ⚠ NÃO RECOMENDADA — evidência negativa", obs:""},
{etapa:"escala", d:"⚠ BENZODIAZEPÍNICO — quando há COMPONENTE ANSIEDADE proeminente ou dispneia refratária a opioide"},
{etapa:"escala", d:"LORAZEPAM 0,5-1 mg VO/SL 6-8/8h ad lib (preferido por meia-vida intermediária)", do:"0,5-1 mg 6-8/8h", via:"VO/SL", o:""},
{etapa:"escala", d:"MIDAZOLAM 1-2,5 mg SC 4/4h se sintomas mais agudos ou SC necessária", do:"1-2,5 mg 4/4h", via:"SC", o:""},
{etapa:"escala", d:"⚠ Diazepam pode ser usado mas meia-vida longa em idoso/IH"},
{etapa:"escala", d:"⚠ OXIGENOTERAPIA — papel limitado"},
{etapa:"escala", d:"⚠ INDICADA quando Sat <90% E paciente sente alívio (ensaio terapêutico)", obs:""},
{etapa:"escala", d:"Em paciente NORMOXÊMICO: ar fresco/ventilador é EQUIVALENTE ou superior", obs:""},
{etapa:"escala", d:"⚠ NÃO PERSISTIR em paciente que não sente alívio — máscara/cânula podem aumentar desconforto, isolamento, ressecamento mucoso"},
{etapa:"escala", d:"⚠ Em FASE ATIVA DE MORTE: geralmente RETIRAR oxigênio se não estiver dando conforto", obs:""},
{etapa:"adj", d:"⚠ DEXAMETASONA — em dispneia por LINFANGITE CARCINOMATOSA, sd. de VEIA CAVA SUPERIOR, edema peritumoral"},
{etapa:"adj", d:"4-8 mg VO/SC/IV manhã (até 16 mg em VCS aguda), titular para dose mínima efetiva", obs:""},
{etapa:"adj", d:"⚠ FUROSEMIDA — em ICC descompensada / congestão pulmonar"},
{etapa:"adj", d:"⚠ INALAÇÃO DE LIDOCAÍNA — para tosse refratária associada (off-label, especializado)", obs:""},
{etapa:"adj", d:"⚠ DISPNEIA TERMINAL REFRATÁRIA — considerar SEDAÇÃO PALIATIVA (vide patologia 'sedacao-paliativa')"},
{etapa:"alta", d:"⚠ COMUNICAÇÃO É TRATAMENTO — sentar, presença, validar 'isso é assustador, vamos cuidar'"},
{etapa:"alta", d:"INSTRUIR FAMÍLIA: nem todo aumento de respiração = sofrimento. Em fase ativa: respiração agônica/Cheyne-Stokes pode parecer angustiante para família mas paciente raramente sente"},
{etapa:"alta", d:"PLANO DE CRISE: prescrição de resgate domiciliar (morfina simples, lorazepam SL, midazolam SC) com instruções claras"},
],
alertas:[
{nivel:"crit", txt:"⚠ ⚠ MORFINA EM DOSE BAIXA é 1ª LINHA para dispneia paliativa. Evidência sólida. Iniciar 2,5-5 mg VO 4/4h em opioide-naive. ⚠ Dispneia ≠ dor — dose menor."},
{nivel:"crit", txt:"⚠ AR FRESCO NA FACE (ventilador) tem evidência sólida — não é placebo. Estímulo trigeminal reduz sensação. Usar SEMPRE como medida não-farmacológica primária."},
{nivel:"warn", txt:"⚠ OXIGÊNIO tem papel LIMITADO — só quando Sat <90% E paciente sente alívio em ensaio. Em normoxêmico: ar fresco/ventilador é equivalente."},
{nivel:"warn", txt:"⚠ BENZODIAZEPÍNICO em dispneia: 2ª linha — para componente ansioso ou refratariedade. NÃO INICIAR como 1ª linha (morfina vem primeiro)."},
{nivel:"warn", txt:"⚠ NÃO INVESTIGAR TEP em paciente em FASE ATIVA DE MORTE — tratar com morfina + suporte. Em paciente com horizonte de meses: avaliar individualmente."},
{nivel:"info", txt:"⚠ Em fase ativa: RESPIRAÇÃO AGÔNICA / Cheyne-Stokes é normal. Pode parecer angustiante para família mas paciente raramente sente. INSTRUIR a família é parte do tratamento."},
{nivel:"info", txt:"⚠ DISPNEIA REFRATÁRIA a opioide + BZD + medidas: considerar SEDAÇÃO PALIATIVA proporcional."},
],
fluxo:null, diretriz:"ATS/ERS Dispneia Paliativa 2010-2021; ANCP; Hui et al."
},
{id:"dor-oncologica", contexto:["pa","ubs"], nome:"Dor Oncológica — Escada Analgésica da OMS adaptada", sis:"pali", grav:"variavel",
cid:"R52.1/G89", ciap:"A01",
sin:["Dor oncológica","Escada OMS","Morfina","Opioide","Analgesia paliativa","Dor crônica câncer","Dor mista"],
def:"⚠ Dor crônica em paciente oncológico — manejo baseado na ESCADA ANALGÉSICA DA OMS (1986, atualizada). PRINCÍPIO MODERNO: subir/descer pela escada conforme INTENSIDADE da dor (não 'tentar tudo até falhar'). Adjuvantes em qualquer degrau. Via VO preferida, SC quando VO inviável. ⚠ DOR SEVERA = MORFINA DIRETA — não passar por tramadol/codeína.",
quadro:["Avaliar DOR EM TODAS as consultas — 5º sinal vital","ESCALA: EVA 0-10 (numérica/visual analógica) OU verbal: leve / moderada / severa","Distinguir: NOCICEPTIVA somática (osso, partes moles — bem localizada), NOCICEPTIVA visceral (mal localizada, em cólica), NEUROPÁTICA (queimação, choque, parestesia — adjuvantes essenciais)","⚠ DOR INCIDENTAL: surge ao movimento — analgesia de RESGATE programada antes do esforço","⚠ DOR BREAKTHROUGH (irruptiva): pico súbito sobre dor basal controlada — resgate disponível"],
diag:["⚠ CLÍNICO — caracterizar: localização, intensidade (EVA), tipo (somática/visceral/neuropática), fatores de melhora/piora, duração, função afetada","Mapear dor em corpo (estudo de Brewer)","Avaliar IMPACTO em sono, humor, função, social","⚠ ESCALAS recomendadas: EVA, Brief Pain Inventory (BPI), Faces (em pediatria/cognição limitada), PAINAD (demência)"],
exames:["Rastrear sinais de DOR EMERGENTE: compressão medular (lombar+motor+esfincter), fratura patológica (dor mecânica nova), HIC, plexopatia","Imagem direcionada quando dor nova/mudança de padrão"],
rx:[
{etapa:"escala", d:"⚠ ⚠ ESCADA OMS — INTENSIDADE GUIA O DEGRAU"},
{etapa:"escala", d:"⚠ DEGRAU 1 — Dor LEVE (EVA 1-3)"},
{etapa:"escala", d:"DIPIRONA 500 mg-1 g VO 6/6h ad lib (REMUME, segura)", do:"500 mg-1 g 6/6h", via:"VO", o:""},
{etapa:"escala", d:"PARACETAMOL 500-1000 mg 6/6h (máx 4 g/d)", do:"500-1000 mg 6/6h", via:"VO", o:"⚠ Hepatotoxicidade em dose alta crônica + alcoólatra/hepatopatia."},
{etapa:"escala", d:"⚠ AINE — USO CAUTELOSO em oncológico (sangramento GI + nefrotox + cardiotox + plaquetopenia)", obs:"Ibuprofeno 600 mg 8/8h. Restringir a uso curto + paciente sem fatores de risco. EM PACIENTE COM TROMBOCITOPENIA, INSUFICIÊNCIA RENAL, IECA: ⚠ EVITAR."},
{etapa:"escala", d:"⚠ ADJUVANTES indicados desde DEGRAU 1 se houver componente:"},
{etapa:"escala", d:"DOR ÓSSEA: AINE quando seguro + BIFOSFONATOS (ác. zoledrônico 4 mg IV/mês — oncologia) + RADIOTERAPIA paliativa", obs:""},
{etapa:"escala", d:"DOR NEUROPÁTICA: GABAPENTINA 300 mg HS titular até 900-1800 mg/d OU PREGABALINA 75 mg 12/12h titular até 300-600 mg/d OU AMITRIPTILINA 10-25 mg HS (cuidado idoso) OU DULOXETINA 30-60 mg/d", obs:""},
{etapa:"escala", d:"COMPONENTE INFLAMATÓRIO/ANTITUMORAL/HIC: DEXAMETASONA 4-8 mg/d (reduzir gradativo). Em compressão medular: bolus 16 mg.", obs:""},
{etapa:"escala", d:"⚠ DEGRAU 2 — Dor MODERADA (EVA 4-6)"},
{etapa:"escala", d:"CODEÍNA 30-60 mg VO 4-6/6h (max 240 mg/d) — pro-droga, metabolismo CYP2D6 variável", do:"30-60 mg 4-6/6h", via:"VO", o:"⚠ ULTRAMETABOLIZADORES: morfinização rápida — risco intoxicação. POBRES METABOLIZADORES: ineficácia (~10% caucasianos). Crianças <12a + tonsilectomia: PROIBIDO."},
{etapa:"escala", d:"TRAMADOL 50-100 mg VO 4-6/6h (max 400 mg/d) — opioide fraco com ação serotoninérgica/noradrenérgica", do:"50-100 mg 4-6/6h", via:"VO", o:"⚠ Útil quando há componente NEUROPÁTICO + nociceptivo. Cautela: convulsão, síndrome serotoninérgica com ISRS, hiponatremia em idoso."},
{etapa:"escala", d:"⚠ EVOLUÇÃO MODERNA: o DEGRAU 2 está em desuso — em DOR MODERADA-SEVERA com expectativa de progressão, SUBIR DIRETO PARA MORFINA dose baixa (vide Degrau 3)"},
{etapa:"escala", d:"⚠ ⚠ DEGRAU 3 — Dor SEVERA (EVA 7-10) ou Moderada com expectativa de progressão"},
{etapa:"escala", d:"⚠ MORFINA — 1ª LINHA, padrão-ouro, mais barata + REMUME"},
{etapa:"escala", d:"⚠ INÍCIO em paciente OPIOIDE-NAIVE: MORFINA SIMPLES 5-10 mg VO 4/4h + RESGATE 5 mg VO 1/1h se dor não controlada", do:"5-10 mg 4/4h", via:"VO", o:"⚠ Idoso/caquético/IRC: 2,5-5 mg 4/4h. Após 24-48h: somar TOTAL DAS 24H (basal + resgates) → DIVIDIR EM 2-3 DOSES de MORFINA LP (12/12h ou 8/8h). Manter 10-15% da DOSE DIÁRIA como RESGATE 1/1h."},
{etapa:"escala", d:"⚠ MORFINA LIBERAÇÃO PROLONGADA (LP / MS Contin): 30 mg 12/12h é dose inicial habitual quando paciente já tolera morfina simples", do:"Calcular pelo total/24h", via:"VO", o:"⚠ ⚠ NÃO PARTIR / NÃO MASTIGAR a LP — engolir inteiro."},
{etapa:"escala", d:"⚠ DOR INCIDENTAL/IRRUPTIVA — RESGATE com MORFINA SIMPLES VO (10-15% da dose diária total) repetido em 1/1h conforme necessário", obs:""},
{etapa:"escala", d:"⚠ NÃO USAR DOSE MÁXIMA — TITULAR conforme efeito (não tem 'teto') + efeitos colaterais. Morfina pode chegar a 2-4 g/d em oncológico avançado."},
{etapa:"escala", d:"⚠ ⚠ VIA SUBCUTÂNEA (SC) — quando VO inviável (vômito, disfagia, obstrução, agonia)"},
{etapa:"escala", d:"⚠ CONVERSÃO VO → SC: dividir dose VO POR 2 (morfina VO 30 mg = morfina SC 15 mg)", obs:""},
{etapa:"escala", d:"Administrar 4/4h SC + resgate; OU em bomba SC contínua (4-8 mg/h ajustar conforme dor)", obs:""},
{etapa:"escala", d:"Sítios SC: deltoide, abdome, coxa, região peitoral; rodízio cada 5-7 dias", obs:""},
{etapa:"escala", d:"⚠ OUTROS OPIOIDES FORTES (alternativas)"},
{etapa:"escala", d:"OXICODONA LP 10-20 mg 12/12h — sem componente diferencial sobre morfina, mais cara, melhor em pruriginosos", do:"10-80 mg 12/12h", via:"VO", o:"Conversão: 10 mg oxicodona VO ≈ 15 mg morfina VO."},
{etapa:"escala", d:"⚠ FENTANIL TRANSDÉRMICO 12-100 mcg/h — em paciente ESTÁVEL com dor controlada, intolerância VO/SC, ESTOMA, vômitos refratários", do:"12-100 mcg/h trocar 72h", via:"TD", o:"⚠ ⚠ NÃO USAR EM DOR AGUDA / INSTÁVEL (demora 12-24h para atingir e 12-24h para sair após retirar). Conversão: morfina VO 60 mg/d ≈ fentanil 25 mcg/h. ⚠ Cuidado com febre (↑ absorção), calor, banho quente."},
{etapa:"escala", d:"⚠ ⚠ METADONA 2,5-5 mg 8-12/12h — uso em DOR REFRATÁRIA, dor neuropática complexa, rotação opioide", do:"2,5-30 mg 8-12/12h (titular lento)", via:"VO", o:"⚠ ⚠ ESPECIALISTA — meia-vida longa e variável (8-150h), conversão NÃO linear, QT longo, INTERAÇÕES MEDICAMENTOSAS importantes. Ótima em dor mista (NMDA antagonista)."},
{etapa:"escala", d:"⚠ BUPRENORFINA TRANSDÉRMICA 5-20 mcg/h trocar 7d — alternativa em IRC, idoso, intolerância morfina", do:"5-20 mcg/h 7/7d", via:"TD", o:""},
{etapa:"adj", d:"⚠ ROTAÇÃO DE OPIOIDES"},
{etapa:"adj", d:"⚠ INDICAÇÃO: efeitos colaterais intoleráveis (sedação, mioclonia, alucinação) OU eficácia insuficiente apesar de titulação OU toxicidade renal pela morfina"},
{etapa:"adj", d:"⚠ TABELA DE EQUIVALÊNCIA (MEDD — Morphine Equivalent Daily Dose):"},
{etapa:"adj", d:"Morfina VO ≡ 1 (base)"},
{etapa:"adj", d:"Codeína VO ≡ 0,15 (10 mg codeína = 1,5 mg morfina)"},
{etapa:"adj", d:"Tramadol VO ≡ 0,1-0,2 (50 mg tramadol ≈ 5-10 mg morfina)"},
{etapa:"adj", d:"Oxicodona VO ≡ 1,5 (10 mg oxicodona ≈ 15 mg morfina)"},
{etapa:"adj", d:"Morfina SC/IV ≡ 2-3× VO (15 mg SC = 30-45 mg VO)"},
{etapa:"adj", d:"Fentanil TD: 25 mcg/h ≈ morfina VO 60 mg/d"},
{etapa:"adj", d:"⚠ Metadona: NÃO LINEAR (1-12% conforme dose total — referência especializada)"},
{etapa:"adj", d:"⚠ ⚠ AO ROTACIONAR: REDUZIR 25-50% da dose calculada (cross-tolerance incompleta) — depois titular"},
{etapa:"adj", d:"⚠ EFEITOS COLATERAIS — PROFILAXIA ATIVA"},
{etapa:"adj", d:"⚠ CONSTIPAÇÃO (universal — 100%): PRESCREVER LAXATIVO COM A 1ª DOSE de opioide", obs:""},
{etapa:"adj", d:"BISACODIL 5-10 mg HS + LACTULOSE 15-30 mL 2-3×/d", do:"", via:"VO", o:""},
{etapa:"adj", d:"OU PEG (polietilenoglicol) 17 g/d", obs:""},
{etapa:"adj", d:"REFRATÁRIO: METILNALTREXONA 8-12 mg SC 1×/d", obs:"Antagonista periférico — não atravessa BHE, mantém analgesia."},
{etapa:"adj", d:"⚠ NÁUSEA (30% início — geralmente cede em 5-7d): HALOPERIDOL 0,5-2 mg VO 12/12h ad lib OU METOCLOPRAMIDA 10 mg 8/8h", obs:""},
{etapa:"adj", d:"⚠ SEDAÇÃO INICIAL: comum primeiros 3-5d, geralmente cede. Se persistir: reduzir 25% OU adicionar metilfenidato 5-10 mg manhã (off-label)", obs:""},
{etapa:"adj", d:"⚠ PRURIDO: anti-H1 (loratadina 10 mg/d). Refratário: rotacionar opioide", obs:""},
{etapa:"adj", d:"⚠ MIOCLONIA / DELIRIUM: sinal de TOXICIDADE — reduzir dose, hidratar, rotacionar (especialmente em IRC com morfina — acúmulo do M3G/M6G)", obs:""},
{etapa:"adj", d:"⚠ DEPRESSÃO RESPIRATÓRIA: raro em paciente em uso crônico bem titulado. Se ocorrer: reduzir dose; NALOXONA apenas se FR <8 ou sat <85% com bradipneia → 0,4 mg diluída em 9 mL, administrar 1 mL/min titular ao mínimo necessário (REVERSÃO COMPLETA pode precipitar dor severa + síndrome de abstinência)", obs:""},
{etapa:"alta", d:"⚠ COMUNICAÇÃO + DESMISTIFICAÇÃO"},
{etapa:"alta", d:"⚠ DESMITIFICAR opiofobia — paciente E família. 'Não é viciante quando usado para dor'. Reforçar regularidade vs PRN"},
{etapa:"alta", d:"⚠ ANTECIPAR resgates — prescrever desde início, ensinar registro de dose"},
{etapa:"alta", d:"DIÁRIO DA DOR — quando ocorre, intensidade, fator desencadeante, resgates usados"},
{etapa:"alta", d:"PSICOLOGIA, terapia ocupacional, fisioterapia — abordagem multimodal"},
{etapa:"alta", d:"⚠ DOR REFRATÁRIA / COMPLEXA → REFERENCIAR equipe especializada em paliativos / dor: bloqueios, neurolíticos (plexo celíaco), radioterapia paliativa, intervencionismo"},
],
alertas:[
{nivel:"crit", txt:"⚠ ⚠ DOR SEVERA EM ONCOLÓGICO = MORFINA DIRETA. Não 'subir devagar' por tramadol/codeína — perde tempo, gera frustração + sofrimento. Iniciar 5-10 mg VO 4/4h em opioide-naive."},
{nivel:"crit", txt:"⚠ CONSTIPAÇÃO É UNIVERSAL em opioide. PROFILAXIA com laxativo NA MESMA PRESCRIÇÃO desde a 1ª dose. Não esperar acontecer."},
{nivel:"crit", txt:"⚠ ⚠ COMPRESSÃO MEDULAR é EMERGÊNCIA. Dor lombar nova/progressiva em oncológico + qualquer sinal motor/sensitivo/esfincteriano = DEXAMETASONA 16 mg IV imediata + RM coluna urgente + radioterapia/cirurgia urgente."},
{nivel:"crit", txt:"⚠ OPIOIDE EM IRC: morfina acumula metabólitos NEUROTÓXICOS (M3G — mioclonia, alucinação, delirium). Em TFG <30: ROTACIONAR para fentanil/buprenorfina/metadona OU reduzir dose 25-50%."},
{nivel:"warn", txt:"⚠ Fentanil TRANSDÉRMICO — NUNCA em DOR INSTÁVEL/AGUDA (demora 12-24h para atingir e 12-24h após retirar). Indicado apenas em dor estável bem-controlada por morfina prévia."},
{nivel:"warn", txt:"⚠ METADONA: meia-vida muito variável, conversão NÃO linear, QT longo, múltiplas interações — USO ESPECIALISTA."},
{nivel:"warn", txt:"⚠ Codeína: ULTRAMETABOLIZADORES (CYP2D6) podem ter intoxicação aguda. CRIANÇA <12a + tonsilectomia/adenoidectomia: PROIBIDO (FDA Black Box — mortes documentadas)."},
{nivel:"warn", txt:"⚠ Tramadol + ISRS/IMAO/Tricíclico = SÍNDROME SEROTONINÉRGICA. Tramadol + Bupropiona = CONVULSÃO."},
{nivel:"info", txt:"⚠ AINE em oncológico com risco — sangramento GI, plaquetopenia, IRC, IECA — USE COM CAUTELA. Dor óssea pode beneficiar de DEXAMETASONA + bifosfonato + radioterapia."},
{nivel:"info", txt:"DOR NEUROPÁTICA: gabapentina/pregabalina + amitriptilina + duloxetina. Resposta gradual 2-4 sem. Esperar antes de mudar."},
{nivel:"info", txt:"REFRATARIEDADE: pensar em compressão medular, fratura patológica, plexopatia, dor neuropática mal abordada, sofrimento existencial 'total pain' (Cicely Saunders)."},
],
fluxo:"escada-oms", diretriz:"OMS Cancer Pain Relief; ANCP (Academia Nacional de Cuidados Paliativos); IAHPC; ESMO."
},
{id:"estertor-terminal", contexto:["pa","ubs"], nome:"Estertor da Morte / Sialorreia Terminal — manejo", sis:"pali", grav:"baixa",
cid:"R09.8", ciap:"R02",
sin:["Estertor terminal","Sororoca","Sialorreia paliativa","Hioscina","Escopolamina","Glicopirrônio"],
def:"⚠ ESTERTOR DA MORTE = ruído de gorgolejo em paciente em FASE ATIVA por acúmulo de secreção em vias aéreas (tipo I — saliva, paciente inconsciente sem deglutir; tipo II — secreção brônquica). ⚠ É MAIS ANGUSTIANTE PARA FAMÍLIA que para paciente — sedado, geralmente não sofre. Manejo: posicionamento + antimuscarínico SC + comunicação familiar.",
quadro:["⚠ RUÍDO de borbulhar / gorgolejar nas vias aéreas superiores em paciente em fase ativa de morte","Não confundir com obstrução de via aérea verdadeira / sufocamento","Paciente geralmente SEM esforço respiratório, sedado","⚠ Tipo I: secreção salivar acumulando (paciente inconsciente sem deglutir) — responde melhor ao antimuscarínico","⚠ Tipo II: secreção brônquica (causa subjacente — pneumonia, edema) — responde pior"],
diag:["⚠ Clínico — característica auscultatória + fase ativa","Observar paciente — sem esforço, sem cianose proeminente significa pouca repercussão respiratória do estertor","⚠ Diferenciar: dispneia ativa (esforço, taquipneia, uso musculatura) vs estertor passivo (ruído sem esforço aparente)"],
exames:["Geralmente nenhum — clínico"],
rx:[
{etapa:"inicial", d:"⚠ ⚠ COMUNICAÇÃO COM FAMÍLIA — INTERVENÇÃO MAIS IMPORTANTE"},
{etapa:"inicial", d:"⚠ Explicar: ruído é por acúmulo de saliva — paciente não está 'sufocando', não há sofrimento subjetivo significativo"},
{etapa:"inicial", d:"⚠ Reasseguramento — 'isso é parte do processo, vamos tornar mais confortável'"},
{etapa:"escala", d:"⚠ MEDIDAS NÃO-FARMACOLÓGICAS"},
{etapa:"escala", d:"⚠ POSICIONAMENTO em DECÚBITO LATERAL — facilita drenagem por gravidade", obs:""},
{etapa:"escala", d:"Cabeceira elevada 30°", obs:""},
{etapa:"escala", d:"⚠ ⚠ NÃO ASPIRAR rotineiramente — invasivo, doloroso, estimula tosse, MAIS secreção reativa. Aspiração apenas se secreção volumosa e bloqueando aeração", obs:""},
{etapa:"escala", d:"Cuidados orais — limpar boca com gaze úmida, hidratar mucosa", obs:""},
{etapa:"escala", d:"⚠ REDUZIR HIDRATAÇÃO PARENTERAL — se em curso, suspender ou minimizar (piora estertor)", obs:""},
{etapa:"escala", d:"⚠ ANTIMUSCARÍNICO SC — redução de secreção"},
{etapa:"escala", d:"⚠ ⚠ HIOSCINA BUTILBROMETO (BUSCOPAN) 20 mg SC 4-6/6h OU BIC 60-120 mg/d", do:"20 mg 4-6/6h SC", via:"SC", o:"⚠ ⚠ NÃO atravessa BHE — sem sedação, sem delirium. SEGURO em paciente acordado. 1ª LINHA NO BRASIL (disponível)."},
{etapa:"escala", d:"⚠ ESCOPOLAMINA (hioscina HIDROBROMETO) 0,4-0,6 mg SC 4-6/6h OU adesivo transdérmico 1 mg cada 72h", do:"0,4-0,6 mg 4-6/6h SC", via:"SC/TD", o:"⚠ Atravessa BHE — pode causar SEDAÇÃO + delirium em algumas pessoas. Adesivo é prático."},
{etapa:"escala", d:"⚠ GLICOPIRRÔNIO 0,2-0,4 mg SC 4-6/6h — mais potente, NÃO atravessa BHE", obs:"Acesso difícil no SUS."},
{etapa:"escala", d:"ATROPINA 0,4-0,6 mg SC 4-6/6h — alternativa em emergência (uso de injeção de atropina já disponível)", do:"0,4-0,6 mg 4-6/6h SC", via:"SC", o:"Atravessa BHE — risco delirium. Uso temporário."},
{etapa:"escala", d:"⚠ INÍCIO PRECOCE é mais eficaz — antes que muita secreção acumule. Em fase ativa: PRESCREVER PROACTIVAMENTE"},
{etapa:"adj", d:"⚠ EFICÁCIA da antimuscarínica é MODESTA — reduz secreção NOVA, não a secreção JÁ ACUMULADA"},
{etapa:"adj", d:"Em refratários: posicionamento + redução de hidratação + paciência + apoio familiar"},
{etapa:"alta", d:"⚠ FOCO EM CONFORTO familiar — explicar processo natural, reforçar que paciente está sereno"},
],
alertas:[
{nivel:"crit", txt:"⚠ ⚠ ESTERTOR É MAIS ANGUSTIANTE PARA A FAMÍLIA — paciente sedado raramente sofre. COMUNICAÇÃO FAMILIAR é tratamento principal."},
{nivel:"crit", txt:"⚠ ⚠ NÃO ASPIRAR rotineiramente — invasivo, doloroso, aumenta secreção reativa. Apenas se secreção volumosa obstruindo aeração."},
{nivel:"warn", txt:"⚠ HIOSCINA BUTILBROMETO (Buscopan) NÃO atravessa BHE — sem sedação/delirium adicional. 1ª linha no Brasil. ESCOPOLAMINA (hidrobrometo) atravessa BHE — risco delirium."},
{nivel:"warn", txt:"⚠ REDUZIR HIDRATAÇÃO PARENTERAL em fase ativa — piora estertor (e edema, sobrecarga, secreção respiratória). Geralmente suspender."},
{nivel:"info", txt:"⚠ ANTIMUSCARÍNICO precoce > tardio — secreção JÁ ACUMULADA não regride. Prescrever proactivamente quando estertor inicia."},
],
fluxo:null, diretriz:"ANCP; Wee-Hudson Sistema Review; EAPC."
},
{id:"hipercalcemia-maligna", contexto:["pa","ubs"], nome:"Hipercalcemia da Malignidade — EMERGÊNCIA paliativa", sis:"pali", grav:"grave",
cid:"E83.5", ciap:"T99",
sin:["Hipercalcemia maligna","PTHrP","Bifosfonato","Ácido zoledrônico","Calcitonina","Denosumab"],
def:"⚠ EMERGÊNCIA — cálcio iônico ou Ca total CORRIGIDO PELA ALBUMINA >12 mg/dL com sintomas (poliúria, polidipsia, fraqueza, letargia, confusão, náusea, constipação severa, arritmia). ⚠ Frequente em mama, pulmão, mieloma, rim, cabeça e pescoço. Mortalidade alta em hipercalcemia GRAVE (>14) — tratamento emergencial paliativo.",
quadro:["⚠ NEURO: letargia, confusão, sonolência, coma (com Ca >15)","⚠ GU: poliúria (diabete insipidus nefrogênico), desidratação intensa","⚠ GI: constipação severa, náusea, vômito, anorexia, dor abdominal, pancreatite (raro)","⚠ MUSC: fraqueza, hipotonia, fraqueza proximal","⚠ CV: bradicardia, encurtamento QT, BLOQUEIO em hipercalcemia muito alta","Risco de PCR em Ca >15-16"],
diag:["⚠ Cálcio total — sempre CORRIGIR PELA ALBUMINA: Ca corrigido = Ca medido + 0,8 × (4 − albumina)","Ou medir CÁLCIO IÔNICO (mais preciso)","⚠ Em paciente oncológico com sintomas inexplicados (letargia, constipação, fraqueza): SEMPRE pedir cálcio"],
exames:["⚠ Cálcio total + albumina (calcular corrigido) OU cálcio iônico","Fósforo","Função renal — ureia, creatinina","Eletrólitos","PTH (afastar hiperparatireoidismo primário em casos atípicos)","ECG — QT, arritmia","Glicemia"],
rx:[
{etapa:"inicial", d:"⚠ ⚠ HIDRATAÇÃO VIGOROSA — pedra angular do tratamento"},
{etapa:"inicial", d:"⚠ SOLUÇÃO SALINA 0,9% 200-500 mL/h IV — corrige desidratação + aumenta excreção renal de cálcio", do:"200-500 mL/h IV", via:"IV", o:"⚠ Volume total: 2-4 L em 24h. Monitor: PA, ausculta pulmonar, débito urinário, balanço."},
{etapa:"inicial", d:"⚠ ⚠ EM PALIATIVO COM SOBREVIDA MUITO LIMITADA: avaliar SE TRATAR — vide alerta. Em fase ativa de morte: hipercalcemia pode ser via de morte 'mais suave' — discutir com paciente/família"},
{etapa:"escala", d:"⚠ FUROSEMIDA 20-40 mg IV — usar APENAS após CORRIGIR desidratação. Aumenta cálcio urinário."},
{etapa:"escala", d:"⚠ NÃO usar tiazídico (reduz cálcio urinário)"},
{etapa:"escala", d:"⚠ ⚠ BIFOSFONATO — droga de DESFECHO"},
{etapa:"escala", d:"⚠ ÁCIDO ZOLEDRÔNICO 4 mg IV em 15 min", do:"4 mg IV em 15 min", via:"IV", o:"⚠ INÍCIO de ação em 24-48h. Pico em 4-7 dias. Duração ~30 dias. Reduzir 50% se TFG 30-60. ⚠ EVITAR em TFG <30."},
{etapa:"escala", d:"⚠ PAMIDRONATO 60-90 mg IV em 2-4h — alternativa", do:"60-90 mg IV em 2-4h", via:"IV", o:"Menos potente."},
{etapa:"escala", d:"⚠ HIDRATAR adequadamente antes (>2L) — bifosfonato é nefrotóxico em desidratação"},
{etapa:"escala", d:"⚠ CALCITONINA 4-8 UI/kg SC/IM 12/12h — ação RÁPIDA (12-24h) mas taquifilaxia em 48-72h", do:"4-8 UI/kg SC 12/12h", via:"SC/IM", o:"⚠ Útil em pacientes em ESPERA do efeito do bifosfonato (primeiras 24-48h). Eficácia decai."},
{etapa:"escala", d:"⚠ DENOSUMAB 120 mg SC — anticorpo anti-RANKL. Alternativa em IRC (TFG <30 onde bifosfonato é proibido)", do:"120 mg SC dose única", via:"SC", o:"Custo alto. Especialista."},
{etapa:"escala", d:"⚠ DEXAMETASONA — útil em hipercalcemia por LINFOMA, MIELOMA, GRANULOMATOSE (mediação 1,25-OH-vit D)", obs:"Não é eficaz em hipercalcemia por PTHrP."},
{etapa:"adj", d:"⚠ EM HIPERCALCEMIA REFRATÁRIA / GRAVE COM IRC + RISCO DE VIDA: HEMODIÁLISE com banho baixo cálcio"},
{etapa:"adj", d:"⚠ MOBILIZAÇÃO precoce (imobilidade piora hipercalcemia)"},
{etapa:"alta", d:"⚠ DISCUTIR PROGNÓSTICO + OBJETIVOS — hipercalcemia maligna é frequentemente MARCADOR DE FASE AVANÇADA"},
{etapa:"alta", d:"⚠ Sobrevida média após hipercalcemia maligna = ~30 dias (sem tratamento específico do tumor)"},
{etapa:"alta", d:"⚠ TRATAR vs OBSERVAR — decisão depende de objetivos. Tratar pode reverter sintomas e dar 'tempo' para conversas/encerramentos; não tratar pode ser óbito sem sofrimento"},
],
alertas:[
{nivel:"crit", txt:"⚠ ⚠ HIPERCALCEMIA MALIGNA é EMERGÊNCIA. Hidratação salina 0,9% 200-500 mL/h + bifosfonato (ác. zoledrônico 4 mg IV) + considerar calcitonina como ponte."},
{nivel:"crit", txt:"⚠ ⚠ EM PALIATIVO AVANÇADO / FASE ATIVA: avaliar SE TRATAR. Hipercalcemia maligna é frequentemente VIA DE MORTE 'mais suave' que outras (letargia → coma). Discussão compartilhada com paciente/família."},
{nivel:"warn", txt:"⚠ FUROSEMIDA: usar APENAS APÓS hidratação adequada. Tiazídico é CONTRAINDICADO (↓ excreção de cálcio)."},
{nivel:"warn", txt:"⚠ ÁCIDO ZOLEDRÔNICO em TFG <30: EVITAR. Em TFG 30-60: 50% dose. Em IRC importante: denosumab é alternativa."},
{nivel:"warn", txt:"⚠ DEXAMETASONA: útil em hipercalcemia por LINFOMA / MIELOMA / GRANULOMATOSE. NÃO é eficaz em hipercalcemia por PTHrP (mama, pulmão escamoso)."},
{nivel:"info", txt:"⚠ SOBREVIDA MÉDIA após hipercalcemia maligna não tratada = ~30 dias. Tratar pode REVERTER sintomas e proporcionar TEMPO para conversas + encerramentos."},
],
fluxo:null, diretriz:"NCCN; ESMO; ASCO; Major et al; Stewart NEJM."
},
{id:"nausea-paliativa", contexto:["pa","ubs"], nome:"Náusea e Vômito em Paliativos — manejo por mecanismo", sis:"pali", grav:"moderada",
cid:"R11", ciap:"D09",
sin:["Náusea paliativa","Vômito paliativo","Antiemético","Haloperidol náusea","Metoclopramida","Ondansetrona"],
def:"⚠ Náusea/vômito acometem 40-70% de pacientes paliativos. ⚠ CHAVE: identificar MECANISMO predominante (4-5 mecanismos comuns) — o antiemético DEPENDE do mecanismo. Tratar com 'qualquer um' geralmente falha. ⚠ Sempre via SC quando vômito persistente.",
quadro:["⚠ 5 MECANISMOS PRINCIPAIS (identificar para escolher droga):","(1) ⚠ ESTÍMULO QUÍMICO via CTZ (zona quimioceptora) — opioides, quimio recente, uremia, hipercalcemia, hiponatremia, infecção, drogas. Receptores D2 + 5-HT3","(2) ⚠ ESTASE GÁSTRICA / OBSTRUÇÃO PARCIAL — saciedade precoce, plenitude, refluxo. Tratamento PROCINÉTICO","(3) ⚠ ESTÍMULO VESTIBULAR / movimento — piora com mudança postural. Receptores H1 + muscarínicos","(4) ⚠ ESTÍMULO CORTICAL — ansiedade, ambiente, antecipação. BZD + suporte","(5) ⚠ ESTÍMULO VAGAL / mecanorreceptores — distensão GI, tumor abdominal, constipação, OBSTRUÇÃO MECÂNICA INTESTINAL — corticoide + opioide + antiemético + considerar octreotida","⚠ Constipação + impactação fecal é causa frequente e SUBESTIMADA — sempre avaliar"],
diag:["⚠ ANAMNESE direcionada ao mecanismo:","'Quando começou?' (relação com novo medicamento, quimio, progressão tumoral)","'Sensação de plenitude precoce, refluxo, eructação?' → ESTASE","'Náusea piora com movimento?' → VESTIBULAR","'Ansiedade, antecipação à comida/quimio?' → CORTICAL","'Distensão abdominal, parada de eliminação?' → OBSTRUÇÃO MECÂNICA","Examinar abdome: distensão, RHA (silente / metálicos / aumentados), massas, fecaloma","Toque retal — descartar impactação","Investigar: eletrólitos (Na, Ca), função renal (uremia), causa infecciosa"],
exames:["Eletrólitos (Na, Ca, Mg, K)","Função renal e hepática","Glicemia","⚠ Rx abdome em pé/decúbito — descartar OBSTRUÇÃO INTESTINAL (níveis hidroaéreos, distensão de alças)","Hemograma + PCR se infecção possível"],
rx:[
{etapa:"inicial", d:"⚠ AVALIAR + TRATAR causas REVERSÍVEIS específicas"},
{etapa:"inicial", d:"Hipercalcemia (Ca corrigido >12): hidratação salina + ác. zoledrônico"},
{etapa:"inicial", d:"Hiponatremia: investigar/corrigir SIADH, reposição cuidadosa"},
{etapa:"inicial", d:"Uremia: avaliar diálise paliativa OU controle sintomático"},
{etapa:"inicial", d:"⚠ Constipação grave / impactação: tratar (laxativos, lavagem retal, supositório)"},
{etapa:"inicial", d:"⚠ HIC: dexametasona 8-16 mg/d"},
{etapa:"escala", d:"⚠ ⚠ ESCOLHER ANTIEMÉTICO PELO MECANISMO"},
{etapa:"escala", d:"⚠ (1) CTZ / QUÍMICO (opioide, quimio, uremia, hipercalcemia)"},
{etapa:"escala", d:"⚠ HALOPERIDOL 0,5-2 mg VO/SC 12/12h ad lib — 1ª LINHA. Antagonista D2. Baixa sedação.", do:"0,5-2 mg 12/12h", via:"VO/SC", o:""},
{etapa:"escala", d:"OU METOCLOPRAMIDA 10 mg VO/SC 6-8/8h (max 30 mg/d — limitação por extrapiramidal)", do:"10 mg 6/6h", via:"VO/SC", o:"Ação dupla: anti-D2 + procinética. ⚠ Sintomas extrapiramidais."},
{etapa:"escala", d:"OU ONDANSETRONA 4-8 mg VO/SC 8/8h — útil em náusea por QUIMIO (5-HT3), pós-op, gestação", do:"4-8 mg 8/8h", via:"VO/SC", o:"⚠ Causa CONSTIPAÇÃO + QT longo."},
{etapa:"escala", d:"⚠ (2) ESTASE GÁSTRICA / saciedade precoce / dispepsia / náusea pós-prandial"},
{etapa:"escala", d:"⚠ METOCLOPRAMIDA 10 mg VO/SC 6-8/8h ANTES DAS REFEIÇÕES — 1ª LINHA (procinética via 5-HT4 + anti-D2)", do:"10 mg 6/6h", via:"VO/SC", o:""},
{etapa:"escala", d:"BROMOPRIDA 10 mg VO/SC 6-8/8h — similar à metoclopramida", obs:""},
{etapa:"escala", d:"⚠ ⚠ NÃO USAR em SUSPEITA DE OBSTRUÇÃO MECÂNICA (cólica, distensão, vômito persistente) — pode piorar"},
{etapa:"escala", d:"⚠ (3) VESTIBULAR / cinetose / mudança postural"},
{etapa:"escala", d:"DIMENIDRINATO 50-100 mg VO 6-8/8h — anti-H1 + anticolinérgico", do:"50-100 mg 6-8/8h", via:"VO", o:""},
{etapa:"escala", d:"PROMETAZINA 25 mg VO/IM 8-12/12h — anti-H1 + anti-D2 (multimecanismo, sedativa)", do:"25 mg 8-12/12h", via:"VO/IM", o:""},
{etapa:"escala", d:"ESCOPOLAMINA TRANSDÉRMICA — útil em vestibular + sialorreia (adesivo retroauricular)", obs:""},
{etapa:"escala", d:"⚠ (4) CORTICAL / ansiedade / antecipação"},
{etapa:"escala", d:"⚠ LORAZEPAM 0,5-1 mg VO/SL antes do estímulo (ex: antes da quimio)", do:"0,5-1 mg", via:"SL/VO", o:""},
{etapa:"escala", d:"+ Suporte psicoterapêutico, técnicas de relaxamento, ambiente", obs:""},
{etapa:"escala", d:"⚠ (5) MECANORRECEPTORES / OBSTRUÇÃO INTESTINAL MALIGNA"},
{etapa:"escala", d:"⚠ ⚠ ABORDAGEM TRÍADE — corticoide + opioide + antiemético + ANTI-SECRETOR"},
{etapa:"escala", d:"DEXAMETASONA 8-16 mg/d SC/IV (reduz edema peritumoral, anti-inflamatório, antiemético)", do:"8-16 mg/d", via:"SC/IV", o:""},
{etapa:"escala", d:"MORFINA SC para dor/cólica + ANTIEMÉTICO (haloperidol; NÃO metoclopramida — pode piorar)", obs:""},
{etapa:"escala", d:"⚠ ⚠ HIOSCINA BUTILBROMETO (Buscopan) 20 mg SC 6/6h — antiespasmódico para cólica obstrutiva", do:"20 mg 6/6h", via:"SC", o:""},
{etapa:"escala", d:"⚠ ⚠ OCTREOTIDA 100-300 mcg SC 8/8h OU 300-900 mcg/d SC contínua — REDUZ secreção GI, descomprime alça obstruída (alternativa cirúrgica em paciente fora de cirurgia)", do:"100-900 mcg/d ÷ 8/8h ou contínua", via:"SC", o:"⚠ Especialista. Custo alto."},
{etapa:"escala", d:"⚠ Avaliar SNG de alívio (descompressiva) — em obstrução alta, vômito incoercível, conforto", obs:""},
{etapa:"adj", d:"⚠ NÁUSEA REFRATÁRIA — combinar drogas com MECANISMOS DIFERENTES"},
{etapa:"adj", d:"Ex: haloperidol (D2) + ondansetrona (5-HT3) + dexametasona (anti-inflamatória)", obs:""},
{etapa:"adj", d:"⚠ ⚠ LEVOMEPROMAZINA 6,25-12,5 mg VO/SC 12-24/24h — antiemético de AMPLO ESPECTRO (D2, 5-HT, H1, muscarínico) — 'limpa-tudo' em refratários", do:"6,25-12,5 mg HS ou 12/12h", via:"VO/SC", o:"⚠ Sedativa. Útil em fase mais avançada."},
{etapa:"adj", d:"OLANZAPINA 2,5-10 mg/d — alternativa em refratários (off-label, evidência crescente)", obs:""},
{etapa:"adj", d:"DRONABINOL / canabinoides — em alguns países disponíveis", obs:""},
{etapa:"alta", d:"⚠ MEDIDAS NÃO-FARMACOLÓGICAS"},
{etapa:"alta", d:"REFEIÇÕES PEQUENAS e frequentes; alimentos frios podem ser melhor tolerados; evitar odores fortes"},
{etapa:"alta", d:"GENGIBRE 1-2 g/d (chá, balas) — evidência modesta", obs:""},
{etapa:"alta", d:"AROMATERAPIA (menta, limão) — alguns pacientes respondem", obs:""},
{etapa:"alta", d:"AMBIENTE ventilado, sem odores de cozinha, posição confortável", obs:""},
],
alertas:[
{nivel:"crit", txt:"⚠ ⚠ IDENTIFICAR MECANISMO — antiemético sem mecanismo é tiro no escuro. Haloperidol em CTZ. Metoclopramida em ESTASE. Anti-H1 em VESTIBULAR. BZD em CORTICAL. Tríade (cortico + opioide + anti-D2 + hioscina + octreotida) em OBSTRUÇÃO."},
{nivel:"crit", txt:"⚠ ⚠ METOCLOPRAMIDA / BROMOPRIDA são CONTRAINDICADAS em OBSTRUÇÃO INTESTINAL MECÂNICA — procinéticos pioram. Em suspeita: parar e investigar."},
{nivel:"warn", txt:"⚠ ⚠ Constipação grave / impactação fecal é CAUSA FREQUENTE e SUBESTIMADA de náusea/vômito em paliativos. Toque retal + Rx abdome antes de assumir mecanismo central."},
{nivel:"warn", txt:"⚠ ONDANSETRONA causa CONSTIPAÇÃO + QT longo. Em paciente já em opioide (constipação) ou em risco cardíaco: cuidado."},
{nivel:"warn", txt:"⚠ HALOPERIDOL e PROMETAZINA em IDOSO: risco extrapiramidal + sedação. Doses baixas (haloperidol 0,5-1 mg)."},
{nivel:"info", txt:"⚠ OBSTRUÇÃO INTESTINAL MALIGNA — abordagem tríade: dexametasona + opioide + hioscina butilbrometo (antiespasmódico) + considerar octreotida (anti-secretor). SNG descompressiva quando vômito incoercível."},
{nivel:"info", txt:"⚠ NÁUSEA REFRATÁRIA: combinar drogas com mecanismos DIFERENTES, ou usar LEVOMEPROMAZINA (espectro amplo)."},
],
fluxo:"nausea-paliativa", diretriz:"NICE Palliative Care; ANCP; ESMO."
},
{id:"sedacao-paliativa", contexto:["pa","ubs"], nome:"Sedação Paliativa — princípios e protocolo", sis:"pali", grav:"grave",
cid:"Z51.5", ciap:"A20",
sin:["Sedação paliativa","Sedação terminal","Midazolam paliativa","Sintoma refratário","Doutrina duplo efeito"],
def:"⚠ SEDAÇÃO PALIATIVA = uso INTENCIONAL de sedativos para REDUZIR CONSCIÊNCIA de paciente em fim de vida com SINTOMA REFRATÁRIO insuportável. ⚠ ≠ EUTANÁSIA (intenção é aliviar sintoma, não causar morte — princípio do DUPLO EFEITO). ⚠ ≠ Sedação 'leve' em UTI. Pode ser PROPORCIONAL (manter o mínimo necessário para conforto) ou PROFUNDA (refratariedade grave).",
quadro:["⚠ INDICAÇÕES: sintoma REFRATÁRIO + insuportável + em paciente com PROGNÓSTICO MUITO LIMITADO (horas-dias):","Dor refratária a opioide titulado","Dispneia refratária a opioide + BZD","Delirium / agitação terminal refratários","Vômito incoercível","Hemorragia maciça (cuidados de conforto)","Distresse existencial REFRATÁRIO (controverso — discussão multidisciplinar)","⚠ NÃO INDICAÇÃO: paciente com horizonte de semanas-meses + sintoma controlável"],
diag:["⚠ AVALIAÇÃO MULTIDISCIPLINAR — discutir caso com equipe + família + paciente quando lúcido","⚠ Critérios para 'refratariedade':","Sintoma não controlado apesar de abordagem otimizada","Toxicidade inaceitável de tratamentos","Probabilidade muito baixa de resposta a outras terapias","⚠ DOCUMENTAR: intenção (alívio de sintoma, não acelerar morte), discussão com paciente/família, opções exploradas, plano de monitorização","⚠ TIPOS:","PROPORCIONAL: dose mínima para conforto, mantém consciência se possível","PROFUNDA CONTÍNUA: para refratariedade grave em fase ativa","TRANSITÓRIA: respiro temporário (ex: 'crise' aguda, depois reavaliar)"],
exames:["Geralmente clínico","Foco em controle sintomático — exames adicionais apenas se mudam conduta"],
rx:[
{etapa:"inicial", d:"⚠ ⚠ DECISÃO COMPARTILHADA — paciente (se lúcido), família, equipe multidisciplinar"},
{etapa:"inicial", d:"⚠ DOCUMENTAR claramente: intenção (alívio sintoma refratário), sintoma alvo, opções exploradas e falhadas, plano de monitorização, comunicação com família"},
{etapa:"inicial", d:"⚠ NÃO ABANDONAR cuidados — sedação paliativa NÃO É retirar cuidado, é INTENSIFICAR conforto"},
{etapa:"escala", d:"⚠ MIDAZOLAM — 1ª LINHA"},
{etapa:"escala", d:"⚠ INDUÇÃO: 2,5-5 mg SC bolus (idoso/caquético: 1-2,5 mg), repetir cada 10-15 min até conforto", do:"2,5-5 mg SC bolus", via:"SC", o:""},
{etapa:"escala", d:"MANUTENÇÃO: BIC SC 0,5-2 mg/h (titular conforme RASS alvo)", do:"0,5-2 mg/h SC contínua", via:"SC", o:"⚠ Em paciente jovem/estável: doses maiores. Em idoso/caquético: doses bem menores."},
{etapa:"escala", d:"Alternativa BIC IV 1-3 mg/h se via IV mantida", obs:""},
{etapa:"escala", d:"⚠ RASS ALVO geralmente -2 a -3 (sedação leve a moderada — paciente arousable mas confortável); -4 a -5 em refratariedade extrema"},
{etapa:"escala", d:"⚠ MIDAZOLAM REFRATÁRIO (raro):"},
{etapa:"escala", d:"⚠ LEVOMEPROMAZINA SC 12,5-25 mg cada 4-6h OU BIC 50-100 mg/d — adicionar ao midazolam (efeito antiemético + sedativo + analgésico adjuvante)", do:"12,5-100 mg/d ÷ 4-6/6h ou BIC", via:"SC", o:""},
{etapa:"escala", d:"⚠ FENOBARBITAL SC bolus 100-200 mg + BIC 600-1600 mg/d — sedação profunda em refratários", obs:"Especialista."},
{etapa:"escala", d:"⚠ PROPOFOL BIC IV 0,5-2 mg/kg/h — em hospital com acesso IV mantido + monitor", obs:"Ambiente hospitalar."},
{etapa:"escala", d:"⚠ CETAMINA SC — em dor refratária associada (efeito dissociativo + analgésico)", obs:"Especialista."},
{etapa:"adj", d:"⚠ ⚠ MANTER OPIOIDE em paralelo — sedação NÃO substitui analgesia. Manter morfina, ajustar conforme dor/dispneia"},
{etapa:"adj", d:"⚠ MANTER HIOSCINA se estertor; manter haloperidol se náusea"},
{etapa:"adj", d:"⚠ DESPRESCREVER medicações não-essenciais (anti-hipertensivos, hipoglicemiantes, estatinas, etc) — fase ativa não justifica"},
{etapa:"adj", d:"⚠ HIDRATAÇÃO — discussão individualizada"},
{etapa:"adj", d:"Em fase ativa de morte: hidratação parenteral GERALMENTE NÃO BENEFICIA + pode piorar edema, estertor, sobrecarga. Suspender ou minimizar"},
{etapa:"adj", d:"Em paciente com expectativa de dias-semanas + delirium hipoativo por desidratação: pode-se considerar hipodermoclise 500-1000 mL/d SC"},
{etapa:"alta", d:"⚠ COMUNICAÇÃO CONTINUA com família"},
{etapa:"alta", d:"⚠ Reforçar: 'estamos aliviando o sofrimento, não acelerando a morte'"},
{etapa:"alta", d:"Informar processo esperado: respiração pode ficar irregular, estertor pode aparecer (não é sufocamento subjetivo), pele pode ficar mosqueada/marmórea"},
{etapa:"alta", d:"Encorajar família a falar com paciente, tocar, presença — audição persiste mais tempo"},
{etapa:"alta", d:"⚠ APOIO ao LUTO — antecipatório + pós-óbito"},
{etapa:"alta", d:"⚠ EQUIPE — apoio mútuo, supervisão; sedação paliativa é estresse emocional para profissionais"},
],
alertas:[
{nivel:"crit", txt:"⚠ ⚠ SEDAÇÃO PALIATIVA ≠ EUTANÁSIA. Intenção é aliviar sintoma refratário, não causar morte. Princípio do DUPLO EFEITO — ética + legalmente aceito no Brasil (Resolução CFM 1.805/2006 + 2.156/2016)."},
{nivel:"crit", txt:"⚠ REFRATARIEDADE deve ser bem documentada — sintoma intratável apesar de abordagem otimizada, com baixa probabilidade de resposta a outras terapias. Discussão multidisciplinar."},
{nivel:"warn", txt:"⚠ MIDAZOLAM SC é 1ª linha. Indução com bolus (2,5-5 mg) até conforto, depois BIC 0,5-2 mg/h. Idoso/caquético: doses menores."},
{nivel:"warn", txt:"⚠ MANTER ANALGESIA — sedação não substitui opioide. Morfina + midazolam em paralelo."},
{nivel:"info", txt:"⚠ HIDRATAÇÃO em fase ativa: GERALMENTE NÃO ÚTIL e pode piorar (edema, estertor, sobrecarga). Suspender ou minimizar (≤500 mL/d SC)."},
{nivel:"info", txt:"⚠ DOCUMENTAR: intenção, sintoma alvo, opções falhadas, discussão com família, plano de monitorização. Proteção ética e legal."},
],
fluxo:"sedacao-paliativa", diretriz:"ANCP Diretrizes Sedação Paliativa; EAPC; CFM Res 1.805/2006 + 2.156/2016; Cherny+Radbruch."
},
{id:"ultimas-horas", contexto:["pa","ubs"], nome:"Últimas Horas de Vida — Cuidados + Kit + Via Subcutânea (SC)", sis:"pali", grav:"grave",
cid:"Z51.5", ciap:"A20",
sin:["Fim de vida","Últimas horas","Kit paliativo","Via subcutânea","Hipodermoclise","Agonia"],
def:"⚠ FASE ATIVA DE MORTE = horizonte de horas-dias. Sinais clínicos clássicos. ⚠ Foco TOTAL em CONFORTO + comunicação familiar. Via SUBCUTÂNEA é via central. KIT BÁSICO previamente prescrito permite resposta rápida em domicílio sem necessidade de UPA. ⚠ Permitir morte em DOMICÍLIO quando esse é o desejo do paciente — direito assegurado.",
quadro:["⚠ SINAIS CLÍNICOS de FASE ATIVA (horas-dias):","↓ ingesta de líquidos e sólidos / dificuldade deglutição","Sonolência crescente, intervalos lúcidos cada vez menores","Respiração irregular — Cheyne-Stokes, pausas, agônica","Estertor terminal (gorgolejo)","Pele MOSQUEADA / marmórea / FRIA em extremidades, cianose periférica","Pulso fino, PA caindo","Diurese reduzida (oligo-anúria)","Alteração cognitiva — delirium, alucinações 'visitantes', referência a viagem","Aparente 'alívio' nas últimas horas em alguns (calm before)","⚠ Pode haver DESPERTAR antes do óbito ('lucidez terminal' / surge final) — frequentemente significativo emocionalmente"],
diag:["⚠ CLÍNICO — reconhecimento de fase","Aceitação da família e do paciente quando possível — não 'forçar reanimação' em fase ativa","⚠ DOCUMENTAR: paciente em fase ativa, plano de cuidados (não-RCP em geral, foco conforto, via SC)","Discussão de OBJETIVOS DE CUIDADO — se ainda não feita, agora"],
exames:["⚠ Geralmente NENHUM — exames adicionais não modificam conduta","Não fazer 'check' de exames laboratoriais de rotina","⚠ DESPRESCREVER medicações não-essenciais"],
rx:[
{etapa:"inicial", d:"⚠ ⚠ ⚠ RECONHECIMENTO DA FASE — comunicar família com clareza"},
{etapa:"inicial", d:"'Estamos entrando nos últimos dias/horas. O foco agora é conforto e presença'"},
{etapa:"inicial", d:"⚠ Reorganizar prioridades: CONFORTO + DIGNIDADE + PRESENÇA FAMILIAR + AMBIENTE"},
{etapa:"escala", d:"⚠ DESPRESCREVER medicações não-essenciais"},
{etapa:"escala", d:"SUSPENDER: anti-hipertensivos, hipoglicemiantes, estatinas, suplementos, vitaminas, antiagregante, AAS preventivo, beta-bloqueador (avaliação caso a caso)"},
{etapa:"escala", d:"MANTER: opioides, antiemético, sedativo, antimuscarínico (estertor), corticoide se útil sintomático"},
{etapa:"escala", d:"⚠ AVALIAR via — VO frequentemente inviável (disfagia, sonolência)"},
{etapa:"escala", d:"⚠ ⚠ VIA SUBCUTÂNEA (SC) — VIA CENTRAL EM PALIATIVOS"},
{etapa:"escala", d:"⚠ ACESSO: cateter (butterfly 21-25 G ou cateter Saf-T-Intima 24G), sítios: deltóide, abdome, coxa anterior, infraclavicular, escapular"},
{etapa:"escala", d:"⚠ RODÍZIO cada 5-7 dias OU se irritação local"},
{etapa:"escala", d:"⚠ VOLUME por sítio: bolus ≤ 2 mL; infusão contínua ≤ 1-2 mL/h (até 4 mL/h se necessário)"},
{etapa:"escala", d:"⚠ DROGAS COMPATÍVEIS SC: morfina, midazolam, haloperidol, levomepromazina, dexametasona, ondansetrona, metoclopramida, hioscina butilbrometo, escopolamina, octreotida, furosemida (volume baixo), enoxaparina, insulina"},
{etapa:"escala", d:"⚠ ⚠ NÃO PODEM ser SC: clorpromazina (necrose), diazepam (precipitação), fenitoína (precipitação), ceftriaxona (necrose), eletrólitos concentrados (K+, NaCl 3%)"},
{etapa:"escala", d:"⚠ HIPODERMOCLISE = hidratação SC com SF 0,9% ou SG 5%, ritmo 25-125 mL/h, até 1500 mL/d. Útil em desidratação leve-moderada. ⚠ Avaliar benefício em fase ativa (frequentemente NÃO indicada)"},
{etapa:"escala", d:"⚠ ⚠ KIT FIM DE VIDA — PRESCRIÇÃO ANTECIPADA EM DOMICÍLIO"},
{etapa:"escala", d:"⚠ Permite à família + cuidador responder a sintomas SEM emergência hospitalar"},
{etapa:"escala", d:"⚠ Drogas + posologia + indicações específicas, dispostas em local acessível"},
{etapa:"escala", d:"COMPOSIÇÃO BÁSICA (variável conforme paciente):"},
{etapa:"escala", d:"(1) MORFINA simples solução oral OU ampola SC — DOR, DISPNEIA"},
{etapa:"escala", d:"(2) MIDAZOLAM ampola 5 mg/mL SC — agitação, dispneia ansiosa, sedação proporcional"},
{etapa:"escala", d:"(3) HALOPERIDOL ampola 5 mg/mL SC — náusea, delirium leve"},
{etapa:"escala", d:"(4) HIOSCINA BUTILBROMETO 20 mg ampola SC — estertor, cólica"},
{etapa:"escala", d:"(5) DEXAMETASONA 4 mg ampola SC — náusea, dispneia (selecionados)"},
{etapa:"escala", d:"(6) LEVOMEPROMAZINA — em refratários"},
{etapa:"escala", d:"+ SERINGAS (1, 5, 10 mL), agulhas 25G, gaze, álcool, papel-toalha"},
{etapa:"escala", d:"+ FOLHA DE INSTRUÇÕES com indicações + doses + telefone do plantonista"},
{etapa:"adj", d:"⚠ EQUIPE de SAD/EMAD ou cuidados paliativos domiciliar idealmente"},
{etapa:"adj", d:"⚠ Localmente: articular com SAD do município + matriciamento com paliativos regional"},
{etapa:"adj", d:"⚠ NÃO HÁ 'protocolo único' — KIT É INDIVIDUALIZADO ao paciente e sintomas previsíveis"},
{etapa:"alta", d:"⚠ COMUNICAÇÃO COM FAMÍLIA"},
{etapa:"alta", d:"⚠ Permitir / orientar: tocar, falar, despedidas — audição persiste até bem tarde"},
{etapa:"alta", d:"⚠ Sinais de morte iminente: cianose, respiração agônica, ausência de pulso, mosqueamento — explicar antes de acontecer reduz pânico"},
{etapa:"alta", d:"⚠ APÓS O ÓBITO: declaração de óbito em domicílio (em seu município, médico assistente declara — não precisa IML em óbito esperado de doença conhecida em paliativos)"},
{etapa:"alta", d:"⚠ ATESTADO em paciente em paliativos: causa imediata + causa intermediária + causa básica (CID da doença oncológica/avançada de base)"},
{etapa:"alta", d:"⚠ APOIO AO LUTO — antecipatório + pós-óbito. Acompanhamento da família é parte do cuidado paliativo"},
],
alertas:[
{nivel:"crit", txt:"⚠ ⚠ RECONHECER A FASE ATIVA — comunicar com clareza à família. Reorganizar para CONFORTO. Não 'forçar reanimação' em paciente em final de vida natural."},
{nivel:"crit", txt:"⚠ ⚠ VIA SUBCUTÂNEA é VIA CENTRAL em paliativos. Acesso fácil + pouco doloroso + drogas múltiplas compatíveis. NÃO é 'segunda escolha' — em paliativos é PRIMEIRA."},
{nivel:"warn", txt:"⚠ KIT FIM DE VIDA prescrito ANTECIPADAMENTE evita emergência domiciliar. Família/cuidador treinado pode administrar SC. Reduz hospitalização desnecessária."},
{nivel:"warn", txt:"⚠ DESPRESCREVER em fase ativa: anti-hipertensivos, hipoglicemiantes, estatinas, suplementos. Manter: opioide, antiemético, sedativo, antimuscarínico, corticoide útil."},
{nivel:"warn", txt:"⚠ ESTERTOR + RESPIRAÇÃO AGÔNICA podem parecer angustiantes para FAMÍLIA mas raramente são sofrimento para paciente. COMUNICAÇÃO é tratamento."},
{nivel:"info", txt:"⚠ DECLARAÇÃO DE ÓBITO EM DOMICÍLIO em paciente em paliativos: médico assistente declara, NÃO precisa IML em óbito esperado de doença conhecida. Causa imediata + intermediária + básica (CID neoplasia/doença avançada)."},
{nivel:"info", txt:"⚠ APOIO AO LUTO antecipatório + pós-óbito é parte do cuidado paliativo. Equipe inclui família como unidade de cuidado."},
],
fluxo:"ultimas-horas", diretriz:"ANCP; EAPC; PCMS-MS; LCP (Liverpool Care Pathway atualizado)."
},
);
