/* ===========================================================
   VOVÔMINIC DOUTÔ — pat/cron.js
   Condições Crônicas (MFC) — HAS, DM2, Síndrome Metabólica
   Sistema: cron
   Foco: PTS estruturado, REMUME, abordagem freireana, P4 explícita
   =========================================================== */

PATOLOGIAS.push(

/* ============================================================
   1. HAS — Hipertensão Arterial Sistêmica (MFC)
   ============================================================ */
{
id:"cron-has", contexto:["ubs"], nome:"Hipertensão Arterial Sistêmica (HAS) — Crônica MFC",
sis:"cron", grav:"media",
cid:"I10", ciap:"K86",
sin:["HAS","hipertensão","pressão alta","HAS crônica","Hiperdia"],
def:"HAS = PA ≥140/90 mmHg em 2+ ocasiões OU PA elevada com lesão de órgão-alvo. Diagnóstico depende de MAPA/MRPA quando disponível para confirmar (excluir HAS jaleco branco). Eixo central da APS: prevalência ~30% em adulto brasileiro, principal causa de morbimortalidade CV.",
intro:"HAS é diagnóstico estatístico e clínico, não meta arbitrária. PA é variável contínua: o risco CV não 'salta' aos 140/90 — ele cresce gradualmente. O alvo terapêutico é INDIVIDUALIZADO: idoso frágil tolera <150, jovem com risco alto se beneficia de <130, e cada paciente tem seu equilíbrio entre proteção e dano (tontura, queda, custo, polifarmácia). MFC vê HAS como uma vida — não um número.",
fisio:"PA = DC × RVP. DC depende de volemia + frequência + contratilidade. RVP depende de vasoconstrição (sistema simpático, RAA, endotelina) + remodelamento arteriolar crônico. Hipertensão primária (95% casos): poligênica + ambiente (sódio, álcool, sedentarismo, obesidade, estresse crônico). Hipertensão secundária (5%): renal (estenose arterial, parênquima), endócrina (hiperaldosteronismo, feocromocitoma, Cushing, tireoide), drogas (AINE, corticoide, simpaticomiméticos, ACO), apneia do sono. Lesão de órgão-alvo: cérebro (AVC, demência vascular), coração (HVE, ICC, IAM), rim (DRC, microalbuminúria), olho (retinopatia hipertensiva), grandes vasos (dissecção, aneurisma).",
apresentacao:"Maioria assintomática até evento agudo (AVC, IAM) ou lesão de órgão-alvo (proteinúria, HVE). Sintomas atribuídos à HAS — cefaleia, tontura, epistaxe — geralmente NÃO são causados pela pressão em si, e desaparecem com convivência (não com tratamento). Captação típica: consulta de rotina, exames pré-operatórios, pré-natal, check-up.",
sintomas:[
"Assintomático na maioria — descoberta em medida casual",
"Cefaleia occipital matinal pode ocorrer mas é inespecífica",
"Sintomas de lesão de órgão-alvo: dispneia de esforço (HVE/ICC), claudicação (DAOP), perda visual súbita (retina), proteinúria espumosa (DRC)",
"Quadro de crise hipertensiva: cefaleia intensa, dispneia, alteração visual, dor torácica, déficit neurológico (encaminhar ao PA — emergência se com LOA)",
"História familiar de HAS (parentes 1º grau) + DM2 + AVC precoce = alto risco para iniciar busca ativa",
],
profilaxia:"Não-farmacológicas (TODAS as fases): (1) Restrição de sódio para <2g/d (= 5g sal); (2) DASH: rica em frutas, vegetais, integrais, baixa gordura saturada; (3) Atividade física aeróbica 150 min/sem moderada OU 75 min vigorosa + força 2x/sem; (4) Perda de peso se IMC>25 (cada 5kg pode reduzir PAS ~5mmHg); (5) Moderar álcool: <2 doses/dia homens, <1 dose/dia mulheres; (6) Cessar tabagismo (não reduz PA mas reduz CV ~50%); (7) Manejo do estresse crônico (sono, lazer, vínculos sociais). Rastreamento primário: medida de PA em TODA consulta ambulatorial; rotina ≥18a a cada 2 anos se PA <120/80, anual se 120-139/80-89. MRPA/MAPA: confirmar diagnóstico em todo caso novo com PA limítrofe (HAS jaleco branco em 10-30%).",
freire:"HAS é doença CRÔNICA — paciente vai conviver, não 'curar'. Linguagem: 'pressão controlada' (não 'pressão normal'). Pergunta freireana: 'O que pressão alta significa pra você?' — explore mitos comuns (pressão sobe com nervoso, dói cabeça é pressão, pressão baixa é melhor). Trabalhe o COMPONENTE COMPORTAMENTAL com o paciente (não pra ele): 'qual mudança você acha que conseguiria fazer essa semana?' Pacto de pequenas mudanças mensuráveis (não 'cortar o sal' — 'tirar o saleiro da mesa por uma semana e ver como fica'). Para idoso: 'a meta da gente não é a pressão perfeita, é você estar bem, dormir bem, andar firme'. Não culpabilizar 'não-aderência'; investigar barreiras (custo, esquecimento, efeitos colaterais que ninguém perguntou, crença sobre o remédio).",
sus_tx:"Estratégia escalonada [Diretriz Brasileira de HAS 2020 + SBC]:\n\n**1ª LINHA** (REMUME + PFPB):\n• Tiazídico — Hidroclorotiazida 25 mg 1x dia, manhã (UBS + PFPB)\n• IECA — Captopril 25 mg 2-3x dia OU Enalapril 5-20 mg 1-2x dia (UBS); 10 mg PFPB\n• BRA — Losartana 50 mg 1-2x dia (UBS + PFPB) — alternativa IECA se tosse\n• BCC di-hidropiridínico — Anlodipino 5 mg 1x dia (UBS)\n\n**ESCALADA** (combinações pareadas):\n• IECA/BRA + tiazídico (sinérgico, controla 60-70%)\n• IECA/BRA + BCC (preferido para negro/idoso/lesão renal)\n• Tiazídico + BCC (alternativa)\n• Tripla terapia se necessário\n\n**4ª LINHA / refratária**:\n• Espironolactona 25-100 mg 1x dia (UBS)\n• Betabloqueador — atenolol 25-50 mg ou propranolol 40 mg (situações específicas: DAC, FA, ICC, jovem hiperadrenérgico)\n\n**SITUAÇÕES ESPECIAIS**:\n• Gestante: METILDOPA 250-500 mg 2-3x/d (PRIMEIRA LINHA gestação)\n• DM2 + microalbuminúria: priorizar IECA/BRA (renoprotetor)\n• ICC com FE reduzida: IECA/BRA + betabloqueador + espironolactona\n• Idoso frágil: começar BAIXO, ir DEVAGAR (start low, go slow)\n\n**Posologia inicial**: começar com 1 droga em dose baixa, reavaliar em 4-8 sem; titular se PA>alvo; combinar antes de aumentar doses ao máximo.",
padrao_ouro:"Alvos PA conforme [SBC Diretriz Brasileira HAS 2020] + [Diretrizes Brasileiras de Cardiogeriatria SBC-SBGG]: ◆ Adulto geral: <140/90; ◆ DM2 + lesão CV: <130/80; ◆ DRC com proteinúria: <130/80; ◆ ≥80a: <150/90 (mais permissivo); ◆ Frágil/expectativa <5a/queda recorrente: <150/90 ou conforme tolerância (não tratar agressivamente). Acréscimos da rede privada: holter PA 24h (não MAPA — ambos validados, MAPA é padrão); cintilografia perfusão se DAC suspeita. SBC orienta investigar lesão de órgão-alvo: ECG, microalbuminúria, fundoscopia, ECO se HVE no ECG ou ICC suspeita.",
prog:"PA controlada (<140/90) reduz AVC ~35%, IAM ~25%, mortalidade CV ~25% [SPRINT 2015; HOPE-3; Systolic Hypertension in the Elderly Program]. Cada 10 mmHg redução de PAS = ~20% redução evento CV [Lancet 2016 meta-análise]. Mortalidade não-tratada ~10% em 10 anos para HAS grave; tratada cai para 2-5%.",
acomp:"**Inicial (após dx)**: consulta 4-8 sem com nova PA + exames de rotina (creatinina, K+, glicemia, lipídograma, microalbuminúria, EAS, ECG; ECO se HVE no ECG). **Controle estável**: 3-6 meses com PA + revisão de eventos. **Anual**: re-screening de lesão de órgão-alvo + revisão medicação. **ACS visita**: pacientes com baixa adesão, idosos sem cuidador, mudança recente de droga. **Hiperdia**: programa MS estruturado — cadastrar para garantir entrega de medicação + retornos. **Pulseira/cartão**: alguns serviços usam cartão de acompanhamento com PA + remédios + retornos.",
p4:"⚠ ALERTA P4: (1) NÃO tratar PA 130-139/80-89 em paciente baixo risco CV global (escore Framingham <10%) — evidência fraca; preferir mudança de estilo de vida; (2) NÃO baixar PA agressivamente em idoso frágil — risco de queda, síncope, AVC isquêmico paradoxal; (3) NÃO usar 'dipirona/captopril sublingual' para PA elevada assintomática — sem evidência; (4) NÃO confundir HAS 'jaleco branco' (PA alta só no consultório) com HAS verdadeira — MRPA/MAPA é diagnóstico; (5) NÃO repetir creatinina/microalbuminúria a cada 3 meses em paciente estável — anual basta; (6) NÃO acrescentar 4ª droga sem investigar HAS secundária e adesão; (7) Cascata de prescrição: AINE para 'tonteira' do anti-hipertensivo, que SOBE a PA → mais anti-hipertensivo. Suspender AINE primeiro; (8) Idoso com >5 medicações: revisar polifarmácia (Beers, STOPP-START); (9) Não 'tratar números' — tratar pacientes com risco.",
diretriz:"[Diretriz Brasileira de Hipertensão Arterial — SBC, SBN, SBNefro, 2020 + Atualização 2024] [Caderno de Atenção Básica MS nº 37, Estratégias para o Cuidado da Pessoa com Doença Crônica: HAS] [DUNCAN 5ª ed, 2022, cap. HAS] [TMFC 2ª ed, 2019, cap. 142] [ESC Hypertension Guidelines 2024]",
mec:[
{nome:"Hidroclorotiazida (tiazídico)", como:"Inibe Na+-Cl- cotransporter no túbulo contornado distal — natriurese leve, redução de volume circulante inicial, posteriormente vasodilatação."},
{nome:"Enalapril/Captopril (IECA)", como:"Inibe ECA → bloqueia conversão Ang I → Ang II → menos vasoconstrição + menos aldosterona + menos retenção Na+. Tosse seca: por bradicinina."},
{nome:"Losartana (BRA)", como:"Bloqueia receptor AT1 da Ang II — mesmo efeito do IECA SEM tosse (não mexe com bradicinina)."},
{nome:"Anlodipino (BCC di-hidro)", como:"Bloqueia canal de Ca++ tipo L da musculatura lisa vascular → vasodilatação periférica predominante. Edema MMII: por dilatação venosa diferencial."},
{nome:"Atenolol/Propranolol (betabloq)", como:"Bloqueia β1 (cardíaco): reduz FC, contratilidade, renina. Propranolol não-seletivo bloqueia β2 também (broncospasmo, cuidado em DPOC/asma)."},
{nome:"Espironolactona", como:"Antagonista do receptor da aldosterona — diurético poupador K+, anti-fibrótico. Ginecomastia: efeito colateral por afinidade androgênica."},
{nome:"Metildopa", como:"Agonista α2 central — reduz tônus simpático. Primeira escolha gestação por segurança (uso antigo, dados extensos)."},
],
},

/* ============================================================
   2. DM2 — Diabetes Mellitus tipo 2 (MFC)
   ============================================================ */
{
id:"cron-dm2", contexto:["ubs"], nome:"Diabetes Mellitus tipo 2 — Crônica MFC",
sis:"cron", grav:"media",
cid:"E11", ciap:"T90",
sin:["DM2","diabetes 2","diabetes tipo 2","HbA1c","Hiperdia DM"],
def:"DM2 = hiperglicemia crônica por resistência insulínica + falência progressiva da célula beta. Diagnóstico: glicemia jejum ≥126 OU HbA1c ≥6,5% OU TOTG 2h ≥200 OU glicemia ao acaso ≥200 com sintomas — confirmado em 2 amostras (1 se sintomático).",
intro:"DM2 não é só 'açúcar alto'. É uma DOENÇA SISTÊMICA com risco aumentado de AVC, IAM, DRC, neuropatia, retinopatia, amputação, demência, depressão, infecção. O alvo terapêutico é INDIVIDUALIZADO conforme idade, comorbidades, expectativa de vida e preferência do paciente. Alvo de HbA1c estrito (<6,5%) NÃO é melhor que alvo padrão (<7%) em estudos longos (ACCORD, ADVANCE) — chegou a aumentar mortalidade no ACCORD. Metformina é a BASE para quase todos.",
fisio:"Resistência insulínica em tecidos (músculo, fígado, gordura) + falência progressiva de célula beta pancreática. Predisposição genética + obesidade visceral + sedentarismo + envelhecimento. Hiperglicemia crônica gera glicação não-enzimática (AGE), estresse oxidativo, inflamação vascular crônica. Resultado clínico: macrovascular (AVC, IAM, DAOP) — geralmente é o que mata; microvascular (retina, rim, nervo) — é o que incapacita.",
apresentacao:"Maioria assintomática — descoberta em rastreio (>45a OU com fatores de risco a qualquer idade: obesidade, HAS, dislipidemia, hist. fam. 1º grau, DM gestacional prévio, SOP, sedentarismo). Sintomatologia clássica (poliúria + polidipsia + perda de peso + polifagia) só em hiperglicemia severa (geralmente >250 mg/dL).",
sintomas:[
"Assintomático em >50% no diagnóstico — busca ativa via fatores de risco",
"Sintomas clássicos: poliúria, polidipsia, polifagia, perda de peso, visão turva",
"Sintomas crônicos: cansaço inexplicado, infecções recorrentes (cândida, ITU), prurido vulvar/escrotal",
"Sintomas de complicação: dor neuropática em MMII, formigamento em pés/mãos, perda visual progressiva, edema periférico (DRC), claudicação",
"Hiperglicemia descompensada aguda: CAD (cetonas, vômitos, dispneia, dor abdominal) ou EHH (idoso, confusão, desidratação severa) → encaminhar PA URGENTE",
],
profilaxia:"PREVENÇÃO PRIMÁRIA (paciente sem dx): perda de peso 5-10% reduz risco DM2 ~50% [DPP study]. Atividade física 150 min/sem. Dieta tipo mediterrânea ou DASH. Em pré-DM (HbA1c 5,7-6,4 OU GJ 100-125 OU TOTG 140-199): intervenção intensiva de estilo de vida é mais eficaz que metformina; metformina apenas se IMC>35, <60a, ou DM gestacional prévio. RASTREAMENTO: ≥45a a cada 3 anos se normal; mais frequente em alto risco. Ferramenta brasileira: FINDRISC.",
freire:"DM2 carrega culpa social ('eu comi açúcar demais'). NÃO reforçar. Trabalhe a doença como COMPLEXA, não escolha individual fácil. Linguagem: 'diabetes em controle' (não 'diabetes controlada'); 'glicemia em metas pactuadas' (não 'meta da médica'). Pergunte: 'o que você sabe sobre diabetes?' — explorar mitos (banana faz mal? remédio vicia? insulina é fim?). Trabalhar a INSULINA como ferramenta normal (não 'fracasso'): 'o pâncreas trabalhou tanto que precisa de ajuda agora'. Pé diabético: olhar O PÉ DELE em consulta — não 'orientar olhar pé'. Glicemia capilar: ensinar paciente a INTERPRETAR (não só registrar). Para idoso: 'a meta da gente não é o número perfeito — é você não passar mal, não cair, não internar'.",
sus_tx:"Estratégia escalonada [SBD Diretrizes 2024-2025]:\n\n**1ª LINHA** (todos, exceto contraindicação):\n• Metformina 500-2550 mg/dia (iniciar 500 mg 12/12h com refeição, titular cada 1-2 sem; alvo 850 mg 12/12h ou 1g 12/12h)\n• Forma XR (500-2000 mg) — melhor tolerância GI; PFPB tem versão tradicional + XR\n• Contraindicação: TFG <30 (e ajustar 30-45); insufici hepática severa; instabilidade clínica\n\n**2ª LINHA** (HbA1c não-controlada após 3-6 meses de metformina):\n• Sulfonilureia — Glibenclamida 5-20 mg/d (UBS+PFPB) OU Gliclazida MR 30-120 mg/d (UBS) — risco hipoglicemia (cuidado idoso)\n• Insulina basal — NPH 0,1-0,2 UI/kg ao deitar, titular cada 3-7 dias; PFPB tem caneta NPH/regular 3 ml\n\n**3ª LINHA / INTENSIFICAÇÃO**:\n• Insulina NPH em 2-3 doses; ajustar conforme glicemia capilar pré-refeições\n• Insulina regular pré-prandial se necessário (esquema basal-bolus)\n\n**NÃO DISPONÍVEL CBAF** (apenas via CEAF ou particular):\n• DPP-4 (sitagliptina, vildagliptina, linagliptina)\n• GLP-1 (liraglutida, semaglutida, dulaglutida)\n• SGLT2 (dapaglifozina, empaglifozina, canaglifozina) — benefício CV e renal extra, indicação preferencial em DM2+ICC ou DM2+DRC\n• Pioglitazona\n• Análogos insulina (glargina, lispro, aspart, degludeca) — algumas vias CEAF com critérios\n\n**ALVO HbA1c**: <7% para maioria; <6,5% jovem sem comorbidade; <8% idoso com hipoglicemia severa prévia, expectativa <10a, comorbidades múltiplas; <8,5% frágil/cuidados paliativos.\n\n**Glicemia capilar**: pré-prandial 80-130; pós-prandial 2h <180.\n\n**ESTATINA** (uso quase universal):\n• Sinvastatina 20-40 mg/d em todo DM2 ≥40a (mesmo LDL normal — prevenção primária); doses altas se DAC estabelecida",
padrao_ouro:"DM2 com DAC + DM2 com ICC + DM2 com DRC: SGLT2 ou GLP-1 (preferencialmente) — benefício CV/renal além do controle glicêmico [SBD; ADA Standards 2025]. Bombas de insulina: para DM1 (não DM2 rotina). Pâncreas artificial / monitorização contínua: DM1 ou DM2 instável. Cirurgia bariátrica em DM2+IMC≥35 com controle ruim — pode induzir remissão. Acréscimos privados: HbA1c capilar (ponto de cuidado), glicemia contínua (FreeStyle Libre).",
prog:"DM2 controlado (HbA1c <7%) reduz complicações microvasculares ~25% [UKPDS]. Controle precoce e intenso tem efeito 'legado' (UKPDS-PTM seguimento 10 anos). DM2 não-controlado por 10+ anos: ~30% desenvolve retinopatia significativa, ~20% nefropatia, ~30% neuropatia. Expectativa de vida: DM2 dx aos 50a reduz ~6 anos em média; bom controle + manejo de FR CV mitiga substancialmente.",
acomp:"**Inicial**: 1ª consulta + 4-8 sem para ajuste + 3 meses para revisão de HbA1c. **Estável**: 3-6 meses com HbA1c, peso, PA, revisão de pés (palpação pulsos + monofilamento 10g + diapasão 128Hz), revisão de medicação. **Anual**: fundoscopia (oftalmologista — referência da UBS), microalbuminúria, creatinina + TFG, lipídograma, ECG. **A cada 2 anos**: ECO se DAC suspeita. **Vacinação**: Pneumo 23 + Influenza anual + COVID-19 — DM2 é indicação CRIE. **ACS**: visita domiciliar para faltosos e idosos. **Sala de Vacina**: orientar fluxo. **Multiprofissional**: nutrição (matriciamento NASF), educação física (Academia da Saúde da UBS), enfermagem (atendimento estruturado), farmacêutico (revisão medicação).",
p4:"⚠ ALERTA P4: (1) HbA1c muito estrita em idoso/frágil AUMENTA mortalidade (ACCORD trial) — não buscar <7% em idoso com expectativa <10a; (2) Sulfonilureia (especialmente glibenclamida) em idoso causa hipoglicemia severa — preferir gliclazida MR ou insulina; (3) Insulina não é 'fim de linha' nem 'castigo' — explicar isso antes de prescrever previne dropout; (4) Estatina em prevenção primária no idoso muito frágil: rever; (5) AAS em prevenção primária DM2 sem DAC: NÃO indicado mais (ASCEND); (6) HbA1c capilar/glicemia toda semana em DM2 estável com SU: desnecessário, pode gerar ansiedade; (7) 'Pré-diabetes' como doença: foco em estilo de vida; metformina só situações específicas; (8) Cascata medicamentosa: tontura por SU em idoso → AAS → sangramento → IBP → todos com efeitos cumulativos. Revisar.",
diretriz:"[SBD — Diretrizes da Sociedade Brasileira de Diabetes 2024-2025] [Caderno de Atenção Básica MS nº 36, Estratégias para o Cuidado da Pessoa com Doença Crônica: DM] [ADA Standards of Care 2025] [DUNCAN 5ª ed, 2022, cap. DM] [TMFC 2ª ed, 2019, cap. 145]",
mec:[
{nome:"Metformina (biguanida)", como:"Reduz produção hepática de glicose (gliconeogênese) + sensibiliza tecidos periféricos à insulina. Não causa hipoglicemia isolada. Efeitos GI iniciais comuns (titular doses). Risco baixo de acidose láctica (cuidado em insuficiência renal severa)."},
{nome:"Glibenclamida (sulfonilureia)", como:"Fecha canal K+-ATP da célula beta → despolariza → libera insulina. Risco de HIPOGLICEMIA — especialmente em idoso, idiossincrasia, jejum prolongado."},
{nome:"Gliclazida MR (sulfonilureia mod. liberação)", como:"Mesmo mecanismo, mas perfil de segurança melhor que glibenclamida em idoso. Menor risco hipoglicemia severa."},
{nome:"Insulina NPH (intermediária)", como:"Insulina humana com retardo por cristalização (protamina+zinco). Pico 4-8h, duração 12-18h. Esquema simples: 1-2x ao dia para basal."},
{nome:"Insulina Regular (rápida)", como:"Insulina humana solúvel. Pico 2-4h, duração 6-8h. Usada pré-prandial em esquema basal-bolus."},
{nome:"Sinvastatina (estatina)", como:"Inibe HMG-CoA redutase → reduz síntese hepática colesterol. Em DM2: reduz LDL ~30% + redução de evento CV mesmo com LDL 'normal' (efeito pleiotrópico)."},
],
},

/* ============================================================
   3. Síndrome Metabólica
   ============================================================ */
{
id:"cron-metab", contexto:["ubs"], nome:"Síndrome Metabólica",
sis:"cron", grav:"baixa",
cid:"E88.81", ciap:"T82",
sin:["sindrome metabolica","SM","obesidade visceral","resistência insulínica"],
def:"Cluster de fatores de risco CV: obesidade central + dislipidemia (TG↑ ou HDL↓) + HAS + glicemia alterada. Critério [IDF 2009/ATP III]: 3 dos 5 — cintura abdominal alterada (♂>94 ou ♀>80 cm para latinos) + TG≥150 + HDL<40♂/<50♀ + PA≥130/85 + GJ≥100.",
intro:"Síndrome metabólica é mais marcador de risco que doença em si. O 'tratamento' é o mesmo de cada componente individual — não há tratamento 'da síndrome'. Mas o cluster sinaliza risco CV elevado e prediz progressão a DM2. Inclui na revisão sistemática do paciente: ferramenta de avaliação global de risco.",
fisio:"Eixo central: resistência insulínica + obesidade visceral. Adipócitos viscerais hipertróficos secretam mediadores inflamatórios (TNF-α, IL-6) e ácidos graxos livres → resistência insulínica em fígado, músculo, endotélio. Resultado: hiperinsulinemia compensatória + dislipidemia (TG↑, HDL↓, LDL pequena-densa pró-aterogênica) + HAS (efeito Na+ retenção, ativação simpática, endotélio) + tendência pró-trombótica e pró-inflamatória (PCR ↑, fibrinogênio ↑).",
apresentacao:"Achado em rotina: paciente com obesidade central, sedentário, com algum componente já-conhecido (HAS, dislipidemia, pré-DM). Frequentemente família com história de DM2 e DCV precoce.",
sintomas:[
"Maioria assintomática até evento CV ou DM2 estabelecido",
"Pode ter sintomas leves: cansaço crônico, sonolência pós-prandial (insulinemia alta), prurido em pregas (acantose nigricans), aumento de gordura central",
"Acantose nigricans: pele aveludada-escurecida em pescoço, axila, prega abdominal — marcador de resistência insulínica",
"História de SOP em mulher = forte associação com SM",
],
profilaxia:"Mudança de estilo de vida É o tratamento: (1) Perda de 7-10% do peso reduz drasticamente todos os componentes; (2) Atividade física 150 min/sem; (3) Dieta mediterrânea ou DASH; (4) Tratar cada componente individualmente — não há 'remédio da síndrome metabólica'.",
freire:"Síndrome metabólica é diagnóstico EDUCATIVO mais que clínico — serve para mostrar ao paciente que os componentes andam juntos. Use a metáfora: 'sua barriga, sua pressão, seu açúcar e seu colesterol não são problemas separados — são pedaços do mesmo problema. A boa notícia: melhora um, melhora tudo.' Evite culpabilizar. Trabalhe metas pequenas e mensuráveis. Para mulher com SOP: validar o sofrimento da infertilidade/acne/hirsutismo; metformina pode ajudar (mesmo sem DM2 estabelecido).",
sus_tx:"Tratamento componente a componente: HAS (ver cron-has); DM2 ou pré-DM (metformina + dieta — ver cron-dm2); dislipidemia (estatina se risco CV alto); obesidade (orientação nutricional + exercício; Liraglutida/Semaglutida via CEAF em casos específicos; cirurgia bariátrica IMC≥40 ou ≥35 com comorbidade). Articulação multiprofissional: NASF/eMulti, Academia da Saúde, nutricionista do município se disponível.",
padrao_ouro:"Tratamento mesmo padrão. Em casos refratários: GLP-1 agonistas (Semaglutida/Liraglutida) — não disponíveis CBAF mas via CEAF em IMC alto com comorbidade (critérios específicos). Cirurgia bariátrica em centro especializado (Hospital regional). Acréscimos privados: bioimpedância detalhada, estudo metabolômico, programas multiprofissionais intensivos.",
prog:"SM duplica risco de DM2 e DCV em 5-10 anos. Mudança de estilo de vida sustentada reverte o quadro em 50-70% dos casos.",
acomp:"Mesmo cronograma de HAS+DM2 conforme componentes. Reavaliar SM (cintura + componentes) anualmente.",
p4:"NÃO 'tratar' síndrome metabólica como entidade — tratar componentes. NÃO indicar estatina rotineiramente sem cálculo de risco CV global (ER/Framingham/PCE). NÃO 'prevenir DM2' com metformina em todo pré-DM — apenas em IMC>35, <60a, DM gestacional prévio (DPP study). NÃO indicar polivitamínico/suplemento como 'cura' da SM.",
diretriz:"[I Diretriz Brasileira de Diagnóstico e Tratamento da Síndrome Metabólica — SBC 2005 + atualizações] [IDF Consensus Worldwide Definition 2009] [DUNCAN 5ª ed, cap. Obesidade e Síndrome Metabólica]",
},

);
