/* ===========================================================
   VOVÔMINIC EMERGÊNCIA — pat/gu.js
   13 patologias
   Sistemas: gu
   =========================================================== */

PATOLOGIAS.push(

/* ============== GU (13) ============== */

{
  id:"candidiase", sis:"gu", grav:"baixa",
  nome:"Candidíase Vulvovaginal",
  sin:["candidíase","corrimento","Cândida"],
  def:"Prurido + corrimento branco em \"leite coalhado\" + ardência + dispareunia. Diagnóstico clínico.",
  exames:["Exame especular","pH vaginal <4,5","Microscopia (hifas) se dúvida"],
  rx:[
    {etapa:"escala", d:"Clotrimazol creme 1%",do:"Aplicador vaginal 1×/d × 7 dias",via:"Vaginal",o:"1ª linha. Alternativa: miconazol."},
    {etapa:"atb", d:"Fluconazol",do:"150 mg VO dose única",via:"VO",o:"Não-gestante. Repetir após 3 dias em casos moderados/graves."},
    {etapa:"escala", d:"Nistatina",do:"Creme vaginal 100.000 UI/g × 14 dias",via:"Vaginal",o:"Gestante (Cat B)."},
  ],
  alertas:[
    {t:"warn",x:"NÃO usar fluconazol em gestante (cat. D em altas doses)."},
  ],
  fisio:"Candida albicans (>85%) — comensal vaginal que prolifera com alteração de flora (ATB, gestação, DM, imunossupressão).",
  mec:[
    {d:"Clotrimazol / Miconazol",x:"Azólicos — inibem <strong>14α-desmetilase fúngica (CYP51)</strong> → ↓ergosterol da membrana fúngica."},
  ],
  diretriz:"FEBRASGO — Vulvovaginites 2024.",
  calcs:[],
},
{
  id:"cistite", sis:"gu", grav:"baixa",
  nome:"Cistite (ITU baixa)",
  sin:["ITU","cistite","infecção urinária"],
  def:"Disúria + polaciúria + urgência miccional + dor suprapúbica, sem febre. Mulher jovem, não-complicada: tratamento empírico.",
  exames:["EAS (leucocitúria, nitrito, hematúria)","Urocultura SOMENTE se: recorrente, gestante, falha terapêutica, complicada, homem, criança"],
  rx:[
    {etapa:"escala", d:"Nitrofurantoína",do:"100 mg VO 6/6h × 5 dias",via:"VO",o:"1ª linha em cistite não-complicada. CI: ClCr <30, gestante 3º trim."},
    {etapa:"atb", d:"Fosfomicina trometamol",do:"3 g VO dose única",via:"VO",o:"Alternativa. Tomar à noite + vesícula vazia."},
    {etapa:"atb", d:"SMX-TMP",do:"800/160 mg VO 12/12h × 3 dias",via:"VO",o:"Alternativa se resistência local <20%."},
    {etapa:"atb", d:"Cefalexina",do:"500 mg VO 6/6h × 7 dias",via:"VO",o:"Gestante."},
  ],
  alertas:[
    {t:"warn",x:"Bacteriúria assintomática: NÃO tratar EXCETO em gestantes e pré-procedimentos urológicos."},
  ],
  fisio:"Colonização periuretral → ascensão à bexiga → invasão de células uroepiteliais. Agente: E. coli (>80%), Klebsiella, Proteus, Staph. saprophyticus.",
  mec:[
    {d:"Nitrofurantoína",x:"Reduzida intracelularmente, gera intermediários reativos que <strong>danificam DNA/proteínas/ribossomos bacterianos</strong>. Concentra-se na urina."},
    {d:"Fosfomicina",x:"Inibe MurA — <strong>primeira etapa da síntese do peptidoglicano</strong>. Espectro amplo, concentra na urina."},
  ],
  diretriz:"IDSA — Treatment of Uncomplicated Cystitis and Pyelonephritis (Gupta K et al., CID 2011;52:e103–e120).",
  calcs:[],
},
{
  id:"herpes-gen", sis:"gu", grav:"media",
  nome:"Herpes Genital",
  sin:["herpes genital","HSV-2"],
  def:"Vesículas dolorosas em mucosa/pele genital + linfadenopatia + sintomas sistêmicos (primária). Recidivas são geralmente mais leves.",
  exames:["Diagnóstico clínico","PCR/cultura se dúvida"],
  rx:[
    {etapa:"atb", d:"Aciclovir",do:"400 mg VO 8/8h × 7–10 dias (primária) / 5 dias (recidiva)",via:"VO",o:"Iniciar nas primeiras 72h."},
    {etapa:"atb", d:"Valaciclovir",do:"1 g VO 12/12h × 7–10 dias",via:"VO",o:"Alternativa, posologia mais cômoda."},
    {etapa:"escala", d:"Famciclovir",do:"250 mg VO 8/8h × 7–10 dias",via:"VO",o:"Alternativa."},
    {etapa:"adj", d:"Profilaxia diária (se >6 recidivas/ano)",do:"Aciclovir 400 mg 12/12h",via:"VO",o:"Reduz recorrência e transmissão."},
  ],
  alertas:[
    {t:"warn",x:"Gestante com primoinfecção próximo ao parto: cesariana + aciclovir EV (transmissão neonatal grave)."},
  ],
  fisio:"HSV-2 (90%) ou HSV-1 (10%) — infecta neurônios sensitivos sacrais (lat e SS3-4); reativações periódicas → vesículas dérmicas.",
  mec:[
    {d:"Aciclovir",x:"Pró-droga — fosforilada pela <strong>timidina-quinase viral</strong> (apenas células infectadas) → trifosfato inibe <strong>DNA-polimerase viral</strong>."},
  ],
  diretriz:"PCDT-IST MS 2022; CDC STI 2021.",
  calcs:[],
},
{
  id:"orquiepi", sis:"gu", grav:"media",
  nome:"Orquiepididimite",
  sin:["epididimite","orquite","escroto agudo"],
  def:"Dor escrotal + edema + ↑eptididimo. Diferenciar de torção testicular (emergência cirúrgica em <6h).",
  exames:["USG Doppler ESCROTAL (excluir torção — fluxo testicular preservado)","EAS + urocultura","Gram/NAAT em jovens"],
  rx:[
    {etapa:"atb", d:"Ceftriaxona + Doxiciclina",do:"500 mg IM + 100 mg 12/12h × 10 dias",via:"IM + VO",o:"<35a — cobertura gono + clamídia."},
    {etapa:"atb", d:"Ciprofloxacino",do:"500 mg VO 12/12h × 10–14 dias",via:"VO",o:">35a — cobertura E. coli, enterobactérias."},
    {etapa:"inicial", d:"Repouso + suporte escrotal + AINE",do:"Em todos",via:"—",o:"Reduz edema e dor."},
  ],
  alertas:[
    {t:"crit",x:"TORÇÃO TESTICULAR é emergência absoluta. Início súbito, sem febre, reflexo cremastérico ausente, testículo elevado, dor INTENSA. Cirurgia em <6h."},
  ],
  fisio:"Refluxo retrógrado de patógenos do trato urinário ou DST.",
  mec:[],
  diretriz:"EAU 2024; PCDT-IST MS 2022.",
  calcs:[],
},
{
  id:"pielonefrite", sis:"gu", grav:"media",
  nome:"Pielonefrite Aguda",
  sin:["pielonefrite","ITU alta"],
  def:"Febre + dor lombar + Giordano + sintomas baixos + leucocitúria. Mais grave que cistite, pode levar à sepse urinária.",
  exames:["EAS + urocultura SEMPRE","Hemograma, PCR, função renal","HMC se internação","USG/TC se complicação"],
  rx:[
    {etapa:"inicial", d:"Avaliação inicial",do:"SSVV + sinais sepse (qSOFA) + Giordano + exame abdominal",via:"—",o:"Diferenciar de cistite baixa. Avaliar obstrução suspeita (cólica, urolitíase prévia)."},
    {etapa:"inicial", d:"Acesso venoso + hidratação",do:"SF/RL 30 mL/kg em 3h se sepse; ou manutenção se estável",via:"IV",o:"Hipovolemia + febre. Ajustar conforme volemia."},
    {etapa:"inicial", d:"Coletar EAS + urocultura + HMC",do:"ANTES da 1ª dose ATB",via:"—",o:"Permite step-down ATB conforme antibiograma."},
    {etapa:"atb", d:"AMBULATORIAL — Ciprofloxacino",do:"500 mg VO 12/12h × 7 dias",via:"VO",o:"Sem comorbidade, sem sepse, sem gestação. Pode falhar se resistência local >10% — checar antibiograma local."},
    {etapa:"atb", d:"AMBULATORIAL alternativo — SMX-TMP",do:"800/160 mg VO 12/12h × 14 dias",via:"VO",o:"Apenas se sensibilidade conhecida (resistência >30% em muitas regiões)."},
    {etapa:"atb", d:"INTERNAÇÃO — Ceftriaxona",do:"1-2 g IV/d × 7-14 dias",via:"IV",o:"1ª LINHA hospitalar. Step-down para VO em 48-72h se melhora + antibiograma."},
    {etapa:"atb", d:"GRAVE/SEPSE — Piperacilina-tazobactam",do:"4,5 g IV 6/6h",via:"IV",o:"Sepse, fatores de risco MR (uso ATB recente, internação, sonda vesical, complicada)."},
    {etapa:"atb", d:"ESBL/MULTIRRESISTENTE — Meropenem",do:"1 g IV 8/8h",via:"IV",o:"ESBL prévia conhecida, sepse refratária, exposição ATB amplo recente."},
    {etapa:"escala", d:"VASOPRESSOR se sepse com choque",do:"Noradrenalina 0,05-2 mcg/kg/min",via:"IV",o:"Meta PAM ≥65. Ver patologia Sepse para escalonamento completo."},
    {etapa:"adj", d:"Antitérmico/Analgésico",do:"Dipirona 2g IV 6/6h ± paracetamol",via:"IV/VO",o:"Conforto + reduz demanda metabólica. Evitar AINEs (risco renal)."},
    {etapa:"adj", d:"Antiemético",do:"Ondansetrona 4-8 mg IV 8/8h",via:"IV",o:"Náusea/vômitos frequentes. Permite hidratação VO."},
    {etapa:"adj", d:"Avaliar OBSTRUÇÃO",do:"USG renal/vias urinárias urgente",via:"—",o:"Hidronefrose + sepse = drenagem URGENTE (cateter duplo J ou nefrostomia). Pielonefrite obstruída evolui mal."},
  ],
  alertas:[
    {t:"crit",x:"Sepse urinária: bundle hour-1. Procurar obstrução (hidronefrose) — drenagem urgente (cateter duplo J, nefrostomia)."},
  ],
  fisio:"Ascensão de bactérias da bexiga via ureter até parênquima renal. E. coli (80%). Em homens/idosos/diabéticos: hospitalar/MR mais frequente.",
  mec:[
    {d:"Ciprofloxacino",x:"Inibe DNA-girase/topoisomerase IV — boa concentração no parênquima renal."},
  ],
  diretriz:"IDSA Gupta 2011; EAU Guidelines on Urological Infections.",
  calcs:[],
},
{id:"priapismo", sis:"gu", grav:"alta",
nome:"Priapismo",
sin:["priapismo","ereção prolongada"],
def:"Ereção persistente >4h, NÃO relacionada a estimulação sexual. ISQUÊMICO (baixo fluxo): doloroso, rígido, EMERGÊNCIA — falência fluxo arterial → necrose corpo cavernoso → impotência permanente. NÃO-ISQUÊMICO (alto fluxo): trauma perineal, indolor, parcial, NÃO urgência.",
exames:["GASO sangue cavernoso (punção): isquêmico = PaO₂ <30, PaCO₂ >60, pH <7,25; não-isq = arterial","HMG (descartar falcêmico)","β-HCG não aplicável","Função renal","Investigar causa: falciforme (eletroforese), leucemia, drogas (sildenafil, cocaína, antipsicóticos)","Doppler peniano em casos selecionados"],
rx:[
{etapa:"inicial", d:"ASPIRAÇÃO + IRRIGAÇÃO cavernosa",do:"Agulha 21G na lateral da base do pênis; aspirar 30-50 mL sangue + irrigar SF",via:"—",o:"1ª linha priapismo isquêmico <6h. Anestesia local (bloqueio peniano). Repetir conforme resposta."},
{etapa:"escala", d:"Fenilefrina intracavernosa",do:"100-500 mcg/mL — 1 mL a cada 5-10 min (máx 1 mg) APÓS aspiração",via:"—",o:"Vasoconstrição local. Monitor PA (risco HAS sistêmica). Diluir 1 mL fenilefrina 10 mg em 99 mL SF (100 mcg/mL)."},
{etapa:"escala", d:"Falcêmico — exsanguineotransfusão",do:"Eritroaférese, alvo HbS <30%",via:"IV",o:"Em PARALELO com manejo local. Não atrasar tratamento peniano."},
{etapa:"escala", d:"Cirurgia (Shunt)",do:"Winter / Ebbehoj / Quackels / Grayhack",via:"Cirúrgico",o:"Falha de tratamento conservador >24-48h. Urologista."},
{etapa:"adj", d:"Hidratação + analgesia",do:"IV vigorosa",via:"IV",o:"Especialmente em falcêmico."},
],
alertas:[
{t:"crit",x:"PRIAPISMO ISQUÊMICO >24h = impotência permanente quase certa. EMERGÊNCIA — não 'aguardar resolução espontânea'."},
{t:"crit",x:"Sildenafil/tadalafil + cocaína/anfetamina ou trazodona/risperidona — combinações de risco."},
{t:"warn",x:"Diferenciar isquêmico (rígido + doloroso, alto risco) de não-isquêmico (parcial, indolor, pós-trauma — angiografia + embolização eletiva)."},
],
fisio:"Isquêmico (baixo fluxo): obstrução do retorno venoso pelo plexo venoso peniano → estagnação → hipóxia + acidose + edema endotelial → fibrose corpo cavernoso. Causas: falciforme (vaso-oclusão), leucemia/mieloma (hiperviscosidade), drogas (PDE5i, antipsicóticos, trazodona, anticoag, cocaína), idiopático. Não-isquêmico: laceração arterial peniana pós-trauma perineal → fluxo descontrolado, sem isquemia.",
mec:[
{d:"Fenilefrina",x:"α1-agonista puro → vasoconstrição. Reverte preenchimento corpo cavernoso."},
],
diretriz:"AUA Guidelines on Priapism 2003 (atualização 2021). EAU.",
fluxo:null, calcs:[],
},
{id:"retencao-urinaria", sis:"gu", grav:"media",
nome:"Retenção Urinária Aguda",
sin:["retenção urinária","RUA","sondagem","cateterismo vesical"],
def:"Incapacidade súbita de esvaziar a bexiga, ± dor suprapúbica + globo vesical palpável. H idoso: HPB descompensada (mais comum). M: causas diversas — bexiga neurogênica, ITU, fecaloma, medicações (anticolinérgicos, opioides).",
exames:["Bexigoma palpável / USG point-of-care (>300-500 mL)","EAS + urocultura","Função renal (ureia/Cr — hidronefrose?)","PSA H >50a","Eletrólitos","RX abdome (fecaloma, urolitíase)"],
rx:[
{etapa:"escala", d:"Cateterismo VESICAL de alívio",do:"Foley 14-18 Fr lubrificada",via:"—",o:"DRENAR — alívio imediato. Esvaziar GRADUALMENTE (clampar após 500 mL × 10-15 min) para evitar hematúria 'ex-vacuo' e hipotensão."},
{etapa:"escala", d:"Cateter SUPRAPÚBICO",do:"Punção 2 dedos acima da sínfise",via:"—",o:"Falha de Foley (estenose uretral, próstata muito aumentada, falha técnica) — chamar urologista."},
{etapa:"escala", d:"α-bloqueador",do:"Tansulosina 0,4 mg VO/d ou Doxazosina 2-4 mg/d",via:"VO",o:"H com HPB — começar precoce. Aumenta taxa de sucesso de trial sem cateter."},
{etapa:"escala", d:"ATB se ITU",do:"Conforme antibiograma; Ceftriaxona 1-2 g IV se febre/sepse",via:"IV/VO",o:"Trato urinário superior — sempre ATB."},
{etapa:"escala", d:"Trial sem cateter (TWOC)",do:"Após 24-72h com α-bloq",via:"—",o:"Sucesso 40-60% em retenção 1ª. Falha → urologia para avaliar próstata + uretra."},
{etapa:"inicial", d:"Tratar fecaloma",do:"Toque retal + lavagem retal (glicerina 12% 500 mL)",via:"—",o:"Causa frequente em idoso/acamado. Sondagem alivia sintomas mas não trata."},
],
alertas:[
{t:"crit",x:"BEXIGA NEUROGÊNICA com hidronefrose bilateral + sintomas neuro novos = SÍNDROME DA CAUDA EQUINA — urgência neurocirúrgica. Avaliar reflexos perineais."},
{t:"warn",x:"Drenagem rápida >500 mL pode causar hipotensão por reflexo + hematúria ex-vácuo. CLAMPAR e drenar gradualmente."},
{t:"warn",x:"H idoso com retenção urinária em uso recente de anticolinérgico (anti-H1 OTC, oxibutinina) — suspender medicação."},
],
fisio:"Causas obstrutivas: HPB (mais comum H), estenose uretral, cálculo impactado, neoplasia, fecaloma, prolapso. Causas neurogênicas: lesão medular, esclerose múltipla, AVC, DM, pós-anestesia/cirurgia. Farmacológicas: anticolinérgicos, opioides, β-bloq, BCC, anti-H1, descongestionantes. Bexiga aguda distendida → ↑pressão → refluxo vésico-ureteral → hidronefrose + lesão renal.",
mec:[
{d:"Tansulosina",x:"α1a-bloqueador seletivo (próstata) — relaxa músculo liso prostático/uretral, ↓resistência ao esvaziamento."},
],
diretriz:"EAU Guidelines Urological Trauma. AUA Guidelines.",
fluxo:null, calcs:[],
},
{
  id:"sua", sis:"gu", grav:"media",
  nome:"Sangramento Uterino Anormal Agudo",
  sin:["SUA","sangramento uterino","menorragia"],
  def:"Sangramento uterino excessivo (≥80 mL ou duração ≥7 dias). FIGO PALM-COEIN para etiologia.",
  exames:["β-HCG (excluir gestação/aborto)","Hemograma, coagulograma","TSH, prolactina (se anovulação)","USG TV"],
  rx:[
    {etapa:"escala", d:"Estrogênios conjugados",do:"25 mg IV 4/4h até cessar (máx 24h) OU 1,25 mg VO 6/6h",via:"IV/VO",o:"Sangramento agudo — efeito hemostático em 12–24h."},
    {etapa:"escala", d:"Medroxiprogesterona",do:"10 mg VO/d × 5–10 dias",via:"VO",o:"Após cessar agudo, manter ciclo regular."},
    {etapa:"escala", d:"Ácido tranexâmico",do:"1 g VO 8/8h × até 5 dias",via:"VO",o:"Reduz volume em 40–50%."},
    {etapa:"escala", d:"ACO combinado",do:"1 cp 8/8h × 3 dias, depois 12/12h × 7d, depois 1×/d",via:"VO",o:"Hemostático e regularização."},
    {etapa:"escala", d:"Transfusão CH",do:"Se Hb <7 + instabilidade",via:"IV",o:"Hemorrágico grave."},
  ],
  alertas:[
    {t:"warn",x:"Sempre β-HCG primeiro. Aborto incompleto/gravidez ectópica mudam totalmente conduta."},
  ],
  fisio:"Múltiplas causas: pólipo, adenomiose, leiomioma, malignidade/hiperplasia, coagulopatia, ovulação disfuncional, endometrial, iatrogênica, não classificada.",
  mec:[
    {d:"Estrogênio",x:"Estimula proliferação endometrial rápida, recobre áreas sangrantes."},
    {d:"Ácido tranexâmico",x:"Análogo da lisina — inibe ligação plasminogênio à fibrina → ↓fibrinólise."},
  ],
  diretriz:"FEBRASGO 2017.",
  calcs:[],
},
{id:"torcao-test", sis:"gu", grav:"alta",
nome:"Torção Testicular",
sin:["torção testicular","testículo torcido","torção cordão espermático"],
def:"Rotação do cordão espermático → isquemia testicular. Dor escrotal súbita unilateral + náusea/vômito + reflexo cremastérico ausente + Prehn negativo (elevação NÃO alivia). PICO: 12-18 anos e neonatal.",
exames:["USG doppler escrotal — ↓fluxo (sensibilidade 88-100%)","β-HCG (afastar gestação se mulher confundida)","Urocultura/EAS"],
rx:[
{etapa:"escala", d:"CIRURGIA URGENTE",do:"Exploração escrotal + destorção + orquiopexia bilateral",via:"Cirúrgico",o:"Janela viabilidade: 4-6h (100% salva), 12h (50%), >24h (≤10%). NÃO ESPERAR USG se quadro clássico."},
{etapa:"escala", d:"Destorção manual",do:"Rotação externa do testículo (como abrir livro)",via:"—",o:"Apenas como ponte até cirurgia. NÃO substitui exploração."},
{etapa:"adj", d:"Analgesia",do:"Dipirona 2g + Tramadol 100mg IV",via:"IV",o:"Cuidado para não mascarar exame seriado."},
],
alertas:[
{t:"crit",x:"CADA HORA CONTA. Diagnóstico é CLÍNICO + USG. Quando há dúvida → operar (custo de orquiectomia desnecessária é menor que perda testicular)."},
{t:"crit",x:"USG NORMAL NÃO EXCLUI (torção intermitente, fluxo preservado parcial)."},
{t:"warn",x:"Diferencial: epididimite (febre, piúria, Prehn positivo, mais gradual), torção apêndice testicular (dor menor, blue dot sign), trauma."},
],
fisio:"Anomalia 'em badalo de sino' (bell-clapper) — testículo móvel dentro da vaginal por inserção alta → torção facilitada por contração cremastérica (frio, esporte, sono). Bilateral em 80% — daí orquiopexia BILATERAL. Após 6h, lesão isquêmica significativa; após 24h, geralmente necrose.",
mec:[],
diretriz:"AUA Guidelines on Testicular Torsion. EAU Pediatric Urology Guidelines 2023.",
fluxo:null,
calcs:[],
},
{
  id:"trico", sis:"gu", grav:"baixa",
  nome:"Tricomoníase",
  sin:["tricomoníase","Trichomonas"],
  def:"Corrimento amarelo-esverdeado, bolhoso, fétido + dispareunia + colo em \"morango\". IST — tratar parceiro.",
  exames:["Exame a fresco (protozoário móvel)","NAAT se disponível"],
  rx:[
    {etapa:"atb", d:"Metronidazol",do:"2 g VO dose única",via:"VO",o:"1ª linha. Ou 500 mg 12/12h × 7 dias. Tratar parceiro."},
    {etapa:"escala", d:"Tinidazol",do:"2 g VO dose única",via:"VO",o:"Alternativa, menor incidência de efeitos adversos."},
  ],
  alertas:[
    {t:"info",x:"IST — investigar outras (HIV, sífilis, gonorreia, clamídia). Tratar parceiro."},
  ],
  fisio:"Trichomonas vaginalis — protozoário flagelado. Transmissão sexual.",
  mec:[],
  diretriz:"PCDT-IST MS 2022.",
  calcs:[],
},
{
  id:"uretrite", sis:"gu", grav:"baixa",
  nome:"Uretrite (Gonocócica e Não-Gonocócica)",
  sin:["uretrite","gonorreia","clamídia","DST"],
  def:"Corrimento uretral + disúria. Gono: purulento, abundante. Não-gono (clamídia, micoplasma): mucoide, escasso. Tratamento EMPÍRICO conjunto.",
  exames:["Gram do corrimento (diplococos GN intracelulares = gono)","NAAT (clamídia + gono) se disponível","Investigar outras IST: HIV, sífilis, hepatite"],
  rx:[
    {etapa:"atb", d:"Ceftriaxona",do:"500 mg IM dose única",via:"IM",o:"Cobertura para gonococo. SEMPRE associar tratamento para clamídia."},
    {etapa:"atb", d:"Azitromicina",do:"1 g VO dose única",via:"VO",o:"Cobertura clamídia. + Tratamento conjunto."},
    {etapa:"atb", d:"Doxiciclina",do:"100 mg VO 12/12h × 7 dias",via:"VO",o:"Alternativa à azitromicina. Preferida em DIP."},
    {etapa:"escala", d:"Tratar parceiro(s)",do:"Notificar e tratar",via:"—",o:"Últimos 60 dias."},
  ],
  alertas:[
    {t:"warn",x:"Em gestantes: ceftriaxona + azitromicina (não doxiciclina — Cat D)."},
    {t:"info",x:"Sempre testar HIV + sífilis + hepatites B/C."},
  ],
  fisio:"Neisseria gonorrhoeae e Chlamydia trachomatis — IST de mucosas. Coinfecção em ~30%.",
  mec:[
    {d:"Azitromicina",x:"Macrolídeo — liga 50S ribossomal."},
    {d:"Doxiciclina",x:"Tetraciclina — liga 30S ribossomal."},
  ],
  diretriz:"PCDT-IST MS 2022.",
  calcs:[],
},
{
  id:"urolitiase", sis:"gu", grav:"media",
  nome:"Urolitíase / Cólica Renal",
  sin:["litíase","cálculo renal","cólica","nefrolitíase"],
  def:"Dor súbita lombar irradiando para flanco/virilha + hematúria + náuseas. Cálculo no ureter.",
  exames:["EAS (hematúria 90%)","USG ou TC sem contraste (PADRÃO-OURO)","Função renal, eletrólitos","β-HCG"],
  rx:[
    {etapa:"escala", d:"Cetoprofeno / Diclofenaco",do:"100 mg IV ou 75 mg IM",via:"IV/IM",o:"1ª linha analgésica. CI: IRC, sangramento, gestação 3º trim."},
    {etapa:"adj", d:"Dipirona",do:"1 g IV",via:"IV",o:"Alternativa/associada."},
    {etapa:"escala", d:"Morfina",do:"0,1 mg/kg IV (max 5 mg/dose)",via:"IV",o:"Dor refratária aos AINEs."},
    {etapa:"escala", d:"Tansulosina",do:"0,4 mg VO/d × até 4 sem",via:"VO",o:"Cálculo distal 5–10 mm — facilita expulsão. Alfa-bloqueador."},
    {etapa:"escala", d:"Hidratação",do:"Conforme tolerância oral; não hiperhidratar",via:"VO/IV",o:"NÃO acelera expulsão. Hidratar para diurese 1,5–2 L/d."},
  ],
  alertas:[
    {t:"crit",x:"PIELONEFRITE OBSTRUTIVA (cálculo + febre + hidronefrose) é EMERGÊNCIA — drenagem urgente (duplo J, nefrostomia) + ATB."},
    {t:"info",x:"Cálculos >10 mm raramente são expulsos espontaneamente — referenciar urologia (LECO, URS)."},
  ],
  fisio:"Supersaturação urinária → cristalização → cálculo. Tipos: <strong>oxalato de Ca</strong> (80%), ácido úrico, estruvita (infecção), cisteína. Obstrução do ureter → ↑pressão pielocalicial → dor visceral cólica.",
  mec:[
    {d:"Tansulosina",x:"<strong>α1A-bloqueador seletivo</strong> — relaxa musculatura lisa do ureter distal, ↑probabilidade de expulsão de cálculos de 5–10 mm em até 28 dias."},
    {d:"AINE",x:"Inibe COX → ↓PGE2 (que aumenta a pressão glomerular contralateral e a contração ureteral); ação periférica e central."},
  ],
  diretriz:"EAU Urolithiasis Guidelines 2024.",
  calcs:[],
},
{
  id:"vaginose", sis:"gu", grav:"baixa",
  nome:"Vaginose Bacteriana",
  sin:["vaginose","Gardnerella"],
  def:"Corrimento branco-acinzentado homogêneo + odor de peixe + pH >4,5 + clue cells + KOH+ (Amsel ≥3/4).",
  exames:["Exame especular + pH + KOH whiff test","Microscopia (clue cells)"],
  rx:[
    {etapa:"atb", d:"Metronidazol",do:"500 mg VO 12/12h × 7 dias",via:"VO",o:"1ª linha. Evitar álcool durante e 48h após."},
    {etapa:"atb", d:"Metronidazol gel 0,75%",do:"5 g vaginal 1×/d × 5 dias",via:"Vaginal",o:"Alternativa."},
    {etapa:"atb", d:"Clindamicina creme 2%",do:"5 g vaginal 1×/d × 7 dias",via:"Vaginal",o:"Alternativa."},
  ],
  alertas:[
    {t:"info",x:"Não é IST. Não tratar parceiro de rotina. Tratar SEMPRE em gestação (risco de prematuridade)."},
  ],
  fisio:"Disbiose vaginal — ↓lactobacilos protetores → ↑Gardnerella vaginalis, Atopobium, anaeróbios. pH alcaliniza.",
  mec:[
    {d:"Metronidazol",x:"5-Nitroimidazol — reduzido em condições anaeróbias → gera intermediários reativos que <strong>danificam DNA bacteriano</strong>."},
  ],
  diretriz:"PCDT-IST MS 2022.",
  calcs:[],
},
);
