/* ===========================================================
   VOVÔMINIC EMERGÊNCIA — pat/hemo.js
   8 patologias
   Sistemas: hemo
   =========================================================== */

PATOLOGIAS.push(

/* ============== HEMO (8) ============== */

{id:"anemia", contexto:["pa","ubs"], sis:"hemo", grav:"media",
nome:"Anemia Ferropriva",
sin:["anemia","ferropriva","ferro"],
def:"Hb <12 (mulher) ou <13 (homem) com VCM <80 + ferritina <30. Causa: perda crônica, ↓ingesta, má absorção, gestação.",
exames:["Hemograma","Ferro sérico, ferritina, sat transferrina","Investigar fonte (TGI em adulto + EDA/colono se ferritina <100 sem causa óbvia)"],
rx:[
{etapa:"inicial", d:"Sulfato ferroso",do:"40–60 mg de Fe elementar 2–3×/d",via:"VO",o:"1 cp = 40 mg Fe elementar. Jejum + suco cítrico (↑absorção). Manter 3–6 meses APÓS Hb normalizar."},
{etapa:"escala", d:"Ferro IV (carboximaltose férrica)",do:"15 mg/kg (máx 1000 mg) em dose única em SF 250 mL em 30 min",via:"IV",o:"Indicações: intolerância VO, perda contínua, IRC, gestação 2º/3º trim, pré-operatório."},
{etapa:"escala", d:"Hidróxido férrico sacarose",do:"200 mg IV 2–3×/sem × 5 doses",via:"IV",o:"Alternativa. Menor dose por aplicação."},
{etapa:"escala", d:"Transfusão de CH",do:"Hb <7 com sintomas; Hb <8 com cardiopatia",via:"IV",o:"Anemia muito grave/sintomática."},
],
alertas:[{t:"warn",x:"Em homem >40 ou pós-menopausa: SEMPRE investigar perda TGI (CCR)."}],
fisio:"Deficit de ferro → ↓síntese de heme → eritropoese ineficaz → eritrócitos hipocrômicos microcíticos.",
mec:[{d:"Sulfato ferroso",x:"Fe²⁺ é absorvido no duodeno via DMT1 (transportador de metal divalente). Carregado pela ferroportina, transportado pela transferrina."}],
diretriz:"WHO; BCSH 2021.",
calcs:[],
},
{id:"civd", contexto:["pa","ubs"], sis:"hemo", grav:"alta",
nome:"CIVD — Coagulação Intravascular Disseminada",
sin:["CIVD","DIC","coagulação intravascular disseminada","coagulopatia consumo"],
def:"Síndrome adquirida de ativação patológica da coagulação → consumo de fatores e plaquetas → sangramento + microtromboses paradoxal. Sempre secundária — investigar a CAUSA. Critérios ISTH: TAP/INR, plaq, fibrinogênio, D-dímero — escore ≥5 = CIVD.",
exames:["TP/INR, TTPA (alargados)","Fibrinogênio (BAIXO; alto não exclui — proteína de fase aguda)","D-dímero (MUITO ALTO)","Plaquetas (BAIXAS, em queda)","Esfregaço (esquistócitos — microangiopatia)","HMG completo + função renal/hepática","Investigar causa: hemoculturas, β-HCG, função tireoidiana, RX, TC"],
rx:[
{etapa:"escala", d:"TRATAR CAUSA",do:"Sepse → ATB + controle foco; obstétrica → resolução; trauma → cirurgia; neoplasia → quimio",via:"—",o:"PILAR. Sem isso, intervenção é paliativa."},
{etapa:"escala", d:"Reposição fatores SE sangramento ATIVO",do:"PFC 10-15 mL/kg + crioprecipitado (fibrinogênio <100) + plaquetas (se <20-50k)",via:"IV",o:"NÃO repor por valores baixos isolados sem sangramento — alimenta a coagulação intravascular."},
{etapa:"anticoag", d:"Heparina (microtromboses dominantes)",do:"HNF 500 UI/h IV (dose baixa) ou HBPM dose profilática",via:"IV/SC",o:"INDICAÇÕES: predomínio trombótico (pele, gangrena, IRA isquêmica), CIVD crônica de neoplasia, em ausência de sangramento ativo grave. CONTROVERSO em CIVD aguda."},
{etapa:"escala", d:"Antifibrinolítico",do:"Ácido tranexâmico 1g IV — CAUTELOSO",via:"IV",o:"Excepcional — em CIVD com predomínio hiperfibrinolítico (leucemia M3, próstata, hemorragia maciça obstétrica) sob orientação hematologista."},
{etapa:"escala", d:"Vit K",do:"10 mg IV/d × 3 dias",via:"IV",o:"Cofator dos fatores II/VII/IX/X — pode estar deficiente em CIVD prolongada."},
{etapa:"escala", d:"Antitrombina, proteína C ativada",do:"—",via:"—",o:"NÃO recomendadas rotineiramente (Xigris retirado do mercado)."},
],
alertas:[
{t:"crit",x:"CIVD é DIAGNÓSTICO DA DOENÇA DE BASE — não tratar 'a CIVD'. Tratar SEPSE, choque, neoplasia, HELLP, obstétrica, trauma."},
{t:"crit",x:"NÃO repor sangue por números laboratoriais — repor SE sangramento ATIVO. Procoagulantes 'alimentam' processo intravascular."},
{t:"warn",x:"Causas comuns BR: sepse (#1), obstétrica (DPP, embolia LA, HPP), trauma maciço, leucemia M3 (LMA M3 = emergência hematológica)."},
],
fisio:"Doença de base libera fator tecidual (TF) sistemicamente → ativação maciça e descontrolada da coagulação → microtrombos disseminados + consumo de fatores/plaquetas + ativação fibrinolítica secundária (PAI-1 alto inicialmente, depois tPA) → padrão paradoxal: trombose microvascular (lesão isquêmica MOF) + sangramento (consumo). LMA M3 (leucemia promielocítica): grânulos liberam TF + anexina A2 → hiperfibrinólise dominante.",
mec:[],
diretriz:"ISTH 2018 (Wada H et al., J Thromb Haemost 2018;16:1929). British Society for Haematology 2009.",
fluxo:null, calcs:[],
},
{id:"crise-falciforme", contexto:["pa"], sis:"hemo", grav:"alta",
nome:"Crise Falciforme (Vaso-oclusiva)",
sin:["crise falciforme","anemia falciforme","CVO","STA","síndrome torácica aguda"],
def:"Anemia falciforme (HbSS) com episódios agudos: CVO (dor óssea/torácica/abdominal súbita); STA (febre + sintomas resp + infiltrado RX); sequestro esplênico (criança, dor + esplenomegalia + ↓Hb); aplasia (parvovírus B19); priapismo; AVC; sepse (encapsulados).",
exames:["Hemograma com reticulócitos","DHL, bilirrubina, haptoglobina (hemólise)","Função renal, eletrólitos","Hemocultura se febril","RX tórax (sempre se sintomas resp)","β-HCG mulher fértil","Tipagem completa (RhE, Kell — aloimunização)"],
rx:[
{etapa:"adj", d:"Analgesia ESCALONADA",do:"Dipirona 2g + Cetorolaco 30mg IV → Morfina 0,1 mg/kg IV (titular)",via:"IV",o:"NÃO subdosar. Crise falciforme dói tanto quanto IAM. PCA/BIC morfina se necessário. SUBESTIMAÇÃO da dor é a regra."},
{etapa:"escala", d:"Hidratação",do:"SF 1-1,5× manutenção (NÃO bolus)",via:"IV",o:"Evitar super-hidratação (risco edema pulmonar)."},
{etapa:"inicial", d:"O₂",do:"Manter SpO₂ ≥95%",via:"—",o:"NÃO usar liberalmente — só se hipoxêmico. O₂ excessivo pode suprimir eritropoiese."},
{etapa:"escala", d:"ATB (se febril/STA)",do:"Ceftriaxona 2g IV + Azitromicina 500 mg IV",via:"IV",o:"Cobertura pneumococo + Mycoplasma. Atypicals comuns em STA."},
{etapa:"escala", d:"Transfusão simples",do:"CH 10-15 mL/kg",via:"IV",o:"Hb >7-9. NÃO ultrapassar Hb 10 (hiperviscosidade)."},
{etapa:"escala", d:"Exsanguineotransfusão",do:"Eritroaférese ou exsang manual",via:"IV",o:"STA grave, AVC, falência multissistêmica, priapismo refratário. Alvo HbS <30%."},
{etapa:"anticoag", d:"Heparina profilática",do:"Enoxaparina 40 mg SC/d",via:"SC",o:"Internação prolongada — alto risco TVP/TEP."},
{etapa:"adj", d:"Tromboprofilaxia mecânica",do:"Meias compressivas",via:"—",o:"Sempre, mesmo em quem recebe heparina."},
],
alertas:[
{t:"crit",x:"SÍNDROME TORÁCICA AGUDA (STA): febre + dispneia/dor torácica + infiltrado novo RX em paciente com anemia falciforme. Mortalidade 4-10% adultos. Atb + O₂ + transfusão se Hb<9 ou hipoxemia."},
{t:"crit",x:"ANEMIA FALCIFORME + FEBRE = sepse até prova contrária. Asplenia funcional → pneumococo, H. influenzae, salmonella. Hemocultura + ATB IV imediato."},
{t:"warn",x:"AVC isquêmico em criança falciforme: trombólise pode ser tentada (caso-a-caso); exsanguineo é central."},
{t:"warn",x:"Priapismo >4h: aspiração + irrigação salina ± fenilefrina intracavernosa + exsanguineo. Urologia."},
],
fisio:"HbS (β6 Glu→Val): em desoxigenação, HbS polimeriza em fibras longas → hemácia em foice → adesão endotelial + rigidez + obstrução microvascular → isquemia tecidual + dor. Crises desencadeadas por: hipóxia, desidratação, infecção, frio, estresse, álcool, altitude. Pacientes têm asplenia funcional (sequestro autoinfartos no baço) → risco encapsulados.",
mec:[
{d:"Hidroxiureia (manutenção, não-crise)",x:"↑síntese de HbF (fetal) — HbF não polimeriza → reduz episódios e mortalidade. Mecanismo molecular não totalmente elucidado (envolve NO, citocinas)."},
{d:"Voxelotor (manutenção)",x:"Liga-se à HbS estabilizando o estado oxigenado → menos polimerização. Disponibilidade limitada no SUS."},
],
diretriz:"ASH 2020 Sickle Cell (Liem RI et al., Blood Adv 2020;4:1554, DOI:10.1182/bloodadvances.2019001142). NHLBI 2014. PCDT MS Brasil.",
fluxo:null,
calcs:[],
},
{id:"hemocomp-ch", contexto:["pa","ubs"], sis:"hemo", grav:"media",
nome:"Concentrado de Hemácias (CH)",
sin:["CH","transfusão","hemácias"],
def:"Volume 250–300 mL. 1 UI eleva Hb ~1 g/dL e Ht ~3% em adulto médio. Pediatria: 10–15 mL/kg.",
exames:["Tipo + Coombs","Reserva sanguínea","Hemograma de controle"],
rx:[
{etapa:"escala", d:"Indicação",do:"Hb <7 (geral); <8 cardiopata/idoso/oncologia; <10 isquemia ativa/hipoxemia",via:"—",o:"Estratégia RESTRITIVA é superior à liberal (TRICC, FOCUS)."},
{etapa:"escala", d:"Velocidade",do:"≤2h por unidade (4h se idoso/IC)",via:"IV",o:"Premedicação com hidrocortisona/anti-H1 não rotineira."},
{etapa:"escala", d:"Choque hipovolêmico",do:"Transfusão maciça 1:1:1 (CH:plasma:plaq)",via:"IV",o:"+ ácido tranexâmico 1 g IV."},
],
alertas:[{t:"warn",x:"Reações: febril não-hemolítica, alérgica, TRALI, sobrecarga (TACO), hemolítica aguda — interromper, suporte."}],
fisio:"",
mec:[],
diretriz:"MS — Guia para Uso de Hemocomponentes, 2ª ed. 2015. Hospitalar.",
calcs:[],
},
{id:"hemocomp-crio", contexto:["pa","ubs"], sis:"hemo", grav:"media",
nome:"Crioprecipitado",
sin:["crio","crioprecipitado","fibrinogênio"],
def:"Volume 10–15 mL/UI. 1 UI/10 kg eleva fibrinogênio ~50 mg/dL.",
exames:["Coagulograma + fibrinogênio"],
rx:[
{etapa:"escala", d:"Hipofibrinogenemia <150 mg/dL com sangramento",do:"10 UI ou 1 UI/10 kg",via:"IV",o:"CIVD, transfusão maciça, hemorragia obstétrica."},
{etapa:"escala", d:"Hemofilia A, doença von Willebrand",do:"Quando concentrado específico indisponível",via:"IV",o:"Preferir fator específico se disponível."},
],
alertas:[],
fisio:"",
mec:[],
diretriz:"MS 2015.",
calcs:[],
},
{id:"hemocomp-pfc", contexto:["pa","ubs"], sis:"hemo", grav:"media",
nome:"Plasma Fresco Congelado (PFC)",
sin:["plasma","PFC"],
def:"Volume 200–250 mL. 10–15 mL/kg eleva fatores ~20–30%.",
exames:["Coagulograma (INR, aPTT)","Hemograma"],
rx:[
{etapa:"escala", d:"Coagulopatia + sangramento ativo",do:"10–15 mL/kg",via:"IV",o:"INR >1,5–2,0 com sangramento."},
{etapa:"escala", d:"Transfusão maciça",do:"1:1:1 com CH e plaquetas",via:"IV",o:""},
{etapa:"anticoag", d:"Reversão de varfarina urgente",do:"PCC (complexo protrombínico) é PREFERIDO; PFC se PCC indisponível",via:"IV",o:"+ vit K 10 mg IV."},
],
alertas:[{t:"warn",x:"NÃO usar para correção de INR sem sangramento (uso de vit K), expansão volêmica ou suporte nutricional."}],
fisio:"",
mec:[],
diretriz:"MS 2015; AABB 2024.",
calcs:[],
},
{id:"hemocomp-plaq", contexto:["pa","ubs"], sis:"hemo", grav:"media",
nome:"Concentrado de Plaquetas",
sin:["plaquetas","plaquetopenia","transfusão de plaquetas"],
def:"1 UI/10 kg eleva ~5–10.000/mm³. 1 aférese ≈ 6–8 unidades randômicas.",
exames:["Hemograma"],
rx:[
{etapa:"escala", d:"Profilática",do:"<10.000 (estável); <20.000 (febre/sepse); <50.000 (procedimento); <100.000 (SNC, oftalmo)",via:"IV",o:"Em LMA/quimio."},
{etapa:"escala", d:"Terapêutica",do:"Sangramento ativo: alvo >50.000 (>100.000 SNC)",via:"IV",o:"+ correção de coagulopatia, antifibrinolítico."},
],
alertas:[{t:"warn",x:"PTT/SHU/HIT: NÃO transfundir plaquetas (perpetua trombose)."}],
fisio:"",
mec:[],
diretriz:"MS 2015.",
calcs:[],
},
{id:"reacao-transf", contexto:["pa","ubs"], sis:"hemo", grav:"alta",
nome:"Reação Transfusional",
sin:["reação transfusional","TRALI","TACO","RTA hemolítica"],
def:"Reação adversa durante/após transfusão. Tipos críticos: HEMOLÍTICA AGUDA (incompatibilidade ABO, mortalidade alta), TRALI (lesão pulmonar relacionada à transfusão), TACO (sobrecarga circulatória), reação alérgica grave/anafilaxia. Outras: febril não-hemolítica, séptica, urticariforme.",
exames:["PARAR transfusão IMEDIATAMENTE","Reavaliar identificação paciente x bolsa","Coombs direto + tipagem repetida","HMG, LDH, bilirrubina indireta, haptoglobina","EAS (Hb urinária = hemoglobinúria — hemólise)","Função renal","RX tórax (TRALI/TACO)","Hemoculturas do paciente + bolsa (reação séptica)","Eletrólitos, K (hemólise + hipercalemia)"],
rx:[
{etapa:"inicial", d:"PARAR transfusão",do:"Imediato",via:"—",o:"PILAR. Manter acesso com SF separado."},
{etapa:"escala", d:"Notificar banco de sangue",do:"Devolver bolsa + tubos para investigação",via:"—",o:"Sempre. Notificação compulsória."},
{etapa:"escala", d:"Reação HEMOLÍTICA AGUDA",do:"Hidratação vigorosa (SF 200-500 mL/h) + manter PAM ≥65 + manitol/furosemida para débito >100 mL/h",via:"IV",o:"Proteção renal. ALERTAR CIVD. Hemodiálise se IRA."},
{etapa:"escala", d:"TRALI",do:"Suporte ventilatório protetor (Vt 6 mL/kg) — geralmente requer IOT",via:"VM",o:"Distingue de TACO: TRALI sem sobrecarga, BNP normal, biópsia anti-HLA/HNA do doador. Mortalidade 5-25%."},
{etapa:"escala", d:"TACO",do:"Diurético (furosemida 40-80 mg IV) + VNI + restrição volume",via:"IV",o:"Idoso, cardiopata, RN, IRC = risco. Prevenção: transfusão lenta + diurético entre bolsas."},
{etapa:"escala", d:"ANAFILAXIA",do:"Adrenalina 0,3-0,5 mg IM + suporte (ver patologia)",via:"IM",o:"IgA deficiente + IgG anti-IgA é causa clássica."},
{etapa:"escala", d:"Febril não-hemolítica",do:"Paracetamol 1 g + suspender bolsa se T >2°C acima basal ou sintomas",via:"VO/IV",o:"Reação mais comum. Geralmente benigna mas exclui sempre as graves."},
{etapa:"escala", d:"Séptica",do:"ATB amplo espectro empírico (vancomicina + cefepima/ceftazidima)",via:"IV",o:"Bolsa contaminada (mais comum plaquetas armazenadas). Suporte sepse."},
],
alertas:[
{t:"crit",x:"DOR LOMBAR + FEBRE + HIPOTENSÃO + URINA ESCURA durante transfusão = HEMÓLISE AGUDA INTRAVASCULAR. Parar imediato. Frequentemente fatal."},
{t:"crit",x:"TRALI vs TACO: ambos têm dispneia + infiltrado RX nas primeiras 6h pós-transfusão. TACO = sobrecarga (↑BNP, ↑PA, ↑PVC); TRALI = lesão (BNP normal, sem sobrecarga, geralmente PA cai)."},
{t:"warn",x:"REAÇÃO DEMORA: TRALI/TACO podem se apresentar até 6h pós; hemólise tardia até 14 dias."},
{t:"info",x:"Hemovigilância: notificar SISVAN/HEMOVIGILÂNCIA."},
],
fisio:"Hemólise aguda: incompatibilidade ABO (erro de identificação — humano, não laboratorial). Anticorpos pré-formados do receptor atacam hemácias do doador → hemólise intravascular maciça → liberação Hb → IRA + CIVD + choque. TRALI: anticorpos anti-HLA/HNA do doador ativam neutrófilos do receptor → lesão alveolar. TACO: simples sobrecarga de volume. Anafilaxia: IgE-mediada, geralmente IgA-deficiente.",
mec:[],
diretriz:"AABB (American Association of Blood Banks). ANVISA — Hemovigilância. Diretrizes SUS para Hemoterapia.",
fluxo:null, calcs:[],
},
);
