/* ===========================================================
   VOVÔMINIC EMERGÊNCIA — pat/neuro.js
   11 patologias
   Sistemas: neuro
   =========================================================== */

PATOLOGIAS.push(

/* ============== NEURO (11) ============== */

{id:"ait", contexto:["pa","ubs"], sis:"neuro", grav:"alta",
nome:"Ataque Isquêmico Transitório (AIT)",
sin:["AIT","TIA","mini-AVC"],
def:"Déficit neurológico súbito de origem vascular com RESOLUÇÃO COMPLETA em ≤24h (geralmente <1h) e SEM evidência de infarto em imagem. Sinal de alarme — 5% terão AVC em 48h, 10% em 90 dias.",
exames:["TC crânio (sem evidência de infarto)","RM com DWI (gold standard para excluir AVC verdadeiro)","Doppler carótidas + vertebrais","ECG + Holter 24-72h (FA paroxística)","Ecocardiograma transtorácico ± transesofágico","HMG, glicemia, perfil lipídico, função renal","HbA1c"],
rx:[
{etapa:"escala", d:"AAS",do:"300 mg dose única + 75-100 mg/d",via:"VO",o:"Iniciar imediatamente após excluir hemorragia."},
{etapa:"escala", d:"DAPT (AAS + Clopidogrel)",do:"AAS 100 mg/d + Clopi 75 mg/d × 21 dias depois AAS",via:"VO",o:"ABCD² ≥4 ou AIT moderado-alto risco. CHANCE/POINT trials — reduz AVC 32%."},
{etapa:"escala", d:"Atorvastatina",do:"40-80 mg/d",via:"VO",o:"Alta intensidade — SPARCL trial. LDL alvo <70."},
{etapa:"anticoag", d:"Anticoagulação",do:"Apixabana 5 mg 12/12h (dose plena) OU varfarina INR 2-3",via:"VO",o:"SE FA presente. CHA₂DS₂-VA ≥1H ou ≥2M."},
{etapa:"escala", d:"Controle pressórico",do:"Após 24-48h, IECA/BRA + diurético tiazídico",via:"VO",o:"Meta progressiva PAS <130. PROGRESS trial."},
{etapa:"escala", d:"Endarterectomia carotídea",do:"—",via:"Cirúrgico",o:"Estenose sintomática 70-99% — em até 14 dias do evento (NASCET)."},
],
alertas:[
{t:"crit",x:"ABCD² ≥4 ou AIT recente (<48h) ou novo déficit ≥30 min → INTERNAÇÃO + investigação rápida + DAPT 21 dias."},
{t:"crit",x:"Crescendo TIAs (AITs múltiplos em curto intervalo) = pré-AVC iminente — UTI neurológica, anticoag/DAPT, imagem urgente."},
{t:"warn",x:"AIT em <55a com sopro carotídeo → considerar dissecção arterial cervical (jovem, esforço, trauma cervical leve)."},
],
fisio:"Mecanismos idênticos ao AVCi: cardioembólico (FA — origem cardíaca), aterosclerose grande vaso (placa carotídea — embolia arterio-arterial), doença de pequenos vasos (lacunar), criptogênico. A diferença com AVC é apenas que aqui o trombo se desfaz/migra antes do dano permanente. RM-DWI mostra que ~30-50% dos AITs clínicos têm pequena lesão isquêmica — alguns reclassificam.",
mec:[
{d:"Clopidogrel",x:"Tienopiridínico — pró-droga ativada pelo CYP2C19, metabólito liga-se irreversivelmente ao receptor P2Y12 plaquetário → bloqueia ativação plaquetária por ADP."},
{d:"Atorvastatina",x:"Inibidor HMG-CoA redutase — ↓síntese colesterol hepático + efeitos pleiotrópicos (estabiliza placa, ↓inflamação, melhora endotélio)."},
],
diretriz:"AHA/ASA 2021 Secondary Prevention (Kleindorfer DO et al., Stroke 2021;52:e364). ESO 2021. CHANCE/POINT trials.",
fluxo:null,
calcs:["abcd2","chads-va"],
},
{
  id: "avci", contexto:["pa"], sis: "neuro", grav: "alta",
  nome: "AVC Isquêmico Agudo / Trombólise",
  sin: ["AVC", "AVCI", "derrame", "stroke", "trombólise"],
  def: "Déficit neurológico focal súbito + neuroimagem sem hemorragia. NIHSS quantifica gravidade. Janela para trombólise IV: 4,5h. Trombectomia: até 24h em casos selecionados.",
  exames: ["NIHSS", "TC crânio sem contraste (ASPECTS) — primeira imagem", "Glicemia capilar (descartar hipoglicemia)", "Coagulograma, plaquetas, função renal", "Angio-TC se candidato a trombectomia", "RM se janela estendida/wake-up stroke (mismatch DWI/FLAIR)"],
  rx: [
    {etapa:"inicial", d:"GLICEMIA capilar IMEDIATA",do:"Excluir hipoglicemia (mimic)",via:"—",o:"Hipoglicemia <50: corrigir antes — pode resolver completamente o quadro. Hiperglicemia >180 aumenta risco hemorragia pós-trombólise."},
    {etapa:"inicial", d:"NIHSS + tempo de início",do:"Aplicar NIHSS + LSW (Last Seen Well)",via:"—",o:"NIHSS quantifica gravidade. LSW = última vez bem documentada. CRÍTICO para janela terapêutica."},
    {etapa:"inicial", d:"TC crânio sem contraste IMEDIATA",do:"≤25 min porta-TC, ≤45 min interpretação",via:"—",o:"Excluir hemorragia. Calcular ASPECTS. Achados precoces de isquemia."},
    {etapa:"inicial", d:"Acessos + monitorização + PA",do:"2 acessos, sem retirar sangue para INR (atrasa)",via:"—",o:"Trombólise pode iniciar SEM aguardar INR/coagulograma se sem suspeita de coagulopatia."},
    {etapa:"escala", d:"① Controle PA pré-trombólise",do:"Alvo PAS <185/PAD <110",via:"IV",o:"Labetalol 10-20 mg IV bolus OU Nitroprussiato 0,25-10 mcg/kg/min. NÃO trombolisar se PA não controlada."},
    {etapa:"escala", d:"② TROMBÓLISE — Alteplase",do:"0,9 mg/kg IV (máx 90 mg) — 10% em bolus 1 min + 90% em 60 min",via:"IV",o:"Em até 4,5h do início. Critérios rigorosos inclusão/exclusão. Padrão SUS."},
    {etapa:"escala", d:"② TROMBÓLISE — Tenecteplase (alternativa)",do:"0,25 mg/kg IV bolus único (máx 25 mg)",via:"IV",o:"AHA/ASA 2025 classe I, alternativa à alteplase em janela ≤4,5h. Bolus único, mais prática. Disponibilidade variável SUS."},
    {etapa:"escala", d:"③ TROMBECTOMIA mecânica",do:"Janela ≤6h (todos) ou 6-24h com mismatch (DAWN/DEFUSE-3)",via:"—",o:"Oclusão de grande vaso (LVO: M1, ACI). ASPECTS ≥6. NIHSS ≥6. Acionar centro de AVC IMEDIATAMENTE."},
    {etapa:"adj", d:"Controle PA pós-trombólise",do:"Alvo PA <180/105 por 24h",via:"IV",o:"Monitorizar 15/15 min × 2h, depois 30/30 min × 6h, depois 1/1h × 16h."},
    {etapa:"adj", d:"NÃO antiagregar nas 1ªs 24h pós-trombólise",do:"Risco de hemorragia",via:"—",o:"Reavaliar TC em 24h antes de iniciar AAS. Se sem hemorragia: AAS 300 mg dose única."},
    {etapa:"escala", d:"AAS (sem trombólise ou após 24h)",do:"300 mg VO/SNG dose única + 100 mg/d",via:"VO",o:"Sem trombólise: iniciar imediato. Pós-trombólise: aguardar 24h + TC controle."},
    {etapa:"adj", d:"Atorvastatina",do:"80 mg VO/d",via:"VO",o:"Iniciar em 24-48h. Indicação independente do LDL."},
    {etapa:"alta", d:"Investigação etiológica",do:"Eco TT/TE, Doppler carótidas, Holter, perfil lipídico, HbA1c",via:"—",o:"Definir etiologia (cardioembólica, aterotrombótica, lacunar, criptogênico). Prevenção secundária guiada."},
    {etapa:"alta", d:"Reabilitação precoce",do:"Fisio, fono, TO em 24-48h se estável",via:"—",o:"Reduz incapacidade. Disfagia: avaliação fono antes de VO."},
  ],
  alertas: [
    { t: "crit", x: "CI absolutas à trombólise: AVC/TCE <3m, hemorragia ativa, plaquetas <100k, INR >1,7, glicose <50 ou >400, PA >185×110 não controlada, neoplasia/MAV SNC, endocardite, dissecção aórtica." },
    { t: "warn", x: "Trombectomia mecânica: oclusão de grande vaso (LVO) + janela ≤6h (todos) ou 6–24h com mismatch perfusional. ASPECTS ≥6 preferencial." },
    { t: "info", x: "Não tratar hipoglicemia simulando AVC. Sempre HGT na chegada." },
  ],
  fisio: "A oclusão arterial cerebral interrompe o suprimento de O₂/glicose. Forma-se uma <strong>zona central de infarto irreversível</strong> rodeada de <strong>penumbra isquêmica</strong> — tecido hipoperfundido mas ainda viável que pode ser salvo se reperfundido em tempo hábil. \"Time is brain\": cada minuto perdido = 1,9 milhão de neurônios mortos. A trombólise IV dissolve o trombo restaurando o fluxo; a trombectomia mecânica remove fisicamente o coágulo em oclusões de grande vaso, com benefício extraordinário (NNT 2,6 para incapacidade reduzida). A AHA/ASA 2026 endossou tenecteplase 0,25 mg/kg como classe I (alternativa à alteplase em janela ≤4,5h), por farmacocinética superior (bolus único).",
  mec: [
    { d: "Alteplase (rt-PA)", x: "Ativador tecidual do plasminogênio recombinante — converte plasminogênio circulante em <strong>plasmina, que degrada fibrina</strong> do trombo. Meia-vida 4–5 min." },
    { d: "Tenecteplase", x: "rt-PA modificado geneticamente (3 mutações) — maior fibrinoespecificidade, resistência ao PAI-1 e meia-vida prolongada (~20 min), permitindo bolus único." },
    { d: "AAS", x: "Inibe COX-1 plaquetária irreversivelmente — bloqueia tromboxano A2 e agregação." },
  ],
  diretriz: "AHA/ASA 2025 Guideline for the Management of Patients With Acute Ischemic Stroke (Powers WJ et al., 2025 update; DOI:10.1161/STR.0000000000000513). Linha de Cuidado em AVC, Ministério da Saúde (Portaria GM/MS 4.129/2024). PCDT MS Brasil 2021 (recomenda apenas alteplase em SUS).",
  imgs: [
    {src:"https://upload.wikimedia.org/wikipedia/commons/4/49/MCA_Territory_Infarct.svg",
     alt:"TC de crânio com hipoatenuação em território de ACM",
     caption:"Infarto extenso em território da artéria cerebral média esquerda — hipoatenuação cortical e apagamento dos sulcos.",
     source:"Wikimedia Commons / Lucien Monfils (CC BY-SA 3.0)"},
  ],
  fluxo: "avci",
  calcs: ["nihss"],
},
{
  id: "bell", contexto:["pa","ubs"], sis: "neuro", grav: "baixa",
  nome: "Paralisia de Bell",
  sin: ["Bell", "paralisia facial", "paralisia facial periférica"],
  def: "Paralisia facial periférica unilateral aguda, idiopática, com envolvimento DA TESTA (House-Brackmann II–VI). Inicio em 72h, geralmente associada a infecção viral.",
  exames: ["Exame neurológico (excluir AVC: testa preservada na central!)", "Otoscopia (Ramsay Hunt: vesículas + dor)", "Glicemia, A1c", "Sorologia herpes/Lyme se suspeita"],
  rx: [
    { etapa:"escala", d: "Prednisona", do: "60 mg/d × 5 dias + desmame em 5 dias", via: "VO", o: "Iniciar nas primeiras 72h. Aumenta chance de recuperação completa." },
    { etapa:"atb", d: "Aciclovir", do: "400 mg VO 5×/d × 10 dias", via: "VO", o: "Em casos graves ou Ramsay Hunt — benefício controverso isolado, mas usado com corticoide." },
    { etapa:"atb", d: "Valaciclovir", do: "1 g VO 8/8h × 7 dias", via: "VO", o: "Alternativa." },
    { etapa:"escala", d: "Lubrificação ocular", do: "Lágrima artificial + curativo oclusivo noturno", via: "Tópico", o: "FUNDAMENTAL para evitar úlcera de córnea." },
  ],
  alertas: [
    { t: "warn", x: "Se TESTA preservada → central (AVC). Investigar imagem." },
    { t: "info", x: "Recuperação em 70–80% em 3 meses. Pior prognóstico se completa, idade avançada, DM, HAS." },
  ],
  fisio: "A causa mais provável é a <strong>reativação do HSV-1 no gânglio geniculado</strong>, causando inflamação e edema do nervo facial no canal estreito do osso temporal → compressão e bloqueio de condução. Outras causas: HHV-6, Borrelia (Lyme), HIV, sarcoidose. Característica fundamental para diferenciar de AVC: a paralisia periférica acomete TODA a hemiface (incluindo a testa), enquanto o AVC poupa a testa (inervação cortical bilateral da porção superior do núcleo facial).",
  mec: [
    { d: "Prednisona", x: "Glicocorticoide — <strong>reduz edema neural</strong> e inflamação no canal facial. O benefício na recuperação é dose- e tempo-dependente (NNT ~10–12 para recuperação completa)." },
    { d: "Aciclovir / Valaciclovir", x: "Antivirais nucleosídeos — fosforilados pela timidina-quinase viral em monofosfato, depois trifosfato → inibem a <strong>DNA-polimerase viral</strong>." },
  ],
  diretriz: "AAN Practice Guideline Update: Steroids and Antivirals for Bell Palsy (Gronseth GS, Paduga R, Neurology 2012;79:2209–2213).",
  fluxo: null,
  calcs: [],
},
{
  id: "cefaleia", contexto:["pa","ubs"], sis: "neuro", grav: "baixa",
  nome: "Cefaleia (primária)",
  sin: ["cefaleia", "dor de cabeça", "tensional"],
  def: "Cefaleia sem sinais de alarme (sem início súbito, sem febre, sem déficit, sem trauma, sem alteração de consciência). Tensional é a mais comum.",
  exames: ["Anamnese e exame neurológico completo", "TC crânio se sinais de alarme (SNOOP10)", "PL se suspeita de meningite ou HSA com TC normal"],
  rx: [
    { etapa:"escala", d: "Dipirona", do: "1 g IV ou 500–1000 mg VO 6/6h", via: "IV/VO", o: "1ª linha. Diluir em SF e administrar lento (raro choque)." },
    { etapa:"escala", d: "Paracetamol", do: "750–1000 mg VO 6/6h", via: "VO", o: "Alternativa. Máx 4 g/24h." },
    { etapa:"escala", d: "Ibuprofeno", do: "400–600 mg VO 8/8h", via: "VO", o: "AINE de 1ª escolha por perfil GI." },
    { etapa:"escala", d: "Cetorolaco", do: "30 mg IV/IM 6/6h", via: "IV/IM", o: "Refratário. Máx 5 dias." },
  ],
  alertas: [
    { t: "crit", x: "Sinais de alarme (SNOOP10): início súbito (\"pior cefaleia da vida\"), febre, sintomas neurológicos, idade >50, mudança de padrão, posicional, trauma, papiledema, imunossupressão, gestação. Investigar." },
  ],
  fisio: "A <strong>cefaleia tensional</strong> tem etiologia multifatorial: tensão musculo-esquelética cervical/pericraniana, sensibilização central da via trigeminocervical, estresse. A dor é descrita como aperto bilateral, leve a moderada, sem náuseas/fotofobia significativas, sem piora aos esforços. Geralmente responde bem a analgésicos comuns. Cefaleia <strong>medicamentosa</strong> (rebote) é frequente em uso >15 dias/mês de analgésicos.",
  mec: [
    { d: "Dipirona (metamizol)", x: "Inibe <strong>COX-3 central</strong> e modula o sistema endocanabinoide; ação analgésica/antipirética sem ação anti-inflamatória periférica significativa." },
    { d: "Paracetamol", x: "Inibe predominantemente <strong>COX-2 no SNC</strong>; analgésico/antipirético. Toxicidade hepática em sobredose (NAPQI)." },
    { d: "Ibuprofeno", x: "AINE não-seletivo — inibe COX-1 e COX-2, reduzindo síntese de prostaglandinas pró-inflamatórias e nociceptivas." },
  ],
  diretriz: "Diretrizes para Tratamento da Crise Migranosa SBCe 2018 (Vincent MB et al.). International Classification of Headache Disorders ICHD-3.",
  fluxo: null,
  calcs: [],
},
{
  id: "crise", contexto:["pa","ubs"], sis: "neuro", grav: "alta",
  nome: "Crise Convulsiva / Estado de Mal Epiléptico",
  sin: ["convulsão", "crise", "EME", "status epilepticus", "epilepsia"],
  def: "Crise convulsiva única autolimitada vs. EME: crise ≥5 min OU crises recorrentes sem recuperação de consciência (ABNeuro/ILAE).",
  exames: ["HGT", "Eletrólitos (Na, Ca, Mg)", "Função renal e hepática", "Hemograma", "Toxicológico", "β-HCG", "Nível sérico de anticonvulsivantes (se em uso)", "TC crânio (1ª crise, focal, déficit, trauma)", "PL se febre/imunossupressão"],
  rx: [
    {etapa:"inicial", d:"PROTEGER + lateralizar + O₂",do:"Cabeceira lateral, retirar objetos, O₂ máscara",via:"—",o:"NÃO conter o paciente. NÃO colocar nada na boca. Cronometrar a crise."},
    {etapa:"inicial", d:"HGT capilar IMEDIATA",do:"Excluir hipoglicemia (mimic frequente)",via:"—",o:"Glicemia <50: Glicose 50% 50 mL IV (após tiamina se etilista)."},
    {etapa:"inicial", d:"Tiamina 100 mg IV antes de glicose",do:"Se etilista, desnutrido, gestante",via:"IV",o:"Previne encefalopatia de Wernicke. EMERGÊNCIA — não atrasa BZD."},
    {etapa:"inicial", d:"Acesso venoso + monitor",do:"2 acessos + ECG + SpO2",via:"—",o:"Acesso difícil em crise — considerar via IO. Coletar exames simultâneo."},
    {etapa:"escala", d:"① BZD — Diazepam IV (acesso disponível)",do:"10 mg IV bolus, repetir até 3×",via:"IV",o:"1ª linha. Em <5 min do início. Cuidado depressão respiratória."},
    {etapa:"escala", d:"① BZD — Midazolam IM (sem acesso IV)",do:"10 mg IM (>40kg) ou 0,2 mg/kg IM/intranasal/bucal",via:"IM/IN",o:"Estudo RAMPART: tão eficaz quanto IV. Início rápido. Sem acesso = via preferida."},
    {etapa:"escala", d:"① BZD — Lorazepam (alternativa preferida)",do:"4 mg IV diluído 1:1",via:"IV",o:"Menor recidiva que diazepam. Onde disponível, preferir."},
    {etapa:"escala", d:"② Anticonvulsivante de 2ª linha — Fenitoína",do:"20 mg/kg IV em SF 0,9% a 50 mg/min",via:"IV",o:"Após BZD se persiste. Monitor cardíaco (bradicardia, hipotensão). Adicional 5-10 mg/kg se ainda persistir."},
    {etapa:"escala", d:"② Anticonvulsivante — Levetiracetam (alternativa)",do:"60 mg/kg IV em 15 min (máx 4,5 g)",via:"IV",o:"ESETT trial: equivalente a fenitoína. Melhor perfil de segurança — preferir em cardiopata."},
    {etapa:"escala", d:"② Anticonvulsivante — Valproato (alternativa)",do:"40 mg/kg IV (máx 3 g)",via:"IV",o:"Útil em generalizadas. CI: hepatopata, gestante (teratogênico)."},
    {etapa:"escala", d:"③ EME refratário (>30 min) — IOT + anestésico",do:"Midazolam 0,2 mg/kg bolus + 0,1-2 mg/kg/h BIC OU Propofol 1-2 mg/kg + 30-200 mcg/kg/min",via:"IV",o:"Preparar IOT. EEG contínuo. UTI."},
    {etapa:"escala", d:"③ EME refratário — Fenobarbital alternativo",do:"15-20 mg/kg IV em 50 mg/min",via:"IV",o:"3ª linha. Depressão respiratória — IOT obrigatória."},
    {etapa:"escala", d:"④ EME super-refratário (>24h)",do:"Coma barbitúrico — Tiopental ou Pentobarbital",via:"IV",o:"UTI com EEG contínuo. Cetamina, lidocaína IV alternativas em estudos."},
    {etapa:"adj", d:"Investigação etiológica",do:"TC, RM, LP se febre, EEG, toxicológico",via:"—",o:"1ª crise sem causa óbvia: TC + considerar PL. Etilista: pensar em abstinência. Gestante: eclâmpsia → MgSO4."},
    {etapa:"alta", d:"Manutenção anticonvulsivante VO",do:"Conforme tipo de crise + neurologista",via:"VO",o:"Crise primária sem causa: discutir início. Causa estrutural ou EME: manutenção indicada."},
  ],
  alertas: [
    { t: "crit", x: "EME super-refratário (>24h): coma barbitúrico com tiopental ou pentobarbital." },
    { t: "warn", x: "SEMPRE tiamina 100 mg IV ANTES de glicose em etilistas/desnutridos (prevenir Wernicke)." },
    { t: "info", x: "Crise primeira sem alterações: investigar ambulatorialmente. Crise com déficit, idade >40, ou alteração estrutural: TC + RM + EEG." },
  ],
  fisio: "Uma crise convulsiva é resultado de uma <strong>descarga neuronal hipersíncrona</strong> excessiva — desequilíbrio entre excitação (glutamato/NMDA/AMPA) e inibição (GABA). Causas: epilepsia primária, suspensão de anticonvulsivante, tumor, AVC, TCE, infecção SNC, drogas/abstinência, distúrbios metabólicos (hipoglicemia, hiponatremia, hipocalcemia, uremia, eclâmpsia), hipertermia. No EME, ocorre <strong>internalização de receptores GABA-A</strong> e <strong>upregulação de NMDA</strong> → resistência progressiva a benzodiazepínicos com o passar do tempo. Por isso o tratamento agressivo nos primeiros 5–30 min é fundamental.",
  mec: [
    { d: "Diazepam / Midazolam / Lorazepam", x: "Agonistas alostéricos positivos do <strong>sítio benzodiazepínico do receptor GABA-A</strong>. ↑frequência de abertura do canal de Cl⁻ → hiperpolarização → inibição neuronal." },
    { d: "Fenitoína", x: "Bloqueia <strong>canais de Na⁺ voltagem-dependentes em estado inativo</strong>, prevenindo despolarização repetitiva de alta frequência." },
    { d: "Levetiracetam", x: "Liga-se à <strong>SV2A (proteína da vesícula sináptica)</strong> — modula liberação de neurotransmissores. Mecanismo único; perfil de segurança superior." },
    { d: "Valproato", x: "Múltiplos: ↑GABA, bloqueio Na⁺/Ca²⁺, modulação canais T." },
    { d: "Fenobarbital", x: "Agonista alostérico positivo do sítio barbitúrico do <strong>GABA-A — ↑duração de abertura do canal de Cl⁻</strong>." },
    { d: "Propofol", x: "Potencializa GABA-A; sedação profunda dose-dependente." },
  ],
  diretriz: "AES Status Epilepticus Guideline (Glauser T et al., Epilepsy Curr 2016;16:48–61). ABNeuro — Diretrizes 2023. ESETT trial (Kapur J et al., NEJM 2019;381:2103–2113, DOI:10.1056/NEJMoa1905795).",
  fluxo: "crise",
  calcs: [],
},
{id:"encefalite", contexto:["pa","ubs"], sis:"neuro", grav:"alta",
nome:"Encefalite",
sin:["encefalite","encefalite herpética","HSV"],
def:"Inflamação do parênquima cerebral — febre + alteração de consciência/cognição + sintomas focais ou crises convulsivas. Diferente de meningite por DISFUNÇÃO cerebral predominante. Mais comum: HSV-1, arbovírus, autoimune.",
exames:["TC crânio (excluir HIC, lesão expansiva)","Punção lombar com pleocitose linfocítica, proteína ↑, glicose normal","PCR para HSV no LCR (sensibilidade 96-98%)","RM crânio (lesões temporais mediais bilaterais = HSV)","EEG (descargas periódicas lateralizadas — PLEDs em HSV)","Sorologia/PCR para arbovírus, HIV, sífilis"],
rx:[
{etapa:"atb", d:"Aciclovir EMPÍRICO",do:"10 mg/kg IV 8/8h × 14-21 dias",via:"IV",o:"INICIAR EMPIRICAMENTE em qualquer encefalite, NÃO esperar PCR. Aciclovir reduz mortalidade HSV de 70% → 20%."},
{etapa:"inicial", d:"Ajuste de aciclovir",do:"Função renal: ClCr 25-50 → 10 mg/kg 12/12h; <25 → 10 mg/kg 24/24h",via:"IV",o:"Hidratação concomitante (cristaloide 1-2 L) — nefrotoxicidade."},
{etapa:"escala", d:"Anticonvulsivantes",do:"Fenitoína 20 mg/kg IV ou levetiracetam 60 mg/kg IV",via:"IV",o:"Crises são frequentes em HSV (50%). Tratar 1ª crise."},
{etapa:"escala", d:"Cobertura para meningite bacteriana",do:"Ceftriaxona 2g IV 12/12h + Vancomicina + Ampicilina",via:"IV",o:"Se LCR incerto/quadro grave/imunossuprimido — adicionar AMPI se >50a (Listeria)."},
],
alertas:[
{t:"crit",x:"ACICLOVIR ANTES DA PCR. Cada hora de atraso piora outcome. PCR pode ser negativa nas 1ª 72h — não usar resultado precoce para descontinuar."},
{t:"warn",x:"Encefalite autoimune (anti-NMDAR, anti-LGI1) — jovens, alteração comportamental, movimentos anormais, crises. Investigar se PCR negativa + RM atípica. Imunoglobulina + corticoide + plasmaférese."},
{t:"info",x:"HSV poupa lobos frontais (preferência por temporal medial bilateral assimétrica). Aspecto na RM é praticamente diagnóstico."},
],
fisio:"HSV-1 alcança SNC via nervo olfatório/trigêmeo, com tropismo pelos lobos temporais mediais. Infecção citopática → necrose hemorrágica focal → edema cerebral → ↑PIC → herniação. Sem tratamento: 70% mortalidade. Sequelas em sobreviventes mesmo tratados: déficit cognitivo/memorial (lobo temporal é hipocampo).",
mec:[
{d:"Aciclovir",x:"Análogo da guanosina — fosforilado pela <strong>timidina-quinase viral</strong> (só vírus tem essa enzima, daí seletividade); a forma trifosfato compete com dGTP pela DNA polimerase viral → terminação de cadeia."},
],
diretriz:"IDSA Encephalitis 2008 (Tunkel AR et al., Clin Infect Dis 2008;47:303). British Encephalitis Society 2012. PCDT/MS.",
fluxo:null,
calcs:[],
},
{id:"hsa", contexto:["pa"], sis:"neuro", grav:"alta",
nome:"Hemorragia Subaracnoide (HSA)",
sin:["HSA","hemorragia subaracnoide","aneurisma roto","trovão"],
def:"Sangramento no espaço subaracnoide — cefaleia 'trovão' (worst headache of life), súbita, máxima intensidade <1 min, ± LOC, ± rigidez nucal, ± déficit focal. Escalas: Hunt-Hess (clínica) e Fisher (radiológica).",
exames:["TC crânio sem contraste (95% sensibilidade nas 1ª 6h)","Punção lombar se TC normal + clínica forte (xantocromia)","Angio-TC ou angio-RM cerebral (procurar aneurisma)","ECG (anormal em 50% — taqui, alt repolarização, prolongamento QT)","Hemograma, eletrólitos","Coagulograma"],
rx:[
{etapa:"inicial", d:"Repouso + cabeceira 30°",do:"Ambiente calmo, monitorizado",via:"—",o:"Reduz pico hipertensivo. Profilaxia de TVP MECÂNICA (sem heparina até clipagem)."},
{etapa:"escala", d:"Nimodipino",do:"60 mg VO 4/4h × 21 dias",via:"VO",o:"INICIAR <96h da hemorragia. PREVINE vasoespasmo (não trata). Suspender se hipoTA."},
{etapa:"escala", d:"Controle da PA",do:"PAS <160 (alguns serviços <140) com labetalol/esmolol/nicardipino",via:"IV",o:"ATÉ a clipagem. Após clipagem, mais liberal (PAS 160-200) para HIPERTENSIVA — terapia 'Triple H' antiquada, focar em mantém PAM."},
{etapa:"adj", d:"Anticonvulsivantes",do:"Fenitoína 1 g IV de ataque OU levetiracetam 500 mg IV 12/12h",via:"IV",o:"Profilaxia 3-7 dias. Não usar de rotina (controverso); reservar para crise documentada."},
{etapa:"escala", d:"Clipagem cirúrgica / coiling endovascular",do:"—",via:"Cirúrgico/Endo",o:"DEFINITIVO. ASAP (<24-72h) — preferir coiling se anatomia favorável (ISAT trial, melhor outcome)."},
],
alertas:[
{t:"crit",x:"PIOR cefaleia da vida + súbita + qualquer LOC = HSA até prova contrária. NÃO se contentar com TC normal — fazer punção se >6h ou clínica clara."},
{t:"crit",x:"Vasoespasmo cerebral: dia 4-14 pós-HSA — déficit focal novo. TCD seriado, nimodipino, monitor neuro."},
{t:"warn",x:"Hidrocefalia aguda em até 20% — DVE se Glasgow ↓."},
{t:"warn",x:"Hunt-Hess: I (assintomático/cefaleia leve) → V (coma profundo, descerebração). Mortalidade 70% no V."},
],
fisio:"85% por ruptura de aneurisma sacular (PolIgono de Willis, comunicante anterior/posterior, ACM). Outras: MAV, trauma, dissecção. Após ruptura, sangue arterial sob pressão se dispersa no LCR → ↑↑PIC súbito → LOC e até herniação. Sequelas: ressangramento (24h crítico), vasoespasmo (D4-14), hidrocefalia, hiponatremia (SIADH/cerebral salt wasting), pneumonia, cardiomiopatia de Takotsubo neurogênica.",
mec:[
{d:"Nimodipino",x:"BCC dihidropiridínico — bloqueia canais L de Ca²⁺ no músculo liso vascular, com seletividade cerebral. <strong>Não previne nem reverte vasoespasmo radiologicamente</strong> mas reduz infarto cerebral retardado e melhora prognóstico funcional (mecanismo neuroprotetor não totalmente elucidado)."},
{d:"Ácido tranexâmico (não rotineiro)",x:"Antifibrinolítico — usado em alguns centros pré-clipagem. STASH e ULTRA trials desafiaram benefício rotineiro."},
],
diretriz:"AHA/ASA 2023 (Hoh BL et al., Stroke 2023;54:e314, DOI:10.1161/STR.0000000000000436). Neurocritical Care Society 2023. PCDT MS Brasil.",
fluxo:null,
calcs:[],
},
{
  id: "meningite", contexto:["pa"], sis: "neuro", grav: "alta",
  nome: "Meningite Bacteriana / Encefalite",
  sin: ["meningite", "encefalite", "meningite bacteriana"],
  def: "Febre + cefaleia + rigidez de nuca + alteração de consciência (tríade clássica em 44%). Encefalite: + alteração comportamental/cognitiva, déficit focal, crise.",
  exames: ["TC crânio ANTES da PL se: alteração de consciência, déficit focal, crise, imunossupressão, papiledema, >60a", "Punção lombar: bioquímica + celularidade + Gram + cultura + látex + PCR herpes", "Hemoculturas (2 pares)", "Hemograma, PCR/procalcitonina"],
  rx: [
    { etapa:"atb", d: "Ceftriaxona", do: "2 g IV 12/12h", via: "IV", o: "Cobertura pneumococo, meningococo, H. influenzae." },
    { etapa:"atb", d: "Vancomicina", do: "15–20 mg/kg IV 8/8h", via: "IV", o: "Pneumococo resistente à penicilina." },
    { etapa:"atb", d: "Ampicilina", do: "2 g IV 4/4h", via: "IV", o: "Adicionar se >50 anos, imunossupressão, alcoolismo, gestante (cobertura Listeria)." },
    { etapa:"adj", d: "Dexametasona", do: "0,15 mg/kg (10 mg) IV 6/6h × 4 dias", via: "IV", o: "ANTES OU JUNTO à 1ª dose de ATB. Reduz mortalidade em pneumococo." },
    { etapa:"atb", d: "Aciclovir", do: "10 mg/kg IV 8/8h × 14–21 dias", via: "IV", o: "Suspeita de encefalite herpética: febre + alteração comportamental + crise. NÃO atrasar." },
  ],
  alertas: [
    { t: "crit", x: "Não atrasar ATB esperando exames. ATB em ≤30 min do reconhecimento clínico. Coletar hemoculturas (NÃO esperar PL)." },
    { t: "warn", x: "Dexametasona deve ser administrada ANTES ou JUNTO à 1ª dose de ATB — não funciona depois (já houve liberação de citocinas)." },
    { t: "info", x: "PL: PMN ↑↑ + glicose <2/3 da glicemia + proteína ↑ = bacteriana. Linfócitos + glicose normal + proteína ↑ = viral." },
  ],
  fisio: "Bactérias colonizam nasofaringe → invadem corrente sanguínea → atravessam barreira hematoencefálica → multiplicam no LCR (espaço subaracnoide, escasso em defesas) → liberam componentes parietais (LPS, ácido lipoteicoico) → ativação de TLR e cascata inflamatória com liberação maciça de TNF-α, IL-1, IL-6 → edema, ↑pressão intracraniana, vasculite, isquemia. A <strong>resposta inflamatória é mais lesiva que a bactéria em si</strong> — daí o benefício da dexametasona ANTES do ATB (que ↑lise bacteriana e libera mais componentes inflamatórios). Agentes principais: pneumococo (50%), meningococo, H. influenzae, Listeria (>50a/imunossuprimido).",
  mec: [
    { d: "Ceftriaxona", x: "Cefalosporina de 3ª geração — inibe <strong>PBPs (proteínas ligadoras de penicilina)</strong> bloqueando a transpeptidação na síntese do peptidoglicano da parede bacteriana. Boa penetração no LCR inflamado." },
    { d: "Vancomicina", x: "Liga-se ao D-Ala-D-Ala do precursor do peptidoglicano impedindo sua incorporação à parede. Cobertura Gram+ inclusive MRSA." },
    { d: "Ampicilina", x: "Aminopenicilina — inibe PBPs; cobre Listeria (intrinsecamente resistente a cefalosporinas)." },
    { d: "Dexametasona", x: "Glicocorticoide — reduz síntese de citocinas pró-inflamatórias (TNF-α, IL-1), atenuando a resposta inflamatória meníngea. Benefício comprovado em pneumocócica adulta." },
    { d: "Aciclovir", x: "Antiviral — fosforilado pela TK viral → trifosfato inibe DNA-polimerase do herpes." },
  ],
  diretriz: "IDSA Practice Guidelines for the Management of Bacterial Meningitis (Tunkel AR et al., CID 2004;39:1267–1284, atualizado 2023). ESCMID Guideline 2016.",
  fluxo: null,
  calcs: [],
},
{
  id: "migranea", contexto:["pa","ubs"], sis: "neuro", grav: "media",
  nome: "Crise Migranosa (Enxaqueca)",
  sin: ["enxaqueca", "migrânea", "migraine"],
  def: "Cefaleia unilateral, pulsátil, moderada-grave, com fotofobia/fonofobia e/ou náuseas/vômitos, piora com atividade. ± aura visual/sensitiva.",
  exames: ["Anamnese (ICHD-3)", "Excluir sinais de alarme", "TC se atípica/persistente"],
  rx: [
    { etapa:"adj", d: "Dipirona", do: "1 g IV em SF 100 mL", via: "IV", o: "1ª linha em PS. Pode associar a antiemético." },
    { etapa:"escala", d: "Cetoprofeno", do: "100 mg IV em 100 mL SF", via: "IV", o: "Alternativa AINE." },
    { etapa:"adj", d: "Metoclopramida", do: "10 mg IV em 100 mL SF lento", via: "IV", o: "Antiemético + ação central na enxaqueca. Pode causar distonia." },
    { etapa:"escala", d: "Sumatriptano", do: "6 mg SC ou 50–100 mg VO ou 20 mg intranasal", via: "SC/VO/IN", o: "Repetir após 2h se necessário (máx 200 mg/d VO). CI: coronariopatia, AVC, HAS não controlada, ergotamina <24h." },
    { etapa:"escala", d: "Clorpromazina", do: "12,5–25 mg IV em 100 mL SF lento", via: "IV", o: "Refratário. Risco de hipotensão e distonia. Hidratar antes." },
    { etapa:"adj", d: "Dexametasona", do: "10 mg IV", via: "IV", o: "Reduz recorrência em 24–72h. Considerar em todos com crise grave/prolongada." },
  ],
  alertas: [
    { t: "warn", x: "Triptanos: CI em coronariopatia, AVC, HAS não controlada, hemiplégica/basilar, gestação." },
    { t: "info", x: "Opioides são UM dos PIORES tratamentos para enxaqueca — risco de cronificação, sem evidência de superioridade. Evitar." },
  ],
  fisio: "A enxaqueca decorre da ativação do <strong>sistema trigêmino-vascular</strong>: estímulos no córtex/tronco encefálico ativam neurônios trigeminais → liberação de neuropeptídios pró-inflamatórios (CGRP, substância P, neurocinina A) nos vasos meníngeos → <strong>vasodilatação meníngea + inflamação neurogênica estéril</strong> + sensibilização periférica e central. A aura é causada por <strong>depressão cortical alastrante</strong> (onda de despolarização que se propaga pelo córtex a 3–5 mm/min, com hiperexcitação seguida de inibição). A teoria mais atual coloca a hiperexcitabilidade neuronal e os canais de Ca²⁺ como centrais à fisiopatologia.",
  mec: [
    { d: "Sumatriptano (e outros triptanos)", x: "Agonistas seletivos dos receptores <strong>5-HT1B (vasoconstrição craniana) e 5-HT1D (↓liberação de neuropeptídios pré-sinapticamente)</strong>. Revertem a vasodilatação meníngea e a inflamação neurogênica." },
    { d: "Metoclopramida", x: "<strong>Antagonista D2</strong> central — reduz a dor migranosa por mecanismo dopaminérgico além do efeito antiemético. Também agonista 5-HT4 (procinético)." },
    { d: "Clorpromazina", x: "Antipsicótico típico, antagonista D2/D1 + bloqueio α1 + anti-H1; eficácia comparável a triptanos em PS. Risco de hipotensão." },
    { d: "Dexametasona", x: "Glicocorticoide — reduz inflamação neurogênica e previne recorrência precoce." },
  ],
  diretriz: "Protocolo Brasileiro de Tratamento da Crise de Migrânea (Sociedade Brasileira de Cefaleia 2022). AHS Consensus 2021 (Ailani J et al., Headache 2021).",
  fluxo: null,
  calcs: [],
},
{id:"sind-serotonin", contexto:["pa","ubs"], sis:"neuro", grav:"alta",
nome:"Síndrome Serotoninérgica / NMS",
sin:["síndrome serotoninérgica","NMS","síndrome neuroléptica maligna","hipertermia maligna"],
def:"Síndrome serotoninérgica: TRIÁDE = alterações mentais + autonômicas (taquicardia, HAS, hipertermia, sudorese) + neuromusculares (CLÔNUS, hiperreflexia, tremor) após inserção/aumento de droga serotoninérgica. NMS: rigidez 'cano de chumbo' + hipertermia + alteração consc + autonômico após neuroléptico (D2-antagonista).",
exames:["CPK (↑↑ ambos), mioglobina urinária","Função renal (rabdomiólise)","Hemograma, função hepática","Gaso arterial, lactato","Eletrólitos","TC crânio + LP se dúvida diagnóstica (excluir meningite)"],
rx:[
{etapa:"atb", d:"SUSPENDER agente causador",do:"Imediato",via:"—",o:"PILAR. Identificar gatilho (ISRS+IMAO+linezolida+tramadol+tryptano+ondansetron, etc.)."},
{etapa:"escala", d:"Suporte agressivo",do:"Resfriamento ativo (manta + cristaloide gelado) + monitorização + hidratação 4-6 L/d",via:"IV",o:"Hipertermia >40°C → intervenção imediata."},
{etapa:"escala", d:"Sedação BZD",do:"Diazepam 5-10 mg IV repetir ou midazolam BIC 0,05-0,2 mg/kg/h",via:"IV",o:"Reduz agitação, rigidez, autonomia. 1ª linha em ambas síndromes."},
{etapa:"escala", d:"Ciproheptadina (S. serotoninérgica)",do:"12 mg VO/SNG ataque + 2 mg 2/2h até melhora (máx 32 mg/d)",via:"VO",o:"Antagonista 5-HT2A. Reservado para casos graves/refratários."},
{etapa:"escala", d:"Bromocriptina + Dantrolene (NMS)",do:"Bromocriptina 2,5-5 mg 8/8h + Dantrolene 2,5 mg/kg IV até 10 mg/kg/d",via:"VO+IV",o:"NMS grave/refratário. Bromocriptina = agonista D2. Dantrolene reduz Ca²⁺ muscular."},
{etapa:"escala", d:"IOT + curare",do:"Bloqueio neuromuscular se rigidez ameaça hipertermia/rabdo",via:"IV",o:"NÃO usar succinilcolina em NMS (risco hipercalemia)."},
],
alertas:[
{t:"crit",x:"NMS rigidez tipo CANO DE CHUMBO (continuous), bradi-reflexia. Serotoninérgica = clônus + HIPERreflexia. Mnemonic: 'neuroléptico = NEUROlepticano' rígido; 'serotonin = SHAKES' (treme/clônus)."},
{t:"crit",x:"HIPERTERMIA >40°C + rabdomiólise + IRA + CIVD → mortalidade 10-20% se não tratada agressivamente."},
{t:"warn",x:"Drogas mais associadas: SS = ISRS+IMAO, linezolida, tramadol, MDMA, LSD. NMS = haloperidol, clorpromazina, depot, retirada abrupta de levodopa."},
],
fisio:"Serotoninérgica: excesso sináptico de 5-HT em receptores 5-HT2A/1A. Início rápido (horas após gatilho). NMS: bloqueio D2 striatal → rigidez e hipertermia central (hipotálamo). Início mais lento (dias-semanas). Ambas causam contratura muscular sustentada → calor + lactato + rabdomiólise + ↑K + acidose + IRA.",
mec:[
{d:"Ciproheptadina",x:"Anti-histamínico de 1ª geração com forte antagonismo 5-HT2A. Bloqueia ação serotoninérgica excessiva."},
{d:"Bromocriptina",x:"Agonista D2 — desbloqueia receptores dopaminérgicos centrais."},
{d:"Dantrolene",x:"Bloqueia receptor de rianodina (RyR1) no retículo sarcoplasmático → ↓liberação de Ca²⁺ → relaxa músculo esquelético sem ação central. Antídoto da hipertermia maligna anestésica também."},
],
diretriz:"Boyer EW, NEJM 2005;352:1112 (Serotonin Syndrome). Strawn JR, Am J Psychiatry 2007;164:870 (NMS).",
fluxo:null,
calcs:[],
},
{
  id: "vertigem", contexto:["pa","ubs"], sis: "neuro", grav: "baixa",
  nome: "Vertigem",
  sin: ["vertigem", "tontura", "VPPB", "labirintite"],
  def: "Sensação ilusória de movimento. Periférica: rotatória, intensa, com náuseas/sudorese, melhora ao fixar olhar, nistagmo unidirecional/horizontal. Central: pior, com déficit focal, nistagmo vertical/multidirecional.",
  exames: ["Exame neurológico completo", "HINTS (Head Impulse, Nystagmus, Test of Skew)", "Manobra de Dix-Hallpike (VPPB)", "TC ou RM se central"],
  rx: [
    { etapa:"escala", d: "Dimenidrato", do: "50–100 mg IV ou 50 mg VO 6/6h", via: "IV/VO", o: "1ª linha em vertigem aguda periférica. Sonolência." },
    { etapa:"escala", d: "Meclozina", do: "25–50 mg VO 8/8h", via: "VO", o: "Alternativa, menos sedativa." },
    { etapa:"escala", d: "Cinarizina", do: "25 mg VO 8/8h", via: "VO", o: "Pode causar SEP em uso prolongado." },
    { etapa:"adj", d: "Metoclopramida", do: "10 mg IV/IM", via: "IV/IM", o: "Antiemético." },
    { etapa:"escala", d: "Manobra de Epley", do: "Reposicionamento canalicular", via: "—", o: "1ª linha em VPPB do canal posterior." },
  ],
  alertas: [
    { t: "warn", x: "HINTS sugestivo de central (impulso negativo + nistagmo direção-mutável + skew deviation) → AVC cerebelar/tronco. Imagem URGENTE." },
  ],
  fisio: "A vertigem periférica decorre de disfunção do <strong>aparelho vestibular</strong> (labirinto, nervo vestibular): <strong>VPPB</strong> (otólitos deslocados em canais semicirculares — 50% dos casos), <strong>neurite vestibular</strong> (provavelmente viral), <strong>doença de Ménière</strong> (hidropsia endolinfática). A vertigem central decorre de lesão de núcleos vestibulares ou cerebelo (AVC, EM, tumor). A distinção é crucial: AVC cerebelar pode mimetizar neurite e tem indicação de imagem urgente.",
  mec: [
    { d: "Dimenidrato / Meclozina", x: "<strong>Antagonistas H1 + anticolinérgicos centrais</strong> — suprimem a transmissão no núcleo vestibular e zona quimiorreceptora gatilho. Eficazes mas sedativos." },
    { d: "Cinarizina", x: "Bloqueador de canais de Ca²⁺ vestibulares + antagonismo H1; ação \"calmante labiríntico\". Pode causar SEP." },
  ],
  diretriz: "Bárány Society — Classification of Vestibular Disorders (Bisdorff A et al., J Vestib Res 2009;19:1–13).",
  fluxo: null,
  calcs: [],
},
);
