/* ===========================================================
   VOVÔMINIC EMERGÊNCIA — pat/psiq.js
   9 patologias
   Sistemas: psiq
   =========================================================== */

PATOLOGIAS.push(

/* ============== PSIQ (9) ============== */

{
  id:"acatisia", sis:"psiq", grav:"baixa",
  nome:"Acatisia",
  sin:["acatisia","SEP","inquietação motora"],
  def:"Inquietação motora subjetiva e objetiva — paciente refere \"não consegue ficar parado\". Efeito adverso de antipsicóticos, metoclopramida, ISRS.",
  exames:["Avaliação clínica","Revisão medicamentosa"],
  rx:[
    {etapa:"escala", d:"Propranolol",do:"20–40 mg VO 8/8h",via:"VO",o:"1ª linha. β-bloqueador lipofílico — atravessa BHE."},
    {etapa:"escala", d:"Biperideno",do:"2–4 mg VO/IM",via:"VO/IM",o:"Anticolinérgico — útil em distonia também."},
    {etapa:"escala", d:"Clonazepam",do:"0,5–2 mg VO",via:"VO",o:"Alternativa."},
    {etapa:"escala", d:"Reduzir/trocar agente causal",do:"—",via:"—",o:"Principalmente — trocar haloperidol por atípico de menor risco."},
  ],
  alertas:[
    {t:"info",x:"Acatisia AGITA o paciente e pode ser confundida com piora psicótica — não aumentar antipsicótico, REDUZIR."},
  ],
  fisio:"Bloqueio de receptores D2 da via mesolímbica/nigroestriatal → desequilíbrio dopaminérgico-colinérgico no estriado.",
  mec:[
    {d:"Propranolol",x:"β-bloqueador não-seletivo lipofílico — penetra BHE e modula sistema noradrenérgico central."},
    {d:"Biperideno",x:"<strong>Anticolinérgico central</strong> — restaura equilíbrio dopa-colinérgico nigroestriatal."},
  ],
  diretriz:"WFSBP; ABP.",
  calcs:[],
},
{
  id:"agitacao", sis:"psiq", grav:"alta",
  nome:"Agitação Psicomotora",
  sin:["agitação","violência","contenção"],
  def:"Agitação intensa com risco para paciente/equipe. Etiologia orgânica (delirium, intox), psiquiátrica ou comportamental.",
  exames:["HGT, eletrólitos, função renal","Toxicológico se suspeita","TC crânio se déficit/trauma"],
  rx:[
    {etapa:"escala", d:"Descalonamento verbal",do:"PRIMEIRO sempre",via:"—",o:"Comunicação calma, espaço, evitar confronto. Eficaz em maioria."},
    {etapa:"escala", d:"Haloperidol + Prometazina",do:"5 mg + 25 mg IM (Cochrane TREC)",via:"IM",o:"Esquema mais estudado em agitação aguda — eficaz e seguro."},
    {etapa:"escala", d:"Midazolam",do:"5–15 mg IM",via:"IM",o:"Alternativa em intoxicação alcoólica/desconhecida. Cuidado: depressão respiratória."},
    {etapa:"escala", d:"Olanzapina",do:"10 mg IM",via:"IM",o:"Atípico — NÃO combinar com BZD IV (depressão respiratória)."},
    {etapa:"escala", d:"Cetamina",do:"4–5 mg/kg IM",via:"IM",o:"Refratário extremo (excited delirium). Pré-hospitalar."},
    {etapa:"adj", d:"Contenção mecânica",do:"4–5 pontos, conforme protocolo",via:"—",o:"Último recurso. Tempo limitado, supervisão contínua, reavaliação."},
  ],
  alertas:[
    {t:"crit",x:"Agitação + febre + rigidez = pensar em SNM ou serotoninérgica. NÃO continuar com antipsicótico de alta potência sem avaliar."},
    {t:"warn",x:"Idoso agitado = delirium até prova contrário (infecção, drogas, retenção urinária, fecal, dor). Tratar a CAUSA, não só o sintoma."},
  ],
  fisio:"Múltiplas causas. Sempre buscar desencadeante orgânico, especialmente no idoso.",
  mec:[],
  diretriz:"Diretrizes Brasileiras para o Manejo da Agitação Psicomotora — ABP (Baldaçara L et al., Debates em Psiquiatria 2021–2022).",
  calcs:[],
},
{
  id:"ansiedade", sis:"psiq", grav:"baixa",
  nome:"Crise de Ansiedade / Pânico",
  sin:["ansiedade","pânico","ataque de pânico"],
  def:"Início súbito de medo intenso + sintomas físicos: taquicardia, sudorese, tremor, dispneia, dor torácica, parestesia, despersonalização. Pico em 10 min, autolimitada.",
  exames:["Excluir causa orgânica: ECG, TSH, glicemia, eletrólitos"],
  rx:[
    {etapa:"escala", d:"Clonazepam",do:"0,5–2 mg VO/SL",via:"VO/SL",o:"Início 30–60 min. BZD de meia-vida longa."},
    {etapa:"escala", d:"Alprazolam",do:"0,25–0,5 mg VO",via:"VO",o:"Início rápido, ação curta."},
    {etapa:"escala", d:"Lorazepam",do:"1–2 mg VO",via:"VO",o:"Boa em hepatopata (sem metabólitos ativos)."},
    {etapa:"escala", d:"Tranquilização verbal",do:"—",via:"—",o:"Importante. Respiração lenta. Não é IAM."},
  ],
  alertas:[
    {t:"warn",x:"BZD são para uso AGUDO. Não prescrever crônico — dependência, tolerância. Encaminhar para psiquiatria/psicologia."},
  ],
  fisio:"Hiperativação do eixo límbico-amigdalar com descarga adrenérgica intensa.",
  mec:[
    {d:"BZD (Clonazepam, Alprazolam, Lorazepam)",x:"Agonistas do sítio benzodiazepínico no <strong>receptor GABA-A</strong> → ↑frequência de abertura de canal Cl⁻ → hiperpolarização → inibição neuronal."},
  ],
  diretriz:"APA Practice Guideline for Panic Disorder.",
  calcs:[],
},
{id:"depressao", nome:"Depressão Maior (TDM) — diagnóstico + tratamento ambulatorial", sis:"psiq", grav:"moderada",
cid:"F32/F33", ciap:"P76",
sin:["TDM","Depressão maior","Depressão unipolar","Episódio depressivo","ISRS","PHQ-9","Ideação suicida"],
def:"⚠ Transtorno depressivo maior (TDM) caracterizado por ≥5 sintomas (DSM-5-TR) por ≥2 SEMANAS, incluindo OBRIGATORIAMENTE humor deprimido OU anedonia. Diferenciar de tristeza situacional, luto, transtorno bipolar (sempre RASTREAR mania), distimia. Tratamento inicial AMBULATORIAL com ISRS + psicoterapia. ⚠ AVALIAÇÃO DE RISCO SUICIDA é parte do diagnóstico.",
quadro:["⚠ ≥5 sintomas DSM-5 por ≥2 sem, com pelo menos 1 dos 2 SINTOMAS CARDINAIS:","(1) Humor deprimido na maior parte do dia","(2) Anedonia (perda de interesse/prazer)","Outros sintomas: alterações de sono, apetite/peso, energia, psicomotor, concentração, autoestima/culpa, ⚠ IDEAÇÃO SUICIDA","Distimia (PDD): sintomas leves persistentes >2 anos","BIPOLAR: SEMPRE rastrear história de MANIA/HIPOMANIA (MDQ — Mood Disorder Questionnaire) — antidepressivo isolado em bipolar precipita mania"],
diag:["DSM-5-TR — clínico","PHQ-9 quantifica gravidade: 0-4 (mínima); 5-9 (leve); 10-14 (moderada); 15-19 (mod-grave); 20-27 (grave)","HAM-D, MADRS — escalas alternativas","⚠ AVALIAR RISCO SUICIDA — pergunta direta NÃO induz suicídio, evidência clara","CSSRS, ideação passiva vs ativa, plano, meio, tentativas prévias, fatores de proteção"],
exames:["TSH (descartar hipotireoidismo)","Hemograma, B12, vit D (em quadro atípico)","Glicemia, função hepática/renal (preparar terapia)","Não há exame que CONFIRME depressão — é diagnóstico clínico","Investigar substância (álcool, drogas, medicamentos: corticoide, anti-hipertensivos)"],
rx:[
{etapa:"inicial", d:"⚠ AVALIAR RISCO SUICIDA em todo paciente"},
{etapa:"inicial", d:"PERGUNTAR DIRETO: 'tem pensado em se machucar / em morrer / fazer algo contra você?'"},
{etapa:"inicial", d:"Estratificar: passiva (cansei de viver) → ativa (planos) → ⚠ INTERNAÇÃO se plano + meio + risco iminente"},
{etapa:"inicial", d:"AVALIAR fatores de RISCO: tentativa prévia, doença crônica grave, perda recente, álcool/droga, isolamento, idade extremos, gênero masculino"},
{etapa:"inicial", d:"FATORES DE PROTEÇÃO: filhos pequenos, religião, vínculos, esperança no tratamento"},
{etapa:"escala", d:"⚠ TRATAMENTO 1ª LINHA — depressão LEVE-MODERADA"},
{etapa:"escala", d:"PSICOTERAPIA isolada — TCC ou interpessoal — em DEPRESSÃO LEVE", o:"⚠ Eficácia comparável a antidepressivo em LEVE. Preferida em gestante, alergia, recusa de fármaco."},
{etapa:"escala", d:"ANTIDEPRESSIVO ISRS — em moderada-grave, ou leve com falência de psicoterapia", o:""},
{etapa:"escala", d:"1ª ESCOLHA: SERTRALINA 25-50 mg/d, titular a 100-200 mg/d em 2-4 sem", do:"50-200 mg/d", via:"VO", o:"Perfil amplo, poucos efeitos colaterais, segura em cardiopata, gestante (com cautela), idoso."},
{etapa:"escala", d:"OU FLUOXETINA 20-60 mg/d", do:"20-60 mg/d", via:"VO", o:"⚠ Longa meia-vida — útil em paciente não-aderente (washout natural se 'esquecer'). Cuidado em idoso. Vantagem: REMUME, custo baixo."},
{etapa:"escala", d:"OU ESCITALOPRAM 10-20 mg/d", do:"10-20 mg/d", via:"VO", o:"⚠ Menos interações medicamentosas (ideal em polifarmacizado, idoso). Custo maior. Dose máxima 20 mg (idoso 10 mg — risco QT)."},
{etapa:"escala", d:"⚠ REAVALIAR em 2-4 SEMANAS — efeito começa em 2-3 semanas, pleno em 4-6 semanas"},
{etapa:"escala", d:"Resposta = ↓50% sintomas; Remissão = PHQ-9 <5"},
{etapa:"adj", d:"⚠ NÃO RESPONDE em 4-6 sem com dose otimizada:"},
{etapa:"adj", d:"(1) Confirmar adesão + tolerância"},
{etapa:"adj", d:"(2) Aumentar dose até máximo tolerado"},
{etapa:"adj", d:"(3) Trocar para outro ISRS (~30% responde)"},
{etapa:"adj", d:"(4) Trocar de classe — ISRSN (venlafaxina, duloxetina) ou atípico (bupropiona, mirtazapina)"},
{etapa:"adj", d:"(5) Combinar 2 classes (psiquiatria) — refratariedade"},
{etapa:"adj", d:"⚠ DEPRESSÃO ATÍPICA (hipersonia, hiperfagia, paralisia plumbea, reatividade humor): ISRS OK; IMAO é alternativa antiga"},
{etapa:"adj", d:"⚠ DEPRESSÃO COM CARACTERÍSTICAS MELANCÓLICAS / ANSIOSAS: ISRS OK"},
{etapa:"adj", d:"⚠ DEPRESSÃO PSICÓTICA: antidepressivo + antipsicótico — ENCAMINHAR psiquiatria"},
{etapa:"adj", d:"⚠ DEPRESSÃO COM INSÔNIA proeminente: MIRTAZAPINA 15-45 mg à noite (sedativa) — alternativa"},
{etapa:"adj", d:"⚠ DEPRESSÃO COM PERDA DE PESO/ENERGIA: MIRTAZAPINA OU bupropiona (estimulante)"},
{etapa:"adj", d:"⚠ COMORBIDADE COM DOR CRÔNICA / FIBROMIALGIA: DULOXETINA 30-120 mg/d OU venlafaxina"},
{etapa:"adj", d:"⚠ COMORBIDADE COM TABAGISMO: BUPROPIONA 150-300 mg/d (efeito dual antidepressivo + cessação tabágica)"},
{etapa:"adj", d:"⚠ SUSPENSÃO DE ANTIDEPRESSIVO — após resposta, MANTER 6-12 MESES após remissão (1º episódio); 2 anos (2º episódio); INDEFINIDO (3+ episódios ou alto risco)"},
{etapa:"adj", d:"⚠ Suspender GRADUALMENTE — reduzir 25% a cada 2-4 semanas (evita síndrome de descontinuação: vertigem, parestesia, sintomas gripais, irritabilidade)"},
{etapa:"adj", d:"⚠ FLUOXETINA tem washout natural — pode suspender sem retirada gradual"},
{etapa:"adj", d:"PAROXETINA, VENLAFAXINA, DULOXETINA: piores síndromes de descontinuação"},
{etapa:"alta", d:"⚠ INDICAÇÕES DE PSIQUIATRIA: depressão refratária (falha 2 ISRSs), psicótica, bipolaridade, alto risco suicida, comorbidade complexa, gestante com indicação de farmacoterapia complexa, idoso com prejuízo funcional importante"},
{etapa:"alta", d:"⚠ INTERNAÇÃO PSIQUIÁTRICA: ideação suicida com plano + meio + risco iminente; psicose com agitação/heteroagressão; impossibilidade de cuidado domiciliar"},
{etapa:"alta", d:"INTEGRAR: psicoterapia (TCC ou interpessoal), exercício aeróbico (4-5×/sem, evidência B), higiene do sono, exposição à luz, suporte social"},
{etapa:"alta", d:"AVALIAR comorbidades clínicas (hipotireoidismo, anemia, B12 baixa, DM descompensada) — tratar pode melhorar humor"},
],
alertas:[
{nivel:"crit", txt:"⚠ AVALIAR RISCO SUICIDA em todo paciente — pergunta direta NÃO induz suicídio. Plano + meio + risco iminente = internação psiquiátrica."},
{nivel:"crit", txt:"⚠ RASTREAR BIPOLARIDADE antes de antidepressivo — questionar mania/hipomania (gastos, projetos grandiosos, dormir pouco se sentir bem, irritabilidade). ANTIDEPRESSIVO ISOLADO em bipolar precipita mania."},
{nivel:"crit", txt:"⚠ AUMENTO DE IDEAÇÃO SUICIDA nas PRIMEIRAS 2-4 SEMANAS após início de ISRS especialmente em <25a — orientar paciente e família, monitor próximo (FDA black box)."},
{nivel:"warn", txt:"⚠ SÍNDROME SEROTONINÉRGICA — risco em ISRS + IMAO + tramadol + linezolida + triptanos + ondansetrona em dose alta. Tríade: hiperreatividade autonômica + alteração mental + alterações neuromusculares (mioclonia, hiperreflexia)."},
{nivel:"warn", txt:"⚠ NÃO INICIAR ANTIDEPRESSIVO em paciente com SINAIS CLAROS DE BIPOLARIDADE — sempre rastrear mania/hipomania, MDQ. Bipolaridade: estabilizador (lítio, valproato, lamotrigina) + psiquiatria."},
{nivel:"warn", txt:"GESTAÇÃO: ISRS aceitos. SERTRALINA é a mais segura. PAROXETINA evitar (anomalias cardíacas em meta-análises). Não suspender antidepressivo na gestação em paciente estabilizada por risco recaída + depressão pós-parto."},
{nivel:"info", txt:"⚠ Efeito do antidepressivo é GRADUAL — começa em 2-3 sem, pleno em 4-6 sem. Importante orientar paciente. Adesão nas primeiras 4 sem é o maior desafio."},
{nivel:"info", txt:"⚠ DURAÇÃO DO TRATAMENTO: 6-12 meses após remissão (1º episódio); 2 anos (2º); indefinido (3+ episódios ou alto risco recorrência)."},
{nivel:"info", txt:"PHQ-9 ≥10 = depressão clinicamente significativa. Item 9 (ideação suicida) requer avaliação independente."},
],
fluxo:null, diretriz:"DSM-5-TR; APA Practice Guideline; NICE Depression; ABP. PHQ-9 validado pt-BR."
},
{id:"insonia", nome:"Insônia crônica — abordagem ambulatorial", sis:"psiq", grav:"baixa",
cid:"F51.0/G47.0", ciap:"P06",
sin:["Insônia","Dificuldade para dormir","TCC-I","Higiene do sono","Hipnóticos"],
def:"⚠ Dificuldade de INICIAR ou MANTER o sono, ou DESPERTAR PRECOCE, com SOFRIMENTO ou PREJUÍZO funcional, ≥3 noites/semana por ≥3 meses (crônica) ou <3 meses (aguda). ⚠ Tratamento 1ª LINHA é TCC-I (terapia cognitivo-comportamental para insônia). Hipnótico é 2ª linha, curto prazo. Sempre INVESTIGAR causa secundária.",
quadro:["⚠ INSÔNIA INICIAL: dificuldade de adormecer (>30 min latência)","⚠ MANUTENÇÃO: despertares frequentes / dificuldade de voltar a dormir","⚠ TERMINAL: despertar precoce, sem possibilidade de retomar sono","Frequência ≥3 noites/sem, ≥3 meses (crônica) ou <3m (aguda)","⚠ AVALIAR HIGIENE DO SONO (vide adiante)","⚠ INVESTIGAR comorbidades: depressão (insônia terminal típica), ansiedade (inicial), apneia do sono (RONCO, PAUSAS, sonolência diurna excessiva), síndrome das pernas inquietas, refluxo, doenças cardiopulmonares, dor crônica, hipertireoidismo, medicações (corticoide, broncodilatador, descongestionante, β-bloqueador, estimulantes)"],
diag:["Anamnese detalhada do sono — diário do sono por 1-2 sem é GOLD STANDARD","Avaliar comorbidades clínicas e psiquiátricas","Pesquisar APNEIA OBSTRUTIVA DO SONO: ronco alto, pausas testemunhadas, sonolência diurna (Epworth), HAS resistente, obesidade. Polissonografia se suspeita.","Pesquisar SÍNDROME DAS PERNAS INQUIETAS: necessidade urgente de mover pernas + sintoma sensitivo + piora repouso + alívio movimento + piora à noite. Dosar ferritina (<75 ng/mL: repor ferro).","Investigar medicações, álcool, cafeína, drogas"],
exames:["Geralmente clínico","TSH (descartar hipertireoidismo)","Ferritina (descartar pernas inquietas associada a ferropenia)","Em suspeita apneia: polissonografia"],
rx:[
{etapa:"escala", d:"⚠ 1ª LINHA — TCC-I (terapia cognitivo-comportamental para insônia)"},
{etapa:"escala", d:"⚠ EFICÁCIA SUPERIOR a fármacos em médio-longo prazo. Sem efeitos colaterais."},
{etapa:"escala", d:"⚠ COMPONENTES:"},
{etapa:"escala", d:"(1) Higiene do sono"},
{etapa:"escala", d:"(2) Controle de estímulos (cama apenas para dormir + sexo; sair se não dormir em 20 min)"},
{etapa:"escala", d:"(3) Restrição do tempo na cama (compactação)"},
{etapa:"escala", d:"(4) Técnicas de relaxamento"},
{etapa:"escala", d:"(5) Reestruturação cognitiva (crenças disfuncionais sobre o sono)"},
{etapa:"escala", d:"Aplicável por psicólogo treinado, terapeuta especialista em sono, ou via apps validados (Sleepio, SHUTi)"},
{etapa:"adj", d:"⚠ HIGIENE DO SONO — orientações práticas (aplicável a todos)"},
{etapa:"adj", d:"HORÁRIO FIXO de deitar e ACORDAR (inclusive fim de semana)"},
{etapa:"adj", d:"EVITAR cochilo diurno >30 min ou após 15h"},
{etapa:"adj", d:"REDUZIR cafeína (após 14h), álcool (sedativo mas fragmenta sono), nicotina"},
{etapa:"adj", d:"EVITAR refeição pesada + líquidos abundantes 2-3h antes"},
{etapa:"adj", d:"EXPOSIÇÃO À LUZ SOLAR durante o dia; ESCURIDÃO à noite"},
{etapa:"adj", d:"AMBIENTE: quarto escuro, fresco (18-20°C), silencioso"},
{etapa:"adj", d:"EVITAR telas (azul-emissores) 1-2h antes de dormir"},
{etapa:"adj", d:"EXERCÍCIO regular — preferencialmente até 3-4h antes de dormir"},
{etapa:"adj", d:"RITUAL relaxante pré-sono (banho morno, leitura, meditação)"},
{etapa:"adj", d:"NÃO 'TENTAR' dormir — se não conseguir em 20 min, levantar e fazer atividade calma até sonolência"},
{etapa:"adj", d:"⚠ 2ª LINHA — FÁRMACOS (uso curto, 2-4 semanas)"},
{etapa:"adj", d:"⚠ TRAZODONA 25-100 mg HS — antidepressivo com efeito sedativo. Eficaz em insônia + depressão. ⚠ Risco priapismo (raro)", do:"25-100 mg à noite", via:"VO", o:"OFF-LABEL para insônia mas amplamente usado. Sem dependência. Sedação residual em alguns."},
{etapa:"adj", d:"⚠ MIRTAZAPINA 7,5-15 mg HS — em insônia + depressão. Sedação forte em dose baixa", do:"7,5-15 mg à noite", via:"VO", o:"Ganho de peso. Útil em paciente com perda de peso."},
{etapa:"adj", d:"⚠ AMITRIPTILINA 10-25 mg HS — tricíclico com efeito sedativo + analgesia neuropática", do:"10-25 mg à noite", via:"VO", o:"Útil em insônia + dor neuropática / cefaleia tensional. ⚠ ANTICOLINÉRGICO — evitar em idoso (Beers), HPB, glaucoma."},
{etapa:"adj", d:"⚠ DOXEPINA 3-6 mg — H1 seletivo em dose baixa, registrado para insônia (não disponível Brasil)", obs:""},
{etapa:"adj", d:"⚠ BENZODIAZEPÍNICOS — 3ª LINHA, USO MUITO CURTO (2-4 sem)"},
{etapa:"adj", d:"CLONAZEPAM 0,25-2 mg HS — longa duração, risco residual matinal", obs:"Dependência rápida. NÃO ROTINEIRO."},
{etapa:"adj", d:"NITRAZEPAM 5-10 mg HS — alternativa similar", obs:""},
{etapa:"adj", d:"FLURAZEPAM, MIDAZOLAM — alternativas. NUNCA em idoso (Beers)."},
{etapa:"adj", d:"⚠ Z-DRUGS (zolpidem, zopiclona, eszopiclona) — efeito semelhante BZD com perfil diferente"},
{etapa:"adj", d:"Zolpidem 5-10 mg HS — vida curta, menos sedação matinal", obs:"Dependência (menos que BZD mas existe). ⚠ Sonambulismo, comportamento complexo durante sono."},
{etapa:"adj", d:"Zopiclona 3,75-7,5 mg HS", obs:"Gosto metálico matinal típico."},
{etapa:"adj", d:"⚠ EVITAR BZD/Z-DRUGS EM IDOSO — Beers Criteria — risco quedas, fraturas, delirium, demência"},
{etapa:"adj", d:"⚠ MELATONINA 0,3-5 mg HS — leve eficácia, sem dependência. Útil em IDOSO (declínio fisiológico) e em distúrbio do ritmo circadiano (jet lag, trabalho noturno)", do:"0,3-5 mg HS", via:"VO", o:"⚠ NUNCA é tratamento principal de insônia crônica clássica. Útil em casos específicos."},
{etapa:"adj", d:"⚠ DIFENIDRAMINA / DRAMIN — ANTI-HISTAMÍNICO, popularmente usado. ⚠ NÃO RECOMENDADO em uso crônico — anticolinérgico (carga cognitiva, demência em idoso, retenção urinária)"},
{etapa:"alta", d:"⚠ INVESTIGAR + TRATAR COMORBIDADE — chave"},
{etapa:"alta", d:"Apneia do sono → CPAP / odontológico / cirurgia (referência polissonografia)"},
{etapa:"alta", d:"Pernas inquietas → ferro VO se ferritina <75 (ferro fumarato 350 mg/d 4-8 sem), agonista dopaminérgico (pramipexol) em refratário"},
{etapa:"alta", d:"Depressão/ansiedade → tratamento específico (ver patologias)"},
{etapa:"alta", d:"Dor crônica, refluxo, hipertireoidismo, etc."},
{etapa:"alta", d:"⚠ AJUSTAR MEDICAÇÕES — descongestionantes, estimulantes, corticoide, broncodilatador, β-bloqueador. Tomar precoces no dia."},
{etapa:"alta", d:"⚠ EM IDOSO: priorizar medidas não-farmacológicas. Se preciso, melatonina ou doses baixas de trazodona."},
],
alertas:[
{nivel:"crit", txt:"⚠ NÃO ASSUMIR insônia primária sem INVESTIGAR APNEIA OBSTRUTIVA DO SONO — ronco alto + pausas testemunhadas + sonolência diurna + obesidade + HAS = alta probabilidade. Polissonografia."},
{nivel:"warn", txt:"⚠ EVITAR BZD/Z-DRUGS EM IDOSO — Beers Criteria. Riscos: quedas, fraturas, delirium, demência, dependência."},
{nivel:"warn", txt:"⚠ TCC-I é 1ª LINHA — eficácia SUPERIOR a fármacos em médio-longo prazo, sem efeitos colaterais. Subutilizada no Brasil por falta de profissionais — apps validados podem ajudar."},
{nivel:"warn", txt:"⚠ ANTI-HISTAMÍNICOS H1 (difenidramina, prometazina, dramin) NÃO são recomendados em uso crônico para insônia — anticolinérgicos, carga cognitiva, demência em idoso, retenção urinária."},
{nivel:"warn", txt:"AMITRIPTILINA em DOSE BAIXA (10-25 mg) é útil em insônia + dor neuropática. EVITAR em idoso por efeito anticolinérgico."},
{nivel:"info", txt:"MELATONINA tem eficácia modesta em insônia crônica. Mais útil em distúrbios do ritmo circadiano (jet lag, idoso, trabalhador noturno)."},
{nivel:"info", txt:"⚠ RESTRIÇÃO DO TEMPO NA CAMA (componente do TCC-I) é contraintuitivo mas EFICAZ — reduzir tempo na cama (mesmo se dormir menos) até consolidar sono, depois aumentar gradativamente."},
],
fluxo:null, diretriz:"AASM (American Academy of Sleep Medicine); ABS (Sono Brasil); NICE Insomnia."
},
{id:"panico", nome:"Transtorno de Pânico — manejo da crise e crônico", sis:"psiq", grav:"moderada",
cid:"F41.0", ciap:"P74",
sin:["Pânico","Transtorno do pânico","Crise de pânico","Agorafobia","Ataque pânico"],
def:"⚠ Ataques recorrentes de PÂNICO ESPONTÂNEOS (sem gatilho identificável) + preocupação persistente sobre novos ataques OU mudança maladaptativa de comportamento (evitação) ≥1 mês. Crise: início abrupto, pico em 10 min, autonômico + cognitivo (medo de morrer/enlouquecer). Frequentemente confundido com IAM/TEP — DDX antes de rotular. Tratamento: ISRS + TCC.",
quadro:["⚠ CRISE DE PÂNICO: início ABRUPTO, pico em 10 min, dura 10-30 min. ≥4 dos seguintes:","palpitação/taquicardia, sudorese, tremor, dispneia, sensação de asfixia, dor torácica, náusea/desconforto abdominal, tonteira, calafrio/calor, parestesias, desrealização/despersonalização, ⚠ MEDO DE MORRER, medo de enlouquecer/perder controle","TRANSTORNO DE PÂNICO: crises recorrentes + ≥1 mês de preocupação OU mudança comportamental","⚠ AGORAFOBIA frequentemente associada — evitação de situações que parecem causar pânico"],
diag:["DSM-5-TR — clínico","⚠ EXCLUIR causas orgânicas no PRIMEIRO ataque: IAM, TEP, arritmia, hipertireoidismo, feocromocitoma, hipoglicemia, abstinência, uso de estimulantes","Em paciente com diagnóstico estabelecido + crise típica recorrente: foco em manejo"],
exames:["⚠ NO PRIMEIRO ATAQUE: ECG, troponina (se dor torácica), D-dímero (se TEP suspeito), TSH, glicemia, eletrólitos, tóxico (urina)","Em pânico estabelecido com crise típica: geralmente nenhum"],
rx:[
{etapa:"inicial", d:"⚠ CRISE AGUDA — abordagem de emergência"},
{etapa:"inicial", d:"⚠ EXCLUIR CAUSA ORGÂNICA em primeira crise atípica (ECG, sinais vitais, exame físico)"},
{etapa:"escala", d:"⚠ AMBIENTE TRANQUILO, isolar do agito"},
{etapa:"escala", d:"COMUNICAÇÃO CALMA, validar emoção, REASSEGURAMENTO 'isso passa, não vai morrer'"},
{etapa:"escala", d:"⚠ TÉCNICA RESPIRATÓRIA — inspirar 4s + segurar 4s + expirar lento 6s (técnica 4-4-6)"},
{etapa:"escala", d:"⚠ NÃO USAR saco de papel — risco hipoxia em causa orgânica oculta (mito perigoso)"},
{etapa:"escala", d:"⚠ MEDICAÇÃO em crise REFRATÁRIA à abordagem comportamental:"},
{etapa:"escala", d:"LORAZEPAM 1-2 mg SL ou VO OU diazepam 5-10 mg VO", do:"1-2 mg (loraz) ou 5-10 mg (diaz)", via:"SL/VO", o:"Início 10-30 min. NÃO ROTINEIRO — preferir respiração + reasseguramento. Em emergência intensa: aceitável dose única."},
{etapa:"escala", d:"PA ELEVADA durante crise: reativa, NORMALIZA com melhora do pânico. ⚠ NÃO usar captopril SL rotineiro"},
{etapa:"adj", d:"⚠ TRATAMENTO CRÔNICO — após estabilização e diagnóstico confirmado"},
{etapa:"adj", d:"⚠ ISRS 1ª LINHA — começar BAIXO (½ a ¼ da dose habitual)"},
{etapa:"adj", d:"SERTRALINA 25 mg/d × 1 sem, depois 50 mg/d, titular a 50-200 mg/d", do:"50-200 mg/d", via:"VO", o:"⚠ Pacientes com pânico são EXTREMAMENTE SENSÍVEIS a efeitos colaterais — começar muito baixo. Pode AUMENTAR ansiedade nas 2 primeiras semanas."},
{etapa:"adj", d:"OU PAROXETINA 5-10 mg/d, titular a 20-40 mg/d", do:"20-40 mg/d", via:"VO", o:"Eficácia comprovada em pânico, mas síndrome de descontinuação forte."},
{etapa:"adj", d:"OU ESCITALOPRAM 5 mg/d × 1 sem, depois 10-20 mg/d", do:"10-20 mg/d", via:"VO", o:""},
{etapa:"adj", d:"OU VENLAFAXINA XR 37,5-225 mg/d", do:"37,5-225 mg/d", via:"VO", o:"Alternativa em ISRS-refratário."},
{etapa:"adj", d:"⚠ BENZODIAZEPÍNICO — uso TRANSITÓRIO (2-4 sem) durante início de ISRS"},
{etapa:"adj", d:"⚠ Vantagem: alívio rápido enquanto ISRS faz efeito (2-3 sem)"},
{etapa:"adj", d:"⚠ Risco: dependência, abstinência. SUSPENDER gradualmente após estabilização com ISRS"},
{etapa:"adj", d:"Clonazepam 0,5-1 mg 12/12h OU lorazepam 0,5-1 mg 8/8h", do:"0,5-1 mg 8-12/12h", via:"VO", o:"Limitar uso. Plano claro de suspensão."},
{etapa:"adj", d:"⚠ TCC — INTERVENÇÃO ESPECÍFICA PARA PÂNICO"},
{etapa:"adj", d:"Exposição interoceptiva (induzir sensações físicas controladas), exposição a situações evitadas, reestruturação cognitiva"},
{etapa:"adj", d:"Eficácia comparável a ISRS, com benefício mais duradouro"},
{etapa:"alta", d:"⚠ DURAÇÃO TRATAMENTO: 12-24 MESES após remissão"},
{etapa:"alta", d:"⚠ Reduzir GRADUALMENTE (10-20% a cada 2-4 sem). Recaída em ~50% — manter por longo tempo em paciente com recidivas."},
{etapa:"alta", d:"⚠ EVITAR cafeína, álcool, nicotina (gatilhos comuns)"},
{etapa:"alta", d:"Exercício aeróbico regular — melhora resposta a tratamento"},
{etapa:"alta", d:"Mindfulness, yoga, técnicas de relaxamento"},
{etapa:"alta", d:"ENCAMINHAR PSIQUIATRIA: refratariedade, agorafobia grave, comorbidade complexa, dependência de BZD instalada"},
],
alertas:[
{nivel:"crit", txt:"⚠ PRIMEIRA CRISE — EXCLUIR causa orgânica: IAM, TEP, hipoglicemia, feocromocitoma, abstinência, uso de estimulantes. Confiar em diagnóstico de pânico só após investigação."},
{nivel:"warn", txt:"⚠ PACIENTES COM PÂNICO são MUITO SENSÍVEIS a efeitos colaterais de ISRS — começar com ½ ou ¼ da dose habitual e titular muito lentamente."},
{nivel:"warn", txt:"⚠ ISRS pode AGRAVAR ansiedade nas 2 primeiras semanas — orientar paciente, oferecer BZD transitório, NÃO suspender."},
{nivel:"warn", txt:"BZD em pânico: papel limitado a 2-4 semanas durante início de ISRS. Risco de dependência alto neste perfil de paciente. Plano claro de suspensão."},
{nivel:"warn", txt:"PA ELEVADA durante crise é REATIVA — normaliza com melhora do pânico. NÃO usar captopril SL rotineiro como 'tratamento de crise hipertensiva'."},
{nivel:"info", txt:"TCC com exposição interoceptiva é tratamento DE PRIMEIRA LINHA — efeito duradouro, sem risco de dependência."},
{nivel:"info", txt:"DURAÇÃO: 12-24 meses após remissão. Recaída em ~50%. Manter mais tempo em paciente com recidivas."},
],
fluxo:null, diretriz:"DSM-5-TR; NICE Panic; ABP."
},
{
  id:"sind-psicotica", sis:"psiq", grav:"alta",
  nome:"Síndrome Psicótica Aguda",
  sin:["psicose","surto psicótico","esquizofrenia","delírio"],
  def:"Delírios + alucinações + alteração do pensamento. 1º episódio = ↑investigação orgânica (orgânica até prova contrária).",
  exames:["Excluir orgânica: HGT, eletrólitos, função renal/hepática, TSH, B12, sífilis, HIV","TC crânio em primeiro episódio com red flags","Toxicológico"],
  rx:[
    {etapa:"escala", d:"Haloperidol",do:"2,5–5 mg IM, repetir 30 min",via:"IM",o:"Antipsicótico típico clássico. Risco SEP."},
    {etapa:"escala", d:"Olanzapina",do:"10 mg IM",via:"IM",o:"Atípico injetável. NÃO associar a BZD IV (depressão respiratória)."},
    {etapa:"escala", d:"Risperidona",do:"1–2 mg VO/VL",via:"VO",o:"Quando colaborativo."},
    {etapa:"escala", d:"Quetiapina",do:"25–100 mg VO",via:"VO",o:"Útil em idoso (menos SEP)."},
    {etapa:"escala", d:"Prometazina",do:"25–50 mg IM",via:"IM",o:"Adjuvante — sedativo + ↓SEP do haloperidol."},
  ],
  alertas:[
    {t:"warn",x:"Risco de síndrome neuroléptica maligna (rara mas grave): febre + rigidez + ↑CK + disautonomia. Suspender antipsicótico, suporte, dantroleno."},
  ],
  fisio:"Hiperatividade dopaminérgica na via mesolímbica (sintomas positivos) + hipoatividade na mesocortical (negativos).",
  mec:[
    {d:"Haloperidol",x:"<strong>Antagonista D2</strong> (típico) — alta afinidade. Risco SEP, ↑prolactina."},
    {d:"Olanzapina/Risperidona/Quetiapina",x:"<strong>Antagonistas D2 + 5-HT2A</strong> (atípicos) — menor SEP."},
  ],
  diretriz:"ABP; APA.",
  calcs:[],
},
{id:"tag", nome:"Transtorno de Ansiedade Generalizada (TAG) — manejo ambulatorial", sis:"psiq", grav:"baixa",
cid:"F41.1", ciap:"P74",
sin:["TAG","Ansiedade generalizada","ISRS ansiedade","Ansiedade crônica","GAD-7"],
def:"⚠ Transtorno caracterizado por ANSIEDADE EXCESSIVA + PREOCUPAÇÃO INCONTROLÁVEL >6 MESES sobre múltiplos eventos, com ≥3 sintomas físicos/cognitivos (DSM-5-TR). Diferenciar de ansiedade situacional, transtorno de pânico, depressão ansiosa, causas orgânicas (hipertireoidismo, feocromocitoma). Tratamento ambulatorial — ISRS/ISRSN + TCC.",
quadro:["⚠ Preocupação EXCESSIVA + INCONTROLÁVEL por >6 meses sobre múltiplos eventos","≥3 sintomas (1 em criança): inquietação, fadigabilidade, dificuldade de concentração, irritabilidade, tensão muscular, alterações de sono","Funcionamento prejudicado","⚠ DIFERENCIAR: pânico (crises agudas episódicas), TOC (obsessões/compulsões), depressão (humor predominante), transtorno de adaptação (<6m), causa orgânica","COMORBIDADE FREQUENTE: depressão (40-60%), outros transtornos ansiosos, abuso de substância"],
diag:["DSM-5-TR — clínico","GAD-7: 0-4 (mínima); 5-9 (leve); 10-14 (moderada); ≥15 (grave). ≥10 sugere TAG.","⚠ DESCARTAR CAUSA ORGÂNICA: hipertireoidismo, anemia, feocromocitoma, hipoglicemia, abstinência, uso de estimulantes (cafeína, descongestionantes), corticoide, broncodilatador"],
exames:["TSH","Hemograma","Glicemia","Em quadro atípico: metanefrinas, ECG, eletrólitos"],
rx:[
{etapa:"escala", d:"⚠ TRATAMENTO 1ª LINHA — TCC + ISRS/ISRSN"},
{etapa:"escala", d:"⚠ TCC isolada — em ansiedade LEVE ou paciente que recusa fármaco", o:"Eficácia equivalente a fármaco em LEVE. Útil em gestante."},
{etapa:"escala", d:"⚠ ISRS — começa BAIXO (¼ a ½ da dose habitual de depressão) e titular lento"},
{etapa:"escala", d:"SERTRALINA 25 mg/d × 1 sem, depois 50 mg/d, titular a 100-200 mg/d", do:"50-200 mg/d", via:"VO", o:"⚠ Cuidado nas primeiras 2 sem — pode AUMENTAR ansiedade transitoriamente. Orientar paciente."},
{etapa:"escala", d:"OU ESCITALOPRAM 5 mg/d × 1 sem, depois 10-20 mg/d", do:"10-20 mg/d", via:"VO", o:""},
{etapa:"escala", d:"OU PAROXETINA 10 mg/d, titular a 20-40 mg/d", do:"20-40 mg/d", via:"VO", o:"Eficaz em ansiedade. Maior potencial de descontinuação e ganho de peso."},
{etapa:"escala", d:"⚠ ISRSN — VENLAFAXINA XR 75-225 mg/d (alternativa, eficaz em TAG)", do:"75-225 mg/d XR", via:"VO", o:"⚠ Pode aumentar PA — monitor PA. Síndrome de descontinuação forte."},
{etapa:"escala", d:"⚠ DURATIVA 30-120 mg/d em TAG", do:"30-120 mg/d", via:"VO", o:"Boa em comorbidade dor crônica / fibromialgia."},
{etapa:"escala", d:"⚠ REAVALIAR 4-6 semanas — efeito ansiolítico do ISRS é GRADUAL"},
{etapa:"adj", d:"⚠ BENZODIAZEPÍNICO — USO TRANSITÓRIO em ansiedade aguda intensa"},
{etapa:"adj", d:"⚠ MÁXIMO 2-4 SEMANAS — risco DEPENDÊNCIA, tolerância, abstinência. NÃO ROTINEIRO em TAG."},
{etapa:"adj", d:"Clonazepam 0,5-2 mg/d ÷ 12/12h OU diazepam 5-10 mg 8/8h (mais sedação)", o:"Limitar a curto prazo (início de ISRS, crise aguda). NÃO PROLONGAR."},
{etapa:"adj", d:"⚠ NUNCA INICIAR BZD em paciente com história de DEPENDÊNCIA / álcool / drogas"},
{etapa:"adj", d:"⚠ EVITAR EM IDOSO — Beers Criteria — risco quedas, delirium, dependência, demência"},
{etapa:"adj", d:"⚠ BUSPIRONA 15-60 mg/d ÷ 8/8h — ansiolítico NÃO BZD, sem dependência, sem sedação", do:"15-60 mg/d", via:"VO", o:"Início lento (2-4 sem). Alternativa em paciente com histórico de dependência."},
{etapa:"adj", d:"⚠ PROPRANOLOL 10-40 mg PRN — para ANSIEDADE DE PERFORMANCE / sintomas adrenérgicos (tremor, palpitação)", o:"Não trata ansiedade global, apenas componente físico em situação específica (apresentação, prova)."},
{etapa:"adj", d:"⚠ COMORBIDADE INSÔNIA: mirtazapina 15-30 mg à noite OU adicionar tratamento específico de insônia (ver patologia 'insônia')"},
{etapa:"alta", d:"⚠ MEDIDAS NÃO-FARMACOLÓGICAS — eficazes e bem evidenciadas"},
{etapa:"alta", d:"⚠ EXERCÍCIO AERÓBICO regular (30 min, 4-5×/sem) — eficácia comparável a ISRS em leve-moderada"},
{etapa:"alta", d:"REDUÇÃO DE CAFEÍNA, álcool, nicotina"},
{etapa:"alta", d:"HIGIENE DO SONO"},
{etapa:"alta", d:"⚠ MINDFULNESS / meditação — evidência crescente, eficácia comparável a TCC em alguns estudos"},
{etapa:"alta", d:"YOGA, técnicas de relaxamento, respiração diafragmática"},
{etapa:"alta", d:"⚠ DURAÇÃO TRATAMENTO: 1 ano após remissão. Recaída comum — manter mais tempo em paciente com recidiva prévia."},
{etapa:"alta", d:"ENCAMINHAR PSIQUIATRIA: refratariedade, comorbidade complexa, suspeita de transtorno bipolar, dependência de BZD instalada (precisa esquema de retirada)"},
],
alertas:[
{nivel:"crit", txt:"⚠ NÃO INICIAR / NÃO PROLONGAR BENZODIAZEPÍNICO em TAG crônica. Uso máximo 2-4 sem em transição. Dependência, tolerância, demência (em idoso), prejuízo cognitivo."},
{nivel:"warn", txt:"⚠ ISRS PODE AUMENTAR ANSIEDADE nas PRIMEIRAS 2 SEMANAS — orientar paciente para persistir, NÃO suspender. Iniciar com dose baixa (¼ a ½) e titular."},
{nivel:"warn", txt:"⚠ INVESTIGAR CAUSAS ORGÂNICAS antes de diagnóstico TAG: hipertireoidismo, feocromocitoma, abstinência (álcool, BZD), uso de estimulantes."},
{nivel:"warn", txt:"VENLAFAXINA pode AUMENTAR PA — monitor PA em paciente hipertenso. Maior em doses >150 mg/d."},
{nivel:"info", txt:"⚠ EXERCÍCIO AERÓBICO regular tem eficácia COMPARÁVEL a ISRS em ansiedade leve-moderada — sempre recomendar."},
{nivel:"info", txt:"⚠ PROPRANOLOL é para ANSIEDADE DE PERFORMANCE pontual, não para TAG crônica. Bloqueia sintomas físicos (tremor, taquicardia) mas não trata o transtorno."},
{nivel:"info", txt:"⚠ GAD-7 ≥10 sugere TAG; útil para rastreamento e monitorização."},
],
fluxo:null, diretriz:"DSM-5-TR; NICE Anxiety; ABP. GAD-7 validado pt-BR."
},
{id:"tentativa-suicidio", sis:"psiq", grav:"alta",
nome:"Tentativa de Suicídio / Ideação Aguda",
sin:["tentativa de suicídio","ideação suicida","autolesão"],
def:"Comportamento autolesivo intencional com intenção de morrer OU ideação suicida estruturada (plano + método + intenção). Avaliar SEMPRE: ideação, plano, intenção, acesso a método letal, tentativa prévia, fatores de risco.",
exames:["Avaliação clínica completa do método","Toxicologia (paracetamol, salicilatos, etanol)","Eletrólitos, função renal, hepática","ECG (se intoxicação)","Beta-HCG mulher fértil"],
rx:[
{etapa:"inicial", d:"ESTABILIZAR clínica",do:"Tratar lesões/intoxicação conforme método",via:"—",o:"PRIMEIRO clinicamente, depois psiquiatria. ABCDE."},
{etapa:"escala", d:"PROTEGER paciente",do:"Acompanhante 1:1, ambiente seguro (sem objetos cortantes/cordas/medicações)",via:"—",o:"Equipe de enfermagem orientada. Reduzir estímulos."},
{etapa:"escala", d:"AVALIAÇÃO PSIQUIÁTRICA",do:"Avaliação por psiquiatra/psicólogo (Resolução CFM)",via:"—",o:"OBRIGATÓRIA. Determina: alta com plano de segurança vs. internação voluntária vs. involuntária (laudo médico)."},
{etapa:"escala", d:"INTERNAÇÃO INVOLUNTÁRIA",do:"Comunicar MP em até 72h (Lei 10.216/2001)",via:"—",o:"Indicações: ideação ativa + plano + acesso meios; tentativa de alta letalidade; falta de suporte; comorbidade psiquiátrica grave."},
{etapa:"escala", d:"Plano de segurança (se alta)",do:"Identificar sinais alarme + estratégias enfrentamento + acionar suporte + limitar meios + serviços emergência",via:"—",o:"Modelo Stanley-Brown. Família orientada. Retirar armas/medicações de casa."},
{etapa:"escala", d:"Encaminhamento",do:"CAPS / consulta psiquiátrica em ≤7 dias",via:"—",o:"Continuidade do cuidado é fator protetor mais robusto."},
],
alertas:[
{t:"crit",x:"ACOLHA SEM JULGAMENTO. Perguntar diretamente sobre ideação NÃO induz comportamento — falta de pergunta sim."},
{t:"crit",x:"FATORES DE ALTO RISCO: tentativa prévia, plano estruturado, acesso a arma, álcool/drogas, depressão grave, psicose, idoso H solitário, dor crônica, doença terminal, perda recente."},
{t:"warn",x:"Período pós-alta é de ALTO RISCO (especialmente 1ª semana). Garantir consulta em 24-72h, plano de segurança escrito."},
{t:"info",x:"CVV 188 (24h, gratuito). CAPS-AD se comorbidade com substância. SAMU 192 transporte."},
],
fisio:"Multifatorial: transtorno mental (depressão 60%, dependência química, esquizofrenia, transtornos de personalidade), fatores biológicos (serotonina, neuroinflamação), psicossociais (perda, isolamento, dor, doença), genéticos (família). É manifestação de SOFRIMENTO + ↓capacidade de tolerar — não 'fraqueza' nem 'manipulação'.",
mec:[],
diretriz:"MS — Diretrizes para um Modelo Brasileiro de Prevenção do Suicídio (Portaria 1.876/2006). CFM 2.057/2013. WHO LIVE LIFE 2021. Lei 13.819/2019 (notificação compulsória).",
fluxo:null,
calcs:[],
},
);
