/* ===========================================================
   VOVÔMINIC EMERGÊNCIA — pat/resp.js
   13 patologias
   Sistemas: resp
   =========================================================== */

PATOLOGIAS.push(

/* ============== RESP (13) ============== */

{
  id: "asma", contexto:["pa"], sis: "resp", grav: "alta",
  nome: "Crise Asmática",
  sin: ["asma", "asma aguda", "broncoespasmo", "crise asmática"],
  def: "Dispneia, sibilos, opressão torácica, tosse + ↑uso musc. acessória. Gravidade por: fala, FR, FC, SpO₂, PFE, alteração de consciência.",
  exames: ["Oximetria + monitorização", "PFE pré e pós-tratamento (% predito)", "Gasometria arterial se grave/sem resposta", "RX tórax se febre, dor torácica, suspeita de pneumotórax/PNM", "Hemograma, PCR se infecção"],
  rx: [
    {etapa:"inicial", d:"Avaliação inicial + PFE",do:"Posição sentada + monitorização + PFE pré-tratamento",via:"—",o:"PFE quantifica gravidade. >70%: leve. 40-69%: moderada. <40%: grave. Repetir após 1h."},
    {etapa:"inicial", d:"O₂ titular SpO₂ 93-95%",do:"Cateter/máscara conforme",via:"—",o:"NÃO O₂ rotineiro alto fluxo. Excesso piora V/Q. Em pediatria: alvo 94-98%."},
    {etapa:"escala", d:"① β2-agonista — Salbutamol nebulizado",do:"5 mg (1 mL) em 3 mL SF, repetir 3× a cada 20 min na 1ª hora",via:"NBZ",o:"1ª LINHA. Ou spray 4-8 jatos com espaçador (equivalente). Contínua em grave: 10-15 mg/h."},
    {etapa:"escala", d:"② Anticolinérgico — Ipratrópio",do:"0,5 mg (40 gotas) JUNTO ao salbutamol",via:"NBZ",o:"Aditivo em moderada/grave nas primeiras 3 doses. Sinergia com β2."},
    {etapa:"escala", d:"③ Corticoide sistêmico — Prednisona",do:"40-60 mg VO dose única, manter 5-7 dias",via:"VO",o:"INICIAR PRECOCEMENTE — efeito em 4-6h. SEMPRE em moderada/grave. Sem desmame se ≤14 dias."},
    {etapa:"escala", d:"③ Corticoide — Metilprednisolona IV (se VO impossível)",do:"1-2 mg/kg IV",via:"IV",o:"Equivalência: 1 mg metilpred = 1,25 mg prednisona. Não é melhor que VO se tolerar."},
    {etapa:"escala", d:"④ Sulfato de magnésio (grave refratária)",do:"2 g IV em 100 mL SF em 20 min",via:"IV",o:"Crise grave refratária a β2 + corticoide. Pediatria: 25-50 mg/kg (máx 2 g)."},
    {etapa:"escala", d:"⑤ Adrenalina (parada iminente)",do:"0,3-0,5 mg IM (1:1000)",via:"IM",o:"Refratário, anafilaxia associada, parada respiratória iminente. Repetir 5-15 min."},
    {etapa:"escala", d:"⑥ IOT — Indutor: Cetamina (broncodilatadora)",do:"Cetamina 1-2 mg/kg IV",via:"IV",o:"PREFERIDO em asma — broncodilatador. Evitar histamino-liberadores (morfina). Preparar VM com ↑tempo expiratório."},
    {etapa:"adj", d:"Hidratação adequada",do:"SF/RL conforme volemia",via:"IV",o:"Evitar tanto hipovolemia (aumenta espessamento secreção) quanto sobrecarga."},
    {etapa:"adj", d:"NÃO usar: antibiótico rotineiro, mucolíticos, sedativos",do:"Sem benefício, podem piorar",via:"—",o:"ATB apenas se infecção bacteriana documentada. Sedativos contraindicados (deprimem ventilação)."},
    {etapa:"alta", d:"Manejo de manutenção",do:"Corticoide inalatório ± LABA + plano de ação",via:"INH",o:"Reavaliar técnica inalatória. Gatilhos. Vacinação. Acompanhamento pneumo."},
  ],
  alertas: [
    { t: "crit", x: "Sinais de iminência de parada respiratória: bradipneia, ↓consciência, silêncio à ausculta, cianose. IOT preparada. Ketamina como indutor (broncodilatadora)." },
    { t: "warn", x: "Manter SpO₂ 93–95% (94–98% em crianças, GINA 2024). Excesso de O₂ pode piorar V/Q." },
    { t: "info", x: "PFE >70% = leve; 40–69% = moderada; <40% = grave; <25% = muito grave." },
  ],
  fisio: "A asma é uma doença inflamatória crônica das vias aéreas com hiper-responsividade brônquica. Na crise, há (1) <strong>broncoespasmo do músculo liso brônquico</strong>, (2) <strong>edema da mucosa</strong> e (3) <strong>hipersecreção de muco viscoso</strong>. A inflamação é predominantemente eosinofílica (mediada por Th2/IL-4/IL-5/IL-13). O fluxo aéreo expiratório é limitado, gerando aprisionamento aéreo, hiperinsuflação dinâmica e ↑trabalho respiratório. A hipoxemia decorre do distúrbio V/Q; em fases avançadas, hipercapnia indica fadiga muscular respiratória (sinal de gravidade).",
  mec: [
    { d: "Salbutamol", x: "<strong>Agonista β2-seletivo</strong> — ativa adenilato ciclase → ↑AMPc → relaxamento do músculo liso brônquico. Início em 5 min, pico 30–60 min, duração 4–6h. Efeitos colaterais: tremor, taquicardia, hipocalemia, hiperglicemia." },
    { d: "Ipratrópio", x: "<strong>Antagonista muscarínico M3</strong> nos brônquios — bloqueia o tônus vagal broncoconstritor. Sinergismo com β2-agonista (mecanismos complementares)." },
    { d: "Corticoides (prednisona, metilprednisolona)", x: "Glicocorticoides — <strong>inibem fosfolipase A2 e transcrição de citocinas inflamatórias</strong>, reduzem eosinófilos, ↑expressão de β2-receptores. Início de efeito clínico em 4–6h." },
    { d: "Sulfato de magnésio", x: "<strong>Bloqueia entrada de Ca²⁺</strong> nas células musculares lisas brônquicas → relaxamento. Também inibe degranulação de mastócitos." },
  ],
  diretriz: "GINA 2024 — Global Initiative for Asthma (ginasthma.org/2024-report). SBPT — Recomendações para o Manejo da Asma Grave 2021 (J Bras Pneumol 47:e20210273). PCDT-Asma MS 2024.",
  fluxo: null,
  calcs: [],
},
{id:"asma-cronica", contexto:["pa","ubs"], nome:"Asma crônica — manejo ambulatorial GINA 2025", sis:"resp", grav:"baixa",
cid:"J45", ciap:"R96",
sin:["Asma","Asma alérgica","Asma persistente","Bombinha","Asma controle","GINA"],
def:"Doença inflamatória crônica das VA caracterizada por HIPER-RESPONSIVIDADE BRÔNQUICA + obstrução variável e reversível. Tratamento atual GINA 2025 abandona SABA isolado — todos pacientes usam ICS-formoterol (MART/SMART) como estratégia preferida. Foco em CONTROLE de sintomas + redução de RISCO futuro (exacerbação, perda de função pulmonar).",
quadro:["Sintomas episódicos: sibilância, dispneia, opressão torácica, TOSSE — piora à noite/manhã","Gatilhos: exercício, alérgenos (ácaro, pelos, pólen), IVAS, frio, fumaça, AINEs","HISTÓRIA pessoal/familiar de ATOPIA (rinite, eczema, alergia)","Resposta a broncodilatador em prova terapêutica","⚠ DDX: DPOC (>40a, tabagismo, irreversível), bronquiectasia, ICC, RGE com tosse"],
diag:["CLÍNICA — sintomas característicos + variabilidade","ESPIROMETRIA com prova broncodilatadora: VEF1/CVF baixo + reversibilidade (Δ VEF1 ≥12% e 200 mL pós-BD)","Em criança <5a: clínica + prova terapêutica","PEAK FLOW seriado: variabilidade >10% adulto, >13% criança"],
exames:["ESPIROMETRIA pré e pós-BD","PEAK FLOW (importante para automonitorização)","Em casos atípicos/graves: IgE total, IgE específicas, FeNO, eosinófilos, RX tórax (excluir DDX)"],
rx:[
{etapa:"escala", d:"⚠ ESCADA GINA 2025 (adultos e adolescentes) — TRACK 1 PREFERIDA: ICS-formoterol como reliever (MART)"},
{etapa:"escala", d:"⚠ DEGRAU 1-2 (sintomas <2×/sem)"},
{etapa:"escala", d:"Budesonida + formoterol 200/6 mcg DPI 1 inalação CONFORME NECESSÁRIO (PRN)", do:"1 inalação PRN", via:"INH", o:"Substitui o antigo SABA isolado. Anti-inflamatório + broncodilatador conforme necessário."},
{etapa:"escala", d:"OU Beclometasona + formoterol 100/6 mcg PRN"},
{etapa:"escala", d:"⚠ DEGRAU 3 (sintomas >2×/sem)"},
{etapa:"escala", d:"Budesonida + formoterol 200/6 mcg DPI — 1 inalação 1-2×/d FIXO + PRN (MART)", do:"1-2 inal fixo/d + PRN", via:"INH"},
{etapa:"escala", d:"⚠ DEGRAU 4 (sintomas frequentes / função pulmonar reduzida)"},
{etapa:"escala", d:"Budesonida + formoterol 200/6 mcg — 2 inalações 2×/d FIXO + PRN", do:"2 inal 2×/d + PRN", via:"INH"},
{etapa:"escala", d:"⚠ DEGRAU 5 (asma grave / refratária) — referenciar pneumologia"},
{etapa:"escala", d:"Dose alta de ICS-formoterol + LAMA (tiotrópio) + considerar biológicos (anti-IgE: omalizumabe; anti-IL5: mepolizumabe, benralizumabe; anti-IL4/13: dupilumabe)"},
{etapa:"adj", d:"⚠ TRACK 2 (alternativa em <12a ou paciente que não aceita MART)"},
{etapa:"adj", d:"ICS DOSE BAIXA + SABA (salbutamol) PRN — modelo clássico"},
{etapa:"adj", d:"Budesonida 200 mcg DPI 1 inal 2×/d + salbutamol PRN"},
{etapa:"adj", d:"OU fluticasona 250 mcg DPI 1 inal 2×/d + salbutamol PRN"},
{etapa:"adj", d:"⚠ CRIANÇA 6-11a — esquemas adaptados"},
{etapa:"adj", d:"Degrau 1-2: ICS baixa dose + SABA PRN ou ICS-formoterol PRN (preferido)"},
{etapa:"adj", d:"Degrau 3-4: ICS dose média + LABA ou ICS-formoterol MART"},
{etapa:"adj", d:"⚠ CRIANÇA <5a — particularidades"},
{etapa:"adj", d:"Espaçador SEMPRE (sem nebulizador rotineiro em ambulatório)"},
{etapa:"adj", d:"Budesonida 200 mcg ESPAÇADOR 1 puff 2×/d (degrau 2)"},
{etapa:"adj", d:"Ou fluticasona 50-125 mcg 2×/d"},
{etapa:"adj", d:"+ salbutamol PRN espaçador"},
{etapa:"adj", d:"⚠ TÉCNICA INALATÓRIA — ESSENCIAL revisar em cada consulta"},
{etapa:"adj", d:"DPI (pó seco): inspiração rápida e profunda"},
{etapa:"adj", d:"MDI: inspiração LENTA e profunda + retenção 10s"},
{etapa:"adj", d:"ESPAÇADOR sempre em criança <12a + idoso + erro de coordenação"},
{etapa:"adj", d:"⚠ MEDIDAS NÃO-FARMACOLÓGICAS"},
{etapa:"adj", d:"CONTROLE DE GATILHOS: ácaros (capa antiácaro, sol no colchão), pólen, pelos, fumaça, AINEs"},
{etapa:"adj", d:"VACINAÇÃO: influenza anual, pneumocócica, COVID-19, RSV (>60a)"},
{etapa:"adj", d:"CESSAÇÃO TABAGISMO (asma + tabagismo = grave)"},
{etapa:"adj", d:"PESO ADEQUADO (obesidade piora asma)"},
{etapa:"adj", d:"EXERCÍCIO regular (com pré-medicação se asma do esforço)"},
{etapa:"adj", d:"⚠ PLANO DE AÇÃO POR ESCRITO"},
{etapa:"adj", d:"VERDE (controlada): manter medicação"},
{etapa:"adj", d:"AMARELO (piora): aumentar ICS-formoterol PRN + considerar ICS-formoterol 4×/d × 7-14 dias"},
{etapa:"adj", d:"VERMELHO (crise): salbutamol + prednisona + procurar PA"},
{etapa:"alta", d:"AVALIAR CONTROLE em CADA consulta — questionário ACT (>20 controlada)"},
{etapa:"alta", d:"⚠ CONSIDERAR DESCALONAMENTO após 3 meses bem controlada (manter degrau mais baixo eficaz)"},
{etapa:"alta", d:"ENCAMINHAR PNEUMOLOGIA: degrau 4-5, exacerbações recorrentes (>2/ano), falência de controle, dúvida diagnóstica"},
{etapa:"alta", d:"⚠ ATENÇÃO: SABA EM EXCESSO (>3 frascos/ano) = mau controle, risco de morte. Reavaliar tratamento"},
],
alertas:[
{nivel:"crit", txt:"⚠ GINA 2025 ABANDONA SABA ISOLADO — todos pacientes >12a usam ICS-formoterol PRN (não salbutamol isolado). Reduziu mortalidade. Track 1 é preferida."},
{nivel:"crit", txt:"USO DE SABA >3 frascos de salbutamol/ano = MAU CONTROLE. Risco aumentado de exacerbação grave e morte. Reavaliar imediatamente."},
{nivel:"warn", txt:"TÉCNICA INALATÓRIA é o erro mais comum — revisar A CADA consulta. Espaçador sempre em criança, idoso, dúvida."},
{nivel:"warn", txt:"AINE pode desencadear crise grave em asma com pólipos (Samter triad). História cuidadosa."},
{nivel:"warn", txt:"CESSAÇÃO TABAGISMO em asma é prioritária — paciente que continua fumando tem perda acelerada de função e refratariedade ao ICS."},
{nivel:"info", txt:"BIOLÓGICOS (omalizumabe, mepolizumabe, dupilumabe) em asma grave refratária — pneumologia especializada."},
{nivel:"info", txt:"PLANO DE AÇÃO POR ESCRITO reduz internações em 30-50%. Deve estar em mãos do paciente."},
],
fluxo:"fluxo-asma", diretriz:"GINA 2025. SBPT. Diretriz Brasileira de Asma."
},
{
  id: "dpoc", contexto:["pa","ubs"], sis: "resp", grav: "alta",
  nome: "DPOC — Exacerbação",
  sin: ["DPOC", "dpoc agudizado", "enfisema", "bronquite", "exacerbação"],
  def: "Piora aguda da dispneia, escarro (volume/purulência) em portador de DPOC. Critérios de Anthonisen: ↑dispneia, ↑volume escarro, ↑purulência (≥2 → considerar ATB).",
  exames: ["Oximetria + gasometria arterial (define VNI)", "RX tórax (PNM, PNT, congestão)", "ECG", "Hemograma, eletrólitos, função renal", "BNP se diagnóstico diferencial com ICC", "Hemoculturas se febre"],
  rx: [
    { etapa:"inicial", d: "Salbutamol nebulizado", do: "5 mg em 3 mL SF, 3× a cada 20 min na 1ª hora", via: "Nebulização", o: "Pode ser contínuo em grave. Em hipercapnia: preferir spray com espaçador (menor risco de retenção de CO₂)." },
    { etapa:"escala", d: "Ipratrópio nebulizado", do: "0,5 mg junto ao salbutamol", via: "Nebulização", o: "Sinérgico." },
    { etapa:"escala", d: "Prednisona", do: "40 mg VO/d × 5 dias (sem desmame)", via: "VO", o: "Reduz falência terapêutica e tempo de internação (REDUCE trial)." },
    { etapa:"atb", d: "Amoxicilina-clavulanato", do: "875/125 mg 12/12h × 5–7 dias", via: "VO", o: "Se Anthonisen ≥2 ou necessidade de VNI/VM." },
    { etapa:"atb", d: "Azitromicina", do: "500 mg/d × 3–5 dias", via: "VO", o: "Alternativa em alergia. Atypicals." },
    { etapa:"escala", d: "VNI (BiPAP)", do: "IPAP 12–15, EPAP 5, FiO₂ p/ SpO₂ 88–92%", via: "Máscara", o: "Indicação: pH <7,35 + pCO₂ >45. Reduz IOT em 60%." },
    { etapa:"inicial", d: "Oxigenoterapia controlada", do: "Cateter nasal 1–3 L/min ou Venturi 24–28%", via: "—", o: "ALVO SpO₂ 88–92%. Excesso de O₂ → ↓drive respiratório e hipercapnia." },
  ],
  alertas: [
    { t: "crit", x: "Sinais de IOT: pH <7,25 sustentado mesmo com VNI, parada/fadiga respiratória, ↓consciência, instabilidade hemodinâmica." },
    { t: "warn", x: "ALVO SpO₂ 88–92% (não 95–100%). Hiperóxia pode causar acidose respiratória e mortalidade em DPOC." },
  ],
  fisio: "A DPOC tem dois fenótipos: <strong>bronquite crônica</strong> (hipersecreção + inflamação) e <strong>enfisema</strong> (destruição alveolar com perda de elastância). Na exacerbação, infecção viral/bacteriana (50–70%) ou poluição/inflamação aumenta o broncoespasmo, edema, secreção → <strong>hiperinsuflação dinâmica + auto-PEEP</strong> → ↑trabalho respiratório → fadiga muscular → hipercapnia → acidose respiratória. Diferente da asma, há limitação fixa ao fluxo aéreo + componente neutrofílico (não eosinofílico).",
  mec: [
    { d: "Salbutamol + Ipratrópio", x: "Broncodilatação por mecanismos complementares (β2-agonista + antagonista M3)." },
    { d: "Prednisona", x: "↓Inflamação brônquica; benefício no DPOC menor que na asma (componente eosinofílico pequeno) mas significativo." },
    { d: "Amoxicilina-clavulanato", x: "Aminopenicilina + inibidor de β-lactamase — cobre Haemophilus, Moraxella, S. pneumoniae produtor de β-lactamase." },
    { d: "VNI (BiPAP)", x: "<strong>IPAP</strong> assiste a inspiração (↓trabalho respiratório, ↑VC, ↓PaCO₂); <strong>EPAP</strong> mantém alvéolos abertos e contrabalança a auto-PEEP." },
  ],
  diretriz: "GOLD 2024 Report — Global Initiative for Chronic Obstructive Lung Disease (goldcopd.org). SBPT — Manual de DPOC 2024 (Pereira LFF et al.).",
  imgs: [
    {src:"https://upload.wikimedia.org/wikipedia/commons/3/36/X-ray_of_COPD_exacerbation_-_anteroposterior_view.jpg",
     alt:"RX tórax com hiperinsuflação em DPOC",
     caption:"DPOC — hiperinsuflação pulmonar, retificação diafragmática, alargamento dos espaços intercostais.",
     source:"Wikimedia Commons / Mikael Häggström (CC0)"},
  ],
  fluxo: null,
  calcs: [],
},
{id:"dpoc", contexto:["pa","ubs"], nome:"DPOC — diagnóstico e manejo GOLD 2025", sis:"resp", grav:"moderada",
cid:"J44", ciap:"R95",
sin:["DPOC","Doença pulmonar obstrutiva crônica","Enfisema","Bronquite crônica","Bombeiro","GOLD","Pulmão de fumante"],
def:"DPOC = doença pulmonar progressiva caracterizada por LIMITAÇÃO de fluxo aéreo NÃO totalmente reversível, associada à RESPOSTA INFLAMATÓRIA anormal a partículas/gases nocivos (tabagismo principalmente, biomassa, ocupacional). Tratamento atual GOLD 2025 estratifica por sintomas (mMRC, CAT) + risco de exacerbação (grupos A/B/E).",
quadro:["Tosse crônica + expectoração + DISPNEIA progressiva, em paciente >40a com história de tabagismo (>10 maços-ano)","Outros: biomassa (lenha doméstica em mulheres rurais), exposição ocupacional (poeiras, vapores)","DEFICIÊNCIA DE α-1-ANTITRIPSINA (<5%, considerar em jovens, não-fumantes, distribuição lobar inferior)","Sintomas progressivos: dispneia ao esforço → dispneia em repouso, exacerbações","⚠ DDX: asma (variável, reversível), ICC, bronquiectasia, TB sequelar"],
diag:["ESPIROMETRIA PÓS-BD — DIAGNÓSTICA: VEF1/CVF <0,70","ESTAGIAMENTO GOLD por VEF1 pós-BD: 1 leve (≥80%), 2 moderado (50-79%), 3 grave (30-49%), 4 muito grave (<30%)","GRUPOS A/B/E baseados em sintomas (mMRC, CAT) + exacerbações no último ano","mMRC: 0 (sem dispneia) a 4 (dispneia mínimo esforço)","CAT (COPD Assessment Test): 0-40"],
exames:["ESPIROMETRIA pré e pós-BD — confirma diagnóstico","RX TÓRAX: hiperinsuflação, retificação das cúpulas diafragmáticas (não diagnóstico)","TC TÓRAX: se atípico, suspeita bronquiectasia, avaliar enfisema","α-1-AT: em jovens, não-fumantes","ECG, gasometria, função renal, hemograma (excluir comorbidades)"],
rx:[
{etapa:"escala", d:"⚠ GOLD 2025 — TRATAMENTO POR GRUPO"},
{etapa:"escala", d:"⚠ GRUPO A (sintomas leves, sem/poucas exacerbações)"},
{etapa:"escala", d:"BRONCODILATADOR de longa duração — LABA ou LAMA"},
{etapa:"escala", d:"Tiotrópio 18 mcg DPI 1 inal/d (preferido em A) OU formoterol 12 mcg 12/12h"},
{etapa:"escala", d:"⚠ GRUPO B (mais sintomático, sem/poucas exacerbações)"},
{etapa:"escala", d:"LABA + LAMA — combinação dupla"},
{etapa:"escala", d:"Indacaterol/glicopirrônio 110/50 mcg 1×/d OU vilanterol/umeclidínio 25/62,5 mcg 1×/d OU formoterol/aclidínio 12/400 mcg 2×/d"},
{etapa:"escala", d:"⚠ GRUPO E (exacerbador — ≥2 moderadas/ano OU ≥1 grave que internou) — independente sintomas"},
{etapa:"escala", d:"LABA + LAMA (dupla)"},
{etapa:"escala", d:"Considerar LABA + LAMA + ICS (TRIPLA) se: eosinófilos sangue ≥300/μL OU eosinófilos 100-300 + exacerbações OU asma-DPOC sobreposta"},
{etapa:"escala", d:"Ex tripla: vilanterol/umeclidínio/fluticasona furoato 25/62,5/100 mcg 1×/d (Trelegy)"},
{etapa:"adj", d:"⚠ ICS em DPOC — INDICAÇÕES (não rotineiro)"},
{etapa:"adj", d:"Eosinófilos ≥300/μL (marcador de resposta ao ICS)"},
{etapa:"adj", d:"Exacerbações recorrentes ≥2/ano + eos ≥100"},
{etapa:"adj", d:"Asma-DPOC overlap"},
{etapa:"adj", d:"NÃO INDICAR ICS isolado em DPOC (sempre com LABA-LAMA)"},
{etapa:"adj", d:"⚠ ICS aumenta RISCO PNEUMONIA em DPOC — avaliar risco-benefício"},
{etapa:"adj", d:"⚠ SABA / SAMA — broncodilatador de RESGATE"},
{etapa:"adj", d:"Salbutamol MDI 100 mcg PRN, 1-2 puffs 4-6/d"},
{etapa:"adj", d:"Ipratrópio (Atrovent) MDI 20 mcg PRN — alternativa, especialmente em paciente com taquicardia"},
{etapa:"adj", d:"⚠ MEDIDAS NÃO-FARMACOLÓGICAS — MORE IMPORTANT THAN DRUGS"},
{etapa:"adj", d:"⚠ CESSAÇÃO TABAGISMO — ÚNICA medida que ALTERA HISTÓRIA NATURAL"},
{etapa:"adj", d:"VACINAÇÃO: influenza anual + pneumocócica (PCV13+PPV23) + COVID-19 + RSV + dTPa (uma vez)"},
{etapa:"adj", d:"REABILITAÇÃO PULMONAR — eficaz em mMRC ≥2: melhora função, qualidade de vida, reduz dispneia"},
{etapa:"adj", d:"⚠ OXIGENOTERAPIA DOMICILIAR — INDICAÇÕES"},
{etapa:"adj", d:"PaO₂ ≤55 mmHg em repouso (em ar ambiente, paciente estável)"},
{etapa:"adj", d:"OU PaO₂ 56-59 mmHg + cor pulmonale OU hematócrito >55%"},
{etapa:"adj", d:"Uso ≥15h/dia (idealmente 24h) — melhora sobrevida em hipoxemia crônica"},
{etapa:"adj", d:"⚠ NUTRIÇÃO — caquexia em DPOC avançada"},
{etapa:"adj", d:"Suporte nutricional + suplemento calórico, força muscular respiratória"},
{etapa:"adj", d:"⚠ MUCOLÍTICOS — N-ACETILCISTEÍNA 600 mg 2×/d em paciente com expectoração + exacerbações recorrentes, evidência modesta"},
{etapa:"adj", d:"⚠ MACROLÍDEO PROFILÁTICO — azitromicina 250 mg 3×/sem em paciente com exacerbações recorrentes apesar de tratamento otimizado, pneumologia especializada"},
{etapa:"alta", d:"⚠ ROFLUMILASTE (inibidor PDE4) 500 mcg 1×/d — paciente com bronquite crônica + VEF1 <50% + exacerbações recorrentes apesar de LABA-LAMA-ICS"},
{etapa:"alta", d:"⚠ ACOMPANHAMENTO REGULAR — sintomas, exacerbações, função pulmonar 1×/ano, técnica inalatória, adesão, comorbidades"},
{etapa:"alta", d:"COMORBIDADES FREQUENTES: ICC, CAD, depressão, osteoporose, sarcopenia, DM, câncer pulmão (rastrear se >50a, ≥20 maços-ano)"},
{etapa:"alta", d:"⚠ EXACERBAÇÃO: aumentar SABA/SAMA + corticoide oral (prednisona 40 mg × 5 dias) + ATB se purulência (amoxicilina+clavulanato OU azitromicina × 5-7 dias)"},
{etapa:"alta", d:"ENCAMINHAR PNEUMOLOGIA: exacerbações frequentes, suspeita asma-DPOC overlap, função muito reduzida, hipoxemia, candidato a transplante"},
],
alertas:[
{nivel:"crit", txt:"CESSAÇÃO TABAGISMO é a ÚNICA MEDIDA que altera história natural — não apenas reduz exacerbações, mas DESACELERA a perda de VEF1. Toda consulta de DPOC deve abordar tabagismo."},
{nivel:"crit", txt:"OXIGENOTERAPIA DOMICILIAR (≥15h/d): aumenta SOBREVIDA em hipoxemia crônica. Critérios estritos — PaO₂ ≤55 ou ≤59 + complicação."},
{nivel:"warn", txt:"⚠ ICS em DPOC NÃO É ROTINEIRO — apenas em paciente com eosinófilos altos, exacerbações recorrentes ou ACO. ICS isolado SEM LABA-LAMA é ERRO."},
{nivel:"warn", txt:"⚠ ICS aumenta RISCO PNEUMONIA em DPOC. Avaliar risco-benefício."},
{nivel:"warn", txt:"⚠ BRONCODILATADORES de LONGA são PILAR — SABA isolado NÃO basta em DPOC sintomática. Iniciar LABA ou LAMA precocemente."},
{nivel:"warn", txt:"DEFICIÊNCIA α-1-AT: pensar em DPOC em JOVEM, NÃO-FUMANTE, com distribuição enfisematosa basal. Dosar α-1-AT sérica."},
{nivel:"info", txt:"REABILITAÇÃO PULMONAR (exercício + educação + nutrição) é altamente eficaz mas SUBUTILIZADA. Reduz dispneia, aumenta tolerância, reduz exacerbações."},
{nivel:"info", txt:"RASTREAR CÂNCER DE PULMÃO em fumante 50-80a com ≥20 maços-ano: TC tórax baixa dose anual (USPSTF)."},
],
fluxo:null, diretriz:"GOLD 2025. SBPT. Diretriz Brasileira DPOC."
},
{
  id: "epistaxe", contexto:["pa","ubs"], sis: "resp", grav: "media",
  nome: "Epistaxe",
  sin: ["sangramento nasal", "epistaxe"],
  def: "Sangramento nasal. Anterior (90%, área de Kiesselbach) ou posterior (mais grave). Causa: trauma, ressecamento, HAS, anticoagulação, coagulopatia.",
  exames: ["Sinais vitais", "Hemograma, coagulograma se anticoagulado/recorrente", "Rinoscopia anterior"],
  rx: [
    { etapa:"inicial", d: "Compressão digital", do: "Pinçar narinas 10–15 min sem soltar, inclinado para frente", via: "—", o: "1ª medida em TODOS. Eficaz em 80%." },
    { etapa:"escala", d: "Oximetazolina spray", do: "2 jatos cada narina", via: "Intranasal", o: "Vasoconstritor. Pode aplicar em algodão e introduzir." },
    { etapa:"adj", d: "Ácido tranexâmico tópico", do: "500 mg em algodão embebido + tamponamento 10 min", via: "Tópico", o: "Útil em pacientes anticoagulados." },
    { etapa:"escala", d: "Tamponamento anterior", do: "Gaze vaselinada ou tampão expansível por 24–48h", via: "—", o: "Falha de medidas iniciais." },
    { etapa:"atb", d: "Tamponamento posterior", do: "Sonda Foley + tampão anterior", via: "—", o: "Sangramento posterior. Hospitalização. ATB profilático (síndrome do choque tóxico)." },
  ],
  alertas: [
    { t: "warn", x: "HAS é fator agravante, não causa primária — controlar PA, mas tratar a fonte do sangramento." },
  ],
  fisio: "Plexo de Kiesselbach (anterior) é vascularizado por anastomose de várias artérias e é o sítio mais comum (95% das epistaxes). Trauma seco, baixa umidade, hipertensão, anticoagulação e antiagregação contribuem. Epistaxe posterior (artéria esfenopalatina) é mais grave, mais frequente em idosos e mais difícil de controlar.",
  mec: [
    { d: "Ácido tranexâmico", x: "Análogo da lisina — bloqueia o sítio de ligação do plasminogênio à fibrina, <strong>inibindo a fibrinólise</strong>. Estabiliza coágulo." },
    { d: "Oximetazolina", x: "α1-agonista — vasoconstrição local." },
  ],
  diretriz: "AAO-HNS Clinical Practice Guideline: Nosebleed (Tunkel DE et al., Otolaryngol Head Neck Surg 2020;162:S1–S38).",
  fluxo: null,
  calcs: [],
},
{
  id: "faringo", contexto:["pa","ubs"], sis: "resp", grav: "baixa",
  nome: "Faringoamigdalite",
  sin: ["faringite", "amigdalite", "garganta", "estrepto"],
  def: "Dor de garganta ± febre + exsudato amigdaliano + adenopatia cervical. Diferenciar viral (90%) de estreptocócica (Centor/McIsaac).",
  exames: ["Critérios de Centor/McIsaac", "Strep test rápido se disponível", "Cultura de orofaringe se necessário"],
  rx: [
    { etapa:"atb", d: "Penicilina G benzatina", do: "1.200.000 UI IM dose única (<27kg: 600.000 UI)", via: "IM", o: "1ª linha. Único ATB que comprova prevenção de febre reumática." },
    { etapa:"atb", d: "Amoxicilina", do: "500 mg VO 8/8h × 10 dias (crianças 50 mg/kg/d)", via: "VO", o: "Alternativa quando não há disponibilidade IM." },
    { etapa:"atb", d: "Azitromicina", do: "500 mg/d × 5 dias", via: "VO", o: "Alergia a penicilina." },
    { etapa:"adj", d: "Analgesia", do: "Dipirona/paracetamol/ibuprofeno", via: "VO", o: "Sintomático." },
  ],
  alertas: [
    { t: "warn", x: "Suspeitar mononucleose (EBV) em adolescentes: febre, faringite exsudativa, adenopatia cervical posterior, hepatoesplenomegalia. AAS amox → rash em 90%." },
  ],
  fisio: "Estreptococo β-hemolítico do grupo A (S. pyogenes) — bacteriana mais comum, causa de febre reumática e glomerulonefrite pós-estreptocócica se não tratada. Viral: rinovírus, coronavírus, adenovírus, influenza, EBV, CMV.",
  mec: [
    { d: "Penicilina G", x: "Inibe PBPs (parede)." },
  ],
  diretriz: "IDSA — Clinical Practice Guideline for the Diagnosis and Management of Group A Streptococcal Pharyngitis (Shulman ST et al., CID 2012;55:e86–e102, DOI:10.1093/cid/cis629).",
  fluxo: null,
  calcs: ["centor"],
},
{id:"hemoptise", contexto:["pa","ubs"], sis:"resp", grav:"alta",
nome:"Hemoptise Maciça",
sin:["hemoptise","sangramento pulmonar"],
def:"Eliminação de sangue pela boca proveniente da via aérea (laringe/traqueia/brônquios/parênquima). Maciça: >200-600 mL/24h OU instabilidade hemodinâmica/respiratória. MORTALIDADE 50-80% maciça não tratada — risco PRINCIPAL é asfixia, não hipovolemia.",
exames:["RX/TC tórax + angio-TC (definir sítio + etiologia)","HMG, coag, função renal, gaso","Tipagem + reserva CH","Broncoscopia (diagnóstica + terapêutica)"],
rx:[
{etapa:"inicial", d:"POSICIONAR — decúbito LATERAL do lado SANGRANTE para baixo",do:"Se o sítio é conhecido",via:"—",o:"PILAR. Protege pulmão são. Se desconhecido — decúbito Trendelenburg (pulmonar)."},
{etapa:"inicial", d:"O₂ + via aérea",do:"IOT se necessário (tubo amplo)",via:"—",o:"Tubo grande (8.0+) para broncoscopia. CONSIDERAR IOT seletiva (Carlens) ou bloqueador brônquico do lado sangrante."},
{etapa:"escala", d:"Suporte hemodinâmico",do:"Cristaloide + CH (tipo O- se urgente)",via:"IV",o:"Reverter anticoagulação se aplicável."},
{etapa:"escala", d:"Ácido tranexâmico",do:"500-1000 mg IV em 10 min OU nebulizado 500 mg",via:"IV/Neb",o:"Reduz sangramento — Cochrane 2020. Pode repetir."},
{etapa:"escala", d:"Broncoscopia rígida",do:"Aspiração + cauterização + tamponamento balão",via:"—",o:"Intervenção precoce em centro especializado."},
{etapa:"escala", d:"Embolização ARTÉRIA BRÔNQUICA",do:"Angiografia + embolização",via:"Endovascular",o:"DEFINITIVO. Sucesso 85-95%. Disponível em centros referência."},
{etapa:"escala", d:"Cirurgia",do:"Lobectomia",via:"Cirúrgico",o:"Falha de embolização, sangramento focal localizado."},
],
alertas:[
{t:"crit",x:"ASFIXIA é a causa de morte, não hipovolemia. PROTEGER via aérea + pulmão são."},
{t:"crit",x:"DECÚBITO LATERAL com sítio sangrante PARA BAIXO. Quando se sabe o lado, isso pode salvar a vida."},
{t:"warn",x:"Etiologia em BR: tuberculose ativa/sequela (bronquiectasia, aspergiloma na cavitação), bronquiectasia, neoplasia, micetoma, vasculite, anticoag/anti-plaq, TEP."},
{t:"info",x:"Hemoptise volumosa em paciente jovem feminina = arteriovenosa pulmonar (Osler-Weber-Rendu)?"},
],
fisio:"90% origem em artéria brônquica (alta pressão, sistêmica) — não em circulação pulmonar (baixa pressão). Causas: erosão por inflamação crônica (TB, bronquiectasia), ruptura aneurisma de Rasmussen (TB cavitária), neoplasia, infarto pulmonar (TEP). Anastomoses bronco-pulmonares aumentam em doença crônica.",
mec:[
{d:"Ácido tranexâmico",x:"Antifibrinolítico — análogo lisina, bloqueia sítios de ligação do plasminogênio. ↓dissolução do coágulo, permite hemostasia local."},
],
diretriz:"BTS Guidelines on Hemoptysis. CHEST Guidelines.",
fluxo:null, calcs:[],
},
{
  id: "oma", contexto:["pa","ubs"], sis: "resp", grav: "baixa",
  nome: "Otite Média Aguda (OMA)",
  sin: ["OMA", "otite", "otalgia"],
  def: "Otalgia + abaulamento timpânico + sinais de inflamação + início <48h. Diferenciar de otite externa (dor à tração tragal) e otite secretora.",
  exames: ["Otoscopia (abaulamento, hiperemia, opacificação)"],
  rx: [
    { etapa:"atb", d: "Amoxicilina", do: "50 mg/kg/d divididos 8/8h × 7–10 dias", via: "VO", o: "1ª linha. Adultos 500 mg 8/8h ou 875 mg 12/12h." },
    { etapa:"atb", d: "Amoxicilina-clavulanato", do: "50 mg/kg/d (amox) × 10 dias", via: "VO", o: "Falha em 48–72h, <2a, otite recorrente, conjuntivite associada, uso recente de ATB." },
    { etapa:"atb", d: "Ceftriaxona", do: "50 mg/kg IM × 1–3 dias", via: "IM", o: "Vômitos / não-aderência. Dose única adultos: 1–2 g." },
    { etapa:"adj", d: "Analgesia", do: "Paracetamol/dipirona/ibuprofeno", via: "VO", o: "Mesmo se observação sem ATB (≥2a, leve, otoscopia duvidosa)." },
  ],
  alertas: [
    { t: "warn", x: "Mastoidite (dor retroauricular + abaulamento + febre) é emergência — TC + ceftriaxona IV + ORL." },
  ],
  fisio: "A disfunção da tuba auditiva (geralmente após IVAS) cria pressão negativa na orelha média → transudação → meio de cultura para bactérias colonizadoras (S. pneumoniae 30–40%, H. influenzae não-tipável 25%, Moraxella catarrhalis 15%). Em crianças, a tuba mais horizontal e curta predispõe.",
  mec: [
    { d: "Amoxicilina", x: "Aminopenicilina — inibe PBPs (peptidoglicano)." },
  ],
  diretriz: "AAP Clinical Practice Guideline: The Diagnosis and Management of Acute Otitis Media (Lieberthal AS et al., Pediatrics 2013;131:e964–e999, DOI:10.1542/peds.2012-3488).",
  fluxo: null,
  calcs: [],
},
{
  id: "pac", contexto:["pa","ubs"], sis: "resp", grav: "media",
  nome: "Pneumonia Adquirida na Comunidade (PAC)",
  sin: ["PAC", "pneumonia", "pneumonia comunitária"],
  def: "Tosse + febre + dispneia/dor pleurítica + crepitação focal + infiltrado novo no RX. CURB-65 estratifica gravidade e sítio de tratamento.",
  exames: ["RX tórax PA + perfil", "Hemograma, PCR/procalcitonina, função renal, eletrólitos, lactato", "Hemoculturas (2 pares) se internação", "Antígeno urinário pneumococo + Legionella se grave", "PCR respiratório viral em pandemia"],
  rx: [
    { etapa:"atb", d: "Amoxicilina", do: "1 g VO 8/8h × 7 dias", via: "VO", o: "Ambulatorial sem comorbidade (CURB-65 0–1)." },
    { etapa:"atb", d: "Amoxicilina-clavulanato + Azitromicina", do: "875/125 mg 12/12h + 500 mg/d × 5 dias", via: "VO", o: "Ambulatorial com comorbidade." },
    { etapa:"atb", d: "Ceftriaxona + Azitromicina", do: "1–2 g IV/d + 500 mg IV/d", via: "IV", o: "Internado, enfermaria (CURB-65 2)." },
    { etapa:"atb", d: "Ceftriaxona + Levofloxacino", do: "2 g IV/d + 750 mg IV/d", via: "IV", o: "UTI (CURB-65 ≥3 ou outros critérios)." },
    { etapa:"atb", d: "Piperacilina-tazobactam ± Vancomicina", do: "4,5 g 6/6h + 15 mg/kg 12/12h", via: "IV", o: "Suspeita Pseudomonas/MRSA: institucionalizado, ATB recente, bronquiectasia, ventilação prévia." },
    { etapa:"atb", d: "Oseltamivir", do: "75 mg VO 12/12h × 5 dias", via: "VO", o: "Influenza em surto/PCR+. Iniciar idealmente em 48h." },
  ],
  alertas: [
    { t: "crit", x: "Sepse: aplicar bundle hour-1 (lactato, hemocultura, ATB <1h, cristaloide, vasopressor)." },
    { t: "info", x: "CURB-65: Confusão / Ureia >50 / FR ≥30 / PA <90×60 / Idade ≥65. 0–1: ambulatorial. 2: enfermaria. ≥3: UTI." },
  ],
  fisio: "PAC = infecção do parênquima pulmonar adquirida em pacientes ambulatoriais. Os patógenos chegam por (1) aspiração de microflora orofaríngea, (2) inalação de aerossol, (3) disseminação hematogênica. Os mais comuns: <strong>S. pneumoniae</strong> (típico, 30%), <strong>Mycoplasma/Chlamydophila/Legionella</strong> (atípicos), <strong>vírus respiratórios</strong> (influenza, SARS-CoV-2). Em CRF grave: + bastonetes Gram-negativos. A inflamação alveolar leva a preenchimento alveolar por exsudato → consolidação visível ao RX. O tratamento ATB deve cobrir típicos + atípicos em pacientes internados.",
  mec: [
    { d: "Amoxicilina / Amox-clav", x: "Aminopenicilinas inibem PBPs (transpeptidação da parede bacteriana). Clavulanato inibe β-lactamases." },
    { d: "Ceftriaxona", x: "Cefalosporina 3ª geração — boa cobertura para pneumococo, H. influenzae, Klebsiella." },
    { d: "Azitromicina", x: "Macrolídeo — liga-se à subunidade <strong>50S do ribossomo bacteriano</strong>, inibindo a translocação na síntese proteica. Cobre atípicos (Mycoplasma, Chlamydophila, Legionella)." },
    { d: "Levofloxacino", x: "Fluoroquinolona — inibe <strong>DNA-girase e topoisomerase IV</strong> bacterianas, impedindo replicação. Cobre típicos + atípicos." },
  ],
  diretriz: "SBPT 2018 — Recomendações para o manejo da PAC (Corrêa RA et al., J Bras Pneumol 2018;44:405–423). ATS/IDSA 2019 (Metlay JP et al., Am J Respir Crit Care Med 2019;200:e45–e67, DOI:10.1164/rccm.201908-1581ST).",
  imgs: [
    {src:"https://upload.wikimedia.org/wikipedia/commons/5/51/X-ray_of_lobar_pneumonia.jpg",
     alt:"RX tórax mostrando pneumonia lobar com consolidação", caption:"Pneumonia lobar — consolidação alveolar densa no lobo inferior direito, com broncograma aéreo.",
     source:"Wikimedia Commons (CC BY-SA)"},
    {src:"https://upload.wikimedia.org/wikipedia/commons/2/20/Chest_X-ray_in_influenza_and_Haemophilus_influenzae.jpg",
     alt:"Consolidação radiológica em pneumonia", caption:"Outro exemplo de consolidação pneumônica.",
     source:"Wikimedia Commons"},
  ],
  fluxo: null,
  calcs: ["curb65"],
},
{
  id: "pneumotorax", contexto:["pa"], sis: "resp", grav: "alta",
  nome: "Pneumotórax / Hemotórax",
  sin: ["pneumotórax", "hemotórax", "PNT"],
  def: "Pneumotórax: ar no espaço pleural — dor torácica súbita + dispneia + hipertimpanismo. Hipertensivo: + hipotensão, desvio traqueal, ↓MV. Hemotórax: sangue no espaço pleural.",
  exames: ["RX tórax PA em pé (hipertransparência sem trama)", "USG point-of-care (ausência de lung sliding, B-lines)", "TC tórax se traumático/loculado", "Hemograma, coagulograma"],
  rx: [
    { etapa:"inicial", d: "Descompressão imediata", do: "Punção 2º EIC linha hemiclavicular OU 4º–5º EIC linha axilar", via: "—", o: "PNT HIPERTENSIVO (instável). Cateter 14G. Drenagem definitiva em seguida." },
    { etapa:"adj", d: "Drenagem torácica em selo d'água", do: "5º EIC linha axilar média, dreno 28–32 Fr", via: "—", o: "PNT >2 cm, sintomático, recidiva, traumatic; hemotórax; derrame complicado. Anestesia local + analgesia." },
    { etapa:"atb", d: "Cefazolina", do: "2 g IV pré-drenagem + 8/8h × 24h", via: "IV", o: "Profilaxia ATB em trauma penetrante." },
    { etapa:"inicial", d: "Conservador", do: "O₂ alto fluxo + observação", via: "—", o: "PNT primário pequeno (<2 cm), assintomático. Reabsorção 1–2%/dia (mais rápido com O₂)." },
  ],
  alertas: [
    { t: "crit", x: "PNT HIPERTENSIVO: diagnóstico CLÍNICO (hipotensão, dispneia grave, ↓MV unilateral, desvio traqueal). NÃO esperar RX — descomprimir imediato." },
  ],
  fisio: "O PNT espontâneo primário ocorre por ruptura de blebs subpleurais (jovens, altos, magros, tabagistas); secundário é complicação de DPOC, asma, TB, fibrose. <strong>Traumático</strong> ocorre por penetração ou contusão. No PNT <strong>hipertensivo</strong>, um mecanismo valvar permite entrada mas não saída de ar — a pressão pleural sobe progressivamente, colaba o pulmão ipsilateral, desvia mediastino e comprime VCS/grandes vasos → ↓retorno venoso → choque obstrutivo. É emergência absoluta.",
  mec: [
    { d: "Drenagem", x: "Remoção mecânica do ar/sangue → restauração da pressão pleural negativa → reexpansão pulmonar." },
    { d: "Oxigenoterapia", x: "↑Pressão parcial de O₂ alveolar → aumenta gradiente para reabsorção pleural (acelera 4×)." },
  ],
  diretriz: "BTS Pleural Disease Guideline 2023 (Roberts ME et al., Thorax 2023;78(Suppl 3):s1–s42). Manual de Trauma ATLS 10ª ed.",
  imgs: [
    {src:"https://upload.wikimedia.org/wikipedia/commons/c/c6/Expired_X-ray_of_pneumothorax.jpg",
     alt:"RX tórax com pneumotórax — expiração",
     caption:"Pneumotórax — RX em expiração: ausência de trama vascular lateralmente, linha pleural visível.",
     source:"Wikimedia Commons / Mikael Häggström (CC0)"},
    {src:"https://upload.wikimedia.org/wikipedia/commons/9/96/Lateral_X-ray_of_pneumothorax_in_inspiration_-_annotated.jpg",
     alt:"RX lateral de pneumotórax com anotação",
     caption:"Visão lateral anotada de pneumotórax.",
     source:"Wikimedia Commons / Mikael Häggström (CC0)"},
  ],
  fluxo: null,
  calcs: [],
},
{
  id: "rino", contexto:["pa","ubs"], sis: "resp", grav: "baixa",
  nome: "Rinossinusite Aguda",
  sin: ["sinusite", "rinossinusite"],
  def: "Sintomas nasais (obstrução, descarga purulenta, dor facial, hiposmia) por <12 sem. Bacteriana se persistir >10 dias OU piorar após 5 dias OU sintomas \"double-sickening\".",
  exames: ["Clínica (>90% diagnóstico). TC apenas em complicações/refratários."],
  rx: [
    { etapa:"atb", d: "Amoxicilina-clavulanato", do: "875/125 mg 12/12h × 7–10 dias", via: "VO", o: "1ª linha em bacteriana." },
    { etapa:"adj", d: "Corticoide intranasal", do: "Mometasona/fluticasona 1–2 sprays cada narina 1×/d", via: "Intranasal", o: "Reduz sintomas. Pode ser monoterapia em casos leves." },
    { etapa:"escala", d: "Lavagem nasal com salina", do: "Solução salina 0,9% várias vezes ao dia", via: "Intranasal", o: "Eficaz em viral + bacteriana." },
  ],
  alertas: [
    { t: "warn", x: "Complicações: celulite orbitária, abscesso periorbitário, trombose de seio cavernoso, meningite. Sinais: edema/eritema periorbital, proptose, oftalmoplegia, sinais meníngeos. TC + ATB IV + ORL." },
  ],
  fisio: "Obstrução do óstio dos seios paranasais (por edema da mucosa, geralmente após viral) → estase de secreção → infecção bacteriana secundária. Agentes: S. pneumoniae, H. influenzae, M. catarrhalis (similares a OMA).",
  mec: [
    { d: "Amoxicilina-clavulanato", x: "Aminopenicilina + inibidor β-lactamase." },
    { d: "Corticoide intranasal", x: "↓Inflamação da mucosa nasal e dos óstios sinusais → melhora drenagem." },
  ],
  diretriz: "EPOS 2020 — European Position Paper on Rhinosinusitis and Nasal Polyps (Fokkens WJ et al., Rhinology 2020;58:1–464).",
  fluxo: null,
  calcs: [],
},
{id:"sdra", contexto:["pa","ubs"], sis:"resp", grav:"alta",
nome:"SDRA / ARDS",
sin:["SDRA","ARDS","Berlin","Síndrome do Desconforto Respiratório Agudo"],
def:"Síndrome inflamatória pulmonar AGUDA — Berlin 2012: início <7 dias + infiltrado bilateral RX/TC + sem evidência de origem cardíaca + hipoxemia. Leve (P/F 200-300, PEEP ≥5), moderada (P/F 100-200), grave (P/F <100).",
exames:["Gaso arterial — calcular P/F","RX/TC tórax","Ecocardiograma (excluir cardiogênico)","HMG + cultura ampla (sepse é causa #1)","BNP, troponina"],
rx:[
{etapa:"escala", d:"Tratar CAUSA",do:"Sepse, pneumonia, aspiração, trauma, transfusão (TRALI), pancreatite",via:"—",o:"PILAR. Sem isso, suporte é apenas paliativo."},
{etapa:"escala", d:"VM PROTETORA (Vt baixo)",do:"Vt 6 mL/kg peso PREDITO + Pplat <30 + driving pressure <15 cmH₂O",via:"VM",o:"ARDSnet — reduz mortalidade. Peso PREDITO (50 + 0,91 × (altura cm - 152,4) H, 45,5 + 0,91 × (altura cm - 152,4) M)."},
{etapa:"escala", d:"PEEP MAIS ALTO",do:"Tabela PEEP/FiO₂ alta (ALVEOLI/EXPRESS)",via:"VM",o:"Mod-grave SDRA. Iniciar 10-12. Titular pela P/F."},
{etapa:"escala", d:"Pronação 16h/d",do:"Posição prona em P/F <150",via:"—",o:"PROSEVA — ↓mortalidade significativamente. Manter 16h/24h, alternando."},
{etapa:"escala", d:"Sedação + curare (BNM)",do:"Sedação profunda + cisatracurio 0,15 mg/kg + 0,3 mg/kg/h",via:"IV",o:"48h em SDRA grave inicial (P/F <120). Reduz mortalidade (ACURASYS). Reavaliar."},
{etapa:"escala", d:"Balanço hídrico negativo",do:"Diurético se euvolêmico + estável",via:"IV",o:"FACTT trial — estratégia conservadora melhora dias livres VM."},
{etapa:"escala", d:"ECMO",do:"VV-ECMO",via:"—",o:"P/F <80 refratário, hipercapnia severa, lesão pulmonar primária reversível. Transferir CENTRO referência."},
{etapa:"adj", d:"NÃO usar — não recomendado",do:"Corticoide rotineiro, surfactante exógeno, β2 alta dose",via:"—",o:"Sem benefício. Corticoide em SDRA por COVID/pneumonia tem evidência (RECOVERY)."},
],
alertas:[
{t:"crit",x:"VM PROTETORA é a única intervenção MORTALIDADE-REDUTORA com evidência sólida. Vt baixo + Pplat baixo SEMPRE — mesmo com 'rebote' de PCO₂ ('permissive hypercapnia')."},
{t:"crit",x:"Pronação NÃO É opcional em P/F <150 — é intervenção de UTI básica em SDRA moderado-grave."},
{t:"warn",x:"Diferencial: SDRA vs edema agudo cardiogênico — ECO + BNP + resposta a diurético. SDRA pode coexistir com IC."},
],
fisio:"Lesão alveolar difusa por estímulo direto (pneumonia, aspiração, contusão, inalação) ou indireto (sepse, pancreatite, transfusão, choque). Fase exsudativa (D1-7): edema rico em proteína + dano endotelial/epitelial + membranas hialinas. Fase proliferativa (D7-21): tentativa de reparo. Fase fibrótica (>21d): fibrose pulmonar.",
mec:[
{d:"Cisatracurio",x:"Bloqueador neuromuscular — antagonista nicotínico competitivo. Eliminação Hofmann (não-renal, não-hepática) — ideal em UTI."},
],
diretriz:"Berlin Definition (ARDS Definition Task Force, JAMA 2012;307:2526). ARDSnet (NEJM 2000;342:1301). PROSEVA (Guérin C et al., NEJM 2013;368:2159). ESICM/ATS/SCCM 2017 (Fan E et al., Am J Respir Crit Care Med 2017;195:1253, DOI:10.1164/rccm.201703-0548ST).",
fluxo:null, calcs:[],
},
{
  id: "tb", contexto:["pa","ubs"], sis: "resp", grav: "media",
  nome: "Tuberculose Pulmonar",
  sin: ["TB", "tuberculose"],
  def: "Tosse ≥3 sem + febre vespertina, sudorese noturna, emagrecimento, hemoptise. Considerar em todo paciente com PNM atípica ou \"sintomas respiratórios\".",
  exames: ["RX tórax (cavitação em ápice, miliar)", "BAAR no escarro × 2 (manhãs consecutivas)", "TRM-TB (GeneXpert) — diagnóstico + resistência à rifampicina em 2h", "Cultura para micobactérias + TS", "HIV (sempre)", "Função hepática e renal antes do esquema"],
  rx: [
    { etapa:"escala", d: "Esquema RIPE", do: "RHZE coformulado: <50kg 2 cp; 50–70kg 3 cp; >70kg 4 cp — uma vez/dia em jejum", via: "VO", o: "Fase intensiva 2 meses. Composição (por cp): R 150 / H 75 / Z 400 / E 275 mg." },
    { etapa:"escala", d: "Manutenção RH", do: "RH coformulado por mais 4 meses", via: "VO", o: "Total 6 meses em PAS comum. 12 meses em meningite ou óssea." },
    { etapa:"adj", d: "Piridoxina (B6)", do: "50 mg/d", via: "VO", o: "Profilaxia de neuropatia por isoniazida em gestante, lactante, DM, etilista, IRC, HIV." },
    { etapa:"adj", d: "Corticoide", do: "Prednisona 1 mg/kg/d × 4–8 sem", via: "VO", o: "Em meningite tuberculosa e pericardite TB." },
  ],
  alertas: [
    { t: "warn", x: "Hepatotoxicidade do RHZE: monitorar AST/ALT. Suspender se TGO/TGP >3× ULN com sintomas ou >5× ULN sem sintomas." },
    { t: "info", x: "Notificação compulsória. Iniciar tratamento mesmo com BAAR/TRM-TB negativo se clínica e RX compatíveis (sob orientação de pneumologia/SCIH)." },
  ],
  fisio: "<em>Mycobacterium tuberculosis</em>, bacilo aeróbio estrito, é transmitido por aerossol. Após inalação, é fagocitado por macrófagos alveolares; sua parede rica em ácidos micólicos resiste à destruição. Inicia infecção primária com formação de granuloma (resposta Th1/IFN-γ/TNF-α) que contém a infecção em 95% dos casos. <strong>Reativação</strong> ocorre em condições de imunossupressão (HIV, DM, corticoide, desnutrição, idade) → cavitação preferencial em ápices pulmonares (ricos em O₂) e disseminação. Sem tratamento, mortalidade 50%.",
  mec: [
    { d: "Rifampicina", x: "Inibe <strong>RNA-polimerase DNA-dependente bacteriana</strong>, bloqueando síntese de RNA. Bactericida. Indutor potente de CYP450 (interações). Urina/lágrimas avermelhadas." },
    { d: "Isoniazida (H)", x: "Pró-droga — ativada pela <strong>catalase-peroxidase (KatG)</strong> bacteriana; inibe a síntese de <strong>ácidos micólicos</strong> (componente único da parede micobacteriana). Bactericida em divisão." },
    { d: "Pirazinamida (Z)", x: "Pró-droga ativada em meio ácido intracelular (pH <6) pela pirazinamidase; mecanismo final envolve disrupção de membrana e síntese proteica. Ativa em macrófagos." },
    { d: "Etambutol (E)", x: "Inibe <strong>arabinosil-transferase</strong>, bloqueando síntese de arabinogalactano da parede. Bacteriostático. Toxicidade: neurite óptica." },
  ],
  diretriz: "Manual de Recomendações para o Controle da Tuberculose no Brasil (MS, 2ª ed. 2019). WHO Consolidated Guidelines on Tuberculosis 2022.",
  imgs: [
    {src:"https://upload.wikimedia.org/wikipedia/commons/9/9c/Tuberculosis-x-ray-1.jpg",
     alt:"RX de tórax com cavitação apical bilateral",
     caption:"TB pulmonar bilateral — infiltrado heterogêneo nos ápices com cavitações.",
     source:"Wikimedia Commons (Domínio público)"},
  ],
  fluxo: null,
  calcs: [],
},
);
