/* ===========================================================
   VOVÔMINIC EMERGÊNCIA — pat/tox-pec.js
   19 patologias
   Sistemas: pec, tox
   =========================================================== */

PATOLOGIAS.push(

/* ============== PEC (7) ============== */

{id:"araneismo", sis:"pec", grav:"media",
nome:"Araneísmo",
sin:["aranha","Loxosceles","Phoneutria","viúva-negra"],
def:"Picada de aranha. 3 gêneros relevantes no Brasil: <strong>Loxosceles</strong> (marrom — necrose), <strong>Phoneutria</strong> (armadeira — dor intensa), <strong>Latrodectus</strong> (viúva-negra — síndrome muscular).",
exames:["Hemograma, função renal, urina (hemólise em Loxosceles cutâneo-visceral)","CK"],
rx:[
{etapa:"escala", d:"LOXOSCELES — SAAr (Soro Antiaracnídico)",do:"MODERADO/GRAVE: 5–10 ampolas IV",via:"IV",o:"Indicação: forma cutâneo-visceral (hemólise, IRA) OU lesão extensa. Eficácia incerta em forma cutânea pura."},
{etapa:"escala", d:"LOXOSCELES — Prednisona",do:"40–60 mg/d × 5 dias",via:"VO",o:"Forma cutânea."},
{etapa:"adj", d:"PHONEUTRIA — SAAr",do:"MODERADO: 2–4 / GRAVE: 5–10 ampolas",via:"IV",o:"Adultos com manifestação local apenas: analgesia geralmente suficiente."},
{etapa:"adj", d:"PHONEUTRIA — Analgesia",do:"Bloqueio com lidocaína 1% + dipirona + opioide",via:"Local/IV",o:"Dor extrema."},
{etapa:"escala", d:"LATRODECTUS — Soro antilatrodéctico",do:"1–2 ampolas IM",via:"IM",o:"Forma moderada/grave (cãibras generalizadas, abdome em tábua)."},
{etapa:"escala", d:"LATRODECTUS — Gluconato Ca + BZD",do:"10 mL IV + diazepam 10 mg",via:"IV",o:"Espasmos."},
],
alertas:[{t:"warn",x:"Loxosceles cutâneo-visceral (mais em crianças): hemólise + IRA → mortalidade significativa. Vigiar urina e Hb."}],
fisio:"Loxosceles: esfingomielinase D → dermonecrose + hemólise. Phoneutria: toxinas neurotóxicas em canais de Na/Ca → liberação massiva de neurotransmissores → dor intensa. Latrodectus: α-latrotoxina → liberação maciça de ACh.",
mec:[],
diretriz:"MS/Butantan 2001 (2017).",
calcs:[],
},
{id:"botropico", sis:"pec", grav:"alta",
nome:"Acidente Botrópico (Jararaca)",
sin:["jararaca","botrópico","Bothrops"],
def:"Acidente mais comum no Brasil. Veneno proteolítico/coagulante/hemorrágico — dor, edema, equimose, sangramento sistêmico, coagulopatia.",
exames:["Tempo de coagulação (TC) — alterado em coagulopatia","Hemograma, função renal, CK","RX local"],
rx:[
{etapa:"escala", d:"SAB (Soro Antibotrópico)",do:"LEVE: 2–4 ampolas IV / MODERADO: 4–8 / GRAVE: 12 ampolas",via:"IV",o:"Diluir em 250 mL SF, infundir em 30 min. NÃO administrar pré-medicação rotineira."},
{etapa:"escala", d:"Hidratação",do:"SF 1–2 mL/kg/h",via:"IV",o:"Manter diurese >1 mL/kg/h — prevenir IRA."},
{etapa:"adj", d:"Analgesia",do:"Dipirona + opioide",via:"IV",o:"NÃO usar AINE (sangramento) nem corticoide rotineiro."},
{etapa:"escala", d:"Antitetânica",do:"dT/IGHAT",via:"IM",o:"Após correção do TC."},
{etapa:"escala", d:"ATB",do:"Amox-clav OU clinda + cefalosporina",via:"IV/VO",o:"Apenas se infecção secundária — não profilático."},
],
alertas:[
{t:"crit",x:"Reação anafilática ao soro: parar infusão + adrenalina IM + corticoide + anti-H1. Reiniciar mais lento."},
{t:"warn",x:"Se TC ainda alterado em 24h após soro: dose adicional."},
],
fisio:"Veneno do gênero Bothrops com toxinas proteolíticas (necrose local), coagulantes (consumo de fibrinogênio → CIVD), hemorrágicas (hemorraginas — lesão endotelial).",
mec:[{d:"SAB",x:"Imunoglobulinas heterólogas que neutralizam toxinas circulantes. Não reverte dano já estabelecido."}],
diretriz:"MS/Butantan — Manual de Diagnóstico e Tratamento de Acidentes por Animais Peçonhentos 2001 (reimpressão 2017).",
calcs:[],
},
{id:"crotalico", sis:"pec", grav:"alta",
nome:"Acidente Crotálico (Cascavel)",
sin:["cascavel","crotálico","Crotalus"],
def:"Veneno neurotóxico (fácies miastênica) + miotóxico (rabdomiólise → urina escura) + coagulante. MAIOR LETALIDADE entre serpentes brasileiras.",
exames:["CK (rabdomiólise — pode atingir >100.000)","Função renal","Eletrólitos (hipercalemia)","Urina (mioglobinúria)","TC","Hemograma"],
rx:[
{etapa:"escala", d:"SAC (Soro Anticrotálico)",do:"LEVE: 5 ampolas / MODERADO: 10 / GRAVE: 20 ampolas",via:"IV",o:"Diluir + 30 min de infusão."},
{etapa:"escala", d:"Hidratação vigorosa",do:"SF 2–3 mL/kg/h, manter diurese >1–2 mL/kg/h",via:"IV",o:"PROTEÇÃO RENAL. Alvo: urina clara."},
{etapa:"escala", d:"Bicarbonato",do:"Alvo pH urinário >6,5",via:"IV",o:"Alcalinização para prevenir nefrotoxicidade da mioglobina."},
{etapa:"escala", d:"Manitol",do:"0,5 g/kg IV",via:"IV",o:"Em rabdomiólise grave (CK >5000)."},
{etapa:"escala", d:"Diálise",do:"—",via:"—",o:"IRA estabelecida."},
],
alertas:[{t:"crit",x:"Insuficiência respiratória por bloqueio neuromuscular → IOT precoce."}],
fisio:"Veneno do gênero Crotalus contém crotoxina (neurotoxina pré-sináptica — bloqueia liberação de ACh), giroxina (coagulante) e fração nefrotóxica.",
mec:[{d:"SAC",x:"Neutraliza crotoxina e demais frações."}],
diretriz:"MS/Butantan 2001 (2017).",
calcs:[],
},
{id:"elapidico", sis:"pec", grav:"alta",
nome:"Acidente Elapídico (Coral Verdadeira)",
sin:["coral","elapídico","Micrurus"],
def:"Coral verdadeira (Micrurus). Veneno neurotóxico pós-sináptico → paralisia flácida ascendente progressiva → IR respiratória.",
exames:["Clínico — sintomas neurológicos","Gasometria"],
rx:[
{etapa:"escala", d:"SAE (Soro Antielapídico)",do:"10 ampolas IV (dose única para todos)",via:"IV",o:"TODOS sintomáticos = grave."},
{etapa:"escala", d:"IOT preventiva",do:"Considerar mesmo com déficit leve",via:"—",o:"Progressão rápida da paralisia."},
{etapa:"escala", d:"Suporte ventilatório",do:"VM",via:"—",o:"Pode durar dias até regeneração de receptores."},
{etapa:"escala", d:"Neostigmina",do:"0,05 mg/kg IV + atropina 0,01 mg/kg",via:"IV",o:"Útil em coral norte-americana e algumas brasileiras (M. corallinus)."},
],
alertas:[{t:"crit",x:"Risco de PCR por paralisia diafragmática. Internar em UTI imediatamente."}],
fisio:"α-neurotoxinas se ligam aos receptores nicotínicos da placa motora (pós-sinápticos) → bloqueio competitivo → paralisia flácida ascendente.",
mec:[
{d:"SAE",x:"Anticorpos heterólogos que neutralizam as toxinas circulantes."},
{d:"Neostigmina",x:"<strong>Inibidor de acetilcolinesterase</strong> → ↑ACh disponível para competir com a toxina."},
],
diretriz:"MS/Butantan 2001 (2017).",
calcs:[],
},
{id:"escorpionismo", sis:"pec", grav:"alta",
nome:"Escorpionismo",
sin:["escorpião","Tityus","escorpionismo"],
def:"Picada de escorpião amarelo (T. serrulatus) ou marrom (T. bahiensis). Dor INTENSA local. Crianças/idosos: risco de complicação cardiovascular/pulmonar grave.",
exames:["ECG (taquicardia, arritmia, alterações de repolarização)","Glicemia, eletrólitos (K, Mg, Ca)","CK-MB, troponina","RX/ecocardiograma se grave","Amilase (pancreatite)"],
rx:[
{etapa:"escala", d:"SAEEsc (Soro Antiescorpiônico)",do:"MODERADO: 2–3 ampolas / GRAVE: 4–6 ampolas",via:"IV",o:"Diluir + 30 min infusão. Em adulto picado moderado: pode dispensar soro."},
{etapa:"adj", d:"Analgesia",do:"Dipirona + opioide (morfina/tramadol) + lidocaína 1% infiltração local",via:"IV/Local",o:"Dor pode ser extrema."},
{etapa:"adj", d:"Antieméticos",do:"Ondansetrona 4–8 mg IV",via:"IV",o:"Vômitos são comuns."},
{etapa:"escala", d:"Suporte cardiovascular",do:"Diurético, vasodilatador, IOT, vasopressor conforme caso",via:"IV",o:"Edema pulmonar/miocardite — UTI."},
],
alertas:[{t:"crit",x:"CRIANÇA <7a com picada de T. serrulatus = sempre grave até prova contrária. Vigilância em UTI."}],
fisio:"Toxinas de Tityus abrem canais de Na⁺ voltagem-dependentes → liberação maciça de catecolaminas e ACh → tempestade autonômica. Em crianças predomina simpático → edema pulmonar, miocardite, choque.",
mec:[{d:"SAEEsc",x:"Neutraliza toxinas Ts1, Ts2, etc."}],
diretriz:"MS/Butantan 2001 (2017).",
calcs:[],
},
{id:"laquetico", sis:"pec", grav:"alta",
nome:"Acidente Laquético (Surucucu)",
sin:["surucucu","laquético","Lachesis"],
def:"Lachesis muta — Amazônia/Mata Atlântica. Síndrome botrópica + componente vagal (bradicardia, hipotensão, diarreia, cólica).",
exames:["Como botrópico","ECG (bradicardia)"],
rx:[
{etapa:"escala", d:"SABL (Soro Antibotrópico-Laquético)",do:"MODERADO: 10 ampolas / GRAVE: 20 ampolas",via:"IV",o:"Diluir + 30 min de infusão."},
{etapa:"escala", d:"Atropina",do:"0,5–1 mg IV",via:"IV",o:"Para bradicardia/síndrome vagal."},
{etapa:"adj", d:"Hidratação + analgesia",do:"Como botrópico",via:"IV",o:""},
],
alertas:[{t:"warn",x:"Síndrome vagal pode mascarar gravidade — vigilância contínua."}],
fisio:"Veneno com efeitos botrópicos + neurotoxina vagal (bradicardia, hipotensão, hipersecreção).",
mec:[],
diretriz:"MS/Butantan 2001 (2017).",
calcs:[],
},
{id:"mordedura", sis:"pec", grav:"media",
nome:"Mordedura Humana / Animal",
sin:["mordedura","cão","gato","raiva"],
def:"Ferida por mordida. Risco infeccioso alto (humana 25%, cão 15%, gato 50%). Risco de raiva em mamíferos silvestres/desconhecidos.",
exames:["RX se trauma profundo","Cultura se infectada"],
rx:[
{etapa:"inicial", d:"Lavagem abundante",do:"Água + sabão por 15 min",via:"—",o:"PILAR. NÃO suturar primária (exceto face)."},
{etapa:"atb", d:"Amoxicilina-clavulanato",do:"875/125 mg VO 12/12h × 5–7 dias",via:"VO",o:"Profilaxia: face, mão, articulação, imunossupressão, diabético, todas as humanas e felinas."},
{etapa:"atb", d:"Ampicilina-sulbactam",do:"1,5 g IV 6/6h",via:"IV",o:"Internado/sepse."},
{etapa:"escala", d:"Antitetânica",do:"dT + IGHAT conforme status",via:"IM",o:"Esquema MS."},
{etapa:"escala", d:"Vacina antirrábica",do:"PEP — esquema MS",via:"IM",o:"Sempre que indicado (animal silvestre, suspeito, ataque não provocado)."},
{etapa:"escala", d:"Imunoglobulina antirrábica humana (IGAH)",do:"20 UI/kg IM, infiltrar na ferida",via:"IM",o:"Acidentes graves + 1ª dose de vacina."},
],
alertas:[{t:"crit",x:"Raiva tem letalidade ~100%. Profilaxia pós-exposição (PEP) é a ÚNICA prevenção. Decisão pelo MS — animal silvestre = SEMPRE PEP."}],
fisio:"Flora da boca: Pasteurella (cão/gato), S. aureus, Streptococcus, anaeróbios. Trauma + corpo estranho = alto risco de infecção.",
mec:[],
diretriz:"MS — Norma Técnica Profilaxia da Raiva Humana 2022.",
calcs:[],
},

/* ============== TOX (12) ============== */

{
  id:"abstinencia", sis:"tox", grav:"alta",
  nome:"Abstinência Alcoólica",
  sin:["abstinência","delirium tremens","CIWA"],
  def:"Síndrome 6–24h após última dose de álcool em dependente: tremor, sudorese, taquicardia, ansiedade. Pode evoluir para convulsão (24–48h) e delirium tremens (48–96h).",
  exames:["Eletrólitos (K, Mg, Na, fósforo)","Função hepática","CIWA-Ar"],
  rx:[
    {etapa:"escala", d:"Diazepam",do:"5–20 mg VO/IV cada 1–2h conforme CIWA",via:"VO/IV",o:"1ª linha. Esquema flexível guiado por sintoma (CIWA ≥8)."},
    {etapa:"escala", d:"Lorazepam",do:"1–4 mg IV cada 30 min",via:"IV",o:"Hepatopata (sem metabólitos ativos)."},
    {etapa:"adj", d:"Tiamina",do:"100–300 mg IV/d × 3 dias",via:"IV",o:"Prevenir Wernicke."},
    {etapa:"adj", d:"Reposição eletrolítica",do:"K, Mg, fósforo VO/IV",via:"VO/IV",o:"Frequentemente deficitários."},
    {etapa:"escala", d:"Haloperidol",do:"2,5–5 mg IM",via:"IM",o:"Agitação refratária a BZD. Reduz limiar convulsivo — cautela."},
    {etapa:"adj", d:"Hidratação",do:"SF + glicose se necessário",via:"IV",o:"Após tiamina."},
  ],
  alertas:[
    {t:"crit",x:"DELIRIUM TREMENS (48–96h): confusão + alucinações + ↑↑adrenérgico. Mortalidade 5–15% sem tratamento. UTI + sedação agressiva."},
  ],
  fisio:"Dependência → upregulação de NMDA + downregulation de GABA. Suspensão → hiperatividade NMDA não-contrabalançada → hiperexcitabilidade neuronal → convulsão, alucinação, autonomia desregulada.",
  mec:[
    {d:"BZD",x:"Restauram tônus inibitório GABA-A → controlam todos os sintomas (tremor, ansiedade, convulsão, delirium)."},
  ],
  diretriz:"APA Substance Use Disorders; CIWA-Ar.",
  calcs:[],
},
{
  id:"alcool", sis:"tox", grav:"media",
  nome:"Intoxicação Alcoólica Aguda",
  sin:["álcool","etanol","intoxicação alcoólica","Wernicke"],
  def:"Embriaguez (etilemia variável) com risco de coma + hipoglicemia + hipotermia + aspiração.",
  exames:["HGT (excluir hipoglicemia)","Eletrólitos, função renal/hepática","Gasometria (acidose lática, KAD)","Etilemia (não rotineiro)","TC se trauma craniano"],
  rx:[
    {etapa:"adj", d:"Tiamina",do:"100 mg IV ANTES da glicose",via:"IV",o:"OBRIGATÓRIO em etilistas/desnutridos — prevenção de Wernicke."},
    {etapa:"adj", d:"Glicose 50%",do:"50 mL IV se hipoglicemia",via:"IV",o:"Após tiamina."},
    {etapa:"escala", d:"Hidratação",do:"SF 0,9% conforme déficit",via:"IV",o:"Cuidado com hiponatremia (potomania, polidipsia)."},
    {etapa:"escala", d:"Suporte",do:"Decúbito lateral + vias aéreas + monitor",via:"—",o:"Prevenção de aspiração."},
  ],
  alertas:[
    {t:"crit",x:"Wernicke-Korsakoff: tríade clássica (oftalmoplegia + ataxia + confusão). Tiamina ANTES da glicose previne. Em estabelecido: 500 mg IV 8/8h × 3 dias."},
  ],
  fisio:"Etanol potencializa GABA-A + inibe NMDA → depressão central. Metabolismo zero-order saturado (15–30 mg/dL/h).",
  mec:[
    {d:"Tiamina (vit B1)",x:"Cofator essencial para piruvato desidrogenase, α-cetoglutarato desidrogenase, transcetolase. Deficiência crônica em etilistas. Sem tiamina, infusão de glicose precipita encefalopatia de Wernicke (depleta tiamina remanescente)."},
  ],
  diretriz:"WHO; SBT.",
  calcs:[],
},
{
  id:"bzd-tox", sis:"tox", grav:"media",
  nome:"Intoxicação por Benzodiazepínicos",
  sin:["benzodiazepínico","BZD","diazepam","flumazenil"],
  def:"Sedação + ataxia + disartria + raramente depressão respiratória (exceto polimedicado/idoso/IV).",
  exames:["Clínico","Excluir coingestão (álcool, opioide, antidepressivo)"],
  rx:[
    {etapa:"escala", d:"Suporte",do:"Vias aéreas, monitor",via:"—",o:"Pilar — maioria evolui bem só com observação."},
    {etapa:"escala", d:"Flumazenil",do:"0,2 mg IV em 30s, repetir 0,2 mg cada min até 1 mg",via:"IV",o:"USO RESTRITO — risco de convulsão. CI: uso crônico de BZD, coingestão TCA, hist. de epilepsia."},
  ],
  alertas:[
    {t:"crit",x:"FLUMAZENIL pode precipitar convulsões refratárias — usar apenas em iatrogenia (sedação procedimental) ou intoxicação isolada com depressão respiratória grave."},
  ],
  fisio:"BZDs potencializam GABA-A → ↑frequência de abertura de canais Cl⁻ → hiperpolarização → sedação, ansiólise, anticonvulsivante, miorrelaxamento.",
  mec:[
    {d:"Flumazenil",x:"<strong>Antagonista competitivo do sítio benzodiazepínico</strong> no receptor GABA-A. Reverte sedação e depressão respiratória."},
  ],
  diretriz:"AACT.",
  calcs:[],
},
{
  id:"carvao", sis:"tox", grav:"baixa",
  nome:"Descontaminação Gastrointestinal",
  sin:["carvão ativado","lavagem","descontaminação"],
  def:"Procedimentos para reduzir absorção de tóxico ingerido. Carvão ativado é o mais usado.",
  exames:["Identificar tóxico, dose, tempo, via","Via aérea pérvia + consciência preservada"],
  rx:[
    {etapa:"escala", d:"Carvão ativado",do:"1 g/kg VO/SNG (adulto 50 g)",via:"VO/SNG",o:"Idealmente <1–2h da ingestão. CI: rebaixamento sem proteção de via aérea, íleo, obstrução, corrosivos."},
    {etapa:"escala", d:"Lavagem gástrica",do:"SNG calibroso + SF morno 200 mL × ciclos",via:"SNG",o:"Indicações restritas: <1h + tóxico potencialmente fatal sem antídoto."},
    {etapa:"escala", d:"Irrigação intestinal total",do:"Polietilenoglicol 1–2 L/h",via:"VO/SNG",o:"Ferro, lítio, sustained-release, packers de drogas."},
    {etapa:"escala", d:"Antídoto específico",do:"Conforme tóxico",via:"—",o:"Ver páginas específicas."},
  ],
  alertas:[
    {t:"crit",x:"CARVÃO NÃO ADSORVE: hidrocarbonetos, álcoois, metais (ferro, lítio, plumbo), corrosivos, cianeto."},
    {t:"warn",x:"Indução de vômito (xarope de ipeca) está OBSOLETA — abandonada por inutilidade e riscos."},
  ],
  fisio:"Carvão ativado tem alta superfície (1000–2000 m²/g) — adsorve a maioria dos compostos orgânicos no TGI antes da absorção sistêmica.",
  mec:[
    {d:"Carvão ativado",x:"Superfície porosa altamente adsorvente — liga toxinas no lúmen intestinal por <strong>forças de van der Waals</strong>, prevenindo absorção."},
  ],
  diretriz:"AACT/EAPCCT Position Statements.",
  calcs:[],
},
{id:"co-tox", sis:"tox", grav:"alta",
nome:"Intoxicação por Monóxido de Carbono",
sin:["CO","monóxido carbono","intoxicação CO"],
def:"Inalação de CO (incêndio, exaustão de motor, aquecedor mal ventilado, fogão a lenha) → afinidade 240× pela Hb (carboxiHb) → hipóxia tissular. Clínica varia: cefaleia, náusea, confusão, síncope, dor torácica, coma. SpO₂ NORMAL (oxímetro não diferencia HbO₂ de HbCO).",
exames:["CarboxiHb (cooximetria — específico): leve 10-20%, moderado 21-40%, grave >40%","Gaso arterial (acidose metabólica láctica)","ECG, troponina (isquemia miocárdica é comum)","Glicemia, eletrólitos","β-HCG","TC crânio se neuro alterado"],
rx:[
{etapa:"inicial", d:"Remoção da fonte + O₂ 100%",do:"Máscara não-reinalante 15 L/min",via:"—",o:"PILAR. Reduz meia-vida CO de 4-6h (ar ambiente) para ~80 min."},
{etapa:"inicial", d:"O₂ hiperbárico (OHB)",do:"2,5-3 atm × 60-90 min",via:"—",o:"INDICAÇÕES: CarboxiHb >25%, perda consciência, gravidez (mesmo CO baixa), sintomas neuro persistentes, isquemia cardíaca, idade extrema. Meia-vida cai para ~20 min."},
{etapa:"escala", d:"Suporte ABC",do:"IOT se rebaixamento; cristaloide se hipotensão",via:"—",o:"Cuidado com lesão térmica via aérea em vítima de incêndio."},
{etapa:"escala", d:"Cianeto (suspeita coingestão em incêndio)",do:"Hidroxocobalamina 5 g IV em 15 min",via:"IV",o:"Se intoxicação por CIANETO suspeita (fumaça plástico/lã/seda + acidose lática grave + carboxiHb mod-grave + ↓consc). Tiossulfato + nitrito (Cyanide Antidote Kit) alternativa."},
{etapa:"escala", d:"Aconselhamento",do:"Identificar fonte (engenheiro, equipe local) + prevenir recorrência",via:"—",o:"NÃO retornar até fonte sanada. Detector de CO."},
],
alertas:[
{t:"crit",x:"SpO₂ NORMAL com clínica suspeita NÃO EXCLUI. Pedir COOXIMETRIA (gaso com Hb total) — oxímetro de pulso é cego para HbCO."},
{t:"crit",x:"GESTANTE — feto tem afinidade Hb-CO MAIOR que mãe + eliminação mais lenta. Indicação ampla de OHB mesmo CO baixa."},
{t:"warn",x:"Síndrome neurológica tardia (3-40 dias pós): parkinsonismo, déficit cognitivo, demência. OHB pode reduzir incidência."},
{t:"info",x:"BR: câmaras hiperbáricas disponíveis em centros principais (transferir se viável)."},
],
fisio:"CO compete com O₂ pela Hb (afinidade 240×) → carboxiHb não transporta O₂. Curva de dissociação O₂-Hb desviada para esquerda → libera menos O₂ aos tecidos. Adicionalmente: CO se liga a mioglobina cardíaca + citocromo c oxidase → bloqueia respiração mitocondrial. Resultado: hipóxia tecidual + dano isquêmico (cérebro, coração).",
mec:[
{d:"O₂ 100%",x:"Lei de ação das massas — ↑PO₂ desloca CO da Hb. Hiperbárico aumenta drasticamente PO₂ dissolvido no plasma (~6 mL/dL vs 0,3) + acelera dissociação."},
{d:"Hidroxocobalamina",x:"Sequestra cianeto formando cianocobalamina (vit B12) atóxica, excretada pelo rim."},
],
diretriz:"Undersea & Hyperbaric Medical Society 2019. CDC.",
fluxo:null, calcs:[],
},
{
  id:"cocaina", sis:"tox", grav:"alta",
  nome:"Intoxicação por Cocaína",
  sin:["cocaína","crack","simpatomimético"],
  def:"Síndrome simpatomimética: HAS, taquicardia, hipertermia, midríase, agitação, dor torácica, convulsão, IAM, AVC.",
  exames:["ECG (excluir IAM)","Troponina","Eletrólitos, função renal, CK (rabdomiólise)","TC crânio se déficit/convulsão"],
  rx:[
    {etapa:"escala", d:"Benzodiazepínico (1ª linha)",do:"Diazepam 5–10 mg IV ou Midazolam 5 mg IV repetir conforme necessário",via:"IV",o:"PILAR. Controla agitação, taquicardia, HAS, convulsão, dor torácica."},
    {etapa:"escala", d:"AAS + nitratos",do:"AAS 300 mg + nitroglicerina IV/SL",via:"VO/IV/SL",o:"Se dor torácica/IAM associado."},
    {etapa:"escala", d:"Fentolamina",do:"5–10 mg IV em 5 min",via:"IV",o:"α-bloqueador para HAS refratária. Alternativa: nitroprussiato."},
    {etapa:"escala", d:"Resfriamento",do:"Compressas frias + SF gelado se T >40°C",via:"—",o:"Hipertermia ameaça à vida."},
    {etapa:"escala", d:"Hidratação",do:"SF + diurese alvo >1 mL/kg/h",via:"IV",o:"Rabdomiólise."},
  ],
  alertas:[
    {t:"crit",x:"NÃO usar β-bloqueador puro (propranolol, metoprolol) — vasoconstrição α não-oposta → HAS PARADOXAL e ↑mortalidade. Se imprescindível, usar labetalol (α+β)."},
  ],
  fisio:"Cocaína inibe recaptação de noradrenalina, dopamina e serotonina nas sinapses → excesso de catecolaminas → estimulação adrenérgica generalizada (α e β). Também bloqueia canais de Na⁺ voltagem-dependentes → efeito tipo classe I (pró-arrítmico, ↓contratilidade em altas doses).",
  mec:[
    {d:"Diazepam",x:"Agonista GABA-A — modula via dopaminérgica + simpática centralmente. \"Anti-cocaína\" indireto."},
  ],
  diretriz:"AHA Cardiovascular Complications of Cocaine Use (McCord J et al., Circulation 2008).",
  calcs:[],
},
{id:"litio-tox", sis:"tox", grav:"alta",
nome:"Intoxicação por Lítio",
sin:["lítio","intoxicação lítio","Li"],
def:"Toxicidade aguda (suicídio): sintomas GI predominam inicialmente. Crônica (paciente em uso terapêutico que descompensa por desidratação, IRA, AINE, IECA, tiazídico): mais grave, predominam neurológicos. Nível tóxico >1,5 mEq/L (terapêutico 0,6-1,2).",
exames:["Nível sérico Li (séries — pico tardio em LP)","Função renal (Cr, ureia)","Eletrólitos (Na frequentemente alterado — diabetes insípido nefrogênico)","Cálcio, magnésio, fósforo","TSH (toxicidade tireoidiana crônica)","ECG (alargamento QT, alterações ST inespecíficas)","Gaso, glicemia","β-HCG"],
rx:[
{etapa:"escala", d:"SUSPENDER lítio + drogas que retém Li",do:"AINE, IECA/BRA, tiazídico, espironolactona",via:"—",o:"PILAR. Listar todas as drogas."},
{etapa:"escala", d:"Hidratação SF 0,9%",do:"200-250 mL/h até diurese adequada",via:"IV",o:"Restaurar volemia + diurese. NÃO usar diurético salina forçada."},
{etapa:"escala", d:"Carvão ativado — NÃO eficaz",do:"—",via:"—",o:"Lítio não adsorve em carvão. Útil só para coingestão."},
{etapa:"escala", d:"Lavagem gástrica precoce",do:"<1h ingestão maciça, via aérea protegida",via:"—",o:"Considerar em maciça aguda."},
{etapa:"escala", d:"HEMODIÁLISE",do:"4-6h",via:"—",o:"PILAR em casos graves. INDICAÇÕES: Li >4 mEq/L; >2,5 com sintomas neuro/cardiacos/renais; IR; sintomas que não melhoram. Pode rebote — repetir."},
{etapa:"escala", d:"Manejo arritmia",do:"Conforme tipo",via:"—",o:"Lítio pode causar disfunção sinusal, BAV, QT longo, taquicardia ventricular."},
{etapa:"escala", d:"BZD se convulsão",do:"Diazepam 5-10 mg IV",via:"IV",o:"Status epilepticus pode ocorrer."},
],
alertas:[
{t:"crit",x:"Intoxicação CRÔNICA é mais grave que aguda no mesmo nível — distribuição tecidual completa. Paciente em uso terapêutico com desidratação/IRA pode ter sintomas graves com Li só levemente acima."},
{t:"crit",x:"Sintomas NEURO: tremor → confusão → mioclonias → convulsão → coma. Sequelas neuro permanentes possíveis em casos graves (SILENT — Syndrome of Irreversible Lithium-Effectuated Neurotoxicity)."},
{t:"warn",x:"Diabetes insípido NEFROGÊNICO induzido por Li — polidipsia, poliúria, hiperNa em uso crônico. Pode persistir após suspensão."},
],
fisio:"Lítio é cátion monovalente, similar ao Na. Excreção QUASE EXCLUSIVAMENTE renal — depende da filtração + 80% reabsorção túbulo proximal (como Na). Desidratação/sódio baixo → ↑reabsorção compensatória de Na + Li → níveis ↑. AINE, IECA, tiazídico fazem o mesmo. Mecanismo tóxico: depleção mioinositol cerebral, alteração 2º mensageiros, inibição GSK-3β (também base terapêutica em transtorno bipolar).",
mec:[
{d:"Hemodiálise",x:"Lítio é íon pequeno (massa 7), não-ligado a proteínas, baixo volume de distribuição. IDEAL para diálise — clearance dialisador >>renal. Rebote por redistribuição é regra; repetir."},
],
diretriz:"EXTRIP Workgroup 2015 — Decisões de extração por diálise.",
fluxo:null, calcs:[],
},
{
  id:"opioide", sis:"tox", grav:"alta",
  nome:"Intoxicação por Opioides",
  sin:["opioide","heroína","fentanil","morfina","naloxona"],
  def:"Tríade: miose puntiforme + depressão respiratória + alteração de consciência. Risco de parada respiratória.",
  exames:["Glicemia, eletrólitos","Gasometria","ECG (QT longo em metadona)"],
  rx:[
    {etapa:"adj", d:"Naloxona",do:"0,04–0,4 mg IV/IM/IN titulada",via:"IV/IM/IN",o:"Dose mínima eficaz — preservar analgesia, evitar abstinência. Repetir 2–3 min se necessário."},
    {etapa:"escala", d:"Naloxona BIC",do:"2/3 da dose efetiva/h",via:"IV",o:"Opioides de longa duração (metadona, opioides extended-release)."},
    {etapa:"escala", d:"Ventilação com BVM",do:"Ambu + máscara",via:"—",o:"Suporte respiratório enquanto naloxona age."},
    {etapa:"escala", d:"IOT se refratário ou aspiração",do:"—",via:"—",o:"Sem resposta a naloxona, vômito, aspiração."},
  ],
  alertas:[
    {t:"warn",x:"Naloxona tem T½ curta (30–60 min) — opioides de longa duração podem ressedar; observar 6–12h e considerar BIC."},
    {t:"info",x:"Abstinência aguda em uso crônico: agitação, midríase, sudorese — desconfortável mas não fatal."},
  ],
  fisio:"Opioides ativam receptores μ no SNC e medula → depressão do centro respiratório bulbar (↓resposta a hipercapnia) + sedação + analgesia + miose.",
  mec:[
    {d:"Naloxona",x:"<strong>Antagonista competitivo do receptor μ</strong> (também κ, δ) — reverte rapidamente os efeitos opioides."},
  ],
  diretriz:"WHO; CDC.",
  calcs:[],
},
{
  id:"organofosforado", sis:"tox", grav:"alta",
  nome:"Intoxicação por Organofosforado",
  sin:["organofosforado","carbamato","chumbinho","Aldicarb"],
  def:"Inibição da acetilcolinesterase → ↑↑ACh → síndrome muscarínica (SLUDGE) + nicotínica + SNC. Causa frequente: \"chumbinho\" (aldicarb).",
  exames:["Clínico","Atividade da colinesterase plasmática e eritrocitária (se disponível)","ECG (bradicardia, QT longo)","Gasometria, eletrólitos","Glicemia"],
  rx:[
    {etapa:"escala", d:"Descontaminação dérmica",do:"Remover roupas + lavar pele/couro cabeludo com água + sabão",via:"—",o:"EPI para equipe. Cuidado com contaminação secundária."},
    {etapa:"escala", d:"Carvão ativado",do:"1 g/kg VO/SNG",via:"VO/SNG",o:"<1h da ingestão + via aérea protegida."},
    {etapa:"escala", d:"Atropina",do:"2–5 mg IV (criança 0,05 mg/kg). DOBRAR cada 3–5 min até atropinização",via:"IV",o:"ALVOS DE ATROPINIZAÇÃO: pele/mucosas secas, FC>80, broncorreia ausente, midríase. Doses cumulativas podem ser >100 mg."},
    {etapa:"escala", d:"Manutenção atropina",do:"BIC 10–20% da dose de atropinização/h",via:"IV",o:"Por horas/dias. Desmame lento."},
    {etapa:"escala", d:"Pralidoxima (2-PAM)",do:"30 mg/kg IV em 30 min + 8 mg/kg/h BIC",via:"IV",o:"SEMPRE APÓS atropinização. Eficaz nas primeiras 24–48h (antes do \"aging\")."},
    {etapa:"escala", d:"Diazepam",do:"5–10 mg IV PRN",via:"IV",o:"Convulsões + reduz mortalidade (efeito neuroprotetor)."},
    {etapa:"escala", d:"Suporte ventilatório",do:"IOT precoce",via:"—",o:"Insuficiência respiratória é principal causa de morte."},
  ],
  alertas:[
    {t:"crit",x:"NÃO usar succinilcolina na IOT (também metabolizada por colinesterase — paralisia prolongada). Usar rocurônio."},
  ],
  fisio:"Organofosforado liga-se irreversivelmente à <strong>acetilcolinesterase</strong> (após \"aging\" — fosforilação estável) → acúmulo de ACh em receptores muscarínicos (M, SLUDGE: salivação, lacrimejamento, urinação, diarreia, GI, êmese, miose) e nicotínicos (N, fraqueza, fasciculação, paralisia respiratória) e SNC (convulsão, coma).",
  mec:[
    {d:"Atropina",x:"<strong>Antagonista muscarínico</strong> competitivo — bloqueia efeitos M de ACh excessiva (mas NÃO efeitos nicotínicos)."},
    {d:"Pralidoxima",x:"<strong>Reativa a acetilcolinesterase</strong> ao remover o grupo fosforil do sítio ativo — antes do \"aging\" (24–48h)."},
  ],
  diretriz:"Diretrizes Brasileiras para Tratamento das Intoxicações por Agrotóxicos, CONITEC/MS 2018.",
  calcs:[],
},
{
  id:"paracetamol", sis:"tox", grav:"alta",
  nome:"Intoxicação por Paracetamol",
  sin:["paracetamol","acetaminofeno","NAC"],
  def:"Ingestão >150 mg/kg ou >7,5 g em adulto. Toxicidade hepática (CYP2E1 → NAPQI). Pode ser silencioso nas primeiras 24h.",
  exames:["Nível sérico de paracetamol 4–24h pós-ingestão (Rumack-Matthew)","Função hepática (AST/ALT, INR, BT, glicose, NH3)","Função renal","Gasometria, lactato","Tempo de ingestão (CRÍTICO)"],
  rx:[
    {etapa:"escala", d:"N-acetilcisteína (NAC) IV",do:"150 mg/kg em 200 mL SG5% em 1h + 50 mg/kg em 4h + 100 mg/kg em 16h",via:"IV",o:"PROTOCOLO 21h. Eficácia máxima <8h da ingestão."},
    {etapa:"escala", d:"NAC VO",do:"140 mg/kg + 70 mg/kg 4/4h × 17 doses",via:"VO",o:"Alternativa se IV indisponível. Mais difícil tolerância (vômitos)."},
    {etapa:"escala", d:"Carvão ativado",do:"1 g/kg VO/SNG",via:"VO/SNG",o:"<1–2h da ingestão E sem rebaixamento."},
    {etapa:"escala", d:"Indicação de NAC",do:"Acima da linha de tratamento no nomograma Rumack-Matthew (150 mcg/mL às 4h) OU ingestão desconhecida com AST elevado",via:"—",o:"Se nível indisponível e ingestão >150 mg/kg: tratar empiricamente."},
  ],
  alertas:[
    {t:"crit",x:"Hepatite fulminante (King's College Criteria): pH <7,3 OU (INR >6,5 + Cr >3,4 + encefalopatia III/IV). Transplante hepático URGENTE."},
  ],
  fisio:"Doses terapêuticas: 90% metabolizado em conjugados não tóxicos (glicuronil/sulfato). 5% via CYP2E1 gera <strong>NAPQI (N-acetil-p-benzoquinona imina)</strong>, neutralizado pela glutationa. Em sobredose: vias de conjugação saturam → mais NAPQI → glutationa hepática depleta → NAPQI livre causa necrose centrolobular hepática.",
  mec:[
    {d:"N-acetilcisteína (NAC)",x:"<strong>Precursor de glutationa</strong> + conjuga NAPQI diretamente + propriedades antioxidantes. Reduz hepatotoxicidade em >95% se iniciada em <8h."},
  ],
  diretriz:"AASLD; UpToDate; Bateman DN (Lancet 2014).",
  calcs:[],
},
{id:"salicilato", sis:"tox", grav:"alta",
nome:"Intoxicação por Salicilato (AAS)",
sin:["salicilato","AAS","aspirina","intoxicação aspirina"],
def:"Sobredose aguda ou crônica de salicilatos (AAS, óleo de Wintergreen, AINE). Clássico: alcalose RESPIRATÓRIA (centro respiratório estimulado) + acidose METABÓLICA (ânion gap) + alterações mentais + zumbido + hipertermia.",
exames:["Nível sérico salicilato (séries 2/2h até pico/queda)","Gaso arterial (típica alcalose mista + acidose metabólica AG)","Glicemia capilar (hipo OU hiper)","Eletrólitos, função renal, hepática","Hemograma, coag","ECG (raro alterações)","Lactato"],
rx:[
{etapa:"escala", d:"Carvão ativado",do:"1 g/kg VO/SNG; doses repetidas 0,5 g/kg 4/4h em ingestão maciça",via:"VO/SNG",o:"INDICADO até várias horas — salicilatos formam bezoar. Via aérea protegida."},
{etapa:"escala", d:"Reidratação",do:"SG/SF + glicose (HipoG cerebral mesmo com BG normal)",via:"IV",o:"Repor déficit. Salicilato causa diurese osmótica."},
{etapa:"escala", d:"Bicarbonato (Alcalinização urinária)",do:"150 mEq em 1L SG 5% IV em 2h, ajustar manter pH urinário 7,5-8,0",via:"IV",o:"PILAR. ↑Excreção urinária 10-20×. K alvo >4 (hipoK impede alcalinização)."},
{etapa:"escala", d:"Reposição de K",do:"KCl 40 mEq por L SG infundido",via:"IV",o:"Salicilato + alcalinização causam HIPOCALEMIA. Sem K, alcalinização falha."},
{etapa:"escala", d:"Hemodiálise",do:"Indicação",via:"—",o:"INDICAÇÕES: nível >100 mg/dL agudo OU >60 mg/dL crônico; SNC alterado, IR, IC, edema pulmonar, acidose refratária. Indicar PRECOCEMENTE."},
{etapa:"escala", d:"IOT — CUIDADO",do:"Manter hiperventilação após IOT",via:"—",o:"Hiperventilação compensa acidose. Se IOT com VM 'normal' → acidose piora drasticamente → óbito rápido. ALERTAR equipe."},
],
alertas:[
{t:"crit",x:"IOT pode MATAR rápido se ventilação 'normal' for instituída. MANTER hiperventilação espontânea sempre que possível. Se IOT necessária: FR alta + Vt amplo."},
{t:"crit",x:"INTOXICAÇÃO CRÔNICA é mais grave que aguda no mesmo nível sérico. Idoso confuso + acidose AG + alcalose resp em uso de AAS regular → suspeitar."},
{t:"warn",x:"Wintergreen (metilsalicilato): 1 mL = ~1g de aspirina. Ingestão pediátrica de pequenas quantidades pode ser letal."},
],
fisio:"AAS é hidrolisado a salicilato (ácido fraco, pKa 3,0). Mecanismos tóxicos: (1) desacopla fosforilação oxidativa → hipertermia + acidose lática; (2) estimula centro respiratório → alcalose respiratória; (3) inibe ciclo de Krebs + síntese ácidos graxos → cetoacidose. Salicilato atravessa BHE em pH baixo — daí piora rápida em acidose. Edema pulmonar não-cardiogênico + cerebral em casos graves.",
mec:[
{d:"Bicarbonato",x:"Alcaliniza urina → ↑fração ionizada de salicilato no túbulo → menos reabsorção. Aumenta clearance dramaticamente. NB: alcalinização sistêmica também impede salicilato de entrar no SNC."},
],
diretriz:"AACT/EAPCCT Position Paper on Salicylate Poisoning 2015.",
fluxo:null, calcs:[],
},
{id:"tca-tox", sis:"tox", grav:"alta",
nome:"Intoxicação por Antidepressivo Tricíclico",
sin:["TCA","amitriptilina","nortriptilina","intoxicação ATC"],
def:"Sobredose de TCA (amitriptilina, nortriptilina, imipramina, clomipramina) — anticolinérgico + cardiotóxico (Na⁺ canal) + neurotóxico. Tríade: alteração mental + cardiotoxicidade (QRS largo) + anticolinérgico. Pode evoluir rápido em horas.",
exames:["ECG IMEDIATO + monitorização contínua","Gaso arterial (acidose piora cardiotoxicidade)","Nível sérico de TCA (não amplamente disponível BR)","Eletrólitos, glicemia","Função renal, hepática","Nível paracetamol, salicilato (coingestão)"],
rx:[
{etapa:"escala", d:"Bicarbonato de Sódio",do:"1-2 mEq/kg IV bolus + BIC mantendo pH 7,50-7,55",via:"IV",o:"PILAR. INDICAÇÕES: QRS >100 ms, hipotensão, arritmia ventricular. ALCALOSE desloca TCA do Na⁺ canal."},
{etapa:"escala", d:"Carvão ativado",do:"1 g/kg VO/SNG",via:"VO/SNG",o:"<1-2h ingestão E via aérea protegida. NÃO em rebaixamento sem IOT (broncoaspiração)."},
{etapa:"escala", d:"Hidratação",do:"SF 0,9% 20 mL/kg em bolus se hipoTA",via:"IV",o:"Cuidado em IC."},
{etapa:"escala", d:"Noradrenalina",do:"0,05-2 mcg/kg/min BIC",via:"IV",o:"Hipotensão refratária a volume e bicarbonato. EVITAR dopamina (esgotamento por bloqueio de recaptação)."},
{etapa:"escala", d:"Lidocaína (classe IB)",do:"1-1,5 mg/kg IV",via:"IV",o:"Arritmia ventricular refratária ao bicarbonato. ÚNICO antiarrítmico aceito. EVITAR IA, IC, III (prolongam QT)."},
{etapa:"escala", d:"BZD",do:"Diazepam 5-10 mg IV se convulsão",via:"IV",o:"Convulsão é comum (delirium tremens-like)."},
{etapa:"escala", d:"Sulfato de Mg",do:"2 g IV em 5 min",via:"IV",o:"Torsades."},
{etapa:"escala", d:"IOT",do:"Sequência rápida",via:"—",o:"Glasgow ≤8 ou convulsão refratária. Hiperventilar levemente após (pH alvo 7,50)."},
],
alertas:[
{t:"crit",x:"QRS >100 ms = preditor de convulsão; >160 ms = arritmia ventricular. BICARBONATO IMEDIATO."},
{t:"crit",x:"Flumazenil NUNCA — pode precipitar convulsão em coingestão BZD."},
{t:"crit",x:"Fisostigmina (anticolinesterásico) NUNCA em TCA — bradiarritmia fatal descrita."},
{t:"warn",x:"R-wave em aVR >3 mm + S em I/aVL = sinais de toxicidade (Liebelt). Onda R aVR >3 mm = preditor arritmia."},
],
fisio:"TCAs bloqueiam: (1) recaptação noradrenalina/serotonina (efeito terapêutico); (2) receptores muscarínicos (anticolinérgico: midríase, taquicardia, retenção urinária, hipertermia, delirium); (3) α1-adrenérgicos (hipotensão ortostática); (4) Na⁺ canais cardíacos (QRS largo, arritmia ventricular — efeito 'tipo IA quinidina'); (5) GABA-A (limiar convulsivo ↓). Acidose AUMENTA fração não-ionizada do TCA → mais ligação a Na⁺ canal → cardiotoxicidade.",
mec:[
{d:"Bicarbonato",x:"Alcaliniza plasma → desloca TCA do Na⁺ canal por gradiente de prótons + Na⁺ extra compete pelo sítio. Resultado: QRS estreita, hipotensão melhora."},
],
diretriz:"AACT/EAPCCT 2007 Position Paper. Liebelt EL, Toxicol Rev 2005;24:243.",
fluxo:null, calcs:[],
},
);
