/* ===========================================================
   VOVÔMINIC EMERGÊNCIA — pat/trauma.js
   9 patologias
   Sistemas: trauma
   =========================================================== */

PATOLOGIAS.push(

/* ============== TRAUMA (9) ============== */

{id:"abcde-trauma-estendido", contexto:["pa"], nome:"ABCDE estendido / secundário — FGHI", sis:"trauma", grav:"alta",
cid:"T07", ciap:"A82",
sin:["ABCDE estendido","ABCDE secundário","FGHI","Avaliação secundária","Trauma secundário","FAST"],
def:"Após ABCDE PRIMÁRIO estabilizado, segue-se AVALIAÇÃO SECUNDÁRIA — exame da cabeça aos pés + investigação SAMPLE + extensões: F (FAST/Foley/Family), G (Glicemia/Gases/Geografia), H (História/Hipotermia/Helicóptero), I (Inventário/Investigação/Imagens). Permite identificar lesões NÃO ameaçadoras de vida imediatas mas relevantes para desfecho.",
quadro:["Paciente politraumatizado APÓS ABCDE primário estabilizado","Continua a avaliação secundária + investigação complementar","⚠ Avaliação secundária só DEPOIS de garantir que ameaças à vida foram tratadas"],
diag:["História + exame da cabeça aos pés + exames complementares","Reavaliar ABCDE a qualquer mudança"],
exames:["Imagens: RX tórax + pelve + cervical (trauma board), FAST, TC crânio/face/tórax/abdome/pelve conforme indicação","Laboratório: hemograma, eletrólitos, função renal/hepática, troponina, lipase, β-hCG, álcool/tóxicos","ECG","Gasometria + lactato (reavaliação)"],
rx:[
{etapa:"inicial", d:"⚠ ABCDE PRIMÁRIO ESTABILIZADO — só agora secundário"},
{etapa:"inicial", d:"⚠ HISTÓRICO — REGRA NEMÔNICA SAMPLE"},
{etapa:"inicial", d:"S — Sinais/sintomas (do trauma)"},
{etapa:"inicial", d:"A — Alergias"},
{etapa:"inicial", d:"M — Medicações em uso (especial: anticoagulantes, antiagregantes)"},
{etapa:"inicial", d:"P — Patologias prévias / cirurgias / Pulmão (DPOC, asma)"},
{etapa:"inicial", d:"L — Last meal (última refeição — para anestesia)"},
{etapa:"inicial", d:"E — Eventos do trauma (cinemática, mecanismo)"},
{etapa:"escala", d:"⚠ F — FAST / Foley / Family / Fractures"},
{etapa:"escala", d:"⚠ FAST (Focused Assessment with Sonography for Trauma):"},
{etapa:"escala", d:"USG abdominal point-of-care — 4 janelas: peri-hepática (Morrison), perisesplênica, pélvica (Douglas), pericárdica"},
{etapa:"escala", d:"FLUIDO LIVRE em qualquer janela = positivo → sugere hemoperitônio / hemopericárdio"},
{etapa:"escala", d:"E-FAST (extended) inclui janelas pleural para pneumotórax"},
{etapa:"escala", d:"Não exclui lesão (sensibilidade ~75%), mas alta especificidade — guia decisão cirúrgica em paciente instável"},
{etapa:"escala", d:"⚠ FOLEY (sonda vesical):"},
{etapa:"escala", d:"Para monitor débito urinário (alvo: 0,5-1 mL/kg/h adulto)"},
{etapa:"escala", d:"⚠ CONTRAINDICAÇÃO ABSOLUTA — suspeita LESÃO URETRAL: sangue no meato, hematoma perineal/escrotal, próstata flutuante ao toque retal, fratura pélvica complexa"},
{etapa:"escala", d:"Em contraindicação: uretrocistografia retrógrada primeiro OU cistostomia suprapúbica"},
{etapa:"escala", d:"⚠ FAMILY (família):"},
{etapa:"escala", d:"Avisar familiares — apoio + obter histórico"},
{etapa:"escala", d:"Decisões compartilhadas (DNAR, doação)"},
{etapa:"escala", d:"⚠ FRATURES (fraturas):"},
{etapa:"escala", d:"Inspeção sistemática — todos os 4 membros + cintura escapular + cintura pélvica"},
{etapa:"escala", d:"⚠ FRATURA PÉLVICA: lesão major — sangramento profuso, alta mortalidade. Pelvic binder + fluido + sangue + transferir centro trauma"},
{etapa:"escala", d:"⚠ FÊMUR: deformidade + dor + perda de 1-1,5 L de sangue. Talas de tração de fêmur"},
{etapa:"adj", d:"⚠ G — GLICEMIA / GASES / GEOGRAFIA"},
{etapa:"adj", d:"⚠ GLICEMIA CAPILAR — todo paciente inconsciente. Hipoglicemia mimetiza/agrava TCE"},
{etapa:"adj", d:"⚠ GASOMETRIA ARTERIAL + lactato:"},
{etapa:"adj", d:"pH, pCO₂, pO₂, HCO₃, BE, lactato, eletrólitos"},
{etapa:"adj", d:"LACTATO ≥2 mmol/L = hipoperfusão. Clarear em 24h reduz mortalidade"},
{etapa:"adj", d:"ACIDOSE METABÓLICA + lactato alto = sinais de hipoperfusão oculta — choque criptococcoso"},
{etapa:"adj", d:"⚠ GEOGRAFIA (mecanismo geográfico):"},
{etapa:"adj", d:"Onde foi o trauma? Acidente rural sem testemunha → demora no socorro → lesões + grave"},
{etapa:"adj", d:"Centro urbano? Especialização disponível?"},
{etapa:"adj", d:"Transferência para centro de trauma se: politrauma, TCE moderado-grave, fratura múltipla, queimadura extensa"},
{etapa:"adj", d:"⚠ H — HISTÓRIA / HIPOTERMIA / HELICÓPTERO"},
{etapa:"adj", d:"⚠ HISTÓRIA DETALHADA — reescuta com paciente consciente ou família"},
{etapa:"adj", d:"Cinemática completa: velocidade, projetil, posição, lugar do veículo, uso de cinto/capacete, ejeção"},
{etapa:"adj", d:"⚠ HIPOTERMIA — MEDIR temperatura central"},
{etapa:"adj", d:"<36°C = hipotermia clinicamente relevante"},
{etapa:"adj", d:"<35°C = hipotermia importante — coagulopatia, arritmia, mortalidade"},
{etapa:"adj", d:"AQUECIMENTO ATIVO: cobertor térmico, fluidos aquecidos (38°C), lavagem cavidades em casos extremos"},
{etapa:"adj", d:"⚠ HELICÓPTERO / TRANSFERÊNCIA:"},
{etapa:"adj", d:"Critérios para acionar SAMU / aeromédico"},
{etapa:"adj", d:"Comunicação SBAR com equipe receptora"},
{etapa:"adj", d:"⚠ I — INVENTÁRIO / INVESTIGAÇÃO / IMAGENS"},
{etapa:"adj", d:"⚠ INVENTÁRIO — exame da CABEÇA aos PÉS:"},
{etapa:"adj", d:"CABEÇA: hematomas, ferimentos, palpar crânio (afundamento), pupila, otorragia, hemorragia retroauricular (Battle), hemorragia periorbitária (olho de guaxinim)"},
{etapa:"adj", d:"FACE: deformidade, instabilidade middle face, oclusão dentária, mobilidade nasal"},
{etapa:"adj", d:"PESCOÇO: enfisema subcutâneo, distensão jugular, desvio traqueal, dor cervical, ferida penetrante"},
{etapa:"adj", d:"TÓRAX: já avaliado em B — reavaliar"},
{etapa:"adj", d:"ABDOME: distensão, dor, defesa, sinais peritoneais, ferida penetrante"},
{etapa:"adj", d:"PELVE: dor à compressão (NÃO 'balançar pelve' rotineiramente — pode aumentar sangramento), instabilidade"},
{etapa:"adj", d:"PERÍNEO: sangue meato, hematoma escrotal/labial, sangramento retal"},
{etapa:"adj", d:"4 MEMBROS: pulsos distais, deformidade, fratura aberta, neurovascular distal"},
{etapa:"adj", d:"⚠ TOQUE RETAL: tônus esfincteriano, próstata, sangue, fragmento ósseo (fratura pélvica)"},
{etapa:"adj", d:"⚠ LOG-ROLL: avaliar coluna toracolombar, dorso completo"},
{etapa:"adj", d:"⚠ INVESTIGAÇÃO:"},
{etapa:"adj", d:"3 RX clássicos do trauma: TÓRAX (frontal), PELVE, CERVICAL (lateral)"},
{etapa:"adj", d:"FAST repetido se piora hemodinâmica"},
{etapa:"adj", d:"TC TÓRAX/ABDOME/PELVE com contraste — paciente estável com cinemática maior"},
{etapa:"adj", d:"TC CRÂNIO se TCE moderado-grave, anticoagulado, GCS <14"},
{etapa:"adj", d:"⚠ IMAGENS — INDICAÇÕES:"},
{etapa:"adj", d:"TC: paciente estável + cinemática significativa"},
{etapa:"adj", d:"FAST/RX: paciente instável + decisão emergencial"},
{etapa:"adj", d:"Angiografia/TC angio: suspeita lesão vascular"},
{etapa:"alta", d:"⚠ APÓS SECUNDÁRIO: decisão de transferência, internação, cirurgia"},
{etapa:"alta", d:"REAVALIAR ABCDE — qualquer mudança no quadro = repetir"},
{etapa:"alta", d:"DOCUMENTAR achados, hipóteses, conduta"},
{etapa:"alta", d:"⚠ PROFILAXIA: antitetânica, antibiótico (em ferida contaminada/aberta), trombose (heparina baixa dose após controle hemorragia)"},
],
alertas:[
{nivel:"crit", txt:"⚠ AVALIAÇÃO SECUNDÁRIA é DEPOIS de estabilização ABCDE primário. NÃO pular A-E para investigar lesões 'interessantes' se ainda há ameaça à vida."},
{nivel:"crit", txt:"⚠ FRATURA PÉLVICA + hipotensão = mortalidade alta. Pelvic binder PRECOCE + hemoterapia + transferir centro trauma. Sangramento retroperitoneal pode ser oculto."},
{nivel:"crit", txt:"⚠ FOLEY contraindicada em suspeita de lesão uretral (sangue meato, hematoma perineal, próstata flutuante, fratura pélvica complexa). Uretrocistografia primeiro OU cistostomia suprapúbica."},
{nivel:"warn", txt:"⚠ FAST não exclui lesão (sens ~75%). Útil em INSTÁVEL para decisão cirúrgica imediata. Em paciente estável: TC com contraste é mais sensível."},
{nivel:"warn", txt:"NÃO 'BALANÇAR PELVE' rotineiramente — pode deslocar coágulos e aumentar sangramento. Apenas compressão suave."},
{nivel:"warn", txt:"⚠ LOG-ROLL: avaliar coluna + dorso. Preservar cervical. Examinador líder coordena."},
{nivel:"warn", txt:"⚠ ANTICOAGULAÇÃO + TCE = TC crânio mesmo com GCS 15. Reverter anticoagulação se hemorragia (vit K, complexo protrombínico, idarucizumabe para dabigatrana)."},
{nivel:"info", txt:"REGRA SAMPLE = Sintomas, Alergias, Medicações, Patologias, Last meal, Eventos. Padrão de história em trauma."},
{nivel:"info", txt:"3 RX CLÁSSICOS: tórax, pelve, cervical lateral. Em centro com TC disponível: maioria substituída por TC."},
],
fluxo:null, diretriz:"ATLS 10ª ed. PHTLS. SBAIT. EAST guidelines."
},
{id:"abcde-trauma-primario", contexto:["pa"], nome:"ABCDE primário do trauma — avaliação inicial ATLS", sis:"trauma", grav:"alta",
cid:"T07", ciap:"A82",
sin:["ABCDE","ATLS","Trauma primário","Avaliação primária","Trauma grave"],
def:"AVALIAÇÃO PRIMÁRIA do paciente traumatizado segue sequência ABCDE — identificar e tratar ameaças à vida na MESMA ORDEM SEMPRE: A) via aérea com controle cervical, B) respiração, C) circulação com controle de hemorragia, D) déficit neurológico, E) exposição e prevenção de hipotermia. Cada etapa tem intervenções específicas. Reavaliar continuamente.",
quadro:["Paciente vítima de TRAUMA — politrauma, acidente, queda, ferimento por arma","Cinemática importante: velocidade, projetil, queda de altura, atropelamento, ejeção","Primeira abordagem em qualquer cenário — pré-hospitalar ou intra-hospitalar","⚠ PREMISSA: cervical é sempre PROTEGIDA até excluir lesão"],
diag:["Avaliação SISTEMÁTICA por A→B→C→D→E","NÃO PULAR etapa por aparente urgência de outra"],
exames:["Em paralelo após estabilização: acessos venosos, sangue para tipagem, gasometria, lactato, troponina (se TCE) ","Imagens conforme indicação: FAST, RX tórax/pelve, TC"],
rx:[
{etapa:"inicial", d:"⚠ SEGURANÇA DA CENA + EPI + Equipe de trauma alertada"},
{etapa:"escala", d:"⚠ A — AIRWAY com CONTROLE CERVICAL"},
{etapa:"escala", d:"PERGUNTAR ao paciente — se RESPONDE COERENTEMENTE: VA pérvia (momentaneamente)"},
{etapa:"escala", d:"AVALIAR: estridor, gargarejo, rouquidão, taquipneia, agitação, cianose"},
{etapa:"escala", d:"⚠ MANTER ALINHAMENTO CERVICAL durante toda a abordagem"},
{etapa:"escala", d:"Imobilização cervical com COLAR + BLOCOS LATERAIS + FIXAÇÃO À MACA"},
{etapa:"escala", d:"⚠ MANOBRAS imediatas se necessário:"},
{etapa:"escala", d:"Elevação do queixo (chin-lift)"},
{etapa:"escala", d:"Tração da mandíbula (jaw-thrust) — preferida em trauma cervical"},
{etapa:"escala", d:"Aspiração de secreções/vômito/sangue"},
{etapa:"escala", d:"Remoção de corpo estranho visível"},
{etapa:"escala", d:"⚠ DISPOSITIVOS:"},
{etapa:"escala", d:"Cânula orofaríngea (Guedel) em inconsciente sem reflexo"},
{etapa:"escala", d:"Cânula nasofaríngea em consciente"},
{etapa:"escala", d:"⚠ VIA AÉREA DEFINITIVA — INDICAÇÕES (intubação):"},
{etapa:"escala", d:"Apneia, GCS ≤8, obstrução não corrigida, queimadura facial/aérea, lesão cervical com edema, choque grave"},
{etapa:"escala", d:"Sequência rápida com etomidato/cetamina + succinilcolina/rocurônio"},
{etapa:"escala", d:"⚠ CRICOTIREOIDOSTOMIA — em via aérea impossível (cant intubate, can't ventilate)"},
{etapa:"escala", d:"⚠ B — BREATHING (respiração e ventilação)"},
{etapa:"escala", d:"INSPEÇÃO: simetria, retrações, ferimentos, deformidade, pulso paradoxal, distensão jugular"},
{etapa:"escala", d:"PALPAÇÃO: enfisema subcutâneo, dor, instabilidade torácica (tórax instável)"},
{etapa:"escala", d:"PERCUSSÃO: timpânico (pneumotórax), maciço (hemotórax)"},
{etapa:"escala", d:"AUSCULTA: assimetria, abolimento (pneumotórax/hemotórax)"},
{etapa:"escala", d:"⚠ AMEAÇAS À VIDA — IDENTIFICAR E TRATAR IMEDIATAMENTE:"},
{etapa:"escala", d:"PNEUMOTÓRAX HIPERTENSIVO: hipotensão + distensão jugular + assimetria + timpanismo + desvio traqueal → TORACOCENTESE DE ALÍVIO (2º EIC linha hemiclavicular OU 4-5º EIC linha axilar anterior, agulha 14G) → DRENO TORÁCICO definitivo"},
{etapa:"escala", d:"HEMOTÓRAX MACIÇO: hipotensão + colapso pulmonar + sons abolidos → DRENO TORÁCICO 28-32 Fr"},
{etapa:"escala", d:"PNEUMOTÓRAX ABERTO: ferida aspirativa → curativo de 3 PONTAS (oclusivo com 1 lado aberto = válvula) + dreno"},
{etapa:"escala", d:"TÓRAX INSTÁVEL: ≥2 fraturas em ≥2 costelas → suporte ventilatório + analgesia"},
{etapa:"escala", d:"⚠ O₂ — 10-15 L/min máscara não-reinalante em todo politrauma inicial"},
{etapa:"escala", d:"MONITOR: SatO₂, capnografia se intubado"},
{etapa:"escala", d:"⚠ C — CIRCULATION com controle de hemorragia"},
{etapa:"escala", d:"AVALIAÇÃO RÁPIDA: nível de consciência, cor da pele, pulso (presença, frequência, qualidade)"},
{etapa:"escala", d:"⚠ HEMORRAGIA EXTERNA — controle imediato:"},
{etapa:"escala", d:"COMPRESSÃO DIRETA com gaze/curativo (1ª escolha)"},
{etapa:"escala", d:"TORNIQUETE em sangramento de membro NÃO controlado por compressão (CAT, SOFTT, ou improvisado com largura adequada)"},
{etapa:"escala", d:"AGENTES HEMOSTÁTICOS (Combat Gauze, Celox) — sangramento juncional"},
{etapa:"escala", d:"⚠ HEMORRAGIA INTERNA — fontes:"},
{etapa:"escala", d:"TÓRAX (hemotórax — RX), ABDOME (FAST), PELVE (RX pelve, ATB band), FÊMUR (deformidade)"},
{etapa:"escala", d:"⚠ ACESSOS VENOSOS — 2 acessos calibrosos (16-18G) em veias periféricas grandes"},
{etapa:"escala", d:"INTRAÓSSEO se falha (tibial proximal, umeral) — 60 segundos"},
{etapa:"escala", d:"⚠ COLETAR SANGUE: tipagem + cruzamento, hemograma, gasometria, lactato, β-hCG, coagulograma"},
{etapa:"escala", d:"⚠ REPOSIÇÃO VOLÊMICA"},
{etapa:"escala", d:"CRISTALOIDE: RINGER LACTATO 1000 mL infusão rápida (limite 2 L em trauma; volumes maiores aumentam mortalidade — hipotensão permissiva)"},
{etapa:"escala", d:"⚠ HEMOTERAPIA precoce: PRBC 1:1:1 (hemácias:plasma:plaquetas) em hemorragia maciça"},
{etapa:"escala", d:"ÁCIDO TRANEXÂMICO 1 g IV em <3h pós-trauma + 1 g em 8h (CRASH-2 trial) — reduz mortalidade em hemorragia"},
{etapa:"escala", d:"⚠ HIPOTENSÃO PERMISSIVA: PA sistólica alvo 80-90 mmHg até controle do sangramento (em trauma penetrante; ajustar em TCE para PAS ≥110)"},
{etapa:"escala", d:"⚠ D — DISABILITY (déficit neurológico)"},
{etapa:"escala", d:"GLASGOW: ocular (1-4) + verbal (1-5) + motor (1-6) = 3-15"},
{etapa:"escala", d:"PUPILAS: tamanho, simetria, fotorreatividade (anisocoria = hipertensão intracraniana / herniação)"},
{etapa:"escala", d:"FUNÇÃO MOTORA: movimento dos 4 membros, força, sensibilidade"},
{etapa:"escala", d:"⚠ AVALIAR sinais de HERNIAÇÃO: anisocoria, postura de descerebração/decorticação, Cushing (HAS + bradicardia + alteração respiratória)"},
{etapa:"escala", d:"GLICEMIA CAPILAR (excluir hipoglicemia)"},
{etapa:"escala", d:"⚠ AINDA em D: avaliar consciência, ABLA (alcohol, drogas, alergias)"},
{etapa:"escala", d:"GCS ≤8: via aérea definitiva indicada"},
{etapa:"escala", d:"GCS 9-12: TC crânio precoce, monitor"},
{etapa:"escala", d:"⚠ E — EXPOSITION e prevenção de HIPOTERMIA"},
{etapa:"escala", d:"DESPIR completamente — cortar roupas se necessário"},
{etapa:"escala", d:"INSPECIONAR todos os segmentos (frente + costas — log-roll preservando cervical)"},
{etapa:"escala", d:"⚠ LOG-ROLL: avaliar coluna toracolombar, dorso, períneo, sangramento retal/vaginal"},
{etapa:"escala", d:"PROCURAR ferimentos ocultos: axila, virilha, períneo, região sacral, lombar"},
{etapa:"escala", d:"⚠ HIPOTERMIA — paciente politraumatizado SE RESFRIA RÁPIDO"},
{etapa:"escala", d:"Cobertor TÉRMICO / aquecimento ativo (Bair Hugger se disponível)"},
{etapa:"escala", d:"Sala AQUECIDA (>24°C)"},
{etapa:"escala", d:"FLUIDOS AQUECIDOS (especialmente em hemoterapia)"},
{etapa:"escala", d:"⚠ TRÍADE LETAL DO TRAUMA: hipotermia + acidose + coagulopatia — prevenir!"},
{etapa:"adj", d:"⚠ REAVALIAR ABCDE continuamente — paciente trauma é DINÂMICO"},
{etapa:"adj", d:"Após estabilização inicial: transferir para AVALIAÇÃO SECUNDÁRIA (ABCDE estendido)"},
{etapa:"alta", d:"⚠ DIRECIONAR para centro de TRAUMA conforme cinemática + gravidade"},
{etapa:"alta", d:"COMUNICAR equipe receptora (SBAR)"},
{etapa:"alta", d:"DOCUMENTAR achados, intervenções, horários"},
],
alertas:[
{nivel:"crit", txt:"⚠ AMEAÇAS À VIDA EM B (Breathing): pneumotórax hipertensivo, hemotórax maciço, pneumotórax aberto, tórax instável. Identificar + tratar IMEDIATAMENTE antes de prosseguir para C."},
{nivel:"crit", txt:"⚠ TRÍADE LETAL DO TRAUMA: hipotermia + acidose + coagulopatia. Prevenir = aquecimento agressivo + hemoterapia balanceada + ácido tranexâmico precoce."},
{nivel:"crit", txt:"⚠ HIPOTENSÃO PERMISSIVA em trauma penetrante (PAS 80-90) — volume excessivo de cristaloide DESLOCA coágulos formados + dilui fatores → AUMENTA mortalidade. Em TCE: PAS ≥110."},
{nivel:"crit", txt:"⚠ ÁCIDO TRANEXÂMICO 1g IV em <3h + 1g em 8h em hemorragia traumática reduz mortalidade (CRASH-2). Disponível, barato, subutilizado."},
{nivel:"warn", txt:"⚠ NÃO PULAR ETAPA — ABCDE é sequencial. Resolver A antes de avaliar B, etc. Mas reavaliar continuamente."},
{nivel:"warn", txt:"⚠ CONTROLE CERVICAL desde o primeiro contato — colar + blocos + maca rígida. Liberar somente após exclusão clínica/radiológica de lesão."},
{nivel:"info", txt:"DEFINITIVA DA VIA AÉREA: GCS ≤8, apneia, obstrução refratária, queimadura aérea, lesão cervical com edema, choque grave."},
{nivel:"info", txt:"REPOSIÇÃO BALANCEADA (1:1:1 hemácias:plasma:plaquetas) > cristaloide isolado em hemorragia maciça."},
],
fluxo:null, diretriz:"ATLS 10ª ed. PHTLS. SBAIT. AHA."
},
{id:"fratura-quadril", contexto:["pa"], sis:"trauma", grav:"media",
nome:"Fratura de Quadril em Idoso",
sin:["fratura quadril","fratura colo femoral","fratura transtrocantérica"],
def:"Fratura proximal de fêmur (colo, transtrocantérica, subtrocantérica) — clássica do idoso após queda da própria altura. Sinal: rotação externa + encurtamento + dor + incapacidade carga. Mortalidade 30% em 1 ano se não operado precocemente.",
exames:["RX bacia AP + lateral quadril","TC se RX inconclusivo (mais 5% RX-negativas)","Hemograma, função renal","ECG + RX tórax (pré-op)","Avaliação anestésica","Ecocardiograma se cardiopata"],
rx:[
{etapa:"escala", d:"Cirurgia em <48h",do:"Hemiartroplastia (colo desviada idoso), DHS/parafuso (intertroc), HD (jovem)",via:"Cirúrgico",o:"PILAR. Cada dia de atraso = ↑mortalidade. Múltiplas diretrizes apoiam <48h."},
{etapa:"adj", d:"Profilaxia TVP",do:"Enoxaparina 40 mg SC/d ou HBPM ajustada",via:"SC",o:"INICIAR pré-op (suspender 12h antes) e manter 4-6 semanas pós-op."},
{etapa:"adj", d:"Analgesia",do:"Bloqueio do fáscia ilíaca (3-Em-1) + paracetamol 1g 6/6h + dipirona",via:"IV/regional",o:"EVITAR opioides em idoso — delirium. Bloqueio regional 1ª linha — Cochrane recomendação forte."},
{etapa:"escala", d:"Reposição volêmica",do:"Cristaloide cauteloso",via:"IV",o:"Idoso descompensa fácil. Avaliar volemia clinicamente."},
{etapa:"escala", d:"Otimização cardíaca",do:"Manter β-bloqueador se uso, controlar PA, corrigir anemia (Hb >8)",via:"—",o:"Cirurgia geralmente cardio-tolerada — não atrasar para 'investigação' desnecessária."},
{etapa:"adj", d:"Profilaxia delirium",do:"Hidratação adequada + reorientação + dispositivos auditivos/visuais + evitar BZD/anti-H1",via:"—",o:"Delirium pós-op em até 50% idosos. Haloperidol 0,25-0,5 mg em crise."},
],
alertas:[
{t:"crit",x:"FRATURA + HIPOTENSÃO em idoso = considerar sangramento (trans/subtrocantérica pode perder 1-2 L). Reservar hemocomponentes."},
{t:"warn",x:"FRATURA SEM TRAUMA significativo = fratura patológica (metástase óssea, mieloma, osteoporose grave) — investigar."},
{t:"info",x:"Avaliação de osteoporose pós-fratura: investigação completa + bifosfonatos/denosumabe. ↓50% nova fratura em 3 anos."},
],
fisio:"Osteoporose senil + queda da própria altura. Colo femoral: fratura pode comprometer vascularização (artéria circunflexa femoral medial) → necrose avascular se desviada (Garden III-IV) → indicação de prótese ao invés de osteossíntese. Transtrocantérica: bem vascularizada, osteossíntese (DHS/PFN). Repouso prolongado → TEP, pneumonia, úlcera de pressão, sarcopenia, dependência permanente.",
mec:[],
diretriz:"AAOS 2021 Hip Fractures in Elderly. NICE NG124. Diretrizes SBOT.",
fluxo:null,
calcs:[],
},
{id:"golpe-calor", contexto:["pa"], sis:"trauma", grav:"alta",
nome:"Golpe de Calor / Hipertermia",
sin:["golpe de calor","insolação","heat stroke","exaustão por calor"],
def:"Hipertermia >40°C + disfunção do SNC (confusão, convulsão, coma) por falha da termorregulação. Clássico (idoso, onda de calor) ou de esforço (atleta, militar). Diferente de exaustão por calor (T <40, sem disfunção SNC).",
exames:["T central (retal/esofágico — fundamental)","Gaso, lactato, eletrólitos, glicemia","CPK, função renal (rabdomiólise)","Função hepática (lesão térmica)","Coag (CIVD)","ECG","β-HCG"],
rx:[
{etapa:"escala", d:"RESFRIAMENTO IMEDIATO",do:"Imersão em água gelada (atleta) OU spray + ventilador + gelo em axilas/inguinais/pescoço/poplítea",via:"—",o:"PILAR. CADA MINUTO conta. Meta: T <38,5°C em ≤30 min."},
{etapa:"escala", d:"Hidratação cautelosa",do:"SF 0,9% guiado por SSVV (não bolus maciço)",via:"IV",o:"Hipovolemia frequente mas não dominante. Cuidado em idoso cardiopata."},
{etapa:"adj", d:"BZD",do:"Diazepam 5-10 mg IV",via:"IV",o:"Calafrios + agitação (não usar antitérmico — ineficaz, hepatotóxico em paracetamol)."},
{etapa:"adj", d:"NÃO usar antitérmicos",do:"Paracetamol/AINE",via:"—",o:"FALÊNCIA hipotalâmica — não responde. Risco hepato/nefrotoxicidade. Resfriar fisicamente."},
{etapa:"escala", d:"Tratar complicações",do:"Rabdomiólise, IRA, CIVD, arritmia",via:"—",o:"Suporte. UTI."},
{etapa:"escala", d:"Dantrolene",do:"NÃO eficaz",via:"—",o:"Útil em hipertermia MALIGNA anestésica, não em golpe de calor."},
],
alertas:[
{t:"crit",x:"Termômetro RETAL/ESOFÁGICO — boca/axilar subestimam. Sem T central, não há diagnóstico."},
{t:"crit",x:"HEAT STROKE clássico em idoso: mortalidade 10-60% conforme tempo até resfriamento. Onda de calor + paciente isolado em ambiente quente."},
{t:"warn",x:"Drogas: anticolinérgicos, antipsicóticos, simpaticomiméticos (cocaína, anfetamina), diuréticos, álcool — TODOS aumentam risco."},
],
fisio:"Falha de dissipação de calor (radiação, condução, evaporação) supera produção endógena. Hipertermia >40-41°C causa desnaturação proteica + apoptose celular + permeabilidade intestinal (endotoxemia) → resposta inflamatória sistêmica + coagulopatia + falência multissistêmica. Diferente de febre (mediado por citocinas, set point hipotalâmico ajustado — resfriamento físico é ineficaz porque corpo resiste).",
mec:[],
diretriz:"American College of Sports Medicine 2007. Bouchama A, NEJM 2002;346:1978.",
fluxo:null, calcs:[],
},
{id:"hipotermia", contexto:["pa"], sis:"trauma", grav:"alta",
nome:"Hipotermia",
sin:["hipotermia","frio","T<35"],
def:"Temperatura central <35°C. Leve 32-35: tremor + taquicardia + taquipneia. Moderada 28-32: ↓ tremor + arritmias + ↓consciência. Grave <28: ausência de tremor + bradicardia + apneia + risco FV.",
exames:["Termômetro esofágico/retal/vesical (boca subestima)","ECG (J wave/Osborn em hipotermia <30°C)","Gaso arterial (sem correção de temperatura)","HMG, eletrólitos","Função renal, glicemia, alcoolemia, paracetamol","TC crânio se trauma","Coag (coagulopatia por hipotermia)"],
rx:[
{etapa:"escala", d:"Reaquecimento PASSIVO",do:"Cobertores, ambiente aquecido",via:"—",o:"LEVE (32-35°C). Tremor preservado = sucesso esperado."},
{etapa:"escala", d:"Reaquecimento ATIVO externo",do:"Mantas térmicas, lâmpadas, banho morno",via:"—",o:"Moderada 28-32°C. ATENÇÃO: 'core temperature afterdrop' — sangue periférico frio retorna."},
{etapa:"escala", d:"Reaquecimento ATIVO interno",do:"Cristaloide aquecido a 40°C; O₂ aquecido; lavagem pleural/peritoneal/vesical a 40-45°C",via:"IV/lavado",o:"Grave <28°C. Aquecer 1-2°C/h."},
{etapa:"escala", d:"ECMO/Bypass CP",do:"Reaquecimento extracorpóreo",via:"—",o:"Hipotermia grave instável, PCR. 5-10°C/h. ELEVADA sobrevida em afogamento gelado."},
{etapa:"escala", d:"ACLS modificado",do:"Não declarar morte até T >32-35°C ('No one is dead until warm and dead')",via:"—",o:"RCP/desfibrilação podem ser ineficazes <30°C. Persistir."},
],
alertas:[
{t:"crit",x:"'NO ONE IS DEAD UNTIL WARM AND DEAD'. RCP prolongado em hipotermia → sobrevida descrita após >2h de PCR + reaquecimento ECMO."},
{t:"crit",x:"MANIPULAÇÃO MÍNIMA em hipotermia grave — pode precipitar FV. Posicionar IV, gentilmente."},
{t:"warn",x:"Causas/co-fatores: etilismo, idoso, hipotireoidismo, sepse, drogas (BZD, neurolépticos, opioide), TCE, hipoglicemia."},
],
fisio:"Termorregulação central (hipotálamo) falha → vasoconstrição + tremor inicial → conforme T cai, função celular se reduz progressivamente. Sistema cardiovascular: bradicardia, hipotensão, arritmias (FA → FV <28°C). SNC: ↓consc → coma <30°C. Respiratório: ↓FR → apneia. Renal: 'cold diuresis' (paradoxal). Coagulação: enzimática (inibida pelo frio) — coagulopatia mesmo sem CIVD.",
mec:[],
diretriz:"AHA ACLS 2020 — Hypothermia. Wilderness Medical Society 2019.",
fluxo:null, calcs:[],
},
{id:"queimaduras", contexto:["pa"], sis:"trauma", grav:"alta",
nome:"Queimaduras",
sin:["queimaduras","queimadura","grande queimado"],
def:"Lesão térmica/química/elétrica/radioativa. Profundidade: 1º grau (epiderme — hiperemia); 2º superficial (papilas — bolhas, dor); 2º profundo (reticular — bolhas, hipoestesia); 3º (subcutâneo, branca/preta, indolor); 4º (músculo/osso). SCT pela regra dos 9 ou Lund-Browder.",
exames:["SCQ (% superfície corporal queimada) — regra dos 9","Gaso arterial + lactato + carboxiHb (incêndio)","HMG, eletrólitos, função renal, hepática","Cinacídio se incêndio (cianeto)","CPK (rabdomiólise se elétrica/extensa)","ECG (elétrica)","RX tórax (lesão inalatória), broncoscopia se suspeita"],
rx:[
{etapa:"inicial", d:"PARAR PROCESSO — irrigação + remoção roupas",do:"Água corrente 15-20 min. NÃO gelo",via:"—",o:"Reduz progressão. Roupas aderidas: NÃO arrancar. Joias/anéis: remover (edema)."},
{etapa:"inicial", d:"ABCDE — Via aérea PRECOCE",do:"IOT se sinais de lesão inalatória",via:"—",o:"Edema progressivo em 24-48h → IOT enquanto fácil. Sinais: queimadura facial, vibrissa singed, escarro carbonáceo, rouquidão, estridor."},
{etapa:"inicial", d:"O₂ 100% se incêndio (CO)",do:"Máscara não-reinalante",via:"—",o:"Reduz meia-vida CO de 4h para 1h. SpO₂ pode mostrar falsamente normal — pedir carboxiHb."},
{etapa:"inicial", d:"2 acessos calibrosos",do:"Idealmente em pele íntegra; se impossível, mesmo em queimada",via:"—",o:"Calibrosos (14-16G). Acesso central se SCQ extensa + vasopressor."},
{etapa:"inicial", d:"Calcular SCQ — Regra dos 9",do:"% superfície corporal queimada (excluir 1º grau)",via:"—",o:"Wallace adulto: cabeça 9, MS 9 cada, tronco ant 18, tronco post 18, MI 18 cada, períneo 1. Palma do paciente = 1%. Em criança: cabeça 18%."},
{etapa:"escala", d:"① REPOSIÇÃO VOLÊMICA — Fórmula PARKLAND",do:"Ringer Lactato 4 mL × kg × %SCQ em 24h (50% nas 1ªs 8h)",via:"IV",o:"INICIAR da HORA DA QUEIMADURA, não da admissão. RL preferido (evita acidose hipercloremica do SF). Ajustar conforme diurese."},
{etapa:"escala", d:"② Titular pela DIURESE",do:"Adulto 0,5-1 mL/kg/h, ped 1-1,5, elétrica 1-2",via:"—",o:"DIURESE é a melhor medida de adequação. NÃO usar PAM como única meta (pode normalizar com volume excessivo)."},
{etapa:"escala", d:"③ ESCAROTOMIA (queimadura circular)",do:"Indicação: tórax circular (restritiva) ou extremidade (sd compartimental)",via:"Cirúrgico",o:"24-48h após queimadura. Antes que evolua para sd compartimental. Sinais: ↑pressão compartimental, pulsos diminuídos, palidez, parestesia."},
{etapa:"escala", d:"④ Cirurgia precoce (2º profundo, 3º)",do:"Excisão tangencial + enxerto em 5-7 dias",via:"Cirúrgico",o:"Reduz hipermetabolismo, infecção, dor. Centro de queimados."},
{etapa:"atb", d:"ATB profilático sistêmico — NÃO indicado",do:"Apenas se infecção estabelecida + cultura",via:"—",o:"Profilaxia sistêmica AUMENTA resistência. Cobertura empírica em sepse: cobrir Pseudomonas + S. aureus + ESBL."},
{etapa:"adj", d:"Antissepsia tópica — Sulfadiazina prata 1%",do:"Aplicar sobre queimadura + gaze",via:"Tópico",o:"Trocar 24/24h. CI: alergia sulfa, gestante, RN. Alternativa: hidrogel ou hidrofibra."},
{etapa:"adj", d:"ANALGESIA — Morfina IV titulada",do:"0,1 mg/kg IV cada 5-15 min até alívio",via:"IV",o:"Doses generosas. PCA quando possível. NÃO subdosar. Cetamina sub-anestésica útil em curativos."},
{etapa:"adj", d:"VACINA antitetânica",do:"dT ± IGHAT conforme esquema",via:"IM",o:"Sempre questionar esquema. Atualizar se >5 anos (queimadura sujidade). IGHAT 250 UI IM se não-vacinado."},
{etapa:"adj", d:"INTOXICAÇÃO — Hidroxocobalamina (cianeto)",do:"5 g IV em 15 min",via:"IV",o:"Incêndio em ambiente fechado + acidose lática + alteração consciência sem CO suficiente. Disponível em poucos centros."},
{etapa:"adj", d:"Profilaxia úlcera + TEV",do:"IBP + Enoxaparina 40 mg SC/d",via:"IV/SC",o:"Grande queimado: alto risco úlcera de Curling + TEV. Iniciar quando hemorragia controlada."},
{etapa:"alta", d:"CRITÉRIOS DE TRANSFERÊNCIA — ABA",do:"Centro de queimados",via:"—",o:">10% SCQ 2º grau, >5% 3º, face/mãos/pés/períneo/articulações, elétrica/química, inalatória, comorbidades, pediátrico, idoso. CROSS-SP: solicitar vaga."},
{etapa:"alta", d:"Reabilitação precoce",do:"Fisio + nutrição + saúde mental",via:"—",o:"Iniciada na fase aguda. Cicatriz hipertrófica/queloide: pressoterapia, silicone."},
],
alertas:[
{t:"crit",x:"VIA AÉREA — Se evidência inalatória, IOT EM PRECOCE em hospital com recursos. Edema rapidamente progressivo torna IOT mais difícil/impossível."},
{t:"crit",x:"INTOXICAÇÃO CO + CIANETO em incêndio fechado. Suspeitar se acidose lática + ↓consc + carboxiHb >25%. Hidroxocobalamina 5g IV."},
{t:"crit",x:"QUEIMADURA ELÉTRICA: SCQ visível subestima dano profundo. Avaliar rabdomiólise (CPK, urina escura), arritmias (ECG), sd compartimental, lesões internas."},
{t:"warn",x:"NÃO usar gelo. NÃO romper bolhas pequenas. NÃO subdosar analgesia."},
],
fisio:"Lesão tecidual direta + resposta inflamatória sistêmica. >20% SCQ: extravasamento capilar generalizado → choque distributivo + hipovolemia maciça. Hipermetabolismo persistente por meses. Imunossupressão. Catabolismo. Infecção é causa #1 de morte após primeira semana. Lesão inalatória (até 30% mortalidade) por calor (via aérea superior) + toxinas (via aérea inferior) + CO/cianeto sistêmico.",
mec:[
{d:"Ringer Lactato",x:"Cristaloide balanceado — semelhança fisiológica ao plasma. Lactato metabolizado a bicarbonato compensa acidose."},
{d:"Sulfadiazina de Prata",x:"Antiseptico tópico — sulfa + Ag⁺ ativo contra Gram+, Gram-, fungos. Penetração superficial."},
],
diretriz:"American Burn Association (ABA) 2018 Guidelines. ATLS 10ª ed. SBQ — Sociedade Brasileira de Queimaduras.",
fluxo:null, calcs:[],
imgs:[
{src:"https://upload.wikimedia.org/wikipedia/commons/c/ca/Wallace_rule_of_nines.png",
alt:"Regra dos 9 de Wallace — distribuição de superfície corporal",
caption:"Regra dos 9 (Wallace) — cabeça 9%, cada MS 9%, tronco anterior 18%, tronco posterior 18%, cada MI 18%, períneo 1%. Em criança: cabeça 18%, cada MI 13,5%.",
source:"Wikimedia Commons"},
],
},
{id:"tce", contexto:["pa"], sis:"trauma", grav:"alta",
nome:"Trauma Cranioencefálico (TCE)",
sin:["TCE","trauma craniano","Glasgow"],
def:"Lesão craniana por mecanismo traumático. Classificar por Glasgow: LEVE 13-15 (75%), MODERADO 9-12 (15%), GRAVE 3-8 (10%). Outras escalas: AVPU, Marshall (TC).",
exames:["Glasgow seriado (cada 30-60 min)","TC crânio sem contraste — INDICAÇÕES: Canadian CT Head, New Orleans (HSA, fratura, sinais neuro)","Glicemia capilar","Hemograma, coagulograma","Função renal","Álcool/drogas se suspeita","RX coluna cervical OU mantida proteção cervical"],
rx:[
{etapa:"inicial", d:"ABCDE",do:"Vias aéreas (IOT se Glasgow ≤8) + cervical + ventilação SpO₂ >94% + circulação",via:"—",o:"PILAR. Hipotensão DOBRA mortalidade em TCE grave. Hipoxia idem."},
{etapa:"escala", d:"Cabeceira 30°",do:"Posição neutra",via:"—",o:"Reduz PIC. NÃO se trauma raquimedular instável."},
{etapa:"escala", d:"Manitol",do:"0,25-1 g/kg IV em 15-30 min",via:"IV",o:"Hipertensão intracraniana (HIC) com sinais clínicos (anisocoria, postura). Repetir 4-6h. Monitor osmolaridade <320."},
{etapa:"escala", d:"Salina hipertônica 3%",do:"250 mL IV em 10-15 min",via:"IV",o:"Alternativa ao manitol — preferida em hipotensão/euvolemia. Verificar Na sérico (alvo 145-155)."},
{etapa:"escala", d:"Anti-convulsivante profilático",do:"Levetiracetam 1 g IV ataque + 500 mg 12/12h × 7 dias",via:"IV",o:"TCE grave (Glasgow ≤8) ou contusão/hematoma — apenas 1ª semana (não previne crises tardias)."},
{etapa:"adj", d:"Reversão de anticoagulante",do:"PCC 25-50 UI/kg (varfarina); idarucizumab (dabigatran); andexanet (rivaroxabana/apixabana)",via:"IV",o:"TCE + anticoag = emergência. Reverter ANTES de cirurgia."},
{etapa:"escala", d:"Cirurgia",do:"Craniotomia evacuação OU craniectomia descompressiva",via:"Cirúrgico",o:"HSD/HED >10 mm ou desvio linha média >5 mm ou HIC refratária — chamar neurocirurgia."},
],
alertas:[
{t:"crit",x:"Canadian CT Head: TC se Glasgow <15 em 2h, suspeita fratura aberta/afundada, sinais base de crânio, ≥2 vômitos, idade ≥65a, queda >0,9 m / >5 degraus, amnésia retrógrada >30 min."},
{t:"crit",x:"Lúcido intervalo seguido de deterioração = HEMATOMA EXTRADURAL (artéria meníngea média) — emergência neurocirúrgica."},
{t:"warn",x:"IDOSO em uso de anticoagulante mesmo com TCE leve → TC. Risco de HSD evolutivo."},
{t:"warn",x:"Síndrome do BC (bebê chacoalhado): TCE pediátrico não acidental — investigar."},
],
fisio:"Lesão primária: imediata, mecânica — concussão, contusão, hematoma extradural (artéria meníngea média, fratura temporal), subdural (veias ponte, idoso/etilista, lesão por aceleração), lesão axonal difusa. Lesão secundária: subsequente, evitável — hipoxia, hipotensão, HIC, hipoglicemia, hipertermia, crises. <strong>Foco do manejo: prevenir lesão secundária</strong>. Manter PAM ≥80 (TCE grave alvo PIC <22, PPC 60-70).",
mec:[
{d:"Manitol",x:"Diurético osmótico — atrai água do parênquima cerebral para o intravascular → ↓edema cerebral + ↓PIC. Efeito reológico (↓viscosidade sangue, melhora perfusão)."},
{d:"Salina hipertônica",x:"Gradiente osmótico via BBB → desloca água do intersticial cerebral. Vantagem sobre manitol: também melhora volemia."},
],
diretriz:"Brain Trauma Foundation 4ª ed. 2017 (Carney N et al., Neurosurgery 2017;80:6). ATLS 10ª ed. Canadian CT Head Rule (Stiell IG et al., Lancet 2001;357:1391).",
fluxo:null,
calcs:[],
},
{id:"trauma-abd", contexto:["pa"], sis:"trauma", grav:"alta",
nome:"Trauma Abdominal",
sin:["trauma abdominal","FAST","laparotomia"],
def:"Lesão abdominal por mecanismo traumático fechado ou penetrante. Trauma fechado: acidente trânsito > queda; órgãos mais lesados: baço, fígado, rim. Penetrante: indicação cirúrgica mais liberal — qualquer FAB com peritonismo, FAF abdominal.",
exames:["FAST (Focused Assessment with Sonography for Trauma) — 4 janelas","TC abdome com contraste (estável, FAST duvidoso)","DPL (lavado peritoneal diagnóstico) — caindo em desuso","Hemograma seriado","Lactato, base excess","Tipagem + prova cruzada"],
rx:[
{etapa:"escala", d:"INSTÁVEL + FAST+",do:"LAPAROTOMIA imediata",via:"Cirúrgico",o:"Sangramento intra-abdominal — não TC. Sala de cirurgia direto."},
{etapa:"escala", d:"ESTÁVEL + Trauma fechado + FAST+",do:"TC com contraste → manejo conservador se grau baixo",via:"—",o:"Trauma esplênico/hepático grau I-III estável → conservador (sucesso 80-90%). Reavaliação frequente."},
{etapa:"escala", d:"PENETRANTE ABD ANTERIOR",do:"FAB + peritonismo → laparotomia; FAB sem peritonismo + estável → exploração local da ferida",via:"—",o:"FAF abdominal: laparotomia em 95% — pode ser exploradora se via duvidosa."},
{etapa:"escala", d:"Ressuscitação balanceada",do:"Hipotensão permissiva (PAS 80-90) até controle cirúrgico — cristaloide ≤1-2 L + transfusão 1:1:1",via:"IV",o:"NÃO super-ressuscitar pré-cirurgia (dilui coagulação, piora sangramento)."},
{etapa:"escala", d:"Ácido tranexâmico",do:"1 g IV em 10 min + 1 g em 8h",via:"IV",o:"CRASH-2: reduz mortalidade se <3h do trauma. SEMPRE em hemorragia grave."},
{etapa:"escala", d:"Embolização angiográfica",do:"—",via:"Endovascular",o:"Trauma esplênico/hepático ativo (blush no TC) em paciente estável."},
],
alertas:[
{t:"crit",x:"Cinto de segurança 'sinal' (equimose abdominal transversal) + dor abdominal = lesão intestinal/mesentério até prova contrária. TC + reavaliação seriada."},
{t:"crit",x:"GRAVIDEZ + trauma — proteger materna primeiro. β-hCG sempre. Anti-D se Rh-negativa. Imobilização lateralizada à esquerda."},
{t:"warn",x:"Trauma pancreático é silencioso — amilase/lipase normais inicialmente; TC com contraste pode subdiagnosticar. Reavaliar."},
],
fisio:"Fechado: lesão por compressão direta, desaceleração (lacerações mesentério, pedículos vasculares), aumento súbito pressão intra-abdominal (ruptura órgão oco). Penetrante: FAB lacera estruturas no trajeto; FAF tem cavitação temporária (alta energia → dano periférico ao trajeto). Hemoperitônio = clínica de choque + irritação peritoneal tardia.",
mec:[],
diretriz:"ATLS 10ª ed. EAST Guidelines. WSES Splenic Trauma 2017 (Coccolini F et al., World J Emerg Surg 2017;12:40).",
fluxo:null,
calcs:[],
},
{id:"trauma-torax", contexto:["pa"], sis:"trauma", grav:"alta",
nome:"Trauma de Tórax",
sin:["trauma torácico","pneumotórax hipertensivo","hemotórax","tórax instável","tamponamento traumático"],
def:"Lesão torácica por mecanismo traumático — fechado (acidente, queda) ou penetrante (PAF, FAB). Avaliar lesões que matam rapidamente: 5 RAPIDAMENTE FATAIS = obstrução VA, PNT hipertensivo, PNT aberto, tamponamento, hemotórax maciço, tórax instável.",
exames:["RX tórax inicial","FAST estendido (EFAST) — derrame pleural/pericárdico/PNT","TC tórax com contraste (estável)","ECG","Hemograma, gaso, lactato, tipagem","Troponina (contusão miocárdica)"],
rx:[
{etapa:"escala", d:"PNT HIPERTENSIVO",do:"Punção descompressiva IMEDIATA — 2º EIC linha hemiclavicular OU 5º EIC linha axilar média, cateter 14G longo",via:"—",o:"DIAGNÓSTICO CLÍNICO — NÃO esperar RX. Após, dreno torácico definitivo."},
{etapa:"escala", d:"PNT ABERTO",do:"Curativo de 3 pontos (válvula unidirecional)",via:"—",o:"Selar 3 lados do curativo → escape ar mas não entrada. Dreno torácico definitivo."},
{etapa:"escala", d:"HEMOTÓRAX MACIÇO",do:"Dreno torácico 32-36 Fr",via:"—",o:"Imediato >1500 mL ou >200 mL/h × 4h → TORACOTOMIA. Autotransfusão se disponível."},
{etapa:"escala", d:"TAMPONAMENTO",do:"Pericardiocentese subxifoide ECO-guiada + ressuscitação volêmica",via:"—",o:"Pode reverter choque temporariamente. Cirurgia definitiva (toracotomia)."},
{etapa:"escala", d:"TÓRAX INSTÁVEL",do:"O₂ + analgesia agressiva (bloqueio intercostal/peridural) + VNI/IOT se IRespA",via:"—",o:"Contusão pulmonar é o problema real. Hidratação cautelosa. Estabilização cirúrgica em casos selecionados."},
{etapa:"atb", d:"ATB Profilático",do:"Cefazolina 2g IV se trauma penetrante + dreno",via:"IV",o:"24-48h. Reduz empiema."},
],
alertas:[
{t:"crit",x:"FRATURA DE 1ª/2ª COSTELA = trauma grave — risco de lesão de aorta/grandes vasos. Investigar com angio-TC."},
{t:"crit",x:"TORACOTOMIA DE REANIMAÇÃO: indicada em FAB/PAF torácico com perda de sinais vitais NO PRONTO-SOCORRO (não em pré-hospitalar prolongado, não em trauma fechado com PCR)."},
{t:"warn",x:"Contusão miocárdica: traço suspeito + ECG anormal + ↑troponina. Geralmente conservador, monitorizar 24-48h."},
{t:"warn",x:"Lesão diafragmática esquerda em trauma penetrante baixo — pode passar despercebida e levar a hérnia/encarceramento tardio. Sempre investigar."},
],
fisio:"Trauma fechado mais comum (acidente trânsito 70%, queda 15%, queda objeto 5%). Penetrante: arma branca (mais baixa energia) ou arma de fogo (alta energia, cavitação). Tamponamento em trauma: hemorragia rápida em saco pericárdico → 150-200 mL é suficiente para fisiopatologia (vs ~1L em crônico). Hemotórax: cada hemitorax cabe 2-3L = choque hemorrágico classe III-IV.",
mec:[],
diretriz:"ATLS 10ª ed. (American College of Surgeons 2018). EAST Guidelines.",
fluxo:null,
calcs:[],
},
);
